### PR TITLE
[MM-28155] Add link customization e2e tests

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR will add link customization e2e tests

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-28155

### CODE REVIEW

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Reviewed the tests and they all seem to line up with corresponding TM4J tasks
- Test run green. No issues found.
LGTM!

**Comment by DHaussermann** [comment]
@saturninoabril not sure why you ween't also requested on this one. It's a bit lengthly but as far as I can tell it matches the steps. 
Let me know if you also want to approve this before merge.

For now I will set the Jira to resolved and update the status on corresponding TM4J cases.

**Comment by saturninoabril** [comment]
Thanks for checking Dylan. I think that's fine. Devs are now fully aware about the ins and outs of Cypress 💯. In case needed, other SDETs can be requested for review as well.

**Review by jfrerich — APPROVED** [review]
LGTM.  I have not one non-blocking nit.

The words `Ensure` and `Verify` are used interchangeably.  I would substitute all the `Ensure`s to `Verify`

**Comment by DHaussermann** [comment]
Hi @iomodo I was going to re-run these after your last commit but I see that only comments were updated. 

This has been through 2 reviews. This is now good to merge 👍

**Pull request merged**
