### PR TITLE
E2E/Cypress:test case fixed

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Fixed Accessibility_modals_dialogs_spec test case
#### Screenshots
image

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by furqanmlk** [comment]
e2e-test

**Review by metanerd — APPROVED** [review]
Great work, Malik! LGTM

**Review by Phrynobatrachus — APPROVED** [review]
Fixes passed in the run above and locally, LGTM. thanks!

**Pull request merged**
