### PR TITLE
[MM-29842] Migrate changeCSS() to CSS variable in utils/utils.jsx

### PR DESCRIPTION
**Pull request by 1jz**
#### Summary

Removes the call to `changeCss()` for the disabled send button mentioned in the issue below and adjusts the buttons color to `--center-channel-color` to the scss file.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16028

### CODE REVIEW

**Comment by hanzei** [comment]
Hey @1jz, thanks for opening a PR! Would you be open on signing the [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks for contributing

**Review by nevyangelova — APPROVED** [review]
LGTM! - 1 Minor conflict to resolve :)

**Comment by 1jz** [comment]
Conflict should be resolved, thank you for your patience :)

**Comment by 1jz** [comment]
I didn't pay close attention and I ended up re-introducing one of the migrated calls in the last merge, it should be removed now.

**Pull request merged**
