### PR TITLE
[MM-34575] - Fix regressions for set a header button in DM

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR fixes a regression for 'set a header' button in DM's and removes the 'important' CSS tag which creates more conflicts in our CSS.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34575

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Down with !important!

**Review by Willyfrog — APPROVED** [review]
LGTM!

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Can you please check the button on hover, it looks a bit off. 
Screen Shot 2021-04-07 at 3 11 18 PM--1682194927

**Comment by nevyangelova** [comment]
@jgilliam17 fixed

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified 'set a header' button position and hover state.

**Pull request merged**
