### PR TITLE
MM-40114 Migrate modals, headers, and onboarding to use getIsMobileView

### PR DESCRIPTION
**Pull request by hmhealey**
`getIsMobileView` is the more redux-friendly, more self-explanatory, and hopefully more performant version of `Utils.isMobile` that we're wanting to be using everywhere now. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40114

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/9507
https://github.com/mattermost/mattermost-webapp/pull/9508
https://github.com/mattermost/mattermost-webapp/pull/9510

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
LGTM you just have a minor TS error.

**Comment by hmhealey** [comment]
Oh nice, I didn't know that command had been added. I just triggered the tests myself manually 😛

**Comment by neallred** [comment]
Code looks good to me. Doing some manual testing, in daily, I can use the mobile menu to options in the RHS. In this test instance, I can open the mobile menu RHS but the options are not clickable, and clicking any of them closes the menu:

RHS in daily:

https://user-images.githubusercontent.com/13738432/146251659-36c168b6-ec2c-4e3d-9d62-9ae96920e8e5.mp4

RHS in branch:

https://user-images.githubusercontent.com/13738432/146251701-0228cd29-f883-4031-880c-0d87359490a3.mp4

**Comment by neallred** [comment]
Not sure if the command is supposed to report test run results or a link or something on github, but it posts a message in QA: Test Automation Reports in community. The run I triggered lives here: https://mattermost-cypress-report.s3.amazonaws.com/97741-395943d-onprem-ent-webapp-pr-9509-mm-ee-test:395943d/mochawesome.html

None of the failures obviously seem immediately related to these changes; though my guess is that these changes mostly impact mobile viewports, and that e2e tests mostly don't test mobile.

**Comment by saturninoabril** [comment]
(Chiming in)
> `/e2e-test`

It's in mattermod but not yet triggering the pipeline under the hood since there's still a pending PR to merge, config change and live testing. We'll announce soon once we have a working slash command here in Github.

> Not sure if the command is supposed to report test run results or a link or something on github

Once working, the slash command will have the ability to trigger the E2E pipeline but no posting of test results/link here in Github yet. Therefore, please watch out in Automation dashboard (almost real-time) or community channel (on complete) for test results. We have it in the roadmap though.

**Comment by saturninoabril** [comment]
> None of the failures obviously seem immediately related to these changes; though my guess is that these changes mostly impact mobile viewports, and that e2e tests mostly don't test mobile.

That's true. For anyone curious, you'll find related tests by searching `cy.viewport` with corresponding mobile view size in `/e2e` folder.

**Comment by hmhealey** [comment]
@neallred Playing around on the test server a bit, I think that's actually a bug caused by the onboarding screens. Once you get past those, the menu is fully clickable, at least on Firefox/Mac for me

**Comment by neallred** [comment]
Ahh, yep, seeing the same on Brave/Linux. LGTM!

**Review by neallred — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @hmhealey 
Tested, looks good to merge.
- Verified mobile view for Channel header, switching global header, More DM, Getting started, find channels and Settings/Profile.
- [E2E report](https://automation-dashboard.vercel.app/cycles/c6d6b8c9-42fe-4f0f-9187-3ae86cbdf525) does not show any PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
