### PR TITLE
MM-34977 - add the correct text to the purchase modal button when trialing

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
Add the correct text to the purchase modal button when trialing

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34977

#### Screenshots
Captura de pantalla 2021-04-17 a las 18 21 24

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Review by marianunez — APPROVED** [review]

**Review by stevemudie — COMMENTED** [review]
@pablovelezvidal I'm still seeing "Upgrade Mattermost Cloud" in the button on https://mattermost-webapp-pr-7939.test.mattermost.cloud/admin_console/billing/subscription

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal I'm still seeing "Upgrade Mattermost Cloud" in the button on https://mattermost-webapp-pr-7939.test.mattermost.cloud/admin_console/billing/subscription

yes, but I don't see that the server has enabled the free_trial option
Captura de pantalla 2021-04-20 a las 23 16 20

**Comment by marianunez** [comment]
Yes, this subscription is not created in trial mode yet, possibly because the trial changes were not in the test portal yet when the test server was created in this PR. 

Adding the tag again to recreate.

**Comment by marianunez** [comment]
> Mattermost

Test server is now updated and in trial mode. @stevemudie you can test again now

**Review by stevemudie — APPROVED** [review]
Tested and passed

Text in purchase button reads "Subscribe Now" as expected

**Pull request merged**
