### PR TITLE
[MM-37990] Update recent emojis based on default selected skin tone

### PR DESCRIPTION
**Pull request by cleferman**
#### Summary

Recent emojis now change (when applicable) based on the default selected
skin tone.

If more than one skin tone was available in the recent section, this
feature will trim all duplicates, displaying only the emoji matching
the default selected skin tone.
#### Ticket Link

Jira ticket: https://mattermost.atlassian.net/browse/MM-37990
Fixes https://github.com/mattermost/mattermost-server/issues/18847
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

|  before  |  after  |
|----|----|
| image | perf-after |

#### Release Note

```release-note
Recent emojis get updated based on default selected skin tone.
```

### CODE REVIEW

**Review by hmhealey — COMMENTED** [review]
Thanks for the PR! I definitely appreciate the performance comparison since, yeah, the emoji picker is pretty terrible at that. We're planning on taking a look at that in the next month or so since we did have it virtualized at one point, but it ended up breaking something else so we were forced to remove it.

This code looks good for the emoji picker, but I think we'll also need this same sort of logic on the recent reactions shown by the post menu.
Screen Shot 2021-11-03 at 5 09 08 PM

**Comment by Willyfrog** [comment]
> This code looks good for the emoji picker, but I think we'll also need this same sort of logic on the recent reactions shown by the post menu.

there is a separate ticket for that, but I haven't seen any activity, let us know if you want to also work on that and we can reach out to the other contributor in case he didn't start working on it.

https://github.com/mattermost/mattermost-server/issues/18603

**Review by Willyfrog — APPROVED** [review]

**Comment by Willyfrog** [comment]
Looks good, for me it is good to merge and we can do the other part in a separate PR

**Comment by cleferman** [comment]
I'll comment on that one if it's still opened after I finish the other thing I still have assigned to me. 
Cheers!

**Review by hmhealey — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @cleferman 
Tested, looks good to merge.
- Verified recently used emoji are updating with the user selected skin tone.
As noted in the previous comments one-click reactions will be addressed in a separate PR.

**Pull request merged**
