### PR TITLE
Limit reactions to 40 to sync with mattermost-mobile

### PR DESCRIPTION
**Pull request by rakhi2104**
#### Summary
- Limit the number of unique reactions on a post to be utmost 40.
- Handle both Center channel and RHS

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/14167

#### Screenshots
After changes,
- In RHS
mm-14167-2-1
- In Center Channel
mm-14167-1-1

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @rakhi2104! Can you confirm the number of reactions is capped at 40? I count 41 in your screen capture above

**Comment by rakhi2104** [comment]
Sorry, the screenshot was captured earlier. Will update soon.

**Comment by nevyangelova** [comment]
LGTM 2/5 I would add a unit test for this.

**Comment by rakhi2104** [comment]
@esethna
Regarding the "+:emoji:" shortcut,
- first we allow the user to type in his reaction
- on sumbit post, if (unique) reactions limit has exceeded, we show the user an error "Reactions limit exceed for current post" and clear out the text field.

**Comment by esethna** [comment]
@rakhi2104 that works. But can you please update the text to 

`Reaction limit exceeded for this message.`

**Comment by rakhi2104** [comment]
> @rakhi2104 that works. But can you please update the text to
> `Reaction limit exceeded for this message.`
I tried creating an alert, but it doesn't work as expected.

**Comment by jgilliam17** [comment]
Thank you @rakhi2104 
Noticed one small issue with the post menu
- `Add Reaction` menu option remains available in mobile web view, after reaching 40 emoji limit. Note: Even though it is available, it does not add another emoji over 40.
Screen Shot 2020-04-17 at 4 25 26 PM

I'm confused by this
>on sumbmit post, if (unique) reactions limit has exceeded, we show the user an error "Reactions limit exceed for current post" and clear out the text field.

I am not sure how to exceed the limit and trigger an alert to verify the wording? 
My understanding was that it would be impossible to go over added reactions as add reaction `+` and link to open emoji picker are removed when limit is reached. Any suggestion on how to do this is appreciated 🙂Thanks

**Comment by esethna** [comment]
Hey @rakhi2104, hope you're well, any questions on the above feedback?

**Comment by esethna** [comment]
Hey @rakhi2104, just checking in on this, any questions?

**Comment by rakhi2104** [comment]
Sorry for being unresponsive.
I've tried creating the error message but that didn't work as expected.

**Comment by esethna** [comment]
@rakhi2104 thanks for the update, do you need any help with this?

**Comment by esethna** [comment]
@rakhi2104 let us know if you need help with this?

**Comment by esethna** [comment]
@calebroseland can you provide some guidance to @rakhi2104 regarding how to accomplish this: https://github.com/mattermost/mattermost-webapp/pull/5222#issuecomment-606611607

cc// @jgilliam17 on how to add a reaction via the message draft area ^

**Comment by rakhi2104** [comment]
Thanks to @M-ZubairAhmed and @calebroseland for helping me resolve some roadblocks.

**Comment by esethna** [comment]
Thanks @jgilliam17 please help retest ^

**Comment by jgilliam17** [comment]
I missed being mentioned while OoO last week. Will take a look on Monday.

**Comment by jgilliam17** [comment]
Thank you @rakhi2104 
- Reaction button has been removed in mobile view when limit has been reached - looks good

- I am seeing some additional issues:
1) Reaction count failing to update when adding an existing reaction to the post using +emoji add reaction button. 
Steps: 
i. User 1 adds an "eye" emoji to the post
ii. User 2 clicks on +emoji button and adds the same "eye" emoji to the post
Observed: Emoji count updates for the first user, but not the second. See gif.

Aug-03-2020 09-03-08

2. Emoji picker appears again unexpectedly
i. User 1 adds 39 reactions to the post and opens emoji picker again 
ii. User 2 adds 40th reaction (observe the emoji picker disappears for user 1 as limit is reached)
iii. Remove 40th reaction as user 2
Observed: Emoji picker for User 1 pops up open unexpectedly as the post reaction limit drops below 40
 
RE: error "Reactions limit exceed for current post"
@calebroseland can you please help me understand this requirement  https://github.com/mattermost/mattermost-webapp/pull/5222#issuecomment-606611607
I am not clear on when and where the user is going to be presented with the error message. On the open emoji picker after another user adds 40th emoji and limit is reached? Thanks.

**Comment by calebroseland** [comment]
@jgilliam17 that is about the `+(reaction)` command:

**Comment by jgilliam17** [comment]
> @jgilliam17 that is about the `+:emoji_name:` command:

Thank you @calebroseland, this whole time I was looking elsewhere 🤦🏽‍♀️

**Comment by jgilliam17** [comment]
Tested the error message and it appears on main channel view and RHS when adding reactions using `+:emoji_name:` via message draft after limit has been exceeded 
Few UX questions: 
1. Should the error message match our existing error message color/font for visibility? See image for comparison. 
Screen Shot 2020-08-03 at 11 37 22 AM

2. When trying to add an emoji again after error is shown, error message highlight dissolves quickly. I'm 0/5 on this, I missed it once or twice - just noting here
Aug-03-2020 12-02-23

**Comment by calebroseland** [comment]
>2. Emoji picker appears again unexpectedly

UX thought: maybe we could keep the + reaction button visible, but disabled with the tooltip changed to:

'Reaction limit exceeded for this message'
Screen Shot 2020-08-03 at 12 02 54

**Comment by hanzei** [comment]
Hi @rakhi2104,

Just wanted to touch bases and ask if you have any question? I would love to get this PR over the finish line.

**Comment by rakhi2104** [comment]
I'll look into these review comments this weekend.

**Comment by jgilliam17** [comment]
Thank you @rakhi2104 
Re-tested and I am still seeing these two issue. Let me know if I need to add more information.
>1. Reaction count failing to update when adding an existing reaction to the post using +emoji add reaction button.
>2. Emoji picker appears again unexpectedly

Additionally, the `Add Reaction` option is available on post menu `...` and mobile view, despite max reaction limit being reached.
Screen Shot 2020-08-28 at 11 46 30 AM
 
Screen Shot 2020-08-28 at 11 48 07 AM

**Comment by jfrerich** [comment]
How's it going, @rakhi2104?  Do you need any further feedback or help with this PR?

**Comment by jfrerich** [comment]
@rakhi2104 Could you merge the master branch and fix the conflicting files listed at the bottom of the PR? 

@jgilliam17, Could you provide additional context or direction on how to resolve the issues that you mentioned? 

@rakhi2104, thanks for reaching out!  If you are stuck, feel free to engage any of the developers reviewing this PR.  They are excellent resources!

**Comment by jgilliam17** [comment]
Thank you @jfrerich 
@rakhi2104 
Here's some additional information 
For the first 2 issues please also see my original post [here](https://github.com/mattermost/mattermost-webapp/pull/5222#issuecomment-668039335) 
1.  Reaction count failing to update when adding an existing reaction to the post 
 - Adding a reaction by clicking on the existing emoji correctly increments for both users ( user1 that added the reaction initially and user2 that clicked on the existing reaction on the same post)
 - The increment count issue is present (e.g. for the user2 in this case) if they use any other way to increment the existing reaction: + add a reaction, emoji picker from post menu or posting `+:emoji:` in the text box, where `emoji` is an existing reaction
The count updates on refresh.
2.  Emoji picker appears again unexpectedly - 
     i. User 1 adds 39 reactions to the post and opens emoji picker again
    ii. User 2 adds 40th reaction (observe the emoji picker disappears for user 1 as limit is reached)
   iii. Remove 40th reaction as user 2 - observe the emoji picker popup for user 1
   - The solution would be to prevent the emoji picker from surfacing again, once removed 
3. Remove post menu option to "Add Reactions" after the limit is reached, in both standard and mobile web browser width. I remember seeing this fixed in mobile web view at one point, but it appears to have regressed 

Let me know if you have any questions or need additional information. Thanks! 🙂

**Comment by esethna** [comment]
@rakhi2104 how's this going?

**Comment by rakhi2104** [comment]
Hey @esethna !
Due to some office work, I'm not able to spend more time looking into this issue. Is it possible for someone to takeover from here? I'd be happy to help transfer my learning with this task.
✌🏼

**Comment by esethna** [comment]
Thanks @rakhi2104 I've reopened the ticket as up for grabs

**Comment by stylianosrigas** [comment]
Removing the cloud test server for maintenance reason. Please feel free to add it again if you need it.

**Pull request closed without merging**
