### PR TITLE
Correct inline image container button positions

### PR DESCRIPTION
**Pull request by Roy-Orbison**
#### Summary
Bug introduced in c667766d27ddd6bb6376535ee84f0d27134feb06 where image action buttons display in the vertical middle rather than the intended top right, at least on external images.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45540

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot_20221214_160758 | Screenshot_20221214_165832 |

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by Roy-Orbison** [comment]
This doesn't fix the fact that those action buttons look awful in the channel header images, and in the mention of the header change by the system, and should probably not be visible at all in those places.

**Comment by devinbinnie** [comment]
@mylonsuren This ticket was closed, not sure if there was something else that needed changing here?

**Comment by Roy-Orbison** [comment]
The normal post display looks okay to me.

I'm unsure of the best way to omit the action buttons from the places they display poorly:

|Occurrance|Example|
|---|---|
|Compose preview|Screenshot_20221215_100543|
|Header|Screenshot_20221215_100423|
|Header popover|Screenshot_20221215_100843|
|Header change mention|Screenshot_20221215_100453|

**Comment by Roy-Orbison** [comment]
@devinbinnie Yes, sorry that was a related ticket, not one specifically for this issue.

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @Roy-Orbison!

**Review by mylonsuren — APPROVED** [review]
Awesome stuff @Roy-Orbison! LGTM 🚀

**Comment by mylonsuren** [comment]
> The normal post display looks okay to me.
> 
> I'm unsure of the best way to omit the action buttons from the places they display poorly:
> 
> Occurrance	Example
> Compose preview	Screenshot_20221215_100543
> Header	Screenshot_20221215_100423
> Header popover	Screenshot_20221215_100843
> Header change mention	Screenshot_20221215_100453

Good catch in finding these @Roy-Orbison! Would you be interested in fixing these possibly? I can create an issue and assign it to you if you're up for it!

**Comment by jgilliam17** [comment]
Thanks @Roy-Orbison 
Tested, looks good to merge - pending e2s; please rebase branch with master so I can trigger the test
Verified action buttons on external images.

**Comment by jgilliam17** [comment]
@Roy-Orbison 
2 tests failed on the latest [e2e report ](https://mattermost-cypress-report.s3.amazonaws.com/277957-7b78249-onprem-ent-webapp-pr-11804-mm-ee-test:7b78249/mochawesome.html)
MM-T1447 and one test in image_attachment_spec.js

**Comment by Roy-Orbison** [comment]
The tests broke because the CSS puts margins on the wrong element. The images themselves are the expected size.

**Comment by jgilliam17** [comment]
Latest [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/279904-28dd711-onprem-ent-webapp-pr-11804-mm-ee-test:28dd711/mochawesome.html) still shows the same tests failing. Are you able to address the cypress tests failures? If you need any help with Cypress please ask in [quality-assurance channel](https://community.mattermost.com/core/channels/quality-assurance) on Community. Thanks 🙂

**Comment by Roy-Orbison** [comment]
@jgilliam17 The images have borders, but the tests are performed on the container dimensions without accounting for those borders. They seem like broken tests, to me. I can change the numbers so they pass, but that is hacky. It made sense to correct which items have margins, but it doesn't to place the border on something other than the images.

I don't get why this PR is suddenly causing failures if the tests were already expecting the dims of a child element but reading the dims of the parents. I tried on that spinwick server and, in Chromium, with the viewport set to 1300x660 like the e2e env, a 1000x40 image resizes to 948:38, which matches the test data but the container tested is 950x40.

**Comment by jgilliam17** [comment]
Thank you for checking @Roy-Orbison 
@saturninoabril Do you have a suggestion on how to address the failing tests? Thanks 🙂

**Comment by saturninoabril** [comment]
Thanks Jelena and sorry for the delay. I just got back in reviewing PRs. I'll take a look.

**Comment by saturninoabril** [comment]
@Roy-Orbison @jgilliam17 I think there's an actual bug there. You'll find it's not actually resizing when you upload [image-40x400.jpg](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/fixtures/image-40x400.jpg), [image-1600x40.jpg](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/fixtures/image-1600x40.jpg) and [image-1000x40.jpg](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/fixtures/image-1000x40.jpg). Also, image is shifting when mouse hovered.

**Comment by Roy-Orbison** [comment]
> I think there's an actual bug there.

I don't believe so. Setting Chromium to the same viewport dimensions as the test, I get this output:
viewport

Dev tools shows the image as resized but also denotes borders on the image, which account for the incorrect height:
dev tools

If they were not resized at all, I'd expect an integer height.

**Comment by saturninoabril** [comment]
Here is the bug I've seen likely introduced by this PR:
- An [image with 1600x40 dimension](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/fixtures/image-1600x40.jpg) didn't resize properly.
Screenshot 2023-01-12 at 2 40 29 PM

**Comment by saturninoabril** [comment]
- Another bug but likely not related is for [image with 40x400 dimension](https://github.com/mattermost/mattermost-webapp/blob/master/e2e/cypress/tests/fixtures/image-40x400.jpg). Rendered image is not resized. You'll notice the height is outside the post height (shaded).
Screenshot 2023-01-12 at 2 41 50 PM

**Comment by Roy-Orbison** [comment]
> You'll find it's not actually resizing per maximum allowable height or width when you upload image-40x400.jpg, image-1600x40.jpg and image-1000x40.jpg.

I was certain the 1000x40 was as I expected, so I must have incorrectly assumed the other sizes were in the same boat, sorry. Those end up wrapped in a few extra layers of markup for "small images" with a lot of overridden CSS rules. They were inheriting `max-height` and `-width` from parents that had none, hence the overflow. I've added rules that should cause the least interference if elements with the `small-image__container` appear elsewhere in the UI.

> Also, image is shifting when mouse hovered.

I don't think I ever noticed this and can't see it now. Is it still occurring for you?

**Comment by saturninoabril** [comment]
Thanks @Roy-Orbison for fixing! LGTM.

Then, please fix the related tests by adjusting some parameters:

For `tests/integration/files_and_attachments/image_link_preview_spec.js` (L169):
```diff
- thumbnailSize: {width: 40, height: 400}
+ thumbnailSize: {width: 35, height: 350},
```

For `tests/integration/messaging/image_attachment_spec.js`
(L59):
```diff
- container: {height: 45, width: 339},
+ container: {height: 45, width: 339},
```

(L80):
```diff
- container: {height: 352, width: 46},
+ container: {height: 348, width: 46},
```

**Comment by jgilliam17** [comment]
@Roy-Orbison Can you please fix failed checks? Thanks 🙂

**Comment by Roy-Orbison** [comment]
I'm not sure what went wrong but it doesn't look like the tests even ran, to me. Some kind of build failure and missing files that this patch doesn't touch at all.

**Comment by jgilliam17** [comment]
Thanks @Roy-Orbison LGTM
Latest [e2e report](https://mattermost-cypress-report.s3.amazonaws.com/291535-b9d9c85-onprem-ent-webapp-pr-11804-mm-ee-test:b9d9c85/mochawesome.html) - no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
