### PR TITLE
MM-39695 : Fix recently used emoji missing aria-label

### PR DESCRIPTION
**Pull request by jbattistispiria**
#### Summary
Fix recently used emoji missing aria-label. Screen reader was not read out recently used emoji.
I use how aria-label was added found in `emoji_picker_item.tsx`.

Updated e2e tests in `accessibility_post_spec.js`.

#### Ticket Link
Fix https://github.com/mattermost/mattermost-server/issues/19029
https://mattermost.atlassian.net/browse/MM-39695

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @jbattistispiria!

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @jbattistispiria 
Tested, looks good to merge.
- Verified screen reader is reading out recently used reactions.
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/188038-5fcb1ff-onprem-ent-webapp-pr-10220-mattermost/mm-ee-test5fcb1ff/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
