### PR TITLE
MM-18021 - Do not allow Guest invitations to teams that are managed by LDAP Group Sync

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
If team is managed by Group Sync, don't allow guest invites. Previously, it would allow the user to attempt to invite a guest but would fail a check later.

This will just not show the option to invite guests from the beginning.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18021

### CODE REVIEW

**Comment by hanzei** [comment]
@sbishel Is this ready for review?

**Comment by sbishel** [comment]
@hanzei - Yes, do I need to mark something?

**Comment by hanzei** [comment]
You don't _need_ to. People are looking for new PRs periodically and requesting reviews. But you can push the process by requesting reviews yourself. See https://developers.mattermost.com/contribute/getting-started/code-review/ for more information about the process.

**Comment by sbishel** [comment]
@srkgupta - Added unit test.
@jespino - please review unit test

**Comment by justinegeffen** [comment]
Content has been added to the documentation in this PR: https://github.com/mattermost/docs/pull/3212.

**Pull request merged**
