### PR TITLE
Add .nvmrc

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Introduce a `.nvmrc` to simplify the setup and workflow for users using the [Node Version Manager](https://github.com/nvm-sh/nvm).

#### Ticket Link
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]
Nice addition!

**Review by hmhealey — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
this is nice because i kept that file and never committed it to the repo 😛

**Comment by M-ZubairAhmed** [comment]
may be we can add in docs to just do `nvm install` and it will install correct node based on `.nvmrc` file ?

**Comment by hmhealey** [comment]
Yeah, that'd be a good idea. We already mention how they can install the correct version of Node using NVM, so it'd probably make sense to just always have people use NVM.

If you want to submit a PR to change that, the repo for https://developers.mattermost.com is https://github.com/mattermost/mattermost-developer-documentation/

**Pull request merged**
