### PR TITLE
[MM-30337] - Fix mobile menus and remove redundant styles

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR  solves styling issues on mobile menus. It removes some redundant styles for submenu icons that just caused a lot of CSS buildup and overtaking. NOTE: The dividers currently have spaces but this is fixed in the Category sorting PR https://github.com/mattermost/mattermost-webapp/pull/7068

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30337

#### Related PR's
https://github.com/mattermost/mattermost-webapp/pull/7068

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Comment by matthewbirtch** [comment]
Thanks @nevyangelova. It looks like the styling issues are largely resolved, however, as we discussed it looks like the chevron on the 'move to' menu is off-centered now

image

**Comment by nevyangelova** [comment]
@matthewbirtch fixed

**Comment by matthewbirtch** [comment]
Thanks @nevyangelova. That issue is fixed, but I just discovered a new one :(

It looks like there is a z-index issue with the category menu showing below the `+` icon for direct messages
image

**Comment by matthewbirtch** [comment]
@nevyangelova ignore the comment above....sounds like this is a known issue not related to this PR specifically.

**Review by matthewbirtch — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 
Tested, looks good to merge.
- Verified mobile view sidebar manus are correctly styled/themed.
Note: Found that some fields are still using white background color in mobile view e.g. browse channels modal and will file that separately for follow up and link the issue here.

**Pull request merged**
