### PR TITLE
[MM-37932] - Onboarding flow in center channel comes back for existing users

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR fixes a regression that was caused by this PR https://github.com/mattermost/mattermost-webapp/pull/8528

#### Ticket Link
[MM-37932](https://mattermost.atlassian.net/browse/MM-37932)

#### Release Note
```release-note
none
```

### CODE REVIEW

**Comment by AGMETEOR** [comment]
@stevemudie just a note, that for this one, I'll need to set up users that simulate to have already existed. I'll add those to the QA steps.

**Review by marianunez — APPROVED** [review]

**Review by neallred — APPROVED** [review]

**Comment by AGMETEOR** [comment]
@stevemudie here are the users

#### Existing
- username: sysadmin | password: Sys@dmin123


#### New users
- username: existing-1 | password: Sys@dmin123

**Review by stevemudie — APPROVED** [review]
Tested and passed.
- Created a new user and encountered the onboarding as expected
- Stepped through tit all and dismissed the Tips & Next Steps
- Logged out then back in and didn't see the Tips & Next Steps or any other sign of onboarding as expected

**Comment by marianunez** [comment]
@AGMETEOR Let's wait for FF to be coomplete before cherry picking this to cloud

**Pull request merged**
