### PR TITLE
WIP: [MM-34325] Migrate 'components/admin_console/permission_schemes_settings' and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by rubenmeza**
#### Summary

This code migrate 'components/admin_console/permission_schemes_settings'  components to typescript

#### Ticket Link

Github Issue: https://github.com/mattermost/mattermost-server/issues/17250
JIRA:  https://mattermost.atlassian.net/browse/MM-34325

#### Release Note

```release-note
- Refactor component to typescript, no changes in UI
```

### CODE REVIEW

**Comment by rubenmeza** [comment]
> Hi @rubenmeza, just wondering how this is coming along.

Hello @devinbinnie, sorry for having this on hold too long, a lot of things happened these past days, but I'll be tackle on this tomorrow

**Comment by rubenmeza** [comment]
Hello @devinbinnie I think I was confused with the requirement of this issue, I thought that the issue was to migrate all the components under this path `components/admin_console/permission_schemes_settings` but after my last push I noticed that there are some conflicts related to this issue https://github.com/mattermost/mattermost-server/issues/17255 so the issue I´m working on it is to migrate only this `components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx` and the tests, right?

**Comment by devinbinnie** [comment]
> Hello @devinbinnie I think I was confused with the requirement of this issue, I thought that the issue was to migrate all the components under this path `components/admin_console/permission_schemes_settings` but after my last push I noticed that there are some conflicts related to this issue [mattermost/mattermost-server#17255](https://github.com/mattermost/mattermost-server/issues/17255) so the issue I´m working on it is to migrate only this `components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx` and the tests, right?

@rubenmeza That's correct, it should just be the files directly in that directory and not the sub-directories. Sorry for the confusion!

**Comment by rubenmeza** [comment]
thank you @devinbinnie closing this PR and I´ll create a new one today

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @rubenmeza

**Pull request closed without merging**
