### PR TITLE
MM-40908 Go to threads view when switching a team if that was the last view

### PR DESCRIPTION
**Pull request by kyeongsoosoo**
#### Summary

I added a localStorage `setter/getter` to save `previousViewedType`. This type includes `channels` and `threads`.
`lastChannelPath` for `center_channel` is decided based on this type.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/19977
Jira: https://mattermost.atlassian.net/browse/MM-40908

#### Screenshots

https://user-images.githubusercontent.com/59413880/166143266-4be7018b-7ec3-4032-824d-ffb3553d07c1.mov

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
LGTM! Thanks @kyeongsoosoo!

**Review by devinbinnie — APPROVED** [review]

**Review by Willyfrog — CHANGES_REQUESTED** [review]
Cool idea, but it is only considering the last channel while on local storage, would it be possible to also take into account that it might not be last but the penultimate? if you look at our usage of global storage we hold the info for both last and second to last, the reason fro this is in case the last one is no longer accessible we try and go back another one. if that still fails, then we revert to the home page. So it would be great to also have the option of threads being the penultimate view.

Would you be able to make this changes as well?

**Comment by kyeongsoosoo** [comment]
Thanks, @Willyfrog. I didn't fully understand the role of penultimate channel. 
I added `penultimateViewedType`. This storage value is updated when `penultimateChannel` is updated.

**Comment by esethna** [comment]
@Willyfrog any feedback? 

@kyeongsoosoo I also opened this ticket today that is very related: https://mattermost.atlassian.net/browse/MM-44169

Would you be keen on adding that to this PR or taking it afterwards?

**Review by Willyfrog — APPROVED** [review]

**Comment by Willyfrog** [comment]
@koox00 heads up about this change, as it migth be useful as well for the future global drafts section.

**Comment by kyeongsoosoo** [comment]
@esethna I would like to work on that [related isssue](https://mattermost.atlassian.net/browse/MM-44169). Would it better to open a new PR?

**Comment by esethna** [comment]
@kyeongsoosoo sure, feel free to do so. I'll open a github issue and you can comment there so I can assign it to you

**Comment by esethna** [comment]
@kyeongsoosoo please comment here and I'll assign you! https://github.com/mattermost/mattermost-server/issues/20207

**Comment by hmhealey** [comment]
@esethna Don't those two tickets want the opposite thing? This one wants it so that the Threads view is treated like a channel view that's remembered when switching back to a team, and the other one wants it so that Threads is treated as a view that exists across teams.

Having both will also lead to some weird navigation situations that pull the user towards Threads view if they're switching teams. If you have two teams, you could end up in a situation like:
1. While viewing Team A, view Threads
2. Switch to Team B. You'll end up in Threads.
3. Switch to Town Square
4. Switch to Team A. You'll end up back in Threads.
5. Switch back to Team B. You'll end up in Threads again.

**Comment by esethna** [comment]
@hmhealey yes that could be a possible outcome. I don't see these tickets as conflicting by any means, especially given the way people use team switching and the threads view in real world scenarios. Given the feedback we've received I think these two tix will be beneficial to the overall UX of Threads, but if that's not the case we can always iterate. 

The ideal solution is a cross-team threads view, but we're not quite there yet.

**Review by jgilliam17 — APPROVED** [review]
Thanks @kyeongsoosoo 
Tested, looks good to merge pending few suggestions below
- Verified user is taken to threads when switching a team if that was the last view.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/200903-0c4c7f6-onprem-ent-webapp-pr-10255-mm-ee-test:0c4c7f6/mochawesome.html) looks good, no PR related failures.
- Added a follow up ticket for returning to Threads on login, if that was the last view https://mattermost.atlassian.net/browse/MM-44731

**Pull request merged**
