### PR TITLE
Migrate 'components/sidebar_right_menu' module to TypeScript

### PR DESCRIPTION
**Pull request by KevinMarioGerard**
#### Summary
Migrate 'components/sidebar_right_menu' module to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/16163

#### Related Pull Requests
Nil

#### Screenshots
Nil

### CODE REVIEW

**Review by gabrieljackson — APPROVED** [review]
LGTM

**Review by deanwhillier — APPROVED** [review]
LGTM, thanks so much @KevinMarioGerard

**Review by jgilliam17 — APPROVED** [review]
Thank you @KevinMarioGerard 
Tested, looks good to merge.
- Verified sidebar right menu - as expected.

**Pull request merged**
