### PR TITLE
[GH-15871] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 559

### PR DESCRIPTION
**Pull request by arc9693**
#### Summary
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 559

#### Ticket Link
Closes https://github.com/mattermost/mattermost-server/issues/15871

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
We already have the `.navbar-brand` rule defined in the file, it would be better if we reuse that instead of creating a duplicate `.navbar-brand` rule.

And then you can define the `.app__body` inside it like this:
```
.navbar-brand {
    .app__body & {
    }
}
```

**Comment by deanwhillier** [comment]
QA will be done for this PR in batch when the campaign branch is merged into master

**Comment by arc9693** [comment]
@asaadmahmood I have made the changes.

**Review by asaadmahmood — APPROVED** [review]

**Comment by hanzei** [comment]
Thank you for the contribution @arc9693 :+1:

**Pull request merged**
