### PR TITLE
MM-35069: Eliminate loading indicator when you delete a post from permalink view

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR fixes a bug when user clicks post's timestamp or on a permalink to post and delete the post using the dot menu, the loading screen is displayed or stuck (if the post is deleted after permalink view is gone). This happens both on channel and direct messages, so both should be tested. 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/20120
JIRA: https://mattermost.atlassian.net/browse/MM-35069 

#### Screenshots
To be added

#### Release Note
```release-note
Bug fixes when deleting highlighted message
```

### CODE REVIEW

**Comment by sinansonmez** [comment]
One thing I need to consult. If you delete the post when it is still highlighted, the page refreshes itself because of [this](https://github.com/mattermost/mattermost-webapp/blob/5487f326fc0c02aa27a000d32fa046f2e9c31f30/components/delete_post_modal/delete_post_modal.tsx#L74) Before I am changing this I wanted to discuss what kind of other side effects this change may bring

**Comment by sinansonmez** [comment]
Unrelated test is failing. Could you please try to run /update-branch

**Review by hmhealey — APPROVED** [review]
Looks good to me. There's a slight flicker of the post list when you delete the post, but I think that's fine to have since this is a rare enough case anyway

**Comment by sinansonmez** [comment]
Kindly pingin for review @koox00

**Review by koox00 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @sinansonmez 
Tested, looks good to merge
- Verified deleted post from permalink no longer shows a loading indicator.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/198995-ed235fc-onprem-ent-webapp-pr-10304-mattermost/mm-ee-tested235fc/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
