### PR TITLE
[MM-35184] Update apps install command for Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Changes per https://github.com/mattermost/mattermost-plugin-apps/pull/166

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35184

#### Related Pull Requests
- Has Apps plugin changes: https://github.com/mattermost/mattermost-plugin-apps/pull/166

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by iomodo — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Together with https://github.com/mattermost/mattermost-plugin-apps/pull/166 this change works to install an app with the app is as a positional argument.
 - No need for the `app-ID` name 
 - No impact found on market place. Was able to install from current production with these changes deployed
 
 LGTM!

**Comment by DHaussermann** [comment]
@hanzei  and @amyblais can we confirm were this was cheery picked?

@hanzei not sure this is supposed to go to May 5th.

**Comment by amyblais** [comment]
@DHaussermann It was cherry-picked to v5.35 and cloud (for May 5).

**Comment by DHaussermann** [comment]
Sorry I was under the impression this would not got until next cloud release. 
 
@catalintomai and @hanzei or possibly @mickmister Can you help with some options here?

v5.35 is not an issue but, this requires an upgraded app-plugin which we will only release next week.

Can we pull this out maybe?

**Comment by DHaussermann** [comment]
cc @amyblais ☝️

**Comment by amyblais** [comment]
I've opened a PR to revert the cloud cherry-pick: https://github.com/mattermost/mattermost-webapp/pull/8069

**Comment by hanzei** [comment]
Yes, this change should not have been to cloud. Thanks for taking care of this @amyblais :+1:

**Pull request merged**
