### PR TITLE
chore : Fixed typo in babel plugin for object, rest, spread

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary

The installed `@babel/plugin-proposal-object-rest-spread` should be added in the babel config as [correct config](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#usage), there was a small typo.

#### Ticket Link

As discussed in [Community](https://community.mattermost.com/core/pl/dj1tpwmuxpf87by67p8tawo51h)

#### Related Pull Requests

N/A

#### Screenshots

N/A

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Good catch! Strange that we haven't seen any issues come up around that though. I assume TypeScript introduces its own version of that, but we definitely use this outside of just TypeScript environments, so perhaps we don't actually need it any more.

I guess we can investigate that next time we're pruning dependencies.

**Review by lieut-data — APPROVED** [review]

**Comment by lieut-data** [comment]
@jgilliam17, is this something for which we can execute an E2E test pass to verify? Nothing else should be required.

**Comment by jgilliam17** [comment]
@lieut-data I asked Saturn to run the E2Es. I will post report links here and check results tomorrow.

**Comment by jgilliam17** [comment]
Here are the results for the [PR E2E test run](https://mm-cypress-report.s3.amazonaws.com/4044-webapp-pr-7798-mattermost-enterprise-edition:a2cd8ab/mochawesome.html) compared agains [E2E run on master](https://mm-cypress-report.s3.amazonaws.com/4044-webapp-pr-7798-mattermost-enterprise-edition:a2cd8ab/mochawesome.html)
I retested failed tests, ones that are not also failing on master, manually and seeing only 2 issues
1. Some errors on first load, does not reproduce consistently, maybe it's just my connection 
Screen Shot 2021-03-31 at 2 27 13 PM
2.  Using `/open ~channel_name` or `/join` opens/joins in a new tab

**Comment by M-ZubairAhmed** [comment]
@jgilliam17 Do you think those errors are due to this PR ?

**Comment by jgilliam17** [comment]
@M-ZubairAhmed Errors (from screenshot) no longer reproduce for me, I am not sure if they are related to the changes from this PR
2nd point  related to slash commands to **join**, **open** and also **leave** I can reproduce consistently on the test server, but not on master.

**Comment by lieut-data** [comment]
@jgilliam17, I can't reproduce the `/join` or `/open` behaviour in my local sandbox with this branch checked out (or master, as you already noted). Is there a way of determining if this is unique to the cloud test instance somehow?

**Comment by lieut-data** [comment]
Ah, I think I found it -- the cloud server is returning a `goto_location` of `http://mattermost-webapp-pr-7798.test.mattermost.cloud/pr7798/channels/snow`, but this doesn't match the SiteURL that should have a leading `https://` in front of it, causing it to open a new tab.

**Comment by lieut-data** [comment]
Yeah, I'm pretty sure this is a cloud-specific issue that I'll raise with the cloud team.

**Review by jgilliam17 — APPROVED** [review]
Thank you @M-ZubairAhmed for your contribution and also @lieut-data for sorting out he slash command issue
Tested, looks good to merge.
- Verified E2Es test results for the server - no new issues.

**Pull request merged**
