### PR TITLE
MM-47295 : Emoji e2e tests to typescript migration

### PR DESCRIPTION
**Pull request by AbhinavVihan**
#### Summary
Emoji e2e tests to typescript migration

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-server/issues/21313
JIRA: https://mattermost.atlassian.net/browse/MM-47295

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note

```release-note
Emoji e2e tests to typescript migration
```

### CODE REVIEW

**Review by furqanmlk — APPROVED** [review]
Thanks @AbhinavVihan

**Comment by AbhinavVihan** [comment]
@furqanmlk, Would you take a look please :)
Thankyou

**Comment by furqanmlk** [comment]
> @furqanmlk, Would you take a look please :) Thank you

I have already approved 👍

**Comment by AshishDhama** [comment]
@furqanmlk Do we need @saturninoabril review or we can merge this.

**Review by saturninoabril — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
