### PR TITLE
MM-19995 Fix usage of React.forwardRef for LocalizedInput

### PR DESCRIPTION
**Pull request by hmhealey**
The login screen is currently broken because `LocalizedInput` was updated to use `React.forwardRef`, but that doesn't work with string refs that are used throughout the app. This updates them all to ref objects.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19995

### CODE REVIEW

**Comment by hmhealey** [comment]
@migbot I haven't tested switching languages, but I have no reason to think it wouldn't. I'll go double check

**Comment by hmhealey** [comment]
Yeah, switching languages works fine

**Comment by mickmister** [comment]
@hmhealey I am still experiencing issues with intl. Getting this error in the js console when clicking a profile popover: `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Also getting this malformed error when running a nonexistent slash command: `Command with a trigger of {command} not found. Click here to send as a message.` Which is expected except it actually says `{command}`.

**Comment by hmhealey** [comment]
@cometkim submitted a PR to hopefully fix that first issue, but it's having some issues
https://github.com/mattermost/mattermost-webapp/pull/4185

I haven't seen the second issue before. Is there a ticket for it?

**Comment by mickmister** [comment]
> I haven't seen the second issue before. Is there a ticket for it?

Just created one https://mattermost.atlassian.net/browse/MM-20169

**Pull request merged**
