### PR TITLE
MM-27208 Add E2E test for MM-T1680

### PR DESCRIPTION
**Pull request by hmhealey**
An E2E test and some infrastructure changes for [MM-T1680](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1680). I'd provide more details on what is tested, but the test conditions are hard to state concisely.

I posted about this in the QA channel, but I've split this off into its own spec file since we're going to be adding a ton of new tests around archived channels. This'll let us run the tests in smaller batches, and it'll also stop Guillermo and I from constantly running into conflicts since we're adding tests for the same area of the codebase.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27208

### CODE REVIEW

**Comment by hmhealey** [comment]
I've added a few more checks that were part of MM-T1681 because that test is just a subset of MM-T1680

**Review by srkgupta — COMMENTED** [review]
Thanks @hmhealey. The changes LGTM and is working fine. Approving the PR.

**Review by devinbinnie — APPROVED** [review]
LGTM, you just have some snapshots to update.

**Review by jgilliam17 — APPROVED** [review]
Thank you @hmhealey 
Looks good to merge.
- Updated TM4J test case steps to match the e2e and updated test cases details and links.

**Pull request merged**
