### PR TITLE
Enable changing channel admin privs in TE

### PR DESCRIPTION
**Pull request by ThiefMaster**
#### Summary
Correctly shows the "make channel admin" option even without a license.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41239

#### Release Note

```release-note
Fixed the "Make channel admin" option not showing up without a license.
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Great catch Adrian! Thanks for the quick fix! 🚀 

Non-blocking, would you be open to cover the admin case with the option to change admin visible in the unit tests here: https://github.com/mattermost/mattermost-webapp/blob/master/components/channel_members_dropdown/channel_members_dropdown.test.jsx

**Comment by ThiefMaster** [comment]
Updated

**Review by hmhealey — APPROVED** [review]
Nice catch! Looks good

**Review by stevemudie — APPROVED** [review]
Tested and passed. The option to promote a user to channel admin is there as expected now. 

Thanks for this @ThiefMaster!

**Comment by marianunez** [comment]
@amyblais can this be cherry-picked to v6.4?

**Comment by ThiefMaster** [comment]
Any plans to also cherry-pick this into v6.3.3 since v6.3 is an ESR so anyone using Team Edition but sticking with ESR won't get the bugfix anytime soon otherwise?

**Pull request merged**
