### PR TITLE
Add artificial delay before creating a second team in team_switch_spec

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Adding a small delay before creating the second team to ensure that the user gets created first. 

#### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — DISMISSED** [review]
I think that instead of adding an arbitrary delay, it'd be better to just wait on the call to `apiLogin` before continuing since I'm pretty sure that's the root cause of the issue we're seeing. I don't know why exactly this isn't waiting for the call to `apiLogin`, but I think that's the issue.

If you move the call to `apiCreateTeam` into `cy.apiLogin().then(() => {...});`, I think that should solve the issue, but it might be easier to remove the explicit call to `apiLogin` and move `apiCreateTeam` into `cy.apiInitSetup({loginAfter: true}).then(() => {...})` instead

**Comment by nevyangelova** [comment]
oh yea adding login: true makes much more sense :D

**Comment by hmhealey** [comment]
That's expected. The problem that's happening right now is that we aren't waiting to be logged in as the new user before we create the team.

I still see that failure, so I think we'll need to move the `apiCreateTeam` in there

**Review by saturninoabril — APPROVED** [review]
Thanks Nevy, LGTM!

**Pull request merged**
