### PR TITLE
Update NOTICE.txt

### PR DESCRIPTION
**Pull request by danmaas**
**Summary**
Update NOTICE.txt with latest open-source license info

**Additional Notes**
This follows the recent NOTICE.txt update to `mattermost-server`, PR here: https://github.com/mattermost/mattermost-server/pull/9433

The only difference is that this is an NPM-based project, so the dependency manifest is created by listing the "dependencies" section of all `package.json` files.

- Add new dependencies (exif2css, prop-types, react-addons-pure-render-mixin, react-color, react-day-picker, smoothscroll-polyfill, webrtc-adapter)
- Remove no-longer-used dependencies (autolinker)
- Update homepage and project owner info for all dependencies
- Add SPDX open-source license IDs
- Alphabetize dependency list so future update diffs will be smaller

Linebreak/whitespace changes in this PR are to match the original LICENSE files supplied with each dependency. This is a one-time change that will make future automated updates smaller.

### CODE REVIEW

**Comment by jasonblais** [comment]
We can also wait until https://github.com/mattermost/mattermost-webapp/pull/1770 is merged if we want to avoid making manual changes to the output returned by your automation. I'm okay with that.

**Comment by danmaas** [comment]
I will wait for #1770 to be merged and then update this PR. Also working on making the "modified version of..." distinction from the other repo.

**Comment by danmaas** [comment]
Just rebased this on today's master. Added the "modified version of..." logic which affects only one dependency here (`marked`).

**Comment by jasonblais** [comment]
Thanks @danmaas! Will we also need to apply the "modified version of..." logic for the `mattermost-server repository, whose NOTICE.txt got merged earlier this week? 

https://github.com/mattermost/mattermost-server/pull/9433

Might be applying the new logic won't affect that repository.

**Comment by danmaas** [comment]
Regarding `mattermost-server`, I'm not sure if there is an easy way to automatically check whether a Go dependency has been modified. Maybe one of the Golang developers can chime in?

With JavaScript projects and NPM, it's straightforward to check if the dependency is being pulled directly from the upstream package registry, or a modified Mattermost-managed source. We can check this just by looking at the version string in `package.json`.

With Go, I'm not sure if there is an easy way to tell if anything is modified just by looking at the `go list` output or the `vendor/` directory, short of downloading everything from the upstream repo and doing a file-by-file comparison.

I was researching license detection codebases today, and saw one where you could check in a configuration file to tell the system things that it can't scan for automatically. This could be a way to add the "modified version of..." text manually, if it's important enough to implement this.

**Comment by jasonblais** [comment]
@cpanato Next week, can you help merge and cherry-pick to 5.4 release branch?

**Comment by jasonblais** [comment]
@danmaas Good question, I'm not actually sure. I've taken a note to follow up on it with one of the Golang developers next week.

**Comment by cpanato** [comment]
@danmaas Hello, can you please rebase? Then I can merge this PR. thanks!

**Comment by danmaas** [comment]
@cpanato I've rebased to latest `master` and re-ran the automation. Just one minor update to a homepage URL in one of the dependencies, otherwise it's the same as before.

**Comment by cpanato** [comment]
cherry-pick a0311dedf148cb116dd6c2528f507d218a2cb197 to release 5.4 done

**Comment by danmaas** [comment]
I've added Gopkg.toml parsing to the automation. Turns out it doesn't
actually change the output in the specific case of `mattermost-server`,
because it was already seeing that the source GitHub repos are forked
from somewhere else. When we see that a dependency comes from a forked
GitHub repo, that fact is already included in the NOTICE.txt output.
(the "forked" language could be tweaked to say "modified" as well,
perhaps).

Dan

**Comment by jasonblais** [comment]
Thanks @danmaas! "modified" might be nice for consistency, and also more obvious for non-technical users who aren't aware of the concept of "forking".

**Pull request merged**
