### PR TITLE
MM-42718 : Do not render ChannelHeaderMobile when not in mobile view

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Doesnt renders the mobile's channel header in non mobile mode

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42718

#### Screenshots
N/A

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
@M-ZubairAhmed Is this still an issue?
https://github.com/mattermost/mattermost-webapp/pull/9848#pullrequestreview-890044075

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed Is this still an issue? [#9848 (review)](https://github.com/mattermost/mattermost-webapp/pull/9848#pullrequestreview-890044075)

No because we dont use that onboarding screen anymore

**Review by devinbinnie — APPROVED** [review]

**Review by pvev — APPROVED** [review]
LGTM! thanks @M-ZubairAhmed

**Comment by jgilliam17** [comment]
Thanks @M-ZubairAhmed 
Tested, looks good to merge.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/220865-62e0ffc-onprem-ent-webapp-pr-10811-mattermost/mm-ee-test62e0ffc/mochawesome.html) - no PR related faiures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
