### PR TITLE
[MM-46006]: fix for unresponsive RHS and LHS in mobile view

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
fixes unresponsive RHS and LHS making the app in mobile view hard to use.

#### Ticket Link
[MM-46006](https://mattermost.atlassian.net/browse/MM-46006)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge - waiting for the Cypress cycle to complete.
- Verified RHS and LHS in mobile view can be dismissed.

**Review by jgilliam17 — APPROVED** [review]
[E2E report](https://automation-dashboard.vercel.app/cycles/554f39f4-1746-46d9-9e2c-bb7febb9805e) looks good - no PR related failures.

**Comment by michelengelen** [comment]
I will defer the second dev review since it is such a small change.

**Pull request merged**
