### PR TITLE
MM-25177 Update latex_block.jsx to left-align math

### PR DESCRIPTION
**Pull request by awerries**
#### Summary
Unlike the result of most mattermost commands and text rendering, KaTeX renders its math output centered by default. This PR overrides this by setting "fleqn: true". This causes left-alignment, which should meet most users' expectations. [This option is documented here](https://katex.org/docs/options.html).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-25177

#### Screenshots
*Before:*
```
    This is an example of KaTeX rendering
    ```latex
    c = \pm\sqrt{a^2 + b^2}\in\R
    ````
```
![Capture](https://user-images.githubusercontent.com/2243102/80659172-0503e180-8a3d-11ea-869e-57435c2c8cd7.PNG)

*After:*
![image](https://user-images.githubusercontent.com/2243102/80693978-b11eea00-8a88-11ea-9984-03e9037d9877.png)

### CODE REVIEW

**Comment by awerries** [comment]
Thanks! Updated description with a screenshot from a test server. Looks great to me. Took me a moment to realize I had to enable LaTeX rendering in the admin settings.

I can test more complex examples if desired.

**Comment by awerries** [comment]
anything else needed?

**Comment by andrewbrown00** [comment]
@hanzei can we have `dev` and `qa` review this, thanks 😄

**Comment by awerries** [comment]
> Test server creation failed. See the logs for more information.

not sure what happened. I don't _think_ my change did this?

**Comment by hmhealey** [comment]
I'll try re-running the build in case it's just an intermittent error. If that doesn't work, we can try updating the branch from master again in case that fixes it.

**Pull request merged**
