### PR TITLE
Migrate string refs to functional ones in brand_image_setting component

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Fixes https://github.com/mattermost/mattermost-server/issues/15851

JIRA ticket: https://mattermost.atlassian.net/browse/MM-29412

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @sowmiyamuthuraman!

**Comment by jasonblais** [comment]
@mkraft kind reminder to help with review :)

**Review by mkraft — APPROVED** [review]

**Review by josephbaylon — APPROVED** [review]
LGTM. @sowmiyamuthuraman Thanks for your contribution !!

Verified `brand_image_setting.test.jsx` already exist and `e2e/cypress/integration/system_console/ui_and_api/customization_spec.js` passed locally.

**Pull request merged**
