### PR TITLE
Remove the reply bar in RHS

### PR DESCRIPTION
**Pull request by enahum**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12377

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

### CODE REVIEW

**Comment by sudheerDev** [comment]
@enahum This PR is just for the ticket or it needs to be updated for other issues as mobile view post RHS header?

**Comment by enahum** [comment]
@sudheerDev there is a conversation around this here https://pre-release.mattermost.com/core/pl/q7jctd8m6fbxbecr397f3zmgwe

**Comment by sudheerDev** [comment]
I saw the thread. I approved assuming it just for the issue described in ticket

**Comment by enahum** [comment]
This PR is for to remove the reply bar,.. it seems that there are other stuff around the same area but I think those should be addressed in different PR's in any case with their own tickets

**Pull request merged**
