### PR TITLE
Updating styles for muted channel

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Updating styles for muted channel

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

screen shot 2018-04-02 at 5 38 57 pm

screen shot 2018-04-02 at 5 41 52 pm

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@esethna Can you approve this if it looks okay?

**Comment by esethna** [comment]
@asaadmahmood I think it's too opaque now. I can't really tell the difference between a muted vs unmuted channel. Maybe 50%?

**Comment by asaadmahmood** [comment]
@esethna Have a look. Reduced it to .5. (Slack has it at .64).
screen shot 2018-04-03 at 5 50 30 am

**Comment by asaadmahmood** [comment]
@enahum Can you make the same changes on your PR? Change that to .5?

**Comment by enahum** [comment]
Made the change about 10 hours ago

**Pull request merged**
