### PR TITLE
MM-19303 - When adding a guest to a team from the user management page the Guest is put into a channel not found page and unable to log out or request help

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
added new message for guests with no channels

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-19303

#### Screenshots

image

### CODE REVIEW

**Comment by lindalumitchell** [comment]
(FYI I borrowed this spinwick for a bit of testing whether OAuth SSO can work on any spinwick; please disregard user I added, etc.)

**Comment by reflog** [comment]
@srkgupta - before I change this - I think this should be discussed with @wiersgallak and @jespino - since to me it's not really clear what's the desired behavior here. Which 'other' team should we redirect to, if there's more than 2?

**Comment by srkgupta** [comment]
@reflog 
Note: If I navigate to / url, it redirects me properly to the other team. So may be redirecting the user to `/` when user clicks on back button will resolve the issue.

**Comment by reflog** [comment]
@srkgupta - ok, I'll look into it. Thanks for catching this

**Comment by srkgupta** [comment]
An alternate way to fix this issue is to prevent system admin to assign a team to a guest user from system console. This would prevent these issues to happen in the first place. It does not makes sense to assign a user to a team, without a channel.

**Comment by reflog** [comment]
True, we've already discussed this with @wiersgallak and it will be addressed by UX team

**Comment by wiersgallak** [comment]
Improvement ticket: https://mattermost.atlassian.net/browse/MM-20207

**Comment by reflog** [comment]
@wiersgallak - given that we have an improvement ticket, should I still add the changes @srkgupta proposed?

**Comment by wiersgallak** [comment]
@reflog Yes please.

**Comment by reflog** [comment]
@srkgupta - I've tried reproducing the issue: guest user in two teams, in channel on **team A** but not on any channel in **team B**.
Seems to work fine, when accessing **Team B**, I get the error message and when I press back, I am taken to **Team A**

Here's a recording (sorry for the quality)
z

**Comment by srkgupta** [comment]
Hi @reflog 
I am still able to reproduce the issue. Here are the steps I had followed. 
1) Guest User is logged into Browser and has access to Team A. 
2) System Admin on different browser assigns Team B to Guest User. 
3) Guest User sees Team B on the sidebar and clicks on it. 
4) User sees an error. When user clicks on Back, user is redirected back to the error page
Let's follow-up on DM if you need any clarifications.

**Comment by reflog** [comment]
@cpanato help please 😢

**Comment by cpanato** [comment]
I'm checking why this is failing, but need to stop now for some meetings, will continue later. bear with me

**Comment by cpanato** [comment]
@reflog sorry for the delay

**Comment by reflog** [comment]
Thanks @cpanato!

**Comment by reflog** [comment]
@srkgupta can you test again please?

**Pull request merged**
