### PR TITLE
PLT-7798 Support new mattermost-redux action returns

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Support new mattermost-redux action returns.

@lindalumitchell could I get your help just running a smoke test on this? I did one myself already but another set of eyes would be awesome. It touches a bunch of different parts of the app, anything broken by this should be obvious and have a JS error.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7798

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@jwilander I'm still working through some more smoke testing, but may have found one issue so far.

1. In a public channel, click channel name > Leave Channel

Observed: Appears to leave channel visually (disappears from LHS and Town Square briefly displays), but then the page auto-refreshes, and channel is still there in LHS and center. Still part of the channel after refresh and logout/login. Can repeat selecting Leave Channel with same behavior.

Expected: User leaves channel. Channel name removed from LHS, and center displays Town Square.

test2-tries-leave-channel

Saw slightly different behavior only once (no refresh, but channel still stayed. Channel top nav appeared blank): test1-after-clicking-to-leave

**Comment by jwilander** [comment]
I'm pretty sure it's caused by the bug that was fixed in the RC but I'll take a look to confirm that's it not anything in this PR

**Comment by jwilander** [comment]
Right here https://github.com/mattermost/mattermost-webapp/blob/master/actions/websocket_actions.jsx#L382, you need to add:

```
dispatch({
    type: ChannelTypes.RECEIVED_PROFILE_NOT_IN_CHANNEL,
    data: {user_id: msg.broadcast.user_id},
    id: channelId
});
```

Essentially the redux store was not getting the information that user was removed from the channel. Dispatching this event should cover that

**Comment by jwilander** [comment]
@lindalumitchell I just rebased onto latest and did another little smoke test myself. The leaving channel issue seems to be fixed now that 4.3 was merged into master.

If you can take another look that would be much appreciated

**Comment by jwilander** [comment]
First one is definitely this PR, I'll fix it. Nice catch!

For the second one yeah, that's likely just a result of the PDF dependency we're using but I'll take a look at it just to be sure

**Comment by jwilander** [comment]
Pushed a fix for adding commands and looked into the second one which is indeed a non-issue

**Comment by lindalumitchell** [comment]
@jwilander I verified that the slash command issue is fixed on the new spinmint, and did some more smoke testing, and it all looks great! No new issues found. 👍

**Comment by jwilander** [comment]
Awesome, thanks @lindalumitchell really appreciate your help on this

**Pull request merged**
