### PR TITLE
[MM-28211] Plan Details Card

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Plan Details card showing current cloud subscription, features, # of seats and some pricing.
UX reviewed here: https://github.com/mattermost/mattermost-webapp/pull/6463

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28211

#### Related Pull Requests
- Has server changes (https://github.com/mattermost/mattermost-server/pull/15655)
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/1250)

### CODE REVIEW

**Review by jwilander — APPROVED** [review]
LGTM - just the one comment

**Review by ali-farooq0 — APPROVED** [review]

**Comment by jwilander** [comment]
@devinbinnie this still has the WIP label on it - just checking if that should be removed

**Comment by devinbinnie** [comment]
@jwilander It's currently waiting on this ticket to finish: https://mattermost.atlassian.net/browse/MM-28714

We can merge as is if you'd like.

**Comment by jwilander** [comment]
Nope, that's fine was just checking - please ignore me :)

**Pull request merged**
