### PR TITLE
Fix bot icon heigth

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The CSS in https://github.com/mattermost/mattermost-webapp/blob/4292e567c6e4f368c6f30f96cb8f1a0e3fb018af/sass/layout/_legacy-sidebar-left.scss#L47-L54 expects the svg to be part of an parent element. This PR adds a `span` around the `svg`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22764

#### Related Pull Requests
None

#### Screenshots
Screenshot from 2020-09-29 16-06-48

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Deployed Matterpoll branch with custom icon
- Icon height looks consistent 
- No issues found

LGTM!

**Pull request merged**
