### PR TITLE
Implementing dark theme for the invitation flow

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Implementing dark theme for the invitation flow

#### Ticket Link
[MM-15559](https://mattermost.atlassian.net/browse/MM-15559)

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@jespino Can we get a screenshot of the invitation flow on light and dark themes?

**Comment by jespino** [comment]
@asaadmahmood I'll do it, but something went wrong with a merge or something like that, so... I have to fix some things before

**Comment by jespino** [comment]
Screenshot_2019-06-25 (1) Town Square - eligendi Mattermost(3)
Screenshot_2019-06-25 (1) Town Square - eligendi Mattermost(2)
Screenshot_2019-06-25 (1) Town Square - eligendi Mattermost(1)
Screenshot_2019-06-25 (1) Town Square - eligendi Mattermost

**Comment by asaadmahmood** [comment]
Looks good to me, I think the padding is a bit messed up for the selected options in the input, but I'll defer that to @michaelgamble.

**Pull request merged**
