### PR TITLE
MM-40222 - show the gov references in license page when gov license

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
This PR adds the logic for checking for the isGovSku value in the licenses, and when found will show the Gov references in the licensing page.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40222

#### Related Pull Requests
- Has server changes (https://github.com/mattermost/mattermost-server/pull/19100)

#### Screenshots

Captura de pantalla 2021-11-29 a las 15 57 05

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]

**Comment by annelieseklein** [comment]
Screen Shot 2021-11-29 at 7 10 45 PM
Looks great! the border radius of the license details should be rounder as seen above in the figma design @pablovelezvidal

**Comment by annelieseklein** [comment]
Is the body text for the license details in open sans?

**Review by AGMETEOR — APPROVED** [review]

**Comment by marianunez** [comment]
@pablovelezvidal it seems that uploading regular licenses is also labeling them as `Gov` as well, can you double check this @stevemudie ?

**Comment by stevemudie** [comment]
@marianunez 

I'm seeing the same. Any/all licenses read Gov.

**Comment by pablovelezvidal** [comment]
> @marianunez
> 
> I'm seeing the same. Any/all licenses read Gov.

addressing it now.

**Comment by pablovelezvidal** [comment]
@marianunez @stevemudie Fixed! good catch! thanks!

@annelieseklein your suggestions were also addressed!
Captura de pantalla 2021-11-30 a las 21 40 39

Captura de pantalla 2021-11-30 a las 21 40 13

**Review by stevemudie — APPROVED** [review]
Looks good @pablovelezvidal!

Gov licenses display as Gov while others do not as expected.

**Review by annelieseklein — APPROVED** [review]

**Pull request merged**
