### PR TITLE
[MM-18531] Added Feature to Close Channel via Direct Message

### PR DESCRIPTION
**Pull request by bradjcoughlin**
Picking up from existing [PR](https://github.com/mattermost/mattermost-webapp/pull/3694) from @DarrellRichards.

### Summary
This PR gives support for Closing a Direct Message under the DM username. 

Decided to create a new component to handle this feature, instead of reworking the `CloseChannel` already in place due to the fact that the `CloseChannel` is based on `isArchived`.

Changes: 

- [X] UI
- [X] Added Unit Tests

#### Ticket Link
Fixes  [https://github.com/mattermost/mattermost-server/issues/12244](https://github.com/mattermost/mattermost-server/issues/12244)

Jira: [https://mattermost.atlassian.net/browse/MM-18531](https://mattermost.atlassian.net/browse/MM-18531)

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thank you @bradjcoughlin 
`Close Channel' is present as DM menu option as described

Few questions for @esethna and @andrewbrown00 
I was wondering if we should consider expanding this PR to include a similar option for GM menu? 

Mobile has this implemented as 'Close Direct Message' and 'Close Group Message' respectively. 
Should we keep the text/menu options consistent across platforms? Thanks.

Screen Shot 2019-12-23 at 4 08 20 PM
Screen Shot 2019-12-23 at 4 08 39 PM

**Comment by andrewbrown00** [comment]
> Few questions for @esethna and @andrewbrown00
> I was wondering if we should consider expanding this PR to include a similar option for GM menu?
> 
> Mobile has this implemented as 'Close Direct Message' and 'Close Group Message' respectively.
> Should we keep the text/menu options consistent across platforms? Thanks.

Hi @jgilliam17 thanks for bringing this up! We should add the option for Group Messages to maintain consistency. Also, I'm 5/5 we should change verbiage to be consistent too, it feels odd to say **Close Channel** for Direct Messages. To a user it's a Direct Message and not a channel; this becomes more confusing for Group Messages, which I know we treat like channels behind the scenes, but they are really just that, **Group** Direct Messages.

**Proposed Changes**
Use consistent verbiage across the web and mobile apps for closing Direct and Group Messages.

- Close Direct Message
- Close Group Message

@adamjclarkson do you mind providing your thoughts here while Eric is OOO.

**Comment by adamjclarkson** [comment]
> **Proposed Changes**
> Use consistent verbiage across the web and mobile apps for closing Direct and Group Messages.
> 
> * Close Direct Message
> * Close Group Message

Agreed. These phrases are better and consistent with mobile. Great catch.

**Comment by bradjcoughlin** [comment]
@andrewbrown00 @adamjclarkson just catching up on this one. Looks like I need to make two string changes in this PR, correct?

**Comment by andrewbrown00** [comment]
> @andrewbrown00 @adamjclarkson just catching up on this one. Looks like I need to make two string changes in this PR, correct?

That's correct, thanks @bradjcoughlin

**Comment by bradjcoughlin** [comment]
@andrewbrown00 @esethna updated this PR if you'd like to take another look 🙏

**Comment by bradjcoughlin** [comment]
@esethna I suggest we create another ticket for the group menu dropdown close option.

**Pull request merged**
