### PR TITLE
remove unused code around unimplemented ExperimentalSettings.EnableCl…

### PR DESCRIPTION
**Pull request by darkLord19**
Fixes https://github.com/mattermost/mattermost-server/issues/20361

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/20389

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Looks good. Thanks for cleaning that up!

I'll also give CI a kick to see if it can sort itself out

**Review by AshishDhama — APPROVED** [review]

**Comment by AshishDhama** [comment]
@hmhealey Do we need QA testing on this.

**Comment by hmhealey** [comment]
No, I don't think so. It's just removing settings infrastructure that wasn't used, so I don't think they'd have anything to test anyway

**Pull request merged**
