### PR TITLE
MM-17294 - Revert "MM-15452 - Add ability to override LHS icon for bot accounts (#3026)

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Disable displaying LHS bot-icon. Will re-enable as part of https://mattermost.atlassian.net/browse/MM-17422

This reverts commit c74f4caba2cbe496683d16a9b57d92c9a8618c7f.
https://github.com/mattermost/mattermost-webapp/pull/3026

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-17294

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/3026

### CODE REVIEW

**Comment by ali-farooq0** [comment]
> @ali-farooq0 After this revert will you revert again when the functionality mentioned in the ticket is implemented (is this possible?) or will it be a different approach and new implementation? Just wondering, if you are going to revert again that you may want to include with commit it is in the JIRA Ticket for later.

@marianunez Yep that's the intention. Good catch on including this PR in the new JIRA. I thought I had this PR's link in there but guess I forgot. Including it now.

**Comment by ali-farooq0** [comment]
@lindalumitchell this is reverting a feature to display LHS bot icon. We need extra functionality on the backend before we can enable this in the webapp. Since this is a revert, does it warrant a QA review? I've done a smoke test myself.

**Comment by lindalumitchell** [comment]
Thanks @ali-farooq0, since MM-15452 hasn't been tested yet, I think it's fine to merge this PR and we can verify while testing MM-15452 that the API piece still works (and also do some smoke testing as you have done).

**Comment by ali-farooq0** [comment]
> Thanks @ali-farooq0, since MM-15452 hasn't been tested yet, I think it's fine to merge this PR and we can verify while testing MM-15452 that the API piece still works (and also do some smoke testing as you have done).

👍 great! merging this in.

**Pull request merged**
