### PR TITLE
Proposed changes to "Contact sales" area title

### PR DESCRIPTION
**Pull request by jasonblais**
Based on PMM proposal, adjust `Need to increase your headcount?` to `Need to increase user count?`

 - "headcount" is not a preferred term over seats or users
 - shortening text slightly to fit within one line

image

```release-note
NONE
```

cc @annelieseklein for your review, plus if we'd need to reflect it in our design file

### CODE REVIEW

**Review by pablovelezvidal — COMMENTED** [review]
thanks @jasonblais , this change requires also a text modification in `i18n > en.json` line 1225. https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json#L1225

**Comment by jasonblais** [comment]
@pablovelezvidal thanks! Good catch, updated

**Review by pablovelezvidal — APPROVED** [review]
LGTM thanks @jasonblais! :shipit:

**Review by stevemudie — APPROVED** [review]
New text appears as expected.

**Review by AGMETEOR — APPROVED** [review]

**Review by annelieseklein — APPROVED** [review]

**Pull request merged**
