### PR TITLE
MM-14774 Use default 'pointer' cursor for non-clickable menu items

### PR DESCRIPTION
**Pull request by bradjcoughlin**
#### Summary
A global pointer style was applied to all `<MenuWrapper>` instances. I removed it and tested on as many menus as I could find and did not see any problems. If QA would like to help me test, that would be great.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/14774

#### Related Pull Requests
N/A

#### Screenshots
Screen Shot 2020-06-11 at 9 11 56 AM

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thank you @bradjcoughlin 
Tested, looks good. 
I checked for other menus with similar title area and only found Members>Channel Members, no change there.
- Verified `Status` text change
- Verified mouse pointer on hover over menu title, no longer hand cursor.

**Comment by esethna** [comment]
@nevyangelova can we merge this?

**Comment by nevyangelova** [comment]
@esethna yes, LGTM!

**Pull request merged**
