### PR TITLE
MM-19176 - Clear button for search in plugins marketplace

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary
Added a 'x' button to clear the search in Plugins Marketplace.
 
#### Ticket Link
[MM-19176](https://mattermost.atlassian.net/browse/MM-19176)

### CODE REVIEW

**Comment by marianunez** [comment]
@jespino Do you think that this 'x' clear button should be something we could include in a widget or part of the `QuickInput` component? I included the same code as it is currently in the Search Bar and it seems to be used in a couple of more places.

**Comment by jespino** [comment]
Yes, I think so, it is part o the widget I think

**Comment by marianunez** [comment]
> it is part o the widget I think

@jespino It is currently not part of the `QuickInput` component. Should I create a separate ticket as part of the common widgets effort?

**Comment by ali-farooq0** [comment]
@marianunez i strongly recommend we add this `clearable` field functionality to the `QuickInput` component, unless it's going to be massive effort to add it there.

**Comment by jespino** [comment]
@marianunez `QuickInput` is not still part of the widgets library, maybe we can try to merge it in the widgets library, but for now is not in our scope. Probably, if is not a big effort, I'm agree with @ali-farooq0, if we can fix it right away, would be great.

**Comment by lieut-data** [comment]
@ali-farooq0, is the proposed improvement to this PR something we should address in v5.18 as part of this feature, or as a "tech-debt" improvement to the general component?

**Comment by marianunez** [comment]
I won't be able to make the refactoring change to meet the 5.18 code complete due to being in SET this week. 

Maybe could merge this for 5.18 so the marketplace does have this feature and I could open a PR for the change for future version? If not marketplace won't have this improvement until 5.20 probably.

**Comment by lieut-data** [comment]
Thanks for the clarification, @marianunez -- retriggering @ali-farooq0 for feedback. If we can't merge, I think it's fine for v5.20.

**Comment by ali-farooq0** [comment]
Creating a tech-debt item for moving this functionality to the `QuickInput` component and pushing that out a release or two sounds good.

**Comment by marianunez** [comment]
I've captured this effort here [MM-20068](https://mattermost.atlassian.net/browse/MM-20068). 

@jespino are you OK with merging this now and having a separate PR for the refactoring work?

**Comment by jespino** [comment]
@marianunez Yes, perfect :)

**Pull request merged**
