### PR TITLE
MM-20144 - Fixed Mattermost typo in System Console -> LDAP Settings

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Fixed Mattermost typo in System Console screen.

#### Ticket Link
Fixes [MM-20144](https://mattermost.atlassian.net/browse/MM-20144)

### CODE REVIEW

**Comment by marianunez** [comment]
> Remove every other translation file but en.json

Even the ones that have the text translated already? like `pl.json`?

**Comment by enahum** [comment]
Yes

**Comment by marianunez** [comment]
@enahum Done! Yeah I wasn't sure if I could modify the translated files directly, hence you as a reviewer 😉 Thanks!

**Comment by marianunez** [comment]
Ok now we are good @enahum

**Pull request merged**
