### PR TITLE
📦 added jest watch typeahead

### PR DESCRIPTION
**Pull request by paulussujono**
#### Summary
Added `jest-watch-typeahead` plugin to show which files are matched by the pattern when running jest in watch mode.
https://github.com/jest-community/jest-watch-typeahead

##### Before
image

##### After
image
image
image

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Awesome, LGTM, thanks @paulussujono!

**Review by ali-farooq0 — APPROVED** [review]
Nice work @paulussujono 🎉 !!

**Comment by hmhealey** [comment]
Hi @paulussujono, thanks for the PR. I want to check with the team before approving this since we want to avoid adding too many dependencies that will later need to be maintained since we already have quite a lot of them. This one only affects development and won't affect end users at all, but we want to make sure we'll actually make use of it in case it slows down the development workflow at all. We should be meeting to discuss that tomorrow.

**Comment by hmhealey** [comment]
We chatted about this, and some people hadn't actually seen Jest watch before, so they're looking forward to trying it out and using it with this plugin as well. Thanks again!

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
