### PR TITLE
[MM-24861] Enabled plugins without any configs to be displayed in admin sidebar

### PR DESCRIPTION
**Pull request by TheDarkestDay**
#### Summary
Admin sidebar now should display all of the plugins under "Plugins" section without hiding the ones which have no available settings besides simple "enabled/disabled" toggle.

#### Ticket Link
Fixes [MM-24861](https://github.com/mattermost/mattermost-server/issues/14473)

#### Related Pull Requests
I believe there are none of them

#### Screenshots
No visual UI changes have been introduced

### CODE REVIEW

**Comment by TheDarkestDay** [comment]
So as far I can see after the pulling latest changes from `master` we have one failing snapshot test - https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/19185/workflows/08cb2244-ecb2-4aab-a575-3d8160016744/jobs/121549/steps

Correct me if I'm wrong but it seems as if my changes have nothing in relation with it?

Should I simply update the snapshots?

**Comment by agarciamontoro** [comment]
This got buried under my notifications, sorry! Updating the branch and merging :)

**Comment by agarciamontoro** [comment]
Thank you again for a great contribution, @TheDarkestDay!

**Pull request merged**
