### PR TITLE
Minor Bug fixes

### PR DESCRIPTION
**Pull request by asaadmahmood**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
MM-10923 - Emoji cut off in header
MM-10930 - Improving reactions and emoji picker
MM-10959 - Fixing emoji picker in RHS expanded
MM-10963 - Updating image modal for tablets
MM-10660 - Single image expand and collapse icon

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10923
https://mattermost.atlassian.net/browse/MM-10930
https://mattermost.atlassian.net/browse/MM-10959
https://mattermost.atlassian.net/browse/MM-10963
https://mattermost.atlassian.net/browse/MM-10660

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by esethna** [comment]
@asaadmahmood looks like there are some build errors?

**Comment by asaadmahmood** [comment]
@esethna Build passed.

**Comment by hmhealey** [comment]
@esethna @asaadmahmood I think we should consider holding off on updating the emoji picker for now since this is going to conflict a lot with the changes required for the gfycat integration

**Comment by asaadmahmood** [comment]
@hmhealey These are just few lines of css changes for the emoji picker. If you want, you can push me the gfycat branch if you're having trouble, and I can merge the css changes I don't think it's going to be that big of an issue. Since there are just not a lot of changes.

**Comment by hmhealey** [comment]
@asaadmahmood We've asked them to make a lot of changes already, so I'd rather not make them deal with additional merge conflicts since the changes that you're making directly conflict with theirs which are high priority for 5.1. If the changes you're making are to fix the linked bugs, we can deal with those conflicts, but some of these look like they're unrelated improvements rather than bug fixes.

**Comment by asaadmahmood** [comment]
@esethna I've removed my changes. Looks like this back and forth is taking up quite some time. Was just looking at the Gfycat channel, and it looks like the feature might need some help with the styling. I can then add these changes when I'm doing the styling improvements there.

**Pull request merged**
