### PR TITLE
Cypress/E2E: Fix user profile focus and menu option aria-label

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Fixed failed tests on user profile focus introduced by https://github.com/mattermost/mattermost-webapp/pull/9383
- Fixed aria-label of "Profile" menu item and include test on it
- Removed the use of implementation specific detail (CSS class) in favor of accessible attribute (`be.focused`)

#### Ticket Link
none, failed on daily run

#### Screenshots
Screen Shot 2021-11-24 at 2 45 43 PM
Screen Shot 2021-11-24 at 3 05 32 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
Thanks @saturninoabril and I am sorry I missed that! We will add an e2e script soon so we don't miss failing e2e tests in the future

**Comment by saturninoabril** [comment]
Thanks @nevyangelova and no worries. We really appreciate to run E2E test atleast once in a PR and fix affected test in the PR itself before merging.
> We will add an e2e script soon

Is this a separate script from what we're [working in mattermod](https://github.com/mattermost/mattermost-mattermod/pull/282) and curl command to directly trigger pipeline from Gitlab? Curious to see if you have other on going effort here.

**Comment by jgilliam17** [comment]
Apologies @saturninoabril, that was my miss, I forgot to run E2Es. 
I see that you posted screenshots with fixed tests, do we need to re-run E2Es? Let me know. Thanks.

**Comment by saturninoabril** [comment]
Thanks Jelena and no worries! I'll spin up the test and will post here the actual result.

**Comment by saturninoabril** [comment]
@jgilliam17 Looks like you ran it already :) - https://automation-dashboard.vercel.app/cycles/a6895bee-35d6-46ce-a9dc-a29a9e4ac94f

**Comment by jgilliam17** [comment]
Thanks @saturninoabril 
Checked the report - looks good to merge.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
