### PR TITLE
Removing more unused files

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Removing more unused files

#### Ticket Link
Remove PersistGate - https://mattermost.atlassian.net/browse/MM-32559

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
🆗  It looks good to me. Thank you

**Comment by jespino** [comment]
@jgilliam17 do you mind to run e2e test here to, to verify we are not breaking anything with this changes?

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
@jespino can you please update manually. Thanks!

**Comment by jespino** [comment]
@jgilliam17 Updated.

**Comment by jgilliam17** [comment]
Thanks @jespino 
Here are the latest results [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/96397-10a0228-onprem-ent-webapp-pr-9422-mm-ee-test:10a0228/mochawesome.html)
Most are unrelated failures and are also present on the master run report.
There are however 3 failed and 9 skipped tests(due to failed) that relate to data retention global and custom policy. Can you please take a look?
Thanks
Screen Shot 2021-12-10 at 2 19 07 PM

**Comment by jespino** [comment]
@jgilliam17 sure, probably next Monday, but I'll take a look.

**Comment by jgilliam17** [comment]
@jespino I ran the E2Es again since I noticed that tests I mentioned above started failing on master and other PRs. 
See latest [E2E results here](https://automation-dashboard.vercel.app/cycles/fc8ae917-23bc-4fa9-9eec-5043c7462026)
Failures do not appear to be PR related, manually re-tested ones that differ from master - passed.
Looks good to merge.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
