### PR TITLE
[MM-44959]: undo & redo for advanced text editor

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
this adds the undo/redo functionality to the `AdvancedTextEditor` component.
It also kind of adds value state management with the `UndoableContext`. It triggers on every value change from the outside. Once the state management is adjusted/refactore we might want to revisit this and change it accordingly.

> ⚠️ NOTE for UX: I designed this with a maximum of 50 items in the each history (past and future). This threshold might be reached pretty fast when typing normally, so we might want to think of a debouncing effect, or only trigger this once a full word is typed or something similar. We could also just increase the maximum length of the history to 1000 items each or so. IMO this should not have any impact on performance.
> 
> One thing to note on this: adding in a different trigger handling might take a considerable amount of work (compared to just adjust the history length) and we might need to wait for the state management refactoring on this, so keep that in mind. The way it is now it works just fine.

Another note on this: I have used `ArrowLeftIcon` and `ArrowRightIcon` for the buttons. Is that fine with UX?

#### Ticket Link
[MM-44959](https://mattermost.atlassian.net/browse/MM-44959)

#### Related Pull Requests
n/a

#### Screenshots
n/a 

#### Release Note
```release-note
adds undo and redo functionality to the advanced text editor
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@michelengelen I don't think we need to add the back/forth buttons in to the advanced text editor UI. It's adding extra clutter. The only thing we should support is the use of the standard undo/redo keyboard shortcuts (e.g. CMD Z/Ctrl Z), which I believe was the intent of this ticket. In this PR, it does not appear to support shortcuts for undo/redo?

**Comment by matthewbirtch** [comment]
> ⚠️ NOTE for UX: I designed this with a maximum of 50 items in the each history (past and future). This threshold might be reached pretty fast when typing normally, so we might want to think of a debouncing effect, or only trigger this once a full word is typed or something similar. We could also just increase the maximum length of the history to 1000 items each or so. IMO this should not have any impact on performance.

I say let's keep it at 50 for now and we can always increase it later.

**Comment by michelengelen** [comment]
@matthewbirtch I removed the buttons and added a keyboard event-handler to handle undo/redo with CTRL+Z and CTRL+SHIFT+Z (since CTRL+Y is a browser-specific command and this aligns with how other applications handle it)

**Comment by michelengelen** [comment]
@matthewbirtch I will close this PR for now, since I ran into several issues with it that need to be handled before we can have a new take on this.

To be a little more specific here is a short list of what we need to adjust:
1. move state handling inside the Advanced Text Editor, specifically the message state.
2. think of a way to make the Advanced Text Editor more implementation-agnostic. More on that below.
3. create a method of getting/storing drafts without breaking the inner state

The problems I have been facing come from several unfortunate data-design decisions. All of the post specific actions are needed to have internal message state. Refactoring this to use the Advanced Text Editor state takes a considerable amount of effort that is out of scope for this PR.

There are so many different use-cases in create-post and create-comment components that need to be handled separately that adding the undo/redo functionality to it is currently either super-hacky and error-prone that I would rather not add it prematurely. (saving drafts, handling slash-commands, setting error messages, handling specific hotkeys for editing the latest post and moving in the message history, etc.)

So if everyone is on the same line here we should think about making the Advanced Text Editor implementation-agnostic first.

I have drafted a document that outlines roughly what needs to be done to achieve what we need for the Advanced Text Editor. I will send an invite to the doc to you after writing this comment.

Please understand my concerns, since I do not feel comfortable meddling with this now and potentially adding in bugs that break an important component such as this.

cc @esethna @AshishDhama

**Comment by matthewbirtch** [comment]
Makes sense to me @michelengelen. I don't think the undo/redo functionality is critical right now anyway and it makes sense to me to do that after we've solved the other problems you've outlined first

**Pull request closed without merging**
