### PR TITLE
[MM-35770] fix issues with timed DND feature

### PR DESCRIPTION
**Pull request by darkLord19**
Fixes https://mattermost.atlassian.net/browse/MM-35770

### CODE REVIEW

**Comment by darkLord19** [comment]
Do Not Merge!!! Waiting for other issues to be identified to send fix via same ticket.

**Comment by darkLord19** [comment]
@jgilliam17

**Comment by jgilliam17** [comment]
Thanks @darkLord19 
Here is the link to the test case [MM-T4070](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4070)
Use MM-T4070_1 thorough _5
I used your steps for the e2es from your previous PR, and split the custom part into 4 different steps, but am open to integrate all back into one. Let me know and I can edit the test case ro reflect your changes. Thanks.

**Comment by Willyfrog** [comment]
> Do Not Merge!!! Waiting for other issues to be identified to send fix via same ticket.

let me know when this is ready, so I can update and assign people accordingly

**Comment by jgilliam17** [comment]
@darkLord19 let me know if you have any additional questions and if the answers you received `in channel` are sufficient. Thanks. 🙂

**Comment by darkLord19** [comment]
Cherry-picked commits to https://github.com/mattermost/mattermost-webapp/pull/8160

**Pull request closed without merging**
