### PR TITLE
[PLT-7690] Add alt to profile images

### PR DESCRIPTION
**Pull request by tejasbubane**
#### Summary
Add alt to all profile images

#### Ticket Link
Github: https://github.com/mattermost/mattermost-server/issues/8033
Jira: https://mattermost.atlassian.net/browse/PLT-7690

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes

### CODE REVIEW

**Comment by hmhealey** [comment]
@jasonblais Does the alt text on these images need to be human readable? Right now, it's `hmhealey-profile-picture`, so I'm wondering if it should be `hmhealey profile picture` instead. We might also want to translate it so any non-English user with a screen reader can see it

**Comment by jasonblais** [comment]
> Does the alt text on these images need to be human readable? Right now, it's hmhealey-profile-picture, so I'm wondering if it should be hmhealey profile picture instead. We might also want to translate it so any non-English user with a screen reader can see it

@asaadmahmood Do you know?

**Comment by asaadmahmood** [comment]
@hmhealey @jasonblais Ideally it should. We can make that change, don't think it's that big of a deal. However, pragmatically, people seeing this alt text would be marginal, in the case where the image does not load, or for screen readers (blind people, etc).

**Comment by jasonblais** [comment]
@tejasbubane Would you be interested helping with the changes @hmhealey mentions above?

> Does the alt text on these images need to be human readable? Right now, it's hmhealey-profile-picture, so I'm wondering if it should be hmhealey profile picture instead. We might also want to translate it so any non-English user with a screen reader can see it

**Comment by tejasbubane** [comment]
> Would you be interested helping with the changes @hmhealey mentions above?

Done. @hmhealey please review.

**Comment by hmhealey** [comment]
Thanks for changing that. Looks good

**Pull request merged**
