### PR TITLE
[MM-45719] Combine focus on avatar and status icon in global header

### PR DESCRIPTION
**Pull request by cyrilzhang-mm**
#### Summary

Combine the avatar and status icon in global header into one button that can be focused.

#### Ticket Link

[Jira ticket](https://mattermost.atlassian.net/browse/MM-45719)

#### Screenshots

Screen Shot 2022-09-29 at 11 21 32 AM

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]
LGTM!

**Comment by cyrilzhang-mm** [comment]
Just pushed a small commit containing CSS as I noticed there was a style issue. It now correctly looks like this:

Screen Shot 2022-10-03 at 10 32 36 AM

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working fine

**Pull request merged**
