### PR TITLE
Improvement - Updated AppManifest Types

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

#### Summary
This PR Updates AppManifestTypes

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-app-zendesk/issues/78

#### Related Pull Requests
Related PR, https://github.com/mattermost/mattermost-redux/pull/1426

### CODE REVIEW

**Comment by mickmister** [comment]
@jfrerich I think the manifests have been changing a bit more right? Maybe we should hold off on merging since the frontend doesn't use this anyway. Is the goal to import this into Nodejs Apps from the webapp repo?

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @adithyaakrishna

**Comment by mickmister** [comment]
@jfrerich I'm concerned that this PR is going stale. What is the urgency on this? Also please see my comment above with some more questions

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna, can you fix the CI linting error? you can do it manually, or by running `npm run fix`

My bad, I had missed this. Will fix it ASAP 💯

**Comment by jfrerich** [comment]
I look forward to the clean build, @adithyaakrishna :)

**Comment by jfrerich** [comment]
@mickmister, yes the goal is to import the this into the Zendesk app.

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
