### PR TITLE
update compass font icon

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Updating the Compass Icon font to the [latest version](https://github.com/deanwhillier/mattermost/tree/cadd40fa886d49b5f91e0105f20a80e3992fcab2) to include new icons needed for ongoing features.

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]
Tested, infinity icon looks good!

**Review by matthewbirtch — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @deanwhillier for the testing steps
Tested, looks good to merge.
- Verified icons for server-variant, server-variant-plus, infinity and crown-outline.

**Pull request merged**
