### PR TITLE
MM-48325, MM-49501: announcement-bar placement in mobile view

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
Adds `announcement` and `footer` css-grid areas in mobile layout to support announcement bars in mobile view, and to better reflect the standard (desktop) layout grid.

Standard:
standard

Mobile:
mobile

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-48325
- https://mattermost.atlassian.net/browse/MM-49501

#### Screenshots
|  before  |  after  |
|----|----|
| before | after |
#### Release Note

```release-note
Fixed a layout issue in mobile-view that caused announcement bars to appear in the wrong place
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Wow, grid view makes that so much simpler than a similar fix would've been before

**Comment by jgilliam17** [comment]
Thanks @calebroseland 
Tested, looks good to merge.
Verified announcement bar placement in mobile webview.
[E2E report](https://automation-dashboard.vercel.app/cycle/291529) looks good - no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
