### PR TITLE
Optimize channels reducer to only update state when necessary

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
The channels reducer was often updating state when nothing had changed, causing significant selector recomputation.

This optimizes that by:

1. Checking if there were any changes before updating state
2. Using server provided timestamps or the last post timestamps for channel view actions

@jgilliam17 can you test that changing channels marks them unread correctly still and that manually marking channels as unread still works as expected?

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @jwilander 
Tested manually, waiting for e2e report before approving. 
- Verified changing channels marks them as unread; no change in manually marking channels as unread - works as expected.

**Comment by jgilliam17** [comment]
@jwilander [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/152407-9a0bebd-onprem-ent-webapp-pr-9832-mattermost/mm-ee-test9a0bebd/mochawesome.html) has more failures than master.
notable failures 
- 7 tests failed in this profile/settings section while failing to find a button - _Verify Accessibility Support in different sections in Settings and Profile Dialog_ 
- few more tests in quick switcher for also failing to find some elements.

**Comment by jwilander** [comment]
@M-ZubairAhmed is going to take this over for me since I can't find the time to get to it

**Comment by M-ZubairAhmed** [comment]
🧪 e2e test 🧪 

https://automation-dashboard.vercel.app/cycles/b81b11ad-931a-43fa-bb9f-b4dce6eec0be

**Comment by jgilliam17** [comment]
@M-ZubairAhmed the quick switcher test are [still failing](https://mattermost-cypress-report.s3.amazonaws.com/170303-dd18bdd-onprem-ent-webapp-pr-9832-mattermost/mm-ee-testdd18bdd/mochawesome.html), I marked the ones that differs from [master](https://mattermost-cypress-report.s3.amazonaws.com/170483-onprem-ent-master-mm-ee-test:test/mochawesome.html). Can you please take a look  🔍 . Thanks 
Screen Shot 2022-03-17 at 1 15 18 PM

**Comment by M-ZubairAhmed** [comment]
reopened in https://github.com/mattermost/mattermost-webapp/pull/10828

**Pull request closed without merging**
