### PR TITLE
MM-18905 : Remove unused status flags in Jobs request state object

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

Remove unused status flags in Jobs request state object

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/12517
Fixes https://mattermost.atlassian.net/browse/MM-18905

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
This is great. feel so good to remove code doesnt it ;)

**Review by nevyangelova — APPROVED** [review]
LGTM, although i would be curious how we can test this correctly

**Review by m1lt0n — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
> LGTM, although i would be curious how we can test this correctly

e2e should be able to cover these

**Review by jgilliam17 — APPROVED** [review]
Thanks @KuSh 
Tested, looks good to merge
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/249048-f904c8f-onprem-ent-webapp-pr-11295-mm-ee-test:f904c8f/mochawesome.html)- no PR related failures.

**Pull request merged**
