### PR TITLE
Don't scroll RHS when emoji picker is open

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Fixes a UI bug causing an e2e test to fail, because RHS was scrollable when emoji picker was open 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38689
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Tested, looks good to merge - pending e2es
Verified RHS doesn't scroll when emoji picker is open.

**Review by jgilliam17 — APPROVED** [review]

**Comment by jgilliam17** [comment]
re-running e2es, last cycle failed to start

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by jgilliam17** [comment]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/224768-6ff7cf5-onprem-ent-webapp-pr-10864-mattermost/mm-ee-test6ff7cf5/mochawesome.html) - no PR related failures

**Review by devinbinnie — APPROVED** [review]

**Pull request merged**
