### PR TITLE
[GH-9502] Add a red dot to browser favicon when there are unread mentions

### PR DESCRIPTION
**Pull request by larkox**
#### Summary

Add a red dot to browser favicon when there are unread mentions

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/9502
#### Related Pull Requests

Original Pull Request: https://github.com/mattermost/mattermost-webapp/pull/2926/files

#### Screenshots

None

### CODE REVIEW

**Comment by larkox** [comment]
I just copied @jkl5616 PR and added the browser check. All merit should go to @jkl5616 .

**Comment by larkox** [comment]
Hi @adamjclarkson ! I just watched the videos and they seem coherent with the mention count on the left-hand sidebar. Would that also need to be changed?

Also, it seems this only happens on private conversations. Am I right?

**Comment by adamjclarkson** [comment]
> @adamjclarkson That looks like it would be an existing issue. That's likely due to some weirdness with how the web app stores unread state for the current channel versus other channels.

Right, agree. It was an issue with both DM and channel messages but is a LHS issue not red dot which is working correctly.  I'll approve.

**Comment by ogi-m** [comment]
The red dot is shown for unread messages in Edge.
Is this expected or should it only be shown in Chrome and Firefox?

Screenshot (226)

**Comment by larkox** [comment]
@ogi-m As far as I know, it should no be happening, and the definition of the issue explicitly says that it should not. I will review the code to see where the error might be and see if I can solve it.

Thank you very much!

**Comment by larkox** [comment]
@ogi-m This should be solved with the latest commit. Please let me know if you find any other problem.

**Comment by cpanato** [comment]
terminating the test server for some cluster maintenance, if the test server is still needed, please label again :)

**Comment by adamjclarkson** [comment]
Hey @ogi-m were you able to re-test? Can we approve it?

cc @esethna

**Pull request merged**
