### PR TITLE
[GH-6123] Add " v New messages below" indicator to the right-hand-side

### PR DESCRIPTION
**Pull request by larkox**
#### Summary

Add " v New messages below" indicator to the right-hand-side
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/6123
#### Related Pull Requests

None
#### Screenshots

None

### CODE REVIEW

**Comment by adamjclarkson** [comment]
Having trouble getting a test server spun up for this. @larkox or @jasonblais any ideas?

**Comment by jasonblais** [comment]
@metanerd possibly an issue with the build system? I also noticed `/update-branch` nor `/check-cla` worked in https://github.com/mattermost/mattermost-webapp/pull/4504

**Comment by adamjclarkson** [comment]
@metanerd, @jasonblais, @larkox anything we can do to get a test server going so i can review?

**Comment by jasonblais** [comment]
@adamjclarkson looks like it's working now

**Comment by jasonblais** [comment]
Or maybe not. @metanerd / @jaydeland is one of you able to take a look when you have a chance?

**Comment by cpanato** [comment]
sorry for any inconvenience, we are fixing that soon

**Comment by jasonblais** [comment]
Thank you! @adamjclarkson on above ^

**Comment by adamjclarkson** [comment]
I can't tell what the expected functionality is from this or past Jira ticket (https://mattermost.atlassian.net/browse/MM-5857) 

I'm looking for a 'new messages below' message in the right hand sidebar, but I'm only getting one in the center channel. Instead when I'm scrolled up in the RHS and a new message is added I am auto-scrolled to the bottom / most recent message.

https://recordit.co/HdRNtZkUvt

**Comment by larkox** [comment]
@adamjclarkson I did not know it scrolls directly to the bottom. The test I have been doing is with another user typing while I was on the screen (using e2e tests). Maybe with a message long enough (or many messages) it scrolls only to the first one and you can see the rest, instead of scrolling to the bottom?

**Comment by larkox** [comment]
@sudheerDev has been working on several changes that may or may not make this ticket obsolete. Until these changes are clear, we should put this PR on hold.

**Comment by adamjclarkson** [comment]
cc @esethna

**Comment by jasonblais** [comment]
@adamjclarkson @esethna is there a next step for this PR or should we put this on hold?

Adam - on your note
> Instead when I'm scrolled up in the RHS and a new message is added I am auto-scrolled to the bottom / most recent message.

I actually reported that behaviour as a bug for the Apps team: https://mattermost.atlassian.net/browse/MM-22042

**Comment by cpanato** [comment]
will remove this test server since this PR is stale

**Comment by jasonblais** [comment]
@adamjclarkson / @esethna kind reminder to help with PM review for this PR :)

**Comment by larkox** [comment]
To give more context, as far as I know, the "v New messages below" indicator has been changed for a Toast. Therefore, this PR as it is would no longer be needed. Maybe it could be changed to adding the toast to the RHS, but I am not sure if this Toast is completely in place already.

**Comment by esethna** [comment]
Propose we close this PR given we have the new toast behaviour and likely some changes to RHS behaviour coming with the threading overhaul (designs in progress).

**Pull request closed without merging**
