### PR TITLE
Cypress/E2E: Fix failed tests

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix failed tests

Screen Shot 2021-08-23 at 1 26 02 PM
Screen Shot 2021-08-23 at 7 46 09 PM
* Note: `MM-T3349_6` is a known valid bug https://mattermost.atlassian.net/browse/MM-38076

Screen Shot 2021-08-23 at 12 53 27 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — COMMENTED** [review]
@saturninoabril Is the `MM-T3349_6` failure expected?

**Comment by saturninoabril** [comment]
Yes, it's a known product bug (https://mattermost.atlassian.net/browse/MM-38076) which I missed to mention. I've updated the description. Thanks for checking.

**Review by furqanmlk — COMMENTED** [review]
All test case passed except one
image
image
image

**Comment by saturninoabril** [comment]
Thanks for checking Malik! It's due to the recent change of port in local inbucket. Should be good now. Please take a look again.
Screen Shot 2021-08-25 at 5 32 55 AM

**Comment by saturninoabril** [comment]
Btw, updated fix to channel menu since https://github.com/mattermost/mattermost-webapp/pull/8677 was recently reverted.
Screen Shot 2021-08-25 at 5 41 27 AM

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril  LGTM
image
image

**Pull request merged**
