### PR TITLE
E2E: Update post list content ID

### PR DESCRIPTION
**Pull request by thekiiingbob**
#### Summary
Update a ID for virtualized post list content to not collide with one we use for cypress e2e testinge.

#### Ticket Link
N/A

### CODE REVIEW

**Comment by thekiiingbob** [comment]
@sudheerDev Updating this ID, any impact for scrolling things if we do so?

**Comment by sudheerDev** [comment]
> @sudheerDev Updating this ID, any impact for scrolling things if we do so?

Nope all good.

**Comment by sudheerDev** [comment]
@thekiiingbob We have the same ID `postListContent `  for IE11 in pist_list_ie.jsx but we are fine for now and we will be deleting that file for 5.16v as well.

**Comment by thekiiingbob** [comment]
@sudheerDev yeah, not an issue for Cypress as we can only run in chrome. Thanks!

**Pull request merged**
