### PR TITLE
[MM-37616] Self-managed: Update email template to new branding - Welcome and Verification email

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR updates the welcome and verify email templates to new branding

Screenshot 2021-08-09 at 10 15 46

-----

Screenshot 2021-08-09 at 10 14 10

#### Ticket Link
[MM-37616](https://mattermost.atlassian.net/browse/MM-37616?atlOrigin=eyJpIjoiZGM4Mjc4M2U0NGU1NDdlYWJmOWU1YzJmZTMzZTViNzYiLCJwIjoiaiJ9)

#### Related Pull Requests
- Has server changes https://github.com/mattermost/mattermost-server/pull/18076

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]
LGTM!

**Review by neallred — APPROVED** [review]
Nice! Could we also remove the old `images/welcome_illustration.png` file in this PR? I imagine this and the server PR can both merge at the same time so there shouldn't be issues of an old version of server trying to read from a more up to date version of webapp that no longer has the old image. And I didn't see any lingering uses of the old image in webapp or in server.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
I'm not sure which PR to comment on here, so I will comment on both. 

I can only review based on the screenshots, but it looks like some changes still need to be updated:
- The headline font is now Metropolis in the emails
- The button/link color is now #1C58D9
- The logo color has been updated to #3F4350 as well
- Text color is now #3F4350

Also, is there a way test emails could be sent to me for closer UI review?

**Comment by AGMETEOR** [comment]
> I'm not sure which PR to comment on here, so I will comment on both.
> 
> I can only review based on the screenshots, but it looks like some changes still need to be updated:
> 
> * The headline font is now Metropolis in the emails
> * The button/link color is now #1C58D9
> * The logo color has been updated to #3F4350 as well
> * Text color is now #3F4350
> 
> Also, is there a way test emails could be sent to me for closer UI review?

@matthewbirtch I have updated the colors. The only issue is the Metropolis font. I can't seem to find a CDN that serves it. Even google fonts doesn't have it. Take a look at the updated screen shots in the PR description.

**Comment by AGMETEOR** [comment]
> Nice! Could we also remove the old `images/welcome_illustration.png` file in this PR? I imagine this and the server PR can both merge at the same time so there shouldn't be issues of an old version of server trying to read from a more up to date version of webapp that no longer has the old image. And I didn't see any lingering uses of the old image in webapp or in server.

Thanks @neallred . I took out the old image.

**Comment by matthewbirtch** [comment]
> @matthewbirtch I have updated the colors. The only issue is the Metropolis font. I can't seem to find a CDN that serves it. Even google fonts doesn't have it. Take a look at the updated screen shots in the PR description.

Ok, I wondered about that. I don't think we use a CDN for Metropolis in the webapp, so maybe it's not any option. Or maybe in the email we can point to the same version of the webfont used in the webapp somehow?

**Comment by AGMETEOR** [comment]
> > @matthewbirtch I have updated the colors. The only issue is the Metropolis font. I can't seem to find a CDN that serves it. Even google fonts doesn't have it. Take a look at the updated screen shots in the PR description.
> 
> Ok, I wondered about that. I don't think we use a CDN for Metropolis in the webapp, so maybe it's not any option. Or maybe in the email we can point to the same version of the webfont used in the webapp somehow?

In the webapp, they Metropolis font files are within the fonts folder in the repository.

**Review by neallred — APPROVED** [review]

**Comment by AGMETEOR** [comment]
Hello @matthewbirtch . I have updated the logo to the one you sent me. Dm'ed you the result. Doesn't seem different

**Review by matthewbirtch — APPROVED** [review]
@AGMETEOR the right image is there, so I'm not sure why it's displaying fuzzy still. Maybe a cache thing? Because the right image is in there, I think it should be good to go.

Still would be good to review the emails from my actual inbox (as end users will see them) - let me know if we find a solution for this

**Comment by AGMETEOR** [comment]
> @AGMETEOR the right image is there, so I'm not sure why it's displaying fuzzy still. Maybe a cache thing? Because the right image is in there, I think it should be good to go.
> 
> Still would be good to review the emails from my actual inbox (as end users will see them) - let me know if we find a solution for this

Alright.

**Pull request merged**
