### PR TITLE
Revert "[MM-34187] - Update React version to 17* (#10739)"

### PR DESCRIPTION
**Pull request by neallred**
This reverts commit 8ca0eeefcc8131aec58ddaad11361a3935bedc46.
=
#### Summary
Revert upgrade to React 17 while we figure out how to sort out the issue with the OverlayTrigger and its dependency on our custom react-bootstrap. Context: https://community.mattermost.com/core/pl/s17rz67icp8r3ndorsuxh3zjaw

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34187

#### Screenshots
TBD

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by marianunez — APPROVED** [review]
Can we verify if this PR we reverted is in the `cloud` branch? If so, this needs to be cherry picked for next cloud release

**Comment by neallred** [comment]
Will check and cherry-pick if need be. My guess is no, because it was recent.

**Comment by neallred** [comment]
Confirmed it is not in the cloud branch, so no need to cherry-pick.

**Pull request merged**
