### PR TITLE
MM-40607 Remove broken autofocus from mobile search box

### PR DESCRIPTION
**Pull request by hmhealey**
A few years ago, we had [a ticket to autofocus the search box when the search view was opened on mobile](https://github.com/mattermost/mattermost-server/issues/5266). [That was added](https://github.com/mattermost/mattermost-server/pull/5284) and then proceeded to get broken at some point so that it hasn't worked properly in some time. Despite not working, the leftover code has caused at least a few regressions since then including the one that this ticket was intended to fix.

Since this hasn't worked in such a long time, I feel like removing the remaining code is our best bet unless someone wants to go re-add it in a way that doesn't cause so many issues.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40607

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
LGTM

**Review by michelengelen — APPROVED** [review]
LGTM

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
- Verified search textbox autofocus has been removed when transitioning from mobile to standard browser view.
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/102917-8a3cb25-onprem-ent-webapp-pr-9539-mattermost/mm-ee-test8a3cb25/mochawesome.html) looks good, no PR related failures.

**Pull request merged**
