### PR TITLE
[MM-41970] Should not have the ability to edit/archive ldap groups

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Hiding the option to archive a group in the user groups list

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41970

#### Release Note

```release-note
Hiding the archive group option from the group sub menu for ldap groups
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by mylonsuren — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
LGTM

**Before**
image

**After**
image

**Pull request merged**
