### PR TITLE
[MM-32269] System Console: TeamIcon edge cases

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary

- Fix: edge cases of TeamIcon in System Console.
- Size 'md' is effectively gone in CSS styling; removing it as an option and default is now `sm`.

Areas affected: 
- System Console > User Management > Teams
- System Console > User Management > Teams > Edit Team
- System Console > User Management > Groups > …(Linked Group, Configure)… > Add Team 

Text- and image-based team icons in LHS visually unaffected, but code changes affect them, so LHS team icons need to be verified.

#### Ticket Link

- Fixes https://mattermost.atlassian.net/browse/MM-32269

#### Screenshots
System Console > User Management > Teams (after)
CleanShot 2021-01-25 at 16 16 26@2x

System Console > User Management -> Teams > Edit Team (before and after)
CleanShot 2021-01-25 at 15 32 33@2x
CleanShot 2021-01-25 at 15 52 18@2x

System Console > User Management > Groups > …(Linked Group)… > Add Team (after)
CleanShot 2021-01-25 at 16 24 40@2x

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @calebroseland 

1. I spun up a test server with CWS - not sure if there is a difference to what you tested on but I am still seeing the alignment issue on the Teams page:

image

2. On the Edit Team page, I'm seeing a weird square when I hover over the team icon

image

3. It also seems like the letters in the icon are not centered within the icon

image

4. **Fixed**: System Console > User Management > Groups > …(Linked Group)… > Add Team

image

**Comment by nevyangelova** [comment]
@calebroseland the before elements casting the shadow will be effectively removed once https://github.com/mattermost/mattermost-webapp/pull/7389 is merged so you can revert the CSS changes as now we will be adding the correct theme variable for the border of the element itself :)

**Review by nevyangelova — CHANGES_REQUESTED** [review]
we can revert the css changes otherwise LGTM!

**Comment by calebroseland** [comment]
@migbot sure, that's no problem

**Comment by lindy65** [comment]
Hi @calebroseland - Cloud Eng helped spin up a test server but I am seeing the same issues I reported above on this new test server.  Do you still need to do some work before I review?

**Comment by calebroseland** [comment]
@lindy65 I'm not sure why the test servers aren't showing it, the code is correct and working fine locally. I wonder if there is a repo-sync issue. I'll try creating a test server against a separate branch and see if that works.

@nevyangelova thanks for sharing the related PR! Could we remove the `:before` parts of this in the eventual merge conflict in the other PR? If this one gets included with 5.32 as slated, I believe the `:before` parts would need to still be there.

**Comment by lindy65** [comment]
Thanks @calebroseland - I'm not sure why the fixes are showing up on the test server either :(

**Comment by nevyangelova** [comment]
@calebroseland seems like more discussions are needed for the PR I linked to be merged so you can go ahead with these changes, and I will rebase with master after and fix any conflicts.

**Review by nevyangelova — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by calebroseland** [comment]
@angeloskyratzakos could you help with the test server not reflecting any changes? Is there a way to clear a cache or something?

**Review by lindy65 — APPROVED** [review]
Thanks @calebroseland - looks good to me now :+1

**Pull request merged**
