### PR TITLE
[MM-44691] Adding gender neutral doctor-emoji

### PR DESCRIPTION
**Pull request by Haliax**
#### Summary

Adding a gender neutral doctor emoji.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/20318

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/20578

#### Screenshots

There are no UI changes.
The gender neutral 🧑‍⚕️ already existed.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by Willyfrog — COMMENTED** [review]
Looks good, but this needs to be added to the server as well (basically running the script and let it appear in the server emoji.go file) so it can be handled by the server as well

**Review by Willyfrog — APPROVED** [review]
disregard, I just noticed the other PR which didn't have any reviewers

**Review by M-ZubairAhmed — APPROVED** [review]
I just tested it with the server changes pr. it works correctly

**Review by jgilliam17 — APPROVED** [review]
Thanks @Haliax 
Tested, looks good to merge.
- Verified gender neutral emoji
- [E2E report](https://automation-dashboard.vercel.app/cycles/f5b9a0ca-f2f5-4346-abee-84cdb9095122) - no PR related failures.

**Pull request merged**
