### PR TITLE
MM-47113 : Migrate "components/interactive_dialog/interactive_dialog.jsx" to Typescript

### PR DESCRIPTION
**Pull request by babinderrathi**
#### Summary
Migration of interactive_dialog.jsx file to tsx 

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/21057

  Fixes https://mattermost.atlassian.net/browse/MM-47113

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note
```release-note

Migration of interactive_dialog.jsx file to tsx 

```

### CODE REVIEW

**Review by michelengelen — CHANGES_REQUESTED** [review]
There are generally a high number of values being typed as either `unknown` or `any`. Please type type the component as strictly as possible. 

If you need advice/help please feel free to reach out to either me or @hmhealey ... we are happy to help to get this migration going!

**Comment by michelengelen** [comment]
hey @babinderrathi is there anything we can help with here?

**Comment by M-ZubairAhmed** [comment]
@babinderrathi hey do you plan to complete this one. i see its almost completed :)

**Comment by babinderrathi** [comment]
Yes, I am working on this.

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
