### PR TITLE
[MM 13714] Migrates 'components/backstage' and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by mitchellroe**
#### Summary

Migrates `components/backstage` and associated tests to TypeScript.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13714

#### Related Pull Requests

None

#### Screenshots

None

### CODE REVIEW

**Comment by mitchellroe** [comment]
I have completed the transition, as far as I know. I would love some feedback.

**Comment by mitchellroe** [comment]
> I have completed the transition, as far as I know. I would love some feedback. First time contributing here.

Never mind. I've found some issues I need to resolve.

**Comment by jasonblais** [comment]
@mitchellroe terribly sorry for the late response to review this PR. I've just queued it for dev review. Really appreciate your contribution!

Don't hesitate to reach out with any questions - and again, deepest apologies. 

(We've re-implemented `mattermod` reminders such as the one [above](https://github.com/mattermost/mattermost-webapp/pull/5703#issuecomment-667443085), which helps identify stale PRs in future)

**Comment by calebroseland** [comment]
Hey @mitchellroe, thanks for your contribution on this! Looks like you got the first two points taken care of, but there's still some type errors/conversions to work though. 

> - Fix any errors generated by the TypeScript compiler. You can run make check-types to display any errors.

Feel free to reach out on https://community.mattermost.com/; happy to jump on a chat/call if you need anything!

**Comment by mitchellroe** [comment]
> Hey @mitchellroe, thanks for your contribution on this! Looks like you got the first two points taken care of, but there's still some type errors/conversions to work though.
> 
> > * Fix any errors generated by the TypeScript compiler. You can run make check-types to display any errors.
> 
> Feel free to reach out on https://community.mattermost.com/; happy to jump on a chat/call if you need anything!

Thank you, @calebroseland. Yeah, I've been meaning to jump back in on this. I'll fix those errors soon and update here. I should have them resolved by the end of the week.

**Comment by mitchellroe** [comment]
Hey, y'all. Sorry for the total lack of movement on this. I'm feeling more out of my element than I thought I would. I'm reaching out for help in the Mattermost Community. Thanks for your patience.

**Comment by jasonblais** [comment]
@mitchellroe Thank you for the heads up! Really appreciate your help :)

**Comment by jasonblais** [comment]
@mitchellroe Hey, just touching base if you got help in the Mattermost Community? We're happy to help :)

**Comment by mitchellroe** [comment]
Thanks, @jasonblais. Things have been busier lately than usual. Sorry for the delay. I'm submitting some more request for help in the MM community (a TS newb).

**Comment by mitchellroe** [comment]
Thank you so much for your help, @calebroseland, in community.mattermost.com. Am I on the right track with my previous commit?

**Comment by jasonblais** [comment]
@calebroseland kind reminder to help review if @mitchellroe is going in the right direction :)

**Comment by jfrerich** [comment]
Hi @mitchellroe, can you please fix the merge conflicts?

**Comment by mitchellroe** [comment]
I'm not sure why GitHub still shows there being merge conflicts. I encountered one in my most recent merge of master into my feature branch, but I resolved it and pushed the update. In my local environment, a merge of my branch into master results in a FF (this was after resetting both my master and feature branches to what is represented in GitHub with `git reset --hard`).

```
➜  mattermost-webapp git:(master) git remote -v                                                                 
fork	git@github.com:mitchellroe/mattermost-webapp.git (fetch)
fork	git@github.com:mitchellroe/mattermost-webapp.git (push)
upstream	https://github.com/mattermost/mattermost-webapp.git (fetch)
upstream	https://github.com/mattermost/mattermost-webapp.git (push)
➜  mattermost-webapp git:(master) git fetch --all --prune
Fetching fork
Fetching upstream
➜  mattermost-webapp git:(master) git reset --hard upstream/master
HEAD is now at 511b8914d MM-28266:  Cypress/E2E: Automate backlogs - Messaging > Edit (11 test cases) (#6838)
➜  mattermost-webapp git:(master) git merge fork/MM-13714-typescript-components_backstage 
Updating 511b8914d..0a1bc5c47
Fast-forward
 components/backstage/{backstage_controller.jsx => backstage_controller.tsx}                                      |  2 +-
 components/backstage/components/__snapshots__/{backstage_header.test.jsx.snap => backstage_header.test.tsx.snap} |  0
 components/backstage/components/{backstage_category.jsx => backstage_category.tsx}                               | 12 ++++++++++--
 components/backstage/components/{backstage_header.test.jsx => backstage_header.test.tsx}                         |  2 +-
 components/backstage/components/{backstage_header.jsx => backstage_header.tsx}                                   |  0
 components/backstage/components/{backstage_list.jsx => backstage_list.tsx}                                       |  2 +-
 components/backstage/components/{backstage_navbar.jsx => backstage_navbar.tsx}                                   |  0
 components/backstage/components/{backstage_section.jsx => backstage_section.tsx}                                 |  0
 components/backstage/components/{backstage_sidebar.test.jsx => backstage_sidebar.test.tsx}                       |  4 ++--
 components/backstage/components/{backstage_sidebar.jsx => backstage_sidebar.tsx}                                 |  4 ++--
 components/backstage/{index.js => index.ts}                                                                      |  6 ++++--
 components/emoji/add_emoji/add_emoji.tsx                                                                         |  2 +-
 components/integrations/abstract_command.jsx                                                                     |  2 +-
 components/integrations/abstract_incoming_webhook.jsx                                                            |  2 +-
 components/integrations/abstract_oauth_app.jsx                                                                   |  2 +-
 components/integrations/abstract_outgoing_webhook.jsx                                                            |  2 +-
 components/integrations/bots/add_bot/add_bot.jsx                                                                 |  2 +-
 components/integrations/bots/bots.jsx                                                                            |  2 +-
 components/integrations/confirm_integration/confirm_integration.jsx                                              |  2 +-
 components/integrations/installed_commands/installed_commands.jsx                                                |  2 +-
 components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.jsx                              |  2 +-
 components/integrations/installed_oauth_apps/installed_oauth_apps.jsx                                            |  2 +-
 components/integrations/installed_oauth_apps/installed_oauth_apps.test.jsx                                       |  2 +-
 components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.jsx                              |  2 +-
 24 files changed, 34 insertions(+), 24 deletions(-)
 rename components/backstage/{backstage_controller.jsx => backstage_controller.tsx} (99%)
 rename components/backstage/components/__snapshots__/{backstage_header.test.jsx.snap => backstage_header.test.tsx.snap} (100%)
 rename components/backstage/components/{backstage_category.jsx => backstage_category.tsx} (91%)
 rename components/backstage/components/{backstage_header.test.jsx => backstage_header.test.tsx} (97%)
 rename components/backstage/components/{backstage_header.jsx => backstage_header.tsx} (100%)
 rename components/backstage/components/{backstage_list.jsx => backstage_list.tsx} (99%)
 rename components/backstage/components/{backstage_navbar.jsx => backstage_navbar.tsx} (100%)
 rename components/backstage/components/{backstage_section.jsx => backstage_section.tsx} (100%)
 rename components/backstage/components/{backstage_sidebar.test.jsx => backstage_sidebar.test.tsx} (98%)
 rename components/backstage/components/{backstage_sidebar.jsx => backstage_sidebar.tsx} (98%)
 rename components/backstage/{index.js => index.ts} (94%)
➜  mattermost-webapp git:(master) 
```

**Comment by mitchellroe** [comment]
Sorry to do this, but I don't think I can commit my time to working on this right now. I will mention this in the issue as well. Thank you for all your help along the way.

**Pull request closed without merging**
