### PR TITLE
Loading svg animation for post image load

### PR DESCRIPTION
**Pull request by niklabh**
#### Summary

Loading svg animation on image load
Screenshot from 2019-09-17 13-55-42

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/11998

### CODE REVIEW

**Comment by niklabh** [comment]
To test use /giphy plugin and try command:
```
/giphy hello
```

**Comment by niklabh** [comment]
Giphy plugin is failed to start on test server. Can anyone check logs.
Screenshot from 2019-09-17 16-38-05

**Comment by mickmister** [comment]
@niklabh You can access the logs from the System Console in the Reporting > Server Logs tab. Here is the log message being printed:

```
Unrecognized remote plugin message:
This usually means that the plugin is either invalid or simply needs to be recompiled to support the latest protocol.
```

I recompiled and reuploaded the plugin, it's working now.

**Comment by hanzei** [comment]
@esethna Gentle reminder to review this

**Comment by mickmister** [comment]
Something to note: Running `/giphy (search)` shows the svg while loading the gif, but pressing "Shuffle" continues to show the old gif until the new one has been fetched.

**Comment by jasonblais** [comment]
Hi @niklabh, thanks for your contribution! Would you have any questions about the feedback from `hmhealey` above? We'd be happy to help clarify if needed

**Pull request closed without merging**
