### PR TITLE
display fullname in channel switcher suggestions

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Adds change to display fullname in channel switcher (CMD + K)

Cc @dmeza 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by dmeza** [comment]
@esethna rebased to latest and made the changes requested.
fullnameonchannelswitcher

**Comment by jasonblais** [comment]
@dmeza @esethna Sorry to jump in here. What is the purpose of this change? We already display username/full_name/nickname in the channel switcher

image

Is it to display the full name first, before the username?

**Comment by dmeza** [comment]
@jasonblais thanks for jumping into the discussion. This is a change that was there before there was a full name in the channel switcher. If you don't agree with the re-order please close it.

**Comment by jasonblais** [comment]
Ah, good point @dmeza. I think full name was added later. Thanks for the context.

I'll let @esethna make the call on ordering, but I think the existing order in the switcher is consistent with other autocompletes.

**Comment by esethna** [comment]
@dmeza If you are okay with the order as it is now ["username - full_name (nickname)"] let's close this, since as Jason mentions, it's more consistent with other autocompletes. I can see there being benefit to reordering the names if we based it on the selected config and [account setting options for teammate name display](https://github.com/mattermost/mattermost-webapp/pull/289), but I'm not sure that's worth it at this point.

**Pull request closed without merging**
