### PR TITLE
MM-27312 Allow uploading 10 files per post

### PR DESCRIPTION
**Pull request by DigasNikas**
#### Summary
Increase the amount of files allowed per post, from 5 to 10.

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/15645
  Jira: https://mattermost.atlassian.net/browse/MM-27312

#### Related Pull Requests
- Has server changes (https://github.com/mattermost/mattermost-server/pull/16235)

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @DigasNikas, can you confirm that the error messages that appear when trying to upload > 10 files are updated accordingly?

**Review by hmhealey — APPROVED** [review]

**Comment by DigasNikas** [comment]
@esethna The test server allowed me to test it and seems to work as expected.
image

**Review by esethna — APPROVED** [review]
Thanks! @DigasNikas are you open to also contributing this on the mobile app to maintain consistency? https://github.com/mattermost/mattermost-mobile

**Comment by DigasNikas** [comment]
@esethna just created the following PR in mobile: https://github.com/mattermost/mattermost-mobile/pull/5028

**Review by saturninoabril — COMMENTED** [review]
Thanks @DigasNikas! We have 2 existing test cases affected by this change. I wonder if you're open to submit a Cypress tests for [MM-T2265](https://automation-test-cases.vercel.app/test/MM-T2265) and [MM-T2266](https://automation-test-cases.vercel.app/test/MM-T2266) (not that both are yet to update per this change). Can be here or in a separate PR. Please let me know if you're interested.

**Comment by DigasNikas** [comment]
@saturninoabril my experience with cypress is very short. The task would require from me more effort than what I can really offer right now. I must pass :(

**Comment by saturninoabril** [comment]
No worries. We'll take care of it. Thank you for your contribution @DigasNikas!

**Pull request merged**
