### PR TITLE
MM-34005 Cypress/E2E: Fix for OAuth

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Tests failed in CI due to unaccessible endpoints from webhook server related to OAuth app.
- fixed by setting up base URLs and credentials on demand via `[webhook_url]/setup` and not thru `process.env` so it's easily configurable, especially when running test in CI. Done thru `cy.requireWebhookServer()`
- added `Dockerfile.webhook`, typically used in CI.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34005

#### Screenshots
Screen Shot 2021-04-12 at 8 18 40 AM

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by josephbaylon — CHANGES_REQUESTED** [review]
@saturninoabril Not sure if it has something to do with your changes but I'm getting 4 failures of similar nature (see images below)

Screen Shot 2021-04-12 at 7 14 29 AM
Screen Shot 2021-04-12 at 7 13 02 AM
Screen Shot 2021-04-12 at 7 13 20 AM
Screen Shot 2021-04-12 at 7 13 39 AM
Screen Shot 2021-04-12 at 7 14 16 AM

**Comment by saturninoabril** [comment]
Did you set `chromeWebSecurity` to false? Can be by `export CYPRESS_chromeWebSecurity=false`.

**Review by josephbaylon — APPROVED** [review]
LGTM. @saturninoabril You might need to get the latest from master to fix the broken unit test.

Screen Shot 2021-04-12 at 7 27 14 AM

**Comment by saturninoabril** [comment]
Awesome, thanks Joseph!

**Review by prapti — APPROVED** [review]
Looks good. The tests don't always pass 100% but it seems flaky due to the environment setting for chromeWebSecurity. They did pass for 80% of the runs I tried.
Approving.

**Comment by saturninoabril** [comment]
Thanks Prapti! Will keep an eye on it.

**Pull request merged**
