### PR TITLE
Fixed post pasteHandler not saving drafts

### PR DESCRIPTION
**Pull request by EricssonLiu**
#### Summary
This ticket fixes a bug in which drafts are not saved after a paste that goes through the pasteHandler in the post textbox is processed (tables and hyperlinks, currently).

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47681

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @EricssonLiu!

**Review by AshishDhama — APPROVED** [review]
LGTM

**Review by mylonsuren — APPROVED** [review]
🚀

**Comment by jgilliam17** [comment]
Thanks @EricssonLiu 
Tested, looks good to merge.
Verified drafts are saved when pasting tables or hyperlinks.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/261030-bb246f7-onprem-ent-webapp-pr-11491-mm-ee-test:bb246f7/mochawesome.html) - no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
