### PR TITLE
fix product switcher tip position

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
This fixes the position of the product switcher tip, which was inadvertently moved as part of other global header work. Deferring QA because of test environment difficulties.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37472

#### Related Pull Requests
None

#### Screenshots
reposition-tutorial-dot

#### Release Note
None because this is a fix for a feature addition that has not been released yet.
```release-note
NONE
```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]
LGTM! nice work! :shipit:

**Review by marianunez — APPROVED** [review]

**Comment by neallred** [comment]
Was able to download the newly released playbooks/boards plugins and do more robust local testing. Found that the old `useShowTutorialStep` was breaking the rules of hooks when it skipped the step because boards or playbooks was missing. So I converted it to a class component and made `useShowTutorialStep` a lot simpler to just have what the settings tip needs. I think the unit tests cover the skip and render logic thoroughly, and manual testing on my local machine with different configurations of  boards and playbooks seems solid.

**Review by marianunez — APPROVED** [review]
Great work @neallred! Much simpler and great test coverage 🎉

**Comment by marianunez** [comment]
We just need to make the linter happy :)

**Review by pablovelezvidal — APPROVED** [review]
LGTM! Great work @neallred!

**Review by AGMETEOR — APPROVED** [review]
LGTM! Thanks @neallred

**Pull request merged**
