### PR TITLE
Fix incorrect link handling of inline MD images

### PR DESCRIPTION
**Pull request by abdusabri**
#### Summary
As of [MM-12898](https://github.com/mattermost/mattermost-webapp/pull/3639), inline markdown images open the image preview modal, except if the markdown image itself is a link. e.g. `[Build Status](https://travis-ci.org/mattermost/platform)`.

**This PR fixes the following bug:**

For a case like `image an image plus some text that has [a link](http://somelink)`

**Observed behavior:** The image doesn't have a pointer cursor, and doesn't open the preview modal

**Expected behavior:** The image should have a pointer cursor and open the preview modal

**Reason of wrong behavior:** just because there is a link (`[a link](http://somelink)`) in the markdown, it falsely assumed that the image itself is actually a link - which is not the case in the example given above

The bug is not a regression, it is a missed case since the implementation of [MM-12898](https://github.com/mattermost/mattermost-webapp/pull/3639), but was only discovered after [MM-15232, MM-18158](https://github.com/mattermost/mattermost-webapp/pull/3877). The issue can be reproduced on community V5.18 and latest master. The bug is not limited to channel header descriptions or its associated system messages, and can be reproduced in regular chat messages as well.

#### Ticket Link
Not created yet (Sudheer will create it)

#### Screenshots
**Before the fix**
image

**After the fix**
image

[MM-15232]: https://mattermost.atlassian.net/browse/MM-15232

### CODE REVIEW

**Comment by amyblais** [comment]
This can be cherry-picked to v5.19 as long as it's not risky. @sudheerDev

**Comment by sudheerDev** [comment]
@amyblais will manually cherrypick

**Pull request merged**
