### PR TITLE
run pngquant on frequenly used logos and icons

### PR DESCRIPTION
**Pull request by tayre**
#### Summary
I was looking around the the webapp to get an idea of the project structure. 
In doing so, I noticed a lot of the .pngs in use were quite large. I ran some of the frequently used images through [libimagequant](https://pngquant.org/). There should be no appreciable visual change. If this PR is accepted, I'll optimize the remaining pngs. 

#### Original
```
-----   ------------
Bytes   File
-----   ------------
16591   icon50x50.png
6576    icon64x64.png
22799   icon_WS.png
18160   logo_compact.png
21529   logo-email.png
25177   logo.png
20570   logoWhite.png
```
##### Optimized
```
Bytes   File
-----   ------------
1434    icon50x50.png
2368    icon64x64.png
10608   icon_WS.png
3056    logo_compact.png
4077    logo-email.png
5766    logo.png
3206    logoWhite.png
```
##### Checklist
- [ x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by jasonblais** [comment]
@asaadmahmood Thoughts?

> There should be no appreciable visual change

Sounds fine to me.

**Comment by asaadmahmood** [comment]
Looks good to me.

**Comment by jasonblais** [comment]
thanks @tayre! This looks good

**Comment by jasonblais** [comment]
@tayre Would you be interested optimizing rest of the PNGs that we use?

Big thanks for your contribution!

**Comment by tayre** [comment]
Can do. Will create a new PR as soon as I can.

**Pull request merged**
