### PR TITLE
Migrate errorMessage string ref

### PR DESCRIPTION
**Pull request by sridhar02**
#### Summary

Migrate errorMessage string ref to new ref syntax

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/16037

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for the PR @sridhar02. Heads up that some types checks failed with :
```
components/admin_console/admin_settings.tsx:269:29 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<OverlayProps>): Overlay', gave the following error.
    Type 'HTMLDivElement | null' is not assignable to type 'Function | Element | Component<any, {}, any> | undefined'.
      Type 'null' is not assignable to type 'Function | Element | Component<any, {}, any> | undefined'.
  Overload 2 of 2, '(props: OverlayProps, context?: any): Overlay', gave the following error.
    Type 'HTMLDivElement | null' is not assignable to type 'Function | Element | Component<any, {}, any> | undefined'.
      Type 'null' is not assignable to type 'Function | Element | Component<any, {}, any> | undefined'.

269                             target={this.errorMessageRef.current}
                                ~~~~~~

  node_modules/@types/react-bootstrap/lib/Overlay.d.ts:14:9
    14         target?: Function | React.ReactInstance;
               ~~~~~~
    The expected type comes from property 'target' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Overlay> & Readonly<OverlayProps> & Readonly<...>'
  node_modules/@types/react-bootstrap/lib/Overlay.d.ts:14:9
    14         target?: Function | React.ReactInstance;
               ~~~~~~
    The expected type comes from property 'target' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Overlay> & Readonly<OverlayProps> & Readonly<...>'


Found 1 error.
```

Could you please take a look?

**Comment by jfrerich** [comment]
Hi @sridhar02, could you address the failing type checks?  Once those are fixed, I'll assign reviewers to the PR and move toward getting full reviews and merge!

**Comment by sridhar02** [comment]
@jfrerich  @hanzei  I have updated the PR and all the checks are passing, I don't know why the build is failing can you check and review the PR?

**Comment by hanzei** [comment]
@sridhar02 I've restarted CI. Let's see if that fixes the issue.

**Comment by sridhar02** [comment]
@hanzei I think it fixed the issue, You just have to remove the stale label and work in progress label then we can see about all the checks for the PR

**Review by sudheerDev — APPROVED** [review]
LGTM @sridhar02 Thank you!

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks!

**Review by jgilliam17 — APPROVED** [review]
Thank you @sridhar02 
Tested, looks good to merge.
- Verified error messages for Bleve, Elasticserch, message export, custom terms and plugin management
@Willyfrog can you please help merge? Thanks 🙂

**Pull request merged**
