### PR TITLE
Add classes for mobile dividers

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Remove specific management settings based on hardcoded configs

cc @dmeza 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
@asaadmahmood Please help review?

**Comment by asaadmahmood** [comment]
@csduarte Needs a rebase.

**Comment by dmeza** [comment]
@asaadmahmood rebased to latest from master.

**Comment by jasonblais** [comment]
@dmeza Sorry, looks like the build fails and as a result the test server doesn't build successfully. Can you try run `make check-style` and `make test` to check for errors?

**Pull request merged**
