### PR TITLE
[MM-45003] Don't emit logged in event until mfa setup is complete

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
When setting up MFA on Desktop the webapp would emit a logged in signal to the other tabs once you have entered your login credentials but it wouldn't take into account whether you had completed your MFA setup or not. That signal caused the other tabs (playbooks & boards) to think they were logged in, they would get a 401 on their requests and you would get logged out from the MFA setup page.

Adding this check means we only emit the login signal after MFA setup.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45003

#### Replication steps
Setup desktop and ensure you also have boards or playbooks tab active too.
Enable MFA and enforce on login.

1. Login using your credentials.
2. Follow the MFA setup steps

Observed: You get redirected back to the login page from the MFA setup

Expected: You can complete the MFA setup and all tabs get logged in afterwards

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working fine

**Pull request merged**
