### PR TITLE
MM-15992 - Updating search bar description

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-15992 - Updating search bar description

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-15992

### CODE REVIEW

**Comment by jespino** [comment]
@asaadmahmood needs a merge from master

**Comment by asaadmahmood** [comment]
Done @jespino

**Comment by asaadmahmood** [comment]
@enahum @jespino Can we get this in?

**Comment by jespino** [comment]
@asaadmahmood Sure! :)

**Pull request merged**
