### PR TITLE
MM-15228 consecutive bot posts maintain the profile image

### PR DESCRIPTION
**Pull request by scottleedavis**
#### Summary

This adds the profile image in consecutive bot posts.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/10681

#### Related Pull Requests
- Has mobile changes https://github.com/mattermost/mattermost-mobile/pull/2746
- Has server changes https://github.com/mattermost/mattermost-server/pull/10793

### CODE REVIEW

**Comment by scottleedavis** [comment]
@jasonblais I had neglected 'compact view'.  With Standard view they are not grouped.  
Screen Shot 2019-04-29 at 2 03 23 PM

**Comment by scottleedavis** [comment]
Though yours look different that collapsed.  The spinmint server gives me different results currently that what you got.

**Comment by jasonblais** [comment]
@scottleedavis That's odd. Mine is indeed in Standard View. Reproduces on macOS Sierra, latest Chrome version

image

**Comment by scottleedavis** [comment]
After a couple page refreshes (chrome, osx mojave) I was able to reproduce it in the spinmint server.  I am however, not currently able to reproduce the issue locally e38ac5b6.

**Comment by scottleedavis** [comment]
@hmhealey @saturninoabril This PR works locally (for me) but not on this spinmint.  Do you have a recommendation on how best to troubleshoot this?

**Comment by saturninoabril** [comment]
Thanks @scottleedavis, I'm checking...

**Comment by saturninoabril** [comment]
I posted several reminders - `/remind me testing in 1 minute` - and below were what I've got after waiting some time.  Each post has profile image which indicates that it works. 

Screen Shot 2019-04-30 at 2 56 40 PM

Could you try it again? 

Not sure if my repro steps are good enough.  Let me know if not and I'll test it again.

**Comment by jasonblais** [comment]
Hm, I'm not able to reproduce it on this new spinmint. So I'll approve the PR with the latest changes.

**Comment by jasonblais** [comment]
@saturninoabril @scottleedavis Actually, it does reproduce.

1. Install v0.1.6 of the remind bot plugin https://github.com/scottleedavis/mattermost-plugin-remind/releases/tag/v0.1.6
2. Post `/remind me testing 5sec`
3. Post `/remind me testing 5sec` again
4. Refresh the page

Observed: Consecutive posts do not have profile picture or username of the bot

image

**Comment by scottleedavis** [comment]
@saturninoabril @jasonblais 
I can confirm latest spinmint, using the test branch https://github.com/scottleedavis/mattermost-plugin-remind/tree/ephemeral-bot-posts , reproduces the results of collapsed consecutive posts.

I also confirm that using the same branch locally, works as intended.

Screen Shot 2019-04-30 at 7 31 21 AM

**Comment by scottleedavis** [comment]
@jasonblais @saturninoabril I was able to replicate the failure locally by recloning the repo and starting fresh.  

This latest commit fixes the issue for me locally, and I am hoping it will run in spinmint as well.   :)

**Comment by jasonblais** [comment]
Thanks @scottleedavis!! Looks like the build is failing, can you help take a look? I'll then generate a new spinmint to test

**Comment by jasonblais** [comment]
Thanks @scottleedavis! Consecutive posts now indeed maintain profile picture and username.

However, on page reload while the profile loads, the posts are initially collapsed, until they're separated. 

This is different from the behaviour for webhook posts, and may cause scroll pop when loading a channel:

image

I'm wondering if there is a way to maintain user profile for consecutive bot posts similar to consecutive webhook posts while the channel contents load?

**Comment by scottleedavis** [comment]
@jasonblais My attempts at optimizing the rendering of user profile for bot posts has not been fruitful so far, and I am curious how to best solve it.

**Comment by scottleedavis** [comment]
@jasonblais following your idea to render the same as a webhook bot, I followed the same pattern of using the post.props sent from server.  In doing so, the 'scroll pop' effect has gone away.  This is because the webapp no longer needs a second call to the store to pull a user object to determine 'isBot' .  This required a minimal server side change as well.  https://github.com/mattermost/mattermost-server/pull/10793

Please let me know if this solves the problem!

**Comment by jasonblais** [comment]
Great, thanks @scottleedavis! Scroll pop is now resolved based on testing I carried out.

One more question which is not directly related to this PR - would you know why the bot post username and profile picture aren't initially loaded after a page refresh, whereas they are for regular users (and also for webhook posts, as in above screenshot).

image

**Comment by scottleedavis** [comment]
@jasonblais Looking at `imageURLForUser(userIdOrObject) `
On page load for users and webhook bots, a user object object is passed, and is immediately translated into an image route.
For bots, a userId is passed, which at first pass is not found in the store and `Constants.TRANSPARENT_PIXEL` is loaded until which time the store has the bot user, and the image is rendered.  (i,e. the dot -> image transition)

For user & webhook username 'Someone' is displayed for one render cycle before switching to the correct username.  For bots it is two, which produces the noticable shift.

I noticed posts stop collapsing for normal users at commit 32d53324 (@hmhealey) after I merged in master.  Is that to be addressed in a seperate PR?

**Comment by jasonblais** [comment]
Thanks @scottleedavis! Appreciate it 

I've created two tickets: one for not loading username and profile picture immediately after page refresh, and included your investigation as part of the ticket: https://mattermost.atlassian.net/browse/MM-15433

Bug ticket for regular user posts no longer collapsing: https://mattermost.atlassian.net/browse/MM-15432

**Pull request merged**
