### PR TITLE
MM-15560 - E2E Fix: update markdown html fixtures

### PR DESCRIPTION
**Pull request by thekiiingbob**
#### Summary
- Updated fixtures for the expected HTML output of markdown for the markdown tests.

#### Ticket Link
[JIRA](https://mattermost.atlassian.net/browse/MM-15560)

To run just these tests run `npm run cypress:run -- --spec "cypress/integration/markdown/**/*.js" --reporter "spec" --browser "chrome"`

### CODE REVIEW

**Comment by thekiiingbob** [comment]
@saturninoabril Should be good now, image proxy for sure impacts this test, so making sure we have it enabled for this test.

**Comment by thekiiingbob** [comment]
@saturninoabril @migbot Latest changes pushed up. Using `cy.route` to wait for request to get posts completes before submitting any additional posts.

This should fix an issue @migbot was having.

Right now there are several tests that do the `win.fetch = null` thing (which causes requests that are fetch to fallback to XHR), which is not entirely ideal, but there is a long awaited open PR to add full network stubbing support - https://github.com/cypress-io/cypress/pull/4176 , which is scheduled after Cypress's 3.3.0 release.

**Comment by saturninoabril** [comment]
@thekiiingbob I've got test failures on "Markdown - in-line images 3 and 4" due to the pending post ID returned from `getLastPostId` (see screenshot).  I think the previous implementation of "WithRetry" is better suited than the one we have now with hard limit timeout of [30 seconds].(https://github.com/mattermost/mattermost-webapp/blob/6ac43f8302ba92932fdc91d5cde4fd0660f9adaa/cypress/support/ui_commands.js#L140) 
Screen Shot 2019-05-17 at 5 49 50 PM
Screen Shot 2019-05-17 at 5 49 08 PM

**Comment by thekiiingbob** [comment]
@saturninoabril I tested this latest code with caching disabled and under the Fast 3G network conditions, and the markdown tests pass for me. Give it a whirl under your environment and let me know if you are having issues. This should handle all the waiting we need for posts.

**Comment by saturninoabril** [comment]
Sure, will give it a test.  One thing though, the very long timeout, especially 150s seems a flaw to me. Do we have other choice?

**Comment by thekiiingbob** [comment]
@saturninoabril  Added timeouts constants file and started using it. Lemme know if the names of the consants is sufficient and clear enough, or if you had something else in mind. Image related markdown tests are now run after, with more intense timeout requirements added.

**Comment by thekiiingbob** [comment]
Also, I had to update the expected HTML for the image tests. It seems that the `alt` attribute is now before the other attributes. If this changes again soon, I'd want to alter how we are doing these tests.

**Pull request merged**
