### PR TITLE
[MM-47184] Updating statistics string to total activated users

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Replacing `Total Active Users` with `Total Activated Users`

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47184

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by coltoneshaw** [comment]
@BenCookie95 should this be changed in all the other i18n files? To keep the wording consistent.

**Comment by BenCookie95** [comment]
> @BenCookie95 should this be changed in all the other i18n files? To keep the wording consistent.

@coltoneshaw The translation team would take care of that, just need to make them aware that the string has changed

/cc @cwarnermm

**Review by coltoneshaw — APPROVED** [review]
LGTM!

**Review by cyrilzhang-mm — APPROVED** [review]

**Comment by cwarnermm** [comment]
@coltoneshaw - Ben is correct; R&D manages the English strings, then our translation community provides translation across all supported langauges. Thanks, @BenCookie95!

**Comment by coltoneshaw** [comment]
> @coltoneshaw - Ben is correct; R&D manages the English strings, then our translation community provides translation across all supported langauges. Thanks, @BenCookie95!

Thanks pretty cool, I didn't know that!

**Review by furqanmlk — APPROVED** [review]
Working fine

**Before**
image

**After**
image

**Pull request merged**
