### PR TITLE
MM-24361 - Updating system console save button

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-24361 - Updating system console save button

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24361

#### Screenshots
**Before:**
IMG_E3507FCCE82E-1

**After:**
IMG_CE857DC9F401-1

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@mkraft `vh` as in `100vh` does not work properly on mobile/tablets, so this can act as a fix in those circumstances.

**Comment by amyblais** [comment]
@asaadmahmood Wondering if this could be cherry-picked to v5.25.

**Comment by asaadmahmood** [comment]
@amyblais Sure.

**Pull request merged**
