### PR TITLE
Fix autocomplete static option case insensitive compare

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

The `MenuActionProvider` attempts to do a case-insensitive compare, but does not cast the user's input to lowercase first. This PR fixes it so it casts the user input to lowercase.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-34359
Fixes https://mattermost.atlassian.net/browse/MM-34777

e2e tests MM-T1745 and MM-T1747 were failing because of this

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by amyblais** [comment]
@DHaussermann This is for Cloud April 21st release.

**Review by DHaussermann — APPROVED** [review]
Tested and passed. 
Casing does not affect autocomplete options now. This is working as expected.

LGTM!

**Comment by DHaussermann** [comment]
Sorry for the delay in testing. 
@mickmister this is ready for a cherry-pick.

**Pull request merged**
