### PR TITLE
Fix french translation related issues

### PR DESCRIPTION
**Pull request by shamboozles**
#### Summary
A couple of errors regarding the french translation were found (missing icon for saved messages and "new unreads" too big) were fixed

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2022-07-07 at 16 13 32 | Screenshot 2022-07-07 at 16 13 53 |
| Screenshot 2022-07-07 at 16 21 50 |  Screenshot 2022-07-07 at 09 14 01 |

#### Release Note

```release-note
Changed some details in french translation to fix some UI related issues
```

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thank you, @shamboozles!

**Comment by devinbinnie** [comment]
@shamboozles Can we get you to sign the CLA as per the above comment?

**Comment by shamboozles** [comment]
Oh sure, my bad, hadn't seen it

/check-cla

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Not sure why `/check-cla` was being such a pain, but that's fixed now. Thanks for the PR!

**Comment by hmhealey** [comment]
Ah, I see. I figured it was the command just not working since it wasn't giving feedback.

Skipping QA review on this since it was easy enough to test myself. I confirmed it works on the test server

**Pull request merged**
