### PR TITLE
Mm 29656

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
This PR is a replacement for #6942. Creating a new PR since the old one came from a fork and is stale. The original PR willbe closed after the creation of this. Dicsussions and comments will not be ported over, so please reference comments from the original PR if needed.

#### Ticket Link
Fixes [MM-29656](https://mattermost.atlassian.net/browse/MM-29656)

#### Related Pull Requests
Original PR: #6942

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@michelengelen how do I test this to get the in-product notices to appear so I can review?

**Comment by michelengelen** [comment]
Maybe @hmhealey can help. I would like to avoid hard-coding something that needs to be removed afterwards!

**Comment by michelengelen** [comment]
Apparently it is not possible, so I will add a hard-coded part for now which I will remove before merging.

**Comment by esethna** [comment]
@michelengelen @matthewbirtch maybe a screenshot would be enough for UX review in this case?

**Comment by matthewbirtch** [comment]
> Thanks for the PR!
> 
> @michelengelen @matthewbirtch maybe a screenshot would be enough for UX review in this case?

yep, that's fine with me if you want to provide screenshots @michelengelen

**Comment by michelengelen** [comment]
@matthewbirtch here are some screenshots:


### Primary Button
|normal|hover|active|focus|
|-------|-----|-------|------|
|Screenshot 2021-04-06 at 17 50 02|Screenshot 2021-04-06 at 17 50 14|Screenshot 2021-04-06 at 17 50 25|Screenshot 2021-04-06 at 17 50 36|

### Secondary Button
|normal|hover|active|focus|
|-------|-----|-------|------|
|Screenshot 2021-04-06 at 17 43 45|Screenshot 2021-04-06 at 17 44 35|Screenshot 2021-04-06 at 17 44 41|Screenshot 2021-04-06 at 17 47 12|

### Tertiary Button
|normal|hover|active|focus|
|-------|-----|-------|------|
|Screenshot 2021-04-06 at 17 51 18|Screenshot 2021-04-06 at 17 51 25|Screenshot 2021-04-06 at 17 51 31|Screenshot 2021-04-06 at 17 51 53|

**Review by matthewbirtch — APPROVED** [review]
Looks great based on the screenshots @michelengelen. Nice work. thanks!

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Approving based on attached screenshots. QA will test after merge.

**Review by devinbinnie — APPROVED** [review]
Looks good, is there anywhere else we need to add these styles? I know the `GenericModal__button` class is used in a few places.

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
