### PR TITLE
[MM-29855] Migrate string-refs to functional ones: this.refs.content

### PR DESCRIPTION
**Pull request by lestgabo**
#### Summary
Update `this.refs.content` to `this.content` as a react ref function

#### Ticket Link
github issue -> Fixes https://github.com/mattermost/mattermost-server/issues/16038
JIRA ticket -> https://mattermost.atlassian.net/browse/MM-29855

#### Related Pull Requests
n/a

#### Screenshots
n/a

### CODE REVIEW

**Comment by lestgabo** [comment]
how do I pass the test `mattermost/serverless-ops/github — This PR needs to sync and merge. `
did I need to merge my branch to my forked master then make the PR? (I didnt do that at first. I only just merged this branch to my master)

**Review by mkraft — APPROVED** [review]

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @lestgabo! :tada:

**Review by josephbaylon — CHANGES_REQUESTED** [review]
Hi @lestgabo Thanks for your contribution !! Please add unit tests for `permission_description`. Here's the guide to writing unit tests: https://developers.mattermost.com/contribute/webapp/unit-testing/

Also, as a bonus, it would also be good to add a happy path E2E for the same. Here's the guide to writing e2e tests:
https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by josephbaylon** [comment]
I'll approve this for now so this can be merged. @mkraft / @jespino I don't know which milestone I should assign, please assign one if necessary. Thanks.

**Review by josephbaylon — APPROVED** [review]
LGTM. We'll just add the unit test later.

**Pull request merged**
