### PR TITLE
Cypress/E2E: Potential workaround for emoji to markdown spec failure

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- Allow a very small delay so message post is triggered before cypress verifies the post textbox; cypress maybe too fast that it grabs the element before it has been updated

#### Ticket Link
None -  master only

Screen Shot 2020-08-19 at 8 32 46 AM

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]

**Comment by prapti** [comment]
Waiting for the checks to complete before merging.

**Comment by josephbaylon** [comment]
@metanerd @jaydeland @khos2ow Any ideas why check-cla is not working?

**Comment by khos2ow** [comment]
@josephbaylon There was an issue with the latest mattermod release and in the meantime it's already been rolled back. You can give it another try now.

**Comment by josephbaylon** [comment]
@khos2ow Thanks so much! Looks like the cla issue got resolved as well. cc// @prapti

**Pull request merged**
