### PR TITLE
MM-19380: Scroll channel into view in LHS

### PR DESCRIPTION
**Pull request by valentijnnieman**
#### Summary
Hello! This is a fix for [issue 12748](https://github.com/mattermost/mattermost-server/issues/12748). I've added some checks to the Cypress tests to show that the name in the list is scrolled to. It looks like there's enough margin to still show the "Unread notifications" tooltip. Let me know if this should be tested further!

For some reason my older commits (from [this merged PR](https://github.com/mattermost/mattermost-webapp/pull/3543)) are shown, although no files are changed (since they are merged already). Not sure why this is happening, maybe it is because I made the previous changes on my fork's master and not on a branch? Apologies anyway, let me know if/how I can fix it.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12748

### CODE REVIEW

**Comment by devinbinnie** [comment]
Hey @valentijnnieman, looks like your changes are fine, as long as there's nothing in 'Files changed' that seems out of place, I think you're okay.

Is this ready for review?

**Comment by valentijnnieman** [comment]
@devinbinnie Hi, sorry, been a bit under the weather these last few days. It's ready for review! Thanks.

**Comment by valentijnnieman** [comment]
@hmhealey I've moved the logic to the `Sidebar` component - you were right in that it's a better place for it, I missed it earlier. Also added a offset to the scrolling function, so that it appears not right at the top. Let me know if this is better!

**Comment by valentijnnieman** [comment]
@hmhealey Good point. I've removed the offset and modified the existing constant - it seems to be about one channel's height extra now, at least on my screen. Let me know what you think!

**Comment by hmhealey** [comment]
@esethna That scrolling animation is the same as the one that's currently used when switching channels with alt+arrows. Would you be okay if we opened a separate ticket for that?

**Comment by valentijnnieman** [comment]
If a separate ticket would be opened, I would be more than happy to take a look at that later (once I've worked on some of the other issues I'm doing!) :-)

**Comment by hmhealey** [comment]
@esethna is out this week, so we're just going to make the animation into a separate ticket and take this as-is. I'll file the followup ticket and post it back here

**Comment by jgilliam17** [comment]
I am not able to open channels on the test server https://mattermost-webapp-pr-3957.test.mattermost.cloud/ using Switch Channel (command K). 
Opens to white screen for every channel I tried.
Wondering if I need to remove and then create a new test server?
Can someone please take a look and let me know? Thanks.
Screen Shot 2019-11-13 at 2 18 14 PM

**Comment by hmhealey** [comment]
@jgilliam17 Were there any errors in the JS console when you did that? I'm not able to log into that server for some reason because the login request is timing out

**Comment by hmhealey** [comment]
I got the error message:
Screen Shot 2019-11-14 at 10 58 26 AM

There's somewhere that we're not using refs right which is probably caused by that big react-intl upgrade PR. This is an issue on master, and this PR depends on that functionality. I filed a ticket for it here
https://mattermost.atlassian.net/browse/MM-20166

**Comment by jgilliam17** [comment]
> @jgilliam17 Were there any errors in the JS console when you did that? I'm not able to log into that server for some reason because the login request is timing out

- Unfortunately, I didn't check it at the time. And now it won't load for me at all

**Comment by hmhealey** [comment]
FYI, this is blocked on https://github.com/mattermost/mattermost-webapp/pull/4255 which should fix that error

**Comment by valentijnnieman** [comment]
@hmhealey OK, I'll wait until that PR is merged and then update this one. Thanks!

**Comment by hmhealey** [comment]
@jgilliam17 That PR I mentioned is in, so this should be ready for another round of reviews once the server is rebuilt

**Pull request merged**
