### PR TITLE
[MM-47966] Improve accessibility for user group popovers

### PR DESCRIPTION
**Pull request by cyrilzhang-mm**
#### Summary

Does the same thing as https://github.com/mattermost/mattermost-webapp/pull/11530 but for the new user group popovers. I decided to split this PR into two just to make merging easier.

#### Ticket Link

[Jira ticket](https://mattermost.atlassian.net/browse/MM-47966)

#### Screenshots

https://user-images.githubusercontent.com/112951043/204305369-87c876bf-14f9-4c76-90a9-f3d167a8d0f6.mov

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by mkraft** [comment]
> #### Summary
> Does the same thing as #11530 but for the new user group popovers. I decided to split this PR into two just to make merging easier.
> 
> #### Ticket Link
> [Jira ticket](https://mattermost.atlassian.net/browse/MM-47966)
> 
> #### Screenshots
>  Screen.Recording.2022-11-28.at.9.38.53.AM.mov 
> #### Release Note
> ```
> NONE
> ```

That look awesome @cyrilzhang-mm! Nice one.

**Review by mkraft — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working fine

**Review by mkraft — APPROVED** [review]

**Pull request merged**
