### PR TITLE
MM-13240 - Updating modal css for sys console

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-13240 - Updating modal css for system console

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-13240

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
Why is this marked for 5.6? It's not a regression. There's a large number of line changes here that make me nervous about merging into the release

/cc @amyblais @lindalumitchell

**Comment by asaadmahmood** [comment]
@jwilander The large number of line changes are just indentation stuff. I have removed a parent tag that was unnecessary, and auto adjusted the spacing.

**Comment by jwilander** [comment]
Either way it's been around since 5.4 at least, not sure why it needs to be rushed into 5.6

**Comment by asaadmahmood** [comment]
Yeah, I'm 0/5 on that.

**Comment by lindalumitchell** [comment]
Thanks @jwilander, @asaadmahmood @amyblais I'm fine with this being for v5.7. I'll change the ticket fix version and the milestone, and do we also just remove the `CherryPickApproved` label? Not sure if there's anything else that needs to be done with labels on the PR.

**Comment by saturninoabril** [comment]
@asaadmahmood just need to fix merge conflicts.
@lindalumitchell I believed we should retain the `CherryPickApproved` label so that we'll not miss to cherry-pick it into `release-5.7` once that branch is available.

**Pull request merged**
