### PR TITLE
MM-16937 - Updating padding for channel intro

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-16937 - Updating padding for channel intro

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16937

**Before:**
localhost_8065_mattermost_channels_off-topic (1)

**Now:**
localhost_8065_mattermost_channels_off-topic

### CODE REVIEW

**Comment by cpanato** [comment]
i dont see any difference 😂

**Comment by asaadmahmood** [comment]
@cpanato See the menu options on the post. :D

**Comment by enahum** [comment]
@cpanato automatic cherry-pick not working?

**Comment by cpanato** [comment]
saw an error. @enahum checking

**Comment by cpanato** [comment]
@enahum the milestone had a space in the end of the name and mattermod did not trim that. fixed and also added the slash command to trigger

**Comment by enahum** [comment]
great

**Comment by cpanato** [comment]
im gonna test here with a non org member to test one case, please ignore

**Pull request merged**
