### PR TITLE
Help text in the status dropdown updated to Disables desktop, email a…

### PR DESCRIPTION
**Pull request by pradeepmurugesan**
…nd push notifications

#### Summary
Help text in the status dropdown updated to include emails

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/12325

#### Related Pull Requests

- Has server changes https://github.com/mattermost/mattermost-server/pull/12502
- Has redux changes NO
- Has mobile changes NO

### CODE REVIEW

**Comment by esethna** [comment]
Should be tested by QA after https://github.com/mattermost/mattermost-server/pull/12502

**Comment by lindy65** [comment]
Thanks @hanzei - I will test this once https://github.com/mattermost/mattermost-server/pull/12502 has been merged (as per Eric's comment above)

**Comment by lindy65** [comment]
Thanks @pradeepmurugesan @esethna 

1. Help text for "DND status" is correct: "Disables desktop, email and push notifications"

2. I tested that email, push and desktop notifications work correctly while "online", "away" and "offline" according to the settings in my "Account Settings > Notifications". I did not find any issues with these statuses.

3. However, I am seeing an issue where my 'lindy' test user is receiving email in DND status.  Perhaps I have not set up correctly? (I _do not_ receive desktop or push notifications while in DND status)

I waited for https://github.com/mattermost/mattermost-server/pull/12502 to be merged then rebuilt this spinwick thinking that the code from https://github.com/mattermost/mattermost-server/pull/12502 would be included?  Is this correct?

Here are screenshots from my 'alice' test account showing 'lindy' in DND status and also the email that is received by 'lindy' while in DND status.

image

image

**Comment by pradeepmurugesan** [comment]
Hello @lindy65 , Thank for testing. I am not sure how the test server is created. But I believe the server is not having our commit. 
Screenshot 2019-10-11 at 22 44 57


In the above screenshot the version has a git commit id : 6ba961a which is made on Oct 1. 

Screenshot 2019-10-11 at 22 42 58

The server changes for this task are merged on Oct 8. Highlighted in the following screenshot

Screenshot 2019-10-11 at 22 43 14


I may be wrong as I am not sure how the spinwick instances are created. 

@esethna Kindly validate the above with core developers to confirm

**Comment by esethna** [comment]
@hanzei would you know on the above? The server commit was merged Oct 8 but the spinwick is not getting those changes.

**Comment by hanzei** [comment]
@lindy65 Would you please try again?

**Pull request merged**
