### PR TITLE
Hiding custom statuses config when feature flag is disabled

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Hiding custom statuses config when feature flag is disabled

#### Ticket Link
[MM-33163](https://mattermost.atlassian.net/browse/MM-33163)

### CODE REVIEW

**Comment by jespino** [comment]
@ogi-m because this is for the next release I added you directly, the amount of code review needed is minimal and I don't expect any changes to the PR, so I guess we can go straight forward to the QA tests.

**Comment by amyblais** [comment]
@hmhealey @michelengelen Please prioritize reviews on this today.

**Review by devinbinnie — APPROVED** [review]

**Review by michelengelen — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Comment by furqanmlk** [comment]
### For False Settings

image

image

### For True Settings
image

image

**Review by ogi-m — APPROVED** [review]
Thanks @furqanmlk ! Approving the PR.

**Pull request merged**
