### PR TITLE
[GH-15724] Remove usage of findDOMNode from Create Team screens

### PR DESCRIPTION
**Pull request by Jonany**
#### Summary
Removed usage of findDOMNode from Create Team screens.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15724

#### Related Pull Requests
None.

#### Screenshots
None.

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @Jonany!

**Review by hmhealey — APPROVED** [review]
Looks good to me. Thanks for adding unit tests as well!

**Review by jgilliam17 — APPROVED** [review]
Thank you @Jonany 
Tested, looks good to merge.
- Verified Create Team screens - works as expected.

**Comment by jbattistispiria** [comment]
@mattermod I would like to grab this one.

**Pull request merged**
