### PR TITLE
MM-12776 - Updating comments in RHS (compact view)

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-12776 - Updating comments in RHS (compact view)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12776

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @asaadmahmood 

Tested on desktop app, compact view and I am not seeing any weird indenting in RHS replies.  Looks good to me!

**Comment by hmhealey** [comment]
Ready to be merged, but it needs a rebase

**Comment by asaadmahmood** [comment]
@hmhealey Done.

**Comment by hmhealey** [comment]
Merged onto master and cherry picked onto release-5.5

**Pull request merged**
