### PR TITLE
WIP: MM-9639 Added ability to collapse long posts

### PR DESCRIPTION
**Pull request by hmhealey**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
[A brief description of what this pull request does.]

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by hmhealey** [comment]
@esethna This isn't ready for testing yet unfortunately. I set up this PR so that I could set up a spinmint for Mike, but it's not coming up for some reason

**Comment by esethna** [comment]
Bumping this to 4.10

**Comment by michaelgamble** [comment]
Had a conversation about a specific use case with Harrison.
USE CASE: If a long post with the read more button is immediately followed by secondary posts by the same user - there by eliminating the user avatar and name how should we handle the spacing.

DECISION: similar to a post being handled if its the only post in the channel - we would add additional gutter to the bottom of the "read more" long post so that it has a 10px space, instead of directly overlapping. The reason being is in this particular use-case the "read more" button should not be overlapping the follow on posts content.

**Comment by hmhealey** [comment]
Closing this for now

**Pull request closed without merging**
