### PR TITLE
migrated status_icon to typescript

### PR DESCRIPTION
**Pull request by Saamiyah**
#### Summary
Migrate status_icon.jsx to typeScript

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/12437

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Comment by jasonblais** [comment]
@Saamiyah thanks for the contribution! Looks like the build didn't pass, can you help take a look?a

**Comment by devinbinnie** [comment]
@Saamiyah these are the error generated by `tsc`:

```
components/profile_picture.tsx:85:26 - error TS2322: Type '{ status: string | undefined; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<StatusIcon> & Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, "children"> & Partial<Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, never>> & Partial<...>'.
  Property 'status' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<StatusIcon> & Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, "children"> & Partial<Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, never>> & Partial<...>'.

85                         <StatusIcon status={this.props.status}/>
                            ~~~~~~~~~~

components/profile_picture.tsx:98:18 - error TS2322: Type '{ status: string | undefined; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<StatusIcon> & Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, "children"> & Partial<Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, never>> & Partial<...>'.
  Property 'status' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<StatusIcon> & Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, "children"> & Partial<Pick<Readonly<{}> & Readonly<{ children?: ReactNode; }>, never>> & Partial<...>'.

98                 <StatusIcon status={this.props.status}/>
                    ~~~~~~~~~~

components/status_icon.tsx:31:16 - error TS2339: Property 'button' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.

31         const {button, status, type} = this.props;
                  ~~~~~~

components/status_icon.tsx:31:24 - error TS2339: Property 'status' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.

31         const {button, status, type} = this.props;
                          ~~~~~~

components/status_icon.tsx:31:32 - error TS2339: Property 'type' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.

31         const {button, status, type} = this.props;
                                  ~~~~

components/status_icon.tsx:37:48 - error TS2339: Property 'className' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.

37         let className = 'status ' + this.props.className;
                                                  ~~~~~~~~~

components/status_icon.tsx:40:36 - error TS2339: Property 'className' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.

40             className = this.props.className;
                                      ~~~~~~~~~

components/status_icon.tsx:46:17 - error TS2322: Type 'typeof StatusOnlineAvatarIcon' is not assignable to type 'string'.

46                 IconComponent = StatusOnlineAvatarIcon;
                   ~~~~~~~~~~~~~

components/status_icon.tsx:48:17 - error TS2322: Type 'typeof StatusAwayAvatarIcon' is not assignable to type 'string'.

48                 IconComponent = StatusAwayAvatarIcon;
                   ~~~~~~~~~~~~~

components/status_icon.tsx:50:17 - error TS2322: Type 'typeof StatusDndAvatarIcon' is not assignable to type 'string'.

50                 IconComponent = StatusDndAvatarIcon;
                   ~~~~~~~~~~~~~

components/status_icon.tsx:52:17 - error TS2322: Type 'typeof StatusDndAvatarIcon' is not assignable to type 'string'.

52                 IconComponent = StatusOfflineAvatarIcon;
                   ~~~~~~~~~~~~~

components/status_icon.tsx:55:13 - error TS2322: Type 'typeof StatusOnlineIcon' is not assignable to type 'string'.

55             IconComponent = StatusOnlineIcon;
               ~~~~~~~~~~~~~

components/status_icon.tsx:57:13 - error TS2322: Type 'typeof StatusAwayIcon' is not assignable to type 'string'.

57             IconComponent = StatusAwayIcon;
               ~~~~~~~~~~~~~

components/status_icon.tsx:59:13 - error TS2322: Type 'typeof StatusDndIcon' is not assignable to type 'string'.

59             IconComponent = StatusDndIcon;
               ~~~~~~~~~~~~~

components/status_icon.tsx:61:13 - error TS2322: Type 'typeof StatusOfflineIcon' is not assignable to type 'string'.

61             IconComponent = StatusOfflineIcon;
               ~~~~~~~~~~~~~

components/status_icon.tsx:64:17 - error TS2322: Type '{ className: string; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'className' does not exist on type 'IntrinsicAttributes'.

64         return <IconComponent className={className}/>;
                   ~~~~~~~~~~~~~
```
I think you forgot to add your `Props` type to the component?

**Comment by jasonblais** [comment]
@Saamiyah let us know if you have any questions, we'd be glad to help! Appreciate your contribution

After a certain time of inactivity, we'll consider closing the PR - you can learn more about the process here https://developers.mattermost.com/contribute/getting-started/inactive-contributions/

**Comment by hanzei** [comment]
Hi @Saamiyah,

I just wanted to check if you are still interesting in continuing this PR.

Please note that we will close this PR after another 10 days of inactivity. If you don't object, other contributors might complete this PR for you.

**Comment by devinbinnie** [comment]
Closing this PR as per the above, please advise if you would like us to reopen :)

**Pull request closed without merging**
