### PR TITLE
MM-47563 : Text inside Cancel Button is not aligned

### PR DESCRIPTION
**Pull request by Manishpandey11**
#### Summary
Cancel button text within ChannelInviteModal is not aligned

Steps to reproduce

1. Click channel members button
2. Click Add button
3. Check Cancel button

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/21427
Jira: https://mattermost.atlassian.net/browse/MM-47563

#### Screenshots
Before 
image
After
image

#### Release Note
NONE

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]

**Comment by michelengelen** [comment]
@Manishpandey11 could you please sign the CLA so I can trigger the workflow? Thanks!

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by Manishpandey11** [comment]
> /check-cla

@jgilliam17  @hmhealey, please merge my PR. I have to submit it to my academic

**Comment by jgilliam17** [comment]
@Manishpandey11 can you please rebase branch with master? Thanks 🙂

**Comment by Manishpandey11** [comment]
@jgilliam17 I have merged master into the feature branch. For some reason tests on the pipeline fails. Can you please check and help me with this?

**Comment by Manishpandey11** [comment]
> @michelengelen, can you please help with the failed checks?

@jgilliam17, please merge my pull request. I need this for my academics. Please try to merge  as soon as possible

**Review by michelengelen — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @Manishpandey11 and apologies for delay
Tested, looks good to merge.

**Pull request merged**
