### PR TITLE
Admin Advisor: get metric status on refresh for admins only

### PR DESCRIPTION
**Pull request by catalintomai**
#### Summary
When the current user is non-admin, we should not be calling the Admin Advisor metric warning functionality on page refresh.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27960

#### Related Pull Requests
https://github.com/mattermost/mattermost-redux/pull/1220

### CODE REVIEW

**Review by srkgupta — APPROVED** [review]
Tested the PR along with its dependent PR and now the API call to the endpoint '/api/v4/warn_metrics/status' is made by webapp only if the logged in user is a sysadmin. Approving the PR.

**Comment by hahmadia** [comment]
Just ensure that redux hash is updated correctly after merge. Thanks

**Comment by amyblais** [comment]
@catalintomai Kind reminder that this is ready to merge,

**Pull request merged**
