### PR TITLE
Fix warnings about React-Bootstrap triggers

### PR DESCRIPTION
**Pull request by hmhealey**
These warnings were printed in dev mode because having tooltips only appear on hover doesn't work on touch screens or when using the keyboard to navigate. The warnings have been around forever, and I finally got annoyed enough to fix them.

#### Release Note
```release-note
Changed some tooltips to appear when focused instead of just on hover
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Comment by hmhealey** [comment]
I was going to skip QA review on this since it shouldn't have any noticeable effect on users, but I just realized that there's a small chance that this would cause a link with a tooltip to keep the tooltip visible when the user clicks on it.

@jgilliam17 Could you do a quick check to see if that happens anywhere? I can get you a list of tooltips that might be affected by this if it would help.

**Comment by jgilliam17** [comment]
List would be helpful @hmhealey. Thanks

**Comment by hmhealey** [comment]
Okay, this affects tooltips for the following components:
1. The buttons for the member, files, and pinned posts in the channel header
2. The skin colour selector in the emoji picker
3. The tooltip for the file attachment button in the post textbox
4. The history controls when using the desktop app
5. The buttons for at mentions, saved posts, and settings in the global header

**Comment by jgilliam17** [comment]
@hmhealey 
- The skin color selector in the emoji picker - tooltip is there on hover, but I can't tab to this icon to focus; we may have a ticket already to make this icon accessible 
- The tooltip for the file attachment button in the post textbox - tooltip is not shown either way, focus or hover.

**Comment by jgilliam17** [comment]
I should probably turn advanced text editor on the test server too and hover/tab through options

**Comment by jgilliam17** [comment]
Ok, I missed this on my first pass not sure if it's expected. Tooltips are not dismissing when I tab to icon, verify tooltip + hit enter - tooltip persists

**Comment by hmhealey** [comment]
> > The tooltip for the file attachment button in the post textbox - tooltip is not shown either way, focus or hover.
> 
> I'll take a look. I thought it didn't work at all when I tested, but I see it working on master. Maybe it got broken by that PR for pinning the comment box to the bottom which was reverted?

Okay, this looks like it's fixed. The upload button isn't positioned right (https://mattermost.atlassian.net/browse/MM-44562), but that's not related to this PR.

I think everything you mentioned is working as expected then.

**Comment by jgilliam17** [comment]
Thanks @hmhealey for checking 
Tested, looks good to merge.
- Verified tooltips on hover and focus - as expected
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/196447-1e624f6-onprem-ent-webapp-pr-10320-mm-ee-test:1e624f6/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
