### PR TITLE
MM-9803: Fixes cursor placement in team and user settings.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary
Chrome sets the cursor at the beginning of text inputs with a value by default ([example fiddle](https://jsfiddle.net/geo5guky/)).

#### Ticket Link
[MM-9803](https://mattermost.atlassian.net/browse/MM-9803)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by mkraft** [comment]
@jespino There may be other places. I did click around and put them everywhere I could think of.

**Comment by jespino** [comment]
I did a rg (Like grep or Ack) of "autoFocus", and looks like the admin console have a lot of cases of that, for example. But as I said, I think is something to investigate and add in other PR.

**Comment by mkraft** [comment]
@jespino If you see are the intersect of `input[type=text]`, could have a value when loaded, and actually focus the input on load then let me know.

**Comment by mkraft** [comment]
@hmhealey I just did a test and it doesn't jump (or some such) when you click into a text input value somewhere other than the end, so I don't think it's an issue.

**Pull request merged**
