### PR TITLE
MM-17909 - Updating users dropdown

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-17909 - Updating users dropdown

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-17909

**Screenshot**
Screenshot 2019-08-21 at 5 52 06 PM

### CODE REVIEW

**Comment by jespino** [comment]
@asaadmahmood If you don't mind, let me merge and cherry-pick this, because was introduced by me in another PR, and I prefer to cherry-pick them in the correct order in to 5.15.

**Comment by asaadmahmood** [comment]
Cool @jespino.

**Comment by jwilander** [comment]
Added do not merge label so that no one but @jespino does the merge

**Comment by lindy65** [comment]
Thanks @asaadmahmood - looks good to me, the dropdown menu is shown for the users in the System Console.

**Comment by bradjcoughlin** [comment]
@jespino I almost reported this again 😉

**Pull request merged**
