### PR TITLE
[MM-35310] Only show channels not in a team attached to the current policy

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
When selecting channels for a policy, you should only see channels that are not related to a team in the current policy

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35310

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Comment by amyblais** [comment]
@calebroseland @furqanmlk Kind note to review, we could get this in for the next Cloud release for May 19th.

**Review by calebroseland — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
### **Working as expected** 
Thanks @BenCookie95 

image

**Comment by amyblais** [comment]
@BenCookie95 Seems to need a manual cherry-pick to ``cloud``.

**Comment by BenCookie95** [comment]
@amyblais cherry-picked to `cloud`

**Pull request merged**
