### PR TITLE
MM-38159 - Fix license checks in System Console for Starter License

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Features below were only checking for the existence of a license in System Console (assuming it would be available for both E10/E20). However, in Cloud Starter, there is a license present but these features should not be available:

- Announcement Banner
- Compliance Monitoring

This PR changes it so it checks for the actual Feature Flags in the license.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38159

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]

**Comment by stevemudie** [comment]
@marianunez I created a Spinwick and purchased a Starter subscription on it but it appears to have unfettered access to all Enterprise features.

Should I be testing this in another way?

**Comment by marianunez** [comment]
> @marianunez I created a Spinwick and purchased a Starter subscription on it but it appears to have unfettered access to all Enterprise features.
> 
> Should I be testing this in another way?

@stevemudie I logged in to the test server you subscribed to `Starter` and I see the Enterprise features not available. Could it be it hadn't finished applying the new license when you tried? 

Screen Shot 2021-09-01 at 2 44 37 PM

**Comment by stevemudie** [comment]
> @stevemudie I logged in to the test server you subscribed to `Starter` and I see the Enterprise features not available. Could it be it hadn't finished applying the new license when you tried?

It looks that way as it's working as expected now. :)

**Review by stevemudie — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Comment by amyblais** [comment]
@marianunez Is this for v6.0?

**Comment by marianunez** [comment]
> @marianunez Is this for v6.0?

No given that this is for Cloud Starter, this is for Sept. 29th Cloud Release. Should we have that as a Milestone in Github too?

**Pull request merged**
