### PR TITLE
[MM-42906] - License receives invalid date in the console when license expiration check runs

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR ensures the `EnterpriseEditionLeftPanel` component uses an unsanitized license to display information about the license

#### Ticket Link
[MM-42906](https://mattermost.atlassian.net/browse/MM-42906)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
I like it.

**Review by neallred — APPROVED** [review]
LGTM, thanks @AGMETEOR !

**Review by marianunez — APPROVED** [review]
Thanks @AGMETEOR!

**Comment by Phrynobatrachus** [comment]
I'm pretty sure the `/e2e-test` runs here are failing because they are running against the `MM-42906` server branch, which is out of date and was already merged separately into `master` over there. I'm checking with the other SDETs on this.

**Comment by saturninoabril** [comment]
@AGMETEOR Test still failed. The build is not picking up the latest update (I made) on your [server's MM-42906 branch](https://github.com/mattermost/mattermost-server/tree/MM-42906). Maybe check with Release team on what's going on. Not sure if it requires the branch to be submitted as PR. If such server branch is not required, could it be deleted so that this PR will build against master of server and enterprise?
Screen Shot 2022-05-04 at 9 36 01 AM

**Comment by saturninoabril** [comment]
Hmm, okay, I just saw this PR - https://github.com/mattermost/mattermost-server/pull/20035 - and it's already closed. Hope you don't mind but while I'm here, I'll go ahead and reopen that PR for the purpose of seeing the build, then eventually close and delete the remote server branch.

**Comment by saturninoabril** [comment]
This should be good now - https://automation-dashboard.vercel.app/cycles/44472e7a-14ce-4232-89c6-63c1bfb8bfd2, but I'll be pushing another empty commit so that it will pick up the new server PR (empty, on master, https://github.com/mattermost/mattermost-server/pull/20132) instead of the old PR (https://github.com/mattermost/mattermost-server/pull/20035).

**Review by stevemudie — APPROVED** [review]
Assuming that the E2E issues are all straightened out now @AGMETEOR this is working as expected otherwise.

**Pull request merged**
