### PR TITLE
MM-40317: fixes showing new replies banner

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Currently we rely on the new messages line visibility on whether to show
or not the "New Replies" banner. However new messages line is not showing,
by design, on unfollowed threads. Which made the new replies banner to
show when new replies arrived for those threads.

This commit fixes the issue by guarding on the list's 'visibleStopIndex',
if visibleStopIndex is zero then the last item of the list is visible.
so we show the new replies only if the visibleStopIndex is not zero.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-40317

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Makes sense to me!

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by jgilliam17** [comment]
@koox00 Thanks for running E2E already - [report ](https://automation-dashboard.vercel.app/cycles/985eeeda-9936-4636-bf47-79880a39a030)looks good, no PR related failures

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Tested, looks good to merge.
- Verified `New Replies arrow` appears when the new message is off the bottom of the rhs screen.

**Pull request merged**
