### PR TITLE
reduce min username length to 2

### PR DESCRIPTION
**Pull request by cherouvim**
#### Summary
Reduces the minimum username length from 3 to 2. This is already supported on the backend.

#### Checklist
- [X] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you @cherouvim for the contribution - requiring at least three characters for the username is done because searching for recent mentions won't work for 1 or 2 character usernames.

The restriction isn't applied on the server-side because some LDAP and SAML usernames might only be 1 or 2 characters long --> in which case their username would turn into a random string, which is worse UX than not having recent mentions search work properly. But we've kept the restriction client-side.

Let me know if you have any thoughts or feedback on this?

**Comment by cherouvim** [comment]
Hello and thanks for your prompt response.

I currently use mattermost (still old version `4.10.0`) and I've updated my username a long time ago directly in the database via an update statement to change it to 2 letters. Every functionality regarding my "custom" username has been working great, including recent mentions feature: https://i.imgur.com/Hij7bVo.png

All of the other users of installation who need a 2 letter username (to match their company provided email alias) have ended up adding a trailing dot to make it possible (e.g `nk.` instead of `nk`).

I think that the ability to have a 2 letter username in mattermost would be handy to others as well.

**Comment by cherouvim** [comment]
No. I've only executed this in postgres (around 1.5 year ago):

    update users set username='jc' where id='5k6nech3qfy19cmr91c9zasjso';

**Comment by jasonblais** [comment]
@cherealnice Sorry for the delay, I investigated this further:

Based on what I found, three-character search minimum is a SQL search default. While it's possible to change it (I suspect your database is running with two-character search minimum), it is generally not recommended for larger installs given the possibility of impacting search performance.

Here's an example of the default value for MySQL: https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_ft_min_token_size

So in general, the proposal for SQL search is to keep the three-character minimum -- which is why we'd keep usernames to be three characters minimum as well.

That said, there have been others who have proposed reducing minimum username to two characters: https://mattermost.uservoice.com/forums/306457-general/suggestions/16391320-changing-min-username-to-2-characters

Would you be open to upvoting the above-linked feature proposal? You get 10 votes in the forum, each one influencing the future of this project.

If the feature request attracts a lot of community interest, we can further discuss potential options for supporting two-character usernames.

**Comment by cherouvim** [comment]
Thanks for your time. Upvoted.

**Comment by jasonblais** [comment]
Thanks @cherouvim! In the meantime I'll close this issue and we'll track via the feature proposal forum https://mattermost.uservoice.com/forums/306457-general/suggestions/16391320-changing-min-username-to-2-characters

**Pull request closed without merging**
