### PR TITLE
[MM-12006] Add SearchHint component and use it on SearchBar and SearchResults

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add SearchHint component and use it on SearchBar and SearchResults

#### Ticket Link
Jira ticket: [MM-12006](https://mattermost.atlassian.net/browse/MM-12006)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by enahum** [comment]
@jsonblais lets consider this and make translators aware

**Comment by enahum** [comment]
@jasonblais lets consider this and make translators aware

**Comment by jasonblais** [comment]
To add, 25% of all servers don't use an English language by default, so we're introducing a potential quality issue / bug that could affect all users on those 25% of servers.

**Comment by saturninoabril** [comment]
Thanks @jasonblais, basically there's a conflict with the "Search Options" header.  We have that on search bar but not on search result, and since it's on a single translation entry, there's really a need to touch the `en` translation.  I'll check again and see what's the minimum change possible.

**Comment by saturninoabril** [comment]
@jasonblais One option is no other deletion and modification in `en.json` except to add 2 translation entries of:
- Use **before:** to find posts before a specific date
- Use **after:** to find posts after a specific date

In my opinion, my initial change is the better way to do it but let me know which do you prefer?

**Comment by enahum** [comment]
Perhaps is best to leave it as it is, but then @jasonblais can make the call to push this to 5.4

**Comment by jasonblais** [comment]
Okay, so sounds like to fix this properly, we should keep it as-is. I'm okay with that.

Then the decision is whether to fix in v5.3 or v5.4. 

1. If v5.3, we have the risk of having English text for a UI component that's used by (almost) everyone. Affects 25% of servers.
2. If v5.4, we have the risk of having inconsistent text between search results and search dropdown.

Given 2 is lower impact, propose pushing to v5.4.

**Comment by saturninoabril** [comment]
@enahum @jespino Base branch changed to master. Basically no change except on fixing conflicts with the translation. 
 Please take a look again before merging to master. Thanks.

**Pull request merged**
