### PR TITLE
Cypress:e2e/Fixed and demote test cases

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Test cases have been fix / demoted.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by metanerd — APPROVED** [review]
Thank you @furqanmlk !

**Review by Phrynobatrachus — APPROVED** [review]
LGTM, thanks

**Comment by amyblais** [comment]
@furqanmlk Seems to need a manual cherry-pick to ``release-6.5``.

**Pull request merged**
