### PR TITLE
[MM-22667] - Add autocomplete="off" to emoji picker input

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
set autocomplete to 'off' in the emoji picker input

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22667

### CODE REVIEW

**Comment by amyblais** [comment]
@nevyangelova Is this fix risky? If this is for v5.22, can you help cherry-pick it?

**Comment by nevyangelova** [comment]
@amyblais this just turns off autocomplete for browsers so no risks involved. I can cherry pick it.

**Comment by amyblais** [comment]
@nevyangelova Has this been cherry-picked?

**Comment by amyblais** [comment]
@nevyangelova Kind reminder to cherry-pick this PR, or change the label to CherryPick/Done if it's already done.

**Pull request merged**
