### PR TITLE
[MM-49061] Fix Thread Drafts not Updating on Team Switch

### PR DESCRIPTION
**Pull request by mylonsuren**
#### Summary

Fixed thread drafts not syncing to server when RHS is unmounted

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49061

#### Related Pull Requests

- This should be merged after https://github.com/mattermost/mattermost-webapp/pull/11733.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Comment by amyblais** [comment]
@koox00 Please help prioritize this PR review.

**Review by koox00 — APPROVED** [review]

**Comment by mylonsuren** [comment]
@jgilliam17 I've updated the QA test steps on the [JIRA ticket](https://mattermost.atlassian.net/browse/MM-49061), let me know if you have any questions.

**Review by jgilliam17 — APPROVED** [review]
Thanks @mylonsuren 
Tested, looks good to merge.
[E2E report ](https://automation-dashboard.vercel.app/cycle/278516)- no PR related failures.

**Pull request merged**
