### PR TITLE
[ICU-720] Fix cropping of images below minimum dimension

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
ICU-720 - Single image thumbnails are not cropping appropriately 
ICU-721 - Rounding all corners for single file thumbnails

#### Ticket Link
https://mattermost.atlassian.net/browse/ICU-720
https://mattermost.atlassian.net/browse/ICU-721

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

### CODE REVIEW

**Comment by saturninoabril** [comment]
@asaadmahmood As requested, please see initial PR. Thanks!

**Comment by jwilander** [comment]
@saturninoabril this is going to conflict with my changes, I suggest we confirm this works as expected and then I will rebase mine on top of this and make sure it still works

**Comment by saturninoabril** [comment]
@jwilander I tried to port these changes into yours and unfortunately it didn't work well. I'm leaning towards accepting your PR first for 4.7 (fix for scroll pop without image responsiveness on browser window resize), and then deal with this improvement next (cropping issue) either 4.7 or 4.8 depending on criticality. Any thoughts? cc @esethna

**Comment by jwilander** [comment]
Assuming this is priority to fix as well then let's merge this and I'll deal with the rebase (and any needed fixes) in my PR

**Comment by esethna** [comment]
@jwilander yes let's get this merged and update your scroll pop PR, thanks!

**Comment by jwilander** [comment]
Just confirming with @AndersonWebStudio and then I'll merge

**Pull request merged**
