### PR TITLE
[MM-31018] Update email address for admin advisor contact requests to support-advisor@mattermost.com

### PR DESCRIPTION
**Pull request by jasonblais**
#### Summary
Update email address for admin advisor contact requests to support-advisor@mattermost.com

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31018

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/16443

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Comment by jasonblais** [comment]
Please review carefully, to make sure I haven't missed a file.

@amyblais I would like to get this into v5.30 if possible. It is not a must-have though, so if I missed a code deadline, let me know and we'll queue for v5.31.

**Comment by amyblais** [comment]
This is for v5.31 - v5.30 will be based on the cloud release we did last week Tuesday - https://community-release.mattermost.com/private-core/pl/aa5m38ngg3dgfd6d3ma4pbbwne.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jasonblais** [comment]
@furqanmlk please help with QA review :)

**Comment by furqanmlk** [comment]
> @furqanmlk please help with QA review :)
@jasonblais
I am in the process of review. 
For some reason I don’t see expected email address. I will confirm with Rohit and update. 
Sorry about the delay as I am new to this feature :)

**Comment by jasonblais** [comment]
All good :) If any questions, let me know

**Review by furqanmlk — COMMENTED** [review]
**Advisory Banner** `Acknowledge` button still sending email to `support@mattermost.com`.
Please see the attachment for reference 

### Advisory Banner
image

### Advisory Banner Mailto:email address
image

**Comment by furqanmlk** [comment]
Advisory Banner `email us` shows correct email address

image

**Comment by jasonblais** [comment]
@catalintomai is this something you can assist with as well? I'm not able to find where in the code we are setting the `acknowledge` button to send the email to support-advisor@mattermost.com

**Comment by catalintomai** [comment]
@jasonblais , you will need to update the  `MM_SUPPORT_ADDRESS` value in mattermost-server/model/config.go. cc: furqanmlk

**Comment by jasonblais** [comment]
@catalintomai I assume this will change the email address for all other places where that constant is used? The intention is to only change it for the admin advisor notifications.

**Comment by catalintomai** [comment]
> @catalintomai I assume this will change the email address for all other places where that constant is used? The intention is to only change it for the admin advisor notifications.

@jasonblais, I introduced the constant for AdminAdvisor purposes, fwik it is not used anywhere else.

**Comment by jasonblais** [comment]
That's great, thanks Catalin! I've made the update in the corresponding server PR: https://github.com/mattermost/mattermost-server/pull/16443#issuecomment-744071195

**Review by furqanmlk — APPROVED** [review]
Tested Contact Us and Email Us button are sending email to support-advisor@mattermost.com.
Test cases have been created for the same feature
[MM-T3656](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T3656)

**Comment by jasonblais** [comment]
@catalintomai Any guidance on why the tests suddenly fail? No changes were made, other than updating to the master branch with `/update-branch`.

Otherwise the PR is ready to merge.

**Comment by catalintomai** [comment]
@jasonblais , you have to run a "make check-style" and address the errors. From the test results, it looks like there are some semicolons missing.

**Comment by jasonblais** [comment]
Thanks @catalintomai for the quick response. I actually made these changes via the UI and don't have the environment running locally to execute `make check-style`. That said, I only updated the email address and should have no missing semicolons.

image

**Comment by catalintomai** [comment]
@jasonblais - the failures are not related to your changes (you can click on the failure link above) - not clear how they made their way into master - I see the errors on my enlistment as well. I suspect they'll be fixed soon (tomorrow) and you should be able to check-in.

**Pull request merged**
