### PR TITLE
Cypress/E2E: Fix intermittent failing tests at common commands

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Fix intermittent failing tests at common commands
- separate `invite` and `groupmsg` into its own spec files to easily run test in isolation, and promote/demote particular test

#### Ticket Link
none, failing in daily Cypress run

Test run - https://mm-cypress-report.s3.amazonaws.com/1034-common-commands-master/mochawesome.html

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Changes look straightforward. All tests passed locally. Thanks @saturninoabril !!

**Comment by prapti** [comment]
Changes look good to me but they are failing locally for me and it looks like the `#postListContent` is taking longer to load in at least 2 test files, invite_commands_spec and common_command_spec even though the timeout side considerably high. But it if passed for Joseph, I can approve it.
Screen Shot 2020-10-01 at 4 38 16 PM
Screen Shot 2020-10-01 at 3 42 47 PM

**Comment by saturninoabril** [comment]
Yeah, let's observe it again next time. And I suspect it might also happen to other similar test.

**Comment by prapti** [comment]
Should we demote it from prod then?

**Comment by saturninoabril** [comment]
I suggest no. I'll take care of it once I wrapped for a week. The one you're seeing can potentially happen to other test. Also, it might depend on local setup as well. Let's see how it run in CI.

**Comment by saturninoabril** [comment]
fyi, this [prod report](https://mm-cypress-report.s3.amazonaws.com/1039-master-prod-master/mochawesome.html) includes the changes from here.

**Review by prapti — APPROVED** [review]

**Pull request merged**
