### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by amyblais**
For https://community-release.mattermost.com/core/pl/8jqbg9hq4pb7fgy838zjwnmkty

### CODE REVIEW

**Comment by esethna** [comment]
@amyblais looks good. In the future can we have someone from tech writing team do reviews on text PRs?

**Comment by cpanato** [comment]
@justinegeffen can you take a look in this English string? :)

**Comment by cpanato** [comment]
@amyblais I'm goin gto use your PR to test the new test servers, hope you don't mind 😄

**Comment by justinegeffen** [comment]
LGTM, thanks!

**Comment by amyblais** [comment]
@hanzei Would you be open to merging this PR as I don't have merge permissions here and the auto-merge label is not working? 🙏

**Pull request merged**
