### PR TITLE
[GH-15886] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 614

### PR DESCRIPTION
**Pull request by tony-ho**
#### Summary

Remove changeCss() for `.nav-pills__unread-indicator` color.
This is no longer required as CSS variable `--mention-color` is already used.

https://github.com/mattermost/mattermost-webapp/blob/c3f01ee92ca30d6bedf62aa93b6e117efd37f9a4/sass/layout/_sidebar-left.scss#L404

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15886

### CODE REVIEW

**Comment by tony-ho** [comment]
Thanks @devinbinnie. I've added the color property in  `_legacy-sidebar-left.scss`.

**Review by devinbinnie — APPROVED** [review]
Looks good now, thanks @tony-ho!

**Comment by hanzei** [comment]
@tony-ho Heads up that there is a merge conflict to resovle

**Review by asaadmahmood — APPROVED** [review]

**Comment by tony-ho** [comment]
Thanks @hanzei, the merge conflict has been resolved.

**Comment by hanzei** [comment]
Thanks @tony-ho :+1:

**Pull request merged**
