### PR TITLE
PLT-8113: Fixes missing values on OAuth2 setup success page.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary
Expected keys in JS object were nested within JSON payload's `data` key.

#### Ticket Link
[PLT-8113](https://mattermost.atlassian.net/browse/PLT-8113)

#### Checklist
- [x] Ran `make check-style` to check for style errors

### CODE REVIEW

**Comment by mkraft** [comment]
Marked as WIP for now because there are two bugs listed in the ticket and I'm awaiting confirmation that the second one still exists.

**Comment by lindalumitchell** [comment]
@mkraft @jasonblais This looks good to me! I was able to successfully set up the Zapier integration with no issues. First issue with values not displaying = fixed, and second issue did not reproduce for me.

**Comment by jwilander** [comment]
This needs to be based off the `release-4.4` branch if it's meant for 4.4. You can change the base branch by clicking the edit button in the top right

**Comment by mkraft** [comment]
@jwilander Fixed base branch.

**Pull request merged**
