### PR TITLE
MM-T389 Invite new user to closed team with "Allow only users with a specific email domain to join this team" set to an email domain that is NOT "sample.mattermost.com"

### PR DESCRIPTION
**Pull request by josephk96**
Summary

This test creates a closed team, ensure that users with a NON 'sample.mattermost.com' email domain can join the team, send out an invite, verify the email and make sure that the new user is successfully able to join the team.

I changed `mattermost.com` -> `sample.mattermost.com` to keep this test standardized with the other ones that use `sample.mattermost.com` as the email address. Please let me know if you would like me to change this to `mattermost.com` instead :) 

Test case: https://automation-test-cases.vercel.app/test/MM-T389

### CODE REVIEW

**Review by saturninoabril — CHANGES_REQUESTED** [review]
Thanks @josephk96! Tested and passed. Really nice to see all your PRs related to team settings/email domain. But I suggests to resolve other PRs first then apply necessary implementation here. It would also be nice to extract helper functions that can be shared by other specs files within `/team_settings` folder.

**Comment by josephk96** [comment]
@saturninoabril @josephbaylon , I refactored the test to use the helper methods defined in `team_settings/helpers.js` . I also added and refactored some helper methods to reduce duplication because this test is 99% the same as MM-T386, which I also refactored in my last commit.

**Comment by josephk96** [comment]
Thanks @josephbaylon !

**Review by saturninoabril — APPROVED** [review]
Thanks @josephk96, LGTM!

**Comment by saturninoabril** [comment]
Sorry for late review @josephk96. Please fix merge conflict, then good to merge.

**Pull request merged**
