### PR TITLE
Revert to React 16

### PR DESCRIPTION
**Pull request by hmhealey**
As we discussed on and off over the past week or so, React 17 causes issues with plugins that still use React DOM 16. We're going to revert the actual dependency update for the time being to give more time for those to be updated.

I left most of the code changes from #10836 so that those won't need to be redone when we go back to React 17 in the future

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47225

#### Related Pull Requests
#10836

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
LG!

**Review by mickmister — APPROVED** [review]
LGTM

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
[E2E report](https://automation-dashboard.vercel.app/cycles/25a0fa07-167b-4a55-810f-cadbeddbff5f) - no PR related failures

**Review by catalintomai — APPROVED** [review]

**Comment by amyblais** [comment]
@hmhealey This needs manual cherry-picks to ``release-7.4`` and ``cloud``.

**Comment by amyblais** [comment]
> @hmhealey This needs manual cherry-picks to `release-7.4` and `cloud`.

@hmhealey Kind reminder ^

**Comment by hmhealey** [comment]
Yep, I'll do those today

**Pull request merged**
