### PR TITLE
translations PR 20190204

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by kaakaa** [comment]
I found that some messages is not translated.




As long as I check community server, the following messages seems to be missing.
 
* user.settings.notifications.desktop.mentionsSound
* user.settings.notifications.desktop.mentionsNoSound
* user.settings.notifications.desktop.mentionsSoundHidden
* user.settings.notifications.desktop.allSound
* user.settings.notifications.desktop.allNoSound
* user.settings.notifications.desktop.allSoundHidden

These messages in [desktop notification settings](https://github.com/mattermost/mattermost-webapp/blob/master/components/user_settings/notifications/desktop_notification_settings.jsx#L212) have been translated on Translation Server  about two weeks ago, but they don't seem to be written in `ja.json`. And other languages seem to have the same issue.

**Comment by enahum** [comment]
@jespino can you check @kaakaa comment and see if we need a PR for that?

**Comment by jespino** [comment]
Yes, exactly, somebody added the strings directly to the en.json but the strings weren't catch by the translation too, because weren't in the cases that are extracted. I going to make a PR with this right now.

**Comment by enahum** [comment]
Thanks @jespino

**Pull request merged**
