### PR TITLE
[MM-15755]  fix old links to use the new urls in system console

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- fix some old links in the en.json to use the new admin console links
- update tests
- fix hardcoded strings in the code

#### Ticket Link
jira: https://mattermost.atlassian.net/browse/MM-15759

### CODE REVIEW

**Comment by hmhealey** [comment]
Perhaps it could be a good idea to set up redirects for the old URLs in case there's anything else that we've missed? 0/5 on that though if we're sure we've gotten all the URLs

**Comment by lindalumitchell** [comment]
I verified on the spinmint that the cases listed in the ticket are fixed. 👍 

1. Do we still need to do a sweep through all the repos to look for other cases?
2. Do we want to consider redirects like Harrison said, just in case?

**Comment by cpanato** [comment]
It is not my call, however we can merge this and we can have a followup

**Comment by cpanato** [comment]
cherry picked 21c0667e43b695d583b7d21f5aa5f49bdd60feee into release 5.12 branch

**Pull request merged**
