### PR TITLE
MM-49976: Fix tag, custom status position in channel switcher

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Fix tag, custom status position in channel switcher

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-49976

#### Related Pull Requests
NA

#### Screenshots

|  before  |  after  |
|----|----|
| image-20230125-195438 | Screenshot 2023-02-02 at 2 20 05 PM |

#### Release Note
```release-note
* Fix tag, custom status position in channel switcher
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@vish9812 @koox00 gentle reminder this is a regression, and we need it in 7.8

**Comment by AshishDhama** [comment]
@amyblais Have added the changes to fix the issues mentioned in the ticket.

**Comment by amyblais** [comment]
@vish9812 @koox00 Please help prioritize this PR review.

**Review by koox00 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @AshishDhama 
Tested, looks good to merge - pending e2es
Verified custom status on channel switcher - as expected.

**Review by jgilliam17 — APPROVED** [review]
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/298987-408fdcd-onprem-ent-webapp-pr-12120-mm-ee-test:408fdcd/mochawesome.html) - no PR related failures.

**Comment by amyblais** [comment]
@AshishDhama Please help open a manual cherry-pick PR.

**Comment by AshishDhama** [comment]
@amyblais I think we should add this as well in 7.8 https://github.com/mattermost/mattermost-webapp/pull/11930

**Pull request merged**
