### PR TITLE
Fixed Command Injection in moment-timezone 

### PR DESCRIPTION
**Pull request by iot-defcon**
#### Summary
```js
6  module.exports = function (grunt) {
7      grunt.registerTask('data-download', '1. Download data from iana.org/time-zones.', function (version) {
8          version = version || 'latest';

10          var done  = this.async(),
11              src   = 'ftp://ftp.iana.org/tz/tzdata-latest.tar.gz',
12              curl  = path.resolve('temp/curl', version, 'data.tar.gz'),
13              dest  = path.resolve('temp/download', version);
...
24          exec('curl ' + src + ' -o ' + curl + ' && cd ' + dest + ' && gzip -dc ' + curl + ' | tar -xf -', function (err) {
```
Ordinarily, one one run this script using something like grunt data-download:2014d, in which case version would have the value 2014d. However, if an attacker were to provide additional content on the command line, they would be able to execute arbitrary code

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@pavkcon thank you so much for this investigation. Do you mean to say that the current version of moment-timezone has security issue? If yes you can we also need to update the dependency in `package.json` file

**Comment by m1lt0n** [comment]
@pavkcon Thanks a lot for your investigation. The current version of moment-timezone on master is 0.5.38, so above 0.5.35 that is mentioned in the package-lock.json, so I guess we should be already ok, right?

**Comment by m1lt0n** [comment]
Hey @saturninoabril I've added you as a reviewer since the dependency mentioned is under e2e/cypress dependencies

**Review by saturninoabril — CHANGES_REQUESTED** [review]
Thanks @pavkcon!

Please bump the version in the package.json, preferably the latest version `5.39`.

I've read the [said fix](https://github.com/moment/moment-timezone/security/advisories/GHSA-56x4-j7p9-fcf9) and really appreciate the time you spent in letting us know. We're not using grunt and only using moment-timezone within the context of the Cypress specs. Could you share potential issue based on how we're using the package?

**Comment by saturninoabril** [comment]
@iot-defcon Any update? Would be good to update the `package.json` in this PR as suggested [here](https://github.com/mattermost/mattermost-webapp/pull/11655#pullrequestreview-1195481025). Otherwise, I'll recommend to close this PR in favor of https://github.com/mattermost/mattermost-webapp/pull/11657.

**Comment by saturninoabril** [comment]
@iot-defcon Again, please update `package.json` to reflect the fix version with the fix. Otherwise, I'll be closing this in favor of https://github.com/mattermost/mattermost-webapp/pull/11657.

**Comment by saturninoabril** [comment]
Also, you haven't sign the CLA which is required before accepting contribution.

**Comment by saturninoabril** [comment]
> can you help for completed this CLA, i have viewed the cla but this directly for downloading files.

Oopss, sorry, I misread. You may register via form in this link - https://mattermost.com/mattermost-contributor-agreement/?redirect_source=mm-org

**Comment by saturninoabril** [comment]
You too @iot-defcon! Hope you could push a new commit as suggested in the last comment https://github.com/mattermost/mattermost-webapp/pull/11655#issuecomment-1337103520. I'll be merging https://github.com/mattermost/mattermost-webapp/pull/11657 soon, just hoping I could merge this first once my request is fulfilled. Otherwise, I'll close this. Thanks for taking time to letting us know.

**Comment by saturninoabril** [comment]
@iot-defcon I haven't seen you made changes to `package.json` as commented. Closing this PR now.

**Pull request closed without merging**
