### PR TITLE
MM-21414 - Updating textbox position in RHS

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-21414 - Updating textbox position in RHS
Now the suggestion list changes its positioning depending on how much space is available at the top.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21414

#### Screenshots
Screenshot 2020-01-02 at 5 37 58 PM
Screenshot 2020-01-02 at 5 38 07 PM
Screenshot 2020-01-02 at 5 38 17 PM

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@saturninoabril @jwilander with the functionality change, the tests were failing, so I tried to fix the tests myself. Do let me know if I've done that incorrectly.

**Comment by saturninoabril** [comment]
Unit test looks good to me.

Two issues found:
1. Not sure if by design but the "Add Comment" button is being pushed down when suggestion list is rendered at the bottom.
Screen Shot 2020-01-03 at 4 35 55 PM

2. When height is short like 600px, the suggestion list is rendered in full then cut-off.
Screen Shot 2020-01-03 at 4 37 41 PM

**Comment by asaadmahmood** [comment]
@saturninoabril Done

**Comment by asaadmahmood** [comment]
asdsad



















asd

**Pull request merged**
