### PR TITLE
[GH-7674] Migrate pdf_preview.jsx to be pure and use Redux

### PR DESCRIPTION
**Pull request by yth0625**
#### Summary
Migrate pdf_preview component to redux

#### Ticket Link
GitHub: https://github.com/mattermost/mattermost-server/issues/7674
Jira: https://mattermost.atlassian.net/browse/PLT-7674

#### Checklist
- [x] Added or updated unit tests

### CODE REVIEW

**Comment by yth0625** [comment]
Hello, I need help writing test code.
When I give 'props' to PDFPreview component, In the 'getDocument' function of the external module pdfjs-dist, I get the same error as the picture.
To solve this problem, I mocked the Promise resolve from 'getDocumention' function.
But that was not a good solution.
Because in practice 'getDocument' is return state of PDFPrview component.
So It' bad to mocking to Promise resolve.
I am in a very difficult situation now.

**Comment by jasonblais** [comment]
@saturninoabril Would you be able to help with writing test code?

@yth0625 Did you actually submit a PR for this help wanted ticket? https://github.com/mattermost/mattermost-server/issues/7674

**Comment by jwilander** [comment]
Yeah, looks like the wrong ticket got linked :P

**Comment by yth0625** [comment]
Oh.. sorry
I checked my ticket link.

**Comment by jasonblais** [comment]
No worries @yth0625! Thanks for working on it :)

**Comment by saturninoabril** [comment]
@yth0625 Thanks for your contribution! I'll take a look at this tomorrow.

**Comment by saturninoabril** [comment]
@yth0625 I don't think there's much we could test (on rendering) here since most logic are handled by PDFJS.
I just added some tests on its internal functions.

**Comment by jwilander** [comment]
Thanks for your work on this @yth0625

**Pull request merged**
