### PR TITLE
MM-12647 Update react-select

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Updates react-select to the new major version and update our usage for the new API.

@lindy65 can you regression test the Add Users To Team, Add Users To Channel and More Direct Messages modals? The only expected difference is the little `x` will be on the right rather than the left for any selected users.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12647

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @jwilander 

Tested the areas you requested above:

1. Adding members to a team (both open and closed teams) is working as expected.

2. Because of [the channel dropdown menu bug on master](https://mattermost.atlassian.net/browse/MM-12762) - I am unable to test adding members to a channel in the channel drop-down menu.  I did, however, create new public and private channels and tested the `invite others to this channel` option at the start of a new channel and this is working as expected.  Adding members from the `Members` > `Manage members` > `Add new members` modal is also working as expected.

3. For the `More...` direct messages modal, I'm seeing the first number (in the example below `15 of 15 members`) drop by 2 when I've selected only one name (this doesn't reproduce on `master`)

image

image

Confirm that the little `x` is appearing to the right of any selected member's name in all cases.

**Comment by jwilander** [comment]
Thanks @lindy65, not sure what's happening with 3) but I'll take a look

**Comment by jwilander** [comment]
3 - This is expected, it removes yourself from the list as soon as you click on another user hence the count decreasing by two

**Comment by lindy65** [comment]
Makes sense, thanks @jwilander !

**Pull request merged**
