### PR TITLE
[MM-42529] DM thread does not get disabled when the user is deactivated

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
While the state was being updated, the RHS didn't get the update in the thread as it wasn't re-render. Scrolling to the bottom serves this purpose and shows the user the message about the user being deactivated in the case of a long scrollable thread.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42529

#### Related Pull Requests
N/A

#### Screenshots
https://user-images.githubusercontent.com/684680/209685484-89c9beee-b43d-4f3a-8c65-0ae3eb7ea67f.mp4

#### Release Note
```release-note
NONE
```

[MM-42529]: https://mattermost.atlassian.net/browse/MM-42529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected.
**Before**
image


**After**

image

**Pull request merged**
