### PR TITLE
Cypress/E2E: Fix failed E2E tests due to message not being submitted

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Most of those are passing in headed but not in headless mode. I'm guessing it's primarily due to the async nature in saving draft into the local storage.  Added extra one second before hitting `{enter}` at `postMessageAndWait `.
- Added extra space when posting a message that open up suggestion list. Extra space will cause suggestion list to close, so that hitting enter within `postMessageAndWait ` will correctly submit a message (and not just close the previously opened suggestion list).
- Removed unnecessary use of `{enter}`

#### Ticket Link
none, failed on daily run.

#### Screenshots
Some of the tests.
Screen Shot 2021-04-26 at 11 25 40 PM

```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. There's a lot of affected files here. I'll take a look at this once merged and the report is posted and fix potential issues, if any.

**Review by furqanmlk — COMMENTED** [review]
@saturninoabril  I am getting error due to `postMessageAndWait()` where it waits for `textContent` to be empty

image

image




image


I am still verifying other test cases.

**Comment by josephbaylon** [comment]
@furqanmlk @saturninoabril Kicked off a cypress run for this PR https://app.circleci.com/pipelines/github/saturninoabril/mattermost-cypress-docker?branch=webapp-pr-7998

**Comment by saturninoabril** [comment]
Thanks @furqanmlk for checking. Got caught up on last minute clean up on it. I've kicked off another test run with changes from this PR and will push change/fix later.

**Comment by saturninoabril** [comment]
@furqanmlk That should be fixed now and also the one at `custom_slash_commands_spec.js`.
Screen Shot 2021-04-29 at 8 03 46 AM
Screen Shot 2021-04-29 at 8 04 00 AM
Screen Shot 2021-04-29 at 8 39 13 AM
Screen Shot 2021-04-29 at 8 40 13 AM
Screen Shot 2021-04-29 at 8 40 46 AM
Screen Shot 2021-04-29 at 8 43 02 AM
Screen Shot 2021-04-29 at 8 48 22 AM
Screen Shot 2021-04-29 at 8 52 28 AM
Screen Shot 2021-04-29 at 8 55 38 AM
Screen Shot 2021-04-29 at 8 58 48 AM
Screen Shot 2021-04-29 at 9 39 20 AM
Screen Shot 2021-04-29 at 9 41 16 AM
Screen Shot 2021-04-29 at 9 42 33 AM
Screen Shot 2021-04-29 at 9 48 38 AM
Screen Shot 2021-04-29 at 9 49 38 AM
Screen Shot 2021-04-29 at 9 50 15 AM
Screen Shot 2021-04-29 at 9 52 38 AM
Screen Shot 2021-04-29 at 9 53 38 AM
Screen Shot 2021-04-29 at 9 54 42 AM
Screen Shot 2021-04-29 at 9 55 53 AM
Screen Shot 2021-04-29 at 9 57 20 AM
Screen Shot 2021-04-29 at 10 03 43 AM
Screen Shot 2021-04-29 at 10 04 34 AM
Screen Shot 2021-04-29 at 10 05 42 AM
Screen Shot 2021-04-29 at 10 07 06 AM
Screen Shot 2021-04-29 at 10 07 42 AM
Screen Shot 2021-04-29 at 10 08 51 AM
Screen Shot 2021-04-29 at 10 09 42 AM
Screen Shot 2021-04-29 at 10 11 00 AM
Screen Shot 2021-04-29 at 10 12 25 AM
Screen Shot 2021-04-29 at 10 13 16 AM

**Comment by saturninoabril** [comment]
Push another fix for posting-a-message related issue based from the last test report - https://mm-cypress-report.s3.amazonaws.com/4776-webapp-pr-7998-mattermost-enterprise-edition:d451dbf/mochawesome.html.

Notable change is the addition of `waitForCommentDraft` when posting message in RHS. That fixes the issue where the last character/s of the original message is being cut-off. It's only applicable to comment since submitting a comment is based from the saved draft at IndexDB/localforage. Also, added `localforage.clear()` in the global before hook to reset the storage before anything else.

I'm running the test again just to make sure I'm not breaking anything - https://app.circleci.com/pipelines/github/saturninoabril/mattermost-cypress-docker?branch=webapp-pr-7998

**Comment by saturninoabril** [comment]
@josephbaylon Please take a look again. Thanks!

**Comment by josephbaylon** [comment]
@saturninoabril Not sure if it has something to do with your changes but the recent cypress run has significantly more failures than the previous run.

**Comment by saturninoabril** [comment]
Yup, it's related. I made `cy.postMessage` stricter and fail fast so we could easily sort out on what's the main issue. I've removed `QA review` label at the moment. Will ping all of you once ready. Thanks for checking!

**Comment by saturninoabril** [comment]
This is now ready for review. Currently running test in CI.

**Review by josephbaylon — APPROVED** [review]
LGTM. Thanks @saturninoabril !!

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril , All look good 👍

**Pull request merged**
