### PR TITLE
Fixed a bug that caused a gap to appear in products using team sidebar when user had only 1 team

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed a bug that caused a gap to appear in products using team sidebar when user had only 1 team

#### Ticket Link
Fixes #19309

#### Related Pull Requests
None

#### Screenshots
Before:
Screenshot 2022-01-11 at 4 58 31 PM

After:
Screenshot 2022-01-11 at 5 03 28 PM

#### Release Note
```release-note
Fixed a bug that caused a gap to appear on the left in products using the team sidebar.
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM, but I think we should test it properly in all the 3 products, to be sure this is working fine.

**Comment by harshilsharma63** [comment]
> LGTM, but I think we should test it properly in all the 3 products, to be sure this is working fine.

@jespino yes I'm gonna run E2E tests on this then @saturninoabril and @ogi-m and test this.

**Comment by harshilsharma63** [comment]
@saturninoabril can you please test this?

**Comment by saturninoabril** [comment]
Requesting reviews to Ogi and Cass to verify for Boards and Playbooks, on top of Channels.

**Comment by harshilsharma63** [comment]
@ogi-m can you try this out?

**Review by Phrynobatrachus — APPROVED** [review]
Confirmed with Jesse that Playbooks should be good on this issue, it's not used by us at the moment.

**Review by ogi-m — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
