### PR TITLE
MM-12205: notify on session expiration

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Trigger a notification when the current session expires, redirecting to `/login?extra=expired`, and displaying a mostly pre-existing message that that seems to have been unused.

The notifications are flagged with `requireInteraction` to stay on screen for platforms that support same, but notably Electron [does not yet support this](https://github.com/electron/electron/issues/9283), so the notifications disappear after a few seconds as usual.

The specifications for this feature also require changes to the badge handling on desktop, but I'll be tackling that in https://mattermost.atlassian.net/browse/MM-12275 given the scope of changes that's required.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12205

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes
- [x] Has redux changes: https://github.com/mattermost/mattermost-redux/pull/641
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by lieut-data** [comment]
One nuance I haven't captured here is:
> If they have the application or server tab in focus, no desktop notification is sent

I had originally implemented this by showing/hiding with the notification on blur/focus, and may revisit that implementation to clarify the above point.

**Comment by lieut-data** [comment]
After completing the badging changes on desktop (https://github.com/mattermost/desktop/pull/866), I realized that my implementation is only limited to detecting active sessions that expire: if the desktop app is closed and re-opened, but finds the session expired, it's treated as a new login altogether.

Fixing this will require a few changes: I'll need to persist something to localStorage akin to "was I logged in?", and set/clear that like I do the `extra=expired` query string parameter now. If the login controller detects this bit, it will redirect appropriately, preserving the interface to the desktop. This will be easier to accomplish once https://github.com/mattermost/mattermost-webapp/pull/1764 is merged.

**Comment by jasonblais** [comment]
@lieut-data would you like to have PM review/testing for this PR, after your changes? Just confirming the purpose of the PM review label

**Comment by lieut-data** [comment]
@jasonblais, I'm primarily hoping to get feedback on the notification experience and login controller handling. The specifications were clear, but there are edge cases that I think could use some "does this feel right" checking.

I think you could experiment with this PR as written -- the proposed changes above should only subtly tweak the triggers. If you hit up `/login?extra=expired`, you can experience 99% of the UX.

**Comment by lieut-data** [comment]
@jasonblais, you can even test in desktop if you login to the spinmint there and then invalidate the session from the browser. You won't get the badging, but the notifications will still work.

**Comment by jasonblais** [comment]
@lieut-data I did some testing on the Chrome browser (didn't look at the desktop app yet), few notes:

1. When you force log out from **Account Settings > Security > View and Logout of Active Sessions**, propose we don't send the additional notification nor the error text on login page. Propose we keep the existing behaviour as-is, similar to when doing Main Menu > Logout.

image

2. Is the error message on the login screen expected? I don't see that on the spec. (Is this the pre-existing message you mention in the PR description)

image

3. In the spec it's noted, `If they have the application or server tab in focus, no desktop notification is sent`, but this appears to fail for the first bullet point.

4. The desktop notification persists, which is expected. I noticed the following however:
- Switch between browser tabs [desktop notification shown]
- Switch back to Mattermost log in page [desktop notification disappears]
- Switch to another browser tab [desktop notification re-appears]

I would expect the desktop notification to not disappear when you enter the Mattermost window

**Comment by lieut-data** [comment]
Thanks for the feedback, Jason!

> 1. When you force log out from Account Settings > Security > View and Logout of Active Sessions, propose we don't send the additional notification nor the error text on login page. Propose we keep the existing behaviour as-is, similar to when doing Main Menu > Logout.

We can't currently distinguish the user invalidating the session from any other event invalidating the session. That is, the remote client in that case only discovers that their session was invalidated due tot the `401 Unauthorized` now being returned from API calls, just like it would in other session expirations. Personally, I think this is desirable, since it's all too easy to invalidate the "wrong" session in that list, and you might want to realize this if you meant to effect a different one.

> 2. Is the error message on the login screen expected? I don't see that on the spec. (Is this the pre-existing message you mention in the PR description)

It's definitely not part of the spec, but after discovering it in the existing code, I restored it for a couple of reasons. First, it provides a necessary explanation for environments (like the Desktop app) where the notification isn't sticky. A badge will be displayed, but it may not be obvious what on the page is triggering the badge. The `(Dismiss)` also provides a nice way to transition "out" of the state of caring about an expired session; otherwise, the notification would keep displaying because you're effectively stuck in a "you must log back in state", even if you don't want to.

> 3. In the spec it's noted, If they have the application or server tab in focus, no desktop notification is sent, but this appears to fail for the first bullet point.

Yeah, the focus tracking isn't ideal here. I can't find a reliable way to determine if the window /currently/ has focus, and must instead track `onFocus` and `onBlur` events. Unfortunately, these don't fire when you type in an URL and press enter (at least in Chrome), even though the page arguably has focus at that point. If you tab away and then back, however, you'll see the notification promptly disappear. I tried inverting the defaults, and assuming we had focus unless we knew otherwise, but this made the Desktop app not display the notification at all when it reloaded after its session expired. I think we might be at the mercy of user agent implementation details here until we revisit some of the desktop app implementation details.

> 4. The desktop notification persists, which is expected. I noticed the following however:
Switch between browser tabs [desktop notification shown]
Switch back to Mattermost log in page [desktop notification disappears]
Switch to another browser tab [desktop notification re-appears]
I would expect the desktop notification to not disappear when you enter the Mattermost window

Interesting! I can fix this to make the notification "sticky", such that if we decide to display it, it doesn't get re-displayed until it's dismissed. Note that, on the desktop app (and Firefox, I think), it's currently not possible to make the notification sticky, so if it disappears without being seen, nothing will trigger it to be shown again in that flow. If we're ok with that (relying on the badging and explanation text instead), I should be able to make that change.

**Comment by jasonblais** [comment]
1. Okay, that should be fine
2. I'm personally okay with it (with a minor correction to read `Your session has expired. Please log in again.` (login --> log in)
3. I *think* this is okay but would be curious to hear @esethna's feedback given he works more closely on end user experience
4. To confirm, the change made here won't affect how Firefox and desktop app already currently work? (notifications not being sticky)

@esethna Hopefully you'll have some time to test on Windows and the desktop app, mine will be limited to the above. If needed, we can also get the QA involved.

**Comment by lieut-data** [comment]
> 4. To confirm, the change made here won't affect how Firefox and desktop app already currently work? (notifications not being sticky)

Right, the only change here would be that if we show the notification and the platform doesn't automatically dismiss it, we'll only close it when you either 1) close the notification yourself, 2) dismiss the notification using whatever UI is available, or 3) successfully login. On platforms like Firefox, or currently Desktop, the notification will disappear automatically, and we won't display it again in that flow.

> 3. I think this is okay but would be curious to hear @esethna's feedback given he works more closely on end user experience

In experimenting some more with this, I feel like the inability to reliably detect present focus effectively makes the focus tracking useless, especially with the changes above to keep showing the notification once it's been shown. I'm not sure of a way around this.

**Comment by jasonblais** [comment]
Thank you @lieut-data, sounds good on the above.

Regarding the third point - while that is true, it is still an improvement on what we have today (no notification ever) which we can iterate over.

Of course, I was testing with steps where the notification did trigger, so it may be different in a "real world" scenario.

**Comment by DHaussermann** [comment]
Hi @lieut-data,

I've taken a look over this on desktop and browser. The one thing I would add is that when testing on desktop, I'm seeing the desktop notification but, I'm not seeing the notification jewel.

I may be missing somersetting here but based on the spec, I am also expecting to see;
- a notification jewel on the server tab (assuming it's not selected)
- a notification jewel on the task bar
- a notification jewel on in the system tray

Should I be seeing this on the SpinMint above?

**Comment by jasonblais** [comment]
Thanks @DHaussermann! Appreciate your help taking a look.

Desktop app specific features are being added by a separate PR here https://github.com/mattermost/desktop/pull/866

This applies to each of the notification jewels. But the desktop notification and the error message on the login screen should appear on desktop app though.

**Comment by jasonblais** [comment]
@lieut-data I apologize for the last commit on package.json. This was not intentional and I've since reverted it. (I thought I was working on another PR)

Hopefully you got enough testing done Eric :)

**Comment by lieut-data** [comment]
@esethna, can you try waiting a minute or so to see if the desktop notification appears? Revoking the session doesn’t send a message to the client in question: it will only realize it has expired once a request fails. If you give it focus, it immediately kicks off a request which fails and triggers the expiration flow, but otherwise you have to wait for a background event to occur before the client realizes. 

It shouldn’t be more than a minute or so.

**Comment by cpanato** [comment]
done

**Comment by lieut-data** [comment]
@jasonblais, I can agree with that. It gets more interesting when both kinds of messages are displayed:

image

Perhaps there's value with the different colour in this case. 0/5.

**Comment by lieut-data** [comment]
@esethna, the "session expired" state is persistent until you login or dismiss. This is necessary, because we don't transition out of the state on refresh: otherwise a desktop app reload wouldn't know the session underneath had previously expired.

Given the above, my thinking was that you might be in a state where you don't want to login (but you also don't want to close the tab, especially on desktop) but do want to dismiss the notifications and badging. I'm 0/5 on this: it's easy to remove or tweak with the "x" button as you suggest.

**Comment by esethna** [comment]
Got it, thanks @lieut-data. Given the above I'd propose we go with an "x" button, tooltip "Dismiss"

**Comment by lieut-data** [comment]
@esethna, how's this?

image

**Comment by esethna** [comment]
Looks good, thanks @lieut-data

**Pull request merged**
