### PR TITLE
[MM-30586] Change super to system

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Super admin to System admin

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30586

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected 

**Before Changes**
image


**After Changes**
image

**Comment by amyblais** [comment]
@hahmadia The ``cloud`` branch was created this morning so this should be cherry-picked to that. I'm not yet sure if v5.30 will be based on the cloud release we'll do next week or the one after that, but it's probably safest to cherry-pick this now.

**Comment by hahmadia** [comment]
@amyblais 

Aye aaye Captain! Will cherry pick it into cloud.

Just a question, what's the difference between cloud-ga and cloud? I'm little confused. Thanks

**Comment by amyblais** [comment]
Will respond offline.

**Pull request merged**
