### PR TITLE
PLT-7709 Generate system console settings pages for plugins

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Generate system console settings pages for plugins. Waiting on some server change for the placeholders to work, but everything else should be good for testing.

@jasonblais I'll DM you a plugin to test with

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7709

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Added or updated unit tests (required for all new features)
- [x] Has server changes (mattermost/mattermost-server#7817)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@jwilander The spinmint doesn't let you upload plugins -- probably a permissions error.

Please help resolve + let me know the steps and I'll to admin guide since others might hit it as well.

**Comment by jwilander** [comment]
Should be fixed now, DMed you the doc stuff

**Comment by jasonblais** [comment]
@jwilander This looks really good 👍 

Only note is the URL for the settings pages is `.../admin_console/plugins/custom/helloworld`
 - is it intentionally `../plugins/custom/helloworld` and not just `../plugins/helloworld`? 
 - what if you upload two plugins with the same name? How would the URL be handled in that case?

Not directly related to this PR, but I noticed I can upload the same plugin multiple times without getting any errors. Previously you got an error `Unable to upload the plugin. Plugin may already exist and be activated.` which we could change to `Unable to upload the plugin. Plugin may already be installed.` now that there's a distinction between installed and active plugins.

**Comment by jwilander** [comment]
Thanks!

It is intentional to have the `/custom/` in the URL to make sure it doesn't collide with any of our other pages.

Uploading two plugins with the same ID isn't supported (at least it's not supposed to work) so it URL collisions shouldn't be a problem there. Not sure why it's letting you upload the same plugin multiple times, it should error out. Probably something to do with the addition of active/inactive states. I filed a bug for it https://mattermost.atlassian.net/browse/PLT-8146

**Pull request merged**
