### PR TITLE
MM-49626: Changed the order of Leave Channel and Archive Channel to be the same as in mobile

### PR DESCRIPTION
**Pull request by satya-vinay**
#### Summary
Changed the order of Archive Channel to last item at Channel dropdown menu, to maintain consistency across clients and avoid accidental actions.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/22133
JIRA: https://mattermost.atlassian.net/browse/MM-49626

#### Related Pull Requests
NA
#### Screenshots

|  before  |

Screenshot 2023-01-28 at 1 36 25 PM

|  after  |

Screenshot 2023-01-28 at 2 07 32 PM

#### Release Note

```
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @satya-vinay 
Tested, looks good. - pending e2es
Verified leave and archive channel order matches mobile.

**Review by jgilliam17 — APPROVED** [review]
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/296151-d7d9df3-onprem-ent-webapp-pr-12089-mm-ee-test:d7d9df3/mochawesome.html)- no PR related failures.
LGTM

**Pull request merged**
