### PR TITLE
MM-24351 Update react virt list to be based on new library

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Updating react window to be based on new repo https://github.com/mattermost/dynamic-virtualized-list
This includes minor cleanup made for library API which reflects the changes made in the PR. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24351

Note: testing will be a smoke testing scroll, loading posts, switching channels

### CODE REVIEW

**Comment by hmhealey** [comment]
I'd be interested in learning more about the library at some point. Maybe a blog post or a demo of some sort? 🙂

**Comment by jgilliam17** [comment]
Adding testing steps, per discussion with Sudheer

This requires a smoke test around scroll conditions, including, but not limited to:
- loading more posts
- checking if landing on unread post works etc
- switching channel and coming back
- posting new post to keep at bottom

**Comment by jgilliam17** [comment]
Thank you @sudheerDev 
I am not able to add new posts on any of the channels/DMs 
Also, text "Beginning of..." text is missing. See image.
Screen Shot 2020-05-14 at 5 45 31 PM

**Comment by stylianosrigas** [comment]
I had to remove the Setup Cloud Test Server label because we need to deprecate the cluster the installation is running. Reapplied successfully.

**Comment by sudheerDev** [comment]
@jgilliam17 Can you test this again?

**Pull request merged**
