### PR TITLE
[MM 18159] Fix multiple hover post menus appearing after escaping from image preview.

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
When clicking on image previews in posts, the post hover menu on the right of the post was getting stuck visible once closing the menus. This PR corrects that by preventing element focusing by the a11yController while modals are open.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18159

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@deanwhillier I took a look and I'm still seeing this issue on the spinwick (note: to repro I set the display to Compact Mode as in the screenshot on the JIRA ticket):

file-tooltip-hover-other-post

**Comment by deanwhillier** [comment]
@lindalumitchell, I think the ticket was specifically referring to the hover post menus on the far right of each post. In the pic from the ticket, there are two hover post menus open at the same time, which I repro'd in my tests. That's what I fixed in this PR. It is interesting that the hover tooltip is showing on the pic though, maybe a new ticket if that's not expected?

I think my PR title is misleading so I've updated it to match the title from the ticket – sorry!

**Comment by deanwhillier** [comment]
Also updated the summary to be a bit more specific.

**Comment by deanwhillier** [comment]
Had a quick look and I believe the tooltip is shown because the image receives focus after the modal closes. Haven't thoroughly test that hunch yet though.

**Comment by lindalumitchell** [comment]
Oh I see I completely misread the issue, thanks for clarifying, @deanwhillier! In that case, all looks good on the spinwick. :)  Removing QA Review label.

(Created https://mattermost.atlassian.net/browse/MM-18875 for the issue I accidentally found.)

**Comment by deanwhillier** [comment]
Thanks Linda!

**Pull request merged**
