### PR TITLE
[MM-41579] Remove FF guided channel creation

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Removes the Feature Flag allowing admin to create a channel as part of the previous onboarding experience. The new Use Case Onboarding still has it active.

I'm setting up the test server with the following variables:
- `MM_FEATUREFLAGS_GUIDEDCHANNELCREATION=true`: would add  the channel creation option if it was not removed
- `MM_FEATUREFLAGS_USECASEONBOARDING=false`: make sure we don't use the new use case onboarding

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41579

#### Related Pull Requests
- Has server changes https://github.com/mattermost/mattermost-server/pull/19673

#### Screenshots
|  before  |  after  |
|----|----|
| image | image|
| Notice step 6 above... | ...is gone now |

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by julmondragon — APPROVED** [review]
LGTM!

**Review by pablovelezvidal — APPROVED** [review]
LGTM, nice work! @JulienTant , One request, please when you add the QA steps for @stevemudie make sure to add steps to also validate that the new Use Case Onboarding still has it active. Thanks.

**Comment by JulienTant** [comment]
> LGTM, nice work! @JulienTant , One request, please when you add the QA steps for @stevemudie make sure to add steps to also validate that the new Use Case Onboarding still has it active. Thanks.

Hey Pablo, yep that's planned, but the `cloud` bot is not creating my server (context: https://community-daily.mattermost.com/private-core/pl/r8zurdzyctf85bsdqyie1pypyr)

**Review by stevemudie — APPROVED** [review]
Just 5 steps. Looks good @JulienTant!

**Comment by JulienTant** [comment]
Hey @stevemudie, it was a trap! 😂 
There's a second step, I forced the activation of the new Use Case Onboarding, can you confirm that during the new onboarding, it DOES offer you to create a channel

**Review by stevemudie — APPROVED** [review]
@JulienTant It's all good - again 😁

The admin onboarding **does** ask you to create a new channel as expected.

The new regular user onboarding, which is very much still the old onboarding, has just 4 steps now which is as expected as well right?

- Complete your profile
- Set up notifications 
- Invite members to your team
- Download the desktop and mobile apps

If that looks good, then we're all set.

**Comment by JulienTant** [comment]
> @JulienTant It's all good - again grin
> 
> The admin onboarding **does** ask you to create a new channel as expected.
> 
> The new regular user onboarding, which is very much still the old onboarding, has just 4 steps now which is as expected as well right?
> 
> * Complete your profile
> * Set up notifications
> * Invite members to your team
> * Download the desktop and mobile apps
> 
> If that looks good, then we're all set.

Yep the user onboarding is not impacted! thanks for checking!

**Pull request merged**
