### PR TITLE
MM-48195 - onboarding messaging item not working on guest users

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
The 'learn more about messaging' onboarding item was not working as expected for guest users since channel creation and user invitation are disabled for this roles. This PR makes sure to start the onboarding tour for this role only in the steps that they can see that are send messages and configure your env.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48195

#### Related Pull Requests
n/a

#### Screenshots

https://user-images.githubusercontent.com/10082627/200505588-14fafff0-de47-46a8-b613-990a5eaa04a5.mp4

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Comment by pvev** [comment]
> @pvev There are some conflicts that need to be resolved in this PR.

ok, perfect, I will, thanks!

**Comment by pvev** [comment]
@AshishDhama requesting re-review after fixing several merge conflicts. Thanks!

**Review by AshishDhama — APPROVED** [review]

**Comment by AshishDhama** [comment]
@pvev Thanks for taking care of conflicts.

**Comment by pvev** [comment]
> @pvev Thanks for taking care of conflicts.

no worries, but there is some problems with the functionality, I will check what happened and will fix it. Will let you know when the new changes are ready. Thanks!

**Review by stevemudie — APPROVED** [review]
Looks good! Worked as expected.

**Pull request merged**
