### PR TITLE
Fix post component merge errors and bugs

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR fixes some UI bugs and e2e test failures that got introduced after merging the post component refactor. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50169
https://mattermost.atlassian.net/browse/MM-50196
https://mattermost.atlassian.net/browse/MM-50205
https://mattermost.atlassian.net/browse/MM-50319

#### Release Note
```release-note
Fix post component related errors
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Are you including [Forward Message ticket](https://mattermost.atlassian.net/browse/MM-50172) in this PR?
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/298090-3199772-onprem-ent-webapp-pr-12148-mm-ee-test:3199772/mochawesome.html) looks good 
The only difference I am seeing are 3 Messaging tests that are not failing on [master](https://mattermost-cypress-report.s3.amazonaws.com/298178-onprem-ent-master-mm-ee-test:test/mochawesome.html)
MM-T90, MM-T93 and MM-T113

**Comment by nevyangelova** [comment]
@jgilliam17 the Forward messages e2e test is a bit more complicated, in part its including issues with the new menus as well, so it will take a big longer to debug. However the menu isn't obstructed in the UI its just that cypress cant bypass some selectors.

I tried multiple ways but I can't repro the new messaging tests locally :(

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @nevyangelova for looking into - this looks good to merge then.

**Pull request merged**
