### PR TITLE
[MM-21076] Improve dropdown menu wrapping behavior

### PR DESCRIPTION
**Pull request by bradjcoughlin**
#### Summary
* added new element to primary text to assist with wrapping when help text is present
* reverted some recent changes to make `<span>`s block elements again
* minor tweaks to spacing to accommodate for element structure changes
* **Updated with this PR**: Add minimum width to prevent short (i.e. two words) menu items for wrapping

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21076

#### Screenshots
Screen Shot 2019-12-16 at 8 58 27 PM
Screen Shot 2019-12-16 at 8 59 11 PM
Screen Shot 2019-12-16 at 8 59 37 PM

### CODE REVIEW

**Comment by amyblais** [comment]
@bradjcoughlin Is this cherry-picked?

**Comment by bradjcoughlin** [comment]
@amyblais yes, thanks

**Pull request merged**
