### PR TITLE
Multiple Bug fixes

### PR DESCRIPTION
**Pull request by asaadmahmood**
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
PLT-7977 - Emoji icon overlapping in edit modal
PLT-7965 - Channel header underline fix
PLT-7985 - Fixing more unreads indicator text
PLT-7282 - Adding @ sign before username in modals
PLT-6828 - Hiding url links for clickable elements
PLT-7928 - Pinned post button position fix
PLT-8000 - Long DM name not truncating
PLT-8033 - Fixing manage members button on mobile

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7977
https://mattermost.atlassian.net/browse/PLT-7965
https://mattermost.atlassian.net/browse/PLT-7985
https://mattermost.atlassian.net/browse/PLT-7282
https://mattermost.atlassian.net/browse/PLT-6828
https://mattermost.atlassian.net/browse/PLT-7928
https://mattermost.atlassian.net/browse/PLT-8000
https://mattermost.atlassian.net/browse/PLT-8033

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
@asaadmahmood 

1) Flagged post icon shows URL when RHS is open
image

2) Team icons still show a URL on hover in the desktop app (messaged you on pre-release since it's part of a separate ticket) 

3) In Integrations > Incoming Webhooks (and other integration pages), the "Edit" button still shows a URL on hover 

4) Channel header not underlined when it's not set and you're hovering over "Add a channel description"
image

**Comment by asaadmahmood** [comment]
1. Fixed.
2. Not related to my changes, will probably be addressed by Saturn.
3. The edit link actually has a valid href attribute rather than just a "#".
4. Done.
5. Done.

**Comment by asaadmahmood** [comment]
1. Fixed.
2. Not related to my changes, will probably be addressed by Saturn.
3. The edit link actually has a valid href attribute rather than just a "#".
4. Done.
5. Done.

**Comment by asaadmahmood** [comment]
Hey @jasonblais have a look.

**Comment by jasonblais** [comment]
@asaadmahmood Above fixes look good, except the channel dropdown is misplaced now

image

**Pull request merged**
