### PR TITLE
MM-30378: Cypress/E2E: Automate backlogs - Messaging > Copy/Paste Multiple Posts (1 test case)

### PR DESCRIPTION
**Pull request by catalintomai**
#### Summary
Cypress/E2E: Automate backlogs - Messaging > Copy/Paste Multiple Posts (1 test case)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30378

### CODE REVIEW

**Comment by catalintomai** [comment]
@saturninoabril 
For Steps #2, #3 and #4, fwik, Cypress does not offer support for native copy/paste ( see https://github.com/cypress-io/cypress/issues/2386) , support for access to the native browser menu and support for right-click access to native context menu. The current PR code does selection + copy/paste but not using the copy/paste shortcuts or using the other native browser ways. Given the limitations, I'm not sure what are the next steps here. 
cc: @DHaussermann

**Comment by saturninoabril** [comment]
Thanks @catalintomai for trying. I've ran the tests and looked good that it's able to select the elements (screenshot). However, I'm afraid we can't fully satisfy the test requirement. With that being said, I'll vote for this test case to be "cannot be automated by Cypress". Maybe this is something we can allot/remain to RFQA or manual tests.

Screen Shot 2020-12-07 at 4 37 45 PM

**Comment by catalintomai** [comment]
Thanks @saturninoabril for validating this. I'll close this PR, do you want me to update https://mattermost.atlassian.net/browse/MM-30378 to N/A than?

**Comment by saturninoabril** [comment]
@catalintomai Yes, please. For MM-T2825, I've already set Cypress status to "N/A" and add comment that it can't be automated with Cypress.

**Pull request closed without merging**
