### PR TITLE
[MM-27231]: cypress test for MM-T1837

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Automate MM-T1837: Bot DM channels display a normal Header

#### Ticket Link

- Part of https://mattermost.atlassian.net/browse/MM-27231

### CODE REVIEW

**Comment by ashishbhate** [comment]
AFAIK, a bot a from a plugin is the same as a "normal" bot, so there's only one test here.

**Comment by josephbaylon** [comment]
@ashishbhate I think step 2 refers to uploading/enabling a plugin and checking if the bot from that plugin also works. It may have the same expectation but the creation flow is a bit different, e.g.

```
        // # Upload and enable "matterpoll" plugin
        cy.apiUploadPlugin('com.github.matterpoll.matterpoll.tar.gz').then(() => {
            cy.apiEnablePluginById('com.github.matterpoll.matterpoll');
        });
```

then check the DM for `@matterpoll`

**Comment by ashishbhate** [comment]
@josephbaylon updated with a test for a bot from a plugin.

**Review by josephbaylon — APPROVED** [review]
LGTM. Just minor title changes to match TM4J. Thanks @ashishbhate !!

**Review by nevyangelova — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
LGTM 👍

**Pull request merged**
