### PR TITLE
Cypress/E2E: Fix failed tests from cloud run

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix failed tests from cloud run

#### Screenshots
Screen Shot 2021-07-13 at 6 26 13 AM
Screen Shot 2021-07-13 at 6 31 44 AM
Screen Shot 2021-07-13 at 6 35 38 AM
Screen Shot 2021-07-13 at 6 40 24 AM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Tested and passed.

**Comment by saturninoabril** [comment]
Added one more fix for MM-T89 from release build.
Screen Shot 2021-07-13 at 10 11 06 AM

**Review by furqanmlk — COMMENTED** [review]
Thanks @saturninoabril 

All tests passed except one, 
image

image

image

image

image

**Comment by saturninoabril** [comment]
Thanks for testing @furqanmlk! The interesting item is the "New Messages" line. I'm not sure what is expected there. I tried here several times but I couldn't reproduced the one you're seeing and it's consistently passing on me. Let's get this in and I'll keep an eye of it.

**Review by furqanmlk — APPROVED** [review]
Sure @saturninoabril

**Comment by saturninoabril** [comment]
Got passing test on [recent run](https://mm-cypress-report.s3.amazonaws.com/336734634-6b9f418-master-e20-prod-mattermost-enterprise-edition:master/mochawesome.html). But will keep on checking.
Screen Shot 2021-07-14 at 4 57 50 PM

**Pull request merged**
