### PR TITLE
[MM-28207] Require channel id for textbox and post markdown components

### PR DESCRIPTION
**Pull request by fmunshi**
#### Summary
- Fixes broken preview post functionality where channel id was not passed and modified existing component definitions to require a channelId as all these components always have a channelId (unless im missing something)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28207

### CODE REVIEW

**Comment by hmhealey** [comment]
Could we pass the channel ID to the post preview instead? I think the `CreatePost` component and co should all be attached to a channel.

**Comment by fmunshi** [comment]
@hmhealey I modified a couple of component definitions to make `channelId` a required prop here

I think I got it all but let me know if you think I missed something...

**Review by isacikgoz — APPROVED** [review]
Looks good from my side 👍

**Review by hmhealey — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
LGTM

**Pull request merged**
