### PR TITLE
[MM-29407]-Migrate-string-refs

### PR DESCRIPTION
**Pull request by sridhar02**
#### Summary
change this.refs into React.createRef
#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/15846

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks!

**Review by sudheerDev — APPROVED** [review]
LGTM

**Review by jgilliam17 — APPROVED** [review]
Thank you @sridhar02 
Tested, looks good to merge.
- Verified/tested around channel header modal, add new, edit, focusing/unfocusing text box, saving etc.  - as expected. 
@Willyfrog Can you please help merge? Thanks.

**Pull request merged**
