### PR TITLE
MM-44420 - remove 14 days hardcoded values

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR removes the 14 days hardcoded value and uses the feature flag isCloudFreeEnabled to determine if the max value is 14 days trial period or 30 days trial period.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44420

#### Related Pull Requests
n/a

#### Screenshots

https://user-images.githubusercontent.com/10082627/170384033-9c460519-bdb3-443f-9ebe-f6ce13646c99.mp4

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by julmondragon — APPROVED** [review]
Looks good!

**Comment by stevemudie** [comment]
@pvev This worked as expected (as I'm only seeing the 30 day banner now) but there was a significant delay between starting the trial and the banner showing up.

More importantly I was able to click the upgrade button then click the `Try free for 30 days` button in the Enterprise column which brought the start trial modal back up etc. Then I was able to click the waffle menu and open the start trial modal there as well.

I was prepping to record a video when it finally showed everything properly.

**Comment by pvev** [comment]
> @pvev This worked as expected (as I'm only seeing the 30 day banner now) but there was a significant delay between starting the trial and the banner showing up.
> 
> More importantly I was able to click the upgrade button then click the `Try free for 30 days` button in the Enterprise column which brought the start trial modal back up etc. Then I was able to click the waffle menu and open the start trial modal there as well.
> 
> I was prepping to record a video when it finally showed everything properly.

hi @stevemudie thanks for the feedback. What you see is a known bug related to CWS cache. This ticket covers it https://mattermost.atlassian.net/browse/MM-44509

**Review by stevemudie — APPROVED** [review]
Thanks @pvev This is all set then!

**Pull request merged**
