### PR TITLE
[MM-30066] Allow sidebar category button width to grow and shrink as needed

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
When a category name is too long, the label will not shrink to fit the NEW icon or the category menu on hover. This PR styles the button so that it will shrink when necessary and grow when needed.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30066

### CODE REVIEW

**Comment by esethna** [comment]
Thanks Devin, no need to add me on bug PRs 👍

**Review by calebroseland — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
@devinbinnie Server failed to update, can you please check? Thanks.
For some reason the existing server fails to enable exp.sidebar in system console

**Comment by devinbinnie** [comment]
@jgilliam17 Seems to be working now.

**Comment by jgilliam17** [comment]
Thanks @devinbinnie 
Tested, looks good to merge.
- Verified long custom category name truncates on hover to reveal 3-dot menu.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
