### PR TITLE
MM-40056: fixes scrolling to selected thread

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Currently when you select a thread and then load more items via infinite
loading (scrolling to the bottom) it will scroll to the selected item
when threads are fetched.
This commit fixes that by removing the thread ids (`ids`) from the
`useEffect` dependencies array.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-40056

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Comment by jgilliam17** [comment]
@koox00 I'm getting a server error when trying to post a reply. Asked SRE support to take a look at the issue. 
This is happening on multiple PR test servers for me, not just this PR.

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Tested, looks good to merge.
- Verified scrolling long threads is as expected.
-  [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/109647-300348b-onprem-ent-webapp-pr-9649-mm-ee-test:300348b/mochawesome.html) looks good, no PR related failures. I re-tested three test cases that failed/differ from master (MM-T952, MM-T453_2 & Handle new post test case) all passing when manually tested.

**Pull request merged**
