### PR TITLE
[MM-42341] Reset password error message

### PR DESCRIPTION
**Pull request by emmyni**
#### Summary
Remove the error message that displays when the inputted password is less than 5 characters so it only relies on the backend error message.

#### Ticket Link
[MM-42341
](https://mattermost.atlassian.net/browse/MM-42341)

#### Screenshots

|  before  |  after  |
|----|----|
| image |image|

#### Release Note

```release-note
Remove the error message on the Reset Password page that appears when the inputted password is fewer than 5 characters .
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Review by Afsoon — APPROVED** [review]

**Comment by nickmisasi** [comment]
@annelieseklein gentle ping on this one - just want a once over on the new UX here!

**Comment by annelieseklein** [comment]
@emmyni we should update the password requirement formatting here to match what is in the singup flow, but i'll approve this

**Review by annelieseklein — APPROVED** [review]

**Comment by emmyni** [comment]
> @emmyni we should update the password requirement formatting here to match what is in the singup flow, but i'll approve this

@annelieseklein Is that a future change or should I add it to this?

**Comment by annelieseklein** [comment]
@emmyni let me get back to you on Monday - I need to check with @dontoisme who is out today on what was happening with the A/B test in the sign up flow

**Comment by emmyni** [comment]
@annelieseklein Are there any updates about this?

**Pull request merged**
