### PR TITLE
PLT-8056 Minor text updates for DND status

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Minor text updates for DND status. @asaadmahmood can you help with the spacing/font size for status dropdown?

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-8056

### CODE REVIEW

**Comment by esethna** [comment]
Adding @crspeller to help look into the spinmint issue

**Comment by esethna** [comment]
Thanks Joram, I've alerted @asaadmahmood on pre-release so we can get the styling updates in as soon as he's back on,

**Comment by asaadmahmood** [comment]
@esethna Submitted my changes. The status dropdown intentionally has a different padding/width due to the help text, and no sector dividers.

**Comment by jwilander** [comment]
@esethna should I change the base to `release-4.4` so this is included in the next RC?

**Comment by esethna** [comment]
@jwilander yes please!

**Pull request merged**
