### PR TITLE
[MM-49983] - Cloud annual pricing modal UI fixes

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Makes fixes to UI since introduction of yearly plans to pricing modal

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49983
https://mattermost.atlassian.net/browse/MM-49955

#### Screenshots
Free (non-admin)
----
Screenshot 2023-02-20 at 17 20 01

Free (admin)
----
Screenshot 2023-02-20 at 17 30 25

Pro monthly (non-admin)
----
Screenshot 2023-02-20 at 17 40 41

Pro monthly (admin)
----
Screenshot 2023-02-20 at 17 31 57

Pro annual (non-admin)
----
Screenshot 2023-02-20 at 17 23 52

Pro annual (admin)
---
Screenshot 2023-02-20 at 17 34 30

Enterprise (non-admin)
----
Screenshot 2023-02-20 at 17 26 14

Enterprise (admin)
----
Screenshot 2023-02-20 at 17 28 02

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @AGMETEOR !

**Comment by yasserfaraazkhan** [comment]
Hi @AGMETEOR , 
all tests passed except 1 where `CURRENTLY ON MONTHLY BILLING` text is not showing up. ([link](https://automation-dashboard.vercel.app/cycle/305274))

**Review by marianunez — APPROVED** [review]
LGTM. Thanks @AGMETEOR! I was trying to get test servers going to take a peek but they don't seem to be going though

**Pull request merged**
