### PR TITLE
User profile photo in sidebar

### PR DESCRIPTION
**Pull request by VitaliyBratyshov**
#### Summary
Displaying custom images in the channel list

#### Screenshots

image
image
image

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @VitaliyBratyshov!

Note that we are doing some major sidebar overhaul work right now, so this may conflict. See details: https://mattermost.com/blog/dev-sneak-peek-experimental-sidebar-features/

image

Adding @matthewbirtch from the design team, thoughts on incorporating profile pics in the LHS?

**Comment by matthewbirtch** [comment]
> Adding @matthewbirtch from the design team, thoughts on incorporating profile pics in the LHS?

It's an interesting idea, but here are the problems I see:
1. The alignment of the channel names. 
2. The avatars would have to be much smaller to make this work well
3. It adds a lot of visual noise to the sidebar (which is already quite busy)
4. The avatar combined with the status makes it even more busy

image


I personally think we should table this until the new sidebar changes soak in (eric referenced above). At that point, the design team could take a look and see if this is something we want to do. I can create a UX ticket for us to review.

**Comment by esethna** [comment]
Works for me, thanks for the UX input Matt. @valentijnnieman given the above, let's close this for now. We may revisit after the new sidebar changes are generally available. Appreciate the contribution, feel free to pick any others from our queue: 

https://github.com/mattermost/mattermost-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22Up+For+Grabs%22+label%3A%22Area%2FEnd+User+Feature%22

**Pull request closed without merging**
