### PR TITLE
MM-23756 Always show unread DMs and GMs in new sidebar

### PR DESCRIPTION
**Pull request by hmhealey**
The relevant changes for this are in the accompanying redux PR

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23756

#### Related Pull Requests
https://github.com/mattermost/mattermost-redux/pull/1114

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thanks @hmhealey 

This appears fixed when new sidebar is set on ON in acct. settings, but DM/GMs are not added to LHS when this feature is set to OFF.

**Comment by hmhealey** [comment]
@jgilliam17 Huh, good catch. I thought this issue was exclusive to the new sidebar. I'll take a look.

**Comment by jgilliam17** [comment]
Note: When system setting is "Enabled Default On" and user changes Account Setting for Experimental sidebar to Off.
I retested this morning and saw the DMs are showing up late.
Notification for desktop and browsers are received in real time, but the actual DM on LHS is late and only comes after window is focused.

**Comment by hmhealey** [comment]
@jgilliam17 I haven't been able to track down the root cause of this, but I'm going to separate the ticket into two. This fixes the worse problem with the new sidebar (unread DMs never showing up), and I'm pretty sure the problem with the old sidebar is a long-running issue.

**Pull request merged**
