### PR TITLE
 [MM-27210] archived channels 4 III

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

final tests MM-T1714 & MM-T1715

**IMPORTANT**: this doesn't work at the time due to bug [https://mattermost.atlassian.net/browse/MM-31358](https://mattermost.atlassian.net/browse/MM-31358) which I found while creating the test. Once fixed, this test should run properly.

#### Ticket Link

[MM-27210](https://mattermost.atlassian.net/browse/MM-27210)

#### Related Pull Requests

https://github.com/mattermost/mattermost-webapp/pull/7205
https://github.com/mattermost/mattermost-webapp/pull/7191

### CODE REVIEW

**Comment by saturninoabril** [comment]
Thanks for the heads up. Will take a look once the said bug is fixed.

**Comment by emilyacook** [comment]
@Willyfrog hey there! I see the bug you linked has been resolved, let me know if you're able to get to this 🙂

**Comment by Willyfrog** [comment]
> @Willyfrog hey there! I see the bug you linked has been resolved, let me know if you're able to get to this 🙂

thanks for the heads up, I didn't notice the bug was resolved. I'll try to take a look at it later today.

**Comment by saturninoabril** [comment]
Please ping me again whenever ready for review. Thanks @Willyfrog!

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
