### PR TITLE
add reused hooks. Refactor pricing modal opening to consistently use …

### PR DESCRIPTION
**Pull request by neallred**
…hook

#### Summary
Supports a couple other tickets (https://mattermost.atlassian.net/browse/MM-43609 , https://mattermost.atlassian.net/browse/MM-43595), and helps us be consistent for the many places we are opening the pricing modal.

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]
HOOKS FOR DAYS
<br><br><br><br><br><br><br><br>






lgtm

**Review by marianunez — COMMENTED** [review]
Not sure if this is in scope of this PR, is the limits showing in the menu item should be showing ? In the test server I added 4 integrations (80%) and doesn't seem to show anything yet

**Comment by neallred** [comment]
> Not sure if this is in scope of this PR, is the limits showing in the menu item should be showing ? 

Nope, that is part of https://github.com/mattermost/mattermost-webapp/tree/MM-43595 . This PR supports that work, however.

**Review by marianunez — APPROVED** [review]
Thanks @neallred!

**Pull request merged**
