### PR TITLE
[MM-44873] Fix button inside of button in global header

### PR DESCRIPTION
**Pull request by cyrilzhang-mm**
#### Summary

The original problem was that the profile picture button in the global header was not announcing the user's status. The previous attempt to fix this resulted in a console warning due to nesting a button inside of a button. This PR adds the status to the outer button label and makes the inner button into a div. 

#### Ticket Link

[Jira ticket](https://mattermost.atlassian.net/browse/MM-44873)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @cyrilzhang-mm 
Tested on Windows using JAWS reader; verified user status is announced as expected -  looks good to merge (pending e2e report).

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
