### PR TITLE
[MM-32401][MM-32450] Some style fixes for the sidebar

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
3 fixes are included in this PR:
- On mobile view, the width of the channels was not set on mobile view correctly. Have now been set to `290px`
- On desktop mobile view, the height of the channel menu element was too high. I've removed the specific height of the menu button element which should no longer be required now that we've switched the parent over to flexbox
- When dragging multiple channels, the count of channels was cutoff due to adding `overflow: hidden`. I've added `overflow: visible` to the dragging state of the channel so that it will show correctly.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32401
https://mattermost.atlassian.net/browse/MM-32450

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thanks @devinbinnie 
Looks good, I'll approve after dev reviews.
- Verified 3-dot icons lineup and vertical alignment(on desktop) in mobile view (and non-mobile, just in case).
- Verified channel count is not cutoff when dragging multiple channels.

**Review by nevyangelova — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by devinbinnie** [comment]
@jgilliam17 Dev reviews are complete.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
