### PR TITLE
MM-30366: Test group mention synced channel.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Tests that mentioning a group that is not associated to a synced channel doesn't prompt to add the group members.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30366

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Review by furqanmlk — COMMENTED** [review]
@mkraft 
One test case is failing for me, can you please confirm

image

**Comment by mkraft** [comment]
> @mkraft
> One test case is failing for me, can you please confirm
> 
> image

Is that the test I added, namely `MM-T2443 - Group Mentions when Channel is Group Synced` or is that a pre-existing failure? If I'm not mistaken that test was failing before?

**Comment by hahmadia** [comment]
@furqanmlk 
(Martin has responded, not sure if you got notified so I am tagging you)

**Comment by furqanmlk** [comment]
> @furqanmlk
> (Martin has responded, not sure if you got notified so I am tagging you)

@hahmadia 
For some reason I am getting two test cases failed.
Let me add other SDET to double check

**Review by furqanmlk — APPROVED** [review]
Test Case passed , all look good to me

**Pull request merged**
