### PR TITLE
MM-32131: Fix header alignment when channel has guests

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Fix header alignment when channel has guests. Now works on chrome and firefox.

#### Ticket Link
[MM-32131](https://mattermost.atlassian.net/browse/MM-32131)

#### Screenshots
imagen

### CODE REVIEW

**Review by calebroseland — COMMENTED** [review]
While we're here, could we remove the `margin-right` on `.channel-header__info .has-guest-header` that makes the separator-dot not centered?

**Review by reflog — APPROVED** [review]

**Comment by jespino** [comment]
@calebroseland done! :)

**Review by calebroseland — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
LGTM!

**Pull request merged**
