### PR TITLE
[MM-36481] Fix thumbsup emoji parsing to support skin tones

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

Thumbs up wasn't being skin toned properly, updated the regex to support that.

#### Ticket Link

[MM-36481](https://mattermost.atlassian.net/browse/MM-36481)

#### Related PRs

- Server https://github.com/mattermost/mattermost-server/pull/17846

#### Screenshots
Screen Shot 2021-06-28 at 19 48 16

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Comment by nevyangelova** [comment]
approved but we need to fix the tests.

**Comment by Willyfrog** [comment]
> approved but we need to fix the tests.

yeah, I was on it, but my laptop is slow running the tests, so it took more running them than actually fixing 😓 

anyway that's done now

**Review by jgilliam17 — APPROVED** [review]
Thanks @Willyfrog 
Tested, looks good to merge.
- Verified thumbsup emoji renders in all available skin tones.

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
@Willyfrog Leaving this to you to merge since I'm not 100% sure if it requires the server changes as well.

**Comment by Willyfrog** [comment]
no they don't I related them as the `todo` in the other PR especified changing the strings that document available formats

**Pull request merged**
