### PR TITLE
MM-31646: Update Office instructions

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates instructions for creating an OAuth Application for Office 365.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31646

#### Screenshots
Screen Shot 2021-01-14 at 5 02 09 PM

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
All looks good  👍 
Test cases passed

image

**One small request**
`At the end of step #02 full stop is missing `

**Comment by hahmadia** [comment]
Hey @sbishel,
I've added the period at the end of step 2 as recommended by Malik and setting this to AutoMerge.

**Pull request merged**
