### PR TITLE
MM-44513: Non-square custom emoji overflow div when set as status

### PR DESCRIPTION
**Pull request by Ballista01**
#### Summary

This PR fix the problem that non-square custom emojis overflow their <code>&lt;span&gt;</code>.

Emojis are rendered in the  <code>emoticon</code> class that contains the <code>backgroundSize: size</code> property. It resizes the emoji only corresponding to the span width. So non-square taller emojis are chopped when they are resized and rendered. By changing the property to <code>backgroundSize: contain</code>, height and width are both considered when rendered. All emojis can be rendered properly now.

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/20264#event-6672695118

https://mattermost.atlassian.net/browse/MM-44513

#### Related Pull Requests

NONE

#### Screenshots

|  before  |  after  |
|----|----|
| overflowed_emoji | fixed_status_pop_up |
|  | fixed_channel_chat |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by jgilliam17** [comment]
@hmhealey Can you please check and approve one workflow? Thanks 🙂

**Comment by hmhealey** [comment]
> @hmhealey Can you please check and approve one workflow? Thanks 🙂

Done

**Review by jgilliam17 — APPROVED** [review]
Thanks @Ballista01 
Tested, looks good to merge.
- Verified custom emoji no longer overflows when set as status.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/207904-13acfe1-onprem-ent-webapp-pr-10433-mm-ee-test:13acfe1/mochawesome.html) looks good, no PR related failures.

**Pull request merged**
