### PR TITLE
Upgrade Web app to React 17 (#11558)

### PR DESCRIPTION
**Pull request by hmhealey**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34187

#### Related Pull Requests
#11558

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
Should we wait for the other 2 PRs before we merge this?

**Comment by hmhealey** [comment]
https://github.com/mattermost/mattermost-server/pull/21617 should probably be merged first, but the other one (the one for patching React DOM) isn't needed since, as far as I know, every marketplace plugin has been updated automatically and won't need that that extra setting. That setting's only needed for people who are using old versions of our plugins or custom plugins that haven't been updated.

**Comment by nevyangelova** [comment]
https://mattermost-cypress-report.s3.amazonaws.com/268421-00712dc-onprem-ent-webapp-pr-11670-mm-ee-test:00712dc/mochawesome.html report seems to be the same as previous runs

**Comment by hmhealey** [comment]
I'm just updating this branch and then I'll be merging this in shortly

**Comment by amyblais** [comment]
@hmhealey I think we should wait for this PR https://github.com/mattermost/mattermost-server/pull/21617. What is the impact on cloud customers if plugins are not ready?

**Comment by hmhealey** [comment]
Right. This'll break those prepackaged plugins if that other PR isn't in

**Comment by amyblais** [comment]
@hmhealey We can consider cherry-picking this to ``release-7.6`` branch once it has been cut, but I think it is too risky to merge this in for Dec 1st Cloud release at this point.

**Pull request closed without merging**
