### PR TITLE
MM-12150 - Updating css for IE11 navbar

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-12150 - Updating css for IE 11 navbar

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12150

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@enahum @asaadmahmood I tested the spinmint on IE11 mobile view and it looks good (also checked on Chrome to make sure still looks good there as well). Removing the QA Review label. 👍

**Comment by sudheerDev** [comment]
@asaadmahmood One thing i see that zoom icon is misplaced still. Is that part of the fix?

screen shot 2018-10-03 at 7 07 09 pm

**Comment by asaadmahmood** [comment]
@sudheerDev what is the screensize at which it is misplaced? It should not be, because I have hidden it below 768px sizes.

**Comment by sudheerDev** [comment]
@asaadmahmood Needs a rebase

**Pull request closed without merging**
