### PR TITLE
Fix stretch for custom branding image in Safari on sign up page

### PR DESCRIPTION
**Pull request by phpfs**
#### Summary
This PR applies the fix known from https://github.com/mattermost/mattermost-webapp/pull/10862 (login page) now also for the sign up page.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46522

#### Screenshots

|  before  |  after  |
|----|----|
| before | after |

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by julmondragon — APPROVED** [review]
Looks good! Thanks!

**Review by matthewbirtch — APPROVED** [review]

**Review by pvev — APPROVED** [review]
LGTM! Thanks @phpfs :shipit:

**Review by stevemudie — APPROVED** [review]
Tested on Safari and on Chrome. Looks good @phpfs!

**Pull request merged**
