### PR TITLE
Revert "Revert "MM-24072 - Position the autocomplete popover relative…

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
Adds back original [PR7082](https://github.com/mattermost/mattermost-webapp/pull/7082) after being reverted because of [MM-31616](https://mattermost.atlassian.net/browse/MM-31616).

PR [7285](https://github.com/mattermost/mattermost-webapp/pull/7285) Must be reviewed first and once approved and merged, this one can be added back again to Master.

### CODE REVIEW

**Comment by hmhealey** [comment]
Is there anything changed in this relative to the original PR, or are all the changes in https://github.com/mattermost/mattermost-webapp/pull/7285?

**Comment by pablovelezvidal** [comment]
> Is there anything changed in this relative to the original PR, or are all the changes in #7285?

No changes relative to the original PR. All the changes related to the reported issue that caused the original reason to revert are in the PR [#7825](https://github.com/mattermost/mattermost-webapp/pull/7285)

**Review by hmhealey — APPROVED** [review]

**Review by crspeller — APPROVED** [review]
Nothing to review just a revert.

**Comment by crspeller** [comment]
@lindalumitchell The testing here is making sure https://mattermost.atlassian.net/browse/MM-31616 is fixed by https://github.com/mattermost/mattermost-webapp/pull/7285

**Review by lindalumitchell — APPROVED** [review]

**Pull request merged**
