### PR TITLE
[MM-41722] Add the upgrade enterprise sales reason

### PR DESCRIPTION
**Pull request by Afsoon**
#### Summary
Pre-fill the contact us form when the admin click `Contact Sales` on upgrade enterprise.

#### Ticket Link
https://mattermost.atlassian.net/jira/software/c/projects/MM/boards/106?modal=detail&selectedIssue=MM-41722&assignee=62ed333d48e310e672967cc8

#### Screenshots
Pre-trial pricing modal clicking contact sales
pre-trial

Post-trial pricing modal clicking contact sales
post-trial

#### Release Note
```release-note
Bug fix where clicking contact sales hasn't prefilled the reason of contact to sales.
```

### CODE REVIEW

**Review by emmyni — APPROVED** [review]
Looks good @Afsoon :)

Just wondering, should this button (circled) also lead to a form with the upgrade enterprise sales reason filled out?
image

**Comment by Afsoon** [comment]
> Looks good @Afsoon :)
> 
> Just wondering, should this button (circled) also lead to a form with the upgrade enterprise sales reason filled out? image

You are right. The banner should be updated as it is related. Thanks, @emmyni!

**Review by AGMETEOR — APPROVED** [review]

**Comment by Afsoon** [comment]
Gentle ping @stevemudie for qa review.

**Review by stevemudie — APPROVED** [review]
Worked as expected @Afsoon!

**Pull request merged**
