### PR TITLE
Migrate string refs of reset password modal

### PR DESCRIPTION
**Pull request by sridhar02**
#### Summary

Migrate errorMessage string ref to new ref syntax

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/16034

### CODE REVIEW

**Review by Willyfrog — CHANGES_REQUESTED** [review]
thanks for the PR! one minor thing: can you also remove the comments about `react/no-string-refs`?

**Review by Willyfrog — APPROVED** [review]
👍

**Review by agarciamontoro — APPROVED** [review]
Thank you for your contribution, @sridhar02! This looks good to me :tada:

**Review by jgilliam17 — APPROVED** [review]
Thank you @sridhar02 
Tested, looks good to merge.
- Verified reset password modal in sys. console - no change in functionality.
@agarciamontoro Can you please help merge? Thanks 🙂

**Pull request merged**
