### PR TITLE
MM-21639 - Adding granular margin/padding css

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-21639 - Adding granular margin/padding css

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21639

### CODE REVIEW

**Comment by jespino** [comment]
@asaadmahmood why is this 5.21? 5.21 should be bug fixes only, I think. It is necessary?

**Comment by asaadmahmood** [comment]
@jespino we can move it to 5.22.

**Comment by andrewbrown00** [comment]
@asaadmahmood throwing this here as a reminder, ignore if you've already added the following:

We talked about adding classes for the when the `margin` or `padding` is the same on all sides.

**Comment by asaadmahmood** [comment]
@andrewbrown00 Yup, it's added :).

**Pull request merged**
