### PR TITLE
[MM-41917] Use feature flag when fetching thread bindings

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR uses the `appsEnabled` selector to determine whether we should fetch thread bindings. Otherwise, we unnecessarily try to communicate with the Apps plugin, resulting in 404s for `plugin not found`.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-41917

#### Related Pull Requests

https://github.com/mattermost/mattermost-mobile/pull/6018

```release-note
The web app no longer attempts to fetch thread bindings when the AppsEnabled feature flag is false
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Confirmed the binging call does not happen on reply threads when the Feature Flag is False
- Tested with and without Collapsed Reply Threads Enabled
The issue no longer reproduces

LGTM!

**Comment by DHaussermann** [comment]
@amyblais Please note that this bug fix would also be valuable for the March 30th Cloud and v6.6 releases 

cc @mickmister

**Pull request merged**
