### PR TITLE
Cypress/E2E: Promote tests to production

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Promote tests to production

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM.

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril
All good !

**Review by prapti — APPROVED** [review]
Thank you Saturn!
One concern here is, not all the tests being promoted here have strictly been passing for the last 5 consecutive runs. They won't cause any major problems since most have passed at least the last 3 runs, but if they fail in production on Friday, do you want me to demote them to unstable again?

**Comment by saturninoabril** [comment]
Thanks for looking Prapti! Sounds good to me.

**Pull request merged**
