### PR TITLE
E2E/Playwright: Initial setup for Boards

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Added [MM-T4274](https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/boards/board-creation-and-set-up/MM-T4274.md) (functional) test for Boards
- Added visual tests for Boards
- Reorganized folder structure to separate functional and visual testing per product. Note that visual testing is recommended to be separated so it could run in separate run group.

Others:
- Added Playwright `test-slomo` npm script to easily follow along test flow in slow motion

Screenshot 2023-02-21 at 10 39 18 PM

#### Ticket Link
none

#### Related Pull Requests
- Waiting for https://github.com/mattermost/mattermost-webapp/pull/12213 to merge

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by saturninoabril** [comment]
@nevyangelova @sbishel @mvitale1989 For your reviews.

**Comment by nevyangelova** [comment]
@saturninoabril I am not familiar with playwright but do we need to commit the screenshots, or do we wanna store them as artifacts?

**Comment by saturninoabril** [comment]
Yes, it's going to be committed in a repo as golden screenshots. There are two ways for our visual testing: one is via committed screenshots where any committer/contributor would be able to validate their changes, and the other is via percy.io where it would be most useful during release testing. Both will be used in our testing process.

**Review by nevyangelova — APPROVED** [review]
From my perspective (and limited knowledge) looks good to me :)

**Review by sbishel — APPROVED** [review]
LGTM - Only question is if the "What's new" banner should be closed for most boards testing, since most users would have it closed.

**Comment by saturninoabril** [comment]
Thanks and good point! I've removed the banner by default in the recent push - https://github.com/mattermost/mattermost-webapp/pull/12237/commits/c25a61ba50c3fbc59568353d4d2688d00cfbe19f

**Review by mvitale1989 — APPROVED** [review]
LGTM, thanks Saturn!

**Pull request merged**
