### PR TITLE
MM-27559 - Clicking 'Create a playbook' button does nothing on MM-Des…

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Allowing any internal-mattermost link to open within the app.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-27559

#### Screenshots
2020-08-14 at 1 52 PM

### CODE REVIEW

**Comment by amyblais** [comment]
@ali-farooq0 FYI that Jelena is OoO for now (just mentioning in case this is time sensitive for v0.6)

**Comment by ali-farooq0** [comment]
Thanks @amyblais. No, not time sensitive, however I'd like to get this in asap. How is covering for Jelena?

**Comment by amyblais** [comment]
Unfortunately I'm not sure who is covering her, maybe Linda or Dean can help.

**Comment by ali-farooq0** [comment]
Hey @stevemudie are you able to help out with the QA request above as a backup to Jelena?

**Pull request merged**
