### PR TITLE
[MM-27815] e2ecypress test automation of MM-T554

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Automates MM-T554
- Adds a missed check for MM-T552
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-27815

### CODE REVIEW

**Comment by ashishbhate** [comment]
@srkgupta I've added you as reviewer because Ogi is OOO

**Comment by ashishbhate** [comment]
@josephbaylon I've added a reply highlight check for this test and a previous test.

**Review by srkgupta — APPROVED** [review]
Thanks @ashishbhate. The test LGTM and is working fine. Approving the PR.

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
