### PR TITLE
PLT-7298 Added Edit Account Settings link to bottom of your own profile popover

### PR DESCRIPTION
**Pull request by santos22**
#### Summary

- Added "Edit Account Settings" link to bottom of your own profile popover (this link only appears for your own account)
- Clicking the link opens the Mattermost Account Settings, performing the same action as CTRL/CMD+SHIFT+A

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7298
https://github.com/mattermost/mattermost-server/issues/7113

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by santos22** [comment]
Hi @esethna - thanks for the feedback! I will go ahead and make those changes - would you know where to find the icon for account settings? I noticed the profile popover email has a plane icon next to it because the className is set to `fa fa-paper-plane` but I wasn't able to find anything for the account settings icon.

**Comment by esethna** [comment]
Thanks @santos22, I'm adding @asaadmahmood who should be able to help answer that.

**Comment by asaadmahmood** [comment]
@santos22 You can just use the [fa-cog](http://fontawesome.io/icon/cog/) icon.

**Comment by jasonblais** [comment]
@santos22 The build most likely failed due to a race condition / unit test that wasn't related to your changes.

He probably closed and re-opened this PR to re-trigger the build (and looks like it now passed)

**Comment by santos22** [comment]
@jasonblais was hoping this would make November's release 😄

**Comment by jasonblais** [comment]
@crspeller Can you help review this next week so we can merge it in time for v4.4?

**Pull request merged**
