### PR TITLE
Migrate 'components/rhs_comment' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by fullstackguyhere**
#13717

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13717

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Comment by devinbinnie** [comment]
@fullstackguyhere So it looks like we'll have to migrate the connectors for `DotMenu` and `FileAttachmentListContainer`, since both are expect a bunch of properties only passed in by the redux connector.

If you'd like you can migrate both components, just let me know so I can assign the proper issues to you.

Thanks for all your work on this :)

**Comment by fullstackguyhere** [comment]
Yeah, sure. I will migrate them. If there are more, I will let you know. @devinbinnie

**Comment by fullstackguyhere** [comment]
@devinbinnie
does the folder  __snapshots__  get created automaticall?

**Comment by fullstackguyhere** [comment]
Also @devinbinnie is there any reason type param from Post type has been used in the below test for Dot Menu? because I cannot see the type being used anywhere in the main component?

`test('should not have divider when able to edit or delete a system message', () => {
        const props = {
            ...baseProps,
            post: {
                ...baseProps.post,
                type: PostTypes.JOIN_CHANNEL,
            },
        };
        const wrapper = shallow(
            <DotMenu {...props}/>
        );

        expect(wrapper.find('#divider_post_post_id_1_edit').exists()).toBe(false);
    });`

**Comment by devinbinnie** [comment]
> @devinbinnie
> does the folder **snapshots** get created automatically? If so should I change them as well?

Snapshots are generated by our tests as a comparison against what the rendered output should look like vs. what it does. If there are changes to these files, that might be fine, but you'll want to take a look.
If you're having trouble determining why a snapshot changed, push up the changes and I can have a look.

> Also @devinbinnie is there any reason type param from Post type has been used in the below test for Dot Menu? because I cannot see the type being used anywhere in the main component?
> 
> ```
> test('should not have divider when able to edit or delete a system message', () => {
>         const props = {
>             ...baseProps,
>             post: {
>                 ...baseProps.post,
>                 type: PostTypes.JOIN_CHANNEL,
>             },
>         };
>         const wrapper = shallow(
>             <DotMenu {...props}/>
>         );
> 
>         expect(wrapper.find('#divider_post_post_id_1_edit').exists()).toBe(false);
>     });
> ```

It's possible it was leftover from an older version of the `DotMenu` component that needed to consume a `post` object. If the `DotMenu` component no longer accepts one, this test might need to be re-written.

**Comment by jasonblais** [comment]
@fullstackguyhere thanks for your contribution! Let us know if you have questions about the feedback from @devinbinnie above. Would be happy to help :)

**Comment by fullstackguyhere** [comment]
@jasonblais Sure. Currently, I am adding types for additional components used in rhs_comments as well. Will update the PR with my changes when done.

**Comment by hanzei** [comment]
@fullstackguyhere Just want to touch bases: Are you still planing to update the PR? Let me know if you need help.

**Comment by fullstackguyhere** [comment]
@hanzei Yes. I do plan to do that in some time.

**Comment by devinbinnie** [comment]
Closing this PR as inactive, @fullstackguyhere let us know if you plan to finish this up.

**Pull request closed without merging**
