### PR TITLE
[MM-19175] Added better tab navigation to Account/Team Settings

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
The TAB navigation for Account and Team Settings was lacking some robustness. This PR adds
1) Pressing ENTER on an already open section will focus the user to the first Edit button of the section
2) The first Edit is now highlighted properly
3) Fixed some sections not receiving proper focus on ENTER.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19175

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @devinbinnie 

I tested on the spinwick as follows:

1. Opened Account Settings modal and, using TAB to navigate, observed that tabbing sequence is as per [your comment on the ticket](https://mattermost.atlassian.net/browse/MM-19175?focusedCommentId=69550&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-69550) (i.e. through the sidebar first)

2. For your comment in 1) above, I am not seeing the focus move to the first Edit button of the section when hitting ENTER on an already open section. Instead, I see no focus on the Edit button and when I hit ENTER the first section on the right-hand-side opens to start editing.  (I'm not sure whether this is what you mean by "focus the user to the first Edit button"?) See .gif below.

account settings tabbing

3. The "first Edit button" is not highlighted (as per your comment in 2) above)

4. Can you let me know which sections were not receiving proper focus on ENTER (as per 3) above) so I can test that this is fixed?

**Comment by devinbinnie** [comment]
@lindy65 Pushed up a fix for the Edit button not focusing on ENTER (it was focusing it just wasn't showing the visual cue).

I don't recall which ones were working or not working in the past, I'd just test a random assortment since it should be working for all of them now and the fix is systematic. I'd also make sure the first Edit button element is always focused when a section is open.

**Comment by lindy65** [comment]
Thanks @devinbinnie 

I'm not seeing this fix - I don't see the outline highlight

> Pushed up a fix for the Edit button not focusing on ENTER (it was focusing it just wasn't showing the visual cue).

> I'd also make sure the first Edit button element is always focused when a section is open.

Do you mean that the "Edit button" should receive an outline highlight after hitting Enter after opening a sub-section or do you mean the "Edit button" should already have an outline highlight when a sub-section is opened?

**Comment by devinbinnie** [comment]
@lindy65 Can you hard reload your browser (Ctrl+F5)? I noticed I had to do that for this change, I'm not sure why though...

**Comment by Willyfrog** [comment]
closing as it is being included in #3965

**Pull request closed without merging**
