### PR TITLE
MM-38446 - theme color fix for tips next steps page plugins image

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
This PR adds the right color variable so the circles appearing in the plugins svg for the tips and next steps page are showing corrently in all the different theme colors.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38446

#### Screenshots
Before:
image-2021-09-09-08-11-42-829

After:

Denim:
Captura de pantalla 2021-09-23 a las 14 11 08

Saphire:
Captura de pantalla 2021-09-23 a las 14 11 45

Quarz:
Captura de pantalla 2021-09-23 a las 14 08 40

Indigo:
Captura de pantalla 2021-09-23 a las 14 12 35

Onyx:
Captura de pantalla 2021-09-23 a las 14 13 08

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by neallred** [comment]
Looks good from a code perspective. Should we pass in the background fill conditionally depending on if its a dark theme or a light theme so that dark themes have a light background and can still be seen?

**Comment by matthewbirtch** [comment]
@pablovelezvidal I'm not seeing the illustrations at all here
image

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal I'm not seeing the illustrations at all here
> image

That is what is shown for non first admin users, and according to the code, it is behaving as expected. It means, has no images.

**Comment by pablovelezvidal** [comment]
> Looks good from a code perspective. Should we pass in the background fill conditionally depending on if its a dark theme or a light theme so that dark themes have a light background and can still be seen?

right now we just use css var colors for it

**Comment by matthewbirtch** [comment]
> That is what is shown for non first admin users, and according to the code, it is behaving as expected. It means, has no images.

Oh, I see. Sorry, I didn't catch that detail. I'll login with the sysadmin user

**Comment by matthewbirtch** [comment]
@pablovelezvidal I think we might want to hardcode white in as a background color for a number of the fills. The illustrations don't work well on dark backgrounds.

I'll see if I can dig up the files where these illustrations originally exist and I can try to apply the hard-coded white fill where it makes sense for these illustrations

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal I think we might want to hardcode white in as a background color for a number of the fills. The illustrations don't work well on dark backgrounds.
> 
> I'll see if I can dig up the files where these illustrations originally exist and I can try to apply the hard-coded white fill where it makes sense for these illustrations

so, what about this pull request, is it still valid? @matthewbirtch ?

**Comment by matthewbirtch** [comment]
> > @pablovelezvidal I think we might want to hardcode white in as a background color for a number of the fills. The illustrations don't work well on dark backgrounds.
> > I'll see if I can dig up the files where these illustrations originally exist and I can try to apply the hard-coded white fill where it makes sense for these illustrations
> 
> so, what about this pull request, is it still valid? @matthewbirtch ?

It's still valid, but we need to hard code the svg fills so they work better on dark backgrounds. These specific illustrations don't work greatly on dark backgrounds.

I put together how I think it should look with dark bgs:

image

Here's the Figma file that shows this: https://www.figma.com/file/zFWaTNbuoB9IkPJKLoWmT5/MM-32771-Update-Tips-and-Next-Steps?node-id=807%3A23774

**Review by AGMETEOR — APPROVED** [review]

**Comment by pablovelezvidal** [comment]
> > > @pablovelezvidal I think we might want to hardcode white in as a background color for a number of the fills. The illustrations don't work well on dark backgrounds.
> > > I'll see if I can dig up the files where these illustrations originally exist and I can try to apply the hard-coded white fill where it makes sense for these illustrations
> > 
> > 
> > so, what about this pull request, is it still valid? @matthewbirtch ?
> 
> It's still valid, but we need to hard code the svg fills so they work better on dark backgrounds. These specific illustrations don't work greatly on dark backgrounds.
> 
> I put together how I think it should look with dark bgs:
> 
> image
> 
> Here's the Figma file that shows this: https://www.figma.com/file/zFWaTNbuoB9IkPJKLoWmT5/MM-32771-Update-Tips-and-Next-Steps?node-id=807%3A23774

Captura de pantalla 2021-09-24 a las 12 56 44
Captura de pantalla 2021-09-24 a las 12 57 50

hey Matt, the changes are done! thanks for the feedback @matthewbirtch !

**Review by matthewbirtch — APPROVED** [review]
Thanks @pablovelezvidal! Looks good to me now

**Review by neallred — APPROVED** [review]
lgtm!

**Pull request merged**
