### PR TITLE
MM- 18893: Change text User to Member

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
When promoting a guest, the menu item was "Promote to user".

This PR updates that string to "Promote to Member".

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18893

#### Screenshots
Screen Shot 2021-01-14 at 8 41 36 AM
Screen Shot 2021-01-14 at 8 47 14 AM

### CODE REVIEW

**Comment by wiersgallak** [comment]
@cwarnermm Can you please review this wording and propose an alternative?  I think we can make this a bit better (especially ending a sentence with "of".).  Thank you in advance!

**Review by cwarnermm — APPROVED** [review]
Looks good to me!

**Review by wiersgallak — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
All tests passed ✅ 

image

image

image

**Comment by cwarnermm** [comment]
@wiersgallak - I apologize! I didn't see your request for microcopy feedback as part of this PR. I realize that this PR has already been merged; however, here is my proposal for an update to the  in-product text:

"This action promotes the guest [x] to a member. As a member, they can join public channels and interact with users in other channels. Are you sure you want to promote guest [x] to member?"

**Pull request merged**
