### PR TITLE
MM-47782 Stop storing compact mode profile colours in localStorage

### PR DESCRIPTION
**Pull request by hmhealey**
We might've gone a bit overboard with caching these colours in localStorage. It probably takes more time to load from localStorage anyway than it would to just regenerate them, even in a worst case scenario.

@nevyangelova This might conflict with your post PR

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47782

#### Release Note
```release-note
Don't persist username colours in compact mode
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
Thanks for the heads up! This change makes a lot of sense, i didn't even notice we were loading them from localstorage.

**Review by oh6hay — APPROVED** [review]
LGTM :+1:

**Comment by hmhealey** [comment]
@jgilliam17 With this PR, when you're in compact mode, users' names should still keep the same colours as they did before after a refresh. We just changed it so that we're doing it without caching anything in browser storage any more.

**Review by koox00 — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
Verified, in compact mode, usernames have the same color after refresh.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/261095-284347e-onprem-ent-webapp-pr-11527-mm-ee-test:284347e/mochawesome.html) - no PR related failures.

**Pull request merged**
