### PR TITLE
[MM-28210] components/popover_list_members: don't filter deleted users

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Instead of filtering deleted users at webapp, it seemed more convenient to do in server. Added the `active: true` query parameter to the API call. Above certain amount of users it is more efficient to handle this in the server.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28210

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/15390
https://github.com/mattermost/mattermost-webapp/pull/5951
https://github.com/mattermost/mattermost-redux/pull/1231

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by Willyfrog — CHANGES_REQUESTED** [review]
LGTM

**Comment by isacikgoz** [comment]
@agnivade implementation has changed after your approval :) Also @Willyfrog did you accidentally requested changes?

**Review by Willyfrog — APPROVED** [review]

**Review by agnivade — APPROVED** [review]

**Comment by lindalumitchell** [comment]
@isacikgoz I tested with just one deactivated user (per the first set of test steps in the ticket), and the member count on Town Square and Off-Topic went down as expected, but the deactivated user still appeared in the member list when I clicked the member icon, even after refresh:

Screen Shot 2020-09-14 at 8 01 41 PM

Screen Shot 2020-09-14 at 8 02 38 PM

**Comment by lindalumitchell** [comment]
Ah I and I just recalled the comment on https://github.com/mattermost/mattermost-server/pull/15390 that these two PRs can be tested together. So maybe a test server on one or the other PR won't work because both are needed?

**Comment by isacikgoz** [comment]
@lindalumitchell Yes, both PRs required to test this, I would expect it to use server branch since they have the same branch names 🤷 Actually after the first spinwick instance is built for this PR, I updated the server PR to reflect review comments. Maybe that can be the issue here.

**Comment by lindalumitchell** [comment]
^Still not showing the expected member list on that updated test server. Trying on the server PR just in case.

**Review by lindalumitchell — APPROVED** [review]
Reviewed on the server PR https://github.com/mattermost/mattermost-server/pull/15390, and looks good there.

**Comment by isacikgoz** [comment]
@lindalumitchell thanks for taking care of this! I reckon the server was not updated in the test server for this PR.

**Pull request merged**
