### PR TITLE
[MM-28225] migrate 'components/post_view/show_more' to typescript

### PR DESCRIPTION
**Pull request by Tak-Iwamoto**
#### Summary
- Migrate 'components/post_view/show_more' module and associated tests to TypeScript
- change `this.refs` to `React.createRef()`
#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15441
JIRA: https://mattermost.atlassian.net/browse/MM-20500

### CODE REVIEW

**Comment by Willyfrog** [comment]
adding devin as reviewer, as he is the one running the campaign

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks for the contribution @Tak-Iwamoto!

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Looks excellent to me! Thanks for the PR, @Tak-Iwamoto!

**Review by jgilliam17 — APPROVED** [review]
Thank you @Tak-Iwamoto 
Tested, looks good to merge.
- Verified long post show more/show less - works as expected.
@hmhealey Can you please help merge? Thanks 🙂

**Pull request merged**
