### PR TITLE
MM-12463 Migrate 'components/localized_input' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by brewsterbhg**
#### Summary
This pull request migrates 'components/localized_input.jsx' and 'components/localized_input.test.jsx' to TypeScript.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12463

### CODE REVIEW

**Comment by sudheerDev** [comment]
@brewsterbhg PR looks good to me but can you rename the file `omponents/localized_input/localized_input.jsx` to `omponents/localized_input/localized_input.tsx`?. I feel that when making the PR you might have created a new file and copied the contents because the git shows it as a new file here. Renaming the file instead will keep the git history intact.

**Comment by sudheerDev** [comment]
@brewsterbhg If you can merge mater into this branch after renaming i can merge this PR

**Comment by brewsterbhg** [comment]
> @brewsterbhg PR looks good to me but can you rename the file `omponents/localized_input/localized_input.jsx` to `omponents/localized_input/localized_input.tsx`?. I feel that when making the PR you might have created a new file and copied the contents because the git shows it as a new file here. Renaming the file instead will keep the git history intact.

@sudheerDev hey sorry, so I actually did rename the file, but I also noticed in the diff that it was committed as a new file. I'll fix that.

**Comment by brewsterbhg** [comment]
> @brewsterbhg I feel that when making the PR you might have created a new file `components/localized_input/localized_input.tsx` and copied the contents from `components/localized_input/localized_input.jsx` then did the typescript changes because the git shows it as a new file here. Renaming the file instead will keep the git history intact.
> 
> Can you let me know if you can rename the file instead? If you are not sure how. I suggest making a temp branch from this commit so you have a ref of this. Delete this branch checkout from master and create a new branch with same name. Then rename the file and copy the contents from this PR into the renamed `tsx` file and force push it. Not a great solution but in case you couldn't think of a way to do it

Hi @sudheerDev so this is an issue in git where if there's too many changes to a file in a branch, it will flag it as an add/delete action vs a rename. I've tried a number of things to rectify this, but I'm unable to avoid it. If you look at the first commit I've made [here](https://github.com/mattermost/mattermost-webapp/pull/3869/commits/d7fa605f72648312f308ce8421321d25914f3ce0), all I've done is rename the extension, and it recognizes as a rename. I added the typings in a second commit [here](https://github.com/mattermost/mattermost-webapp/pull/3869/commits/6ec301ca857ee5fcfc47d98a92f5eaaf6325bf89) which also works fine and considers it as an edit. But if you look at the diff under "files changed", it's picking it up as if it's an entirely new file. I thought separating this into two commits would work for the rename, but I think it has to be on a branch by branch basis.

**Comment by sudheerDev** [comment]
@brewsterbhg Thanks for going through the trouble of figuring this out. That is not a blocker for the PR i am going to merge this when builds pass.

**Pull request merged**
