### PR TITLE
MM-46597:  Unreads button in channel sidebar is missing alt text for screen readers

### PR DESCRIPTION
**Pull request by babinderrathi**
#### Summary
 Unreads button in channel sidebar is missing alt text for screen readers
 
#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-46597

#### Related Pull Requests
NONE

#### Screenshots

https://user-images.githubusercontent.com/102028591/203821723-f16cbb3f-0d0b-489c-b951-03128195a158.mp4

#### Release Note
```release-note

Unreads button in channel sidebar is missing alt text for screen readers
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM other thank @tboulis' comments. Thanks @babinderrathi!

**Comment by babinderrathi** [comment]
@tboulis can you please re-review the changes.

**Comment by jgilliam17** [comment]
Thanks @babinderrathi 
Tested, looks good to merge.
Verified LHS unreads filter button is read by the screen reader.
[E2E report](https://github.com/mattermost/mattermost-webapp/pull/11641) - no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
