### PR TITLE
[MM-41570] Moving next on dismiss on boarding tour and finished value

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Moving next on dismiss on causing issue with onBoarding Tour

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-41570

#### Related Pull Requests
``NONE``

#### Screenshots
|  before  |  after  |
|----|----|
| https://user-images.githubusercontent.com/16203333/152521050-2a5e9cf5-2d1a-4ef4-b62e-8118c74b731a.mov | https://user-images.githubusercontent.com/16203333/152521160-3b7a5347-8a17-4428-8b94-4e21fa744da2.mov |

#### Release Note

```release-note
UI: Moving next on dismiss on causing issue with onBoarding Tour
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@amyblais is it still possible to include this with following https://mattermost.atlassian.net/browse/MM-29622

**Review by neallred — APPROVED** [review]
lgtm!

**Comment by amyblais** [comment]
@AGMETEOR Please help prioritize PR review.

**Review by AGMETEOR — APPROVED** [review]

**Comment by amyblais** [comment]
@AshishDhama This seems to need a manual cherry-pick.

**Pull request merged**
