### PR TITLE
fix(cypress): a11y account settings test case

### PR DESCRIPTION
**Pull request by yasserfaraazkhan**
Failing test on master: https://mattermost-cypress-report.s3.amazonaws.com/282972-onprem-ent-ha-master-mm-ee-test:test/mochawesome.html

**before**:
Screenshot 2023-01-02 at 9 04 37 PM

**after**:
Screenshot 2023-01-02 at 9 05 13 PM

```release-note
NONE
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by JulienTant — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by furqanmlk — COMMENTED** [review]
Thanks @yasserfaraazkhan

**Pull request merged**
