### PR TITLE
[MM-38502] Fixing image name in modal title

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
If image proxy was turned on, the image modal title would show the proxied url.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38502

#### Screenshots
Now:
Screen Shot 2021-09-27 at 5 46 48 PM
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by engineereng — APPROVED** [review]
Looks good to me!

**Review by hmhealey — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Thanks @BenCookie95 

All looks good

image

**Pull request merged**
