### PR TITLE
Migrate lazy loading to use React.lazy rather than bundle-loader

### PR DESCRIPTION
**Pull request by anindha**
#### Summary
Use the native React.lazy() to lazy load components rather than the third party bundle-loader.

### CODE REVIEW

**Comment by jasonblais** [comment]
Hey @anindha, sorry for the delay in starting to review this PR. Can you help rebase against master and I'll start the review process? If any questions, don't hesitate to let us know!

**Comment by anindha** [comment]
@jasonblais I have rebased. Thanks for looking at this!

**Comment by anindha** [comment]
I found an issue with this. Closing for now.

**Pull request closed without merging**
