### PR TITLE
[ICU-621] Unreads sidebar section

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Add Experimental unread channel section in the sidebar, this includes a section in Account Settings -> Sidebar to enable or disable the option to display the unread channel section in the sidebar.

Also this PR fixes the window title not displaying the amount of unread messages.

#### Ticket Link
https://mattermost.atlassian.net/browse/ICU-621

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has server changes (https://github.com/mattermost/mattermost-server/pull/8127)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

@esethna when setting a test server you'll have to add the server setting in the config.json I think

### CODE REVIEW

**Comment by enahum** [comment]
I'll rebase this and then it should be ready for testing

**Comment by enahum** [comment]
@esethna rebased and ready to be tested

**Comment by esethna** [comment]
@jwilander when you have a chance can you set the "ExperimentalGroupUnreadChannels": to true in the config?

**Comment by enahum** [comment]
@esethna the problem is that once you click on the unread channel is no longer unread, to accomplish that behavior is going to be tricky I’ll see what I can do, I have an idea for a workaround but lets see if it’s actually possible

**Comment by enahum** [comment]
@esethna this should be ready to test again (The spinmint has already the setting enabled)

**Comment by esethna** [comment]
@enahum sorry it looks like it's still jumping the channel out of the unreads section as soon as you click it:

unreads

**Comment by enahum** [comment]
looks like the spinmint didn't include the latests changes in mattermost-redux, don't know exactly why

**Comment by enahum** [comment]
@esethna I don't think there is a way to prevent the mention issue as it sorts according to that, and once you read a channel there's no way to keep the sorting as there are no mentions, as I showed during my demo.

As for the second issue I haven't seen that before, and I would love consistent repro steps if we don't have them is going to be nearly impossible to figure out.

**Comment by esethna** [comment]
Thanks @enahum, maybe we should remove the mention sorting if we can't fix the issue?  I'm not comfortable shipping with the channels jumping around like that. So if there's nothing else we can do let's just sort alphabetically in the unreads section.

I can't seem to get reliable repro steps. Let's try to make the change above ^ and then retest and see if we have the issue still?

**Comment by esethna** [comment]
@enahum just confirming this PR has diagnostics?

**Comment by enahum** [comment]
diagnostics where added in the server PR, is there anything we need to track client side?

**Comment by esethna** [comment]
Good to go then, thanks

**Pull request merged**
