### PR TITLE
MM-34366: Migrate 'components/post_view/post_list_virtualized' and associated tests to TypeScript 

### PR DESCRIPTION
**Pull request by naftalimurgor**
#### Summary

This Pull Request Migrates `components/post_view/post_list_virtualized` and associated tests to TypeScript as 
described in this issue https://github.com/mattermost/mattermost-server/issues/17289

#### Ticket Link

JIRA: https://mattermost.atlassian.net/browse/MM-34366
issue: https://github.com/mattermost/mattermost-server/issues/17289
#### Related Pull Requests

- Has no server changes
- Has no mobile changes

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by naftalimurgor** [comment]
@devinbinnie 
 Hey,

I closed the previous WIP PR and submitted one complete PR that covers all the changes.

**Comment by devinbinnie** [comment]
@naftalimurgor Thanks again for the work on this :) could you merge `master` in and fix the conflicts? Then I can take a look.

**Comment by naftalimurgor** [comment]
@devinbinnie 
Ok, I'm on it 👍🏽

**Comment by naftalimurgor** [comment]
@devinbinnie 
I resolve the conflict, I think there are some failing checks

**Comment by devinbinnie** [comment]
@naftalimurgor Yep, this is the error I'm seeing:
```
components/global/product_switcher.tsx:105:17 - error TS2322: Type '"view-grid-outline"' is not assignable to type 'TIconGlyph'.

105                 icon={'view-grid-outline'}
                    ~~~~

  node_modules/@mattermost/compass-components/components/icon-button/IconButton.props.d.ts:8:5
    8     icon: TIconGlyph;
          ~~~~
    The expected type comes from property 'icon' which is declared here on type 'IntrinsicAttributes & PIconButton & RefAttributes<HTMLButtonElement>'
```

Can we fix this?

**Comment by naftalimurgor** [comment]
Ok, I'm working on it 👍. I think the error occured after resolving the conflicts.

**Comment by naftalimurgor** [comment]
> @naftalimurgor Yep, this is the error I'm seeing:
> 
> ```
> components/global/product_switcher.tsx:105:17 - error TS2322: Type '"view-grid-outline"' is not assignable to type 'TIconGlyph'.
> 
> 105                 icon={'view-grid-outline'}
>                     ~~~~
> 
>   node_modules/@mattermost/compass-components/components/icon-button/IconButton.props.d.ts:8:5
>     8     icon: TIconGlyph;
>           ~~~~
>     The expected type comes from property 'icon' which is declared here on type 'IntrinsicAttributes & PIconButton & RefAttributes<HTMLButtonElement>'
> ```
> 
> Can we fix this?

Hello 👋🏽  @devinbinnie 
I looked into the error that was causing a
the failed checked, though a bit later and saw that it has been fixed so I resolved some merge conflicts to incorporate the changes.

**Comment by naftalimurgor** [comment]
@devinbinnie 
Hello, The failing check has already been fixed.

**Comment by devinbinnie** [comment]
Thanks @naftalimurgor, looks like there are a couple conflicts though. Can we fix those up? :)

**Comment by devinbinnie** [comment]
Hey @naftalimurgor, thanks for merging master, but it looks like there's a test failing now. Can you have a look at that?

**Comment by naftalimurgor** [comment]
Ok. I ran all the test and several others where failing too.

**Comment by devinbinnie** [comment]
> @devinbinnie
> Could this be because of the snapshots?

Yeah it's possible, you can update them by running `npm test -- -u`

**Comment by naftalimurgor** [comment]
@devinbinnie 
I did that, some snapshots got updated, is this ok? :)

**Comment by devinbinnie** [comment]
> @devinbinnie
> I did that, some snapshots got updated, is this ok? :)

Looks like it's still failing, here's the error its spitting out:
```
Summary of all failing tests
 FAIL  components/post_view/post_list/post_list.test.jsx
  ● components/post_view/post_list › snapshot for loading when there are no posts

    Unexpected console logsWarning: Failed prop type: The prop `atOldestPost` is marked as required in `PostList`, but its value is `undefined`.
        in PostList,Warning: Failed prop type: The prop `latestPostTimeStamp` is marked as required in `PostList`, but its value is `undefined`.
        in PostList

      89 |     if (warns.length > 0 || errors.length > 0) {
      90 |         const message = 'Unexpected console logs' + warns + errors;
    > 91 |         throw new Error(message);
         |               ^
      92 |     }
      93 | });
      94 |

      at Object.<anonymous> (tests/setup.js:91:15)
```

You can get this output yourself as well by running `npm run test`

**Comment by naftalimurgor** [comment]
I ran `npm test -- -u` locally and some snapshots got updated. Is this ok?

**Comment by naftalimurgor** [comment]
I think it's the recent merge conflict, I'll have to look at how I resolved them. I think it's the reason why tests are failing.

**Comment by devinbinnie** [comment]
@naftalimurgor How's things going? Let us know if you need any help with this.

**Comment by naftalimurgor** [comment]
> @naftalimurgor How's things going? Let us know if you need any help with this.

Hey @devinbinnie I think I'll have to re-clone this repository to do away with the breaking stuff and resubmit the PR ensuring all the checks pass

**Comment by jasonblais** [comment]
@naftalimurgor let us know if we can help with the resubmission. Really appreciate your help with this contribution!

**Pull request closed without merging**
