### PR TITLE
MM-35366 Improve messaging in the add members to channel modal

### PR DESCRIPTION
**Pull request by pqzx**
#### Summary

Update add members to channel modal so message about user limit is only displayed when limit is reached. Message no longer mentions 'You can add X more'. Aim is to be consistent with current behaviour of invite users modal. The approach taken stemmed from discussion here https://community.mattermost.com/core/pl/tr1epqd9big7zr3xh3dsmqdwxw

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/17707
https://mattermost.atlassian.net/browse/MM-35366

#### Screenshots

Before:
before

After:
s1
s2
s3
s4

Note: the numbers seen in the images were temporarily modified in the example for ease of testing. The actual limit remains the same (20).

#### Release Note

```release-note
Added behavioural and UI changes for Multiselect component.
```

### CODE REVIEW

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @pqzx

**Comment by michelengelen** [comment]
@pqzx is there anything we can help you with on this?

**Comment by pqzx** [comment]
Sorry, I haven't been able to get to this the last few weeks. Thanks for all the comments, will try to address them in the next week.

**Comment by Willyfrog** [comment]
closing as we changed the user add to channel and this might need to be reworked.

**Pull request closed without merging**
