### PR TITLE
New channel Modal close button a11y issue.

### PR DESCRIPTION
**Pull request by MathewtheCoder**
#### Summary
Added **aria-label** to the new channel modal close button which was previously unreadable by screen readers. Added a **title** also to give more clues to the user.

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/13012
JIRA Ticket No: https://mattermost.atlassian.net/browse/MM-19777

### CODE REVIEW

**Comment by Willyfrog** [comment]
Code looks good, waiting for the test server to check on the axe plugin

**Comment by Willyfrog** [comment]
@MathewtheCoder please remember to sign the CLA, as we cannot accept a PR withouth this step. See [a checklist](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) that will ensure your PR get's accepted.

**Comment by MathewtheCoder** [comment]
@Willyfrog I have signed the **CLA** was it not recorded ?

**Comment by Willyfrog** [comment]
I definitely see your name on it, I'll check what's going on.
in the meantime, could you sync this PR with the master branch?

**Comment by MathewtheCoder** [comment]
@Willyfrog Actually i had done it twice cause i submitted some wrong info insufficient info on the first try. Maybe because of that. I will sync it up with master in the evening.

**Comment by saturninoabril** [comment]
Thanks @MathewtheCoder!

**Pull request merged**
