### PR TITLE
MM-8589: remove most usages of the global mm_config and mm_license

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
This is a BIG pull request. The commits are mostly independent and focussed, but there are also a lot of those, so review as you wish.

The change removes the bulk of our dependence on the global `mm_config` and `mm_license` objects. These changes will ultimately facilitate resolving https://mattermost.atlassian.net/browse/MM-8604, allowing us to stop hard refreshing the application whenever someone makes a configuration change. 

I did not always write unit tests for components that didn't already have them, however I've manually tested practically every component along the way in addition to updating existing unit tests and writing new cases where needed.

There is still some scattered use of `mm_config` and `mm_license`, particularly in the utilities and actions, but I'm cutting things off at this point in a bid to get a review before v4.8 (T-15). The remaining components and code require some additional surgery to expunge the use of these globals and I'll be tackling that in parallel with this review, but it is likely not to make cut off.

I've tried to converge on a single style for the changes being made, but it's possible I wasn't always self-consistent. Let me know if you have any concerns :)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-8589

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors.
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests

### CODE REVIEW

**Comment by lieut-data** [comment]
@jwilander and @mkraft, I've picked you as reviewers so as to not add anything to the ICU team right now. Let me know if you think you won't have time to look at this and I can try to recruit others :)

**Comment by mkraft** [comment]
@lieut-data It brings up an interesting problem, generally, of how to review big PRs that would take all day to go through line-by-line.

**Comment by mkraft** [comment]
@lieut-data Maybe this'll work: is there anything in particular you me to focus on? Anything where you think there needs a critical eye either from an architectural perspective or a potential for errors/mistakes?

**Comment by lieut-data** [comment]
@mkraft, I made another proposal on pre-release re: splitting up this PR artificially into chunks. (The commits are almost entirely independent, so I could even parallelize this.) Let me know what you think of that idea :)

**Comment by lieut-data** [comment]
I'm going to try to split this one up.

**Pull request closed without merging**
