### PR TITLE
MM-8622: Improved plugin error reporting

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
This represents the implementation effort of a design proposed in ~developer-toolkit on pre-release.mattermost.com.

Here's the main take aways from the webapp PR. More details are given in the accompanying [server](https://github.com/mattermost/mattermost-server/pull/8737) and [redux](https://github.com/mattermost/mattermost-redux/pull/490) PRs:
* The Plugins > Management page is now driven by queries / websocket events re: PluginStatuses
* Updated plugin UI for single server case:
image
* Updated plugin UI for multi-server case:
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-8622

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has server changes: https://github.com/mattermost/mattermost-server/pull/8737
- [x] Has redux changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jwilander** [comment]
This is going to be a great addition to plugins 👍

**Comment by jasonblais** [comment]
@asaadmahmood @michaelgamble thoughts on the above UI screenshots?

**Comment by asaadmahmood** [comment]
@jasonblais Looks good for the most part, shouldn't we have a different icon for the running and off state? Perhaps an x icon for the off state, and a checkmark icon for the running state?

**Comment by jasonblais** [comment]
@asaadmahmood Makes sense when the plugin is running.

The plugin may also be intentionally deactivated (e.g. someone installed Zoom but decided they didn't want it). So I'm not sure if "X" makes sense in that case, although definitely open to using a different icon.

**Comment by lieut-data** [comment]
@jasonblais, yep, I can effect those changes!

**Comment by lieut-data** [comment]
Ready for review! :D

**Pull request merged**
