### PR TITLE
MM-14843 Fix IME composition for non-Chrome browsers in multiselect components

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Switch to using our fork until https://github.com/JedWatson/react-select/pull/3563 is accepted and released upstream.

The commit I'm using in our fork is based off the react-select 2.4.2 release.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-14843

### CODE REVIEW

**Comment by jwilander** [comment]
Testing something before it's ready for review.

**Comment by jwilander** [comment]
Ready for review.

**Comment by enahum** [comment]
@jwilander your PR was merged upstream, feel free to remove the fork at any time ;)

**Comment by jwilander** [comment]
Thanks for your help @enahum :)

**Pull request merged**
