### PR TITLE
[MM-14833] Add UI and Redux to disable bot from user settings

### PR DESCRIPTION
**Pull request by CooperAtive**
#### Summary
Add UI and Redux to disable bot from user settings

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/10543
https://mattermost.atlassian.net/browse/MM-14833

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @CooperAtive! Testing it now, and I'm seeing potential complications with listing bot accounts in System Console > Users unrelated to this PR. Reached out to our engineering team and will follow up here after.

Really appreciate your help with this contribution!

**Comment by jasonblais** [comment]
Thanks @CooperAtive  for your pull request on bot accounts! https://github.com/mattermost/mattermost-webapp/pull/2640

I've been testing it out and while your changes are as specified in the GitHub issue, I'm thinking we've made an incorrect design decision on our end. 

A bot isn't a real user, so as an administrator I wouldn't actually expect bots to appear in a list of system users. As a result, I'm leaning towards hiding bots from System Console > Users list, instead of allowing one to disable bots on this page.

I apologize for the change in direction..I'd love to work with you on this improvement instead to hide bots from System Console > Users. Would this be something you're open to helping with?

**Comment by CooperAtive** [comment]
Sure sounds great. Should I look out for a new jira issue or just do the work to filter out bots?

**Comment by jasonblais** [comment]
@CooperAtive Thank you so much! I opened a separate issue for it. It'll be easier to track this separately (we can close this PR if you're open to it). https://github.com/mattermost/mattermost-server/issues/10596

Really appreciate your flexibility 👍

**Comment by CooperAtive** [comment]
Spec changed, closing.

**Pull request closed without merging**
