### PR TITLE
MM-19326: Keyboard shortcut to open/close the right-hand

### PR DESCRIPTION
**Pull request by ChrisDobby**
#### Summary
Cmd/Ctl + period will open and close the right hand side.  When opening it will open in its previous state - if the previous state is not available ie. selected post has been deleted, or the right hand side has not been opened before it will open with an empty search.
#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/13300

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @ChrisDobby for the contribution! Heads up that reviews may be slower with the holidays.

**Comment by hanzei** [comment]
Hey @ogi-m @devinbinnie,

Would you please review this PR when you are back from the weekend? Thanks :wink:

**Comment by ogi-m** [comment]
Tested the command and it's working as expected.

@ChrisDobby We have opened a ticket for adding this shortcut to the list on the Keyboard Shortcuts modal: https://mattermost.atlassian.net/browse/MM-21889
Would you like to work on this one maybe? It can be done in a new PR, or ideally as part of this one?

cc @esethna

**Comment by ChrisDobby** [comment]
> Tested the command and it's working as expected.
> 
> @ChrisDobby We have opened a ticket for adding this shortcut to the list on the Keyboard Shortcuts modal: https://mattermost.atlassian.net/browse/MM-21889
> Would you like to work on this one maybe? It can be done in a new PR, or ideally as part of this one?
> 
> cc @esethna

@ogi-m am happy to work on that as part of this PR

**Comment by ChrisDobby** [comment]
Have updated the PR to include this ticket:

https://mattermost.atlassian.net/browse/MM-21889

**Comment by hanzei** [comment]
Great work @ChrisDobby. Thank you very much for this awesome contribution :tada:

**Pull request merged**
