### PR TITLE
[GH-16537][MM-31148] Add Formatting Shortcut Keys to Shortcut modal

### PR DESCRIPTION
**Pull request by jp0707**
#### Summary
Add Formatting Shortcut Keys to Shortcut modal

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/16537
Fixes https://mattermost.atlassian.net/browse/MM-31148

#### Screenshot
Screenshot from 2020-12-15 16-24-15

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for another PR for this, @jp0707! Looks good, but I'm going to block this PR on https://github.com/mattermost/mattermost-webapp/pull/7125 just so that we have the link hotkey working before it shows up in the shortcuts modal.

**Comment by jfrerich** [comment]
@hmhealey, it looks like https://github.com/mattermost/mattermost-webapp/pull/7125 is ready to merge.  If you could merge that ticket and finish this one after, that would be awesome!

Thanks for the PR, @jp0707

**Review by nevyangelova — APPROVED** [review]
Thanks @jp0707 LGTM!

**Comment by hmhealey** [comment]
@jgilliam17 This can be tested to ensure the shortcuts modal displays correctly. The PR is only blocked from being mergedsince we don't support the link keyboard shortcut yet, but it's perfectly fine to test.

**Review by jgilliam17 — APPROVED** [review]
Thank you @jp0707 
Tested, looks good to merge after PR with link support is ready/merged. Tested on macOS, Windows and Ubuntu.
- Verified Shortcut keys for bold, italic and link display as expected on Keyboard shortcuts modal.

**Comment by jfrerich** [comment]
@hmhealey, it looks like the PR we are waiting on has been merged. If that is correct, could you do the merge? Thanks!

**Comment by hmhealey** [comment]
Thanks for the reminder, @jfrerich! I'll do that now

**Pull request merged**
