### PR TITLE
MM-20260 - Email notification still sent while disabled in UI

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Treating `INTERVAL_NEVER` as `INTERVAL_IMMEDIATE` when `enableEmail` is `true`.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-20260

#### Related Pull Requests
- Has redux changes (https://github.com/mattermost/mattermost-redux/pull/997)

#### Screenshots
image

image

#### How to test

Set `Users.NotifyProps.email` to `true`
```
UPDATE `mattermost_test`.`Users` SET `NotifyProps` = '{\"auto_responder_active\":\"false\",\"auto_responder_message\":\"Hello, I am out of office and unable to respond to messages.\",\"channel\":\"true\",\"comments\":\"never\",\"desktop\":\"mention\",\"desktop_sound\":\"true\",\"email\":\"true\",\"first_name\":\"false\",\"mention_keys\":\"ali.farooq2\",\"push\":\"mention\",\"push_status\":\"away\"}' WHERE `Id` = '<USER_ID>';
```

Set `email_interval` to `0`.
```
UPDATE `mattermost_test`.`Preferences` SET `Value` = '0' WHERE `UserId` = '<USER_ID>' AND `Category` = 'notifications' AND `Name` = 'email_interval';
```

### CODE REVIEW

**Comment by ali-farooq0** [comment]
@jgilliam17 this is ready for QA.

**Comment by amyblais** [comment]
@ali-farooq0 Do you know if this is a big change / too risky for v5.18, or could this be added in v5.18?

**Comment by ali-farooq0** [comment]
> @ali-farooq0 Do you know if this is a big change / too risky for v5.18, or could this be added in v5.18?

@amyblais Sorry seeing this now. Replied on the on the jira [here](https://mattermost.atlassian.net/browse/MM-20260). My recommendation is to push this to 5.19 and NOT 5.18.

**Pull request merged**
