### PR TITLE
[MM-30193] change file attachment info to show fractions below 10

### PR DESCRIPTION
**Pull request by svelle**
Previously a file that was for example 1.5GB or 1.5MB would show up as 1GB and 1MB respectively.
Conventionally in rounding file sizes however you'd only round to an integer value for file sizes above 10, this PR does just that.

#### Screenshots
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30193

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]

**Comment by devinbinnie** [comment]
@svelle Does this have a ticket associated with it? Also, should someone from QA have a look before we merge?

**Comment by svelle** [comment]
> @svelle Does this have a ticket associated with it? Also, should someone from QA have a look before we merge?

no ticket, was just me coding away in my free time because of an issue I saw come up. I can create one though.

Don't know about QA. Guess it wouldn't hurt.

**Comment by devinbinnie** [comment]
> > @svelle Does this have a ticket associated with it? Also, should someone from QA have a look before we merge?
> 
> no ticket, was just me coding away in my free time because of an issue I saw come up. I can create one though.
> 
> Don't know about QA. Guess it wouldn't hurt.

Since QA is swamped right now between Hacktoberfest and release testing, we can have them look at it later.

**Pull request merged**
