### PR TITLE
MM-34128: Allow clearing custom status with only the emoji and no text

### PR DESCRIPTION
**Pull request by chetanyakan**
#### Summary
- Added the support to show a clear button even if the input has no value in the Quickinput component

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34128

#### Screenshots

image

#### Release Note

```release-note
In Custom Statuses, added the ability to clear the custom status with only the emoji and no text from UI
```

### CODE REVIEW

**Comment by chetanyakan** [comment]
@matthewbirtch were you able to test this?

**Comment by matthewbirtch** [comment]
> @matthewbirtch were you able to test this?

Just tested it and it appears to work now as expected.

**Review by matthewbirtch — APPROVED** [review]

**Comment by chetanyakan** [comment]
@esethna Can you assign other reviewers to this PR?

**Comment by esethna** [comment]
@chetanyakan done, apologies for the delay

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @chetanyakan!

**Review by michelengelen — COMMENTED** [review]
Thanks @chetanyakan ... LGTM!

**Review by michelengelen — APPROVED** [review]

**Pull request merged**
