### PR TITLE
MM-42258: Displays message about username-groupname conflict.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Displays a useful message when attempting to update to a username that conflicts with an existing group name.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-42201

#### Related Pull Requests

https://github.com/mattermost/mattermost-server/pull/19660

#### Screenshots

Screen Shot 2022-03-02 at 7 04 18 PM

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by BenCookie95** [comment]
I have that fix in my PR as well: https://github.com/mattermost/mattermost-webapp/pull/9920. Do you want to keep this PR or mine?

**Comment by mylonsuren** [comment]
> I have that fix in my PR as well: #9920. Do you want to keep this PR or mine?

@BenCookie95 Looks like it's in #9919 with the difference being that this PR has a test for the username error. I'm good either way if we merge this PR and remove the username part from #9919 or add the test to that PR, whichever you think would be easier.

**Comment by mkraft** [comment]
@BenCookie95 Let me know if you want to use this PR or if you want me to close it.

**Review by BenCookie95 — APPROVED** [review]
Let's use this one since you have a test for it, I'll revert it from my PR

**Comment by mkraft** [comment]
> Let's use this one since you have a test for it, I'll revert it from my PR

cc @mylonsuren

**Review by mylonsuren — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
working as expected
image

**Pull request merged**
