### PR TITLE
[GH-20901]: Add ExperimentalSettings.InteractiveDialogTriggerTimeout to the System Console

### PR DESCRIPTION
**Pull request by adityash1**
#### Summary
To be able to set InteractiveDialogTriggerTimeout env variable through system console

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/21901

#### Related Pull Requests
- Has server changes (https://github.com/mattermost/mattermost-server/pull/22047)

#### Release Note
```release-note
Added a new config setting to determine the request timeout for interactive dialog triggers.
```

### CODE REVIEW

**Comment by hmhealey** [comment]
@mickmister I don't entirely understand what this timeout affects because I haven't used interactive dialogs in ages, but maybe it should live in `ServiceSettings` instead of `ExperimentalSettings`? Usually "experimental" config settings are either for enabling features that are in active development or for settings that are mostly safety valves in case something breaks.

**Comment by mickmister** [comment]
> @mickmister I don't entirely understand what this timeout affects because I haven't used interactive dialogs in ages, but maybe it should live in `ServiceSettings` instead of `ExperimentalSettings`? Usually "experimental" config settings are either for enabling features that are in active development or for settings that are mostly safety valves in case something breaks.

`ServiceSettings` makes sense to me :+1:

**Comment by hmhealey** [comment]
Cool. In that case, would you mind moving the setting into `ServiceSettings` in the config then, @adityash1? At the same time, I think the setting in the System Console should probably be moved into the Integrations > Integration Management page along with the settings for controlling webhooks and slash commands

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
