### PR TITLE
MM-43323 : White screen when leaving channel in webapp, with unread filter is on.

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Fixes the undefined error when unread filter is on and the current team is left.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43323

#### Related Pull Requests
N/A

#### Screenshots
N/A

#### Release Note

```release-note
Fixed undefined error on leaving a channel with unread filter on.
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Do we know why there's an undefined entry in that array? I'd prefer to catch the problem before we return since this error might reappear if we add more logic into that selector

**Comment by M-ZubairAhmed** [comment]
> Do we know why there's an undefined entry in that array? I'd prefer to catch the problem before we return since this error might reappear if we add more logic into that selector

Yes i fixed it now, since the current channel was left, it was removed from all channels list and it became undefined.

**Review by hmhealey — APPROVED** [review]
Zubair and I chatted a bit earlier and tried to see if we could figure out why the one of these IDs wasn't matching a channel in the store, but we weren't able to find it

**Pull request merged**
