### PR TITLE
Update Compass icon font

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Current process for updating the icon font:

1. Download the latest font package from https://github.com/mattermost/compass-icons/actions by clicking on the appropriate completed action and downloading the resulting Artifact.
2. Unzip the package
3. Copy the generated fonts from the package (`{package}/font`) to the webapp (`{webapp}/font/compass-icons/*`)
4. Diff the `{package}/css/compass-icons.css` file against the `{webapp}/sass/base/_compass-icons.scss` and copy across the changes.
5. Submit a PR that includes a UX designer, two devs and QA reviewer as usual.

Updated icon names for QA:

Added:
- icon-search-list
- icon-brand-gitlab
- icon-brand-google
- icon-brand-office-365
- icon-brand-one-login
- icon-application-cog
- icon-key-variant-circle
- icon-key-variant
- icon-home-variant-outline

Renamed:
- icon-check-outline-circle to icon-check-circle-outline

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Thank you for the thorough description, @deanwhillier, I know now how to do it :)

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified new added icons are loaded as expected and one icon that has been removed - no longer loads.

**Review by nevyangelova — APPROVED** [review]
LGTM!

**Review by michaelgamble — APPROVED** [review]
Was able to confirm that icon-check-circle-outline from @deanwhillier was a duplicate being removed. Everything looks good to go for me.

**Comment by deanwhillier** [comment]
To clarify, it was actually a rename. I updated the description and testing the icon myself so we don't have to hold this up. @jgilliam17, please feel free to double check the rename regardless! :)

**Comment by jgilliam17** [comment]
Thanks @deanwhillier There's an issue with the test server - I think if you have already tested it, no need to hold this up. 🙂

**Pull request merged**
