### PR TITLE
[MM-36714] - Renew Now button in announcement bar lost its styling

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR fixes styling of the announcement banner

#### Ticket Link
[MM-36714](https://mattermost.atlassian.net/browse/MM-36714?atlOrigin=eyJpIjoiYTBmOGU3MTJlOTc0NDA4MGFjNzU5N2EwNWMxNDBjN2MiLCJwIjoiaiJ9)

#### Screenshots
Screenshot 2021-06-29 at 14 18 55

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Comment by AGMETEOR** [comment]
Hello @harshilsharma63 , this PR https://github.com/mattermost/mattermost-webapp/pull/7944 broke some styling in the announcement banner hence the request for a review here

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
@AGMETEOR the changes look fine but the build is failing.

**Comment by marianunez** [comment]
@amyblais where do we need to cherry-pick this to make it to the v5.37 release? Should it go to the cloud branch?

**Comment by amyblais** [comment]
> @amyblais where do we need to cherry-pick this to make it to the v5.37 release? Should it go to the cloud branch?

@marianunez @AGMETEOR The ``cloud`` branch.

**Comment by marianunez** [comment]
> /cherry-pick cloud

@AGMETEOR you can use this command once the PR is merged.

**Review by marianunez — APPROVED** [review]

**Comment by marianunez** [comment]
@stevemudie let's test this post-merge so it can get into the `cloud` update for tomorrow.

**Pull request merged**
