### PR TITLE
[MM-47890] Upgrade p-queue from 7.1.0 to 7.3.0

### PR DESCRIPTION
**Pull request by m1lt0n**
#### Summary

In the context of regularly upgrading dependencies in web app, this PR upgrades p-queue to latest version.

| From version | To version | changelog | Notes |
|--------------|-----------|------------|-------|
| 7.1.0               | 7.3.0          | [releases](https://github.com/sindresorhus/p-queue/releases) | Only some new functionality added without breaking changes. Namely, new "empty" queue event emitted in v7.3.0, as well as an abort task signal and controller added in v7.2.0.|

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47890

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @m1lt0n !

**Review by M-ZubairAhmed — APPROVED** [review]
coming to the component which uses this ie. `data_prefetch`, its time to revisit that and see what we can improve there. https://mattermost.atlassian.net/browse/MM-47946

**Review by jgilliam17 — APPROVED** [review]
Thanks @m1lt0n 
Tested, looks good to merge.
[E2E report ](https://automation-dashboard.vercel.app/cycles/29af1a7d-4d09-4896-ae00-a720ef135229)- no PR related failures.

**Pull request merged**
