### PR TITLE
MM-19925-remove role from user card

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Removes the role from the user card, since it causes confusion.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19925

#### Screenshots
Screen Shot 2021-02-11 at 5 15 16 PM

### CODE REVIEW

**Review by hahmadia — CHANGES_REQUESTED** [review]
If we are removing `{currentRoles}`, do we still need the variable defined above in the render method (seems it's not being used anywhere else). Could we just get rid of the variable altogether and reduce code in the render function?

Line 357 and beyond.
```js
    let currentRoles = (
            <FormattedMessage
                id='admin.user_item.member'
                defaultMessage='Member'
            />
        );
...
```

**Review by hahmadia — APPROVED** [review]
👍

**Comment by sbishel** [comment]
@BenCookie95 - ping on this PR.

**Review by BenCookie95 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Checked Cypress and Zephyr test cases, all looks good

image

**Pull request merged**
