### PR TITLE
Avoid avatars to be shrinked by flexbox policies

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Avoid avatars to be shrinked by flexbox policies

#### Ticket Link
[MM-18670](https://mattermost.atlassian.net/browse/MM-18670)

### CODE REVIEW

**Comment by asaadmahmood** [comment]
See screenshots.
Screenshot 2019-09-24 at 7 43 58 PM
Screenshot 2019-09-24 at 7 44 00 PM

**Comment by jespino** [comment]
@asaadmahmood good catch, let me check if I can find the proper solution, I guess the change of `Avatar-lg` to `Avatar-md` should be enough, but I would like to remove unneeded existing css if is possible.

**Comment by asaadmahmood** [comment]
@jespino Yes, we should remove that css too that I have shown in that screenshot too, now that the avatar is giving it the width/heigth.

**Comment by jespino** [comment]
@asaadmahmood done

**Pull request merged**
