### PR TITLE
MM-44114 : Announcing of channel interface language dropdown correctly (#11121)

### PR DESCRIPTION
**Pull request by hmhealey**
Cherry-pick of #11121 to the 7.1 ESR

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44114
https://mattermost.atlassian.net/browse/MM-47881

#### Related Pull Requests
#11121

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
CC @amyblais assuming she hasn't already seen this 😀

**Comment by jgilliam17** [comment]
Thanks @hmhealey 
Tested, looks good to merge - language announced as expected - peninding e2es
cycle failed https://automation-dashboard.vercel.app/cycles/bf3b07e6-1250-4f19-b4db-de455ac84df9
re-running

**Comment by jgilliam17** [comment]
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/254835-4719dc1-onprem-ent-webapp-pr-11432-mm-ee-test:4719dc1/mochawesome.html) has more failures than expected. @saturninoabril do yo think the failures are related to the fact that this cycle ran on v7.1?

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @saturninoabril for looking into it
  @hmhealey this is good to merge now.

**Pull request merged**
