### PR TITLE
System console > User screen, Team Membership layout is broken

### PR DESCRIPTION
**Pull request by ethervoid**
#### Summary

The Team System console > User Configuration > Team Membership layout is broken when the description field for the team is long (about 40 characters and the maximum is 50) so this change fixes that doing the column a medium one instead of a small one.

In the fixed version screenshot you'll see that the string is smaller, that is due to the 50 characters limit in the description field.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-19965

#### Screenshots

Broken version

image-2019-11-07-10-17-05-289

Fixed version

Screenshot from 2019-11-21 10-55-43

### CODE REVIEW

**Comment by ethervoid** [comment]
Seems like everything is working without problem with the fix:

Screenshot from 2019-11-21 12-20-47
Screenshot from 2019-11-21 11-42-05

I've also detected that the Team UI is missing the `Type` column

**Comment by reflog** [comment]
@ethervoid I think teams is broken, column name is not left aligned:
image

regarding the Type column - that's fine, they are not supposed to look exactly alike :)

**Comment by ethervoid** [comment]
For what I'm seeing those components are using different CSS classes:

- User management > Users > Teams uses the `TeamRow`
- User management > Teams uses `group-row`

I've gone back to master and I'm seeing the same problem in that component. Should I open a new issue or fix it in this ticket?

**Comment by reflog** [comment]
@ethervoid - if it's a one-liner fix, please add it here. Otherwise - open a new issue. 
Thanks!

**Comment by lindy65** [comment]
Hi @ethervoid - if you're going to fix in the PR, I'll wait to QA test, otherwise I can test now, please let me know? Thanks!

**Comment by ethervoid** [comment]
Hi @lindy65 . You can QA test this issue because I've created [a new one](https://mattermost.atlassian.net/browse/MM-20639) for the other issue so I'm not going to fix it in this PR. Thank you!

**Comment by lindy65** [comment]
Thanks @ethervoid - I'll go ahead and test then :)

**Pull request merged**
