### PR TITLE
change the plugins icon in the channel header - in case of multiple p…

### PR DESCRIPTION
**Pull request by pradeepmurugesan**
…lugins

#### Summary
change the plugins icon in the channel header - in case of multiple plugins associated with the channel

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/12359
Jira ticket: https://mattermost.atlassian.net/browse/MM-17506
#### Related Pull Requests

- Has server changes - NO
- Has redux changes - NO
- Has mobile changes - NO

### CODE REVIEW

**Comment by aaronrothschild** [comment]
Thanks @pradeepmurugesan 

The icon and the number (3 in this case) don't look vertically aligned very well:
image

For others, I loaded a few plugins up and this is what the menu looks like now:
image

**Comment by pradeepmurugesan** [comment]
Hello @aaronrothschild  Thanks for taking a look. Will fix the css now and let you know

**Comment by pradeepmurugesan** [comment]
@aaronrothschild kindly check now

**Comment by aaronrothschild** [comment]
Thanks, Looks good to me:
image

**Pull request merged**
