### PR TITLE
Upgrade pdfjs-dist to latest version

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR upgrades PDFJS-dist to the latest version. Includes minor breaking changes.

Note for QA: uploading and previewing a pdf file should work the same as on master.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32929

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by jupenur — APPROVED** [review]
Great stuff, thanks for tackling this @nevyangelova!

**Comment by nevyangelova** [comment]
@hmhealey I started seeing this message on master recently, I am not sure if its related. But would be interesting to investigate.

**Review by M-ZubairAhmed — APPROVED** [review]
Great work on this

**Comment by nevyangelova** [comment]
@hmhealey kind reminder to review :)

**Review by hmhealey — APPROVED** [review]
This looks good to merge since it'll hopefully unblock people that end up using NPM 8 like we keep seeing.

@nevyangelova Would you mind filing a followup to look into that warning some more when we get the chance? I haven't figured out what the side effects of it are, but it seems like it might be fixable by importing the package a webpack version of the package ([link](https://github.com/mozilla/pdf.js/tree/master/examples/webpack#worker-loading)). According to the Webpack docs, we don't need `worker-loader` though becuse we're on Webpack 5

**Pull request merged**
