### PR TITLE
Mm 15723 analytics screen remove finddomnode

### PR DESCRIPTION
**Pull request by 93lykevin**
#### Summary
  Removed findDOMNode and replaced it with Refs on the Analytics Screens

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/15723

### CODE REVIEW

**Review by reflog — APPROVED** [review]
LGTM!

**Review by hmhealey — APPROVED** [review]
Thanks for the PR! Looks good to me running on my local instance.
Screen Shot 2020-10-15 at 2 08 17 PM

@jgilliam17 It's possible that this won't be testable well on the test server if the server hasn't been around for long enough, but if that's the case, we can leave it for a few days to give it enough data to generate the charts.

**Review by saturninoabril — APPROVED** [review]
@93lykevin Thank you for contribution! Tested and passed.

**Pull request merged**
