### PR TITLE
Clean up some unused channel-related code

### PR DESCRIPTION
**Pull request by hmhealey**
Each commit should be fairly self-explanatory, but to provide some more context on the first two:
- Fake channels are an old concept that was used to show channels in the sidebar that didn't exist yet. A very long time ago, new users would automatically have a number of DM channels appear in their sidebar to make Mattermost look more friendly to new users, but those channels weren't created in the DB until the user viewed them. That was later removed during a previous sidebar redesign, and that code was left over from before that.
- `Channel.ExtraUpdateAt` is no longer used on the server as of https://github.com/mattermost/mattermost-server/pull/8762 (https://mattermost.atlassian.net/browse/MM-9739). It's still around and unused, and removing it from the type definition on lets us just ignore it on the client.

This is done in preparation for https://mattermost.atlassian.net/browse/MM-37021 since the rest of that is blocked by https://github.com/mattermost/mattermost-webapp/pull/8503 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Thank you for the discrete commits!! Looks good, and excited for the next round of changes.

**Review by larkox — APPROVED** [review]
LGTM.

**Comment by hmhealey** [comment]
Skipping QA review since this is just dead code removal.

**Comment by amyblais** [comment]
@hmhealey Is this for v6.0?

**Comment by hmhealey** [comment]
Nope, it's not needed for it. Thanks for checking though

**Pull request merged**
