### PR TITLE
[MM-19985] Fix modal not displaying correctly

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Fixes modal not showing up correctly (opening up when it should be opening down)

**The fix that I implemented was rather than opening the modal up for the last 5 items in the list , I open it up for the last 3 items in the list ONLY if there is more than 5 items in the list.**

@jasonblais I tried implementing the fix we are using in the chat channel where we decide to open the modal up or down depending on the screen size available but that was proving to be very difficult so I decided to go with this fix. Please let me know your opinion. Thanks!

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19985

#### Screenshots
**Prefix**
image
image

**Post Fix**
image
image
image

### CODE REVIEW

**Comment by hmhealey** [comment]
It'd be nice if we could add some better detection of where the dropdown should open, but that'll require us to drop react-bootstrap for those dropdowns entirely since their edge detection has never been good.

**Comment by jasonblais** [comment]
@hahmadia It fixes the issue partially, but not when there are, say, 10 users in the list and you click on the 5th one that's visible on the screen

image

However, based on Harrison's comment, I'm not sure how much effort the proper fix is, so want to be cautious of how much effort is spent on this

**Comment by hahmadia** [comment]
@jasonblais 
That's true but I think currently with any "quick solution" there will be a trade off (unless someone else has a better idea?). The point of the fix is to allow users to be able to see the modal and click on menu items and not have it hidden behind the border where it is not visible at all. In the scenario you presented, it is still possible to scroll down and click on menu items. It's not perfect but at least the user can select the menu items. If we want to use available screen width, the complexity increases and it will become more effort and harder problem to fix. This is the best solution I had in mind for the problem that came about but I'm not sure if we want to hold back to work on the "best solution" (and as Harrison mentioned would require some rework) or if this solution is viable for the current problem users would face. Thoughts?

**Comment by jasonblais** [comment]
> The point of the fix is to allow users to be able to see the modal and click on menu items and not have it hidden behind the border where it is not visible at all.

Good point 👍 

> If we want to use available screen width, the complexity increases and it will become more effort and harder problem to fix

Yeah, and I feel that's not worth the time at this point.

Approving, the most pressing issue is resolved here. Thanks @hahmadia!

**Pull request merged**
