### PR TITLE
[MM-344156] - Fix regression for channel members modal

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
PR https://github.com/mattermost/mattermost-webapp/pull/6913 caused a minor regression for the channel members modal. Adding an extra class for the direct channel modal for setting min height makes sure the other modals aren't affected. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34416

### CODE REVIEW

**Comment by amyblais** [comment]
@hmhealey @calebroseland @jgilliam17 We could get this fixed before tomorrow's April 7th cloud release.

**Review by michelengelen — CHANGES_REQUESTED** [review]
Sry to step in here, but it seems as if the change was the wrong way around. 

I had a quick look at it and talked to @matthewbirtch about it.

Each row should have a height of `50px` like it is on community at the moment. the change to `min-height: 65px` on community-daily is not intended and should be fixed here.

Would you e able to provide a fix here @nevyangelova or should I take over?

**Comment by jgilliam17** [comment]
Thank you @nevyangelova 
Channel member modal looks good. 
Seeing a slight discrepancy with other user lists, e.g. Add Direct Message or Manage members modal, that seems to be impacted by this change.
The bot name has a different height when compared to other members, sometimes  See image and video.

Screen Shot 2021-04-06 at 1 16 08 PM

https://user-images.githubusercontent.com/52937121/113752349-da091f80-96da-11eb-97d2-cd5ef3352e50.mov

**Comment by michelengelen** [comment]
thanks @jgilliam17 ... I added a fix for that!

**Review by hmhealey — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]
LGTM

**Comment by michelengelen** [comment]
Argh... stupid GitHub UI... i accidentally removed the de reviewers. 🙇‍♂️ sorry about the confusion.

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen and @nevyangelova 
Tested, looks good to merge.
- Verified channel members popover modal list spacing - as expected.

**Comment by amyblais** [comment]
Can merge to master for the next cloud release in April 21st.

**Review by michelengelen — APPROVED** [review]

**Pull request merged**
