### PR TITLE
Hide "Help Resources" button when help link is empty

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

Currently, even if `Help Link` in the system console is empty, it still shows up in the global header. This PR adds a non-empty condition.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-44165

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2023-01-19 at 2 06 00 PM | Screenshot 2023-01-19 at 2 06 15 PM |

#### Release Note

```release-note
Fixed a bug where Help Resources button pointed to the current link in a new tab, if empty.
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working fine

**Pull request closed without merging**
