### PR TITLE
MM-18541 Size list padding dynamically

### PR DESCRIPTION
**Pull request by hmhealey**
Currently, the left padding for lists is a fixed width, so larger numbers get cut off. To make it dynamically-sized with pure CSS, you aren't able to have the bullets right-aligned, so we have to do work out the padding manually (or do something crazier like switching the list to a table).

I'm actually quite happy with how the formula to calculate that worked out. I didn't know about the `ch` unit or that you could size things in CSS based on the width of a character before now.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18541

#### Screenshots
image
Screen Shot 2019-11-23 at 11 18 34 AM

### CODE REVIEW

**Comment by hmhealey** [comment]
That's about right, although to be exact, it would say `9999` and have a margin of `7ch` to fit the numbers, period, and a bit of whitespace

**Comment by deanwhillier** [comment]
Hey @hmhealey, looks like the alignment is still a bit off in a few cases as currently seen on the SpinWick above: 
image (see the 999/1000 and 99999/100000 entries). Admittedly those are unlikely situations, but do point to the possibility of being off.

I think the challenge with the `ch` unit is it [depends on the font](https://meyerweb.com/eric/thoughts/2018/06/28/what-is-the-css-ch-unit/) – if the font is fixed-width (like courier), then it can absolutely be used to define a consistent width to hold text, but if it is a variable-width font (like open sans), then it kinda falls flat. Even if only one character has a slightly different width to all the others, that can mess up the overall measurement.

I took a few minutes to play around with lists and css and came up with the following based on some searching and experimenting for your consideration: https://jsfiddle.net/owdbs72r/2/. The markup is still list-based, but the css converts to tables and uses counters and content selectors to re-introduce the list numbers. Any lists that start with `1` don't need to have any additional html attributes and any lists that start with a greater number need a style attribute to reset the list count (they would need an attribute to set the initial list number regardless).

I'd be more inclined to use a CSS approach over JS calculations so the browser can take care of the details, though admittedly doing character-based padding is kinda cool ... I honestly didn't realize that existed!

Let me know what you think!

**Comment by hmhealey** [comment]
I'll take a look at the CSS solution. It definitely sounds interesting, and pure CSS would be a bit nicer, although I am a bit worried it might be too magic. Then again, that might just be because I don't understand the properties used for it.

I wouldn't be opposed to sticking with the JS solution though. Since we have a set font and we're only using a limited subset of characters for list indices (0-9, period, and space), chances are that the current method would work fine enough. The main reason I'd lean towards sticking with this for now is that it's easier to understand how it works right in JS since we are close to code complete, although I don't know if it's necessary for this to go into 5.18.

@esethna Thoughts on moving this to 5.19 or 5.20 so that we have more time to do it right? This solution is already a bit involved for a bug fix, and it's worked the same way since at least 5.14, probably earlier.

**Comment by esethna** [comment]
That's fine, moving it to v5.19

**Comment by hmhealey** [comment]
I've updated this to use the technique that Dean found, so I've re-requested reviews on it. This now also involves a marked.js change so that we don't have to calculate the initial index of the list any more.

The PR for that is here: https://github.com/mattermost/marked/pull/17

**Comment by hmhealey** [comment]
And here's a screenshot of how it appears with the updated changes. It looks pretty much the same.
Screen Shot 2019-12-03 at 5 19 48 PM

**Comment by bradjcoughlin** [comment]
Google Docs does it a little differently, adding enough spaces for the tens place initially to the right. Once the list hits 100, then enough space is added for the ten-thousands place it seems:
Screen Shot 2019-12-03 at 3 35 06 PM
Screen Shot 2019-12-03 at 3 31 20 PM

**Comment by hmhealey** [comment]
Yeah, they aren't styling it quite the same way since they're not using a fixed width for their list numbers. For another point of reference, GitHub does the same thing we do without this ticket.

1. a
1. b
1. c

---

99999. a
1. b
1. c

**Comment by deanwhillier** [comment]
Looks good @hmhealey! I noticed one more CSS tweak that we should probably make. Sub numbered bullets have padding added by a CSS rule with more specificity that is making them look way more indented now that we are using `::before`. The rule from dev tools is:
``` css
.post__body ol li ol {
    font-size: 1em;
    margin: 0;
    padding: 0 0 0 20px;
}
```
We need to override the left padding for any `ol`'s that now have the `markdown__list` class.

image

**Comment by cpanato** [comment]
will delete this test server because i need to deprecate the cluster that is running, will spin a new test server soon

**Comment by hmhealey** [comment]
I removed that rule for ordered lists so it now indents those as it did before. I posted screenshots below of the new code (the light theme) and the old code (the dark theme)

New:
Screen Shot 2019-12-18 at 4 20 19 PM

Old:
Screen Shot 2019-12-18 at 4 20 34 PM

**Pull request merged**
