### PR TITLE
[MM-38283] - fixed `SUGGESTION.UNDEFINED` in quick-switch modal

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
when using the quick switch modal with results that had different types of items in the results (open, public and archived channels and direct messages) it was showing `SUGGESTION.UNDEFINED` as a divider for the direct messages.

This fix involves setting a new property on the items for direct messages in the `SwitchChannelProvider`.

#### Ticket Link
[MM-38283](https://mattermost.atlassian.net/browse/MM-38283)

#### Screenshots
|  before  |  after  |
|-----|-----|
|Screenshot 2021-09-08 at 15 05 01|Screenshot 2021-09-08 at 15 04 17|

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
LGTM

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @michelengelen I see some doubling of the Direct Message label

Screen Shot 2021-09-10 at 10 30 15 AM
Screen Shot 2021-09-10 at 10 23 18 AM

**Comment by michelengelen** [comment]
Great find @jgilliam17 ... could you tell me how you produced those? I cannot seem to find a way to myself! 😁

**Comment by jgilliam17** [comment]
I don't think I did anything unusual, opened the channel switcher after adding test users, channels etc - let me take a look.

**Comment by jgilliam17** [comment]
@michelengelen Ah, deleting search term adds an extra Direct Message label

**Comment by michelengelen** [comment]
@jgilliam17 I will postpone this to after the productivity sprint. IMO there are more things to be adjusted. I have already asked @esethna about open questions regarding this.

**Comment by jgilliam17** [comment]
Sounds good.  Thanks @michelengelen

**Comment by michelengelen** [comment]
@jgilliam17 it should be ready to re-reviewed now.

**Comment by jgilliam17** [comment]
@michelengelen the issue with multi DM label is resolved. 
There's a new issue with the private channels being in undefined section
Screen Shot 2021-09-22 at 8 58 01 AM

**Comment by michelengelen** [comment]
@jgilliam17 I fixed that as well ... could you have a look again. 

IMO we should rework a lot of the stuff going on there. 🚀

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified Channel Switcher shows correct categories, no longer shows `SUGGESTION.UNDEFINED` for Direct Messages nor any other channel categories.

**Comment by jgilliam17** [comment]
@michelengelen update branch didn't work, couldn't merge - please take a look when you have a chance. Thanks.

**Pull request merged**
