### PR TITLE
Fix typo (openraph -> opengraph) in CSS classes

### PR DESCRIPTION
**Pull request by ThiefMaster**
#### Summary
Fix typo in CSS classes

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by jasonblais** [comment]
@ThiefMaster Sorry for the delay here - can you help rebase your PR? @hmhealey once rebased, please help merge?

Thanks for fixing the typo! :)

**Comment by ThiefMaster** [comment]
sorry, currently at a festival with limited access. feel free to rebase and forcepush to my branch though

**Comment by jasonblais** [comment]
> sorry, currently at a festival with limited access. feel free to rebase and forcepush to my branch though

No worries! Enjoy the festival :)

@hmhealey Perhaps you can help with that?

**Comment by hmhealey** [comment]
Ready to merge once the build finishes

**Pull request merged**
