### PR TITLE
MM-12047: Fix LHS unusably slow scrolling on FF

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
- Replaces perfect scrollbar with the scrollbar used in the RHS
- Fixes issue on FF where scrolling was unusably slow
- Tested on all browsers we support (except safari)

### CODE REVIEW

**Comment by jasonblais** [comment]
This is really awesome by the way, thanks for doing this Chris!

**Comment by crspeller** [comment]
@jasonblais I didn't notice that the system console sidebar did the same thing. It doesn't fix that sidebar, because it's actually a separate component. A similar fix could probably be done for that sidebar as well. But that would be a separate PR.

**Comment by jasonblais** [comment]
Cool, ticket created for System Console LHS: https://mattermost.atlassian.net/browse/MM-12051

Will queue for dev review once QA has had a chance to review and test if they'd like to.

**Comment by lindy65** [comment]
Thanks @crspeller @jasonblais 

Tested on Firefox/Win10 and it looks good to me. (Noted that System Console scrollbar will be fixed in a separate PR).

**Comment by crspeller** [comment]
@hmhealey Ideally yes. I didn't know this existed before.

**Pull request merged**
