### PR TITLE
Added additional cypress tests part of MM-29347

### PR DESCRIPTION
**Pull request by srkgupta**
#### Summary
MM-29347: E2E Cypress Tests - System Console > Enterprise > Group Mentions (Part 2)

#### Ticket Link
JIRA Ticket:
[MM-29347](https://mattermost.atlassian.net/browse/MM-29347)

TM4J Tests:
[MM-T2447](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2447)
[MM-T2460](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2460)
[MM-T2461](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2461)

#### Related Pull Requests
None

#### Screenshots
Screenshot 2020-10-06 at 7 35 45 PM

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]
Code looks very clean and nicely documented. I like! 👍

**Comment by srkgupta** [comment]
The last commit was actually a fix based on the [PR 6652](https://github.com/mattermost/mattermost-webapp/pull/6652)

**Review by prapti — APPROVED** [review]
@srkgupta I haven't run the test because my local server has not run normally today. But I gave it a thorough look, and it looks great! Also checked 
Approving.
Also a quick note that the associated Jira ticket has more tests than are covered in this PR, not sure what the state of the other tests are, so I haven't closed that one.

**Pull request merged**
