### PR TITLE
MM-44514: display correctly the emojis independently of the case (should work even if the user typed some capital cases)

### PR DESCRIPTION
**Pull request by ismaaylSpiria**
#### Summary
Display correctly the emojis independently of the case (should work even if the user typed some capital cases)

#### Ticket Link
[MM-44514](https://mattermost.atlassian.net/browse/MM-44514)

#### Release Note
```release-note
Fully typed emoji that contains a capital letter are now correctly displayed
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
Thanks for fixing this! LGTM!

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @ismaaylSpiria 
Tested, looks good to merge - pending e2es.
- Verified Emojis display correctly when capital letters are used.

**Comment by jgilliam17** [comment]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/211640-5906452-onprem-ent-webapp-pr-10544-mattermost/mm-ee-test5906452/mochawesome.html) - PR related failures

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
