### PR TITLE
MM-43168 : Update web app dependencies (June 2022)

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
- @floating-ui/react-dom : [Bug fix](https://github.com/floating-ui/floating-ui/pull/1752)
- @mattermost/compass-icons : Icons updated
- core-js : [Internal code changes](https://github.com/zloirock/core-js/blob/master/CHANGELOG.md#3233---20220626) as per latest TC39 meetings
- html-to-react : Ramda [dependency removed](https://github.com/aknuds1/html-to-react/blob/master/CHANGELOG.md)
- react-window-infinite-loader : internal [react 18 update](https://github.com/bvaughn/react-window-infinite-loader/pull/53)
- nock : [bug fixes](https://github.com/nock/nock/releases/tag/v13.2.8)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43168

#### Related Pull Requests
N/A

#### Screenshots
N/A

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
LGTM

**Review by michelengelen — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@jgilliam17 i just tried with the steps you provided, i am unable to reproduce. Also the error messages seems to be about few resources not loading. Can you please try again and check

**Comment by jgilliam17** [comment]
Thanks for checking @M-ZubairAhmed 
Re-tested - looks good to merge.
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/215829-41b9f89-onprem-ent-webapp-pr-10714-mm-ee-test:41b9f89/mochawesome.html)looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
