### PR TITLE
[MM-13824] add one_you strings for better translatability 

### PR DESCRIPTION
**Pull request by MartB**
#### Summary
Adds new strings for team/channel related messages for better translatability.
Proper translation to the german language  was impossible before.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/10335
[MM-13824]

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Needs to be implemented in mobile [PR](https://github.com/mattermost/mattermost-mobile/pull/2604)
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by MartB** [comment]
I could complete the german translations but i guess they need to go through pootle first, right? I did not edit the german file because i didnt want to manually mess around there possibly breaking automatic imports ^^

**Comment by jasonblais** [comment]
@MartB no need - as you mentioned they'll be done via Pootle. So the PR was submitted correctly 👍

**Comment by jespino** [comment]
I don't know about German, but in Spanish, probably in the plurals makes sense as far as you are part of the users involve. It is not the same to say "X, Y, Z and me left the channel" than "X, Y,  and Z left the channel", the verb in Spanish is in a different form, I mean "We" and "They" use different verb form.

**Comment by MartB** [comment]
Yeah, i think with num_others >= 1 it should also make sense in german. The only special case we needed was for introducing:
"Sie haben ..." instead of "Sie hat ..." because "hat" is only used for a single person that is not yourself in german. (third person)

**Comment by jespino** [comment]
Ok, then get this merge and we can solve the "spanish" thing later.

**Comment by MartB** [comment]
Sounds like a plan!

**Pull request merged**
