### PR TITLE
Fix pinned post list from refreshing

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
While working on the ticket to try and fix a bug that no longer reproduces I found myself refactoring this to avoid unnecessary re-renders

Affected areas:
Search results, pinned posts, flagged posts

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12938

### CODE REVIEW

**Comment by enahum** [comment]
@jwilander requested test from @DHaussermann

**Comment by enahum** [comment]
@DHaussermann don't forget to test this one please

**Comment by enahum** [comment]
ok @DHaussermann I'll take a look at why that is happening, I'll let you know.

**Comment by enahum** [comment]
@DHaussermann definitely happening on master and I know why, I'll fix it with this PR

**Comment by DHaussermann** [comment]
@enahum yes you're correct (sorry I accidentally verified on CI and thought it was working on master). I can create a new bug for this. 

No other issues found. The following regression testing was done for this PR:
1. Search results, 
2. Pinned posts
3. flagged posts 

For each:
- Open and close 
- Data stays current Add / Remove
- Data in pain updates in real time 
- Pinned posts are relevant to current channel
- Elements such as jump and reply are working
- No strange UX behavior while browsing or posting

No other issues found.

**Comment by enahum** [comment]
seems that the regression was introduced in #1897

**Comment by enahum** [comment]
@DHaussermann fixed, try again please

**Comment by DHaussermann** [comment]
Thanks @enahum 

This now working as expected again.
- In the Pinned posts pain label is removed in rel time and updated next tine it's viewed when data changes
- Pinned posts pain updates as user changes channel

Added test steps to JIRA 

Looks good to me.

**Pull request merged**
