### PR TITLE
New Code of Pluggable.jsx for Mattermost-Webapp

### PR DESCRIPTION
**Pull request by drraghavendra**
Please see the latest updates of Pluggable.jsx for Mattermost-webapp under plugins category

### CODE REVIEW

**Comment by hanzei** [comment]
@drraghavendra Is there a ticket that you are trying to fix with this PR?

**Comment by drraghavendra** [comment]
suggesting to "import ReactTable from 'react-table/lib'" along with code available in pluggable.jsx which I  posted earlier.Please let me know your thoughts

**Comment by drraghavendra** [comment]
Kindly be informed to see the last post and let me know your thoughts, review procedure.

**Comment by drraghavendra** [comment]
Sir @jasonblais pluggable.jsx   suggesting to add "import ReactTable from 'react-table/lib'" along with code available in pluggable.jsx which I posted earlier.Kindly review and Please let me know your thoughts

**Comment by jasonblais** [comment]
Thank you @drraghavendra - I will defer to @hanzei and team for next steps

**Review by hanzei — CHANGES_REQUESTED** [review]
`plugins/pluggable/Pluggable.jsx` already exists as `plugins/pluggable/pluggable.jsx`. Would you please remove it from this PR?

**Comment by jfrerich** [comment]
Hi @drraghavendra, do you need any assistance on this PR? Does comment form @hanzei make sense?

**Comment by drraghavendra** [comment]
please update on the above Pull request as the code is viable and updated

**Comment by drraghavendra** [comment]
Sir Request you to please update on the above Pull request as the code is viable   @jasonblais @jfrerich @emilyacook

**Comment by jasonblais** [comment]
Hi @drraghavendra - from the latest comment from @hanzei, it looks like we are already importing the React table at https://github.com/mattermost/mattermost-webapp/blob/master/plugins/pluggable/pluggable.jsx

Let me know if I'm misunderstanding the changes in this PR?

**Comment by drraghavendra** [comment]
Sir Please make a note   the code is  more logical and even viable @jasonblais .Hence I request you to merge the PR

**Comment by drraghavendra** [comment]
Sir Please make a note the above code  which provided by myself is  logical and even viable @jasonblais .Hence I request you to merge the PR

**Comment by drraghavendra** [comment]
Kindly make a note as the PR is accepted in Hacktoberfest. Please Merge PR as Quickly as possible.

**Comment by jasonblais** [comment]
@drraghavendra would you be open to describe your exact changes of this pull request? You mentioned you added importing a React library, but it looks like this is already done in the pluggable.jsx file: https://github.com/mattermost/mattermost-webapp/blob/master/plugins/pluggable/pluggable.jsx

If there is a link to an existing GitHub issue, that is fine as I can review it. 

If there isn't a link to an existing GitHub issue, please see our process for contributions without a ticket: https://developers.mattermost.com/contribute/getting-started/contributions-without-ticket/

**Comment by drraghavendra** [comment]
Sir check the code as it is more viable and less no of lines code involved @jasonblais

**Comment by jasonblais** [comment]
Thanks @drraghavendra, given https://github.com/mattermost/mattermost-webapp/blob/master/plugins/pluggable/pluggable.jsx includes properties such as `pluggableId` and `subComponentName`, I'll close this PR in favor of what we currently have.

If there is a specific improvement or use case this helps address, please link to an existing GitHub issue, or otherwise see our process for contributions without a ticket: https://developers.mattermost.com/contribute/getting-started/contributions-without-ticket/

**Pull request closed without merging**
