### PR TITLE
active state for iconbuttons in global header

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
changed the `toggle` appearance to `active` when the menus are open.
components that are changed:
1. `ProductSwitcher`
2. `UserGuideDropdown`
3. `SidebarHeader`

The `Avatar` active styling already got handled by @nevyangelova in #8585 

#### Ticket Link
[MM-37799](https://mattermost.atlassian.net/browse/MM-37799)

#### Screenshots
|  component  |  before  |  after  |
|-----|-----|-----|
|  `ProductSwitcher`  |Screenshot 2021-08-19 at 15 51 38|Screenshot 2021-08-19 at 15 47 16|
|  `UserGuideDropdown`  |Screenshot 2021-08-19 at 15 52 43|Screenshot 2021-08-19 at 15 51 51
|  `SidebarHeader`  |Screenshot 2021-08-19 at 15 53 23|Screenshot 2021-08-19 at 15 52 59|

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by andrewbrown00** [comment]
Hey, @michelengelen, same issue with this test server. The **Global Header** feature is not available.

**Comment by michelengelen** [comment]
> Hey, @michelengelen, same issue with this test server. The **Global Header** feature is not available.

@andrewbrown00 I will get in touch with the cloud team to see what is missing here.

**Review by nevyangelova — APPROVED** [review]
LGTM although the PR you mentioned also adds the state for the user_guide_dropdown :D and product switcher menu but I think it wouldn't create conflicts so its g2g 👍

**Comment by michelengelen** [comment]
> LGTM although the PR you mentioned also adds the state for the user_guide_dropdown :D and product switcher menu but I think it wouldn't create conflicts so its g2g 👍

@nevyangelova thats why i suggested to merge it asap and go forward from there with small incremental updates... those mammoth-PRs are a hell to maintain, review and keep track of.

**Comment by michelengelen** [comment]
@spirosoik we are facing a white screen again, when trying to access the server ... something is off here. :/

**Comment by andrewbrown00** [comment]
Yeah, I'm still seeing the white screen 😞

**Review by andrewbrown00 — APPROVED** [review]
Thanks, @michelengelen, changes look good 🙂  and yes, the `test server` is finally working 🙌 

* Verified we are using the `active state` and not the `toggle state`  ✅ 
* Verified on dark themes as well ✅ 

Product switcher | Help | Sidebar header | Dark theme
----- | ----- | ----- | -----
image | image | image | image

**Review by deanwhillier — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified active state of global header icons (not using toggle state) in light and dark themes.

**Pull request merged**
