### PR TITLE
[MM-11264] Added statuses to channel invite modal

### PR DESCRIPTION
**Pull request by courtneypattison**
#### Summary
Adds user statuses to "add member to channel" list

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/11264

#### Screenshots
Screen Shot 2020-12-09 at 4 28 11 PM

### CODE REVIEW

**Review by esethna — APPROVED** [review]
Thanks @courtneypattison! 

FYI @asaadmahmood on this PR

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks for contributing :)

**Comment by esethna** [comment]
@asaadmahmood how do you want to proceed with this PR? Would it be best to close this and merge the changes into your PR for the add members modal? We probably want to match the designs you did for how the online status appears in the autocomplete?

**Comment by jfrerich** [comment]
@esethna I'm not sure the best way to push this forward. @asaadmahmood, could you help with this. If not, I understand and I hope you've been well!

**Comment by asaadmahmood** [comment]
@esethna Yup, we can close this PR and I can add the statuses in another PR.

**Comment by esethna** [comment]
cc// @courtneypattison, so we'll close this Pr and merge the changes in Asaads other PR

**Comment by courtneypattison** [comment]
@esethna thank you for the heads up!

**Pull request closed without merging**
