### PR TITLE
[MM-38091] - Adjust custom status menu item according to new designs

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
This PR adds the change to the custom status dropdown according to new design, including of aligning the status + expiry time if set, and removing the clear button, changing help text colour.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38091

#### Screenshots

Screenshot 2021-10-20 at 12 41 35
Screenshot 2021-10-20 at 12 41 44
Screenshot 2021-10-20 at 12 41 54

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — APPROVED** [review]
Thanks @nevyangelova. Tested without status text, with/without expiry time and it displays as designed. Nice work

**Review by devinbinnie — APPROVED** [review]

**Review by michelengelen — APPROVED** [review]

**Review by matthewbirtch — APPROVED** [review]
Thanks @nevyangelova!

**Review by jgilliam17 — CHANGES_REQUESTED** [review]
Thanks Nevy
Can you please also change the following?

**Review by michelengelen — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified updated custom status.

**Pull request merged**
