### PR TITLE
[MM-49090]: Exclude file count on channel stats api call on from channel header

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Exclude file count on channel stats api call on from channel header.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-49090

#### Related Pull Requests
- Has server changes (Merged) https://github.com/mattermost/mattermost-server/pull/22096

#### Release Note
```release-note
* Exclude file count on channel stats api call on from channel header.
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@itao @asaadmahmood, are we fine with files count number updating after some time and if not, what should we do? In this change we will call the file count API (channel stats API) with file count info if user opens channels info section, but that cause the issue in video. Please go through the ticket to understand why this change is necessary.(TL;DR, due to file count info channel stats, API was crashing servers).
https://user-images.githubusercontent.com/16203333/220527243-dce01392-6016-4c89-bf96-d26e02c30569.mov

**Comment by Willyfrog** [comment]
maybe we can hide the number until we get the info from the server?

**Review by itao — APPROVED** [review]
Functionally I'm onboard with not fetching this stat when opening channels since it's not rendered anyways until user opens RHS. I'm 0/5 on animation options (ie. hide, spinner, as demoed in video) and look to @asaadmahmood for guidance there

**Comment by asaadmahmood** [comment]
@AshishDhama I think we should use a small spinner instead of the "0". And then show the number when its fetched.

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
It's going to look something like this:
https://www.figma.com/file/43xvK7GOEPh6VJ31UfRvSg/MM-28021-Channel-Info-RHS?node-id=3145%3A170687&t=GMqgqRWpaDzPfkY4-11

Let me know if we have a spinner available somewhere in the webapp, we can use the same one.

**Review by neallred — APPROVED** [review]
LGTM, thanks @AshishDhama !

**Comment by AshishDhama** [comment]
@asaadmahmood Could not find the spinner you had in the figma, I have added the one have in the app.

**Comment by asaadmahmood** [comment]
Maybe move the spinner 4px on the right a bit, we need it to be centered with the text above it.
Screenshot 2023-03-09 at 10 22 35 PM

Also, sometimes I get -1 as the count.
Screenshot 2023-03-09 at 10 23 15 PM

**Comment by asaadmahmood** [comment]
@AshishDhama Have a look.

**Comment by Willyfrog** [comment]
just a heads up that this might need to be backported as more clients are affected by the stat problem.

**Review by asaadmahmood — APPROVED** [review]
LGTM apart from the 0 files issue I sent Ashish when switching channels.

**Review by Willyfrog — APPROVED** [review]
Lgtm

**Comment by AshishDhama** [comment]
> LGTM apart from the 0 files issue I sent Ashish when switching channels.

Thanks for the video @asaadmahmood, Have fixed the issue.

**Review by furqanmlk — COMMENTED** [review]
@AshishDhama 
1. When files are added, the File counter gets increased right away, but when files are deleted; the counter does not get decreased until refreshed or reopened Channel info or revisited.

2. API is still giving `-1` with  `exclude_files_count=true`

image

**Comment by AshishDhama** [comment]
@furqanmlk 
1. It is happening on the community server, so it's not related to this

https://user-images.githubusercontent.com/16203333/225000530-2d76ee67-ef1b-4373-9f85-a45a33d6fad6.mov

2. Yeah, it gives back file count because that's what we do on the backend.

So none of the above should block this. For 1, could you please create a separate ticket?

@Willyfrog, should we change this https://github.com/mattermost/mattermost-server/blob/b6d13806a78ebc4715c530f6eba3d745497398ac/api4/channel.go#L661
Although on the Frontend, the only place we use file count is Channels info Rhs, we have handled this -1 value there.

**Review by furqanmlk — APPROVED** [review]
Thanks @AshishDhama and @Willyfrog

**Comment by AshishDhama** [comment]
Closing in favour of https://github.com/mattermost/mattermost-server/pull/22624

**Pull request closed without merging**
