### PR TITLE
Switch to using @mattermost/compass-icons package

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
This PR updates the webapp to import Compass Icons from the new NPM package in favour of the embedded version we have been using to date. This will make it easier to manage versions and to update the font when new icons come down the pipe from Design.

#### Release Note
There should be zero difference from an end user perspective, so not sure release notes are needed?

```release-note
NONE
```

### CODE REVIEW

**Comment by deanwhillier** [comment]
Looks like a type error made it's way into my PR from merging master ... investigating.

**Comment by deanwhillier** [comment]
K, type error fixed.

**Review by hmhealey — APPROVED** [review]
Looks great!

**Review by nevyangelova — APPROVED** [review]

**Review by esethna — APPROVED** [review]

**Review by michaelgamble — APPROVED** [review]
Looks good to me :)

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified icons in the app - no change, as before.
Out of scope question: Do we have an icon for "Getting Started"? Noticed it was missing on mobile webview menu.

**Comment by deanwhillier** [comment]
@michaelgamble, @matthewbirtch, do you guys know if there is an icon for the "Getting Started" menu item in the mobile phone view? (See @jgilliam17's question above)

**Comment by matthewbirtch** [comment]
> @michaelgamble, @matthewbirtch, do you guys know if there is an icon for the "Getting Started" menu item in the mobile phone view? (See @jgilliam17's question above)

1. Can we use `icon-play` for "Getting Started"?
2. Can we use ` icon-lightbulb-outline` for "Tips and Next Steps"?

**Comment by deanwhillier** [comment]
@matthewbirtch, icon has been added if you want to take a quick look once the spinwick has updated

**Review by matthewbirtch — APPROVED** [review]
thanks @deanwhillier

**Pull request merged**
