### PR TITLE
Cypress/E2E: Improve handling of specs to properly distribute in parallel

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Currently, the specs are being subdivided into all the parallel test runners. So if there are 400 spec files for 4 runners, each runner will get 100 spec files to run the test. Depending on spec files assigned, a runner can be completed longer than the other, and the accumulated difference could go as high as one hour (at the moment). When a runner unexpectedly quit for some reason, untested spec files will not be able to process and will require to retest all over again.

In this PR, the runner is not  pre-assigned with spec files. Instead, each runner gets one spec file at a time until all specs are completed. The typical flow would be:
1. Filter out spec files to run and save into the remote dashboard server. It is done by `node generate_test_cycle.js --stage="@prod"`
2. Each runner claims an available spec file from the dashboard server. Once completed, a runner records the result to the server and then claim again until no more spec file available. It is done by `node run_test_cycle.js`.
3. When a runner quits unexpectedly, processing of the remaining spec files will still continue and will be shared among the available runners.
4. A runner may get different number of spec files but each runner will be completed in almost the same time.

Note: The dashboard server is done on a separate repo. Initially at https://github.com/saturninoabril/automation-dashboard

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21950

#### Screenshots
Screen Shot 2021-04-08 at 11 15 15 AM

### CODE REVIEW

**Comment by josephbaylon** [comment]
@saturninoabril Can you add in the summary how this distributes evenly with time?

**Comment by saturninoabril** [comment]
@josephbaylon Sure. Please take a look again.

**Comment by josephbaylon** [comment]
@saturninoabril Awesome! Thanks for the explanation. It now makes sense to me

**Review by josephbaylon — APPROVED** [review]
LGTM. I was now able to understand the workflow with your summary. This a great improvement!

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril 
It looks good and amazing 👍

**Review by prapti — APPROVED** [review]
This is great! I just added a tiny text change. Hope that's right. Thanks Saturn!

**Comment by saturninoabril** [comment]
Thanks for updating Prapti!

**Pull request merged**
