### PR TITLE
[MM-50811] Enable loading translation files asynchronously

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

While working on Calls i18n support I was looking to load translation files dynamically at time of need vs bundling them all together but it seems like it wasn't possible without some minor changes. Making `registry.registerTranslations()` accept both types of functions (sync/async) seems to be working fine.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-50811

#### Release Note

```release-note
Added support for passing asynchronous functions to registry.registerTranslations()
```

### CODE REVIEW

**Comment by hmhealey** [comment]
What's the motivation for wanting to load those translations with an async function? Since we're awaiting on them, it ends up being basically synchronous even if it's loading the plugin i18n strings concurrently now.

I'm also realizing that that function blocks loading of the app, especially for non-English users since those translations are loaded after the plugin ones

**Comment by streamer45** [comment]
> What's the motivation for wanting to load those translations with an async function? Since we're awaiting on them, it ends up being basically synchronous even if it's loading the plugin i18n strings concurrently now.
> 
> I'm also realizing that that function blocks loading of the app, especially for non-English users since those translations are loaded after the plugin ones

The goal here would be to avoid bundling all the translation files in the plugin js but instead have them as separate json assets to be loaded when/if needed. This shouldn't be blocking the app initialization though so there may be more needed here if that's the case. I guess another option would be to expose a function in the window object to let plugins do this asynchronously.

**Comment by hmhealey** [comment]
This action is used on page load, so it unfortunately does block the initialization of the app since we're waiting to get those plugin translations. We could probably make it so that the initial `loadTranslations` action dispatches a followup that adds the plugin translations to those though if you just want them to not block the initialization.

I think a PluginRegistry hook or something similar on the window would get more of what you're looking for, but the plugin itself might still need to be aware of when it might become visible to register those lazily. There's also some far future things we could do with module federation to lazy load them more automatically if we ever get plugins onto that, but that's obviously a longer term task

**Comment by streamer45** [comment]
Thanks Harrison. I'll have another look but also not a huge deal, mostly a nice to have at this point.

**Comment by streamer45** [comment]
Okay had another glance at this. If I understand correctly the reason we'd be blocking the app initialization is because we are waiting to render the `IntlProvider` wrapper until the translations are set. 

https://github.com/mattermost/mattermost-webapp/blob/cba045cae0cbcdd423020fde6715809f85165396/components/intl_provider/intl_provider.tsx#L61-L75

What I am failing to understand still though is how getting them asynchronously is that much different from the current behaviour which is equally blocking. Yes, we may be making a couple of extra HTTP calls in parallel for those plugins supporting this async logic but that's the tradeoff to pay to avoid including them all in the bundle. Also we could probably optimize this a little further by fetching the server translations in the same batch of promises of plugins ones.

Overall it seems cleaner to do it this way vs providing yet another hook but not opposed to that approach either. @hmhealey let me know if I am missing something here.

**Comment by hmhealey** [comment]
Yep, that's where the blocking would happen.

The difference between the two is just those extra HTTP calls which we'd now be blocking on. The difference is likely minimal but it could start to add up, especially if someone misuses that option or if that callback throws an error. If we were to remove the `await` on the plugin translations, it'd fix that issue, although there's a chance it could cause warnings to come from React Intl if it's loaded and used for the plugin before the strings themselves are loaded.

Maybe we can step back and discuss the motivation for this a bit? I do agree with loading the translations asynchronously in principle, but I don't know if the current plugin framework can support that with how it front-loads all of the plugin loading right away. If the goal is to reduce the bundle size, that's definitely something that'd be good to address, but I don't know how much just removing the unused translations would affect that since I'd put more blame in the rest of the plugin system for the bundle size currently

**Comment by streamer45** [comment]
> Maybe we can step back and discuss the motivation for this a bit? I do agree with loading the translations asynchronously in principle, but I don't know if the current plugin framework can support that with how it front-loads all of the plugin loading right away. If the goal is to reduce the bundle size, that's definitely something that'd be good to address, but I don't know how much just removing the unused translations would affect that since I'd put more blame in the rest of the plugin system for the bundle size currently

The motivation here was purely improving the use case I mentioned which was to only load translation files that apply to the user's locale which would mean get a consistent behaviour between webapp and plugins when it comes to fetching such assets. 

I totally agree that there are better ways to lower the overall bundle size but this was purely coincidental as I was currently working on translations for Calls and thought it was a safe enough improvement. But I also understand the hesitation and we can definitely live without this as [other plugins did](https://github.com/mattermost/mattermost-plugin-playbooks/blob/d995a76d67b52e6b1df9c5900092197d823eacf8/webapp/src/index.tsx#L144) so far. 

I'll close this for now and we can revisit in the future if it makes sense to do so.

**Pull request closed without merging**
