### PR TITLE
[MM-42726] : Threads link in channel switcher

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
This will add threads in search results and on a load of the channel switcher

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-42726

#### Related Pull Requests
n/a

#### Screenshots
Screenshot 2022-03-29 at 3 51 21 PM

#### Release Note
```release-note
UI: Threads link in channel switcher
```

### CODE REVIEW

**Review by Willyfrog — COMMENTED** [review]
Shouldn't we have an e2e test to check this behaviour stays consistent in the future?

**Comment by AshishDhama** [comment]
@Willyfrog Yeah, we should let @matthewbirtch go through it once, will add unit test as well e2e.

**Comment by AshishDhama** [comment]
@matthewbirtch Yeah there is a bug, have fixed that will push it in some time.

**Comment by AshishDhama** [comment]
@matthewbirtch Have fixed the issue please check again whenever you can.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Looking good @AshishDhama. I just tested and noticed a few things:

1. When searching, unread channels don't display bold like they do in the default state. I think we should be consistent here
2. When I typed the 't' character, for some reason 'user-1' shows up in the list of results. I have no idea why - there is no 't' in the username. There might be something weird with the logic here.

image

4. When typing 'To' I would expect "Town Square" to be displayed before "Off-Topic" based on relevancy, but "Off-Topic" shows first.

image

5. Can we remove the divider line above the 'recent' title? I don't think it's needed since there is dividing space there and the title

6. We are only displaying Threads in the channel switcher for the current team. Since the channel switcher is now cross-team, I wonder if we need to show threads for any team. This might get a little weird, but it would make logical sense if we're showing channels for all teams here

**Comment by AshishDhama** [comment]
Closing this in favour of https://github.com/mattermost/mattermost-webapp/pull/10013, moving comments there only.

**Pull request closed without merging**
