### PR TITLE
MM-9734 Fix permalink view loading from search results

### PR DESCRIPTION
**Pull request by koxen**
Fixes posts not loading around selected posts due to wrong assumption that ChannelStore.getCurrent() can be used to get channel id for post, before emitPostFocusEvent has finished loading.
It works fine when you boot to a permalink, but doesn't work correctly if you switch channel view to permalink view.
This caused surrounding posts to be requested but with wrong channel id, and empty results were returned.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-9734

### CODE REVIEW

**Comment by koxen** [comment]
@grundleborg

**Comment by grundleborg** [comment]
@koxen thanks very much for the fix! Please could you rebase it onto the `release-4.8` branch so we can merge it into that rather than master?

**Comment by koxen** [comment]
> This branch has no conflicts with the base branch
better now?

**Comment by koxen** [comment]
give me 5 minutes to fix this

**Comment by grundleborg** [comment]
Yeah, that looks great. Jenkins is getting confused though, so I'll try and persuade it to actually build it properly.

**Comment by grundleborg** [comment]
Hey @koxen there's something a bit wrong with this PR - it looks like github isn't serving up the actual commit with the code in properly when cloning this repo. I think Github just screwed up for some reason. Would you be able to rewrite the commits somehow so they have different commit hashes and then open a fresh PR? Hopefully that will unbreak Github and then we can get this tested.

**Comment by grundleborg** [comment]
Thanks very much for the fix @koxen

**Pull request merged**
