### PR TITLE
MM-44986 fix image preview e2e

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
fix image preview e2e

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-44986

#### Related Pull Requests
NA

#### Screenshots
NA

#### Release Note
```release-note
* fix image preview e2e
```

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]

**Comment by saturninoabril** [comment]
Thanks @AshishDhama! Could you please fix similar item at ``messaging/long_post_attachments_spec.js``?

**Comment by AshishDhama** [comment]
Got fixed in https://github.com/mattermost/mattermost-webapp/pull/10735

**Pull request closed without merging**
