### PR TITLE
Remove animation effect on channel buttons

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
After letting it soak for a while, the consensus is that the animation on the channel buttons in the LHS feel more like lag than helpful UX so this PR removes the effect.

#### Ticket Link
Related to: https://mattermost.atlassian.net/browse/MM-18370

### CODE REVIEW

**Comment by andrewbrown00** [comment]
@deanwhillier do we have a test server for this?

**Comment by deanwhillier** [comment]
@andrewbrown00, yes, there are details just above your comment for a Spinwick. Was probably still starting up when you initially looked! 🙂

Might want to wait for the updated version as I also removed the animation from the post backgrounds per @esethna's request.

**Comment by andrewbrown00** [comment]
@deanwhillier yup, I see it now. I'll wait a bit next time 😄

**Comment by stevemudie** [comment]
QA will test once changes are merged.

**Pull request merged**
