### PR TITLE
MM-50726 Align subscribeCloudSubscription type with the standard ActionResult type

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Align `subscribeCloudSubscription` type with the standard ActionResult type

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50726

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by ConorMacpherson — APPROVED** [review]
Wonderful changes! :)

**Review by nickmisasi — APPROVED** [review]
| |

**Comment by neallred** [comment]
Looks like CWS linked spinwicks still aren't working, might be better to test this post-merge.

**Review by yasserfaraazkhan — APPROVED** [review]
will test it post merge.

**Pull request merged**
