### PR TITLE
Remove old post components code and update tests

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Part of https://mattermost.atlassian.net/browse/MM-43162 is to remove unused old components code, adjust styles, fix unit tests, e2e tests. This PR will handle this

[x] - Removed old post components
[x] - Updated unit tests and snapshots

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43162

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/11127

#### Release Note

```release-note
Removed all post components in favour of a unified approach
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
:tada:

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
I saw 95% pass and pulled latest fixes from master,
if conflicts are too many, you can do `git revert 7f98c00`

**Pull request merged**
