### PR TITLE
MM-23209 Fix for clicking on new messages toast before redirect when in permalink view acts funky

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
We need to cancel on timeout for any changes to url not just on unMount of component.
The bug happens because when entering a permalink there is a timeout to change the url from permalink to channel after 6 sec. If user clicks on the toast before this then the url changes to take user to latest set of posts and later the timeout kicks in causing it to act funky.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23209

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thanks @sudheerDev 
- It looks good, user is redirected to the bottom of the channel without any unusual refreshing or glitching after doing the following:(copying steps from other PR)

1. Visit a channel
2. Mark few posts in channel as unread by scrolling up a bit
3. Scroll a bit more and load more posts.
4. Click on a post timestamp to load the permalink view
5. Click on the unread toast before post highlight fades (within 6 sec)

On a side note @sudheerDev should I be seeing history toast on this server too?

**Comment by sudheerDev** [comment]
> should I be seeing history toast on this server too?

@jgilliam17? I didn't get that. You should be seeing if you are not the at latest set of posts or if you have 1000px equivalent of posts from the permalink post to the bottom of the channel

**Comment by jgilliam17** [comment]
> > should I be seeing history toast on this server too?
> 
> @jgilliam17? I didn't get that. You should be seeing if you are not the at latest set of posts or if you have 1000px equivalent of posts from the permalink post to the bottom of the channel

Unfortunately, I am not seeing the history toast while doing this:
1.  Scroll up quite a bit (about 100 posts in my case), ensure this channel is read
2. Copy link and paste in a different channel
3. Click on the link 
- Expected: Redirected to channel, post highlighted, gray history toast on top since there are about 100 more recent posts below
Actual: Redirected to channel and post highlighted, but no history toast

**Comment by sudheerDev** [comment]
@jgilliam17 Sorry about that. Merging master now and It should fix that. Master has a fix that is needed for what you are testing. If you paste the link in url it works for toast and that is how i was testing.

**Comment by jgilliam17** [comment]
> @jgilliam17 Sorry about that. Merging master now and It should fix that. Master has a fix that is needed for what you are testing. If you paste the link in url it works for toast and that is how i was testing.

Great! Thanks Sudheer I was loosing my battle with the `toasts` today 😄

**Pull request merged**
