### PR TITLE
MM-26609 Create a new single entry point to get help, with a new "Ask  Mattermost Community" menu item

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
* Add new entry point for help in channel header
* Add new icon for user guide help
* Add e2e tests for click and checking hrefs

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-26609

#### Screenshots
Untitled

### CODE REVIEW

**Comment by sudheerDev** [comment]
FYI, I think the dropdown is a bit below when compared to the figma. it is mainly because of how the styling of icons in header are. I am using dropdown instead of popover because we have certain API for using things like external links in the component

**Comment by jasonblais** [comment]
@sudheerDev Thank you! I'll defer to Mike on UX/styling, but below are a few things I noticed:

1 - The left edge of the search bar is no longer aligned with the RHS. We may need to reduce the width of the search bar when it's activated.

image

2 - Help icon is missing in tablet view when RHS is open
image

3 - " I am using dropdown instead of popover because we have certain API for using things like external links in the component"

So we're unable to use the same component as the one for "Channel Members" or "Plugins"

image

4 - "Keyboard Shortcuts" should be "Keyboard shortcuts"
image

5 - "Help" tooltip doesn't disappear once clicked
image

**Comment by jasonblais** [comment]
@sudheerDev Thank you! Functionally looking good, will defer UX/UI styling to the design team.

One minor thing: in tablet view, the search bar isn't still quite aligned with the RHS
image

**Comment by sudheerDev** [comment]
@jasonblais I was gonna ping you for review about the above items luckily you already did. Thanks for the review 👍 .  

About tablet view alignment are you sure it changed?
On daily:
Untitled

WIh the PR:
Untitled 2

**Comment by jasonblais** [comment]
@sudheerDev You're right, it reproduces on master. I created a separate ticket, since it's not caused by changes in this PR: https://mattermost.atlassian.net/browse/MM-26697

**Comment by esethna** [comment]
Switching this to @michaelgamble for UX review. 

Looks good to me other than the alignment of the ? icon in the hover effect box:
image

**Comment by sudheerDev** [comment]
@esethna Updated the placement. I will wait for @andrewbrown00 feedback for further changes

Untitled

**Comment by sudheerDev** [comment]
@calebroseland @deanwhillier ping. It will be easy if this gets in soon. because couple off other PR's will be dependent on this

**Pull request merged**
