### PR TITLE
MM-49088: fixes file uploading state

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

File uploading should not update the draft in a debounced fashion. It should update immediately and should not be interrupted by message changes.

This commit was authored to fix a bug where file uploads appear as processing for ever if a user starts typing while the upload is in processing state.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49088

#### Release Note

```release-note
Fixed a bug where file uploading would appear "stuck" in processing state.
```

### CODE REVIEW

**Review by mylonsuren — APPROVED** [review]

**Comment by koox00** [comment]
> Does this also need to be changed for the `AdvancedCreateComment` as well?

oh forgot about that... thanks @hmhealey.

> One of these days, we really need to get the draft handling done in a different way so that the component isn't in charge of all of the debouncing and such

Yes I agree although I cannot think of a great improvement.
Maybe using hooks to so that we reuse most functionality between post and comment.

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
I'll re-run e2es after update. Last cycle failed to start.

**Comment by jgilliam17** [comment]
@koox00 is this PR also fixing this https://mattermost.atlassian.net/browse/MM-49621

**Comment by koox00** [comment]
> @koox00 is this PR also fixing this https://mattermost.atlassian.net/browse/MM-49621

@jgilliam17 no that issue still stands

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Tested, looks good to merge.
Verified, file upload while user types - works as expected.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/298988-ece4365-onprem-ent-webapp-pr-12107-mm-ee-test:ece4365/mochawesome.html) - no PR related failures.

**Pull request merged**
