### PR TITLE
[MM-47168] removing redundant test file 

### PR DESCRIPTION
**Pull request by salmanmanekia**
#### Summary
The UI has changed and we do not have these banners for trial anymore

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47168

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by yasserfaraazkhan — APPROVED** [review]
Thank you @salmanmanekia . These tests are not valid , right ?

**Comment by salmanmanekia** [comment]
> Thank you @salmanmanekia . These tests are not valid , right ?

@yasserfaraazkhan yes, thats right. The UI has changed and at some later point of time we will write new test cases for the up-to-date UI.

**Comment by yasserfaraazkhan** [comment]
> > Thank you @salmanmanekia . These tests are not valid , right ?
> 
> @yasserfaraazkhan yes, thats right. The UI has changed and at some later point of time we will write new test cases for the up-to-date UI.

Got it @salmanmanekia, I'll archive the tests in zephyr too

**Review by pvev — APPROVED** [review]
LGTM! thanks @salmanmanekia :ship:

**Pull request merged**
