### PR TITLE
MM-12795: Remove "@" for full name display in push notifications

### PR DESCRIPTION
**Pull request by patniharshit**
#### Summary
Remove "@" for full name display in push notifications

Some random screenshots showing that it works as expected:
private
direct
username
town

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/9807

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [x] Has UI changes

### CODE REVIEW

**Comment by patniharshit** [comment]
@esethna  @amyblais just a friendly ping in case you haven't noticed :)

**Comment by esethna** [comment]
Thanks @patniharshit! Firing up a test server for review

**Comment by patniharshit** [comment]
@esethna thank you for catching that. I have now removed the '@' when either nickname or full name is set to display. Kindly check again.

**Comment by patniharshit** [comment]
For the mobile part, I was looking in this file 
https://github.com/mattermost/mattermost-mobile/blob/f48cad8e64da498120d366441f65cbc6fbddbd08/app/screens/notification/notification.js#L164,
but wasn't able to find out just by inspecting the code that where the '@' is being prepended to names.

I will try to compile the mobile code and print some intermediate variables in that file to find where @ is being prepended.

Or am I looking in the wrong place?

**Comment by hanzei** [comment]
@enahum Can you help with @patniharshit question?

**Comment by enahum** [comment]
@patniharshit the code for the push notifications is server side. https://github.com/mattermost/mattermost-server/blob/master/app/notification_push.go#L149

**Comment by cpanato** [comment]
`Setup Test Server` label detected. Spinmint test server created if build succeeds (checks pass and no conflicts with base branch).

**Comment by cpanato** [comment]
Spintmint test server creation failed. See the logs for more information.

**Comment by esethna** [comment]
Hi @patniharshit, let us know if you have any more questions on this?

**Comment by hanzei** [comment]
Hi @patniharshit,

Do you have questions about the above feedback? Can we help with anything?

Please note that we will close this PR after another 30 days of inactivity. If you don't object, contributors might complete this PR for you.

**Comment by patniharshit** [comment]
@hanzei @esethna I am extremely sorry for not being able to come back to it. It is difficult for me to complete it anytime soon. Please do the needful to bring it to completion.

**Comment by hanzei** [comment]
Hey @patniharshit,

Thank you for the heads up. Don't worry about not completing this PR. This happens. :wink: 

I will close this PR, because there are also changes on the server side needed and a new PR will be needed anyway.

**Pull request closed without merging**
