### PR TITLE
[MM-28208] Styling for new tooltips used by Cloud Billing

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Added new styling for tool-tips used by Cloud Billing.
Styling is based on the `react-bootstrap` `Tooltip` component which we already make liberal use of.

NOTE: Shouldn't need to review the HTML here, just the CSS.

Demo in the System Console > Billing and Account > Subscriptions section.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28208

### CODE REVIEW

**Review by jwilander — APPROVED** [review]

**Review by nickmisasi — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
LGTM

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@devinbinnie nice job. It looks great, except it appears to be missing the shadow



Should be able to use `box-shadow: 0px 12px 32px rgba(0, 0, 0, 0.12);`

So it should look like this:
Frame 135

**Comment by matthewbirtch** [comment]
Looks like the test server failed @devinbinnie. I don't see this in the Billing and Account section in the link above

**Comment by devinbinnie** [comment]
@matthewbirtch Yeah I had a merge conflict from merging the Alert Banners, server should update shortly :)

**Review by matthewbirtch — APPROVED** [review]
Looks good to go!

**Pull request merged**
