### PR TITLE
Fix incorrect translation id

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary
Fix incorrect translation id (produced by [this commit](https://github.com/mattermost/mattermost-webapp/commit/2b85ae63e9c644c10f6eedbd153f2b252251a64d))

#### Ticket Link
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [ ] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
@kaakaa Looks like the build isn't passing, can you help take a look? 

Big thanks for noticing and fixing it :)

**Comment by kaakaa** [comment]
@jasonblais Thank you for letting me know it!
But I don't know why this error happens, since `Details` page returns 404 Not Found.
Do you know something about it?

**Comment by jasonblais** [comment]
I'm not sure - @enahum or @jwilander might know better

**Comment by kaakaa** [comment]
@jasonblais Now, the build looks fine at all... I'm doing nothing `¯\_(ツ)_/¯`

**Comment by cpanato** [comment]
@kaakaa can you please rebase?

**Comment by kaakaa** [comment]
@cpanato Rebased 👍

**Pull request merged**
