### PR TITLE
ApplyTheme Updates – convert older changeCSS JS to CSS variables part 2

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
This PR is based off of #8399 and continues the process of converting from `changeCSS()` JS theming to CSS properties (variables). This PR only deals with the `centerChannelBg` colour. 

Specific commits with descriptions indicating what each commit affects are as follows:
- https://github.com/mattermost/mattermost-webapp/commit/19faee0dc1398791216679c6466c875ee092a20f
- https://github.com/mattermost/mattermost-webapp/commit/16a1c96f85ff29e416eec7a1741c5cefebcca70b
- https://github.com/mattermost/mattermost-webapp/commit/7ec10236e2837f72902fbfd285e95dad4e1f66c6
- https://github.com/mattermost/mattermost-webapp/commit/6cd1eb4384ebbf95dfd24e356ec4c399b06a5da4
- https://github.com/mattermost/mattermost-webapp/commit/9e1ce2b5b132d8ffed08349bff14cc8277710d6e
- https://github.com/mattermost/mattermost-webapp/commit/98836b8463fa2fa38ab333e23ab6294c0ebac5b9

#### Related Pull Requests
- This PR follows after #8399, but is reconstructed based off of the master branch

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by deanwhillier** [comment]
🙄

**Review by michaelgamble — DISMISSED** [review]
I only noticed one problem:
- channel header file button icon seems to have disappeared.

**Comment by deanwhillier** [comment]
@michaelgamble, as discussed, the file icon issue has been dealt with in [this PR](https://github.com/mattermost/mattermost-webapp/pull/8565). :)

**Review by hmhealey — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier and I apologize about delay
Tested, looks good to merge.
- Verified the list of changes as listed in description.

**Comment by amyblais** [comment]
@deanwhillier Is this for v6.0 or v6.1?

**Comment by deanwhillier** [comment]
@amyblais, it's not really related to either specifically but is rather another step in slowly dealing with some tech debt around theming that needs to get done ideally before a larger layout overhaul coming up. I'd say it can go in whatever version makes sense and that has minimal impact to timing and QA.

**Pull request merged**
