### PR TITLE
MM-41273 : Restore main menu items added by plugins

### PR DESCRIPTION
**Pull request by ThiefMaster**
#### Summary
Render main menu items added by plugins.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41273

#### Release Note

```release-note
Restored rendering of main menu items from plugins in non-mobile view
```

#### Screenshot

image

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
LGTM, do you mind posting a screenshot for @matthewbirtch to review? Also heads up that it looks like an existing test is failing now

**Comment by M-ZubairAhmed** [comment]
@ThiefMaster thank you doing this :)
Do you mind adding the demo plugin in the cloud instance which will be generated shortly, please login via the sysadmin user

**Comment by ThiefMaster** [comment]
Since plugin upload is disabled on that instance I can't do that. Anyway, I think if someone does have the ability to upload a plugin there, taking the demo one from https://github.com/mattermost/mattermost-plugin-demo/releases/tag/v0.9.0 should do the job..

**Comment by M-ZubairAhmed** [comment]
@mickmister gentle ping

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@M-ZubairAhmed @mickmister how can I test this so I can see it?

**Comment by mickmister** [comment]
@matthewbirtch I've DM'd you a link to a cloud server running this PR's code and the demo plugin.

**Review by matthewbirtch — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@DHaussermann gentle ping on this pr

**Comment by jgilliam17** [comment]
@mickmister is the cloud server running this PR's code still available for testing?

**Comment by jgilliam17** [comment]
@ThiefMaster thank you for your contribution 
Some check are failing, can you please fix so I can trigger e2es? 🙂

**Comment by ThiefMaster** [comment]
There we go... pretty sure this test didn't fail at the very beginning though?

**Review by jgilliam17 — APPROVED** [review]
Thanks @ThiefMaster 
Tested, looks good to merge.
- Verified team menu dropdown contains plugin entries.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/173904-5c79700-onprem-ent-webapp-pr-9845-mattermost/mm-ee-test5c79700/mochawesome.html) looks good, no PR related failures

**Pull request merged**
