### PR TITLE
Adding new container for permalinks

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Adding new container component that can be used by permalinks, links, focalboard. I decided to build this off the existing container and made some slight adjustments. It's flexible as it allows you to make your own adjustments with the `className` prop.

#### Ticket Link
Ticket: https://mattermost.atlassian.net/browse/MM-36383
Discussion: https://community.mattermost.com/core/pl/oz9muyuibtf8jqje8dtn6gptkw

#### Screenshots
Screen Shot 2021-06-11 at 9 06 54 AM
Hover (slight change in shadow):
Screen Shot 2021-06-11 at 9 07 38 AM

#### Release Note
```release-note
Adding new container for permalinks and links
```

### CODE REVIEW

**Comment by BenCookie95** [comment]
Moving back to in progress, after discussions with Michael the card needs to be clickable. I need to figure out how to stop event propagation from children components such as external links and images

**Comment by BenCookie95** [comment]
Removed work in progress label, I have fixed the event propagation

**Review by sbishel — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Comment by esethna** [comment]
@BenCookie95 can we get an updated test server (with server changes) for UX to take another pass at it and approve?

**Comment by jgilliam17** [comment]
Thanks @BenCookie95 
I am not seeing the changes on the test server. Maybe I'm missing something, is there a setting I need to toggle on?

**Comment by furqanmlk** [comment]
@jgilliam17 
I will take care of this PR. We might need other PRs as well.

**Comment by esethna** [comment]
Unblocking on UX as Mike gave it a review earlier and those things were addressed https://github.com/mattermost/mattermost-server/pull/17796#pullrequestreview-708612315

**Comment by esethna** [comment]
Unblocking on UX as Mike gave it a review earlier and those things were addressed https://github.com/mattermost/mattermost-server/pull/17796#pullrequestreview-708612315

**Review by furqanmlk — APPROVED** [review]
Updated tests details in other PR
mattermost/mattermost-server#17796

**Comment by esethna** [comment]
@BenCookie95 please go ahead and merge if reviews are complete :)

**Comment by esethna** [comment]
@mkraft once this is merged (I think it's the last remaining PR?), can you help get the autolinker disabled on community-daily so we can use it as a test environment?

**Comment by BenCookie95** [comment]
> @mkraft once this is merged (I think it's the last remaining PR?), can you help get the autolinker disabled on community-daily so we can use it as a test environment?

I actually don't think this is needed anymore. I'll close it

**Pull request closed without merging**
