### PR TITLE
[MM-22147] Fix code block copying line numbers

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR will fix line number copying in the code block.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-22147

### CODE REVIEW

**Comment by saturninoabril** [comment]
Is this for v5.20? I can see the Jira ticket is not assigned to that milestone.  Please help verify, thanks

**Comment by hmhealey** [comment]
Leaving this for @iomodo to merge since it's unclear what release this should be merged into.

**Pull request merged**
