### PR TITLE
[MM-27274] Restrict convert to private to create private channels permission

### PR DESCRIPTION
**Pull request by fmunshi**
#### Summary
- Currently any team admin can convert a public channel to a private channel, this allows a team admin to create a public channel and then convert it to a private channel essentially sidestepping the permission

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-27274

#### Related Pull Requests
- https://github.com/mattermost/mattermost-server/pull/15243

### CODE REVIEW

**Comment by amyblais** [comment]
@jespino Kind reminder to review for v5.27,

**Comment by jespino** [comment]
@amyblais the code looks good to me, but I have concerns about the underneath reasoning, I asked @thefactremains about it. Going forward with this approach can end up in a hard to revert decision.

**Review by srkgupta — APPROVED** [review]
Tested on the PR and the issue is fixed now and is working fine. The option to convert a public channel to private is not provided if the user does not has permission. Even the API returns a permission denied error.

**Comment by thefactremains** [comment]
> @amyblais the code looks good to me, but I have concerns about the underneath reasoning, I asked @thefactremains about it. Going forward with this approach can end up in a hard to revert decision.

@jespino can you please describe your concerns again? It is my understanding that our current approach would not be hard to revert or iterate on. Another approach @fmunshi and I discussed was creating a new permission for "convert public to private channel".

**Comment by amyblais** [comment]
@thefactremains I think the concerns are listed here https://github.com/mattermost/mattermost-server/pull/15243#issuecomment-675386896.

**Comment by fmunshi** [comment]
Will open a new PR as the new solution is a different story

**Pull request closed without merging**
