### PR TITLE
[MM-16057] Fixed a screen reader issue on multiselect when no items are found

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
There was an issue with MM-16057 where the screen reader would not read the 'No items found' prompt on `multiselect` components after more than one character was typed resulting in 0 results. This fixes that issue by forcing the reader to read that prompt after every character is typed (but won't read while typing)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16057

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @devinbinnie 

1. I've tested the fix for this PR and on the first attempt, inserting a user that does not exist, the reader reads out "No items found".

2. However, I cannot backspace to remove the search and search for another user. The left and right arrows work in the field and I can then hit the "Delete" key to delete the text.

image

3. The reader highlight is also not highlighting the entire input field?

image

4. Also, if I delete the text from the "Search and add members" box and try to search for another user (whether they exist or not), the reader does not read this out.

5. Is the reader supposed to read out the user if they do exist/are found? This is not happening.

image

**Comment by lindy65** [comment]
Hi @devinbinnie - is this ready to retest?

I see 1) is still working as expected

However 2) is still not fixed - I cannot backspace to delete the text I typed into the "Search and add users" field.  Home/End and left/right arrows do not work in that field either.  I cannot highlight the text to remove it with the DEL key either.

3) might have been caused by the "use virtual PC cursor" which was on when I was testing the first time. I have disabled this now and there is no weird highlighting in the field

4) (although I cannot delete text in this field now) and 5) still need resolution as I'm not seeing them fixed (if they are indeed expected?)

**Comment by devinbinnie** [comment]
Hey @lindy65,

My apologies for the confusion, I will address each of your points below:

2) What browser/OS are you using? I haven't had any trouble backspacing using this PR. Can anyone else confirm this issue?

3) This was an issue with the way the multi-select control was designed. I've added a fix now so it should be working properly.

5) So JAWS and Chrome (not sure what browser you're testing with) doesn't consistently read the selected user when the user is typed quickly (or at a normal speed). I've created a bug to address this as a separate issue (link here: https://mattermost.atlassian.net/browse/MM-17284) and I think we're comfortable shipping this as a known issue. This should be working correctly with JAWS in Firefox. Let me know if there are other cases that are not working correctly for you.

At this point feel free to re-test and let me know your findings. Thanks again!

**Comment by lindy65** [comment]
Hey @devinbinnie 

Thanks! I will re-test again in a little while - just got a slew of meetings :/

I'm testing on Win/Chrome and Win/Desktop App

Will post back here soonest once tested!

**Comment by lindy65** [comment]
Thanks @devinbinnie 

I've re-tested and am still having the same issues as in my previous comment - I am not able to backspace or use any navigation keys including DEL key in the "Search and add members" input box.

I'm not sure if this is an issue with the way I am using Jaws (the only change I have made is switching the 'virtual PC cursor' off.

Is it possible for you or @esethna to test on the spinwick to see whether you find the same issues?

**Comment by srkgupta** [comment]
I tried the same steps as Lindy had mentioned and even I am facing the same issue.

**Comment by esethna** [comment]
I am not able to reproduce the backspace issue (Win10/DEkstop)

**Comment by devinbinnie** [comment]
Good news everyone! I've apparently fixed the backspace issue, it was working on my Windows 10 17134 machine. Let me know if you can still reproduce it...

**Comment by jwilander** [comment]
FYI cloud team is looking at why the spinwick server didn't delete properly

**Pull request merged**
