### PR TITLE
custom URL scheme upper case letters not working

### PR DESCRIPTION
**Pull request by Hobby-Student**
#### Summary
1. System Console > Customization > Posts 
2. In `Custom URL Schemes` field enter a value like "file, DMS, dms"

I did so and the upper case one is not working. We have a software which is exporting links as
```
DMS:<GUID>
```
inserting this link into a message is not working. Manually replace _DMS_ to
```
dms:<GUID>
```
is working as a clickable link.
I don't know if this is the only place, but I didn't find any other... If this is only rendered on client side, the windows desktop is also affected (have not tested other apps).

Webapp -> uppercase not working
windows desktop app -> uppercase not working
Android App -> uppercase partially working (_DMS_ does, _HTTP_ does not)

image
image

#### Ticket Link
none

#### Checklist
- [x] just a little regex

### CODE REVIEW

**Comment by jasonblais** [comment]
Definitely not a problem! Let us know if you have any questions along the way :)

**Comment by hanzei** [comment]
Hey @Hobby-Student,

The Spinmint test server is used to test a PR. For developing a feature please use a local dev environment. You can find an instruction for this on https://developers.mattermost.com/contribute/webapp/developer-setup/. If you have problems feel free as them on the [Mattermost Community Server](https://community.mattermost.com).

**Comment by Hobby-Student** [comment]
@hanzei 

did read the dev instructions. will try to get a dev machine asap.

**Comment by hanzei** [comment]
Hey @Hobby-Student,

Did you manage to set up a dev environment? Is there anything I can help you with?

**Comment by Hobby-Student** [comment]
> Did you manage to set up a dev environment?

I'm currently waiting for some RAM. Should arrive the day after tomorrow.
Setting up the dev machine itself seems to be easy.

**Comment by hmhealey** [comment]
> 2. In `Custom URL Schemes` field enter a value like "file, DMS, dms"

Instead of having the admin specify an uppercase custom URL scheme, would it make sense to make all of the custom URL schemes case-insensitive?

**Comment by Hobby-Student** [comment]
> Instead of having the admin specify an uppercase custom URL scheme, would it make sense to make all of the custom URL schemes case-insensitive?

exactly what I'm trying to do. If you could point me to the right direction, where custom schemes are parsed...?

Android app seems to work case insensitive.

**Comment by hmhealey** [comment]
I think [this line](https://github.com/mattermost/mattermost-webapp/blob/4bd90bfe538179fc5490e53b8cce483f139864ee/utils/markdown/renderer.jsx#L154) is the one that needs to be changed since it currently looks for the exact string in the array. Using a `.findIndex` would let you do a case insensitive comparison instead.

**Comment by jasonblais** [comment]
Hey @Hobby-Student - let us know, if we can help or have any questions on the latest note from @hmhealey :)

**Comment by Hobby-Student** [comment]
@jasonblais you could buy me some free time ;)

dev machine is currently setting up. hope to get my hands on the code this weekend

**Comment by Hobby-Student** [comment]
I think I got it. it now recognizes lower and upper case letter before ":" and then checks the message with "toLowerCase()" against the default and custom schemes.

- check url also with upper case protocol (href is converted to lower case)
- check scheme in lower case against list of schemes (default and custom) <- without this, default schemes are only recognized as is, e. g. HTTP won't be recognized
image
image



the only thing it needs, is to also edit _marked.js_. Without this, the message will only be checked against lower case protocols.
image

**should I make a pull request for mattermost/marked?**

**Comment by jasonblais** [comment]
Great work @Hobby-Student!! :tada:

@hmhealey will have insight on potential changes for mattermost/marked.

**Comment by hmhealey** [comment]
Yes, please submit a PR against https://github.com/mattermost/marked for that, and when you do, can you link the PR back here so we definitely see it? It's easy for us to miss PRs against forked libraries somestimes.

After that's merged, this PR can be updated to point to the new version of marked

**Comment by Hobby-Student** [comment]
> please submit a PR

done

**Comment by hmhealey** [comment]
FYI, this will conflict with https://github.com/mattermost/mattermost-webapp/pull/2516 depending on which gets merged first. The commit hash in this PR is the newer one

**Comment by Hobby-Student** [comment]
tested. results:
image
image
URL with title is working as expected. URL with quotes is working in lowercase only.


it seems, that there are some more changes needed to get it work in all circumstances...

**Comment by jasonblais** [comment]
Thank you @Hobby-Student! 

@hmhealey apart from what's shown in the screenshot above, any additional tests that we should do? If so, I can ask our QA, but in general it appears to work as expected.

**Comment by hmhealey** [comment]
I don't think there's anything specific to test. These changes are mostly around making it so that the URL scheme can contain uppercase letters

**Comment by jasonblais** [comment]
Sounds good.

Thanks @Hobby-Student for this! I requested a second dev review and then this should be ready to merge :)

**Comment by Hobby-Student** [comment]
> Please rebase and fix conflicts so we can merge it.
done.

Glad that I was able help 😃

**Comment by hanzei** [comment]
Thank you for the contribution @Hobby-Student 👍

**Pull request merged**
