### PR TITLE
MM-T2503 Boolean value check

### PR DESCRIPTION
**Pull request by simcard0000**
#### Summary
This test completes the steps outlined in https://github.com/mattermost/mattermost-server/issues/18176, except for checking in the iOS and Android apps.

@saturninoabril _How do I go about writing a test for the iOS/Android apps (for example, do I need to add them to the webapp repository)?_

#### Ticket Link
Web-app E2E test with Cypress for: https://github.com/mattermost/mattermost-server/issues/18176

#### Related Pull Requests
N/A as of now.

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by furqanmlk — APPROVED** [review]
Thanks @simcard0000

**Comment by saturninoabril** [comment]
Thanks Sim and sorry for the delay. I just got back for reviewing PRs. I'll take a look.

**Comment by saturninoabril** [comment]
> How do I go about writing a test for the iOS/Android apps (for example, do I need to add them to the webapp repository)?

That will be at https://github.com/mattermost/mattermost-mobile/tree/main/detox. The HW https://github.com/mattermost/mattermost-server/issues/18176 is for the webapp only. Mobile/Detox will have its own separate campaign.

Thanks Sim!

**Pull request merged**
