### PR TITLE
MM-47044 Wrap Pluggable component in an error boundary

### PR DESCRIPTION
**Pull request by hmhealey**
While we can't guarantee plugins won't crash, we can at least guarantee that they won't crash the whole web app by using error boundaries. An error boundary stops a React error from crashing the web app with the sort of crash that makes the whole page go blank. Since we use this `Pluggable` component to wrap everywhere that a plugin injects content into the web app, this'll protect most of the app from errors.

Some of these examples are faked, but the one with clicking "unfollow run" is a real one.

https://user-images.githubusercontent.com/3277310/190820848-42c8dbdf-38fe-4374-b1e8-ffb24691dab8.mp4
https://user-images.githubusercontent.com/3277310/190820883-a834e9ab-4cc1-48f2-8f7f-d8903daf6add.mp4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47044

#### Release Note
```release-note
Prevent plugin components from crashing the entire web app
```

### CODE REVIEW

**Comment by hmhealey** [comment]
For this, I went with a simple design that should hopefully fit everywhere we need it, although it might get a bit squished in some places like menus and such. We can probably come up with a nicer design later.

**Review by mickmister — APPROVED** [review]
Awesome work on this @hmhealey :+1: I really like the UX of being able to refresh the component after an error occurs.

I've confirmed this PR fixes the crash for all currently known affected plugins, except for the custom attributes plugin. In the case of this plugin, the crash is occurring in a custom admin console setting. This component doesn't use the `Pluggable` component, so the fix in this PR doesn't fix the crash for the admin console custom settings. I've raised https://github.com/mattermost/mattermost-webapp/pull/11149 to cover instances of plugins rendering components outside of the `Pluggable` component.

**Comment by mickmister** [comment]
I'm thinking we should also log this error as in the Developer Mode error banner, so it is easier to find when these sort of errors occur.

**Comment by hmhealey** [comment]
If I remember right, the error is still logged even with the error boundary in place. At the very least, the error bar still triggers, so I assume it's logged.

That's just not visible in the first example because the error bar only exists in Channels for whatever reason.

**Comment by hmhealey** [comment]
@jgilliam17 For testing, you can try uploading a version of a plugin like the TODO plugin that errors out with React 17. It might not look great depending on which component errors out, but I'm focusing specifically on not crashing the whole web app here

/e2e-test

**Comment by DHaussermann** [comment]
@hmhealey the spin-up ☝️ is setup too restrictive and will only tale pre-packaged but, I did test this PR with GitHub and was able to observe the behavior. 

When the react select happens, the modals closes out and does not re-open afterwards. As I understand it - this is the desired behavior. 
It's a bit confusing as it never tries to open the modal again or show any reason in the dev console why it's not opening afterwards. Should I start working normally once it's using react packaged with the webapp without the user needing to do a refresh or anything? 
Is this PR still needed if we're reverting the react version?

**Comment by hmhealey** [comment]
> When the react select happens, the modals closes out and does not re-open afterwards. As I understand it - this is the desired behavior. This does side step the webapp crash.
It's a bit confusing as it never tries to open the modal again or show any reason in the dev console why it's not opening afterwards. Should I start working normally once it's using react packaged with the webapp without the user needing to do a refresh or anything?

Hmm, that might be something else we can improve on. I'm not familiar with how the TODO plugin does its modal though. Is there a ticket for that issue that I could look at? I'm not familiar with the error case that it hits

> Is this PR still needed if we're reverting the react version?

Yeah, it's still something we'd want. Currently, any plugin could just crash the app if it causes an error in React code. This is actually a pattern we'd like to follow throughout the web app code base as well since it makes the app a bit more resilient to errors.

**Comment by DHaussermann** [comment]
@mickmister as per out discussion - When I set this up on local development server I **can** now see the JS error banner pop up when the errors occur.

@hmhealey after a discussion with Michael, this is good to merge 👍

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey and @DHaussermann for testing this
Looks good to merge.
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/246702-2b8baa7-onprem-ent-webapp-pr-11148-mm-ee-test:2b8baa7/mochawesome.html)- No PR related failures.

**Pull request merged**
