### PR TITLE
Track the nickname when needed, not the username

### PR DESCRIPTION
**Pull request by evelikov**
#### Summary
The wrong event is tracked during submitNickname. A trivial username -> nickname typo

#### Ticket Link
N/A

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by grundleborg** [comment]
Hi @evelikov - thanks very much for doing this PR - looks like it's all good except for one thing: it needs a rebase onto the current `master` branch. Then we are ready to merge it. Would you be able to rebase and force push it (or merge master into your PR branch and push it if you prefer), and then we once the CI server has run the tests we can get it merged.

**Comment by evelikov** [comment]
Is github broken wrt merge requests or it's more of a policy to always rebase?
Either way rebased and force-pushed - thanks for the tip @grundleborg.

**Comment by grundleborg** [comment]
@evelikov it's our policy - we used to have issues with PRs that had been hanging around for a while breaking master when they broke with respect to other changes in the interim. So now we have a policy, enforced by a bot, that a PR can only be merged if it branches within `n` commits from the head.

Anyway, thanks very much for doing that, and for the contribution. I'll merge it right now :)

**Comment by evelikov** [comment]
@grundleborg makes sense. Thanks for the help.

**Pull request merged**
