### PR TITLE
MM-9766 Export text formatting as 'post-utils' for use in plugins

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
I'm selectively exporting these two functions as they'll allow plugins to format text, emojis, markdown, etc. just like we do in the web app.

To use these in a plugin:

```javascript
const React = window.react;
const PostUtils = window['post-utils']; // import the post utilities
import PropTypes from 'prop-types';
import {makeStyleFromTheme} from 'mattermost-redux/utils/theme_utils';

export default class PostTypeFormatted extends React.PureComponent {

    // ...

    render() {
        const style = getStyle(this.props.theme);
        const post = this.props.post;

        const formattedText = PostUtils.formatText(post.message); // format the text

        return (
            <div
                style={{...style.container}}
            >
                {'Formatted text: '}
                {PostUtils.messageHtmlToComponent(formattedText)} // convert the html to components
            </div>
        );
    }
}
```

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-9766

### CODE REVIEW

**Comment by hmhealey** [comment]
@jwilander Any thoughts on how this might work when we change around the text formatting code eventually? Do we have a deprecation policy yet for plugin features, or do we not care while plugins are still in beta

**Comment by jwilander** [comment]
While in beta we have a bit more of a freehand but we should do our best to follow the [deprecation policy](https://docs.mattermost.com/process/deprecated-features.html) when making changes to the these functions even while in beta. If we do need to change them, we just need to make sure that we still provide the backwards compatible interface to the plugins even if that's a bit more work

**Comment by hmhealey** [comment]
Sounds good. It wouldn't be too hard to add a 3 step deprecation process in the code like

1. Mark the existing function as deprecated and print a warning when it's first used
2. Remove the existing function's code, but leave the warning
3. Remove it completely

Or something like that

**Comment by jwilander** [comment]
I like it, it would also be useful for mattermost-redux too when we get around to handling deprecations over there better

**Comment by jwilander** [comment]
Made a ticket for it here https://mattermost.atlassian.net/browse/MM-9874

**Pull request merged**
