### PR TITLE
Cypress/E2E: Add @noncloud to support_packet_generation_spec

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Recently there were changes in Packet generation Dialog for Cloud user.

Following two test cases are not valid for cloud anymore

```
'MM-T3849 - Commercial Support Dialog UI - E10/E20 License'
'MM-T3818 - Commercial Support Dialog UI - Links'
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. @furqanmlk I modified the title to be more descriptive.

**Review by prapti — APPROVED** [review]
👍

**Review by saturninoabril — APPROVED** [review]
@furqanmlk Looks good to me! However, I wonder if there's a similar test intended for cloud.

**Comment by saturninoabril** [comment]
@furqanmlk Comment non-blocking so feel free to merge anytime if no other action is required.

**Pull request merged**
