### PR TITLE
[PLT-7814] Upgrade to enzyme-adapter-react-16 and enable unit/components tests at Jenkins build

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
This is the final batch for PLT-7814, resolving existing (and additional) component test failures.

Included in this PR:
(UPDATE) ~~1. Upgrade to `enzyme-adapter-react-16` with the recent upgrade to React 16~~
  ~~- encountered several test suites failures like `Error: Enzyme Internal Error: unknown node with tag 4` due to [issue on Enzyme 3](https://github.com/airbnb/enzyme/issues/1164)~~
  ~~- it turned out that Adapter React 16 does not support new Portal node types. Though we are not using Portals, our dependencies do like the Modal of `react-bootstrap`.~~
  ~~- affected test cases were temporarily ~~disabled~~ removed (instead of making workaround) until this PR https://github.com/airbnb/enzyme/pull/1263 to `enzyme-adapter-react-16` gets merged.~~

2. Add `make test` command
3. Enable unit/components tests at Jenkins build.
4. Add `make test` to PR checklist
5. Add `reducers` and `selectors` folders for test coverage computation
6. (UPDATE) Add `"clearMocks": true` to jest config to automatically clear mock calls and instances between every test.

#### Ticket Link
Jira ticket: [PLT-7814](https://mattermost.atlassian.net/browse/PLT-7814)

(UPDATE): Jira ticket to revert component tests - [PLT-8133](https://mattermost.atlassian.net/browse/PLT-8133)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Added or updated unit tests (required for all new features)
- [x] Touches critical sections of the codebase (Jenkins build, make file)

### CODE REVIEW

**Comment by ccbrown** [comment]
As a general principle, I'm really against commenting out tests since they have a tendency to just sit in the codebase and rot. If you intend to update these, I would recommend deleting them instead and giving yourself a JIRA ticket. That eliminates the possibility that they'll just rot and makes it much more likely that they'll get updated eventually, keeping our code prettier and more navigable in the meantime. It also allows you to better capture the work you have to do when planning or reviewing your sprints. Git was literally made for preserving old versions of our code. We don't need comments for that.

**Comment by saturninoabril** [comment]
I understand. I left it that way since most of those were written by community contributors. But anyway, I'll send update removing those commented lines, and will just put back whenever `enzyme` issue gets resolve.

**Comment by saturninoabril** [comment]
Updated PR and description above, adding Jira ticket assigned to me - https://mattermost.atlassian.net/browse/PLT-8133 - to revert component tests.

**Comment by saturninoabril** [comment]
I forgot this one. I added clearMocks (set to true) to jest config. This is to automatically clear mock calls and instances between every test.

**Comment by saturninoabril** [comment]
I noticed that the awaited PR for `enzyme-adapter-react-16` is now merged and so I upgraded this PR to `enzyme-adapter-react-16@1.1.0`, and then reverted all those previously disabled tests.

**Comment by crspeller** [comment]
@saturninoabril Can you resubmit this as a branch on the mattermost-webapp repository? I have jenkins configured to not trust Jenkinsfile changes that are not from branches on the main repo.

**Comment by saturninoabril** [comment]
@crspeller Noted. Submitted branch - https://github.com/mattermost/mattermost-webapp/pull/310

**Pull request closed without merging**
