### PR TITLE
Use dark semi-transparent border for code blocks for compatibility with dark and light themes

### PR DESCRIPTION
**Pull request by last-partizan**
This pull-request changes border on code blocks to use dark semi-transparent border.

Old was a bit off with dark themes
image

New variant looks good with both light and dark
Screenshot from 2019-09-05 18-57-54
Screenshot from 2019-09-05 18-57-21

Fixes https://github.com/mattermost/mattermost-server/issues/12057

### CODE REVIEW

**Comment by last-partizan** [comment]
@andrewbrown00 will using `border: $border-gray;` achives desired effect? or maybe you have another suggestion? (I don't have dev instance at hand to check it myself, and not yet understand how theming works in this project).

**Comment by andrewbrown00** [comment]
@last-partizan what's the output color `border: $border-gray;`?

**Comment by last-partizan** [comment]
@andrewbrown00 
```
sass/utils/_variables.scss
19:$border-gray: 1px solid #ddd;
```

But in `.sidebar--left`, for example on our production node with Mattermost Dark theme it is replaced by
Screenshot from 2019-09-13 20-11-47

And looks like magick happens in utils/utils.jsx, and i need to add `.post-code code` to
```
utils/utils.jsx
489:        changeCss('.app__body .sidebar--left ......', 'background:' + theme.sidebarBg);

```

**Comment by andrewbrown00** [comment]
@last-partizan looking at this again, I'm not sure we need to make a change. Theming can be tricky, which is why (just guessing) the current **border color** is shared across all themes. Since this isn't a bug, but an improvement, I'm going to pull in another designer @asaadmahmood to have a quick look and provide some feedback here.

**Comment by asaadmahmood** [comment]
@last-partizan using `border: 1px solid v(center-channel-color-20);`, should give you the desired result.

**Comment by last-partizan** [comment]
@asaadmahmood thanks.

@andrewbrown00 I updated PR.

**Comment by andrewbrown00** [comment]
Thanks @last-partizan, will you add a screen shot for both iOS and Android for me to review 😄

**Comment by lindalumitchell** [comment]
@andrewbrown00 could you also help add a JIRA ticket to track this change (if there isn't one already; I didn't see one)?

**Comment by last-partizan** [comment]
@andrewbrown00 unfrtunately i was unable to run webapp yet.

I would be glad if someone with working dev install can test it. Or i will make another attempt later.

**Comment by andrewbrown00** [comment]
> @andrewbrown00 could you also help add a JIRA ticket to track this change (if there isn't one already; I didn't see one)?

@lindalumitchell ticket created in JIRA https://mattermost.atlassian.net/browse/MM-18615

**Comment by andrewbrown00** [comment]
@last-partizan can you spark a server for me to test with, thanks.

**Comment by last-partizan** [comment]
@andrewbrown00 great, thank you for screenshots! i'll sync my branch with master in a minute.

**Comment by last-partizan** [comment]
Do i need to do something to get this merged?

**Comment by jasonblais** [comment]
Hi @last-partizan, sorry for the delay here. Looks like we didn't assign reviewers - I've done this now so we can move forward with the PR review!

**Comment by last-partizan** [comment]
@jasonblais should i sync it with master branch or it is not neccessary?

**Comment by jasonblais** [comment]
@last-partizan Yes, that would actually be helpful, thank you! :+1:

**Comment by hanzei** [comment]
@hmhealey Could you please review this PR when you have the time?

**Comment by last-partizan** [comment]
@hmhealey done!

**Comment by hanzei** [comment]
Thanks for fixing this @last-partizan :+1:

**Comment by last-partizan** [comment]
@hanzei i'm glad to help :)

**Pull request merged**
