### PR TITLE
[MM-23101] - Fix error in RHS posts with emoji

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Fixes the JS error caused by not passing emojiMap to createAriaLabelForPost in rhs_comment.jsx

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23101

Fix versions
v5.22 (April 2020)

### CODE REVIEW

**Comment by amyblais** [comment]
@nevyangelova Has this been cherry-picked?

**Comment by hmhealey** [comment]
The bot missed it for some reason. I asked Nevy about it a bit earlier, and she said she'll be cherry-picking it tomorrow

**Pull request merged**
