### PR TITLE
WIP: [MM-12741] Refactor emoji picker

### PR DESCRIPTION
**Pull request by cometkim**
## Summary

- [ ] Rewrite around of EmojiPicker with TypeScript
- [ ] Rewrite around of EmojiPicker with FC/Hooks
- [ ] Cleanup component tree
- [ ] Virtualize emoji list using react-window
- [ ] Code-split for emoji picker component
- [ ] Fix a bug that moves to wrong emoji position when arrow keys down.
- [ ] Benchmark 

#### Ticket Link

GitHub: https://github.com/mattermost/mattermost-server/issues/10346
Jira: [MM-12741]

#### Related Pull Requests

- Awaited #3866 to use react-intl's hooks API like `useIntl()`.

[MM-12741]: https://mattermost.atlassian.net/browse/MM-12741

### CODE REVIEW

**Comment by jasonblais** [comment]
Hi @cometkim! 👋 Let us know if you have any questions - sounds like this might have been a starter PR for initial review based on a note here? https://github.com/mattermost/mattermost-server/issues/10346#issuecomment-530509871

**Comment by cometkim** [comment]
Hey @jasonblais , currently I'm working on this only weekend. so this would be delayed.

I will make some progress and mention you.

**Comment by jasonblais** [comment]
No worries! Thank you for the heads up 👍

**Comment by cometkim** [comment]
Awaiting #3866 PR to be merged.

**Comment by HarshaLaxman** [comment]
Any update on this?
Emoji picker freezes the app 50% of the time for me.

**Comment by cometkim** [comment]
Hey @HarshaLaxman, thank you for watching at this.

I've been very busy at work for couple months, so would resume any contribution later this month.

And probably going to go ahead from react-bootstrap related issues first because It blocks the use of react's context API. you can see the context from https://github.com/mattermost/mattermost-webapp/pull/3866 and https://github.com/mattermost/mattermost-webapp/pull/4185#issuecomment-555116758

**Comment by esethna** [comment]
Hi @cometkim, anything we can help with here?

**Comment by cometkim** [comment]
Hi @esethna. Since it hasn't been in a while, this PR will be rewritten from scratch. (Another contributor may take it)

Sharing here some of what I've researched before.

## Approaches

I benchmarked a similar component before starting this.

emoji-mart vs slack

[Emoji Mart](https://github.com/missive/emoji-mart) takes full advantage of HTML/CSS features, so there are almost no JS re-rendering. the initial mount/unmount cost is bit high, but the DOM structure is that not complicated, so it shows quite good performance with less codes and also accessibility is quite good because it is based on basic HTML elements.

Slack seems to have chosen Virtualization for more interaction, and sticky section headers etc. have also been implemented directly using JS. Since the DOM structure is not intuitive, it seems like a hack for the A11y will be necessary, but it could perform better and may be better if it optimizes the re-render more.

I suggest using the community version of emoji-mart for maintainability.

## License issue

Another issue is the fact that [the images contained in the emoji data used by Mattermost violate Apple's license terms](https://github.com/mattermost/mattermost-server/issues/10629). It is important to understand that contributing to code that uses it poses a risk to individual contributors.

So I want to migrate it to [open source emoji-data](https://github.com/iamcal/emoji-data) and use other images/emoji-fonts or just system fonts, but Mattermost's emoji codebase is pretty complicated.

It seems better suited for the core team. After resolving issues across the webapp and the redux, it will be easier for other contributors to improve the emoji picker.

**Comment by esethna** [comment]
Thanks for the details @cometkim, closing this PR. I agree it would make sense to bring this in the core team

**Pull request closed without merging**
