### PR TITLE
MM-34235 - remove trailing slash causing nav bar to hide

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
remove trailing slash causing nav bar to hide

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34235

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
The easiest bug fix ever! 🤣 Thanks @pablovelezvidal!

**Comment by marianunez** [comment]
@lieut-data Just an FYI - you may find this behavior interesting or know why this was happening

**Comment by pablovelezvidal** [comment]
> The easiest bug fix ever! 🤣 Thanks @pablovelezvidal!

All week investigating this bug 😢

**Comment by lieut-data** [comment]
Ah, yeah, we ran into this before and did the same fix instead of addressing the root cause. (I never imagined another entry point ;))

Should work a treat, but hopefully we get back to the root cause in our plugin later.

**Review by nickmisasi — APPROVED** [review]

**Pull request merged**
