### PR TITLE
Detect user-agent for mobile firefox and show app download page

### PR DESCRIPTION
**Pull request by tejasbubane**
#### Summary
Show app download page on mobile firefox.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/8783

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @tejasbubane, appreciate the PR. @lindalumitchell can QA please help queue this for testing on a firefox mobile browser?

**Comment by lindy65** [comment]
@tejasbubane @esethna 

Thanks, I've tested the PR on Android Firefox and the "Mattermost works best if you switch to our Android app" page shows up when going to the spinmint URL.  Tapping on "Continue" takes me to the Playstore to download the MM app.  Looks good to me!

**Comment by tejasbubane** [comment]
@hmhealey I have rebased the PR.

**Comment by hmhealey** [comment]
@tejasbubane Excellent. Thanks!

**Pull request merged**
