### PR TITLE
MM-33330 - fixed SidebarLink background-color on hover

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
fix for hover on SidebarLink to use correct color set from theme

#### Ticket Link
[MM-33330](https://mattermost.atlassian.net/browse/MM-33330)

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by deanwhillier — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@michelengelen the test server doesn't seem to be spinning up so I can't seem to review it yet.

**Review by matthewbirtch — APPROVED** [review]
Looks like it's using the variable now as expected. The color used on the default theme for this isn't great, but that's a different issue, and we'll be updating the default themes soon anyway

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified hover background color for sidebar items - applies correctly from the set variable.

**Pull request merged**
