### PR TITLE
Increased nickname length in settings and const

### PR DESCRIPTION
**Pull request by coltoneshaw**
#### Summary
Increased the nickname length on webapp from 22 to 64

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50324

#### Related Pull Requests
https://github.com/mattermost/mattermost-mobile/pull/7214

#### Screenshots
Screenshot 2023-03-17 at 2 48 36 PM
Screenshot 2023-03-17 at 2 48 30 PM
Screenshot 2023-03-17 at 2 48 19 PM
Screenshot 2023-03-17 at 2 17 19 PM
Screenshot 2023-03-17 at 2 17 05 PM
Screenshot 2023-03-17 at 2 57 08 PM

#### Release Note

```release-note
- Increase nickname field on UI from 22 to 64 characters
```

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@coltoneshaw Any specific reason we made this a textarea?
image


Wouldn't this allow users to add line breaks as well?

**Comment by coltoneshaw** [comment]
@asaadmahmood Based on feedback from Anna in the ticket. I can revert it back if wanted too, I'm 1/5 on it being a textarea. only benefit seems to be easier to manage a string of that length.

**Comment by asaadmahmood** [comment]
@coltoneshaw Apologies, yes it should be a basic input field instead of a textarea.

**Comment by coltoneshaw** [comment]
> @coltoneshaw Apologies, yes it should be a basic input field instead of a textarea.

Sounds good! I assume I'll have to move this onto the mono repo too, so I'll make that change and resubmit there!

**Pull request closed without merging**
