### PR TITLE
Fixing group to channel modal

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
There was an accidental omission in a typescript refactor

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33650

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Comment by BenCookie95** [comment]
@hahmadia There is already a cypress test for this and it caught the issue, the test is `MM-T1537`

**Comment by BenCookie95** [comment]
Testing blocked by https://mattermost.atlassian.net/browse/MM-33700 right now

**Review by furqanmlk — APPROVED** [review]
All looks good
image

**Pull request merged**
