### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
Resubmitting dependency updates against master.

#### QA Requirements
Quick smoke test to make sure test server comes up and behaves as expected for basic functionality.

### CODE REVIEW

**Comment by stevemudie** [comment]
@grundleborg The test server spun up on first try and appears to be working as expected.

**Comment by grundleborg** [comment]
@stevemudie thanks! Are we good to merge from the QA point of view?

**Comment by stevemudie** [comment]
@grundleborg As far as I can see, yes.

**Pull request merged**
