### PR TITLE
[MM-22703] Fix channel switcher duplicate bug

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

The channel switcher is based off of non unique terms. I have made the terms unique by appending the index to the terms to ensure all the terms are unique and we don't run in to duplicates.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22703

#### Screenshots

MM-22703

### CODE REVIEW

**Comment by mickmister** [comment]
@hahmadia Out of curiosity, what made you choose to use the index versus the channel id?

**Comment by hahmadia** [comment]
> @hahmadia Out of curiosity, what made you choose to use the index versus the channel id?

@mickmister 
No particular reason. It was the first property that came to mind when trying to think of how I can make channel names unique.

**Comment by hahmadia** [comment]
@hmhealey 
Thanks for pointing that out. Never crossed my mind. I use the channel ID instead of channel name and it doesn't lose it's position anymore.

**Comment by hmhealey** [comment]
Does this need to be cherry-picked onto 5.22?

**Pull request merged**
