### PR TITLE
Fix typo s/fatures/features in en.json

### PR DESCRIPTION
**Pull request by nathanaelhoun**
#### Summary

- [x] Fix typo `s/fatures/features` in `en.json` and in original file
#### Ticket Link

/

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR!

Could you also fix the spelling in the default text that appears where this is used?
https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/license_settings/starter_edition/starter_left_panel.tsx#L57

**Review by calebroseland — CHANGES_REQUESTED** [review]
@nathanaelhoun, would you mind changing here, too? [components/admin_console/license_settings/starter_edition/starter_left_panel.tsx](https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/license_settings/starter_edition/starter_left_panel.tsx#L55-L58)

**Comment by nathanaelhoun** [comment]
Oups, forgotten. Fixed @hmhealey @calebroseland :-) Thanks for the hint!

**Review by calebroseland — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @nathanaelhoun 
Tested, looks good to merge.
- Verified typo has been fixed `fatures>features`. [E2E report](https://automation-dashboard.vercel.app/cycles/30b32b39-9c6c-47a3-b8c5-fd6efb028015) looks good, no PR related failures.

**Comment by jgilliam17** [comment]
@hmhealey I re-ran the failed check few times, that same AWS error is persisting. What would be our next step to fix this check?

**Comment by hmhealey** [comment]
I'll try merging master into this. Perhaps something changed with the CI configuration that needed to be updated.

**Comment by calebroseland** [comment]
> I'll try merging master into this. Perhaps something changed with the CI configuration that needed to be updated.

I think there was an AWS outage around then.

**Pull request merged**
