### PR TITLE
Updates to AD/LDAP settings help text

### PR DESCRIPTION
**Pull request by jasonblais**
Feel free to squash my commits before merging.

List of changes:

1) `that will be used` to `used` in attribute help texts
2) Make PositionAttribute help text consistent with others
3) Fix `admin.ldap.uernameAttrDesc` --> `admin.ldap.usernameAttrDesc` typo.
4) For `IdAttribute`, add link to documentation for the CLI tool and renamed it from "platform ldap" to "mattermost ldap". A .com page to be created once LDAP login ID attribute docs are done.
5) Simplified Login ID Attribute help text.
6) Broke Username and Login ID Attribute texts to two paragraphs for easier readability.

WIP until I've got a chance to test the changes.

### CODE REVIEW

**Comment by jasonblais** [comment]
Not sure what the line breaks don't format properly, or the link. Probably an oversight I'm not seeing :/ 

@crspeller Not urgent, but perhaps you can help take a look?

image

**Comment by crspeller** [comment]
@jasonblais You can't just throw random HTML into the text.

**Comment by jasonblais** [comment]
@crspeller We do it all over the place though, e.g. https://github.com/mattermost/mattermost-webapp/blob/57b6a4a5c75d023107c725c007323c0c287bf53b/components/admin_console/admin_definition.jsx#L965

**Comment by jasonblais** [comment]
@crspeller Can you help? Sorry, not sure what I'm doing wrong here,

**Comment by crspeller** [comment]
@jasonblais To get the HTML to render you need to add the property `help_text_html: true,`

**Comment by jasonblais** [comment]
Thanks @crspeller - that did it

**Pull request merged**
