### PR TITLE
put timed dnd feature behind feature flag

### PR DESCRIPTION
**Pull request by darkLord19**

### CODE REVIEW

**Review by devinbinnie — COMMENTED** [review]
Thanks for the PR @darkLord19!
I just had one question about this change.

**Comment by devinbinnie** [comment]
@darkLord19 Also, it looks like the snapshots need to be updated as well.

**Review by devinbinnie — APPROVED** [review]
Approved! Thanks @darkLord19!

**Review by hmhealey — APPROVED** [review]
Looks good, but I think this'll need to wait for the feature to be re-added since it was reverted. The revert just needs to be reverted 😛

**Comment by hmhealey** [comment]
@darkLord19 Are these changes included in https://github.com/mattermost/mattermost-webapp/pull/8160? Can this PR be closed in favour of that one?

**Comment by darkLord19** [comment]
@hmhealey This was already reviewed so I haven't added this changes to other PR you mentioned. I can cherry-pick to that branch if you want.

**Comment by hmhealey** [comment]
That might be easier. That way, we only have one PR to merge so the feature will always be behind a feature flag, and you also won't need to update this branch after the other changes are in.

**Comment by darkLord19** [comment]
cherry-picked to #8160

**Comment by darkLord19** [comment]
@hmhealey I have added this commit to webapp pr

**Pull request closed without merging**
