### PR TITLE
Cypress/E2E: Overwrite cy.visit and cy.reload to have default 3s wait

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- Overwrote cy.visit and cy.reload to have 3s wait by default
- Reverted visitAndWait

```
e2e/cypress/support/extended_commands.d.ts
e2e/cypress/support/extended_commands.js
```

Note: I spot tested e2e with visit and reload and worked fined locally. I also triggered a whole cypress run here: [webapp-pr-7410](https://app.circleci.com/pipelines/github/saturninoabril/mattermost-cypress-docker?branch=webapp-pr-7410)

#### Ticket Link
NA

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Thanks Joseph! LGTM.

**Review by furqanmlk — APPROVED** [review]
Thanks @josephbaylon 
It has mede life easy :)
All look good !

**Review by prapti — APPROVED** [review]
Look through them quick, looks good!
Approving.

**Comment by prapti** [comment]
Gah! I approved the other PR that was cherry picked that possibly caused the conflicts here that need to be fixed :( Sorry @josephbaylon!

**Comment by josephbaylon** [comment]
@prapti No worries. I'm able to rebase from master and fix conflicts.

**Pull request merged**
