### PR TITLE
Prototype for use an inverted scroll in the posts list

### PR DESCRIPTION
**Pull request by jespino**
This is a prototype, it can't be merged as is, it don't handle any
repositioning, like "new messages separator" or "permalink".

It doesn't handle yet keyboard events like arrows or page up/down.

### CODE REVIEW

**Comment by jwilander** [comment]
Nice! Very interested to see if it's feasible to do this. If we could gain more control over scrolling that would be incredibly useful

One obstacle might be getting it to work well on each of the different browsers we support

**Comment by jespino** [comment]
Basically what I use now is CSS transform, which is supported by all the browser excepts OperaMini. And we have to manage all events that change the scroll (basically wheel, keypress UP/DOWN PAGE UP/PAGE DOWN, and on mobile/table, the swipe scroll). If we can manage all that cases, in the new Intermediate component. We will be able to encapsulate the inverted scroll complexity in one clear clase, and all "move-to" operations in other place (basically, move to start of the unread posts, and move to post in permalinks).

**Comment by sudheerDev** [comment]
@jespino Interesting. Would it feel like the natural scroll of the browser?

**Comment by jespino** [comment]
@sudheerDev Yes, that is the idea. Encapsulate the concept of inverse scroll to make it fill exactly the same that a normal scrolled contend, but starting in the bottom and growing in the top. I want to share the prototype to share concerns and possible edge cases and blind spots about it. If we don't find anything, I can try to build something more robust and definitive.

**Comment by jespino** [comment]
Ok, I found a trade-off here. It's not possible to intercept and modify the wheel events, that means that we have to emulate the wheel scroll behavior, so, probably it'll feel a little weird, because the scroll will not work exactly the same (probably multi-browser makes it harder, because each browser/os will manage the scroll in its own way).

**Comment by jasonblais** [comment]
@jespino Are there any next steps on this one?

**Pull request closed without merging**
