### PR TITLE
[MM-37726] - Self-managed: Update email template to new branding - Invitation email

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This email updates the invitation email template to the new branding

Screenshot 2021-08-13 at 15 04 07

#### Ticket Link
[MM-37726](https://mattermost.atlassian.net/browse/MM-37726)

#### Related Pull Requests
Has server changes (https://github.com/mattermost/mattermost-server/pull/18136)

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Review by neallred — CHANGES_REQUESTED** [review]
Can we replace `invite_illustration.png` with the new file instead of adding a new file and leaving the now unused file?

**Comment by matthewbirtch** [comment]
@AGMETEOR this test server also doesn't seem to be sending the new invite email
image

**Comment by AGMETEOR** [comment]
> @AGMETEOR this test server also doesn't seem to be sending the new invite email
> image

@matthewbirtch this PR also has server changes that contain the new templates. We can test this post merge?

**Review by neallred — APPROVED** [review]
Looks good!

**Comment by matthewbirtch** [comment]
@AGMETEOR I'll approve based on the screenshot, but we will need to ensure this is tested properly once merged. I'm off this week, so could you please coordinate with @andrewbrown00 when this is merged to test the new emails?

**Review by matthewbirtch — APPROVED** [review]

**Comment by AGMETEOR** [comment]
Ok I’ll add him for PM review for this and all the rest.

**Comment by andrewbrown00** [comment]
Thanks, @AGMETEOR, let me know when the other PR is merged and I can test.

> ...this PR also has server changes that contain the new templates. We can test this post merge?

**Comment by AGMETEOR** [comment]
> Thanks, @AGMETEOR, let me know when the other PR is merged and I can test.
> 
> > ...this PR also has server changes that contain the new templates. We can test this post merge?

@andrewbrown00 I merged the server PR.

**Comment by andrewbrown00** [comment]
Thanks, @AGMETEOR, looks like there's an issue with the `Test Servers` which seems to be impacting all or a lot of PR's atm.

**Review by andrewbrown00 — CHANGES_REQUESTED** [review]
Thanks @AGMETEOR, there are a few items to change:

- [ ] **Logo** should use the `Sapphire/Center Channel Text
#3F4350` color
- [ ] **Title** should use the `Sapphire/Center Channel Text
#3F4350` color
- [ ] **Body** should use the `Sapphire/64% Center Channel Text
#3F4350 64%` color
- [ ] **Button** (CTA) should to use the `Sapphire/Button BG
#1C58D9` color
- [ ] **Illustration** is too large and should be 246px wide
- [ ] Secondary body text should to use the `Sapphire/Center Channel Text
#3F4350` color
- [ ] **Learn more** link should use the `Sapphire/Button BG
#1C58D9` color
- [ ] **Footer text** should use the `Sapphire/56% Center Channel Text
#3F4350 56%` color

[Here's a link to the design file for reference.](https://www.figma.com/file/TnHl6HeN0Z9n7zYXx6hS5T/MM-37612-Update-Emails-to-align-with-new-brand?node-id=521%3A6333)

image

**Review by pablovelezvidal — APPROVED** [review]
LGTM!

**Comment by AGMETEOR** [comment]
> Thanks @AGMETEOR, there are a few items to change:
> 
> * [ ]  **Logo** should to use the `Sapphire/Center Channel Text #3F4350` color
> * [ ]  **Title** should to use the `Sapphire/Center Channel Text #3F4350` color
> * [ ]  **Body** should use the `Sapphire/64% Center Channel Text #3F4350 64%` color
> * [ ]  **Button** (CTA) should to use the `Sapphire/Button BG #1C58D9` color
> * [ ]  **Illustration** is too large and should be 246px wide
> * [ ]  Secondary body text should to use the `Sapphire/Center Channel Text #3F4350` color
> * [ ]  **Learn more** link should use the `Sapphire/Button BG #1C58D9` color
> * [ ]  **Footer text** should use the `Sapphire/56% Center Channel Text #3F4350 56%` color
> 
> [Here's a link to the design file for reference.](https://www.figma.com/file/TnHl6HeN0Z9n7zYXx6hS5T/MM-37612-Update-Emails-to-align-with-new-brand?node-id=521%3A6333)
> 
> image

@andrewbrown00 most of the items mentioned were not showing up due to spinwick issues. I have spun up a server that includes those now. For the image size, here's a new PR on the server side https://github.com/mattermost/mattermost-server/pull/18200 that adjusts that size. That change may not propagate quickly to this PR's spinwick though

**Review by andrewbrown00 — CHANGES_REQUESTED** [review]
Thanks, @AGMETEOR, one small change:

- [ ] **Body** should use the `Sapphire/64% Center Channel Text
#3F4350 64%` color. It has the correct color applied, but it's not using the 64% opacity.

image

**Comment by AGMETEOR** [comment]
> Thanks, @AGMETEOR, one small change:
> 
> * [ ]  **Body** should use the `Sapphire/64% Center Channel Text #3F4350 64%` color. It has the correct color applied, but it's not using the 64% opacity.
> 
> image

@andrewbrown00 updated the color in the server PR https://github.com/mattermost/mattermost-server/pull/18200/files

**Review by andrewbrown00 — APPROVED** [review]
Thanks, @AGMETEOR, this is good to go. I saw the opacity change in the other PR.

**Pull request merged**
