### PR TITLE
MM-12239 Remove "Plugins > Configuration" page, move enabling plugins setting to the Management page

### PR DESCRIPTION
**Pull request by avasconcelos114**
#### Summary
Removing Plugin `Configuration` page, and moving the enable option to the Plugin `Management` page.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/9485

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by avasconcelos114** [comment]
Notes: 
* I had to make the `PluginManagement` component an extension of `AdminSettings` in order to use `BooleanSettings` and the save function that is implemented there. Method names and implementations were adjusted accordingly in that component (and probably will need to be reviewed somewhat carefully)
* This PR changes how a user activates and enables Plugins a bit (in a UI/UX standpoint), I asked a few questions regarding how to implement these changes but it may be good to confirm that these were done well enough.

**Comment by jasonblais** [comment]
@avasconcelos114 looks like the build fails. Can you help take a look?

I'll generate another test server afterwards and ask our team member to help disable plugin uploads on it for testing (he was away last week)

**Comment by cpanato** [comment]
@avasconcelos114 try to `npm test -- -u` and check if the snapshots update makes sense

**Comment by jasonblais** [comment]
@cpanato can you help disable plugin uploads on the above test server :)

**Comment by cpanato** [comment]
@jasonblais done

**Comment by avasconcelos114** [comment]
Added a new help text for the case you described, which now leaves the upload text with 3 different cases:
* Plugins AND Plugin uploads enabled: Upload a plugin for your Mattermost server. See [documentation](!https://about.mattermost.com/default-plugin-uploads) to learn more.
* Plugins enabled but uploads disabled: Enable plugin uploads in config.json. See [documentation](!https://about.mattermost.com/default-plugin-uploads) to learn more.
* Both options disabled: To enable plugins, set **Enable Plugins** to true. See [documentation](!https://about.mattermost.com/default-plugin-uploads) to learn more.

If there's anything else I can do just let me know!

**Comment by saturninoabril** [comment]
Thanks Andre!

**Pull request merged**
