### PR TITLE
PLT-7783 Update PAT help text

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Update PAT help text.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7783

### CODE REVIEW

**Comment by jwilander** [comment]
@jasonblais I made the text changes but looking at the modals after it might be worth making some minor improvements

screen shot 2017-10-18 at 11 31 07 am
That's getting a bit long for text box IMO, maybe we make the second part help text with a grey color underneath?


screen shot 2017-10-18 at 11 30 56 am
To me this kind of looks weird with the rest of the modal, and might look better if grey colored like the other help text in the system console

2/5 on both of these

**Comment by jasonblais** [comment]
@asaadmahmood Thoughts on the above two points?

I agree with the first point where we could have
 - `Allow this account to generate personal access tokens.` as the setting text with 
 - `Removing this permission doesn't delete existing tokens. To delete them, go to the user's Manage Tokens menu.` below it as help text, in grey colour

We do this in the desktop app Settings page
image

For the second screenshot I'm 0/5

**Comment by asaadmahmood** [comment]
First one sounds fine.
For the second one, if we want to have it at the top, I think it's fine, as being on the top it takes priority, so lowering it's opacity won't do a lot. Help text at the top is similar to how it is in our account settings modal.

Another thing we can do for the second one is that we can push the help text to the bottom, and reduce it's opacity. Screenshot attached.

screen shot 2017-10-18 at 10 54 09 pm

**Comment by jasonblais** [comment]
@jwilander Would you need help with the UI changes for the "Manage Roles" screen?

For "Manage Tokens" screen: We'll want to keep the help text at the top. If the text is at the bottom and the user several tokens, the text may not be easily discoverable. So let's keep "Manage Tokens" screen as-is.

**Comment by jwilander** [comment]
I can take care of it, thanks guys

**Comment by jwilander** [comment]
Actually @asaadmahmood could I have your help with the help text coloring/indenting CSS? I feel like I'm just going to do it in a hacky way. I pushed a commit that separates the text out from the checkbox

**Comment by jasonblais** [comment]
Created a ticket for Asaad to take a look at this and another PR for CSS changes: https://mattermost.atlassian.net/browse/PLT-7942

**Comment by asaadmahmood** [comment]
Done @jasonblais @jwilander

**Comment by jasonblais** [comment]
@jwilander @asaadmahmood Looks good, except after de-selecting `Allow this account to generate...` checkbox, the help text appears below the dialog with white text

image

**Comment by jasonblais** [comment]
^same if you toggle between `System Admin` and `Member` roles

**Comment by jwilander** [comment]
@asaadmahmood looks like a CSS issue, can you take a look?

**Comment by asaadmahmood** [comment]
@jasonblais Looks like a browser rendering issue or something? Can you try another browser.
Also @jwilander, can you try this and see if you can repro it?

**Comment by jasonblais** [comment]
Reproes on Win10/Chrome but not Win10/Firefox+IE11+Edge

**Comment by asaadmahmood** [comment]
@jasonblais I've done a minor change, have a look and see if that fixes it once the build passes.

**Comment by asaadmahmood** [comment]
Then not really sure, @jasonblais can we get someone else to test it on the same browser/os.

**Comment by jasonblais** [comment]
Have asked @esethna to help repro.

**Comment by jasonblais** [comment]
Eric couldn't repro so it seems to be something on my end.

Given other people can't repro and it's only on that one browser for me, we can ignore it for now until someone else sees the issue. Moving to dev review

**Comment by jasonblais** [comment]
@jwilander Before this can be merged, it'll also need a rebase,

**Comment by jwilander** [comment]
Already done :P

**Pull request merged**
