### PR TITLE
Add deactivated users to dm modal

### PR DESCRIPTION
**Pull request by ccbrown**
#### Summary
This updates the DM modal with the changes requested in [PLT-7917](https://mattermost.atlassian.net/browse/PLT-7917).

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7917

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by saturninoabril** [comment]
Looks good to me, will just wait for PM review.

**Comment by esethna** [comment]
Need to fix build issues before test server can spin up changes

**Comment by ccbrown** [comment]
@esethna Yep... it's probably nothing wrong with this PR. Jenkins is still just totally broken. Waiting on @crspeller to get it up and running again.

**Comment by ccbrown** [comment]
@esethna New test server up.

**Pull request merged**
