### PR TITLE
show contact sales card when not on a limited plan.

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Show contact sales card for enterprise plan and legacy plan. Show subscription card for legacy plan. Having reviewed the legacy plan page, it looks ok to me with the exception of the [planned work](https://mattermost.atlassian.net/browse/MM-44772) for paid legacy customers to be prompted to change to professional (instead of the current prompt to change to starter)

To minimize review churn and because it was a fairly simple change, I also implemented https://mattermost.atlassian.net/browse/MM-44771 as part of this PR.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44760
https://mattermost.atlassian.net/browse/MM-44771

#### Screenshots
Using a higher quality cloud mock made it a lot easier to see what all these screens look like:

Cloud Starter Free
cloud-starter-free

Cloud Starter Paid (legacy)
cloud-starter-legacy

Cloud Professional
cloud-professional

Cloud Enterprise
cloud-enterprise

Cloud Legacy
cloud-legacy

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by johndavidlugtu** [comment]
@neallred 
Screen Shot 2022-06-02 at 4 21 55 PM
Can we change "View all benefits" to "View all features"?

Justine has pointed out that we don't use "benefits" elsewhere.

**Comment by neallred** [comment]
Updated. Assuming spinwick build is successful, you should see the change in about 30 minutes if you refresh the page.

**Comment by johndavidlugtu** [comment]
>And likewise Explore Enterprise features?

Yes good catch, that too

**Review by marianunez — CHANGES_REQUESTED** [review]
- Starter both LGTM 

 For Professional:

- Given that they are a paying customer, we need to show them the billing summary like Enterprise on the RHS 

For Cloud Legacy:

- The name is showing Free but I’m not sure if that’s just a detail on the subscription setup for the test
- If Cloud Legacy, isPaidTier then they also need to see the billing summary on the RHS

(Doing the code review next)

**Review by marianunez — COMMENTED** [review]
Code LGTM. Will re-review after the changes requested above

**Comment by neallred** [comment]
>  For Professional:
>
> * Given that they are a paying customer, we need to show them the billing summary like Enterprise on the RHS

I can do that, but it conflicts with designs showing an upgrade card: https://www.figma.com/file/Aob5ffHtfjKzQoebR93ycA/Cloud-Freemium?node-id=3183%3A216991 

upgrade-card

**Comment by johndavidlugtu** [comment]
@marianunez that works

**Review by nickmisasi — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
I tested each product one-by-one and these all look good @neallred!

**Review by johndavidlugtu — APPROVED** [review]
This is great, thanks @neallred

**Pull request merged**
