### PR TITLE
[MM-21954] Fix CSS problems

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Address the following problems:
- Team and channel membership table - padding is missing
- Remove team icons.
- Change opacity of text in type column
- Remove confirmation modal has placeholder text

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21954

#### Screenshots
image
image

### CODE REVIEW

**Comment by srkgupta** [comment]
@hahmadia 
There is another PR submitted for fixing the padding issue by @asaadmahmood 
https://github.com/mattermost/mattermost-webapp/pull/4722

**Comment by srkgupta** [comment]
@hahmadia can you also please update the Cypress test.

**Comment by hahmadia** [comment]
> @hahmadia
> There is another PR submitted for fixing the padding issue by @asaadmahmood
> #4722

Ok! This is for the team and channel membership table in the groups. It isn't regarding those tables that Asaad has fixed.

**Comment by hahmadia** [comment]
@srkgupta 
I have updated the cypress test and now it works like before.

@michaelgamble 
I have removed the quotes as discussed. Please see updated screenshot

**Pull request merged**
