### PR TITLE
Revert "[MM-24507]: sticky "reply to thread..." input"

### PR DESCRIPTION
**Pull request by michelengelen**
Reverts mattermost/mattermost-webapp#9482

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44131

### CODE REVIEW

**Comment by michelengelen** [comment]
@koox00 @jgilliam17 @larkox kind reminder to review!

**Review by koox00 — APPROVED** [review]

**Comment by hmhealey** [comment]
I added a link to https://mattermost.atlassian.net/browse/MM-44131 since we think they're related, and I wanted to be able to see the status of the PR from there.

Also, /release-note-none

**Comment by amyblais** [comment]
@michelengelen This has merge conflicts that need to be resolved.

**Comment by amyblais** [comment]
@jgilliam17 This is ready for testing.

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified sticky reply input has been reverted.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/197663-31f8844-onprem-ent-webapp-pr-10317-mm-ee-test:31f8844/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
