### PR TITLE
MM-28042,MM-28046 - Web/Desktop: Relative links open in a new tab/window

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Restored the regex used to detect internal links

#### Ticket Link
Fixes:
https://mattermost.atlassian.net/browse/MM-28042
https://mattermost.atlassian.net/browse/MM-28046

### CODE REVIEW

**Review by sudheerDev — APPROVED** [review]
LGTM

**Comment by sudheerDev** [comment]
@ali-farooq0 Linked another ticket and assigned it to you as it solves that as well.

**Comment by hmhealey** [comment]
What about https://github.com/mattermost/mattermost-webapp/pull/6147? Perhaps we can just check for if the link starts with the site URL or `/` instead?

**Comment by ali-farooq0** [comment]
I'm afraid that with the relative link it might be possible to abuse it in someway which is why i kept the regex in. Also I do check if the link starts with siteURL or the origin regex `/(...admin...|pl...)` so  #6147 is still works.

**Comment by hmhealey** [comment]
Yeah, that makes sense. I was worried that might be an issue when I was suggesting it. I don’t think that’s actually the case, but it’s good to be safe. As long as there’s no regressions here, this looks good to me.

**Comment by ali-farooq0** [comment]
@stevemudie would you be able help QA this PR? Thanks!

**Pull request merged**
