### PR TITLE
[MM-42858] Fix Actions Menu Background height in Mobile View

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
Note this is in Mobile View. 

This PR fixes an issue where an open Actions Menu background will be off-center and not cover the whole screen.  The solution is to call the `handleDropDownOpened` callback prop, similar to how a `...` menu click does.

QA should test for opening the actions menu in the following mobile post view locations:
* center channel
* RHS root post
* RHS comment post

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42858

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |

#### Release Note

```release-note

```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by jwilander — APPROVED** [review]

**Review by matthewbirtch — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks @jfrerich! Tested and passed.

**Comment by saturninoabril** [comment]
Oh no, I accidentally removed the "CherryPick/Approved" label. Now added back.

**Pull request merged**
