### PR TITLE
[MM-47846] Retrieve playbook templates

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
We need playbooks to expose their internal templates for the Work Templates project. The PR from the playbooks repository dispatches an action in the store, this PR is responsible for reading and reducing this action to make it usable from the webapp.

This is the other side of this PR made in playbooks: https://github.com/mattermost/mattermost-plugin-playbooks/pull/1631

#### Ticket Link
Part of [mattermost.atlassian.net/browse/MM-47846](https://mattermost.atlassian.net/browse/MM-47846)

#### Related Pull Requests
- Playbooks: https://github.com/mattermost/mattermost-plugin-playbooks/pull/1631

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
LGTM! thanks @JulienTant!

**Review by gbochora — APPROVED** [review]

**Comment by hmhealey** [comment]
Where's this action dispatched from? I don't see any reference to that in the linked Playbooks PR.

Since we're still trying to avoid storing Playbooks stuff in with the main web app or at least limit it, could we perhaps store them somewhere more work templates specific like `entities.workTemplates.playbookTemplates`? If we're putting Playbooks state in the web app, I'd prefer to make it less generic sounding so that other people are less likely to follow that pattern.

**Comment by JulienTant** [comment]
> Where's this action dispatched from? I don't see any reference to that in the linked Playbooks PR.

Hey @hmhealey the action is declared here:
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1631/files#diff-1f362212a3bba1279c8de995a16bff31e0bb41ba52ebb1d27eaa970073b958dfR404

and dispatched here:
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1631/files#diff-47ddfada7835e6c591120fc4ca2bde4e83ba9834df8550cddb48349d7040b36eR323

> Since we're still trying to avoid storing Playbooks stuff in with the main web app or at least limit it, could we perhaps store them somewhere more work templates specific like `entities.workTemplates.playbookTemplates`? If we're putting Playbooks state in the web app, I'd prefer to make it less generic sounding so that other people are less likely to follow that pattern.

Yeah I can definitely move it, I've set it to the root of `entities` because I was trying to prevent any duplication but I'm really 0/5 on that.

**Comment by hmhealey** [comment]
> Hey @hmhealey the action is declared here:

Oh, sorry about that. I didn't work out that those were the same action type for some reason.

> Yeah I can definitely move it, I've set it to the root of `entities` because I was trying to prevent any duplication but I'm really 0/5 on that.

Cool, thanks. I agree that preventing duplication is important, but I'm starting to get in the mindset that waiting for something to actually be needed in two places before moving it to somewhere shared. Otherwise, you end up with a lot of one-off logic and helpers cluttering up places like `mattermost-redux` or `utils/utils`

**Pull request merged**
