### PR TITLE
scale uploaded profile pics proportionally

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Scales uploaded profile pics proportionally

Cc @dmeza

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by esethna** [comment]
@dmeza please help rebase to get the build passing

**Comment by dmeza** [comment]
@asaadmahmood @csduarte I tested IE11 and it even though it's not supported, nothing breaks. Now, I think we can close this PR since it seems to be fixed in MM master. It was intended to keep aspect ratio of images that didn't happen with tall or wide images.

**Comment by jasonblais** [comment]
@dmeza 

> Now, I think we can close this PR since it seems to be fixed in MM master.

Is this PR still needed by your team? Or should we close it?

**Comment by dmeza** [comment]
@jasonblais You can close it, thank you. The changes on master seem to work fine.

**Pull request closed without merging**
