### PR TITLE
E2E Update text for opening keyboard shortcuts modal

### PR DESCRIPTION
**Pull request by jgilliam17**
#### Summary
When checking if we had an automated test for related PR (see below), found this test, currently unstable.
I updated `findByText` from `CTRL` to `Ctrl` .

#### Ticket Link
Related Jira Ticket: https://mattermost.atlassian.net/browse/MM-40853
Releated PR: https://github.com/mattermost/mattermost-webapp/pull/9802

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots
Screen Shot 2022-02-23 at 2 27 03 PM

#### Release Note

```release-note
none
```

### CODE REVIEW

**Comment by jgilliam17** [comment]
I didn't see the test case on the report, added prod tag

**Comment by jgilliam17** [comment]
Find `Ctrl` step is passing, updating to latest I think it is missing the fix from the related PR that was merged in the meantime
Screen Shot 2022-03-10 at 3 02 22 PM

**Comment by jgilliam17** [comment]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/169779-5ba45a0-onprem-ent-webapp-pr-9872-mm-ee-test:5ba45a0/mochawesome.html) finally green 🎉 
Screen Shot 2022-03-11 at 5 53 01 PM

**Review by saturninoabril — APPROVED** [review]
Thank you Jelena! Great to see you're fixing automated tests!

**Comment by saturninoabril** [comment]
Merging now before I merged my PR that reorganize folder structure for `/e2e`

**Pull request merged**
