### PR TITLE
[MM-28211] Plan Details Card - UX demo

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
This PR shows off the Plan Details card on the new Cloud Billing screen
Currently there's no back-end hookup for it, but I'd like to have the design reviewed while other PRs are awaiting review.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28211

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@devinbinnie the test server creation failed.

**Comment by devinbinnie** [comment]
@matthewbirtch Good to go now, sorry about that.

**Comment by matthewbirtch** [comment]
Sorry @devinbinnie I can't seem to access the billing and account section
image

**Comment by devinbinnie** [comment]
> Sorry @devinbinnie I can't seem to access the billing and account section
> image

@matthewbirtch Forgot to upload the license and flip the switch, it's on now.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @devinbinnie. A few small tweaks to make:

1. The white container should have a `border-radius: 4px`
2. Reduce the space between checklist lines by 4px. The top margin is right (12px), the text line-height is right(16px), but something with the check icon is causing the container to be taller and add extra space between each check list item

**Review by matthewbirtch — APPROVED** [review]
Looks great. Nice work @devinbinnie

**Comment by devinbinnie** [comment]
Closing as UX review is complete, will put up a new PR including logic once that is complete

**Pull request closed without merging**
