### PR TITLE
[MM-35176] Fixing banner times

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Fixing an issue where the announcement banner time won't match the trial card

#### Ticket
https://mattermost.atlassian.net/browse/MM-35176

```release-note
Fixed an issue with trial licenses where the banner end date did not match the trial card end date.
```

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Comment by amyblais** [comment]
@sbishel Is this bug fix needed for v5.35, or the fix version doesn't matter?

**Comment by BenCookie95** [comment]
> @sbishel Is this bug fix needed for v5.35, or the fix version doesn't matter?

I would like to put it in v5.35 if possible?

**Comment by sbishel** [comment]
@BenCookie95 - Could you add the ticket to the description.
If  @furqanmlk - Would you have time to test this quickly. Then we can get it in, but otherwise it can wait for v5.36.

**Comment by furqanmlk** [comment]
> @BenCookie95 - Could you add the ticket to the description.
> If @furqanmlk - Would you have time to test this quickly. Then we can get it in, but otherwise it can wait for v5.36.

Sure I am testing now

**Pull request merged**
