### PR TITLE
    MM-20415 Migrate 'components/channel_header_mobile/unmute_channel_button' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by Revanth47**
MM-20415 Migrate 'components/channel_header_mobile/unmute_channel_button' module and associated tests to TypeScript

#### Summary
Migrating 'components/channel_header_mobile/unmute_channel_button' module and associated tests to TypeScript

#### Ticket Link
Fixes mattermost/mattermost-server#16158
JIRA: https://mattermost.atlassian.net/browse/MM-20415

### CODE REVIEW

**Comment by jfrerich** [comment]
@deanwhillier, @cpoile, gentle reminder to review this PR

**Review by cpoile — APPROVED** [review]
Looks good to me, thanks @tbalthazar !

**Review by deanwhillier — APPROVED** [review]
LGTM, thanks so much @Revanth47!

**Review by jgilliam17 — APPROVED** [review]
Thank you @Revanth47 
Tested, looks good to merge.
-Verified unmute button on mobile web view channel header - no change in functionality.
@deanwhillier Can you please help merge? Thanks 🙂

**Comment by hanzei** [comment]
Thank you for the contribution @jgilliam17 :tada:

**Comment by hanzei** [comment]
Thank you for the contribution @Revanth47 :tada:

**Pull request merged**
