### PR TITLE
MM-17468 - Improving performance of fetching threads

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
Added support for new 'response_count' field in Post to improve performance for threaded post fetching.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-17468

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/11980
https://github.com/mattermost/mattermost-redux/pull/911

### CODE REVIEW

**Comment by reflog** [comment]
@lieut-data - reworked the PR, now that the server always returns the root post as well with the proper count - results should be displayed properly

**Comment by hanzei** [comment]
@lindalumitchell Can you please confirm if this PR needs QA review?

**Comment by lindalumitchell** [comment]
Thanks, this one is fine to continue. Removing QA Review label.

**Comment by hanzei** [comment]
@reflog Is this ready to merge?

**Pull request merged**
