### PR TITLE
[MM-44400]: remove feature flag references and legacy code

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
removal of all feature flag related code and also the legacy components `CreateComment` and `CreatePost`.

#### Ticket Link
[MM-44400](https://mattermost.atlassian.net/browse/MM-44400)
[MM-44327](https://mattermost.atlassian.net/browse/MM-44327)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by Willyfrog** [comment]
@stevemudie were the results from e2e ok?

@michelengelen can you fix the conflicts?

**Comment by stevemudie** [comment]
@Willyfrog Yes, sorry for the delay but the E2E went through just fine.

**Pull request merged**
