### PR TITLE
Fixing a typo

### PR DESCRIPTION
**Pull request by amyblais**
#### Summary
Fixing a typo in "Town-Square is Read-Only" setting description. Will update docs once this is approved.

### CODE REVIEW

**Comment by amyblais** [comment]
@mkraft Wasn't sure who to ask but do you know if there are other places where this should be updated?

**Comment by mkraft** [comment]
@amyblais This looks like all the places to me 👍

**Comment by hanzei** [comment]
@amyblais  You need to merge `master` into this.

**Comment by amyblais** [comment]
@hanzei I probably don't have access to do that or I'm not sure how to do it.

**Comment by hanzei** [comment]
@amyblais Fixed and merged this for you. Hope you are fine witht this.

**Comment by amyblais** [comment]
Thank you!

**Pull request merged**
