### PR TITLE
[PLT-6940] Add webrtc call at channel navbar and make it available on narrow window

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add webrtc call at channel navbar and make it available on narrow window

Resubmitted to mattermost-webapp from https://github.com/mattermost/mattermost-server/pull/7294
Note: With pending UI decision from @asaadmahmood and @jasonblais  

#### Ticket Link
Jira ticket: [PLT-6940](https://mattermost.atlassian.net/browse/PLT-6940)

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@saturninoabril Does this have changes from @asaadmahmood yet?

**Comment by saturninoabril** [comment]
@jasonblais None yet. I just submitted this PR so he can push whatever is necessary.

**Comment by jasonblais** [comment]
@saturninoabril Were all the changes from https://github.com/mattermost/mattermost-server/pull/7294 applied to this PR? 

I wasn't able to get the video icon to show in mobile view.

**Comment by saturninoabril** [comment]
@jasonblais Yes. I think the problem occurred after the rebase. I'm seeing error not related to this PR but related to the migration of channel_header to redux pattern. I'll queue resubmission of this PR later. 

screen shot 2017-09-27 at 6 16 21 pm

**Comment by saturninoabril** [comment]
@jasonblais Should be fine now after a rebasing again to master, and yes all from https://github.com/mattermost/mattermost-server/pull/7294 were included.

**Comment by jasonblais** [comment]
Thanks @saturninoabril!

1) Based on https://github.com/mattermost/mattermost-server/pull/7294#issuecomment-326980239, I'd expect
 - show header icon (webrtc__button) at >480px up to 768px
 - show dropdown list (webrtc__option) at 480px and below

but it looks like the header icon is never shown in mobile view regardless of screen size.

2) Is it possible to add an offline state, both in the header and the menu? This would be consistent with the desktop view, where the icon is always visible but with different states depending on if the other user is online or offline. If yes, I can give you a proposed design.

I think otherwise this looks good.

**Comment by saturninoabril** [comment]
@jasonblais I'll fix item #1 and 👍  yes for #2. Please let me know the design. thanks!

**Comment by jasonblais** [comment]
@saturninoabril Really sorry for not following up on this sooner.

1) Perfect, sounds good.
2a) For the header icon, can you help match what we do in desktop view? When it's in offline mode, we reduce the opacity of the icon
2b) For the menu (channel navbar), please help include `Start Video Call` regardless of whether the user is online or not as a start and we can get Asaad's help with CSS. We might reduce the opacity when the user is offline for instance.

**Comment by jasonblais** [comment]
@saturninoabril Let me know if you had any questions about above?

**Comment by saturninoabril** [comment]
@jasonblais Sorry, for late reply. I'll check this out.

**Comment by saturninoabril** [comment]
@jasonblais This should be ready for PM review. Also, I have included here the WebRTC behavior for DND (do not disturb); I made it similar to busy and offline.
- added "Do not disturb" tooltip. Tooltip text for your approval.

2a - should be good now.
2b - should be ready for further modification. Note that as requested, dropdown menu for WebRTC will show "Start Video Call" for statuses like offline, DND and busy. On top of CSS styles (opacity), it might also be better to have the text change depending on status. 

Let me know if there's something to change.

**Pull request merged**
