### PR TITLE
Cypress/e2e:fixed custom status test case

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Fixed custom status cases 
This small change fixed 5 test cases

#### Screenshots

image

```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM

**Review by saturninoabril — APPROVED** [review]
Awesome, thanks Malik!
(Just need to fix the lint error)

**Review by prapti — APPROVED** [review]

**Pull request merged**
