### PR TITLE
MM-19818 - Updating whitespace for th in markdown

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-19818 - Updating whitespace for th in markdown
This also fixes the post alignment issue in the RHS Thread.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19818

#### Screenshots
Screenshot 2019-12-05 at 6 18 00 PM
Screenshot 2019-12-05 at 6 18 07 PM

### CODE REVIEW

**Comment by stevemudie** [comment]
@asaadmahmood I noticed that the email address is limited to the width of the number of characters in the header row.

Is this expected?

Long text in header row

Short text in header row

**Comment by asaadmahmood** [comment]
@stevemudie Not expected, good catch.

**Comment by asaadmahmood** [comment]
@stevemudie Have a look again when you get the chance.

**Comment by stevemudie** [comment]
@asaadmahmood Should I kill the test server and rebuild?
Or wait for this? ➜ "_New commit detected. SpinWick will upgrade if the updated docker image is available._"

**Comment by asaadmahmood** [comment]
@stevemudie wait for it.

**Comment by amyblais** [comment]
@cpanato Could you help with cherry-picking this to v5.18?

**Comment by asaadmahmood** [comment]
@amyblais That's done.

**Pull request merged**
