### PR TITLE
MM-44417 Fix translation typo

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Fixing a copy-paste error
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44417
#### Release Note
```
NONE
```
```release-note
NONE
```

### CODE REVIEW

**Comment by ctlaltdieliet** [comment]
Hi @amyblais,
I fixed the copy-paste error in the  code. I don't know if I have to modify en.json as well. Can you give me a clue on that.
Thank you.

**Comment by ctlaltdieliet** [comment]
Hi @amyblais,
I fixed the copy-paste error in the  code. I don't know if I have to modify en.json as well. Can you give me a clue on that.
Thank you.

**Comment by amyblais** [comment]
> Hi @amyblais, I fixed the copy-paste error in the code. I don't know if I have to modify en.json as well. Can you give me a clue on that. Thank you.

I'm guessing yes, but dev reviewers can confirm on that.

**Review by hmhealey — COMMENTED** [review]
The change looks good to me. From what I can tell, the typo didn't make it to en.json, but it did end up in the German translation somehow
```
harrison-mm:mattermost-webapp harrison $ ag shortcuts.msgs.markdown.preview
components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
331:            id: t('shortcuts.msgs.markdown.preview'),
335:            id: t('shortcuts.msgs.markdown.preview.mac'),

i18n/de.json
4336:  "shortcuts.msgs.markdown.preview": "Emoji / Gif Auswahl:\tStrg|Umschalt|P",
4337:  "shortcuts.msgs.markdown.preview.mac": "Vorschau ein/ausblenden:\t⌘|Umschalt|P",

i18n/en.json
4285:  "shortcuts.msgs.markdown.preview": "Show/Hide Preview:\tCtrl|Shift|P",
4286:  "shortcuts.msgs.markdown.preview.mac": "Show/Hide Preview:\t⌘|Shift|P",
```

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
