### PR TITLE
RTL View and Persian Language

### PR DESCRIPTION
**Pull request by theSinner**
#### Summary
Adding RTL layout and Persian language to available languages.
Translation to Persian is incomplete yet, but main sentences and words are translated.
Please see the Transifex in the below link:
https://www.transifex.com/system-negar-saina/mattermost-web-application
#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you @theSinner for the contribution!

Few initial thoughts to get the discussion started:

1. I'm wondering your thoughts on what is the best way to maintain an RTL layout long-term. I worry how much effort it adds for testing and development effort to maintain each release. For instance, would adding [end-to-end testing](https://developers.mattermost.com/contribute/webapp/end-to-end-tests/) be an option?

2. What changes does this PR make to the UI to support an RTL layout? I'd be happy to test it and generate a server for it, but looks like the build fails.

3. You probably already know, but just mentioning that RTL layout would need to be added for mobile separately here: https://github.com/mattermost/mattermost-mobile

4. As a side note, translations are actually managed by our [Translations Server](https://translate.mattermost.com/projects/mattermost) - so before accepting the PR, we should migrate the translated strings from en.json there.

Thanks again! If anyone in the community has additional thoughts to share, please let us know. Hope to discuss RTL support and what it would take to release it :)

**Comment by jasonblais** [comment]
Hey @theSinner, let us know if you have any questions about the above? Would be happy to discuss with you :)

**Comment by theSinner** [comment]
Hi
Sorry for replying very late, I was very busy and I didn't check my Github notifications.
1. yeah, it's a good idea to add e2e testing. I'll try to add it for RTL layout.

2. I ran web-app build and test commands before sending merge request, but I didn't run it with a server. since we are using Mattermost in our company, I started to override the LTR style whenever I see a problem in RTL view in daily usage. Usually, we create a style file for every component in our multi-language web projects in my team, but I thought it’s better to make less code change for adding this feature. If you think using separate style files for each component is better, I can create a new pr to handle this.
I also added dir=“auto” to all inputs to set text-align based on the entered text.

3. Yes, I’m working on the mobile project. I added the Persian language and a condition for forcing RTL layout when selected language is Persian, but components need custom styles for handling RTL view. I couldn’t find select language in settings. I realize that changing language is only available at web-app. Is it a good idea to add this to the app settings as a separate feature?

4. Yes, when I started adding Persian to project, I requested to add Persian language to Mattermost translation server, but I received an email that mentioned we cannot add Persian, because Mattermost has not RTL layout yet and because of using Mattermost in our teams, I should translate the primary sentences to make it better. I can move it to Mattermost translation server and disable the Transifex project whenever you want.

**Comment by jasonblais** [comment]
Thanks @theSinner! Really appreciate your input. 1 - 4 make sense and I'll think about them some more.

Wondering if you'd be open to reviewing the build details [here](https://github.com/mattermost/mattermost-webapp/pull/2967/checks?check_run_id=148463434) and see if we can resolve the test failure? Then we should be able to generate a test server to try things out :tada:

I do want to be transparent that I cannot guarantee we are in a position to accept the changes - it'll depend on overall estimate of maintenance and testing effort against the value of the feature for the wider community. But I'd like to get a server up and running so we can at least test the changes and go from there. I'm excited to try it out :D

**Comment by theSinner** [comment]
I'm sorry. I forgot the snapshot errors. I fixed them, but when I run `npm run-script test` I saw another failed test about create-post that isn't about my changes and when I fetch new commits from the master branch and merge them, I have 3 errors and they aren't about my changes neither.

### This is the result before merging:

  Summary of all failing tests
   FAIL  components/create_post/create_post.test.jsx
    ● Test suite failed to run

      babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
      Invalid variable access: process
      Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, console, expect, isNaN, jest, parseFloat, parseInt, require, undefined, global, clearInterval, clearTimeout, setInterval, setTimeout, queueMicrotask, clearImmediate, setImmediate.
      Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` (case insensitive) are permitted.

        at invariant (node_modules/babel-plugin-jest-hoist/build/index.js:15:11)
        at newFn (node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)
        at NodePath._call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
        at NodePath.call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
        at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:88:12)
        at TraversalContext.visitQueue (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitMultiple (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:85:17)


  Test Suites: 1 failed, 371 passed, 372 total
  Tests:       2301 passed, 2301 total
  Snapshots:   955 passed, 955 total
  Time:        256.063s
  Ran all test suites.

### and this is the test result after merging with the current master:

  Summary of all failing tests
   FAIL  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
    ● components/suggestion/at_mention_provider/AtMentionProvider › should suggest for username match "@-split"

      expect(jest.fn()).toHaveBeenNthCalledWith(expected)

      Expected mock function third call to have been called with:
        {"component": [Function AtMentionSuggestion], "items": [{"first_name": "out Junior", "id": "userid6", "last_name": "out", "nickname": "out", "type": "mention.nonmembers", "username": "user.six-split"}], "matchedPretext": "@-split", "terms": ["@user.six-split"]}
      as argument 1, but it was called with
        {"component": [Function AtMentionSuggestion], "items": [], "matchedPretext": "@-split", "terms": []}.

      Difference:

      - Expected
      + Received

        Object {
          "component": [Function AtMentionSuggestion],
      -   "items": Array [
      -     Object {
      -       "first_name": "out Junior",
      -       "id": "userid6",
      -       "last_name": "out",
      -       "nickname": "out",
      -       "type": "mention.nonmembers",
      -       "username": "user.six-split",
      -     },
      -   ],
      +   "items": Array [],
          "matchedPretext": "@-split",
      -   "terms": Array [
      -     "@user.six-split",
      -   ],
      +   "terms": Array [],
        }

        453 | 
        454 |         await Promise.resolve().then(() => {
      > 455 |             expect(resultCallback).toHaveBeenNthCalledWith(3, {
            |                                    ^
        456 |                 matchedPretext,
        457 |                 terms: [
        458 |                     '@user.six-split',

        at toHaveBeenNthCalledWith (components/suggestion/at_mention_provider/at_mention_provider.test.jsx:455:36)

   FAIL  components/create_post/create_post.test.jsx
    ● Test suite failed to run

      babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
      Invalid variable access: process
      Whitelisted objects: Array, ArrayBuffer, Boolean, DataView, Date, Error, EvalError, Float32Array, Float64Array, Function, Generator, GeneratorFunction, Infinity, Int16Array, Int32Array, Int8Array, InternalError, Intl, JSON, Map, Math, NaN, Number, Object, Promise, Proxy, RangeError, ReferenceError, Reflect, RegExp, Set, String, Symbol, SyntaxError, TypeError, URIError, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WeakMap, WeakSet, arguments, console, expect, isNaN, jest, parseFloat, parseInt, require, undefined, global, clearInterval, clearTimeout, setInterval, setTimeout, queueMicrotask, clearImmediate, setImmediate.
      Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` (case insensitive) are permitted.

        at invariant (node_modules/babel-plugin-jest-hoist/build/index.js:15:11)
        at newFn (node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)
        at NodePath._call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
        at NodePath.call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
        at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:88:12)
        at TraversalContext.visitQueue (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitMultiple (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:85:17)


  Snapshot Summary
   › 11 snapshots updated from 5 test suites.

  Test Suites: 2 failed, 372 passed, 374 total
  Tests:       1 failed, 2337 passed, 2338 total
  Snapshots:   11 updated, 952 passed, 963 total
  Time:        108.956s
  Ran all test suites.

**Comment by jasonblais** [comment]
Thanks for sharing these! @asaadmahmood or @enahum Wondering if resolving these errors is something you'd be able to help with?

By the way - @theSinner - a heads up that I'll be out of office next week so may be slow to respond until I'm back July 8th

**Comment by enahum** [comment]
Snapshots are failing

```
UNKNOWN
4 FAILURES
Your job ran 2377 tests with 4 failures
components/PostMarkdown plugin hooks can build upon other hook message updates - components/PostMarkdown plugin hooks can build upon other hook message updates
Error: expect(received).toMatchSnapshot()
components/PostMarkdown plugin hooks can overwrite other hooks messages - components/PostMarkdown plugin hooks can overwrite other hooks messages
Error: expect(received).toMatchSnapshot()
components/PostMarkdown should render properly with a post - components/PostMarkdown should render properly with a post
Error: expect(received).toMatchSnapshot()
Less
components/PostMarkdown should render properly with an empty post - components/PostMarkdown should render properly with an empty post
Error: expect(received).toMatchSnapshot()
```

**Comment by jasonblais** [comment]
Very cool

image

There's been other team members who have been interested in RTL view with Persian language, so I'll see if they're open to trying it out as well and share feedback

**Comment by enahum** [comment]
@theSinner @jasonblais Regarding 3 :
> Yes, I’m working on the mobile project. I added the Persian language and a condition for forcing RTL layout when selected language is Persian, but components need custom styles for handling RTL view. I couldn’t find select language in settings. I realize that changing language is only available at web-app. Is it a good idea to add this to the app settings as a separate feature?

Yes the mobile app will need styles for RTL everywhere, so this is a big change!! and the language is a user setting so it applies everywhere, it is not device or session specific, if we want to add the option to change the language on mobile, that's fine but is going to affect the webapp/desktop when changed.

My concern is that RTL is going to become a 5th class citizen and people will not pay attention to it, imagine at this point the mobile app is still a 2nd class citizen and the desktop app does not fall short really, so having Designers, PM, QA and Devs thinking on features and bug fixes and having to build and test them with RTL in my opinion is going to fail unless Everyone is aware of this and is a company decision to add it in.

**Comment by jasonblais** [comment]
@enahum Good points about RTL - and I'm not sure we have the bandwidth to consider it as a first-class citizen with the upcoming UI overhaul that's planned, which may require a lot of changes for this particular feature

**Comment by tomer953** [comment]
Hey, I'm also interested in the RTL layout for mattermost.
Great to see that someone is actually working on it.

I am here to help if any testing is needed.
from a few minutes of exploring the test server, I noticed a few css problems
for example radio buttons, and timestamps are not aligned well.

image

image

Also I noticed that when a phrase starts with English word, the result is LTR in the chat,
and when its not, the result is RTL. I really think that the we should stick RTL only, even for phrases that starts with English..
imagine this case:
Message 1: "hey user please type:" (IN RTL Language - will show on right side)
Message 2: "command" (IN ENGLISH, will show on the left side)
Message 3: "to register to our service..." (IN RTL Language - will show again on the right side)

in this case the user might not notice the second message...

Again, many thanks and great work!

For the devs, please consider adding this option as Experimental, that's the only way to my opinion that things actually will moves forward.. no LTR user will ever enable this option, but every RTL user will glad to see this experimental option coming... even only on single platforms.
(ie: in  my org, we do not use mobile)

Thank you all.

**Comment by jasonblais** [comment]
@theSinner wondering your thoughts on any of the above?

**Comment by jasonblais** [comment]
Hi @theSinner - touching base to hear your thoughts on latest feedback? I'd be happy to jump on a call (audio or video) to discuss as well, if easier. Let me know

**Comment by theSinner** [comment]
Hi @jasonblais
Sorry for not responding. I’ve been busy these past weeks.
As I mentioned before, I made these changes for my team and then I think that its  a good idea to send a PR to official repo and I know that maybe it has many problems. I’ll be happy if we can fix the problems and merge the changes to master, but I don’t want to make any challenge or risk. If you think we can find a solution for how to maintain the RTL feature, I can contribute to it in my free time.


Hi @tomer953
Thank you for reporting the issues.
About the right aligned English that you mentioned , I set dir=“auto” to all contents. I tested it with right aligned English, and it was a little messy in writing and displaying.

**Comment by theSinner** [comment]
Yes, of course. I will update my fork with the main repo and fix the issues we face while using it.
Just I was thinking that there are too many sentences that must be translated and you said translation must be done in mattermost translate engine, can you add Persian language to it to start the translation?

**Comment by jasonblais** [comment]
@theSinner 

> Just I was thinking that there are too many sentences that must be translated and you said translation must be done in mattermost translate engine, can you add Persian language to it to start the translation?

Certainly! I've asked our team to help add the language to the translations server 👍

**Comment by jasonblais** [comment]
@theSinner Persian has now been added: https://translate.mattermost.com/fa/mattermost/

I'll close this PR for now as per above discussion. Thanks again @theSinner :+1:

**Pull request closed without merging**
