### PR TITLE
[MM-46819] Fix post overlay menu blocking message in compact mode

### PR DESCRIPTION
**Pull request by babinderrathi**
#### Summary
Fix post overlay menu blocking message in compact mode

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/20923
Jira: https://mattermost.atlassian.net/browse/MM-46819

#### Related Pull Requests
|  before  |  after  |
|----|----|
| unknown | unknown |

#### Release Note

```release-note
- Fix post overlay menu blocking message in compact mode
```

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM

**Review by nevyangelova — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @babinderrathi 
Tested, looks good to merge.
Verified post menu overlay, while in compact mode, is no longer blocking the message text 
[E2E report ](https://automation-dashboard.vercel.app/cycles/be56ed1e-e676-4caa-8083-46ba6977e02f)- no PR related failures

**Pull request merged**
