### PR TITLE
Mm 47645 show license count activated users

### PR DESCRIPTION
**Pull request by Afsoon**
#### Summary
Display the number of active users on License Panel Detail and dynamically style based on some limits.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47645

#### Related Pull Requests
- Has server changes https://github.com/mattermost/mattermost-server/pull/21666

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |

Between 5% - 10% Overage.

image

Over 10% Overage
image

#### Release Note
```release-note
Self hosted license detail display the active users.
```

### CODE REVIEW

**Review by ConorMacpherson — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
Thank you @Afsoon ,

I tested it locally. Trying to generate some data in pr-instance.

Added a zephyr for release testing, [MM-T5222](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T5222
)
Screenshot 2022-11-01 at 11 30 06 AM

Screenshot 2022-11-01 at 11 29 44 AM

**Comment by Afsoon** [comment]
gentle ping @annelieseklein

**Comment by Afsoon** [comment]
@annelieseklein gentle ping to review the design of this ticket. Here it's the URL to the instance where you can check it, and it has enough users to force the first threshold. 

URL: https://mattermost-server-pr-21666.test.mattermost.cloud/

| Account Type | Username | Password |
|---|---|---|
| Admin | sysadmin | Sys@dmin123 |
| User | user-1 | User-1@123 |

**Comment by Afsoon** [comment]
> @annelieseklein gentle ping to review the design of this ticket. Here it's the URL to the instance where you can check it, and it has enough users to force the first threshold.
> 
> URL: https://mattermost-server-pr-21666.test.mattermost.cloud/
> 
> Account Type	Username	Password
> Admin	sysadmin	Sys@dmin123
> User	user-1	User-1@123

gentle ping @annelieseklein

**Review by annelieseklein — APPROVED** [review]
LGTM

**Pull request merged**
