### PR TITLE
fix/MM-40381 : unified is not defined bug when recent used emoji is deleted

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
This possibly fixes the `unified not defined` bug in the recently used emoji section of emoji picker. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40381

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by esethna** [comment]
@hmhealey @Willyfrog I am really struggling with this crash if we can try to get it merged asap 🙏

**Review by hmhealey — CHANGES_REQUESTED** [review]
Zubair and I discussed making some changes to the `replaceAll` since we found that this might not fully fix the issue

**Comment by amyblais** [comment]
@Willyfrog @hmhealey Please help prioritize PR review if you can.

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
Waiting for E2E run to finish, will approve after I verify the report.
Manually tested and it looks good. Deleting recently used custom emoji no longer breaks the app.

**Review by Willyfrog — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @M-ZubairAhmed 
Tested, looks good to merge. 
In addition to manual testing, [E2E report ](https://automation-dashboard.vercel.app/cycles/d7d214b0-f197-44c6-bfe6-9a4a9e9aec0b)also looks good - no PR related failures.

**Pull request merged**
