### PR TITLE
[MM-45540] Fix channel header not displaying inline images (markdown)

### PR DESCRIPTION
**Pull request by mylonsuren**
#### Summary

Fixes issue where inline images would not appear in the channel header.

#### Ticket Link

[MM-45540](https://mattermost.atlassian.net/browse/MM-45540)

#### Screenshots

|  Before  |  After  |
|----|----|
| image | image |

#### Release Note

```release-note
Fixes bug where inline images would not appear in channel header.
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @mylonsuren 
few tests are failing 
see full report [here](https://automation-dashboard.vercel.app/cycles/09908e17-162b-4dba-846f-9602f3f8064c) 
Here are the names of ones that appear related to the PR changes:
- channel header is a markdown image
- channel header is a markdown image that is also a link
- Image with height smaller than 48px
- MM-T1447 Images below a min-width and min-height are posted in a container that is clickable

**Comment by mylonsuren** [comment]
> Thanks @mylonsuren few tests are failing see full report [here](https://automation-dashboard.vercel.app/cycles/09908e17-162b-4dba-846f-9602f3f8064c) Here are the names of ones that appear related to the PR changes:
> 
> * channel header is a markdown image
> * channel header is a markdown image that is also a link
> * Image with height smaller than 48px
> * MM-T1447 Images below a min-width and min-height are posted in a container that is clickable

@jgilliam17 I've made some changes to address the failing tests, should be good for another look.

**Review by jgilliam17 — APPROVED** [review]
Thanks @mylonsuren 
Tested, looks good to merge.
Verified, channel header is displaying inline image markdown.
E2E [report ](https://automation-dashboard.vercel.app/cycles/777bcb28-8f7c-4669-9af3-977c5287b41a)- no PR related failures.

**Pull request merged**
