### PR TITLE
MM-9843: improve semantics around Forward80To443

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Customers with Forward80To443 enabled but not actually listening on :443 would get an instance of Mattermost that ran but didn't listen on anything. This PR improves semantics around this setting, making the following changes:
* System console should automatically set to true (and disable) Forward80To443 if LetsEncrypt is true
* System console should prevent enabling Forward80To443 if not listening on 443.

It's accompanied by a corresponding server change: https://github.com/mattermost/mattermost-server/pull/8496

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-9843

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has server changes: https://github.com/mattermost/mattermost-server/pull/8496
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by lieut-data** [comment]
Jason, can I get your feedback on the proposed System Console changes? "Enable port 80 to 443" gets moved up, and there's new help text for same and for Let's Encrypt:

image

Additionally, as noted in the commit, boolean settings are now forced to be false when saved if their dependencies are not satisfied.

**Comment by jasonblais** [comment]
@lieut-data I think overall that sounds good, will just test the admin experience around those settings.

However, it seems neither setting is editable in the the test server right now (both are disabled). Perhaps because the server PR isn't merged yet?

image

**Comment by lieut-data** [comment]
@jasonblais, that's because the listen port is not :443 -- the thinking @crspeller and I discussed was to disable this feature unless Mattermost was configured to be listening on :443 in the first place. I added the help text in a bid to explain:

> ... This setting requires listening on port 443.

But perhaps that's not obvious enough? Would someone be looking to enable the feature and not have gotten to the point of listening on :443?

**Comment by jasonblais** [comment]
Got it, that makes sense. Propose we do something similar to the email batching setting, where the setting text is different when the setting is disabled (email batching is disabled if site URL isn't set).

Let me know your thoughts on the proposed texts below:

1) Forward port 80 to 443:
 - if NOT listening to port 443: `Forwards all insecure traffic from port 80 to secure port 443. Not recommended when using a proxy server.\n\nThe setting cannot be enabled until your server is listening on port 443, to prevent the Mattermost server from not starting.`
 - if listening to port 443: `Forwards all insecure traffic from port 80 to secure port 443. Not recommended when using a proxy server.`

2) Let's Encrypt:
 - if `Forward80To443` is set to FALSE: `Enable the automatic retreval of certificates from Let's Encrypt. The certificate will be retrieved when a client attempts to connect from a new domain. This will work with multiple domains.`
 - if `Forward80To443` is set to TRUE: `Enable the automatic retreval of certificates from Let's Encrypt. The certificate will be retrieved when a client attempts to connect from a new domain. This will work with multiple domains.\n\nLet's Encrypt cannot be enabled unless **Forward port 80 to 443** is set to true in **System Console > Configuration**.`

PS: 
 - `\n` represents a line break
 - `**...**` represents bolded text

**Comment by lieut-data** [comment]
@jasonblais, I like the proposed changes. Some minor counter-suggestions on text.

1) I feel like we should drop:
> , to prevent the Mattermost server from not starting.

as it's an obscure implementation detail. We /could/ make the server work despite this setting, but the crux is that we don't want to enable this feature unless we're listening on :443.

2) What if we (anchor) link to the `Forward port 80 to 443` setting in the Let's Encrypt help text? It seems a bit odd to reference an option on the same page as though it had to be navigated to be found?
> Let's Encrypt cannot be enabled unless **<Forward port 80 to 443>** is set to true.

Should we link `<listening>` in the help text to the `Listen Address` setting as well?

**Comment by jasonblais** [comment]
1. Fair enough.
2. Agree, if we can anchor to the setting, that would be better. And we can anchor `<listening>` as well, didn't actually realize the `Listen Address` setting was related (although it's obvious now that you say it)

**Comment by lieut-data** [comment]
Ok, here's the final text when enabled:

image
image

and when disabled:

image

image

**Comment by jasonblais** [comment]
One minor nit, can we change `<Forward port 80 to 443>` to `<Forward port 80 to 443 setting>` so it's clear it's a setting. 0/5 on this one.

Otherwise looks great to me 👍

**Comment by lieut-data** [comment]
Sounds good!

**Pull request merged**
