### PR TITLE
MM-31189 Revert New Messages toast PRs

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
Reverts https://github.com/mattermost/mattermost-webapp/pull/7028 and https://github.com/mattermost/mattermost-webapp/pull/5828 as requested due to some issues with the New Messages toast.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31189

#### Related Pull Requests
- https://github.com/mattermost/mattermost-webapp/pull/5828
- https://github.com/mattermost/mattermost-webapp/pull/7028

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thanks @hmhealey 
Seeing one small issue where the new message toast flashes for a brief moment when returning to channel where posts were previously marked as unread. See video.

https://user-images.githubusercontent.com/52937121/103948649-22c73180-5108-11eb-89bd-2086c6613e79.mov

**Review by Willyfrog — APPROVED** [review]
i've setup a 5.28 environment and seems that the behaviour seen by @jgilliam17 was already happening, since PM and UX will review the feature, I'd not block on that one

**Comment by amyblais** [comment]
@calebroseland @jgilliam17 Kind note to review this PR for today's v5.31 code freeze deadline.

**Review by jgilliam17 — APPROVED** [review]
Thank you @Willyfrog for checking on 5.28, I can also confirm it was an existing behavior. I'm ok with merging since this will be reevaluated by UX.
- Verified 1000px threshold for new message toast has been removed, toast present in all cases except when user is at the absolute bottom
- Verified when marking older posts as unread, new message toast appears immediately, except when user is at the bottom.

**Comment by hmhealey** [comment]
Thanks for checking on that, Guillermo. I assumed that would be the case since this was a straight revert without any conflicts to resolve, so that saves me from having to check myself.

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
