### PR TITLE
[MM-34331] Migrate 'components/call_button' and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by majidsajadi**
#### Summary

migrated call_batton to typescript.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/17260

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @majidsajadi!

**Review by nickmisasi — APPROVED** [review]
Thanks @majidsajadi!

**Comment by lindy65** [comment]
Thanks @devinbinnie - can you confirm that it's Channel membership that needs a smoke test?

**Comment by devinbinnie** [comment]
@lindy65 Looks like it's actually in the post box, if a plugin we use has a call method (ie. Zoom, Jitsi). Funny I thought we'd moved all those out to the top bar...

**Review by lindy65 — APPROVED** [review]
Thanks @majidsajadi - this will be tested after merge.

@devinbinnie - due to difficulties getting Zoom/Jitsi set up on spinmints, I'll defer QA on this PR and test after merge 👍

**Pull request merged**
