### PR TITLE
[MM-27261] fix: scrollbar click/drag in edit post modal

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
- Add scrollbar detection to `edit_post_modal`.
_Present in `create_post`/`create_comment`, to nudge `.post-body__actions` out of the way. 
Without this nudging, the scrollbar is covered by a div and is not interact-able._ 
- Fix cursor on hover of scrollbar, some browsers (e.g. Chrome on Mac OS) would oddly display `cursor: text`.
- Add scrollbar `width` detection to `create_post`, `create_comment`, and `edit_post_modal`
_The current static `right` offset is inconsistent in various OS's/browsers._ (Now vs Prev)
Screen Shot 2020-08-25 at 02 07 35
Screen Shot 2020-08-25 at 02 12 04

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-27261

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
LGTM :)

**Comment by amyblais** [comment]
@calebroseland Farhan and Jelena are off. Could another dev/QA review this?

**Review by asaadmahmood — APPROVED** [review]
The buttons shift now, which for me is not ideal. but think can taken in for now.

**Review by ogi-m — COMMENTED** [review]
@calebroseland One tiny issue - on Chrome and Desktop app (Windows), hovering the scroll bar shows the text selection cursor instead of the pointer (Firefox shows the pointer as expected).
This only repros on the PR, not seeing it on 5.27 or master. Could we fix that if it's related to this change or should we file that separately?

**Comment by calebroseland** [comment]
> @calebroseland One tiny issue - on Chrome and Desktop app (Windows), hovering the scroll bar shows the text selection cursor instead of the pointer (Firefox shows the pointer as expected).
> This only repros on the PR, not seeing it on 5.27 or master. Could we fix that if it's related to this change or should we file that separately?

This PR is just syncing the UX between `edit_post_modal` and `create_post`.

I think it's technically separate, but I'm sometimes a fan of the "as long as we're here" mentality.

This is what I'm seeing in Chrome, Mac OS on Daily:

**Comment by ogi-m** [comment]
Ah, you're right - I see it now in the textbox on 5.27 & master (I only looked at the edit post modal previously). 

Yes, I see the same thing in Chrome. Shouldn't it show the default cursor when dragging the scroll bar instead of the text cursor, like Firefox does?
This is what I see in Firefox:

scroll_ff

**Comment by asaadmahmood** [comment]
@ogi-m Yes, the cursor change looks weird, I would expect it to display the default one.

**Comment by calebroseland** [comment]
@asaadmahmood @ogi-m those cursor oddities should be fixed now. (And description updated.)

**Review by ogi-m — APPROVED** [review]
Thanks @calebroseland, LGTM 👍

**Pull request merged**
