### PR TITLE
E2E/Cypress:fixed cloud test cases

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Fixed Cloud test cases
`ui_and_api/notifications_spec.js`
`reply_notifications_spec.js`
`new_messages_toast_spec.js`

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Great, thanks @furqanmlk!

**Comment by metanerd** [comment]
Triggering via label looks like it is using an old api call to check for listing the reviews. GitHub API docs: https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls/#list-reviews-for-a-pull-request

It's not clear to me, how to retrieve it nowadays. I need to investigate a bit more.

**Review by metanerd — APPROVED** [review]
Thank you, @furqanmlk ! Sorry to have distracted a bit in your PR. Good stuff!

**Pull request merged**
