### PR TITLE
Initial storybook commit

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Add an initial skel for start building the storybook. Included some examples.

I think QA is not needed here in the sense is almost not touching the real code (just a small change related to how the color of the theme is applied to the badges) the rest of the code is just related to the storybook.

#### Ticket Link
[MM-17861](https://mattermost.atlassian.net/browse/MM-17861)

### CODE REVIEW

**Comment by jespino** [comment]
Has been in between the merge of the other branch, but I can check it, the necessary changes should be minimal

**Comment by jespino** [comment]
@reflog good catch, now is working, thanks for the heads up :)

**Comment by lindy65** [comment]
Thanks @jespino!

Can you give me more info on what to check for here: 

> (just a small change related to how the color of the theme is applied to the badges)

Also, is it possible to write unit tests and/or Cypress tests for storybook PRs?

**Comment by jespino** [comment]
@lindy65 Yes, it was a change about how the background color of the badges is defined. Before the change it was done through the all themeing approach (which is not working properly for the storybook) so I change it to use the new approach (css-variables). I is a look and feel change only that Is quite hard to test and is not tested anyway in any other case. The "QA" test should be verify that the color of the badges change accordingly to the theming changes, with that I think we are safe.

About Unit/Cypress test of the storybooks, we could do that for sure, but I think would be a pretty high investment in adding tests to something that is going to be documentation only.

**Comment by lindy65** [comment]
Thanks @jespino 👍 

Can you give me a list of areas to check the badges or is it across the app?

Thanks for explanation re unit/cypress tests - agree - not necessary for documentation only.

**Comment by jespino** [comment]
@lindy65 it is across the app but is affecting everything in the same way using the same CSS, so it should behave in the same way in every instance.

**Comment by lindy65** [comment]
Perfect, thanks @jespino! I'll test soonest!

**Comment by lindy65** [comment]
Thanks @jespino 

I tested the background colours of BOT badges when changing themes

For the "Mattermost" and "Organization" themes, the background of the BOT badges is a light grey when not hovered over 

image

and a darker grey when hovered over

image

For the "Mattermost Dark" and "Windows Dark" themes, the background of the BOT badge is a darker grey when not hovered over

image

and a lighter grey when hovered over

image

Let me know if you think there are other badges you think I should test, otherwise this looks good to me!

**Comment by jespino** [comment]
No, If that is right, I think we are good to go :)

**Pull request merged**
