### PR TITLE
[MM-44169]: Stay on Threads view when switching teams

### PR DESCRIPTION
**Pull request by kyeongsoosoo**
#### Summary

When switching teams, check `previousTeamLastViewedType`.
If this value is set to `threads`, then `lastChannelPath` is set to threads, too. 

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/20207

#### Related Pull Requests

- https://github.com/mattermost/mattermost-webapp/pull/10255

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by esethna — APPROVED** [review]
Thanks @kyeongsoosoo!

**Comment by hmhealey** [comment]
@esethna Playing with this a bit on the test server, I'm ending up in that situation I was worried about where you get sort of stuck in Threads view as soon as you've switched teams with it open once. After switching away from a team with Threads open once, it seems like I'm always sent back to Threads view when switching teams after that because either I swapped from a team with Threads view open (keeping me in that view) or I switched to a team which had it open. Maybe that'll happen less often in practice because I'd have more channels and be less likely to switch back and forth between teams repeatedly, but it definitely feels weird to me as-designed.

**Review by hmhealey — APPROVED** [review]
The code for this looks good though. Thanks, @kyeongsoosoo!

**Comment by esethna** [comment]
> Maybe that'll happen less often in practice because I'd have more channels and be less likely to switch back and forth between teams repeatedly, but it definitely feels weird to me as-designed.

Ya thanks for the feedback. I feel the same on the test server but I'd like to use it in production to see if it's an issue in real world use. If so we can always revert this PR or adapt accordingly

**Review by koox00 — APPROVED** [review]

**Comment by esethna** [comment]
@jgilliam17 for QA review please

**Comment by jgilliam17** [comment]
Thanks @kyeongsoosoo 
Tested, looks good to merge - pending e2es - re-running [here](https://automation-dashboard.vercel.app/cycles/11475d70-0b57-4214-9acb-e021fa7b07ac) last report had significant number of specs skipped
- Verified user stays on Threads when switching teams

**Comment by jgilliam17** [comment]
Latest [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/211677-81a6dc1-onprem-ent-webapp-pr-10477-mm-ee-test:81a6dc1/mochawesome.html)- no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Comment by esethna** [comment]
Thanks for this PR @kyeongsoosoo!

**Pull request merged**
