### PR TITLE
ABC-193: Add webapp commit hash to "about" modal

### PR DESCRIPTION
**Pull request by ccbrown**
#### Summary
screen shot 2018-02-07 at 6 17 10 pm

#### Ticket Link
https://mattermost.atlassian.net/browse/ABC-193

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@ccbrown Looks like the build failed,

**Comment by ccbrown** [comment]
@jasonblais fixed.

**Comment by jasonblais** [comment]
Tested at different screen widths and zoom levels.

@ccbrown Only question is whether it's obvious the `Build Hash` and `EE Build Hash` refer to the server and enterprise branches?

**Comment by ccbrown** [comment]
@jasonblais 🤷‍♂️  I think it's at least more obvious than it was before now that the webapp hash is also there. Being labeled "webapp", it kinda implies that the others *aren't* webapp.

**Pull request merged**
