### PR TITLE
[MM-29310] Migrate string-refs to functional ones: this.refs.video 

### PR DESCRIPTION
**Pull request by ShajithaMohammed**
#### Summary
change this.refs into React.createRef

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15799
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29310

#### Related Pull Requests
#5753

### CODE REVIEW

**Review by nevyangelova — CHANGES_REQUESTED** [review]
Is there a reason why we are not removing the `source` ref in this PR? 

When this is done remember to remove the `eslint-ignore` line :P

**Comment by ShajithaMohammed** [comment]
> Is there a reason why we are not removing the `source` ref in this PR?
> 
> When this is done remember to remove the `eslint-ignore` line :P

Hi @nevyangelova . Thanks for the feedback. Is migrating `source` ref in scope for this ticket - mattermost/mattermost-server#15799 

Also, As I see multiple ticket in place as a campaign to migrate string refs to functionals ones, I assume `source` ref will be addressed as part of some other ticket. Can you please double check?

**Comment by nevyangelova** [comment]
@ShajithaMohammed they are, I just thought that it made sense to go about it on a file basis since its a simple change :P and we can link both tickets in the PR. But its ok to ship this as it is  as well. Up to you 🎉

**Comment by Willyfrog** [comment]
Hi there @ShajithaMohammed 

First of all: thanks for taking the time to fix the issue

> Is migrating `source` ref in scope for this ticket - mattermost/mattermost-server#15799 

It is in scope, tickets are created by file, and although it references the first ref (mostly due to using automation tools) but in the ticket it is specified:

> 5. Look for any other this.refs used in the file and repeat from the begining.

So it is not going to appear in any other issue as we are expecting to remove any string refs in any file in one go.

**Review by nevyangelova — APPROVED** [review]
Thanks 🎉

**Review by sudheerDev — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @ShajithaMohammed 
Tested, looks good to merge.
- Verified video file previews, scrolling through multiple file preview, downloading etc.

**Pull request merged**
