### PR TITLE
[MM-35669] - Align channel globe icons with sidebar navigator icons

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
this PR aligns the channel sidebar icons with the navigator icons, needed to increase the padding on the left to achieve the result.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35669

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Comment by matthewbirtch** [comment]
Thanks @nevyangelova. To my eyes it looks like a couple of adjustments need to be made:

1. The channel icons need to bump to the left 1px (although the avatars look properly aligned)
image

2. Can we reduce the right-margin on the mention badge by 2px so that a 1-digit mention feels aligned?
3. This is outside of the scope of this one, but now the hamburger icon feels really misaligned. We should maybe look at a follow-up ticket to fix that, but we can leave it out of this PR

**Review by hmhealey — APPROVED** [review]

**Comment by nevyangelova** [comment]
@matthewbirtch fixed. I moved the hamburger menu to match the outer edge of the + button the same way the current user avatar matches the outer edge of the filter button. Let me know if you want it positioned differently.

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified icons are aligned in relation to sidebar navigator icons, including the hamburger menu icon.

**Comment by matthewbirtch** [comment]
> @matthewbirtch fixed. I moved the hamburger menu to match the outer edge of the + button the same way the current user avatar matches the outer edge of the filter button. Let me know if you want it positioned differently.

@nevyangelova For the hamburger icon, I was thinking it would be better if it was aligned horizontally with the center of the other icons like the below:
Screen Shot 2021-05-27 at 12 14 10 PM

**Comment by nevyangelova** [comment]
@matthewbirtch updated

**Review by matthewbirtch — APPROVED** [review]
Looks good @nevyangelova

**Comment by matthewbirtch** [comment]
@hanzei I see you requested my review on this PR again. I already provided my review, but was there something specific you wanted me to look at?

**Comment by hanzei** [comment]
Sorry @matthewbirtch, I didn't noticed that you already approved the PR. So no, nothing specific to look for.

**Pull request merged**
