### PR TITLE
MM-21863: fix bool defaults for interactive dialog

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
The `default` property of interactive dialog elements is, unfortunately, only expressable as a string. Address this in the short term by handling a string value and correctly distinguishing `"true"` from `"false"` case insensitively.

A future improvement to allow truly boolean default values in the payload is logged as https://mattermost.atlassian.net/browse/MM-21713.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-21683

#### Related Pull Requests
- https://github.com/mattermost/mattermost-mobile/pull/3793
- https://github.com/mattermost/mattermost-plugin-demo/pull/83

### CODE REVIEW

**Comment by prapti** [comment]
@lieut-data is this set of changes supposed to not stringify the boolean data like it was doing before so that selecting true/false from the mobile app will now send data as `true`/`false` and not "true"/"false"?

**Comment by prapti** [comment]
@lieut-data The booleans are no longer stringified, but the boolean options _someboolean_default_false_ and _someboolean_default_true_ do not accept false as choices (someboolean_default_false_optional and someboolean_default_true_optional do accept false). Will it be ok to address this within this PR?

**Comment by lieut-data** [comment]
@prapti, I /think/ that's by design: only the `_optional` elements allow both `false` and `true`, otherwise the field /must/ be `true`. At least, I think that's a reasonable interpretation of required, since there's currently not a way to "choose nothing", and even then, it's likely that `true` was the desired option to require. I see this being used in a terms-of-service flow, where the user must agree before they can submit.

Thoughts?

**Comment by prapti** [comment]
@lieut-data That sort of makes sense, but that particular case is covered by the first boolean choice in the list, _someboolean_, which is not optional and has to be true to be able to submit the form. I think it's ok to leave it as is, but might be confusing for someone who runs into it esp. because the help text says "Pick a choice". It might be helpful to update the text that they have to be set to true?

**Comment by lieut-data** [comment]
@prapti, agreed this could be confusing. The overlap was intentional, because of the string nature of the defaults, in that the demo plugin lets us verify what happens without an explicit default, with an explicit default of `"true"` and an explicit default of `"false"`. The text is also fully customizable by the author of the interactive dialog -- i.e. the `Pick a choice`  is defined by https://github.com/mattermost/mattermost-plugin-demo/pull/83/files#diff-ae7d00408bc3cf4a08823e84a6065b03R402.

I'd inclined to consider the webapp changes complete, since everything else is up to the author of the interactive dialog. We might also want to tweak the help text on the demo plugin to facilitate easier testing -- feel free to suggest changes there.

**Pull request merged**
