### PR TITLE
[MM-42636] fix disabled dot menu clicking 

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR fixes an issue where the shortcut additions in the post dot menu had disabled the ability to click the menu item with the mouse.

QA should verify that both the shortcut and clicking activate the desired response.

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by jfrerich** [comment]
@jwilander I've pulled this out of the other larger PR. If we can get this through dev review and QA, we could hit the daily release for tomorrow. @DHaussermann, thanks for checking in so soon to the PR :) Let me know if you find andy issues.

**Review by jwilander — APPROVED** [review]
Thanks @jfrerich !

**Review by crspeller — APPROVED** [review]

**Comment by DHaussermann** [comment]
Testing completed.

- Issue B. for Jira ticker MM-42592 seems completely solved. The `...` menu only open when I actually click it. This solves the confusing flakiness you would see when sliding the cursor down a set of posts   
- Things such as `...` menu showing in an open state when you mouse over to a new pop-over then return are consistent with previous v6.5.0 Webapp
- Regression tested cases where 2 post pop-overs are visible at once and edge cases where it's possible to draw a popover on top of an expanded menu. All are consistent with previous v6.5.0 Webapp 
- Tested in both states with and without the green "something is new" dot (which seemed to trigger the issue before this PR)  
- Tested in main and RHS threads
- No "ghosting" observed where visual elements remain visible once all post options are closed out. (Not sure if the root cause was related)   
- Sanity checked ephemeral and system posts as a precaution no issues found. 

@jfrerich  1 thing to look at here that is likely outside the scope of the Actions Changes. In the something is new box - The `x` and the `Opt out of these tips` link are non functional. When I click them I see 1 web request got off which returns a 200 response but, noting happens. (The `Got It` button works fine.) Is there any chance this is specific to the feature?
image

**Comment by jfrerich** [comment]
@DHaussermann, outside of the `x` and `Opt out of these tips` not working, does that pass for merging?

**Comment by DHaussermann** [comment]
Correct @jfrerich 
The issue is resolved and all other minor edge cases are pre-existing. Aside from the `x` and the link it fine to merge
LGTM!

I just left the approval off because I wasn't sure if that was in scope.

**Comment by jfrerich** [comment]
@DHaussermann, I created a ticker for the `x` and link issue 
https://mattermost.atlassian.net/browse/MM-42769

**Comment by jfrerich** [comment]
If you approve, I'll merge this and move to the next issue.

**Review by DHaussermann — APPROVED** [review]
Testing passed as per comment above ☝️

**Pull request merged**
