### PR TITLE
Removing some unused files and components

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Removing some unused files and components

#### Ticket Link
None

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by jespino** [comment]
@AGMETEOR @nickmisasi I added you to the review to confirm about the `user_limit_modal` that looks like is no longer used, so I guess we can remove that. This is only part of the files that are unused, I have other extra files that I going to add in other PR.

**Comment by nickmisasi** [comment]
> @AGMETEOR @nickmisasi I added you to the review to confirm about the `user_limit_modal` that looks like is no longer used, so I guess we can remove that. This is only part of the files that are unused, I have other extra files that I going to add in other PR.

We've got no plans for this for the time being so should be good to remove. Worst case we can pull it back in from the git history.

**Review by nickmisasi — APPROVED** [review]

**Comment by nickmisasi** [comment]
> @AGMETEOR @nickmisasi I added you to the review to confirm about the `user_limit_modal` that looks like is no longer used, so I guess we can remove that. This is only part of the files that are unused, I have other extra files that I going to add in other PR.

@jespino Withdrawing my previous comment - this model should still be in use by legacy installations on our free tier. We'll need this component until Feb 2022, when those grandfathered installations are moved to a paid plan.

**Comment by AGMETEOR** [comment]
> @nickmisasi but where is this used?

Looks like it was removed from main_menu and wasn't added to the global header menu. I have failed to locate which PR removed it. But, Nick is right we still needed to show it for legacy cloud plan installations.

**Review by AGMETEOR — APPROVED** [review]
LGTM. Maybe we shall create a new ticket to temporarily add the user_limit_modal again. That'll be @marianunez call.

**Comment by marianunez** [comment]
> LGTM. Maybe we shall create a new ticket to temporarily add the user_limit_modal again. That'll be @marianunez call.

This used to be called here: https://github.com/mattermost/mattermost-webapp/blob/f68d8dd0a335b05eada0cbe8c36f61dfbdfab798/components/invitation_modal/invitation_modal.jsx#L327 but was removed as part of a revamp of the invitation modal here https://github.com/mattermost/mattermost-webapp/pull/9358

This user limit modal is no longer needed as in server side it is handling this check and presented the error in the new invite modal. We should be good to permanently remove `user_limit_modal`.

**Review by M-ZubairAhmed — APPROVED** [review]
🆗  It looks good to me. Thank you

**Review by hmhealey — APPROVED** [review]
Well now I'm annoyed that I wasted some time in trying to migrate ConfirmNotifyAdminModal to the ModalController a few weeks back 😛

**Comment by jespino** [comment]
@hmhealey do you think we need any QA on this? I think we don't because we are mainly removing code, and if something would break, should do it at compilation time, right?

**Comment by jespino** [comment]
@jgilliam17 do you mind to run the e2e tests over this branch, I think that should be enough "smoke testing" to ensure that we are not breaking anything with this changes.

**Comment by jgilliam17** [comment]
Thanks @jespino E2Es running here https://automation-dashboard.vercel.app/cycles/1342b5d3-6823-4231-9b71-9dbe1e46dc0f
I'll post the report when ready.

**Comment by jespino** [comment]
@jgilliam17 thanks!

**Comment by jgilliam17** [comment]
E2E results https://mattermost-cypress-report.s3.amazonaws.com/90515-d88f783-ee-ent-webapp-pr-9419-mm-ee-test:d88f783/mochawesome.html
I'll re-run after update, some of these failures look familiar just want to rule out as already fixed.

**Comment by jgilliam17** [comment]
@jespino here's the new report https://automation-dashboard.vercel.app/cycles/ba839b68-7253-4bcb-b180-f9dd5e29ac40
similar failures, re-tested manually and not able to reproduce. Looks good to merge.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
