### PR TITLE
Fixes: "Write Webapp E2E with Cypress: "MM-T1255 CTRL/CMD+UP or DOWN no action on draft post".

### PR DESCRIPTION
**Pull request by ZeeshanAmjad0495**
#### Summary
   Added a Cypress end to end test to check that after typing some text in the post box there is no action upon pressing 
   CTRL/CMD + UP or DOWN except the regular actions of a text box.

#### Ticket Link
   Fixes https://github.com/mattermost/mattermost-server/issues/18709

#### Release Note 
 ```
  NONE
 ```

### CODE REVIEW

**Comment by musabsohail** [comment]
@ZeeshanAmjad0495 Please see the failing pipeline.

**Comment by ZeeshanAmjad0495** [comment]
> Hi @ZeeshanAmjad0495
> 
> I am sorry, it’s still failing for me after your changes, it is different error though.
> 
> image

@furqanmlk please try now the error has been fixed in the last commit.

**Comment by saturninoabril** [comment]
> MM-T1265 UP - System message does not open for edit; opens previous regular message

@ZeeshanAmjad0495 Please open in a separate PR.

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @ZeeshanAmjad0495

**Pull request merged**
