### PR TITLE
MM-13064 Improving the keyboard usability of the emoji picker.

### PR DESCRIPTION
**Pull request by thnat1234**
#### Summary
Improve the keyboard usability of the emoji picker

#### Description
This PR improves keyboard usability between the emoji picker and the search bar. It also recovers basic functionality for work with text in the search bar using the keyboard.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/11950

### CODE REVIEW

**Comment by adamjclarkson** [comment]
Hi @thnat1234,

Thanks for the work you've done on this ticket. Looking great! Also a great suggestion for us to think harder about the proper solution from an accessibility standpoint. Using TAB might be more in line with the standard (referring to your comments here: https://github.com/mattermost/mattermost-server/issues/11950) 

However I think the work you've done here is great and is an improvement on what we've currently got so let's keep moving it forward. 

There are a couple small things I noticed that we should tweak. In fact these are changes to the original spec not your implementation. 

1. The original spec says "If the right arrow key is pressed when the cursor is at the end of the word in the text box, move the selection to the right in the emoji picker, otherwise move the cursor to the right in the text". Conversely, if the left arrow key is pressed when the cursor is highlighting the first emoji in the top left of the emoji search results, the cursor should back into the text box to the end of the string. 

2. If the cursor is highlighting an emoji in the top row of the search results, the up arrow should move the cursor back into the text box to the end of the string (currently it move the cursor into the text box to the beginning of the string).

3. if the cursor is at the beginning of the string, the down arrow should move the cursor to the end of the string (presently it moves the cursor into the emoji search results field). 

cc @esethna

**Comment by thnat1234** [comment]
Hi @adamjclarkson ,

I'm happy you considered my suggestions and I'll be happy if they will be considered for future tickets. 

I fixed the mentioned inconsistencies above so now it should work as expected.  
Could you please review it?

Thanks, 
Tomas

**Comment by thnat1234** [comment]
Hi @adamjclarkson ,

shift + down/up key functionality is up and hopefully, it will be good to go.

Thanks,
Tomas

**Comment by hmhealey** [comment]
Updating the branch to the latest master to hopefully fix the test server

**Comment by jasonblais** [comment]
Hi @thnat1234, thanks for your contribution! Let us know if you have any questions about the feedback above, we'd be happy to clarify :)

**Comment by thnat1234** [comment]
Hi, 
I'm sorry for inactivity for the last month but I was on holiday and out of computer access. Also, until the end of January, I have a lot of final exams in school. 

Back to PR. As far as I remember, I struggled with the E2E tests for the implemented functionality because I need to learn how to do it, so I will need more time for that. 

Thanks for understanding, 
Tomas

**Comment by jasonblais** [comment]
Hey @thnat1234, thanks for following up! Totally understand, we can follow back in February after your final exams over :) Good luck with them!

cc @hanzei

**Comment by jasonblais** [comment]
Also, if you have any questions as you start working on E2E tests, please don't hesitate to let us know.

**Comment by cpanato** [comment]
will remove this test server since this PR is stale

**Comment by jasonblais** [comment]
@hanzei or @saturninoabril would you be open to helping @thnat1234 with adding E2E tests?

**Comment by saturninoabril** [comment]
Sure @jasonblais, will look into it.

**Comment by hmhealey** [comment]
@saturninoabril Are you still looking at this?

**Comment by saturninoabril** [comment]
I just got back 100% online starting today.  Past 2 weeks were on a travel.

I'll look into this after team release testing, probably later this week.

**Comment by saturninoabril** [comment]
@hmhealey @srkgupta Added Cypress tests only on the first 2 cases. For other test cases, down arrow key and ctrl/cmd/shift in combination with other keys didn't work.  I recommend to deal with it on separate PR as I find it as potentially a Cypress issue. Ticket filed - https://mattermost.atlassian.net/browse/MM-23125

@srkgupta I may be wrong on my observation.  Feel free to try and let me know your findings, thanks

**Comment by stevemudie** [comment]
I've tested this here and it looks good overall. I was wondering though if there's any concern with the very faint highlight/shadow over the currently selected emoji? The emoji you're on is visible at the bottom of course but if a user is focusing on where the 'cursor' is at the moment then might they be more interested with what's up/down or next to the one they are on?

Highlight shadow

**Comment by esethna** [comment]
@stevemudie agree it's very hard to see, can you create a separate improvement ticket to darken the hover effect slightly (maybe 30%?)

**Comment by esethna** [comment]
If all else is good can you please approve the PR so it can be merged?

**Comment by hmhealey** [comment]
@srkgupta Is there anything else you still want addressed with this, or is it good to go?

**Pull request merged**
