### PR TITLE
MM-3736 Change HTML messages to Markdown style

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary
For removing messages with html tags.

My policy for fixing this issue is noted in the following.
https://github.com/mattermost/mattermost-server/issues/6174#issuecomment-403213921

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-3736
[GH-6174](https://github.com/mattermost/mattermost-server/issues/6174)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@kaakaa many thanks for your contribution! When translating strings, is Markdown okay/easy to translate in your experience compared to HTML?

**Comment by kaakaa** [comment]
@jasonblais 
Compared to HTML style that markup symbol is character(e.g.: `a`, `b`, `strong`...), markdown style is easy to recognize their markup symbol.
So I think that tranlation of markdown messages is easier to than HTML. Especially in anchor tags.

But markdown style generates some contexts.
In the first time to translate messages, they may not understand that it is markdown.

**Comment by kaakaa** [comment]
Hmm....I agree with avoiding Markdown as well.
It makes no difference for users.

But now there are messages with markdown and html. So I think that It had better unified to either html or markdown. I prefer markdown styles.
However, if someone don’t want to change to markdown style, I agree with their thought and closing PR about this issue.

That is my thought :smiley:

**Comment by jasonblais** [comment]
@kaakaa 

> So I think that It had better unified to either html or markdown. I prefer markdown styles.

I absolutely agree markdown style is preferred. So I wouldn't close this PR.

That said, https://github.com/mattermost/mattermost-server/pull/8903 didn't use Markdown style for the en.json strings. Is this an option?

**Comment by kaakaa** [comment]
@jasonblais 
Yes, I think that it is an option.
Most messages in mattermost-server don't require markup. The only exception is `<strong>` that fixed by mattermost/mattermost-server#8903.
And when considering only the translation work, since `[[{{.VAR}}]]` is not a part to be translated, I think that it is no problem as it is.

Of course, we can use Markdown parser (e.g.: [russross/blackfriday](https://github.com/russross/blackfriday)) for messages in mattermost-server with the same way as webapp. But that way looks overdoing, because most messages don't require markup.

Besides that, it makes sense that we use `**{{.VAR}}**` like markdown style instead of `[[{{.VAR}}]]`. This way can be achieved by a little work.

**Comment by kaakaa** [comment]
oh...I'm sorry, my answer was not clear.

Yes, it's my suggestion.
If you think that server messages must be markdown style, I can do that.
But I think that server messages have no problem as it is.

**Comment by jasonblais** [comment]
@kaakaa I agree. I'll queue this for UX review for testing next.

QA team: this PR updates 23 strings to remove HTML tags, or replace HTML with Markdown. This is to help improve translations experience. https://github.com/mattermost/mattermost-webapp/pull/1453/files#diff-8aed887c744b7eb6f40c0a268ae06e7b

It would be good to verify these strings are still properly formatted in the UI. Please help verify that?

**Comment by lindy65** [comment]
@kaakaa @jasonblais 

> QA team: this PR updates 23 strings to remove HTML tags, or replace HTML with Markdown. This is to help improve translations experience. https://github.com/mattermost/mattermost-webapp/pull/1453/files#diff-8aed887c744b7eb6f40c0a268ae06e7b

Review steps:
I added a licence to the spinmint to access enterprise features and checked that all strings in the above PR are correct in the System Console.

Comments:
1. Line 501 `Would like to help with translations?` should read `Would you like to help with translations?` (Not sure whether it's necessary to fix here as there is [this ticket](https://mattermost.atlassian.net/browse/MM-11197) which has fixed the issue in v5.2
2. The comment, `AD/LDAP is an enterprise feature` on `AD/LDAP` screen has been removed as intended.
3. Checked websocket disconnect message, Town Square and Off-Topic channels "beginning of channel messages" in the app.

Looks good to me!

**Comment by jasonblais** [comment]
Thanks Lindy!

@kaakaa Can you help rebase as that should resolve 1. If so, I'll queue for dev review next.

**Comment by kaakaa** [comment]
Thanks Lindy and Jason!

@jasonblais 
I've rebased this branch.
However, since new message is html style, it isn't rendered correctly.


I have worked on [additional work for fixing this problem](https://github.com/mattermost/mattermost-webapp/pull/1453/commits/cb7f5ec1c8df64b7ebf5fa978a907479e8c52507) and now that message is rendered correctly. If you don't like this change, please let me know.

**Comment by jasonblais** [comment]
@kaakaa Your change from HTML to Markdown looks good to me 👍

**Comment by jasonblais** [comment]
@kaakaa we're you going to push the change you mentioned in https://github.com/mattermost/mattermost-webapp/pull/1453#issuecomment-408125500 to this branch?

**Comment by kaakaa** [comment]
@jasonblais  Oh...sorry for my unclear comment, I had already pushed it on this branch.
Now, I've rebased for resolving conflicts, so this PR is ready for review if ci has no error.

**Pull request merged**
