### PR TITLE
[MM-28061] Cloud Telemetry for Invite Members modal

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Cloud Telemetry for Invite Members modal

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28061

### CODE REVIEW

**Review by Adovenmuehle — APPROVED** [review]
LGTM

**Review by marianunez — APPROVED** [review]
LGTM

**Review by nickmisasi — APPROVED** [review]
LGTM

**Comment by marianunez** [comment]
@devinbinnie gentle ping to cherry-pick to `cloud-beta`

**Pull request merged**
