### PR TITLE
Add ellipsis to channel suggestions and channel selector in forms and interactive dialogs

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
On interactive dialogs, the purpose of the channel was always showing, and when too big, it would create bad UX (see original ticket).

On channel suggestion, the experience was not so bad, but when you had a channel with a too big name it would just stop showing at one of the ends of the box.

Now for both cases we use ellipsis.

Disclaimer: The color of the ellipsis is the one from the first element (opaque black). This may feel weird with other elements of the suggestion (lighter color text, like the one of the channel name or purpose).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35927

#### Related Pull Requests
None

#### Screenshots
Screenshot from 2021-06-15 16-30-05
Screenshot from 2021-06-15 16-30-38

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — COMMENTED** [review]
Is there a way to change the  color of the ellipsis ?

**Comment by matthewbirtch** [comment]
> Is there a way to change the color of the ellipsis ?

Agree with @hanzei. It would be best of the ellipsis matched the color of the text it sits next to (see screenshot below)

Screen Shot 2021-06-16 at 9 58 50 AM

Other than that, I think it's good to go

**Review by catalintomai — APPROVED** [review]

**Comment by larkox** [comment]
Changing the color of the ellipsis seems challenging at least. The idea is that what controls the ellipsis is the container div, and takes the color out of the container. Since we have inside the container several different colors, we never know which color the ellipsis should be, and as far as I have seen there doesn't seem to be any solution for that in CSS.

Another solution is to remove the ellipsis, and just have the text truncated.

**Comment by matthewbirtch** [comment]
> Changing the color of the ellipsis seems challenging at least. The idea is that what controls the ellipsis is the container div, and takes the color out of the container. Since we have inside the container several different colors, we never know which color the ellipsis should be, and as far as I have seen there doesn't seem to be any solution for that in CSS.
> 
> Another solution is to remove the ellipsis, and just have the text truncated.

@larkox I think the solution you have is better than not having an ellipsis at all. Maybe we could just use the reduced opacity on the ellipsis always? I think that might work better

**Comment by larkox** [comment]
I did a huge refactoring to simplify the styles. Adding @hmhealey also as a reviewer since I am touching several parts of the webapp.

**Comment by larkox** [comment]
Also, I expect several tests and e2e test to fail. I will fix them once the refactoring is accepted.

**Comment by larkox** [comment]
@matthewbirtch I updated the pr, and all the suggestions should now be able to add ellipsis. The locations are:
- Add user to channel modal (profile popover, add to channel)
- User and channel mentions
- User and channel search
- User and channel select on Interactive dialogs
- Channel switcher

**Comment by matthewbirtch** [comment]
@larkox it looks like the test server failed

**Comment by cpanato** [comment]
looks like a real test failure, maybe need to update the snapshots
```
Snapshot name: `components/suggestion/search_channel_suggestion should match snapshot, isSelection is false 1`

- Snapshot  - 15
+ Received  + 13

  <div
-   className="search-autocomplete__item"
+   className="suggestion-list__item"
    onClick={[Function]}
    onMouseMove={[Function]}
    role="button"
    tabIndex={-1}
  >
    <span
-     className="search-autocomplete__name"
-     data-testid="listItem"
+     className="suggestion-list__icon suggestion-list__icon--large"
    >
-     <div
-       className="search-autocomplete__icon"
-     >
-       <i
-         className="icon light icon--standard icon--no-spacing icon-globe"
-       />
-     </div>
+     <i
+       className="icon icon--standard icon--no-spacing icon-globe"
+     />
+   </span>
+   <div
+     className="suggestion-list__ellipsis"
+   >
      <span
-       className="ml-3"
+       className="suggestion-list__main"
      >
        name
      </span>
      <span
-       className="ml-2 light"
+       className="ml-2"
      >
-       ~
-       DN
+       ~DN
      </span>
-   </span>
+   </div>
  </div>
    at Object.<anonymous> (/root/mattermost/mattermost-webapp/components/suggestion/search_channel_suggestion/search_channel_suggestion.test.tsx:38:25)
    at Object.asyncJestTest (/root/mattermost/mattermost-webapp/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
    at /root/mattermost/mattermost-webapp/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (/root/mattermost/mattermost-webapp/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /root/mattermost/mattermost-webapp/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

9 tests fail: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/39738/workflows/7be4b412-1f20-49e7-ac49-1fd5b1a962f5/jobs/271026/tests

**Review by matthewbirtch — APPROVED** [review]
Looks good now @larkox!

**Review by hmhealey — APPROVED** [review]
The code looks good to me. I didn't realize that TImezoneProvider was no longer used, so it's nice to clean that up as well.

I did a quick test on the test server of the different autocompletes (post textbox, search box, quick switcher, add to channel), and they all seemed to be working

**Review by DHaussermann — APPROVED** [review]
Tested and passed.
- Tested various cases of long and short channel name with long and short purpose
- Purpose is truncated with ellipses as expected when purpose is too long
- Tested modal in web and in Mobile web view
- Regression tested other areas where channel provider is used - no impact
- No issues found  

LGTM!
Will test again if dev review requests changes.

**Comment by larkox** [comment]
@hanzei @catalintomai Tests fixed. If I have your OK, we can merge.
@hmhealey I stripped off also the team switcher, since it is not being used (the map state to props function was directly disabling it)

**Review by hanzei — COMMENTED** [review]
LGTM, thanks for the cleanup :+1:

**Review by hanzei — APPROVED** [review]
LGTM, thanks for the cleanup :+1:

**Comment by larkox** [comment]
This shouldn't need to be cherrypicked, since it was merged into the cloud branch during the merge at commit 8ca7448cf86b112ac49253dc923b8107aad1b5fb

**Comment by larkox** [comment]
@amyblais :point_up:

**Pull request merged**
