### PR TITLE
Cypress/E2E Maintenance: Fix failing tests

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- Updated tests to new behavior.
- Renamed onboarding function.

#### Ticket Link
NA

#### Screenshots
Screen Shot 2021-07-19 at 10 27 28 AM
Screen Shot 2021-07-19 at 10 32 42 AM
Screen Shot 2021-07-19 at 1 23 52 PM
Screen Shot 2021-07-19 at 6 24 33 PM
Screen Shot 2021-07-19 at 6 27 10 PM
Screen Shot 2021-07-19 at 6 41 44 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by josephbaylon** [comment]
@metanerd Please look into the aws failure, something about missing param. Thanks!

**Comment by josephbaylon** [comment]
Looks like the aws issue fixed itself.

**Review by saturninoabril — APPROVED** [review]
Nice, thanks @josephbaylon!

**Comment by saturninoabril** [comment]
I'm merging this now since I believed FM is out of office.

**Pull request merged**
