### PR TITLE
Update WebApp dependencies to latest

### PR DESCRIPTION
**Pull request by GuyKh**
#### Summary
Update project dependency to latest:
```
 @formatjs/intl-pluralrules                   3.2.3  →    3.4.8
 @formatjs/intl-relativetimeformat            6.2.3  →    7.2.8
 bootstrap                                    3.4.1  →    4.5.2
 highlight.js                                10.1.2  →   10.2.1
 jasny-bootstrap                              3.1.3  →    4.0.0
 katex                                       0.11.1  →   0.12.0
 localforage                                  1.7.3  →    1.9.0
 localforage-observable                       2.0.1  →    2.1.1
 pdfjs-dist                                 2.1.266  →  2.5.207
 prettier                                     2.0.5  →    2.1.2
 react-hot-loader                           4.12.21  →   4.13.0
 react-inlinesvg                              1.2.0  →    2.1.1
 react-intl                                   5.3.2  →    5.8.4
 react-overlays                               1.2.0  →    4.1.0
 react-select                                 2.4.4  →    3.1.0
 redux-persist                               4.10.2  →    6.0.0
 superagent                                   5.2.2  →    6.1.0
 tinycolor2                                   1.4.1  →    1.4.2
 typescript                                   3.9.7  →    4.0.3
 @babel/cli                                  7.10.5  →   7.11.6
 @babel/core                                 7.10.5  →   7.11.6
 @babel/plugin-proposal-object-rest-spread   7.10.4  →   7.11.0
 @babel/preset-env                           7.10.4  →   7.11.5
 @storybook/addon-actions                    5.3.19  →   6.0.22
 @storybook/addon-knobs                      5.3.19  →   6.0.22
 @storybook/addon-links                      5.3.19  →   6.0.22
 @storybook/addon-notes                      5.3.19  →   5.3.21
 @storybook/addons                           5.3.19  →   6.0.22
 @storybook/react                            5.3.19  →   6.0.22
 @testing-library/react                      10.4.9  →   11.0.4
 @types/enzyme                               3.10.5  →   3.10.7
 @types/history                               4.7.7  →    4.7.8
 @types/jest                                26.0.12  →  26.0.14
 @types/marked                                0.7.4  →    1.1.0
 @types/node                                14.0.23  →  14.11.2
 @types/react-bootstrap                     0.32.22  →  0.32.24
 @types/react-select                         3.0.19  →   3.0.21
 @typescript-eslint/eslint-plugin             3.6.1  →    4.3.0
 @typescript-eslint/parser                    3.6.1  →    4.3.0
 babel-jest                                  26.1.0  →   26.3.0
 babel-plugin-typescript-to-proptypes        0.17.1  →    1.4.1
 browser-resolve                             1.11.3  →    2.0.0
 copy-webpack-plugin                          6.0.3  →    6.1.1
 css-loader                                   3.6.0  →    4.3.0
 enzyme-adapter-react-16                     1.15.4  →   1.15.5
 enzyme-to-json                               3.5.0  →    3.6.1
 eslint                                       7.4.0  →   7.10.0
 eslint-import-resolver-webpack              0.12.2  →   0.13.0
 eslint-plugin-cypress                       2.11.1  →   2.11.2
 eslint-plugin-header                         3.0.0  →    3.1.0
 eslint-plugin-import                        2.22.0  →   2.22.1
 eslint-plugin-react                         7.20.6  →   7.21.2
 file-loader                                  6.0.0  →    6.1.0
 html-loader                                  1.1.0  →    1.3.1
 html-webpack-plugin                          4.3.0  →    4.5.0
 image-webpack-loader                         6.0.0  →    7.0.1
 jest                                        26.1.0  →   26.4.2
 jest-canvas-mock                             2.2.0  →    2.3.0
 jest-cli                                    26.1.0  →   26.4.2
 jest-junit                                  11.0.1  →   11.1.0
 mini-css-extract-plugin                      0.9.0  →   0.11.2
 sass-loader                                  8.0.2  →   10.0.2
 webpack                                     4.43.0  →   4.44.2
 webpack-node-externals                       1.7.2  →    2.5.2
```

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Comment by GuyKh** [comment]
Signed the CLA

**Comment by jasonblais** [comment]
Thank you @GuyKh for the contribution!

@crspeller I wasn't sure what our process is for dependency updates, so pinging you for this PR.

**Comment by crspeller** [comment]
Hi @GuyKh. Thanks for your interest! However our dependencies are not in quite enough order to be able to blindly update them like that. A bunch of those updates have known problems. As well, for security, we usually only allow core committers to perform dependency updates. 

If you are looking for good ways to contribute to Hacktoberfest with us, a good place to start is: https://mattermost.com/hacktoberfest/

Going to close this.

**Pull request closed without merging**
