### PR TITLE
Changed the api call for the remove recent custom status API

### PR DESCRIPTION
**Pull request by chetanyakan**
#### Summary
- Changed the request type to POST and update the URL for the remove recent custom status API
Previously - https://github.com/mattermost/mattermost-redux/pull/1409

#### Related Pull Requests
- https://github.com/mattermost/mattermost-server/pull/17122
- https://github.com/mattermost/mattermost-api-reference/pull/623

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by hmhealey — APPROVED** [review]
Looks good, but needs the server PR in before we can continue with review

**Comment by chetanyakan** [comment]
@isacikgoz Have a look at this PR too when you get a chance.

**Comment by hmhealey** [comment]
@chetanyakan Is this ready to be tested now that the server changes have been merged?

**Comment by hmhealey** [comment]
Also, could you merge the latest master into your branch?

**Comment by chetanyakan** [comment]
@hmhealey This is ready to be tested.

> Also, could you merge the latest master into your branch?
Done.


Also, I've set the release note to NONE as functionality-wise, there would be no change.

**Comment by hmhealey** [comment]
Yeah, that sounds fine for the release note. Having one to say the method changed might be important, but I'd assume the server PR would've already included that.

@DHaussermann This is ready for testing then.

**Comment by DHaussermann** [comment]
@hmhealey I'm not familiar with this functionality. Can you provide some guidance or test steps to validate this change. 

cc @ogi-m in case you have some context on this.

**Comment by hmhealey** [comment]
I think the test steps are:
1. Change custom statuses a few times so that you have a few listed under Recent in the popup
2. Click X next to the recent ones to verify that they're removed from recent

This would just be testing for regressions since the API call moved around.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
This is working as expected. 
- No issues clearing recent statuses
- Tested with pre-canned an user created statuses
- Tested that customizing emoji on a preached status also reverts the emoji 

LGTM!

**Pull request merged**
