### PR TITLE
Don't pre-emptively redirect to /login. Wait for the redirect at render time.

### PR DESCRIPTION
**Pull request by crspeller**
https://mattermost.atlassian.net/browse/ABC-203

### CODE REVIEW

**Comment by jasonblais** [comment]
@crspeller Do I need to test something here?

**Comment by crspeller** [comment]
@jasonblais Ya. If you where able to reproduce the login screen flash I would like to know that you don't see it on the spinmint.

**Comment by jasonblais** [comment]
Spinmint not working, will test tomorrow.

**Comment by jasonblais** [comment]
@crspeller Actually, unless there's a risk of causing regressions, I'm okay just merging the PR after second dev review and keeping an eye for this issue on pre-release. 

Since it doesn't repro, I may not be able to repro on the spinmint either. E.g. I tried on a CI and pre-release, and couldn't repro it.

**Pull request merged**
