### PR TITLE
MM-43792 - fix invite modal email results

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR adds the correct css to the invitation modal results so when there is a long list of emails, the modal keeps its size and adds a scroll bar to the result list.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43792

#### Related Pull Requests
n/a

#### Screenshots
Before:
Captura de pantalla 2022-05-10 a las 13 48 13

After:
Captura de pantalla 2022-05-10 a las 13 47 35

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @pvev !

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@pvev just one thing from me:

1. Can we make the scrollbar show only when it's needed? It seems to show even for 1 invitation.
Screen Shot 2022-05-16 at 3 24 41 PM

**Comment by pvev** [comment]
done @matthewbirtch 

https://user-images.githubusercontent.com/10082627/168679144-19a2e193-a51a-4b7a-8635-abdcd439bf94.mp4

**Review by matthewbirtch — APPROVED** [review]

**Comment by pvev** [comment]
> **blocker ** Expected — Waiting for status to be reported

hey @matthewbirtch is there something you need to do to remove the blocker that doesn't allow to merge the PR?

**Comment by neallred** [comment]
Not sure what is causing it not to be reported in this specific case, but seems more like an issue with Circle CI not completing something correctly:
* https://discuss.circleci.com/t/circleci-reports-waiting-for-status-to-be-reported/35866
* https://discuss.circleci.com/t/waiting-for-status-to-be-reported/10875/3

**Comment by pvev** [comment]
> Not sure what is causing it not to be reported in this specific case, but seems more like an issue with Circle CI not completing something correctly:
> 
> * https://discuss.circleci.com/t/circleci-reports-waiting-for-status-to-be-reported/35866
> * https://discuss.circleci.com/t/waiting-for-status-to-be-reported/10875/3

oh, ok! thanks @neallred for the info

**Comment by matthewbirtch** [comment]
> > **blocker ** Expected — Waiting for status to be reported
> 
> 
> 
> hey @matthewbirtch is there something you need to do to remove the blocker that doesn't allow to merge the PR?

No, I approved

**Pull request merged**
