### PR TITLE
Cypress/E2E: Save code body, error details and screenshots to dashboard when test  failed

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Save code body, error details (if available) and screenshots to Automation Dashboard when test  failed.

#### Screenshots
Screen Shot 2021-04-19 at 5 16 49 PM

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Thanks @saturninoabril !!

**Review by prapti — APPROVED** [review]
This is looking great! Thanks @saturninoabril!

One minor suggestion is to have the date of the result also published next to the screenshot or in the same section with the repo, branch and build id. That will perhaps be helpful in eliminating confusion when comparing failing tests etc of two or more days. How do you feel about that?

**Comment by saturninoabril** [comment]
Thanks Prapti and thanks for the feedback. We can discuss and consolidate all the feedbacks during our meeting.

**Pull request merged**
