### PR TITLE
fix mention badge styling

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Changed from using a `:before` to darken the mention badge knockout to adding an additional `box-shadow` layer to the existing `box-shadow` that applies the initial knockout to do the same thing as the `:before`.

Includes showing '99+' for over 99 mentions.

Added in additional design tweaks to badges in the LHS.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32192

#### Screenshots
image

### CODE REVIEW

**Review by esethna — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified styling/theme for team sidebar mention icon on browsers and desktop app (other ux suggestions will be addressed in a different PR)

**Comment by deanwhillier** [comment]
Now includes all the requested changes from the ticket in this PR.

**Review by hmhealey — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]
LGTM!

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified styling and position of team sidebar mention badge, does not interfere with other team icons 
- Verified badge styling/state for 1 digit, 2 digit and 99+ count mentions; extra border around mention badge has been removed.
Screen Shot 2021-01-21 at 11 18 01 AM

**Review by esethna — APPROVED** [review]

**Comment by esethna** [comment]
Thanks guys, looks great!

**Review by matthewbirtch — APPROVED** [review]
Looks great!

**Comment by amyblais** [comment]
cherry-pick cloud

**Pull request merged**
