### PR TITLE
WIP: [MM-44087] Fixing focusable item and tab order

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
When opening account and profile setting modals, the focus should be set to the first item in the in the modal body list. When you click the edit link items, your focus should be on the first item on the form

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44087

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]
Sorry, must have lost tract of this one.

**Comment by furqanmlk** [comment]
@BenCookie95 can you please fix the conflict ?

**Comment by furqanmlk** [comment]
Hi @BenCookie95  can you please fix lint issue

**Comment by BenCookie95** [comment]
> Hi @BenCookie95 can you please fix lint issue

@furqanmlk this PR needs some changes, going to move back to WIP

**Pull request closed without merging**
