### PR TITLE
Add the Teammate Name Display setting back to Account Settings > Display, below "Clock Display" option.

### PR DESCRIPTION
**Pull request by KishoreFartiyal**
#### Summary
In Account Settings > Display , below 'Clock Display' option a new display setting for 'Teammate Name Display' is added. It's default value will be set from the system config value set by admin in System Console > Users and Teams > Teammate Name display. End user's preference will be given priority than the system config setting.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/7560

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by KishoreFartiyal** [comment]
@jasonblais 
is this PR still under review ?
If done, please merge it .

**Comment by jasonblais** [comment]
@KishoreFartiyal It is under review. @esethna will be helping test it out and share feedback if any on the PM Review stage.

We've been finalizing our Mattermost v4.4 release for tomorrow, but will review this PR soon! Big thanks for your contribution

**Comment by KishoreFartiyal** [comment]
@esethna changes done to change the dropdown into radio button.

**Comment by KishoreFartiyal** [comment]
@jasonblais
Can you help, what the problem with the integration build is?
Build is successful on my local.

**Comment by jasonblais** [comment]
@KishoreFartiyal Did you run `make check-style` after the most recent changes?

**Comment by KishoreFartiyal** [comment]
@jasonblais yes, I ran 'make check-style' and it completed successfully.
Can you check the error logs of why the build is failing?

**Comment by jasonblais** [comment]
@saturninoabril Would you be able to help take a look?

**Comment by KishoreFartiyal** [comment]
@jasonblais, should I expect any help on this PR  :-)

**Comment by saturninoabril** [comment]
@KishoreFartiyal It's failing on component/unit test. Try to run `make test` on your local dev to see what's failing.
Updating the snapshots for UserSettingsDisplay should be fine just to make the tests passed.

**Comment by saturninoabril** [comment]
First of all, I suggest you work on your branch (e.g. `GSLabDev:GH-7560`) and not on master (`GSLabDev:master`).
- `git checkout -b GH-7560`

To inspect and fix failing tests on your local dev:
1. Run `make test` or `yarn run test`. You’ll notice there are failing tests on `user_settings_display.test.jsx`
2. Try to run `yarn run test:watch`, select `p` and then enter `user_settings_display.test.jsx`
3. Notice that the snapshots failed due to the changes you’ve made on `Teammate Name Display`
4. Press `u` to update the snapshots and see if the tests passed. Press `q` to quit watch mode.
5. Finally, run `make test` and see that all tests passed.

**Comment by saturninoabril** [comment]
@KishoreFartiyal Looks like it failed on style check.

**Pull request closed without merging**
