### PR TITLE
[MM-49263]: Spacing Changes for the Purchases Modal

### PR DESCRIPTION
**Pull request by emmyni**
#### Summary

A few spacing changes for the purchases modal: 
- Change the padding at the top from 20px to 40px
- Move the middle section down so that the "Alternate Payment Options" header starts below "provide your payment details"
- Fix the spacing underneath the "Seats" input box so that when the value 0 is entered, the spacing is still consistent
- Change the font size of "Total" to 14px
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49263
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

|  before  |  after  |
|----|----|
| image | image|

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @emmyni !

**Review by marianunez — APPROVED** [review]
Thanks @emmyni!

**Comment by stevemudie** [comment]
Looks good @emmyni! I just need to wait on the E2E results and then I'll approve it.

**Comment by annelieseklein** [comment]
LGTM! Thanks!

**Review by annelieseklein — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
This is all set @emmyni

**Pull request merged**
