### PR TITLE
MM-15982, MM-15984, Minor Accessibility fixes

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-15984 - Updating Main Menu to button
MM-15982 - Updating status icon and dropdown

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-15982
https://mattermost.atlassian.net/browse/MM-15984

### CODE REVIEW

**Comment by esethna** [comment]
@asaadmahmood the channel menu is still inaccessible in the spinmint (doesn't look like this ticket is solved): https://mattermost.atlassian.net/browse/MM-15988

**Comment by asaadmahmood** [comment]
@esethna Nice point, the ticket in this PR was the main menu and the status icon, not the channel menu.

**Comment by asaadmahmood** [comment]
Sorry for the changes after the review @jespino. Forgot to add the main menu label and forgot to lowercase some labels.

**Comment by jespino** [comment]
@asaadmahmood no problem, re-reviewed :)

**Comment by asaadmahmood** [comment]
Thanks a lot!

**Pull request merged**
