### PR TITLE
MM-46994 : Suffix REST to "fetchAllMyTeamsChannelsAndChannelMembers" & "fetchMyChannelsAndMembers"

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
In ahead preparation to convert both of them will be converted to separate GQL action

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46994

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]
Looks good @M-ZubairAhmed 
Question out of curiosity: will these changes be merged into the GraphQL PR I've approved and make the PR smaller? Is that the reasoning behind this PR?

**Comment by M-ZubairAhmed** [comment]
> Looks good @M-ZubairAhmed Question out of curiosity: will these changes be merged into the GraphQL PR I've approved and make the PR smaller? Is that the reasoning behind this PR?

Yes thats exactly the reason

**Review by michelengelen — APPROVED** [review]
lgtm

**Review by larkox — APPROVED** [review]
LGTM, just wondering if this is the level where you want to declare the "*Rest" functions. My point is... you want things to be transparent to the feature developer, so... the feature developer just wants to say "give me all channels and memberships". Then, the action itself check the feature flag, and select the proper method (Rest or GraphQL). That would make things cleaner, I think.

**Comment by M-ZubairAhmed** [comment]
> LGTM, just wondering if this is the level where you want to declare the "*Rest" functions. My point is... you want things to be transparent to the feature developer, so... the feature developer just wants to say "give me all channels and memberships". Then, the action itself check the feature flag, and select the proper method (Rest or GraphQL). That would make things cleaner, I think.

Thats actually a good point. We currently suffix REST because we want to retire then in future.

**Pull request merged**
