### PR TITLE
[MM-44430]: Add resize observer to observe change in size of Advanced text editor enclosing div

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Add resize observer to observe the change in the size of the Advanced text editor enclosing div

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-44430

#### Related Pull Requests
NONE

#### Screenshots
|  before  |  after  |
|----|----|
| <insert before screenshot here> | Screenshot 2022-05-24 at 7 03 59 PM |

#### Release Note
```release-note
* Add resize observer to observe the change in the size of the Advanced text editor enclosing div
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@hmhealey I think`` useMeasure`` from ``react-use`` will not work for this use case, at least from my first look it seems so will take a deeper look.

**Comment by hmhealey** [comment]
Why wouldn't `useMeasure` work here? Is it just because we're triggering a callback when the dimensions change rather than using the specific values from it?

**Comment by AshishDhama** [comment]
> Why wouldn't `useMeasure` work here? Is it just because we're triggering a callback when the dimensions change rather than using the specific values from it?
No, For using ``useMeasure`` I will need to change the whole implementation of hooks getting used in the FormattingBar component, As you cannot pass a reference to ``useMeasure`` instead need to use the one it provides and assign it to div you want to monitor.

**Review by hmhealey — APPROVED** [review]
Looks good to me then

**Review by michelengelen — APPROVED** [review]

**Pull request merged**
