### PR TITLE
[MM-48771] Mentions fixes

### PR DESCRIPTION
**Pull request by cyrilzhang-mm**
#### Summary

Fixes the text color of highlighted mentions that are not at-mentions. 
Also fixes a bug where clicking on at-mentions in post preview sends the message.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-48771
https://mattermost.atlassian.net/browse/MM-48925

#### Screenshots

Before:
Screen Shot 2022-12-06 at 1 28 51 PM

After:
Screen Shot 2022-12-06 at 1 29 20 PM

The group mention has always looked different, it seems to be intentional. 

#### QA Test Steps:

1. Ensure that the highlighted keyword mentions and highlighted first name mentions have the same styling as highlighted at-mentions using custom themes (see screenshots above). 
2. Make a draft message with an at-mention but don't send it.
3. View the preview of the message. Click on the at-mention that renders. 
4. Ensure that the message does not send when clicking on the at-mention.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected

image

**Comment by amyblais** [comment]
@cyrilzhang-mm I'm not sure if the "Performance Benchmarks" CI error needs to be fixed first before merging this.

**Pull request merged**
