### PR TITLE
Cypress/E2E: Fixed compliance compliance data retention

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
MM-T3388 - Verify the Admin Role - System Read Only Admin

#### Screenshots
image

### CODE REVIEW

**Comment by furqanmlk** [comment]
Fix for `circle/ci: test` is in this PR 
https://github.com/mattermost/mattermost-webapp/pull/8085

**Review by saturninoabril — APPROVED** [review]
Thanks Malik!

**Pull request merged**
