### PR TITLE
[MM-41158] Remove white circles from App Bar icons

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR makes it so the icons in the App Bar no longer have a white circle outline. The white circle still applies to the fallback icon. Please see the example screenshots below.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-41158

#### Screenshots

<details>

Before:

After:

Indigo

Before:

After:

Onyx

Before:

After:

</details>

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@mickmister how do I turn on the apps bar again?

**Review by michelengelen — APPROVED** [review]
LGTM

**Review by larkox — APPROVED** [review]

**Comment by mickmister** [comment]
Hi @matthewbirtch, you can use this cloud server to test here https://github.com/mattermost/mattermost-webapp/pull/9680. I've created an item in the developer's meeting to discuss how we should be using feature flags in the open PR testing servers.

**Comment by mickmister** [comment]
@matthewbirtch Whoops I meant to post this link https://app-bar-toggle.test.mattermost.cloud/

**Comment by matthewbirtch** [comment]
> @matthewbirtch Whoops I meant to post this link https://app-bar-toggle.test.mattermost.cloud/

Perfect. Thanks @mickmister! This looks a lot better without the white borders.

**Review by matthewbirtch — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann This is ready for testing

**Review by aaronrothschild — APPROVED** [review]
LGTM

**Comment by mickmister** [comment]
@DHaussermann With the App Bar being emphasized in MM v7 soon, I think we need to get this tested

**Comment by mickmister** [comment]
@DHaussermann I'm re-posting my comment above

> With the App Bar being emphasized in MM v7 soon, I think we need to get this tested

**Comment by mickmister** [comment]
@agarciamontoro I'm wondering if we should test this with your PR https://github.com/mattermost/mattermost-webapp/pull/10311, since the styling would affect the non-controlled icons being moved from the channel header

**Comment by agarciamontoro** [comment]
> @agarciamontoro I'm wondering if we should test this with your PR #10311, since the styling would affect the non-controlled icons being moved from the channel header to the App Bar

It probably will. We can merge this PR and then I can merge master and check, if that works for you.

**Comment by DHaussermann** [comment]
@mickmister I had issues deploying this code Friday. The test spin-up Seems to have App Bar disabled? As per Split IO it should be on. 

I tried before and after pulling in `master` to use `/cloud` but the tool says it can't find the corresponding Docker tag. 

We could do a quick sanity check if there was an easy way to deploy. Thoughts?

**Comment by DHaussermann** [comment]
This PR was deployable on a server with App Bar enabled after the last pull-in from `master` 👍

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Ensured white circles are removed
- Tested with multiple plugin / Apps in App Bar
- Check all themes
- Ensured there is still a very slight color change for visual feedback when the user mouse-over occurs
LGTM!

**Pull request merged**
