### PR TITLE
MM-44602 - fix flakyness showing onboarding trial

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR makes sure that the logic to show/hide the new onboarding task list is executed by the same Onboarding component in a context where the user preferences have been already loaded, even in case they haven't will force load them and execute the right logic based on preference values.

*** This is just to make sure the task list is expanded as expected for all users, all the existing functionality keeps the same. Check the QA steps on the ticket for more details.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44602

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @pvev

**Review by AGMETEOR — APPROVED** [review]

**Comment by stevemudie** [comment]
@pvev This worked as expected for fist admin, new admin and user.

I'm just waiting on the E2E at this point but it's being held up due to issues that are still [being investigated](https://community-daily.mattermost.com/core/pl/ps78mbqd9tdiznqyjris8fskfh).

**Review by stevemudie — APPROVED** [review]
The E2E went through so this is all set @pvev 

I'm not sure if this also cures https://mattermost.atlassian.net/browse/MM-44641 or not but I didn't encounter that once in all of the tests if it helps at all.

**Comment by pvev** [comment]
> The E2E went through so this is all set @pvev
> 
> I'm not sure if this also cures https://mattermost.atlassian.net/browse/MM-44641 or not but I didn't encounter that once in all of the tests if it helps at all.

Thanks @stevemudie , yes, It should fix it, since it had the same root cause.

**Pull request merged**
