### PR TITLE
Fixed couple of failing cypress tests

### PR DESCRIPTION
**Pull request by srkgupta**
#### Summary
Fixed couple of failing cypress tests based on daily E2E runs. 

#### Ticket Link
NA

#### Screenshots
Screenshot 2020-10-27 at 7 03 28 PM

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Thanks @srkgupta!

**Review by prapti — APPROVED** [review]
Looks great!

**Comment by saturninoabril** [comment]
Hello @amyblais, we'd like to cherry-pick this into the `release-5.29` to fix E2E. This is low risk and no side-effect to product.

**Comment by srkgupta** [comment]
Thanks @saturninoabril and @amyblais for helping me to cherry-pick this

**Pull request merged**
