### PR TITLE
style/MM-16514 : Emoji Autocomplete UI update in webapp

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Updated the emoji autocomplete as per the figma design

#### Ticket Link
Issue https://github.com/mattermost/mattermost-server/issues/16514
Jira https://mattermost.atlassian.net/browse/MM-30898

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

image

#### Release Note

```release-note
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
Any updates on this ?

**Review by Willyfrog — APPROVED** [review]
LGTM, sorry for the delay as I was OOO

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Looks good to me. That failing CI check can also be ignored.

Added @matthewbirtch to this to do a UX review as well just to double check everything.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks for the contribution @M-ZubairAhmed! A few small UI tweaks we could make:

1. The `emoji` autocomplete popover doesn't seem to be positioned consistently with the positioning of the `@mention` autocomplete. I'm noticing a few small differences:

    - **Positioning when it's the first character**
As per the screenshot below, the popover is not aligned with the left edge of the message input box
image

    - **Positioning when it's in the middle of a sentence**
As per the screenshot below, the positioning in this case is also inconsistent with the other autocomplete popovers
image

    - **Positioning in the Edit Post modal**
The above seems to be true in the `Edit Post` modal as well
image


2. The alignment and spacing is also slightly inconsistent _within_ the `emoji` autocomplete popovers. Notice in the screenshot below how the text is not quite aligned and the icons/images are not aligned the same.
image

3. I'm not sure if this is a problem with this PR, but I notice that when I hover towards the bottom of the emoji autocomplete popover, it scrolls down on its own.

**Comment by M-ZubairAhmed** [comment]
@matthewbirtch thank you for posting the feedback, let me work on them

**Comment by hmhealey** [comment]
> 3. I'm not sure if this is a problem with this PR, but I notice that when I hover towards the bottom of the emoji autocomplete popover, it scrolls down on its own.

That's an existing issue. I think it happens because mousing over an item "selects" it, and that triggers the list to make the item visible. It was intended to keep the selection visible when you're scrolling through items, but it triggers on mouseover for whatever reason.

**Comment by hmhealey** [comment]
@M-ZubairAhmed Let us know if you'd like any help from us.

**Comment by M-ZubairAhmed** [comment]
@hmhealey let me get back to this post cypress hackathon

**Comment by Willyfrog** [comment]
removing the label as this week was mattercon :)

**Comment by hmhealey** [comment]
@M-ZubairAhmed Have you been able to get back to this? Let us know when it's ready for another review

**Comment by M-ZubairAhmed** [comment]
since the branch got deleted opened it up here https://github.com/mattermost/mattermost-webapp/pull/8673

**Pull request closed without merging**
