### PR TITLE
update admin console help text re: subpath

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Update admin console help text re: subpath.

image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10366

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by jasonblais** [comment]
@lieut-data So I feel this would be a better example for a subpath

```
http://example.com:8065/company/mattermost
```

1) It avoids using an awkward `messaging` in the URL (and avoids using the controversial `chat`)
2) The subpath is `mattermost` which is great for branding, but also what some unnamed customers are planning to do

Spoke with Rich and he agrees.

If we made this change, then are we able to tweak the example and the input hint from `http://mattermost.example.com:8065` to `http://example.com:8065` for consistency?

**Comment by lieut-data** [comment]
I like it! Two minor proposed tweaks. Given that the first paragraph calls out the "non-standard ports" and gives an example, perhaps the input hint itself could be the "best practice" of: `https://example.com`? (SSL and no-subpath). The the paragraphs outline other "examples". I've also slightly condensed my original text proposal:

image

The counter-argument to this approach might be that `:8065` is our default proposal for enterprise setups behind a load balancer. Thoughts? I haven't pushed any changes yet.

**Comment by jasonblais** [comment]
Regarding input hint, what is more consistent with our install guides? Sounds like with the `8065` port?

Otherwise looks great 👍

**Comment by lieut-data** [comment]
Good point! I've converged on this based on all of the above, and pushed the changes:

image

**Pull request merged**
