### PR TITLE
[MM-47285] - Migrate /autocomplete/database e2e tests to TypeScript

### LINKED ISSUE #21301: CLONE - Migrate /autocomplete/database tests to TypeScript
Converting following spec files under /integration/autocomplete/database to Typescript 

  1. users*in_channel_switcher*spec.js  
  1. users*in_message_input_box*spec.js 
  1. users_spec.js

**Below is a checklist of items you should be doing to migrate:**

  1. Rename the files to their associated TypeScript extensions (ie. `js` to `ts`)
  1. Move over all the types from the declaration (`d.ts`) files into the matching typescript file, and delete the declaration file (see Support Migration PR link below for reference )

  1. Fix any errors generated by the TypeScript compiler.

  * Navigate to `/e2e/cypress` and run `npm run check-types` to display any errors.

  1. Run 

`/e2e-run` from PR and make sure all migrated and existing tests are passed. Automation results can be seen here [Automation Dashboard](https://automation-dashboard.vercel.app/cycles)

#### **Note:**

  * Please update `types` in the declaration files (`d.ts`) if they are out of date or mismatch with actual usage.
  * Please migrate `support` files to typescript if the new typescript files depend on them (*you will see compilation errors if this is the case*)

#### References

📗 **Suport Files Migration Reference**

[Support Migration PR](https://github.com/mattermost/mattermost-webapp/pull/10910)

📘 **Spec File Migration Reference**

[account_settings/profile tests migration PR](https://github.com/mattermost/mattermost-webapp/pull/11254)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-47285

### PR DESCRIPTION
**Pull request by gitstart**
### DEMO SNAPSHOT
Screen Shot 2023-03-03 at 16 36 17

Screen Shot 2023-03-03 at 16 35 50

Screen Shot 2023-03-03 at 16 34 41

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by mattermost-quality** [comment]
@gitstart Thanks for your contribution! Is this ready for review?

**Comment by M-ZubairAhmed** [comment]
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

**Comment by hmhealey** [comment]
The web app now lives in the `webapp/channels` over there. We decided to move it to be a monorepo to make both development and our CI pipelines easier, but it's unfortunately disruptive right now. We've updated [our setup docs](https://developers.mattermost.com/contribute/developer-setup/) and added [some steps for migrating to working with the monorepo](https://developers.mattermost.com/contribute/monorepo-migration-notes/).

Copying the changes over there hopefully shouldn't be too hard. There's a few changes to file paths (such as the code living in a dedicated `src` subdirectory), but most things should look the same as they do now. 

Let us know if you could use any help with this. Hopefully the process is smooth.

**Comment by gitstart** [comment]
@hmhealey This PR has been moved to a monorepo https://github.com/mattermost/mattermost-server/pull/22723 cc @M-ZubairAhmed

**Pull request closed without merging**
