### PR TITLE
[MM-44495] - Update text on pricing modal

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR updates the text about the different cloud plans on the pricing modal

#### Ticket Link
[MM-44495](https://mattermost.atlassian.net/browse/MM-44495)

#### Screenshots
pre trial
----
Screenshot 2022-05-25 at 13 38 36

post trial
---
Screenshot 2022-05-25 at 13 39 37

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by AGMETEOR** [comment]
> @AGMETEOR can we move "SSO with SAML 2.0 including Okta, OneLogin and ADFS" as a top feature instead? I've recently learned this is a top-selling feature for us. Thanks.

Screenshot 2022-05-26 at 12 15 50

**Comment by johndavidlugtu** [comment]
@AGMETEOR the "More features" should all be aligned according to the Figma design. Otherwise, all good from my end and ready to go, thanks!
Screen Shot 2022-05-26 at 9 35 12 AM

**Comment by AGMETEOR** [comment]
> @AGMETEOR the "More features" should all be aligned according to the Figma design. Otherwise, all good from my end and ready to go, thanks!
> Screen Shot 2022-05-26 at 9 35 12 AM

@johndavidlugtu unless we get rid of the contact sales button in the pre trial modal

**Comment by johndavidlugtu** [comment]
Fair point @AGMETEOR -- I'll defer to @annelieseklein on this

**Review by marianunez — APPROVED** [review]
Code LGTM, pending PM approval here

**Review by johndavidlugtu — APPROVED** [review]
Looks good, thanks @AGMETEOR !

Again, I'll leave the "More features" alignment to @annelieseklein 's call.

**Comment by annelieseklein** [comment]
Screen Shot 2022-05-26 at 12 46 55 PM
@AGMETEOR looks good! The modal height should be 700px. (I had extended it in the design to show all info but it should be 700px heigh and scrollable).  I've moved the Contact Sales button to be above the Try free for 30 days so that everything else can be aligned

**Comment by AGMETEOR** [comment]
> Screen Shot 2022-05-26 at 12 46 55 PM
> 
> @AGMETEOR looks good! The modal height should be 700px. (I had extended it in the design to show all info but it should be 700px heigh and scrollable). I've moved the Contact Sales button to be above the Try free for 30 days so that everything else can be aligned

Screenshot 2022-05-27 at 00 23 14
@annelieseklein made updates. The CTA to contact sales will be moved in a separate PR. I created a ticket https://mattermost.atlassian.net/browse/MM-44649

**Comment by annelieseklein** [comment]
Looks great

**Review by annelieseklein — APPROVED** [review]

**Pull request merged**
