### PR TITLE
fix the same target in make help output

### PR DESCRIPTION
**Pull request by rebornwwp**
Change-Id: I5c664cdc5616d9a6f9eac5c420bdc0c5c090a4d1

#### Summary

All make targets are the same in `make help` output.  So specify the makefile path for the `grep` command.

#### Ticket Link

NA

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

|  before  |  after  |
|----|----|
| image|image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @rebornwwp!

I'm not sure how this was broken for so long since I thought it was just copied from the server's Makefile, but it looks like that's not the case since it's been correct all along. Regardless of that though, it'll be nice having this working correctly, so we really appreciate that you caught it 😄

**Review by crspeller — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@jupenur can you please security approve the work flow

**Comment by jupenur** [comment]
I assume the ping was due to the CI failure, but unfortunately I can't help with that. See discussion here: https://community.mattermost.com/private-core/pl/76375bjyx3bqjna7qo6emzkyea

**Comment by hmhealey** [comment]
I tried re-running those CI steps when I did my review, so I'm not sure why they're still failing. Regardless though, this PR shouldn't have any effect outside of development, so I think we can skip those checks

**Pull request merged**
