### PR TITLE
[MM-11959] Add feature to send code block on CTRL + ENTER

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add feature to send code block on CTRL + ENTER.

@esethna Could you please give this a smoke test if feature is according to specs?  Thanks!

(Note:  Constants will be updated as soon as mattermost-redux PR is merged.)

#### Ticket Link
Jira ticket: [MM-11959](https://mattermost.atlassian.net/browse/MM-11959)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by saturninoabril** [comment]
@esethna I thought we'll do that in P2, but okay will do. 

@esethna @DHaussermann I thought it's working fine.  Maybe something mess up on my last code clean up.

**Comment by saturninoabril** [comment]
@esethna @DHaussermann Thanks for the review.  May I request for another round review?  Issues found should be fixed now.

**Comment by saturninoabril** [comment]
@esethna Noted, I'll make a change.  At first, I didn't bother to update it since I thought it's not specified.

**Comment by saturninoabril** [comment]
@esethna Thanks for the review.  That last issue should be fixed now.  This is now ready for another review. 🤞

**Comment by amyblais** [comment]
@saturninoabril This one seems to be ready to merge as well.

**Comment by saturninoabril** [comment]
Cool, thanks!  I'll just update the redux counter part and a few constants here.

**Pull request merged**
