### PR TITLE
MM-12211 Add setting to let everyone create user access tokens

### PR DESCRIPTION
**Pull request by ThiefMaster**
#### Summary
Enabling this lets all users create user access tokens, without requiring an admin to enable tokens for them first.

#### Ticket Link
https://pre-release.mattermost.com/core/pl/jkerpgtu63ywxej84aqhhmw6ie

#### Checklist
- [x] Ran `make check-style` to check for style errors
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests - fixed existing tests, didn't add new ones since there are no in-depth ones for the areas I touched
- [x] Has server changes: mattermost/mattermost-server#9310
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
As noted in https://github.com/mattermost/mattermost-server/pull/9310, we're ready to proceed with the PR. Sorry about the delay.

The only change that is needed for the PR before it's ready for review is add the new setting also to the permissions system for Enterprise Edition.

@jespino would you be able to guide @ThiefMaster on what changes are required to add a new setting similar to `EnableOnlyAdminIntegrations`, which is configurable in System Console, and
 - writes to config.json in TE [already implemented]
 - maps to role-permissions in EE [not yet implemented]

If you need any clarification, let me know. Ticket is [here](https://mattermost.atlassian.net/browse/MM-12211) and server-side PR is [here](https://github.com/mattermost/mattermost-server/pull/9310).

**Comment by jasonblais** [comment]
To map `EnableOnlyAdminIntegrations` to the role-permissions in EE was done through these two PRs, but I believe they had other changes included that aren't relevant here.

- https://github.com/mattermost/mattermost-webapp/pull/704
- https://github.com/mattermost/mattermost-webapp/pull/1661

**Comment by jespino** [comment]
@ThiefMaster, I really sorry the delay reviewing it. I was very busy and lately I've been in my parental leave, so, I'll review it ASAP.

**Comment by jespino** [comment]
@ThiefMaster I realized that the server part is under discussion yet, so, when that part is solved I'll review it.

**Pull request closed without merging**
