### PR TITLE
[MM-47478] - Tall single images aren't scaled properly

### PR DESCRIPTION
**Pull request by gitstart**
Summary
Tall single images aren't scaled properly

Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/21428

Before
Screenshot 2023-01-13 at 12 19 12

After
Screenshot 2023-01-11 at 14 40 56

### Release note
```release-note
fixes disproportionate height issue
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR!

Unfortunately, this is sort of the opposite of what we want to do here. This makes it so that disproportionately tall images aren't treated as a "small image" any more, but we still want the image to be treated as a "small image" so that it gets an extra border area and is easier to click on. This is how that looks for a small image that's mostly square.

Screen Shot 2023-01-27 at 11 38 39 AM

For this ticket, we still want these images to get the extra border and clickable area, but we also want to scale down the image so that it fits the max height that we use for larger images

**Comment by gitstart** [comment]
> Thanks for the PR!
> 
> Unfortunately, this is sort of the opposite of what we want to do here. This makes it so that disproportionately tall images aren't treated as a "small image" any more, but we still want the image to be treated as a "small image" so that it gets an extra border area and is easier to click on. This is how that looks for a small image that's mostly square.
> 
> Screen Shot 2023-01-27 at 11 38 39 AM
> 
> For this ticket, we still want these images to get the extra border and clickable area, but we also want to scale down the image so that it fits the max height that we use for larger images

Addressed

**Review by hmhealey — APPROVED** [review]
Thanks for the change! This looks good to me for every combination of small/large images and different screen sizes that I can come up with

**Review by nevyangelova — APPROVED** [review]
Thanks @gitstart LGTM!

**Review by stevemudie — APPROVED** [review]
Looks good @gitstart!

**Pull request merged**
