### PR TITLE
Cypress:e2e/Cloud test cases fixed

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Fixed Cloud test cases

 #### Release Note
```release-note
 NONE
```

### CODE REVIEW

**Review by yasserfaraazkhan — APPROVED** [review]
awesome 🙌

**Comment by furqanmlk** [comment]
Hi @Phrynobatrachus can you please review so we can see in tomorrow result ?

**Review by Phrynobatrachus — APPROVED** [review]

**Pull request merged**
