### PR TITLE
Fix registered Stylus language name

### PR DESCRIPTION
**Pull request by jazzzz**
#### Summary
It fixes the Stylus syntax highlighting.

### CODE REVIEW

**Comment by sudheerDev** [comment]
@jazzzz Hey. Have you encountered any issues with stylus highlighting? `styl` is also an alias for stylus. https://github.com/highlightjs/highlight.js/blob/dfe7bac4efcb1e873f12d62aac3f608f7490ff00/docs/css-classes-reference.rst

**Comment by sudheerDev** [comment]
Aah. I see, Got it. Thanks

**Comment by hmhealey** [comment]
@jazzzz Looks like the branch needs to be updated to the latest master before it can be merged

**Comment by sudheerDev** [comment]
@jazzzz Do mention one of the reviewers when you rebase so we don't miss merging this before commits go into master again.

**Comment by jazzzz** [comment]
> @jazzzz Looks like the branch needs to be updated to the latest master before it can be merged

@sudheerDev @jasonblais @hmhealey Done.

**Pull request merged**
