### PR TITLE
Cypress/E2E: Fix search box focus related failures

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- Fix search box focus related failures; modified to use click instead of focus
- From `archived_leave_channel_spec.js`, there are 2 expected failures related to [MM-32606](https://mattermost.atlassian.net/browse/MM-32606)
    - MM-T1672_1 and MM-T1673

#### Ticket Link
NA

### CODE REVIEW

**Review by furqanmlk — COMMENTED** [review]
All tests passed ✅ 

image

image

image

image

Failing `MM-T419 Desktop session expires when the focus is on the tab`
image

**Comment by josephbaylon** [comment]
@furqanmlk I removed the authentication_spec from this PR. It wasn't supposed to be part of this PR.

**Review by furqanmlk — APPROVED** [review]
All test passed 👍 

@josephbaylon

**Review by prapti — APPROVED** [review]
LGTM.

**Pull request merged**
