### PR TITLE
[MM-34288] Fix BaseDN typo

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Fix baseDN typo

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34299

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Comment by hahmadia** [comment]
Sorry @furqanmlk , I mistakenly assign you. It should be Steve who QA this.

**Review by stevemudie — APPROVED** [review]
Tested and passed.

Uploaded E10 and then E20 license and text read as "Base DN" as expected.

**Pull request merged**
