### PR TITLE
MM 31192  - license renewal telemetry

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
Adds the license renewal telemetry to the renewal banner and system console card

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31192

#### Related Pull Requests

https://github.com/mattermost/mattermost-webapp/pull/7391

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Looks great! Thanks @pablovelezvidal!

**Review by AGMETEOR — COMMENTED** [review]
Hey @pablovelezvidal . Everythings looks great. I just have a small question. Why do we have to make ```telemetryInfo``` a prop? Since that `RenewLink` button is dedicated to renewing licenses, I was of the view that the events will always be `renew_license_admin_console_success` and `renew_license_admin_console_fail` and that we could just specify those as contants in the component itself?

**Review by AGMETEOR — APPROVED** [review]

**Comment by pablovelezvidal** [comment]
> Hey @pablovelezvidal . Everything looks great. I just have a small question. Why do we have to make `telemetryInfo` a prop? Since that `RenewLink` button is dedicated to renewing licenses, I was of the view that the events will always be `renew_license_admin_console_success` and `renew_license_admin_console_fail` and that we could just specify those as contants in the component itself?

Thanks for the review @AGMETEOR . So, the user story define to send telemetry from two different places, one from the system console and the other from the banner which can be anywhere in the app. So, we have telemetry for `renew_license_admin_console_success` and for `renew_license_banner_success` and this also let the possibility to call the renewal link cmp from any other place and handle different telemetry.

**Comment by AGMETEOR** [comment]
> > Hey @pablovelezvidal . Everything looks great. I just have a small question. Why do we have to make `telemetryInfo` a prop? Since that `RenewLink` button is dedicated to renewing licenses, I was of the view that the events will always be `renew_license_admin_console_success` and `renew_license_admin_console_fail` and that we could just specify those as contants in the component itself?
> 
> Thanks for the review @AGMETEOR . So, the user story define to send telemetry from two different places, one from the system console and the other from the banner which can be anywhere in the app. So, we have telemetry for `renew_license_admin_console_success` and for `renew_license_banner_success` and this also let the possibility to call the renewal link cmp from any other place and handle different telemetry.

Oh yeah. I have now noticed the difference. Thanks a lot, Pablo.

**Pull request merged**
