### PR TITLE
Use dropdownText for App Bar tooltip, if no tooltip text was provided

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

For the legacy channel header components to the App Bar, we were using the provided `tooltipText`, and falling back to the plugin id. Some plugins do not provide a `tooltipText`, and instead only provide a `dropdownText`. This PR makes it so we fallback to this `dropdownText` if it is provided.

For example, this PR makes it so the Zoom plugin's "force-migrated" channel header component tooltip shows "Start a Meeting", rather than "zoom".

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-44918

#### Screenshots

image

image

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by mickmister** [comment]
Sorry @pvev @DHaussermann, didn't mean to make you an assignee on to the PR 🙂

**Comment by mickmister** [comment]
Zoom 1.5.1 or earlier should be used to test this, since it has the legacy channel header component implemented, rather than the proper App Bar component

**Review by pvev — APPROVED** [review]
LGTM! thanks @mickmister :shipit:

**Pull request merged**
