### PR TITLE
MM-33791 - add openId to check for account types

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
If only OpenID is selected as an authentication method. The "Sign-In Method" section is not displayed. This PR adds OpenID to that check and also checks when set for current user. Adds Unit test. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33791

#### Screenshots

Screen Shot 2021-03-12 at 9 45 28 AM
Screen Shot 2021-03-12 at 9 45 37 AM

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]
LGTM!

**Review by furqanmlk — APPROVED** [review]
Looks good

Added test case in Zephyr [MM-T3899](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T3899)

image

**Pull request merged**
