### PR TITLE
Added E2E Cypress test to Verify Accessibility Support in Channel Sidebar Navigation

### PR DESCRIPTION
**Pull request by srkgupta**
#### Summary
Added E2E Cypress test to Verify Accessibility Support in Channel Sidebar Navigation

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-22630

#### Screenshots
Screenshot 2020-03-16 at 5 58 12 PM

### CODE REVIEW

**Comment by srkgupta** [comment]
Thanks @josephbaylon. I have fixed the issue now. Before running the corresponding test, I have now added step to create few unread channels & public channels & also join off-topic channel. This should resolve the issue you are seeing. Please reverify.

**Comment by srkgupta** [comment]
> @srkgupta The first one seem to be resolved but replaced with similar error from 2 & 3.
> @saturninoabril Maybe you have a different result but I'm getting below consistently
> Screen Shot 2020-03-17 at 9 42 12 AM

@josephbaylon from the screenshot you have shared, it looks like a bug on the application side. If you notice there are unread channels which are marked as bold, however they are not displayed under the Unreads section. Ideally it should be grouped & displayed under Unreads section. Can you please manually check by posting as a different user & probably file a bug for this with build information?

**Comment by srkgupta** [comment]
@josephbaylon for some reasons your previously requested changes were not automatically resolved when you had approved the PR. Requesting your review again. Please approve again. Thanks.

**Comment by saturninoabril** [comment]
Have seen this failing on me. PTAL
Screen Shot 2020-03-18 at 8 31 24 PM

**Comment by srkgupta** [comment]
Thanks. Looks like something is broken with the latest code. I will recheck again

**Comment by srkgupta** [comment]
@saturninoabril and @josephbaylon I can confirm that this is an issue with the server code on the latest master instance. I have filed a bug for this here:
https://mattermost.atlassian.net/browse/MM-23433

**Comment by saturninoabril** [comment]
Thanks @srkgupta, I'll wait for that to be fixed before merging this PR. Please ping once ready for review.

**Comment by srkgupta** [comment]
@saturninoabril and @josephbaylon in order for the unreads section to be displayed the configuration ExperimentalChannelOrganization was supposed to be turned on. There was some confusion and now I have updated the tests and it is working fine on the latest build. Can you please re-check this?

**Pull request merged**
