### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-webapp_master/) for mattermost-languages-shipped/mattermost-webapp.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by metanerd — APPROVED** [review]

**Comment by metanerd** [comment]
Cherry picked https://github.com/mattermost/mattermost-webapp/commit/8f10cbd13975b830101518e4eef5240c41277f92

**Comment by amyblais** [comment]
@metanerd Was this cherry-picked to v5.30?

**Comment by metanerd** [comment]
No, this was not cherry-picked into v5.30. Since we already have an RC, does it make sense?

**Pull request merged**
