### PR TITLE
[MM-43337] Add image for emails

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
Adding this asset for use in an email.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43337
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
None
```

### CODE REVIEW

**Comment by nickmisasi** [comment]
@neallred correct - consumer is an email in mattermost-server. PR not ready yet.

**Comment by nickmisasi** [comment]
FYI @neallred ended up needing another one added.

**Review by neallred — APPROVED** [review]

**Review by marianunez — COMMENTED** [review]
Surprised we didn't already have the credit card image at least, I think we use that in the payment screen

**Comment by nickmisasi** [comment]
@marianunez we do - but it's an SVG, which Gmail doesn't support

**Review by marianunez — APPROVED** [review]

**Pull request merged**
