### PR TITLE
[GH-13727] Migrate 'components/dot_menu' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by strtw**
#### Summary

WIP attempt to migrate Dot menu to TypsScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13727

### CODE REVIEW

**Comment by teresa-novoa** [comment]
Thanks @strtw for your contribution! Let us know if you need any help here, Thanks! cc @hanzei

**Comment by jasonblais** [comment]
Hey @strtw, thanks for your contribution! I see it's currently in draft stage. Let us know if you have questions or are still interested working on it. Would love to get it into the review stage soon :)

**Comment by strtw** [comment]
Thx @jasonblais, I had created a draft PR in order to hand it over in case my work helped anyone out to get it over the finish line. I don't anticipate working on it any time soon.

**Comment by jasonblais** [comment]
Ah! I see your note in the help wanted issue. Thank you!

**Comment by hanzei** [comment]
@strtw Are you still planing to finish this PR?

**Comment by vraravam** [comment]
is this open for a different contributor?

**Comment by jasonblais** [comment]
Covered by a new PR opened by @vraravam: https://github.com/mattermost/mattermost-webapp/pull/6825

Closing in favor of https://github.com/mattermost/mattermost-webapp/pull/6825

**Pull request closed without merging**
