### PR TITLE
[MM-23517] - Fix channel header popover

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
This fixes the line breaks that were removed in the markdown formatting. Checked the messages everywhere that use the 'marked' function and nothing looks broken. The style change is needed because on the new side bar the popover needs a different left offset. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23517

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by esethna — CHANGES_REQUESTED** [review]
Thanks Nevy! Nice find on the sidebar left offset, although I'm still seeing a slight shift:

c186ca1d3762a23b84267555d73c6345

**Review by esethna — APPROVED** [review]

**Review by devinbinnie — COMMENTED** [review]
There's actually a way you can do this without using JavaScript.
You can define a CSS selector that checks to see if `#SidebarContainer` is a sibling, then select `.channel__wrap` and you can go down the CSS tree from there.

Should look something like:
`#SidebarContainer + .channel__wrap .channel-header__popover`

**Comment by nevyangelova** [comment]
@devinbinnie I see the point of doing it without Javascript but I feel in this case is more clear to drive it from the state, because the reason for adding the class is clearer and its grouped together with the other variable.

**Comment by jgilliam17** [comment]
@nevyangelova Looks good
Only one issue
there is a shift to the left in the popover on DM channels, due to status below name. See gif.
Popover shift

**Comment by nevyangelova** [comment]
@hmhealey @devinbinnie I am not super happy with the hacky CSS of the popover and would like to open a follow up ticket to investigate re-doing it and fixing the positioning in a more elegant and consistent way, similar to the dot menu exploration.

**Comment by devinbinnie** [comment]
> @devinbinnie I see the point of doing it without Javascript but I feel in this case is more clear to drive it from the state, because the reason for adding the class is clearer and its grouped together with the other variable.

@nevyangelova I look at it as a separation of concerns issue, where the styling and component logic should be kept separate. I would only use a custom class driven by component logic when CSS breaks down.

I'm only about 2/5 on this, not sure what other people think but I won't hold up the PR.

**Review by devinbinnie — APPROVED** [review]

**Comment by nevyangelova** [comment]
I agree with that and I am not happy with the final solution with adding classes, lets explore redesigning the component and styles in the ticket I mentioned above.

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 

Tested, looks good to merge.
- Verified line breaks, new lines, fixed first line of channel description and popover not shifting on hover.
- Popover text formatting matches edit channel header modal.

**Pull request merged**
