### PR TITLE
Cypress/E2E: Update tests related to edit indicator

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Failed tests introduced by https://github.com/mattermost/mattermost-webapp/pull/8851

Test report - https://automation-dashboard.vercel.app/cycles/726450d3-2515-48ec-bae7-ceb55a246d35

Note: MM-T1239 is known product bug - https://mattermost.atlassian.net/browse/MM-38971

#### Screenshots (some)
Screen Shot 2021-10-01 at 6 24 12 AM
Screen Shot 2021-10-01 at 6 24 53 AM
Screen Shot 2021-10-01 at 7 49 18 AM
Screen Shot 2021-10-01 at 8 16 36 AM
Screen Shot 2021-10-01 at 8 18 20 AM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by josephbaylon** [comment]
@saturninoabril Please resolve conflicts

**Comment by saturninoabril** [comment]
@josephbaylon Done update.

**Review by josephbaylon — APPROVED** [review]
LGTM. Tested locally, all else passed excepted for the expected failure.

**Review by michelengelen — APPROVED** [review]
LGTM

**Pull request merged**
