### PR TITLE
Promote Polish from Alpha to Beta

### PR DESCRIPTION
**Pull request by jasonblais**
#### Summary
Promote Polish from Alpha to Beta. The language has now reached 90%.

### CODE REVIEW

**Comment by enahum** [comment]
Build is failing

**Comment by jasonblais** [comment]
Not sure why, couldn't tell from the Jenkins log..

**Comment by cpanato** [comment]
@jasonblais need to update the snapshots

**Comment by cpanato** [comment]
```


Summary of all failing tests

FAIL components/admin_console/schema_admin_settings.test.jsx (15.197s)

  ● components/admin_console/SchemaAdminSettings › should match snapshot with settings and plugin



    expect(value).toMatchSnapshot()



    Received value does not match stored snapshot "components/admin_console/SchemaAdminSettings should match snapshot with settings and plugin 1".



    - Snapshot

    + Received



    @@ -382,11 +382,11 @@

                    "text": "Nederlands (Alpha)",

                    "value": "nl",

                  },

                  Object {

                    "order": 6,

    -               "text": "Polski (Alpha)",

    +               "text": "Polski (Beta)",

                    "value": "pl",

                  },

                  Object {

                    "order": 7,

                    "text": "Português (Brasil)",



      233 |             />

      234 |         );

    > 235 |         expect(wrapper).toMatchSnapshot();

          |                         ^

      236 |     });

      237 | 

      238 |     test('should match snapshot with custom component', () => {



      at Object.toMatchSnapshot (components/admin_console/schema_admin_settings.test.jsx:235:25)





Snapshot Summary

 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm test -- -u` to update them.

```

**Comment by jasonblais** [comment]
Updated

**Pull request merged**
