### PR TITLE
tests/MM-40609 : E2Es for recent custom emoji fixes 

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Adds end to end tests for following scenarious
- [x] Emoji picker should show all custom emojis without overlaps.
- [x] Custom emoji - delete emoji after reacting with it on a post.
- [x] Recently used custom emoji, when is deleted should be removed from recent category of emoji picker and quick reactions.
- [x] Changing the skin of emojis should apply the same skin to emojis in recent section.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40609

#### Related Pull Requests
None

#### Screenshots
None

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Tests passed locally. Thanks @M-ZubairAhmed !!

**Comment by M-ZubairAhmed** [comment]
@furqanmlk could you please also check if other tests got effected due to change in `checkReactionFromPost` function

**Review by furqanmlk — APPROVED** [review]
Thanks @M-ZubairAhmed 👍

**Pull request merged**
