### PR TITLE
[MM-50798]: Fix custom status emoji search issue

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
fix custom status emoji search issue

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-50798

#### Related Pull Requests
NA

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2023-02-23 at 11 07 28 AM| Screenshot 2023-02-27 at 1 23 25 PM |

#### Release Note
```release-note
* Fix custom status emoji search issue
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Comment by AshishDhama** [comment]
@harshilsharma63 Gentle reminder on this

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by amyblais** [comment]
@AshishDhama Please help open a manual cherry-pick PR for the ``release-7.9`` branch.

**Pull request merged**
