### PR TITLE
Automated cherry pick of #9450 on release-6.2

### PR DESCRIPTION
**Pull request by puerco**
Automated cherry pick of #9450 on release-6.2

Cherry pick of #9450 on release-6.2.

/cc  @weblate

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
The tests are failing.

**Comment by puerco** [comment]
Yes, I wonder if this is because we did not cherry pick [the last weblate PR](https://github.com/mattermost/mattermost-webapp/pull/9410) :thinking:

**Comment by puerco** [comment]
The missing message is in the previours PR, here:
https://github.com/weblate/mattermost-webapp/blob/f2ba922c4cec14d3cd6ca9c1d40a4c71a070ee75/i18n/es.json#L694-L695

**Review by cpanato — APPROVED** [review]

**Comment by amyblais** [comment]
I don't know what the correct solution is, but if the previous PR needs to be cherry-picked too, that's fine to me.

**Comment by cpanato** [comment]
@puerco @amyblais anything that we need to update here?

**Comment by puerco** [comment]
I'll backport the previous weblate PR to try to complete the stringset that is causing the test to fail.

**Comment by puerco** [comment]
OK, let's see if merging this one first fixes it:
https://github.com/mattermost/mattermost-webapp/pull/9468

**Comment by puerco** [comment]
OK, I've found the problem. It seems the branches have diverged and translations cannot be cherry-picked because `master` and `release-6.2` require a different set of strings.

The translation string that is breaking the cherry-pick `admin.data_retention.note.description` exists in `release-6.2`:
https://github.com/mattermost/mattermost-webapp/blob/bedf9b58d4804b7de7a6c0fe508123fa265b3f77/components/admin_console/admin_definition.jsx#L5394

But it was removed in this commit to master:
https://github.com/mattermost/mattermost-webapp/commit/c54cc7b35b269ea0fd4d33114caf19d39f3aabdc#diff-128483fb9ca10b5b50926c114c9f7b76158c7520591249b993c7d4e8c1c4a051L5393

It seems the commit was never cherry-picked to the release branch. @hmhealey can this change be backported to `release-6.2`?

**Comment by hmhealey** [comment]
Yeah, that should be fine to cherry-pick over. The only functional change in it is the search text that changed to cause this conflict.

**Comment by hmhealey** [comment]
https://github.com/mattermost/mattermost-webapp/pull/9481

**Comment by puerco** [comment]
OK, that did the trick. Thanks a lot @hmhealey !!

**Pull request merged**
