### PR TITLE
[MM-49528]- Webapp: remove right-click hijacking on code blocks in messages

### PR DESCRIPTION
**Pull request by gitstart**
Summary
remove right-click hijacking on code blocks in messages

Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/22040
Jira: https://mattermost.atlassian.net/browse/MM-49528
Screenshots

Before: 
Screenshot 2023-01-10 at 20 52 50

After:
Screenshot 2023-01-10 at 20 55 43

### Release note
```release-note
Removed right-click hijacking on code blocks in messages
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
LGTM!

**Review by esethna — APPROVED** [review]
Approving from PM perspective as I agree with the redundancy of the new copy code block button on hover. Will defer to QA for testing

**Review by matthewbirtch — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @gitstart 
Verified right-click menu on code blocks on messages - as expected.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/294392-7e8828a-onprem-ent-webapp-pr-11962-mm-ee-test:7e8828a/mochawesome.html) has few failures related to changes 
4 Markdown message tests failed in  `markdown_text_spec.js`

**Comment by jgilliam17** [comment]
Thank you for fixing the tests @gitstart 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/296173-ea32f60-onprem-ent-webapp-pr-11962-mm-ee-test:ea32f60/mochawesome.html) - no PR related failures.
LGTM

**Pull request merged**
