### PR TITLE
Cypress/E2E: Move more channels API commands

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Move more channels API commands.

Test results: https://mm-cypress-report.s3.amazonaws.com/975-cypress-move-channels-api-master/mochawesome.html

### CODE REVIEW

**Comment by saturninoabril** [comment]
Test results now updated. Related failed tests on "channel public/private toggle" is fixed by recent commit (https://github.com/mattermost/mattermost-webapp/pull/6472/commits/d02014374af91195943566c8c9b361da8be56e46).

**Review by prapti — APPROVED** [review]
LGTM. Ran few of the changed tests, passed without issues.

**Review by srkgupta — APPROVED** [review]
Thanks @saturninoabril for adding the report. Changes LGTM. My only observation is that the test e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js fails in the final report. Can you please confirm if the test isnt failing because of your changes.

**Comment by saturninoabril** [comment]
@srkgupta Yes, it's related but I pushed a commit to fix it as I mentioned [here](https://github.com/mattermost/mattermost-webapp/pull/6472#issuecomment-694300003).

Latest report after the fix: https://mm-cypress-report.s3.amazonaws.com/980-cypress-move-channels-api-master/mochawesome.html

**Pull request merged**
