### PR TITLE
[MM-16042] Added aria-labels to profile picture settings buttons

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Added `aria-label` tags to the buttons under the Profile Picture settings in Account Settings. Also changed the tags from being anchors to actual buttons so that they can be tabbed correctly.

NOTE: The part where the screen reader says ‘read-only’ before the Select button is read is being fixed by https://github.com/mattermost/mattermost-webapp/pull/3100

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16042

### CODE REVIEW

**Comment by esethna** [comment]
1. tab to the profile pic edit button, hit enter
2. tab once to the select button

Observed: read out says "Dialog account settings dialog read only read only select button"
Expected: "Select button"

**Comment by esethna** [comment]
Select button is not getting proper visual focus box like the save and cancel buttons

**Comment by enahum** [comment]
@devinbinnie the remove profile picture action is not accessible through the keyboard, we should make sure you are able to also remove the profile picture that way.

**Comment by devinbinnie** [comment]
> @devinbinnie the remove profile picture action is not accessible through the keyboard, we should make sure you are able to also remove the profile picture that way.

Done!

**Comment by esethna** [comment]
@amyblais curious why is the cherrypick approved label on here? This is for v5.14

**Pull request merged**
