### PR TITLE
MM-18454 - Updating quick switch modal

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-18454 - Updating quick switch modal

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18454

### CODE REVIEW

**Comment by esethna** [comment]
Also, should we horizontally align the section breaks with the input box?

image

**Comment by asaadmahmood** [comment]
@esethna We can use a transparent scrollbar, but if use a custom scrollbar here, it will be updated in all other places where that list is used (autocompletes) etc. And that is a big change (not technically, but the different parts it is implemented). (Unless I modify that component to use a custom scrollbar only for that specific instance).

So I say, we can consider that as a whole for that component.

For the other 2 UI points, I have removed the space from the bottom, and the divider is already at the edge, but just shifts inside when the scrollbar appears.

See example below:
Screenshot 2019-09-17 at 5 01 42 PM

**Comment by esethna** [comment]
Thanks @asaadmahmood can you help create a follow-up ticket for that change to the scroll bar component? May be a good HW tix

**Comment by lindy65** [comment]
Thanks @asaadmahmood 

Looks good to me!

**Pull request merged**
