### PR TITLE
Promote archived channels to Beta

### PR DESCRIPTION
**Pull request by jasonblais**
#### Summary
Promote archived channels to Beta.

PM sign-off on promotion: https://community.mattermost.com/core/pl/j8driu8totgxdcbd7gqe8tygiy

#### Ticket Link
No ticket

#### Related Pull Requests
N/A

#### Screenshots
N/A

### CODE REVIEW

**Comment by jasonblais** [comment]
Doesn't need QA review, but tagging @DHaussermann as a heads up.

@amyblais Can this be approved for 5.18? It's not a bug, but it's a low risk text change in help text to promote archived channels to Beta.

**Comment by crspeller** [comment]
@jasonblais The setting to turn it on is still in the "experimental features" section.

**Comment by jasonblais** [comment]
@crspeller It's actually in "Users and Teams" section

image

**Comment by DHaussermann** [comment]
@crspeller  can proceed with merge and cherry pick for this.

**Pull request merged**
