### PR TITLE
MM-19556 - E10 License: Permission Schemes not working properly

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
Don't sent guest role changes if license doesn't allow it

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-19556

### CODE REVIEW

**Comment by srkgupta** [comment]
Hi @reflog 

By default all users have permissions to invite Guest Accounts. It should be only sysadmins should have this privilege. Can you please fix this. 

Screenshot 2019-10-22 at 7 51 20 PM

**Comment by reflog** [comment]
@srkgupta - I don't think it's related to this PR.
Here's some feedback from @jespino :

> In team edition that permission is granted by default, so, when you change to E10, the permission is already granted to team user role

**Comment by srkgupta** [comment]
Hi @reflog 

If you check this documentation, its mentioned that by default only sysadmin can invite guests. However on an E10 instance which is newly migrated to 5.16, anyone can invite guests. 

image

https://docs.mattermost.com/deployment/guest-accounts.html#guest-permission-settings

**Comment by jespino** [comment]
@srkgupta The setup sets the `INVITE_USER` permission to every team member during installation, after that it migrates the permissions (if the permissions migrations is not applied yet) and it add the `INVITE_GUEST` to any role with `INVITE_USER` permission, so if you migrated to 5.16 and you had `INVITE_USER` permission for all team members, you will have `INVITE_GUEST` for all team members.

**Comment by wiersgallak** [comment]
@jespino The original intent was to have only the system admin by default.  If we had a discussion on this, can you refresh my memory?  Can we have a quick conversation on this?

**Comment by srkgupta** [comment]
Thanks @wiersgallak 
I have created a separate ticket to track this issue. https://mattermost.atlassian.net/browse/MM-19684

**Comment by amyblais** [comment]
@reflog FYI that v5.16.1 dot release is now done, so this PR can be cherry-picked to v5.16 to be included in v5.16.2 dot release.

**Comment by reflog** [comment]
@amyblais already done!

**Comment by amyblais** [comment]
@reflog If it's already done, did it get included in v5.16.1 final build that I just cut an hour ago?

**Comment by reflog** [comment]
@amyblais - as far as I can tell, it's **not** in 5.16.1

**Comment by amyblais** [comment]
@reflog Would you be open to linking to the commit that cherry-picked this to v5.16?

**Comment by reflog** [comment]
@amyblais - my apologies, seems it was only cherrypicked into 5.17 . Since 5.16 is out - where should I cherrypick it to? 5.16.1 ?

**Comment by amyblais** [comment]
@reflog 5.16.2

**Comment by reflog** [comment]
@amyblais - seems 5.16.2 wasn't cut yet

**Comment by amyblais** [comment]
@reflog What is the status of getting this cherry-picked to v5.16?

**Comment by reflog** [comment]
@amyblais done

**Pull request merged**
