### PR TITLE
MM-10555 Update outgoing webhook content-type help text

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Update outgoing webhook content-type help text.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10555

### CODE REVIEW

**Comment by jasonblais** [comment]
@jwilander Build failed, otherwise looks good

**Comment by jwilander** [comment]
Build failure is unrelated to my changes.

**Comment by cpanato** [comment]
this should go to `release-5.0`? @jwilander

**Comment by jwilander** [comment]
Yeah let's put it in 5.0

**Pull request merged**
