### PR TITLE
[MM-14250] Fix rage emoticon from being grabbed by mention regex

### PR DESCRIPTION
**Pull request by seansackowitz**
#### Summary
This fixes the case where a `@` with zero characters following it is grabbed as a mention. This caused the Rage emoticon to not be parsed, as the singular `@` in the `:@` or `:-@` was being converted to a mention before being converted to an emoticon

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/10807
and https://mattermost.atlassian.net/browse/MM-14250

### CODE REVIEW

**Comment by hanzei** [comment]
Hey @esethna, gently reminder about reviewing this PR

**Comment by esethna** [comment]
Apologies for the delay, looks great, thanks @seansackowitz! Moving to dev review

**Comment by deanwhillier** [comment]
Apologies for the delay in completing this @seansackowitz! I took a look, got redirected and completely forgot to come back and finish. 😞

Any chance you could merge master into your branch and push so I can merge this into master? Thx!

**Comment by seansackowitz** [comment]
@deanwhillier done!

**Comment by deanwhillier** [comment]
Great, thanks @seansackowitz!

**Pull request merged**
