### PR TITLE
MM-20648 - Updating dropdown css

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-20648 - Updating dropdown css

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20648

### CODE REVIEW

**Comment by srkgupta** [comment]
Also noticed that there are some teams displayed at the bottom outside the white dropdown background. It should be wrapped within the dropdown height and should not be displayed outside. Can you fix this issue too.

**Comment by asaadmahmood** [comment]
@srkgupta Please try again.

**Comment by amyblais** [comment]
@asaadmahmood Rohitesh is off this week, can we request another QA to review this?

**Comment by asaadmahmood** [comment]
Sure @amyblais

**Pull request merged**
