### PR TITLE
Fixing attachments code preview

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Fixing attachments code preview

#### Ticket Link
[MM-40359](https://mattermost.atlassian.net/browse/MM-40359)

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Comment by amyblais** [comment]
@jespino Is this bug in the v6.2 branch, or just master?

**Comment by amyblais** [comment]
> @jespino Is this bug in the v6.2 branch, or just master?

Or @hmhealey if you know? ^

**Comment by jespino** [comment]
@amyblais just master

**Pull request merged**
