### PR TITLE
Remove unused getYoutubeVideoInfo function

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Remove unused getYoutubeVideoInfo function

#### Ticket Link
No ticket needed

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Wow nice catch 😄

**Comment by jespino** [comment]
@M-ZubairAhmed actually, there are a lot of them, I going to make another PR removing some files.

**Comment by M-ZubairAhmed** [comment]
Feel free to disapprove : Also in the squash merge commit message can we write which exactly function did we remove

**Comment by jespino** [comment]
@M-ZubairAhmed ohh no, I just creating more PRs for that, I prefer small PRs that are easy to review.

**Comment by hmhealey** [comment]
I'm going to file a followup ticket to this as well. The API key that was previously passed into this function actually isn't used any more since this function stopped being used in favour of getting the YouTube metadata from OpenGraph. That can be done separately though since it'll require server and web app changes outside the scope of what you're working on.

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
