### PR TITLE
MM-33903 rename slash commands & permissions

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR renames the permission `manage_remote_clusters` to `manage_secure_connections` per revised shared channels spec.  https://docs.google.com/document/d/12Jwu9aODzVArNP3z6_ivTePIvz9EsjDpwSSVmzl5pU8/edit#bookmark=id.j0ctjvp2k0h5

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33903

#### Related Pull Requests

- Has server changes https://github.com/mattermost/mattermost-server/pull/17494

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
There's not going to be any compatibility issues with changing this will there? There were some issues with some other renamed permissions recently which broke the system console, but those were older permissions that had been chcanged.

**Comment by wiggin77** [comment]
> There's not going to be any compatibility issues with changing this will there? There were some issues with some other renamed permissions recently which broke the system console, but those were older permissions that had been chcanged.

Thanks @hmhealey   I did a test and the system console showed the renamed permission.  Do you recall what the symptom of the breakage was?

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by wiggin77** [comment]
@furqanmlk the QA for this is just to ensure the renamed permission shows up in system console and didn't break.

**Comment by hmhealey** [comment]
The bug I hit was that most of the items in the System Console sidebar didn't show up, but there were a lot more permissions being renamed back then. It was also only happening when the server and client were on different versions. I don't know if that can even happen here.

**Comment by wiggin77** [comment]
> The bug I hit was that most of the items in the System Console sidebar didn't show up, but there were a lot more permissions being renamed back then. It was also only happening when the server and client were on different versions. I don't know if that can even happen here.

Got it, thanks.  Not seeing that in testing so looks like we're good.

**Review by furqanmlk — COMMENTED** [review]
**Secure Connection**
image

**Share channel invite**
image

**Accept**
image

**Share Channel**
image


**There is no auto-complete ID for following commands** 
Large GIF (670x388)

Large GIF (670x388)

**Comment by wiggin77** [comment]
@furqanmlk, the auto-complete issues are fixed.

**Comment by wiggin77** [comment]
BTW, @furqanmlk, the autocomplete fix is in server PR.

**Comment by furqanmlk** [comment]
> BTW, @furqanmlk, the autocomplete fix is in server PR.

Thanks @wiggin77 , actually I am testing both PRs together. I approved server PR my accident :)

**Review by furqanmlk — APPROVED** [review]
All Slash commands and permission tested ✅ 
Test case has been updated.

**Pull request merged**
