### PR TITLE
[MM-42592] resolve flakiness when actions menu is open

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR resolves an issue when the Actions Menu has been opened. When looking at release v6.5, the expected behavior of an open `...` menu is that the menu would open for the selected post. However, moving the mouse up and down the channel view would open the `post_info` of other posts while the original opened menu remains open.  This PR adds that same expected behavior to the `Actions Menu` when opened.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42592

#### Release Note

```release-note

```

### CODE REVIEW

**Review by jwilander — APPROVED** [review]
LGTM

**Comment by jfrerich** [comment]
@DHaussermann I believe this is also going to solve the flakiness with the mobile webview where a user clicks the `Actions` menu, but it doesn't open. If we can't repro with this PR (I can't), I think we can safely close https://mattermost.atlassian.net/browse/MM-42603 also

**Review by Willyfrog — APPROVED** [review]

**Comment by DHaussermann** [comment]
@jfrerich I do share your opinion that having the items persist on mouse away feels less flaky. 

That said - I do still see an issue here. The behavior between `...` and "Actions" is still inconsistent. 
The state of the menu open / closed is solved but, Actions items remain visible when you mouse away and `...` does not.  

1/5 Seeing as how this is low impact - I would opt for not cherry-picking this until Jason's solution can be applied to `...` as well. This would give us consistency between the 2 menus. We could also confirm with UX if needed that this is the desired behavior if we feel it's subjective.  

cc @amyblais may have a thought on this as well.

**Comment by DHaussermann** [comment]
cc @saturninoabril on point above ☝️

**Comment by jfrerich** [comment]
@DHaussermann, I'm seeing that the `...` menu operates differently depending on where the post hover is located.
* Center Channel Comment
* RHS Root Comment
* RHS Comment

**Comment by jfrerich** [comment]
For the `...` menu I see the following behavior when moving the mouse
* center channel - menu stays open
* RHS root comment - menu closes after moving mouse away from menu
* RHS reply comment - menu stays open.

@matthewbirtch, what the preference from a UX perspective?

**Comment by amyblais** [comment]
> cc @amyblais may have a thought on this as well.

I'm fine with not cherry-picking to cloud for now and we can cherry-pick this to 6.6 later this week when this is ready.

**Comment by jfrerich** [comment]
@saturninoabril or @DHaussermann can we merge this with the inconsistent open menu option?  I feel like the flakiness solved with this PR outweighs the inconsistent open menus.  Plus we will be waiting in feedback from UX before I can make those changes

**Comment by saturninoabril** [comment]
Honestly, there's no easy way to pick one or the other as I don't see any advantage. Both are broken and will result to not good user experience. With menu open, hovering over different posts or menu items, in combination with menu position or post content (with link, message attachment, etc), reveal some undesirable/broken UI.
+1 on consistency for Cloud March 30th then permanent fix based on UX decision on v6.6.
I'm fine whatever you (@jfrerich) and Dylan agreed upon.

**Comment by matthewbirtch** [comment]
@jfrerich also, I'm seeing some z-index issues with the menu when moving my mouse around and hovering over other posts, the hover actions display on top of an open menu. The menu should be always on top
image

**Comment by jfrerich** [comment]
@matthewbirtch, I agree there are index issue.  However they have been there before this PR or the actions menu.  Here is release v6.5.

image

**Comment by jfrerich** [comment]
I can fix the inconsistancy with the menu staying open until the user clicks an action or clicks away from the menu.  However, I propose not fixing the z-index issue in this PR.  While it should be fixed, It was not introduced by this new Actions Menu.

**Comment by matthewbirtch** [comment]
> I can fix the inconsistancy with the menu staying open until the user clicks an action or clicks away from the menu. However, I propose not fixing the z-index issue in this PR. While it should be fixed, It was not introduced by this new Actions Menu.

Ok, do we have a ticket open for this to be fixed?

**Comment by matthewbirtch** [comment]
> No. not yet.

https://mattermost.atlassian.net/browse/MM-42874

**Comment by jfrerich** [comment]
@matthewbirtch, I believe the menu remaining open has been fixe in my last commit.  I do see that z-index issue, but honestly will need some assistance on solving that issue.  Please confirm the open menu remains open for `Actions Menu` and `Dot Menu` options in the center channel posts, RHS root, and RHS comment posts.

**Review by matthewbirtch — APPROVED** [review]
Approving this knowing the z-index issue will be resolved separately

**Comment by amyblais** [comment]
@DHaussermann Kind reminder to QA review this.

**Comment by DHaussermann** [comment]
@jfrerich I just realized the traparency issue above looks similar to https://github.com/mattermost/mattermost-webapp/pull/10111#issue-1188241981 on the other PR? 
Maybe the issue is not theme specific?

**Comment by jfrerich** [comment]
@DHaussermann, you are correct. That divider hovering issue will be resolved separately in https://github.com/mattermost/mattermost-webapp/pull/10111

**Comment by jfrerich** [comment]
@DHaussermann, aside from the hovering issue, resolved elsewhere, is this PR ready to merge?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- As per testing above the 2 issues have been resolved
- The issue I found was already being addressed here https://github.com/mattermost/mattermost-webapp/pull/10111

LGTM! @jfrerich

**Pull request merged**
