### PR TITLE
[MM-45097] Fix attachment menu overlap issue

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Advanced text editor attachment menu overlap issue
Note: need to install the Draw plugin or some other plugin making use of that menu
https://github.com/jespino/mattermost-plugin-draw
https://github.com/streamer45/mattermost-plugin-voice

#### Ticket Link
 Fixes https://mattermost.atlassian.net/browse/MM-45097

#### Related Pull Requests
NONE

#### Screenshots
|  before  |  after  |
|----|----|
| Image Pasted at 2022-6-14 19-05 | Screenshot 2022-06-15 at 12 10 56 AM  |

#### Release Note
```release-note
Advanced text editor attachment menu overlap issue
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
//cc @amyblais

**Review by Willyfrog — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @AshishDhama 
Looks good, one suggestion - can we stop Upload files tooltip from triggering when hovering away from paperclip icon and over other popover options.
Screenshot 2022-06-17 171659

**Comment by AshishDhama** [comment]
> Thanks @AshishDhama Looks good, one suggestion - can we stop Upload files tooltip from triggering when hovering away from paperclip icon and over other popover options. Screenshot 2022-06-17 171659
Sure

**Review by jgilliam17 — APPROVED** [review]
Thanks @AshishDhama 
Tested, looks good to merge.
- Verified attachment menu opens as expected.
- [E2E report](https://automation-dashboard.vercel.app/cycles/573d1e0a-8404-411b-b889-232d91825942), known failures; not PR related

**Comment by AshishDhama** [comment]
@koox00 it’s ready for review.

**Pull request merged**
