### PR TITLE
MM-43352: syncs threads on reconnect

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Currently upon reconnect we fetch all teams counts, and we sync threads
for the current team.

This commit will sync threads for all teams, with priority to threads
of current team first.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-43352

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
@josephbaylon I guess that @koox00 is the right person to answer that. Also, I added you as reviewer because I thought this was mobile. Feel free to assign to @jgilliam17 if needed.

**Comment by josephbaylon** [comment]
@larkox I see. I'll re-assign to @jgilliam17 then. Thanks!

**Comment by jgilliam17** [comment]
Thanks @koox00 
I am seeing few errors on console when reconnecting, I'll try to add few pages of what I see in case it's related to your changes. Apologies if there's doubling of images/errors etc.

Screen Shot 2022-04-20 at 4 12 55 PM
Screen Shot 2022-04-20 at 4 12 14 PM
Screen Shot 2022-04-20 at 4 11 44 PM
Screen Shot 2022-04-20 at 4 18 46 PM

**Comment by jgilliam17** [comment]
Here is the [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/186058-a533b60-onprem-ent-webapp-pr-10191-mm-ee-test:a533b60/mochawesome.html) from Friday. It had more failures than master. I am updating and re-running to rule out flaky tests.

**Comment by jgilliam17** [comment]
Latest [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/187177-90716c5-onprem-ent-webapp-pr-10191-mattermost/mm-ee-test90716c5/mochawesome.html) looks good, no PR related failures.

**Comment by esethna** [comment]
@Willyfrog are there next steps for this PR? I'd like to try getting this in for v6.7 if possible

**Comment by Willyfrog** [comment]
> Latest [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/187177-90716c5-onprem-ent-webapp-pr-10191-mattermost/mm-ee-test90716c5/mochawesome.html) looks good, no PR related failures.

@jgilliam17 does this mean that the change is good to go? or are the above screenshots still relevant?

**Comment by koox00** [comment]
@Willyfrog some of the errors are relevant to this change, I'll investigate to see why, maybe it was more of a general failure to fetch.

**Comment by koox00** [comment]
How no issues whatsoever locally, could the errors in the screenshots be from a bad connection?
Can you re-test @jgilliam17 just to be on the safe side?

**Comment by jgilliam17** [comment]
@koox00 Thanks for checking. I retested on my end and no longer seeing the errors.
The errors I posted above were present for me on startup after waking computer in the morning. I haven't seen the same errors again with the same server. It is possible that I had a bad connection.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
