### PR TITLE
Migrate headerOverlay string ref to functional ones in channel_info_button.js

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Fixes https://github.com/mattermost/mattermost-server/issues/15797#event-3844313554

JIRA ticket: https://mattermost.atlassian.net/browse/MM-29308

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]
THANKYOU

**Review by ashishbhate — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @sowmiyamuthuraman 
Tested, looks good to merge.
- Verified/tested around channel info modal/channel info button in mobile view - as expected.

**Pull request merged**
