### PR TITLE
[MM-46437]: removed submitting the forward on pressing enter

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
for some users submitting the forward modal on hitting enter was proving to be buggy.

This is due to the character replacement (in japanese it is common to write hiragana, which then gets converted to a kanji with a popover) happening in a popover which is still technically a part of the modal and therefor pressing enter will be seen as a trigger for submitting.

This is fixing that behavior.

#### Ticket Link
[MM-46437](https://mattermost.atlassian.net/browse/MM-46437)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
tested, looks good to merge - pending e2es
Verified forwarded message is not submitting on enter while drafting comment. Tested in English and Japanese.

**Review by jgilliam17 — APPROVED** [review]
[E2E report](https://automation-dashboard.vercel.app/cycles/e7984300-def5-4902-8c48-067b7197c72e) looks good - no PR related failures.

**Comment by michelengelen** [comment]
@koox00 kind reminder to review

**Review by koox00 — APPROVED** [review]

**Pull request merged**
