### PR TITLE
MM-48401 : Convert "sidebar_category_menu" to functional components and replace with compass icons

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48401

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]
LGTM! Only one small question: have we checked if the existing tests written for the menu are sufficient and we won't introduce a regression? (since this is a major refactoring)

**Comment by M-ZubairAhmed** [comment]
Failed on only 1 test, not related to the pr https://automation-dashboard.vercel.app/cycles/ea8ca97b-1d80-4cc3-b6d5-a5b106f004fa

**Pull request merged**
