### PR TITLE
[MM-41981] Always install the latest compatible version via the Marketplace

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Since https://github.com/mattermost/mattermost-server/pull/19613 an marketplace install requests always installs the latest version. This PR updates the webapp code to take that into account.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41981

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/19613

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Review by mickmister — APPROVED** [review]
Off topic, but would it be beneficial to allow for a downgrade?

**Comment by hanzei** [comment]
> Off topic, but would it be beneficial to allow for a downgrade?

I don't think this is a short/mid term goal. Some plugins won't support a downgrade or we would have to make it clear for devs that they need to respect semver. Also, allowing that would open up the issue that caused the server PR in the first place.

**Comment by DHaussermann** [comment]
I tested this and see no regressions or changes in functionality. 

However - We may need to clarify the business rules for how Marketplace listings work together with pre-packaged plugins.    
- Currently pre-packaged plugins will supersede marketplace installs.   

- Should the marketplace version take precedence if it is newer than the pre-packaged release? 
I don't see this happening on this PR or on `master` You can see that **Calls** now has a newer release listed in the marketplace but the existing pre-packaged release is the one that is installed.
image
@levb or @wiersgallak do you have any thoughts on this?

**Comment by itao** [comment]
If the minimum server version doesn't conflict then it shouldn't be an issue.

**Comment by DHaussermann** [comment]
Thanks for your thoughts @wiersgallak and @itao. As mentioned in the comment above, there is no direct impact for this PR so, I have created a jira ticket here https://mattermost.atlassian.net/browse/MM-45776 to further address this point.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Regression testing completed
- No issues or changes in behavior found to remote marketplace installs
- No change found to prepackaged plugins
- Created Jira issue for follow-up concern
LGTM!

**Comment by DHaussermann** [comment]
@mickmister can please merge this for us when you have a chance?

**Pull request merged**
