### PR TITLE
MM-14977 Remove metadata backwards compatibility

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
  * Remove API calls for reactions, files and opengraphdata
  * Remove checks for metadata as they should exist if post exists
  * Add metadata empty obj for creating posts and comment
  * Remove waitForHeight callback in size_aware_component

#### Ticket Link
[MM-14977](https://mattermost.atlassian.net/browse/MM-14977)

#### Related Pull Requests
https://github.com/mattermost/mattermost-redux/pull/811

### CODE REVIEW

**Comment by mkraft** [comment]
@sudheerDev Just awaiting the conflicts and test failures.

**Comment by sudheerDev** [comment]
@mkraft Yup. I will be on it mostly before the start of next week. Just does not feel as important as the other TODO's in my list so this took a backseat.

**Comment by sudheerDev** [comment]
@mkraft Will let you know once i turn the dev review label on it.

**Comment by mkraft** [comment]
@sudheerDev Do you mind just re-adding me when it's ready?

**Comment by sudheerDev** [comment]
@migbot @mkraft PR is up for review

**Pull request merged**
