### PR TITLE
[MM-25805] Fix mobile web view hashtags and channel links not working

### PR DESCRIPTION
**Pull request by fmunshi**
#### Summary
- Fixes channel header not following hashtags and channel links in mobile web view

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-25805

#### Screenshots
mobile-hashtag-channel-link

### CODE REVIEW

**Comment by fmunshi** [comment]
ping @sudheerDev for review

**Comment by jgilliam17** [comment]
Thank you @fmunshi 
Tested and it looks good when opening hashtag and channel link via `i` 
Hashtag in the header section on View Info screen is not opening hashtag Search
e.g. Off Topic>View Info>click on the hashtag in Header: section 
Screen Shot 2020-06-18 at 11 58 52 AM

**Comment by fmunshi** [comment]
Hi @jgilliam17 I have updated the PR with the same hashtag and channel linking in the `View Info` modal, so it should be good now

**Pull request merged**
