### PR TITLE
Fixing discard changes confirm modal accesibility for invitation process

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Fixing discard changes confirm modal accesibility for invitation process

#### Ticket Link
[MM-20934](https://mattermost.atlassian.net/browse/MM-20934)

### CODE REVIEW

**Comment by srkgupta** [comment]
Sorry @Willyfrog Re-requested your review by mistake

**Comment by srkgupta** [comment]
@jespino just to confirm that this PR only handles one part of the JIRA ticket, i.e. Fixing discard changes confirm modal accessibility for invitation process. There are still many more things for which we need support for accessibility. Right?

**Comment by jespino** [comment]
@srkgupta Yes, actually I think the most sensible approach is to split the ticket in different tickets, specially because for me is hard to use and debug with JAWS (I don't have a windows computer at home) and I'm using VoiceOver in mac for most of the tasks.

**Comment by srkgupta** [comment]
@jespino honestly it will be too much to add these issues as separate ticket. Generally each section is added as a single ticket, something like this: https://mattermost.atlassian.net/browse/MM-22256. We can have multiple PRs for single JIRA ticket.

**Pull request merged**
