### PR TITLE
Replacing blacklist with blocklist

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Replacing blacklist with blocklist

Jira ticket: https://mattermost.atlassian.net/browse/MM-27193

### CODE REVIEW

**Comment by hanzei** [comment]
Drive by comment: Is the decision to use certain terms like "Blocklist" worth documenting somewhere e.g. in https://developers.mattermost.com/contribute/getting-started/?

**Comment by jespino** [comment]
@hanzei I think would be great to have some documentation around it, but we should decide what is the things that we want to try avoid in our code, blacklist was an easy one, but there are other. @jasonblais What do you think? is better to add something now about blacklist and grow from there, or is better to wait until have something more organized and write a more clear policy?

**Comment by jasonblais** [comment]
I would wait until we've formalized a policy

**Comment by hanzei** [comment]
I'm fine with waiting for a well defined policy as long it get added eventually.

**Pull request merged**
