### PR TITLE
MM-38745: DND improvements

### PR DESCRIPTION
**Pull request by SharathHuddar**
#### Summary
Add "Don't Clear" option to DND settings and update copy

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38745
Closes https://github.com/mattermost/mattermost-server/issues/19134

#### Screenshots
|  before  |  after  |
|---|---|
| Screenshot 2021-12-24 at 12 54 08 PM | Screenshot 2022-01-23 at 6 04 16 PM |

#### Release Note

```release-note
Add "Don't Clear" option to DND settings and update copy

```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@SharathHuddar you can make this PR as draft while you are working on. Feel free to ignore it though

**Comment by hmhealey** [comment]
Thanks for the work on this so far! Let us know if you have any questions or when you want us to start looking at this

**Comment by SharathHuddar** [comment]
@hmhealey I will let you know once I test this on my local and add the SS and release notes. Have been busy with my day job as well 😅

**Comment by hmhealey** [comment]
Yep, that's totally fine. Work comes first 🙂

**Comment by SharathHuddar** [comment]
@hmhealey can you please take a look at this ?

**Comment by SharathHuddar** [comment]
@hmhealey can you please take a look at this ?

**Comment by esethna** [comment]
Thanks @SharathHuddar! Looking good. I think there are two requirements missing from the ticket if you can take a look: 
image

https://mattermost.atlassian.net/browse/MM-38745

**Review by esethna — CHANGES_REQUESTED** [review]
Thanks @SharathHuddar! Looking good. I think there are two requirements missing from the ticket if you can take a look: 
image

https://mattermost.atlassian.net/browse/MM-38745

**Comment by hmhealey** [comment]
The code changes look good so far, but I'll hold off on submitting my review for now

**Comment by esethna** [comment]
@SharathHuddar checking in if you need any help with the comments above? ^ Would love to see these changes in the product 

cc// FYI @laneycs this is a separate feature improvement around DND

**Comment by SharathHuddar** [comment]
@esethna Done with the changes needed to show the DND expiry time. Figuring out how to handle the mobile case

**Review by laneycs — APPROVED** [review]

**Comment by esethna** [comment]
Nice! cc// @hmhealey @BenCookie95 @furqanmlk review when possible, thanks!

**Comment by furqanmlk** [comment]
@SharathHuddar can you please resolve the conflict please ?

**Review by BenCookie95 — APPROVED** [review]
Nice work, code looks good to me! Just need to fix the pipeline

**Review by furqanmlk — COMMENTED** [review]
@SharathHuddar  This [issue](https://github.com/mattermost/mattermost-webapp/pull/9747) has been fixed. I still see the bug in your PR.

https://user-images.githubusercontent.com/6909890/153504814-786fa2cb-a0b2-4c39-b0f3-70be1060557a.mp4

**Review by hmhealey — APPROVED** [review]
A couple conflicts need to be resolved, but this looks good to me!

**Comment by hmhealey** [comment]
I'm not sure why the i18n-check step is failing since the lines that it's saying are different look the same. Maybe if you edited those lines manually, your editor is doing something funny with the whitespace. Perhaps you could try running `make i18n-extract` to have the tool update `en.json` for you?

**Comment by hmhealey** [comment]
@esethna Was there still anything you wanted to review on this? It sounds like you were happy with this, but I just wanted to double check since your last review requested changes.

@SharathHuddar Would you like help resolving that issue? I see there's also another conflict. I guess someone else is working on this same area of the code as well

**Comment by SharathHuddar** [comment]
@hmhealey I'm not able to figure out why i18n-check keeps failing. Can you please help me out?

**Comment by hmhealey** [comment]
I've pushed a commit to revert the accidental changes to en.json. I'm not sure why your `make i18n-extract` still removed these strings, but that should be fixed now.

@furqanmlk Are you still seeing that bug? I'm not able to reproduce it on either Firefox or Chrome
Screen Shot 2022-02-22 at 2 40 32 PM

**Comment by hmhealey** [comment]
@SharathHuddar Now that that's fixed, it looks like there's an actual test failure

**Comment by furqanmlk** [comment]
Hi @SharathHuddar can you fix the build

**Comment by esethna** [comment]
@SharathHuddar just checking in, how's this going?

**Comment by SharathHuddar** [comment]
Hey, I  thought someone else was going to pick this task up

**Comment by darkLord19** [comment]
@esethna I'll probably take a different approach which is more server centric. I may just cherry-pick some design related commits from this but so we can close this PR.

**Comment by esethna** [comment]
Sounds good, thanks @darkLord19

**Pull request closed without merging**
