### PR TITLE
MM-39199 Fix permissions for reactions buttons

### PR DESCRIPTION
**Pull request by hmhealey**
This fixes some weirdness with the permissions around emoji reactions. The following weird cases are fixed:
1. Non-admins weren't able to click on existing reactions to add them in the Town Square with a license. This seems to be a side effect of https://github.com/mattermost/mattermost-webapp/pull/8541
2. Users without the permission to react to a post wouldn't be able to click on existing reactions, but they would see the + button with the emoji picker. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39199

#### Release Note
```release-note
Fix emoji reaction buttons on posts not respecting user permissions
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @hmhealey 
Seeing one issue, +emoji icon is missing after first reaction has been added. This is reproing in all cases, even when all channel permissions are enabled.
Screen Shot 2021-11-03 at 10 21 22 AM

**Comment by hmhealey** [comment]
@jgilliam17 That should be fixed now. It turns out I was mixing up things called `canAddReaction` and `canAddReactions` when passing around permissions.

**Pull request merged**
