### PR TITLE
[MM-42744] Top playbooks insight

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Adding new widget for playbooks

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42744

#### Related Pull Requests
- https://github.com/mattermost/mattermost-plugin-playbooks/pull/1398
- 
#### Screenshots
Screen Shot 2022-08-10 at 4 33 24 PM

#### Release Note

```release-note
Adding new top playbooks widgets to insights
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by plant99 — APPROVED** [review]

**Comment by amyblais** [comment]
Assigned to Ben to fix conflicts.

**Review by matthewbirtch — APPROVED** [review]
Thanks for the great work on this @BenCookie95!

**Review by furqanmlk — APPROVED** [review]
Thanks @BenCookie95 for fixing issue very quick.

Working as expected

**Pull request merged**
