### PR TITLE
Exposing the Menu groups and items as static class properties

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Exposing the Menu groups and items as static class properties.

The idea is to change the Menu API to expose it as more visually scoped to the Menu component itself. so now the items of the menus are expressed like `Menu.ItemXXX` when that items are defined as part of the widgets library.

#### Ticket Link
[MM-17863](https://mattermost.atlassian.net/browse/MM-17863)

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @jespino 

I've tested as per the list of areas to test on the [Jira ticket](https://mattermost.atlassian.net/browse/MM-17909) and here are my findings:

1. This can be tested post-merge or, if you'd like to help set up on the spinwick, I can test

**Comment by lindy65** [comment]
Thanks @jespino

I've tested as per the list of areas to test on the [Jira ticket](https://mattermost.atlassian.net/browse/MM-17863) and here are my findings:

1. This can be tested post-merge or, if you'd like to help set up on the spinwick, I can test on the spinwick:
>the group details menu (with group sync enabled and with groups configured)

2. The "the admin console users management, the dropdown for actions of the user" is affected by the bug in https://mattermost.atlassian.net/browse/MM-17909. Once the fix is merged, can you help update the spinwick?

3. In the channel dropdown menu, if I MUTE the channel, the muted icon is now displayed way over on the right instead of just to the right of the channel name

image

4. In the hamburger menu (main menu) > Manage members, clicking on the dropdown next to a member in the Members modal does nothing (no options displayed). I think this was affected by this PR as you mention checking the "Manage Members" for the team dropdown for the members and this is what is not working.

image

5. In the hamburger menu (main menu) > Integrations > Bot Accounts, the "Add Bot Account" button is missing. Not sure if this is related to this PR?

image

**Comment by jespino** [comment]
@lindy65 

1. Ok to test it after merge
2. Yes, we can wait until is fixed in master and merge it here.
3. Looks like i can reproduce it in other branches, so, shouldn't be related to my PR.
4. Perfect, lets wait until is fixed in master.
5. Not shown in other branch, so shouldn't be related to this PR.

**Comment by lindy65** [comment]
Thanks @jespino 

- I'll wait for you to update the spinwick with the fixes for 1) 2) and 4) and then re-test. Please ping me on this PR when ready :)

- For 3) I have filed https://mattermost.atlassian.net/browse/MM-18037

- For 5) I realised this is not a bug.  I needed to ENABLE Bot Account creation in the System Console for this button to show up:
image

**Comment by lindy65** [comment]
Thanks @jespino 

2. and 4. are fixed - working as expected

1. will be tested post merge

**Pull request merged**
