### PR TITLE
[MM-29949] Add extra space for team name and user name on new sidebar

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Team and usernames in the sidebar header were being truncated unnecessarily, this PR increases the `max-width` on those `divs` to account for the extra width on the new sidebar.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29949

#### Screenshots
**Before:**
Screen Shot 2020-10-28 at 10 49 06 AM

**After:**
Screen Shot 2020-10-28 at 10 49 22 AM

### CODE REVIEW

**Review by stevemudie — COMMENTED** [review]
Unfortunately, the fix appears to have had the opposite effect.

Before, a 15 character team name wouldn't fit with the new sidebar enabled but would if it was the old sidebar. Now the reverse is true here on the Spinwick.

**Comment by devinbinnie** [comment]
> Unfortunately, the fix appears to have had the opposite effect.
> 
> Before, a 15 character team name wouldn't fit with the new sidebar enabled but would if it was the old sidebar. Now the reverse is true here on the Spinwick.

@stevemudie So there was no change made on the old sidebar, so something else must have changed here. It's possible the font size was made bigger. It also makes sense that there's less space for a team name on the old sidebar as it's only 220px wide vs the new one at 240px wide.

How should we proceed here?

**Comment by stevemudie** [comment]
@devinbinnie Honestly, I'm not sure what the next step is. Even though the old sidebar is narrower it displays the full 15 characters now on the latest release. So while your fix works for when the exp. sidebar is in place we'll be right back at it for when it's disabled in a new ticket and PR I expect. 

Piled on top of this is the larger question of https://mattermost.atlassian.net/browse/MM-29946 which addresses the overall limit to the team name and https://mattermost.atlassian.net/browse/MM-27400 which has to do with the lack of a tooltip when hovering over truncated team names.

@marianunez what's your take?

**Comment by hmhealey** [comment]
Perhaps something else changed between the latest release and master here? I tested locally on the latest master, and I'm still seeing that 15 character name cut off.
Screen Shot 2020-10-30 at 3 36 40 PM

**Comment by devinbinnie** [comment]
@stevemudie Any thoughts on Harrison's comment?

**Comment by stevemudie** [comment]
@devinbinnie @hmhealey I'm in the midst of RC tests on 5.29.0-rc1 right now and it's the direct opposite of what you see in the spinwick here. So unfortunately, no, I'm not sure what to think.

Perhaps this should wait until https://mattermost.atlassian.net/browse/MM-29946 is decided upon?

**Comment by stylianosrigas** [comment]
Hey guys the update of the spinwick is failing with the following error:
```json
{"level":"info","ts":1604337863.0604606,"caller":"app/server.go:226","msg":"Server is initializing..."}
{"level":"info","ts":1604337863.0607593,"caller":"app/web_hub.go:83","msg":"Starting websocket hubs","number_of_hubs":4}
{"level":"warn","ts":1604337863.0608985,"caller":"app/server.go:235","msg":"Sentry reporting is enabled, but SENTRY_DSN is not set. Disabling reporting."}
{"level":"info","ts":1604337863.0615416,"caller":"utils/i18n.go:90","msg":"Loaded system translations","for locale":"en","from locale":"/mattermost/i18n/en.json"}
{"level":"debug","ts":1604337863.0620747,"caller":"utils/html.go:30","msg":"Parsing server templates","templates_directory":"/mattermost/templates"}
{"level":"info","ts":1604337863.065127,"caller":"sqlstore/supplier.go:235","msg":"Pinging SQL","database":"master"}
{"level":"debug","ts":1604337863.065391,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":0}
{"level":"debug","ts":1604337863.0654273,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":1}
{"level":"debug","ts":1604337863.065454,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":2}
{"level":"debug","ts":1604337863.0654733,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":3}
{"level":"info","ts":1604337863.075647,"caller":"sqlstore/supplier.go:235","msg":"Pinging SQL","database":"replica-0"}
{"level":"error","ts":1604337863.407903,"caller":"sqlstore/supplier.go:909","msg":"Failed to create index","error":"pq: relation \"idx_threads_channel_id\" does not exist","error":"pq: column \"channelid\" does not exist"}
```

**Comment by devinbinnie** [comment]
> Hey guys the update of the spinwick is failing with the following error:
> 
> ```json
> {"level":"info","ts":1604337863.0604606,"caller":"app/server.go:226","msg":"Server is initializing..."}
> {"level":"info","ts":1604337863.0607593,"caller":"app/web_hub.go:83","msg":"Starting websocket hubs","number_of_hubs":4}
> {"level":"warn","ts":1604337863.0608985,"caller":"app/server.go:235","msg":"Sentry reporting is enabled, but SENTRY_DSN is not set. Disabling reporting."}
> {"level":"info","ts":1604337863.0615416,"caller":"utils/i18n.go:90","msg":"Loaded system translations","for locale":"en","from locale":"/mattermost/i18n/en.json"}
> {"level":"debug","ts":1604337863.0620747,"caller":"utils/html.go:30","msg":"Parsing server templates","templates_directory":"/mattermost/templates"}
> {"level":"info","ts":1604337863.065127,"caller":"sqlstore/supplier.go:235","msg":"Pinging SQL","database":"master"}
> {"level":"debug","ts":1604337863.065391,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":0}
> {"level":"debug","ts":1604337863.0654273,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":1}
> {"level":"debug","ts":1604337863.065454,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":2}
> {"level":"debug","ts":1604337863.0654733,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":3}
> {"level":"info","ts":1604337863.075647,"caller":"sqlstore/supplier.go:235","msg":"Pinging SQL","database":"replica-0"}
> {"level":"error","ts":1604337863.407903,"caller":"sqlstore/supplier.go:909","msg":"Failed to create index","error":"pq: relation \"idx_threads_channel_id\" does not exist","error":"pq: column \"channelid\" does not exist"}
> ```

@stylianosrigas Shouldn't be an issue with this PR, this is purely a front-end styling change. Maybe it'll go away if I re-instantiate the SpinWick?

**Comment by stylianosrigas** [comment]
> > Hey guys the update of the spinwick is failing with the following error:
> > ```json
> > {"level":"info","ts":1604337863.0604606,"caller":"app/server.go:226","msg":"Server is initializing..."}
> > {"level":"info","ts":1604337863.0607593,"caller":"app/web_hub.go:83","msg":"Starting websocket hubs","number_of_hubs":4}
> > {"level":"warn","ts":1604337863.0608985,"caller":"app/server.go:235","msg":"Sentry reporting is enabled, but SENTRY_DSN is not set. Disabling reporting."}
> > {"level":"info","ts":1604337863.0615416,"caller":"utils/i18n.go:90","msg":"Loaded system translations","for locale":"en","from locale":"/mattermost/i18n/en.json"}
> > {"level":"debug","ts":1604337863.0620747,"caller":"utils/html.go:30","msg":"Parsing server templates","templates_directory":"/mattermost/templates"}
> > {"level":"info","ts":1604337863.065127,"caller":"sqlstore/supplier.go:235","msg":"Pinging SQL","database":"master"}
> > {"level":"debug","ts":1604337863.065391,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":0}
> > {"level":"debug","ts":1604337863.0654273,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":1}
> > {"level":"debug","ts":1604337863.065454,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":2}
> > {"level":"debug","ts":1604337863.0654733,"caller":"app/web_hub.go:413","msg":"Hub is starting","index":3}
> > {"level":"info","ts":1604337863.075647,"caller":"sqlstore/supplier.go:235","msg":"Pinging SQL","database":"replica-0"}
> > {"level":"error","ts":1604337863.407903,"caller":"sqlstore/supplier.go:909","msg":"Failed to create index","error":"pq: relation \"idx_threads_channel_id\" does not exist","error":"pq: column \"channelid\" does not exist"}
> > ```
> 
> @stylianosrigas Shouldn't be an issue with this PR, this is purely a front-end styling change. Maybe it'll go away if I re-instantiate the SpinWick?

Maybe @devinbinnie . Try to remove the spinwick label and after some seconds add it back.

**Review by sudheerDev — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by devinbinnie** [comment]
> @devinbinnie @hmhealey I'm in the midst of RC tests on 5.29.0-rc1 right now and it's the direct opposite of what you see in the spinwick here. So unfortunately, no, I'm not sure what to think.
> 
> Perhaps this should wait until https://mattermost.atlassian.net/browse/MM-29946 is decided upon?

@stevemudie Since the above ticket is backlogged, what should become of this PR?

**Comment by stevemudie** [comment]
> > Perhaps this should wait until https://mattermost.atlassian.net/browse/MM-29946 is decided upon?
> 
> @stevemudie Since the above ticket is backlogged, what should become of this PR?
@devinbinnie I'm really not sure.
@marianunez what do you think?

**Comment by marianunez** [comment]
If I'm following this thread correctly and as I saw on the PR test server, this PR makes all the 15 char visible for the new sidebar and I don't see a regression when disabling to the old sidebar on this PR given that it still cuts off the name the same as it does in the latest release. In either case, my understanding is that we are starting to move away from maintaining the old sidebar so I would be more inclined to provide the fix for that first - we could get a PM to weigh on this assumption. 

From the cloud side, the inconsistencies between the team name created by cloud onboarding and the current limit of 15 will be addressed later in [MM-29946](https://mattermost.atlassian.net/browse/MM-29946) but shouldn't be a blocker for this improvement.

**Review by stevemudie — APPROVED** [review]
Thanks @marianunez

**Pull request merged**
