### PR TITLE
Update p-queue and jest

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR updates p-queue, that has no breaking changes in the code but we need to bump the jest version as well in order to handle the import issues.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34914

#### Release Note

```release-note
Updated npm packages 'p-queue' and 'jest'
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by hmhealey** [comment]
Looks good from testing the one place I know that p-queue is used, preloading unread channels on page load. I'll hold off on approving until the issue with the Jest import is sorted out since it still appears to be happening

**Comment by nevyangelova** [comment]
@hmhealey updated

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Tested, looks good to merge - pending e2es
Verified around what Harrison mentioned preloading unread channels on page load - works as expected.

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
