### PR TITLE
Use React lazy and Suspense instead of bundle-loader and AsyncComponent

### PR DESCRIPTION
**Pull request by anindha**
#### Summary

Replace bundle-loader and AsyncComponent with React.Lazy and React.Suspense.

This is a rework of #3981  The issue with the previous PR was that it only had a Suspense component at the top level so when a child component was loading it showed a blank screen.

This version works identically to the current version where each lazy loaded component is wrapped in its own AsyncComponent, but now using React.Suspense.

There is no ticket currently, but was discussed in a developer meeting on Oct 9th.

#### Advantages of this approach:
- Easier for new developers to understand standard React way of lazy loading rather than proprietary code.
- Drops a an unneeded library.
- It makes it easy for further UX improvements such as eager loading and adding loaders

### Ticket 
https://mattermost.atlassian.net/browse/MM-19763

#### Testing
- Ran production build locally testing bundle sizes, no difference
- Ran local production build against community server, no difference
- Checked bundle size using [webpack monitor](http://webpackmonitor.com/), no difference

Thanks to @sudheerDev for his help with this!

### CODE REVIEW

**Comment by anindha** [comment]
@hanzei Would it be possible to please request someone to help me with this? I was working with @sudheerDev but he might have gotten busy. I can discuss in the next developer meeting otherwise and see if someone is willing to help.

**Comment by hanzei** [comment]
@anindha I will reach to to @sudheerDev about this.

**Comment by sudheerDev** [comment]
@anindha hey, Sorry i didn't realise that this is up for review. Code looks good to me. This is on my radar. I will go though the spinmint later today and if i dont find any issue this is good to go IMO

**Comment by levb** [comment]
@sudheerDev @lindalumitchell do I need to assign a specific QA for this?

**Comment by saturninoabril** [comment]
Thanks @levb, I'll look into this.

**Comment by saturninoabril** [comment]
@sudheerDev Feel free to merge.

**Comment by anindha** [comment]
@sudheerDev I have rebased. Ready to merge.

**Pull request merged**
