### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by chetanyakan**
#### Summary
- Remove `has redux changes` link option as there will be no changes to redux repo.

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Good catch. That template is crowded enough as it is with relevant info, so removing irrelevant stuff is an excellent idea.

**Comment by hanzei** [comment]
Thanks @chetanyakan :+1:

**Pull request merged**
