### PR TITLE
[MM-20540] Migrate 'components/user_settings/advanced' module and associated tests to TypeScript 

### PR DESCRIPTION
**Pull request by jakubnovak998**
#### Summary
- Rename the files to their associated TypeScript extensions (ie. js to ts, jsx to tsx)
- Update any components using those to the correct imports
- Fix any errors generated by the TypeScript compiler. You can run make check-types to display any errors.

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/13701

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for opening this PR @jakubnovak998 :+1:

CI complains about an issue with the types:
```

components/user_settings/advanced/user_settings_advanced.tsx:72:9 - error TS2741: Property 'serverError' is missing in type '{ preReleaseFeatures: { MARKDOWN_PREVIEW: { label: string; description: string; }; }; settings: { send_on_ctrl_enter: string; code_block_ctrl_enter: boolean; formatting: string; join_leave: string; }; ... 4 more ...; showDeactivateAccountModal: boolean; }' but required in type 'Readonly<State>'.

72         this.state = this.getStateFromProps();
           ~~~~~~~~~~

  components/user_settings/advanced/user_settings_advanced.tsx:65:5
    65     serverError: string;
           ~~~~~~~~~~~
    'serverError' is declared here.

components/user_settings/user_settings.tsx:96:25 - error TS2322: Type '{ activeSection: string | undefined; updateSection: (section: string) => void; closeModal: () => void; collapseModal: () => void; }' is not assignable to type '(IntrinsicAttributes & Pick<unknown, never>) | (IntrinsicAttributes & Pick<Pick<unknown, never>, never> & Pick<InferProps<unknown>, never>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>)'.
  Property 'activeSection' does not exist on type '(IntrinsicAttributes & Pick<unknown, never>) | (IntrinsicAttributes & Pick<Pick<unknown, never>, never> & Pick<InferProps<unknown>, never>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>)'.

96                         activeSection={this.props.activeSection}
                           ~~~~~~~~~~~~~

```

and a linter issue
```
/root/mattermost/mattermost-webapp/components/user_settings/advanced/user_settings_advanced.test.tsx
  43:37  error  Missing trailing comma                                           comma-dangle
  71:9   error  Do not use "// @ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment
  71:9   error  Expected line before comment                                     lines-around-comment
  91:9   error  Do not use "// @ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment
  91:9   error  Expected line before comment                                     lines-around-comment

/root/mattermost/mattermost-webapp/components/user_settings/advanced/user_settings_advanced.tsx
  112:39  error  Missing trailing comma                                           comma-dangle
  691:25  error  Expected line before comment                                     lines-around-comment
  691:25  error  Do not use "// @ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment
  693:25  error  Do not use "// @ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment
  693:25  error  Expected line before comment                                     lines-around-comment
  695:25  error  Expected line before comment                                     lines-around-comment
  695:25  error  Do not use "// @ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment
```

Let me know if you need help resolving these.

**Comment by hanzei** [comment]
Thanks for fixing the linter issues :+1: 

Some types seem to be not compatible: 
```
components/user_settings/advanced/user_settings_advanced.test.tsx:72:34 - error TS2322: Type '{ actions: { updateUserActive: Mock<Promise<{}>, []>; savePreferences: Mock<any, any>; revokeAllSessionsForUser: Mock<any, any>; }; currentUser: { id: string; username: string; locale: string; auth_service: string; timezone: { ...; }; }; ... 10 more ...; enableUserDeactivation: boolean; }' is not assignable to type 'Readonly<Props>'.
  The types returned by 'actions.updateUserActive(...)' are incompatible between these types.
    Type 'Promise<{}>' is not assignable to type 'Promise<{ error: ServerError; }>'.
      Property 'error' is missing in type '{}' but required in type '{ error: ServerError; }'.

72         const wrapper = shallow(<AdvancedSettingsDisplay {...props}/>);
                                    ~~~~~~~~~~~~~~~~~~~~~~~

  components/user_settings/advanced/user_settings_advanced.tsx:52:69
    52         updateUserActive: (id: string, active: boolean) => Promise<{error: ServerError}>;
                                                                           ~~~~~
    'error' is declared here.

components/user_settings/advanced/user_settings_advanced.test.tsx:92:34 - error TS2322: Type '{ actions: { revokeAllSessionsForUser: () => Promise<{ error: { message: string; }; }>; savePreferences: Mock<any, any>; updateUserActive: Mock<any, any>; }; currentUser: { ...; }; ... 10 more ...; enableUserDeactivation: boolean; }' is not assignable to type 'Readonly<Props>'.
  The types returned by 'actions.revokeAllSessionsForUser(...)' are incompatible between these types.
    Type 'Promise<{ error: { message: string; }; }>' is not assignable to type 'Promise<{ error: ServerError; data: any; }>'.
      Property 'data' is missing in type '{ error: { message: string; }; }' but required in type '{ error: ServerError; data: any; }'.

92         const wrapper = shallow(<AdvancedSettingsDisplay {...props}/>);
                                    ~~~~~~~~~~~~~~~~~~~~~~~

  components/user_settings/advanced/user_settings_advanced.tsx:53:80
    53         revokeAllSessionsForUser: (id: string) => Promise<{error: ServerError; data: any}>;
                                                                                      ~~~~
    'data' is declared here.

components/user_settings/advanced/user_settings_advanced.tsx:72:9 - error TS2741: Property 'serverError' is missing in type '{ preReleaseFeatures: { MARKDOWN_PREVIEW: { label: string; description: string; }; }; settings: { send_on_ctrl_enter: string; code_block_ctrl_enter: boolean; formatting: string; join_leave: string; }; ... 4 more ...; showDeactivateAccountModal: boolean; }' but required in type 'Readonly<State>'.

72         this.state = this.getStateFromProps();
           ~~~~~~~~~~

  components/user_settings/advanced/user_settings_advanced.tsx:65:5
    65     serverError: string;
           ~~~~~~~~~~~
    'serverError' is declared here.

components/user_settings/user_settings.tsx:96:25 - error TS2322: Type '{ activeSection: string | undefined; updateSection: (section: string) => void; closeModal: () => void; collapseModal: () => void; }' is not assignable to type '(IntrinsicAttributes & Pick<unknown, never>) | (IntrinsicAttributes & Pick<Pick<unknown, never>, never> & Pick<InferProps<unknown>, never>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>)'.
  Property 'activeSection' does not exist on type '(IntrinsicAttributes & Pick<unknown, never>) | (IntrinsicAttributes & Pick<Pick<unknown, never>, never> & Pick<InferProps<unknown>, never>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>) | (IntrinsicAttributes & ... 2 more ... & Partial<...>)'.

96                         activeSection={this.props.activeSection}
                           ~~~~~~~~~~~~~
```

**Comment by hanzei** [comment]
@jakubnovak998 Let me know if you need any help with the failures above.

**Comment by jfrerich** [comment]
Hi @jakubnovak998, please let myself or @hanzei know if we can assist you with fixing the remaining errors :)

**Comment by devinbinnie** [comment]
Closing this PR as inactive, @jakubnovak998 let us know if you plan on finishing this up.

**Pull request closed without merging**
