### PR TITLE
Improve RHS toggle state

### PR DESCRIPTION
**Pull request by antonbuks**
#### Summary

I don't know if this is intended but the toggle for the RHS sidebar only has the active state when the RHS is on the general info tab. It also doesn't hide the sidebar if you are on another tab (users for example) instead reopening the general info tab.

I think everything in the sidebar is technically channel info so I think it's a little more user friendly to use this button as a global toggle and the caret to go back to the general tab (currently both the caret and the toggle will go back to the general info tab so it's a duplication).

```release-note
NONE
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]
Thanks for your contribution @antonbuks! Code looks neat 👍🏻 
I'm not sure if I like this change or not from a UX perspective, changing this makes it more difficult to access the RHS. If you click on the `File` icon below the channel name, or open a thread, and want to access the channel info panel, you have to click twice on the button now (once to close the RHS, once to open channel info RHS).
I approve the changes from a code perspective, and I'll let @matthewbirtch review the UX!

**Comment by antonbuks** [comment]
@JulienTant Thank you for the feedback, you're right I didn't notice these two edge cases. I think for the threads case I can make a condition in the code to keep the old behaviour just for the threads view as it's the only thing in RHS which is not technically channel info. For the files case I can see that the files tab that is opened from the channel header doesn't have the caret that is there if you open it directly from the general tab, I could potentially add the caret for the case where it's opened from the header as well.

In any case I'll wait for the feeback from Matthew and I can implement the improvements if this change is wanted.

**Comment by matthewbirtch** [comment]
So, a few thoughts from me:

1. The Info toggle button should not be highlighted when the following RHS views are open:
    - Thread
    - Search results
    - Recent Mentions
    - Saved posts
    - Any RHS view used by plugins or apps (e.g. playbooks RHS)
    - Any other RHS view unrelated to channel info....

2. The only views that make sense for the info icon button to be highlighted are anything related to channel info and its subviews:
    - Channel info main view
    - Channel Members
    - Files in channel
    - Pinned messages

3. Another problem is if you access the channel Members view directly from the icon under the channel name, we don't have a back button in this specific case. The back button currently only shows if you have accessed these subviews from the main channel info view. In order to do point no. 2 above, we would need to change this to always show the back arrow on these subviews regardless of where it was accessed (for easy access back to the channel info view).

I think if these points were addressed we could see how it feels and determine whether it's a sound solution. I'm open to the idea as long as these are addressed.

**Review by nevyangelova — APPROVED** [review]

**Comment by antonbuks** [comment]
sorry, had to leave for vacation before I had a chance to finish this off, will try to wrap it up this week 🙏

**Comment by JulienTant** [comment]
> sorry, had to leave for vacation before I had a chance to finish this off, will try to wrap it up this week 🙏

Hey thanks @antonbuks!

**Comment by matthewbirtch** [comment]
Thanks @antonbuks. I see now that the Recent Mentions, Saved, Search results RHS views always have a back button now that takes me to the channel info view for the active channel. This shouldn't be the case. These views should have the back button that leads to the channel info RHS view at all. The only ones that should have the back button should be subviews of the info panel (members, pinned, files, etc).

**Comment by matthewbirtch** [comment]
@antonbuks it looks like the back button has properly been removed from the recent mentions/saved/search results RHS views, but now the members subview doesn't have a back button

image

**Comment by antonbuks** [comment]
@matthewbirtch good catch ! Latest commit should fix it

**Comment by matthewbirtch** [comment]
Now I wonder if we should make the info icon button always open or close the RHS. Right now if I'm on a subview of the channel info, the `i` icon returns back to the parent info view, but the back arrow is there to do that job. I think the `i` should only be a toggle to open or close the info RHS entirely - never to return back to the main info view. Thoughts?

**Comment by antonbuks** [comment]
@matthewbirtch I like the idea, the only issue I see is when you open the first view, if you open anything that's not the general info view through the header for example (Files, Pins etc), you have no back `<` and the only way to go to general info is to close and reopen via the `i` button.

Maybe if an `i` button was added to the header buttons for the channel then the right channel info button could act as just a switch, but then there is no need for this button anymore since the rhs has a `X` on the right to close. This is the way slack does it with rhs panels, a single `X` close button on the right.


Screenshot 2022-07-29 at 09 43 43

**Comment by matthewbirtch** [comment]
Moving the info button would be out of scope for this IMO. That's another topic altogether, so let's leave it where it is currently in the product for now.

However, I would be ok with making the `i` icon act more like a switch and less like a toggle. I like the behavior we have now, but let's keep the position of the button where it was originally.

**Review by matthewbirtch — APPROVED** [review]
I think this works @antonbuks. Thanks! We should definitely get QA to review now. @stevemudie would this be in your purview?

**Comment by stevemudie** [comment]
@antonbuks This looks good! Thank you for all of your work on this.

I only need to run it through E2E then I'll be able to approve it assuming everything goes well there.

It shouldn't take long. ツ

**Review by stevemudie — APPROVED** [review]
@antonbuks This is all set!

**Comment by antonbuks** [comment]
If someone could merge this please I don't have permissions :)

**Comment by JulienTant** [comment]
All set, thank you @antonbuks for your contribution!

**Pull request merged**
