### PR TITLE
[MM-42443]: fix selectionRange updates in edit_post component

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
Fixed updating the inputs `selectionRange` by using the state to determine whenever it has to be manually updated.

This should go hand in hand with #10034 since changes in this PR might affect it directly.

I discovered that **only** italic markdown is being handled differently and the italic markers are excluded from the selection. I would propose to add other markers as well (e.g. **bold**, ~~strikethrough~~, etc.) and let the manual update on selectionRanges be handled by the component (maybe write a getter function in Utils, but let the actual updates to the input be handled inside the component)

#### Ticket Link
[MM-42443](https://mattermost.atlassian.net/browse/MM-42443)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
fixes markdown insert link behavior in edit post input field
```

### CODE REVIEW

**Comment by michelengelen** [comment]
@amyblais 2/3 for cloud release

**Review by matthewbirtch — APPROVED** [review]
Works great @michelengelen

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge - pending e2e report
- Verified insert link keyboard shortcut is working as expected in edit post textbox.

**Comment by jgilliam17** [comment]
@michelengelen 
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/174033-f2088fb-onprem-ent-webapp-pr-10035-mattermost/mm-ee-testf2088fb/mochawesome.html) looks good overall
One test failure may be related - this test case is passing when testing manually 
MM-T2139

**Comment by michelengelen** [comment]
hi @jgilliam17 ... I adjusted the script to wait a bit before searching for the `postMesage_<postId>` container ... it now should not fail anymore.

**Comment by jgilliam17** [comment]
Thanks @michelengelen Can you please update the branch so I can re-run the e2es. Thanks

**Comment by michelengelen** [comment]
@jgilliam17 merged master just now ... feel free to re-run whenever you like!

**Comment by jgilliam17** [comment]
@michelengelen unfortunately, the same test is failing again. See report [here](https://github.com/mattermost/mattermost-webapp/pull/10035#issuecomment-1076530568)

**Comment by michelengelen** [comment]
@jgilliam I increased the wait time for the test and it runs on my local machine just fine.

**Comment by jgilliam17** [comment]
E2E test running [here](https://automation-dashboard.vercel.app/cycles/e6f61c54-305e-4f9d-8aac-5ba404469892)

**Comment by jgilliam17** [comment]
Thanks @michelengelen I am starting to think this may be a flaky test MM-T2139, full report [here](https://mattermost-cypress-report.s3.amazonaws.com/174960-0aa1c59-onprem-ent-webapp-pr-10035-mm-ee-test:0aa1c59/mochawesome.html) 
@saturninoabril thoughts?

**Review by hmhealey — APPROVED** [review]

**Comment by saturninoabril** [comment]
I think most of those were recently addressed, especially by https://github.com/mattermost/mattermost-webapp/pull/10053. I'll update this PR then will run E2E again. Thanks Jelena!

**Comment by saturninoabril** [comment]
Oopss, sorry, I thought other failed tests from the report. I'll take a look what's going on with MM-T2139.

**Comment by saturninoabril** [comment]
E2E test at https://automation-dashboard.vercel.app/cycles/241b1375-0313-4088-81ec-4908c92abf34

**Review by calebroseland — APPROVED** [review]

**Comment by saturninoabril** [comment]
@jgilliam17 MM-T2139 should be good now. Please take a look again.

**Comment by jgilliam17** [comment]
Thanks @michelengelen - looks good to merge.
And thank you @saturninoabril for taking care of the flaky test. 
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/175070-c19d92d-onprem-ent-webapp-pr-10035-mm-ee-test:c19d92d/mochawesome.html)looks good.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
