### PR TITLE
Cypress/E2E: Fix MM-T1752 enable account creation

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Fixed MM-T1752 enable account creation
- Fixed focus on password field on email verification

Note: 
- submitted on top of https://github.com/mattermost/mattermost-webapp/commit/870033516371bdbb7e88068dbe8274f28284ab29, will rebase once merged.
- see https://github.com/mattermost/mattermost-webapp/commit/40583eab4c5c593c91fa02be4b174182047c77bb for changes related to this PR.

#### Ticket Link
none, failed on daily Cypress run

### CODE REVIEW

**Comment by josephbaylon** [comment]
@saturninoabril Everything else passed but I'm getting this failure consistently (MM-T1770). I made sure I'm running your code changes. Seems like the server has injects a default value

Screen Shot 2021-02-01 at 9 44 14 AM

**Review by furqanmlk — COMMENTED** [review]
image

image

image

I am also getting same error as @josephbaylon 
image

image

**Comment by saturninoabril** [comment]
@josephbaylon @furqanmlk Thank you for testing! I had the last fix for server with cloud license and missed to get back to E20. It should be good now. Please take a look again.

**Review by josephbaylon — APPROVED** [review]
LGTM. Failing test is passing locally. Thanks @saturninoabril !!

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril 

All test cases passed ✅ 

image

**Pull request merged**
