### PR TITLE
[MM-38376]fix-app-crash-on-root-post-delete-from-global-threads

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Webapp crashes when the root post is deleted from Threads RHS
Note: All other scenarios of post delete, as well as global threads RHS, require testing.

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-38376

#### Related Pull Requests
``None``

#### Screenshots
|  before  |  after  |
|----|----|
| [https://www.loom.com/share/2c626dd0418444999390b2ed932cd719](https://www.loom.com/share/2c626dd0418444999390b2ed932cd719) | [https://www.loom.com/share/ff354c7621cd46a1a1fcc58c02c7fa32](https://www.loom.com/share/ff354c7621cd46a1a1fcc58c02c7fa32) |

#### Release Note

```release-note
* Bug fixes app crash on root post delete from global threads
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]
nice!

**Comment by jgilliam17** [comment]
Thanks @AshishDhama 
Looks good, tested all post delete variation for root post delete including global threads.
[E2E run in progress](https://automation-dashboard.vercel.app/cycles/6f303dbb-eee1-4501-99c1-cb321442ab30) will review and approve after run completes and I verify the report. 🙂

**Review by calebroseland — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @AshishDhama 
Looks good to merge. 
- Verified app no longer crashes on root post delete, Additionally, verified E2E report failures not related to this PR.

**Pull request merged**
