### PR TITLE
MM-20493 Migrate 'components/post_view/post_reaction' module and asso…

### PR DESCRIPTION
**Pull request by pikami**
#### Summary
Migrate 'components/post_view/post_reaction' module and associated tests to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15448

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @pikami! :sparkles:

**Review by deanwhillier — APPROVED** [review]

**Comment by deanwhillier** [comment]
Whoops, I merged too early, QA still needs to take a look. Apologies @jgilliam17!

**Pull request merged**
