### PR TITLE
Make use of parameter that was never used

### PR DESCRIPTION
**Pull request by wlsf82**
#### Summary
This PR simply makes use of a function's parameter that was defined but never used.

### CODE REVIEW

**Comment by wlsf82** [comment]
`cla/mattermost` has failed, but I'm in the list, you the below image shows.

Captura de Tela 2019-11-14 às 22 16 50

**Comment by wlsf82** [comment]
Excuse me, but what does this failure means?

`mattermost/serverless-ops/github — This PR needs to sync and merge.`

**Comment by wlsf82** [comment]
Thanks, @saturninoabril, I have just rebased and pushed the code on top of the up-to-date master upstream.

**Comment by wlsf82** [comment]
@srkgupta, it's taking a bit long for this PR to be reviewed, so I thought you could review it since you have already reviewed, approved, and merged another of my PRs (https://github.com/mattermost/mattermost-webapp/pull/4232).
Thanks in advance!

**Comment by saturninoabril** [comment]
@prapti For your review.

**Comment by wlsf82** [comment]
Due to the review process taking too long, every two to three days I have to rebase my code on top of the updated upstream master to get the full pipeline green. What could be done to improve this process and make it a better experience for community contributors?

**Pull request merged**
