### PR TITLE
Update help text for at-here, at-channel, at-all

### PR DESCRIPTION
**Pull request by jasonblais**
https://community.mattermost.com/core/pl/kqmabdzqb3df7xx5xjsaosozir

@hmhealey Please help confirm at-channel and at-all are functionally the same. From my (and UX) understanding they are.

### CODE REVIEW

**Comment by hmhealey** [comment]
Yes, they work the same

**Comment by hmhealey** [comment]
The build on this is going to fail because of the trailing newline in en.json. I tried to remove it using the GitHub web UI twice now, but it keeps adding it back in.

CCing @jespino on this while I fix it manually

**Comment by hmhealey** [comment]
@jasonblais Can you submit a PR for the mobile app to make this change there as well?

**Comment by jespino** [comment]
@hmhealey You have a PR waiting to get merged to fix exactly that :)

**Comment by jasonblais** [comment]
Mobile PR is here: https://github.com/mattermost/mattermost-mobile/pull/2790

**Comment by hmhealey** [comment]
@jespino Huh, I didn't even see that PR. Maybe you're just fast enough to have it finished last Saturday 😛

**Pull request merged**
