### PR TITLE
Cypress/E2E: Fix account setting sections json

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- Fixed `accessibility_account_setting_spec`

#### Ticket Link
NA

#### Screenshots
Screen Shot 2021-05-24 at 11 05 09 AM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by prapti — APPROVED** [review]
LGTM!

**Review by furqanmlk — COMMENTED** [review]
If I add ```TAB``` , it is passing

image

**Comment by josephbaylon** [comment]
@furqanmlk It's consistently passing for me without the additional tab. Is it consistently failing for you?

**Comment by furqanmlk** [comment]
> @furqanmlk It's consistently passing for me without the additional tab. Is it consistently failing for you?

Sorry, yeah I mixed with other PR.

**Review by furqanmlk — APPROVED** [review]

**Comment by furqanmlk** [comment]
Sorry @prapti by mistake I requested your review

**Pull request merged**
