### PR TITLE
Fix master lint issue.

### PR DESCRIPTION
**Pull request by metanerd**
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note

```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
:tada:

**Comment by metanerd** [comment]
Please can someone let me know if I can safely run update snapshot?

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by michelengelen** [comment]
> Please can someone let me know if I can safely run update snapshot?

Should be no problem with these changes.

**Pull request merged**
