### PR TITLE
Update commands.jsx

### PR DESCRIPTION
**Pull request by amyblais**
In response to: https://github.com/mattermost/mattermost-server/issues/8923.

`https://docs.mattermost.com/_images/slashCommandsTable1.PNG` doesn't exist anymore so I'm replacing it with a table as seen here: https://github.com/mattermost/docs/edit/master/source/help/messaging/executing-commands.rst.

I'm not sure about the formatting - should the whole table be on the same line?
I'm not able to see a preview of the changes.

- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@enahum Thoughts on whether this format works for the help files, or if there's another way to generate the table?

**Comment by jasonblais** [comment]
Should we then keep the image at https://docs.mattermost.com/_images/slashCommandsTable1.PNG? It's no longer used in docs but we could take another screenshot for it.

@enahum

**Comment by enahum** [comment]
We could keep it or we could add all the strings properly so they are localizable inside an html table

**Comment by jasonblais** [comment]
@amyblais Thoughts on taking a screenshot of the updated table and saving it at https://docs.mattermost.com/_images/slashCommandsTable1.PNG?

Might be easier for now..let me know if you have questions or thoughts?

**Comment by amyblais** [comment]
Took screenshots, again don't know what it actually looks like.

**Comment by jasonblais** [comment]
Thanks! We can test with the spinmint

**Comment by esethna** [comment]
@amyblais looks like it's still broken:

image

**Comment by jasonblais** [comment]
Hm, not sure why https://docs.mattermost.com/_images/slashCommandsTable1.png isn't rendering.

Even though the image is there https://github.com/mattermost/docs/blob/master/source/images/slashCommandsTable1.png

Any thoughts from anyone?

**Comment by kaakaa** [comment]
I did `make html` for mattermost/docs in local machine.
It seems that sphinx collect only files refered from documents. 

`slashCommandsTable1.png` isn't refered from any documents, so isn't deployed to docs.mattermost.com. I think.

**Comment by jasonblais** [comment]
Ah I see. Thanks @kaakaa! Appreciate it.

Would there be any suggestions @enahum @kaakaa how we could fix the broken table easily? It's no longer an image in the docs but a csv formatted table. Do we need to do the same here?

**Comment by enahum** [comment]
I think is best to build the html table here as it can be translated instead of using and image

**Comment by jasonblais** [comment]
@enahum Would you be able to give a sample of a couple of lines and Amy & I can finish it off from there?

**Comment by enahum** [comment]
I can do it sometime next week, is that ok?

**Comment by enahum** [comment]
@jasonblais perhaps all we need to do is include it in the webapp instead of the docs? cause looking at the table I don't think we actually need to translate it

**Comment by jasonblais** [comment]
Either way works for me, whichever is least effort to fix the table.

We'd just have to remember to update the table both in docs and webapp if there are more new slash commands being added.

**Comment by jasonblais** [comment]
@enahum how/where we do we go about adding it in the webapp repo?

**Comment by jasonblais** [comment]
^@enahum

**Comment by jasonblais** [comment]
thanks! We can merge @cpanato (I don't have permissions to do that)

**Pull request merged**
