### PR TITLE
[MM-44933] Advanced Text Editor: fixes forced refresh on message submit via button if message have special mentions all, channel etc

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Advanced Text Editor: forced refresh on message submit via send button if message has special mentions all, channel etc

#### Ticket Link
 Fixes https://mattermost.atlassian.net/browse/MM-44933

#### Related Pull Requests
NONE

#### Screenshots
NONE

#### Release Note
```release-note
Advanced Text Editor: fixes forced refresh on message submit via button if message have special mentions all, channel etc
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Comment by amyblais** [comment]
@michelengelen Please help prioritize this PR review.

**Review by Willyfrog — APPROVED** [review]

**Comment by Willyfrog** [comment]
Merging as it is QA deferred

**Pull request merged**
