### PR TITLE
fix "install plugins" button on plugin marketplace page

### PR DESCRIPTION
**Pull request by nadalfederer**
Summary
Fix button "Install Plugins" not changing tab correctly
Screenshot from 2019-12-07 20-15-03

Ticket Link
[MM-21188](https://mattermost.atlassian.net/browse/MM-21188)

### CODE REVIEW

**Comment by lieut-data** [comment]
Thanks, @nadalfederer!

**Comment by amyblais** [comment]
@marianunez FYI this is not cherry-picked yet.

**Comment by hanzei** [comment]
Hi @nadalfederer,

Thank you very much for the PR and also the E2E that you added. Unfortunately the E2E test fails by any plugins are previously installed. Would you be interested in fixing this? I've filled https://mattermost.atlassian.net/browse/MM-21610 to track the bug.

**Comment by nadalfederer** [comment]
sure, I'll create appropriate PR to fix it

**Comment by hanzei** [comment]
Thanks @nadalfederer, opened https://github.com/mattermost/mattermost-server/issues/13596 for you

**Pull request merged**
