### PR TITLE
Cypress/E2E: Upgrade to cypress@12.3 and other dependencies

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Upgrade to cypress@12.3 and other dependencies

- New config of `testIsolation: false`: Ideally, this should be true but our test currently has some dependencies with other test and setting this to true will require lots of changes. See reference to read more - https://docs.cypress.io/guides/core-concepts/test-isolation
- `"cypress-file-upload": "5.0.8"` will eventually remove once `attachFile` is migrated to use the built-in `selectFile`.
- `"@testing-library/cypress": "9.0.0"` is temporarily patched until the issue is resolved when querying an element.
- chaining of `should` after `then` seemed to not work anymore.
- `within` with multiple children works differently with the new version.
- multiple use of alias (`as`), either single or multiple, has a side-effect of constantly updating the value depending on base reference element. Workaround is to alias the specific value (not the entire element).
- `cy.server` was deprecated and removed, and recommended to use `cy.intercept`.
- `Cypress.Cookies.preserveOnce` was deprecated and removed.

Other: Fixed few broken/flaky tests.

#### Ticket Link
none

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by mattermost-quality** [comment]
E2E test ongoing. See link to [dashboard](https://automation-dashboard.vercel.app/cycle/289760) and/or [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/289760).

**Comment by mattermost-quality** [comment]
E2E result: 132 of 1625 tests failed :x:. See [link to report](https://automation-dashboard.vercel.app/cycle/289760).

**Review by m1lt0n — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by mattermost-quality** [comment]
E2E test ongoing. See link to [dashboard](https://automation-dashboard.vercel.app/cycle/290622) and/or [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/290622).

**Comment by mattermost-quality** [comment]
E2E result: 3 of 1605 tests failed :x:. See [link to report](https://automation-dashboard.vercel.app/cycle/290622).

**Comment by mattermost-quality** [comment]
E2E test ongoing. See link to [dashboard](https://automation-dashboard.vercel.app/cycle/290641) and/or [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/290641).

**Comment by mattermost-quality** [comment]
:x: E2E: 6 of 1606 tests failed
[pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/290641) | [dashboard](https://automation-dashboard.vercel.app/cycle/290641)

**Comment by mattermost-quality** [comment]
E2E: successfully triggered -- [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/290663) | [dashboard](https://automation-dashboard.vercel.app/cycle/290663)

**Comment by mattermost-quality** [comment]
E2E: successfully triggered -- [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/290680) | [dashboard](https://automation-dashboard.vercel.app/cycle/290680)

**Comment by mattermost-quality** [comment]
:x: E2E: 2 of 1616 tests failed -- [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/290680) | [dashboard](https://automation-dashboard.vercel.app/cycle/290680)

**Comment by furqanmlk** [comment]
> :x: E2E: 2 of 1616 tests failed -- [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/290680) | [dashboard](https://automation-dashboard.vercel.app/cycle/290680)

Oh wow report comes back with results 🎉

**Comment by saturninoabril** [comment]
Yup, not yet in our production pipelines but this is likely the setup. You'll notice the commit status as well (on Checks).

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril

**Comment by mattermost-quality** [comment]
E2E: successfully triggered -- [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/291102) | [dashboard](https://automation-dashboard.vercel.app/cycle/291102)

**Comment by mattermost-quality** [comment]
:x: E2E: 4 of 1615 tests failed -- [pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/291102) | [dashboard](https://automation-dashboard.vercel.app/cycle/291102)

**Comment by saturninoabril** [comment]
I'm merging this now. Let me know Yasser if you have comment/question.

**Pull request merged**
