### PR TITLE
MM-23366-Fix favourite channel tooltip position

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Fixes the toggling of the add/remove from favourites tooltip in the channel header

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23366

Fix versions
Queued

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 
Tested, looks good to merge.
- Verified control tooltips remain in the same position after the control is toggled. Tested on favorite and pin to channel toggles.

**Comment by amyblais** [comment]
@nevyangelova Is this a regression introduced in v5.22?

**Comment by nevyangelova** [comment]
@amyblais its not a regression.

**Comment by hmhealey** [comment]
I've re-added the cherry-pick label because this will need to be cherry-picked into the release-5.23 branch once that's created after 5.22 is done.

**Pull request merged**
