### PR TITLE
MM-34699-fix oauth check in admin_definition

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
OAuth is no longer being displayed on the System Console sidebar when it should be, even with System Admin. The wrong Config Group was being checked. This was added to handle a system role that did not contain that permission. This PR checks for the correct Groups and also checks the Setting for null.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34699

#### Screenshots
Screen Shot 2021-04-08 at 11 51 13 AM

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

**Comment by amyblais** [comment]
@sbishel Is this a recent regression, and which versions does it reproduce on?

**Comment by furqanmlk** [comment]
> @sbishel Is this a recent regression, and which versions does it reproduce on?

Hi @amyblais 
Cypress got this issue on Master

**Comment by sbishel** [comment]
> s this a recent regression, and which versions does it reproduce on?

**Comment by sbishel** [comment]
> @sbishel Is this a recent regression, and which versions does it reproduce on?

Yep. Just master. PR went in on Tuesday.

**Review by furqanmlk — APPROVED** [review]
Locally passed.
image

**Pull request merged**
