### PR TITLE
Disable desktop promp in cloud context

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
The desktop app prompt was breaking the cloud workspace flow for new users. This PR disables it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46490

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]
LGTM! Thanks @nevyangelova

**Review by saturninoabril — APPROVED** [review]
Thanks Nevy! LGTM.

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
