### PR TITLE
[MM-29217] Remove Posts.ParentId

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Removing the deprecated `Posts.ParentId`.

#### Ticket

https://mattermost.atlassian.net/browse/MM-29217

#### Release Notes

```release-note
Removed deprecated Posts.ParentId in favor of the semantically equivalent Posts.RootId
```

#### Related PRs

https://github.com/mattermost/mattermost-server/pull/17923
https://github.com/mattermost/enterprise/pull/1019
https://github.com/mattermost/mattermost-api-reference/pull/648
https://github.com/mattermost/mattermost-mobile/pull/5541

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Awesome! This has been a long time coming.

Posts.ParentId wasn't even used in [this initial commit](https://github.com/mattermost/mattermost-server/tree/56e74239d6b34df8f30ef046f0b0ff4ff0866a71) of Mattermost. That's just how old and deprecated it was. 😛

**Comment by metanerd** [comment]
Changed base branch, otherwise I cannot delete release-6.0 branch.

**Comment by amyblais** [comment]
@streamer45 Needs cherry-picking to ``cloud``.

**Comment by streamer45** [comment]
I think this is already included in cloud. It's been merged several days ago.

**Pull request merged**
