### PR TITLE
[MM-45935]: remove post forwarding feature flag

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
removed feature flag getter and all props that this is passed into as

#### Ticket Link
[MM-45935](https://mattermost.atlassian.net/browse/MM-45935)

#### Related Pull Requests
- Has server changes [here](https://github.com/mattermost/mattermost-server/pull/20714)

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Comment by jgilliam17** [comment]
@michelengelen I see the flag is shown in System Console>Experimental>Feature Flags `PostForwarding | false`  and at the same time post forwarding is enabled on the server. Can you please take a look - thanks 🙂

**Comment by jgilliam17** [comment]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/229665-f89e839-onprem-ent-webapp-pr-10838-mm-ee-test:f89e839/mochawesome.html) looks good, no PR related failures

**Comment by michelengelen** [comment]
> @michelengelen I see the flag is shown in System Console>Experimental>Feature Flags `PostForwarding | false` and at the same time post forwarding is enabled on the server. Can you please take a look - thanks 🙂

Hi @jgilliam17 ... this is due to the fact that with this PR I removed all of the connections to the feature flag ... the server in this instance still has the feature flag set and it is also still present in code as long as https://github.com/mattermost/mattermost-server/pull/20714 is not merged

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge.
Verified post forward feature flag has been removed. Post forwarding is enabled and working as expected. 
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/233719-9aa401c-onprem-ent-webapp-pr-10838-mm-ee-test:9aa401c/mochawesome.html)looks good, no PR related failures

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
