### PR TITLE
Optimize png image with zopflipng lossless compression

### PR DESCRIPTION
**Pull request by PeterDaveHello**
#### Summary
Recompress the PNG images losslessly via Google's [zopflipng](http://github.com/google/zopfli) to reduce the application size without losing any visual quality!

The parameters used in this optimization were: `zopflipng --iterations=600 --keepchunks=iCCP --lossy_transparent --splitting=3` 

1652 PNG images were optimized in total.

#### Related Pull Requests
- https://github.com/mattermost/mattermost-mobile/pull/2682
- https://github.com/mattermost/desktop/pull/981

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @PeterDaveHello, discussing this PR with Asaad internally. Will report back here soon

**Comment by hanzei** [comment]
Hey @esethna,

Do you have updates about this PR?

**Comment by esethna** [comment]
Thanks @PeterDaveHello, discussed with Asaad and tested to verify there was no visible signs of quality loss. Moving to dev review

**Comment by hmhealey** [comment]
@PeterDaveHello Would you be able to update this PR to the latest master and resolve the merge conflict?

**Comment by PeterDaveHello** [comment]
Should be done!

**Comment by hmhealey** [comment]
Thanks!

**Pull request merged**
