### PR TITLE
[MM-20480] Migrate new_message_separator and its tests to typescript

### PR DESCRIPTION
**Pull request by abdusabri**
#### Summary

Migrates `new_message_separator` module and its tests to TypeScript.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15461, https://mattermost.atlassian.net/browse/MM-20480

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @abdusabri!

**Review by sudheerDev — APPROVED** [review]
LGTM

**Review by lindy65 — APPROVED** [review]
Thanks @abdusabri - tested around new messages separator and looks good to me 👍 

@sudheerDev - please resolve associated Jira ticket after merge - thanks!

**Comment by hanzei** [comment]
Thanks for yet another contribution @abdusabri. Glad you are continuously contributing :rocket:

**Comment by abdusabri** [comment]
> Thanks for yet another contribution @abdusabri. Glad you are continuously contributing :rocket: 

Thanks Ben! Happy to help 😊

**Pull request merged**
