### PR TITLE
[GH-15873] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 562

### PR DESCRIPTION
**Pull request by ashutosh97**
## Summary
This PR removes usage of changeCSS() function to change the border-color of team-btn element.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15873

### CODE REVIEW

**Comment by hanzei** [comment]
@ashutosh97 It seems like you haven't signed the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/9) yet. Would you mind doing that?

**Review by calebroseland — CHANGES_REQUESTED** [review]
nit: could this live inside the `.team-btn` style above? With other styles not under `.app__body`, seems redundant here.

**Review by Willyfrog — COMMENTED** [review]
LGTM, other than @calebroseland suggestion

**Comment by deanwhillier** [comment]
QA for this PR will be batched when the campaign branch is merged to master

**Comment by ashutosh97** [comment]
@calebroseland I have made the change as per your suggestion.

**Review by calebroseland — APPROVED** [review]
Thank you!

**Pull request merged**
