### PR TITLE
Remove background color for post action buttons

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Remove background color from post action buttons to avoid errors with themes.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-28919

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
Nice!

**Review by hmhealey — APPROVED** [review]

**Comment by DHaussermann** [comment]
@larkox it's not entirely clear to me where there was a backgroundColor of white before. Can you please provide test steps for this one?

**Comment by larkox** [comment]
If you create a interactive message with a button with a style, the styled button will have a white background, no matter the theme.

In order to add some style to the buttons of an interactive message, you have to add a style field. This is a go example:
```
{
	Type:  "button",
	Name:  "Button ***B***",
	Style: "success",
},
```

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- White back color has been removed from button
- Tested with all button styles and all themes 
- I did find an unrelated issue where one of the styles is not properly applied on dark theme. Created https://mattermost.atlassian.net/browse/MM-31493 to address this

LGTM!

**Pull request merged**
