### PR TITLE
MM-21424 - Updating RHS css for responsive view

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-21424 - Updating RHS css for responsive view

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21424

#### Screenshots
Screenshot 2020-01-30 at 6 08 29 PM

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thank you @asaadmahmood 
I noticed that icons to the left of the Search bar (Members and Pinned posts) are now removed as the window gets smaller while the RHS is open.
Is there anything that can be done about that? 
Screen Shot 2020-01-30 at 11 19 52 AM
Screen Shot 2020-01-30 at 11 19 42 AM

**Comment by asaadmahmood** [comment]
@jgilliam17 That's how it has been for narrow screens, the RHS opens on top of the icons behind, which is why they are hidden.
You can verify that in the previous releases as well.

**Comment by jgilliam17** [comment]
> @jgilliam17 That's how it has been for narrow screens, the RHS opens on top of the icons behind, which is why they are hidden.
> You can verify that in the previous releases as well.

Thanks. 
You're right, I've seen this in previous releases.
I was just trying to understand why we hide the icons on the left side of the search bar and keep the icons on the right available in smaller window widths. Wondering why we don't just hide all, except search bar, when RHS is open.

**Comment by asaadmahmood** [comment]
@jgilliam17 That's just how it is built, however you can look at it in this way.
The flag and the mentions are global actions like search whereas pins and the user list are channel specific.

**Pull request merged**
