### PR TITLE
[MM-7854] Revoke all sessions from all users (front)

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

Add a button that enables a system administrator to revoke all sessions in the system.

#### Ticket Link
Github: https://github.com/mattermost/mattermost-server/issues/7811
Jira: https://mattermost.atlassian.net/browse/MM-7854

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/11200
- Has redux changes: https://github.com/mattermost/mattermost-redux/pull/866

### CODE REVIEW

**Comment by hanzei** [comment]
@Willyfrog Would you please merge `master` into your branch and update the `redux` commit?

**Comment by Willyfrog** [comment]
hi @hanzei what do you mean by "update the redux commit"? is there some other PR that affects this? I haven't seen any

**Comment by Willyfrog** [comment]
1 - Fixed.
2 - I put it into black as the original description asked, let me know if you want it back to red.
3 - changed text on english and spanish

**Comment by Willyfrog** [comment]
How can I get it to be recreated?

**Comment by jasonblais** [comment]
Thanks! 

1 - Looks like the button is now cut off the screen

image

3 - Looks like the text changed it also for the dialog when you try to deactivate someone. Ideally this would stay as "Deactivate"
image

PS: You don't actually need the translations in es.json, they will be handled separately via https://translate.mattermost.com

**Comment by Willyfrog** [comment]
I've already fixed number 3 on my local, sorry about that, I'm dumb and forgot I started from the deactivate modal.

Number 1 is going to take me a little longer, as css is acting weird and content goes over the wrapper for some reason, pushing everything down.

**Comment by asaadmahmood** [comment]
@jasonblais Is there a confirmation that a user receives after clicking the button? If so, i'm fine having it black, and then in the modal, it can be red.

**Comment by Willyfrog** [comment]
There is a modal asking for confirmation, and that is red. So I guess you are fine with it being black. Thanks!

**Comment by Willyfrog** [comment]
@jasonblais button should be better placed, I changed the scss which I feel is unique for this component within the admin section.

**Comment by lindalumitchell** [comment]
Just to verify, is this PR related to https://mattermost.atlassian.net/browse/MM-12440 (which was split off from MM-7854)?

**Comment by jasonblais** [comment]
@lindalumitchell that's correct 👍

**Comment by srkgupta** [comment]
Hi @hmhealey, since the PR instance is removed and the code is still not merged, I am kind of stuck here as I am trying to complete the test automation for this story. Can I go ahead and bring up the instance again until the code is merged into master?

**Comment by hanzei** [comment]
Hey @srkgupta,

Sorry, I didn't know you still needed the test server. I didn't mean to disturb your work flow.

FYI: You can set up a test server yourself by adding the `Setup Cloud Test Server` label.

**Comment by srkgupta** [comment]
Thanks @hanzei. I wasn't sure about the process and the permissions. Good to know about it.

**Comment by hanzei** [comment]
@srkgupta What are the next steps for this PR? Should this be merged together with the tests or can this be merged now?

**Comment by srkgupta** [comment]
Hi @hanzei,

This PR is ready to be merged along with the rest referenced.

**Comment by hanzei** [comment]
@amyblais Would you be fine including this into `5.14`? The server and redux PR have already be merged and a cypress test is on his way.

**Comment by amyblais** [comment]
I'm sorry, we are past feature complete so I would prefer not to merge this for v5.14. If the server/redux PRs will cause issues in v5.14 if this PR isn't merged, then it is ok to include this in v5.14. @hanzei

**Pull request merged**
