### PR TITLE
[MM-18074] Format of Position in User Profile is incorrect

### PR DESCRIPTION
**Pull request by bradjcoughlin**
#### Summary
The format of the position string of text looks slightly off from the design. I'm not sure if this is the best fix, but to me, but increasing the size by a pixel (15px) looks a bit better:
Screen Shot 2019-09-30 at 11 03 45 AM

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18074

### CODE REVIEW

**Comment by wiersgallak** [comment]
@bradjcoughlin I'll deter to @michaelgamble on the exact pixels, but it looks to have more vertical white space above the position string then below -  I'd expect it to be the same or a bit closer to the top than bottom 

Screen Shot 2019-09-30 at 1 17 02 PM

**Comment by bradjcoughlin** [comment]
@michaelgamble I've reduced the font size back down to 14px, and changed the padding/margin so that the white space appears equidistant.

**Comment by bradjcoughlin** [comment]
@michaelgamble Implemented changes discussed offline. I'll file a new ticket to add the "role" icon.

**Comment by lindalumitchell** [comment]
Not sure if this had official QA review, but I took a look and this LGTM.

**Pull request merged**
