### PR TITLE
MM-31916: channel mention for specific keywords breaks application

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
provided a more sophisticated check for certain keywords in the channelNamesMap to check for the type being an object.
The application broke at this point because the value searched for is non-existent and therefore could not extract the `display_name` property, which is why the application was failing at this point. The change that fixes the bug is to be found at line 402

On the way I fixed some warnings and errors in the file

#### Ticket Link
Fixes [MM-31916](https://mattermost.atlassian.net/browse/MM-31916)

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@michelengelen this seems like more of a technical fix based on the description. Does it need a ux review? If so, what specifically should I look at?

**Comment by michelengelen** [comment]
@matthewbirtch not really ... It is just to check if it renders correctly (how it is supposed to be)

**Review by srkgupta — APPROVED** [review]
Thanks @michelengelen. Tested and the fix is working fine now. Looks good from security perspective.

**Review by hmhealey — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @michelengelen 
Tested, looks good to merge.
- Verified specific text, as mentioned, no longer breaks the application.

**Pull request merged**
