### PR TITLE
Feature/mm 37821 remove global header option

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
this PR aims to remove the "Global Header"-option from the account settings modal, since in the future it will be set from a feature flag instead.

#### Ticket Link
[MM-37821](https://mattermost.atlassian.net/browse/MM-37821)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
I probably would have just inverted the default given the state of it. But the ticket says otherwise.

Also just to correct the description:
> since in the future it will be set from a feature flag instead.

It's already controlled by a feature flag today.

**Comment by michelengelen** [comment]
> Also just to correct the description:
> 
> > since in the future it will be set from a feature flag instead.
>
> It's already controlled by a feature flag today.

Haha. Sry! I should have written "since in the future it will be set solely from a feature flag instead."

**Review by nevyangelova — APPROVED** [review]

**Comment by michaelgamble** [comment]
@michelengelen @andrewbrown00 I removed myself as the reviewer on this PR as I wont be around next week.. for the life of me I cant get a test server up and running to review this one.

**Comment by andrewbrown00** [comment]
@michelengelen are you able to get the test server working on this PR? It shows up as a white screen for me.

**Comment by michelengelen** [comment]
@andrewbrown00 it wont spin up for me as well. I asked the SRE team for support in another ticket

**Comment by andrewbrown00** [comment]
@michelengelen looks like the test server was built successfully, but I just see a **white screen** when hitting the URL. Any thoughts?

image

**Comment by michelengelen** [comment]
I am sorry @andrewbrown00 , but i do not know what is happening here. the info from the console could mean the server is not starting up correctly, since the APIs are not reachable. @spirosoik is there currently a known issue that could be the cause for this?

**Comment by michelengelen** [comment]
I just noticed that the running server was initiated with CWS ... I will try to start one without it, just to be sure

**Comment by michelengelen** [comment]
@andrewbrown00 it is the same for a server without CWS ... I think we might need someone from the SRE team here to solve the issue.

**Comment by andrewbrown00** [comment]
Thanks for the update @michelengelen, let me know if the SRE team is able to resolve the issue and I'll review 🙂

**Comment by michelengelen** [comment]
> Thanks for the update @michelengelen, let me know if the SRE team is able to resolve the issue and I'll review 🙂

Interestingly the PR #8571 is working just fine.

**Comment by spirosoik** [comment]
@michelengelen there's no any known issue but I will have a look to see what's going on.

**Comment by spirosoik** [comment]
@michelengelen a rebase and get latest master can help as it will get latest server changes too which may fix any issue

**Comment by michelengelen** [comment]
> @michelengelen a rebase and get latest master can help as it will get latest server changes too which may fix any issue

I did merge the current master before trying to spin up a server, so that clearly did not help.

**Comment by spirosoik** [comment]
let me check @michelengelen

**Comment by spirosoik** [comment]
@michelengelen just retested everything seems ok

**Comment by michelengelen** [comment]
@spirosoik it is running, but we hit a white screen, as seen in the screenshots:

Screenshot 2021-08-18 at 12 07 04

Screenshot 2021-08-18 at 12 07 23

**Comment by spirosoik** [comment]
@michelengelen are we sure that it's not related with any change in app? seems that the endpoints get 401 and doesn't redirect back to login screen to me after a session expiration. I have the same but in the morning when I logged in was ok

**Comment by michelengelen** [comment]
@spirosoik could it be that it works for a couple of minutes and then somehow breaks after the session expires? I will try to set a server up and check immediately after it's gone up, ok?

**Comment by michelengelen** [comment]
@spirosoik It does not work with CWS and normal instances. Every time I want to view it i just get a white screen with the beforementioned console errors. I will try my last resort on this: creating a new branch with a new PR and see if it works there, ok?

**Comment by spirosoik** [comment]
@michelengelen give me a few minutes to have a look

**Comment by spirosoik** [comment]
@michelengelen I cross-checked the logs in server for this installation and I cannot see any error except 

```
{"timestamp":"2021-08-18 19:25:08.383 Z","level":"info","msg":"\u001b[31merror\u001b[0m [2021-08-18 19:25:08.382 Z] Unable to clean up the sessions          \u001b[31merror\u001b[0m=\"no update allowed from focalboard, update it using mattermost\"","plugin_id":"focalboard","source":"plugin_stdout"}
```

**Comment by andrewbrown00** [comment]
I'm still seeing a white screen and no UI 😞 

image

**Comment by michelengelen** [comment]
Closing in favor of #8645 ... spinwicks are working on that PR

**Pull request closed without merging**
