### PR TITLE
MM-13638 Add support for Elixir syntax highlighting

### PR DESCRIPTION
**Pull request by ja11sop**
#### Summary
This PR attempts to add support for syntax highlighting of Elixir code.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-13638

#### Checklist
- [ ] Ran `make check-style` to check for style errors (required for all pull requests) <- don't have access to npm setup to do this atm
- [ ] Ran `make test` to ensure unit and component tests passed <- don't have access to npm setup to do this atm
- [ ] Added or updated unit tests (required for all new features) <- don't believe there are tests for similar code
- [x] Needs to be implemented in mobile (link to PR or User Story) 
see https://github.com/mattermost/mattermost-mobile/pull/2355

### CODE REVIEW

**Comment by hmhealey** [comment]
I also gave this a quick smoke test, so I can confirm it works as expected

**Comment by jasonblais** [comment]
Hey @ja11sop! Huge thanks for your contribution :tada: 

Would you be open to helping with a rebase, and then we'll merge? As a first contributor, you'll receive a limited edition mug featuring your username and date of first commit after your changes ship in a Mattermost release. So let us know if you have any questions to help you get this one merged! :) 

image

**Comment by ja11sop** [comment]
@jasonblais @enahum @hmhealey - rebased I believe and ready to merge - apologies for the delay in getting back to this.

**Comment by hmhealey** [comment]
Thanks for the rebase. Jenkins seems to be having some issues, so I'm going to close and reopen the PR to trigger a rebuild

**Comment by hmhealey** [comment]
I've added a ticket so that QA know to test this for the upcoming release. Thanks again for the submission!

**Pull request merged**
