### PR TITLE
[MM 19901] Fix keyboard navigation sorting of RHS posts

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Implementation of sorting for posts wasn't working in older Chrome browsers (noticed in older Desktop App v4.2.x). This PR explicitly adds a11y sort order to posts in the RHS as well as improves the sorting function that looks at an optional attribute on matching elements for a defined sort order.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19901

### CODE REVIEW

**Comment by amyblais** [comment]
@marianunez @cpoile Please review this PR as a highest priority.

**Comment by amyblais** [comment]
@sadohert Yes I've asked @deanwhillier to cherry-pick this to v5.15.

**Comment by deanwhillier** [comment]
I will also be cherry picking to v5.16 as this can be repro'd on community.mattermost.com (v5.16.2 at time of comment)

**Comment by deanwhillier** [comment]
v5.15 and v5.16 cherry pick's complete!

**Pull request merged**
