### PR TITLE
[MM-37716] Drop support for LHS specific bot icons

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
See https://github.com/mattermost/mattermost-server/pull/18087

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37716

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/18087
- Has mobile changes: None

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM

**Review by hmhealey — APPROVED** [review]
Glad to see this! That feature always felt like a bit of a dud anyway since I don't know if we ever ended up actually using it before we redesigned the icon for DM channels

**Comment by DHaussermann** [comment]
Tested along with https://github.com/mattermost/mattermost-server/pull/18087

Tested and passed
- Deployed Server and Webapp PRs
- SVG use in sidebar is no longer functional
- Even if already set - Upgrading to this PR will use profile image now instead
- Tested legacy sidebar as well to ensure that LHS icon will revert to generic bot icon 
No issues found

LGTM!

**Pull request merged**
