### PR TITLE
MM-T5208 - Continue to show global Threads item when unread filter is enabled

### PR DESCRIPTION
**Pull request by simcard0000**
#### Summary
This test goes over the steps outlined in https://automation-test-cases.vercel.app/test/MM-T5208. 

#### Ticket Link
Web-app E2E test with Cypress for: https://github.com/mattermost/mattermost-server/issues/21387

#### Related Pull Requests
N/A as of now.

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by simcard0000** [comment]
Not sure why some random E2E tests are failing when I haven't touched them, but it might be related to: https://community.mattermost.com/private-core/pl/sf8zswgqxiyhddixnqr9zpdxcc

**Review by furqanmlk — APPROVED** [review]
Thanks @simcard0000, LGTM

**Comment by simcard0000** [comment]
Hey @saturninoabril; just a bump on reviewing :)

**Review by saturninoabril — APPROVED** [review]
Thanks Sim! LGTM.

**Pull request merged**
