### PR TITLE
MM-32589 : Fix CHB "This channel has guests" accessibility

### PR DESCRIPTION
**Pull request by jbattistispiria**
#### Summary
Fix CHB "This channel has guests" accessibility.
Jaws TABS to "This channel has guests" and also reads it out

Added a span, otherwise screen reader read the bullet icon. "This channel has guests, bullet"

#### Ticket Link
Fix https://github.com/mattermost/mattermost-server/issues/19163
https://mattermost.atlassian.net/browse/MM-32589

#### Screenshots
image

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thanks @jbattistispiria 
Tested, looks good to merge - pending e2e report, will post link here shortly.
- Verified "This channel has guests" label is being read by the screen readers.

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by jgilliam17** [comment]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/187359-f768bdc-onprem-ent-webapp-pr-10215-mattermost/mm-ee-testf768bdc/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
