### PR TITLE
MM-35016 - Update payment screen info text

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary
Update payment screen info banner to remove references of free tier. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35016

#### Screenshots

Screen Shot 2021-04-19 at 4 59 49 PM

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Comment by marianunez** [comment]
@stevemudie we can test post-merge so we can cherry-pick this to cloud now

**Comment by marianunez** [comment]
@amyblais another cherry-pick minor text change.

**Pull request merged**
