### PR TITLE
[MM-47041] fix escape key not closing channel switcher issue

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
fix escape key not closing channel switcher issue

#### Ticket Link
fixes https://mattermost.atlassian.net/browse/MM-47041

#### Related Pull Requests
NA

#### Screenshots
NA

#### Release Note
```release-note
NA
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @AshishDhama 
Tested, looks good to merge.
Verified esc closes channel switcher.
[E2E report ](https://automation-dashboard.vercel.app/cycles/fe29bb31-fa56-429f-85e0-4ff10746efe1)- no PR related failures.

**Comment by AshishDhama** [comment]
@furqanmlk Should I merge it

**Review by jwilander — APPROVED** [review]

**Comment by furqanmlk** [comment]
> https://mattermost-webapp-pr-11155.test.mattermost.cloud

@AshishDhama 
Issue is fixed and E2E passed 
Good to merge

**Pull request merged**
