### PR TITLE
[MM-23448] - Fix drag and drop in desktop app

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
After some digging it turned out that the events were working correctly in Desktop app, but the button wasn't draggable. Actually only the side indicator was draggable and working even before that change. Now that we are using the same component for webapp and desktop it works as expected. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23448

Fix versions
v4.5 Desktop App

### CODE REVIEW

**Comment by esethna** [comment]
Nice find, thanks Nevy!

**Comment by amyblais** [comment]
@nevyangelova Has this been cherry-picked?

**Pull request merged**
