### PR TITLE
Mm 20374 migrate get public link modal to typescript

### PR DESCRIPTION
**Pull request by kashifsoofi**
#### Summary
Migrate `components/get_public_link_modal` to typescript

#### Ticket Link
GitHub: Fixes https://github.com/mattermost/mattermost-server/issues/16732
JIRA: https://mattermost.atlassian.net/browse/MM-20374

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @kashifsoofi!

**Comment by lindy65** [comment]
Hi @kashifsoofi - while testing "get public link" I'm seeing `[object Object]` in the field - see below

image

/cc @devinbinnie

**Comment by kashifsoofi** [comment]
> 
> 
> Hi @kashifsoofi - while testing "get public link" I'm seeing `[object Object]` in the field - see below
> 
> image
> 
> /cc @devinbinnie

Thanks, I am quite new to React (1st time working) I see the problem on test, is there a document to run this locally so I can debug?

**Comment by lindy65** [comment]
Hi @kashifsoofi - no problem :)

I'm sure @devinbinnie will be able to point you in the right direction when he wakes up a little later (he's on American/Canadian time ;) )

**Comment by kashifsoofi** [comment]
> 
> 
> Hi @kashifsoofi - no problem :)
> 
> I'm sure @devinbinnie will be able to point you in the right direction when he wakes up a little later (he's on American/Canadian time ;) )

Thanks I think I figured out how to run it, for some reason couldn't workout why networking is not working on wsl2 so i will try it later on osx/linux machine.

**Comment by lindy65** [comment]
Thanks @kashifsoofi :) Sounds good 👍

**Comment by devinbinnie** [comment]
> > Hi @kashifsoofi - no problem :)
> > I'm sure @devinbinnie will be able to point you in the right direction when he wakes up a little later (he's on American/Canadian time ;) )
> 
> Thanks I think I figured out how to run it, couldn't workout why networking is not working on wsl2 (after trying different solutions) so i will try it later on osx/linux machine.

@kashifsoofi With respect to WSL2, do you have a bridged network adapter installed? Usually the install process should set that all up for you, but I remember having to do some strange configuration to get everything working.

Any luck reproducing the error in Lindy's comment?

**Review by nevyangelova — APPROVED** [review]
LGTM, thanks :)

**Comment by kashifsoofi** [comment]
> Any luck reproducing the error in Lindy's comment?

Managed to reproduce the error on test server. however i am getting following on localhost
image

**Comment by kashifsoofi** [comment]
Just realised forgot to switch branch :( will try again today

**Comment by kashifsoofi** [comment]
> Any luck reproducing the error in Lindy's comment?
Managed to reproduce the error, if i do a `JSON.stringify` i get ```{"link":"http://localhost:8065/files/cs751bmdgp8ubyjs5987nh1ksc/public?h=7zITIqI6G-wswZqKjgQuAKudxWBIkibBI9JP_i60jpc"}``` however when i update index.ts Line 15 as ```link: Selectors.getFilePublicLink(state)?.link``` <- this is a function call instead of a string value,  it gives a compiler error on Line 31 that i cannot figure out how to fix.

**Comment by kashifsoofi** [comment]
image

Url is not visible on Modal, however there is a warning/error on index.ts line 31, could not figure out how to fix that.

**Review by lindy65 — APPROVED** [review]
Hi @kashifsoofi :)

I tested on the updated test server and I see the URL and can copy and paste it successfully.  It looks fixed to me. I don't see any errors in the js.console.  

/cc @devinbinnie - is this good to merge?

**Pull request merged**
