### PR TITLE
MM-4887: Remove back to MM button for Zapier-MM OAuth integration setup

### PR DESCRIPTION
**Pull request by catalintomai**
#### Summary
OAuth2.0: Incorrect Client ID during authentication allows user to go "Back to Mattermost" in the authentication window

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-4887

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/13890

@jwilander , when you have time, can you take a look at the change (it is an old issue - see ticket link) and from I gather you were the last one to work in the GoogleAuth area. Thanks!

### CODE REVIEW

**Comment by catalintomai** [comment]
@srkgupta , my understanding of the scope of the bug is that we want to remove the "back to MM" button in the case(s) in which the auth error happens in an external product (like Zapier) - and only in the setup phase, not all products have a similar setup wizard page - some just use configs with ClientId+Secret), not to remove the "back to MM" for all cases where the auth fails. @esethna , can you please confirm that is the intention of the ticket? Thanks.

**Comment by esethna** [comment]
@catalintomai, that is correct ^

**Comment by catalintomai** [comment]
> > @srkgupta , my understanding of the scope of the bug is that we want to remove the "back to MM" button in the case(s) in which the auth error happens in an external product (like Zapier) - and only in the setup phase, not all products have a similar setup wizard page - some just use configs with ClientId+Secret), not to remove the "back to MM" for all cases where the auth fails. @esethna , can you please confirm that is the intention of the ticket? Thanks.
> 
> @catalintomai The error which I had mentioned also comes while configuring the Zapier when the redirect_url does not matches with the one configured on MM. This happens during the setup wizard page itself. I will go ahead approve this PR. We can handle this usecase if it comes up later.

@srkgupta , thanks for pointing it out I saw MM in the background of the 

> > @srkgupta , my understanding of the scope of the bug is that we want to remove the "back to MM" button in the case(s) in which the auth error happens in an external product (like Zapier) - and only in the setup phase, not all products have a similar setup wizard page - some just use configs with ClientId+Secret), not to remove the "back to MM" for all cases where the auth fails. @esethna , can you please confirm that is the intention of the ticket? Thanks.
> 
> @catalintomai The error which I had mentioned also comes while configuring the Zapier when the redirect_url does not matches with the one configured on MM. This happens during the setup wizard page itself. I will go ahead approve this PR. We can handle this usecase if it comes up later.

@srkgupta, thanks for pointing it out. I saw MM in the background and assumed that it is happening when visiting the MM auth page. My take right now is that we are invoke the server code from more than one entry point (external wizard in this case) and there is a danger of breaking one while fixing another.  I say open the ticket for the other issue you identified (and I am sure there are others of the same kind) and we'll prob. do a scrub later on this area.

**Comment by srkgupta** [comment]
Thanks @catalintomai. I have raised the issue separately:
https://mattermost.atlassian.net/browse/MM-23699

**Pull request merged**
