### PR TITLE
color formatting

### PR DESCRIPTION
**Pull request by yehonatanz**
Color formatting is now supported via link syntax.

``[My red warning](color://red)``
will now render as:
image

Color formatting is not supported in the markdown standard, but is a lovely feature to have.
Corresponding PR to docs: https://github.com/mattermost/docs/pull/1539

(This PR has no ticket, but since it's a minor improvement the guidelines lead me to believe that such ticket is not needed)

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @yehonatanz, appreciate your interest here! Agree that color formatting is a nice feature to have. I'm curious if you've seen this standard in other messaging platforms? If so can you provide examples so we can investigate?

I'm concerned about:
1. Usability:
    - It's not obvious what colors are acceptable (ie, is "maroon" acceptable?)
    - If a color typed is not acceptable wouldn't it render as an bad link?
2. Discoverability:
    - Given that it's not a standard markdown feature, how will people know to use it and the syntax.

Given the above concerns I think this improvement should require a ticket. Also, we have been planning to add a message formatter (similar to GitHub) to make markdown more discoverable, so color formatting could be an added feature there, rather than using a non-standard work around. Definitely open to discussion, highly appreciate the PR,

**Comment by yehonatanz** [comment]
Hey @esethna, thanks for your feedback and apologies for the delay!
I've seen no platforms that support colors in markdown with any syntax other than embedded HTML.
I thought that a quick non-standard solution might be an acceptable choice (contrast to messing with the sanitation process).
Regarding your points:

1. 
 - Valid colors are the standard HTML color, either by name ("red"), hex ("#ff0000") or short hex ("#f00").
 - Invalid colors will render as uncolored text.
2.
 - Using the wonderful docs mattermost offers - a corresponding docs PR is already open.
That said, I tend to agree with your statement about the formatter, and that it might actually require a ticket.
However, as far as I know, the currently used markdown processor (the wonderful [marked.js](https://github.com/chjj/marked) does not support allowing specific HTML tags or attributes.
Meaning non-standard syntax, or further customization of the markdown processor will be needed anyway for this feature.

**Comment by esethna** [comment]
Thanks @yehonatanz, can you please help me understand what the end user syntax would be for the solution you're proposing? I'm also adding @hmhealey as he is most familiar with markdown on our dev team.

**Comment by yehonatanz** [comment]
@esethna Sure, I thought of something like that:
<font color="red">my red text</font>
As I understood that embedding html is the (most) standard way to apply colors in markdown.

**Comment by hmhealey** [comment]
If we were to add something like this, I'd prefer to follow how other systems work, like you mentioned about possibly using inline HTML. Our usual reference points are GitHub and GitLab, but while they both allow some inline HTML (which we don't support at all), neither appears to have any method to colour text. Even adding inline HTML support to Mattermost is iffy since it'll be difficult to support on the mobile apps since they don't natively understand HTML.

While I appreciate the effort here (PRs that include documentation are super rare, so thanks for adding that!), I don't think it make sense for us to include in Mattermost right now.

**Comment by yehonatanz** [comment]
That's too bad, I've really been looking forward for colors in mattermost.
Thanks for considering, and please let me know if there's anything I can do to further promote this feature!

**Comment by esethna** [comment]
Thanks @yehonatanz, I'm going to close this PR for now, but definitely appreciate the effort here. 

FYI we have a lot of [open Hacktoberfest tickets](https://github.com/mattermost/mattermost-server/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest) if you are interested in contributing any other features.

**Pull request closed without merging**
