### PR TITLE
Cypress/E2E:fixed cloud test cases

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Fixed Channel file spec test case
Fixed mark as unread using shortcut test case
Fixed use team invite link to sign up test case

#### Screenshots
image

#### Release Note
```release-note
NONE
```

#### Passed in [E2E](https://automation-dashboard.vercel.app/cycles/c8310716-a130-4646-b856-1152d6c7c9cb)

image

image

image

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Thanks Malik!

**Review by Phrynobatrachus — APPROVED** [review]
looks fine pending test run once that's working again, thanks!

**Pull request merged**
