### PR TITLE
Changed min username length to 2

### PR DESCRIPTION
**Pull request by Huseriato**
#### Summary
Changed min username length to 2.

#### Ticket Link
There is currently no ticket.

### CODE REVIEW

**Comment by Huseriato** [comment]
See also: https://github.com/mattermost/mattermost-server/issues/5794

**Comment by Huseriato** [comment]
I've signed the CLA. May be you can update this. I found, that the server will accept usernames with one character, too. Using the HTTP Api I've checked this on the javascript console inside the webapp running in Opera.

This is my command:

```
$.ajax({
    url: 'https://mattermost.ourserver.com/api/v4/users/me/patch',
    type: 'PUT',
    contentType: 'application/json',
    dataType: 'json',
    data: JSON.stringify({
        username: "a"
    })
});
```

So the only thing that's blocking is the client. We've changed our users names running this command (it's possible to use the user id for "me" in the url). But the issue is still open. Maybe you can change my pull request to `MIN_USERNAME_LENGTH = 1` instead of `2`.

**Comment by jasonblais** [comment]
Thanks @Huseriato for the contribution.

Three-character search minimum is a SQL search default. This search minimum would also apply to username searches across the UI (when adding to channels, @-mention autocomplete, etc). While it's possible to change it below two characters, it is generally not recommended for larger installs given the possibility of impacting search performance.

Here's an example of the default value for MySQL: https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_ft_min_token_size

So in general, the proposal for SQL search is to keep the three-character minimum -- which is why we'd keep usernames to be three characters minimum as well.

That said, there have been others who have proposed reducing minimum username to two characters: https://mattermost.uservoice.com/forums/306457-general/suggestions/16391320-changing-min-username-to-2-characters

Would you be open to upvoting the above-linked feature proposal? You get 10 votes in the forum, each one influencing the future of this project.

If the feature request attracts a lot of community interest, we can further discuss potential options for supporting two-character usernames.

**Comment by Huseriato** [comment]
Hello, the whole UI have no problems with 2 or 1 character usernames. The servers loves them, autocompletion and detection in mentions also works. I cannot see, why the client should limit them. Our whole company uses usernames with 2 characters in more than 10 software packages without any problems. We really would like to avoid a fork just the get rid of this limit.

The minimum value in https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_ft_min_token_size is 0. It's just a default of 3.

**Comment by jasonblais** [comment]
Thanks @Huseriato for the feedback! We've had search issues in the past, but maybe some of those have been resolved since,

Does searching for recent mentions (via the "@" symbol next to search bar in top right corner) work?  Or the ability to search for posts from certain users (via `from:` modifier) work with usernames 1 or 2 characters long?

**Comment by Huseriato** [comment]
Hello, yes it works with the current server, if you set [innodb_ft_min_token_size](https://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_ft_min_token_size) to a value of "2" in the database. I can use the @-symbol on the upper right and can make a search using "text from:aa" without any problems.

**Comment by jasonblais** [comment]
Thanks @Huseriato, that's good to know. Let me touch base with the team about this

**Comment by jasonblais** [comment]
@Huseriato Actually, I was reviewing my old notes and [my previous response](https://github.com/mattermost/mattermost-webapp/pull/2635#issuecomment-483693548) still stands, but I think I didn’t explain the reasoning sufficiently:

1 - Given the `innodb_ft_min_token_size` is 3 by default, that means searching for usernames with 1 or 2 characters won’t work properly by default. There will be issues with recent mentions search and potentially other areas of the UI.
  - Simply allowing users to create 2 character usernames when the database only searches for 3+ characters does not follow our [fast, obvious, forgiving](https://docs.mattermost.com/developer/fx-guidelines.html#fast-obvious-forgiving) design principle, given we let administrators and users to make a mistake in the default configuration.

2 - While it's possible to change the default value to below three characters, larger deployments will likely not do so given the possibility of impacting search performance. Thus, we would necessarily cause breaking issues with username search for largest deployments.

With the above, I feel strongly that we should keep the default minimum username length at 3.

That said, we [recently added a config.json setting](https://github.com/mattermost/mattermost-server/issues/9156) for changing the minimum searchable hashtag length —> by default it is 3, but it could be changed to 1 or 2 characters.

We could do something similar for usernames, which is adding a config.json setting for the minimum username length. This way, the default value would be 3 not leading to issues in 1 & 2 noted above, while supporting use cases like you and others have mentioned. Two things I’d want to ensure are:

A. Have complete coverage through automated unit tests - given username search occurs throughout the UI, we want to make sure we have adequate testing coverage for it
B. Works seamlessly for PostgreSQL, MySQL and [Elasticsearch](https://docs.mattermost.com/deployment/elasticsearch.html)

However, I think both would be feasible.

If we opened this as a help wanted issue, would this be something you’d be open to help contribute?

**Comment by Huseriato** [comment]
Hello, good to hear. Yes, I'll support this idea.

**Comment by jasonblais** [comment]
@Huseriato Great! I've opened a proposed [help wanted](https://docs.mattermost.com/process/help-wanted.html) (HW) ticket for it https://mattermost.atlassian.net/browse/MM-15268

If approved, we'll add the help wanted label for it, which will then open a GitHub issue for our community to help contribute https://github.com/mattermost/mattermost-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22Up+For+Grabs%22

**Comment by jasonblais** [comment]
@Huseriato We've opened a help wanted ticket and welcome contributions from the community 👍 

https://github.com/mattermost/mattermost-server/issues/10702

Thanks so much for all the feedback above to better understand the use cases.

**Comment by jasonblais** [comment]
@Huseriato I'll close this PR for now given the above discussion, and we can track further development via https://github.com/mattermost/mattermost-server/issues/10702

I'll leave the branch open though, in case you wanted to use it for any other changes.

Thanks so much for bringing this up for discussion. Much appreciated!

**Pull request closed without merging**
