### PR TITLE
inline playback for gif attachments

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Adds Inline playback for git attachments

Cc @dmeza
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by dmeza** [comment]
@esethna rebased to latest from master, added gif playback to preview and re-created snapshots. Checked that styles and tests are passing.

**Comment by dmeza** [comment]
@esethna reviewed the PR and the conflict will be on the snapshot for `components/file_attachment.jsx`. Otherwise it should be fine.

**Comment by hmhealey** [comment]
How does this handle non-animated gifs? Does it load the full image for them or just the thumbnail?

Also, is there any ability to not autoplay the gifs for users who don't want that?

**Comment by dmeza** [comment]
@hmhealey thanks for the comments. 
- Since there's no way to know if it's animated or not, it does load the full image in for gifs. Do you know of a way we can control that?
- It would need a config to display the thumbnail, but that could be a following step.

**Comment by hmhealey** [comment]
For whether or not it's an animated gif, I believe the FileInfo object will have has_preview_image set to false if it's an animated gif (to prompt it to show the animated gif in the preview modal

For turning on/off the animation, I'll double check with PMs. When we had something similar to it in the past, we had a toggle like that, but maybe it's not necessary any more

**Comment by dmeza** [comment]
@hmhealey I'll add that change later today.

**Comment by dmeza** [comment]
@hmhealey made the fix to check than when it's a gif and has_preview_image is true to display the thumbnail. Rebased to latest from master.

**Pull request merged**
