### PR TITLE
Markdown parser replacment using WebAssembly and Rust

### PR DESCRIPTION
**Pull request by crspeller**
## Overview
This PR introduces an experimental alternative CommonMark parser written in Rust and compiled to WebAssembly for use in the web app. It is based on the https://github.com/raphlinus/pulldown-cmark library with modifications to support Mattermost's unique features.

This PR is fully compatible with all browsers we currently support. All browsers we currently support will be able to use the new WebAssembly parser except IE11. IE11 does not support WASM and therefore, this PR provides a mechanism for browsers that do not support WASM to fall back to using the old parser. The code that does this is found in the root component. 

Since we need to support the fallback for now, the changes to the current parser are limited to a branch and a few hooks for the WASM code. The bulk of the new code can be found in `rust/src/markdown.rs`.

## Breaking Changes
Currently there are some breaking changes to our markdown syntax in this PR:
- Strikethrough text is not supported. (not part of the CommonMark specification)
- Resizing markdown embedded images is not supported. (not part of the CommonMark specification)
- Switching to bullets half way though a numbered list does not keep numbering going (no idea why this is our behavior)
- A new line after a list doesn't not end a list. Need a blank line. (part of the CommonMark spec)

Developer machines will require a rust installation.

## Next steps
- Dropping support for IE11 and removing the fallback.
- Moving more of the text processing code that currently needs to be called back to JS from the rust code (`doHighlight` and `wasmDoFormatText`) into rust.
- Investigate the feasibility of using this on our react-native app or the server.

## Trying this out
Developers need to do some setup to build this PR.

### I have a rust environment
If you already have a rust development environment you need to make sure you are upgraded to rust 1.30 and install the target `wasm32-unknown-unknown`.
```
rustup update
rustup target add wasm32-unknown-unknown
```

### I need a rust environment
1. Install the Rust toolchain installer rustup: https://rustup.rs/
2. Run these commands to install the toolchain and wasm target using these commands:
```
rustup install stable
rustup target add wasm32-unknown-unknown
```
Everything else should be installed automatically when you run the build for the first time. If you have trouble please leave a comment on this PR so we can get these instructions correct.

## TODO
1. Install Rust on the build server so this actually builds.
2. Post some performance comparisons. (if you want to do this yourself, make sure you do the performance comparisons in release mode! You're not in JavaScript anymore.)
3. Setup some unit tests from within rust and/or with jest.

### CODE REVIEW

**Comment by hmhealey** [comment]
Some thoughts:
> Using https://github.com/raphlinus/pulldown-cmark

That looks really interesting. I haven't heard of "pull parsing" specifically before, but I like the sound of it. I skimmed their README and something that really stood out to me was how they mention that manyother implementations "make the assumption that the rendering process can be fully represented as a serialized string" since we've dealt with that already with Marked. That's why we use html-to-react which is pretty hokey.

> IE11 support

I don't know what Rust uses to compile to WebAssembly, but if it uses something like Emscripten, we could look at having that compile into JS directly for IE11 so that we can at least use the same source code for both

> - Strikethrough text is not supported. (not part of the CommonMark specification)

This isn't part of CommonMark, but it is part of the [Github Flavored Markdown Spec](https://github.github.com/gfm/) that extends it. That also includes tables, task lists (kind of trivial and could be done after the fact), and URL autolinking (which is different from `<https://example.com>` which Markdown calls autolinking). We'll need to support all of these.

> - Resizing markdown embedded images is not supported. (not part of the CommonMark specification)

This is something we need to reconsider at some point, maybe once we have a better story around how plugins integrate with text formatting since there do seem to be people using the feature even if it's not well supported.

> - Switching to bullets half way though a numbered list does not keep numbering going (no idea why this is our behavior)

That's just because Marked follows the regular Markdown spec which isn't strict about that. It's fine to break that.

> - A new line after a list doesn't not end a list. Need a blank line. (part of the CommonMark spec)

This is an addition we made since we considered the behaviour of Markdown and CommonMark to be confusing for regular users. We should try to match the current behaviour, although we could discuss changing it depending on how much we value spec conformance vs usability improvements.

There's a few other places where we deviate from those specs as well:
1. We have another small usability improvement for double backslashes for UNC paths where it doesn't apply escaping when you have text that looks like `/[\s|^]\\(?:[a-z0-9])+/`
2. We support email autolinking
3. There's all the other stuff we support like at mentions and hashtags although whether that affects this depends on how we decide to structure that

**Comment by hmhealey** [comment]
As for the next steps:

> Moving more of the text processing code that currently needs to be called back to JS from the rust code (doHighlight and wasmDoFormatText) into rust.

We should chat about this at some point. I've spent a lot of time looking at GitHub's [html-pipeline](https://github.com/jch/html-pipeline) library, and I think writing a similar transformation pipeline will be our best bet for handling the other parts of our text formatting like at mentions and such. Apart from the initial Markdown parsing, they have [additional transformations](https://github.com/jch/html-pipeline#filters) that it goes through to perform autolinking, mention parsing, etc, and if we were to write those in Rust, we could make use of them on every platform, and we could mix and match them when needed. Then, we could probably output the resulting AST into a "native" Go or JS object and render it from there on that specific client.

**Comment by hmhealey** [comment]
Last but not least, regarding adding Rust as a dev dependency, we're likely going to store the Markdown parser and related text formatting code in its own repo if we're sharing it across platforms, so could we precompile it so that you don't need Rust to work on the other packages? I don't think it's a blocker if we can't do that, but it would make it easier for people who aren't modifying that part of the code

**Comment by hanzei** [comment]
Hi @crspeller,

I'm wondering if you we should keep the PR open. I don't see this merged in the near term given that there hasn't been an update in the last 12 month. What do you think about closing the PR, but keeping the branch?

**Comment by crspeller** [comment]
Yup. No need for this to be open. If I where to get back to this there would be a bunch of work required.

**Pull request closed without merging**
