### PR TITLE
MM-47879 - add telemetry track to open/close onboarding task list act…

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR adds telemetry to the open/close events over the onboarding task list item.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47879

#### Related Pull Requests
n/a

#### Screenshots
Captura de Pantalla 2022-10-28 a las 13 55 23
Captura de Pantalla 2022-10-28 a las 13 55 47

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by pvev** [comment]
@marianunez @amyblais this is a cloud cherry-pick candidate, a small PR for adding some telemetry, no functionality affected at all.

**Review by JulienTant — APPROVED** [review]

**Review by marianunez — APPROVED** [review]
Thanks @pvev! Can you add the QA Steps for testing this post-merge?

**Comment by pvev** [comment]
@stevemudie @dontoisme this track events additions can be validated post merge 👍

**Comment by cwarnermm** [comment]
@dontoisme - Is there Telemetry documentation impact for this PR, or is this a change we're making that doesn't need to be communicated externally?

**Comment by cwarnermm** [comment]
Friendly follow-up on this, @dontoisme. Is there telemetry documentation updates we'd like to see made associated with this change? My read of this is that telemetry updates aren't needed.

**Comment by dontoisme** [comment]
@cwarnermm I don't think this warrants external communication but I don't know the principles we apply to make sure we are communicating tracking changes. This change is small and the intent is to measure interactions of the onboarding experience so we can make a future decision on how to improve the feature.

**Comment by cwarnermm** [comment]
Thank you for confirming, @dontoisme, and I agree that we need clear principles in place to know when to communicate tracking changes. Revisiting the telemetry documentation is on the docs roadmap this year, and this gap will be addressed as part of that effort.

**Pull request merged**
