### PR TITLE
[MM-34163][MM-34165] - UI fixes to direct channel profile pics

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR addresses minor UI fixes to direct channel profile picture. 
- Removes status icon from bot accounts
- Reduce spacing between icon and label 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34165
https://mattermost.atlassian.net/browse/MM-34163

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @nevyangelova this looks good. One other small change that I think we should do while you're fixing these small tweaks:

Can we change the negative space between the avatar and the status icon to 2px? It's a very small detail, but I think it will help distinguish the status from the avatar.
image

**Comment by nevyangelova** [comment]
Updated @matthewbirtch

**Review by matthewbirtch — APPROVED** [review]
Looks great! Thanks @nevyangelova

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 
Tested, looks good to merge.
- Verified space between icons and channel labels on the sidebar; verified updated negative space around member status icon on the LHS
- Status icon has been removed from bots icons on the sidebar.

**Pull request merged**
