### PR TITLE
Fix Marketplace aria-label in MM-T1476 e2e test

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

The marketplace item in the main menu used to be labeled `Plugin Marketplace`, and is now labeled `Marketplace`. This PR updates the e2e test to reflect this.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-34360

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Thanks for the fix :+1:

**Review by saturninoabril — COMMENTED** [review]
I don't see the change yet on master. Should this PR be submitted against the feature branch where the change was made?

**Review by saturninoabril — APPROVED** [review]
Thanks for fixing Michael!

**Pull request merged**
