### PR TITLE
MM 17278 - Stop posts lists from scrolling when the emoji picker is open

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
When adding a reaction to a post/comment, the posts/comments lists can scroll while the picker remains stationary (ie not anchored to the post/comment that triggered it). This is due to needing to support a full-screen picker when in mobile web view. This PR uses CSS to stop user interaction with the posts/comments lists while the emoji picker is open, preventing scrolling. Dismissing the picker re-enables user interaction.

This approach is a more global, vanilla js approach and quicker/easier to implement. An alternative approach would be to handle each implementation of the emoji picker locally to its usage context within React (would probably need to traverse multiple components). Interested in thoughts on this!

One possible downside to this approach is that no matter what emoji picker is open, posts and comments lists will both have user interaction disabled preventing scrolling until the picker is dismissed.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-17278

### CODE REVIEW

**Comment by lieut-data** [comment]
At a technical level, I don't see a problem. I'd probably suggest a `PM Review` on this one.

**Comment by mickmister** [comment]
I'm not sure about any gotcha's here. Is it possible we end up in a state where the post list is locked indefinitely?

**Comment by deanwhillier** [comment]
I suppose if an emoji picker somehow gets removed without the `componentWillUnmount` function getting called? That shouldn't happen though, should it?

A completely different approach could be to dismiss the Emoji Picker if the user scrolls in the posts/comments lists. That comes with its own set of challenges of course.

**Comment by deanwhillier** [comment]
Okay, we'll go with this for now pending PM review.

**Comment by lindy65** [comment]
Hi @deanwhillier - when you have a chance, can you update this PR with the latest master please? Setting up a test server is failing...

**Comment by jasonblais** [comment]
Hi @deanwhillier - looks like the PR just needs to be synced with `master` and this PR is ready to merge?

It is labelled cherry pick approved, so I'm not sure if that means the changes here will go to 5.17/5.16 as well?

**Comment by deanwhillier** [comment]
Thanks for the reminder @jasonblais! Looks like this is scheduled for 5.18 so I removed the label and will just merge to master.

**Pull request merged**
