### PR TITLE
MM-46858: Hide mention badge in the team icon for muted channels

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR hides unread mention badge in the team icon for muted channels.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/20939
JIRA: https://mattermost.atlassian.net/browse/MM-46858

#### Screenshots
Check the `nostrum` channel in the pictures below

**before**

https://user-images.githubusercontent.com/37421564/188734983-0aa74b6f-0b6d-43f7-ad00-eb3a688f5891.mov

**after**

https://user-images.githubusercontent.com/37421564/188735069-9c60e536-ac23-4e5e-817d-993d450da220.mov

#### Release Note
```release-note
Hides unread icon for muted channels in the sidebar
```

### CODE REVIEW

**Comment by sinansonmez** [comment]
One related question. In the previous PR, we removed muted channels from the unread section of channel switcher. However, when you search the channel, you can still find the channels. In the list, the unread icon is still visible. 

To be consistent, should we also remove the unread icon for muted channels in the channel switcher?
Screen Shot 2022-09-03 at 09 44 59

**Comment by AshishDhama** [comment]
@sinansonmez I don’t think @agnivade (Please correct me if I am wrong) meant to remove mentions badge from the channel item from the sidebar, He was referring to the team icon. 
cc// @matthewbirtch

**Comment by AshishDhama** [comment]
In my opinion, JtheBAB made the valid point ([thread](https://community.mattermost.com/core/pl/9s8zhtfzxbfo3nh7z7wzrsgsqo)) that person mentioning is either expecting the person mentioned to reply or see the message. So we should show muted Channels in the switcher as well with different ones instead of removing anything, reverting the earlier change and adding colour coding like the sidebar.
@matthewbirtch if you could suggest some solution here?

**Comment by sinansonmez** [comment]
Thanks for the correction @AshishDhama. Just for me to understand the terminology for future PRs, which team icon Agniva was referring, and where is it?

Then I will wait for the final decision to do related changes. Please let me know.

**Comment by agnivade** [comment]
Dhama is correct. The team icons are the "EL" and "MI" buttons in your pictures. When you are in EL, and someone in a muted channel mentions you in MI, then you will see 1 in a pill over the MI icon. But when you use the channel switcher, you won't see any unread channel. Hence the confusion.

We need to remove that.

**Comment by esethna** [comment]
@sinansonmez +1 to Agniva above. We just want to remove the mention badges (bubbles with the numbers inside) from the team icons when you have a mention in a muted channel. As Agniva said, these badges only appear when you switch to a different team. We should leave the mention badges on the channel items in the sidebar. Let me know if you have any questions!

image

**Comment by sinansonmez** [comment]
Thanks to all for clarifications @AshishDhama @agnivade @esethna. I updated the PR as suggested.

**Review by esethna — APPROVED** [review]
Thanks @sinansonmez great work! No more action needed, this covers the requirements since we discussed this further in a team meeting this morning

**Review by AshishDhama — APPROVED** [review]

**Comment by AshishDhama** [comment]
@sinansonmez if you could resolve the conflict

**Review by michelengelen — APPROVED** [review]
lgtm

**Comment by hmhealey** [comment]
Adding @M-ZubairAhmed as a reviewer since he changed this code recently. Funnily enough, I think his changes actually made this possible

**Comment by AshishDhama** [comment]
@sinansonmez sorry man I think you need to resolve conflicts again.

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by sinansonmez** [comment]
@AshishDhama conflicts are resolved 🥇

**Review by AshishDhama — APPROVED** [review]

**Comment by michelengelen** [comment]
removing @jgilliam17 since she is on PTO from today on and adding @saturninoabril instead. Feel free to re-assign.

**Comment by michelengelen** [comment]
@jgilliam17 could you take over again please?

**Review by jgilliam17 — APPROVED** [review]
Thanks @sinansonmez 
Tested, looks good to merge.
Verified muted channel mentions are not shown/counted on the team icon mention badge. 
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/238589-868372a-onprem-ent-webapp-pr-11058-mm-ee-test:868372a/mochawesome.html)- no PR related failures.

**Pull request merged**
