### PR TITLE
[MM-24705] Add telemetry for Experimental Sidebar Phase 2

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Telemetry calls for various points in the new sidebar, as described by spec.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24705

### CODE REVIEW

**Comment by esethna** [comment]
@devinbinnie were we able to add all events in the spec?

**Comment by devinbinnie** [comment]
> @devinbinnie were we able to add all events in the spec?

Yes, except for this one:

```
Can we get data or do we already have data that tells us the number of DMs users have in their sidebar? Ie DMs that are visible in the sidebar because they haven’t been closed (or hidden via the hide after 7 day setting). 
```

**Pull request merged**
