### PR TITLE
Fix ImageProxy settings

### PR DESCRIPTION
**Pull request by ThiefMaster**
#### Summary
This fixes the admin console not showing the current values for image proxy settings, nor being able to save them.

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by lieut-data** [comment]
Thanks, @ThiefMaster! @jasonblais, this seems like a candidate for a 5.0.1.

**Comment by ThiefMaster** [comment]
Great! Do you want me to rebase against `release-5.0` and change the target of this PR, since it's currently against `master`?

**Comment by jasonblais** [comment]
@lieut-data @ThiefMaster This only affects the image proxy settings, correct?

And is this a recent regression, or does it appear to have been a bug for a while?

**Comment by ThiefMaster** [comment]
I just checked on my 4.10.1 production server, and the settings work fine there.

**Comment by jasonblais** [comment]
Thanks @ThiefMaster! 

@lieut-data @ThiefMaster While it's a regression, only a few have enabled it (and hence would be affected), and there is an easy workaround to configure it in config.json instead.

So I don't think we need a 5.0.1 for it. 5.1 is sufficient.

I'll add a note to the 5.0 changelog though for a known issue.

**Comment by jasonblais** [comment]
By the way, big thanks @ThiefMaster for noticing and fixing the issue :)

**Comment by jespino** [comment]
Thanks @ThiefMaster !! :sparkles:

**Pull request merged**
