### PR TITLE
[MM-42030] CRT Thread pane tutorial tour migration to new tour tip component

### PR DESCRIPTION
**Pull request by AbhinavVihan**
#### Summary
CRT Thread pane tutorial according to new tour tip component

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/19802
Fixes https://mattermost.atlassian.net/browse/MM-42030

#### Related Pull Requests
None

#### Screenshots
NA

#### Release Note
```release-note
CRT Thread pane tutorial according to new tour tip component
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by jgilliam17** [comment]
@AbhinavVihan can you please fix conflicts and update - thanks 🙂

**Comment by AbhinavVihan** [comment]
@jgilliam17 Conflicts have been resolved. Would you take another look please.

**Review by jgilliam17 — APPROVED** [review]
Thanks @AbhinavVihan 
Tested, looks good to merge.
Verified crt tutorial is working as before.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/238998-0cd7175-onprem-ent-webapp-pr-11107-mm-ee-test:0cd7175/mochawesome.html) - no PR related failures.
@AshishDhama can you please approve the last check/workflow and merge - thanks 🙂

**Pull request merged**
