### PR TITLE
[MM-15220] Add support for generic error message in interactive dialog

### PR DESCRIPTION
**Pull request by pbitty**
#### Summary

This implements the webapp portion of https://github.com/mattermost/mattermost-server/issues/12043.

There are no tests for the `InteractiveDialog` yet, but I wanted to get this in front of people's eyes to validate the approach and CSS styling.  I am not experienced with CSS, but I'm putting this up as a starting point.

---

While working on this, I ran into the bug described in [MM-18340](https://mattermost.atlassian.net/browse/MM-18340).  I worked around it by having the server-side integration       sending the `OpenDialogRequest` two seconds _after_ the response had been returned to the webapp.

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/12043

#### Related Pull Requests

- https://github.com/mattermost/mattermost-server/pull/12081

### CODE REVIEW

**Comment by pbitty** [comment]
This is what it looks like:

Screen Shot 2019-09-08 at 2 59 22 AM

**Review by aaronrothschild — APPROVED** [review]
LGTM!  Thanks for your contribution @pbitty !

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by iomodo — APPROVED** [review]
LGTM! Thanks @pbitty 👍

**Review by prapti — APPROVED** [review]
Works as expected.
Approving.

**Comment by amyblais** [comment]
Removed from v5.16 because it didn't make it to feature complete. Please let me know if this is important for v5.16.

**Comment by hanzei** [comment]
@amyblais No, this feature isn't important. But it would be great for integration developers to get this in. This feature is already implemented in the demo plugin, which makes testing a lot easier. The current state is:
- Server: Merged
- Webapp: Reviews and tests done
- Mobile: 1/4 reviews

What do you think about merging the webapp PR and deferring mobile for the next release? This way integration developer can start experimenting with this.

**Comment by amyblais** [comment]
I think it would be good to have features together both on webapp and mobile. I've asked Jesse to go through remaining v5.16 feature tickets and he'll let me know if we want this in for v5.16.

**Pull request merged**
