### PR TITLE
Fix active state for dropdown

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Fixes active state of dropdown

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

### CODE REVIEW

**Comment by sudheerDev** [comment]
@stephenkiers I don't know about open class either

**Comment by asaadmahmood** [comment]
Hey @sudheerDev what was the issue we were facing?

**Comment by asaadmahmood** [comment]
If the issue is having the title with the icon colored when the dropdown is open, then that make sense, however, with the current changes, only the icon is colored, and the text is not.
screen shot 2018-01-19 at 10 10 12 pm

**Comment by asaadmahmood** [comment]
I have fixed that however with my commit.

**Comment by sudheerDev** [comment]
@asaadmahmood Active state when we open drop-down for channel header options. And it works fine for me without just my commit

screen shot 2018-01-19 at 10 49 25 pm

**Comment by stephenkiers** [comment]
Okay. So adding the hover color on `.open` is different than on `:hover`. Which behaviour is preferred?

**Comment by asaadmahmood** [comment]
Not sure why it wasn't working for me, but after my commit it does, so I think lets just keep my commit as a safe side.

**Comment by sudheerDev** [comment]
@asaadmahmood Stange. Anyway, your commits works for me too 👍

**Pull request merged**
