### PR TITLE
added a guard to check for the currentUser in `status_dropdown.tsx`

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
this PR aims to potentially fix the "white screen of death" issue appearing in spinwick instances.

The issue first appeared after the global header got introduced in all instances.

PRs in which the error occurs (list might not be complete):
- #8645 
- #8648 
- #8651 
- #8677 
- #8678 
- #8679 

cc// @spirosoik @jgilliam17 @andrewbrown00 

#### Ticket Link
```
NONE
```

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by andrewbrown00 — APPROVED** [review]
Thanks, @michelengelen, looks good, and NO white screen for me 🙂

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified both types of users, admin and non-admin, are able to log in onto test server. Checked for both when global header is enabled and also disabled (for now).

**Review by lieut-data — APPROVED** [review]

**Pull request merged**
