### PR TITLE
[MM-20070] Added rule for focused SubMenuItem

### PR DESCRIPTION
**Pull request by lapaz17**
#### Summary

Adds a rule for SubMenuItem (Move to...) under channel header.
#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/20070

#### Screenshots

|  before  |  after  |
|----|----|
| <insert before screenshot here>
20070b
 | <insert after screenshot here

> |

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @lapaz17!

**Review by hmhealey — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected

**Comment by hmhealey** [comment]
Whoops. I only realized after merging it that the ticket number was wrong in the title. Jira should at least find this PR with the updated number at least

**Pull request merged**
