### PR TITLE
[MM-30360] Cypress/E2E: Account settings

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

For the `Set user status` test, there is a step that says to change the theme, and then verify that the icons appropriately change their styling to reflect the new theme. I wasn't sure how to accomplish this so it is not implemented at the moment.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30360

- [x] [MM-T2080](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2080) - Can remove profile pic

- [x] [MM-T2088](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2088) - View and Logout of Active Sessions (Se)

- [x] [MM-T2090](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2090) - Theme Colors: New theme color is saved

- [x] [MM-T2927](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2927) - Set user status

### CODE REVIEW

**Comment by DHaussermann** [comment]
@mickmister all test run green and seem in order. But, I'm not sure I understand your concern about the status color. These do change between light and dark theme. 
Screen Shot 2020-12-09 at 11 37 18 AM

Ca you verify in the DOM that these colors update? They don't always change but in some cases they vary and the negative space within the color updates.

**Review by saturninoabril — APPROVED** [review]
Thanks @mickmister! Tested and all passed. LGTM.
Heads up that we are transitioning to adopt more usage of testing-library with Cypress automation. There's an active documentation PR about it, especially on ["which query to use"](https://github.com/mattermost/mattermost-developer-documentation/pull/745/files#diff-b28dacdaa9e85745c4e44fbafc016a2f3a7b6077b31fedce8dab7b94d34847c6R10). Next action from us is to update our codebase, one-by-one (per section of the app). Please consider looking at the guide in the future and let us know any feedback/comment.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
Test run green and follow TM4J scripts
LGTM!

@saturninoabril heads up that in this case there was no way to confirm the theme changing icon status with a reasonable amount of effort due to the way the icon color is inherited from CSS elsewhere. After speaking with @mickmister  the validation around theme that is included seemed reasonable enough.

**Pull request merged**
