### PR TITLE
[MM-31364] - Remove whats new modal

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Remove What's new Modal from the sidebar and all associated definitions

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31364

### CODE REVIEW

**Review by devinbinnie — COMMENTED** [review]
Are we sure we want to outright delete the modal? I feel like we'll want it to showcase other changes to the application in the future.

**Comment by nevyangelova** [comment]
> Are we sure we want to outright delete the modal? I feel like we'll want it to showcase other changes to the application in the future.

From my understanding yes and we will use the in product notice for the future.

**Review by devinbinnie — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks @nevyangelova! Tested and passed. LGTM.

**Review by hmhealey — CHANGES_REQUESTED** [review]
I think we can also remove the animated gif that appeared in that modal if you could remove that too

**Comment by hmhealey** [comment]
Also adding Do Not Merge so we can merge this once we've confirmed we're ready to go to GA

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
