### PR TITLE
ICU-695 - Fixing paragraph spacing for last child

### PR DESCRIPTION
**Pull request by stephenkiers**
This is a response to PR- https://github.com/mattermost/mattermost-webapp/pull/731

I removed the span as I didn't see the need for it, and therefore the `display: inline-block` works again.

### CODE REVIEW

**Comment by stephenkiers** [comment]
I am updating snapshots

**Comment by stephenkiers** [comment]
screen shot 2018-02-06 at 5 26 21 pm

**Comment by asaadmahmood** [comment]
@stephenkiers Can you edit your message?

**Comment by asaadmahmood** [comment]
Yup, this looks better.

**Pull request merged**
