### PR TITLE
Removed unused roles requests state objects

### PR DESCRIPTION
**Pull request by djanda97**
#### Summary

As a part of https://github.com/mattermost/mattermost-server/issues/12520, this PR removes unused roles requests state objects from the webapp.
Changes will also need to happen in the redux repo.
#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/12520
#### Related Pull Requests

- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by jgilliam17** [comment]
@michelengelen or @jespino Can you please add QA test steps? I am not sure how to test this. Thanks.

**Comment by jespino** [comment]
@jgilliam17 This is only touching the admin console permissions/roles management, where you define the roles and the permissions for each role, if that loads and shows properly, should be fine (anyway, this change is really tiny).

**Review by jespino — APPROVED** [review]
Looks good to me, Thanks @djanda97! :tada:

**Comment by michelengelen** [comment]
I was just checking the impact as well, just when @jespino wrote his comment... ✨

**Review by jgilliam17 — APPROVED** [review]
Thank you @djanda97 
Tested, looks good to merge.
- Verified system console user permissions and roles management, no issues.
Thank you Jesus and Michel for adding the steps. @michelengelen Can you please help merge? 🙂

**Comment by michelengelen** [comment]
Done! ... thanks for your contribution @djanda97 ✨

**Pull request merged**
