### PR TITLE
[MM 42088] : Compact message view thread footer avatar click issue

### PR DESCRIPTION
**Pull request by VishakhaPoonia**
#### Summary
Fixes: CRT: Compact message view, clicking on thread footer avatar is not opening profile modal

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/19659
  Fixes https://mattermost.atlassian.net/browse/MM-42088

#### Related Pull Requests
NONE

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot 2022-03-09 at 9 28 39 AM | Screenshot 2022-03-09 at 9 28 10 AM |

#### Release Note
```release-note
UI: Fixes : CRTCompact message view, clicking on thread footer avatar is not opening profile modal
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Thanks for the PR, @VishakhaPoonia! Looking at the PR, it's also changing it so that the area to the left of username (where user's status icon is) is now clickable as well because this rule affects all `.status-wrapper` elements in the post. Perhaps we can narrow this change so that it only affects the profile pictures in the collapsed thread footer?

**Comment by VishakhaPoonia** [comment]
@hmhealey I have made the pointer css more specific to status wrapper it is targeted for hope that works.

**Review by hmhealey — APPROVED** [review]
Perfect! Looks good to me now

**Review by koox00 — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @VishakhaPoonia 
Tested, looks good to merge.
- Verified click on thread avatars in compact message view opens user profile modal.
-  [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/173599-d6e6c8b-onprem-ent-webapp-pr-9926-mm-ee-test:d6e6c8b/mochawesome.html) looks good, no PR related failures.

**Pull request merged**
