### PR TITLE
MM-11387: tweak tooltip CSS

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Remove the `display` and `flex-direction` properties to fix the tooltip
rendering in the announcement banner. This seems to make no difference
to the rendering of the tooltips in the team sidebar.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-23546

#### Screenshots
Before:
image

After:
image

Also:
image

### CODE REVIEW

**Comment by lieut-data** [comment]
I've opted to skip `2: Dev Review` here since if this passes `1: UX Review`, there's literally nothing to review. Will still ask for QA Review to ensure behaviour is as expected.

**Comment by deanwhillier** [comment]
Just happened upon this and wanted to mention that if there is no `display: flex` being used, `align-items: center` has no effect since it is a flexbox specific property. :)

**Comment by lieut-data** [comment]
Good catch, @deanwhillier -- thanks :)

**Comment by lieut-data** [comment]
@andrewbrown00, happy to help with that. Do you mind if I submit a separate PR to `master` (for v5.23) as such? It looks like the required changes include moving some React elements around, and I'm unsure how that will affect the various announcement bars and supported browsers.

**Comment by andrewbrown00** [comment]
> @andrewbrown00, happy to help with that. Do you mind if I submit a separate PR to `master` (for v5.23) as such? It looks like the required changes include moving some React elements around, and I'm unsure how that will affect the various announcement bars and supported browsers.

Not at all @lieut-data, thanks for the context 😄

**Comment by lieut-data** [comment]
Thanks, @andrewbrown00! Once this is approved and merged, I'll push that PR your way for a secondary review as well :)

**Comment by lieut-data** [comment]
Moved this back to v5.22 given the regression in rendering, but will keep the CSS tweaks and reorganization for v5.23.

**Comment by lieut-data** [comment]
@andrewbrown00, just to confirm, are you good with the changes here? (Looking for two reviewers before I move on to QA Review.)

**Comment by lieut-data** [comment]
@andrewbrown00, I'm going to go ahead and merge and cherry-pick this -- feel free to ping me if you have any concerns with the code changes as proposed relative to v5.22.

**Pull request merged**
