### PR TITLE
MM-14119 - Upating header button styling

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-14119 - Upating header button styling

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-14119

### CODE REVIEW

**Comment by cpanato** [comment]
checking the test server, bear with me

**Comment by hmhealey** [comment]
I added the PM Review label since it looks like this is still waiting on review from @michaelgamble

**Comment by hanzei** [comment]
Can this PR get merged?

**Comment by hmhealey** [comment]
@asaadmahmood Are we okay to merge this? It doesn't seem like there's anything left to be done here

**Comment by asaadmahmood** [comment]
@hmhealey @hanzei Yes please.

**Pull request merged**
