### PR TITLE
Add E2E test for desktop notifications for empty strings

### PR DESCRIPTION
**Pull request by shinnlok**
#### Summary

Adds a test for MM-T497 Desktop Notifications for empty string without mention badge

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15701

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Thanks @shinnlok! 
This looks good to me (although tbh it's my first server e2e review).

**Review by prapti — CHANGES_REQUESTED** [review]
Thank you for working on this @shinnlok! The test looks great and passed as well. I have suggested some minor changes in the comments. Would you mind revisiting them? TIA!

**Comment by shinnlok** [comment]
@prapti Updated. Thanks for the feedback!

**Review by marianunez — APPROVED** [review]
Thanks @shinnlok! There is a linter error from your last commit, besides that, LGTM. 👍

**Review by prapti — APPROVED** [review]
Thank you for your contribution @shinnlok! The test looks good, and it's a great first time contribution 🎉

**Pull request merged**
