### PR TITLE
MM-20078: Migrate 'components/admin_console/radio_setting.jsx' and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by allenlai18**
#### Summary

Migrate 'components/admin_console/radio_setting.jsx' and associated tests to TypeScript 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-20078

### CODE REVIEW

**Comment by allenlai18** [comment]
> Thanks @allenlai18 👍
> 
> Would you be open to adding tests for your PR please?

@lindy65  Yes. I would be open. What test are you talking about though?

**Comment by lindy65** [comment]
Hi @allenlai18 :)

Thanks, In the title it mentions 'associated tests' so I'm not sure whether any unit tests existed already?  If they do, then it would be converting them to TypeScript.  If none exist, it would mean writing unit tests for this PR...

**Comment by jespino** [comment]
@allenlai18 you can base your tests in other similar files in the same directory, for example `color_setting.test.tsx`.

**Comment by allenlai18** [comment]
> Hi @allenlai18 :)
> 
> Thanks, In the title it mentions 'associated tests' so I'm not sure whether any unit tests existed already? If they do, then it would be converting them to TypeScript. If none exist, it would mean writing unit tests for this PR...

@lindy65 @jespino :)  Gotcha, so there is a unit test for radio_setting.tsx but its for the one in /widgets/settings/ .    I migrated the one in admin_console.   They both have the exact same component name and filename.  Would it be better to rename them?   I will write unit test for admin_console RadioSetting

**Comment by lindy65** [comment]
Thanks @allenlai18, appreciated 👍 

I'll defer to @jespino for your question on renaming...

**Comment by jespino** [comment]
I don't think so, one of the is a widget that is design to be generally used (but is only used in one place for now) and the other is scoped to the admin console, I think we can keep both as they are.

**Comment by allenlai18** [comment]
> Now looks good to me. Thanks @allenlai18! 🎉

I do not have much experience in writing unit test. please let me know if there are any suggestions or things that I could have done better!

**Comment by allenlai18** [comment]
just added the .snap file

**Comment by jespino** [comment]
@allenlai18 yes, you had to add it, thanks

**Comment by jespino** [comment]
Merged! thanks @allenlai18! :tada:

**Pull request merged**
