### PR TITLE
[MM-44657] Insights responsive

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Adding media queries for responsiveness

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44828

#### Screenshots

1680 min
Screen Shot 2022-06-03 at 2 42 45 PM
Screen Shot 2022-06-03 at 2 43 08 PM

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by plant99 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@BenCookie95 do you think we can get a test server up with the changes for me to review or did you want to do another live review?

**Comment by matthewbirtch** [comment]
Thanks @BenCookie95 that works perfectly for me

**Review by matthewbirtch — APPROVED** [review]
Really great work @BenCookie95!

**Review by furqanmlk — COMMENTED** [review]
Insight is not responsive with thread window

image

**Comment by matthewbirtch** [comment]
> Insight is not responsive with thread window
> 
> image

@furqanmlk Ben and I talked about this and agreed we would work on improving this as a follow-up

**Pull request merged**
