### PR TITLE
MM-19517 Adding ability to disable attachment buttons and fields.

### PR DESCRIPTION
**Pull request by crspeller**
### Summary 
Adds ability to disable buttons and fields in slack attachments.

### Screenshot
image

### CODE REVIEW

**Comment by DHaussermann** [comment]
@crspeller I'm not seeing what I expected here. I don't know if it's a deployment issue or if I'm just rusty on the use case when this would occur.

After I start a workflow, it move to a step such as `Triage`. I then select some options and transition the workflow to the `Triaged` step, I expected to see a screen such as what you attached above. Instead I'm seeing what looks like the previous behavior. Drop-down options can be adjusted and button appear to be in a functional state.
SelectableOptions

**Comment by crspeller** [comment]
@DHaussermann This has to be implemented on the plugin side as well. You can generate a slack attachment yourself using the disabled field. 
I will also DM you a version of the plugin where I have implemented this.

**Comment by DHaussermann** [comment]
@crspeller, strangely I'm still not seeing the change with the advanced build you supplied.

Looking at the spin-up server ☝️ the webapp build hash matches the commit. But the server build hash does not match https://github.com/mattermost/mattermost-server/pull/11669 Is there a way you can confirm that the server code needed is being included?

**Comment by crspeller** [comment]
@DHaussermann Ya it's not the right commit. Looking for clarification from the cloud team.

**Comment by crspeller** [comment]
@DHaussermann Test servers fixed by https://github.com/mattermost/mattermost-webapp/pull/4204 so it works now.

**Comment by aaronrothschild** [comment]
@crspeller Is this documented anywhere on developers.mattermost.com?  I can't find a reference to it.

**Comment by crspeller** [comment]
I don't think they are documented there. The docs are in the main docs here: https://docs.mattermost.com/developer/message-attachments.html

**Pull request merged**
