### PR TITLE
Updating compass icons

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Updating compass icons

#### Ticket:
https://mattermost.atlassian.net/browse/MM-28200

### CODE REVIEW

**Comment by hmhealey** [comment]
Is there a ticket attached to this or something we can refer to for what changed?

**Comment by devinbinnie** [comment]
@hmhealey @asaadmahmood You can use this, as I needed the credit card icon added:
https://mattermost.atlassian.net/browse/MM-28200

**Comment by asaadmahmood** [comment]
For QA, just have a quick scan and see if the icons in the app (sidebar, autocomplete etc) appear the same on this PR as in daily.

**Review by hmhealey — APPROVED** [review]

**Review by srkgupta — APPROVED** [review]
Did some sanity test on the webapp and the icons looked fine. Approving the PR.

**Pull request merged**
