### PR TITLE
PLT-7617: Admin console UI for Data Retention settings.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
Admin console UI for Data Retention settings, as per spec.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7617

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file updates

### CODE REVIEW

**Comment by jasonblais** [comment]
^All P2s can be separate tickets, doesn't block merging the PR

**Comment by grundleborg** [comment]
1) Easy server-side fix. Will do in a separate PR.
2) I'll add server side validation in the same PR as for (1) that gives an error if greater than some ridiculous maximum (100,000 days?)
3) The messages are deleted but the files are retained on s3/local disk until they reach their cutoff date.
4) As it's P2, propose a separate ticket for this?
5) As for (4)
6) Will update this PR.
7) Can do. Will again update this PR.
8) This will be provided automatically when we add Corey's job table to this page (in a future PR).

**Comment by jasonblais** [comment]
Thanks! All +1. For 2), 100,000 days should be fine :) 

Will create separate tickets for 4/5

**Comment by grundleborg** [comment]
(6) & (7) are done. You'll probably want me to change the error on invalid time too - that'll be part of the upcoming server PR :)

**Pull request merged**
