### PR TITLE
Terminology changes: Account Settings to Profile

### PR DESCRIPTION
**Pull request by cwarnermm**
#### Ticket Link
```
N/A
```

#### Release Note
```release-note
Updated **Account Settings** terminology to **Profile**. 
```

### CODE REVIEW

**Comment by cwarnermm** [comment]
@saturninoabril - I believe I have the remaining instances of Account Settings updated to Profile. Can you re-run E2E tests and let me know if there are further issues that I need to address, please?

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by saturninoabril** [comment]
@cwarnermm I was out last week and only see this now. I'll fix the merge conflicts then will run E2E.

**Comment by saturninoabril** [comment]
E2E at https://automation-dashboard.vercel.app/cycles/8db1d23f-8e17-45f3-b896-3f6270353502

**Review by saturninoabril — APPROVED** [review]
@cwarnermm Tests passed. Thanks for improving and making terminologies consistent!
@jgilliam17 You might want to take a final look or feel free to merge. Also, please let us know how you'd plan to update the affected test cases in Zephyr. @lindy65 fyi since this will potentially break lots of tests in RFQA.

**Comment by jgilliam17** [comment]
Thanks @saturninoabril for running the E2Es
@cwarnermm I found one more instance in System Console>Integrations>Integration Management> Enable Personal access tokens
Other then this, everything else looks good. Thanks.
Screen Shot 2021-11-08 at 4 37 30 PM

**Comment by cwarnermm** [comment]
Great catch, @jgilliam17! I've updated that remaining instance of Account Settings to Profile.

**Review by jgilliam17 — APPROVED** [review]
Thanks @cwarnermm 
Tested, looks good to merge.

**Pull request merged**
