### PR TITLE
Fix post component date separator and mobile view

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR addresses smaller bugs related to the post component unification as well as UI adjustments to the post container

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50395
https://mattermost.atlassian.net/browse/MM-50357

#### Release Note

```release-note
UI fixes for the new post component
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Comment by nevyangelova** [comment]
closing in favour of https://github.com/mattermost/mattermost-webapp/pull/12201 so we can run the pipeline

**Pull request closed without merging**
