### PR TITLE
[MM-20486] 🏷 migrated 'post_add_channel_member' module to TypeScript

### PR DESCRIPTION
**Pull request by paulussujono**
#### Summary
Migrated 'components/post_view/post_add_channel_member' module and associated tests to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15455
Jira - [MM-20486](https://mattermost.atlassian.net/browse/MM-20486)

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

**Review by crspeller — APPROVED** [review]

**Review by lindalumitchell — APPROVED** [review]

**Comment by hanzei** [comment]
@paulussujono Could you please resolve the merge conflicts? Then this PR is good to go.

**Comment by hanzei** [comment]
@paulussujono Merging `master` seems to have broken CI. Can you please take a look?

**Comment by paulussujono** [comment]
@hanzei the test for `components/data_prefetch/data_prefetch.test.tsx` seems to be broken on `master`

**Comment by hanzei** [comment]
@paulussujono CI seems to be able to run that test just fine

**Pull request merged**
