### PR TITLE
For Dev and QA, allow RUDDER_KEY and RUDDER_DATAPLANE_URL env vars to…

### PR DESCRIPTION
**Pull request by Adovenmuehle**
… be used for telemetry.

#### Summary
To ease dev and QA development and testing of telemetry, we'll allow environment variables to allow telemetry to be sent from local environments, spinwicks, and other non-RC or production environments.

#### Related Pull Requests

- Has server changes
https://github.com/mattermost/mattermost-server/pull/15026
Note: this doesn't technically depend on the server PR but is related

### CODE REVIEW

**Comment by Adovenmuehle** [comment]
@grundleborg @jespino @jaydeland Please take a peek.

**Comment by Adovenmuehle** [comment]
@grundleborg Need guidance here as well

**Comment by grundleborg** [comment]
@amyblais I see you've set the milestone for this to 5.27 but not added the Cherry-Pick-Approved label. Is this intended to be cherry-picked to 5.27, or merged just to master for 5.28?

**Comment by amyblais** [comment]
@grundleborg I've set the milestone for it to get prioritized by request from Alex, but I don't know if it needs cherry-picking to a release or not.

**Comment by amyblais** [comment]
I'll let @Adovenmuehle comment ^

**Comment by Adovenmuehle** [comment]
I went through the telemetry tickets and I think we should be ok just merging this to master for 5.28.

**Pull request merged**
