### PR TITLE
MM-38260: Enabled the team list and team details system console pages in team edition build.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Enabled the team list and team details system console pages in team edition build.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-38260

#### Screenshots

Screen Shot 2021-09-16 at 4 13 19 PM
Screen Shot 2021-09-16 at 4 13 30 PM
Screen Shot 2021-09-16 at 4 13 40 PM

#### Release Note

```release-note
Enabled the team list and team details system console pages in team edition build.
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks for the extra push on this @mkraft!

**Review by neallred — APPROVED** [review]
lgtm!

**Review by stevemudie — APPROVED** [review]
- Verified that the Teams sub-page is present on all cloud and on-prem versions
- Sync Group Members and Groups only available to E20 and Enterprise as expected

Nice work @mkraft!

**Comment by jasonblais** [comment]
Thank you all! You rock 🤘

**Pull request merged**
