### PR TITLE
[MM-48994]: disabled ability to apply markdown in preview mode

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
previously it was (incorrectly) allowed to apply markdown formatting in preview mode. This PR adds an early return to the `applyMarkdown` functions in `advanced_create_post.tsx` and `advanced_create_comment.tsx` (the only places where this is relevant).

#### Ticket Link
[MM-48994](https://mattermost.atlassian.net/browse/MM-48994)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

[MM-48994]: https://mattermost.atlassian.net/browse/MM-48994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by michelengelen** [comment]
adding @matthewbirtch to check if this is what UX would expect as well.

**Review by AshishDhama — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @michelengelen - can you please fix failing checks so I trigger e2es? 
Tested looks good to merge - pending e2es
Verified markdown can't be applied in draft preview mode.

**Review by matthewbirtch — APPROVED** [review]
Seems good to me

**Comment by michelengelen** [comment]
@jgilliam17 I have run the E2E tests ... if there are no PR-related fails please feel free to merge this. Thanks!

**Comment by jgilliam17** [comment]
I'll re-run e2es after update, latest [report](https://mattermost-cypress-report.s3.amazonaws.com/285975-0aabd10-onprem-ent-webapp-pr-11849-mm-ee-test:0aabd10/mochawesome.html) had 150+ failures

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
New [report ](https://mattermost-cypress-report.s3.amazonaws.com/286390-8098d4b-onprem-ent-webapp-pr-11849-mm-ee-test:8098d4b/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Comment by jgilliam17** [comment]
I didn't merge since the Performance benchmark check is still failing. I'm re-running one failed check, will merge in the morning if it's green.

**Comment by michelengelen** [comment]
@jgilliam17 the failures in the benchmark run are unrelated to my changes, so I will proceed and merge it. Thanks!

**Pull request merged**
