### PR TITLE
MM-45624: Removed extra checkbox nesting. Split-out individual group permissions.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

* Removed a bug where the group permissions had an extra level of nesting in the UI. 
* Split-out the permissions checkboxes into their individual custom group permissions for a greater granularity of control.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45624

#### Related Pull Requests

n/a

#### Screenshots

Screen Shot 2022-07-15 at 1 56 48 PM

#### Release Note

```release-note
Removed a bug where the group permissions had an extra level of nesting in the UI. Split-out the permissions checkboxes into their individual custom group permissions for a greater granularity of control.
```

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]

**Comment by mkraft** [comment]
> ### When `Edit` checkbox is **OFF** `[ ]`
> 1.`Edit Details` option can still be seen. 2. When Group name is edited, it does not give a proper error message. However, In Network log it shows `You do not have the appropriate permissions` message image
> 
> ### When `Delete` checkbox is **OFF** `[ ]`
> 1. `Archive Group` option can still be seen.
> 2. When Group is archived, There is no error message. However, In Network log it shows `You do not have the appropriate permissions` message
> 
> image

It looks like we have some existing bugs around showing edit and delete options in the UI in spite of lacking those permissions. I'll open a separate ticket since the two things can be shipped distinctly and this PR can still add value for users in isolation of the UI fixes.

**Comment by mkraft** [comment]
@furqanmlk https://mattermost.atlassian.net/browse/MM-45909

**Review by furqanmlk — APPROVED** [review]
Working as expected adding test cases

**Pull request merged**
