### PR TITLE
MM-18943 migrate about_build_modal to typescript

### PR DESCRIPTION
**Pull request by cmygray**
#### Summary

Converts `about_build_modal` component to TypeScript React class component.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18943

Fixes https://github.com/mattermost/mattermost-server/issues/12475

### CODE REVIEW

**Comment by cmygray** [comment]
completed CLA

**Comment by devinbinnie** [comment]
Hey @cmygray, it looks like there are some conflicts on your branch, as well as some lint and type-check errors.
Would you be able to resolve those before I take a look? Thanks!

**Comment by jasonblais** [comment]
Hey @cmygray, let us know if we can help with resolving the conflicts on your branch, and the lint and type-check errors mentioned by @devinbinnie above. Happy to help. Thanks for your contribution!

**Comment by hanzei** [comment]
This PR has been inactive for quite some quite. I'm going to close it. @cmygray Let me know, if you want to continue working on this PR.

**Pull request closed without merging**
