### PR TITLE
[MM-32120] - Restrict calls to `/cloud/subscription` endpoint to only admins

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This issue was initially intended to remove permissions from the ```/cloud/subscription``` endpoint but we decided against that. In order to remove/reduce the unwanted logs, we add a check for only admins to call ```/cloud/subscription``` endpoint

#### Ticket Link
[MM-32120](https://mattermost.atlassian.net/browse/MM-32120?atlOrigin=eyJpIjoiMDBlM2IyOGUzNjM3NDgyM2JjNzc5ODIwOTU0YjcyM2QiLCJwIjoiaiJ9)

#### Related Pull Requests
[Has server changes](https://github.com/mattermost/mattermost-server/pull/16786)

### CODE REVIEW

**Comment by marianunez** [comment]
Is this ready for review?

**Comment by AGMETEOR** [comment]
> Is this ready for review?

yes

**Review by marianunez — APPROVED** [review]
Great stuff @AGMETEOR!

**Review by pablovelezvidal — APPROVED** [review]

**Comment by stevemudie** [comment]
@pablovelezvidal @marianunez Can you guide me on how to test this?

**Comment by AGMETEOR** [comment]
> @pablovelezvidal @marianunez Can you guide me on how to test this?

How to test:
- Login as normal user
-  Observe network tab 
- Also, you could toggle the Main menu

I agree there's really no concrete way to test this.

**Pull request merged**
