### PR TITLE
MM-31391: Add max connection idle timeout to config

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-31391

Companion of https://github.com/mattermost/mattermost-server/pull/16792

### CODE REVIEW

**Comment by agnivade** [comment]
@haardikdharma10 - Feel free to see the test to get an idea.

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Review by isacikgoz — APPROVED** [review]
Looks good 👍

**Comment by agnivade** [comment]
Adding @sbishel for admin console changes.

**Review by sbishel — APPROVED** [review]
LGTM

**Pull request merged**
