### PR TITLE
PLT-7633 Add config setting for session idle timeout

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Add config setting for session idle timeout. Also fixed some capitalization. ~~Waiting on mattermost/mattermost-server#7524~~

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7633

#### Checklist
- [x] Has server changes (mattermost/mattermost-server#7524)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jwilander** [comment]
Now that the server changes have been merged, should be ready for PM review @jasonblais

**Comment by jasonblais** [comment]
Created a PR that tweaks the help text (adds that 0 is unlimited, which wasn't immediately obvious): https://github.com/mattermost/mattermost-webapp/pull/78

Smoke tested and works well. Have asked Linda to help test too

**Comment by lindalumitchell** [comment]
@jason @joram a little way into testing this PR, I noticed that even if the user is actively typing at the time, they get logged out:

1. Set idle time to 2 min
2. Log in user
3. Post a message every few seconds, change a channel, create a new channel
4. At 2 minutes, the user is logged out, even if actively posting a message at that moment

I also noticed that logging in and just letting the browser sit there without even moving the mouse logs the user out at timeout limit, whereas the ticket says it should check for idle timeout time based on the user making a request of some kind.

But either way, it definitely seems like the above test steps should not result in the user being logged out (while they're active)?

**Comment by jwilander** [comment]
Any request to the server will trigger the check and logout, it doesn't require any direct user action on the app, just that they have it open and it made some sort of request. Making it request specific is harder and less secure.

Also setting the timeout to under 5 minutes is going to be unreliable and log users out more aggressively since we only update the last activity at a maximum of once every 5 minutes (I chatted earlier with JB about this). This is probably why you're seeing it happen even though you've made actions in the last 2 minutes

**Comment by jwilander** [comment]
Also it's @jasonblais :P

**Comment by lindalumitchell** [comment]
Ah okay, thanks Joram. I wondered about unreliable tests at lower numbers, which is why I changed from 1min to 2min, but obviously needed to up it even more. Makes sense, and I'll keep on testing with that in mind. Thanks!

**Comment by jasonblais** [comment]
@jwilander Wasn't the minimum supposed to be 5 minutes?

**Comment by jwilander** [comment]
I didn't add the UI minimum in because we didn't already have support for that in the settings and with this coming in so hot I didn't have time to add support for it. Sorry, had it on my list of things to talk to you about but seems like I missed it

I can add change the behaviour so if it's less than 5 (and non-zero) it changes to 5 but adding an error message and the other standard error behaviour is a lot more work. Other option is we just update the help text to mention it

**Comment by jasonblais** [comment]
@jwilander That's okay. If we change it so that 
 - an integer >0 but <5 changes to 5
 - first sentence of help text reads `The number of minutes from the last time a user was active on the system to the expiry of the user's session. Once expired, the user will need to log in to continue. Minimum is 5 minutes, and 0 is unlimited.`

it should be okay. As discussed, <5 minutes is a rare case anyways.

**Comment by jwilander** [comment]
Sounds good, I'll make that update

**Comment by lindalumitchell** [comment]
@jwilander @jasonblais I did a bunch of testing on this today, but only once (after increasing the time from 2 min) saw a logout happen as expected (I understand the expected might be somewhat of a moving target, as far as exact timing goes, but tried to take that into account). Maybe I'm mis-testing somehow?

Just now, I checked on the spinmint, which I had set to timeout after 30 minutes, almost 2 hours ago. Neither test nor test2 were logged out when I came back just now to the browsers and switched channels, posted messages, and refreshed. 

The one logout I did see earlier was when it was set to time out after 7 minutes, and the test user (the system admin) was logged out after 20 minutes of no activity, when I clicked a desktop notification from test2. Test2 hasn't been logged out either in the 7-minute test or the 30-minute test. (I have since tested other desktop notifications, but they haven't logged out the user.)

My messy testing notes, just in case: https://docs.google.com/document/d/1V23lNtv401sTqwQ7KL4qqEt2ceAbjLhwhV2_5fm8pjY/edit#bookmark=id.ijgf5m20t14x

**Comment by jwilander** [comment]
Alright, not sure why it's not working but it's definitely a server-side issue and not related to this PR (which is just the client-side config setting).

I think we should move this PR to dev review after I make the minor UI changes and then I'll try to investigate what you're seeing @lindalumitchell and I will make a server PR for any fixes

**Comment by jasonblais** [comment]
@jwilander Looks like the PR needs to be rebased,

I'll just briefly test the UI and then queue for dev review. It seemed to be working fine for me when I tested it,

**Comment by jwilander** [comment]
Rebased. I also submitted some changes that should fix the issues @lindalumitchell was seeing mattermost/mattermost-server#7549

**Pull request merged**
