### PR TITLE
Use ActionResult error field for CallResponse errors

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR makes it so errors returned from `doAppCall` are returned use the `ActionResult`'s `error` field instead of the `data` field.

#### Related Pull Requests

- https://github.com/mattermost/mattermost-webapp/pull/7773

This addresses the PR comment https://github.com/mattermost/mattermost-webapp/pull/7773#discussion_r607565718

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann testing this involves testing happy/error cases of bindings and apps modals.

**Comment by DHaussermann** [comment]
@mickmister I was about to begin testing the webapp soon with the teat-app https://github.com/larkox/mattermost-app-test 
Will this expose the new functionality? It includes many test commands for Valid, Invalid and Error cases.

**Comment by mickmister** [comment]
> Will this expose the new functionality? It includes many test commands for Valid, Invalid and Error cases.

@DHaussermann No this is purely a refactor of how the errors are structured after receiving a call response. The refactor makes it so the error-handling is more similar to how the rest of redux actions are handled throughout the webapp. This has already been applied to the mobile app.

**Review by DHaussermann — APPROVED** [review]
Re-tested again after last commit and rebase.
- Tested using the test app
- All valid, invalid and error commands seem to eork as expected
- Confirmed that error response are show in web UI as expected
- Tested on Browser and desktop

LGTM!

**Review by larkox — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested again with latest commit. 
No change in behavior found when running through commands of the test app. 

LGTM!

**Comment by DHaussermann** [comment]
Rather than target the next cloud release, this PR will be changed to deliver a more complete solution in a future release. 
I have removed the milestone and added the `Do Not Merge` label for clarity as this is not to be cherry picked.

**Comment by DHaussermann** [comment]
Tested and passed
- Ran through all Valid, Invalid and Error cases using the test app
- Tested these cases from command parser, channel header and post menu bindings
- No issues found

LGTM!

**Review by DHaussermann — APPROVED** [review]

**Comment by DHaussermann** [comment]
@mickmister This has passed testing. Can we ping someone for a fresh dev review?

**Comment by mickmister** [comment]
@DHaussermann Can't merge due to cla check failing

**Comment by amyblais** [comment]
This has v5.35 milestone, is this meant to be cherry-picked? @DHaussermann @hanzei

**Comment by amyblais** [comment]
@mickmister Needs a manual cherry-pick to 5.35.

**Pull request merged**
