### PR TITLE
Daily Merge release-4.6 into master

### PR DESCRIPTION
**Pull request by AndersonWebStudio**
Daily merge

### CODE REVIEW

**Comment by AndersonWebStudio** [comment]
not a bad idea @ccbrown , i can at least put the commit authors as reviewers manually until then

**Comment by enahum** [comment]
I’m not following, if this was on the release branch you should have no problem to merge it back to master ;)

**Comment by jwilander** [comment]
There's a bunch of conflicts with `master` that need to be resolved, I can help with that in a little bit

**Comment by AndersonWebStudio** [comment]
@stephenkiers , @hmhealey - are you able to assist with the merge conflicts here?

**Comment by jwilander** [comment]
Closing in favor of #589

**Pull request closed without merging**
