### PR TITLE
[MM-37838]: global header clean up

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
cleaning up intermittent code after global header reached GA.

#### Ticket Link
[MM-37838](https://mattermost.atlassian.net/browse/MM-37838)

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/19763

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]
LGTM!

**Comment by michelengelen** [comment]
@jgilliam17 gentle ping on this so it can make the next release.

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified global header - no change, working as before.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/169548-d9ecd65-onprem-ent-webapp-pr-9993-mattermost/mm-ee-testd9ecd65/mochawesome.html) looks good, no PR related failures when compared to [master run ](https://mattermost-cypress-report.s3.amazonaws.com/169344-onprem-ent-master-mm-ee-test:test/mochawesome.html)
4 failed tests from the report are passing when tested on the test server.
Feature flag is still present on this test server, assume that will be removed in the related server PR, correct?

**Pull request merged**
