### PR TITLE
[MM-47362] Remove redux from stores/browser_store

### PR DESCRIPTION
**Pull request by batebobo**
#### Summary
Removed redux from browser_store.ts. There were two (IMO) conflicting parts of this class
* Redux convenience functions (action creators + selectors)
* Class properties + functions that deal with the underlying browser storage.

I think that these should be placed in separate places as this violates the single responsibility principle and makes the class harder to comprehend & extend.

The redux convenience funcitons in this class weren't used in many places, so I removed them entirely.

#### Release Note
```
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @batebobo!

I always forget the BrowserStore still exists since it's a relic of before we even used Redux. I imagine we'll remove the rest of it some day, but your changes will ensure people always use the storage actions instead, so that'll stop it from being used anywhere new at least.

**Review by Afsoon — APPROVED** [review]
LGTM @batebobo, thank you for the PR!

**Comment by nevyangelova** [comment]
test report: https://mattermost-cypress-report.s3.amazonaws.com/257573-fdd9995-onprem-ent-webapp-pr-11470-mm-ee-test:fdd9995/mochawesome.html

**Comment by nevyangelova** [comment]
@batebobo could you verify that the failing tests are not related to this change?

You can run them locally by navigating to `/e2e/cypress` then install packages and run `npm run cypress:open`

**Comment by batebobo** [comment]
Sure, @nevyangelova! Is a local pass sufficient to verify this?

**Comment by nevyangelova** [comment]
@batebobo should be visible on the screenshots yes :)

**Comment by batebobo** [comment]
Hi! After running the tests locally, some of them seem to be failing. Here's a list:
```
new_channel_with_board_spec - timeout
with_email_login_spec - 403
with_ldap_login_spec - 403
member_invitation_ui_spec - 403
starter_edition_spec - timeout
poll_spec - timeout
forward_message_from_public_channel_spec - 403
plugin_install_spec - don’t have the demo plugin 
edit_spec - timeout
```

The `403` errors should be due to configuration and I will install the demo plugin for the `plugin_install_spec`, but for all other tests the error is the same as in the report @nevyangelova. 
I'll also run these specs from master just to make sure :)

**Pull request merged**
