### PR TITLE
[PLT-4340] Channel Mute and "/mute" command #7617 #7713

### PR DESCRIPTION
**Pull request by chclaus**
#### Summary
 - Modify channel notification dialog and add mute section
 - Add unmute button to channel header
 - Make muted channel transparent in sidebar

#### Ticket Link
[Github](https://github.com/mattermost/mattermost-server/issues/7617)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [x] [Has server changes](https://github.com/mattermost/mattermost-server/pull/7713)
- [x] [Has redux changes](https://github.com/mattermost/mattermost-redux/pull/434)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

#### Further notes
The server implementation is feature complete, but the webapp-implementation isn't. Two requirements are still missing:

> The channel is sorted to the bottom of the sidebar section (secondary sorting of muted channels is based on standard channel sorting)

As I have no Idea how to access the channelMember model inside the channel sorting it would be nice if another person could challenge this.

> Remove the setting Channel Notification Preferences > Mark Channel Unread. Turn on Mute Channel for any channel which had been set to "Only for mentions".

I have no idea how to handle this and doesn't have a good feeling to implement this migration step as a complete newbie at this project. Could another one keep care of it?

### CODE REVIEW

**Comment by esethna** [comment]
Awesome, thanks @chclaus! I'm adding @hmhealey to help provide some guidance on the items you've mentioned.

**Comment by chclaus** [comment]
Cool thanks @esethna!

**Comment by hmhealey** [comment]
Hey @chclaus,

To answer your questions:
1. Do you know where the sorting for that list is done? It might need to be in the https://github.com/mattermost/mattermost-redux repository, in which case it'll affect the mobile app as well. Depending on how/where its done, if you can get a map of channel IDs to channel member objects, you could have something like
```
channels.sort((a, b) => {
    const aMuted = channelMembers[a.id].muted;
    const bMuted = channelMembers[b.id].muted;

    if (aMuted !== bMuted) {
        if (aMuted) { // a is muted, and b is not
            return 1;
        } else { // b is muted, and a is not
            return -1;
        }
    }

    // sort as usual
}
```
2. Instead of doing an actual migration from the old value to the new one, you could either
    1. Just use the old setting internally. For example, instead of setting `member.notify_props.mut = true` when a channel is muted, instead set `member.notify_props.mark_channel_as_unread = 'mentions'` like it does currently. It might be good to make a helper function like `isChannelMemberMuted` instead of checking the setting everywhere to make the code more readable, but it could function as you want it to now
    2. You could add the new setting, but leave in code to look at the old setting if the new one is unset. Again, a helper function would be good here. So instead of
```
function isChannelMemberMuted(member) {
    return member.notify_props.mute;
}
```
you'd have
```
function isChannelMemberMuted(member) {
    return member.notify_props.mute || (member.notify_props.mute == null && member.notify_props.mark_channel_as_unread == 'mention');
}
```

Personally, I think I'd go with the first one if possible. It would make the code a bit trickier to follow (since the field name isn't obvious), but it would avoid having to have two separate code paths for whether the setting is set or not.

**Comment by esethna** [comment]
Awesome, thanks @chclaus! Just so you're aware, if you'd like to get this in for v4.4, shipping in November, this PR and the webapp PR should be reviewed and merged by October 31. If not we can definitely take it in v4.5. Super excited to get this in!

**Comment by chclaus** [comment]
Hej @esethna,

as mentioned on the server PR, I think this will unfortunately take in to v4.5. I'm pessimistic that I can find enough time this month to dive into redux etc. :-/

**Comment by jasonblais** [comment]
@chclaus That's perfectly fine, really appreciate your help on this feature!

**Comment by esethna** [comment]
@chclaus just checking in, please let us know if there's anything we can help with :)

**Comment by chclaus** [comment]
Hej @esethna , I had some very intensive working days... Hope that I find time within the next days

**Comment by esethna** [comment]
No problem @chclaus, let us know if you need any help :)

**Comment by chclaus** [comment]
Hej @esethna, hej @hmhealey, 

I've got a problem that I can't solve... I've produced a state that I can't change any notification setting inside the channel notification dialog. Even if I try to start with a complete clean clone of this repo in master version I can't make any change...

I've stucked there for a few days now and can't find any reason. Also I've asked colleges of myself and in the mattermost dev-channel but it seems that I'm the only person who got this problem. :(

Can you please give some advice?

**Comment by hmhealey** [comment]
Hey @chclaus,

Sorry, I totally missed your message. What exactly are you seeing? Is it just not saving any changes, or are you seeing errors?

**Comment by chclaus** [comment]
Hej @hmhealey,

no problem. I‘ll give it a try to explain the problem more in detail. 

the core problem is the following: The channel notification dialog offers some sections and each section offers radio buttons. When I try to change any value of an arbitrary radio button, the component does a rerendering but leave the state untouched. 🤔

The result is, that the radios are flickering for a short time but doesn‘t change their values. 

Can you follow? 😕

Greetings,
Christian

**Comment by hmhealey** [comment]
Hi,

It sounds like either the state isn't being changed or something is changing it back. Maybe add some console.log statements to `handleUpdateMuteNotificationLevel` to see if it's being called at the correct time or add them to `componentDidUpdate` to see if something else is changing the state back?

**Comment by chclaus** [comment]
Hej @hmhealey,

dunno what so say... The problem vanished after so many days. But thanks a lot for your advices. All features but the re-sorting of muted channels are done. I would be pleased if the changes could find a way into a release without the the resorting feature. I've got some time deficits atm :(

Could it be possible to create a another task for this left functionality?

Greetings,
Christian

**Comment by esethna** [comment]
Thanks @chclaus! Can you please help resolve conflicts so we can get a test server running? 

As for the sorting, if you are okay with it, we may just get one of our core devs to take a look and finish it off so we can push it into an upcoming release?

**Comment by chclaus** [comment]
Hej @esethna,

thanks a lot. Both repos (server and webapp) are completely merged. Hope everything looks good enough :)

**Comment by chclaus** [comment]
Hej @esethna,

at first thanks for the detailed feedback. A really great job that makes me feel well 😄 

And now a few words to your findings:

> 1. Can we move the bell icon to the right of the channel name?
In my first version the bell icon was exactly at the right side of the channel name. But in the meantime there was a commit (`89a70f1e`) that makes a lot of bugfixes and also prevents the positioning of further icons at the right side of the channel name. The channel name now has a width of 100%. So I decided to place the icon at the left side.

> 2. Can we please style the bell icon the same as the favorites icon? ie grey until hovered over
:white_check_mark:

> 3. The cancel button doesn't work on the "Mute channel" setting in channel notification preferences:
:white_check_mark:

> 4. The collapsed text for the setting should just be "On" or "Off"
:white_check_mark:

> 5. If a channel is muted and in the favorites section, triggering a mention in that channel causes it to appear in the public channels list as well as the favorites channel list
In my opinion, there is no correlation to my changes. I've also found this problem in the current master. When you're mentioned on a favorite channel, the channel also appears under the favorite section as under the public section.

> 6. A mention in a muted channel should bold the channel name in the left hand side (but should still remain at reduced opacity)
:white_check_mark:

And again: Thanks a lot for your support and your patience. 😄

**Comment by esethna** [comment]
Thanks @chclaus, regarding (1), I'm adding @asaadmahmood to comment. 

It feels strange for the channel name to pop left and right when the channel is muted and unmuted, I think the right side would make more sense, @asaadmahmood thoughts?

image

-------

(5) has been fixed on master I believe, thanks!

**Comment by asaadmahmood** [comment]
I agree with having the bell icon on the right, also the bell icon seems to be a bit larger and darken than the favourites icon. Would prefer if it's a bit smaller, and has slightly reduced opacity.

**Comment by esethna** [comment]
Cool, @chclaus can we please make that change to move the bell to the right and decrease in size slightly as per AM comments?

**Comment by chclaus** [comment]
Hej @esethna, hej @asaadmahmood,

you're right, putting the bell on the right side looks cleaner. I've changed it and merged the current master. 

notify

Best, Christian

**Comment by esethna** [comment]
Thanks @chclaus, awesome work here, super appreciated! We are going to queue this internally to finish off the sorting functionality when channels get muted. Feel free to work on it yourself if you have a chance.

https://mattermost.atlassian.net/browse/ICU-666

**Comment by asaadmahmood** [comment]
Wow @chclaus Looks awesome, you also managed to make the icon quite similar in size and contrast. Great work!

**Comment by chclaus** [comment]
Thanks guys 😄

**Comment by esethna** [comment]
Hi @chclaus, hope you're doing well! Our team is ready to finish off this PR so we can get it into v4.9, can I ask your help to please [allow changes from the repo maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so we can commit to this PR's branch? Both here and on the [server PR](https://github.com/mattermost/mattermost-server/pull/7713)

**Comment by chclaus** [comment]
Hej @esethna,

I'm fine thanks. Hope you're doing well too. 

I'm very thankful that your team is ready to handle the changes. This PR and the corresponding server PR are both already configured with grants to allow changes by the maintainers. If you need more Informations or support, feel free to ask.

Best,
Christian

**Comment by esethna** [comment]
@enahum @chclaus really great work on this. So happy to be getting this in! Moving to dev review.

**Comment by jwilander** [comment]
Whoever resolves the conflicts please make sure to update mattermost-redux to latest

**Comment by enahum** [comment]
@jwilander done

**Pull request merged**
