### PR TITLE
[MM-43986] Fix plugin enable status toggle reverting to true on plugin disable

### PR DESCRIPTION
**Pull request by thinkGeist**
#### Summary

This pull request aims to solve a problem that occurs in the web application when disabling a plugin from within the plugins configuration page. 

#### Background 
This issue only occurs on when removing WebApp plugins as they trigger the `plugin_disabled` websocket action, which in turn calls `removePlugin` in `plugins/index.js`. This issue seems to occur because of the `removeWebappPlugin` and `unregisterAdminConsolePlugin` actions due to how the reducer always returns a new state even if no alteration will be made to the state.

This change follows the theme of some other reducers within the same file and only returns a new state object if the data we intend to remove from the state actually exists in the state, if it does not then we return the old state object. By doing so it prevents the DOM refresh and allows the `doSubmit` of `components/admin_console/schema_admin_settings.jsx` to continue after calling 
`await this.props.updateConfig(config)` where it would previously fail to call `this.setState(getStateFromConfig(config))` because `this` was unmounted. 

Relevant chunk of code:

https://github.com/mattermost/mattermost-webapp/blob/54542da9a3ce53fa6ca92974992acb4c292f9b20/components/admin_console/schema_admin_settings.jsx#L993-L1027

#### Ticket Link
[Jira](https://mattermost.atlassian.net/browse/MM-43986)
[GH Issue](https://github.com/mattermost/mattermost-server/issues/20190)

```release-note
Corrects an issue where disabling a WebApp plugin from its configuration page would result in the radio button reverting to true.
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @thinkGeist! I'm not 100% on the context for fixing the bug, but I'll defer that part to @mickmister. The code change looks good though since we've definitely followed that pattern in many places

**Comment by hmhealey** [comment]
Sorry for the delay in reviews. I didn't realize that @mickmister has been out on vacation, so I reassigned this

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann I've verified the PR works as intended (resolves https://mattermost.atlassian.net/browse/MM-43986). I would do some regression testing on installing, enabling/disabling, and removing plugins to see if the data is accurate in both the plugin management page and the individual plugin's settings page

**Comment by hmhealey** [comment]
@DHaussermann Do you have a chance to review this in the next few days, or is there someone else we could re-assign it to?

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Toggle now always shows in correct state without refresh
- Tested with various plugins include with and without webapp
- Tested on HA server as well
- Ensured the state showing on plugin management stays accurate in other browser tab when saving the radio (though this may not be directly affected by this PR)
No issues found.
LGTM!

**Comment by DHaussermann** [comment]
This is good to merge. Huge thanks @thinkGeist for this PR 🎉  This issue has been a real nuisance :)

**Pull request merged**
