### PR TITLE
[MM-40407] - Do not show the Renew Now if the license id does not exist in the portal

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR adds checks to the renewal link component in order to make sure that users are able to renew their license from portal. Otherwise, they're redirect to contact sales

#### Ticket Link
[MM-40407](https://mattermost.atlassian.net/browse/MM-40407)

#### Related PRs
https://github.com/mattermost/enterprise/pull/1116
https://github.com/mattermost/customer-web-server/pull/632
https://github.com/mattermost/mattermost-server/pull/19188

#### Release Note
```release-note
NONE

```

### CODE REVIEW

**Comment by marianunez** [comment]
@AGMETEOR can you provide a screenshot of how it will look if they cannot renew on the portal?

**Review by marianunez — CHANGES_REQUESTED** [review]
Code looks good, can we add some tests to cover this case?

**Comment by AGMETEOR** [comment]
> @AGMETEOR can you provide a screenshot of how it will look if they cannot renew on the portal?

Screenshot 2021-12-17 at 14 00 24

**Comment by AGMETEOR** [comment]
> > @AGMETEOR can you provide a screenshot of how it will look if they cannot renew on the portal?
> 
> Screenshot 2021-12-17 at 14 00 24

@marianunez notice how the banner now has 2 "Contact sales" buttons. Maybe we should get rid of the second one since RenewalLink component now handles that?

**Comment by marianunez** [comment]
> @marianunez notice how the banner now has 2 "Contact sales" buttons. Maybe we should get rid of the second one since RenewalLink component now handles that?

Agreed, it should not be shown if the `Renew Now` was transformed to `Contact Sales` but we still want it otherwise. 

@jasonblais what is the correct link that the admin should be redirected to Contact Sales for sales-serve renewals? 

I see we are currently have two in the code: https://mattermost.com/contact-sales/ and https://mattermost.com/contact-us/ from [here](https://github.com/mattermost/mattermost-webapp/blob/cf3e14185814259624b9f516f3b15c48dba4173f/components/announcement_bar/contact_sales/contact_us.tsx#L21)

**Comment by jasonblais** [comment]
@marianunez I would use what we have today as both redirect to https://mattermost.com/contact-sales/ at the moment, and I'm not sure what the long-term change is.

**Review by nickmisasi — APPROVED** [review]
Code LGTM - approving since I'll be out next week

**Review by marianunez — APPROVED** [review]
Thanks @AGMETEOR, great tests 🎉

**Comment by AGMETEOR** [comment]
@stevemudie related PRs have been merged. However, I think this should be a post merge QA test

**Comment by stevemudie** [comment]
Will test post merge.

**Review by stevemudie — APPROVED** [review]

**Comment by jasonblais** [comment]
This will be a great improvement, thanks everyone! 🚀

**Pull request merged**
