### PR TITLE
Spinwick PR Mm 22845 permalink preview

### PR DESCRIPTION
**Pull request by mkraft**
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @BenCookie95 @mkraft! Few things:

1. The system console has two settings with the same name, Propose changing the original link preview setting name to "Enable website link previews"

image

2. Similarly, can we change the name of the Disable link previews from these domains > "Disable website link previews from these domains" and move the position after the setting for "Enable website link previews"

image

3. Default for the new system console setting should be "true", but I think it might be currently "false" as it was set this way before I changed it and I can't seem to enable it by saving the config
image

**Comment by esethna** [comment]
@BenCookie95 or @mkraft can you guys help look into why the config can't be saved to enable the feature? ^

**Comment by BenCookie95** [comment]
> @BenCookie95 or @mkraft can you guys help look into why the config can't be saved to enable the feature? ^

I don't think this is picking up the server changes maybe? I'll check it out

**Comment by esethna** [comment]
@BenCookie95 looking awesome! Found one UI issue:

https://mattermost-server-pr-17796.test.mattermost.cloud/asgdg-ds/pl/xg1kgt7c1pbofks51i9mamcgja

**Comment by esethna** [comment]
@michaelgamble can you please give this a priority UX review?

**Comment by esethna** [comment]
@BenCookie95 UX review here: https://github.com/mattermost/mattermost-server/pull/17796#pullrequestreview-708612315

**Comment by esethna** [comment]
@BenCookie95 were these changes made? https://github.com/mattermost/mattermost-webapp/pull/8403#issuecomment-880873931

I didn't see them on the latest spinwick on the server PR but maybe it isn't pulling the latest webapp changes? https://github.com/mattermost/mattermost-server/pull/17796#issuecomment-887898631

cc// @mkraft

**Comment by BenCookie95** [comment]
> @BenCookie95 were these changes made? [#8403 (comment)](https://github.com/mattermost/mattermost-webapp/pull/8403#issuecomment-880873931)
> 
> I didn't see them on the latest spinwick on the server PR but maybe it isn't pulling the latest webapp changes? [mattermost/mattermost-server#17796 (comment)](https://github.com/mattermost/mattermost-server/pull/17796#issuecomment-887898631)
> 
> cc// @mkraft

I might not have pushed to the spinwick branch, I'll check it out

**Comment by BenCookie95** [comment]
> @BenCookie95 were these changes made? [#8403 (comment)](https://github.com/mattermost/mattermost-webapp/pull/8403#issuecomment-880873931)
> 
> I didn't see them on the latest spinwick on the server PR but maybe it isn't pulling the latest webapp changes? [mattermost/mattermost-server#17796 (comment)](https://github.com/mattermost/mattermost-server/pull/17796#issuecomment-887898631)
> 
> cc// @mkraft

@esethna This is fixed now. You can see it here https://mattermost-server-pr-17796.test.mattermost.cloud/

**Comment by cwarnermm** [comment]
@esethna - We do have a process for this use case. Any team needing an in-product docs link can request one of the Writing team via a JIRA ticket. In-product docs links can be initially set up ahead of a given feature release.

The Writing team then either:
- identifies where the new feature details will live in the doc set, or
- creates a source file for the new feature docs

The Writing team provides that link to the R&D team implementing the feature, and then the Writing ensures that the feature documentation is available in time for the product release.

If redirects are needed in the future, the process of setting up in-product redirects is [documented in the Handbook](https://handbook.mattermost.com/operations/research-and-development/product/product-management-team-handbook#how-do-i-create-redirects-for-in-product-documentation).

**Comment by cwarnermm** [comment]
@esethna - Would you be open to creating a docs PR requesting the in-product docs link? In this docs ticket, can you also include details around the additional in-product text changes coming as part of this feature update? It would be ideal to track all necessary changes for this feature together, and the config setting changes will impact both docs and 301 redirects already in place.

**Comment by esethna** [comment]
Sure @cwarnermm PR here: https://github.com/mattermost/docs/pull/4921

**Pull request closed without merging**
