### PR TITLE
[GH-19858]Channel header icons impacted by long channel name in mobile view

### PR DESCRIPTION
**Pull request by TylerStilson**
#### Summary

I changed the space that the truncated header could take in different mobile views to keep it from affecting the icons.

#### Ticket Link

fixes https://github.com/mattermost/mattermost-server/issues/19858
Jira ticket: https://mattermost.atlassian.net/browse/MM-42752
#

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Comment by koox00** [comment]
@M-ZubairAhmed, can you add some screenshots as well?

**Comment by M-ZubairAhmed** [comment]
cc @TylerStilson

**Comment by michelengelen** [comment]
I am sorry, but this fix is way too complicated and uses a lot of fixed widths as well.
IMO it is easier and more future-proof to leverage the capabilities of the `flex` or `grid` system here.

if you add this to the class `.navbar-toggle.navbar-right__icon` everything works just fine:

```
flex: 0 0 32px;
```

With this we can even remove the `width: 32px;` from the same class definition.

There is an edge-case though where the plugged button is a dropdown, but I cannot find a way to show it in my local instance (and the MM community server has no plugins installed that uses that as well). @M-ZubairAhmed or @koox00 would you know of a plugin that uses that?

**Comment by michelengelen** [comment]
While testing this I discovered that we can also remove the wrapping `li` element that surround the plugged in `buttons` (not the dropdown ones atm, since I didn't have a chance to test that yet) [here](https://github.com/mattermost/mattermost-webapp/blob/ae69876e2c30c46a932807e0fb44b6d98ef6250a/plugins/mobile_channel_header_plug/mobile_channel_header_plug.tsx#L68-L82) and [here](https://github.com/mattermost/mattermost-webapp/blob/ae69876e2c30c46a932807e0fb44b6d98ef6250a/plugins/mobile_channel_header_plug/mobile_channel_header_plug.tsx#L107-L116).

Screenshots for reference:

#### Very small view:
Screenshot 2022-04-14 at 13 19 32

#### Medium mobile view
Screenshot 2022-04-14 at 13 21 00

#### inspector and class definition
Screenshot 2022-04-14 at 13 21 29

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
1. It appears that the icon shapes are still getting impacted. This appears to be happening between 450-768 browser widths. This was noted in the [original jira ticket](https://mattermost.atlassian.net/browse/MM-42752), but doesn't appear to be fixed in this PR.

image

2. I'm also noticing that the menu button and channel name shift horizontally a bit when going from <450px to >450px.

**Comment by michelengelen** [comment]
> 1. It appears that the icon shapes are still getting impacted. This appears to be happening between 450-768 browser widths. This was noted in the [original jira ticket](https://mattermost.atlassian.net/browse/MM-42752), but doesn't appear to be fixed in this PR.
> 
> 
> image
> 
>     2. I'm also noticing that the menu button and channel name shift horizontally a bit when going from <450px to >450px.

@matthewbirtch this should all be fixed when using `flex` properly :D

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
The shape of the buttons are now fixed, but I still seeing the menu button and channel name shift a bit when resizing the window below 500px

**Comment by TylerStilson** [comment]
@matthewbirtch Thanks, I'll look into that!

**Comment by michelengelen** [comment]
> The shape of the buttons are now fixed, but I still seeing the menu button and channel name shift a bit when resizing the window below 500px
> 
> 

@TylerStilson to fix that you could apply the same change for the left icon as well ... just use the shorthand `flex` property 

```
flex: 0 0 <x>px;
```

where `x` is your desired width for the element.

**Comment by michelengelen** [comment]
@TylerStilson we should definitely remove the surrounding `li` on the plugged in buttons as mentioned here: https://github.com/mattermost/mattermost-webapp/pull/10166#issuecomment-1099087740

**Comment by TylerStilson** [comment]
https://user-images.githubusercontent.com/78005462/165625193-45aa2b4e-3b4f-4458-a696-96fd1ffd801e.mov

**Comment by TylerStilson** [comment]
Here is a recording of the new changes:

https://user-images.githubusercontent.com/78005462/165625645-b3577fc4-546d-47a7-b168-8934e0be27a6.mov

**Review by matthewbirtch — APPROVED** [review]
Looks good now @TylerStilson!

**Review by michelengelen — APPROVED** [review]
LGTM

**Review by koox00 — COMMENTED** [review]
Thank you for your work @TylerStilson 💯 
Can you fix the failing tests as well?

**Comment by jgilliam17** [comment]
Thanks @TylerStilson 
Manually tested, looks good to merge - pending E2E report - please fix the failed checks so E2Es can be triggered. 
- Verified channel header icons in mobile webview are not affected by long channel names.

**Comment by michelengelen** [comment]
@TylerStilson anything we can help you with on this?

**Comment by michelengelen** [comment]
Hi @TylerStilson could you update the snapshots please? just run `npm run updatesnapshot plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.tsx` and push the changes to the PR. Thanks 🙇🏼

**Comment by TylerStilson** [comment]
Sorry I was gone for awhile! @michelengelen I just tried to run that command in the webapp folder but I am coming up with this error. I've tried a few things but I don't know why it's not working.

Screen Shot 2022-07-07 at 11 59 51 AM

**Comment by jgilliam17** [comment]
Hello @TylerStilson - Let us know if you need help fixing the failing tests 🙂

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
