### PR TITLE
[GH-15775] Replaced button-bg-## to use button-bg-rgb variables

### PR DESCRIPTION
**Pull request by arc9693**
#### Summary
Replaced button-bg-## to use button-bg-rgb variables

#### Ticket Link
Closes [Remove usage of button-bg-## CSS variables #15775](https://github.com/mattermost/mattermost-server/issues/15775)

### CODE REVIEW

**Comment by arc9693** [comment]
```/check-cla```

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Review by nevyangelova — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks for the contribution @arc9693 - looks good to me 👍

**Comment by arc9693** [comment]
@mattermod can this be merged?

**Comment by nevyangelova** [comment]
Hey @arc9693 yes indeed when you get three approvals you can merge :) You just have a conflict with master, commit the fix and feel free to merge after 🎉

**Comment by arc9693** [comment]
@mattermod Hey, could you please merge? I don't have the authority to merge.

**Pull request merged**
