### PR TITLE
MM-46003 Update webpack-cli to 4.10.0

### PR DESCRIPTION
**Pull request by hmhealey**
This fixes an issue where webpack-dev-server suddenly decided to stop working

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46003

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by pvev** [comment]
webpack is running, however with the code on this branch, it fails with something related with the generic_modal components migration (even when running with make run).

`ERROR in ./components/generic_modal.tsx 12:0-54
Module not found: Error: Can't resolve '@mattermost/components' in '/Users/pvelez/Documents/projects/mattermost/mattermost-webapp/components'`

**Review by AshishDhama — APPROVED** [review]

**Comment by hmhealey** [comment]
@pvev Did you try running a clean as well? That PR moved some stuff and started using a new workspace, so it’s possible that it wouldn’t work without a clean. The test server works, and this shouldn’t make anything *worse* for you, so I’m going to merge it now.

Also, I did see an issue where editors will fail to find the components package, but I’ll fix that separately. The build tools should still be able to find it regardless of that

**Comment by pvev** [comment]
> @pvev Did you try running a clean as well? That PR moved some stuff and started using a new workspace, so it’s possible that it wouldn’t work without a clean. The test server works, and this shouldn’t make anything _worse_ for you at least.
> 
> Also, I did see an issue where editors will fail to find the components package, but I’ll fix that separately. The build tools should still be able to find it regardless of that

awesome!, let me clean everything and try again. Thanks @hmhealey

**Comment by pvev** [comment]
the make nuke just did the trick, thanks @hmhealey!

**Review by pvev — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
