### PR TITLE
Fix french conjugation: vous a --> vous avez

### PR DESCRIPTION
**Pull request by dllu**
#### Summary

Previously the conjugation is incorrect:

image

image

image

It should be as follows:

* Others reacted: {other people} ont réagi
* You + others reacted: vous et {other people} avez réagi
* You reacted: vous avez réagi
* Other single person reacted: {other user} a réagi

image

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
Fixed grammar in French localization.
```

### CODE REVIEW

**Comment by dllu** [comment]
OK, I've made the relevant suggestions here:

* https://translate.mattermost.com/translate/mattermost/mattermost-webapp_master/fr/?checksum=4b6b05080a041f7c&q=reacted&sort_by=-priority%2Cposition
*https://translate.mattermost.com/translate/mattermost/mattermost-webapp_master/fr/?checksum=2f5a4fd6b3e78b67&q=reacted&sort_by=-priority%2Cposition#suggestions
* https://translate.mattermost.com/translate/mattermost/mattermost-webapp_master/fr/?checksum=a7c14cbbd2f6babe&q=reacted&sort_by=-priority%2Cposition

**Comment by m1lt0n** [comment]
Thankyou @dllu . I will then close this PR. Thanks for your contribution!

**Pull request closed without merging**
