### PR TITLE
[MM-45239] Fixing font size of markdown headings

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
The heading will no longer get cut off for insights

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45261

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@furqanmlk could you enable the feature flag on this server?

**Review by plant99 — APPROVED** [review]

**Review by furqanmlk — COMMENTED** [review]
Hi @BenCookie95, One question,

Should text formate be applied on ellipsis? 
image


image
image

**Comment by BenCookie95** [comment]
> Hi @BenCookie95, One question,
> 
> Should text formate be applied on ellipsis? image
> 
> image

I'm not 100% sure what you're asking but do you mean should the message body be truncated with ellipsis? If so, yes it should

**Comment by BenCookie95** [comment]
> > > Hi @BenCookie95, One question,
> > > Should text formate be applied on ellipsis? image
> > > image
> > 
> > 
> > I'm not 100% sure what you're asking but do you mean should the message body be truncated with ellipsis? If so, yes it should
> 
> @BenCookie95 Sorry I meant, Should body text formate be applied on ellipsis ? In Top Thread Ellipsis is not highlighted
> 
> image
> 
> But on Model Ellipsis is highlighted
> 
> image

Hey, I don't think this is an issue for now. I'm only dealing with the headings

**Pull request merged**
