### PR TITLE
Show desktop app download prompt on first visit to a new server #10573

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR https://github.com/mattermost/mattermost-webapp/pull/10573 had to be reverted due to most e2e test failing, this submits it with the fix. 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by saturninoabril** [comment]
I realized this will cause Rainforest to fail as well. Unlike Cypress, Rainforest VM/Browser/Desktop App does not have a way to manipulate browser's local storage or a conditional check when running a test. I wonder if such landing page can be hidden via server's config or user setting whenever a server is under test (default), and only enable as required by specific test.

cc @lindy65 @lindalumitchell

**Review by devinbinnie — APPROVED** [review]

**Comment by nevyangelova** [comment]
@saturninoabril i can definitely do that but that would mean that QA won't be able to test this before it goes to master

**Comment by saturninoabril** [comment]
@nevyangelova Thanks for considering! Let us know in QA once available and we'll setup a preview test in Rainforest just to make sure before merging.

**Comment by nevyangelova** [comment]
@saturninoabril @lindalumitchell after discussing with my team how to handle this it seems that excluding the test.mattermost urls is the best option as we won't be able to add this to user settings or config. It should work now!

**Comment by nevyangelova** [comment]
@saturninoabril any updates regarding the rainforest tests?

**Comment by saturninoabril** [comment]
Lindy is currently looking into this. Note that RFQA servers were recently freed up from the on going Cloud July 27th release.

**Comment by saturninoabril** [comment]
Hello Nevy, sorry for last minute request and I totally missed, but could you please add Cypress test? Thanks!

**Comment by saturninoabril** [comment]
Will run test again since the recent run failed in several places - https://automation-dashboard.vercel.app/cycles/0204f0a8-daaa-49e9-879b-cc17a7a9b204. Not sure if related to this PR.

**Comment by nevyangelova** [comment]
Tests are passing locally for me. I didn't merge with master though.

**Comment by lindy65** [comment]
Hi @nevyangelova / @saturninoabril 

Apologies for the delay in testing this in Rainforest while Cloud 27 July release tests were running.

With this PR's build running in Rainforest, I see the following screen _after_ downloading the desktop app in Rainforest then adding a new server:

image

After clicking "View in Desktop App" I see this screen but nothing happens and I'm not directed to the desktop app (which I've already downloaded and connected a server in)

image

I'm a little confused why this screen shows up when adding a server to the already downloaded/installed desktop app though?

**Review by saturninoabril — CHANGES_REQUESTED** [review]
> Tests are passing locally for me. I didn't merge with master though.

Hello Nevy, I can confirm that the failed tests were related to this PR. You'll find the details/screenshots here - https://mattermost-cypress-report.s3.amazonaws.com/222263-8834d94-onprem-ent-webapp-pr-10653-mattermost/mm-ee-test8834d94/mochawesome.html

**Comment by nevyangelova** [comment]
@saturninoabril like mentioned before, these tests are passing for me here is an example of the unread bottom toast spec 
Screenshot 2022-07-26 at 13 23 12

@lindy65 i will push a fix to disable this screen for desktop app. Nice catch!

**Comment by lindy65** [comment]
Thanks @nevyangelova :) Ping me once fixed and I'll retest in Rainforest 👍

**Comment by nevyangelova** [comment]
@saturninoabril actually I did see some tests failing when using the force reload command as this clears the browser cache. Adding the local storage value on 'Reload' as well fixes them. Please check again :)

**Comment by nevyangelova** [comment]
@lindy65 checks passed, should be ready to test :)

**Review by lindy65 — APPROVED** [review]
Thanks @nevyangelova - this looks great!

1. Tested a few Rainforest servers in browser (Win10/Chrome) and I see the expected "Where would you like to view this?" screen.  
     - Following the flow to view in browser, I am taken to the servers login page.  
     - Following the flow to view in the desktop app, which I already have installed locally, I see an "Open Mattermost?" modal and clicking the "Open Mattermost" button gives me a "No matching server" screen - which is expected as I do not have any Rainforest servers set up in my local Desktop App.  My Desktop App opens and I can click on "OK" to remove the error modal.  I also still see in my browser, a link to download the desktop app if I wanted to.
2. Testing from within Rainforest and downloading the desktop app first, I do not see the "Where would you like to view this?" screen;  the desktop app loads correctly and I can add a server without any issues.

**Comment by saturninoabril** [comment]
Thanks for updating @nevyangelova! Looking at the test reports (here, https://community.mattermost.com/core/pl/dq9f5g5njbb1xf65ph8zhk4pbh), couple of last failed tests were found related to this PR such as
- e2e/cypress/tests/integration/integrations/builtin_commands/common_commands_2_spec.js
- e2e/cypress/tests/integration/signin_authentication/login_spec.js

Once PR is updated, you may run Cypress test by commenting with `/e2e-test`. Then you'll find the test running at https://automation-dashboard.vercel.app/cycles eventually. Reports will also be posted at https://community.mattermost.com/core/channels/qa-test-automation-reports where you could check if there's no more related test failures.

**Comment by nevyangelova** [comment]
@saturninoabril i tried running all test as well as those two separately and they are not failing for me locally

**Comment by saturninoabril** [comment]
@nevyangelova For `MM-T686 /logout` at `/integrations/builtin_commands/common_commands_2_spec.js`, I wonder what's the expected behaviour after the user has been logout via `/logout` slash command. Should it redirect to login or landing page?
Screen Shot 2022-08-02 at 3 00 24 PM

**Comment by saturninoabril** [comment]
Similar case to `MM-42489` at `/signin_authentication/login_spec.js`, the user logged out via "Log Out" of user menu. Should it redirect to login or landing page?

**Comment by nevyangelova** [comment]
@saturninoabril i suppose since this is shown to first time users only, it should redirect back to login page. However this test is passing for me. I will try again to see if i can reproduce.

**Comment by saturninoabril** [comment]
Hello Nevy, thanks for updating. As agreed offline, I'll push minor clean up on test, then I'm all good.

**Review by saturninoabril — APPROVED** [review]
Looks good with [E2E results](https://mattermost-cypress-report.s3.amazonaws.com/225612-03fa980-onprem-ent-webapp-pr-10653-mattermost/mm-ee-test03fa980/mochawesome.html). Thanks Nevy!

**Pull request merged**
