### PR TITLE
Mm 36402: Display leave,archive channel action as destructure

### PR DESCRIPTION
**Pull request by Apahadi73**
#### Summary

This PR applies the destructive action color to `Archive Channel` and `Leave Channel` menu actions. 

#### Ticket Link

Issue: [Web app - Leave channel & archive channel actions should display as destructive](https://github.com/mattermost/mattermost-server/issues/19791)

Jira Link: [MM-36402](https://mattermost.atlassian.net/browse/MM-36402)

#### Screenshots

|  before  |  after  |
|----|----|
|168078853-2afdd4d7-c178-421f-95f6-e3495be489eb|Screen Shot 2022-07-12 at 10 11 08 PM

#### Release Note

```release-note
Added the destructive action color to `Archive Channel` and `Leave Channel` menu actions. 
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
Thanks for the PR @Apahadi73! Looks like some of the snapshots are failing.

Can you run `npm run test -- -u` and submit the changes? Thanks!

**Comment by nevyangelova** [comment]
thanks @Apahadi73 just need to update the snapshots as @devinbinnie suggested

**Comment by Apahadi73** [comment]
@nevyangelova @devinbinnie Thank you for the approval and suggestion. I have updated my PR with appropriate changes.

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @Apahadi73!

**Comment by Apahadi73** [comment]
/remove-do-not-merge/release-note-label-needed

**Review by jgilliam17 — APPROVED** [review]
Thanks @Apahadi73 
Tested, looks good to merge.
- Verified leave and archive actions, display as destructive (red bg)
- [E2E report](https://automation-dashboard.vercel.app/cycles/277587a2-5a93-45f8-99ca-b68f300c8bb0) looks good, no PR related failures.

**Pull request merged**
