### PR TITLE
[MM-32581][MM-32582] - Fix popover regressions

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
This PR fixes two regressions related to popovers for Cloud Release - Feb 10th
Note: The parameter 'shouldUpdatePosition' is not defined in the @types for react-bootstrap so I had to extend the @types from @types/react-bootstrap.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32581
https://mattermost.atlassian.net/browse/MM-32582

### CODE REVIEW

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified channel header description popover location with/without banner and reaction popover - as expected. 
Please @ me here if any changes are made and I'll re-test. Thanks 🙂

**Review by michelengelen — APPROVED** [review]
LGTM! ✨

**Review by calebroseland — APPROVED** [review]
LGTM! 

Aside: seems like there's a small 1px shift, but this happens on daily, too.

CleanShot 2021-02-05 at 15 45 31

**Comment by amyblais** [comment]
To be cherry-picked to ``cloud`` branch.

**Pull request merged**
