### PR TITLE
MM-46526 - add telemetry event for initial show of tasklist and add event to dismiss

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
this PR adds a telemetry event for initial show of the onboarding tasklist and and also add event when the tasklist dismissed

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46526

#### Related Pull Requests
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks @pvev!

**Review by JulienTant — APPROVED** [review]

**Review by julmondragon — APPROVED** [review]
LGTM

**Comment by pvev** [comment]
@stevemudie the validation for this PR can be deferred to post merge.

**Review by stevemudie — APPROVED** [review]
Will test this post merge.

**Pull request merged**
