### PR TITLE
 MM-20412: Migrate 'components/channel_header_mobile/show_search_button' module to TypeScript

### PR DESCRIPTION
**Pull request by Revanth47**
MM-20412: Migrate 'components/channel_header_mobile/show_search_button' module to TypeScript

#### Summary
Migrating 'components/channel_header_mobile/show_search_button' module to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/16161
JIRA: https://mattermost.atlassian.net/browse/MM-20412

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
Thanks!

**Review by agarciamontoro — APPROVED** [review]
Thank you for your contribution, @Revanth47! This looks good to me :tada:

**Comment by stylianosrigas** [comment]
Removing cloud test server label for maintenance purposes. Please re add if you need it :)

**Review by jgilliam17 — APPROVED** [review]
Thank you @Revanth47 
Tested, looks good to merge.
- Verified search button in mobile view - no change in functionality.
@agarciamontoro can you please help merge? Thanks 🙂

**Pull request merged**
