### PR TITLE
Break generated "emoji_data.go" file across multiple lines

### PR DESCRIPTION
**Pull request by Roy-Orbison**
#### Summary
Prevents the generated `.go` file from being a huge, unreadable blob without bloating its file size. Substitutes the space in the joiner for a newline.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
Hello @Roy-Orbison , thanks for your contribution.

I was wondering what was the pain being addressed by this, as the go file is just the result of all the calculations and it was not expected to be read by a person.

Code looks good, but I'd like to dig deeper into the reasoning behind the PR.

**Comment by Roy-Orbison** [comment]
The current "cheat sheet" for emoji codes in Mattermost is [this](https://raw.githubusercontent.com/mattermost/mattermost-server/master/model/emoji_data.go). With this change, it should look like this:
```go
// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
// This file is automatically generated via `make emojis`. Do not modify it manually.

package model

var SystemEmojis = map[string]string{
"grinning": "1f600",
"smiley": "1f603",
"smile": "1f604",
"grin": "1f601",
"laughing": "1f606",
"satisfied": "1f606",
"sweat_smile": "1f605",
"rolling_on_the_floor_laughing": "1f923",
"rofl": "1f923",
"joy": "1f602",
"slightly_smiling_face": "1f642",
"upside_down_face": "1f643",
"wink": "1f609",
"blush": "1f60a",
"innocent": "1f607",
"smiling_face_with_3_hearts": "1f970",
"heart_eyes": "1f60d",
//...
"raised_hand_medium_skin_tone": "270b-1f3fd",
"hand_medium_dark_skin_tone": "270b-1f3fe",
"raised_hand_medium_dark_skin_tone": "270b-1f3fe",
"hand_dark_skin_tone": "270b-1f3ff",
"raised_hand_dark_skin_tone": "270b-1f3ff",
"v_light_skin_tone": "270c-1f3fb",
"v_medium_light_skin_tone": "270c-1f3fc",
"v_medium_skin_tone": "270c-1f3fd",
"v_medium_dark_skin_tone": "270c-1f3fe",
"v_dark_skin_tone": "270c-1f3ff",
"writing_hand_light_skin_tone": "270d-1f3fb",
"writing_hand_medium_light_skin_tone": "270d-1f3fc",
"writing_hand_medium_skin_tone": "270d-1f3fd",
"writing_hand_medium_dark_skin_tone": "270d-1f3fe",
"writing_hand_dark_skin_tone": "270d-1f3ff",
"mattermost": "mattermost",
}
```

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good to me in perspective of formatting. But i would like defer it to @Willyfrog for final decision

**Review by Willyfrog — APPROVED** [review]

**Comment by Willyfrog** [comment]
> The current "cheat sheet" for emoji codes in Mattermost is [this](https://raw.githubusercontent.com/mattermost/mattermost-server/master/model/emoji_data.go). With this change, it should look like this:

yeah, I understood the results, but I was wondering why did it bother you to make the change. The reason for that, is that I thought about formatting it, but I thought noone was going to read that file and that proper formatting wasn't really needed. With your change I realize I might be wrong and I was wondering what was 

Also, realize that it requires a server PR that adds the results into the server, otherwise it won't happen until next time someone has to run the script.

@jgilliam17 I tagged you in this one, but without the server changes there is not much that needs to be tested in here as the results of the file changed will output into the server and not the webapp.

**Review by hmhealey — CHANGES_REQUESTED** [review]
This might cause problems because `gofmt` is going to start complaining ones these are on multiple lines. Each line needs to be indented which is easy enough to fix, but once we do that, `gofmt` will want everything aligned in columns like
```go
var SystemEmojis = map[string]string{
	"grinning":    "1f600",
	"smiley":      "1f603",
	"smile":       "1f604",
	"grin":        "1f601",
	"laughing":    "1f606",
	"satisfied":   "1f606",
}
```

That's probably going to be a pain to do on the JS side, so maybe we could just make this script run `gofmt -w emoji_data.go` after its written the file?

**Comment by Roy-Orbison** [comment]
Running through `gofmt` seems the most future-proof. Is it possible to track that output file in server repo instead? It makes sense having the generator be in a single place, but it's odd having the server code tracked in the client.

**Comment by hmhealey** [comment]
It is a bit odd, but this script generates the data files for the server and both apps, so we end up having to copy files anyway. The web app repo is the one that contains the images and most of the data about the emojis, so that's why it lives here.

**Comment by hmhealey** [comment]
That's partly a reminder for us if it's blocked because one of us hasn't reviewed it or because the person working on it needs help. I wouldn't pay too much attention to it 🙂

**Review by hmhealey — CHANGES_REQUESTED** [review]
Unfortunately, that's not lining up in the same way gofmt does it. I don't understand the exact logic that gofmt is using since it seems like it's not spacing everything the same like I originally thought. I'm not even sure what rules it's using to do that because it doesn't seem consistent with how it's grouping lines of different lengths.

For example, the version of emoji_data.go generated by your script produces a nice and even
```go
var SystemEmojis = map[string]string{
	// ...
	"yum":                                                                      "1f60b",
	"stuck_out_tongue":                                                         "1f61b",
	"stuck_out_tongue_winking_eye":                                             "1f61c",
	"zany_face":                                                                "1f92a",
	"grinning_face_with_one_large_and_one_small_eye":                           "1f92a",
	"stuck_out_tongue_closed_eyes":                                             "1f61d",
	"money_mouth_face":                                                         "1f911",
	"hugging_face":                                                             "1f917",
	"hugs":                                                                     "1f917",
	"face_with_hand_over_mouth":                                                "1f92d",
	"smiling_face_with_smiling_eyes_and_hand_covering_mouth":                   "1f92d",
	"shushing_face":                                                            "1f92b",
	"face_with_finger_covering_closed_lips":                                    "1f92b",
	"thinking_face":                                                            "1f914",
	"thinking":                                                                 "1f914",
	// ...
}
```
but then when you run it through gofmt, it produces
```go
var SystemEmojis = map[string]string{
	// ...
	"yum":                           "1f60b",
	"stuck_out_tongue":              "1f61b",
	"stuck_out_tongue_winking_eye":  "1f61c",
	"zany_face":                     "1f92a",
	"grinning_face_with_one_large_and_one_small_eye": "1f92a",
	"stuck_out_tongue_closed_eyes":                   "1f61d",
	"money_mouth_face":                               "1f911",
	"hugging_face":                                   "1f917",
	"hugs":                                           "1f917",
	"face_with_hand_over_mouth":                      "1f92d",
	"smiling_face_with_smiling_eyes_and_hand_covering_mouth": "1f92d",
	"shushing_face":                         "1f92b",
	"face_with_finger_covering_closed_lips": "1f92b",
	"thinking_face":                         "1f914",
	"thinking":                              "1f914",
	// ...
}
```

I think we may as well just run gofmt on this automatically since figuring out their logic seems difficult

**Comment by Roy-Orbison** [comment]
> maybe we could just make this script run `gofmt -w emoji_data.go` after its written the file?

Doesn't that wrongly introduce a dependency on `gofmt` to this repo, which doesn't have any other Golang code? Won't the [server's `golangci-lint` make job](https://github.com/mattermost/mattermost-server/blob/0ce7c5e3da8b9a508f0467b31167cd65e50ed2a2/Makefile#L313) automatically fix it? I could I add the `gofmt -w` before the lint check, or to the [old job](https://github.com/mattermost/mattermost-server/blob/0ce7c5e3da8b9a508f0467b31167cd65e50ed2a2/build/legacy.mk#L10) but I can't tell if anything runs the latter automatically.

**Comment by hmhealey** [comment]
I think it's fine to add that dependency here. This script already has some of its own dependencies that also aren't used anywhere else in the repo. This is run pretty rarely, so we won't need to add Go to the web app repo's setup instructions or anything.

Regarding `golangci-lint`, that won't fix this issue though. In fact, that check will fail the build if this script doesn't generate `emoji_data.go` matching its expected formatting

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Skipping QA review on this since it doesn't have any user-visible changes.

I'm going to try to merge master to see if that gives CircleCI the kick it needs to complete. It's possible that it's not liking it because this PR predates the security issue CircleCI had

/update-branch

**Comment by Roy-Orbison** [comment]
@hmhealey Would you mind? I don't have that repo or Go set up on my local machine.

**Comment by M-ZubairAhmed** [comment]
@hmhealey here is the JIRA https://mattermost.atlassian.net/browse/MM-49731

**Comment by hmhealey** [comment]
Will do. Thanks for filing that, Zubair!

**Pull request merged**
