### PR TITLE
MM-39379 - success modal svg  not aligned with button

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
This PR adds a specific style to the svg present in the success purchase modal, so the svg image of the laptop is centered aligned with the `lets go` button

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39379

#### Screenshots
Before:
Captura de pantalla 2022-02-14 a las 23 15 45

After:
Captura de pantalla 2022-02-14 a las 23 16 07

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by annelieseklein** [comment]
@pablovelezvidal where am I supposed to be looking?

**Review by JulienTant — APPROVED** [review]
LGTM @pablovelezvidal ! (Toggling the Server to reset the trial as I "purchased" a license)

**Review by AGMETEOR — APPROVED** [review]

**Comment by annelieseklein** [comment]
@pablovelezvidal can you send me the screenshots here please? :)

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal can you send me the screenshots here please? :)

hey @annelieseklein I am seeing some weird behavior with other SVGs I am verifying what is the cause of this, just to make sure there are no regressions added. For now, I will remove you from the reviewers, and when this gets ready, I will add you again. Sorry I didn't do it before and had this on your plate

**Comment by pablovelezvidal** [comment]
@annelieseklein now is working as expected

Captura de pantalla 2022-02-14 a las 23 14 15


** This one is just for reference, using the inspector I changed the margin just to verify it is well centered with the button
Captura de pantalla 2022-02-09 a las 18 56 40

**Review by annelieseklein — APPROVED** [review]
looks good!

**Pull request merged**
