### PR TITLE
[MM-9695] Added statuses to channel invite modal

### PR DESCRIPTION
**Pull request by courtneypattison**
#### Summary
Adds user statuses to "add member to channel" list

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/11264

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/7194

#### Screenshots
Screen Shot 2021-03-29 at 3 03 59 PM

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
Thanks @courtneypattison LGTM! 🎉

**Review by matthewbirtch — APPROVED** [review]
thanks for the contribution @courtneypattison! Looks good, but I'd like to request a minor tweak to the status positioning. With that, this is approved

```
bottom: -4px;
right: -4px;
```

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @courtneypattison!

**Comment by jgilliam17** [comment]
@matthewbirtch Ticket https://mattermost.atlassian.net/browse/MM-9695 mentions adding statuses to both, channel invite modal and team invite modal. I can create a separate ticket for team invite modal if we plan on adding statuses there too. Let me know. Thanks

**Comment by matthewbirtch** [comment]
> @matthewbirtch Ticket https://mattermost.atlassian.net/browse/MM-9695 mentions adding statuses to both, channel invite modal and team invite modal. I can create a separate ticket for team invite modal if we plan on adding statuses there too. Let me know. Thanks

I suppose it could/would make sense to show the status in the team invite modal for consistency's sake but seems less important in this case to me. If you want, feel free to create a ticket for the UX team to triage

**Review by jgilliam17 — APPROVED** [review]
Thank you @courtneypattison 
Tested, looks good to merge.
- Verified user statuses on channel invite modal.
@devinbinnie Can you please help merge? Thanks 🙂

**Pull request merged**
