### PR TITLE
Cypress/E2E: Fix failing tests on MM-T706 and MM-T706

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix failing tests on MM-T706 and MM-T706

#### Ticket Link
none, failing on daily Cypress tests

### CODE REVIEW

**Comment by saturninoabril** [comment]
Yup, you need the webhook server running - https://github.com/mattermost/mattermost-webapp/pull/6139/files#diff-dbe7b346ca5fa5dd87baa3de5670b91cL13

**Comment by saturninoabril** [comment]
If it's for MM-T706, it's expected. Could you share the more about the failing logs/screenshot?

**Comment by josephbaylon** [comment]
@saturninoabril Not sure if this is what you need but I'm attaching the cypress log

Screen Shot 2020-08-14 at 10 25 25 AM

**Comment by josephbaylon** [comment]
Oh and it is for MM-T706. However for MM-T707, I'm getting this one,

Screen Shot 2020-08-14 at 10 29 27 AM

**Comment by prapti** [comment]
I'm getting this error when running the test. Not sure what's causing it, but I'm looking into it. Have you seen this?
Screen Shot 2020-08-18 at 6 18 31 PM

**Pull request merged**
