### PR TITLE
e2e/Cypress:fixed spec files

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary
Fixed ctrl_cmd_k_focuses_message_box_spec.js 
Fixed ctrl_cmd_k_open_channel_from_global_threads_spec.js
Fixed quick_switcher_spec.js
Fixed image_aspect_ratio_spec.js

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by Phrynobatrachus — APPROVED** [review]
Thanks!

**Review by yasserfaraazkhan — APPROVED** [review]
🎉

**Pull request merged**
