### PR TITLE
legacy mattermost cloud bar

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Show banner to legacy mattermost cloud admins that they need to change workspace soon.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45013

#### Screenshots

https://user-images.githubusercontent.com/13738432/194353683-19502477-a002-4102-b61e-bc0bac5b3ed4.mp4

#### Release Note

```release-note
Show banner to legacy mattermost cloud admins that they need to change workspace soon.
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks @neallred!

**Review by Afsoon — APPROVED** [review]
LGTM

**Comment by marianunez** [comment]
@stevemudie let's test this post-merge as part of the cloud release testing so it can make it to the cloud branch

**Pull request merged**
