### PR TITLE
Cypress/E2E: fix and update tests

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix and update tests
- with recent change on UI Text from "Pinned posts" to "Pinned Posts"
- marked other test not for cloud
- removed unnecessary verification to non-deterministic UI animation

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. @saturninoabril Should this be applied to v5.31 as well?

**Comment by saturninoabril** [comment]
Thanks @josephbaylon, I agree.
@amyblais For your approval to get this into release-5.31. Changes were related to tests and no risk to product.

**Comment by amyblais** [comment]
Sounds good!

**Review by prapti — APPROVED** [review]
All tests passed and changes look good to me 👍

**Comment by saturninoabril** [comment]
Done cherry-pick into release-5.31 - https://github.com/mattermost/mattermost-webapp/commit/3beab88d5a28bc72274ae47f0c0bab157dcb2d89

**Pull request merged**
