### PR TITLE
Removing Beta from sv and bg

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
Removing beta from sv and bg
Replacing the [other pr](https://github.com/mattermost/mattermost-webapp/pull/7746/files?file-filters%5B%5D=) that also added En-AU but has an issue in Mobile.

### CODE REVIEW

**Comment by amyblais** [comment]
@ctlaltdieliet Do we need a PR for mobile too or just for webapp?

**Comment by ctlaltdieliet** [comment]
Hi Amy,

Just for Webapp as far as I know.
I checked in the app and you can't set the language.
My guess : the language is stored in the user settings on the server.
When I change my settings in the browser, it refreshes the app to the new language settings.

When I added sv and bg to Mobile I only had to make sure that the language files were found.

Tom

**Review by jasonblais — APPROVED** [review]
Thanks!

**Comment by amyblais** [comment]
@metanerd This will be good to include in v5.34 release (RC-1 will be cut on Thursday this week, so maybe we can get this in before Thursday).

**Comment by metanerd** [comment]
Thank you @ctlaltdieliet ! Can you try running `npm run updatesnapshot` again? The CI is failing due to some problems with the snapshot. You can view it here: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/36062/workflows/deb70153-0327-4aa2-add6-b57f53150c09/jobs/244590

**Comment by ctlaltdieliet** [comment]
> Thank you @ctlaltdieliet ! Can you try running `npm run updatesnapshot` again? The CI is failing due to some problems with the snapshot. You can view it here: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/36062/workflows/deb70153-0327-4aa2-add6-b57f53150c09/jobs/244590

Done... :fingers_crossed:

**Review by metanerd — APPROVED** [review]

**Comment by metanerd** [comment]
Looks good! Going to merge it and backport it. Thank you @ctlaltdieliet !

**Pull request merged**
