### PR TITLE
translations PR 20190923

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by amyblais** [comment]
@mgdelacroix Kind reminder to review this for v5.16.

**Comment by amyblais** [comment]
@enahum Do the translation PRs need to be merged before cutting RC-1 today or are they ok for RC-2?

**Comment by enahum** [comment]
@amyblais any time will do I don't mind

**Comment by enahum** [comment]
should I merge it?

**Comment by enahum** [comment]
@mgdelacroix my friend the PR cannot be changed.. if you want to make changes on the translations for future PR's go into the [Translation server](https://translate.mattermost.com) and make the changes there so they can be submitted with the next PR.

**Comment by mgdelacroix** [comment]
@enahum I see, is the point of the review then just to check the format then?

**Comment by enahum** [comment]
yup

**Pull request merged**
