### PR TITLE
WIP: [MM-14632] Add a Cypress E2E test for ""Remove Team Icon""

### PR DESCRIPTION
**Pull request by cannalee90**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/10470

### CODE REVIEW

**Comment by hanzei** [comment]
Hey @cannalee90,

How is your process on this PR going? Can we help with anything?

**Comment by cannalee90** [comment]
@hanzei Thank you for your concern. I've been very busy last weeks so I almost miss about this issue. I'm going to finish it by end of this week. Thank you!

**Comment by hanzei** [comment]
Hey @cannalee90, thanks for the heads up. Looking forward to this PR :+1:

**Comment by hanzei** [comment]
Hey @cannalee90,

Is there anything we can help you with to get this PR to a "reviewable" state?

**Comment by hanzei** [comment]
Closing this PR because of inactivity. Still thanks @cannalee90. Let me know, if you still want to work on this.

**Pull request closed without merging**
