### PR TITLE
MM-31858 - Include build hash in cloud about modal

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Include build hashes in cloud about modal

#### Ticket Link
[MM-31858](https://mattermost.atlassian.net/browse/MM-31858)

#### Screenshots

Screen Shot 2021-01-08 at 3 43 49 PM

### CODE REVIEW

**Review by jwilander — APPROVED** [review]
LGTM

**Review by nickmisasi — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
LGTM

**Comment by jwilander** [comment]
@marianunez did we want to cherry-pick this one to `cloud`?

**Comment by marianunez** [comment]
> @marianunez did we want to cherry-pick this one to `cloud`?

I did not, given that we were so late into cloud testing didn't want to introduce last minute changes that didn't seem urgent.

**Pull request merged**
