### PR TITLE
[MM-48061]: Allow CTRL/CMD + K to insert link formatting when text is selected

### LINKED ISSUE #21575: Allow CTRL/CMD + K to insert link formatting when text is selected
Problem: The typical link formatting shortcut is CTRL/CMD + K, but that conflicts with our channel switcher, so we use CTRL + Alt+ K. This is not discoverable and takes high cognitive load to process the shortcut in mattermost compared to other products.

Proposed Solution (Same as GitHub): When text is selected in the message input are or reply input area,

image

- If the user hits CTRL/CMD + K then add the markdown link formatting (same as if they hit CTRL + Alt + K). GitHub example: https://gyazo.com/ec59afbe931dac369850248e00f03817
    - In all other cases (ie text is not selected in the input areas), CTRL/CMD + K opens the Find Channels dialog as it does today 

- If the clipboard contains a URL beginning with http:// or https:// and the user pastes, format it as a markdown hyperlink with the selected text. GitHub example: https://gyazo.com/a96702d5a16f5a009856fb4fa6bbe901
    - If the clipboard does not contain a URL, then paste should behave as normal and overwrite the selected text.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-48061

### PR DESCRIPTION
**Pull request by kyeongsoosoo**
#### Summary

This PR resolves two issues.
- If the user hits CTRL/CMD + K then add the markdown link formatting (same as if they hit CTRL + Alt + K). 
 - If the clipboard contains a URL beginning with http:// or https:// and the user pastes, format it as a markdown hyperlink with the selected text.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/21575

#### Screenshots

- If the user hits CTRL/CMD + K then add the markdown link formatting (same as if they hit CTRL + Alt + K). 

https://user-images.githubusercontent.com/59413880/220940058-09446d46-1b74-40d3-814b-495cbef8ff22.mov

- If the clipboard contains a URL beginning with http:// or https:// and the user pastes, format it as a markdown hyperlink with the selected text.

https://user-images.githubusercontent.com/59413880/220939735-d7e9b92f-b8d6-4280-ae9d-757616d0fa04.mov

#### Release Note

```release-note
Allow CTRL/CMD + K to insert link formatting when text is selected
```

### CODE REVIEW

**Comment by esethna** [comment]
Thank you for the PR @kyeongsoosoo, this is sweet!

**Comment by esethna** [comment]
@AshishDhama can you help look into why the test server won't fire up?

**Review by esethna — APPROVED** [review]
This is amazing, such a life saver. Great work @kyeongsoosoo!

**Review by BenCookie95 — APPROVED** [review]
Nice work!

**Review by AshishDhama — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

**Comment by hmhealey** [comment]
The web app now lives in the `webapp/channels` over in https://github.com/mattermost/mattermost-server. We decided to move it to be a monorepo to make both development and our CI pipelines easier, but it's unfortunately disruptive right now. We've updated [our setup docs](https://developers.mattermost.com/contribute/developer-setup/) and added [some steps for migrating to working with the monorepo](https://developers.mattermost.com/contribute/monorepo-migration-notes/).

Copying the changes over there hopefully shouldn't be too hard. There's a few changes to file paths (such as the code living in a dedicated `src` subdirectory), but most things should look the same as they do now. 

Let us know if you could use any help with this. Hopefully the process is smooth.

**Comment by kyeongsoosoo** [comment]
@hmhealey  @M-ZubairAhmed  I'll open the PR soon!

**Comment by furqanmlk** [comment]
Hi @kyeongsoosoo, Can you please assign me a new PR for QA review?

**Pull request closed without merging**
