### PR TITLE
MM-19509 Prioritize autocomplete results based on interactions and threads

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
 * Add sort method of auto complete results to be based on last_viewed_at as well
  * Add new prop priorityResults to auto complete so we can add profiles
    like thread interactions on top

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19509

#### Related Pull Requests
https://github.com/mattermost/mattermost-redux/pull/1279

### CODE REVIEW

**Review by esethna — APPROVED** [review]

**Comment by esethna** [comment]
@jgilliam17 same as the channel switcher PR, let's do a brief test here and then do a more thorough test once it's merged to daily since this will be hard to test without real data

**Comment by jgilliam17** [comment]
Thank you @sudheerDev
Looks good
- Verified using @ in channel sorts results by last interacted 
- Verified using @ in a thread sorts by thread participant that commented most recently, followed by other thread participants and lastly other members of the channel  
Out of scope: Do we care to sort `not in channel` section by last interacted or continue to display a-z?
Screenshot 2020-11-02 210146

**Review by hmhealey — APPROVED** [review]

**Comment by esethna** [comment]
> Do we care to sort "not in channel" section by last interacted or continue to display a-z?

I think we identified that as out of scope, is that correct @sudheerDev? @jgilliam17 please approve if QA is complete

**Review by jgilliam17 — APPROVED** [review]

**Comment by sudheerDev** [comment]
> > Do we care to sort "not in channel" section by last interacted or continue to display a-z?
> 
> I think we identified that as out of scope, is that correct @sudheerDev? @jgilliam17 please approve if QA is complete

No @esethna,  @jgilliam17. Aah, I noticed that. but I thought I was able to do that as well.  Let me check this and get back to you guys

**Comment by sudheerDev** [comment]
@jgilliam17 You can give this another try, I sorted remote results as well. @esethna i thought i already did that but as it turns i was doing it on some really old unused code, i removed that and fixed the actual path

**Review by nevyangelova — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thank you @sudheerDev 
re-tested , can you please check again, I'm seeing `not in channel` section still sorting a-z.
Screen Shot 2020-11-09 at 8 56 30 AM

**Comment by sudheerDev** [comment]
@jgilliam17 Aah, sorry about that. I screwed up my git. I thought I did push changes but it didn't work, just did and I checked the spinmint as well this time. It should be good for testing

**Comment by jgilliam17** [comment]
No problem at all @sudheerDev 
Can you check if this error is related to this fix. I am not able to reliably reproduce or offer steps. I thought it appeared when I placed focus back on the browser window and tried to dismiss new messages banner
Screen Shot 2020-11-10 at 9 54 03 AM

**Comment by sudheerDev** [comment]
> No problem at all @sudheerDev
> Can you check if this error is related to this fix. I am not able to reliably reproduce or offer steps. I thought it appeared when I placed focus back on the browser window and tried to dismiss new messages banner

I don't think it is related.

**Comment by jgilliam17** [comment]
Thank you @sudheerDev 
Re-tested - looks good to merge.
- Verified that  `not in channel` sorts by last interacted.
The errors reproduce on master, filed separately for follow up. https://mattermost.atlassian.net/browse/MM-30446

**Pull request merged**
