### PR TITLE
MM-T576 /poll

### PR DESCRIPTION
**Pull request by clarmso**
#### Summary

This PR adds tests for the /poll slash command from the MatterPoll plugin (https://github.com/matterpoll/matterpoll).  Please note that the plugin *must* be installed prior to running these tests.

#### Ticket Link

https://automation-test-cases.vercel.app/test/MM-T576

#### Related Pull Requests

- Has server changes N/A
- Has redux changes N/A
- Has mobile changes N/A

#### Screenshots

Screen Shot 2020-08-19 at 1 12 20 AM

### CODE REVIEW

**Comment by clarmso** [comment]
Could someone from Mattermost put the label "Hackfest" to this PR? Thanks!!

**Review by saturninoabril — CHANGES_REQUESTED** [review]
Thanks @clarmso for updating. All looks good except for the a must to remove the tar file. `*.tar.gz` is intentionally git ignored. Such file will be downloaded and setup on demand both for local dev and in CI.

**Review by saturninoabril — APPROVED** [review]
Thanks @clarmso, LGTM!

**Pull request merged**
