### PR TITLE
Adds a red dot to browser favicon when there are unread mentions

### PR DESCRIPTION
**Pull request by b-lawrence**
#### Summary
Adds a red dot to browser favicon when there are unread mentions.

#### Ticket Link
[MM-9563](https://github.com/mattermost/mattermost-server/issues/9502)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by hanzei** [comment]
Hey @b-lawrence,

Do you have questions about the provided feedback?

Looking forward to this feature! :tada:

**Comment by esethna** [comment]
@b-lawrence please let me know if there are any questions regarding the above feedback. Excited about this change!

**Comment by hanzei** [comment]
Hey @b-lawrence,

Thanks you for the contribution!Do you require further help or feedback?

Please note that we will close this PR after another 30 days of inactivity. If you don't object, contributors might complete this PR for you.

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the PR is no longer being worked on.

If you're interested continuing to help on this, let us know! Happy to help you finish the contribution.

**Comment by wujku** [comment]
I would like to pick up this task. Could you give me any tips on how to accomplish this feature?

**Comment by jasonblais** [comment]
Thanks @wujku! Here's a guide to help you get started: https://developers.mattermost.com/contribute/getting-started/

In step 4 when selecting a ticket, you can choose the issue related to this PR: https://github.com/mattermost/mattermost-server/issues/9502

**Pull request closed without merging**
