### PR TITLE
[MM-28591] Pass show prop to plugin link tooltips

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Before this change, tooltips would be rendered on page load. In the case of the GitHub plugin this lead to fetching all PR/issue details on pageload.

By passing a `show` prop to the tooltips plugins can decide themself, if they want to render while not being shown.

Thanks to @mickmister for going me guiding me with this ticket 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28591

#### Related Pull Requests
- https://github.com/mattermost/mattermost-plugin-github/pull/368

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by amyblais** [comment]
@hanzei Feature complete was yesterday. Can you help describe this PR so I understand if it should be pushed to the next release?

**Comment by hanzei** [comment]
@amyblais This PR allows plugin to decide them self if they want to show a link tooltip. It's a highly desired change as the tooltip on the GitHub plugin is hardly usable in environments with a lot of GH links. It's a change with minimal risk of regressions and only impacts plugin tooltips.

**Review by mickmister — APPROVED** [review]
Great work!

**Comment by hanzei** [comment]
@DHaussermann This changes should be tested alongside with https://github.com/mattermost/mattermost-plugin-github/pull/368:

1. Run this PR and https://github.com/mattermost/mattermost-plugin-github/pull/368
2. Run webapp `master` and https://github.com/mattermost/mattermost-plugin-github/pull/368
3. Run this PR and GitHub plugin `master`

In all three cases the tooltip should show up. For 1. a small delay before showing the tooltip is expected.

**Comment by amyblais** [comment]
@DHaussermann Kind reminder to review for v5.28.

**Comment by DHaussermann** [comment]
Tested the following combinations of plugin version and server version:
- GitHub previous on master --> web-requests are made when channel opens 
- GitHub with PR 368  on master --> web-requests are made when channel opens (as this PR is not yet merged)
- GitHub with PR 368  on 5.27 --> web-requests are made when channel opens (no regressions)
- GitHub with PR 368 and this Webapp PR 6492 --> web-requests are made when only on pop-over 🎉 
- GitHub with PR 368 on 5.25.3 --> previews is not supported (no regressions)
@hanzei  let me know if you can think of any other cases worth checking. It seems like other combination would have already been covered in their respective release testing cycles. 


This is working as expected with the changes to plugin and webapp. It also works as expected when running a new version of the plugin with older server versions or an older version of the plugin with newer server versions. 

More Tooltip related testing will be done as part of release testing.

LGTM!

**Review by DHaussermann — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Awesome, thanks for the in depth testing :rocket:

**Pull request merged**
