### PR TITLE
MM-16247/MM-16279 Re-render RHS when post type components change

### PR DESCRIPTION
**Pull request by hmhealey**
These components still used `shouldComponentUpdate` which hadn't been updated with more recently added props include the post type plugins

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16247
https://mattermost.atlassian.net/browse/MM-16279

### CODE REVIEW

**Comment by jwilander** [comment]
@hmhealey this makes me a bit nervous to squish into the release. How confident are you that this won't cause problems? Can we just add the new props to `shouldComponentUpdate` for now?

**Comment by hmhealey** [comment]
I don't see any reason why this would cause problems since we've been using `PureComponent` instead of `shouldComponentUpdate` for a long time now. Most of the other props were being checked already except for things that won't change like the `teamId` and `currentUserId` or system console settings like `enableEmojiPicker` and `enablePostUsernameOverride`

**Comment by cpoile** [comment]
@jwilander @hmhealey afaik, PureComponent will only work with simple props and state, and we're sure that's all that these will have? Otherwise it will fail to re-render (again, afaik)

**Comment by jwilander** [comment]
PureComponents can have some issues if the object doesn't change and something inside of it does but since all the redux state is immutable and has to be a new object when modified we don't generally have to worry about that too much

**Pull request merged**
