### PR TITLE
MM-28839 Fix for hover of cursor on indicators

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Replacing `a` tag with `span` tag to remove the hover

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28839

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]
Curious, why was this an anchor in the first place? 😕

**Comment by sudheerDev** [comment]
> Curious, why was this an anchor in the first place? 😕

Copied from an existing pattern, i was meant to remove it at the end but forgot about it

**Review by jgilliam17 — APPROVED** [review]
Thank you @sudheerDev 
Tested, looks good to merge.
- Verified cursor pointer on dot page indicators hover. Hand pointer has been removed.

**Comment by sudheerDev** [comment]
Reverted the last two commits added after dev reviews made for hardcoding to ease QA testing

**Pull request merged**
