### PR TITLE
MM-45486: Allows users to remove themselves from a custom role.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Allows users to remove themselves from a system role.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45486

#### Release Note

```release-note
Allowed users to remove themselves from a system role.
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by michelengelen — CHANGES_REQUESTED** [review]
Sry to block this, but could you please address the changes I mentioned earlier?

**Comment by mkraft** [comment]
> Sry to block this, but could you please address the changes I mentioned earlier?

Thanks for noticing that. I've pushed the commit.

**Review by michelengelen — APPROVED** [review]
LGTM ... thanks!

**Pull request merged**
