### PR TITLE
[MM-30432]: Allow users to specify different desktop notification sounds per channel

### PR DESCRIPTION
**Pull request by kyeongsoosoo**
#### Summary

I added `desktop_sound` and `desktop_notification_sound` props to `ChannelNotifyProps`.
When these props are set, they are applied instead of `UserNotifyProps`.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/21191
Jira: https://mattermost.atlassian.net/browse/MM-30432
#### Related Pull Requests

- https://github.com/mattermost/mattermost-server/pull/21671

#### Screenshots

https://user-images.githubusercontent.com/59413880/201989524-4d5cd11f-9ba6-4e9c-bbbd-50b3bd57a577.mov

#### Release Note

```release-note
Allow users to specify different desktop notification sounds per channel
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Tested with v5.2.1 and seems to work well :)
Thanks @kyeongsoosoo!

**Comment by jgilliam17** [comment]
@kyeongsoosoo Do I need to build the test server on the related server PR in order to be able to test all the changes? Let me know - thanks 🙂

**Comment by kyeongsoosoo** [comment]
@jgilliam17 Yes! we need the test server on the related server PR.

**Review by Rishselva — COMMENTED** [review]
Great work!

@matthewbirtch I wanted to clarify two aspects of this feature before I give the green light on this review.
1. Should the "reset to defaults" option always be present in the notifications preference section or only appear if changes are made? Currently, I see the option even without making any changes. 
Screen Shot 2022-11-23 at 11 01 17 AM

2. Should there be a "reset to defaults" option in the main desktop notifications under setting? 
Screen Shot 2022-11-23 at 11 00 45 AM

**Comment by matthewbirtch** [comment]
> 1. Should the "reset to defaults" option always be present in the notifications preference section or only appear if changes are made? Currently, I see the option even without making any changes.

This should only show if the user has made changes that deviate from the global default notifications settings

> 3\. Should there be a "reset to defaults" option in the main desktop notifications under setting?

No, this _is_ where the global default is set

**Comment by Rishselva** [comment]
@kyeongsoosoo Great work! 

One change that needs to be made is only showing the "reset to default" option if the user has made changes that deviate from the global default notifications settings as Matt mentioned above. Thank you :)

**Comment by kyeongsoosoo** [comment]
@Rishselva Thanks for the review. I fixed it!

https://user-images.githubusercontent.com/59413880/203629554-1abd8a2c-5f33-44bf-bf68-764c5ba69429.mov

**Review by Rishselva — APPROVED** [review]
Looks great! Thank you @kyeongsoosoo

**Comment by Rishselva** [comment]
Hiello @jgilliam17! Any updates on the testing for this ticket? :)

**Comment by kyeongsoosoo** [comment]
Hi, @jgilliam17 
Could you check this PR please?

**Comment by jgilliam17** [comment]
@kyeongsoosoo Can you please rebase branch with master? The test server on the related server PR is failing to create. Thanks

**Comment by kyeongsoosoo** [comment]
@jgilliam17 I updated the branch :)

**Comment by jgilliam17** [comment]
Thanks @kyeongsoosoo 
Verified new user setting for channel specific sound notificatios
Can you please update again so I can trigger e2es? I suspect some automated tests will fail due to changes on the channel Notification modal

**Comment by kyeongsoosoo** [comment]
Thanks @jgilliam17 
I updated the branch😄

**Comment by jgilliam17** [comment]
Thanks @kyeongsoosoo 
e2e report show some failures related to text changes 
e.g. MM-T4417_1 and MM-T4417_2, but there may be more that are not as apparent.
I'd like to wait and re-run the cycle again after we fix current issues with our Cypress resulting in a large number of failures related to accessibility 
It will be easier to identify failures after that fix is merged. Appreciate  your understanding 🙂

**Comment by jgilliam17** [comment]
Thanks @kyeongsoosoo 
Latest [e2e report](https://mattermost-cypress-report.s3.amazonaws.com/283157-064e115-onprem-ent-webapp-pr-11605-mm-ee-test:064e115/mochawesome.html) - 3 tests are failing due to text change 
MM-T4417_1 , MM-T4417_2 and MM-T885

**Comment by kyeongsoosoo** [comment]
@jgilliam17
I fixed the e2e test  failures related to text changes. Please let me know if there's anything else I need to fix.

**Comment by jgilliam17** [comment]
Thanks @kyeongsoosoo 
I'm re-running e2es

**Comment by jgilliam17** [comment]
Noticed that there is a change in "Send mobile push notifications" section. 
Default state is lost, and new sub-header is added " Send desktop notifications" I don't believe this was part of the original design, and may be unintentional.
@matthewbirtch can you please take a look and advise? Thanks 
Before:
Screen Shot 2023-01-03 at 1 49 12 PM


Now, on test server:
Screen Shot 2023-01-03 at 1 44 20 PM

**Comment by jgilliam17** [comment]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/283656-685ad7a-onprem-ent-webapp-pr-11605-mm-ee-test:685ad7a/mochawesome.html) - no PR related failures

**Comment by matthewbirtch** [comment]
> Noticed that there is a change in "Send mobile push notifications" section. Default state is lost, and new sub-header is added " Send desktop notifications" I don't believe this was part of the original design, and may be unintentional. @matthewbirtch can you please take a look and advise? Thanks Before: Screen Shot 2023-01-03 at 1 49 12 PM
> 
> Now, on test server: Screen Shot 2023-01-03 at 1 44 20 PM

Yes, you're right @jgilliam17. There are some issues here - even beyond what you've mentioned here. Based on the changes that have been made, this PR seems to be about more than just sound settings, is that correct?

1. Under 'Desktop notifications' we should put "default" in brackets on the option that the global setting has set. For example, if the global notifications setting is set to 'Only for mentions', then the option in the channel notifications setting should read "Only for mentions (default)".
2. We need to update the help text below to "Selecting an option other than the "global default" will override the global notification settings..."
3. Under 'Mobile push notifications' it now says "Send Desktop notifications". 
4. Can we change the title for "Send mobile push notifications" to just "Mobile push notifications" (the title that shows in the collapsed state)
5. Under mobile push notifications, I am seeing no radio button selected initially. There should never be a case for this. It should behave just like the desktop notifications and have the global default set with '(default)' in brackes for that option. If the user changes from the default, the 'reset to defaults' button show up in this section as well.

For clarity, I have added some screens in the Figma file: https://www.figma.com/file/LfJ8K7tn9xYZtBnBDqL0Ut/MM-30432-Notification-Sounds-Per-Channel?node-id=0%3A1

**Comment by kyeongsoosoo** [comment]
@matthewbirtch @jgilliam17   
Thanks for the advise. I'll fix it soon.
It seems that a bug occurred while changing the Desktop notification component.

Could you check the figma file?
Now it looks like the image below.
스크린샷 2023-01-06 오전 2 39 48

**Comment by jgilliam17** [comment]
Figma file opens for me, @matthewbirtch can you please check if we can allow access/permissions for contributors? Thanks

**Comment by matthewbirtch** [comment]
> @matthewbirtch @jgilliam17 Thanks for the advise. I'll fix it soon. It seems that a bug occurred while changing the Desktop notification component.
> 
> Could you check the figma file? Now it looks like the image below. 스크린샷 2023-01-06 오전 2 39 48

My apologies, I guess the permissions were not properly set on that Figma file. You should be able to see it now @kyeongsoosoo: https://www.figma.com/file/LfJ8K7tn9xYZtBnBDqL0Ut/MM-30432-Notification-Sounds-Per-Channel?node-id=0%3A1&t=NMYcOr4jNQJaXttD-1

**Comment by kyeongsoosoo** [comment]
@matthewbirtch  Thanks. I can access it now.

**Comment by kyeongsoosoo** [comment]
@matthewbirtch  I made some changes based on the Figma file. Can you please check this?

https://user-images.githubusercontent.com/59413880/212335168-8cb085ee-d967-420f-b05a-a7ba04b1adf6.mov

**Comment by matthewbirtch** [comment]
These changes are looking great @kyeongsoosoo. Two things that we should add:

- When changing the sound, we should play the selected sound once - just like we do in the global notifications setting.
- In the sound dropdown options, can we add (default) in brackets after the name of the item that is the global default sound?

Other than that, I think everything seems to be working well. Over to @jgilliam17 to test again.

**Comment by kyeongsoosoo** [comment]
> These changes are looking great @kyeongsoosoo. Two things that we should add:
> 
> * When changing the sound, we should play the selected sound once - just like we do in the global notifications setting.
> * In the sound dropdown options, can we add (default) in brackets after the name of the item that is the global default sound?

@matthewbirtch  I added these things. Please take a look.

**Comment by matthewbirtch** [comment]
> * In the sound dropdown options, can we add (default) in brackets after the name of the item that is the global default sound?

@kyeongsoosoo I'm not seeing this one added yet. In the screen below 'Bing' should show as 'Bing (default)' because it is the global default sound.

image

**Comment by kyeongsoosoo** [comment]
@matthewbirtch I fixed it. Now it's working as expected.

스크린샷 2023-01-17 오전 12 51 03

**Comment by jgilliam17** [comment]
Thanks @kyeongsoosoo 
Looks great
I only noticed few small issues that need to be clarified 
1. For sysadmin user on the test server default sound was Crackle. I created one additional user `jelena` and also checked for `user-1`  and both had correct `Bing` as default.
After checking global setting, I realized that modal is displaying sound `default` label for what user has selected on global desktop notifications. I don't think that this is the right approach and we should keep `Bing` as channel level sound default regardless of global preference for sound. We should not pull this info from global preferences each time it is updated.
 I'll let @matthewbirtch give guidance in case I am mistaken. 

Screen Shot 2023-01-18 at 4 29 33 PM


2. Channel level desktop notification sound resets to `On` or `Off` depending on global setting, regardless of user's selection.

I just wanted to make sure I understand what we are trying to achieve. My understanding is that we are not trying to override global desktop notifications setting, only allow users to select custom channel notification sound when global notifications allow it.
While testing, I noticed that turning channel level notification sound ON will not persist when global notification sound is OFF, and vice versa.
To avoid confusion, I would suggest it's best to hide channel level notification preference for sound when global setting for desktop notifications sound is Off. Unless we are decoupling channel level notification sound setting from global notification sound in which case this is not working as expected.

Steps to reproduce:
Set global notification sound setting to Off
Navigate to channel and open channel level notification settings
Keep "Only for mentions" default selected
Select On for Notification Sound
Save
Refresh using cmd+r
Receive mention in channel
Open channel level Notification Preferences 
Observed: Sound did not play when channel mention was received, channel level setting is Off in preferences 
Expected: Since option is present to customize sound per channel, I expected sound to play for channel level mentions regardless of global setting.

**Comment by matthewbirtch** [comment]
> 1. After checking global setting, I realized that modal is displaying sound `default` label for what user has selected on global desktop notifications. I don't think that this is the right approach and we should keep `Bing` as channel level sound default regardless of global preference for sound. We should not pull this info from global preferences each time it is updated.
>    I'll let @matthewbirtch give guidance in case I am mistaken.

@jgilliam17 this is actually working as it should. If you change the global default sound, that should be reflected as the default sound in the channel notification options.

I'm curious to know why you don't think this is the right approach? This is how we are handling the other defaults.

**Comment by matthewbirtch** [comment]
> I just wanted to make sure I understand what we are trying to achieve. My understanding is that we are not trying to override global desktop notifications setting, only allow users to select custom channel notification sound when global notifications allow it.
> While testing, I noticed that turning channel level notification sound ON will not persist when global notification sound is OFF, and vice versa.
> To avoid confusion, I would suggest it's best to hide channel level notification preference for sound when global setting for desktop notifications sound is Off. Unless we are decoupling channel level notification sound setting from global notification sound in which case this is not working as expected.

@jgilliam17 the channel level notifications are intended to be an override of the global settings. If untouched, they stay linked to the global settings. However, if a user decides to change their settings at the channel level, it overrides the global setting. That's actually how the settings work today. For example, if my global setting is set to 'Never' for desktop notifications, I can still override the notifications at the channel level and set to 'For all activity' for that channel.

cc @esethna

**Comment by jgilliam17** [comment]
> > 1. After checking global setting, I realized that modal is displaying sound `default` label for what user has selected on global desktop notifications. I don't think that this is the right approach and we should keep `Bing` as channel level sound default regardless of global preference for sound. We should not pull this info from global preferences each time it is updated.

> @jgilliam17 this is actually working as it should. If you change the global default sound, that should be reflected as the default sound in the channel notification options.

@matthewbirtch This is what threw me off. Maybe had I tested with only one user, I don't think I would have gone down this path. 🙂 
While testing, with 3 different users I observed different sounds with default label, it felt off. 
In my mind, default connotes constant, preselected value, not specified by the user, one where "reset to default" button would return to or if all else fails system would reset to.

One example: When I turn global desktop notifications Off, set to Never, I can see channel level sound notification with default value e.g. Crackle(default)  
In this case, the value I am seeing would have been the last saved sound, before Never was selected and not actual current user set , as  "Never" does not include sound selection. Default label was still shown on channel level sound selector appearing to indicate reset would return to this default sound.

I am definitely making this too complicated  🙃 
I'll move this conversation out of this PR to unblock it and maybe continue in channel or when we tackle work on notifications in the future.

**Comment by jgilliam17** [comment]
For 2. I'll wait for Eric to share thoughts 
Based on the steps I shared and Matt's comment I should be able to override global sound setting where sound is set to OFF, by selecting custom sound for channel notifications, but it continues to fail for me.
I suspect this is happening because I am keeping `Only for mentions(default)` selected which in turn is preventing channel sound from overriding global notifications.
Per help text 
`Selecting an option other than the "default" will override the global notification settings. Desktop notifications are available on Firefox, Safari, and Chrome.`
Does this mean that keeping the default selection will not override global settings? This is possibly why my changes to channel notification sound are not persisting after refresh.

**Comment by esethna** [comment]
@jgilliam17 Sounds like a bug. Whatever is selected in the channel notification settings should be the behaviour of the channel
. If "reset to default" is selected, then it stays in sync with whatever is set in account settings (even if account settings are changed)

**Review by esethna — CHANGES_REQUESTED** [review]
To avoid confusion, perhaps we should remove the "(default)" labelling on the radio button options and in the sound selector dropdown. 

Functionally, defaults from global account settings stay in sync only when the user selects "reset to defaults" (or if they've never adjusted channel notification preferences before). Otherwise any selections in the channel notification preferences act as overrides and are no longer "linked" to the global account setting notification preferences.

**Comment by esethna** [comment]
@kyeongsoosoo can you help look into the above ^? Thanks so much for the contribution!

**Comment by kyeongsoosoo** [comment]
@esethna I'll take a look this weekend!

**Comment by kyeongsoosoo** [comment]
> Steps to reproduce:
Set global notification sound setting to Off
Navigate to channel and open channel level notification settings
Keep "Only for mentions" default selected
Select On for Notification Sound
Save
Refresh using cmd+r
Receive mention in channel
Open channel level Notification Preferences
Observed: Sound did not play when channel mention was received, channel level setting is Off in preferences
Expected: Since option is present to customize sound per channel, I expected sound to play for channel level mentions regardless of global setting.

@jgilliam17  In the process of following the steps to reproduce, I met the following [error message](https://goo.gl/xX8pDD).
스크린샷 2023-02-05 오후 7 55 48


Could you check if the reason why it wasn't possible is related to this?
If there was no such error, it seemed to work properly.

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Comment by kyeongsoosoo** [comment]
@stevemudie There was only qa stage left for this PR, so if I open the PR again, should I ask you for a review?

**Pull request closed without merging**
