### PR TITLE
MM-49474 - Collect Reason for Downgrade to Free

### PR DESCRIPTION
**Pull request by ConorMacpherson**
#### Summary

When a workspace downgrades from Cloud Professional to Cloud Free self-serve, we currently do not have insights as to why they downgraded. This is useful insight that we should be collecting.

With these changes, users can choose answers via a dropdown, as well as leave additional comments
Reason for downgrade:
- `Experienced technical issues`
- `No longer need Cloud Professional features`
- `Exploring other solutions`
- `Too expensive`

In the options, if the user chooses `Other`, the comment text box becomes mandatory
Once completed, the downgrade should be fulfilled immediately.

#### Ticket Link

[MM-49474](https://mattermost.atlassian.net/browse/MM-49474)

#### Screenshots

**Downgrade feedback no additional action required**

https://user-images.githubusercontent.com/116016004/213802662-bb98ba6c-e922-4525-8dce-6811a94467ac.mov

**Downgrade Feedback with team selection**

https://user-images.githubusercontent.com/116016004/213802349-b5689213-677d-48e0-8d61-057534b8f308.mov

#### Test Plan

**Happy Path 1 - Non "other" feedback**
1. Ensure you are on a monthly cloud professional license and can downgrade to starter.
2. In Mattermost, navigate to  the subscription subsection under `Billing & Account` in the system console.
3. Click `View Plans`.
4. Click the `Downgrade` option on the free plan.
5. A feedback modal should appear.
6. Click any reason except for "other".
7. Notice you can click the submit button without providing any additional comments in the text box.
8. Once submitted, the downgrade should happen immediately if no other actions need to be taken.

**Happy Path 2 - "Other" feedback**
1. Ensure you are on a monthly cloud professional license and can downgrade to a starter.
2. In Mattermost, navigate to the subscription subsection under `Billing & Account` in the system console.
3. Click `View Plans`.
4. Click the `Downgrade` option on the free plan.
5. A feedback modal should appear.
6. Click the "Other" reason.
7. Notice you cannot submit the feedback without providing any additional comments.
8. Provide some more comments in the text box.
9. Notice you can click the submit button after providing additional comments.
10. Once submitted, the downgrade should happen immediately if no other actions need to be taken.

**Happy Path 3 - Feedback after choosing team** 

1. Ensure you have at least 2 teams set up in your workspace.
2. Follow the regular downgrade process, this time selecting the team you'd like to keep
3. Notice the downgrade feedback modal appears after the team selection modal has been closed.
4. Select your reason and submit.
5. Once submitted, the downgrade should happen immediately if no other action needs to be taken.

#### Release Note

```release-note
Adds a feedback survey during the downgrade process
```

[MM-49474]: https://mattermost.atlassian.net/browse/MM-49474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ConorMacpherson** [comment]
Had a PR with the same changes up and full approval recently, but it was parked to avoid conflicts with another higher-priority feature. 

This uses the generic feedback modal introduced in the workspace deletion feature (which was built from parts of the aforementioned PR) and has the exact same functionality as before.

**Review by neallred — APPROVED** [review]
S(till)LGTM, thanks @ConorMacpherson !

**Review by nickmisasi — COMMENTED** [review]
LGTM but will comment so I can do a quick check before merge after conflicts resolved

**Review by nickmisasi — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
Hi @ConorMacpherson ,
- on the spin wick, if we downgrade from Professional, we see the Error screen/failure screen, but then again after reloading, the we can see the instance is now 'Cloud Free'.

- The delete workspace is not occurring, I was wondering if there's any setting we might need to do.

**Comment by ConorMacpherson** [comment]
Hey @yasserfaraazkhan 

> on the spin wick, if we downgrade from Professional, we see the Error screen/failure screen, but then again after reloading, the we can see the instance is now 'Cloud Free'.

I'm seeing another failure when changing plans on this spinwick server. I just tried to upgrade from cloud free to cloud professional (via the pricing modal), but it fails every time with an error stating:

`Received status code 400 from CWS while changing subscription plan`

I wonder if this issue is related. In any case, I'm seeing this with downgrades as well, but in some cases, I have to attempt to downgrade twice before this occurs. I'm going to try and hunt down some logs to check the changes we made in the back-end a while back for this. I'll update you with my findings here.

> The delete workspace is not occurring, I was wondering if there's any setting we might need to do.

Delete workspace is unrelated to these changes. That being said, the back-end is not merged yet (mm-server, enterprise and cws changes), so I don't think we'll see that working just yet. It's not scheduled for release until 7.9/march in any case.

**Comment by ConorMacpherson** [comment]
@yasserfaraazkhan I'm currently waiting to hear back from Security to get me access to the logs for these test servers.
Here are some things I've been noticing though:

- The issue is coming from CWS. The only change related to this has been pushed a while back, and we are still able to see the subscription changes succeed in most cases (aside from the issues reported here).
- CWS is giving us a 400 response (bad request), any time the subscription change fails
  - I'm not sure why this is a bad request, I would imagine more of a 500 internal server error, but that's okay.
  - Looking through the code changes related to the feedback, I don't see anything that would result in the failure caused by the feedback data.
    - The feedback data may or may not be present, we check this.
    - The feedback data is only used when downgrading to a freemium product (we also check this).

Once I get more visibility in the logs, I think I'll be able to diagnose this issue a lot better, but I'm confident these changes are not causing this, especially after testing on:
- This spinwick test server:
  - Testing Upgrade to professional path (this is also failing)
  - Manually moving the subscription product from Cloud Free to Cloud Professional (monthly), and trying to downgrade (obviously fails)
- In my Local env
  - Downgrading with the feedback. As usual, in my local environment, I have to send subscription change requests twice. The first time fails (due the cluster installation not being found, which I think is expected locally) and when I send it again, it fails once more but only because the subscription has already been changed in the last request (I see: `Subscription is already on the requested plan prod_LSBESgGXq9KlLj, doing nothing`) and everything is updated once I refresh. This is how I've always had to downgrade or upgrade.
- On a test server spun up via the test portal (which does not have these changes)
  - I cannot for the life of me upgrade my subscription without it failing. I always have to change it manually in stripe.
  - Upgrades are giving me the same, a 400 response from CWS, resulting in a failure and early exist/response in mm-server
  - This server has the delete workspace modal with the option to downgrade from the modal. I'm seeing the same thing here when I try to change my subscription.
- Just to be extra sure, I made a brand new workspace from the test portal (the other one I used was made fairly recently but maybe a few changes behind)
  - The exact same thing happens here for me that happened in the other workspace from the test portal.  

Since we don't know the cause of this issue, I think we should hold off on any kind of testing for this, but it seems like there is something going on with the subscription change endpoints.

**Comment by ConorMacpherson** [comment]
@yasserfaraazkhan I think we may have to test this in post-merge.

This flow can only be accessed when a monthly subscription is present. In the past I had been modifying a stripe subscription's product manually to make it a pro monthly subscription, but apparently there is more to this than just modifying it in stripe.

Nick shared a curl command with me that will create a new workspace with a pro monthly subscription setup:

```
curl --location --request POST 'https://api.internal.test.cloud.mattermost.com/api/v1/internal/installation/with_test_clock' \
--header 'Content-Type: application/json' \
--data-raw '{
    "workspace_name": "new_name",
    "workspace_admin_password": "admin_password",
    "use_test_clock": true,
    "product_id": "prod_K0AxuWCDoDD9Qq"
}'
```

I think we can use this to test unless you know of another option.

**Pull request merged**
