### PR TITLE
MM-44836 : Remove getLastPostPerChannel selector

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
`channel.last_post_at` have been updated consistently on new messages. So now we can fall back on these values instead of `getLastPostPerChannel` selector which internally relied on all post.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44846

#### Related Pull Requests
N/A

#### Screenshots
N/A

#### Release Note

```release-note
Removed getLastPostPerChannel selector for improved performance in channel sorting.
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]
LGTM!

**Review by jgilliam17 — APPROVED** [review]
Thanks @M-ZubairAhmed 
Tested, looks good to merge.
- Verified channel sorting - as before
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/213651-800080a-onprem-ent-webapp-pr-10659-mattermost/mm-ee-test800080a/mochawesome.html)looks good, no PR related failures.

**Pull request merged**
