### PR TITLE
Update profile picture help text.

### PR DESCRIPTION
**Pull request by herooftimeandspace**
#### Summary
Appends the text "Maximum file size 15 MB." to the help text for uploading profile pictures.
screenshot from 2018-07-09 16-22-12

#### Ticket Link
None

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
  - Tests:       10 skipped, 1190 passed, 1200 total
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by herooftimeandspace** [comment]
Thanks for the feedback. I'll update the changes to i8n & run build tests once I've sorted out the `MaxFileSize` thing.

**Comment by herooftimeandspace** [comment]
#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `npm test -- -u` to update snapshots
  - › 7 snapshots updated from 1 test suite.
  - Test Suites: 203 passed, 203 total
  - Tests:       10 skipped, 1223 passed, 1233 total
  - Snapshots:   7 updated, 607 passed, 614 total
  - Time:        42.211s
  - Ran all test suites.
- [x] Ran `make test` to ensure unit and component tests passed
  - Test Suites: 203 passed, 203 total
  - Tests:       10 skipped, 1223 passed, 1233 total
  - Snapshots:   614 passed, 614 total
  - Time:        24.442s, estimated 38s
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

**Comment by herooftimeandspace** [comment]
I accidentally deleted `package-lock.json`. I was trying to just not stage it. I apologize for the many, many mistakes. Trying to get a handle on this whole git thing. As soon™ as I figure out how to revert that change, I'll commit it.

**Comment by saturninoabril** [comment]
@wiersgallak 
This is ready to merge but I don't see a ticket or PM approval yet for this.  May I request for PM review and approval before merging this.  Thanks!

**Comment by wiersgallak** [comment]
I see the MaxFileSize on the image upload help text is 50 MB on this server currently.  @saturninoabril Can you please confirm that is correct and adjust the MaxFileSize in config.jsn to a different threshold so that I can verify the value changes?

**Comment by saturninoabril** [comment]
That's correct.  When logged in as sysadmin, you can change the setting via System Console > Files > Storage > Maximum File Size.

**Comment by wiersgallak** [comment]
Thanks for confirming @saturninoabril looks good from my perspective.  Thank you for adding this for us @herooftimeandspace!

**Pull request merged**
