### PR TITLE
Issue  7786 new

### PR DESCRIPTION
**Pull request by panditsavitags**
#### Summary
Migrate delete_emoji_modal.jsx to pure and to use redux

Ticket Link
[issue_7786](https://github.com/mattermost/mattermost-server/issues/7786)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [x] Has redux changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by panditsavitags** [comment]
@saturninoabril , Please review this pull request

**Comment by saturninoabril** [comment]
@panditsavitags The changes looks good to me except for those unrelated commits that needs to remove. Just a few questions on your git workflow:
- Do you have your upstream (remote) setup and pointed to `mattermost/mattermost-webapp` repo?
- Did you fetch latest master from upstream (`git fetch upstream`) and merged it to your master (`git merge upstream/master`) before you created your branch (`git checkout -b GH-7786`)?
- When doing a rebase of your branch, do usually fetch latest, merge to your master and then do the rebase (`git rebase master`)?

**Comment by panditsavitags** [comment]
@saturninoabril , 

- Do you have your upstream (remote) setup and pointed to mattermost/mattermost-webapp repo?
  - Yes
- Did you fetch latest master from upstream (git fetch upstream) and merged it to your master (git merge upstream/master) before you created your branch (git checkout -b GH-7786)?
  - Yes
- When doing a rebase of your branch, do usually fetch latest, merge to your master and then do the rebase (git rebase master)?
   -Yes

**Comment by jwilander** [comment]
@panditsavitags would you mind giving this a quick rebase? Then I can merge it

**Comment by panditsavitags** [comment]
@jwilander , Please merge this PR

**Pull request merged**
