### PR TITLE
GH-20109 : Fix sass Slash as Division deprecated

### PR DESCRIPTION
**Pull request by jbattistispiria**
#### Summary
Fix sass deprecated warning when running `make run`.

Run:
```
$ npm install -g sass-migrator
$ sass-migrator division **/*.scss
```

#### Ticket Link
Fix https://github.com/mattermost/mattermost-server/issues/20109

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Really appreciate for fixing this 😄

**Comment by M-ZubairAhmed** [comment]
@jgilliam17 please just do a smoke test keeping in mind the font sizes in some places around the app.

**Review by larkox — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks for that fix! I didn't realize it would be that easy to fix that warning since I assumed it was caused by some ancient dependency that I was afraid to update 😛

**Comment by jgilliam17** [comment]
Thanks @jbattistispiria 
Tested, looks good to merge.
-Verified font size in the app - no issues
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/196726-f0889ae-onprem-ent-webapp-pr-10254-mm-ee-test:f0889ae/mochawesome.html), no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
