### PR TITLE
(WIP) Fixes MM-13497 : Migrate 'components/admin_console/license_settings' module and associated tests to TypeScript

### LINKED ISSUE #13497: Migrate 'components/admin_console/license_settings' module and associated tests to TypeScript
We are starting to migrate the mattermost-webapp over to TypeScript to facilitate better code quality. This `Help Wanted` issue is to modify all files in `components/admin*console/license*settings` (not sub-directories included) and associated test files.

Below is a checklist of items you should be doing to migrate:

- < ] Rename the files to their associated TypeScript extensions (ie. `js` to `ts`, `jsx` to `tsx`)
- [ ] Update any components using those to the correct imports
- [ > Fix any errors generated by the TypeScript compiler. You can run `make check-types` to display any errors.

We are aiming to be as strict as possible for the time being, but if you run into any issues where the file cannot be successfully migrated without significant change in other libraries, or our `tsconfig.json`, please feel free to raise them as we are aiming to keep this process smooth and gradual, while enforcing as much as we can.

Some examples of already migrated files can be found here:

- https://github.com/mattermost/mattermost-webapp/pull/3790
- https://github.com/mattermost/mattermost-webapp/pull/3472
- https://github.com/mattermost/mattermost-webapp/pull/4230

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-20575

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary

WIP 🚧 : Attempt to migrate files under `components/admin_console` to typescript.

#### Ticket Link

GH : Fixes https://github.com/mattermost/mattermost-server/issues/13497
JIRA: https://mattermost.atlassian.net/browse/MM-20575

#### Related Pull Requests
none

#### Screenshots
none

### CODE REVIEW

**Comment by jfrerich** [comment]
Hello again, @M-ZubairAhmed!  I hope you've been well!  I have added reviewers to your Draft PR.  Could you communicate what you expect is needed to push from Draft to formal PR?

**Comment by M-ZubairAhmed** [comment]
@jfrerich i am good thank you Jason. Actually this was part of the live stream i am doing, i was showing live how to pick up a MM issue, figure it out and work on it.  I ended the live stream because i streched more than 2 hours (unfortunately it wasnt recorded :-( ) i will complete the remaining pr shortly.

**Comment by jfrerich** [comment]
Thanks @M-ZubairAhmed!  I cleared our reviewers but will add them back when your PR is ready for review.  Thanks for another PR!

**Comment by devinbinnie** [comment]
Closing this PR as inactive, @M-ZubairAhmed, let us know if you plan on finishing this up.

**Pull request closed without merging**
