### PR TITLE
MM-47666 Add ability to run Cypress tests in GitHub CI for benchmarking

### PR DESCRIPTION
**Pull request by hmhealey**
We can use this to run whatever Cypress tests we want for benchmarking web app PRs once we decide how those tests should work.

For now, assuming this works how I want, it should be run on every PR commit and on every commit to master or a release branch. It runs the tests against the previously built server compiled by CircleCI, so it has to wait for that to finish before running. This does add a couple minutes to the CI cycle even with the quick test I picked as an example, but that seems like the best I could do for now because I couldn't figure out how to make it wait for the specific `ci/circleci: prepare-docker-build` step to complete, but I think that's fine to avoid duplicating that CI flow on here.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47666

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by nevyangelova** [comment]
https://github.com/mattermost/mattermost-webapp/actions/runs/3441113396/jobs/5740315665 BEAUTIFUL! @hmhealey

**Review by larkox — APPROVED** [review]
Not really proficient on this part of the code, but with my limited knowledge... LGTM :smile:

**Review by nevyangelova — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks @hmhealey, LGTM! I'm requesting review with Mario.

**Review by mvitale1989 — APPROVED** [review]
I'm not very familiar with GH actions either, but afaict this looks good to me as well! Thanks @hmhealey

**Pull request merged**
