### PR TITLE
MM-43933 Avoid hints overlap suggestions in searchbox

### PR DESCRIPTION
**Pull request by anler**
#### Summary

This PR is trying to address issue [mattermost-server/#20127](https://github.com/mattermost/mattermost-server/issues/20127) which is causing the hints modal overlap the auto-suggestion ones.

The solution I have opted for is try to better detect whether one modal should be shown or the other.

The heuristic works as follows:

> If the text cursor is not at the end of the search term in the search input, and the character before is not a blank, then avoid displaying the hints modal as there's probably an auto-suggestion modal being displayed.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/20127
Fixes https://mattermost.atlassian.net/browse/MM-43933

#### Screenshots

https://user-images.githubusercontent.com/83847/167301089-630da780-5cdc-4043-997b-f2c331a6a1de.mp4

#### Release Note
```release-note
Prevent search hints from overlapping search autocomplete
```

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thank you @anler 
Tested, looks good to merge.
- Verified autocomplete behavior in search no longer hidden by hints.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/199143-61e2435-onprem-ent-webapp-pr-10284-mm-ee-test:61e2435/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR! I'm actually noticing causes the search hint to be displayed if you have a space between the search flag (eg. `in:`) and the text you're typing.

Current:
https://user-images.githubusercontent.com/3277310/171433513-b103efb9-8842-42cd-aa8a-aa1e28978bbe.mov

With this PR:
https://user-images.githubusercontent.com/3277310/171433581-86feb5b4-be33-4691-8552-2ba675115da8.mov

I like the idea of something simpler like checking for a blank before the cursor, but that unfortunately doesn't work when spaces are allowed after the flag. I'm not actually sure how the previous version of the code handled this either though

**Comment by anler** [comment]
Hi @hmhealey 

I've been thinking about this 🤔

The issue with my heuristic is that we don't know if the space character before the cursor marks the end of the search flag or is it still part of its input.

So possible solutions I can think of:

- Keep stretching my heuristic and consider leading whitespace in the search flag as input
- Change how autosuggestions and hints are displayed altogether and show them inside the same dropdown instead of separated: hints will always be visible in one column and autosuggestions will appear in another column if there are any

**Comment by hmhealey** [comment]
Also, linking this here since it could end up being relevant, but we have a ticket open which will allow spaces in search flags at some point, so that'll require more changes to this logic. I don't think this PR has to support that logic though

https://github.com/mattermost/mattermost-server/issues/16242

**Comment by hmhealey** [comment]
Hi @anler. Are you still working on this? Is there anything we could help with on it?

**Comment by anler** [comment]
@hmhealey I’m on holidays for a couple of weeks, will take a look asap when I’m back (I have no computer with me unfortunately)

**Comment by hmhealey** [comment]
Thanks for putting in more work on this! Always nice to see a PR revived after some time 🙂 

Let me know when you want me to review it again so that I don't miss that by mistake

**Comment by anler** [comment]
Yeah @hmhealey I've been quite busy and finding time for this is hard but I want to see it done! Let me fix the linter errors and make sure everything is good and I'll ask you to review it again :)

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
