### PR TITLE
bugfix: Hide HistoryButtons in browser

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
Added a condition that only renders the HistoryButton sub-component when in the Desktop App

#### Ticket Link
[MM-37829](https://mattermost.atlassian.net/browse/MM-37829)

#### Release note
```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
LGTM! Just in case did you do a reverse flip of the condition to make sure the arrows behave correctly on desktop when header is on/off?

**Comment by michelengelen** [comment]
> LGTM! Just in case did you do a reverse flip of the condition to make sure the arrows behave correctly on desktop when header is on/off?

reverse flip? Do you mean a `double negation` (`!!`)?

**Review by crspeller — COMMENTED** [review]
There is already commented out logic to do this within the history buttons component. You should probably clean that up as part of this PR?

**Comment by michelengelen** [comment]
@michaelgamble and @jgilliam17 gentle reminder to review.

**Review by crspeller — APPROVED** [review]

**Review by michaelgamble — APPROVED** [review]
This looks good to me

**Comment by michelengelen** [comment]
@jgilliam17 I have merged master manually

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified history buttons are hidden on the browser; still present on the desktop app as part of the global header.

**Pull request merged**
