### PR TITLE
Try to get expanded URL from store

### PR DESCRIPTION
**Pull request by Robbe7730**
#### Summary
This adds the functionality of [mattermost-mobile#2538](https://github.com/mattermost/mattermost-mobile/pull/2538), namely that it tries to get the expanded URL from the state of it exists.

#### Ticket Link
https://github.com/mattermost/mattermost-mobile/issues/2507
https://mattermost.atlassian.net/browse/MM-14011

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Needs to be implemented in mobile (https://github.com/mattermost/mattermost-mobile/pull/2538)
- [x] Has redux changes (https://github.com/mattermost/mattermost-redux/pull/760)

### CODE REVIEW

**Comment by esethna** [comment]
@hmhealey what is the best way to test this?

**Comment by hmhealey** [comment]
@esethna There's two things to test: that shortened links still show previews (there's one you can use in [this ticket](https://mattermost.atlassian.net/browse/MM-13356)) and that expanded URLs are only requested from the server once since that's the new behaviour. If you open the dev tools to the Network tab and view a post containing a link, you'll see a request to the server at `/api/v4/redirect_location?url=<the encoded link>`. If you switch channels away and back (without refreshing), you shouldn't see a second request to that same URL. Previously, the client would make that request each time it viewed a post

**Comment by esethna** [comment]
@Robbe7730 looks like a build error if you can take a look?

**Comment by hanzei** [comment]
Hey @Robbe7730,

I just want to check out if you need help with fixing the build error? Could you also please merge `master` into your branch?

**Comment by Robbe7730** [comment]
@hanzei sorry for not responding, I'll look into it. There seems to be a problem with the loading of images, however I do not know why that happens.

**Comment by hanzei** [comment]
Hey @Robbe7730,
Thanks for the reply. Feel free to ask for help in the [~Developers channel](https://community.mattermost.com/core/channels/developers) on the Mattermost Community Server.

**Comment by amyblais** [comment]
@hmhealey Looks like this doesn't make it for today's Feature Complete. Is the redux PR going to cause any issues as it's already merged to master without this PR?

**Comment by hmhealey** [comment]
@amyblais Sorry, this is a bit late, but no, it won't. It adds new functionality, but that's just not used by either app.

**Comment by jasonblais** [comment]
Hey @Robbe7730 - let us know if we can help troubleshoot the issue with loading of images, happy to help!

**Comment by Robbe7730** [comment]
Sorry for remaining quiet for so long. I've been extra busy with my studies lately. I do however want to finish this as soon as I find the time, hopefully later this week. Thanks for all the help anyway!

**Comment by jasonblais** [comment]
Thanks @Robbe7730, great to hear! Really appreciate it. Hopefully your studies have been going well :)

**Comment by hmhealey** [comment]
Actually, this PR might not be needed any more. The post metadata feature that was added a while has now stabilized to the point where we're actually removing all usage of `getRedirectLocation` from the web app ([link](https://github.com/mattermost/mattermost-webapp/pull/2638)), so we won't need to worry about excessive API calls from it any more. We do definitely appreciate the work on this though.

**Comment by jasonblais** [comment]
@hmhealey I see. Would the same apply for mobile? https://github.com/mattermost/mattermost-mobile/pull/2538

**Comment by hmhealey** [comment]
I'll check. I feel like mobile may be a bit behind with these changes. It'll likely apply as long as you're connecting to a server with post metadata since it still needs to be compatible with the 4.10 ESR

**Comment by hmhealey** [comment]
Hi @Robbe7730,

Thanks for all the work you put into this, but this won't be needed any more since we've been removing all of the calls to `getRedirectLocation` from the app.

**Pull request closed without merging**
