### PR TITLE
[MM-17406] Fixed channel switcher setting so that it shows the real setting on exit

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
While testing MM-17406, an issue was found where the incorrect variable was being used to show the saved state of the Channel Switcher setting when the setting was closed. This PR fixes that.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-17406

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @devinbinnie,

Tested the specific issue found while testing [MM-17406](https://mattermost.atlassian.net/browse/MM-17406?focusedCommentId=67347&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-67347) and this is fixed.

However, I'm seeing a similar issue when:
1. Main Menu >Account Settings > Sidebar 
2. Click "edit" to the right of Automatically Close Direct Messages (should be set to "After 7 days with no new messages")
3. Change the setting to "Never" but _don't click Save_
4. Press SHIFT+TAB to set focus on the "Edit" button for Channel Switcher, then hit Enter

Observed: 
The setting you changed in 3) above is saved
Expected:
The setting you changed in 3) above is not saved

Can you take a look on the spinwick please?

**Comment by devinbinnie** [comment]
@lindy65 Yep I'm seeing that issue as well. It might be worth creating a separate ticket for these issues, because it's starting to sound like there's a lot of them. Probably all the same fix however.

**Comment by lindy65** [comment]
Hey @devinbinnie - It's mentioned in the description of MM-17406 that this is a global issue across Account Settings so I'm not sure that creating a new ticket is the way to go...

Perhaps if time is short for 5.15, we can reschedule this ticket for 5.17 (as the behavior is not a regression) and continue work later? My thoughts are that there is not much point in fixing only one issue in 5.15 and having tickets to fix the rest in a later release.  

If your suspicions are correct and it is all the same fix, it might make sense to do them all in one PR...

**Comment by devinbinnie** [comment]
@lindy65 That's true, but the issue you're seeing is a visual bug and is only affecting radio buttons/checkboxes, so it is technically separate from the bug that was reported. I only made this fix because I thought it was the only one, but from your further testing it sounds like it's more prevalent that I'd expected.

I'll leave it up to you of course, but I don't think we should fail MM-17406 on testing based on this visual issue. Let me know your thoughts :)

**Pull request merged**
