### PR TITLE
MM-18759 - Floating timestamp in mobile view

### PR DESCRIPTION
**Pull request by Jonany**
#### Summary
Tested that floating date indicator changes the date to reflect the messages being viewed

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12324

### CODE REVIEW

**Comment by saturninoabril** [comment]
@Jonany Let me know if this is ready for review.

**Comment by Jonany** [comment]
It's close. I have it generating a block of ten messages for three
different days. Right now, I'm working on scrolling to the middle of each
block so I can check the timestamp. Any suggestions on how to do that would
be helpful :)

**Comment by saturninoabril** [comment]
@Jonany Sure, will just do some release testing and then will look into it.

**Comment by jasonblais** [comment]
cc @saturninoabril quick reminder once new releases are published to help take a look at this PR :)

**Comment by saturninoabril** [comment]
@Jonany sorry for this as I didn't had a chance to look on it.  Feel free to close.  I'll probably look into it once I get a chance.

**Comment by saturninoabril** [comment]
Closing this.  Another community member grabbed it.

**Pull request closed without merging**
