### PR TITLE
translations PR 20190916

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by jasonblais** [comment]
@enahum @amyblais Were these supposed to ship with 5.15?

**Comment by amyblais** [comment]
Do we submit these manually earlier in the future?

**Comment by jasonblais** [comment]
@amyblais Yeah, we should submit the last translations PR around or after [T-7](https://docs.mattermost.com/process/feature-release.html#i-t-minus-7-working-days-release-candidate-testing-finished), which can be manual if the Monday's PR is too late

**Comment by amyblais** [comment]
Noted, last week Monday was T-5.

**Pull request closed without merging**
