### PR TITLE
MM-29670 - Hide payment screen in system Console if in free tier

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
* Hides payment screen for free tier

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-29670

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks Ali! 🎉

**Review by nickmisasi — APPROVED** [review]
LGTM 🎉

**Comment by marianunez** [comment]
Will be tested after merge

**Pull request merged**
