### PR TITLE
MM-22249 : Add automatic lazy loading of syntax highlighting libraries

### LINKED ISSUE #14029: Add automatic lazy loading of syntax highlighting libraries
Currently, all of the supported syntax highlighting languages are manually included as part of JS bundle for the web app. If we were to lazy load those, it would reduce the size of the initial JS bundle, and it would allow us to enable all languages supported by highlight.js instead of the subset that we've decided to support.

For example, if a user posts Java code, the part of highlight.js that handles Java should be loaded.

Some links that may be helpful for this are:
- https://github.com/mattermost/mattermost-webapp/blob/master/utils/syntax_highlighting.tsx - This is where the supported languages are loaded into the app
- https://github.com/mattermost/mattermost-webapp/blob/master/components/latex_block/latex_block.jsx - This component lazily loads the library for formatting Latex. We might be able to use similar code for this.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-22249

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary

- Added dynamic require and register of languages in hightlight js

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/14029
JIRA https://mattermost.atlassian.net/browse/MM-22249

#### Related Pull Requests
none

#### Screenshots
none

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
Hi Team , please take a look at my implementation and let me know if it works for you. I have tested it , does seem to work but obviously i could have missed some details.

I could not use dynamic import as they return promise and we need to pass it all the way to the marked library, the overloading function `code` properties does not match promises. So i tried that approach but had to abandon due to those problems of resolving promise.

Let me know your suggestion and thoughts so i can continue work on this.

**Comment by hanzei** [comment]
Hi @M-ZubairAhmed, thanks you very much for the PR. Could you please resolve the linter issues? https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/21233/workflows/52739f53-d1a4-41ff-9eaf-587d9a6bf111/jobs/134271

I will queue the PR for early dev review anyway.

**Comment by M-ZubairAhmed** [comment]
@hanzei i plan to clear all the types, lint errors after i complete the PR. i first would like to see if this is the approach the team want to solve the problem.

So i used require because is sync and not import as it is async

**Comment by cpanato** [comment]
test server removed due some underlying issues in the cluster that made this one unstable.

**Comment by M-ZubairAhmed** [comment]
Will continue after the Hackathon

**Comment by hanzei** [comment]
@M-ZubairAhmed Just want to touch bases: Are you planing to work on this PR?

**Comment by M-ZubairAhmed** [comment]
@hanzei yes i will, will discuss with @sudheerDev and @hmhealey

**Comment by M-ZubairAhmed** [comment]
Closing this and will reopen when i can be able to work on it

**Pull request closed without merging**
