### PR TITLE
MM-13342: Fix dividers showing when menu section is empty.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
Fix dividers showing when menu section is empty.

This fix is a little ugly - it checks the children-of-children are not
null to work around connected components themselves not being null but
having the actual component within being null.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-13342

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by hmhealey** [comment]
If you're wanting to avoid adding that extra introspection, perhaps we could actually fix this using CSS? If you look [here](https://github.com/mattermost/mattermost-webapp/blob/master/sass/layout/_headers.scss#L460), we already use `.divider + .divider` to hide the dividers for empty sections other than the first, so we can add `.divider:firstChild` to hide that first one as well.

**Comment by grundleborg** [comment]
I don't think that will work, as we're not successfully hiding *any* of the dividers currently with the CSS. This fix targets *all* the unnecessary ones, not just the first one. Then again my CSS-foo isn't great so maybe I'm misunderstanding it?

**Comment by grundleborg** [comment]
Sigh. Looks like this was a duplicate ticket anyway and Asaad has fixed it here https://github.com/mattermost/mattermost-webapp/pull/2152

**Comment by hmhealey** [comment]
I've merged and cherry picked that PR, so we could test again now to see if it's still an issue

**Comment by grundleborg** [comment]
Looks fixed to me now with Asaad's changes. Closing this PR.

**Pull request closed without merging**
