### PR TITLE
[MM-29391] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 513 (#15830)

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 513

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15830
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29391

### CODE REVIEW

**Comment by deanwhillier** [comment]
QA review will be done on the final PR that merges all changes to this campaign branch into master.

**Review by sudheerDev — APPROVED** [review]

**Comment by sudheerDev** [comment]
@KuSh Thank you!

**Comment by deanwhillier** [comment]
This PR will be QA'd when merging from campaign branch to master.

**Review by deanwhillier — APPROVED** [review]
LGTM, thanks @KuSh!

**Pull request merged**
