### PR TITLE
MM-30381/cypress notifications teammate name MM-T488

### PR DESCRIPTION
**Pull request by nronas**
#### Summary
Automates MM-T488 as shown in https://mattermost.atlassian.net/browse/MM-30381

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30381

*NOTE* 2 more PRs will follow for the remaining test cases

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Review by furqanmlk — APPROVED** [review]
All test cases are passed

**Review by lindy65 — APPROVED** [review]
Thanks @nronas - looks good to me 👍

**Pull request merged**
