### PR TITLE
Fixed custom status issues

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary

- Fixed MM-35924 Custom status emoji is undersized and misaligned in the RHS
- Fixed MM-36026 "Update your status" is showing an all users posts instead of just the current user

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-35924
- https://mattermost.atlassian.net/browse/MM-36026

#### Release Note

```release-note
Fixed MM-35924 and MM-36026 issues
```

### CODE REVIEW

**Review by chetanyakan — APPROVED** [review]

**Comment by amyblais** [comment]
@koox00 @ogi-m Assigned this to you in case we can get this is in for tomorrow's cloud release. Feel free to re-assign reviewers.

**Review by koox00 — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
LGTM
- the emoji are now the same size in the centre pane and RHS
- CTA only show on the user's own posts

**Comment by amyblais** [comment]
@koox00 Perhaps you can help cherry-pick this to the ``cloud`` branch.

**Comment by amyblais** [comment]
@michelengelen @agarciamontoro Random question, would one of you be able to help cherry-pick this to the ``cloud`` branch?

**Comment by koox00** [comment]
@amyblais, I'll do it

**Pull request merged**
