### PR TITLE
Revert "PLT-5574: Left/right/up/down arrows can be used to navigate through the emoji picker"

### PR DESCRIPTION
**Pull request by stephenkiers**
Reverts mattermost/mattermost-webapp#315

Bug fixes and optimizations requested

### CODE REVIEW

**Comment by stephenkiers** [comment]
@jasonblais could you approve this reversion. Then I can re-create the original PR

**Comment by stephenkiers** [comment]
I am not authorized to merge this... I don't think I have any github permissions yet

**Comment by jasonblais** [comment]
@stephenkiers You can then ask someone else to merge for now,

**Comment by stephenkiers** [comment]
@enahum would you mind merging this?

**Comment by enahum** [comment]
Sure once jenkins finishes

**Pull request merged**
