### PR TITLE
Cyperss/E2E:fixed emoji preview  and keyboard accessibility 

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary

Fixed emoji and keyboard accessibility test cases 

#### Screenshots

image

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM

**Review by saturninoabril — APPROVED** [review]
Thanks Malik!

**Comment by saturninoabril** [comment]
I'm merging this now so it'll be included in today's scheduled test run.

**Pull request merged**
