### PR TITLE
MM-9639 Added ability to collapse long posts

### PR DESCRIPTION
**Pull request by hmhealey**
This is a resubmission of the previous PR so that it can be demoed with the newish design.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-9639

#### Checklist
- Has UI changes
- Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by hmhealey** [comment]
@esethna This still has the 200 pixel max height for a post since I wasn't able to find the expected max height in any of the designs I had

**Comment by esethna** [comment]
Thanks Harrison! Few comments:

1. Looks like the "Show More/Less" buttons have a blue outline after being clicked. Can we remove that blue outline and instead add an on hover effect. @michaelgamble any thoughts on the on-hover effect, maybe the drop shadow used for images?

show more


2. Can we try 600 pixels max height?@michaelgamble any thoughts given the current height is 200 pixels on the test server?

3. @hmhealey can we increase the allowable limit to 16k to we can get a better feel for it?

**Comment by michaelgamble** [comment]
UI Review Issues:
- gutter below the show more button should be 10px
- hover state missing (please refer to blue button variant in invision docs)
- show more button > click state currently shows a bright glow > this should be removed
- Padding in show more button should be reduced from 10px to 8px
- post-collapse__show-more-line > opacity should be reduced from 20% to 10%
- Show more button > border opacity should be reduced from 20% to 10%

**Comment by michaelgamble** [comment]
@asaadmahmood  can we add subtle animation transitions?
I'm thinking quick .5 second ease-ins for state changes:
- when the content height changes (expand / collapse)
- hover effect on the show more button

**Comment by hmhealey** [comment]
I've made the requested UI changes except for the transitions which I'll need Asaad's help for. I've also merged in the latest changes from master, so that should increase the post limit.

**Comment by hmhealey** [comment]
@asaadmahmood Are you able to look at the adding the transitions Mike requested? I'm not familiar with how to do that

**Comment by esethna** [comment]
Thanks guys. @hmhealey @asaadmahmood @michaelgamble I'm wondering your thoughts about pinning the "Show Less" button so it's always on screen during scroll. So in the center channel as you are scrolling down the long post the "Show Less" button is pinned just above the text input box. In the RHS might get a bit more complex given the text box isn't always pinned to the bottom, but same principle could apply. I tested with 16k characters and I'm slightly about getting lost in long posts. Open to feedback if you guys give it a go.

**Comment by michaelgamble** [comment]
UI Review Issues:
* The gradient cutting off the bottom of the text seems to abrupt, please adjust to meet designs... feel free to ping me if any questions

Performance Concern:
* When I jump out of the browser, and jump back in to the browser having focus, the channel with show more content seems to lock up the whole app for a few seconds.. something odd is going on their

**Comment by hmhealey** [comment]
@esethna @michaelgamble Here's the updated gradient and Show More/Less button positioning. I'm trying to reproduce the lag you guys reported since I definitely saw it happen before even though I can't repro it currently. It seems to be due to the existence of longer posts rather than the expand/collapse behaviour, but I still need to confirm that

**Comment by hmhealey** [comment]
@esethna How is this version?

**Comment by esethna** [comment]
@hmhealey I'm definitely still noticing a lag in the responsiveness of the UI. To repro try setting your connection speed to slow 3G. For example:

1. Type a long post (~16k), after hitting ENTER there is a lag of about 5-7 seconds before the post appears in the post list and clears the text input box. Then another UI freeze of about 2-3 seconds before the UI is responsive again.
2. On a long post (~16k), hit the reply arrow, observe a UI freeze of about 2-3 seconds before the post opens in the RHS and UI is responsive again
3. Random UI freezes when long posts are being displayed. GIF attached showing how the cursor is frozen and no hover effects being displayed for almost 10 seconds:

freeze

Other than that UI looks good but it's really hard to do a thorough test until we sort out the perf issues

**Comment by esethna** [comment]
Separate PR from HH to address perf issues^ https://github.com/mattermost/mattermost-webapp/pull/1204

Will re-test once that's merged

**Comment by hmhealey** [comment]
@esethna This is ready to test again once the test server comes back up

**Comment by esethna** [comment]
@hmhealey I think I froze the server - maybe crashed it? I posted 16k characters that was just links. Can you look into what's going on, the server won't load for me anymore and my browser just wants to kill it. No console errors.

image

**Comment by michaelgamble** [comment]
screen shot 2018-05-16 at 3 55 31 pm

Encountered this strange issue

**Comment by michaelgamble** [comment]
screen shot 2018-05-17 at 12 26 15 pm

The "Show More" button gradient is still too abrupt when exists as a reply.. please make the same changes to this use case.

**Comment by michaelgamble** [comment]
* Reviewed UI fixes by @hmhealey based on my previous comments - completed and approved
* discussed sticky "Show Less" with @esethna - decision to defer unless needed and will que up designs for approacch
* discussed what triggers long post div max-height vs character count - landed on div max-height

As far as I'm concerned this PR is approved

**Comment by esethna** [comment]
Queued for testing with QA

**Comment by lindalumitchell** [comment]
Trying a new spinmint; the previous one could not be reached (`ERR_CONNECTION_REFUSED`).

**Comment by cpanato** [comment]
I fixed an issue in the spinmint server, now this test server is good to go.

**Comment by lindy65** [comment]
@hmhealey @esethna 

I tested across devices (RN app build 104 on iOS and Android;  Desktop App and Chrome/Win 10 browser) and found the following issues:

1. UI looks broken on searches for pinned / flagged posts in the RHS. (Long post with "Show More" in the center panel shows the last couple of lines greyed out.  In pinned/flagged posts in the RHS, the last couple of lines are not greyed out.) - **(DOES NO REPRO ON iOS/ANDROID RN APP but does on Desktop App/Browser)**

image

2. In direct and group messages, the person making the post does not see "Show More/Less" on their own post but it does show up for other users.  If, however, you open the RHS on this same post, the "Show More/Less" suddenly shows up. - **(DOES NO REPRO ON iOS/ANDROID RN APP but does on Desktop App/Browser)**

Screenshot 1: Post posted by `sysadmin` to `user-1` (and being viewed as `sysadmin` - no "Show More" in center panel
image

Screenshot 2: The same post still being viewed by `sysadmin` after having clicked "reply icon" on the message in the center panel to open the RHS
image

FYI, @lindalumitchell and/or @DHaussermann are still going to do some testing and might find other issues.

**Comment by esethna** [comment]
Thanks guys, good catches. cc// @hmhealey on the above.

**Comment by hmhealey** [comment]
@lindy65 For issue number 2, how wide was your window at the time? It looks like your message may not have been tall enough to cause the post to appear collapsed with the Show More button, but clicking the reply arrow increased the height enough for that to happen

**Comment by hmhealey** [comment]
@DHaussermann Are you sure that isn't just because the first line is a heading so it has a margin before it? I tried to reproduce the issue and it appears the same on the spinmint as this screenshot from pre-release
image

**Comment by DHaussermann** [comment]
Hi @hmhealey , Yes, you're right. After looking at this closer it is unrelated to the expand\collapse and is not specific to this PR.

@esethna, we should still decide if this is worth resolving. I can just create a ticket for it.

**Comment by lindy65** [comment]
@hmhealey - for 2) above, I hadn't changed the width of my screen at all - same width / size as I usually use displaying over my full laptop screen.

**Comment by esethna** [comment]
2) Ya I think this is fine, given the post takes up more vertical room after the reply arrow is clicked, so this pushes it over the trigger limit for long posts.

**Comment by hmhealey** [comment]
@esethna I've fixed the first issue Lindy reported where the fade out was missing in search results, and I went through and double checked that fade out in all other circumstances. As mentioned above, I couldn't repro the other issue

**Pull request merged**
