### PR TITLE
Manual cherry pick of #5385

### PR DESCRIPTION
**Pull request by agarciamontoro**
There were some conflicts, so I needed to do the cherry-picking manually.

### CODE REVIEW

**Comment by agarciamontoro** [comment]
@amyblais, I asked for your review to make sure I didn't do anything wrong with the manual cherry-picking process. Thanks!

**Comment by amyblais** [comment]
@agarciamontoro Process-wise looks good, but I can't comment on the "technical" correctness as I'm not a dev.

**Comment by agarciamontoro** [comment]
I was only concerned about the process. Labels, milestone (which I forgot), all that. Should I add some doc-related labels?

**Comment by amyblais** [comment]
No labels are needed, but I've added "Docs/not needed" and "Changelog/not needed" labels which I normally add as I go through merged PRs.

**Comment by agarciamontoro** [comment]
Thank you very much for your help and for the clarifications, @amyblais! :hugs:

**Pull request merged**
