### PR TITLE
[MM-13663][MM-11504] Adds bi-directional scrolling and use unread API on channel load

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Adds bi-directional scrolling and uses unread API on channel load

#### Ticket Link
[MM-13663](https://mattermost.atlassian.net/browse/MM-13663)
[MM-11504](https://mattermost.atlassian.net/browse/MM-11504)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has redux changes (please link)
- [x] Has UI changes

### CODE REVIEW

**Comment by enahum** [comment]
@amyblais I believe this will be available in 5.10 not 5.8

**Comment by enahum** [comment]
@sudheerDev should we merge this against the feature branch instead of master?

**Comment by sudheerDev** [comment]
Feature branch wasn't updated in a while and there are a lot of merge conflicts so raised another PR and i thought to use this as base for future work.  

I am not really sure on how we should go about this. Should i fix the conflicts of feature branch and raise it against it?

Feature branch has almost same code without auto-load, scroll logic and minor refactors.

**Comment by hanzei** [comment]
Hey @sudheerDev,

Could you please give a quick update on this PR? What is the status?

**Comment by sudheerDev** [comment]
@hanzei We will be working on this sometime this week. This is blocked by https://github.com/mattermost/mattermost-webapp/pull/2447

**Comment by jasonblais** [comment]
@sudheerDev Should I add a `lifecycle:frozen` label to keep the PR open?

**Comment by sudheerDev** [comment]
@jasonblais Done changed the label on this. We mostly will be working in `sprint 60/61`

**Comment by sudheerDev** [comment]
Closing this in favour of https://github.com/mattermost/mattermost-webapp/pull/3049

**Pull request closed without merging**
