### PR TITLE
[MM-29675] - Add sorting for channels in categories

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR adds the sorting option for channels in a category by recency, alphabetically or manual user sorting. There are some styling issues that need to be addressed and a question for UX. @matthewbirtch which icon should we use for Manual sorting? I couldn't find it in the design. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29675

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/7068

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@nevyangelova I've updated the Figma file to use the following icon for sorting manually:
image

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
As you mentioned, there are definitely some styling issues we'll need to resolve:

1. When I hover over the Sort menu option to show the submenu, it displays on top of the parent menu obscuring the options:
image

2. On the Channels category menu, the sort label seems to be center aligned. I'm entirely sure how I got this state, but this is how it initially appeared for me. After I've been testing I can't seem to get back to this state.
image

2. For the sort type label, can we position it down by 1px? It feels slightly high to me

3. I happened to check the Direct Messages menu as well and a similar issue appears there, but on the 'Show' option. I think it might be because there were no direct messages in the list at the time
image

**Comment by nevyangelova** [comment]
Thanks @matthewbirtch  fixed. I cannot repro the bug you saw initially but will keep an eye for it. It might be related to the category sorting redux changes.

**Review by hmhealey — APPROVED** [review]

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
> 3\. For the sort type label, can we position it down by 1px? It feels slightly high to me

I'm still seeing this issue @nevyangelova

Also, I took another look at mobile webview and there seems to be some conflicting hover interactions happening with the content below the menu. 


This may be related to the above, but there looks to be a z-index issue with the category names showing on top of the menu
image

**Comment by nevyangelova** [comment]
@matthewbirtch fixed the label, but the hover issues are related to the menu component and will probably have to be fixed with the new component. However I don't see it as extreme as you do when I tested on IphoneX, iPhone 6 and Ipad in Chrome view. Which resolution did you test on to get those results? Or browsers?

**Comment by matthewbirtch** [comment]
> @matthewbirtch fixed the label, but the hover issues are related to the menu component and will probably have to be fixed with the new component. However I don't see it as extreme as you do when I tested on IphoneX, iPhone 6 and Ipad in Chrome view. Which resolution did you test on to get those results? Or browsers?

The screenshots above were from Chrome in mobile web view below 768px browser widths.

I'll approve this PR knowing that we need to fix the overlapping issues with the menu component revamp

**Review by matthewbirtch — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]

**Comment by hmhealey** [comment]
@matthewbirtch Are there any further changes needed on this, or is it good to go from your point of view?

@nevyangelova Which PR is this waiting on? It doesn't appear to be based off the DM autoclosing changes

**Comment by matthewbirtch** [comment]
> @matthewbirtch Are there any further changes needed on this, or is it good to go from your point of view?

I approved it above. It's good to go knowing we will be fixing identified issues with the overlapping in the menu component revamp

**Comment by jgilliam17** [comment]
@nevyangelova 
Seeing few issues with sort 
>Show the drop target outline around the entire category (like in the DMs section) when trying to drop channels into it. Once dropped, sort by the appropriate method.

1. I am not seeing the outline around the whole category, only category name. 
2. Category does not keep the sort order for recency or alpha when channels are dropped in the category and does not auto sort the dropped channel appropriately using the pre-selected, existing sort

> If any channels were added since the last manual sort, sort them to the bottom of the category when manual sorting is re-enabled.

3. Similarly, as mentioned in 2.  if the category is sorted by alpha or recency and new channel is dropped in, sort is lost and it auto-switches to manual sort; dropped channel remains where it was dropped, not sorted to the bottom of the manual list.
Noting, when dragging any channel out of the category that is sorted by alpha/recent, that category sort order persists - as expected.

**Comment by nevyangelova** [comment]
@jgilliam17 @esethna I missed the part where we have to drop and sort according to the specified sorting, at the moment this defaults to a manual sort. Would we have some buffer time after feature complete on Monday for additional tweaking and bug fixes so this would go in and a bug PR can be submitted afterwards?

**Comment by esethna** [comment]
@nevyangelova @jgilliam17 Ya let's file a follow-up ticket for that and work on it Monday ^

**Comment by hmhealey** [comment]
https://mattermost.atlassian.net/browse/MM-32099 filed for keeping the category automatically sorted

**Pull request merged**
