### PR TITLE
[MM-44643] - Support the ability to link directly into the pricing modal

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR adds ability to open pricing modal using query param on the admin billing route

#### Ticket Link
[MM-44643](https://mattermost.atlassian.net/browse/MM-44643)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @AGMETEOR !

**Review by marianunez — COMMENTED** [review]
@AGMETEOR what is the url that will open the pricing modal? I tried with `admin_console/billing/subscription%3Faction%3Dshow_pricing_modal` but didn't work for me. It takes me to the admin console but doesn't open the modal

Link: https://mattermost-webapp-pr-10417.test.mattermost.cloud/admin_console/billing/subscription%3Faction%3Dshow_pricing_modal

**Comment by AGMETEOR** [comment]
> https://mattermost-webapp-pr-10417.test.mattermost.cloud

@marianunez `https://mattermost-webapp-pr-10417.test.mattermost.cloud/admin_console/billing/subscription?action=show_pricing_modal`

**Review by stevemudie — APPROVED** [review]
Looks good @AGMETEOR! The link worked as expected.

**Pull request merged**
