### PR TITLE
clean up test output

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Clean up test output by renaming `*.svg.tsx` files to `_svg.tsx`. The Jest module mapper stubs out `*.svg*` files, which led to the error output shown in the screenshot below. We already have a pattern for naming those files as `_svg.tsx`. As context for why I'm doing this now, I discovered that this is what is happening when some `.svg.tsx` files I had in my growth spike pr were also erroring out. Instead of changing these files in that PR, I split this into its own PR.

QA Deferred because we ended up making changes post QA testing, but spinwick stopped working; so we will test the rest of it post-merge.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41539

#### Screenshots:

Test output in CI with these changes: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/49171/workflows/c35f51b2-84c0-439c-86df-517e2c12fe59/jobs/341903/parallel-runs/0/steps/0-103

before screenshot of test output:
before

after screenshot of test output:
after

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by stevemudie — APPROVED** [review]
Everything appears to be looking normal. Tested and passed.

**Comment by julmondragon** [comment]
Looks good, this covers the problematic files in the scope of the ticket.

Though, there are some other files still using the naming convention `*.svg.tsx`, specially in `components/common/svg_images_components/`.
Should we have a ticket to address those later, so we don't run into similar issues, and get SVG component files standardized?

**Review by julmondragon — APPROVED** [review]

**Comment by neallred** [comment]
Hmm, it's a small enough set of remaining files that I'd feel comfortable changing them now. As I add them, I can make a note in the ticket to @stevemudie about which *additional* pages need look and feel testing.

**Review by pablovelezvidal — APPROVED** [review]
Thank you @neallred , this was something that needed to be done sooner than later. Good catch 🚀

**Comment by stevemudie** [comment]
Will test this again post merge since there were last minute changes after my initial tests.

**Pull request merged**
