### PR TITLE
[PLT-7972] Ability to reset your own password via System Console Users List

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Ability to reset your own password via System Console Users List

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/PLT-7972
GitHub: https://github.com/mattermost/mattermost-server/issues/7882

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [x] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @cpanato! A few things to take a look at:

1) Please help add whitespace between "Current" and "New" password fields, similar to the image in the ticket https://mattermost.atlassian.net/browse/PLT-7972

image

2) Please left-align the texts "Current Password" and "New Password", as in the ticket

image

3) When current password is incorrect, the "new password" field is highlighted. Expected: current password is highlighted
image

4) When "Current Password" isn't set, 
 - error message: "Invalid or missing current_password in request body"
 - expected error message: "Please enter your current password."

image

5) When you click "Reset Password" and the dialog opens,
 - focus is on "New Password"
 - hitting TAB brings you to "Reset", then outside the modal
 - expected: focus is on "Current Password", hitting TAB brings you to "New Password" --> "Reset" --> "Cancel" --> "X"

**Comment by cpanato** [comment]
will work on the bugs later this week and next.

**Comment by cpanato** [comment]
@jasonblais done :) can you please do anotehr round when you have some free time 😄

**Comment by jasonblais** [comment]
Thanks @cpanato, I'll take a look  by next week

**Comment by jasonblais** [comment]
@cpanato The changes don't seem to be reflected on the spinmint

image

Can you try rebasing the PR? It might be because of the build failure, which is caused by an updated Jenkinsfile https://pre-release.mattermost.com/core/pl/yaekybic6tb5zcp53jgnkcejkr

**Comment by cpanato** [comment]
@jasonblais rebased

**Comment by jasonblais** [comment]
@cpanato The error text for the case described in 4) above is incorrect. But otherwise looks good 👍 

image

**Comment by cpanato** [comment]
@jasonblais updated the code based in your feedback

**Pull request merged**
