### PR TITLE
[MM-36128] Enable 'Set Status' button if the custom status hasn't changed from currently set status

### PR DESCRIPTION
**Pull request by darkLord19**
Fixes mattermost/mattermost-server#17731

Jira issue: https://mattermost.atlassian.net/browse/MM-36128

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by darkLord19** [comment]
@hmhealey in the linked there was also change mentioned in button color but I wasn't sure exactly what color that is so can you check and let me know if you are aware 😅

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by jgilliam17** [comment]
@matthewbirtch Can you please advise on the button color, see comment here https://github.com/mattermost/mattermost-webapp/pull/8307#issuecomment-868709575 Thanks
>update the disabled state of the `Set Status` button to transparent channel color instead of transparent button color

**Comment by matthewbirtch** [comment]
> @matthewbirtch Can you please advise on the button color, see comment here [#8307 (comment)](https://github.com/mattermost/mattermost-webapp/pull/8307#issuecomment-868709575) Thanks
> 
> > update the disabled state of the `Set Status` button to transparent channel color instead of transparent button color

the disabled state of the button should have the following styles:

```
color: rgba(var(--center-channel-color-rgb), 0.32);
background: rgba(var(--center-channel-color-rgb), 0.08);
opacity: 1;
```

In addition to the above, the disabled button should not have a hover state change.

**Comment by darkLord19** [comment]
@matthewbirtch thanks! @jgilliam17 i have updated the pr please verify again

**Comment by matthewbirtch** [comment]
> @matthewbirtch thanks! @jgilliam17 i have updated the pr please verify again

Looks great! Thanks for updating @darkLord19

**Review by jgilliam17 — APPROVED** [review]
Thank you @darkLord19 
Tested, looks good to merge.
- Verified Set Status button disabled color, and no hover state; set Status button is no longer disabled when opening status modal with previously set status or when changing/not changing status message text.

**Comment by jgilliam17** [comment]
@darkLord19 Can you please help add a [release note](https://github.com/mattermost/chewbacca#release-notes-process) so we can unblock merging? Thanks.

**Pull request merged**
