### PR TITLE
WIP ci/test: add NODE_OPTIONS max_old_space_size=500

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
ci/test: add NODE_OPTIONS max_old_space_size=500

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Thank you!

**Comment by cpanato** [comment]
> Thank you!

thanks to @agnivade 🎉

**Review by agnivade — APPROVED** [review]
Let's also remove `test-ci-gitlab` and try with `test-ci` in Gitlab.

**Comment by cpanato** [comment]
@agnivade run in gitlab and looks like it is working as well

https://git.internal.mattermost.com/cpanato/mattermost-webapp/-/jobs/67285

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
