### PR TITLE
MM36866 -  mid month proration UX changes

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
This PR adds the changes to show the proration information to customers that want to upgrade from Cloud Starter (non-free-trial) to any of the other product offerings.

This PR is created because the original one had troubles with the spinwick data so with this new one we can spin a new server with fresh data for QA and UX testing.

Original PR and conversations around it: https://github.com/mattermost/mattermost-webapp/pull/8394

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36866

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by stevemudie — APPROVED** [review]
Looks good!

The tooltip displayed the proper information as expected after selecting Mattermost Cloud or Cloud Enterprise as the product I was upgrading to.

**Comment by stevemudie** [comment]
I did notice though that after I upgraded to Mattermost Cloud then went to upgrade again (this time to Enterprise) the tooltip wasn't present.

Should it be @pablovelezvidal ?

**Comment by pablovelezvidal** [comment]
> I did notice though that after I upgraded to Mattermost Cloud then went to upgrade again (this time to Enterprise) the tooltip wasn't present.
> 
> Should it be @pablovelezvidal ?

no, it shouldn't be present, as per the requirement, the scenario should only happen when:
- Upgrading from Cloud Starter (flat_fee) to (per_user) Cloud Professional or Cloud Enterprise and not in trialing period.

**Comment by pablovelezvidal** [comment]
Closing this PR in favor of the original one, this one was just QA could use a spinwick server.

**Pull request closed without merging**
