### PR TITLE
[MM-49484] - Need updated info on self-hosted pricing modal

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Update pricing info on self hosted modal

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49484

```release-note
NONE
```

### CODE REVIEW

**Review by Afsoon — APPROVED** [review]

**Review by neallred — APPROVED** [review]
LGTM, thanks @AGMETEOR !

**Review by yasserfaraazkhan — APPROVED** [review]
change is showing up and tests have passed
Screenshot 2023-01-05 at 9 39 40 PM

**Pull request merged**
