### PR TITLE
fixes build due to merged tag feature

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
fixes broken build due to merged code-quality branch: #11100 

#### Ticket Link
n/a

#### Related Pull Requests
- broken branch: https://github.com/mattermost/mattermost-webapp/pull/11100
- related pipieline: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/66228/workflows/7d78e04b-9b18-4b7f-81b9-44a50f8d1d35

#### Screenshots
webapp build on local succeeds
Screenshot 2023-01-17 at 15 45 35

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by neallred — APPROVED** [review]

**Comment by koox00** [comment]
AFAICT E2E failures are unrelated to this PR, should we merge?

**Comment by michelengelen** [comment]
I just checked as well and AFAIK all failures are unrelated ... should we consult @jgilliam17 on this? She has more insight in it

**Review by AshishDhama — APPROVED** [review]

**Comment by hmhealey** [comment]
I think we can have @jgilliam17 do a review after this goes in. Anyone working off the latest master is currently blocked by the failures that these changes would fix

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
