### PR TITLE
MM-20584: Migrate 'components/admin_console/team_channel_settings/team/details' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR migrates 'components/admin_console/team_channel_settings/team/details' module and associated tests to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13488
JIRA: https://mattermost.atlassian.net/browse/MM-20584

#### Screenshots
not applicable 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]
Nice work, LGTM!

**Review by hmhealey — COMMENTED** [review]
Sorry for the delay. This looks good to me, but there's now some conflicts unfortunately, so could you fix those?

**Comment by sinansonmez** [comment]
Conflicts are not easy to resolve as they are made to old jsx files. I will close this and create a clean PR.

**Pull request closed without merging**
