### PR TITLE
[MM-15195] Bot account can be edited even though it's managed by a plugin

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR addresses the case where a bot can be edited through the system console UI, even if the bot is managed by a plugin.  

Before: An admin has the ability to create tokens, edit and disable a bot account through the system console.
image

After: An admin cannot create tokens, edit or disable a bot account through the system console.  However, an admin does retain the ability to disable or delete a token
image

Testing:  We should test that the UI elements do not show up for the plugin managed bot, so the existing tests cases were retained, but the expected result is set to false.  

Testing that create, edit, and disable elements exist were added to an existing test that sets up a bot account that is not managed by a plugin.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-15195

#### Related Pull Requests
n/a

### CODE REVIEW

**Comment by jasonblais** [comment]
@DHaussermann Can you help with testing? You can use the remind bot for testing purposes https://github.com/scottleedavis/mattermost-plugin-remind/releases

**Comment by crspeller** [comment]
@jfrerich @jasonblais If we are going to restrict this, should we restrict token disable/delete as well? It's not a useful function.

**Comment by jasonblais** [comment]
@crspeller From my understanding, plugins don't create access tokens so the list would always be empty. Hence, I didn't see the need to add an exception for this.

Please do let me know if you feel differently, particularly if my assumption is incorrect.

**Comment by DHaussermann** [comment]
This is working as expected. Cannot edit, disable or create token for the bot managed by an integration. 

There  is an outstanding issue where the interface to mange users will still allow other users to make changes to the bot. 
ManageBots


@jasonblais  I believe we plan to remove bot account from this list for 5.12. If not, we would need a change here.

**Comment by jasonblais** [comment]
@DHaussermann Yes, we've got an open ticket for it at https://mattermost.atlassian.net/browse/MM-15073 and PR here https://github.com/mattermost/mattermost-webapp/pull/2650

**Comment by levb** [comment]
@jasonblais @crspeller I'm holding off until you guys resolve

**Comment by crspeller** [comment]
@jasonblais You are right, plugins probably would not create user access tokens for their bot accounts. So I think it's fine to ignore that case.

**Comment by jasonblais** [comment]
@levb Ready for your review

**Pull request merged**
