### PR TITLE
PLT-8553 Properly centred status icons

### PR DESCRIPTION
**Pull request by hmhealey**
I'm proposing this for 4.6 since it's a small fix and it looks kind of ugly right now. This is how it looks with this PR

image

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-8553

#### Checklist
- Has UI changes

### CODE REVIEW

**Comment by stephenkiers** [comment]
Just removing the height and width fixes the issue? There are no side-effects to that? Have you checked in multiple browsers?

That is my only concern

**Comment by hmhealey** [comment]
I can check other browsers. The one that it worked on was using `width="100%" height="100%"` so I was thinking that was equivalent to not having it set

**Comment by hmhealey** [comment]
Good call, Stephen. It broke Edge and Firefox oddly enough. I've confirmed it looks correct on Chrome (Windows + Mac), IE11 (Windows), and Safari (Mac)

**Comment by stephenkiers** [comment]
Yeah, my thought is that this probably should be handled with flexbox to get the alignment right. If the 100%/100% works though, that is easiest. :)

**Comment by jasonblais** [comment]
@hmhealey This is now good across browsers?

**Pull request merged**
