### PR TITLE
Remove flux usages from email invite modal

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Remove flux usages from email invite modal and converted the modal to use the modal controller.

@lindy65 can you regression test the email invite modal?

#### Ticket Link
Part of https://mattermost.atlassian.net/browse/MM-12564

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by lindy65** [comment]
@jwilander - same issue with the spinmint failing to build for this one, can you take a look please?  Thanks!

**Comment by jwilander** [comment]
@lindy65 test server is up

**Comment by lindy65** [comment]
Thanks @jwilander,

As discussed, I'll test this one post merge.

**Comment by sudheerDev** [comment]
@jwilander Needs a rebase

**Pull request merged**
