### PR TITLE
PLT-7771: Add jobs table to Elasticsearch admin UI

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
This is a draft version of the ticket to get PM feedback on where the widget is in the UI, and the strings changes. It's not ready for dev review yet.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7771

#### Checklist
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

### CODE REVIEW

**Comment by grundleborg** [comment]
@esethna 

1. Done
2. Done. If there is an existing index it is incrementally updated.
3. Will look at this as soon as the new spinmint is read.
a. You'll see :)
b. Again, it'll be obvious when it's working. % progress I think will be shown in the "extra" column.
c. "Extra" column.

**Comment by grundleborg** [comment]
1 & 5 are CSS fixes so might be better to ask AM to take a look at them.

4. Can happen if you're messing the server about enough. Shouldn't happen normally. It gets stuck in Cancelling state, and won't ever change. Not really anything we can do right now to fix it. There's a plan eventually to add some kind of cleanup functionality for the jobs SQL table to address this.

2 & 3 - will investigate and update the PR.

**Comment by grundleborg** [comment]
(the reason for it getting stuck in this case was me messing with the Elasitcsearch setup to try and give you an example of an "error" result, which didn't work out right).

**Comment by esethna** [comment]
@asaadmahmood can you help out with 1 & 5 above when you get a chance?

**Comment by asaadmahmood** [comment]
Done @jasonblais

**Comment by asaadmahmood** [comment]
@grundleborg Please pull my changes before submitting yours.

**Comment by grundleborg** [comment]
@esethna all done.

**Comment by grundleborg** [comment]
@esethna spinmint set up with elasticsearch now, ready for you to verify the changes.

**Comment by esethna** [comment]
Looks good, thanks @grundleborg @asaadmahmood

**Pull request merged**
