### PR TITLE
[MM-28216] Billing History View (UX Only)

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Billing History table demo. UX only.
Includes a button so you can see what no billing history looks like.
Will merge this PR and submit a follow-up PR once the backend is complete.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28216

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]
LGTM! 👍

**Review by stevemudie — APPROVED** [review]
LGTM

**Review by marianunez — APPROVED** [review]

**Review by matthewbirtch — APPROVED** [review]
Solid work @devinbinnie. Will we include pagination in another PR?

**Comment by devinbinnie** [comment]
> Solid work @devinbinnie. Will we include pagination in another PR?

Thanks @matthewbirtch. The functionality will, but I think i'll add the UI for it now. Thanks for the reminder!

**Comment by devinbinnie** [comment]
@matthewbirtch I added the paging section, can you have a quick glance?

**Review by matthewbirtch — APPROVED** [review]
Looks good!

**Pull request merged**
