### PR TITLE
Fixes GH-13865 : Added a11y popover to memebers list

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary

This PR adds accessibility classes to ~few of the modals and popovers which were missed.~ to popover list member component which is used in channel header

#### Ticket Link
Fixes partially : https://github.com/mattermost/mattermost-server/issues/13865
Jira : Nil

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
Hi all,
i am using Chrome Vox to check for accessibilty, Wondering whats the options in Vox do you all have ? so my tests can be reliable.

**Comment by hanzei** [comment]
@M-ZubairAhmed Heads up that the build failed because of a liner issue: https://app.circleci.com/jobs/github/mattermost/mattermost-webapp/78747/parallel-runs/0/steps/0-103

**Comment by M-ZubairAhmed** [comment]
thank you, yes i will fix it. Also awaiting further instructions to test this pr.

**Comment by devinbinnie** [comment]
@M-ZubairAhmed Thanks for the PR!
Unfortunately I have very limited experience with Chrome Vox. What we have been using is a Chrome extension called aXe (https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd) to scan for and identify accessibility issues. As long as the issue described in the ticket is no longer visible in aXe, we can consider the issue resolved.

As for screen readers, we have mostly been testing on JAWS on Windows, and Apple VoiceOver on Mac if you have access to those.

**Comment by M-ZubairAhmed** [comment]
@devinbinnie thank you for your response
How do you propose going forward with this PR?
I dont have access to windows netiher Mac, Is it possible to test it at the team's end.?

**Comment by devinbinnie** [comment]
> @devinbinnie thank you for your response
> How do you propose going forward with this PR?
> 
> I don't have access to windows neither Mac, Is it possible to test it at the team's end.?

@M-ZubairAhmed Are you able to download the Chrome extension I've linked? That is what we'll be using to test. I know there are other version of aXe available if that doesn't work.

We can and definitely will be testing on our end, but to avoid extra churn it would really help if you were able to use the tools we will be using. Let me know if that will be an issue. Thanks again for the contribution :)

**Comment by M-ZubairAhmed** [comment]
Hi @devinbinnie yes i have downloaded the Axe extension and i am using it. 
As per @devinbinnie comment here https://community.mattermost.com/core/pl/atfqrr3uwfncubfeubwapkq64r

I am trying to see if with and without the a11y does it make any difference.

**Comment by jasonblais** [comment]
@M-ZubairAhmed I added a work in progress label while you're investigating :)

**Comment by M-ZubairAhmed** [comment]
@devinbinnie there is no new accessibility issues and as per @deanwhillier comments to add a11y classes to tooltips, i added them.

**Comment by M-ZubairAhmed** [comment]
Let me know what to do next

**Comment by jasonblais** [comment]
@M-ZubairAhmed Sorry for such a long wait!

@devinbinnie @deanwhillier are you open to help review when you have a moment? Thanks!

**Comment by jasonblais** [comment]
Given it's been a few months, this may need manual updates to resolve conflicts,

**Comment by M-ZubairAhmed** [comment]
I will so a manual update @jasonblais

**Comment by hanzei** [comment]
@M-ZubairAhmed Heads up that there is a merge conflict to resolve

**Comment by hanzei** [comment]
@deanwhillier @devinbinnie Gentle reminder to review this PR :wink:

**Comment by devinbinnie** [comment]
> @deanwhillier @devinbinnie Gentle reminder to review this PR 😉

@M-ZubairAhmed if you are able to resolve the conflicts I'll work on getting a test server setup so I can review the changes. Sorry about the wait!

**Comment by esethna** [comment]
@M-ZubairAhmed friendly ping on this, please let us know if you'd like to finish work on this PR or if we should close it :)

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed friendly ping on this, please let us know if you'd like to finish work on this PR or if we should close it :)

@esethna i think its been a quite while and i have forgotten the context of this pr, lets close it for now and if theres related issue i can look at it in future.

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed friendly ping on this, please let us know if you'd like to finish work on this PR or if we should close it :)

Since it has been long due from my side, i have reduced the scope of this PR, currently it add a11y class to channel header popover, Let me know if this is still good or would you like me to let go of this?

**Comment by esethna** [comment]
Thanks @M-ZubairAhmed! I'll let @deanwhillier and @devinbinnie comment on that ^ Even with reduced scope we should be able to accept the PR if it's working as expected.

**Review by deanwhillier — APPROVED** [review]
LGTM!

**Review by devinbinnie — APPROVED** [review]

**Comment by devinbinnie** [comment]
This looks good to me, sorry for the delay in response.

**Pull request merged**
