### PR TITLE
[MM-29393] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 519 (#15832)

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 519

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15832
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29393

### CODE REVIEW

**Comment by deanwhillier** [comment]
QA review will be done on the final PR that merges all changes to this campaign branch into master.

**Review by nevyangelova — COMMENTED** [review]
Thanks! Can you double check that the theme switch works in the new sidebar as well? Right now its only updated for the legacy sidebar.

**Comment by KuSh** [comment]
> Thanks! Can you double check that the theme switch works in the new sidebar as well? Right now its only updated for the legacy sidebar.

This is totally normal `.sidebar--left` class is only used by legacy sidebar so removed line in utils was only targeting legacy sidebar (and so is the migrated css rule)

**Review by asaadmahmood — APPROVED** [review]

**Comment by deanwhillier** [comment]
PR will be QA'd in batch when campaign branch is merged to master

**Review by deanwhillier — APPROVED** [review]
@KuSh, thanks for confirming for @nevyangelova!

**Pull request merged**
