### PR TITLE
String update: Clarify Add Member to Channel hint text

### PR DESCRIPTION
**Pull request by cwarnermm**
When adding members to a channel, the existing hint text ambiguously suggests that a maximum of 20 members can be added to a given channel. Updated hint text to clarify that users can add up to 20 members at a time to the channel.

```release-note
Updated help text on Add Users to Channel modal
```

### CODE REVIEW

**Comment by cwarnermm** [comment]
@hmhealey - Thank you for alerting me to the fact that I was attempting to update an existing product string in an incorrect repository. https://github.com/mattermost/i18n-wip/pull/9 has now been closed, and I've created a PR on this repository, where this update belongs. Would a change like this warrant a release note entry as well? Thanks for your help with this!

**Review by esethna — APPROVED** [review]
Looks good as long as the "max" syntax will work

**Comment by cwarnermm** [comment]
Thank you so much, @hmhealey!

**Review by nevyangelova — APPROVED** [review]
LGTM!

**Review by jgilliam17 — APPROVED** [review]
Thanks @cwarnermm 
Tested, looks good to merge.
- Verified new hint on add member to channel modal.
Screen Shot 2021-05-26 at 9 27 36 AM

**Comment by michaelgamble** [comment]
Hey everyone, Had a chat with @andrewbrown00  last week and took a moment to review this PR as I did the original design work.. it struck me as an odd proposal that we would put emphasis on a limitation that may not affect all users.. what i mean by this is - if the majority of users are only adding a couple of users at a time, then its only a fringe case where we start getting into bulk imports that this impacts...

So i propose we take a slightly less "always visible" approach that follows the patterns we have already established for this type of autocomplete input field (reference the error states of the invite members to teams)

https://www.figma.com/file/U10zzjkOQd5bO2ekAnllpt/Add-Members-to-Channel?node-id=513%3A1

To be clear the proposal is:

- Don't show any statement about a user limitation until the user starts to attempt to add the 21st person
@cwarnermm  @hmhealey  @esethna

**Pull request merged**
