### PR TITLE
MM-50296: fixes click to open thread

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Click to open a thread should only happen when a post in the CENTER channel is clicked.
This commit adds the location check in click to open thread.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-50296

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
Thanks @koox00 🎉

**Comment by koox00** [comment]
@nevyangelova, @M-ZubairAhmed BTW I'd like to make some changes in the component, mostly in the sense of wrapping functions that are being passed as props to React components with `useCallback`.

Do you mind me adding these changes in this PR, or would you prefer a new one? 
I'm 0/5 on how to proceed on this.

**Comment by nevyangelova** [comment]
@koox00 I am ok with adding them to this one and I will give it another review after

**Comment by Willyfrog** [comment]
Is this aimed at v7.8? I think this is a regression on the current RC
cc/ @amyblais

**Comment by koox00** [comment]
> Is this aimed at v7.8? I think this is a regression on the current RC

I think so yes. It's a regression of the unified post component effort.

**Comment by amyblais** [comment]
QA mentioned it doesn't reproduce on v7.8, but this can be fixed before the next cloud release.

**Comment by koox00** [comment]
@amyblais, @Willyfrog sorry I confirmed it is not reproducing in 7.8.
@nevyangelova isn't the unified post component released in 7.8?

**Comment by amyblais** [comment]
> isn't the unified post component released in 7.8?

No, it will go into v7.9.

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]

**Review by lindalumitchell — APPROVED** [review]
Verified fix on test server, and found no related failures in e2es. LGTM.

**Comment by Willyfrog** [comment]
@koox00 what's left to merge this?

**Review by Willyfrog — APPROVED** [review]

**Pull request merged**
