### PR TITLE
MM-47217 Reorder the leave channel menu item

### PR DESCRIPTION
**Pull request by esethna**
Temporary fix to reorder the "leave channel" menu option above the plugin menu entries so users on smaller monitors still have the ability to leave a channel. The full fix will be addressed with https://mattermost.atlassian.net/browse/MM-40156 and the web platform teams Q4 OKRs for menus

Root cause is this bug: https://mattermost.atlassian.net/browse/MM-47217

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by esethna** [comment]
Tested and verified the fix on the test server

**Comment by matthewbirtch** [comment]
@esethna maybe we should put it in the same Menu Group as `Archive Channel`. It feels a bit odd to have a group of only one item (it wasn't as odd when it was the last item in the menu)

**Comment by AshishDhama** [comment]
@esethna we will need to update the test snapshot, due want me to do that?

**Comment by hmhealey** [comment]
If you wanted to do that yourself, Eric, you can run `npm test -- -u` to update the snapshot files. If you check those updated files in, that should unblock CI

**Comment by esethna** [comment]
@AshishDhama do you mind helping with the test? I actually just edited this in the browser so I haven't installed a dev environment

**Review by AshishDhama — APPROVED** [review]

**Comment by matthewbirtch** [comment]
> @esethna maybe we should put it in the same Menu Group as `Archive Channel`. It feels a bit odd to have a group of only one item (it wasn't as odd when it was the last item in the menu)

@esethna this isn't a blocker, but let me know your thoughts on it

**Comment by esethna** [comment]
> but let me know your thoughts on it

@matthewbirtch agree with removing the divider.

**Review by matthewbirtch — APPROVED** [review]

**Comment by esethna** [comment]
@AshishDhama the tests might need to be updated again since the latest change to remove the divider

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
