### PR TITLE
[MM-49515] Show board insights for boards 'product'

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

After focalboard switched from a plugin to product, the check which made sure focalboard is installed before displaying insights broke, thus not displaying insights at all if boards is installed as a product.

This PR extends these checks to boards "product".
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49515
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@amyblais - cherry-pick candidate for 7.7

**Review by BenCookie95 — APPROVED** [review]

**Review by kostaspt — APPROVED** [review]

**Comment by amyblais** [comment]
@furqanmlk Please help prioritize this PR review.

**Comment by BenCookie95** [comment]
@furqanmlk conflicts are fixed

**Review by furqanmlk — APPROVED** [review]
### Tested as Product
Following were the steps to verify
1. From focalboard repo: 
    a. Checkout `rolling-stable` branch 
    b. `cd webapp && npm install` 
    c. cd ..
    d. `make watch-product`
2. From webapp: `make run`
3. From server: `export MM_FEATUREFLAGS_BoardsProduct=true` and `make run-server`
4. Verified Boards were working as expected in Insights

### Tested as Plugin
Working as expected

**Comment by amyblais** [comment]
@plant99 Needs manual cherry-picks to ``release-7.7`` and ``cloud`` branches (please open PRs).

**Comment by plant99** [comment]
@amyblais let me cherry-pick this manually. There seems to be some conflict.

**Pull request merged**
