### PR TITLE
[MM-42603] if mobile view, don't show pulsating dot. Always open the actions menu

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
When a user is in the mobile view, the actions menu should not wait for the user to view the tooltip.
* do not show pulsating dot on Action menu
* clicking the Actions Menu will always open the menu
* side effect is that they can use the new Actions Menu feature on mobile, but will see the pulsating dot if viewing on web view.

I added the logic to the selector which is used by post_info, rhs_comment, and rhs_root components.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42603

#### Screenshots

|  before  |  after  |
|----|----|
| image| image |

  
#### Release Note

```release-note

```

### CODE REVIEW

**Review by matthewbirtch — COMMENTED** [review]
@jfrerich I'm not sure if this is an issue with this PR specifically, but it seems like the darkening overlay layer is not quite covering the full background when the actions menu is open: 

image

**Comment by jfrerich** [comment]
@matthewbirtch, I'm sure it has to do with the new Actions Menu. I'm looking into it now

**Comment by jfrerich** [comment]
@matthewbirtch, I haven't figure out the darkening overlay issue yet. I'll create a separate ticket for that issue.

**Comment by jfrerich** [comment]
Ticket created. https://mattermost.atlassian.net/browse/MM-42858

**Review by hmhealey — APPROVED** [review]

**Review by matthewbirtch — APPROVED** [review]
Confirming that the dot is hidden on mobile webview. Thanks for creating the other ticket @jfrerich

**Review by saturninoabril — APPROVED** [review]
Thanks @jfrerich! Tested and passed.

@amyblais @jfrerich re: https://mattermost.atlassian.net/browse/MM-42858 - Are you planning to get it fix for March 30th Cloud release? Maybe it's fine if can't make it as it's low impact but should definitely be fixed in v6.6.

**Comment by saturninoabril** [comment]
@jfrerich Feel free to merge and cherry-pick.

**Pull request merged**
