### PR TITLE
Mm 37657 migrate cloud purchase screens to new branding

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
This PR updates the SVG images present in the purchase modal and processing payment section to the new branding UX.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37657

#### Related Pull Requests
This PR includes the changes present in https://github.com/mattermost/mattermost-webapp/pull/8560

#### Screenshots
Captura de pantalla 2021-08-12 a las 1 38 02

#### Release Note
Captura de pantalla 2021-08-12 a las 13 02 33
Captura de pantalla 2021-08-12 a las 13 56 05
Captura de pantalla 2021-08-12 a las 13 56 38

```release-note
Updated the images present in the purchase modal and processing payment section to the new branding
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@pablovelezvidal can you let me know when the test server issue is resolved and I can review this (along with the system console changes)

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal can you let me know when the test server issue is resolved and I can review this (along with the system console changes)

yes @matthewbirtch , I will, as soon as the spinwick get's fixed! Thanks!

**Comment by pablovelezvidal** [comment]
@matthewbirtch spinwick server is working now!

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @pablovelezvidal. I'll dive deeper, but wanted to call out the first thing I noticed when using dark themes:
image

I guess we need to use theme variables in the background svg

**Review by neallred — APPROVED** [review]
Aside from Matt's suggestions, code looks good to me.

**Review by marianunez — APPROVED** [review]
LGTM. Thanks @pablovelezvidal!

**Comment by pablovelezvidal** [comment]
The issues related to the purchase modal not working with theming are covered and will be worked as part of this JIRA ticket: https://mattermost.atlassian.net/browse/MM-34899 .

Point 4 of @matthewbirtch comments, is something that is not related to this changes but it is definitely worth taking a look because I have also seen that happening even without the purchase modal opened. Something is causing that redirection and we need to check what it is cc: @marianunez . Also point 6 is something that needs to be addressed as part of a new ticket.

The other points are addressed with my latest commit.

**Comment by marianunez** [comment]
> Point 4 of @matthewbirtch comments, is something that is not related to this changes but it is definitely worth taking a look because I have also seen that once happening, although very few times, even without the purchase modal opened. Something is causing that redirection and we need to check what it is cc: @marianunez . Also point 6 is something that needs to be addressed as part of a new ticket.

Agreed, let's split out these in two separate tickets so we can fix in follow up PRs.

**Review by matthewbirtch — APPROVED** [review]

**Comment by marianunez** [comment]
Given that these images are only for cloud and not needed for on-prem 6.0, let's hold off on merging this so it can closer to Sept. 15th new branding launch. Adding `Do not merge` tag in the meantime

**Review by stevemudie — APPROVED** [review]
Looks good @pablovelezvidal ! Everything appeared as expected.

**Comment by marianunez** [comment]
@pablovelezvidal We can now merge this and it will make it to the Sept. 8th Cloud release - last cloud release before Sept. 15th.

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal We can now merge this and it will make it to the Sept. 8th Cloud release - last cloud release before Sept. 15th.

ok!

**Comment by marianunez** [comment]
> /cherry-pick cloud

@amyblais we don't want to cherry pick this to `cloud` just yet. These changes of branding just affect cloud customers - do not apply to on-prem v6.0 - and we want to release them as close as possible to Sept. 15th when all the brand updates will be launched.

**Pull request merged**
