### PR TITLE
[GH-13483] Migrate 'components/channel_invite_modal' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by tweichart**
#### Summary
This PR migrates the components/channel_invite_modal to TypeScript.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13483

### CODE REVIEW

**Comment by tweichart** [comment]
The Props.actions definition in `channel_invite_modal.tsx` for `addUsersToChannel` & `getProfilesNotInChannel` needed to be adjusted to any due to the fact that `actions/channel_actions.jsx` is not migrated to TypeScript. Is there a ticket that addresses this, so that this file will be migrated too? It's used in many components so I didn't want to touch it in this PR here.

**Comment by jfrerich** [comment]
@nickmisasi, @crspeller gentle reminder to review this PR

**Review by nickmisasi — APPROVED** [review]
LGTM! Thanks @tweichart 🎉

**Review by crspeller — APPROVED** [review]

**Review by lindalumitchell — APPROVED** [review]
Did general testing around the channel invite modal, no issues found. LGTM!

**Pull request merged**
