### PR TITLE
[MM-16087] Accessibility changes for the emoji picker

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Some accessibility changes to the emoji picker to make it easier to navigate, and to ensure all labels for categories and the emojis themselves are read out correctly.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16087

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@devinbinnie This looks good for the most part, there is just one thing, and we can tackle it here, or separately. The fact that when you navigate to the categories, you cannot used the `up/down` arrow keys to navigate to the emojis, you have to return to the search bar to do that.

That may not be intuitive, neither ideal.

But as said, we can look at that separately too if we want.
Will leave that decision to @esethna.

**Comment by devinbinnie** [comment]
> @devinbinnie This looks good for the most part, there is just one thing, and we can tackle it here, or separately. The fact that when you navigate to the categories, you cannot used the `up/down` arrow keys to navigate to the emojis, you have to return to the search bar to do that.
> 
> That may not be intuitive, neither ideal.
> 
> But as said, we can look at that separately too if we want.
> Will leave that decision to @esethna.

After discussing with @esethna we decided to implement this change. Now when you are tabbed onto a category, if you press the arrow keys, it will refocus you to the search bar and you can arrow through the emojis normally.

**Comment by devinbinnie** [comment]
> 1. After arrowing to an emoji, hit ENTER, then I would expect that focus is set back on the text input area so i can hit ENTER again to send the post. Right now hitting ENTER again re-opens the emoji picker
> 2. Also, emoji picker doesn't open from the RHS text input area
> 
> image
> 
> Looks good other than that

Pushed a fix for 2), 1) is going to be an issue, as we are already calling `focus()` on the textbox after the emoji picker is closed. It might be a larger issue with the application.

**Comment by esethna** [comment]
Okay thanks, will file a separate bug ticket

**Comment by esethna** [comment]
Bug re focus: https://mattermost.atlassian.net/browse/MM-17074

**Pull request merged**
