### PR TITLE
[MM-40111] Reset theme in system console modals

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
The theme CSS variables are leaking inside the admin console, while the console doesn't follow those rules.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40111

#### Related Pull Requests
N/A

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |

#### Release Note
```release-note
NONE
```

[MM-40111]: https://mattermost.atlassian.net/browse/MM-40111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Comment by kostaspt** [comment]
@BenCookie95 @mkraft If you'd like to take a look at [these changes](https://github.com/mattermost/mattermost-webapp/pull/11867/commits/3bde27c0950e96fe521eae6adf89e190f6f084cd). It's similar to https://github.com/mattermost/mattermost-webapp/pull/11938 using my findings there for resetting the theme which requires much fewer changes than before.

**Review by furqanmlk — COMMENTED** [review]
@kostaspt, Can you please fix lint ?

**Review by furqanmlk — APPROVED** [review]
Thanks @kostaspt , working as expected with following steps
1. Login as sysadmin
2. Go to Settings > Display > Theme 
3. Select `Onyx` theme
4. Go to System Console > Users 
5. Click on a User's role dropdown and select 'Manage Roles'
Result: Modal footer's is white

**Beforer**
image

**After**
image

**Pull request merged**
