### PR TITLE
[MM-29034] Remove usage of sidebar-text-## CSS variables

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary
Remove usage of sidebar-text-## CSS variables
Also fixes a forgotten --sidebar-text-16 occurence left during a previous refactoring

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15782
JIRA: https://mattermost.atlassian.net/browse/MM-29034

### CODE REVIEW

**Comment by KuSh** [comment]
It seems this doesn't count as a valid Hacktoberfest contribution because your repositories aren't marked with hacktoberfest topic, see https://hacktoberfest.digitalocean.com/faq

**Comment by jasonblais** [comment]
Thanks @KuSh for the contribution!

@hmhealey wasn't sure if this needs PM review - if so, please request ESethna's review.

**Comment by asaadmahmood** [comment]
@KuSh I haven't tested this, but does this work?
I think there is an issue where css variables don't work well with numeric values, rather work well with other css variables for the opacities themselves.

**Comment by KuSh** [comment]
> @KuSh I haven't tested this, but does this work?
> I think there is an issue where css variables don't work well with numeric values, rather work well with other css variables for the opacities themselves.

I'll launch the app to test those changes but it would be really strange on your side to specifically ask for a change (see issue content) that is known to not work ...

**Comment by asaadmahmood** [comment]
@KuSh Scratch that then, just had a look, looks good to me!

**Review by asaadmahmood — APPROVED** [review]

**Comment by KuSh** [comment]
I would be thankful if you could label this PR hacktoberfest-accepted as you are not currently marked as participating in the hacktoberfest (I've been told it's being handled on Contributors channel but this is a temporary solution in the mean time)

See https://github.com/digitalocean/hacktoberfest/pull/596 for references

**Comment by KuSh** [comment]
> @asaadmahmood I'll launch the app to test those changes
Just tested the change (after battling a little bit with dev env :)) and I can confirm that it works as expected

**Comment by jasonblais** [comment]
Thanks @KuSh! We'll also be labeling PRs with `hacktoberfest-accepted` label soon, so it counts towards your Hacktoberfest contributions!

**Review by hmhealey — APPROVED** [review]
Thanks for the help with this! Looks good to me

**Review by jgilliam17 — APPROVED** [review]
Thank you @KuSh 
Tested, looks good to merge.
- Verified sidebar text in light and dark themes - es expected.

**Pull request merged**
