### PR TITLE
MM-45109 Fix incorrectly formatted System Console text

### PR DESCRIPTION
**Pull request by hmhealey**
Most of these were caused by the default text and English translation strings getting out of sync. Some of the regressions reported in the ticket were caused by recent changes, but some that I found were actually older cases where we didn't turn on Markdown formatting for existing text.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45109

#### Release Note
```release-note
Fixed incorrectly formatted text in the System Console
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]
LGTM!

**Comment by hmhealey** [comment]
@ctlaltdieliet FYI on this. Hopefully it won't conflict with #10442 too much since it's in the same area

**Review by jgilliam17 — CHANGES_REQUESTED** [review]
Thanks @hmhealey 
- Verified links and text formatting in System Console.
- There is one failure that may be related to PR changes test case `MM-T1100` see full report [here](https://mattermost-cypress-report.s3.amazonaws.com/215060-29ef207-onprem-ent-webapp-pr-10680-mattermost/mm-ee-test29ef207/mochawesome.html) Can you please take a look? 
When manually testing on the PR server, this line is formatted as expected.

**Comment by hmhealey** [comment]
I updated the failing test case. It looks like it was relying on the incorrect behaviour from before

Screen Shot 2022-07-15 at 3 55 14 PM

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
- Verified text in System console is formatted porperly
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/219246-ddd2634-onprem-ent-webapp-pr-10680-mattermost/mm-ee-testddd2634/mochawesome.html)- no PR related failures.
Screen Shot 2022-07-19 at 12 19 56 PM

**Pull request merged**
