### PR TITLE
XYZ-32: Increases max length of position.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary
Increases max length accepted by of position input.

#### Ticket Link
[XYZ-32](https://mattermost.atlassian.net/browse/XYZ-32). 

**Do not merge until https://github.com/mattermost/mattermost-server/pull/8148 is merged.**

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@mkraft I think we only wanted to increase the DB field size but keep the UI same as before.

**Comment by mkraft** [comment]
@jasonblais What's the purpose of limiting the UI to 35 characters (as it currently is in production) vs allowing 128 characters to be set via LDAP?

**Comment by jasonblais** [comment]
If you have a position field that's 128 characters long, it won't look great on the profile popover. So we want to be forgiving to the end user who inputs their position via the UI.

However, enterprises that use LDAP sync to update the field may use it for something else than just the job title. If they exceed the character limit of 64, then the sync fails to update the user altogether.

**Comment by mkraft** [comment]
@jasonblais Fair enough. Closing this.

**Comment by hmhealey** [comment]
I just came across this in the Community Heartbeat channel. Isn't having a long position field already handled since we truncate the position in the profile popover?
image

**Comment by mkraft** [comment]
@jasonblais ^ For your consideration. Let me know if this changes anything.

**Comment by jasonblais** [comment]
@mkraft @hmhealey Oh I see. We must have changed that then. We also show a tooltip when you hover over the position field in the profile popover.

I'm okay merging this change.

**Pull request merged**
