### PR TITLE
ABC-79: use autocomplete channels endpoint

### PR DESCRIPTION
**Pull request by ccbrown**
#### Summary
See https://github.com/mattermost/mattermost-server/pull/8163 and https://github.com/mattermost/mattermost-redux/pull/384

Won't work until the other PRs are merged.

#### Ticket Link
https://mattermost.atlassian.net/browse/ABC-79

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has server changes
- [x] Has redux changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@ccbrown Server-side results not loading for me on channel autocomplete. Client-side results displayed immediately. The test server has 24 channels of which the `user-0` account has joined 6.

image

Network should be fine. Waited for several seconds. Other channel searches seem fine.

**Comment by ccbrown** [comment]
@jasonblais Had to update redux after its PR was merged. This spinmint is good to test now.

**Comment by jasonblais** [comment]
@ccbrown This looks good to me. The difference in perf is great. It was usable at even slow 3G connection.

It's hard to say if users would notice the difference when returning X arbitrary results instead of the first X.. I personally didn't when I tested. And given it's standard in other apps I suspect users wouldn't.

One issue though: `Off-Topic` channel always shows at the top of my "Other Channels" list:

image

**Comment by ccbrown** [comment]
@jasonblais I'm not sure I see the problem. The user wasn't in the off-topic channel. So it should have been there, right? I just joined the off-topic channel and it was moved from the "other channels" list as expected.

**Comment by ccbrown** [comment]
Oh. I guess you're referring to the sorting. Yeah, it looks like capitalized channel names are sorted before lowercase. That would be a server-side fix though, not part of this review.

**Comment by ccbrown** [comment]
Here's the PR to fix that: https://github.com/mattermost/mattermost-server/pull/8176

**Comment by amyblais** [comment]
The new PR (mattermost/mattermost-server#8176) is now merged.

**Pull request merged**
