### PR TITLE
[MM-47931] a/b test for reduced onboarding task list item

### PR DESCRIPTION
**Pull request by mhd-sln**
#### Summary
This PR allows A/B testing for reducing onboarding task list item. With feature flag ON the following three items are not displayed in the onboarding task list

- Download the Desktop and Mobile Apps
- Complete your Profile
- Visit the System Console to configure your workspace

For testing, I have created the following users having different roles in the spinwick server.

| role | user id | password |
|----|----|----|
| admin | admin@admintest.com | admin@admintest.com |
| user | user-1 | User-1@123 |
| guest | muhammad.salman+reduceonboardingguestuser@mattermost.com | muhammad.salman+reduceonboardingguestuser@mattermost.com |

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47931

#### Related Pull Requests
- Has server changes (https://github.com/mattermost/mattermost-server/pull/21571)

#### Screenshots

|  before/feature flag: off |  after/feature flag: on  |
|----|----|
| ADMIN USER ||
|  Screenshot 2022-11-04 at 22 28 55 | Screenshot 2022-11-04 at 22 18 26 |
| MEMBER ||
| Screenshot 2022-11-04 at 22 30 18 | Screenshot 2022-11-04 at 22 26 09 |
| GUEST ||
|  Screenshot 2022-11-04 at 22 31 06 | Screenshot 2022-11-04 at 22 23 44 |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Comment by marianunez** [comment]
@stevemudie gentle ping for this QA review so we can cherry pick for next cloud release

**Comment by marianunez** [comment]
@mhd-sln Looking at the screenshots, it seems it's not showing the tour for boards and playbooks in the list. Is this intended?

**Comment by marianunez** [comment]
> @mhd-sln Looking at the screenshots, it seems it's not showing the tour for boards and playbooks in the list. Is this intended?

Oh this is probably being hidden from the `UseCaseOnboarding` flag that used to not show it unless the user selected that use case. Is that the case @pvev ?

**Comment by pvev** [comment]
> Oh this is probably being hidden from the `UseCaseOnboarding` flag that used to not show it unless the user selected that use case. Is that the case @pvev ?
> 
> Edit: It seems that it is because the plugins are not installed here

yes, it is because the plugins are not installed in the workspace.

**Comment by annelieseklein** [comment]
Can we  get rid of the play button in both A/B test options so it is just the emoji?j https://mattermost.atlassian.net/browse/MM-48361








Can we  get rid of the play button in both A/B test options so it is just the emoji?j

**Comment by marianunez** [comment]
> Can we get rid of the play button in both A/B test options so it is just the emoji?j https://mattermost.atlassian.net/browse/MM-48361
> 
> Can we get rid of the play button in both A/B test options so it is just the emoji?j

I've made this change in https://github.com/mattermost/mattermost-webapp/pull/11581

**Review by stevemudie — APPROVED** [review]
Looks good and worked as expected @mhd-sln

**Pull request merged**
