### PR TITLE
Add registry function to register the call pluggables

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Add registry function to register the call pluggables.

#### Ticket Link
Hackaton

#### Related Pull Requests
https://github.com/mattermost/mattermost-plugin-calls/pull/128
https://github.com/matterpoll/matterpoll/pull/435

#### Release Note
```release-note
Added new plugin registry function to register pluggables for Calls
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Only 1/5, but would it be a good idea to do this in a more generic way so that Calls and other products/plugins could add their own pluggables more easily? I guess that would bring us closer to just having people dispatching `RECEIVED_PLUGIN_COMPONENT` themselves, but I would like to keep the plugin registry as a layer of abstraction in front of the Redux actions.

I'm also realizing this isn't exactly a pluggable in the sense of of the Pluggable component since that's expected to be rendering a React component. It's not the first place we've done this, so it's an existing issue with our naming, but we're definitely abusing the fact that we're storing everything in a field called `components`. No wonder the type definitions for this part of the code are either non-existent or awful 😛

**Comment by larkox** [comment]
> I guess that would bring us closer to just having people dispatching `RECEIVED_PLUGIN_COMPONENT` themselves

https://github.com/matterpoll/matterpoll/blob/d432d0899b3bb6327d6b31c2cfa878a5ce64d150/webapp/src/plugin.jsx#L55-L70 :P

**Comment by larkox** [comment]
> would it be a good idea to do this in a more generic way so that Calls and other products/plugins could add their own pluggables more easily?

I was considering something like "registering a registry function", but then we get "the chicken and the egg" problem. For example... Calls, when initialized register this registry function. And Playbooks wants to use that registry function to register an action to create a playbook from a call (because why not, it is an example :P). But the order or initialization is not determined, so playbooks may init before Calls, and then the registry function doesn't exist. So let's make the products start first and in a determined order. Then what if calls wants to add a call button in a playbook? It could not, because it is always initialized first and the registry function does not exist.
We could try to make a two rounds initialization, or a "on all plugins loaded" kind of hook. But then what happens if we install calls after we had the plugins installed and working? Do we need to disable and reenable them form them to show the information?

It feels a bit too troublesome, but if you have better ideas, I am always happy to listen :D

**Comment by hmhealey** [comment]
> https://github.com/matterpoll/matterpoll/blob/d432d0899b3bb6327d6b31c2cfa878a5ce64d150/webapp/src/plugin.jsx#L55-L70 :P

Ah, backwards compatibility

> > would it be a good idea to do this in a more generic way so that Calls and other products/plugins could add their own pluggables more easily?
> 
> I was considering something like "registering a registry function", but then we get "the chicken and the egg" problem. For example... Calls, when initialized register this registry function. And Playbooks wants to use that registry function to register an action to create a playbook from a call (because why not, it is an example :P). But the order or initialization is not determined, so playbooks may init before Calls, and then the registry function doesn't exist. So let's make the products start first and in a determined order. Then what if calls wants to add a call button in a playbook? It could not, because it is always initialized first and the registry function does not exist. We could try to make a two rounds initialization, or a "on all plugins loaded" kind of hook. But then what happens if we install calls after we had the plugins installed and working? Do we need to disable and reenable them form them to show the information?
> 
> It feels a bit too troublesome, but if you have better ideas, I am always happy to listen :D

I was thinking more like having a generic `registerPluginPluggable` method which takes some string telling the pluggable where to show up rather than having a specific method for each location of the pluggable. We could even go more general and have a `registerPluggable` that semi-replaces all these other methods, but then we lose out on any ability for this code to act as self-documentation. The core web app would still hold onto the data about what's been registered in the same way it does now, so I don't think we'd have any order-of-initialization issues

**Comment by larkox** [comment]
@hmhealey I am going to block the merge, mainly for the calls team to make a decision if they want that in the product, and so on. In the meanwhile, not sure if you want any QA for this PR, or we can skip it.

**Comment by larkox** [comment]
Closing since there is no short-term plan to add this. Can be reopened if there is a change in this.

**Pull request closed without merging**
