### PR TITLE
MM-47849 - show worktemplate tourtip only once

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR makes sure that the tourtip shown after a worktemplate execution is shown only once per user and not on every worktemplate use

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51028

#### Related Pull Requests
Original PR
https://github.com/mattermost/mattermost-webapp/pull/12219

#### Screenshots

https://user-images.githubusercontent.com/10082627/222408535-8c37277a-f67d-45ec-a9f1-a83143a17831.mov

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by pvev** [comment]
@annelieseklein @marianunez @esethna heads up that I included the tourtip styles changes from blue to dark-classic as part of this original PR

**Review by julmondragon — APPROVED** [review]
LGTM! Thanks @pvev

**Comment by stevemudie** [comment]
@pvev I'm not sure why but I'm not able to fully execute a Work Template as I see errors and never have the RHS pop open etc. 😕 

It's this way here on the Spinwick and on test servers as well for some reason.

Thoughts?

**Comment by pvev** [comment]
> @pvev I'm not sure why but I'm not able to fully execute a Work Template as I see errors and never have the RHS pop open etc. 😕
> 
> It's this way here on the Spinwick and on test servers as well for some reason.
> 
> Thoughts?

@stevemudie if you try one of the templates that only load boards you will be able to test this change. Also @marianunez I think this should be cherry-picked to 7.9, right?

**Comment by stevemudie** [comment]
@pvev Thanks for the tip!

It only works — i.e., the tooltip doesn't return — if I click the `Got it` button though and I noticed you clicked the `Done` button in the video demo above as well. 🤔 

Is that expected?

**Comment by pvev** [comment]
> @pvev Thanks for the tip!
> 
> It only works — i.e., the tooltip doesn't return — if I click the `Got it` button though and I noticed you clicked the `Done` button in the video demo above as well. 🤔
> 
> Is that expected?

yes, that is the expected behavior as the other tourtips in the app. The tourtip should be clicked `Done` or `Got it` and then it is going to be discarded, meaning that if it is just ignored by clicking outside or page reloaded, it is going to be shown again in the new template usage. @annelieseklein @marianunez can you please confirm this is the expected behavior?

**Review by JulienTant — APPROVED** [review]
Good job @pvev

**Comment by annelieseklein** [comment]
@pvev i'm unable to open this test server

**Comment by pvev** [comment]
> @pvev i'm unable to open this test server

seems to be down, let me recreate it again

**Comment by annelieseklein** [comment]
@pvev looks great!  i don't think we need the dark overlay

**Review by stevemudie — APPROVED** [review]
Looks good!

**Comment by pvev** [comment]
Migrated to https://github.com/mattermost/mattermost-server/pull/22703

**Pull request closed without merging**
