### PR TITLE
MM - 34503 - new contact sales form option for cloud trial

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
Add new contact sales form option for the cloud trial period

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34503

#### Related Pull Requests
https://github.com/mattermost/customer-web-server/pull/427

#### Screenshots
Captura de pantalla 2021-04-17 a las 18 00 18
Captura de pantalla 2021-04-17 a las 18 01 10

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Review by marianunez — APPROVED** [review]

**Review by stevemudie — COMMENTED** [review]
@pablovelezvidal The Contact Sales link opens the page properly but the pre-selected trial questions text is in the list twice until you select something different. Then it's only there once.
Trial questions listed twice

**Review by stevemudie — APPROVED** [review]
Tested and passed.

New “I have questions about a trial and want to be contacted by an account representative.” wording selected by default when you use the Contact Sales button as expected.

[MM-35082](https://mattermost.atlassian.net/browse/MM-35082) written to address concerns I had above that don't directly affect this PR from passing.

**Pull request merged**
