### PR TITLE
[MM-24729] Fix incorrect highlighting (no box shadown) when tab into the input fields 

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

No highlighting (no box shadown) when you tab into the input fields on the guest and members invite to team pages

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-24729

#### Screenshots

image
image
image

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by michaelgamble — APPROVED** [review]
looks good :)

**Review by deanwhillier — APPROVED** [review]
Approving as a short-term fix. This input component actually needs to be re-structured/styled so that we don't need to negate the a11y border and maintain consistency with it's usage on other inputs.

As discussed, @hahmadia will be creating a followup ticket to update this component with a new input common component once it is ready.

**Review by srkgupta — CHANGES_REQUESTED** [review]
Hi @hahmadia 

I am still able to replicate the issue. The CSS due to incorrect highlighting is actually still rendered from a different place. Please check these screenshots. 

Screenshot 2020-09-22 at 11 17 46 AM

Screenshot 2020-09-22 at 11 19 42 AM

Screenshot 2020-09-22 at 11 18 19 AM

**Review by srkgupta — APPROVED** [review]
Tested and the issue is fixed now and is working fine. Approving the PR

**Pull request merged**
