### PR TITLE
[MM-22858] Include invalid value in username validation message

### PR DESCRIPTION
**Pull request by farah**
#### Summary
 Includes the invalid value in username validation message.

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/14505

Jira ticket: https://mattermost.atlassian.net/browse/MM-22858

### CODE REVIEW

**Comment by farah** [comment]
@hmhealey Thanks. Let me know if there's anything else I need to do on my end. Look forward to working with you again.

**Comment by farah** [comment]
Hi @ nevyangelova, have you had a chance to look at this PR?

**Comment by farah** [comment]
Hi @nevyangelova, have you had a chance to look at this PR?

**Comment by farah** [comment]
Hi guys, just wondering why its taking so long to merge this PR? Do I have to perform an action?

**Comment by nevyangelova** [comment]
Hey @farah we are waiting for the QA check and we will merge the PR after we get the final approval. Sorry for the long wait 🎉 @DHaussermann can you review this?

**Comment by levb** [comment]
Since this is just a text change, do we need @DHaussermann's approval? Conversely, @DHaussermann can you approve?

**Comment by levb** [comment]
@hmhealey @nevyangelova I am not sure of the SOP in webapp - I ran `/update-branch` but the PR is still showing up with 
image - can you please take it from here?

**Comment by nevyangelova** [comment]
@levb seems to have worked, I will keep an eye :)

**Comment by hmhealey** [comment]
Thanks again for the contribution, @farah! It'll be shipping out in our 5.26 release coming in August.

**Comment by farah** [comment]
Thanks @hmhealey!

**Pull request merged**
