### PR TITLE
MM-41327 : Avoid re-rendering of TextboxLinks component on typing

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
This PR includes a fix which reduces the re rending of the TextboxLinks component (see screenshots) on every key type on the its corresponding textbox component. 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41327

Part of [Reduce lag while hovering over posts](https://mattermost.atlassian.net/browse/MM-40113) 

#### Related Pull Requests
N/A

#### Screenshots
Before

https://user-images.githubusercontent.com/17708702/150975089-3d96a72f-2446-4ea8-abd7-7b4dde739d35.mov

After

https://user-images.githubusercontent.com/17708702/150974551-9ff814ff-82d0-4de7-852c-ad158efd7639.mov

#### Release Note

```release-note
Avoid of re rendering of TextBox links component below post box while typing.
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Looks great, but I have some grammar nitpicking. Those new props should both be named `hasX` instead of `haveX`

**Comment by M-ZubairAhmed** [comment]
> Looks great, but I have some grammar nitpicking. Those new props should both be named `hasX` instead of `haveX`

✅  Updated as per request/discussion

**Review by hmhealey — APPROVED** [review]
Perfect, thanks!

**Review by jespino — APPROVED** [review]
Nice refactor. Looks good to me.

**Comment by jgilliam17** [comment]
Thanks for running the E2E @M-ZubairAhmed 
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/108925-99f12c6-onprem-ent-webapp-pr-9697-mattermost/mm-ee-test99f12c6/mochawesome.html)shows a high number of failures compared to master (64 vs. 16)
On a quick glance a lot of the tests that failed are missing `edited` text
Can you please take a look. Thanks 🙂

**Comment by M-ZubairAhmed** [comment]
@jgilliam17 this is the report for this pr e2e https://automation-dashboard.vercel.app/cycles/2932224a-f01c-4c8c-bc71-0e820c92b5af could you let me know if this pr introduced any more new failures. From my point of view i dont think so , but please let me know

**Pull request merged**
