### PR TITLE
Backward compatible fix theme.mentionBg typo

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Change `theme.mentionBj` to `theme.mentionBg` in a backwards compatible manner. Once theme becomes a true server model we can remove the backwards compatibility. Done because theme objects are more customer/user facing with plugins.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-8142

### CODE REVIEW

**Comment by hmhealey** [comment]
Looks good, but it will cause problems for the RN app since it'll still expect the old name when the server is is on a newer version than the app. We had something similar come up when discussing permission stuff, so I'll try to see what our support policy is going to be for that case. It may be that this needs to be delayed for a while until the changes to the RN app are in the wild for a while

**Comment by jwilander** [comment]
Sounds good 👍  let me know if you need anything from me

**Comment by hmhealey** [comment]
Alright, so we do want to maintain some backwards compatibility for the time being. Maybe we can leave both a backwards-compatible mentionBj and add mentionBg for integrations to use? We can also change the getTheme selector to handle either of them so that in a few releases, we can remove mentionBj entirely

**Comment by hmhealey** [comment]
Actually, if integrations will be using getTheme entirely, we can:
1. Modify getTheme to only return a theme with a mentionBg field set to either mentionBg or mentionBj (whichever is present)
2. Have both the web app and mobile app only use mentionBg, except for the web app will also set the mentionBj field when saving themes so that still exists for older mobile apps
3. In a few months, we remove that fallback code and everything will be using mentionBg

**Comment by jwilander** [comment]
Alright, so the action item for this PR is to make sure both `mentionBj` and `mentionBg` are saved in the account settings

Then also a PR to mattermost-redux updating the selector to return mentionBg, using mentionBg if present and mentionBj if not

**Comment by hmhealey** [comment]
Yeah, that's correct. That'll give us the ability for integrations to use the new field, start using the new field in both the web and mobile app, and gives us the ability to remove mentionBj eventually

**Comment by jwilander** [comment]
Cool, I'll make the change here and submit a PR to the redux repo

**Comment by cpanato** [comment]
is the other PR in place?

**Comment by jwilander** [comment]
Not yet, I'll probably get to this on Monday so we can get it in before code complete

**Comment by jwilander** [comment]
@hmhealey @cpanato PR updated and redux PR submitted at mattermost/mattermost-redux#345

**Pull request merged**
