### PR TITLE
[PLT-7364] Ability to Direct Message yourself

### PR DESCRIPTION
**Pull request by cpanato**
I need some help to test and find if this is good in terms of code.
@jasonblais can help me here?

Server PR: https://github.com/mattermost/mattermost-server/pull/7696

#### Summary
 Ability to Direct Message yourself

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/PLT-7364
GitHub: https://github.com/mattermost/mattermost-server/issues/7618

#### Checklist
- [x] Has server changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@cpanato We can get the https://github.com/mattermost/mattermost-redux/pull/282 and https://github.com/mattermost/mattermost-server/pull/7696 PRs reviewed first - once merged we can set up a spinmint for the webapp change

**Comment by cpanato** [comment]
@esethna thanks! The first one I know and I'm trying to fix it. The second I will fix it.
thanks so much for the review

**Comment by jwilander** [comment]
Not to derail this, but I feel like 1. would be very unexpected for the user. The modal suddenly changes behaviour just because I clicked on myself? If anything I think 1. should act more like 2. where if I click myself all the other users disappear instead of just immediately doing something and then I still need to hit Enter or hit Go to initiate a change

In all honestly I think it's going to be confusing if you show yourself in that list at all. I personally think it's much better to have an explicit button or something separate for opening a DM with yourself. 0/5 on what the mechanism is but 4/5 on having it work within the current more DMs list is confusing

**Comment by cpanato** [comment]
@esethna what are your thoughts?

**Comment by esethna** [comment]
Thanks for the comments JW. This design was reviewed in UX and was decided to be the best approach for the feature. I don't necessarily agree that clicking yourself should add you to the input box and hide all other users, since then we would be opening up a new avenue of confusion about "why can't I add more people to my group message". Instead, if you are directed to the self DM directly, there is no confusion about having to add yourself to GMs. We are following Slacks model here which, in my mind, follows the fast (less buttons to click to create a self DM) and obvious (by limiting confusion about having to add yourself to GMs).

**Comment by jwilander** [comment]
I won't say I agree but I'll defer to the UX team.

**Comment by esethna** [comment]
Okay, thanks Joram, this is not for 4.4 so once it merges it will soak for a while.

@cpanato please proceed with the tweaks as per my initial review, thanks for the ping!

**Comment by cpanato** [comment]
@esethna did the changes good to go.
and a big thanks to @jwilander for figure out how to submit the form 🎉  I owe you a beer 🍻

**Comment by jwilander** [comment]
Ready to merge but holding off until the release cut on Monday

**Pull request merged**
