### PR TITLE
Growth channel intro

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Adds a "Create board" button to the Channel Intro section.

#### Ticket Link
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/canqped3rnty78yz9bedq5ka8qe

#### Screenshots
Screen Shot 2022-01-20 at 4 16 16 PM
Screen Shot 2022-01-20 at 4 16 03 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@chenilim @wuwinson Currently clicking on the "Create a board" takes the user to the board created in that workspace.
We can take it if we want. But just wanted to point out that it does not "Create a board", it only Creates a board just the first time I think.

CC @ogi-m

**Comment by wuwinson** [comment]
@asaadmahmood @chenilim Do you see any downsides of directing the user to the template selector dialog? Will allow for a more consistent experience when clicking on that link.

**Comment by asaadmahmood** [comment]
@wuwinson I think it should take the user to the template selector.

**Comment by sbishel** [comment]
@ogi-m - This PR now required changes to Boards. This is the PR for boards, but it doesn't appear you can upload a plugin with a spinwick.
https://github.com/mattermost/focalboard/pull/2181

**Review by BenCookie95 — APPROVED** [review]
Code looks good to me!

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by ogi-m** [comment]
@sbishel  The channel intro buttons are the same as they are currently (without the corresponding boards build), so I'm fine with merging this and testing afterwards.

**Pull request merged**
