### PR TITLE
Cypress/E2E: Update remaining tests for the new config of sidebar organization

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Update remaining tests for the new config of sidebar organization

#### Ticket Link
none, failed on daily Cypress test

### CODE REVIEW

**Review by prapti — APPROVED** [review]

**Comment by prapti** [comment]
Thanks Saturn!

**Review by josephbaylon — APPROVED** [review]
LGTM

**Comment by devinbinnie** [comment]
@saturninoabril The value of `EnableLegacySidebar` is actually a `boolean` now, so all of these will likely evaluate to `true` since they are non-empty strings.

**Comment by saturninoabril** [comment]
Thanks Devin for catching! Will take a look and submit a follow up fix.

**Pull request merged**
