### PR TITLE
Swap order between Romanian and Turkish

### PR DESCRIPTION
**Pull request by jasonblais**
Romanian should be below Portuguese, above Turkish

### CODE REVIEW

**Comment by cpanato** [comment]
@jasonblais need to update the tests

**Comment by jasonblais** [comment]
If I just swap the order and revert the other changes, do I need to update the tests?

**Comment by jasonblais** [comment]
That would be helpful @cpanato :)

**Comment by cpanato** [comment]
@enahum PTAL

**Comment by jasonblais** [comment]
Thanks Carlos! Ready to merge (don't have permissions to merge)

**Pull request merged**
