### PR TITLE
[MM-21960] Fix double highlight when using mouse and keyboard together in Direct Messages > More modal

### PR DESCRIPTION
**Pull request by larkox**
#### Summary

Fix double highlight when using mouse and keyboard together in Direct Messages > More modal
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21960
#### Related Pull Requests

- Fix bug introduced in https://github.com/mattermost/mattermost-webapp/pull/4396

#### Screenshots
None

### CODE REVIEW

**Comment by hmhealey** [comment]
Adding @esethna to this since I don't think removing the hover effect is the correct fix here

**Comment by larkox** [comment]
@hmhealey This change is on top of the work done before. Removing the hover does not remove the actual hover effect. The hover effect is achieved in a different way (changing the class of the elements on mouse move), and the css hover is just making this effect duplicate. That is the reason removing the css hover fixes the problem.

**Comment by deanwhillier** [comment]
Ah, so mouse hovering is still made possible by changing the `selected` class on the elements as the mouse enters/leaves using JS, we're just removing the `:hover` css pseudo-selector that is duplicating the hover detection. That sum it up @larkox?

**Comment by larkox** [comment]
@deanwhillier Yes, that's it. :D

**Comment by hmhealey** [comment]
Thanks for the explanation. This makes sense to me then.

**Comment by hmhealey** [comment]
Removing Eric from the reviews since there's no functional difference

**Pull request merged**
