### PR TITLE
[MM-39060] - A/B Test: Reminder to Join Workspace email

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR is a part of the work done here https://github.com/mattermost/mattermost-server/pull/18894 in order to track successful signups from the email reminders we send to users that're initially invited but join imediately

#### Ticket Link
[MM-39060](https://mattermost.atlassian.net/browse/MM-39060)

#### Related Pull Requests

- Has server changes (https://github.com/mattermost/mattermost-server/pull/18894)

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]

**Review by neallred — APPROVED** [review]
lgtm!

**Review by nickmisasi — APPROVED** [review]
LGTM!

**Comment by AGMETEOR** [comment]
Hi @amyblais this is part of the Invite email A/B test PR. I think we should cherry pick to cloud as well/

**Comment by AGMETEOR** [comment]
Looks like this is also already on the cloud branch 👍🏿

**Pull request merged**
