### PR TITLE
[MM-15039] Revert react-redux to 5.1.1 fixing the issue mostly on profile pop-over and edit channel header components

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Seems to be related to recent update of react-redux to v6.0.1 which might not be compatible with react-bootstrap@0.32.4 (per [react-redux discussion](https://github.com/reduxjs/react-redux/issues/1083#issuecomment-441312159)).

I'd suggest to upgrade react-redux to v6/v7 once react-bootstrap releases the stable version of v1.

#### Ticket Link
Jira - [MM-15039](https://mattermost.atlassian.net/browse/MM-15039)

### CODE REVIEW

**Comment by enahum** [comment]
Saturnino why not upgrading the react-bootstrap library instead?

**Comment by saturninoabril** [comment]
I did try but it's giving me another set of errors.  Besides, it's still in beta - 1.0.0-beta.6.  I don't know if we want that.

**Comment by enahum** [comment]
I think we should move fwd instead of backwards. Having said that I’ll approve just because of the beta version BUT I want to ensure that there is a follow up ticket for this.

**Comment by saturninoabril** [comment]
@enahum I agree.  Ticket filed - https://mattermost.atlassian.net/browse/MM-15040

**Comment by crspeller** [comment]
@saturninoabril @enahum That's going to be quite the ticket. 
Looks like react-bootstrap upgraded to bootstrap 4 for v1: https://react-bootstrap.github.io/migrating/

You might want to consider fixing this now rather than relying on that upgrade.

**Comment by enahum** [comment]
@crspeller I’m with you but in any case I think we should downgrade the react-redux vs as is breaking current functionality and when upgrading again we should make sure everything works, there is no point in upgrading a dependency if we are not addressing the breaking changes.

Then after the issues are fixed we could work on it.

**Comment by saturninoabril** [comment]
Thanks @crspeller @enahum.  I added that comment to https://mattermost.atlassian.net/browse/MM-15040

**Pull request merged**
