### PR TITLE
MM-15586 Bot tag missing for bots in channel switcher 

### PR DESCRIPTION
**Pull request by scottleedavis**
#### Summary
Removes a width 0 style on the bot name in the channel switch suggestion list which puts the BOT badge at the end.

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/10865

### CODE REVIEW

**Comment by scottleedavis** [comment]
@jasonblais I was able to replicate, but only for user created bots.  The BOT badge shows up for plugin created bots.  (replicated on spinmint as well as local)

Screen Shot 2019-05-22 at 3 49 50 PM

I will look further why the badge is not showing up for user created bots.

**Comment by jasonblais** [comment]
It doesn't show up for me for the Remind plugin, on the above spinmint at least

image

**Comment by scottleedavis** [comment]
I believe If you have no message history with the bot, not bot tag.  However if you have any DM history the BOT tag shows up.  There is some logic that only adds the BOT tags if a DM has occurred.

Screen Shot 2019-05-22 at 4 01 07 PM

**Comment by jasonblais** [comment]
@scottleedavis Good find. In fact, it seems as soon as the DM channel with the bot is created in the system, the `BOT` tag shows up in the channel switcher

**Comment by scottleedavis** [comment]
@jasonblais I pushed a changed that I believe solves the non-dm channel with a bot.   

Screen Shot 2019-05-22 at 4 20 26 PM

**Pull request merged**
