### PR TITLE
[MM-31708][MM-31726][MM-31739][MM-31727] - Fix regressions in RHS and Status menu

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR fixes regressions caused by https://github.com/mattermost/mattermost-webapp/pull/7029 and other style changes. I added a fix for the 'focussed' typo

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31708
https://mattermost.atlassian.net/browse/MM-31726
https://mattermost.atlassian.net/browse/MM-31739
https://mattermost.atlassian.net/browse/MM-31727

Fix v. Cloud (January 12)

### CODE REVIEW

**Comment by amyblais** [comment]
To be cherry-picked to ``cloud`` for Jan 12th release.

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Seeing one issue related to https://mattermost.atlassian.net/browse/MM-31727
For the top post on the RHS, hover effect is not extended up to the date separator line. Here's community screenshot for comparison.
on community
and on test server
Screen Shot 2021-01-07 at 10 59 30 AM

**Comment by nevyangelova** [comment]
@jgilliam17 fixed

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 
Tested, looks good to merge.
- Verified search dropdown is not triggered for plugins and when opening RHS.
- Verified file drag and drop works in RHS
- Verified status icons are aligned
- Verified margins around the RHS date separator and textbox

**Comment by amyblais** [comment]
@hmhealey @calebroseland Kind note to prioritize reviews for Cloud January 12th release.

**Review by calebroseland — APPROVED** [review]

**Comment by calebroseland** [comment]
@nevyangelova does this handle where the suggestion list opens when the github plugin is opened? 
CleanShot 2021-01-08 at 13 03 50

(Observed on daily)

**Review by cpoile — APPROVED** [review]

**Comment by cpoile** [comment]
@calebroseland It should -- I tested it with the Incident Managment plugin, which opens the RHS and was having the same problem. I reviewed because Harrison is busy for a bit, and it probably should have be elevated to SET (it's affecting the IM e2e tests). Thanks!

**Comment by calebroseland** [comment]
@cpoile can confirml. Realized it repro'd with the Incident Management and found the same. Thanks!

**Pull request merged**
