### PR TITLE
chore: upgrade to cypress@11.2.0 and its dependencies

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Upgraded to cypress@11.2.0 and its dependencies

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]
LGTM! 

This addresses also the PR https://github.com/mattermost/mattermost-webapp/pull/11655

**Review by yasserfaraazkhan — APPROVED** [review]
💯

**Review by furqanmlk — APPROVED** [review]

**Pull request merged**
