### PR TITLE
Cypress/E2E: Fix failed tests in prod

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Failed on daily Cypress prod test

#### Screenshots
Screen Shot 2021-08-03 at 6 27 44 PM
Screen Shot 2021-08-03 at 7 28 22 PM
Screen Shot 2021-08-03 at 7 29 42 PM
Screen Shot 2021-08-03 at 7 31 43 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by furqanmlk — COMMENTED** [review]
Thanks @saturninoabril every thing look good except one test case,
`M-T2345 /me on RHS`

image


image

image

image

**Comment by saturninoabril** [comment]
> Thanks @saturninoabril every thing look good except one test case,
> `M-T2345 /me on RHS`

I see. Looks like it's due the `CollapsedThreads` enabled on your setup. Currently, we're running both local and prod with that as not set or disabled. We'll have it enable for sure for cases as required.

**Review by josephbaylon — CHANGES_REQUESTED** [review]
@saturninoabril I'm getting this failure consistently on `MM-T2345`

Screen Shot 2021-08-04 at 9 11 44 AM

**Comment by furqanmlk** [comment]
> > Thanks @saturninoabril every thing look good except one test case,
> > `M-T2345 /me on RHS`
> 
> I see. Looks like it's due to the `CollapsedThreads` enabled on your setup. Currently, we're running both local and prod with that as not set or disabled. We'll have it enable for sure for cases as required.

Thanks @saturninoabril after disabling  `CollapsedThread` setting passed.
I am wondering how did you figure out ?

**Review by furqanmlk — APPROVED** [review]

**Comment by saturninoabril** [comment]
@furqanmlk I noticed from your screenshot :)

@josephbaylon Good catch! Probably due to the recent app change. Update, PTAL.
Screen Shot 2021-08-05 at 12 31 08 PM

**Review by josephbaylon — APPROVED** [review]
LGTM. Tests passed locally

**Pull request merged**
