### PR TITLE
MM-19811 Add Mark as Unread to RHS 

### PR DESCRIPTION
**Pull request by hmhealey**
There was a conflict in the original spec which made it unclear whether or not the RHS should have the Mark as Unread options. This changes it so that both the RHS and centre channel have the option.

@andrewbrown00 Let me know how this feels. While I like having both the RHS and centre channel providing different options, now that I've tried it out, it feels strange now that I've played around with it some more.F

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19811

### CODE REVIEW

**Comment by hmhealey** [comment]
> system messages change the cursor to a pointer, since you shouldn't mark them I don't think we should change the cursor.

Oh yeah, that sounds like a bug. I'll file a followup since that'll affect both of these PRs.

> when clicking on the post it wasn't marked as unread, not sure if the server has all the changes needed for it.

Yeah, that's intended. Test servers just run the corresponding master branch of the other repo

**Comment by hmhealey** [comment]
> > system messages change the cursor to a pointer, since you shouldn't mark them I don't think we should change the cursor.

> Oh yeah, that sounds like a bug. I'll file a followup since that'll affect both of these PRs.

Actually, I checked with Andrew, and we want to show the cursor for all posts since you can technically mark a channel as unread from a system message, even though it'll move the New Messages line

**Comment by Willyfrog** [comment]
as I said, LGTM and if what I found was intended, no problem on my side :D

**Comment by hmhealey** [comment]
Removing the UX review from this since the test server doesn't have the required serverside code to test this

**Pull request merged**
