### PR TITLE
Feature: In-product support for Cloud Trial

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Feature branch merge to support cloud 14-day trial subscriptions in Subscriptions section in the System Console with corresponding in-product banner notifications. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34441
https://mattermost.atlassian.net/browse/MM-34505
https://mattermost.atlassian.net/browse/MM-34506

#### Related Pull Requests

Server feature branch PR: https://github.com/mattermost/mattermost-server/pull/17397
Customer Portal branch: https://github.com/mattermost/customer-web-server/tree/feature/cloud_trial_multiple_skus

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Comment by marianunez** [comment]
@stevemudie heads up this is the feature PR for Cloud Trial for webapp, we can do a test once merged and the customer portal can create trial workspaces

**Review by pablovelezvidal — APPROVED** [review]

**Comment by marianunez** [comment]
@nickmisasi can you help configure the subscription for this pr https://dashboard.stripe.com/test/subscriptions/sub_JITmVTRRWWCXAL to be a trial so @annelieseklein can get a final feature UX pass before we merge to master

**Comment by nickmisasi** [comment]
@marianunez added a 3 day trial. @annelieseklein let me know if you want to increase/decrease the amount of time left in the trial.

**Comment by marianunez** [comment]
Just realized we can't test this yet because the portal is not updated with the new `is_trial` calculations. 

Apologies @annelieseklein, we can do the feature UX review once we merge and get the customer portal updated as well.

**Comment by marianunez** [comment]
@amyblais heads up this is the cloud 14 day feature that we are merging and need to cherry pick to cloud. The feature will be turned on/off from the portal based on the release testing this week.

**Pull request merged**
