### PR TITLE
[MM-37497] Rename view image modal to file preview modal and change imports

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
As part of new file preview modal ui changes [MM-12104](https://mattermost.atlassian.net/browse/MM-12104), Changing the preview modal name from view image modal to file preview modal. We show variety of files (pdf) using that component, so name is little misleading.

#### Ticket Link
[https://mattermost.atlassian.net/browse/MM-37497](https://mattermost.atlassian.net/browse/MM-37497)

#### Related Pull Requests
* None

#### Screenshots
Screenshot 2021-07-29 at 8 21 17 AM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — COMMENTED** [review]
LGTM! one question, do we need to add a release note for this change,
Is it considered a breaking change? cc @hmhealey

**Review by hmhealey — APPROVED** [review]
Looks good to me! I appreciate breaking out these changes since it'll help keep everything cleaner later.

**Comment by hmhealey** [comment]
I don't think this needs to be in the release notes since it won't have any effect on users yet

**Comment by AshishDhama** [comment]
> I don't think this needs to be in the release notes since it won't have any effect on users yet

@hmhealey Should I remove the release note then.

**Comment by hmhealey** [comment]
Yeah, please do. I think those end up in [the changelog](https://docs.mattermost.com/install/self-managed-changelog.html), so they only need to be things that end users will actually care about. The actual technical details we need are in the commit messages themselves.

**Review by koox00 — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @AshishDhama 
Tested, looks good to merge.
- Verified/tested file and image preview - as before.
Found few issues that also reproduce on master, filed separately 
MM-37565
MM-37566
MM-37567

**Comment by AshishDhama** [comment]
> Thanks @AshishDhama
> Tested, looks good to merge.
> 
> * Verified/tested file and image preview - as before.
>   Found few issues that also reproduce on master, filed separately
>   MM-37565
>   MM-37566
>   MM-37567

@jgilliam17 Thanks will check if we can fix these as part of parent ticket.

**Comment by cwarnermm** [comment]
@AshishDhama - This PR may have API documentation impact. Are you open to review and update the API docs as needed?

**Comment by AshishDhama** [comment]
> @AshishDhama - This PR may have API documentation impact. Are you open to review and update the API docs as needed?

@cwarnermm sure I will check the documents if there will something that needs to be updated will do that.

**Comment by AshishDhama** [comment]
@cwarnermm This pr doesn’t contains any api changes, Actually in this pr we have just renamed the ``Image view modal`` to ``file preview modal``. So only renaming No changes in UI as well

**Comment by hmhealey** [comment]
Yeah, I don't think this has any effects on documented APIs unless plugins are doing something wonky to access it directly.

**Pull request merged**
