### PR TITLE
MM-36965 - Refactor all tracking events into groups of constants

### PR DESCRIPTION
**Pull request by MichaelAnckaert**
#### Summary

This PR refactors the Telemetry categories and events to be defined as constants instead of hard coded strings. 

#### Ticket Link

GH Issue: #18578
Jira Issue: [MM-36965]

#### Note

There is a lot of opportunity here to restructure the Telemetry categories and events. Right now this is a very naive refactoring in the sense it only removes the hard coded strings and replaces them with constants. Depending on the business case there are a lot of opportunities to make the `trackEvent` function better, consolidate events or make other improvements. 

[MM-36965]: https://mattermost.atlassian.net/browse/MM-36965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @MichaelAnckaert

**Comment by koox00** [comment]
It seems there are conflicting files, can you fix those as well?

**Comment by neallred** [comment]
Thanks @MichaelAnckaert ! I agree with everything @koox00 said. I think the [PR](https://github.com/MichaelAnckaert/mattermost-webapp/pull/1) I opened against your fork resolves the conflicts and missing imports.

**Comment by Willyfrog** [comment]
Hi @MichaelAnckaert do you have any questions regarding the feedback?

**Comment by neallred** [comment]
Closing because of lack of activity.

**Pull request closed without merging**
