### PR TITLE
E2E/Playwright: Restructure page and components model and page closing

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Added base setup for Calls E2E test
- Added test cases based from:
  - https://github.com/mattermost/mattermost-plugin-calls/blob/main/e2e/tests/global_widget.spec.ts
  - https://github.com/mattermost/mattermost-plugin-calls/blob/main/e2e/tests/join_call.spec.ts (added one more case for RHS post)

Notes:
- ~~This PR is submitted on top of https://github.com/mattermost/mattermost-webapp/pull/12237 and will rebase once the said PR is merged.~~ (done)
- ~~Test cases have pending PR. Once merged and saved to Zephyr, test cases here will be updated accordingly - https://github.com/mattermost/mattermost-test-management/pull/76~~ (done - [MM-T5399](https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/calls/MM-T5399.md) and [MM-T5400](https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/calls/MM-T5400.md))

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]

**Comment by saturninoabril** [comment]
@mvitale1989 @cpoile Gentle reminder for your reviews. Looking forward to merge this soon so this will be included with the upcoming monorepo changes.

**Review by mvitale1989 — APPROVED** [review]
lgtm as well, thanks @saturninoabril !

**Comment by saturninoabril** [comment]
@hmhealey Could this still be added to monorepo? I was hoping to get this in since it fixes some of the base Playwright setup but it's fine if not as I understand the additional overhead it brings with your on going work/branch.

**Comment by hmhealey** [comment]
It'll have to wait for the monorepo to be merged into master on the server repo. If you want to start porting this over though, you can make your changes against the `mono-repo` branch on it to confirm it works. I haven't actually tested the E2E tests over there, so hopefully they still work. I can't see any reason why they would've broken though

**Comment by saturninoabril** [comment]
Thanks @hmhealey and well noted.

**Comment by saturninoabril** [comment]
Closed in favor of https://github.com/mattermost/mattermost-server/pull/22602

**Pull request closed without merging**
