### PR TITLE
Adds public routes for products, that do not require the user to be logged in

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR adds the concept of public routes to products. It adds a property to the product structure and registry method to pass a `publicComponent` at registration time and creates a public route with that component that can be accessed by non logged in users.

#### Release Note
```release-note
* Adds the capability for products to serve public routes accessible by non logged in users
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Are we sure this should go into 7.8? I thought 7.8 wasn't getting any new features

**Review by mickmister — APPROVED** [review]
Awesome!

**Comment by mickmister** [comment]
Wondering if we can include a unit or e2e test for this PR

**Comment by mgdelacroix** [comment]
@mickmister test added on https://github.com/mattermost/mattermost-webapp/pull/12021/commits/5701fbf94c3ee23a7fce2ba6273d849f1c98f9dd
@hmhealey @amyblais the reason to include this on `v7.8` is that with the change to product mode we lose the ability to expose public routes that we had with plugin mode. If we don't add this mechanism and ship boards as a product, we will break the share public board feature for `v7.8`

**Comment by amyblais** [comment]
@mgdelacroix Please help fix failing tests and add appropriate QA reviewer.

**Comment by mgdelacroix** [comment]
@ogi-m QA should be done together with https://github.com/mattermost/focalboard/pull/4519 for product mode

**Comment by amyblais** [comment]
This is no longer needed for v7.8 as Boards is reverted back to plugin mode.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by M-ZubairAhmed** [comment]
Hello there! Could you please open the PR in the mattermost-server as part of the monorepo? I will be closing this PR for now. Thank you very much for your understanding and cooperation in this matter.

**Pull request closed without merging**
