### PR TITLE
Allow default team to be configured

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
These changes depend the config value  "DefaultTeamName" was added allows to be able to config the name of a default team. It adds:
- Admin for "DefaultTeamName" config.
- In `login_controller.jsx`, if user is already logged in and there's a value is set then redirect to that team. Also, after finishing sign in, if there's not a team, redirect to the default team.
- In `root.jsx`, if it needs a redirect then check to see if user is logged in and a value set, then redirect to the default team.
- Hides `Leave Team` from LHS and RHS menus.

Depends on this `mattermost-server` PR:
https://github.com/mattermost/mattermost-server/pull/7846

cc @dmeza 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [x] Has server changes (please link)
- [ ] Has redux changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by dmeza** [comment]
@esethna rebased to latest from master. Also the `server` changes: https://github.com/mattermost/mattermost-server/pull/7846

**Comment by dmeza** [comment]
@esethna rebased to latest from master

**Comment by esethna** [comment]
Thanks @dmeza just awaiting the server PR to merge so I can test this

**Comment by esethna** [comment]
@jwilander can I please have your help setting the config for default team to the "Main" team?

**Comment by jwilander** [comment]
Done, `DefaultTeamName` set to "Main"

**Comment by dmeza** [comment]
@esethna could this get reviewed and merged this week? cc @csduarte

**Comment by dmeza** [comment]
@lfbrock please help review this ticket. The server side changes are already merged to master: https://github.com/mattermost/mattermost-server/pull/7846

**Comment by dmeza** [comment]
@lfbrock please help us test these PR. The server side changes are already merged to master: https://github.com/mattermost/mattermost-server/pull/7846

**Comment by dmeza** [comment]
@lfbrock rebased to latest from master and fixed the name of the variable to store from admin. It's working now.

**Comment by lfbrock** [comment]
@dmeza - I tested this creating a user through the api (/api/v4/users) and through SAML, and each time I still ended up on the team selection page instead of added to the default team. 

Can you confirm that this PR is working for you, or let me know if there's something I'm testing incorrectly?

**Comment by dmeza** [comment]
@lfbrock discussed with @csduarte. He explained that the feature is thought out as the user already being joined to the team via the API. The user wouldn't have the option to choose other teams or leave teams. That's why it doesn't have that logic.
Would it help to rename the variable to something else so that it's clearer?

**Comment by lfbrock** [comment]
@dmeza - for now, can we hide the System Console setting and call the config setting "ExperimentalPrimaryTeam"? 

---

Just to share some long term thoughts for this, I think we may want to consider: 
1. Making a separate setting to prevent users from leaving teams, since it's not immediately obvious why this would be tied to a setting selecting a main/default team
    - Also consider whether this would block users from joining teams or not, since joining is already controlled in the Team Settings by the `Allow any user with an account on this server to join this team` setting
2. Decide whether the primary team setting is still needed after we fix this ticket to [direct users to the team they last viewed](https://mattermost.atlassian.net/browse/PLT-6157) when they log in

But for the short term, I think if we call it experimental and hide the System Console setting that would be the best way to get it merged in.

**Comment by dmeza** [comment]
@lfbrock renaming `DefaultTeamName` to `ExperimentalPrimaryTeam`. I have to make a server side PR.

**Comment by lfbrock** [comment]
@dmeza that's okay, I think it's worth the added clarity since we get requests from other people to add default teams users will automatically join and they might get confused about what the setting does.

**Comment by dmeza** [comment]
@lfbrock @jwilander ready the changes requested to `Rename DefaultTeamName to ExperimentalPrimaryTeam`.
This is the server side PR: https://github.com/mattermost/mattermost-server/pull/8039

**Pull request merged**
