### PR TITLE
MM-34366: Wip: Migrate 'components/post_view/post_list_virtualized' and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by naftalimurgor**
#### Summary

This pull request makes TypeScript type definitions available for `DynamicSizeList` component which used in `PostList` component in `components/post_view/post_list_virtualized.jsx`
This is work in progress for this issue https://github.com/mattermost/mattermost-server/issues/17289 

#### Ticket Link

JIRA: https://mattermost.atlassian.net/browse/MM-34366
issue: https://github.com/mattermost/mattermost-server/issues/17289
#### Related Pull Requests

- Has no server changes
- Has no mobile changes

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
@naftalimurgor Thanks for the PR! I assume this is still a WIP?

**Comment by naftalimurgor** [comment]
@devinbinnie Yup, It's a WIP.

**Comment by devinbinnie** [comment]
Hey @naftalimurgor, just wondering how things are going/if you had any questions to get this moved along.

**Comment by naftalimurgor** [comment]
Hey @devinbinnie 
Currently I have two questions, but first, my appologies, I got so busy. There are two more git Pull Request to address this issue:- On that:
1. Migrate `components/post_view/post_list_virtualized.jsx` to TypeScript
2. Migrate `components/post_view/post_list_virtualiz.test.ed.jsx` to TypeScript
Will submit them in that order.

**Comment by naftalimurgor** [comment]
My questions are kinda ambigous, bear with me,
1. I branched from master, create a branch named `MM-34346`, my question is: how do just change the file extensions from `.jsx` to `.tsx` for both branches at a go? Like simultaneously? Then do the changes?
2. I'm still kind of new to git.
3. Here's what I did:
4. I worked on the branch, and made the migration, if I merged the changes, I'll end up having both `.jsx` files and `.tsx` existing side by side. Kindly help clarify this.

Thanks

**Comment by devinbinnie** [comment]
> My questions are kinda ambigous, bear with me,
> 
> 1. I branched from master, create a branch named `MM-34346`, my question is: how do just change the file extensions from `.jsx` to `.tsx` for both branches at a go? Like simultaneously? Then do the changes?
> 2. I'm still kind of new to git.
> 3. Here's what I did:
> 4. I worked on the branch, and made the migration, if I merged the changes, I'll end up having both `.jsx` files and `.tsx` existing side by side. Kindly help clarify this.
> 
> Thanks

No worries @naftalimurgor. So what you would want to do is rename the files using the new extension, and then in the same commit, do a `git rm` on the `.jsx` file and then a `git add` on the `.tsx` file.

As a suggestion, if you use an editor like Visual Studio Code and stage the changes altogether, it should do all of this for you.

**Comment by naftalimurgor** [comment]
Thanks @devinbinnie  for the insight. Will submit the above mentioned PRs so we can move foward with this issue.

**Comment by naftalimurgor** [comment]
Hey @devinbinnie 
The PR is ready, however `ci/circleci: type-check` keeps failing despite adding `@types/react-virtualized-auto-sizer` by running: `npm i --save-dev @types/react-virtualized-auto-sizer`.
 Any insights are highly welcome on resolving this issue.
Thank you.

**Pull request closed without merging**
