### PR TITLE
[MM-24338] - Render plugins section only when components are present in state

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Fix the condition that drives the render of the plugin subsection 
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24338

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Comment by jgilliam17** [comment]
Removing myself, since there's one QA reviewer already added. 😀Thanks @prapti

**Review by hmhealey — APPROVED** [review]

**Review by prapti — APPROVED** [review]
Looks good. Couldn't repro the original issue.

**Pull request merged**
