### PR TITLE
Cypress/E2E: fix SAML/Keycloak and other tests for v6

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Fixed and cleaned up SAML tests
- Made SAML test users dynamic and unique
- Fixed other tests

Test report - https://mm-cypress-report.s3.amazonaws.com/46199-08cc1df-ee-ent-webapp-pr-8955-mattermost-enterprise-edition:08cc1df/mochawesome.html

#### Screenshots
Screen Shot 2021-09-24 at 7 44 18 PM
Screen Shot 2021-09-24 at 7 46 44 PM
Screen Shot 2021-09-24 at 7 55 58 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by metanerd — APPROVED** [review]
Awesome work! Thank you!

**Review by josephbaylon — APPROVED** [review]
LGTM

**Review by furqanmlk — COMMENTED** [review]
Thanks @saturninoabril All tests passed

Except that I had to create `ldap` folder manually.

As discussed, I will approve it when you commit the changes.


image

image


image

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril 
Looks good now :)

image

**Pull request merged**
