### PR TITLE
MM-44979_Move Create Account link closer to login container

### PR DESCRIPTION
**Pull request by julmondragon**
#### Summary
Move Login/Signup alternate links closer to the main content of the page.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44979

#### Design
https://www.figma.com/file/PZuUUM5KPZtGS4YiJYvgSg/MM-44979-Move-Create-Account-Button?node-id=0%3A1

##### Login
Screen Shot 2022-07-06 at 7 36 56 PM

##### Login (Mobile)
Screen Shot 2022-07-06 at 7 37 35 PM

##### Signup
Screen Shot 2022-07-06 at 7 38 07 PM

##### Signup (Mobile)
Screen Shot 2022-07-06 at 7 37 52 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
LGTM! thanks @julmondragon

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
This is great, thank you @julmondragon!

One minor thing:
- Between 1020px and 1200px, I think we can anchor this link back to the top-right corner the same way we do below 1020. Right now, it feels like it's just kind of floating where it is right now at this breakpoint. It also seems to be pushing the main content down unnecessarily. 

image

**Review by JulienTant — APPROVED** [review]
Thanks Julian!

**Comment by julmondragon** [comment]
> This is great, thank you @julmondragon!
> 
> One minor thing:
> 
> * Between 1020px and 1200px, I think we can anchor this link back to the top-right corner the same way we do below 1020. Right now, it feels like it's just kind of floating where it is right now at this breakpoint. It also seems to be pushing the main content down unnecessarily.
> 
> image

@matthewbirtch  This has been addressed as discussed offline.

**Review by matthewbirtch — APPROVED** [review]

**Pull request merged**
