### PR TITLE
MM-12803 - Fixing permanent banner styling

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-12803 - Fixing permanent banner styling

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12803

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@asaadmahmood I took a look and now it looks like when the banner is dismissable, the padding below the banner text is missing:

banner-padding

**Comment by asaadmahmood** [comment]
@lindalumitchell Have a look again.

**Comment by lindalumitchell** [comment]
Thanks @asaadmahmood, I took another look on a new spinmint, but now it looks like it's showing the original issue again: When non-dismissable, the banner covers some content:

screen shot 2018-11-05 at 10 15 20 am

**Comment by asaadmahmood** [comment]
Looks like those changes happened because of some recent changes that @crspeller did. Let me see what happened.

**Comment by asaadmahmood** [comment]
@lindalumitchell Talked to @crspeller The changes that he did are not in for 5.5. So we can get my changes in for 5.5 and test it on the 5.5 RC. It should work fine there.

**Comment by lindalumitchell** [comment]
Ah I see, thanks @asaadmahmood. Which means we may need a v5.6 ticket then? I can follow up on that. So let's get this merged in for the 5.5 RC and we'll test it there as you said. Thanks!

**Comment by lindalumitchell** [comment]
(Notes for reference) Thanks Asaad; I see you put in a ticket for v5.6 (MM-12902). So we'll test this on RC2 after this PR is merged. Looks like Amy labeled it Ready to Merge, and it's also Cherry Pick Approved.

**Pull request merged**
