### PR TITLE
Update and improved root.html

### PR DESCRIPTION
**Pull request by HemantL04**
#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Comment by HemantL04** [comment]
> Hello @HemantL04,
> 
> Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).
> 
> Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.
> 
> **Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
> Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.
> 
> This is a standard procedure for many open source projects.
> 
> Please let us know if you have any questions.
> 
> We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

check-cla

**Comment by jasonblais** [comment]
Hi @HemantL04, thanks for your contribution! Can you help share more information about your changes, or help link to a ticket you worked off of?

**Comment by jasonblais** [comment]
@HemantL04 Thanks for the pull request! We appreciate your contribution, but these changes aren't applicable at this time. If you are looking for good ways to contribute to hacktoberfest, see https://mattermost.com/hacktoberfest/ to get started.

If you did work from an open GitHub issue, let us know and I'll reopen this pull request for reviews. Thank you!

**Pull request closed without merging**
