### PR TITLE
[MM-39792] - Add tab focus to global header heading and user avatar

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Add tab focus to elements in the global header - product heading and user avatar.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39792

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM

**Review by calebroseland — APPROVED** [review]

**Review by calebroseland — COMMENTED** [review]
Though I would like to comment that perhaps `.MenuWrapper` should be the item that gets focused, as that's what's actually clickable. 
(There's also now dual focus for the same item; e.g. if the img is focused, space/enter won't do anything.)
CleanShot 2021-11-18 at 16 43 43@2x
)

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified tabbing through global header items works as expected.

**Comment by jgilliam17** [comment]
@nevyangelova I didn't merge due to comment from Caleb above.

**Comment by nevyangelova** [comment]
@jgilliam17 thanks, sorry I forgot to respond to @calebroseland - when i tested this suggestion the avatar alt didn't get read out.

**Pull request merged**
