### PR TITLE
[MM-35780] - Update add users to channel modal test case

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Update test case to show the status wrapper which is present on the profile picture in the users row within Add users to channel modal. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35780

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Looks good. I'll let Saturn have the final say from QA perspective.
I updated Zephyr test case steps and any necessary with the change.

**Review by jgilliam17 — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks @nevyangelova!

**Pull request merged**
