### PR TITLE
Change SVG images to PNG

### PR DESCRIPTION
**Pull request by jp0707**
#### Summary
Change SVG images to PNG as SVG images don't work with gmail's image proxy!

Reference: https://stackoverflow.com/questions/20815613/svg-images-blocked-by-gmail-proxy

#### Ticket Link

mattermost/mattermost-server#15906

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
I compared the images, and they all look the same. 
The only question is if we probably will have problems with sizing, since `png` files are not vectors and most likely will look bulky when resized.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Hi @jp0707. It looks like the resolution on some of the images might be too small. These images won't look sharp on high-resolution screens. 

Can we ensure that the images we export will be 2x the size of the dimensions they will be scaled to in the emails? The logo in particular looks small to me, but some of the other images may also not look sharp in the rendered emails on retina displays.

**Comment by michelengelen** [comment]
> Hi @jp0707. It looks like the resolution on some of the images might be too small. These images won't look sharp on high-resolution screens. 
> 
> 
> 
> Can we ensure that the images we export will be 2x the size of the dimensions they will be scaled to in the emails? The logo in particular looks small to me, but some of the other images may also not look sharp in the rendered emails on retina displays.

That's what I have feared as well.

**Comment by jp0707** [comment]
Done. Please take a look

**Comment by michelengelen** [comment]
@matthewbirtch do we have any guidance on the dimensions the images **can** take in the emails? Or are they dynamically sized?

**Review by nevyangelova — APPROVED** [review]

**Comment by matthewbirtch** [comment]
> @matthewbirtch do we have any guidance on the dimensions the images **can** take in the emails? Or are they dynamically sized?

Here are the dimensions I would have expected based on the email designs and exporting them at 2x the size:

**Logo**
- designed at: 132x22
- @2x export size: 264x44

**Invite Illustration**
- designed at: 320x212
- @2x export size: 640x424

**Forgot Password Illustration**
- designed at: 350x234
- @2x export size: 700x468

**Welcome Illustration**
- designed at: 320x214
- @2x export size: 640x428

**Comment by jp0707** [comment]
@matthewbirtch Done. Exported 2x images.

**Review by matthewbirtch — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @jp0707 
Looks good to merge.

**Pull request merged**
