### PR TITLE
GH-16149: Typescript components/youtube_video

### PR DESCRIPTION
**Pull request by swatikothari**
Fixes https://github.com/mattermost/mattermost-server/issues/16149

### CODE REVIEW

**Comment by hanzei** [comment]
@swatikothari Thanks for the contribution :tada: 

Heads up that CI reported two type errors:
```
components/youtube_video/index.ts:29:41 - error TS2345: Argument of type 'typeof YoutubeVideo' is not assignable to parameter of type 'ComponentType<Matching<{ currentChannelId: string; googleDeveloperKey: string | undefined; hasImageProxy: boolean; metadata: OpenGraphMetadata | undefined; } & DispatchProp<AnyAction>, ClassAttributes<...> & Props>>'.
  Type 'typeof YoutubeVideo' is not assignable to type 'ComponentClass<Matching<{ currentChannelId: string; googleDeveloperKey: string | undefined; hasImageProxy: boolean; metadata: OpenGraphMetadata | undefined; } & DispatchProp<AnyAction>, ClassAttributes<...> & Props>, any>'.
    Types of property 'getDerivedStateFromProps' are incompatible.
      Type '(props: Props, state: State) => State | null' is not assignable to type 'GetDerivedStateFromProps<Matching<{ currentChannelId: string; googleDeveloperKey: string | undefined; hasImageProxy: boolean; metadata: OpenGraphMetadata | undefined; } & DispatchProp<AnyAction>, ClassAttributes<...> & Props>, any>'.
        Types of parameters 'props' and 'nextProps' are incompatible.
          Type 'Readonly<Matching<{ currentChannelId: string; googleDeveloperKey: string | undefined; hasImageProxy: boolean; metadata: OpenGraphMetadata | undefined; } & DispatchProp<AnyAction>, ClassAttributes<...> & Props>>' is not assignable to type 'Props'.
            Types of property 'metadata' are incompatible.
              Type 'OpenGraphMetadata | undefined' is not assignable to type '{ title: string; images: [{ secure_url?: string | undefined; url?: string | undefined; }]; }'.
                Type 'undefined' is not assignable to type '{ title: string; images: [{ secure_url?: string | undefined; url?: string | undefined; }]; }'.

29 export default connect(mapStateToProps)(YoutubeVideo);
                                           ~~~~~~~~~~~~

components/youtube_video/youtube_video.tsx:79:21 - error TS2322: Type '{ src: string; width: string; height: string; type: string; frameBorder: string; allowFullScreen: true; }' is not assignable to type 'DetailedHTMLProps<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>'.
  Property 'type' does not exist on type 'DetailedHTMLProps<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>'.

79                     type='text/html'
                       ~~~~
```

**Review by nevyangelova — APPROVED** [review]

**Review by nevyangelova — CHANGES_REQUESTED** [review]
Hey thanks for the contribution 🎉 seems like some props are missing in your type definition. Also the second error suggest that something renders as 'undefined' could we check the conditional rendering?

**Review by nickmisasi — COMMENTED** [review]
@swatikothari Code looks good so far, just a few issues that @nevyangelova mentioned with the tests. Let us know if you need any help!

**Comment by swatikothari** [comment]
Thanks for the review, I will address around this weekend.

**Comment by jfrerich** [comment]
Hi @swatikothari and thanks for the PR!  Could you also fix the merge conflicts that are listed?  Thanks!

**Comment by devinbinnie** [comment]
Closing this PR as inactive, @swatikothari let us know if you still plan to finish up this PR.

**Pull request closed without merging**
