### PR TITLE
MM-10431 - Updating UI for post controls

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-10431 - Updating UI for post controls

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10431

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

**Before:**
screen shot 2018-05-02 at 2 01 06 pm

**After:**
screen shot 2018-05-02 at 1 53 23 pm

### CODE REVIEW

**Comment by jasonblais** [comment]
@asaadmahmood This is because the [...] is missing. https://mattermost.atlassian.net/browse/MM-10324

Not sure if we want to make this change regardless though.

**Comment by hmhealey** [comment]
As long as it still looks correct with all 3 icons, we could take it. It's possible to end up with only 2 icons there when you're in the town square with the read only mode turned on.

**Comment by asaadmahmood** [comment]
@jasonblais I know, but that exactly is what is messing it up, it is changing the position of the emoji reactions and adding a weird space.

**Comment by asaadmahmood** [comment]
And yes it looks correct with those 3 buttons.
screen shot 2018-05-02 at 10 29 47 pm

**Pull request merged**
