### PR TITLE
MM-18818 Prompt admins to set the Support Email

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Admin Advisor now prompts system admins if _support email_ is not configured.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18818

#### Related Pull Requests
- Has server changes - https://github.com/mattermost/mattermost-server/pull/17296

#### Screenshots
Screenshot 2021-03-30 at 10 59 10 AM

#### Release Notes

```release-notes
Prompt admins to set support email
```

### CODE REVIEW

**Review by BenCookie95 — COMMENTED** [review]
Do we have a test that actually checks if admin advisor sends the SupportEmail prompt?

**Review by BenCookie95 — APPROVED** [review]

**Review by hahmadia — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected, Test plan has been updated

image

**Comment by harshilsharma63** [comment]
Do not merge this yet. I'll be making a change in this to sync with the disabled Admin Advisor.

**Comment by cpanato** [comment]
and we are on rate limit again

**Comment by harshilsharma63** [comment]
> and we are on rate limit again

I can just for a while. This is nothing urgent or critical.

**Comment by cpanato** [comment]
all good now @harshilsharma63 just need a release note or if don't need you can make a comment with `/release-note-none`

**Pull request merged**
