### PR TITLE
[MM-42133]: added new action buttons to the edit post view

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
@see title! :D

#### Ticket Link
[MM-42133](https://mattermost.atlassian.net/browse/MM-42133)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @michelengelen! Looks good. A few minor tweaks:

1. Can we make the label on the `Cancel` button Semibold?
2. Can we add 4px of space under the Save/Cancel buttons? Looks like the margin is 4px on the button, but can we make it 8px?
3. For the help text `ENTER to Save, ESC to Cancel`, can we make that 12px

Other than that, it looks good I think!

**Review by neallred — APPROVED** [review]
LGTM, thanks @michelengelen !

**Comment by matthewbirtch** [comment]
> 3\. For the help text `ENTER to Save, ESC to Cancel`, can we make that 12px

Sorry @michelengelen this change was not written very clearly. I meant to make the font size for the help text `font-size: 12px;`

**Comment by michelengelen** [comment]
> > 3\. For the help text `ENTER to Save, ESC to Cancel`, can we make that 12px
> 
> 
> 
> Sorry @michelengelen this change was not written very clearly. I meant to make the font size for the help text `font-size: 12px;`

No problem!

**Review by matthewbirtch — APPROVED** [review]

**Comment by jgilliam17** [comment]
There were some additional session length failures on the [report](https://mattermost-cypress-report.s3.amazonaws.com/215318-16e3b6a-onprem-ent-webapp-pr-10705-mattermost/mm-ee-test16e3b6a/mochawesome.html), I don't believe they are related to changes here. I updated the branch and re-running e2es.

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Seeing one issue in mobile webview. Save button is not working; saving by hitting enter still works in mobile view.

https://user-images.githubusercontent.com/52937121/177626350-56217b04-91ef-407d-9ee3-718036583a67.mov

**Comment by michelengelen** [comment]
> Thanks @michelengelen Seeing one issue in mobile webview. Save button is not working; saving by hitting enter still works in mobile view.

I fixed this one (pretty nasty bug as well)

> One more thing -can you please add a unit or e2e test for this? Thanks 🙂

Will do this in a follow-up PR (ticket [MM-45563](https://mattermost.atlassian.net/browse/MM-45563))

**Comment by jgilliam17** [comment]
Thanks @michelengelen and also for adding a follow up ticket.
Tested, looks good to merge.
- Verified `save` and `cancel` buttons on edit post view.
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/215826-7aa0c6f-onprem-ent-webapp-pr-10705-mm-ee-test:7aa0c6f/mochawesome.html) looks good, no PR related failures.(linking another version of the [report](https://automation-dashboard.vercel.app/cycles/11acc2d5-557d-430d-9a44-a5866768e37f) here, the first one is missing some suites)

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
