### PR TITLE
Add Stylus support

### PR DESCRIPTION
**Pull request by jazzzz**
#### Summary
Adds syntax highlighting for Stylus code and files.

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes
- [ ] Has redux changes
- [ ] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by enahum** [comment]
adding @hmhealey to review this PR as this might need to be included in RN as well

**Comment by jazzzz** [comment]
@enahum I will remove the changes as soon as possible. Just curious: what's wrong with these localizations?

**Comment by jazzzz** [comment]
> Just curious: what's wrong with these localizations?

No need to reply, I found the reason myself!

**Comment by jazzzz** [comment]
> can you remove the changes in every localization file but en.json ?

Done.

**Pull request merged**
