### PR TITLE
MM-49414 : Fix failing e2e due to recent a11y changes

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Conversation here https://community.mattermost.com/core/pl/9s4rk93kkbfb7dr54u3utsxp8h

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49414

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thanks @M-ZubairAhmed 
See full E2E report [here](https://mattermost-cypress-report.s3.amazonaws.com/282253-42fe16b-onprem-ent-webapp-pr-11877-mm-ee-test:42fe16b/mochawesome.html) - looks good to merge.
I'll create a follow up ticket for few tests I mentioned in our [chat](https://community.mattermost.com/core/pl/y7o8dnjutt8r5k8asqix8kh4ye)

**Review by jgilliam17 — APPROVED** [review]

**Comment by jgilliam17** [comment]
Ticket for follow up https://mattermost.atlassian.net/browse/MM-49426

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
Thank you @M-ZubairAhmed , will merge this one.

**Comment by saturninoabril** [comment]
Awesome, thanks @M-ZubairAhmed!

**Pull request merged**
