### PR TITLE
remove bodyOnly prop

### PR DESCRIPTION
**Pull request by darkLord19**
Fixes https://github.com/mattermost/mattermost-server/issues/18360

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @darkLord19!

**Review by hmhealey — APPROVED** [review]
I removed the prop from the MoreDirectChannels modal in https://github.com/mattermost/mattermost-webapp/pull/8821, so this'll conflict with that, but that's probably fine since this is going to get through review much faster than that one.

**Comment by hmhealey** [comment]
Skipping QA review since this is just dead code removal

**Pull request merged**
