### PR TITLE
[MM-25435] Redesign Emoji Picker UI

### PR DESCRIPTION
**Pull request by bhargav50**
#### Summary
It revamps emoji picker UI

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15636

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @bhargav50, adding the work in progress label as you and @asaadmahmood get it the PR ready for review 👍

**Comment by esethna** [comment]
@bhargav50 @asaadmahmood anything we can help with here to move this PR along?

**Comment by esethna** [comment]
@bhargav50 just checking if you're still working on this?

**Comment by bhargav50** [comment]
> @bhargav50 just checking if you're still working on this?

@esethna  I need help with that expanding animation in this PR. I think I commented about this last time as well but can't find that conversation anymore.

**Comment by esethna** [comment]
@asaadmahmood are you able to help with this on the PR? I think @bhargav50 is referring to the skin tone selector and how it animates out to provide the skin tone options. @bhargav50 please add any more details as needed

**Comment by bhargav50** [comment]
> @asaadmahmood are you able to help with this on the PR? I think @bhargav50 is referring to the skin tone selector and how it animates out to provide the skin tone options. @bhargav50 please add any more details as needed

Yeah @esethna  that animation only, I am not able to visualize how mathematically I can modify the divisions to render that animation. If someone can just point me toward a high-level approach I will figure out a way to implement it then.

**Comment by asaadmahmood** [comment]
@esethna @bhargav50 I have added that particular effect and make some other UI changes.
There are a bunch of other UI changes and a bunch of functional changes that need to happen inorder for the PR to look and function like the designs.

But for the sliding animation etc, we should be good to go.
Jan-26-2021 20-56-33

**Comment by bhargav50** [comment]
@esethna I am closing this PR for now. Will raise it again once it is ready for review.

**Comment by esethna** [comment]
@bhargav50 just checking how this is coming along? Need any help or guidance?

**Pull request closed without merging**
