### PR TITLE
[MM-47412] Check if delinquency since is not null before to calculate…

### PR DESCRIPTION
**Pull request by Afsoon**
#### Summary

Hide the modal when delinquency since is null. 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47412

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks @Afsoon!

**Review by nickmisasi — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
@Afsoon I'm not encountering the delinquency pop up so all appears to be good!

**Pull request merged**
