### PR TITLE
MM-39059 - AB test for the add members to channel btn

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
This PR adds the two options for the AB test for the add members to channel button.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39059

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/18832

#### Screenshots

https://user-images.githubusercontent.com/10082627/138562400-e5774969-7518-4891-bdf6-06e398f8571b.mp4

https://user-images.githubusercontent.com/10082627/138562409-3b148d20-f776-4928-8267-00aace6ff5a4.mp4

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal This version looks good and worked as expected.
> 
> image
> 
> Once you can toggle it to the other type I'll test that as well.

changed, now you can verify it

**Review by stevemudie — APPROVED** [review]
@pablovelezvidal Looks good!

Both versions worked as expected.

**Comment by amyblais** [comment]
@marianunez Is this for the next cloud release?

**Comment by marianunez** [comment]
> @marianunez Is this for the next cloud release?

Yes, we should cherry-pick this to `cloud`. Did the name change with the new branch cut for webapp?

**Comment by amyblais** [comment]
> > @marianunez Is this for the next cloud release?
> 
> Yes, we should cherry-pick this to `cloud`. Did the name change with the new branch cut for webapp?

@isacikgoz Is it just ``cloud``?

**Comment by marianunez** [comment]
@pablovelezvidal can we do a manual cherry-pick to the `cloud` branch?

@puerco just an FYI error on cherry-pick above that may help with your on-going cherrypick improvements.

**Comment by pablovelezvidal** [comment]
> @pablovelezvidal can we do a manual cherry-pick to the `cloud` branch?
> 
> @puerco just an FYI error on cherry-pick above that may help with your on-going cherrypick improvements.

@marianunez @puerco I updated my cloud branch and noticed that the commit generated by this PR was already in cloud, not sure exactly how https://github.com/mattermost/mattermost-webapp/commits/cloud

**Pull request merged**
