### PR TITLE
Cypress/E2E: fix failed tests

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Sorry for this huge changes. This includes the following:
- introduced `cy.uiGetReplyTextBox()` for `#reply_textbox`
- introduced `cy.uiGetPostTextBox()` for `#post_textbox`
- introduced `cy.uiGetFileUploadPreview` to easily access file preview in ATE
- fixed tests related to ATE like when uploading/rendering/pasting a file/preview
- fixed other random tests
- removed unnecessary line of code like
```javascript
// * Post text box should be visible
cy.get('#post_textbox').should('be.visible');
```
when already followed by `cy.postMessage(messageText);`

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by saturninoabril** [comment]
Change reviewer to Cass since FM is having issue with internet provider.

**Review by Phrynobatrachus — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
