### PR TITLE
[MM-18793] Remove dead code for "Install plugin by URL" in Admin Console

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR removes the state management code related to the "Install plugin by URL" component.

The component was originally introduced as a precursor to the plugin marketplace, but was removed due to UX issues around the display of errors. The state management code added with the feature was not removed during the revert. Now that the plugin marketplace component is in place, this dead code needs to be removed.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18793

### CODE REVIEW

**Comment by lieut-data** [comment]
Swapping myself out for @ali-farooq0.

Aaron, do you recall if the plan was to restore this functionality when the UX issues were resolved, or remove it altogether?

**Comment by ali-farooq0** [comment]
Interesting. I thought the plan was to restore this functionality?

**Comment by cpoile** [comment]
Waiting on @aaronrothschild before I review (just in case)

**Comment by aaronrothschild** [comment]
@ali-farooq0 @lieut-data I was 0/5 on keeping/removing it.  IF we keep it, 4/5 we should fix the error and UX. 

Who would this help going forward? Would the upload by URL accomodate signed repos too?

**Comment by mickmister** [comment]
I'm thinking we should close the PR in favor of improving the feature if it's still up in the air.

**Pull request closed without merging**
