### PR TITLE
edits to defaultMessage in components

### PR DESCRIPTION
**Pull request by AninditaBasu**
Part of GSoD'19 work

#### Summary

Edits to the corresponding default message of each component for which the in-product text was refined through PR#4555.

#### Ticket Link

Fixes @saturninoabril's comment at https://github.com/mattermost/mattermost-webapp/pull/4555/files#r371101441

#### Related Pull Requests

https://github.com/mattermost/mattermost-server/issues/10888

### CODE REVIEW

**Comment by saturninoabril** [comment]
@AninditaBasu Looks good to me. I'll push a commit to fix failing test as I believed you don't have npm installed on your machine.

**Comment by hanzei** [comment]
@saturninoabril Is there any way to check grammatically if any messages where missed?

**Comment by saturninoabril** [comment]
Did you mean comparing text message between en.json and the one in the component's defaultMessage? If yes, I don't think there is than to manually inspect changes. Maybe a good feature of mmjstool?

If you mean grammatical correctness, not that I'm aware of.  What I'm using is just a [spell checker extension for VSCode](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).  Works well but doesn't scale since it's aid for manual check only.

**Comment by hanzei** [comment]
> Did you mean comparing text message between en.json and the one in the component's defaultMessage? If yes, I don't think there is than to manually inspect changes. Maybe a good feature of mmjstool?

Yes, I was referring to this. Thanks for the explanation. I opened an issue  https://github.com/mattermost/mattermost-utilities/issues/26.

**Comment by hanzei** [comment]
@saturninoabril Is this ready to merge?

**Comment by saturninoabril** [comment]
Yes, I'll merge it now. 
Thanks @AninditaBasu!

**Comment by saturninoabril** [comment]
@hanzei @amyblais Before merging, just like to confirm if we can cherry-pick this into release-5.20. Looking at related PR - https://github.com/mattermost/mattermost-webapp/pull/4555, it's confirmed to be part of v5.20.0.

**Pull request merged**
