### PR TITLE
[MM-34763][MM-34744][MM-34767] - Fix UX issues with channel navigator and navbar

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR addresses UI issues related to hard coded variables and misalignment of the channel header with the 'has guests' text. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34763
https://mattermost.atlassian.net/browse/MM-34767
https://mattermost.atlassian.net/browse/MM-34744

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by matthewbirtch** [comment]
Looks good @nevyangelova. I'm not able to test the channel header update though since I'm not sure how to configure a channel to add guests so it will show `this channel has guests'. How can I test that?

**Review by devinbinnie — APPROVED** [review]

**Comment by jgilliam17** [comment]
@matthewbirtch I added a guest to Town Square

**Comment by matthewbirtch** [comment]
> @matthewbirtch I added a guest to Town Square

Thanks @jgilliam17!

@nevyangelova I'm still seeing a misalignment if the channel header description has markdown bullets in it
image

**Comment by nevyangelova** [comment]
@matthewbirtch didn't test with a markdown bullet! Now it should be fixed

**Review by matthewbirtch — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified channel with guest header; channel descriptions with bullets aligns with "channel has guest" text
- Verified background color of LHS header on hover. 
- Verified sidebar navigation elements are using sidebar color of different opacity; can be distinguished in lighter themes.

**Pull request merged**
