### PR TITLE
[MM-18117] Add F6 navigation to search/mentions/flagged/pinned RHS views

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Pressing F6 did not take you to the RHS if it wasn't the thread view. This PR adds that navigation and allows arrow key navigation between the posts. It will also read the posts in the same manner as the center channel.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18117

### CODE REVIEW

**Comment by devinbinnie** [comment]
@esethna I've pushed up fixes to address 1) and 4).

2) I think this needs to be a separate ticket/story. This isn't a quick thing to do and requires some changes to how the `a11y-controller` works in order for it to be implemented correctly. I also don't think it's a huge priority as you are still able to tab down to the RHS relatively quickly from the search bar. Plus it's scope creep.

3) Unfortunately I don't think there's anything we can do about this. Our fix in the past was to put in `role=application` on the section but as we've now learned, that causes lots of problems with other screen readers (like NVDA). I feel like (and this is worth investigating) that JAWS users disable the automatic turn on of the Virtual PC cursor, and only toggle it on when it's useful. I've noticed that whenever it injects itself into our app or other apps (eg. Visual Studio Code) it breaks a lot of the functionality. The correct behaviour here is to turn off the Virtual PC cursor and use the navigation we provide.

**Comment by esethna** [comment]
@srkgupta thanks for the review. Re 1) That's fixed, 2) good catch but I think that's fine 3) That was solved in a different PR

**Comment by esethna** [comment]
Adding @deanwhillier and @asaadmahmood for review

**Comment by devinbinnie** [comment]
@esethna @amyblais Manually cherry-picked to v5.15 and v5.16.

**Pull request merged**
