### PR TITLE
Updated Terms of Service to Terms of Use

### PR DESCRIPTION
**Pull request by cwarnermm**
#### Ticket Link
https://community-daily.mattermost.com/boards/workspace/g4k9s1f953n4bytz5f9sz9orer/16c12e26-4cda-4237-88c2-9a33f37d20ee/99977bbc-45ec-4aa4-889e-091f43e83737/449824d8-11ed-4103-8329-064bb990439e

#### Related Pull Requests
Product Documentation update: https://github.com/mattermost/docs/pull/5274
Server update: https://github.com/mattermost/mattermost-server/pull/19043

#### Release Note

```release-note
Updated "Terms of Service" terminology to "Terms of Use" product-wide.
```

### CODE REVIEW

**Comment by cwarnermm** [comment]
@michelengelen - There's an additional instance of "terms of service" that this PR doesn't cover yet -- the default URL for the config setting:
Screen Shot 2021-11-22 at 1 41 22 PM

Do you know where in the code I'd update this text?

Also, at least 2 E2E tests are going to break as a result of this update; however, the URLs that will break will also auto-redirect users to the correct URL as needed. Looking for guidance/advice on how to proceed with those updates. CC @jgilliam17

**Review by wiersgallak — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @cwarnermm Running the [E2Es here](https://automation-dashboard.vercel.app/cycles/636c94c8-7142-401f-a037-c36aaf2ca5bf) to identify failing tests. I will post the report here when available.

**Comment by jgilliam17** [comment]
Thanks @saturninoabril for updating and re-running the test. 
@cwarnermm here are the [results ](https://mattermost-cypress-report.s3.amazonaws.com/89411-00e004e-ee-ent-webapp-pr-9412-mm-ee-test:00e004e/mochawesome.html) , can be compared to [master here](https://mattermost-cypress-report.s3.amazonaws.com/89448-ee-ent-master-mm-ee-test:test/mochawesome.html)
Failing test cases related to this PR:
1. MM-T1211
2. MM-T1032
3. MM-T1034
4. MM-T1035
5. Test for Signup email page, no reference number

There are also 2 Compliance export tests and one Profile Popover test failing, but they do not appear to be related to this PR.

**Comment by michelengelen** [comment]
> @michelengelen - There's an additional instance of "terms of service" that this PR doesn't cover yet -- the default URL for the config setting: Screen Shot 2021-11-22 at 1 41 22 PM
> 
> Do you know where in the code I'd update this text?

It is in the server repo and can be found here: https://github.com/mattermost/mattermost-server/blob/master/model/config.go

**Comment by cwarnermm** [comment]
Thanks, @jgilliam17! I've reviewed the test results and see that I'm going to need some assistance updating the failed tests. @saturninoabril - Are you open to assisting with these updates (given that there wouldn't be a clear implementing team/developer to assist in this case)?

@michelengelen - Thank you for your help with this! I'll ensure that's updated as well and cross-reference the work between PRs for traceability.

**Comment by saturninoabril** [comment]
Sure Carrie, happy to help here.

**Comment by saturninoabril** [comment]
@cwarnermm Done, please see changes [here](https://github.com/mattermost/mattermost-webapp/pull/9412/commits/df27ddb7b0d71cb78891401264ca632ffda48589) and check whether other UI text changes were correct or not. Feel free to modify just in case. E2E tests were fixed and [latest run](https://mattermost-cypress-report.s3.amazonaws.com/90178-df27ddb-ee-ent-webapp-pr-9412-mm-ee-test:df27ddb/mochawesome.html) were good without related failed tests. cc @jgilliam17

**Comment by cwarnermm** [comment]
@saturninoabril - Unfortunately, we need to draw a distinction between our Terms of Use and our Custom Terms of Service product functionality. The legal terminology change required doesn't extend to the Custom Terms of Service feature, and terminology updates made to the feature need to be reverted.

**Comment by saturninoabril** [comment]
@cwarnermm Got it! Please take a look again - https://github.com/mattermost/mattermost-webapp/pull/9412/commits/6d9c61c1937b287f2facf4cd20a4d0cd1104b1ee (did a force-pushed for you to easily compare against your initial change)

Test report - https://automation-dashboard.vercel.app/cycles/021ae2aa-8123-434c-a9f1-573f0976eeeb

**Review by michelengelen — APPROVED** [review]

**Comment by cwarnermm** [comment]
Looks great, @saturninoabril. Thank you for your help with these important updates!

**Comment by cwarnermm** [comment]
@jgilliam17 - This PR is now ready for your review.

**Comment by jgilliam17** [comment]
Thanks @cwarnermm, and thanks @saturninoabril for fixing and running the tests
Tested, looks good to merge.
- Verified Terms of Use terminology update

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
