### PR TITLE
Catch errors from plugin reconnect handlers

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

There was an issue with the todo plugin throwing an exception in its reconnect handler https://github.com/mattermost/mattermost-plugin-todo/issues/155. This made it so the webapp didn't finish the rest of its reconnect logic.

This PR makes it so the webapp catches any errors thrown by the plugin reconnect handlers. It now logs the error and moves on with other reconnect logic.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-41975

#### Related Pull Requests

https://github.com/mattermost/mattermost-plugin-todo/pull/156

#### Release Note

```release-note
The webapp is able to properly handle errors occuring in plugin reconnect handlers.
```

### CODE REVIEW

**Comment by hanzei** [comment]
@mickmister Are there other places in the webapp plugin code that could benefited from defensive code like this one?

**Review by larkox — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann Please test this PR with the `0.5.0` release of the todo plugin. The release bump PR is here https://github.com/mattermost/mattermost-plugin-todo/pull/148, code reachable through commit https://github.com/mattermost/mattermost-plugin-todo/commit/c71859ae965b4675f2ee6d3bbfb2e4ab4c14e91c


Before this PR, trigger a websocket reconnect by toggling your ngrok tunnel off and on. There will be an error banner shown after websocket reconnect.

After this PR, the banner will not be shown during reconnect. Also, if you check the redux dev tools, there will correctly be many more app-related redux actions dispatched during reconnect, than compared to when using the "before PR" webapp code.

**Comment by larkox** [comment]
Does it make sense to add automated tests for this? My point is having for all executable plugin functions have a `throw` mocked inside, so it fails silently (or not so silently).

**Comment by hanzei** [comment]
@mickmister With this PR plugin devs will not longer be easily able to identify JS errors in there reconnect handlers. Is there a way we can have both: A banner when the error happens, but **no** log request to the server as that is to spammy.

**Comment by mickmister** [comment]
@hanzei Yeah we can do something like this to defer the throwing out of the current context:

```js
try {
    handler();
} catch (e) {
    setTimeout(() => {
        throw e;
    });
}

**Comment by mickmister** [comment]
> A banner when the error happens, but no log request to the server as that is to spammy?

@hanzei I'm not sure if we can avoid that. Maybe there is a "show error banner but don't log to the server" function available in the webapp code.

**Comment by hmhealey** [comment]
I'm 0/5 about whether or not we want the error banner to show up here. Personally, I haven't found the error banner to be that helpful in quite a while now since it no longer shows the actual error message like it once did, so I don't find it particularly helpful personally.

As for a function to show it without logging to the server, I don't think we have anything like that currently. I suppose we could modify the `logError` action with a way to override that though

**Review by hmhealey — APPROVED** [review]

**Comment by mickmister** [comment]
Closing this in favor of more holistic error handling for plugin hooks

**Pull request closed without merging**
