### PR TITLE
[MM-49198] Fix reported device as desktop when coming from mobile app

### PR DESCRIPTION
**Pull request by m1lt0n**
#### Summary

QA review reported an issue with the log activity (active sessions) reporting of the device of sessions, where sessions from mobile v2 are reported as Desktop ones. This PR changes the logic/branching for that component.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49198

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]
Lgtm

**Review by agnivade — COMMENTED** [review]
Should we have a new test for this?

**Comment by jgilliam17** [comment]
Thanks @m1lt0n I triggered e2es again, last cycle failed to start 
Tested, looks good to merge - pending e2es
Verified active session information is as expected.
Screen Shot 2022-12-22 at 11 25 48 AM

**Comment by m1lt0n** [comment]
@agnivade Good idea (I did some manual QA and verified the results, but an additional automated test is a good idea). I've added (in a separate commit) a snapshot test with browser set as 'Desktop App' but device_id set to 'apple' in the session mock and it indeed identifies the session as mobile with the fix.

Since the test was added after the fact, I checked out the component from current master to verify that the new test failed before the fix and indeed the new test showed the session as desktop app.

**Review by agnivade — APPROVED** [review]
Thanks for adding a test Pantelis!

**Review by lieut-data — APPROVED** [review]
Thanks for unravelling all the backstory here, @m1lt0n :)

**Review by jgilliam17 — APPROVED** [review]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/279453-34e8a0c-onprem-ent-webapp-pr-11854-mm-ee-test:34e8a0c/mochawesome.html) - looks good, no PR related failures

**Pull request merged**
