### PR TITLE
Fixing the initial plus sign in the search result counters

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Fixing the initial plus sign in the search result counters

#### Ticket Link
[MM-34999](https://mattermost.atlassian.net/browse/MM-34999)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
LGTM

**Comment by cpanato** [comment]
Cherry pick is scheduled.

**Pull request merged**
