### PR TITLE
Advanced Text Editor UX changes

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Adding multiple UX changes to the Advanced text editor to address issues user are facing and make it more future proof
https://www.figma.com/file/TUCCrr4qlJZOmabkqm3BPn/Patterns---Message-Input?node-id=54%3A11405

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-44390
  Fixes https://mattermost.atlassian.net/browse/MM-44457
  Fixes https://mattermost.atlassian.net/browse/MM-44538
  Fixes https://mattermost.atlassian.net/browse/MM-44393
  Fixes https://mattermost.atlassian.net/browse/MM-44562

#### Related Pull Requests
NONE

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot 2022-05-26 at 10 47 54 PM | Screenshot 2022-05-26 at 10 47 32 PM |

#### Release Note
```release-note
* Adding multiple UX changes to the Advanced text editor to address issues users are facing and make it more future proof
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Nice work on this @AshishDhama. I think this will help resolve many of the layout issues we were finding and will help future-proof for when we add some of the new features that are coming.

A few things I'm noticing:

1. The formatting overflow popover menu is not positioning correctly. It needs to be positioned relative to the `•••` button. Right now it is anchoring to the top-left of the input.
image

2. In the RHS version, can we add a `|` divider between the `•••` and the attachment icon? 

3. When the RHS is expanded, it doesn't need to collapse all the formatting controls. Can we show them all when RHS is expanded. We should do the same in the Threads view since there is enough width there as well. Just make sure that we keep it collapsed for smaller viewports though or when the width of the input can't handle all the icons.

**Comment by AshishDhama** [comment]
@matthewbirtch this PR https://github.com/mattermost/mattermost-webapp/pull/10374 fix point 3, Rest I will fix here.

**Comment by matthewbirtch** [comment]
@AshishDhama could you also add a hover state (while not focused) to the input container - just change the border color to 24% center channel color while hovering. (make sure it stays at 32% opacity while focus-within and hover are happening though)

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Found one more thing:

- In the smaller version of the input, when the formatting bar is turned off, we need to hide the overflow menu and `|` next to it
image

**Comment by matthewbirtch** [comment]
@AshishDhama can you also hide the 'Send' button for read-only channels?

**Comment by AshishDhama** [comment]
> @AshishDhama can you also hide the 'Send' button for read-only channels?

Yeah, we can hide send button as well.

**Comment by matthewbirtch** [comment]
One other thing I just noticed on mobile view: the left/right border changes on hover which causes things to jump around. On mobile widths, we don't need the left/right borders at all.

**Review by Willyfrog — APPROVED** [review]

**Comment by AshishDhama** [comment]
@koox00 Gentle reminder on this.

**Review by koox00 — APPROVED** [review]
lgtm 💪

**Comment by AshishDhama** [comment]
@jgilliam17 This is ready for review.

**Comment by jgilliam17** [comment]
Thanks @AshishDhama 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/200484-6d5e089-onprem-ent-webapp-pr-10384-mattermost/mm-ee-test6d5e089/mochawesome.html) looks good, no PR related failures
I'm having  trouble with the test server, randomly loosing connection 
Screen Shot 2022-05-31 at 12 26 11 PM

**Comment by jgilliam17** [comment]
@AshishDhama 
just two observation that we can address in a follow up
1. We could make the rhs textbox smaller on read-only channels (https://mattermost.atlassian.net/browse/MM-44458 will probably fix this)
Screen Shot 2022-05-31 at 1 45 31 PM
2. On expanded RHS, additional formatting options remain collapsed even though there's enough space to show all
Screen Shot 2022-05-31 at 12 04 10 PM

**Comment by AshishDhama** [comment]
> Let me know what is it that we decide to do (or not) for extra space when attachments are present
Formatting bar enabled

@jgilliam17 I will create a follow pr for this.
 About point 
 1. Yeah please add this to the ticket you have mentioned,
 2. For this have merged a PR in master today that will fix it, so I think we can try updating this PR and check.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
