### PR TITLE
Add Metropolis font and apply to headings

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Add Metropolis font for headings as per Compass Design system guidelines.

Applies to h1-h3 headings globally with specific overrides in a few places for visual consistency. Open Sans is still maintained for everything else.

Worked with Design team on visual tweaks to better integrate Metropolis. Given current semantic inconsistencies across the app, visual design has been prioritized for now. That will be corrected as Compass Components start to replace existing UI.

#### Ticket Link
[MM-37085](https://mattermost.atlassian.net/browse/MM-37085)

#### Release Note

```release-note
Changed H1-H3 heading font from Open Sans to Metropolis
```

### CODE REVIEW

**Comment by andrewbrown00** [comment]
Thanks, @deanwhillier knocking this out! 

From a cursory review, things are looking good with the update to Metropolis for the H1-H6 tags. I'm seeing issues anywhere that's not using semantic HTML (no H tags) and using custom classes to define headers 😕 . As well as instances where the `H tag` is being overwritten and breaks the `font-size` hierarchy. Lastly, from what I'm seeing, the **system console** is not using semantic HTML either and there are NO `H tags` anywhere.

**Note**
We may want to adjust the weights up, some of them feel a bit light.

cc @matthewbirtch

**Comment by matthewbirtch** [comment]
I don't have time to go through every screen, but I don't think it's quite as simple as using Metropolis for all `h1`-`h6` tags since it would appear that the heading levels don't necessarily apply the expected sizes. 

A few things I noticed in a first quick pass:

1. For the `getting started` screen in particular, I think we should only use metropolis for the 'Welcome to Mattermost' header and open sans for everything else.
image

2. Same as above for the 'Tips and Next Steps screen
image

3. I think I would have expected the "Let's add some people to the workspace" line to be a heading style using metropolis
image

4. For modals, I think I would make the `font-weight: 600` for the header
image

5. For these empty states in the RHS, I would have expected the "No saved posts yet" header to be using metropolis
image

6. The create account screen the labels above the input fields should be open sans I think
image

That's all I had time to review today, but I think this will take much longer to identify all issues

**Comment by andrewbrown00** [comment]
@deanwhillier Matt and I are carving out time on Friday to do a deeper review and document and prioritize where we make changes. We'll post the breakdown in the Jira ticket - https://mattermost.atlassian.net/browse/MM-37085

**Comment by matthewbirtch** [comment]
@andrewbrown00 @deanwhillier and myself reviewed this live together in a lengthy, thorough session today. We will have one more final glance, but things are in good shape after our review today.

**Comment by deanwhillier** [comment]
Working through merge conflicts with master. Will remove WIP label when done.

**Review by nevyangelova — APPROVED** [review]
Code wise looks good, but we need to do extensive QA on this. I am assuming all the P tags wouldn't have the Metropolis font, is this applied in all the right places. What is the difference between the `next_steps_view` and `next_steps_tips` for example that one has the metropolis font and the other doesn't?

**Review by calebroseland — APPROVED** [review]
Font changes are always "that looks different" for me, but everything looks good!

**Comment by deanwhillier** [comment]
@esethna, @jgilliam17, @matthewbirtch, test servers are back up and running! 🎉

**Comment by esethna** [comment]
Thanks! Looks good, my 2 cents of feedback is that the new H1 feels very heavy in comparison to what is was before, which works for some places but feels slightly off in others, ie

image

0/5, perhaps it's just that it's new and different. I also think it will look less out of place as we start to update our aging UI components, ie modals etc,

image

**Review by esethna — APPROVED** [review]

**Comment by jgilliam17** [comment]
@deanwhillier For some reason test server stoped working for me.
I've seen few screens though before my session expired, including Create new team where team name looks a bit smaller

before
before
now
now

**Comment by deanwhillier** [comment]
If I recall correctly, that was intentional, but I'll let @andrewbrown00 or @matthewbirtch weigh in when they are able.

**Comment by jgilliam17** [comment]
Thanks @deanwhillier I'll re-test after ux. Test server is working again and the font looks good so far.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Looking great @deanwhillier. Only a few minor things I see after another pass:

1. When the team name is long, it gets truncated, but the ellipses appear too tight to the hamburger menu in the channel sidebar header. Anything we can do to fix that? 
Screen Shot 2021-07-25 at 8 50 46 PM

2. In the channel header, if a user is a guest, the tag for `GUEST` is using metropolis and the padding looks off. It should be using open sans - just like it does for the Bot tag in Bot channel headers (see comparison below)

<table>
<tr>
<td><strong>Bot</strong></td>
<td><strong>Guest</strong></td>
</tr>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

3. In the RHS Header for Threads and Files, can we make the channel name open sans instead of Metropolis? ("Off Topic" in the example below)
image

4. For the Marketplace, can we change the title on the screen to use `font-weight: 600` for consistency? It appears to be using `400` right now
image

5. For Direct Messages and Bots, at the beginning of the channel it shows the user's avatar and their username/display name. Can we use Metropolis for the name in the same way we use it for the 'Beggining of {Channel}' titles?
<table>
<tr>
<td><strong>DM or Bots</strong></td>
<td><strong>Channels</strong></td>
</tr>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

5. How can we test the cloud purchase screens?
6. Should we create a follow-up ticket to look at Playbooks?
6. Can we create a follow-up ticket to update the system console as well?

**Comment by matthewbirtch** [comment]
> If I recall correctly, that was intentional, but I'll let @andrewbrown00 or @matthewbirtch weigh in when they are able.

Yes, this was intentional @jgilliam17

**Comment by deanwhillier** [comment]
@matthewbirtch, additional updates made, have a look when you get a minute!

5. Probably best to check with the cloud teams on that
6. Yes. But probably best to work their team directly if possible as I'm not familiar with their plugin. I can still try help if all else fails.
7. Yes. There are a number of tasks that still need to be done. This one feels like it is lower priority, so will need to wait till the other are done. Thoughts?

**Comment by matthewbirtch** [comment]
> * Probably best to check with the cloud teams on that
> * Yes. But probably best to work their team directly if possible as I'm not familiar with their plugin. I can still try help if all else fails.
> * Yes. There are a number of tasks that still need to be done. This one feels like it is lower priority, so will need to wait till the other are done. Thoughts?

Makes sense on all the above

One other thing I just found:
- It looks like the team name in the sidebar header is not getting truncated now:
image

And I'm still seeing this for guests:
image

**Comment by deanwhillier** [comment]
@matthewbirtch, looks like another PR that was recently merged to master is doing that. I'll have to find and fix, stay tuned.

**Comment by deanwhillier** [comment]
Well, that was fun. Unfortunately I had to rebuild my branch as merging master messed it up royally, requiring a force-push.

Should be good now @matthewbirtch 🤞

**Comment by deanwhillier** [comment]
Spinwick: https://mattermost-webapp-pr-8402.test.mattermost.cloud/pr8402/channels/town-square

**Review by matthewbirtch — APPROVED** [review]
Looks great @deanwhillier! I think we're good to go

**Comment by deanwhillier** [comment]
Thanks Matt! @jgilliam17, you're up when you have a spare minute! :)

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified Metropolis font is applied to headings.

**Comment by AGMETEOR** [comment]
Hello @deanwhillier , is there a CDN where these Metropolis fonts are served.

**Comment by lieut-data** [comment]
@AGMETEOR, I believe these fonts are bundled with the mattermost webapp, thus not requiring any external hosting.

**Comment by AGMETEOR** [comment]
> @AGMETEOR, I believe these fonts are bundled with the mattermost webapp, thus not requiring any external hosting.

Hello @lieut-data . How could we add them to an email template for example?

**Comment by lieut-data** [comment]
@AGMETEOR, ah thank you for the clarity. I don't know about CDN hosting, but indeed nothing here will help with email templates. I'll defer to UI Platform team on whether it's even feasible to host these fonts for that kind of usage.

**Comment by deanwhillier** [comment]
@AGMETEOR, apologies, I missed the original question. I checked with Design and it doesn't appear there is a CDN hosted version. There's also the question of licensing and what used restrictions there are ... check with Design on that.

Likely not the ideal situation, but can the templates by updated to use the originating MM instance as the 'CDN' for the Metropolis font files? Obviously would only work when the MM instance is accessible from the receiving end, but fallback fonts can be used for when not.

**Pull request merged**
