### PR TITLE
MM-40114 Migrate file preview modals to TS and to use getIsMobileView

### PR DESCRIPTION
**Pull request by hmhealey**
`getIsMobileView` is the more redux-friendly, more self-explanatory, and hopefully more performant version of `Utils.isMobile` that we're wanting to be using everywhere now. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40114

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/9508
https://github.com/mattermost/mattermost-webapp/pull/9509
https://github.com/mattermost/mattermost-webapp/pull/9510

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]
LGTM

**Review by BenCookie95 — APPROVED** [review]

**Comment by hmhealey** [comment]
I've started the automated E2E tests for this PR

**Comment by jgilliam17** [comment]
Thanks @hmhealey 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/97315-7ec44bf-onprem-ent-webapp-pr-9507-mm-ee-test:7ec44bf/mochawesome.html) looks good, not PR related failures.
Also tested manually, looks good to merge.
- Verified file preview modal in different browser window sizes (mobile through fullscreen).

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
