### PR TITLE
[MM-17067] reorder dot menu items

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary
- Reorder menu items
- group menu items
- mark delete as a dangerous menu item

also, there might be future changes based on @andrewbrown00 feedback here: https://community.mattermost.com/core/pl/78yhio9ah7yszxoa5qmds9n75a

#### Ticket Link

[MM-17067](https://mattermost.atlassian.net/browse/MM-17067)

#### Related Pull Requests

requires changes on #3513 as well as previous ones

### CODE REVIEW

**Comment by jespino** [comment]
@Willyfrog another comment, the description doesn't mention anything about "unread" so that means it should be in the description or shouldn't be in the PR.

**Comment by Willyfrog** [comment]
@jespino it is not merging against master, for some reason is having trouble with its own history... I'll take a look and update. Once it goes against master it might have the problem you mention.
Regarding `unread` this PR doesn't do anything on the unread feature, it's something that was added on the design documents to handle the number of menu items, so we are doing it at the same time and as such is falling into the same feature branch. Sorry if this is confusing!

**Comment by jespino** [comment]
@Willyfrog I didn't saw the fact that wasn't merging into master. So... everything looks good to me :)

**Comment by Willyfrog** [comment]
@hmhealey this goes into a feature branch, I think it's safe to merge :)

**Comment by Willyfrog** [comment]
ah, no, I was thinking this was waiting for the redux, I'll do the appropiate changes if needed, sorry!

**Pull request merged**
