### PR TITLE
[MM-44473] - Fix theming and text color for pricing modal

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Fixes theming colors for the pricing modal

#### Ticket Link
[MM-44473](https://mattermost.atlassian.net/browse/MM-44473)

#### Screenshots
ONYX
----
Screenshot 2022-05-23 at 16 30 53

INDIGO
----
Screenshot 2022-05-23 at 16 32 00

QUARTZ
----
Screenshot 2022-05-23 at 16 33 15

SAPHIRE
----
Screenshot 2022-05-23 at 16 34 10

DENIM
-----
Screenshot 2022-05-23 at 16 34 48

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @AGMETEOR !

**Review by marianunez — COMMENTED** [review]
For the dark themes, the content in the modal seems a bit hard to read. Is this intended @annelieseklein ?

**Comment by annelieseklein** [comment]
@marianunez No, the design was updated to include center channel texts

Screen Shot 2022-05-23 at 8 56 25 AM

**Review by stevemudie — APPROVED** [review]
Ah… Much better on the eyes. ツ

Tested in both standard dark themes as well as the light ones just to be sure.

Great work @AGMETEOR!

**Review by marianunez — COMMENTED** [review]
Do we still need to update the text for the prices ? They still seem a bit dark:
Screen Shot 2022-05-26 at 1 36 00 PM

**Comment by AGMETEOR** [comment]
> Do we still need to update the text for the prices ? They still seem a bit dark: Screen Shot 2022-05-26 at 1 36 00 PM
Those were using another color that's doesn't change according to theme. Fixed now
Screenshot 2022-05-26 at 22 37 16

**Comment by annelieseklein** [comment]
> The center-channel-text doesn't seem available in the dark themes

yes this should be center channel color

**Comment by annelieseklein** [comment]
Looking great! @AGMETEOR  Can we please make the plan names "Starter" "Professional" and the "/user/month" 72% center channel text so it is a bit lighter

Screen Shot 2022-05-26 at 1 01 51 PM

**Review by annelieseklein — APPROVED** [review]

**Pull request merged**
