### PR TITLE
[MM-34812] Add feature discoveries

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Add the rest of the feature discoveries.
As instructed by Michael , I used the SAML picture as a placeholder

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34812

#### Screenshots

image

image

image

image

image

image

image

image

image

image

image

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hahmadia** [comment]
Currently in the process of writing cypress test for these

**Comment by hahmadia** [comment]
Cypress Tests Have Been Added

**Review by BenCookie95 — APPROVED** [review]
LGTM!

**Review by sbishel — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
All looks good,

**Pull request merged**
