### PR TITLE
MM-9753 - Header UI updates

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-9753 - Header UI updates

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-9753

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by amyblais** [comment]
@asaadmahmood Is this WIP or is this good for a PM/dev review?

**Comment by asaadmahmood** [comment]
@amyblais Yup, its up for review now.

**Comment by asaadmahmood** [comment]
Hey @esethna just checked. Looks like it is behaving as expected. The sidebar goes in overlay mode at  around 1020px (this feature is quite old). This is to avoid the content being squished too much.

**Comment by esethna** [comment]
Cool, looks good Asaad!

**Pull request merged**
