### PR TITLE
[MM-16043] Auto focus first interactable element on settings modal

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
This adds a bit of code on component mount for any open settings item to force focus to the first interactable element (ie. `button`, `a`, `input`, `textarea`, etc.)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16043

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@devinbinnie Can't we just apply the `autoFocus` property to the markup?

**Comment by devinbinnie** [comment]
> @devinbinnie Is there a reason why we're not using `autoFocus` and doing this globally?

@asaadmahmood The `autoFocus` attribute only works with `<input>` elements, but won't work with `<a>` elements, which we use in a few different components instead of `buttons`. We also have a few cases where `buttons` are rendered dynamically based on system or user settings, and it's hard to determine which elements to set the `autoFocus` attribute to (eg. `createSignInSection()` method of `user_settings_security.jsx` component, where the buttons are added to the DOM based on system settings).

It would be doable to manually figure out each case, but I thought this might be a cleaner way of fixing all the focus issues for all settings sections in modals. However, I'm not sure it's the best way of setting focus globally. I'm still a little new to React, is there something I'm missing?

**Comment by asaadmahmood** [comment]
@devinbinnie Using global selectors like this one might not be the most ideal way to do things in react. We usually use `refs` or `findDomNode` to fetch elements.

But maybe if @deanwhillier is okay doing it this way for now, then maybe it's fine for now, and we can think about it more later.

**Comment by devinbinnie** [comment]
@asaadmahmood That `focus-trap-react` package you're using on https://github.com/mattermost/mattermost-webapp/pull/3118/ could also solve this issue I believe, the caveat being that you'd have to hit the cancel button to get out. What do you think?

**Comment by asaadmahmood** [comment]
Oh okay wait, I didn't see the ticket properly, we do not need to do this.
The `focus-trap-react` is primarily to trap the focus, it automatically though focuses the first active element, and using it on the setting-item_max would not make sense, because we would still want the user to navigate outside of it.

If we have a look at the other setttings, like the generals tab, this issue does not repro there. So there seems to be an issue with the edit functionality, the thing is, we need the edit button to be focused only when the sidebar item (General, Security, Display) is select, not always.

If you have a look at the behaviour in the General tab, that works fine, so if click on any of the section in the General tab like "Username" and then press save or cancel, it takes me to the edit button in the next section.

This solution may fix the issue only when you open the section, but will not fix that, and that issue already seems to be fixed in most other places, so we just need to follow what is being done there.

**Comment by deanwhillier** [comment]
What about just converting `<a>`'s into `<buttons>` and applying the `autofocus` attribute?

[`<button>`'s, `<input>`'s, `<select>`'s and `<textarea>`'s all support `autofocus`](https://www.w3schools.com/tags/att_autofocus.asp).

**Comment by devinbinnie** [comment]
> What about just converting `<a>`'s into `<buttons>` and applying the `autofocus` attribute? That would keep it consistent with how the other sections with `<input>`'s currently work.
> 
> [`<button>`'s, `<input>`'s, `<select>`'s and `<textarea>`'s all support `autofocus`](https://www.w3schools.com/tags/att_autofocus.asp).

@deanwhillier It would require a fair bit more logic due to the cases like the one I mentioned above with `user_settings_security.jsx`. I'll bet there are more cases like that. However if that's the right way to go, we can do it, it'll just take more time to track down and find the issues.

**Comment by deanwhillier** [comment]
@devinbinnie, took a closer look and ya, I see what you're saying. It's certainly doable to add the logic to apply `autofocus` appropriately, but as you say that may take more time that we currently have and we are already doing similar things for the initial MVP of a11y support.

**Comment by asaadmahmood** [comment]
I would suggest we still fix that one case properly for that one section, and then we can take care of all the other sections later.

**Comment by asaadmahmood** [comment]
Cool.

**Pull request merged**
