### PR TITLE
MM-41870/MM-41872 Add debug settings to disable "User is typing..." and telemetry events

### PR DESCRIPTION
**Pull request by hmhealey**
These are based on a couple theories we had about past performance issues. I ended up submitting these together since the PRs would've conflicted if I didn't.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41870
https://mattermost.atlassian.net/browse/MM-41872

#### Release Note
```release-note
Added additional performance debugging settings
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Comment by jgilliam17** [comment]
@hmhealey is the setting for "user is typing" disabling the feature both ways e.g. other users can't see you are typing and you can't see other users typing?

**Comment by jgilliam17** [comment]
[E2E report](https://automation-dashboard.vercel.app/cycles/fce49e67-6d4d-4590-8fb0-d620e2566108) looks good - no PR related failures.

**Comment by hmhealey** [comment]
@jgilliam17 Yeah, that's correct. Any user with it turned on won't see "user is typing..." for other users, and they won't send the event that triggers other users to see that they're typing

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
- Verified performance debugging settings for disabling "user is typing" and telemetry events.

**Comment by cwarnermm** [comment]
Documented via https://github.com/mattermost/docs/pull/5524

**Pull request merged**
