### PR TITLE
MM-42490_Rename new footer and header containers' classnames

### PR DESCRIPTION
**Pull request by julmondragon**
#### Summary
Apply new designs for the Signup screen - Rename new footer and header containers' classnames to avoid affecting other components.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42490

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/10324

##### Before
Screen Shot 2022-05-24 at 1 37 16 PM

##### After
Screen Shot 2022-05-24 at 2 52 17 PM

##### New login/signup
Screen Shot 2022-05-24 at 2 54 18 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks @julmondragon! Can we rename the PR to avoid confusion with the commit of the actual complete revamp work?

**Review by JulienTant — APPROVED** [review]
LGTM @julmondragon

**Pull request merged**
