### PR TITLE
fix name label tooltips in LHS

### PR DESCRIPTION
**Pull request by antonbuks**
#### Summary
I noticed on community that groups with long display names don't have tooltips in the LHS sidebar so I went digging in the code and noticed that during render the label gets added a `truncated` class that adds an overflow hidden, preventing the render condition for the tooltip `const showTooltip = element && element.offsetWidth < element.scrollWidth` from passing (since overflow hidden makes `element.scrollWidth` equal to `element.offsetWidth` effectively resetting `showTooltip` to `false`).

I fixed this by moving the truncate class to a wrapping element which is added only when a tooltip needs to be rendered.

A better solution might be rewriting the render logic for this component that also preserves the flex on the wrapper instead of replacing it with display block to apply the truncate, however as I understand the flex is just used to stretch the short labels to fill 100% of the sidebar width for the action menu trigger to always be aligned on the right which is unnecessary anyway for the labels that pass the tooltip condition so in my opinion it's a good temporary solution.

#### Screenshots
current hover behaviour (tooltip should show and text should be truncated):

Screenshot 2022-06-07 at 17 51 40

after PR (tooltip shows + name truncated with ...):

Screenshot 2022-06-07 at 18 05 00

#### Release Note
```release-note
UI: fix truncate and tooltip display for long name labels in LHS sidebar
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR! I'm not seeing this bug with the the GM channels I'm in, but perhaps it's inconsistent since I could definitely see how what you're describing would come up.

Most of this looks good, but could you remove the old `&.truncated` rule on line 1099 of `_sidebar-left.scss`? I don't think it'll apply any more with these changes

**Review by hmhealey — APPROVED** [review]
Thanks for removing that!

**Comment by jgilliam17** [comment]
@nevyangelova Can you please check and approve the 1st time contributor workflow below? Thanks 🙂

**Comment by jgilliam17** [comment]
Thanks for approving the workflow and running the e2es @hmhealey 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/209002-1d2d659-onprem-ent-webapp-pr-10509-mattermost/mm-ee-test1d2d659/mochawesome.html) looks good, failures are not PR related. LGTM

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
