### PR TITLE
Migrate lazy loading to use React.lazy rather than bundle-loader

### PR DESCRIPTION
**Pull request by anindha**
#### Summary

Replace bundle-loader and AsyncComponent with React.Lazy and React.Suspense.

#### Advantages of this approach:
- Easier for new developers to understand standard React way of lazy loading rather than proprietary code.
- Drops a an unneeded library.
- It makes it easy for further UX improvements such as eager loading and adding loaders

#### Testing
- Ran production build locally testing bundle sizes, no difference
- Checked bundle size using [webpack monitor](http://webpackmonitor.com/), no difference

Thanks to @sudheerDev for his help with this!

### CODE REVIEW

**Comment by hanzei** [comment]
@anindha Thanks for the PR! Does this change target a Help Wanted ticket?

**Comment by sudheerDev** [comment]
> @anindha Thanks for the PR! Does this change target a Help Wanted ticket?

Nope. I will create a ticket in jira for tracking this.

**Comment by anindha** [comment]
> Mattermost test server created! 🎉
> 
> Access here: https://mattermost-webapp-pr-3981.test.mattermost.cloud

Thanks for this. Is there an equivalent test server for master? I want to compare the two directly.

**Comment by sudheerDev** [comment]
@anindha Here you can compare with test server on https://github.com/mattermost/mattermost-webapp/pull/3962.

**Comment by anindha** [comment]
> @anindha Here you can compare with test server on #3962.

The servers serve the same file sizes. There doesn't seem to be a functional change.

**Comment by sudheerDev** [comment]
@anindha Code changes LGTM but there is a flash when opening `account settings` modal can you take a look at it?

**Comment by sudheerDev** [comment]
i guess it is related to concurrent mode https://github.com/facebook/react/issues/14438 https://dev.to/stereobooster/friday-hack-suspense-concurrent-mode-and-lazy-to-load-locales-for-i18n-hgg

**Comment by anindha** [comment]
> @anindha Code changes LGTM but there is the page flash while loading `account settings` modal can you take a look at it?

@sudheerDev There is a problem in the way I added Suspense. I will investigate how to fix today.

**Comment by anindha** [comment]
Reworking this

**Pull request closed without merging**
