### PR TITLE
[MM-34742][MM-34743][MM-34745] - Hard coded values fixes

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR submits fixes requested by UX in regards to hardcoded theme colours. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34745
https://mattermost.atlassian.net/browse/MM-34743
https://mattermost.atlassian.net/browse/MM-34742

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM!

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
nice work @nevyangelova.

I'd like to request a change if possible. For the Active State in the LHS, can we change it to 8% opacity? When I customize the theme to use a light colored sidebar, 16% is too heavy.

Also, I can't really test the github plugin bar on the test server, but maybe you could provide a few screenshots with different themes to ensure it's resolved?

**Comment by nevyangelova** [comment]
@matthewbirtch fixed and attaching screenshots: 
Screenshot 2021-04-16 at 17 40 53
Screenshot 2021-04-16 at 17 41 08
Screenshot 2021-04-16 at 17 41 27

**Review by matthewbirtch — APPROVED** [review]

**Comment by angeloskyratzakos** [comment]
Hi team, we got 2 log panics from that test workspace (mattermost-webapp-pr-7926.test.mattermost.cloud)
```
msg:http: panic serving 100.98.0.2:39294: runtime error: invalid memory address or nil pointer dereference goroutine 20641 [running]: net/http.(*conn).serve.func1(0xc0053e05a0) net/http/server.go:1801 +0x147 panic(0x27803c0, 0x430d240) runtime/panic.go:975 +0x47a github.com/getsentry/sentry-go/http.(*Handler).recoverWithSentry(0xc00537c930, 0xc001b7f9e0, 0xc0020acc00) github.com/getsentry/sentry-go@v0.10.0/http/sentryhttp.go:117 +0x14f panic(0x27803c0, 0x430d240) runtime/panic.go:969 +0x1b9 github.com/mattermost/mattermost-server/v5/app.(*App).MarkChannelAsUnreadFromPost(0xc00646f7a0, 0xc005481bc4, 0x1a, 0xc005481ba3, 0x1a, 0x178eba3b96d, 0x1798622816d) github.com/mattermost/mattermost-server/v5/app/channel.go:2405 +0xa62 github.com/mattermost/mattermost-server/v5/api4.setPostUnread(0xc002275740, 0x2faf820, 0xc0022756c0, 0xc0020ace00) github.com/mattermost/mattermost-server/v5/api4/post.go:656 +0x36b github.com/mattermost/mattermost-server/v5/web.Handler.ServeHTTP(0xc000c6bb40, 0x2c7c4c8, 0x4096f18, 0xd, 0x100000001, 0x0, 0x0, 0x2fb28a0, 0xc00199c850, 0xc0020ace00) github.com/mattermost/mattermost-server/v5/web/handlers.go:298 +0x1f32 github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2fb22a0, 0xc00653c0e0, 0xc0020ace00) github.com/NYTimes/gziphandler@v1.1.1/gzip.go:337 +0x225 net/http.HandlerFunc.ServeHTTP(0xc002487d70, 0x2fb22a0, 0xc00653c0e0, 0xc0020ace00) net/http/server.go:2042 +0x44 github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001be240, 0x2fb22a0, 0xc00653c0e0, 0xc0020acc00) github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3 github.com/getsentry/sentry-go/http.(*Handler).handle.func1(0x2fb22a0, 0xc00653c0e0, 0xc0020acb00) github.com/getsentry/sentry-go@v0.10.0/http/sentryhttp.go:103 +0x402 net/http.HandlerFunc.ServeHTTP(0xc000ddf280, 0x2fb22a0, 0xc00653c0e0, 0xc0020acb00) net/http/server.go:2042 +0x44 net/http.serverHandler.ServeHTTP(0xc001d3ac40, 0x2fb22a0, 0xc00653c0e0, 0xc0020acb00) net/http/server.go:2843 +0xa3 net/http.(*conn).serve(0xc0053e05a0, 0x2fbc7a0, 0xc001c2aa00) net/http/server.go:1925 +0x8ad created by net/http.(*Server).Serve net/http/server.go:2969 +0x36c @timestamp:Apr 19, 2021 @ 23:05:28.073 log:{"level":"error","ts":1618862728.0730517,"caller":"http/server.go:3093","msg":"http: panic serving 100.98.0.2:39294: runtime error: invalid memory address or nil pointer dereference\ngoroutine 20641 [running]:\nnet/http.(*conn).serve.func1(0xc0053e05a0)\n\tnet/http/server.go:1801 +0x147\npanic(0x27803c0, 0x430d240)\n\truntime/panic.go:975 +0x47a\ngithub.com/getsentry/sentry-go/http.(*Handler).recoverWithSentry(0xc00537c930, 0xc001b7f9e0, 0xc0020acc00)\n\tgithub.com/getsentry/sentry-go@v0.10.0/http/sentryhttp.go:117 +0x14f\npanic(0x27803c0, 0x430d240)\n\truntime/panic.go:969 +0x1b9\ngithub.com/mattermost/mattermost-server/v5/app.(*App).MarkChannelAsUnreadFromPost(0xc00646f7a0, 0xc005481bc4, 0x1a, 0xc005481ba3, 0x1a, 0x178eba3b96d, 0x1798622816d)\n\tgithub.com/mattermost/mattermost-server/v5/app/channel.go:2405 +0xa62\ngithub.com/mattermost/mattermost-server/v5/api4.setPostUnread(0xc002275740, 0x2faf820, 0xc0022756c0, 0xc0020ace00)\n\tgithub.com/mattermost/mattermost-server/v5/api4/post.go:656 +0x36b\ngithub.com/mattermost/mattermost-server/v5/web.Handler.ServeHTTP(0xc000c6bb40, 0x2c7c4c8, 0x4096f18, 0xd, 0x100000001, 0x0, 0x0, 0x2fb28a0, 0xc00199c850, 0xc0020ace00)\n\tgithub.com/mattermost/mattermost-server/v5/web/handlers.go:298 +0x1f32\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2fb22a0, 0xc00653c0e0, 0xc0020ace00)\n\tgithub.com/NYTimes/gziphandler@v1.1.1/gzip.go:337 +0x225\nnet/http.HandlerFunc.ServeHTTP(0xc002487d70, 0x2fb22a0, 0xc00653c0e0, 0xc0020ace00)\n\tnet/http/server.go:2042 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0001be240, 0x2fb22a0, 0xc00653c0e0, 0xc0020acc00)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3\ngithub.com/getsentry/sentry-go/http.(*Handler).handle.func1(0x2fb22a0, 0xc00653c0e0, 0xc0020acb00)\n\tgithub.com/getsentry/sentry-go@v0.10.0/http/sentryhttp.go:103 +0x402\nnet/http.HandlerFunc.ServeHTTP(0xc000ddf280, 0x2fb22a0, 0xc00653c0e0, 0xc0020acb00)\n\tnet/http/server.go:2042 +0x44\nnet/http.serverHandler.ServeHTTP(0xc001d3ac40, 0x2fb22a0, 0xc00653c0e0, 0xc0020acb00)\n\tnet/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc0053e05a0, 0x2fbc7a0, 0xc001c2aa00)\n\tnet/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:2969 +0x36c","source":"httpserver"} stream:stderr time:Apr 19, 2021 @ 23:05:28.073 level:error ts:1,618,862,728.073 caller:http/server.go:3093 source:httpserver kubernetes.pod_name:mm-7ud9-74d84c479f-ss9dn kubernetes.namespace_name:7ud9i6gad7gtfbxj4ogn58yo6e kubernetes.pod_id:d32d8de2-5448-4464-97f7-170d281aa4b3 kubernetes.labels.app:mattermost kubernetes.labels.installation_mattermost_com/installation:mm-7ud9 kubernetes.labels.installation_mattermost_com/resource:mm-7ud9 kubernetes.labels.pod-template-hash:74d84c479f kubernetes.host:ip-10-160-0-195.ec2.internal kubernetes.container_name:mattermost kubernetes.docker_id:0e6b522e7f8810c28bc307581559a9750eb498d33a593efba4498ebfeea8098f kubernetes.container_image:mattermost/mattermost-enterprise-edition:8987813 _id:qfi863gBbvcN2_Ln5YX_ _type:_doc _index:logstash-2021.04.19 _score: -
```

**Comment by michelengelen** [comment]
Hi @angeloskyratzakos are you sure this could potentially be coming from changes in this PR.
IMO it is not very likely since this PR only includes SCSS changes.

**Pull request merged**
