### PR TITLE
Fixing a typo in translation from 0365 to O365

### PR DESCRIPTION
**Pull request by YetAnotherBlogArticle**
#### Summary
Fixing a small typo (0365->O365)

#### Ticket Link
https://translate.mattermost.com/translate/mattermost/mattermost-webapp_master/en/?checksum=9d9f72ea51311df5
#### Related Pull Requests
None
#### Screenshots
Screenshots

#### Release Note
```release-note
None
```

### CODE REVIEW

**Comment by YetAnotherBlogArticle** [comment]
I'm working on a blog post 'Git for non-developers' so I created a new username to start from scratch but hey, it's just me: @ctlaltdieliet :wave:

**Comment by M-ZubairAhmed** [comment]
@YetAnotherBlogArticle you might need to run mmjstool to extract the translations into en.json i18n file

**Review by M-ZubairAhmed — COMMENTED** [review]
@YetAnotherBlogArticle you might need to run mmjstool to extract the translations into en.json i18n file

**Review by nevyangelova — APPROVED** [review]
LGTM!

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @YetAnotherBlogArticle 
Tested, looks good to merge.
- Verified text change
- [E2E report ](url), failures are not related, being address separately

**Pull request merged**
