### PR TITLE
MM-49764: Fixes truncation of username when not needed

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Fixes the truncation of usernames if no other field (i.e. full name) are present in the suggestion list item.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49764

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2023-01-19 at 4 14 38 PM | Screenshot 2023-01-19 at 5 28 33 PM |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by koox00** [comment]
@larkox In this case we had `max-width: 89%` in the parent, as well as in the child,
and both the parent and child with a rules to truncate text, so white-space: nowrap; overflow: hidden;.
What was happening is that the parent was taking the exact width of the child, but then the child can take up to 89% of the parent, and because we are truncating it's not visible.

I've made an example sandbox for experimenting with that.
https://codesandbox.io/s/cool-violet-yvc7hz?file=/index.html

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by michelengelen — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @koox00 
Tested, looks good to merge
Verified usernames are not truncated when full name and last name are not set
- 1 mention suggestion list test case failed MM-T183 , but it seems to be unrelated, since it also started failing on master on Jan 17th
see full [e2e report ](https://mattermost-cypress-report.s3.amazonaws.com/290821-46d3f82-onprem-ent-webapp-pr-12030-mm-ee-test:46d3f82/mochawesome.html)

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
