### PR TITLE
Fixing FullScreen modal styles usage from plugins

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Fixing FullScreen modal styles usage from plugins

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40625

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
This fix seems weird to me. How are plugins able to use full screen modals without importing the CSS? Are they just using the CSS classes without actually using the JS code for the modals in the web app?

**Comment by jespino** [comment]
@hmhealey exactly, they are using the css classes but not the JavaScript. They do all the logic to show/hide but leverage the existing classes for the styling part (including the visibility and the positioning)

**Comment by amyblais** [comment]
@jespino Let me know if you found out which commit/PR caused this bug.

**Comment by jespino** [comment]
@amyblais it was introduced here: #9367 

This shouldn't affect the release because was merged like 3 days ago.

**Review by hmhealey — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by amyblais** [comment]
@jespino Does this need QA?

**Comment by jespino** [comment]
@amyblais sorry, the answer is yes, it needs QA because we need confirmation that the issue is gone.

**Comment by jgilliam17** [comment]
@jespino Would you be able to add To Do plugin? Manual plugin upload is disabled on the test servers. Thanks

**Comment by jgilliam17** [comment]
I reviewed [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/102916-fb3d5be-onprem-ent-webapp-pr-9541-mattermost/mm-ee-testfb3d5be/mochawesome.html) and retested 3 tests that are failing on the PR, but not on the master.
They are passing when testing manually, listing below for visibility 
MM-T613
MM-T1958
MM-T952

**Comment by mickmister** [comment]
> @hmhealey exactly, they are using the css classes but not the JavaScript. They do all the logic to show/hide but leverage the existing classes for the styling part (including the visibility and the positioning)

@jespino Do you have an example of what plugins should be doing to properly load the webapp's modal css, so I can ensure all plugins are doing this correctly? Most plugins are currently not using `openModal`, which is something we can take care of simultaneously with the fix to all the plugins using modals.

**Comment by mickmister** [comment]
@jespino @hmhealey

Here is some discussion on the history of this https://community.mattermost.com/core/pl/tcwouk5uqb8cbjn7dpnr76gyfr. Basically there were css conflicts when the plugins were setting up their own css classes, and the solution chosen was to just remove the css from the plugins. Indeed at the moment there is no webapp-provided js being used by most the plugins for any modal-related functionality.

**Comment by amyblais** [comment]
@jespino Let me know if we're able to get this merged before Jan 19th cloud release.
Optionally this may need to be reverted https://github.com/mattermost/mattermost-webapp/pull/9367 from the cloud branch.

**Comment by amyblais** [comment]
@jgilliam17 Does this also affect Cloud test servers?
I'm trying to determine if this is high priority for the next cloud release.

**Comment by jgilliam17** [comment]
@amyblais Yes, this is also present on the cloud test servers. (tested on https://cloud-rc.test.mattermost.cloud )

**Comment by jgilliam17** [comment]
@jespino just to follow up, are you able to add multiple plugins to the test server for testing, including the todo plugin? Manual upload is disabled for me. Let me know. Thanks.

**Comment by jespino** [comment]
@jgilliam17 I don't think I can add plugins tot he test server, I manually tested it when I developed it in my local environment. Taking into consideration the size of the PR can we test this after merge?

**Comment by mickmister** [comment]
FYI I also tested this locally and it's working correctly

> Taking into consideration the size of the PR can we test this after merge?

I agree :+1: cc @jgilliam17

**Comment by jgilliam17** [comment]
Thanks @jespino and @mickmister - I agree, QA can test after merge.

**Review by jgilliam17 — APPROVED** [review]
QA will test after merge.

**Comment by mickmister** [comment]
@jespino I want to make sure the proper fix is applied to the plugins as well. Making changes like the lazy loading PR should not break things with plugins. There's a coupling between the two systems (webapp and plugins) that needs to be resolved.

I'm not sure what that fix is that needs to be applied to the plugins though. Based on https://github.com/mattermost/mattermost-webapp/pull/9541#issuecomment-995471527, it seems to be Javascript-based. I can ensure the fix is applied to all plugins once I know what fix needs to be applied.

**Comment by mickmister** [comment]
@jespino Do you mind if we merge this?

**Comment by jespino** [comment]
@mickmister no problem, go ahead

**Pull request merged**
