### PR TITLE
[MM-39106] Fix emoji size in post menu for one-click reactions

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Fix the size of the one-click reaction emojis.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39106

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by Rina-dsg** [comment]
@isacikgoz can we try ~16pt size for emojis? 18pt seems still too big

**Comment by isacikgoz** [comment]
Hmm, interesting.. I only changed css file.

**Comment by alauregaillard** [comment]
@emilyacook please can you create the QA hacktoberfestissue? I want to QA it.

**Comment by jgilliam17** [comment]
Thanks @alauregaillard for testing. I'll merge shortly.
>When you click on "Add reaction" emoji size is bigger. May be to be improved in another issue?

This PR only reduces the size of recently used emoji in the post menu, we are not changing the existing emoji size in the emoji picker. 
Hope that answers your question.
Thank you again for your contribution! 🙂

**Pull request merged**
