### PR TITLE
[MM-35110] Change plugin header count from 5 to 15

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR will change plugin header count from 5 to 15 in e2e tests

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-35110

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Review by saturninoabril — CHANGES_REQUESTED** [review]
Thanks @iomodo for updating, especially the update to "test plugin". I ran the test and passed. However, by looking at the original test case [MM-T1649](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T1649), I can't see the ff:
- on step 2, item 3 - "Verify that clicking the plugins icon opens drop-down menu with the list of plugins", and
- on step 3, item 2 - "Disable one of the plugins, (then) Verify the plugin icons in top nav expand out to show individually rather than being collapsed behind one icon".
Let me know how you'd like to proceed.

Todo: I'll update the test case in Zephyr to reflect the change of 5 to 15 plugin header count.

**Review by mickmister — APPROVED** [review]

**Comment by iomodo** [comment]
My bad, not sure how I missed that. Thanks @saturninoabril for pointing out

**Review by crspeller — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Great, thanks @iomodo!

**Pull request merged**
