### PR TITLE
MM-17619 Fix for scroll correction issue in Edge

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
  * element.scrollBy does not exist on edge so it depends on scrollTo for correction
   https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollBy#Browser_compatibility

  * scrollTop on postListref will always be zero and parentElement should be considered for scrollTop which then passes the right values for scrollTo

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-17619

### CODE REVIEW

**Comment by lindalumitchell** [comment]
Okay for QA to test this after it's merged. Removing QA Review label.

**Comment by sudheerDev** [comment]
> I'm not seeing the big jumps I was seeing before, but the scrolling is still jumping slightly when a new page is loaded.

I was working out of browserstack so i had a delay with scroll ingeneral so overlooked it. Will check this again

> Is this PR missing some of the changes you mentioned? I don't see anything referencing scrollBy here

https://github.com/mattermost/react-window/blob/7b3d8686954c06427549518eab886ae678347bd8/src/createListComponent.js#L173
If browser does not support element.scrollBy react-window does use scrollTop but the value for scrollTop would be different compared to scrollBy

**Comment by hmhealey** [comment]
If Browserstack is slow for you, you could try using one of the VMs that Microsoft provides ([link](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)). I could also try to help since I've got a Windows PC I can use.

I see what you meant with `scrollBy`. I had thought you meant that it was a new change

**Comment by sudheerDev** [comment]
@hmhealey No luck on this. Was occupied with another release ticket which is slightly more important. I am inclined to having rather have another ticket later for the minor jump as this is really close to release now.

@amyblais The ticket for rather big jumps on edge. This PR solves it but it still jumps slightly. I think we should have this as it is and fix the rest of the issue for 5.15v. FYI i dont think this is a regression in the first place

**Comment by amyblais** [comment]
"I think we should have this as it is and fix the rest of the issue for 5.15v." - Sounds good to me.

**Comment by hmhealey** [comment]
@sudheerDev CircleCI is having issues for some reason, and it refuses to rebuild the current commit. Can you add some more changes to this to get CircleCI to rebuild? If you merge master, that should fix it

**Pull request merged**
