### PR TITLE
[GH-15906][MM-22844] Add images for email notification redesign

### PR DESCRIPTION
**Pull request by jp0707**
#### Summary
Add images for email notification redesign. 

#### Ticket Link
  https://github.com/mattermost/mattermost-server/issues/15906

### CODE REVIEW

**Comment by jp0707** [comment]
@nickmisasi Please take a look. These are based on this [figma file](https://www.figma.com/file/xMMUFcqIFlyiJlIhLMlcWX/MM-22844-Email-Notification-Redesign?node-id=42%3A56)

**Comment by esethna** [comment]
@devinbinnie and @nickmisasi gentle ping on this, thx!

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @jp0707!

**Review by nickmisasi — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]

**Pull request merged**
