### PR TITLE
[MM-24999] fix css on Copy Theme Colors button

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR fixes the CSS of the `Copy Theme Colors` button.

The proposed solution is attached in the screenshots below.  I'm not positive of the original intention for the CSS of the button.  Regarding UX, do we prefer to use a clickable link, instead of the visible button?

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24999

#### Screenshots
Before:
image

After: 
image

### CODE REVIEW

**Comment by jfrerich** [comment]
Thanks, @andrewbrown00.  I'm completely hacking with CSS and appreciated the suggestions.  Looking at my last commit, I reverted to use the `copy-theme-button` class again.  I found the `v()` function used elsewhere and set the button text color using `color: v(button-bg);`

Here are couple of screenshots showing the button text matching the `button-bg`, which is shown in the `Save` button	

Mattermost Theme
image
image

Windows Dark Theme
image
image

**Comment by jfrerich** [comment]
@andrewbrown00, that makes sense.  Now the button is tracking the link colors as shown in your images.  I also verified change the link color also changes the button and border text.

**Comment by andrewbrown00** [comment]
@jfrerich the test server shows up blank when I go to https://mattermost-webapp-pr-5492.test.mattermost.cloud, any idea why?

**Comment by jfrerich** [comment]
> @jfrerich the test server shows up blank when I go to [mattermost-webapp-pr-5492.test.mattermost.cloud](https://mattermost-webapp-pr-5492.test.mattermost.cloud), any idea why?
I am not sure what is causing the white screen, but I am getting it too.

**Comment by bradjcoughlin** [comment]
@jfrerich I'm seeing this white screen fairly often, too.

**Comment by jfrerich** [comment]
Thanks, @cpanato for the fix and @bradjcoughlin for the additional confirmation regarding the white screen.

@andrewbrown00, I was able to load the cloud instance and see the change.

**Comment by lieut-data** [comment]
@nevyangelova, can you help as a second dev reviewer?

**Pull request merged**
