### PR TITLE
Link previews and styled components

### PR DESCRIPTION
**Pull request by stephenkiers**
#### Summary
This is a multi-function PR.

1) It is a demo of styled components
2) it is a re-write of open-graph attachments
3) it adds bootstrap-4 (namespaced by prepending `bs4-` to classes)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Has UI changes

### CODE REVIEW

**Comment by stephenkiers** [comment]
I don't understand why spinmint isn't working. If you can get it working, try adding some links that generate open graph previews.

Ex. 

- Twitter : https://twitter.com/elonmusk/status/960992715579125760
- https://cloudingo.com/pricing/
- Zoom - https://zoom.us/j/688620921
- Github - https://github.com/mattermost/mattermost-webapp/pull/770

**Comment by asaadmahmood** [comment]
@stephenkiers Not too sure on how to use styled components for now, but after some research, I think styled components are the way to go. However, I can't comment much on the code for now.

I see that you included bootstrap v4, however I still do not see that in affect on the spinmint.

**Comment by stephenkiers** [comment]
@asaadmahmood I included bootstrap4, but I name spaced all the classes with `.bs4-` so that the bootstrap 3 stuff is unaffected. We can go through and update the old bootstrap files. When done we can remove all the namespacing. 
But this way we can use both in the same app. I will document this somewhere else. :)

**Comment by asaadmahmood** [comment]
@stephenkiers Before we merge, I'd like to know, why are the links preview taking the css from the main file instead of styles being applied directly in the html?
Did we not remove those styles from the css?
screen shot 2018-02-13 at 8 15 07 pm

**Pull request closed without merging**
