### PR TITLE
[MM-36626] fix emoji picker colors

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

Some colors were not following the theme guidelines.

#### Ticket Link
[MM-36626](https://mattermost.atlassian.net/browse/MM-36626)

#### Screenshots
Screen Shot 2021-06-23 at 01 37 06

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
Looks much better @Willyfrog. A couple tweaks:

- The 'Custom Emoji' button text should be `color: var(--button-bg);`. It looks like it's getting overriden.
- While we're at it, can we adjust the **hover state** on this button?
  - remove the underline
  - change the background color to `background-color: rgba(var(--button-bg-rgb), 0.12);`

**Comment by matthewbirtch** [comment]
Thanks @Willyfrog, I'm not seeing the requested hover state change on the background for the `Custom Emoji` button. The underline is removed, but the background color doesn't change.

One other thing I just noticed: The gif tab and the Emojis tab seem to have inconsistent styling:
1. In the default state for inactive tabs, the color should be `var(--center-channel-color-56)`
2. In the hover state for inactive tabs, the color should be `var(--center-channel-color-72)`

**Review by matthewbirtch — APPROVED** [review]
🎉

**Review by jwilander — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @Willyfrog 
Tested, looks good to merge.
- Verified skin selector respects theme.

**Pull request merged**
