### PR TITLE
[MM-42020] Fix Categorization of Permissions

### PR DESCRIPTION
**Pull request by mylonsuren**
#### Summary

Fixes categorization of permissions for posts, integrations, and shared channels.

#### Ticket Link

Fixes [MM-42020](https://mattermost.atlassian.net/browse/MM-42020)

#### Screenshots

|  Before  |  After  |
|----|----|
| image | image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Thanks @mylonsuren LGTM

image

**Pull request merged**
