### PR TITLE
[MM-20607] Migrate 'components/modal_controller'  to Typescript

### PR DESCRIPTION
**Pull request by dantepippi**
#### Summary

This pull request migrates 'components/modal_controller' to Typescript 

Closes https://github.com/mattermost/mattermost-server/issues/13467
JIRA ticket: https://mattermost.atlassian.net/browse/MM-20607

### CODE REVIEW

**Comment by jasonblais** [comment]
Hi @dantepippi, thanks for your contribution! Looks like this PR is in draft stage. Let us know if you questions to help get this ready for review? Thank you!

**Comment by dantepippi** [comment]
> Hi @dantepippi, thanks for your contribution! Looks like this PR is in draft stage. Let us know if you questions to help get this ready for review? Thank you!

Greetings @jasonblais. I'm sorry for the delay. I was interested in learning more about Typescript and the webapp but got stuck with not much time for studying those. I did ask for [directions](https://community.mattermost.com/core/pl/8jfeu173ftn4dr5uauwfmcfbra) some time ago but haven't heard back.
I'll try to get back to this ASAP.

**Comment by jasonblais** [comment]
@dantepippi thanks! I also pinged a developer on the question you asked few weeks back.

**Comment by devinbinnie** [comment]
Hey @dantepippi, sorry for the delay on a response.
Can you tell me which line you're seeing the error you mentioned in the TypeScript Migration channel?

**Comment by dantepippi** [comment]
> Hey @dantepippi, sorry for the delay on a response.
> Can you tell me which line you're seeing the error you mentioned in the TypeScript Migration channel?



> Hey @dantepippi, sorry for the delay on a response.
> Can you tell me which line you're seeing the error you mentioned in the TypeScript Migration channel?

[This ](https://github.com/mattermost/mattermost-webapp/blob/b6e0c91d18765d9a03a71f434432d63ef91788e6/components/modal_controller/modal_controller.test.tsx#L16) line

**Comment by devinbinnie** [comment]
> > Hey @dantepippi, sorry for the delay on a response.
> > Can you tell me which line you're seeing the error you mentioned in the TypeScript Migration channel?
> 
> [This ](https://github.com/mattermost/mattermost-webapp/blob/b6e0c91d18765d9a03a71f434432d63ef91788e6/components/modal_controller/modal_controller.test.tsx#L16) line

Ahh okay, we'll want to add the `onHide` prop to that component. You can just use the mock function `jest.fn()` as the parameter.

**Comment by jasonblais** [comment]
Hey @dantepippi, let us know if the above was helpful. We'd be happy to help :)

**Pull request closed without merging**
