### PR TITLE
MM-19551: Track plugin id for default marketplace

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
When the default marketplace is configured, track the plugin id, current version, and target version for all install and update events. Never track this information for `Configure` events, since non-marketplace plugins may show up here.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19551

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/13183

### CODE REVIEW

**Comment by lieut-data** [comment]
@aaronrothschild is out this week, but had already asked for these changes.

**Comment by prapti** [comment]
@lieut-data I'm getting a JavaScript error while trying to install a plugin both locally as well as in the PR SpinWick: `Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.`

**Comment by lieut-data** [comment]
Sorry about that, @prapti -- tested with a unit test, but apparently failed in my testing of the e2e feature. Can you take a second look now?

**Comment by prapti** [comment]
@lieut-data reading the description of the PR, does `Configure` events mean clicking on the configure button on Marketplace that routes it to the plugin's configure page in system console (and not saving a configure in system console)?

**Comment by lieut-data** [comment]
@prapti, yes, this is referring to clicking `Configure` in the plugin marketplace. We will log a tracking event for same, but it won't include the plugin id unlike download and update.

**Pull request merged**
