### PR TITLE
Add .gitlab-ci.yml-compatible continuous integration configuration

### PR DESCRIPTION
**Pull request by jayaddison-collabora**
#### Summary
This changeset provides a GitLab-CI compatible YAML config to run linting and unit testing for `mattermost-webapp`.

The initially-presented filename `.gitlab-ci.collabora.yml` is what I've been using verbatim during development at @collabora - open to moving this to a `contrib` directory and/or otherwise reducing any namespace pollution or confusion.

As mentioned in mattermost/mattermost-server#17843, the [`CI_CONFIG_PATH`](https://docs.gitlab.com/13.12/ee/ci/variables/predefined_variables.html) can be used to configure GitLab CI to read from this configuration file on a per-repository basis.

#### Ticket Link
Relates to mattermost/mattermost-server#17843.

#### Release Note
This doesn't affect the functionality of the Mattermost product and application.

```release-note
NONE
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
hey, thanks for the PR, I'll assign some reviewers as I'm not familiar with gitlab's yml

**Review by cpanato — CHANGES_REQUESTED** [review]
agree in moving this to a contrib directory and not having it in the root.

Also will be good to have some documentation in how to use this

thanks for this PR!

**Comment by jayaddison-collabora** [comment]
Thanks @cpanato, I'll relocate the file soon.  Would somewhere under https://github.com/mattermost/mattermost-developer-documentation/tree/master/site/content/contribute be a good place to offer some corresponding documentation?

**Comment by cpanato** [comment]
@jayaddison-collabora I would say, this file should be in a directory maybe called `contrib` in this repo together with a README.md in the same directory to explain how to use that.

the documentation in the other repo will be good as well, but I would like to see something together with this addition

thanks!

**Comment by jayaddison-collabora** [comment]
Sounds good to me, thanks @cpanato!

**Review by metanerd — APPROVED** [review]
Thank you @jayaddison-collabora for your contribution! Great suggestion!

**Comment by jayaddison-collabora** [comment]
Thanks @metanerd!

**Comment by jayaddison-collabora** [comment]
There are at least two issues to address here I think:

- One is an immediate practical issue; the `test` build step has begun failing due to an upstream issue https://github.com/nodejs/full-icu-npm/issues/61 - I think it's best to resolve that by moving to a non-Alpine-based image, where a packaged distribution of ICU data is available (removing the need for the `full-icu` NPM package)

- A larger structural issue is that these continuous integration steps could be quite wasteful if they pull full base images on each pipeline run.  Building custom images and pushing them to a local registry (as the [existing `.gitlab-ci.yml` does](https://github.com/mattermost/mattermost-webapp/blob/4f94e80ea5809871d06e0c4610eb6f3b7c4f93fe/.gitlab-ci.yml#L8)) is a nice efficient way to resolve this, although it makes sharing the build and test infrastructure more challenging.  I feel like some of this is really an architecture issue with GitLab and container images more generally -- but in the short term, perhaps placing a `needs` dependency (or pipeline stage) between `lint` and `test` steps would at least mean that we don't duplicate network traffic and package installation for a pipeline that isn't going to succeed.  Alternatively, we could perform both linting and unit testing within a single job.

**Comment by jayaddison-collabora** [comment]
Some more thoughts: although running linting and unit tests is a start, I think a more valuable follow-on from this would be to add the ability to produce build packages of `mattermost-webapp` and `mattermost-server`.

That would require some careful planning because the webapp `dist` package is included in the server package build.  I think it'd be possible though: GitLab provides [multi-project pipelines](https://docs.gitlab.com/ee/ci/pipelines/multi_project_pipelines.html), so a change to either project could start a webapp build pipeline which in turn could [communicate a cross-project artifact](https://docs.gitlab.com/ee/ci/pipelines/multi_project_pipelines.html#pass-cicd-variables-to-a-downstream-pipeline-by-using-variable-inheritance) (NB: premium feature) and start a server build pipeline that includes that package.

A bonus would be to use the [`CI_COMMIT_TAG` predefined variable](https://docs.gitlab.com/13.12/ee/ci/variables/predefined_variables.html) and pass that through as the [`BUILD_NUMBER`](https://github.com/mattermost/mattermost-server/blob/249a0b98705e2969985d74713f7900bfd27366bc/Makefile#L22).

It's possible I might experiment with some of this soon, it'd make life easier in a bunch of ways.

**Comment by Willyfrog** [comment]
friendly ping @cpanato

**Pull request merged**
