### PR TITLE
[MM-28003] Fix autocomplete in DM

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR will fix slash command autocomplete in direct messages

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-28003

### CODE REVIEW

**Comment by amyblais** [comment]
@cpoile Kind reminder to review for v5.27,

**Comment by amyblais** [comment]
@iomodo Chris is off this week, can you help assign another dev for this?

**Review by jespino — APPROVED** [review]
LGTM

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed that auto-complete options are shown in DM channels 
- No issues sending auto-complete commands in DM chnnels
- Regression tested Public, Private and GFM channels
LGTM!

Added tests in TM4J to cover auto-complete in DM channels (as well as explicitly test RHS which also seemed to be a test not documented)

**Pull request merged**
