### PR TITLE
[MM-44519] Fixes missing replies in thread

### PR DESCRIPTION
**Pull request by koox00**
#### Summary
Currently we fetch updated thread items (not replies) from all teams upon reconnection,
so we have to assume that we always have updated reply counts stored.

However if a thread has already some replies stored in the browser when we open the thread
we fetch only newer replies than the last, this leads to missing messages when a post gets edited.
 
This commit fetches whole thread replies if counts have a difference (like we used to),
or fetches newer replies when counts are the same.

#### Release Note

```release-note
Fixes a bug where replies appear missing in threads
```

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Comment by jgilliam17** [comment]
E2E cycle failed, checking on git and restarting. Will approve after report posts.

**Comment by jgilliam17** [comment]
Thanks @koox00 
Tested, looks good to merge. 
- Verified thread reply count (repro steps shared in channel)- as expected  
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/197640-349950c-onprem-ent-webapp-pr-10345-mattermost/mm-ee-test349950c/mochawesome.html)looks good, no PR related failures.
- Ticket created to track testing after merge https://mattermost.atlassian.net/browse/MM-44519

**Review by jgilliam17 — APPROVED** [review]

**Comment by jgilliam17** [comment]
@amyblais I did not add fix version. Will this go in v7?

**Comment by koox00** [comment]
FWIW the code that introduced the bug is not in v6.7.0

**Pull request merged**
