### PR TITLE
T-8 merge release-4.8 into master

### PR DESCRIPTION
**Pull request by AndersonWebStudio**
Merging release-4.8 changes into master

### CODE REVIEW

**Comment by jwilander** [comment]
For these webapp merge PRs can we actually discard any changes to `yarn.lock`? It usually gets us pointing at the wrong branch for mattermost-redux since the release branch needs to point at the mattermost-redux release branch

**Comment by jwilander** [comment]
Oh and same for package.json as well

**Comment by AndersonWebStudio** [comment]
No problem @jwilander but I feel like doing that as a matter of process would be dangerous also? Will there ever be a change made in a release branch that requires a dependency change, or is that generally a no-no?

**Comment by jwilander** [comment]
Generally the answer is we shouldn't being adding/modifying dependencies in a release branch but it _does_ happen.

Maybe a better process is to just run the right yarn commands on this branch to point mattermost-redux back to master

**Comment by AndersonWebStudio** [comment]
I will start a different PR and pluck those 2 files out before the merge commit

**Comment by AndersonWebStudio** [comment]
I like that suggestion @jwilander i'll get this one done with pulling those then I can look at integrating yarn commands.

**Comment by jwilander** [comment]
Sounds good

**Pull request closed without merging**
