### PR TITLE
[MM-47621] Upgrade highlight.js to 11.6.0

### PR DESCRIPTION
**Pull request by m1lt0n**
#### Summary

In the context of regular dependency upgrades, this is the upgrade of highlight.js to version 11.6.0 (minor version upgrade).

| From version | To Version | Change log | Notes |
| ------------- | ------------- | ------------- | ------------- |
| 11.5.1  | 11.6.0  | [changelog](https://github.com/highlightjs/highlight.js/releases/tag/11.6.0) | Changes are dropped support for node 12.x and fixes or enhancements of grammars |

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47621

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Comment by hmhealey** [comment]
Is there anything in here that might affect https://github.com/mattermost/mattermost-webapp/pull/11303? Hopefully this won't cause any issues for that PR since it's adding lazy loading for highlight.js

**Comment by m1lt0n** [comment]
@hmhealey from the changelog between 11.5.1->11.6.0, there are only fixes and enhancements in grammar of different languages, nothing else (apart from dropping support for Node 12.x), so I don't expect something. cc: @sk409 for visibility

**Comment by jgilliam17** [comment]
Re-running e2es, last run [cycle](https://automation-dashboard.vercel.app/cycles/4b2cb821-abe7-4809-a36b-51aef183c950) failed.

**Comment by jgilliam17** [comment]
Thanks @m1lt0n 
Tested, looks good to merge.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/254157-1bec096-onprem-ent-webapp-pr-11393-mm-ee-test:1bec096/mochawesome.html) - no PR related failures.
There are few tests that are failing related to channel switcher (differ from master) but not reproducing when testing manually.

**Pull request merged**
