### PR TITLE
dropdown action button aligned with action buttons

### PR DESCRIPTION
**Pull request by scottleedavis**
this PR was kicked off at @esethna 's request.   :)

#### Summary
This pull request aligns interaction dropdown select buttons with action buttons, so they appear as one group/list
reminder

#### Ticket Link
This supports the 'remindbot' work of [MM-10580](https://github.com/mattermost/mattermost-server/issues/9283), about aligning the styling of a reminder's buttons with that of slackbot's output.

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Needs to be implemented in mobile (link to PR or User Story) . Maybe?
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@scottleedavis Overall this looks like a great improvement.

1 - There may now be instances where on narrower screens, the dropdowns and buttons are mixed together as attached below

image

whereas previously they were nicely stacked one after the other

image

But that may be okay, given the benefit we gain on wider screens.

@esethna thoughts on point 1 above?

2 - Will this change need to be applied on mobile as well? Or do we leave mobile as-is, given it's a narrower screen so the menus and buttons will most likely stack vertically anyway.

----

@asaadmahmood 

3 - Can you help review the style changes for message menus below? I think they look great to me.

Before:
image


After:
image

**Comment by esethna** [comment]
Thanks @jasonblais, RE 1, given the larger horizontal real-estate on webapp I think this is fine, unless there are use cases that break the horizontal layout?

Re 2: Agree, on React Native I think vertically stacking is fine given the small screen widths

Re 3: Styling looks great, thanks for making those tweaks @scottleedavis.

**Comment by enahum** [comment]
I'm going to merge this as it has been approved by 2 devs, 2 PMs and UX

**Comment by enahum** [comment]
Thanks for this @scottleedavis

**Comment by scottleedavis** [comment]
Great process.  Thank you all.  :)

**Pull request merged**
