### PR TITLE
MM-40746 - make licensing page purchase buttons responsive

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
Buttons on the licensing page were not responsive so when resizing the screen, the buttons were showing a different padding. This PR makes those buttons responsive so in smaller screens they are displayed as block elements occupying all the available space.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40746

#### Screenshots

https://user-images.githubusercontent.com/10082627/147148025-bb749630-a80f-436c-a7b2-6aa77e48a8bb.mp4

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
lgtm!

**Review by stevemudie — APPROVED** [review]
Worked as expected! Looks good @pablovelezvidal

**Comment by annelieseklein** [comment]
Looks good - just want to make sure that the font size is 16 px, and the height of each button should be 48px. It looks like something might be off here with either sizing

**Comment by pablovelezvidal** [comment]
> Looks good - just want to make sure that the font size is 16 px, and the height of each button should be 48px. It looks like something might be off here with either sizing

thanks @annelieseklein you are right, font size was 14px. My latest commit fixes that.

Captura de pantalla 2021-12-22 a las 21 48 10

**Review by marianunez — APPROVED** [review]
Looks great!

**Comment by annelieseklein** [comment]
Screen Shot 2022-01-04 at 12 37 16 PM
Screen Shot 2022-01-04 at 12 37 21 PM

@pablovelezvidal  these buttons still look very different to me. The text on the button should be semibold opensans, 16pt font and the button height should be 48px

**Comment by pablovelezvidal** [comment]
> Screen Shot 2022-01-04 at 12 37 16 PM
> 
> Screen Shot 2022-01-04 at 12 37 21 PM
> 
> @pablovelezvidal these buttons still look very different to me. The text on the button should be semibold opensans, 16pt font and the button height should be 48px

Those two buttons are removed and replaced by the upload modal in https://github.com/mattermost/mattermost-webapp/pull/9611

**Review by annelieseklein — APPROVED** [review]

**Pull request merged**
