### PR TITLE
Migrate get link modal to be pure and use Redux

### PR DESCRIPTION
**Pull request by tkbky**
#### Summary

Migrate get link modal to be pure and use Redux.

#### Ticket Link

[mattermost-server/issues/7679](https://github.com/mattermost/mattermost-server/issues/7679)

#### Checklist

- [ ] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by tkbky** [comment]
@saturninoabril Here is the PR. I'm stuck at getting the tests passed because of some unsupported DOM API by jsdom, namely `queryCommandSupported` and `execCommand`. 

Related issues on jsdom:
* https://github.com/tmpvar/jsdom/issues/1539
* https://github.com/tmpvar/jsdom/issues/1742

Another finding is using the `Object.defineProperty` on `document` doesn't seem to work because of the `Unforgeable` properties in `document` that makes it not configurable as mentioned in [this issue](https://github.com/tmpvar/jsdom/issues/1208)

**Comment by saturninoabril** [comment]
@tkbky I've found a workaround, on mocking like:
```
const supportedCommands = ['copy'];

Object.defineProperty(document, 'queryCommandSupported', {
  value: (cmd) => supportedCommands.includes(cmd)
});

Object.defineProperty(document, 'execCommand', {
  value: (cmd) => supportedCommands.includes(cmd)
});
```

Also added/modified some tests.

**Comment by tkbky** [comment]
@saturninoabril That looks great! Thanks for making the PR way better. 😄

**Comment by jwilander** [comment]
Awesome, thanks @tkbky

**Pull request merged**
