### PR TITLE
MM-21635 fix: not closing channel header modal

### PR DESCRIPTION
**Pull request by nadalfederer**
modal now working properly on set header button
Peek 2019-12-18 23-16

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21635

### CODE REVIEW

**Comment by hanzei** [comment]
@nadalfederer Would you please fix the linter errors:
```
/root/mattermost-webapp/components/edit_channel_header_modal/index.js
  12:1  error  `./edit_channel_header_modal.jsx` import should occur after import of `../../utils/constants`  import/order
  12:1  error  There should be at least one empty line between import groups                                  import/order
```
Then I can bring this up for review.

**Comment by hanzei** [comment]
Hi @nadalfederer,

One test is still failing:
```
Summary of all failing tests
 FAIL  components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
  ● components/EditChannelHeaderModal › should match snapshot, init

    Unexpected console logsWarning: Failed prop type: The prop `show` is marked as required in `EditChannelHeaderModal`, but its value is `undefined`.
        in EditChannelHeaderModal

      67 | afterEach(() => {
      68 |     if (logs.length > 0 || warns.length > 0 || errors.length > 0) {
    > 69 |         throw new Error('Unexpected console logs' + logs + warns + errors);
         |               ^
      70 |     }
      71 | });
      72 | 

      at Object.<anonymous>.afterEach (tests/setup.js:69:15)


Test Suites: 1 failed, 449 passed, 450 total
```

**Comment by nadalfederer** [comment]
I'm sorry that I've missed this error. It fixed now

**Pull request merged**
