### PR TITLE
MM-20016 Initialize EmojiPickerOverlay using props from the constructor

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Initialize EmojiPickerOverlay using props from the constructor

#### Ticket Link
Fixes [https://github.com/mattermost/mattermost-server/issues/13025](https://github.com/mattermost/mattermost-server/issues/13025)
https://mattermost.atlassian.net/browse/MM-20016

### CODE REVIEW

**Comment by AGMETEOR** [comment]
> Instead of modifying `getDerivedStateFromProps` and setting an initial value for those values, I think you might be able to fix that warning by just setting `this.state = {};` in the constructor. `getDerivedStateFromProps` is called before mounting as far as I know.

I was thinking because `getDerivedStateFromProps` is called on mount and even updates, the initial solution wanted a way to make sure the state in set on the initial mount hence my changes. But let me make that change according to your suggestion.

**Comment by AGMETEOR** [comment]
@hmhealey made the change. Thanks for the review.

**Comment by lindy65** [comment]
Hi @hmhealey @sudheerDev - is there a Jira ticket for this? I didn't see one linked to the GitHub issue either?

**Comment by sudheerDev** [comment]
@lindalumitchell Nope. I was going to create it and link it in few mins.

**Comment by sudheerDev** [comment]
> Hi @hmhealey @sudheerDev - is there a Jira ticket for this? I didn't see one linked to the GitHub issue either?

Done.

**Comment by lindy65** [comment]
Thanks @sudheerDev :)

**Pull request merged**
