### PR TITLE
The pdf zoom level is store independently per file preview

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
The pdf zoom level is store independently per file preview

#### Ticket Link
[MM-33371](https://mattermost.atlassian.net/browse/MM-33371)

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
LGTM

**Review by calebroseland — APPROVED** [review]
Looks good!

**Review by ogi-m — APPROVED** [review]
Tested and passed
- zoom levels are stored independently for each file
- zoom level is remembered when returning to the file

**Pull request merged**
