### PR TITLE
[MM-20590] Migrate 'components/interactive_dialog/dialog_element' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by LSantos06**
#### Summary

This migrates the `components/interactive_dialog/dialog_element` component in the webapp to TypeScript. I've used the `apps_form_field` component as a reference and the trickiest part was that I coudn't avoid using type assertions for the `value` prop.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13482
JIRA: https://mattermost.atlassian.net/browse/MM-20590

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
@levb Gentle ping to review this :)

**Review by levb — APPROVED** [review]

**Comment by levb** [comment]
cc @mickmister

**Comment by devinbinnie** [comment]
@DHaussermann Gentle ping to review :)

**Review by DHaussermann — APPROVED** [review]
Tested and passed
Deployed this locally and used demo plugin dialog commands for testing. 
- No issues with dialog opening and submitting
- Tested dialog with different filed types
- Tested dialog with user and channel picker
- Tested on Chrome and Desktop client 
- No functional issues found
- No new or relevant JS errors found

LGTM!

Huge thanks for this PR @LSantos06 🎉      Sorry for the delay in getting this tested.

**Pull request merged**
