### PR TITLE
[MM-13840] Change eMail as a post-verification action

### PR DESCRIPTION
**Pull request by DSchalla**
#### Summary
Currently we update the eMail in the database directly after the change was requested, which allows some impersonation attacks but also cause some UX issues, e.g.:

1. We send both the changed and verification email at the same time
2. You cannot log in after a email change was requested, but your current session persists
3. A email verification token is not bound to a specific email change request

This PR updates the eMail only after the verification was completed and keeps the previous eMail still validated and active until this was done, to avoid that a user locks himself out of an account or enters an eMail he actually does not control.

@hmhealey Will we need a mobile patch for that one as well? A quick search I couldn't find any references to email verification in mobile itself.

#### Ticket Link
https://mattermost.atlassian.net/projects/MM/issues/MM-13840

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has server changes: https://github.com/mattermost/mattermost-server/pull/10253
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [x] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
I'll test this out when we've sorted the issues with spinmints.

In the meantime, is this the correct description of the proposed behaviour:

When user updates their email address in Account Settings,
1. They receive an email notification to both their old and new email address about the email change
2. In Mattermost, they see a blue bar at the top asking the user to confirm their new email address
3. They see the same in Account Settings > General
image
4. When they expand Account Settings > General, their old email address is still displayed, not the one they updated to
5. After logging out, only their old email address is accepted, unless they've verified their new email address.

**Comment by DSchalla** [comment]
Hi Jason, the proposed flow is the following:

1. They change their eMail in Mattermost and get a top bar that requests them to verify their eMail
2. They receive only a verification email to the new email address asking for verification
3. Until this point, the old address is still active & verified. Nothing changed until now.
4. When clicking the verification link, the new email is set active and verified
5. A "Email changed successful" email is sent to both the old & new email

**Comment by hmhealey** [comment]
@DSchalla We don't need a mobile PR for this since we don't actually let you change your email from mobile

**Comment by jasonblais** [comment]
@DSchalla 

The UX [you shared](https://github.com/mattermost/mattermost-webapp/pull/2356#issuecomment-462285214) makes sense to me. When testing the PR on the spinmint, neither 1 or 2 occurs though, but I may just need to wait until https://github.com/mattermost/mattermost-server/pull/10253 is merged.

I'll message about a question on community instead of here.

**Comment by DSchalla** [comment]
@jasonblais https://github.com/mattermost/mattermost-server/pull/10253 was merged, would appreciate if you could re-test.

**Comment by jasonblais** [comment]
I'm not getting email notifications to work  and receive a `Received invalid response from the server.` error when testing SMTP connection.

image

@cpanato can you help take a look? I think it's an SMTP misconfiguration on my end, but couldn't figure it out..

**Comment by cpanato** [comment]
This PR https://github.com/mattermost/mattermost-server/pull/10144 introduce the reply-to mandatory otherwise the test fail and maybe the sending email will fail

@jasonblais we need to add some new documentation regarding that, and maybe add some better error message when clicking in the test button.


fixed for this spinmint and for the future ones.

**Comment by DSchalla** [comment]
@jasonblais
1. Fixed - Merge conflict caused some problems there.
2. Unrelated to the PR, however currently 24 hours - There is a change in the works that might increase it to 48 hours, but let's revisit that topic with a separate ticket.

**Pull request merged**
