### PR TITLE
update tip placement

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Fix placement of tips 3 (add channels tip) and 4 (menu tip)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37956

#### Related Pull Requests
none

#### Screenshots
expected-tip-3
expected-tip-4

#### Release Note
No release note: this is for a bug fix to new UI that has not yet been released.

```release-note
NONE
```

### CODE REVIEW

**Review by esethna — APPROVED** [review]

**Comment by esethna** [comment]
Thanks @neallred!

**Review by stevemudie — APPROVED** [review]
Looks good @neallred !

Tested and passed.

**Review by pablovelezvidal — APPROVED** [review]
LGTM!

**Review by AGMETEOR — APPROVED** [review]

**Pull request merged**
