### PR TITLE
[MM-45688]: fixed missing options due to wrong filtering

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
fixes bug on cloud instances with forwarding to new DMs (no options showing due to wrong filtering)

#### Ticket Link
[MM-45688](https://mattermost.atlassian.net/browse/MM-45688)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
As member, non-admin, user - I am not able to forward to new DM. Forward button is disabled.
No issues for sysadmin.
Screen Shot 2022-10-05 at 2 10 35 PM

**Comment by michelengelen** [comment]
@jgilliam17 it is now fixed. Please re-test when you see fit

**Comment by michelengelen** [comment]
Hi @jgilliam17 I could not reproduce those console errors, but i added a guard to the specific checks anyways, just to be sure.

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen this looks good to merge. No errors.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/248358-c023043-onprem-ent-webapp-pr-11282-mm-ee-test:c023043/mochawesome.html) -  no PR related failures.

**Pull request merged**
