### PR TITLE
[MM-46236]: remove deactivated users from the select list

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
previously it was possible to forward messages to deactivated users.
This PR aims to fix that by removing the deactivated users as options from the select list.

#### Ticket Link
[MM-46236](https://mattermost.atlassian.net/browse/MM-46236)

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by michelengelen** [comment]
@stevemudie could you maybe take over for @jgilliam17 ?

**Comment by stevemudie** [comment]
@michelengelen I took a look at this but for some odd reason the dropdown for users or channels remains empty whether a user is deactivated or not. Typing the name in doesn't help.

**Comment by michelengelen** [comment]
@stevemudie @jgilliam17 I fixed the condition and it is now working as expected. It was working for me locally and I dont know why, but this time it is, so feel free to retest

**Comment by stevemudie** [comment]
@michelengelen I'm seeing the available channels but the users still don't appear in the list and typing them in fails as well.

**Comment by michelengelen** [comment]
That's strange @stevemudie .... it works for me (see screen recording below)

https://user-images.githubusercontent.com/32863416/192715011-f960d7a5-1309-48de-ae32-007223c2523d.mov

**Review by stevemudie — APPROVED** [review]
@michelengelen I ran it in an incognito window this time and all is well. Not sure what was happening before.

Looks good!

**Pull request merged**
