### PR TITLE
MM-47073:Migrate "components/suggestion/search_channel_with_permissions_provider.jsx" to Typescript

### LINKED ISSUE #21096: Migrate "components/suggestion/search_channel_with_permissions_provider.jsx" to Typescript
We are plan to migrate the mattermost-webapp over to TypeScript to facilitate better code quality. This `Help Wanted` issue is to modify the above mentioned file and associate test files (if the file exists).

Below is a checklist of items you should be doing to migrate:

  * Rename the files to their associated TypeScript extensions (ie. `js` to `ts`, `jsx` to `tsx`).
  * Add relevant types in the component(s) code.
  * Update any components using those to the correct imports.
  * Fix any errors generated by the TypeScript compiler. You can run `rpm run check-types` to display any errors.

We are aiming to be as strict as possible for the time being, but if you run into any issues where the file cannot be successfully migrated without significant change in other libraries, or our `tsconfig.json`, please feel free to raise them as we are aiming to keep this process smooth and gradual, while enforcing as much as we can.

Some examples of already migrated files can be found here:

  * [https://github.com/mattermost/mattermost-webapp/pull/10826](https://github.com/mattermost/mattermost-webapp/pull/10826)  
  * [https://github.com/mattermost/mattermost-webapp/pull/10931](https://github.com/mattermost/mattermost-webapp/pull/10931)  

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-47073

### PR DESCRIPTION
**Pull request by nik-1207**
**Summary**
This PR migrates Migrates `components/suggestion/search_channel_with_permissions_provider.jsx` and tests  to Typescript

**Ticket Link**
Fixes https://github.com/mattermost/mattermost-server/issues/21096
JIRA:  https://mattermost.atlassian.net/browse/MM-47073

Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]

**Review by m1lt0n — APPROVED** [review]

**Review by mickmister — COMMENTED** [review]
Thanks so much for this contribution @nik-1207!

LGTM, I just have some whitespace nitpicks. I'm not sure why our linter didn't catch these ones.

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@saturninoabril Any thoughts on who can provide QA on this?

**Comment by saturninoabril** [comment]
@mickmister Thanks for the ping. I'll take a look.

@nik-1207 Thanks for your contribution! Could you please take a look at the failed test : `FAIL components/suggestion/search_channel_with_permissions_provider.test.tsx`? Ping me once resolved and ready for review.

**Review by saturninoabril — CHANGES_REQUESTED** [review]
@nik-1207 Thanks for your contribution! Could you please take a look at the failed test : FAIL components/suggestion/search_channel_with_permissions_provider.test.tsx? Ping me once resolved and ready for review.

**Comment by hmhealey** [comment]
The web app now lives in the `webapp/channels` over in https://github.com/mattermost/mattermost-server. We decided to move it to be a monorepo to make both development and our CI pipelines easier, but it's unfortunately disruptive right now. We've updated [our setup docs](https://developers.mattermost.com/contribute/developer-setup/) and added [some steps for migrating to working with the monorepo](https://developers.mattermost.com/contribute/monorepo-migration-notes/).

Copying the changes over there hopefully shouldn't be too hard. There's a few changes to file paths (such as the code living in a dedicated `src` subdirectory), but most things should look the same as they do now. 

Let us know if you could use any help with this. Hopefully the process is smooth.

**Comment by M-ZubairAhmed** [comment]
Hello there! Could you please open the PR in the mattermost-server as part of the monorepo? I will be closing this PR for now. Thank you very much for your understanding and cooperation in this matter.

**Pull request closed without merging**
