### PR TITLE
Update CRT docs link in notice

### PR DESCRIPTION
**Pull request by esethna**
cc// @cwarnermm as an example of an in product "text" change

```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Comment by jgilliam17** [comment]
@esethna The link text is updated (verified by copying link from the warning modal), but it is not opening the updated url. Instead it still opens the same as https://docs.mattermost.com/help/messaging/organizing-conversations.html

**Comment by esethna** [comment]
@jgilliam17 ah thanks, docs reorg issue, I updated the URL

**Review by jgilliam17 — APPROVED** [review]
Thanks @esethna 
Tested, looks good to merge.
- Verified CRT warning modal "know issues" url has been updated to https://docs.mattermost.com/messaging/organizing-conversations.html#known-issues

**Comment by jgilliam17** [comment]
@esethna The URL should also be updated on the in-product Notices PR.

**Pull request merged**
