### PR TITLE
[MM-41997] Channel Info RHS: add Pinned Messages menu item + improvements

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
The main feature added by this PR is the support of the "Pinned Messages" menu in the Channel Info RHS.
Adding the menu item was quite easy but it came with a major navigation issue: When going from the Channel Info RHS to the Pinned Messages RHS, if one of those pinned messages is a thread and you click to open the Thread RHS, we would lose the "Channel Info RHS" parent and would not be able to go back. I changed the `previousRhsState` from a string to an array to fix this issue.

Additionally, the following changes have been added in response to feedback:
- ~~When in developer mode (`System Console > Environment > Enable Developer Mode` is `true`), the Channel Info RHS will also show the channel ID~~ **edit:** channel url has been removed and channel Id added for everyone
- The "more" button in the line limiter has been moved below the content
- We now limit to 4 lines instead of 3
- The line limiter now resizes emojis and images to prevent them from breaking the system.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41997

#### Related Pull Requests
N/A

#### Screenshots

<details>
<summary>Pinned message menu + the `more` buton is now below the content</summary>

image

</details>

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — APPROVED** [review]
Thanks @JulienTant looks good. Just one thing:

If the full purpose is showing, it's still displaying the 'more' button. We can hide it in this case.

**Comment by JulienTant** [comment]
> If the full purpose is showing, it's still displaying the 'more' button. We can hide it in this case.

Yeah, I'm looking into this right now, the issue is the emoji adding one extra pixel somewhere so my component considers that we have more content below haha. I might just add an error margin of a few pixels

**Comment by matthewbirtch** [comment]
> When going from the Channel Info RHS to the Pinned Messages RHS, if one of those pinned messages is a thread and you click to open the Thread RHS, we would lose the "Channel Info RHS" parent and would not be able to go back

Great solution on this by the way

**Review by matthewbirtch — APPROVED** [review]
Looks good now!

**Review by pvev — APPROVED** [review]
LGTM! awesome work @JulienTant :shipit:

**Review by neallred — APPROVED** [review]
LGTM! Thanks, @JulienTant

**Comment by JulienTant** [comment]
Changed:
- When in developer mode (System Console > Environment > Enable Developer Mode is true), the Channel Info RHS will also show the channel ID
- 
To:
- channel url has been removed and channel Id added for everyone

context: https://community.mattermost.com/core/pl/deneqqafi7ba5ywe6ybotem4fw

**Review by stevemudie — APPROVED** [review]
Looks good @JulienTant!

**Pull request merged**
