### PR TITLE
MM-22963 - Updating post spacing and highlight

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-22963 - Updating post spacing and highlight

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22963
https://mattermost.atlassian.net/browse/MM-23047

### CODE REVIEW

**Comment by esethna** [comment]
@amyblais please help add the v5.23, 5.24 milestones, this PR should go into v5.24

**Comment by amyblais** [comment]
@esethna I don't have permissions, maybe @metanerd can help add v5.23, 5.24 milestones.

**Comment by metanerd** [comment]
@amyblais I created milestones until june.

**Comment by esethna** [comment]
@amyblais please make sure this in not in the v5.22 release as we want it to soak on daily for an entire release cycle

**Comment by asaadmahmood** [comment]
@deanwhillier Yeah, we want to make it really subtle and see the response.

**Comment by deanwhillier** [comment]
Haha, not showing is definitely subtle! 😛

**Comment by jgilliam17** [comment]
Thank you @asaadmahmood 
I am seeing one small issue, otherwise looks good.
- Noticed that on the RHS spacing is missing between time stamp+flag and post text. 
Screen Shot 2020-03-30 at 8 16 03 PM
Screen Shot 2020-03-30 at 8 19 42 PM

**Comment by jgilliam17** [comment]
@asaadmahmood one more thing
pinned label on the RHS is out of line with the test slightly 
Screen Shot 2020-04-01 at 9 33 48 AM

**Pull request merged**
