### PR TITLE
Cypress/E2E: Fix test related to channel switcher and bot display name

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
For channel switcher, it's due to the malformed aria-label - [MM-35081](https://mattermost.atlassian.net/browse/MM-35081). But updated the test here instead of waiting for the fix since it's affecting several tests.
For bot display name, it's intermittently failing in prod. Fix here is a potential fix.

#### Screenshots
Screen Shot 2021-04-21 at 6 22 25 PM
Screen Shot 2021-04-21 at 6 53 31 PM
Screen Shot 2021-04-21 at 6 55 37 PM
Screen Shot 2021-04-21 at 6 57 39 PM
Screen Shot 2021-04-21 at 6 59 12 PM
Screen Shot 2021-04-21 at 7 14 47 PM

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. All tests passed locally. Thanks @saturninoabril !!

**Review by furqanmlk — APPROVED** [review]
LGTM

image

image

image

image

image

image

**Review by prapti — APPROVED** [review]
LGTM!
Thanks Saturn!

**Pull request merged**
