### PR TITLE
[PLT-7396] Add the ability to revoke user sessions in System Console > Users #7493

### PR DESCRIPTION
**Pull request by rickbatka**
#### NOTE! This PR is part of a group of PRs with identical title in the following 4 repos, all of which must be merged simultaneously:
mattermost-server
mattermost-redux
mattermost-webapp
mattermost-api-reference

#### Summary
Adds action link to system users dropdown to revoke all sessions for a user, with confirm dialog and i18n strings.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/7493

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs)
- [x] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
This is awesome @rickbatka ! Really nice work

Once the server and mattermost-redux PRs go in, I'll need your help pointing package.json and yarn.lock at the correct mattermost-redux commit and then we can setup a test server for a PM to try out before doing the final code review on this PR

**Comment by jasonblais** [comment]
@rickbatka Now that the server and redux PRs are merged, can you help point package.json and yarn.lock at the correct mattermost-redux commit, and I'll set up a test server to test this out.

Great work on this feature thus far!

**Comment by rickbatka** [comment]
Ok, I just ran `yarn upgrade mattermost-redux`, it seems to have worked.

Looks like the mattermost-redux project has added another dependency since I started working on this; I definitely didn't add the `shallow-equals` reference.

**Comment by jasonblais** [comment]
Awesome! UI/UX looks good, have asked @lindalumitchell to help test functionality. 

And yeah, looks like `shallow-equals` was added with https://github.com/mattermost/mattermost-redux/pull/269.

**Comment by lindalumitchell** [comment]
@rickbatka @jasonblais I spent some time testing the functionality, and it looks great! No issues found. Summary of my testing below.

The one thing I didn't test was personal access tokens. Maybe we could get Joram's help with that?

Scenarios / Verifications = all passed:

1. Revoke session of user logged in on one browser using email / password
2. User logged in to many sessions at once:
 - Browser Chrome on Mac, user status set manually to away
 - Browser Firefox on Mac
 - Browser IE on Win 10, computer asleep
 - Desktop app
 - iOS Classic, screen off
 - Android Classic
 - iOS New
 - Android New
3. OAuth 2.0 SSO
4. SAML SSO
5. LDAP signin
6. UI messaging verified
7. Cancel = no sessions revoked
7. Revoke the current user him/herself, while logged in to multiple places
8. All can log back in after revoked

When system admin clicks to revoke sessions, user is logged out and login page displays either:
1. When the user tries to switch channels or otherwise interact with the app, or
2. Automatically after a period of ~2-10 seconds without the user touching the app

Trying to send message after system admin has clicked to revoke but before screen has changed results in same behavior as if internet were disconnected (message displays but grayed out, with info that message was not sent), then after a few seconds screen changes to login page. Message is not sent (as expected).

**Comment by rickbatka** [comment]
@grundleborg Ok, merged and fixed conflicts. Let me know if anything is amiss.

**Comment by grundleborg** [comment]
@rickbatka I think you needed to do a rebase, not a merge. The diff now appears to be enormous, with lots of unrelated changes in it.

**Comment by rickbatka** [comment]
@grundleborg sorry about that. I fixed it up to be a rebase. Let me know if you need anything else, I think it's good to go now.

**Comment by jasonblais** [comment]
Thanks @rickbatka! Looks like the build didn't pass for some reason..I've re-triggered the build, but if it fails again, can you help take a look?

Really excited to get this in soon :)

**Comment by rickbatka** [comment]
@jasonblais Do you know why I can't view the build details? The jenkins link tries to take me to "http://unconfigured-jenkins-location/job/mattermost-webapp/job/PR-152/1/display/redirect"...

**Comment by jasonblais** [comment]
@rickbatka I posted a question in the Developers channel: https://pre-release.mattermost.com/core/pl/woefnsubhby99m5ms8rek9omka

**Comment by ccbrown** [comment]
@rickbatka Sorry about the build issues. While the broken link is totally our fault, I believe the build was failing due to a GitHub bug (GitHub is supposed to make PRs available as "refs/pull/152/head", but instead, fetching that returned the wrong commit.). I made a random edit (removed a newline), and that fixed it.

**Comment by jwilander** [comment]
@rickbatka if can you give this a rebase we can merge it. Sorry again for the delays on this

**Comment by rickbatka** [comment]
I'll take care of it soon!

**Comment by rickbatka** [comment]
@jwilander I have done the rebase. Hopefully the build will work on the first try this time!

**Comment by jwilander** [comment]
I re-triggered it and will escalate if it fails again

**Comment by jwilander** [comment]
Merged :) Thanks again for all your work on this @rickbatka !

**Comment by rickbatka** [comment]
Hey, alright! Glad it worked out. That was my first real open source contribution; sorry if I was flailing a little. I look forward to seeing the feature in a future release!

**Comment by jasonblais** [comment]
Awesome, thank you @rickbatka! This is great 👍

**Pull request merged**
