### PR TITLE
Automated cherry pick of #9497 on release-6.2

### PR DESCRIPTION
**Pull request by puerco**
Automated cherry pick of #9497 on release-6.2

Cherry pick of #9497 on release-6.2.

/cc  @weblate

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
This and the cloud cherry-pick have failing checks.

**Review by cpanato — APPROVED** [review]

**Comment by hmhealey** [comment]
It says these are failing because there's a missing string in the Australian English translation files. I'm not sure how we'd go about fixing that.

Have we previously been cherry-picking translation stuff? I thought we were only ever merging them directly into master or the latest release branch depending on whether or not we were in a release cycle

**Comment by puerco** [comment]
@hmhealey yes until now, translations have been backported to release branches of server and webapp. This PR is failing probably like last week, a missed cherry pick of a change removed that string. I will push commits to these PRs to ensure the check passes. If it keeps failing next Monday, I'll try to track down which commit is missing to backport to even the branches.

**Comment by puerco** [comment]
Ready, @cpanato PTAL

**Pull request merged**
