### PR TITLE
MM-17661 Pass ProfilePopover `hide` through to plugin components 

### PR DESCRIPTION
**Pull request by MatthewDorner**
#### Summary
Pass this.props.hide to Pluggable for Popover User Actions and Popover User Attributes plugin components, so the components are able to hide the popover.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/11842

### CODE REVIEW

**Comment by MatthewDorner** [comment]
yeah, I can do that.

**Comment by MatthewDorner** [comment]
Not sure if you're waiting for the https://github.com/mattermost/mattermost-plugin-demo PR before merging this one, but I should have it ready sometime this week.

**Comment by prapti** [comment]
@MatthewDorner Could you please add unit tests for the PR. That'd be great!

**Comment by MatthewDorner** [comment]
Can you provide any guidance on where these tests should go? I see tests in a lot of different places in the repository and I'm still new to the project.

**Comment by saturninoabril** [comment]
@MatthewDorner `Pluggable` component is so generic where props are not exactly define.  Since this implementation is specific to `ProfilePopover` component, I suggest to have the test on itself ([profile_popover.test.jsx](https://github.com/MatthewDorner/mattermost-webapp/blob/GH-11842/components/profile_popover/profile_popover.test.jsx)), checking whether props, including `hide` is passed into the `Pluggable` component.  Something like:
```javascript
import Pluggable from 'plugins/pluggable';
...
    test('should match props passed into Pluggable component', () => {
        const hide = jest.fn();
        const status = 'online';
        const props = {...baseProps, hide, status};

        const wrapper = shallowWithIntl(
            <ProfilePopover {...props}/>
        ).dive();

        const pluggableProps = {
            hide,
            status,
            user: props.user,
        };
        expect(wrapper.find(Pluggable).first().props()).toEqual({...pluggableProps, pluggableName: 'PopoverUserAttributes'});
        expect(wrapper.find(Pluggable).last().props()).toEqual({...pluggableProps, pluggableName: 'PopoverUserActions'});
    });
```

**Pull request merged**
