### PR TITLE
[MM-27231]: cypress test for MM-T1840

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Automate MM-T1840: Description allows for special character

#### Ticket Link

Part of https://mattermost.atlassian.net/browse/MM-27231

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Code looks good. Test passed. Thanks @ashishbhate !!

**Review by srkgupta — APPROVED** [review]
Thanks @ashishbhate. The test is working fine and LGTM. Approving the PR

**Review by calebroseland — APPROVED** [review]
LGTM!

**Pull request merged**
