### PR TITLE
MM-12547 - Fixing videos modal

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-12547 - Fixing videos modal

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12547

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @asaadmahmood 

I tested on the spinmint using the mp4 file attached to the Jira ticket (which was the original file that was truncating at the top). 

What I'm seeing now is that the video doesn't take up the full preview screen on the right-hand-side of the preview window (see below)

image

**Comment by asaadmahmood** [comment]
Should be fixed now @lindy65. However, if the video is smaller than 300 pixels, then it will not be centered and gray spaces will appear on the left and right of the video. Because we have a min-width set for the content.

**Comment by lindy65** [comment]
Thanks @asaadmahmood 

I'll try to spin up a new test server and re-test.

**Comment by lindy65** [comment]
Looks good to me @asaadmahmood with no blank edges around video preview.

**Pull request merged**
