### PR TITLE
[MM-37578] - Add setting for onboarding

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR adds a setting `EnableOnboardingFlow` in the configuration to toggle onboarding flow

#### Ticket Link
[MM-37578](https://mattermost.atlassian.net/browse/MM-37578?atlOrigin=eyJpIjoiNzViZDIyN2MzZTkzNGNhODk0NzRiNmUxY2Y0YWM4ZjAiLCJwIjoiaiJ9)

#### Related Pull Requests
Has Server Changes: https://github.com/mattermost/mattermost-server/pull/18068

#### Release Note
```release-note
Added a new config setting ServiceSettings.EnableOnboardingFlow
```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]
LGTM! thanks @AGMETEOR! :shipit:

**Review by neallred — APPROVED** [review]

**Comment by stevemudie** [comment]
@AGMETEOR The setting is present in the System Console as expected but if I toggle it to true then navigate anywhere else then return and it's set back to false.

Is this expected?

**Comment by AGMETEOR** [comment]
> @AGMETEOR The setting is present in the System Console as expected but if I toggle it to true then navigate anywhere else then return and it's set back to false.
> 
> Is this expected?

@stevemudie the test servers were not using the new code. I have updated now and it should work fine

**Comment by AGMETEOR** [comment]
Hello @stevemudie . Gentle ping on this.

**Review by stevemudie — APPROVED** [review]
Tested and passed. Toggling and saving the change retains the state even after navigating away then returning.

**Pull request merged**
