### PR TITLE
MM:20579 -  Migrate 'components/admin_console/team_channel_settings/group' module and associated tests to TypeScript #13493

### PR DESCRIPTION
**Pull request by allenlai18**
#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/13493
https://mattermost.atlassian.net/browse/MM-20579

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks Allen! I tagged a couple of reviewers who can probably help you with the VS Code errors (after holidays :) )

**Comment by reflog** [comment]
Hi @allenlai18 - most of the errors here happen either due to incorrect type imported from Redux (please check that you are accessing the proper type by reading src/types/store.ts in redux) or due to lack of null checking (error: Object is possibly 'undefined').
Let me know if you need additional help with this (feel free to contact me on the community server)

**Comment by reflog** [comment]
@allenlai18 - I've committed some changes to your PR, fixing the type issues. Please take a look

**Comment by allenlai18** [comment]
@devinbinnie  i think we are good to merge

**Comment by devinbinnie** [comment]
@allenlai18 Looks like there's a conflict to resolve, can you take care of that and ping me when it's done? I can merge then.

**Pull request merged**
