### PR TITLE
Cypress/E2E: Update cypress report

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
This fixes the duration in the report in community channel and also add info about the env overrides of the test server (in support to running daily run with some feature flags enabled like in the case of GraphQL)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by saturninoabril** [comment]
Right, I was supposed to message you about that. Thanks for looking!

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril 
looks neat 👍 

image

**Pull request merged**
