### PR TITLE
[MM-47618] Patch version upgrades for multiple dependencies

### PR DESCRIPTION
**Pull request by m1lt0n**
#### Summary

In the context of regular dependency upgrades, this PR includes a bunch of patch version upgrades for multiple dependencies. All dependencies have only fixes and minor improvements. See changelogs or notes for further information:

| Dependency | From version | To Version | Changelog | Notes |
|------------|--------------|------------|-----------|-------|
| classname  | 2.3.1        | 2.3.2      | [changelog](https://github.com/JedWatson/classnames/blob/main/HISTORY.md) | Minor fixes |
| css-vars-ponyfill | 2.4.7 | 2.4.8      | [changelog](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/CHANGELOG.md) | Just a small fix when using shadowDOM |
| styled-components | 5.3.5 | 5.3.6      | [changelog](https://github.com/styled-components/styled-components/releases/tag/v5.3.6) | Fixes and deprecation of $as and $forwardedAs |
| moment-timezone   | 0.5.34 | 0.5.38    | [changelog](https://github.com/moment/moment-timezone/blob/develop/changelog.md) | Fixes and updates in IANA TZDB |
| semver            | 7.3.7  | 7.3.8     | [changelog](https://github.com/npm/node-semver/blob/main/CHANGELOG.md) | Fixes: add support for node.js esm auto exports and documentation changes |

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47618
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by nevyangelova** [comment]
Nit: should we skip the integrity updates here?

**Comment by m1lt0n** [comment]
Hey @nevyangelova what do you mean by integrity updates?

**Comment by hmhealey** [comment]
The `integrity` line for each package in `package-lock.json` contains a hash of the package. We've had to remove that line from some packages that we import directly from their git repos because we were running into issues with the hashes of those being different on different OSes. That's in `skip_integrity_check.js` that's run when you install dependencies using `make node_modules`.

That said, none of these packages are affected by it since they come from NPM. The only ones affected are ones we've written or forked

**Review by hmhealey — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
