### PR TITLE
Cypress/E2E: Fix e2e new sidebar

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix failing E2E test in new sidebar

### CODE REVIEW

**Review by srkgupta — APPROVED** [review]
Changes LGTM and test passed. @saturninoabril my only question is why isn't this change also pushed to master and only to 5.27?

**Comment by saturninoabril** [comment]
It's already fixed on master - https://github.com/mattermost/mattermost-webapp/pull/6305 - and it's done via API command. However, lots have changed on master already and others might not be applicable to 5.27 (given it's cut from 5.26). I think it would be better to do quick fix with minimum code change as much as possible.

**Comment by srkgupta** [comment]
> It's already fixed on master - #6305 - and it's done via API command. However, lots have changed on master already and others might not be applicable to 5.27 (given it's cut from 5.26). I think it would be better to do quick fix with minimum code change as much as possible.

Got it. Thanks. Makes sense

**Review by josephbaylon — APPROVED** [review]
LGTM. Although the latest run on Cypress passed. @saturninoabril I'll let you decide whether to merge.

**Comment by saturninoabril** [comment]
It passed because I added this in advance 😄

**Pull request merged**
