### PR TITLE
MM-48687 - Billing History is not showing empty state when no invoices are listed

### PR DESCRIPTION
**Pull request by ConorMacpherson**
#### Summary

When the billing history in the admin console has no invoices listed, the billing history table should display:
 - An image
 - Text stating `"In the future, this is where your billing history will show."`
 - [A link to our cloud billing details](https://docs.mattermost.com/manage/cloud-billing.html)

Currently, none of these are displayed.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-48687

#### Screenshots

|  before  |  after  |
|----|----|
| image | image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Review by Afsoon — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
Thank you @ConorMacpherson ,

can I add this small PR into this one https://github.com/mattermost/mattermost-webapp/pull/11786 ?

**Comment by marianunez** [comment]
@amyblais heads up - cherrypicking this bug fix to cloud

**Comment by amyblais** [comment]
No need to cherry-pick to cloud as last fast-forward for Jan 12 release will be done in January.

**Pull request merged**
