### PR TITLE
Revert "[feat] Addition of CD workflow"

### PR DESCRIPTION
**Pull request by m1lt0n**
This reverts the addition of `cd.yml` github workflow.

#### Summary

`cd.yml` was accidentally committed to the translations repository. This change reverts the commit that added it.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by spirosoik — APPROVED** [review]
looks good. let's wait for CI

**Comment by m1lt0n** [comment]
@amyblais this needs to be cherry-picked with the translations PR that includes the unnecessary `cd.yml` file

**Comment by amyblais** [comment]
@m1lt0n Which translations PR adds the cd.yml file? How do I check?

**Comment by m1lt0n** [comment]
@amyblais https://github.com/mattermost/mattermost-webapp/pull/12197 this is the PR that adds it

**Pull request merged**
