### PR TITLE
MM-14713 - Updating help text security panel

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-14713 - Updating help text security panel

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-14713

### CODE REVIEW

**Comment by DHaussermann** [comment]
For some reason this did not get resolved in 5.10.  
This issue is still present on 5.11-release. 

@hanzei or @saturninoabril would either of you be able to cherry-pick this to 5.11-release to see if it solves the problem?

(re-added label for 5.11 branch)

**Comment by hanzei** [comment]
As you can see in https://github.com/mattermost/mattermost-webapp/commit/df8f3c5859a0ab82761a00ccbc0abbb8f478bb49 this change is already part of the `release-5.11` branch.

**Comment by saturninoabril** [comment]
I agree.  It's both on 5.10 and 5.11.

**Comment by DHaussermann** [comment]
Thanks. strange that the cherry-pick did not resolve the issue. I will follow up with Asaad.

**Pull request merged**
