### PR TITLE
MM-20454 - Migrate 'components/integrations/' and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by A01123748**
#### Summary
This PR includes updating the files under components/integration to a typescript format and associated tests.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20454

#### Related Pull Requests
NONE

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Sorry for the delay with re-reviewing this. It looks like something got merged into this incorrectly. Would you mind if I try to sort that out? It's making it difficult to review again since there's some changes from my PR integrated into this as well

**Comment by A01123748** [comment]
Sure, please go ahead

**Comment by A01123748** [comment]
> Sorry for the delay with re-reviewing this. It looks like something got merged into this incorrectly. Would you mind if I try to sort that out? It's making it difficult to review again since there's some changes from my PR integrated into this as well

Sure, please go ahead.

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @A01123748

**Comment by hmhealey** [comment]
Just a heads up, I'm still working on that cleanup. I ended up getting pulled away to help fix some stuff for a customer, but I'm hoping to get this done tomorrow.

**Comment by hmhealey** [comment]
@A01123748 I'm really sorry! I screwed up the force push command and accidentally force pushed the latest master branch without your changes instead of the one with your changes applied. Then that caused GitHub to automatically close this PR which removed my ability to fix the branch because I lost the ability to push to your master branch. I'll follow up shortly with how to fix this since I still have your original code and my cleaned up branch around.

**Comment by A01123748** [comment]
No worries @hmhealey. Let me know any help I can provide to you since I would love to show up as a collaborator.

**Comment by hmhealey** [comment]
So your original code is available [on this branch](https://github.com/mattermost/mattermost-webapp/tree/A01123748-master-original), and the rebased version is [this one](https://github.com/mattermost/mattermost-webapp/tree/A01123748-master).

If you know enough about git to pull down a branch from our repo, you could do that and resubmit a PR. I can figure out how to do that though if you don't know how to do that. That'd probably be the best option since I think if I submit a PR using one of those branches, it might show them as my commits.

**Comment by hmhealey** [comment]
Ignore the rebased version of your branch. That seems like it was just a bad idea from the start since merging the latest master into your branch fixes this much more nicely and wouldn't have needed a force push to begin with. I pushed a test PR after doing that, and it fixed the unrelated changes that got me to do a force push to begin with.

I see you're fixing the branch yourself, so I'll let you do that now to avoid messing anything else up myself.

**Pull request closed without merging**
