### PR TITLE
MM-36740 - fix close button styling

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
fixes styles (color) for modal-header close button by increasing class specificity

#### Ticket Link
Fixes [MM-36740](https://mattermost.atlassian.net/browse/MM-36740)

#### Screenshots
| before | after |
|-------|-------|
|Screenshot 2021-07-07 at 16 15 17|Screenshot 2021-07-07 at 16 14 43|

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified channel switcher close button styling in light and dark themes - as expected.

**Comment by amyblais** [comment]
@calebroseland Please help prioritize review for tomorrow's 5.37 code freeze.

**Review by calebroseland — APPROVED** [review]

**Comment by michelengelen** [comment]
@amyblais cherry pick did fail ... i am attempting to do a manual pick now

**Comment by michelengelen** [comment]
@amyblais I did already cherry pick to the cloud branch

**Comment by amyblais** [comment]
@michelengelen It needs a cherry-pick to ``release-5.37`` too.

**Comment by amyblais** [comment]
@michelengelen ^

**Comment by michelengelen** [comment]
@amyblais done^^

**Pull request merged**
