### PR TITLE
Cypress/E2E: Fix Elasticsearch autocomplete and add several test keys

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix Elasticsearch autocomplete and add several test keys.

#### Ticket Link
none, failing on daily run

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Code looks good. I couldn't run the tests properly locally because my elasticsearch keeps on dying.

**Review by furqanmlk — COMMENTED** [review]
Test cases are failing at `Bulk Indexing`

image

**Comment by saturninoabril** [comment]
Thanks @furqanmlk for checking! Similar to our offline discussion, that error is more likely related to your local dev. All tests passed for me though. Let me know if you need help.

**Review by furqanmlk — APPROVED** [review]
Looks like my environment is not properly setup for Elasticsearch.
Everything else look good

**Pull request merged**
