### PR TITLE
Fix tooltip text for copying incoming webhook url

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary
When adding incoming webhook, users can copy webhook url, but tooltip text for copy icon is incorrect.

スクリーンショット 2020-11-01 22 07 34

Fix tooltip text to just `copy` as well as [outgoing webhook](https://github.com/mattermost/mattermost-webapp/blob/7d9e4f0614c05e678ed9b23c0a3d04fe3f866e76/components/integrations/confirm_integration/confirm_integration.jsx#L152).

#### Ticket Link
N/A

(I followed [Contributions Without Ticket](https://developers.mattermost.com/contribute/getting-started/contributions-without-ticket/).)

#### Related Pull Requests
N/A

#### Screenshots
Fixed.

スクリーンショット 2020-11-01 22 09 29

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
Awesome LGTM :+1:

**Review by larkox — APPROVED** [review]
LGTM. Thank you very much for the fix!

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- On the webhook step it now show the `copy` tooltip instead
- Tested other areas of integration
- No issues found

LGTM!

Thanks @kaakaa for this fix!

**Comment by amyblais** [comment]
Opened a ticket for future release testing https://mattermost.atlassian.net/browse/MM-31288

**Pull request merged**
