### PR TITLE
Revert "Automated cherry pick of #8009"

### PR DESCRIPTION
**Pull request by amyblais**
Reverts mattermost/mattermost-webapp#8067

### CODE REVIEW

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Install and uninstall are both functional with the production version of app `v0.5.0`

LGTM!

**Comment by DHaussermann** [comment]
Huge thanks @amyblais  for being able to help with this PR!

Just to double check - Can you confirm for that the cloud image going to production will include this revert PR?

**Comment by amyblais** [comment]
> Huge thanks @amyblais for being able to help with this PR!
> 
> Just to double check - Can you confirm for that the cloud image going to production will include this revert PR?

Yes, I'll ask Cloud team to include this in the release.

**Pull request merged**
