### PR TITLE
Updating post control menu

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Updating post control menu

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-14433

#### Checklist
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by esethna** [comment]
@michaelgamble please review this and comment on the implementation

**Comment by asaadmahmood** [comment]
@michaelgamble Note that we agreed to keep the spacing between the text and the icon 3px instead of 4.

**Comment by hanzei** [comment]
@michaelgamble @asaadmahmood What are the next steps with this PR?

**Comment by asaadmahmood** [comment]
@hanzei Will defer this to @esethna.

**Comment by hanzei** [comment]
@esethna Gently reminder about this: https://github.com/mattermost/mattermost-webapp/pull/2478#issuecomment-481586962

**Comment by hanzei** [comment]
@esethna Would you pleas take a look?

**Comment by esethna** [comment]
@asaadmahmood can you please create a feature branch for the UI redesign and then submit this PR against that?

**Comment by jasonblais** [comment]
@asaadmahmood FYI on the above note from Eric

> @asaadmahmood can you please create a feature branch for the UI redesign and then submit this PR against that?

**Comment by asaadmahmood** [comment]
@jasonblais I've just kept the commit for now stored locally. Inorder to do those changes again it may take some time to actually update it and probably fix the merge conflicts (if they exist). I'll submit it when we are sure we want to take it so I only have to work on it once, rather than updating it multiple times.

**Pull request closed without merging**
