### PR TITLE
Adding class to indicate if the menu is open on the menu wrapper

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Adding class to indicate if the menu is open on the menu wrapper

#### Jira ticket
https://mattermost.atlassian.net/browse/MM-35458

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by calebroseland — APPROVED** [review]

**Comment by lindy65** [comment]
Hey @asaadmahmood - I've taken a look at all menus in the main menu, channel menu, channel switcher, 

- When opening Main Menu > Account Settings - the General tab opens but is scrolled down a bit (top of the page is not visible). This does not reproduce on `master` so could perhaps be an issue with this PR? This only seems to be an issue on the "General" tab of Account Settings.

image

- Main Menu > Help opens to Mattermost Academy. Not sure if this is an effect of your PR?  `master` opens Help to `https://github.com/mattermost/mattermost-server/blob/master/doc/help/README.md` and `community` opens Help to Mattermost Academy (also a Cloud server) so perhaps this is a spinwick setting.

image

**Comment by asaadmahmood** [comment]
@lindy65 Apologies, by menus I mean the dropdown menus.
This PR does not touch any UI/aesthetic changes.

Screenshot 2021-05-05 at 1 39 05 PM

**Comment by lindy65** [comment]
Ooooooooooh, ha ha!  Sorry about the misunderstanding @asaadmahmood!

I've tested the drop-down menu you screenshotted above as well as the channel drop-down menu and both look good to me 👍

**Comment by asaadmahmood** [comment]
Sounds good.

**Review by lindy65 — APPROVED** [review]
Looks good to me, thanks @asaadmahmood 👍

**Pull request merged**
