### PR TITLE
[Epic MM-23811] Applytheme / centerChannelColor consolidated Hacktober PRs

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
This pull request consolidates several PRs from last years Hacktoberfest. It is probably best to review the individual commits as that will make it easier to determine what changes are related. PR's for each commit have already had full dev reviews (eg. https://github.com/mattermost/mattermost-webapp/pull/6807), so now we are just looking for final UX and QA reviews.

See the commits tab for a list of all the relevant commits. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23811

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by jgilliam17** [comment]
@deanwhillier 
I checked listed commits as we discussed and have some I was not able to find.
Prefixed the ones verified with `pass`

1.  `Pass` #6807 files only deleted, no other changes
2.  #6810 this should be edit post modal, but I wasn’t able to find `bg-text-200` anywhere
#6814 `svg-text-color` channel icon background - not found
3. `Pass` #6812 background color of user role pill e.g `system admin` on user popover  as expected changed to  `rgba(var(--center-channel-color-rgb), 0.3)`
4. `Pass` #6821 4 files deleted, no other changes all 4 with `theme.centerChannelColor` not found in the app, as expected
5. `Pass` #6862 Channel header dropdown icon, chevron using correct color `--center-channel-color-rgb`
6. `Pass` #6917 channel header is using --center-channel-color Note: noticed the difference in font size file has `font-size: 14px;`, but it’s `font-size: 16px;` on test server.
7. #6915 disabled send button - Not sure this is applied correctly I wasn’t able to find that it is using `--center-channel-color` , I see `color: rgb(255, 255, 255)` on the test server
8. `Pass` #6986 date separator text is using `--center-channel-color` as expected
9. `Pass` #6985 server URL border on rename channel modal has correct color theme `--center-channel-color-rgb`
10. #6933 this PR deletes one file, I wasn’t able to verify, not sure how to trigger system notice “The system notices for admins in the bottom right of the app (not the new in-product notices) should still have their drop shadow coloured correctly”
11. #6993 not sure where this is, I tried channel header popover, but wasn’t able to confirm
12. #6992 Also not able to find where the change was applied. It should be “Popovers (such as the Member List in the channel header) should be styled correctly” <popover appears styled correctly 
13. `Pass` #6991 button transparency as expected
14. #6938 not able to verify, system notice related, unsure how to trigger on the test server
15. #7018 this one is for channel header plugin dropdown, I wasn’t able to check. I enabled a bunch of plugins, but I’m probably missing a step to make them appear in the header dropdown.
16. `Pass` #6990 channel header popover as expected
17. `Pass` #6994  popover border bottom color looks good, using `center-channel-color-rgb`
18. `Pass` #6988 user popover is using `center-channel-color-rgb` as expected
19. #7248 not sure where to find post link 
20. `Pass` #7406 post create using `center-channel-color`
21. `Pass` #9155 - emoji picker header border is using `center-channel-color-rgb`

**Comment by michaelgamble** [comment]
@zefhemel I have no idea if this pr is relevant anymore, I have two vauge conversations with Dean.. first one was he would need to walk me through all the changes.. and then the second most recent conversation I THINK he mentioned that this would all have to change based on the in progress themeing work?? maybe? sooo I think im going to remove myself as a reviewer on this one, and hand it to you to figure out what to do with this :)

**Comment by jgilliam17** [comment]
Removing myself as a reviewer as well. Please - re-add me when ready for qa. Thanks.

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
