### PR TITLE
[MM 14024] Stop leading spaces from preventing jumbo emoji

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Currently, spaces preceding what should be jumbo emoji posts are preventing the emoji from becoming jumbo. This PR allows jumbo emoji to still be recognized with leading spaces.

#### Ticket Link
[MM-14024](https://mattermost.atlassian.net/projects/MM/issues/MM-14024)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by saturninoabril** [comment]
I attempted to cherry-pick this to release-5.9 branch but got merge conflict since https://github.com/mattermost/mattermost-webapp/pull/2383 needs to cherry-pick first.  I'll let you do the cherry-pick then.

**Comment by enahum** [comment]
@saturninoabril next time remember the labels ;)

**Comment by saturninoabril** [comment]
Also I corrected reference PR above (it should be https://github.com/mattermost/mattermost-webapp/pull/2324 - added CherryPickApproved to that PR as well).

**Comment by amyblais** [comment]
@deanwhillier Can you help cherry-pick this to v5.9 (if not already)?

**Pull request merged**
