### PR TITLE
Updating favicon images

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Mm 37697 - Updated Favicons

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37697

#### Release Note
```release-note
None
```

### CODE REVIEW

**Review by andrewbrown00 — APPROVED** [review]
Good to go, thanks, @asaadmahmood 👍

**Comment by andrewbrown00** [comment]
@deanwhillier do you mind doing the dev review on this? It's updating the favicons to the new branding, [here's the Figma file for reference](https://www.figma.com/file/ZoGSPtyCqkSmt22WfzGzZl/?node-id=692%3A227), thanks 🙂

**Review by deanwhillier — CHANGES_REQUESTED** [review]
Looks good for the most part! The deleted files are unfortunately still being referenced in the `webpack.config.js` file starting at line 315. If you are sure they are not needed anymore, then you'll need to remove the references to them from that file.

Also, the built-in rounded corners don't match the iOS icon rounding: 
Screenshot 2021-12-09 at 4 03 06 PM

That said, I would suggest reading [this post on "How to Favicon in 2021"](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs). Looks like we could greatly simplify the whole process to just 6 files ... times 3 to handle unread and mentions.

**Comment by asaadmahmood** [comment]
Hey @deanwhillier, regarding your comment about removal.
The images are still in there, I have just modified the files, not removed them. For some reason, Github is showing those images as removed, but they are there.
https://github.com/asaadmahmood/mattermost-webapp/tree/MM-37697/images/favicon

**Comment by deanwhillier** [comment]
@asaadmahmood, ah yes, my bad! I saw red and just assumed that meant deleted as I'm used to seeing code changes, which obviously doesn't happen with image ... please ignore that comment. :P

**Comment by asaadmahmood** [comment]
Cool. @deanwhillier I also went ahead and removed the border radius on the IOS assets, so the rounding thing should be fixed if it autocrops it.

**Review by deanwhillier — APPROVED** [review]

**Comment by stylianosrigas** [comment]
Removing cloud test server for maintenance reason. Please feel free to add it again if needed.

**Pull request merged**
