### PR TITLE
remove duplicate text

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Remove duplicate "Advanced compliance management" text in self hosted pricing modal.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48823

#### Screenshots

before:
duplicate-text

after:
after

#### Release Note

```release-note
Remove duplicate text in self-hosted pricing modal
```

### CODE REVIEW

**Review by ConorMacpherson — APPROVED** [review]
LGTM, just needs the i18n ordering updated it seems.

**Comment by neallred** [comment]
Thanks for noticing that! Looks like the cloud version was using that other version. Updated both to use the more verbose version.

**Review by AGMETEOR — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
Looks good!

**Pull request merged**
