### PR TITLE
Changing "One-click" to "Quick" reactions on messages

### PR DESCRIPTION
**Pull request by cwarnermm**
#### Summary
Updated the "One-click reactions on messages" user setting to "Quick reactions on messages".

#### Ticket Link
https://community-daily.mattermost.com/boards/workspace/g4k9s1f953n4bytz5f9sz9orer/e7651b0e-83ad-4910-874d-875706ddf121/925d0849-da95-4be0-8dd5-f0bf1914e0c3/466b1283-64dd-4599-809e-bb20408ad24e

#### Release Note

```release-note
Updated the "One-click reactions on messages" user setting to "Quick reactions on messages".
```

### CODE REVIEW

**Comment by michelengelen** [comment]
@saturninoabril should we check the E2E here as well?

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by saturninoabril** [comment]
@michelengelen On a quick look, I'd say no need since it seems obvious enough but by looking at the text change, I think it has missed to change the one at `en.json`. So for me in general, I'd recommend to run E2E in a PR at least once as part of final criteria before merging so we can fix as much as possible during PR review and not after merge.

**Comment by cwarnermm** [comment]
Thanks, @saturninoabril for noting that the changes were missing from the ``en.json`` file. I've corrected that.

**Comment by saturninoabril** [comment]
Here are the E2E test results:
- before the change in `en.json` - [link](https://mattermost-cypress-report.s3.amazonaws.com/55376-0da9d44-ee-ent-webapp-pr-9366-mm-ee-test:0da9d44/mochawesome.html) - with failed test related to text change
- after the change - [link](https://mattermost-cypress-report.s3.amazonaws.com/57192-9e1b7b7-ee-ent-webapp-pr-9366-mm-ee-test:9e1b7b7/mochawesome.html) - ✅

**Comment by jgilliam17** [comment]
Thank you @saturninoabril for running the E2Es. 
Thanks @cwarnermm 
Tested, looks good to merge.
- Verified user setting text change from "one-click" to "quick" reactions on messages.

**Review by jgilliam17 — APPROVED** [review]

**Comment by cwarnermm** [comment]
Thanks, @saturninoabril! I'd like to help with the E2E test fixes, but I'm not sure how to help.

**Comment by saturninoabril** [comment]
@cwarnermm Thanks and I really appreciate your willingness to help with E2E! You've probably seen it already but posting here [our E2E guide/docs](https://developers.mattermost.com/contribute/webapp/e2e/) for reference. We can connect via Zoom too to clarify all things/questions you have in mind.

**Comment by cwarnermm** [comment]
@michelengelen - Would you be open to helping correct the failing E2E tests resulting from this PR?

**Review by esethna — APPROVED** [review]

**Pull request merged**
