### PR TITLE
MM-15976 Replace forced refresh with banner alerting users that a new version is available

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
To avoid refreshing the app on users without telling them, we now show a banner alerting them that a new version is available with a link to refresh the app.

Proposing this for 5.13 since it's a good quality of life improvement.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-15976

### CODE REVIEW

**Comment by jwilander** [comment]
@wiersgallak this is hard to test since it requires manipulating the server version. Thankfully the UI is minimal so here's a screenshot:

Screen Shot 2019-06-03 at 17 35 13

Some questions/comments for your consideration:

1. The colour of the banner does not match the design since I am using the banner colour we already have for announcements. If you want me to introduce the new colour to match the design, let me know
2. The spacing on the banner also deviates from the design as I matched the spacing all our other banners used. I can change this as well, but I'm leaning towards keeping our spacing consistent across all our banners
3. Minor but the `.` in the `Refresh the app now.` when it is not in the design. I can change that if it matters
4. The precedence for what type of banner will show up (when there are multiple banners trying to show at once) is: Configuration bar, version bar, error bar, announcement bar. I can move the version bar around in that if you don't think that works

**Comment by wiersgallak** [comment]
@andrewbrown00 - Can you please review 1, 2, 3?  

@jwilander - I am good with 4.

**Comment by andrewbrown00** [comment]
@jwilander answers below:

1. Let's use the updated color. We'd like to introduce it as the new default color to create more contrast from the rest of the default theme and other theme UIs.
2. Same for the banner height. We'd also like to introduce the new height to align with the UI redesign which follows the 8px grid and more breathing room.
3. We should not include the period as part of the link. Terminal periods should be excluded from text links when they are sentences. **Note** this is a rule we will need to our guidelines and also define the rest of the rules around Links and punctuation.

**Comment by jwilander** [comment]
Thanks @andrewbrown00 @wiersgallak. Couple clarifications:

1) Am I updating all our blue banners to use this new colour, or just adding a new one for the upgrade banner?
2) To do this I would be changing all the banner heights, not just the one for upgrading. Is that ok?

**Comment by andrewbrown00** [comment]
Welcome @jwilander.

1. Yes, we'd like to use the new banner color for the default Announcement banner color.
2. Yes, increasing all banner heights is good.

**Comment by jwilander** [comment]
Thanks! I'll make those changes

**Comment by jwilander** [comment]
@wiersgallak @andrewbrown00 changes made for 1-3. Here's an updated screenshot:

Screen Shot 2019-06-04 at 11 00 39

If that looks good to you, please approve and I can move this to developer review.

**Comment by hanzei** [comment]
@amyblais Should this be cherry picked?

**Comment by amyblais** [comment]
@jwilander Quality releases are normally for bug fixes, is this non-risky to add to v5.13? If yes, can you help cherry-pick?

**Comment by jwilander** [comment]
It's fairly low risk and it's been soaked on community-daily for sometime now. I'll cherry-pick 👍

**Pull request merged**
