### PR TITLE
[MM-32188] Fix Apps modal styling issues

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR adds the modifications to the ReactSelect component to have its options be fully visible in the Apps modal. These modifications are done in 3 other places in the webapp as well.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-32188
Fixes https://mattermost.atlassian.net/browse/MM-32042

#### Screenshots

Before select option fix

After select option fix

Before error-spacing fix

After error-spacing fix

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM

**Review by jfrerich — APPROVED** [review]
This looks awesome with the fix!

**Review by DHaussermann — APPROVED** [review]
Tested and passed. 
Tested with an addition to the test-app
- Initial vertical resolution of modal is now reasonable
- Modal height can now be increased when fields and information change after it's initially opened
- Regardless of number of fields and info added modal height reaches a reasonable maximum and can scroll vertically as expected to show remaining info

LGTM! 

I will test this again with ZenDesk once it is available in case any follow-up changes are needed.

**Pull request merged**
