### PR TITLE
Uses PureComponent wherever shouldComponentUpdate absent.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary
Switches from `Component` to `PureComponent` wherever `shouldComponentUpdate` is absent. [Apparently some teams at Facebook are doing the same](https://news.ycombinator.com/item?id=14418576). This change is predicated on the belief that re-rendering is more expensive than checking whether props have changed - which I believe to be likely in the majority of cases although I admittedly have not proven it. 

I would be happy to gather a random sampling of data from the 173 components that this PR changes and we could regroup on that data if we want to prove/disprove my assumption before moving forward.

Thoughts?

Note this PR [was originally here](https://github.com/mattermost/mattermost-webapp/pull/246) but had to be re-opened.

#### Ticket Link
n/a

#### Checklist
- [x] Touches critical sections of the codebase (auth, posting, etc.)

#### Illustration

Here's an example showing the decrease in the number of renders of the `SearchBar` component when composing a post:

Using `Component` in `SearchBar` (existing production code):
more-renders

Using `PureComponent` in `SearchBar` (PR code):
fewer-renders

### CODE REVIEW

**Comment by mkraft** [comment]
I have compared `master` and `pure-components` branches with the following scenarios:

* Posting 'a' 10x to an empty channel
* Re-loading the page
* Changing to the 'organization' theme starting from Town Square

I used the following Chrome tools:

* Performance tab (using both no CPU throttling and with 6x slowdown)
* Memory tab
* Audit tab
* More Tools -> JavaScript Profiler

Results:

* JS heap size: no discernible difference
* Timing (page load, scripting, and rendering times): no discernible difference
* CPU throttling: no discernible effect on timing

It is possible that my tests were insufficient or flawed or misinterpreted, but **I’m wondering if the React framework's virtual-DOM equivalency checking code is close enough in efficiency to the framework's shouldComponentUpdate code that the difference is not noticeable in the context we're operating?**

Anyhow we haven't proven that this PR is an improvement but we're currently migrating components one at a time to be pure anyhow, so this will only speed up that process and allow us to focus on other things so I saw merge it.

**Comment by jwilander** [comment]
I'm a little wary merging this if there's not a discernible performance improvement. I think if I was confident it wouldn't cause any subtle bugs (like @hmhealey mentioned on pre-release) I'd be more OK with it. Unfortunately the reality is our React components aren't perfect, and a lot of them might rely on some state that's independent of a component's state/props causing those subtle bugs.

That said, I'm not totally against it but I'd prefer it be at the beginning of a release cycle so it has more time to soak before it gets included in a release and also have LM run through it and do a smoke test first

**Comment by mkraft** [comment]
@jwilander That is a good point and I had forgotten that Harrison had told me that *not all state in the app is immutable* when I was writing my comment. That does change things because merging this could cause a blast of bugs. I suppose to your point do we do them all at once or component-by-component. Riskier/faster/less-labour-intensive vs slower/more-conservative/more-work?

**Comment by jwilander** [comment]
Well we're already migrating components one-by-one to use the Redux pattern, and part of that is making the component pure and have immutable state/props so eventually it'll be covered by that campaign anyways. If there's no noticeable perf improvement from doing it all at once, then I think it's better to go with the slower lazy-load method

**Comment by mkraft** [comment]
@jwilander Agreed. Closing. Oh well.

**Pull request closed without merging**
