### PR TITLE
[MM-48044] bulk dependency upgrades patch version changes

### PR DESCRIPTION
**Pull request by m1lt0n**
#### Summary

In the context of dependency upgrades, patch-level dependency upgrades (batch update multiple dependencies)

| Dependency | From version | To version | Changelog | Notes |
|-------------|-------------|----------|------------|---------|
| react-router-dom | 5.3.3 | 5.3.4 | [Changelog](https://github.com/remix-run/react-router/releases/tag/v5.3.4) | Removal of a dependency to mini-create-react-context | 
| react-window | 1.8.7 | 1.8.8 | [Commits in last release](https://github.com/bvaughn/react-window/commits/master) | Small fixes for off-layout scroll bar size | 
| react-virtualized-autosizer | 1.0.6 | 1.0.7 | [Changelog](https://github.com/bvaughn/react-virtualized-auto-sizer/commits/master) | Added peer dependency for react 18 | 
| react-beautiful-dnd | 13.1.0 | 13.1.1 | [Changelog](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v13.1.1) | Adds react 18 in supported React versions and changes of internal dependencies | 
| redux-thunk | 2.4.1 | 2.4.2 | [Changelog](https://github.com/reduxjs/redux-thunk/releases/tag/v2.4.2) | Removal of unused type | 
| regenerator-runtime | 0.13.9 | 0.13.10 | [Commits for latest version - no changelog](https://github.com/facebook/regenerator/commits/main/packages/runtime) | Minor low-level changes | 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-48044

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by nevyangelova** [comment]
Thanks @m1lt0n LGTM! Might be some overlap with the react upgrades but I can resolve conflicts if there are any.

**Comment by M-ZubairAhmed** [comment]
Some time in future, we might have to stop with updates of react router, because with the v6, the complete api changes. I am not sure if we have any appetite to change that.

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by m1lt0n** [comment]
yep @M-ZubairAhmed I looked into react router v6, it's a quite big project to move away from v5, changes spanning the whole app and to some point also moving away from class components, so rewriting some of the app code.

**Pull request merged**
