### PR TITLE
[MM-21405] Show warning first when Sync group members is turned on without members and then show error if save without groups added

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Display a warning if no groups are added and user tries to sync members and after they press save turn it into an error (matches team configuration page)

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21405

#### Screenshots

MM-21405

### CODE REVIEW

**Comment by srkgupta** [comment]
Hi @thefactremains 
I am not sure if you noticed this, but as per the JIRA ticket, the behavior should be in consistence with Team Profile page. However on the Team Profile page, the moment we toggle the Sync Group Members radio button, we get a message at the bottom, something like this, before clicking on Save button. 

 
Should the behavior be changed in Team Profile page as well and message be displayed only after clicking on Save button (like in Channel page)

**Comment by thefactremains** [comment]
@srkgupta you are correct. The purpose of this was to match the functionality of the team config page alert process. It was clearly an error on my part as the JIRA ticket states conflicting info. I have confirmed that the team config page shows the error prior to save and change the message as groups are added. 

@hahmadia my apologies, but this PR may have been built on misdirection from me. Can you please ensure that the functionality matches the team config page? I will add a comment to the JIRA ticket as well.

**Comment by hahmadia** [comment]
@thefactremains @srkgupta 
Updated! Please see main post for details.

**Comment by hahmadia** [comment]
> @hahmadia just found one inconsistency still, i.e. on Channel Configuration page when you hit save, it displays "Saving Config..." and then displays the error in red. However on Team Configuration page, when you hit save, it does not displays "Saving Config...". It just displays the error. The problem with displaying "Saving Config..." is that the error message shifts to the right a few pixels and then comes back which looks odd. Can we make this consistent too?

Done. I tagged Michael just to get his approval on this too.

**Comment by thefactremains** [comment]
@srkgupta yes. same verbiage (though replacing "team" with "channel") is good by me.

**Comment by hahmadia** [comment]
@srkgupta 
I have updated the text. Please ensure that channel config page works as usual and that the text on team config page has also not changed.

**Comment by michaelgamble** [comment]
> @michaelgamble @thefactremains can you also confirm if the message is fine on the Channel configuration page. It says ` You must add at least one group to manage this team by sync group members.` whereas it should be ` You must add at least one group to manage this channel by sync group members.`. I can raise this as a separate issue on JIRA since its existing on the prior versions as well. Please confirm.

Yes you're correct in what the warning should be changed too.

**Comment by michaelgamble** [comment]
Ha cool, i just noticed my review wasnt required anymore, seems like you guys have this PR under control

**Pull request merged**
