### PR TITLE
[MM-46607] Style fixes for insights

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Fixes the following tickets:
- https://mattermost.atlassian.net/browse/MM-46607
- https://mattermost.atlassian.net/browse/MM-46594 (number 2)
- https://mattermost.atlassian.net/browse/MM-46886
- https://mattermost.atlassian.net/browse/MM-46595

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@BenCookie95 There are some conflicts to resolve here.

**Review by mkraft — APPROVED** [review]

**Review by plant99 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Except this ticket https://mattermost.atlassian.net/browse/MM-46607

Everything else was passed

**Comment by amyblais** [comment]
> Except this ticket https://mattermost.atlassian.net/browse/MM-46607
> 
> Everything else was passed

@furqanmlk Do you know if this is good to merge if the one ticket didn't pass? Or will that be discussed with the team on Monday?

**Comment by furqanmlk** [comment]
> > Except this ticket https://mattermost.atlassian.net/browse/MM-46607
> > Everything else was passed
> 
> @furqanmlk Do you know if this is good to merge if the one ticket didn't pass? Or will that be discussed with the team on Monday?

This is good to merge for Monday release. I talked to @plant99 we will create separate PR. But I tested this PR, it is working as expected nothing is breaking

**Pull request merged**
