### PR TITLE
Mm t2920 wip

### PR DESCRIPTION
**Pull request by nkrishna79**
#### Related Pull Requests
- Has server changes (https://github.com/mattermost/mattermost-webapp/pull/8245)

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by Willyfrog** [comment]
@nkrishna79 is this a WIP pr?

**Comment by nkrishna79** [comment]
> @nkrishna79 is this a WIP pr?

Sorry its not WIP. I just named it to give it more sense when starting to work on it. But this is the final PR

**Comment by Willyfrog** [comment]
> > @nkrishna79 is this a WIP pr?
> 
> Sorry its not WIP. I just named it to give it more sense when starting to work on it. But this is the final PR

Would you be so kind to fill the template with the appropiate info in the root post so we know what we should be looking for?

You also need to sign the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/)

**Comment by nkrishna79** [comment]
> 
> 
> > > @nkrishna79 is this a WIP pr?
> > 
> > 
> > Sorry its not WIP. I just named it to give it more sense when starting to work on it. But this is the final PR
> 
> Would you be so kind to fill the template with the appropiate info in the root post so we know what we should be looking for?
> Sorry I dont understand. When you say template - did you mean "Excel" sheet? 

> You also need to sign the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/)
I have already signed it.

**Comment by Willyfrog** [comment]
no, sorry, I meant to fill the info up in this PR, the one that is currently like this:


> #### Summary
> #### Ticket Link
> #### Related Pull Requests
> 
>     * Has server changes (please link here)
> 
>     * Has mobile changes (please link here)
> 
> 
> #### Screenshots
> #### Release Note
> 
> ```
> 
> ```

**Pull request closed without merging**
