### PR TITLE
Trim unused languages

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
By default, we include code to highlight all languages that highlight.js supports, but we really only support a much smaller, static list. By removing those we don't support, we can shave about 200KB gzipped off the production bundle size (measured by userin webpack-bundle-analyzer on assets created with `npm run build`, before and after my changes).

I also added support for some languages file extension names where it seemed missing, and added back in zsh support (there's no zsh language in highlight.js, so the closest thing is the bash language, which their supported language page [recommends](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)).

I also posted a gist to my own github with snippets for all languages we currently support: https://gist.github.com/neallred/a81c30202c0a689207504fb46dfd63f9

Note that latex support is added via the `latexcode` tag.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46227

#### Release Note
```release-note
Code blocks have better support for language filetype extensions
Smaller bundle size
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Thanks! That's a pretty solid reduction to bundle size for stuff we're not using. Here's hoping we can find more ways to improve this since we're surely loading a lot of extra data here

**Comment by hmhealey** [comment]
> I noticed latex doesn't seem like its working in master or in this branch. I'm very ok not trying to fix it as part of this effort.

Do you mean you're trying to use it with `latex` or `latexcode` as the language? The former is intentionally not supported since we highjacked that way back to do latex rendering, but using `latexcode` as the language in the web app is supposed to get around that.

This works for me on community at least
~~~
```latexcode
\documentclass{article}

\begin{document}

Hello World!

\end{document}
```
~~~

**Comment by neallred** [comment]
Ahh, didn't realize it needed to be `latexcode`. That works for me in community and on this branch.

**Review by stevemudie — APPROVED** [review]
Looks good @neallred!

**Pull request merged**
