### PR TITLE
Webpack 4 compatible pdfjs-dist.

### PR DESCRIPTION
**Pull request by silverskyvicto**
#### Summary
mattermost-webapp uses webpack 4, but pdfjs-dist 2.0.489 assumes webpack 2 or 3.

If it is the latest one, it supports webpack 4.

How about upgrading pdfjs-dist?

### CODE REVIEW

**Comment by hmhealey** [comment]
Adding @grundleborg to this since he's been handling dependency updates lately.

**Comment by hmhealey** [comment]
The error that I'm seeing is that something is trying to run an `eval` statement which is blocked by CSP. I suppose that's why the stayed at the previous version of the library? According to [this](https://github.com/mozilla/pdf.js/issues/10229), it's caused by one of their dependencies (either Babel or facebook/regenerator), but as far as I know, we have newer versions of both of those dependencies.

**Comment by cpanato** [comment]
removing the test server due stale, if need again please add the label back

**Comment by hmhealey** [comment]
Hi @silverskyvicto. Have you had a chance to look into the stuff we talked about above? Is there anything we could help with?

**Comment by silverskyvicto** [comment]
Hi @hmhealey 

Sorry for the late reply.

I am also currently checking.
The query will close once, as it will take some time.
Reopen when progress is made.

**Comment by hmhealey** [comment]
No worries. Let us know what you figure out!

**Pull request closed without merging**
