### PR TITLE
MM-29656 Fix button styles in product notices

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Fixing the hover styles for buttons in product notices modal

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29656

#### Screenshots
Oct-27-2020 21-09-40
Oct-27-2020 21-12-49

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Comment by asaadmahmood** [comment]
@matthewbirtch Can you verify and see if the hover states match our design system, I think they don't, but I haven't looked at the buttons in a while.

**Comment by matthewbirtch** [comment]
@asaadmahmood @sudheerDev how do I get the notice to show?

**Comment by asaadmahmood** [comment]
Not sure, will have to wait for Sudheer.

**Comment by sudheerDev** [comment]
@asaadmahmood @matthewbirtch Aah, sorry. it is hard to test in normal way. I can hardcode a notice in code to show up to in the UI, Does that work for you guys?

**Comment by matthewbirtch** [comment]
> @asaadmahmood @matthewbirtch Aah, sorry. it is hard to test in normal way. I can hardcode a notice in code to show up to in the UI, Does that work for you guys?

Yep, that would work for me @sudheerDev

**Comment by sudheerDev** [comment]
@matthewbirtch You can now try the spinmint, I hardcoded a couple of notices to get the idea

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Hey @sudheerDev A few things to note:

1. The focus state of the secondary button has a `text-decoration: underline` on. Can you remove?
image

2. The size of the 'Download' button here should be our 'Medium' size (40px height). Have a look at our [button component file](https://www.figma.com/file/2uYWxjnMJ9IQDOba9b9bfV/Components-Buttons?node-id=1088%3A1091). It looks like you're using the right font size for the medium button, but the padding and overall height/width doesn't match the button size used  for exact specs:
3. The hover state for the 'Previous' button here should also be updated to match the 'small' 'tertiary' button hover state (again have a look at the Figma component file above).
image.

With Figma you can view and inspect all the dimensions. But let me know if you need help with that.

**Comment by emilyacook** [comment]
> Hey @sudheerDev A few things to note:
> 
> 1. The focus state of the secondary button has a `text-decoration: underline` on. Can you remove?
>    image
> 2. The size of the 'Download' button here should be our 'Medium' size (40px height). Have a look at our [button component file](https://www.figma.com/file/2uYWxjnMJ9IQDOba9b9bfV/Components-Buttons?node-id=1088%3A1091). It looks like you're using the right font size for the medium button, but the padding and overall height/width doesn't match the button size used  for exact specs.
> 
> 
> 
> 1. The hover state for the 'Previous' button here should also be updated to match the 'small' 'tertiary' button hover state (again have a look at the Figma component file above).
> 
> 
> 
> With Figma you can view and inspect all the dimensions. But let me know if you need help with that.

Hey @sudheerDev! Gentle ping on this :)

**Comment by esethna** [comment]
@deanwhillier can your team help finish this up if  possible? Just minor button and styling fixes on the notice modals

**Comment by michelengelen** [comment]
hi @esethna ... I (or maybe @nevyangelova) can take this over on monday, if that is sufficient!

**Comment by michelengelen** [comment]
closing in favour of #7820

**Pull request closed without merging**
