### PR TITLE
MM-13198 Add placeholder when loading images

### PR DESCRIPTION
**Pull request by hmhealey**
This is to fix the aspect ratio of images in the RHS and on small screens while still using the image dimensions to lay out the post before an image is loaded.

The reason this ends up being so complicated is because HTML only supports resizing an image and maintaining its aspect ratio if and only if the image has no explicit width or height set, but without a width or height set, the image will pop in and cause the post layout to change. To solve this, we generate a blank image of the correct dimensions (createPlaceholderImage in utils/image_utils.jsx) and render that while the actual image loads in the background (loadImage in utils/image_utils.jsx).

I tested this on all 5 browsers, and with metadata enabled, I did see some pop in with Firefox on the first page load, but that's fine for now since that's experimental.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-13198

#### Checklist
- Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by sudheerDev** [comment]
@hmhealey This needs to be done for the large image instance in  webhook attachment as well.

**Comment by hmhealey** [comment]
Alright, I made that use the same SizeAwareImage component (previously called MarkdownImage) as well so we can go back to setting the width of that to 100% instead of calculating the dimensions manually

**Comment by hmhealey** [comment]
@cpanato Files are broken on this spinmint for some reason. It seems like it can't write to disk since when I try to upload a file, I get this error:
image

**Comment by cpanato** [comment]
@hmhealey let me check the server

**Comment by cpanato** [comment]
@hmhealey try again

**Comment by hmhealey** [comment]
Thanks!

@DHaussermann You're good to test now

**Comment by DHaussermann** [comment]
Tested Tall and wide images in main and RHS thread
Tested in markdown as well as webhook post

@hmhealey I'm not sure on the scope of this task. I found no issues in the RHS but webhook posts in the main thread that are very tall will have an issue with aspect ratio. Please advise if this must also be changed in this PR. 

tall-markdown

**Comment by DHaussermann** [comment]
Hi @hmhealey ,  I looked into the issue above where images with tall aspect ratios do not display with their full height - main thread only. This does not repo on Master or previous versions. 
Also, it does not seem to make a difference if you include other data in the post as seen in the screenshot.

**Comment by hmhealey** [comment]
@DHaussermann I think I've fixed it, and I've tested with both wide images
image
and tall ones
image

**Comment by hmhealey** [comment]
@DHaussermann This is ready for QA review again unless you're willing to take my screenshots as proof that it's fixed :P

**Comment by sudheerDev** [comment]
@hmhealey is this for 5.7

**Comment by hmhealey** [comment]
@sudheerDev No, if it still goes into 5.7, there'll be a lighter version of it that only fixes the dimensions without post metadata

**Pull request merged**
