### PR TITLE
E2E/Playwright: Add user browser context, reorganize env variables and update screenshots

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Added user browser context to easily login user per browser and its pages
- Reorganized env variables in one place only
- Fixed tests and updated snapshots
- Removed applitools

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
Thank you @saturninoabril ,
I've run this locally, it works well now.
I had one observation, there's lot of explicit mention of 'networidle', wondering of we can make it implicit when Channel() is called, ([example](https://github.com/mattermost/mattermost-webapp/blob/ce8d4cd6b54170d893faba7f13aa3e9f24aa3272/e2e/playwright/tests/visual/intro_channel.spec.ts#L24))

I can try it in follow up pr

**Review by furqanmlk — APPROVED** [review]
wow, thanks @saturninoabril 
excited to use this framework.

Looks amazing

**Review by mvitale1989 — APPROVED** [review]
LGTM, thank you @saturninoabril !

**Comment by saturninoabril** [comment]
@yasserfaraazkhan Good point! I've addressed it in the other PR - https://github.com/mattermost/mattermost-webapp/pull/12237

**Pull request merged**
