### PR TITLE
MM-14622 Pass post id as well as link when retrieving opengraph data

### PR DESCRIPTION
**Pull request by ChrisDobby**
This change in mattermost-redux - https://github.com/mattermost/mattermost-redux/pull/964 - requires a post id to be passed to getOpenGraphMetadataForUrl

  Fixes https://github.com/mattermost/mattermost-server/issues/12015

Otherwise, link the JIRA ticket.
-->

- Has redux changes https://github.com/mattermost/mattermost-redux/pull/964
- Has mobile changes https://github.com/mattermost/mattermost-mobile/pull/3516

### CODE REVIEW

**Comment by hmhealey** [comment]
Approved, but this has to be merged at the same time as the mattermost-redux changes since it changes the arguments of the selector

**Comment by jasonblais** [comment]
Hey @jgilliam17, friendly reminder to help with QA review once 5.17 release tasks are done :)

@ChrisDobby would you be open to help sync/rebase your branch against `master`? Thanks for your contribution!

**Comment by ChrisDobby** [comment]
> @ChrisDobby would you be open to help sync/rebase your branch against `master`? Thanks for your contribution!

Have rebased with master

**Comment by jgilliam17** [comment]
> Mattermost test server created! 🎉
> 
> Access here: https://mattermost-webapp-pr-4119.test.mattermost.cloud
> 
> Account Type	Username	Password
> Admin	sysadmin	Sys@dmin123
> User	user-1	User-1@123

I'll remove this server in a few hours after I am done testing, please don't destroy 😃

**Comment by jgilliam17** [comment]
@hmhealey I was hoping you can help me with the test server. Blocked on testing at the moment.
I've enabled link previews in the system console and account settings and now I'm getting a blank screen when trying to view the channel (Town Square) with the links and there are also 2 errors, see screenshot. 

Screen Shot 2019-11-20 at 9 57 56 AM

**Comment by hmhealey** [comment]
I updated the branch to the latest version of master since I think there was a merge issue that caused the branch to pull the wrong version of mattermost-redux. Let's see if that fixes it

**Comment by jgilliam17** [comment]
Thanks for the update @hmhealey 
I'm still seeing the same 2 errors + white screen after posting a youtube link

**Comment by hmhealey** [comment]
@ChrisDobby Would you be able to take a look into those errors? I'm seeing them on the test server as well. If they're not reproducing for you locally, you can log into the test server with the credentials listed above

**Comment by ChrisDobby** [comment]
> @ChrisDobby Would you be able to take a look into those errors? I'm seeing them on the test server as well. If they're not reproducing for you locally, you can log into the test server with the credentials listed above

Will do

**Comment by ChrisDobby** [comment]
Hi @hmhealey @jgilliam17 have had a look at the above error on the test server as I couldn't repro it locally.  When debugging it I found that, as far as I can see, the version of mattermost-redux distributed in the node_modules folder on the test server is not the version containing the changes - https://github.com/mattermost/mattermost-redux/pull/964. For instance the attached images show the difference between the `getOpenGraphMetadataForUrl` function on my local build and the test server.

Package.json looks OK and when I build everything from scratch locally it is fine.
local
test-server

**Comment by sudheerDev** [comment]
@ChrisDobby Hey, You need to update package-lock.json as well. The redux file issue is because the package-lock file references to a different commit hash.

**Comment by ChrisDobby** [comment]
> @ChrisDobby Hey, You need to update package-lock.json as well. The redux file issue is because the package-lock file references to a different commit hash.

Thanks for that @sudheerDev !  Have pushed a change to package-lock.json

**Comment by hmhealey** [comment]
I've updated this branch, but the PR doesn't seem to be updating. Once the build for mattermost-redux is finished, I'll merge that and update these branches

**Comment by hmhealey** [comment]
Thanks again for the PRs, @ChrisDobby! Glad to have this in

**Pull request merged**
