### PR TITLE
MM-47462: Removed global state from 'actions/views/root.ts'

### PR DESCRIPTION
**Pull request by codewithshariq**
#### Summary

Removed global state from 'actions/views/root.ts'

#### Ticket Link

Fixes [https://github.com/mattermost/mattermost-server/issues/21360](https://github.com/mattermost/mattermost-server/issues/21360)
Jira [https://mattermost.atlassian.net/browse/MM-47462](https://mattermost.atlassian.net/browse/MM-47462)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by koox00** [comment]
This seems that it does the opposite of what we want, we want to eliminate passing `state` to actions, since actions can getState from the thunk

**Review by koox00 — CHANGES_REQUESTED** [review]
This seems that it does the opposite of what we want, we want to eliminate passing `state` to actions, since "thunked" actions have `getState` available.

**Review by nevyangelova — CHANGES_REQUESTED** [review]
Thanks @codewithshariq I have updated the ticket so it makes it a little more clear what we would like to achieve. We would be calling getState as long as it's coming from a thunk inside the component. We don't want to import it from stores/redux_store.

Example in trackEvent 

```
export function trackEvent(category, event, props) {
    return async (dispatch, getState) => {
        const state = getState();
        ...
        ...
        ...
   }
});
dispatcht(trackEvent(...));
```

**Comment by hmhealey** [comment]
Closing as per https://github.com/mattermost/mattermost-webapp/pull/11367#issuecomment-1282969494

**Pull request closed without merging**
