### PR TITLE
[MM-28225] Private Cloud sales card

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Sales card on the Subscriptions screen to upsell Mattermost Private Cloud.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28225

### CODE REVIEW

**Review by stevemudie — APPROVED** [review]
LGTM

**Comment by matthewbirtch** [comment]
@devinbinnie I don't see the subscription page, or the billing & account section altogether in the system console

**Comment by devinbinnie** [comment]
> @devinbinnie I don't see the subscription page, or the billing & account section altogether in the system console

@matthewbirtch Flipped the switch, it's on now.

**Review by matthewbirtch — APPROVED** [review]
Looks perfect @devinbinnie! Awesome job

**Review by ethervoid — APPROVED** [review]
LGTM! Noice!

**Review by nickmisasi — APPROVED** [review]
LGTM

**Pull request merged**
