### PR TITLE
[MM-18035] Spacebar now activates all <button>'s when focused

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Some screen readers read `<button>` elements with a tutor message that says 'Press space to activate'. This PR adds that functionality to all `<button>`s in the system such that pressing space will trigger their click event.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18035

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @devinbinnie 

Tested on the spinwick (Chrome/Win10) and these are my results:
- **Pressing Space Bar opens the respective menu / activates the button for**
1. _Message List Main Region (center panel) and Message Details (RHS)_
   - Tab to focus on the username of the person who made the post (space bar opens their profile pop-over - see note below in A - Notes)
   - Tab to focus on the flag icon - Flag for follow-up (space bar flags the post - see below in B - Notes)
   - Tab to focus on the More Actions [...] menu (space bar opens the menu - see below in C - Notes)
   - Tab to focus on the Attachment Button - works as expected and opens attachments window
   - Tab to focus on the Emoji Picker Button - works as expected and opens emoji picker
   - Tab to focus on the Reply Button - works as expected and opens RHS reply input box
2. _Reply Input Region (RHS)_
   - Tab to focus on the Attachment Button - works as expected and opens attachments window
   - Tab to focus on the Emoji Picker Button - works as expected and opens emoji picker
   - Tab to focus on the Preview Button - works as expected and puts the text in preview mode (but see below in D - Notes)
   - Tab to focus on the Add Comment Button - works as expected and posts the reply (but see below in E - Notes)
3. _MESSAGE DETAILS (top of reply area in RHS)_
   - Expand button - works as expected and expands/collapses the RHS
   - Close button - works as expected and closes the RHS
4. _Message Input Complimentary Region (center)_
   - Attachment button - works as expected and opens attachments window
   - Emoji Picker button - works as expected and opens emoji picker
   - Preview button - works as expected and puts the text in preview mode (but see below in F - Notes)
5. _Team Menu Region (top of LHS)_
   - Tab to focus on Set Status button - works as expected and opens Status selection menu (but see below in G - Notes)
   - Tab to focus on Main Menu button - works as expected and opens the Main Menu (but see below in G - Notes)
6. _Channel Sidebar Region (LHS)_
   - Tab to focus on the "+" to the right of PUBLIC CHANNELS, PRIVATE CHANNELS and DIRECT MESSAGES - works as expected and opens the Create New Public/Private/Direct channel modals
   - Tab to focus on the "More..." below PUBLIC CHANNELS and DIRECT MESSAGES - works as expected and opens the More Channels/Direct Messages modals
7. _Channel Header Region (top of Center)_
   - Tab to focus on the "star/favorite icon" - works as expected and favorites/unfavorites the channel (but see below in H - Notes)
   - Tab to focus on the Channel Menu button - works as expected and opens the channel menu dropdown (but see below in I - Notes)
   - Tab to focus on the Add a Channel Description button - works as expected and opens the "Edit Header for [channel_name]" modal
   - Tab to focus on the Members button - works as expected and opens the Channel Members dropdown (but see below in J - Notes)
   - Tab to focus on the Message button (to the right of a username in the Channel Members dropdown) - works as expected and opens a direct message with the user
   - Tab to focus on the Manage Members button (bottom of Channel Members dropdown) - works as expected and opens the [Channel_name] Members modal
   - Tab to focus on the Pinned Posts/Recent Mentions/Flagged Posts icons - work as expected and open in the RHS (but see below in K - Notes)
8. _Region at the top of a newly created channel_
   - Invite others to this team button - works as expected and opens the Invite Members screen (but see below in L - Notes)
   - Set a header button - works as expected and opens the Edit Header for [channel_name] modal
9. _Main Menu - Account Settings_
   - All sections and subsections in Account Settings modal are working as expected - open when space bar is pressed (but see below in M - Notes)
10. _Main Menu - All options_ - the reader reads out the option name (e.g. Account Settings --> Invite People --> etc) but does _NOT_ read "Press Space Bar to activate" although pressing Space Bar to activate _DOES_ work for _SOME_ options (see below in N - Notes)

**General Observation:**
For all areas mentioned below in the notes, where pressing space bar moves focus/the cursor to the message input box:
 - this could be problematic because the "space" that's being pressed is actually being added to the message input box, creating a "draft message" of spaces and causing the placeholder text "Write to [channel_name]" to disappear.
- Strangely, this doesn't cause the "draft pencil icon" to appear to the left of the channel name?
- In a scenario where the user's next post would be a slash command, the command would fail because there is a space before the '/'
image


**NOTES**:
A. Once you have pressed space bar on the username of the person who made the post and pressed space bar, their profile pop-over opens - however, the cursor then jumps to the message input box and the reader reads "Message input complimentary region - write to [channel name]". _There is no notification to the person that a user's profile pop-over is open on the screen_.

B. Once you have pressed space bar to activate the Flag icon, the cursor jumps to the message input box and there is no feedback to the user that the post has been flagged (other than knowing that pressing space bar activates the flag). If, however, you go back to the post, the reader does read that the message is flagged.

C. Pressing space bar opens the More Actions [...] menu but the cursor then jumps to the message input box and does not stay focused on the menu items - there is no way to select one of the options in the menu

D. Pressing space bar puts the text in Preview mode but the cursor then jumps to the message input box in the center panel, leaving the text in the message input box in the RHS in preview mode 

E. I am able to tab to focus on the Add Comment button when there is no text in the input box and the Add Comment button is greyed out. Reader reads out "press space bar to activate" but this does nothing.

F. Pressing space bar puts the text in Preview mode but focus is not directed anywhere else and the user is left in a situation viewing a message in preview mode. (I can hit Tab which focuses on the Preview button again and pressing Space Bar takes the user back to Edit mode)

G. Pressing space bar opens the Status Selection and Main Menu but the cursor jumps to the message input box in the center, leaving the selection menu open, with no option highlighted, and no indication to the user how to make a selection

H. Pressing space bar favorites/unfavorites the channel but the cursor jumps to the message input box in the center and gives no indication to the user that the channel has been favorited/unfavorited (If I use Tab to go back to the "star icon", reader does read out "Add to Favorites/Remove from Favorites")

I. Pressing space bar opens the Channel dropdown menu but the cursor jumps to the message input box in the center, leaving the selection menu open, with no option highlighted, and no indication to the user how to make a selection

J. Pressing space bar opens the Channel Members dropdown menu but the cursor jumps to the message input box in the center, leaving the selection menu open, with no option highlighted, and no indication to the user how to make a selection.  _I also noticed that after tabbing away/removing focus from the Members button, it remains highlighted._ (Waiting until the reader has finished reading out the "message input region" and then pressing Tab _does_ focus on the first option in the list though)

K. Pressing space bar opens the Pinned Posts/Recent Mentions/Flagged Posts in the RHS but the cursor jumps to the message input box in the center. The reader does not read anything in the RHS.  _I also noticed that after tabbing away/removing focus from these buttons, they remain highlighted._

image

L. Pressing space bar opens the Add Members screen but the cursor jumps to the message input box in the screen behind the Add Members screen and the reader reads out "Message Input Complimentary Region - Write to [channel_name]". The reader doesn't read out anything on the Add Members screen and the user has to click on the "X" to close this screen and return to Mattermost window.

M. All Account Settings options are working as expected, however, it seems that I am only able to use Tab to navigate within the sub-menus (e.g. Notifications > Email Notifications) _IF I turn the Virtual PC Cursor ON._ I might be mis-remembering this but I'm sure tabbing to navigate within these menus worked before.  On the spinwick, when I open Main Menu > Account Settings (using Space Bar and with Virtual PC Cursor OFF) nothing is read once the Account Settings modal is open.  However, if I turn the Virtual PC Cursor ON and then open Main Menu > Account Settings (using Space Bar), the reader starts reading the first option in General > Full Name > Edit button.  _Is this expected now / has this behavior changed?_ (I've just tested on `community` 5.14.1 and, with Virtual PC Cursor OFF the reader starts reading the first option in General > Full Name > Edit button - so I think the behavior on this PR is new)

N. The sections within the Main Menu that _do not_ open using Space Bar are:
  - Create a New Team
  - Integrations
  - System Console
  - Help
  - Report a Problem
  - Download Apps

Sorry this is so long - I tried to cover all areas where pressing space bar would open a menu and/or activate a button...

Let me know if you have any questions!

**Comment by jwilander** [comment]
Wow, great review @lindy65 that's a lot of good detail 👍

**Comment by devinbinnie** [comment]
Hey @lindy65,

Thanks for your very comprehensive feedback!
I've boiled down most of your issues into the following points which i'll address below:

**Cursor/focus moving to text box when SPACE is pressed**
I've made a fix that should address this issue globally. Feel free to re-test :)

**Focus on Add Comment button**
This was a small quick fix, so I added as part of this PR. Feel free to re-test :)

**Notification from screen reader that status changed (ie. flag for follow-up toggle, popover open)**
These are existing issues with the system that still exist regardless of what keyboard action (enter, spacebar, or otherwise) is used to trigger the `button`. Unfortunately all these cases are specific to their areas and will require specific solutions based on what the case is. I'm not sure if we want to create an epic or a ticket to track these, but I think it's part of next steps to make the system more accessible. Unfortunately, it's out of scope for this PR due to the magnitude of change required.

**Navigation in Account Settings and menus**
I'm not having any trouble navigating within Account Settings, everything seems to be working for me. This might have been fixed with the changes I've made but I can't see why. Worth re-testing I suppose.

However, I am noticing that navigating within menus doesn't work with arrow keys, and it doesn't loop through the menu when tabbing. This is also reproducible on `community`. I'm not sure if that is expected either but it might need to be looked into.

**Inconsistent behaviour of some elements**
This PR was designed to address the tutor message created by JAWS on `button` elements. Unfortunately, for some strange reason some of the Main Menu elements are `span` elements or `a` elements instead. This is another large change that is outside the scope of this PR, but should definitely be tracked by some kind of story for a future release.

I think that's everything, let me know if I missed anything. Thanks again!

**Comment by lindy65** [comment]
Thanks @devinbinnie @jwilander! 

I've been caught up in meetings for a while so I'll test your fixes first thing in my morning Devin!

**Comment by lindy65** [comment]
Thanks for reviewing all my comments and for your feedback @devinbinnie!

**Cursor/focus moving to text box when SPACE is pressed**
  - Thanks, **this is fixed**, however I have noticed that cursor focus is no longer in the message input box. Pressing TAB after focus is set there, takes the user to Team Menu Region > Set Status button:

image

**Account Settings Modal**
  - The issues I had navigating yesterday **do indeed seem to be fixed**. _However, I've noticed Jaws misses out focusing on the first option in each sub-section (although it does read the option out)._
  - Like you, I also noticed that moving through menu options using up/down arrow keys does not work and tabbing does not cycle through the menu options) and have deferred to Eric in the comments directed at him below.

image

> E. I am able to tab to focus on the Add Comment button when there is no text in the input box and the Add Comment button is greyed out. Reader reads out "press space bar to activate" but this does nothing
  - **FIXED - can no longer tab to the greyed out button**

> K. I also noticed that after tabbing away/removing focus from these buttons, they remain highlighted.
  - **FIXED - no longer remain highlighted**

**NEW ISSUES OBSERVED SINCE PREVIOUS TESTING:**

a. When a header is already set, Jaws skips tabbing to the field in the header region (it does tab there when no header is set)

image

b. When RHS is open, Jaws reads "unlabelled button" for Recent Mentions (it reads the button correctly if RHS is closed)

image

On your comments as per below, I'll defer to @esethna to decide on improvement tickets for the feature:

> **Notification from screen reader that status changed** (ie. flag for follow-up toggle, popover open)
These are existing issues with the system that still exist regardless of what keyboard action (enter, spacebar, or otherwise) is used to trigger the button. Unfortunately all these cases are specific to their areas and will require specific solutions based on what the case is. I'm not sure if we want to create an epic or a ticket to track these, but I think it's part of next steps to make the system more accessible. Unfortunately, it's out of scope for this PR due to the magnitude of change required.

> **Inconsistent behaviour of some elements**
This PR was designed to address the tutor message created by JAWS on button elements. Unfortunately, for some strange reason some of the Main Menu elements are span elements or a elements instead. This is another large change that is outside the scope of this PR, but should definitely be tracked by some kind of story for a future release.

> However, I am noticing that **navigating within menus doesn't work with arrow keys, and it doesn't loop through the menu when tabbing**. This is also reproducible on community. I'm not sure if that is expected either but it might need to be looked into.

Thanks again Devin, this feature is improving so much!

**Comment by devinbinnie** [comment]
Hey @lindy65, thanks again. Comments are below.

> **Cursor/focus moving to text box when SPACE is pressed**
> 
> * Thanks, **this is fixed**, however I have noticed that cursor focus is no longer in the message input box. Pressing TAB after focus is set there, takes the user to Team Menu Region > Set Status button:

Not sure what you mean, nothing odd is happening for me here. What's the steps to reproduce this?

> 
> **Account Settings Modal**
> 
> * The issues I had navigating yesterday **do indeed seem to be fixed**. _However, I've noticed Jaws misses out focusing on the first option in each sub-section (although it does read the option out).

This is an issue with the accessibility controller, it actually is focused and JAWS should be reading it, but the accessibility controller isn't applying the class to show the outline. Should probably be a separate ticket.
 
> **NEW ISSUES OBSERVED SINCE PREVIOUS TESTING:**
> 
> a. When a header is already set, Jaws skips tabbing to the field in the header region (it does tab there when no header is set)

I can't get it to tab there regardless of if a header exists or not. Must not be focusable. Separate ticket/story (not sure if it was missed or not)

> b. When RHS is open, Jaws reads "unlabelled button" for Recent Mentions (it reads the button correctly if RHS is closed)

Was missed when doing the accessibility work. This should be a new story.

**Comment by lindy65** [comment]
Hey @devinbinnie 

For your question about repro steps for:

> **Cursor/focus moving to text box when SPACE is pressed**
>  - Thanks, **this is fixed**, however I have noticed that cursor focus is no longer in the message input box. 

Repro:
- Observe when first logging in the the cursor is focused in the message input box
- CTRL+F6/F6 until focus is on the "favorite star"
- Press space bar to activate the "favorite star"
- Observe cursor does not have focus in the message input box

However:
- I tested on `master` and v5.15 release branch and behavior is the same, even when using the mouse to navigate/click.
- Once the user starts typing, focus is automatically put in the message input box so I don't believe this is an issue

> **NEW ISSUES OBSERVED SINCE PREVIOUS TESTING:**
a. When a header is already set, Jaws skips tabbing to the field in the header region (it does tab there when no header is set)
**I can't get it to tab there regardless of if a header exists or not. Must not be focusable. Separate ticket/story (not sure if it was missed or not)**

  - I am able to tab to/focus on the "Add a channel description" field IF no header has been set. Once a header is set, Jaws skips this field when tabbing (Win10/Chrome). Are you using a Mac? Desktop App? Just want to clarify for ticket purposes...

header

**Recent Mentions being read as "unlabelled button" when RHS is open**
> b. When RHS is open, Jaws reads "unlabelled button" for Recent Mentions (it reads the button correctly if RHS is closed)
> - Was missed when doing the accessibility work. This should be a new story.

  - I will create a ticket for this issue, together with the issue above (once I know what platform you're on)

**Comment by devinbinnie** [comment]
@lindy65 I was using Chrome/Win10, without JAWS running however. Though that shouldn't affect focus behaviour.

As for the 'favourite star' issue, that is definitely expected behaviour as far as I'm concerned. So we should be good there :)

**Comment by lindy65** [comment]
Thanks @devinbinnie 

- For not being able to TAB to "Add a channel description" field, I've filed https://mattermost.atlassian.net/browse/MM-18163

- For Recent Mentions button being read as "unlabelled button" when the RHS is open, I've filed https://mattermost.atlassian.net/browse/MM-18164

- As Eric is away at the moment and, so we don't lose sight of the issues, I've created https://mattermost.atlassian.net/browse/MM-18165 for him to take a look at when he's back.

I think we're good to go then! Thanks :)

**Pull request merged**
