### PR TITLE
MM-23516: Fix images being pasted as text in Firefox

### PR DESCRIPTION
**Pull request by luryus**
#### Summary
This PR fixes some images being pasted as text in addition to the file attachment in Firefox. See the [issue for details](https://github.com/mattermost/mattermost-server/issues/14027).

In some situations, Firefox seems to paste images from the clipboard into any text field as text. For example, if clipping any image with `xclip` like this:
```
xclip -sel clip -t image/png -i sample.png
```
Firefox is happy to paste the image as text to the search field in the New tab page (at least on Linux, FF 80):
image
For some reason, this is only done in some situations. For instance, copying an image from GIMP (as mentioned in the Github issue), or from Firefox itself, does not cause FF to paste the image as text.

In Mattermost, pasting an image correcly attached it as a file, but Firefox also pasted the image as text in the message field.

I worked around this by simply adding a `preventDefault()` call when any files are pasted from the clipboard. I also added/updated relevant unit tests.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/14027

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you @luryus 👍

**Comment by esethna** [comment]
Adding @jgilliam17 for QA review

**Review by sudheerDev — APPROVED** [review]

**Comment by sudheerDev** [comment]
@luryus Thank you 🎉

**Review by jgilliam17 — APPROVED** [review]
Thank you @luryus 
Tested, looks good to merge.
- Verified images paste as expected in Firefox, not as text. Tested on macOS, Windows and Ubuntu.

**Comment by sudheerDev** [comment]
@amyblais Want to confirm again, is this for 5.27v?

**Comment by amyblais** [comment]
@sudheerDev At this point of the v5.27 release cycle we should focus on fixing regressions as we're past code complete and nearing the end of the release,

**Comment by sudheerDev** [comment]
Aah, misread the milestone.

**Pull request merged**
