### PR TITLE
[MM-32201] Job table changes for data retention

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
This update is for data retention. I needed a prop to hide the create job button because I need to call the create job endpoint from outside this component.

Design: https://www.figma.com/file/PdZPkf36lNU6ZO41JlEjKd/Team-%26-Channel-Data-Retention?node-id=20%3A181

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32201

#### Screenshot
Screen Shot 2021-03-31 at 10 45 08 AM

### CODE REVIEW

**Review by anurag6713 — APPROVED** [review]
LGTM!

**Review by maxerenberg — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
image

**Pull request merged**
