### PR TITLE
[MM-26599] Make new  category outline on dragover

### PR DESCRIPTION
**Pull request by camgraff**
Fixes https://github.com/mattermost/mattermost-server/issues/15902

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-26599

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
@deanwhillier Gentle reminder to review this PR

**Review by deanwhillier — APPROVED** [review]
LGTM, thanks for the contribution @camgraff and apologies for the delayed review!

**Comment by hmhealey** [comment]
Thanks for the PR, @camgraff. Unfortunately, it looks like I accidentally fixed this while cleaning up some code in that same area, so that's why there's the merge conflict here. Sorry that we can't merge your changes now, but I believe this should still count towards your Hacktoberfest contributions. Thanks again for your contribution though 🙂

**Pull request closed without merging**
