### PR TITLE
MM-34026 Cypress/E2E: fix markdown tests

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fixed markdown tests

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34026

#### Screenshot
Screen Shot 2021-03-31 at 9 51 05 PM

### CODE REVIEW

**Review by furqanmlk — APPROVED** [review]
image

LGTM

**Review by josephbaylon — APPROVED** [review]
@saturninoabril LGTM. But looks like the PR build is failing.

**Review by prapti — APPROVED** [review]
Looks good, tests passed locally as well.
Thanks Saturn!

**Pull request merged**
