### PR TITLE
MM-40148: decouples thread data from counts

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

Currently fetch threads returns counts for threads as well.
This raises some performance concerns.

As of now we support `onlyThreads` and `onlyCounts` on the getThreadsForUser
api.
This commit utilizes these two query parameters to decouple counts from
actual thread data.
Introduces `getThreadCounts` action which only returns counts and
`getThreads` now will only return threads.

This is the same as https://github.com/mattermost/mattermost-webapp/pull/9735 with a master merge and pushed to the mattermost org to make testing easier.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-40148

#### Related Pull Requests

- Has server changes (https://github.com/mattermost/mattermost-server/pull/19833)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by ashishbhate** [comment]
@koox00 

This is the same as #9735, with a some minor changes to bring it up to date with master. I've also pushed it to the mattermost org to make testing easier.

**Review by koox00 — APPROVED** [review]
awesome! thanks!

**Comment by ashishbhate** [comment]
@jgilliam17 this needs to be tested along with the server PR - https://github.com/mattermost/mattermost-server/pull/19833

This ticket primarily addresses some performance issues, so just some smoke testing around thread unreads and counts should suffice.

**Comment by ashishbhate** [comment]
This PR might also fix - https://mattermost.atlassian.net/browse/MM-40561

**Comment by jgilliam17** [comment]
@ashishbhate @koox00 Here is one way to reproduce negative unread count
1. As User1 -Create a new channel and add root post
2. Reply to the post mentioning user2
3. Add user2 to channel on the rhs
4. As user 2 login and open global threads (observe that global threads item has mention badge + not bolded(bug?), open threads and graphic shows no unread threads)
5. Open thread on thread inbox to read
6. Switch away to a different channel (observe global threads is now bolded)
7. Open global threads again - Graphic shows -1 unread count

**Comment by ashishbhate** [comment]
I don't think the changes in this PR will necessarily fix the negative unreads counts issue. The changes here just leverage some performance improvements on the server side. We might see some improvement in users seeing missing messages in the RHS.

**Comment by jgilliam17** [comment]
Thanks @ashishbhate 
Tested, looks good to merge.
- Verified threads unreads and mention count - as expected.
- [E2E report](https://automation-dashboard.vercel.app/cycles/2a743136-adbb-4f94-b2e3-7ff31e36ed76) looks good. There was one crt related test that failed, but it is not reproducing when testing manually.
- I'll leave the test server up after approving in case either you or @koox00 would like to debug `-1` count per steps above.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
