### PR TITLE
9140 changed the custom trigger to accept spaces

### PR DESCRIPTION
**Pull request by pradeepmurugesan**
#### Summary
Changed the custom trigger text to accept spaces

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/9140

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [x] Has server changes  - https://github.com/mattermost/mattermost-server/pull/9180
- [ ] Has redux changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by esethna** [comment]
Amazin, thanks @pradeepmurugesan! One issue I found was when clicking recent mentions the keywords with spaces should be in quotes so results for the individual words don't appear:

image
image

So I would expect the recent mentions query to include ``"one two" three``

Queung this for QA review. Great work.

@hmhealey any thoughts on the implementation? I know you had some thoughts on this earlier

**Comment by pradeepmurugesan** [comment]
@esethna I am sorry.. Didn't know such a feature exists.. Will provide a fix for the same

**Comment by lindy65** [comment]
Thanks @pradeepmurugesan @esethna 

I have tested on the above spinmint but don't think it contains Pradeep's latest commit?  Can you spin up a new test server Eric and I'll re-test everything again?

Thanks!

**Comment by pradeepmurugesan** [comment]
@esethna pushed the changes for recent mentions.. Kindly check and let me know

**Comment by esethna** [comment]
Approach being discussed on the server PR: https://github.com/mattermost/mattermost-server/pull/9180

**Comment by cpanato** [comment]
`Setup Test Server` label detected. Spinmint test server created if build succeeds (checks pass and no conflicts with base branch).

**Comment by cpanato** [comment]
Spintmint test server creation failed. See the logs for more information.

**Comment by esethna** [comment]
@pradeepmurugesan are you okay if we close this and related PR's for now? Based on internal discussion, it sounds like if we are going to find a new library used for searching mention keywords we need to get more clear on the expected for various cases of symbols, spaces etc and what we should be supporting. I can circle back with you once we have that and a proposed approach for how to solve this completely.

**Comment by pradeepmurugesan** [comment]
@esethna Yes.. Sounds good for me.. 👍

**Pull request closed without merging**
