### PR TITLE
Update subpackage versions to 7.0.0

### PR DESCRIPTION
**Pull request by hmhealey**
I'll probably automate this eventually, but the release process for the subpackages is pretty simple since they're locked to the version of the web app. There's a more detailed version in `packages/README.md` in this repo, but for now, I'm just updating these version numbers, and then once this is merged, I'll tag the commit for future reference.

Also, for my own future reference, the published packages are available here:
- https://www.npmjs.com/package/@mattermost/client
- https://www.npmjs.com/package/@mattermost/types

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44326

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Also, since this is a fairly simple change, I'll probably skip this PR in the future and just push the commit/tags to the release branch directly, assuming that's still possible with however we have the release branches configured here.

**Comment by pfltdv** [comment]
> Also, since this is a fairly simple change, I'll probably skip this PR in the future and just push the commit/tags to the release branch directly, assuming that's still possible with however we have the release branches configured here.

Thanks alot @hmhealey for keeping us in the look, in future yes skipping may be useful if those are applied to the master branch as well.

**Review by pfltdv — APPROVED** [review]
LGTM

**Pull request merged**
