### PR TITLE
Remove the play/check icon in onboarding task list

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

With the intro of emojis in the tasklist, we want to remove the play/check icon so it's not so cluttered at the start. This is a request from UX. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48361

#### Screenshots

|  before  |  after  |
|----|----|
|  Screen Shot 2022-11-11 at 12 10 50 PM | Screen Shot 2022-11-11 at 12 35 32 PM|

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by annelieseklein — APPROVED** [review]

**Comment by annelieseklein** [comment]
@marianunez can we ensure a spacing of 10px between emoji and text please?

**Comment by pvev** [comment]
I think this style can be removed too https://github.com/mattermost/mattermost-webapp/blob/master/components/onboarding_tasklist/onboarding_tasklist_task.tsx#L36

**Review by pvev — APPROVED** [review]
LGTM! thanks @marianunez :shipit:

**Comment by marianunez** [comment]
> @marianunez can we ensure a spacing of 10px between emoji and text please?

The spacing here is going to be tricky because the emoji is part of the text. If we want to control this more I think we would need to separate the emojis. Thoughts @pvev ?

**Comment by marianunez** [comment]
> > @marianunez can we ensure a spacing of 10px between emoji and text please?
> 
> The spacing here is going to be tricky because the emoji is part of the text. If we want to control this more I think we would need to separate the emojis. Thoughts @pvev ?

We will need to separate them anyways if we want to change the first emojis with the product icons. We'll do that separetly from this PR @annelieseklein

**Comment by pvev** [comment]
> > @marianunez can we ensure a spacing of 10px between emoji and text please?
> 
> The spacing here is going to be tricky because the emoji is part of the text. If we want to control this more I think we would need to separate the emojis. Thoughts @pvev ?

let me take a look!

**Comment by pvev** [comment]
> > > @marianunez can we ensure a spacing of 10px between emoji and text please?
> > 
> > 
> > The spacing here is going to be tricky because the emoji is part of the text. If we want to control this more I think we would need to separate the emojis. Thoughts @pvev ?
> 
> let me take a look!

@marianunez you are right, with the symbol being included in the text the px spacing will be tricky, however based on this ticket https://mattermost.atlassian.net/browse/MM-48361 the idea is to change the icons, so in that case we should place the icons/symbols in its own element so we can easily apply styles to it.

**Review by julmondragon — APPROVED** [review]
LGTM!

**Comment by marianunez** [comment]
> @marianunez you are right, with the symbol being included in the text the px spacing will be tricky, however based on this ticket https://mattermost.atlassian.net/browse/MM-48361 the idea is to replace the icons with new ones, so in that case we should place the icons/symbols in its own element so we can easily apply styles to it.

Products icons with the new spacing will be covered in https://mattermost.atlassian.net/browse/MM-48362

**Comment by marianunez** [comment]
@amyblais heads up that I am going to cherry pick to this small change to the `cloud` branch for next week release

**Pull request merged**
