### PR TITLE
MM-37961 - update invite members image to new branding

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
Updates the invite members button image to the new branding.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37961

#### Screenshots
Before:
Screen Shot 2021-08-16 at 3 57 19 PM

After:
Captura de pantalla 2021-08-17 a las 12 42 34

Captura de pantalla 2021-08-17 a las 12 43 15

#### Release Note

```release-note
NONE


```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
lgtm! :sunglasses:

**Comment by annelieseklein** [comment]
lgtm! I just updated the illustration to better match themes: https://www.figma.com/file/MYVj0NUudT9V7GV9KepBy3/Illustrations?node-id=416%3A5018

**Review by annelieseklein — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
Looks good @pablovelezvidal !

Tested it in different themes and it worked as expected.

**Review by AGMETEOR — APPROVED** [review]

**Comment by amyblais** [comment]
@marianunez Is this for cloud release tomorrow?

**Comment by marianunez** [comment]
This is for v6.0 so it should be cherrypicked to `cloud`

**Pull request merged**
