### PR TITLE
[MM-35392, MM-35972] CRT: cross team unreads handling

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
 - Include `prevUnreadMentions`, `prevUnreadReplies` for calculating thread-unread increment/decrement
 - Include thread unreads (per-team) to existing getMyTeamUnreads pipeline/flow
 - Utilize `channel_type` in `handleThreadReadChanged` to determine if GM/DM (should affect all team counts)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35392
https://mattermost.atlassian.net/browse/MM-35972
https://mattermost.atlassian.net/browse/MM-35393

#### Related Pull Requests

https://github.com/mattermost/mattermost-server/pull/17813

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by esethna** [comment]
@calebroseland how's this PR and the related server work going?

**Comment by esethna** [comment]
@koox00 is taking over this PR

**Comment by esethna** [comment]
@koox00 @jwilander how is finishing these PRs coming along?

**Comment by jwilander** [comment]
@esethna haven't had the time to work on it yet. Hoping to look at it later this week.

**Pull request closed without merging**
