### PR TITLE
MM-22116: fix clear search results

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Avoid trying to write to `this.value` when clearing the search text -- which might be an invalid ref -- and rely exclusively on the incoming `onClear` callback to effect the necessary props changes. Update the unit tests to make explicit assertions about what's visible vs. mostly relying on snapshots.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-22116

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/4766
https://github.com/mattermost/mattermost-webapp/pull/4389

### CODE REVIEW

**Comment by lieut-data** [comment]
@marianunez, I might have missed something, but `SearchableChannelList` also doesn't set `clearable`, so wouldn't expect the widget at all. I contemplated collapsing this into a single property, but wasn't sure if those semantics would be clear enough.

**Comment by marianunez** [comment]
> @marianunez, I might have missed something, but `SearchableChannelList` also doesn't set `clearable`, so wouldn't expect the widget at all. I contemplated collapsing this into a single property, but wasn't sure if those semantics would be clear enough.

Gotcha! Maybe we could add a note in the documentation of the `clearable` to clarify that the `OnClear` is also required for the `X` to appear.

**Comment by lieut-data** [comment]
Thoughts on just coupling `onClear` and eliminating `clearable` altogether, with documentation clarifying what setting this does?

**Comment by marianunez** [comment]
> Thoughts on just coupling `onClear` and eliminating `clearable` altogether, with documentation clarifying what setting this does?

1/5 I like keeping the `clearable` prop because I wouldn't expect that an event handler also adds a "feature" to the component that I am subscribing to. IMO would be more clear if I can turn it on/off specifically with that setting.

**Comment by lieut-data** [comment]
Sounds good -- I've attempted to clarify the component props documentation. Let me know what you think!

**Pull request merged**
