### PR TITLE
MM-50308 - Custom status in more places

### PR DESCRIPTION
**Pull request by coltoneshaw**
#### Summary
Added the custom user status in the RHS user list, fixed the style in the team members list, and added it to the Sys Console > Users list for fun.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50308

#### Screenshots
|  before  |  after  |
|----|----|
|  Screenshot 2023-02-03 at 2 18 06 PM |  Screenshot 2023-02-03 at 2 15 42 PM |
|Screenshot 2023-02-03 at 2 17 52 PM  | Screenshot 2023-02-03 at 2 15 33 PM |
| Screenshot 2023-02-03 at 2 17 58 PM | Screenshot 2023-02-03 at 2 15 25 PM |

#### Release Note

```release-note
Show custom user status in channels RHS and system console.
```

### CODE REVIEW

**Comment by coltoneshaw** [comment]
@matthewbirtch - Let me know if you find any other places where I can throw the user status. I looked around and didn't see any logical places on first glance.

**Review by laneycs — APPROVED** [review]

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Nice improvement @coltoneshaw. Thanks!

I think the primary place is in the Channel Info RHS, I'm not sure it is as important in the system console, but suppose it can't really hurt. If we are going to add it more to the system console, there are other members lists that appear within groups, teams, channels I believe. But again, I think the Channel info RHS is the main place we need it. So if you want to keep this PR isolated to that, I'd be fine with that.

- There is some extra space showing to the left of the custom status emoji on the Team Members modal:
    image
- In the find channels modal, there is a wide gap between the user and the custom status emoji - not sure if this is caused by this PR though as it seems there are some similar issues on community right now.
    image

**Comment by coltoneshaw** [comment]
@matthewbirtch - The second feedback should be fixed in another PR https://github.com/mattermost/mattermost-webapp/pull/12120

**Comment by coltoneshaw** [comment]
> I think the primary place is in the Channel Info RHS, I'm not sure it is as important in the system console, but suppose it can't really hurt. If we are going to add it more to the system console, there are other members lists that appear within groups, teams, channels I believe. But again, I think the Channel info RHS is the main place we need it. So if you want to keep this PR isolated to that, I'd be fine with that.

Happy to remove it from the system console. I figure it should go any place that you are taking action on that specific user or looking at their info. So, System Console > Users felt like a good place to not be over bearing. I imagine a situation where an admit is looking up who a user is, they use the search in sys console and see the user is on PTO for a week or something. 

----------

Let me fix that spacing in the team members too. I didn't see that locally.

**Comment by coltoneshaw** [comment]
@matthewbirtch - Okay, I found the difference here. It's when you do not have a first / last name. Let me play with this to see what I can to do make this look even. 
 
Screenshot 2023-02-03 at 3 09 32 PM

**Comment by coltoneshaw** [comment]
Okay, fixed it and added controls to those random spaces that were added.

Screenshot 2023-02-03 at 3 24 12 PM

**Comment by matthewbirtch** [comment]
@coltoneshaw thanks for fixing those few issues. One other thing: I notice we're placing the custom status in an inconsistent position. Sometimes between the display name and username and other times at the end of both the display name and user name

image

image

image

image

image

image

Seems like the majority of cases show it after both display name and username. We should consider making the order consistent everywhere. If this ends up blowing the scope of this PR, we can consider creating a follow-up ticket to fix that. Let me know

**Comment by coltoneshaw** [comment]
@matthewbirtch - What's your ideal location for the custom status?

**Comment by matthewbirtch** [comment]
> @matthewbirtch - What's your ideal location for the custom status?

@coltoneshaw I think it makes the most sense to show it at the end

**Comment by coltoneshaw** [comment]
> @coltoneshaw I think it makes the most sense to show it at the end

Alright, I'll see about sticking it there!

**Comment by coltoneshaw** [comment]
**RHS Channel Members**

RHS Channel Members

**Channel Switcher**
(I checked the other PR fix and that still works fine here)

Screenshot 2023-02-03 at 10 18 40 PM

**@ Mention**

Screenshot 2023-02-03 at 10 22 13 PM

**System Console > Users**

Screenshot 2023-02-03 at 10 20 29 PM

**Create new DM**

Screenshot 2023-02-03 at 10 21 10 PM

**Comment by coltoneshaw** [comment]
@matthewbirtch - It's not letting me rerequest review, but see above everything is updated so far.

**Review by matthewbirtch — APPROVED** [review]
Nice work @coltoneshaw! Looks good to me

**Comment by coltoneshaw** [comment]
@BenCookie95 Would you still be the one to review here?

**Comment by BenCookie95** [comment]
> @BenCookie95 Would you still be the one to review here?

Yep I can do this one, I'll add another reviewer as well

**Review by BenCookie95 — APPROVED** [review]

**Comment by coltoneshaw** [comment]
@BenCookie95 / @kostaspt - Want me to move this to a branch on this repo, instead of a fork so the builds can finish?

**Comment by BenCookie95** [comment]
> @BenCookie95 / @kostaspt - Want me to move this to a branch on this repo, instead of a fork so the builds can finish?

@coltoneshaw Is there an ETA to when fork pipelines will be fixed?

**Comment by coltoneshaw** [comment]
> > @BenCookie95 / @kostaspt - Want me to move this to a branch on this repo, instead of a fork so the builds can finish?
> 
> @coltoneshaw Is there an ETA to when fork pipelines will be fixed?

I don't think so, no. I got this info from https://community.mattermost.com/private-core/pl/m6s1gagnsjgudk98gd6inojzte

**Pull request closed without merging**
