### PR TITLE
[MM-43786] Insights top channels

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Adding top channels widget for insights

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43786

#### Related Pull Requests
Need to merge first:
- https://github.com/mattermost/mattermost-webapp/pull/10207
- https://github.com/mattermost/mattermost-webapp/pull/10238

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by plant99 — APPROVED** [review]

**Comment by BenCookie95** [comment]
@furqanmlk Can you enable the feature flag please?

**Comment by furqanmlk** [comment]
> @furqanmlk Can you enable the feature flag please?

@BenCookie95 Done

**Review by furqanmlk — COMMENTED** [review]
1.
 image
image

2. According to figma total number of top channel is 10 but in this PR total number of top channel is 9

**Comment by BenCookie95** [comment]
> https://mattermost-webapp-pr-10262.test.mattermost.cloud

@furqanmlk I can see 10 top channels in the PR?

**Comment by BenCookie95** [comment]
> image
> 
> image
> 
> 2. According to figma total number of top channel is 10 but in this PR total number of top channel is 9

@matthewbirtch is the figma correct? I thought we were supposed to lowercase the first letter of the second word?

**Comment by furqanmlk** [comment]
> > https://mattermost-webapp-pr-10262.test.mattermost.cloud
> 
> @furqanmlk I can see 10 top channels in the PR?

Ah sorry.. I meant other way around. Figma shows 9

**Comment by BenCookie95** [comment]
> > > https://mattermost-webapp-pr-10262.test.mattermost.cloud
> > 
> > 
> > @furqanmlk I can see 10 top channels in the PR?
> 
> Ah sorry.. I meant other way around. Figma shows 9

Ah right, I'm pretty sure it's supposed to be top 10 as we removed pagination. Can you confirm @matthewbirtch ?

**Comment by furqanmlk** [comment]
@BenCookie95 **I noticed couple of things, if Channel name is too long, icon is disturbed**
image
**Bar looks very small in number**
image
**After resizing, There is no scroll bar**
image

**Comment by BenCookie95** [comment]
> @BenCookie95 **I noticed couple of things, if Channel name is too long, icon is disturbed** image **Bar looks very small in number** image **After resizing, There is no scroll bar** image

Thanks Malik!

1. I can fix that
2. I don't know if there is anything I can do about it because those sizes are calculated as a percentage and those numbers are a lot smaller than than the total
3. I will address the responsive stuff in another PR

**Comment by matthewbirtch** [comment]
> @matthewbirtch is the figma correct? I thought we were supposed to lowercase the first letter of the second word?

@furqanmlk good catch. This is a mistake in Figma. I will update. We should be using sentence case (only capitalize the first letter of the first work)

**Review by furqanmlk — APPROVED** [review]
LGTM

**Comment by matthewbirtch** [comment]
> if Channel name is too long, icon is disturbed

@BenCookie95 rather than wrapping the channel name, can we truncate it so it always appears on a single line? (similar to what we do in the LHS)

**Comment by BenCookie95** [comment]
> > if Channel name is too long, icon is disturbed
> 
> @BenCookie95 rather than wrapping the channel name, can we truncate it so it always appears on a single line? (similar to what we do in the LHS)

Looks like the cloud server didn't update due to the conflict, I'll fix that and you'll be able to see the single line truncation

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
1. Please truncate channel names to a single line within the widget (as noted in previous comment).

2. The modal is displaying off the screen for me rather than vertically centering. Doesn't quite seem right.
image

3. Also, in the modal, can we truncate the channel names to a single line?

4. Private channels are using the incorrect icon. It should be the outlined version of the lock icon. (design below)
image

5. Can we add hover states to each row when you hover?
image

6. Can we also add tooltips to the numbers as designed?
image

**Comment by BenCookie95** [comment]
> 6\. oltips to the numbers as designed?

@matthewbirtch All those things are fixed, only thing you might notice is that they tooltip appears on the right and not on top. This is due to some flex issues where it wasn't appearing centred above the number

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @BenCookie95 looks much better now, thanks!

A couple last styling things I noticed in the modal view:
- In the modal, can you make the icons next to the channel names 56% just like they are in the widget view? (`color: rgba(var(--center-channel-color), .56);`
- The channel names in the modal should also be semi-bold (`font-weight: 600`) just like they are in the widget view
- can we add 4px or margin between the icon and text in the channel name within the modal?

**Comment by BenCookie95** [comment]
> * color: rgba(var(--center-channel-color-rgb), .56);

@matthewbirtch those issue are fixed now

**Review by matthewbirtch — APPROVED** [review]
Thanks! Looks good @BenCookie95

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Spoke to soon...just realized there is a wrong theme variable being used for the channel name in the widget. Can you change it to use `center-channel-color` rather than `center-channel-text`? 

I'm not sure what `center-channel-text` is used for in the app, but I've run in to this problem before. It should always be the `center-channel-color` variable as that's the proper theme variable.

image

**Comment by BenCookie95** [comment]
> center-channel-color

No problem, fixed!

**Review by matthewbirtch — APPROVED** [review]

**Comment by amyblais** [comment]
@BenCookie95 This is not needed for v7.0, correct?

**Comment by BenCookie95** [comment]
> @BenCookie95 This is not needed for v7.0, correct?

Nope, not for v7.0

**Pull request merged**
