### PR TITLE
Adjusted min and max username length to reflect value from mattermost-server.

### PR DESCRIPTION
**Pull request by stschindler**
#### Summary
Minimum and maximum username length are set to the same values as in Mattermost server, allowing username lengths from 1 to 64 characters.

#### Ticket Link
None.

#### Checklist
- [x] Ran `make check-style` to check for style errors
- [x] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests
- [ ] Has server changes
- [ ] Has redux changes
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [x] Touches critical sections of the codebase (constants)

### CODE REVIEW

**Comment by jasonblais** [comment]
Hey @stschindler - the restriction for 3 to 22 characters is to optimize the UX and avoid issues with very short and long usernames.

What login method does your system have - email/password, or something else?

**Comment by stschindler** [comment]
@jasonblais Hey. Exactly, we use either email/password or username/password. The usernames of our team are the user's initials.

Whereas I can understand the reasoning behind the restriction, it makes it impossible for us to follow our naming policies. For us, that's no good UX obviously. ;-) 

IMO ideally, this should be configurable at the server and respected by the clients.

**Comment by jasonblais** [comment]
Thanks @stschindler, appreciate the feedback 👍 

Let me touch base with our design team and get their thoughts.

**Comment by jasonblais** [comment]
Hey @stschindler - requiring at least three characters for the username is done because searching for recent mentions won't work for 1 or 2 character usernames.

The restriction isn't applied on the server-side because some LDAP and SAML usernames might only be 1 or 2 characters long --> in which case their username would turn into a random string, which is worse UX than not having recent mentions search work properly. But we've kept the restriction client-side.

Let me know if you have any thoughts or feedback on this

**Comment by jasonblais** [comment]
Hey @stschindler - really appreciate the thoughtfulness here and contributing back to the Mattermost project.

However, given the concerns with recent mentions search with 1 and 2 character usernames, we won't be able to accept the PR at this time.

We're happy to discuss it if you have feedback on the decision. Here is the relevant thread in the UX Design channel if you're interested participating: https://pre-release.mattermost.com/core/pl/njneuws6e3y5fm45t4fyrcmjaw

**Pull request closed without merging**
