### PR TITLE
MM-20664 Add client side ping pong

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary

  * Emit ping event after every 10secs
  * clear timer to not emit ping events when socket is emitting messages(Means socket is alive and does not require pings)
  * close conn if the server does not respond with a pong in due time(This is needed to close stale connections on weird network errors)

This follows the recommended approach or sockets https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20664

The revert was made because the client was reconnecting after socket disconnect without closing the earlier connection. After reconnect the first socket events are considered as missed websocket event because of clearing the `this.eventSequence` value making frontend enter to weird states. Such as duplication of events and data.

The last couple of commits here fixes this problem by closing the socket connection but not clear out `this.conn` so it can still try and reconnect

Should resolve https://mattermost.atlassian.net/browse/MM-28715

### CODE REVIEW

**Comment by sudheerDev** [comment]
This is mostly going in for 5.29v if we are changing from tik tok release but for now adding 5.30v label

**Review by Willyfrog — APPROVED** [review]

**Review by deanwhillier — APPROVED** [review]

**Comment by emilyacook** [comment]
@jgilliam17 I think this is waiting on your review?

**Comment by jgilliam17** [comment]
Thanks @emilyacook for bringing this to my attention. There was still an issue with socket reconnect, previously discussed in channel with Sudheer, that needed to be resolved before QA could test. 
@deanwhillier I will add `Work in Progress` label in the meantime and queue for team discussion for Monday next week.

**Comment by lindy65** [comment]
Hi @hmhealey - do you know what the status is on this PR? I see the Jira ticket is assigned to you.  (I'm helping to review stale PRs)

//cc @jgilliam17

**Comment by hmhealey** [comment]
I have no idea actually. The previous Server Platform team had taken over message reliability, so we weren't working on it ourselves any more. I'll bring up the ticket for discussion in triage next week to see where it'll end up since I'm not sure if it falls under Web Platform's scope any more.

**Pull request closed without merging**
