### PR TITLE
MM-28278 - Channel header button should have highlighted background when active

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- `style--none` was preventing plugin channel header buttons from having a highlighted background when active.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-28278

#### Related Pull Requests
- none

### CODE REVIEW

**Review by asaadmahmood — APPROVED** [review]

**Review by crspeller — APPROVED** [review]

**Comment by cpoile** [comment]
@lindalumitchell Do you think this requires QA review? It's a styling change for plugin channel header buttons.

**Review by hmhealey — APPROVED** [review]

**Comment by amyblais** [comment]
@cpoile Linda is off until Tuesday, maybe another QA can take a look.

**Comment by cpoile** [comment]
Thanks @amyblais.
@prapti could you give an opinion whether this needs QA, and if so who is in charge of this area?  Thank you!

**Comment by prapti** [comment]
@cpoile For UI, style and text changes in the front end, I think the consensus is to also run the PR through a PM in addition to a UX expert (Asaad's already added), and if my memory serves correctly, I think I've asked @wiersgallak in the past for a quick check. Once all the reviews are done, I can do the QA review :)

**Comment by wiersgallak** [comment]
@prapti @cpoile Added Eric Sethna as a PM reviewer.

**Comment by esethna** [comment]
@cpoile can you please help post a screenshot of the active state for the button? If it's following the pattern used by the pinned post button then should be fine

**Comment by cpoile** [comment]
@esethna Sure thing.

Pre change, unactivated:
image

Pre change, activated:
image

Post this PR, unactivated (same), activated:
image

Same as pinned post:
image

**Review by esethna — APPROVED** [review]
Thanks!

**Review by prapti — APPROVED** [review]
The incident response plugin button has a highlighted background when active. Tested in 2 light and 2 dark themes.
Approving this PR before Asaad and Christopher since it's a simple change. If there are more changes after, please assign me for review again. Thank you!

**Comment by cpoile** [comment]
Christopher and Asaad approved, it's just not showing in the rhs for some reason. Going to merge. Thanks everyone!

**Pull request merged**
