### PR TITLE
[MM-45222] Fixing insights header

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
The header shrinks when you navigate to Threads

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45222

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by plant99 — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@furqanmlk could you enable the feature flag for insights on the test server here?

**Comment by furqanmlk** [comment]
> https://mattermost-webapp-pr-10655.test.mattermost.cloud

@matthewbirtch 
Done ✅ 
https://mattermost-webapp-pr-10655.test.mattermost.cloud/pr10655/channels/town-square

**Review by matthewbirtch — APPROVED** [review]
LGTM

**Comment by furqanmlk** [comment]
@BenCookie95 

Header still shrinking on resizing browser 


https://user-images.githubusercontent.com/6909890/177632165-b88d3f17-85c8-4e69-9a5e-7a23cbafe86d.mp4

**Pull request merged**
