### PR TITLE
MM-45494: Edit message history

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
This PR introduces a new feature for users to 
-	see the edit history of their edited messages
-	restore an old version

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/20864
JIRA: https://mattermost.atlassian.net/browse/MM-45494

#### Related Pull Requests

- Has server changes https://github.com/mattermost/mattermost-server/pull/21601

#### Screenshots

https://user-images.githubusercontent.com/37421564/189528414-5afc2363-a227-4cb9-9221-fc19a0ac6631.mov

#### Release Note
```release-note
Give ability to users to see the history of edited messages and restore an old version with current version.
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@sinansonmez, could you please take a look and confirm everything is fine? Have merged the latest master.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
This is great! Some changes I'd like to request. Some of them are design changes, so I apologize for that, but hopefully they aren't big changes for you. I'm updating the Figma file to reflect these changes.

1. In the Edit History RHS, when a row is collapsed, can we make the entire row clickable to expand with a full-width hover state rather than just the small chevron icon button? Then there won't need to be a hover state on the chevron anymore once that change is made.

2. Can we tighten up the space between the chevron and the date? Looks like you've got a gap of 16px, but it should be 4px

3. For the 'Current Version' tag, can we place that to the right of the date instead of under it? It takes up unnecessary vertical space. Sorry we didn't catch this in the design phase (this was done by another designer). I'd prefer it to display like this as it takes up much less vertical space and doesn't need to sit on its own line.

image

6. Doing the above may resolve this, but the row that has the `Current Version` tag seems like it gets vertically misaligned with the chevron on the left compared to the other rows.

4. Once we've done that, can we also add some 8px of space above the message header (avatar and user name) so it is a bit more separated from the date?

5. Also, the message text content seems like it's getting extra padding on the left and right that is causing it to be indented when it should be left-aligned with the avatar above it.

7. For the tooltip on the restore icon can we make it say 'Restore this version'?

8. For the Restore this message modal, can we make the title "Restore this version"
9. Also in the confirmation modal, can we use the same layout for the message that appears in the history RHS and show the avatar and username? And lets give it a padded container with a border so it doesn't feel as awkward to be left-aligned. I've updated the [figma file](https://www.figma.com/file/bP6bGPN9MuF13swtwAxd3I/MM-45494-Undo-edit-message?node-id=263%3A123572) with this change 
10. In this modal, can you also increase the space above the buttons

image

11. For the 'Restored message' toast that appears in the bottom-right, can we add 8px of padding on the left side so the icon is not so close to the left edge?

Let me know if you have any questions about these changes. I can do another pass once the above is done. Thanks!

**Comment by AshishDhama** [comment]
@sinansonmez ^

**Comment by sinansonmez** [comment]
@matthewbirtch This is ready for another round of review. Please let me know if I missed anything.

I have one info and one question for you related to restore button
- **Question**: Should restore button have any hover state? If yes, could you please provide details?
- **Info**:As you can see below, the tooltip is moved to the left side of the restore button. As the button is very close to the right edge, the tooltip is misaligned when put under the button. Similar to `expand the right sidebar` tooltip below. 
image

image

**Comment by matthewbirtch** [comment]
> @matthewbirtch This is ready for another round of review. Please let me know if I missed anything.
> 
> I have one info and one question for you related to restore button
> 
> * **Question**: Should restore button have any hover state? If yes, could you please provide details?
> * **Info**:As you can see below, the tooltip is moved to the left side of the restore button. As the button is very close to the right edge, the tooltip is misaligned when put under the button. Similar to `expand the right sidebar` tooltip below.
> 
> image
> 
> image

Thanks for the call outs @sinansonmez. Apologies for not providing all the states needed here. I put together a Frame in Figma that should give you all the states you need. You'll notice this hover state for when a row is collapsed is a bit different (uses the 8% center channel bg instead).

For the hover state of the "Restore this version" button, it should behave like a regular Icon Button with an 8% center channel bg color, and the icon color should also adjust to 72% opacity on hover.

Let me know if I've missed anything https://www.figma.com/file/bP6bGPN9MuF13swtwAxd3I/MM-45494-Edit-Message-History?node-id=625%3A141691&t=PnTZZczRxRd7dO1i-4

As for the tooltip, I'm fine with where you've got it positioned.

**Comment by matthewbirtch** [comment]
thanks @sinansonmez. It looks like you resolved everything that was called out previously. The only thing I'm seeing now is some glitchiness with expanding and collapsing the rows sometimes. It's hard to reproduce consistently, but this is what I'm seeing:

https://user-images.githubusercontent.com/2040554/206785043-8ea6d804-b7ec-4189-a0e6-dc6ae66561af.mov

**Comment by sinansonmez** [comment]
@matthewbirtch I couldnt reproduce the issue. However I did some minor changes which might fix the issue. Could you please give another look?

**Comment by matthewbirtch** [comment]
> @matthewbirtch I couldnt reproduce the issue. However I did some minor changes which might fix the issue. Could you please give another look?

Definitely seems better @sinansonmez, thanks!

One final thing I just noticed: If I have the 'Edit History' RHS open while editing it doesn't seem to add a new row or show the proper history trail. It only seems to update the 'Current row', but doesn't adjust the rest accordingly. If I close and re-open it though, it seems to update properly.

**Comment by sinansonmez** [comment]
@matthewbirtch thanks. I fixed the issue on editing when RHS is open. Please give another look

**Comment by jgilliam17** [comment]
Thanks @sinansonmez 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/297158-bba2fd5-onprem-ent-webapp-pr-11555-mm-ee-test:bba2fd5/mochawesome.html) - looks good, no PR related failures when compared to [master](https://mattermost-cypress-report.s3.amazonaws.com/296804-onprem-ent-master-mm-ee-test:test/mochawesome.html)
2 tests failing due to `#user-profile-popover`, also fail on other prs. I'll create a follow up ticket for that and link here if you'd like to pick it up
Help Wanted ticket created: https://mattermost.atlassian.net/browse/MM-50295
Screen Shot 2023-02-02 at 3 49 54 PM
Screen Shot 2023-02-02 at 4 19 32 PM

**Comment by sinansonmez** [comment]
Thanks @jgilliam17 I commented on the issue to assign it to myself. 

I suppose my 2 PRs (https://github.com/mattermost/mattermost-server/pull/20945 and https://github.com/mattermost/mattermost-webapp/pull/11069/) are ready to be merged.

**Comment by jgilliam17** [comment]
Thanks for picking up another Help Wanted ticket @sinansonmez 
Can you please rebase branch with master and fix conflicts. 
@AshishDhama please let me know if anything else needs to be done before merge of all 3 PRs? Thanks 🙂

**Review by jgilliam17 — APPROVED** [review]

**Comment by sinansonmez** [comment]
Thanks @jgilliam17 i just updated branches and fixed conflicts in my PRs. Ashish just need to pull the changes

**Review by jgilliam17 — COMMENTED** [review]
Suggesting test case ID

**Comment by AshishDhama** [comment]
closing this in favour of original

**Pull request closed without merging**
