### PR TITLE
Fix nested a tags in Marketplace labels

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Labels might contains `a` tags. Hence, the `a` tag linking to the plugins homepage may to contain the labels.

I've also remove an unused prop in 1370a20bf1a815f73756e85b7338e65c280ed883.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28948

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by agarciamontoro — APPROVED** [review]
:tada:

**Comment by hanzei** [comment]
@DHaussermann Take your time with reviewing this PR. It's a nice to have to 5.29. Test steps are in the JIRA ticket.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- The issue shown in the console no longer occurs
- No issues with labels
- Briefly regression tested for functional issue in UI
- Checked browser and desktop

**Pull request merged**
