### PR TITLE
MM-20414: Migrate 'components/channel_header_mobile/channel_info_button' module and associated tests to TypeScript 

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR migrates 'components/channel_header_mobile/channel_info_button' module and associated tests to TypeScript 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/16159
JIRA: https://mattermost.atlassian.net/browse/MM-20414

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
🆗  It looks good to me. Thank you

**Review by jgilliam17 — APPROVED** [review]
Thanks @sinansonmez 
Tested, looks good to merge.
[E2E report](https://automation-dashboard.vercel.app/cycles/d34bf922-e667-472c-88eb-b4d47a3d4500) - no PR related failures.

**Pull request merged**
