### PR TITLE
MM-T307 added test for canceling a file upload

### PR DESCRIPTION
**Pull request by JeremyShih**
#### Summary

cancel a file upload

#### Ticket Link

[MM-T307](https://automation-test-cases.vercel.app/test/MM-T307)
mattermost/mattermost-server#15259

### CODE REVIEW

**Comment by saturninoabril** [comment]
@JeremyShih Thanks for updating. Ping me once ready for another review.

**Comment by JeremyShih** [comment]
Sure.
After applied the suggested change, cypress could not get the cancel icon anymore.
I tried but did not figured it out by Monday.

**Comment by JeremyShih** [comment]
> Hi @JeremyShih , I tried running the test locally but am getting the following error (see image).
> 
> Also, please fix lint issues,
> https://circleci.com/gh/mattermost/mattermost-webapp/150711?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> 
> Screen Shot 2020-08-24 at 9 54 21 AM

That's because the file name does not match in suggested code. I have fixed that but got stuck on other issue now.
Lint issues will be fixed after that.

**Comment by saturninoabril** [comment]
@JeremyShih You'll need to stub the network request for `/api/v4/files` endpoint so that the `huge-image.jpg` will stay in "processing" state, by:
```javascript
const options = {method: 'POST', url: '/api/v4/files'};
cy.server();

// # Stub response of /files endpoint 
cy.route({...options, response: {client_ids: [], file_infos: []}});

// # Post an image in center channel
const hugeImage = 'huge-image.jpg';
cy.get('#centerChannelFooter').find('#fileUploadInput').attachFile(hugeImage);
...
```

Then release it so that the next file upload will work as usual by:
```javascript
// # Release response of /files endpoint 
cy.route({...options});

// # Post a different file in center channel
const textFile = 'long_text_post.txt';
cy.get('#centerChannelFooter').find('#fileUploadInput').attachFile(textFile);
...
```

**Comment by saturninoabril** [comment]
@JeremyShih Let me know once ready for review.

**Comment by JeremyShih** [comment]
Sure. Thanks to your help the first item works now.

**Comment by JeremyShih** [comment]
@saturninoabril I think the code is ready for another review. Local test looks good now.
Should I squash the comments?
And the CI build failed at prepare-docker-build. How to trigger re-build?

**Review by saturninoabril — APPROVED** [review]
@JeremyShih Awesome, thank your for your contribution!

**Comment by saturninoabril** [comment]
btw, no need to squash. It's all good.

**Comment by JeremyShih** [comment]
Good to know that. Thanks for your help!

**Pull request merged**
