### PR TITLE
MM-41152: fixes RHS results when changing screens

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Currently upon searching if you switch to the files tab prior on
changing RHS_STATE to e.g pinned posts, you'll continue to see file
results in RHS.

This commit fixes that by resetting the search type (messages, files)
upon changing RHS_STATE to another screen.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41152

#### Release Note

```release-note
Fixes RHS search results when changing screens from file results to any other
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Looks good to me.
Just out of curiosity are the current dependencies enough to clear back to search type?

**Comment by koox00** [comment]
> Looks good to me. Just out of curiosity are the current dependencies enough to clear back to search type?

AFAICT yes, those are sufficient. 

PS: going back to search results would mean one those changed to `false`

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by jgilliam17** [comment]
Thanks @koox00 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/110310-e7a05db-onprem-ent-webapp-pr-9712-mattermost/mm-ee-teste7a05db/mochawesome.html) looks good, no PR related failures.

When manually testing, I am still seeing a similar issue to the one described in the ticket. On the attached image we are not clearing search field ( is this intended?) when switching to pinned posts and a file(s) continues to display on the RHS. 

Screen Shot 2022-02-01 at 2 41 07 PM

**Comment by koox00** [comment]
Oh, yes you are correct... I was testing it "wrong".
I was searching for a term, then selecting the files tab in the search results, then clicking saved posts.
Which also was a broken case!
Fixed the other cases as well, thanks @jgilliam17!!

**Comment by koox00** [comment]
@esethna, currentlywhen we click on mentions on global header we display the mention keys in the search input.
Do we mind if we don't display them?

**Comment by jgilliam17** [comment]
Thanks @koox00 
Tested, looks good to merge.
- Verified RHS results clear when switching between search results, mentions, pinned and saved posts. 
Please ping me here for re-test if changes are requested.  🙂

**Review by jgilliam17 — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]
🆗  It looks good to me. Thank you

**Comment by esethna** [comment]
> currently when we click on mentions on global header we display user's mention keys in the search input.
Do we mind if we don't display them?

@koox00 that's totally fine if we don't show them (in fact it has caused confusion in the past)

**Review by michelengelen — APPROVED** [review]

**Pull request merged**
