### PR TITLE
Remove displayDate method from utils.jsx

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Fixes [mattermost/mattermost-server#12243](https://github.com/mattermost/mattermost-server/issues/12243)
#### JIRA
https://mattermost.atlassian.net/browse/MM-18581

### CODE REVIEW

**Comment by sowmiyamuthuraman** [comment]
@Willyfrog Thanks for the input. I have made the changes and amended to the same commit.

**Comment by Willyfrog** [comment]
looking better, but I've run it and it's showing like this. Can you take a look into that?
Screenshot 2019-09-26 at 17 59 10

**Comment by cpanato** [comment]
the fork repository was removed.

**Comment by sowmiyamuthuraman** [comment]
> the fork repository was removed.
@cpanato can i close this pr and reopen it again?

**Comment by hmhealey** [comment]
@cpanato Is that going to cause any issues for the build system? GitHub isn't complaining, so I think we can still merge this fine as long as no further changes are needed to it

**Comment by cpanato** [comment]
we can merge that, i just make a note that the head repo is deleted

**Comment by Willyfrog** [comment]
adding bob to do the QA

**Pull request merged**
