### PR TITLE
Migrate String Refs to Functional ones

### PR DESCRIPTION
**Pull request by ShajithaMohammed**
#### Summary
Replace this.refs with React.createRef

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15842
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29403

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by nevyangelova** [comment]
Interesting that the typescript check didn't pick those up 🤔 otherwise LGTM. Thanks @ShajithaMohammed

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @ShajithaMohammed

**Review by nevyangelova — COMMENTED** [review]
@ShajithaMohammed let us know if you need any assistance with this PR :)

**Comment by hmhealey** [comment]
Thanks for any work you've done on this, @ShajithaMohammed.

Feel free to let us know if you'd still like to work on this issue, but otherwise, we're going to open it back up for others to work on.

**Pull request closed without merging**
