### PR TITLE
Landing page for deep linking to native app new

### PR DESCRIPTION
**Pull request by csduarte**
NOTE: @esethna @enahum The original PR got closed and contains the history of revisions and conversations that we had: https://github.com/mattermost/mattermost-webapp/pull/208

These changes add a new route vault to a landing page that allows to fire the protocol to native client if installed or give the user the option to download the native app or redirects to the webapp after 5 seconds.

This is an example if the native app is installed and the protocol is successfully registered:
<<image>>

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-8255
https://github.com/mattermost/desktop/issues/628

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

mm_landingpage

### CODE REVIEW

**Comment by esethna** [comment]
FYI on this, our design team has a ticket queued this week for UI updates to the landing page and adding a selector for remembering the choice of opening in browser: https://mattermost.atlassian.net/browse/MM-11443

**Comment by dmeza** [comment]
@esethna here is the PR to `Change link to redirect email notifications to landing page` that would complete these changes:
https://github.com/mattermost/mattermost-server/pull/10268

**Comment by esethna** [comment]
@dmeza would you be open to jumping on another call about this PR next week? 

Design team had some thoughts about an update to the landing page UX/UI: https://projects.invisionapp.com/share/RAQJY1U68NE#/screens/347225775_Title_-_Deep_Link_Landing_Page

 We would like to chat through if there are specific limitations technically as it is a bit of a deviation from the UX proposed in this PR.

**Comment by csduarte** [comment]
The designs look nice, but really are hard on custom branding. Please consider a good way to swap our images/names.

Is it possible to accept the PR without a direct usage, the functionality is there and is very much needed in the platform.

**Comment by dmeza** [comment]
Hey @esethna here are some comments. I think it would be easier to understand if get in a call to discuss and decide changes:

> It seems to redirect to Mattermost in browser after the landing page is open for a few seconds.
It was thought as a way to get the user to the message result even if they don't take an action. It can be removed if the flow doesn't make sense.

> What's expected when the user clicks "Download and open in Mattermost"? Right now I'm getting a "Team not Found" page
To make testing easier I added a hack to always go to the production desktop domain (pre-release). In the server you're testing it might be that the team or channel is not available in pre-release. I can remove it and you can do full testing with it.

> Opening in desktop from the pop-up dialog doesn't seem to do anything - no response after clicking Open Mattermost.
I'd like you to show me when it's happening.

> 4. Is a system pop-up page necessary or can we get them to click the "View In Desktop" button here. We looked at some other apps and I recall finding some that did not launch a system dialog from the landing page.
It will need to happen since you're telling the OS to allow access to that protocol. That's not optional.

> 5. Related to above, if we can eliminate the system pop-up dialog, can we have a "Remember my preference" button on the landing page itself that would apply to the "View in Mattermost" or "View in Browser" buttons?
The view on the browser button can be set to always to de redirect and not go to the protocol.

> 6. Can we detect if the user has Mattermost installed and change the landing page UI if so? ie this page if they do, this page if they don't. Notice the buttons are different.
The browser can not detect it since it's an OS installed application.

Let me know if you'd like to discuss.

**Comment by esethna** [comment]
Thanks @dmeza, get on a call to discuss. Are you available 11am San Fran time on Monday?

**Comment by dmeza** [comment]
@esethna yes, that sounds good. I'll be available.

**Comment by esethna** [comment]
Thanks for the meeting yesterday @dmeza, to summarize:

1. Created a ticket for us to address the flow that we discussed: https://mattermost.atlassian.net/browse/MM-14557

2. If you can please follow up on this PR to 
  - Remove the hack to pre-release
  - Remove the redirect to webapp from the landing page

3. As discussed please inform on mobile (iOS and Android) landing page flow so we can adjust the designs, ie:
  - Can we go straight to app from email notifications without showing landing page?
  - If not, how does the detection and app launching work on mobile from the landing page

**Comment by dmeza** [comment]
Sorry for the delay @esethna. The changes for #2 are done and pushed. It had a build error but it's fixed now. After testing I realized why it goes directly to open the url with the protocol, it's the way to detect if it's installed or not, that means that's the flow that should be kept.

For Android:
- If the mobile app is not installed it opens the landing page and follows the same process.  
- If it's installed, it does give the user the option to go directly to the mobile app.

**Comment by hanzei** [comment]
@esethna What is the status on this ticket? Is this ready for review?

**Comment by esethna** [comment]
@csduarte was hoping to get your feedback regarding ease of custom branding in this proposed design:

image
https://projects.invisionapp.com/share/M5RMI6O87SC#/screens/359008499

image
https://projects.invisionapp.com/share/VGRMI62F6BS#/screens/359009765

Note that the image has transparencies so the only requirement is to change the header logo and pick a color for the image background/buttons. Would this be acceptable?

**Comment by csduarte** [comment]
@esethna sorry for the delay, I think it's good. So long as there is any hardcoded branded imagery, it's fine.

**Comment by hanzei** [comment]
Hey @esethna,

What are the next steps for this PR?

**Comment by esethna** [comment]
@hanzei we need to get final approval on the designs then see where we can schedule this in for development. No immediate updates, we can change this to a WIP PR

**Comment by esethna** [comment]
FYI we will be picking this back up now internally.

**Comment by devinbinnie** [comment]
Closing in favour of https://github.com/mattermost/mattermost-webapp/pull/4455

**Pull request closed without merging**
