### PR TITLE
MM-40447: fixes minor styling issues in suggestions

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Fixes some styling issues in auto suggesting items upon searching.

- Avatar in user auto complete has no space from text.
- Channel icon and name are not center aligned.
- Hovering a date and selected date are not circles but ellipses.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-40447

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2021-12-06 at 4 29 35 PM|Screenshot 2021-12-06 at 4 30 09 PM|
| Screenshot 2021-12-06 at 2 03 27 PM | Screenshot 2021-12-06 at 2 01 35 PM |
|Screenshot 2021-12-06 at 2 06 27 PM|Screenshot 2021-12-06 at 2 06 55 PM|

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — APPROVED** [review]
Looks much better. Thanks for making these tweaks @koox00!

**Comment by jgilliam17** [comment]
Thanks @koox00 
Smoke tested and changes look good, spacing and date circles are as expected.
I also ran E2Es, but see an unusually large number of failures and skipped tests. 
https://automation-dashboard.vercel.app/cycles/734ab542-47e2-47a4-ae9f-4103483c0802
I'll re-run tomorrow after update and see if it looks better. Failures appear to be cypress related though, server failed to start on most failed tests.

**Comment by amyblais** [comment]
@deanwhillier @nevyangelova FYI, code freeze for v6.2 is coming this Thursday, please help review by then if you can.

**Review by nevyangelova — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Here's the latest E2E report - looks good, no PR related failures.
https://automation-dashboard.vercel.app/cycles/0c80a3d1-c5c4-4f05-88f6-fd05b25d3f84

**Review by larkox — APPROVED** [review]
LGTM. Just curious how this came to be.

**Comment by koox00** [comment]
> LGTM. Just curious how this came to be.

@larkox the avatars issue was caused when we added [status indicator to the mentions provider](https://github.com/mattermost/mattermost-webapp/commit/1095a5e43b3a7590e4a1929f9ad3f9012d9d4ee5#diff-97c449b27fb65af4422a58a4a2dad3dd1ab1d8b05e8c674ed63ff7d2312054d4),
for the others I didn't search, but I guess the date picker since the global header, 
and the channel one I think is there long time now.

**Pull request merged**
