### PR TITLE
Cypress/E2E: Fix tutorial header verification

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- This fixes the issues related to tutorial header verification
- There are still further issues with `finish_tutorial_spec` which will be addressed in a separate PR

#### Ticket Link
NA - master only

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]

**Review by srkgupta — CHANGES_REQUESTED** [review]
Hi @josephbaylon 
The tests are failing for me because it does not shows up the text "Welcome to Mattermost". Instead it still shows the older welcome screen. Can you please check and let me know if this requires some additional changes in the config.json file (or) something else which I am missing. I am on the latest master. 

Screenshot 2020-10-12 at 6 15 20 PM

**Comment by saturninoabril** [comment]
Such test requires a license with "Cloud" feature. Our CI runs with "Cloud" feature license. I wonder if we should provide different tests for with and without a license, to cover both cases.

**Comment by srkgupta** [comment]
Should we add dynamic assertions. If Cloud license is present then verify one welcome screen. If it's not present, then verify different welcome screen

**Comment by josephbaylon** [comment]
@mattermod `/update-branch` doesn't seem to work for me. Please take a look. Thanks.

**Comment by josephbaylon** [comment]
@srkgupta Are you still having issues even with cloud license? Let me know. Thanks

**Comment by josephbaylon** [comment]
@srkgupta @saturninoabril Added cloud license check on affected files

**Review by srkgupta — CHANGES_REQUESTED** [review]
Hi @josephbaylon 
I am seeing some failures with Cloud License uploaded. Can you please re-run and check. Here are some errors I see. 

Screenshot 2020-10-13 at 9 27 27 PM

Screenshot 2020-10-13 at 9 36 02 PM

**Comment by josephbaylon** [comment]
@srkgupta I reverted the ones that didn't really need the cloud feature license. As for `finish_tutorial_spec`, that has known issues as indicated in summary and will be addressed in a separate PR

**Comment by josephbaylon** [comment]
@srkgupta If you're still getting failures locally wrt to cloud license, I'll close this PR for now since this may require bigger changes.

**Review by srkgupta — APPROVED** [review]
Thanks @josephbaylon. Tests are working fine now.

**Comment by srkgupta** [comment]
> @srkgupta If you're still getting failures locally wrt to cloud license, I'll close this PR for now since this may require bigger changes.

Note @josephbaylon: There are some tests which will fail on the regular enterprise instance (non-cloud license), i.e. tests using the method `signupAndVerifyTutorial`

**Comment by josephbaylon** [comment]
@srkgupta I reverted the helpers as well as that seem to need more changes on affected files.

**Review by saturninoabril — APPROVED** [review]

**Pull request merged**
