### PR TITLE
PLT-8018: Bundled jira plugin

### PR DESCRIPTION
**Pull request by ccbrown**
#### Summary
Removes the old settings and add a "prepackaged" indicator:

screen shot 2017-11-29 at 9 12 04 pm

Also added the plugin name. The mock on this ticket seems to be confusing the name and id. The name should probably be the most prominent thing and the id should be the least (when a name is defined). Just left them both there for now though.

Added the plugin version too as it's just really useful to see.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-8018

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has server changes (https://github.com/mattermost/mattermost-server/pull/7920)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
1) Maybe I'm not testing it correctly, but I don't see the JIRA plugin anywhere.

image

2) I didn't know we supported both an ID and a name, but I guess that makes sense. I'll think about this when I test it

**Comment by ccbrown** [comment]
1. It's because of the [bug](https://mattermost.atlassian.net/browse/PLT-8254) you files and the permissions error. I'm about to fix the permissions error on that instance manually now.

**Comment by ccbrown** [comment]
Gotta rebase this too since it depended on another PR.

**Comment by ccbrown** [comment]
@jasonblais Alright, sorry it took so long, but this Spinmint server should be good to test!

**Comment by jasonblais** [comment]
@ccbrown Few comments:

1) Comparing the webhook integration and plugin settings pages side-by-side:
 - title should be in capital letters
 - if the plugin is disabled, the "Regenerate" button should be disabled
 - if the plugin is disabled, the "Search" box should be disabled
 - setting titles should have a colon, `:`, at the end
 - "Search" box missing "Search" input hint
 - the formatting of the white banner below settings doesn't match
 - the webhook URL doesn't pick up the secret nor the site URL
 - `YOURSITE.COM` should say `SITEURL`; `ABOVESECRET` should say `WEBHOOKSECRET`

^I realize not all of this functionality is available with the current plugin settings schema implementation, but pointing out the differences.

image

2) On the plugins management page, can we reorder the fields to
  - `Name: <name> - **pre-packaged**`
  - `Description: <description>`
  - `ID: <id>, Version: <version>`

I agree that ID should have lower priority compared to the name. Also, We can combine the ID and the version in the same line to reduce vertical space taken by a single plugin.

3) Question: I tried to use the following URL for the JIRA webhook, but wasn't able to get any posts to fire. Server logs showed no messages.

https://32zanxm6u6.execute-api.us-east-1.amazonaws.com/dev/proxy?url=https%3A%2F%2Fi-0354977f3ffb3ec49.spinmint.com/%3A80%2Fplugins%2Fjira%2Fwebhook%3Fsecret%3DWb6w15YWJ9WeBooebLHslgr2KN1AajI_%26team%3Dpr380%26channel%3Dtown-square

**Comment by ccbrown** [comment]
@jasonblais 

1. Yeah I'll change the things are easily doable, but most of these should probably get a separate JIRA ticket.

2. Sure thing!

3. It's because that server didn't get this fix: https://github.com/mattermost/mattermost-server/pull/7929 It'll work again after I update the PR (which I'll do before Monday).

**Comment by ccbrown** [comment]
* [x] Page header now shows the plugin name (capital "JIRA" in this case), not the id.
* [x] Setting labels now have a colon suffixes.
* [x] User settings now default to having the "Search" placeholder text.
* [x] Rearranged plugin fields.

The white banner formatting and URL are defined in the JIRA plugin repo ([here](https://github.com/mattermost/mattermost-plugin-jira/blob/master/plugin.yaml#L23)). I can't really make it exactly the same as it was since it's now defined by markdown rather than HTML, but if you have any markdown suggestions for it, it's trivial to change (You could probably put in the PR yourself.).

Everything else probably needs separate tickets.

**Comment by ccbrown** [comment]
@jasonblais I was wrong; you won't be able to get this test server to post any messages until [this other PR is merged](https://github.com/mattermost/mattermost-server/pull/7934). But this PR won't have any effect on the message posting.

You can review the other UI changes I made to the console on it though.

**Comment by jasonblais** [comment]
@ccbrown I created a new spinmint as I saw a recent commit, and I think that wiped out the JIRA plugin because of the permissions issue, sorry. Can you help with that?

**Comment by ccbrown** [comment]
@jasonblais Done.

**Comment by jasonblais** [comment]
1) Thanks for the changes
 - Can you change `YOURSITE.COM` to `YOURSITEURL` or `SITEURL`? Site URL is more obvious + the domain may not have a .com in it.
 - For the white box, what's the formatting if we use code blocks? (three backticks, ```)
 - For disabled settings when plugin not active, I don't think this is necessary. See 4 below for more.
 - For automatically adding the Site URL and secret to the webhook URL, created a ticket: https://mattermost.atlassian.net/browse/PLT-8285

2) Looks good
3) Okay not to test with this PR since there are no functional changes

4) Is the Enable/Disable setting useful anymore?

My understanding was this toggles the activate/deactivate state, but that is not actually the case. I think we should just remove the enable/disable setting for now given the admin has to not only activate the plugin but also enable it from the settings.

**Comment by ccbrown** [comment]
@jasonblais 

1. I changed the placeholders in the other repo: https://github.com/mattermost/mattermost-plugin-jira/blob/master/plugin.yaml#L23.

4. Probably not, but that's also not part of this PR. That would be a change to the plugin repo as well.

**Comment by jasonblais** [comment]
1. Okay, thanks

4. Do I create a ticket for this?

**Comment by ccbrown** [comment]
@jasonblais Sure, that's fine.

**Comment by jasonblais** [comment]
4 - ticket:  https://mattermost.atlassian.net/browse/PLT-8286

Not much otherwise, so this should be good to

**Pull request merged**
