### PR TITLE
Fix default offline status change on page load

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Recently its been reported that navigating to system console or our other apps, as well as refreshing the page triggers an unwanted status page. I see that we still have a websocket event for statuses, but currently i can't think of a use case to have the statuses controlled by the websocket. Removing this event gives us more control and solves the bugs mentioned.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40064

#### Release Note

-->
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
We can't remove all status handling from the websocket since we do use those sometimes for other users' statuses, but good find that it's probably caused by the websocket.

I tried reproducing your findings, and I noticed that the websocket actually disconnects when switching from the system console to web app (as well as between Channels and Boards). That's definitely not what we want. This might even be a bit of a race condition since it appears that, at least sometimes, we set the current user to online last which should mean this bug doesn't repro in those cases, but it's inconsistent.

I guess the ideal fix for this would be to ensure the websocket stays connected when switching pages, but that might be outside the scope of this. I wonder if maybe instead of that, we stick with something more like what you have here, but just ignore our own status changes coming from the websocket instead of removing all handling of statuses from the websocket? I'd want to double check that that doesn't break other behaviour like manually setting the status on one tab properly propagating that to other tabs

**Comment by nevyangelova** [comment]
@hmhealey that's a good point! I added the check but can't test navigating the system console as something is breaking on master currently?

**Comment by hmhealey** [comment]
Are you still seeing that? I'm able to view the System Console on the PR test server. I do seem to be set as offline permanently now though. Hopefully we aren't using the websocket for requesting the current user's status normally though

**Comment by nevyangelova** [comment]
> Are you still seeing that? I'm able to view the System Console on the PR test server. I do seem to be set as offline permanently now though. Hopefully we aren't using the websocket for requesting the current user's status normally though

@hmhealey i do see the change again. I tested locally and even if you remove any code from the function, it still changes the status 🤯 only by removing the case itself is the status being kept consistent. I probably need to investigate further

**Comment by nevyangelova** [comment]
@hmhealey this turned out to have a super easy fix, it was setting the default status to offline every time the component was rendered because the prop was set to OFFLINE by default

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
@nevyangelova Could you update the title of this PR to match what we're actually changing now?

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, looks good to merge.
- Verified current user status is preserved when visiting System Console and coming back to team.
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/219236-90d4b17-onprem-ent-webapp-pr-10414-mattermost/mm-ee-test90d4b17/mochawesome.html)- no PR related failures.

**Pull request merged**
