### PR TITLE
MM-377220 Fix theming and stying of Add Users to Channel modals 

### PR DESCRIPTION
**Pull request by hmhealey**
In January, we updated the styling of the Add Users to Channel modal to more closely match the Channel Switcher (#7172). These styles didn't take into account the fact that the modal existed in the System Console as well though, so in March, we fixed that but broke the styles of the dropdown and close button outside of the System Console (#7696). A couple weeks ago, we attempted to fix the appearance of the close button, but that entirely broke the styling of the modal in the System Console (#8366).

With all that said and done, I think I've fixed all the existing issues around that modal without reintroducing any other bugs. I also split up the CSS a bit better beetween the Add Users to Channel modal and Channel Switcher since they shared CSS in a way that was causing them to break each other. There's a video below going through both modals in light and dark themes to ensure they look correct.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37220

#### Screenshots
https://user-images.githubusercontent.com/3277310/126688729-6894cd4e-0925-432d-9b77-5f82da63dcf4.mov

#### Release Note

```release-note
Fixed appearance of Channel Switcher and Add Users to Channel modals
```

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
-Verified theming of Add member to channel modal and also same modal in system console. Channel switcher modal - no changes, as before.

**Comment by amyblais** [comment]
@asaadmahmood Kind reminder for PR review.

**Review by asaadmahmood — APPROVED** [review]

**Pull request merged**
