### PR TITLE
[MM-38154] - Webapp: Change Getting Started/Tips & Next Steps to be it's own view rather than overlay on active channel

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR makes the next steps view component accessible on it's own route `/:team/tips`

#### Ticket Link
[MM-38154](https://mattermost.atlassian.net/browse/MM-38154)

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Comment by stevemudie** [comment]
@AGMETEOR **Getting Started** stands alone without any channel selected when it's selected but it's also not the first thing I see when logging in for the first time but it should be right?

**Comment by AGMETEOR** [comment]
> @AGMETEOR **Getting Started** stands alone without any channel selected when it's selected but it's also not the first thing I see when logging in for the first time but it should be right?

@stevemudie I have fixed that issue. Thanks for pointing it out.

**Review by stevemudie — APPROVED** [review]
Looks good @AGMETEOR!

Thank you for addressing the issue I noticed.

**Review by neallred — APPROVED** [review]
LGTM. Nice job changing e2e tests! FWIW queued the whole suite manually, and the [results](https://mattermost-cypress-report.s3.amazonaws.com/102666-514735c-onprem-ent-webapp-pr-9604-mm-ee-test:514735c/mochawesome.html) don't seem to show failures related to these changes.

**Comment by AGMETEOR** [comment]
@pablovelezvidal gentle ping on this

**Review by pablovelezvidal — APPROVED** [review]
thanks @AGMETEOR, LGTM :shipit:

**Pull request merged**
