### PR TITLE
Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 566 

### PR DESCRIPTION
**Pull request by prazolpp**
#### Summary

This pr simply migrates the changeCSS() to CSS variable in utils/utils.jsx. 
It removes the changeCSS() in line 566 and adds a css variable in the _team-sidebar.scss  file. 
There are also some trivial changes like replacing "" with '', and adding 0s as first digits before decimals (eg. .15 to 0.15)

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15876

### CODE REVIEW

**Comment by nevyangelova** [comment]
Hey @prazolpp thanks for this! It seems that the change that removes the `changeCSS()` function was not committed? Can you double check that?

**Comment by prazolpp** [comment]
> Hey @prazolpp thanks for this! It seems that the change that removes the `changeCSS()` function was not committed? Can you double check that?

Opps! sorry about that and just fixed it.

**Review by nevyangelova — APPROVED** [review]

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @prazolpp! :confetti_ball:

**Pull request merged**
