### PR TITLE
Cypress/E2E: Promote tests with 23 TM4J test cases

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Promote tests with 23 TM4J test cases

### CODE REVIEW

**Review by furqanmlk — APPROVED** [review]
Looks good 👍

**Review by prapti — COMMENTED** [review]
Hi @saturninoabril, these tests have not been passing in the last 5 runs, especially the user management tests that were failing throughout last week. Are we sure we want to promote these tests right away?

**Comment by saturninoabril** [comment]
Thanks for looking Prapti! If you're referring to MM-T942 and MM-T943, then you're right, they had 2 recent passing tests only. Please let me know if I missed specific test that you'd like to point out. But the rests from Bots and User management have been passing for more than 5 already since I fixed those (https://github.com/mattermost/mattermost-webapp/pull/7362, https://github.com/mattermost/mattermost-webapp/pull/7364), which happened to run as well in cloud and prod (see screenshot). Sorry for the cutting corner but yes, I'd like to promote those into production and I will take a closer look until this week where I'd do follow up fix or demote as last resort. I'm hoping to increase Cypress production tests as much as possible since we're very much behind either in promoting a stable or fixing a broken test.
Screen Shot 2021-01-27 at 3 41 15 PM

**Review by josephbaylon — APPROVED** [review]

**Review by prapti — APPROVED** [review]
Yeah, that sounds good. Cleaning it up as we go and keeping an eye on them sound like a good idea.
Thanks Saturn! Approving.

**Pull request merged**
