### PR TITLE
MM-44863 - update trial details in product menu

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR changes the style and the text of the menu cloud trial call to action

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44863

#### Related Pull Requests
[mm-server](https://github.com/mattermost/mattermost-server/pull/20534)

#### Screenshots
Admin:
Captura de pantalla 2022-06-20 a las 1 59 43

End user:
Pre-Post trial:
Captura de pantalla 2022-06-22 a las 13 25 12

During Trial:
Captura de pantalla 2022-06-22 a las 13 26 45

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by stevemudie — APPROVED** [review]
Looks good @pvev!

**Comment by pvev** [comment]
@JulienTant @annelieseklein friendly reminder on this one :)

**Review by JulienTant — APPROVED** [review]
Sorry for the delay @pvev! Looks good!

**Comment by marianunez** [comment]
> Mattermost test server with CWS created! 🎉
> 
> Access here: https://mattermost-webapp-pr-10609.test.mattermost.cloud
> 
> Account Type	Username	Password
> Admin	[user-mattermost-webapp-pr-10609@example.mattermost.com](mailto:user-mattermost-webapp-pr-10609@example.mattermost.com)	Cws@10102020

@pvev on this latest version I can't still see the menu entry for end-user. Are you able to see it?

**Review by annelieseklein — APPROVED** [review]
Looks great! Thanks Pablo!

**Comment by pvev** [comment]
> > Mattermost test server with CWS created! 🎉
> > Access here: https://mattermost-webapp-pr-10609.test.mattermost.cloud
> > Account Type	Username	Password
> > Admin	[user-mattermost-webapp-pr-10609@example.mattermost.com](mailto:user-mattermost-webapp-pr-10609@example.mattermost.com)	Cws@10102020
> 
> @pvev on this latest version I can't still see the menu entry for end-user. Are you able to see it?

One of the latest changes I added was to restrict what is shown to the end user to be shown only for trial, which requires accessing the subscription information for end users, which is currently restricted. I am going to validate with @AGMETEOR on what is his strategy to access cloud-subscription information from end-users session.

**Review by marianunez — CHANGES_REQUESTED** [review]
Requesting changes on what was discussed above to also include the end-user (so it can be removed from my review list until ready)

**Comment by pvev** [comment]
@marianunez even after merging https://github.com/mattermost/mattermost-server/pull/20534 the spinwick server is still referencing an old commit.
Captura de pantalla 2022-06-27 a las 16 16 37


BTW, the mm-server branch was named exactly as this branch, but seems to be there is a sync problem with the spinwick server.

Maybe we can fully validate the scenario for end-users after merge?

**Review by marianunez — CHANGES_REQUESTED** [review]
@pvev Based on the original design, the CTA for the end-user should be `View Plans` that opens the Pricing modal instead of `Learn More` see- https://community.mattermost.com/private-core/pl/k75butmhntbg8pqzth7jsqwerh

**Comment by pvev** [comment]
latest changes to end users view plans modal

https://user-images.githubusercontent.com/10082627/177767308-de879eeb-f35b-4907-8b85-657307def1e4.mp4

**Review by marianunez — APPROVED** [review]
Thanks @pvev! Apologies on the delayed review.

**Pull request merged**
