### PR TITLE
Cypress/E2E: Fix tests for cloud

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- exclude tests related to Elasticsearch (ES) for cloud since config related to it is not writable
- remove unnecessary requirement to ES to some specs
- add option to ignore 'api.cloud.get_subscription.error'

#### Ticket Link
none, failed on Cloud test run

### CODE REVIEW

**Comment by saturninoabril** [comment]
@amyblais This PR fixes tests for cloud, specifically for the upcoming March 24 release. I recommend to cherry-pick this into the cloud branch. For your approval, thanks!

**Comment by amyblais** [comment]
@saturninoabril Sounds good.

**Review by prapti — APPROVED** [review]
Looks good. Thank you Saturn!

**Review by josephbaylon — APPROVED** [review]
LGTM

**Review by furqanmlk — APPROVED** [review]
thanks @saturninoabril 
Looks good

**Comment by saturninoabril** [comment]
Done manual cherry-pick - https://github.com/mattermost/mattermost-webapp/commit/acb92f1f7883213a5a59396adac2aefe7dc67ef7

**Pull request merged**
