### PR TITLE
[MM-44648] - Card input not visible in darker modes

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR fixes a couple of theming issues (especially in darker modes) for the stripe card element and generally on the purchase modal

#### Ticket Link
[MM-44648](https://mattermost.atlassian.net/browse/MM-44648)

#### Screenshots
onyx
----
Screenshot 2022-06-07 at 14 09 25

indigo
----
Screenshot 2022-06-07 at 14 09 48

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Comment by stevemudie** [comment]
@AGMETEOR This looks good but I noticed that the card number field stands out in an odd way after you fill in the fields.

At first I thought it might have been because I initially skipped typing in the CVC number but it retained the formatting after I corrected it and moved focus out of the field completely.
Screen Shot 2022-06-07 at 11 35 58 AM
Screen Shot 2022-06-07 at 11 34 38 AM

**Comment by AGMETEOR** [comment]
> @AGMETEOR This looks good but I noticed that the card number field stands out in an odd way after you fill in the fields.
> 
> At first I thought it might have been because I initially skipped typing in the CVC number but it retained the formatting after I corrected it and moved focus out of the field completely. Screen Shot 2022-06-07 at 11 35 58 AM Screen Shot 2022-06-07 at 11 34 38 AM
> 
> **ETA**: I hadn't noticed it before but it has a yellow background in non-dark themes as well. 🤔 Screen Shot 2022-06-07 at 11 47 51 AM

@stevemudie any steps to reproduce? I have failed to reproduce it on my side.

**Comment by stevemudie** [comment]
> @stevemudie any steps to reproduce? I have failed to reproduce it on my side.
@AGMETEOR It looks like it only turns yellow in the background of the credit card field when using the Chrome autofill which is what I often use as I have it loaded with a variety of Stripe test cards.

I'll pass this along and we can address it if needed later.

**Review by stevemudie — APPROVED** [review]
Looks good in both dark modes tested. This is all set @AGMETEOR!

**Comment by amyblais** [comment]
@marianunez @AGMETEOR Is this for cloud freemium release?

**Comment by marianunez** [comment]
> @marianunez @AGMETEOR Is this for cloud freemium release?

Yes, let's cherry pick this to `cloud`

**Pull request merged**
