### PR TITLE
[MM-28680] fix blank page on undefined message

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

A plugin can create an ephymeral post without message (see https://github.com/mattermost/mattermost-plugin-zoom/pull/161), which breaks while trying to generate the aria label. This should prevent the white page

#### Ticket Link

[MM-28680](https://mattermost.atlassian.net/browse/MM-28680)

#### additional notes
I've been unable to recreate the problem, I've added a unit test to recreate the condition.

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by sudheerDev — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thank you @Willyfrog 
I tested on Dylan's server (upgraded with this fix) since it had all the plugins already set.
There is an error and empty post on the screen when you open a channel and start a Jitsi Meeting followed by starting a Zoom meeting in the same channel
No white screen or attempt to launch Zoom on new tab.
Screen Shot 2020-09-23 at 5 22 57 PM

**Review by jgilliam17 — APPROVED** [review]
Thank you @Willyfrog 
Tested, looks good to merge.
- Verified no white screen when zoom fails. ( Thank you again for clarifying the expected 🙂)

**Pull request merged**
