### PR TITLE
Not showing search options tooltip on mobile view

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
In webapp mobile view don't show the tooltip for search options, because the information is already visible.

#### Ticket Link
[MM-16632](https://mattermost.atlassian.net/browse/MM-16632)

### CODE REVIEW

**Comment by jespino** [comment]
This can be reproduced in 5.13 too, this kind of bug is going to be backported too?

**Comment by lindy65** [comment]
Thanks @jespino,

I've tested on the spinwick and confirm that I do not see the tooltip overlapping the Search screen.

However, items in the Main (hamburger) Menu are not the same colors as the theme (Mattermost theme). Is this a result of this PR or a different issue?

image

Also, I did not see a unit test in the "Changed Files" section of this PR. Does one exist?

**Comment by jespino** [comment]
@lindy65 Does not exist, but I going to add one right now.

About the menu colors is not related to this PR at all, I would suggest to create one ticket for that.

**Comment by lindy65** [comment]
Thanks @jespino!

I've filed https://mattermost.atlassian.net/browse/MM-17306 to address the Main Menu issue.

Otherwise this looks good to me, thanks!

**Comment by jespino** [comment]
@lindy65 Added the tests.

**Pull request merged**
