### PR TITLE
MM-11375: fix period in channel purpose issue

### PR DESCRIPTION
**Pull request by michaelkochub**
#### Summary
Remove trailing period from the channel purpose when displaying the formatted message in the channel chat. This message is shown when a channel is first created. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-11375

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Includes text changes

### CODE REVIEW

**Comment by esethna** [comment]
Great! Looks good @michaelkochub, thanks for your contribution! Let us know if there are any other tickets you'd like to take on. And feel free to join our nightly build server with core mattermost devs and contributors if you haven't already :) https://pre-release.mattermost.com/core/channels/tickets

**Comment by esethna** [comment]
Adding @DSchalla here as he had some alternate thoughts on implementation

**Comment by DSchalla** [comment]
Hi @michaelkochub, I looked into the issue before hand and didn't had time to work on the PR sadly, thanks for yours! While the proposed fix would fix the issue itself, I think it might make more sense to fix referenced translation string in the component, with the ID `intro_messages.purpose`:
```
± % grep -r "intro_messages.purpose" | grep -v dist | grep -v vendor
i18n/ja.json:  "intro_messages.purpose": " この{type}の目的: {purpose}",
i18n/ru.json:  "intro_messages.purpose": " Назначение для {type}: {purpose}.",
i18n/pt-BR.json:  "intro_messages.purpose": " O propósito deste {type} é: {purpose}.",
i18n/it.json:  "intro_messages.purpose": " Lo scopo di {type} è: {purpose}.",
i18n/nl.json:  "intro_messages.purpose": " This {type}'s purpose is: {purpose}.",
i18n/zh-CN.json:  "intro_messages.purpose": "此{type}的用途是：{purpose}。",
i18n/zh-TW.json:  "intro_messages.purpose": "此{type}的用途為：{purpose}。",
i18n/ko.json:  "intro_messages.purpose": "이 {type}의 설명: {purpose}.",
i18n/es.json:  "intro_messages.purpose": " El propósito de este {type} es: {purpose}.",
i18n/pl.json:  "intro_messages.purpose": " Celem tego {type} jest: {purpose}.",
i18n/en.json:  "intro_messages.purpose": " This {type}'s purpose is: {purpose}.",
i18n/tr.json:  "intro_messages.purpose": " Bu {type} için amaç: {purpose}.",
i18n/de.json:  "intro_messages.purpose": " Der Zweck der/des {type} ist: {purpose}.",
i18n/fr.json:  "intro_messages.purpose": " L'objectif de {type} est : {purpose}.",
components/post_view/channel_intro_message/channel_intro_message.jsx:                    id='intro_messages.purpose'
```

As you can see, the translation strings end with a dot. If we remove the dot from the translation files the behavior should also be as expected, and we keep the translation files and code clean. What you think?

**Comment by DSchalla** [comment]
@michaelkochub It would display no period if the purpose doesn't contain a period, if it does it will be displayed in a normal fashion. So the result is pretty much the same, just in the case where your purpose doesn't contain a dot, a dot isn't artificially added. 

That's also my understanding of the goal itself, maybe @jasonblais can confirm.

**Comment by jasonblais** [comment]
>@michaelkochub It would display no period if the purpose doesn't contain a period, if it does it will be displayed in a normal fashion. So the result is pretty much the same, just in the case where your purpose doesn't contain a dot, a dot isn't artificially added. That leaves it up to the user whether he wants to add a dot or not in the end.

> That's also my understanding of the goal itself, maybe @jasonblais can confirm.

Thanks @DSchalla! Tagging @esethna instead as he's more familiar with the goals for this one.

Also, appreciate your contribution @michaelkochub :tada:

**Comment by michaelkochub** [comment]
Sounds good, thank you all for the help. I've updated the commit to the appropriate fix.

**Comment by michaelkochub** [comment]
`pr-merge` failed, @esethna, just had to rebase on prod and push force again. I think it should be good to go now, provided a clean CI run.

**Comment by mkochub** [comment]
Would it be possible to get a second look-over on this? @esethna @DSchalla

**Comment by DSchalla** [comment]
Looks good to me, @esethna!

**Comment by sudheerDev** [comment]
@michaelkochub 👍. This would require a rebase again

**Comment by saturninoabril** [comment]
@michaelkochub Please rebase.  Then, this is good to merge.

**Comment by jasonblais** [comment]
Hey @michaelkochub -- sorry we missed your rebase earlier..can you help with it one more time and then we'll merge? Thanks so much for your help here.

**Comment by jasonblais** [comment]
Actually, @saturninoabril will help with the rebase and then we'll merge.

Thanks again @michaelkochub for your contribution :)

**Pull request merged**
