### PR TITLE
MM-19221 - Updating profile popover

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-19221 - Updating profile popover
This issue is being caused by the dynamic content that gets added to the popover after the popover has loaded. This is a temporary fix, we may need to find a more suitable fix for this in the future.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19221

### CODE REVIEW

**Comment by cpanato** [comment]
Mattermost test server created! :tada:
Access here: https://mattermost-webapp-pr-3930.test.mattermost.cloud
| Account Type | Username | Password |
|---|---|---|
| Admin | sysadmin | Sys@dmin123 |
| User | user-1 | User-1@123 |

**Comment by cpanato** [comment]
mattermod got api rate limit

**Comment by lindalumitchell** [comment]
@asaadmahmood can Saturn be swapped out for a(nother) dev review? He's out until Monday (and Steve already took a look for QA).

**Comment by lindalumitchell** [comment]
> I'm okay merging this since QA has tested it, but this is a lot of new CSS that's never been needed before, and this is really late in the release process to be adding it. Are we sure this has to go into 5.16?

That's a good point. Should this wait for v5.17, maybe? @asaadmahmood

**Comment by asaadmahmood** [comment]
@hmhealey @lindalumitchell Yeah, it can wait for 5.17, the bug isn't that big of a deal.

**Pull request merged**
