### PR TITLE
MM-35720,MM-36293: land at new messages line

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

- When opening a thread scrolls to last message
- When opening a followed thread with unreads, land at/scroll to New
Messages line
- Shows a loading screen when the whole thread isn't yet loaded

Refactors some initial actions, for fetching the thread, to a single function (`onInit`), 
this was done to be able to `await` for all posts to be retrieved and
then scroll to new messages line, or bottom.
 
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-35720
https://mattermost.atlassian.net/browse/MM-36293
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by esethna** [comment]
@ogi-m @jgilliam17 can you help enable CRT here ^

We should verify that the scroll to new message line only happens if the new message line would be off screen (ie in a long thread). If the new message line would normally be on screen when the thread opens then no scroll would be expected

**Comment by ogi-m** [comment]
@esethna The feature flag is now on by default for all test servers going forward, it just needs to be enabled in the system console

**Review by esethna — APPROVED** [review]
Looks great! Thanks @koox00 

I think this might also fix this somewhat related issue, but I'll leave it to QA to verify that: https://mattermost.atlassian.net/browse/MM-36293 cc// @ogi-m @jgilliam17

**Comment by koox00** [comment]
> Looks great! Thanks @koox00
> 
> I think this might also fix this somewhat related issue, but I'll leave it to QA to verify that: https://mattermost.atlassian.net/browse/MM-36293 cc// @ogi-m @jgilliam17

@esethna yes, I was meaning to solve that as well, didn't realize that there was a separate task for that, I'll add it in the description so we test it too.

**Comment by esethna** [comment]
@calebroseland @ogi-m @jfrerich would love to try and get this merged today for a testing session tomorrow if you guys can help prioritize reviews. Much appreciated!

**Comment by ogi-m** [comment]
@koox00 I'm seeing an issue:
1. User A posts a reply in a thread that User B is following 
2. Observe Threads area as User B - it gets bolded, as expected
3. User B goes to Threads and opens the unread thread - now marked as read; Threads unbolded
4. User B returns to a channel
5. User A posts a reply in the thread again
6. Observe Threads area for User B

**Observed**: Threads area gets bolded for a moment and then unbolds again (this behavior repeats with every consecutive new reply
**Expected**: Threads area gets bolded and stays bolded until the user views the thread

I can repro on the test server on the PR, but not on master.

**Comment by koox00** [comment]
> @koox00 I'm seeing an issue:
> 
>     1. User A posts a reply in a thread that User B is following
> 
>     2. Observe Threads area as User B - it gets bolded, as expected
> 
>     3. User B goes to Threads and opens the unread thread - now marked as read; Threads unbolded
> 
>     4. User B returns to a channel
> 
>     5. User A posts a reply in the thread again
> 
>     6. Observe Threads area for User B
> 
> 
> **Observed**: Threads area gets bolded for a moment and then unbolds again (this behavior repeats with every consecutive new reply
> **Expected**: Threads area gets bolded and stays bolded until the user views the thread
> 
> I can repro on the test server on the PR, but not on master.

Great catch @ogi-m, this was introduced here #8149, my guess is that on daily it won't reproduce due to the high availability thread read bug. Regardless, I'll fix it here, thx!

**Comment by koox00** [comment]
fyi @ogi-m the test server creation failed for the  commit which merged master into this branch,
the commit that holds the fix has been deployed correctly.

**Comment by esethna** [comment]
Perhaps @jwilander can take one of the reviews instead of @calebroseland given he's out the rest of this week?

@jfrerich are you able to help prioritize a review on this one as well?

**Comment by jfrerich** [comment]
@esethna, I'm not that comfortable with doing this review and would suggest someone from webapp to the review, if you are wanting a very in-depth review.  Can you reassign?

**Review by jwilander — APPROVED** [review]

**Comment by jwilander** [comment]
@jfrerich no worries. @devinbinnie mind taking a look?

**Comment by jfrerich** [comment]
Thanks, @jwilander

**Comment by ogi-m** [comment]
@koox00 Looks like the user is landing at the bottom of the thread when it should be the new messages line if he doesn't refresh the client before opening the thread:
https://gyazo.com/23e349cfbce14ae40f4046b7152cd258

**Steps**:
1. User2 posts a bunch of replies in a thread user1 is following
2. User1 goes to Threads and opens the thread without refreshing
**Expected**: Lands at the new messages line
**Observed**: Lands at the bottom of the thread

If User1 refreshes between steps 1 and 2, then he lands at the New Messages line


One more issue I'm seeing with the new messages line but with two different results:
- New messages line doesn't show up when first opening the thread from Threads inbox
- New messages line only shows up above the last reply when opening the thread in a channel

Steps when opening in Threads:
1. User1 creates a root post
2. User2 posts a bunch of replies to that root post
3. User1 goes to Threads inbox and opens the thread
**Expected**: New Messages line shown above the first reply post ( cc @matthewbirtch  @esethna is this expected?)
**Observed**: New Messages line isn't shown

Steps when opening from channel:
1. User1 creates a root post
2. User2 posts a bunch of replies to that root post
3. User1 clicks the reply button on the root post in the channel to open the thread in LHS
**Expected**: New Messages line shown above the first reply post
**Observed**: New Messages line is shown above the **last** reply post

**Comment by esethna** [comment]
@ogi-m good questions. I'm also not sure on the expected here. ie this is the case where you've never opened a thread before and all the replies are new. I think what you're proposing makes sense (ie show the new message line above the oldest reply post), will leave that up to @matthewbirtch ,

**Comment by matthewbirtch** [comment]
> @ogi-m good questions. I'm also not sure on the expected here. ie this is the case where you've never opened a thread before and all the replies are new. I think what you're proposing makes sense (ie show the new message line above the oldest reply post), will leave that up to @matthewbirtch ,

@ogi-m @esethna Since it's a thread that User 1 created the root post for, showing the new message line above the first reply post (your expected result) makes the most sense to me

**Comment by koox00** [comment]
> @ogi-m @esethna Since it's a thread that User 1 (current active user) created the root post for, showing the new message line above the first reply post (your expected result) makes the most sense to me
> 
> However, if it's a thread that someone else created and I haven't read the thread at all yet, I guess I would expect that no new message line would show at all since all posts are new to the user.

In my mind, all messages are new in both cases since you only have read the root post, so it would make sense to treat them the same way. 

Also for the second case (another user has created the thread) you'll have to manually follow the thread/message to be able to see the new messages line, for any new messages that arrive from that time and on.

**Comment by esethna** [comment]
@ogi-m or @jgilliam17 please help prioritize a review here so we can get this merged before the testing session tomorrow

**Review by ogi-m — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
