### PR TITLE
[MM-25571] Fix new message indicator not showing for webhook messages to webhook owner

### PR DESCRIPTION
**Pull request by WGH-**
The new message indicator has a special case for messages posted by the
current user. Currently, webhook messages are attributed to its creator,
which breaks the new message indicator.

See https://github.com/mattermost/mattermost-redux/pull/1159
Fixes https://github.com/mattermost/mattermost-server/issues/14612

### CODE REVIEW

**Comment by jgilliam17** [comment]
Thank you @WGH- 
I'm not seeing the new message line. Can you please check? Thanks

**Comment by WGH-** [comment]
I did `npm update mattermost-redux`, and it made several changes to `package-lock.json`. Not sure if that's right.

**Comment by jgilliam17** [comment]
@WGH- Can you please take a look at the failing build checks? I am having trouble creating a test server. Thanks.

**Comment by hmhealey** [comment]
@WGH- The changes to the package-lock.json are probably fine, although I'm not sure what keeps causing icu4c to change. The build failures are likely happening because your mattermost-redux branch is out of date with the latest master. Would you mind updating it and then updating the commit here? That should hopefully fix the build

**Comment by WGH-** [comment]
I rebased everything (both PRs) on top of the current masters.

I tried to read the CI error log from before, but I couldn't decipher the problem. I've noticed this error, but it's like at line 21000 out of 235000 (number of zeroes is right), so I'm not sure.
```
ERROR in ./actions/views/channel_sidebar.ts
Module not found: Error: Can't resolve 'mattermost-redux/utils/array_utils' in '/root/mattermost/mattermost-webapp/actions/views'
resolve 'mattermost-redux/utils/array_utils' in '/root/mattermost/mattermost-webapp/actions/views'
```

**Comment by hmhealey** [comment]
I know CI has issues building mattermost-redux sometimes, so you might've run into a temporary build bug. Looks like it built correctly though

**Comment by hmhealey** [comment]
I just did a quick test, and it looks like it's pulling the right version of mattermost-redux

**Comment by hmhealey** [comment]
Thanks, Jelena!

@WGH- If you update mattermost-redux to `4e60437ef540f030a5fdb9e921451f80f2f2c1ef` we can get this merged in then

**Comment by WGH-** [comment]
Done!

**Comment by hmhealey** [comment]
Awesome, thanks! This is good to go for 5.28 then

**Pull request merged**
