### PR TITLE
MM-41329 : Avoid re-rendering of CustomStatusEmoji component on post hovering

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Previously `CustomStatusEmoji` component was being continuously re rendered on hovering over post. This PR memoizes the component along with appropriate `shouldUpdate` implementation for the same component. All the props to the component except `userid` were static of nature, i.e wouldn't change during course of components lifecycle, would only be set at beginning of component mounting. Reason for re render of the component was due to few style props (of form `{{key: 'value'}} being passed to component and their the object referring change due to its parent re renders.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41329

Part of [Reduce lag while hovering over posts ](https://mattermost.atlassian.net/browse/MM-40113)

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots
|  before  |  after  |
|----|----|
|image| image |
|Before optimization it can be seen that the component is rendered multiple time on post hover due for props change, whose value actually didnt change but the object reference was changed|Since the profile was started after webapp was mounted, and only duration profile was run was for over post hover, it can be seen that since the CustomStatusEmoji was already rendered it wasnt re rendered on hover|

#### Release Note

```release-note
Avoid re rendering of CustomStatusEmoji component on post hovering.
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@hmhealey 
- Since here redux props are injected into the component via props but throught hooks, i.e useSelector, they do not effect the `arePropsEqual`

- In place where we use useMemo, we are only memoizing the function to get the underlying function `getCustomStatus`, we are then calling that function via useSelector, which will only gets changed if `userId or state` change or its input selector changes. https://github.com/mattermost/mattermost-webapp/blob/d5dce5067378ec9fa70e5139fb7063e127a87cc9/components/custom_status/custom_status_emoji.tsx#L41

I tested the app with change in status, it works fine. Lets have a cloud instance for us to check it out

**Review by AGMETEOR — APPROVED** [review]
👍🏿

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
@M-ZubairAhmed Can you please fix the failed checks? I re-ran once, but all failed again.
I'd like to trigger E2Es again after update, [last report](https://mattermost-cypress-report.s3.amazonaws.com/109377-d5dce50-onprem-ent-webapp-pr-9698-mattermost/mm-ee-testd5dce50/mochawesome.html) had 70+ failures.
Tested manually - custom statuses are working as expected - able to set correctly, clear and changes status text including the emoji.
I saw an issue with the server on initial login, it opened on a white screen (what shout have been main view with tips). Unfortunately I hit r instead of 4 when trying to take a screenshot 😞 
I'll remove the server and create a new one to see if I can reproduce.

**Comment by jgilliam17** [comment]
Re-tested - No issues with the new server.

**Review by jgilliam17 — APPROVED** [review]
@M-ZubairAhmed 
[Latest E2E report](https://mattermost-cypress-report.s3.amazonaws.com/146733-fa95529-onprem-ent-webapp-pr-9698-mm-ee-test:fa95529/mochawesome.html) looks good, no PR related failures.
There are still some failed checks that are preventing merge.

**Pull request merged**
