### PR TITLE
[MM-29517]: Update favicon assets to improve contrast on dark themes

### PR DESCRIPTION
**Pull request by gitstart**
Summary
Webapp: Update favicon assets to improve contrast on dark themes

Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/16046

### Release note
```release-note
Update favicon assets to improve contrast on dark themes
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@asaadmahmood could I ask you to review this PR?

**Comment by asaadmahmood** [comment]
@matthewbirtch Sure.

**Review by asaadmahmood — APPROVED** [review]
Verified the assets, they look good to me.

**Comment by nevyangelova** [comment]
@gitstart can you please update your fork with our latest master.

**Comment by AshishDhama** [comment]
This change isn't required. We already fixed it as part of our branding change last year.
https://mattermost.atlassian.net/browse/MM-29517
cc// @esethna

**Comment by AshishDhama** [comment]
@gitstart Thanks for this, It is an old ticket which we should have closed.
Screenshot 2023-01-18 at 8 16 14 PM

**Pull request closed without merging**
