### PR TITLE
[MM-9695] Add status icons on "add member to channel" and "add member to team" lists

### PR DESCRIPTION
**Pull request by CoolTomatos**
#### Summary
Add status icons on "add member to channel" and "add member to team" lists.
Update the snapshot `add_users_to_team.test.jsx.snap`

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/8425
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-9695)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes

### CODE REVIEW

**Comment by amyblais** [comment]
This looks good to me and I didn't see any issues when I tested - ready for @jasonblais to confirm.

**Comment by CoolTomatos** [comment]
Thanks @amyblais

**Comment by CoolTomatos** [comment]
Sorry I got a few school deadlines at hand. May not be able to do it this time.

**Comment by saturninoabril** [comment]
@CoolTomatos FYI, I did a follow up PR (here -> https://github.com/mattermost/mattermost-webapp/pull/957). Like I said earlier, I'm good with your changes here and really appreciate your effort, but maybe it's practical if we'll proceed with my PR.
Is it okay if we close this PR in favor of mine? I'm really sorry for this.

**Comment by CoolTomatos** [comment]
@saturninoabril sure

**Comment by jasonblais** [comment]
@CoolTomatos Do you still get credit for your school project/assignment, even though this was closed?

**Comment by CoolTomatos** [comment]
@jasonblais haha. Contribution is just one part of the assessment. More is about the analysis, which we are kinda struggling.

**Comment by saturninoabril** [comment]
@CoolTomatos I feel bad about this. Let me know if there's something I could make up for you 🥇

**Pull request closed without merging**
