### PR TITLE
[MM-47074] : Migrate "components/suggestion/generic_channel_provider.jsx" to Typescript

### PR DESCRIPTION
**Pull request by aashish0909**
#### Summary

Migrate components/suggestion/generic_channel_provider.jsx to typescript

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/21095
Fixes https://mattermost.atlassian.net/browse/MM-47074

#### Related Pull Requests

NONE

#### Screenshots

NONE

#### Release Note

NONE
```release-note
NONE
```

### CODE REVIEW

**Review by sinansonmez — APPROVED** [review]
LGTM 🚀 thanks for your effort

**Review by AshishDhama — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
@aashish0909 this is all set.

**Comment by hmhealey** [comment]
Thanks again for the PR, @aashish0909!

**Pull request merged**
