### PR TITLE
[MM-24760] Fix post card icon CSS

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Fix the CSS problems of post cards.

#### Ticket Link
MM24760 https://mattermost.atlassian.net/browse/MM-24760

#### Related Pull Requests
None

#### Screenshots
Closed not hover
Screenshot from 2020-05-25 18-59-16

Closed hover
Screenshot from 2020-05-25 18-59-32

Opened not hover
Screenshot from 2020-05-25 18-59-42

Opened hover
Screenshot from 2020-05-25 18-59-53

### CODE REVIEW

**Comment by stylianosrigas** [comment]
I had to remove the Setup Cloud Test Server label because we need to deprecate the cluster the installation is running. Reapplied successfully.

**Comment by larkox** [comment]
@prapti Thanks for finding that out. I have corrected it for RHS Root, RHS comments and Search Results. In theory, that is all the places I found it in the code where this can happen. If you find anything else, let me know.

**Pull request merged**
