### PR TITLE
MM-49057 - disable channel creation if add board check is checked but…

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR adds the condition to disable the create channel button when the add Board check is checked but no template has been selected. So, once the add Board check is checked and a template is selected, the user will be able to create the new channel and associate the new board to the channel.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49057

#### Related Pull Requests
n/a

#### Screenshots

https://user-images.githubusercontent.com/10082627/210070027-d383cd7e-a1c3-4c1e-b4fb-e5107e1a72cc.mp4

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by julmondragon — APPROVED** [review]
Thanks @pvev !

**Review by hmhealey — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]

**Pull request merged**
