### PR TITLE
[MM-20441] - Migrate 'components/integrations/installed_oauth_apps' to TypeScript

### PR DESCRIPTION
**Pull request by bjorge82**
#### Summary
- Improve code by migrating it to Typescript
- All files in folder installed_oauth_apps are migrated
- `make test` passed with success
- List of installed OAuth apps are affected by this change

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16133

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks!

**Comment by jfrerich** [comment]
Thanks for the PR, @bjorge82! Many of us have been out for the holidays. Your PR will finish the review process shortly.

**Review by nevyangelova — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you for your contribution @bjorge82 
Tested, looks good to merge.
- Verified installed OAuth app list and action on oauth app screen - as before.

**Comment by hanzei** [comment]
@bjorge82 Merging `master` into your branch seems to have broken CI:

```
> tsc

components/integrations/installed_oauth_apps/installed_oauth_apps.tsx:106:21 - error TS2322: Type '(appId: string) => ActionFunc' is not assignable to type '(oauthAppId: string) => Promise<{ error?: { message: string; } | undefined; }>'.
  Type 'ActionFunc' is missing the following properties from type 'Promise<{ error?: { message: string; } | undefined; }>': then, catch, [Symbol.toStringTag], finally

106                     onRegenerateSecret={this.props.actions.regenOAuthAppSecret}
                        ~~~~~~~~~~~~~~~~~~

  components/integrations/installed_oauth_app/installed_oauth_app.tsx:45:5
    45     onRegenerateSecret: (oauthAppId: string) => Promise<{ error?: { message: string } }>;
           ~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'onRegenerateSecret' which is declared here on type 'IntrinsicAttributes & Pick<ClassAttributes<InstalledOAuthApp> & InstalledOAuthAppProps, "team" | ... 5 more ... | "onRegenerateSecret"> & InstalledOAuthAppProps'


Found 1 error.
```

Could you please take a look? After the issue is resolved, I'm happy to merge the PR. Sorry for the inconvenience.

**Comment by emilyacook** [comment]
> @bjorge82 Merging `master` into your branch seems to have broken CI:
> 
> ```
> > tsc
> 
> components/integrations/installed_oauth_apps/installed_oauth_apps.tsx:106:21 - error TS2322: Type '(appId: string) => ActionFunc' is not assignable to type '(oauthAppId: string) => Promise<{ error?: { message: string; } | undefined; }>'.
>   Type 'ActionFunc' is missing the following properties from type 'Promise<{ error?: { message: string; } | undefined; }>': then, catch, [Symbol.toStringTag], finally
> 
> 106                     onRegenerateSecret={this.props.actions.regenOAuthAppSecret}
>                         ~~~~~~~~~~~~~~~~~~
> 
>   components/integrations/installed_oauth_app/installed_oauth_app.tsx:45:5
>     45     onRegenerateSecret: (oauthAppId: string) => Promise<{ error?: { message: string } }>;
>            ~~~~~~~~~~~~~~~~~~
>     The expected type comes from property 'onRegenerateSecret' which is declared here on type 'IntrinsicAttributes & Pick<ClassAttributes<InstalledOAuthApp> & InstalledOAuthAppProps, "team" | ... 5 more ... | "onRegenerateSecret"> & InstalledOAuthAppProps'
> 
> 
> Found 1 error.
> ```
> 
> Could you please take a look? After the issue is resolved, I'm happy to merge the PR. Sorry for the inconvenience.

@bjorge82 Thank you so much for your contribution! Let me know if there's anything we can help you with on this :)

**Comment by hanzei** [comment]
@bjorge82 I've fixed the type error for you. Hope you are find with that.

@jgilliam17 Could you please take another look? Just wanted to double check that I didn't broke anything.

**Review by jgilliam17 — APPROVED** [review]
@hanzei Re-tested - Looks good to merge.

**Pull request merged**
