### PR TITLE
[GH-15740] channel mentions in message attachments

### PR DESCRIPTION
**Pull request by jufab**
#### Summary

This PR fix the webapp problem with message attachements for channel and internal link.

#### Ticket Link

Jira ticket: https://mattermost.atlassian.net/browse/MM-28980
https://github.com/mattermost/mattermost-server/issues/15740 => For the webapp part

#### Related Pull Requests

None

#### Screenshots

No UI change

### CODE REVIEW

**Comment by jufab** [comment]
I create a message with attachments in the town-square channel => This redirect to Off-Topic

**Review by aaronrothschild — APPROVED** [review]
Looks good to me @jufab thanks for your contribution!

**Review by larkox — CHANGES_REQUESTED** [review]
Awesome! Thank you for fixing this.
Just one small change. Could you revert the changes in package-lock.json. You are not actually changing anything there, and the changes are probably just due a difference between your npm  version (or other build related tools) and the one we use.

**Review by nevyangelova — APPROVED** [review]
Thanks! LGTM, can you just revert the changes in package-lock.json?

**Comment by jufab** [comment]
No problem, it's done!

**Review by larkox — APPROVED** [review]
LGTM!

**Comment by amyblais** [comment]
@prapti Kind reminder to review for v5.29.

**Comment by prapti** [comment]
Testing this, but waiting on some answers from Alejandro about test steps. Will continue on Monday.

**Review by agarciamontoro — APPROVED** [review]
Great work, @jufab!

I just tested this in the webapp and confirmed that:
- If the link is contained in the Pretext field, there is no longer a page refresh on webapp when navigating to the link.
- If the link is contained in the Text field, there is no longer a Not Found error when navigating to the link.

We'll duplicate the original ticket to keep track of the mobile bug as well.

Thank you again!

**Review by prapti — APPROVED** [review]
Thank you @jufab for working on this one! 🎉 
A big thanks to @agarciamontoro for doing the peer QA review on this PR.. approving.

**Pull request merged**
