### PR TITLE
[MM-50284]: Fixes letter spacing on main titles for login and create account screens

### PR DESCRIPTION
**Pull request by stevemudie**
#### Summary

Changes the letter spacing on the signup & login pages to make the main text look less jumbled together.

#### Ticket Link

[MM-50284](https://mattermost.atlassian.net/browse/MM-50284)

[MM-50284]: https://mattermost.atlassian.net/browse/MM-50284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @stevemudie! Looks good. The only thing I'm seeing is that this change causes the main title to wrap on to 3 lines. 

I think we can just make a change to the padding on the h1 as well and that should prevent this.

````
.login-body .login-body-content .login-body-message .login-body-message-title {
    padding-right: 48px;
}
````

**Review by julmondragon — CHANGES_REQUESTED** [review]
Thanks @stevemudie !

Additionally to @matthewbirtch 's comment, it looks like we need to also adjust the padding in some screen widths to preserve the title wrap.
ie. In the login page for `(max-width: 1199px)` it could be reduced around 180px (https://github.com/mattermost/mattermost-webapp/blob/master/components/login/login.scss#L257)

**Review by julmondragon — APPROVED** [review]
Looks good! Thanks @stevemudie !

**Comment by stevemudie** [comment]
> Thanks @stevemudie! Looks good. The only thing I'm seeing is that this change causes the main title to wrap on to 3 lines.
> 
> I think we can just make a change to the padding on the h1 as well and that should prevent this.
> 
> ```
> .login-body .login-body-content .login-body-message .login-body-message-title {
>     padding-right: 48px;
> }
> ```
@matthewbirtch I made the change but unfortunately it still wraps to 3 lines on the login screen. 😕 

However, if I change the letter-spacing to -0.02em it fixes it without affecting the previous jumbled together issue.

Would you like me to make that change?

`letter-spacing: -0.01em`
letter-spacing -0 01em

`letter-spacing: -0.02em`
letter-spacing -0 02em

**Comment by julmondragon** [comment]
> @matthewbirtch I made the change but unfortunately it still wraps to 3 lines on the login screen. 😕
> 
> However, if I change the letter-spacing to -0.02em it fixes it without affecting the previous jumbled together issue.
> 
> Would you like me to make that change?

@stevemudie It looks like we need to reduce padding for title when in large screens as well (`(min-width: 1680px)`).
This should do the trick:
https://github.com/mattermost/mattermost-webapp/blob/master/components/login/login.scss#L231
```
        .login-body-message .login-body-message-title {
            - padding-right: 130px;
            + padding-right: 110px;
```

**Comment by matthewbirtch** [comment]
Test server seems to be failing, so I can't see the changes at the moment

**Review by lindalumitchell — APPROVED** [review]
Well done Steve! Checked both screens on various widths and they look great. 👍

**Review by matthewbirtch — APPROVED** [review]
Thanks @stevemudie!

**Pull request merged**
