### PR TITLE
[MM-38937] Remove the cursor pointer when hovering at "Disable notifications until:"

### PR DESCRIPTION
**Pull request by KuSh**
#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/18532
JIRA https://mattermost.atlassian.net/browse/MM-38937

#### Screenshots
|  before  |  after  |
|----|----|
| before | after |

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by KuSh** [comment]
> Thanks @KuSh That sounds good, I'll split the closing part out of this ticket. One more thing on this PR - can you please also remove the shading of the header item on hover? Thanks

Thanks. I'll have a try sure

**Comment by KuSh** [comment]
I've removed the shading of the header item on hove. It seems to be a regression after an id renaming in code that wasn't applied to css.
I've also removed an unused style definition

Perhaps a dev review is needed again. The code isn't what was reviewed anymore ^^

Regards,
Nicolas

**Comment by KuSh** [comment]
@jgilliam17 I've checked why the menu is closing, it is due to function `toggle` in menu_wrapper.tsx but I'm not confident at touching it as it is here for the mobile version and I don't know that code so much.

**Comment by jgilliam17** [comment]
Thanks @KuSh Looks good. I'll ask for re-reviews before approving. 
We'll address the closing of the menu on header click in the followup ticket, thanks for looking into it.

**Review by devinbinnie — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you for your contribution @KuSh 
Tested, looks good to merge.
- Verified hover effect and hand cursor no longer show on dnd submenu header.

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @KuSh

**Pull request merged**
