### PR TITLE
[MM-12483] Add babel-plugin-transform-dynamic-import to unit tests error

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add `babel-plugin-transform-dynamic-import` to unit tests error

@jasonblais Here is the [license link](https://github.com/airbnb/babel-plugin-dynamic-import-node/blob/master/LICENSE) of the added package for your review.  Thanks!

#### Ticket Link
Jira ticket: [MM-12483](https://mattermost.atlassian.net/browse/MM-12483)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by crspeller** [comment]
@saturninoabril If this is required, why do they pass on the build server and for me? Maybe you just need to upgrade your node version?

**Comment by saturninoabril** [comment]
I'm on `node: v9.11.2` and `npm: 6.4.1` and I'm sure that AM's local test fail is the same with me. What versions do you have?

**Comment by crspeller** [comment]
@saturninoabril
```
~➤ node -v
v10.11.0
~➤ npm -v
6.4.1
```

**Comment by saturninoabril** [comment]
Thanks @crspeller @enahum @jasonblais 

Closing this PR with the aim to bump our minimum node version to 10 (which also avoids adding more dependencies).

**Pull request closed without merging**
