### PR TITLE
MM-22191: Fix the mentions that get attached in a list

### PR DESCRIPTION
**Pull request by ethervoid**
After we converted our lists to table cells the whitespace nodes
behaves differently for Firefox and Webkit so wrapping them in the
same span, fixes the problem.

Thank you @hmhealey for your help

#### Summary

This PR fixes a problem introduced when we make the list elements a table. After that, the whitespace nodes kept working in Firefox but in Webkit didn't.

Looks like the mix between tables and li elements causes this problem and wrapping the content of the li element into a span fixes it.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-22192

### CODE REVIEW

**Comment by amyblais** [comment]
@ethervoid Do you know which PR caused this? Does this affect other things than autolinks?

**Comment by ethervoid** [comment]
@amyblais The regression is caused by [this PR](https://github.com/mattermost/mattermost-webapp/pull/4328). AFAIK everything inside a `<span>` element is affected: autolink is an example of it

**Comment by ethervoid** [comment]
@hmhealey a gentle ping :D

**Comment by ethervoid** [comment]
@devinbinnie Thank you! :)

**Comment by ethervoid** [comment]
@lindy65 Sorry I've merged it before QA :man_facepalming: I'll wait to merge the cherry pick until I have the ok from you :_(

**Comment by lindy65** [comment]
OK, thanks @ethervoid - testing now 👍

**Comment by lindy65** [comment]
Thanks @ethervoid - tested on the cherry-pick spinwick and this is fixed 👍

**Pull request merged**
