### PR TITLE
[MM-48104] upgrade core-js

### PR DESCRIPTION
**Pull request by m1lt0n**
#### Summary

Upgrade core-js to its latest version (minor updates):

| From version | To version | Changelog | Notes |
|----------|----------|---------|---------|
| 3.23.3    | 3.26.0 | [changelog](https://github.com/zloirock/core-js/releases) | - |

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-48104

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
i am afraid there is not much testing we can do apart from e2e here. since this is a shim library i think we can look into bundle size changes. Even that could be insignificant since this is just a minor version bump.

**Review by trilopin — APPROVED** [review]
Not easy to test but looking at the changelog, just more polyfills added and some regression fixed...so approved.

The JIRA issue was empty, did we upgrade the version because we had an issue or just for pure maintenance/version-health? 

Thank you!

**Comment by m1lt0n** [comment]
Thanks @trilopin . Maintenance/version-health indeed.

**Comment by trilopin** [comment]
@m1lt0n I'm not very familiar with core-js and I might ask a stupid question... but is it normal for core-js to not appear used in the code? is it used more internally by the bundler and that's why I don't find it?

After a regular search, I tried with [depcheck](https://www.npmjs.com/package/depcheck):
```
➜  mattermost-webapp git:(master) depcheck            
Unused dependencies
* buffer
* core-js
* emoji-datasource
* emoji-datasource-apple
* process
```

**Comment by M-ZubairAhmed** [comment]
> @m1lt0n I'm not very familiar with core-js and I might ask a stupid question... but is it normal for core-js to not appear used in the code? is it used more internally by the bundler and that's why I don't find it?
> 
> After a regular search, I tried with [depcheck](https://www.npmjs.com/package/depcheck):
> 
> ```
> ➜  mattermost-webapp git:(master) depcheck            
> Unused dependencies
> * buffer
> * core-js
> * emoji-datasource
> * emoji-datasource-apple
> * process
> ```

It wont show up in the actual bundler code directly since its used by babel internally to poly fill code based on the browsers list we have give. 
it is being used here in babel config https://github.com/mattermost/mattermost-webapp/blob/master/babel.config.js#L14

So essentially it would have poly filled `Array.includes` if we were to support ie11. But we are not so its not adding that poly fill

**Comment by m1lt0n** [comment]
@M-ZubairAhmed I've triggered e2e tests and a test server to just do some random manual checks. Feel free to review. Also, I've checked the bundle size and there is no measurable change with the old and new version of core-js.

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
