### PR TITLE
MM-49632 Don't block center channel during team switch

### PR DESCRIPTION
**Pull request by hmhealey**
When switching teams, we reload all of the current users' channels and channel members for that team (including DMs/GMs). I think there's a good chance that this is no longer needed, but I'm not certain about that yet, so that'll be a future ticket, probably as part of the one OKR Zubair has for the upcoming quarter.

This recently started feeling slower on Community because GraphQL requires paging through those channels and making multiple requests which are blocked on each other. To mitigate this, I just changed it so that we don't show the "Loading..." when switching teams any more. We're not making any less requests, but it'll improve perceived performance.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49632
Also lets us close https://mattermost.atlassian.net/browse/MM-48260

#### Release Note
```release-note
Don't show center channel as loading while switching teams
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]
The change in logic looks good. Approving, but qq: are there going to be changes due to MM-48260? If so, feel free to ask for re-review so I can see the new changes.

**Comment by hmhealey** [comment]
Nope, there's no more changes planned. I'll wait for Zubair to confirm, but I think the issue we ran into before was that guest users would see the centre channel stuck as "Loading..." because one of those requests failed and `state.requests.channels.getChannelsAndChannelMembers` would get set to something other than `success`. Since we don't check that state before for the loading indicator, that wouldn't happen any more regardless of if a request failed.

That said, I couldn't reproduce the issue locally, so perhaps it was already fixed some other way

**Comment by M-ZubairAhmed** [comment]
The guest issue is not able to reproduce in this PR. so may be it got fixed.

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @hmhealey 
Verified team switching is working as expected. 
I also tried to create few guest users to see if the issue mentioned above is fixed. 
I used "move to" to sort guests channels, and see one error when guest is moving channel to new category (3-dot menu>Move to>new category). Guest user belonged to 2 teams, 1 channel on each team.
I couldn't repro on master.
Screen Shot 2023-01-27 at 3 37 21 PM
Screen Shot 2023-01-27 at 3 51 31 PM

**Comment by jgilliam17** [comment]
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/292579-57213f0-onprem-ent-webapp-pr-12058-mm-ee-test:57213f0/mochawesome.html)- no PR related failures

**Comment by jgilliam17** [comment]
Thanks @hmhealey 
This PR is ok to merge then. I'll follow up with Zubair on menu issue.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
