### PR TITLE
[MM-14784] UI Automation: Write an automated test using `cypress` for "An ellipsis indicates the channel header is too long - DM

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
Wrote an automated test using `cypress` for "An ellipsis indicates the channel header is too long - DM

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/10520

### CODE REVIEW

**Comment by reflog** [comment]
Done!

**Comment by cometkim** [comment]
Hmm, Where this submodule came from?
image

**Comment by reflog** [comment]
> Hmm, Where this submodule came from?
> image


my apologies, leftover file on the filesystem

**Review by cometkim — CHANGES_REQUESTED** [review]
Code looks fine :ok_hand: But there is a missing assertion for:

> Clicking on the channel header should still display it in it's entirety.

**Comment by reflog** [comment]
@cometkim - You are absolutely right. Added the missing assertion.

**Comment by cometkim** [comment]
Thanks, @reflog :grin:

**Pull request merged**
