### PR TITLE
MM 37062 Add new default branded theme "Denim"

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Add new default branded theme 'Denim'

#### Release Note
```release-note
Added new default brand theme "Denim"
```

### CODE REVIEW

**Review by esethna — APPROVED** [review]
Looks good. 

@michaelgamble is the button color intentionally a brighter blue? My 2 cents is that it felt very bright/light compared to the sidebar and header colors used, which felt a bit out of place. Not a blocker, just an opinion ;)

**Review by nevyangelova — APPROVED** [review]
LGTM but  I didn't know we decided that this will be the default one from now on. I know people think its sexy tho :P so I am excited

**Review by matthewbirtch — APPROVED** [review]
Awesome! Loving this theme

**Review by michaelgamble — APPROVED** [review]
Looks good to me :)

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge. 
- Verified new Denim theme and theme preview icon in account settings.

**Comment by hmhealey** [comment]
image
Not a code thing, but a purely aesthetic thing. Are we okay with having 5 themes in this modal? Having the one item on the next row looks funny to me

**Review by hmhealey — APPROVED** [review]

**Comment by deanwhillier** [comment]
@hmhealey, had a chat with Design about that already, they are fine with it like that for now. :)

**Pull request merged**
