### PR TITLE
Updating header size

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
This is an update on the header size based on the new changes proposed. @lfbrock have a look.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by lfbrock** [comment]
@asaadmahmood: 

1. Search icon centering seems off 
screenshot 2018-03-06 05 53 13

2. Is it the search bar collapsing to the search icon happening at the right size? 

3. What are yours/Mike's thoughts on validating the change with users? Should we get any feedback before we merge it?

**Comment by jasonblais** [comment]
@asaadmahmood Thoughts on the feedback above?

**Comment by asaadmahmood** [comment]
@lfbrock @jasonblais Sorry for the late response.
1. Did that.
2. If I was triggering it on a lower size, it was taking a bunch of space of the header description etc. Also note that webrtc and zoom are disabled on the spinmint.
3. I definitely think we should. I am not completely for this change, I do not think it adds much to the experience of the app, as the search bar toggling to the search icon even with a slightly bigger button size is sufficient.

**Comment by michaelgamble** [comment]
Had a discussion with Asaad, the following changes were discussed in order to accommodate the way the header is currently built and to take the implementation a little closer to what is in the invision screenshots (https://invis.io/2JFXM7453AF): 
- in the full width resolution - decrease the search bar width to 180px
- have the search bar increase back to its current 296px when:
- - the user clicks into the search field
- - the user submits a search
** the reason here is when the search field results show in the RHS the search field, flags and mentions all exist in an RHS header, so if the search field width is reduced then mentions and flags will be left aligned leaving too much space to the right of the search field. This is a temporary solution that will be fixed as part of the planned 5.0 release design upgrades.

**Comment by asaadmahmood** [comment]
@michaelgamble Done. I did not change the header title to bold as that variant is currently unavailable in the app.

**Pull request merged**
