### PR TITLE
Uses PureComponent wherever shouldComponentUpdate absent.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary
Switches from `Component` to `PureComponent` wherever `shouldComponentUpdate` is absent. [Apparently some teams at Facebook are doing the same](https://news.ycombinator.com/item?id=14418576). This change is predicated on the belief that re-rendering is more expensive than checking whether props have changed - which I believe to be likely in the majority of cases although I admittedly have not proven it. 

I would be happy to gather a random sampling of data from the 173 components that this PR changes and we could regroup on that data if we want to prove/disprove my assumption before moving forward.

Thoughts?

#### Ticket Link
n/a

#### Checklist
- [x] Touches critical sections of the codebase (auth, posting, etc.)

#### Illustration

Here's an example showing the decrease in the number of renders of the `SearchBar` component when composing a post:

Using `Component` in `SearchBar` (existing production code):
more-renders

Using `PureComponent` in `SearchBar` (PR code):
fewer-renders

### CODE REVIEW

**Comment by jwilander** [comment]
Interesting, I think I like this.

A quick thought about potential downsides to this is that any component that is getting passed a new object or new function on every render is going to cause a guaranteed re-render (this isn't changing). But that would mean we'd be doing a shallow compare on props + render every time instead of just a render. I really don't think that's a big deal but I wonder if we should look into fixing cases [like this](https://github.com/mattermost/mattermost-webapp/blob/master/components/channel_header/channel_header.jsx#L759) so we avoid creating new objects/functions just on render

**Comment by mkraft** [comment]
@jwilander What I'm also going to do is automate and profile a workflow in Chrome to compare the performance between master and this PR branch. I'll post my results when ready.

**Comment by coreyhulen** [comment]
Whats the consensus here?

**Comment by mkraft** [comment]
@coreyhulen I automated a workflow using selenium and compared the PR branch to master but it didn't prove anything one way or another using the Chrome profiler. I'm going to have another look today to see if I can come up with something more conclusive.

**Comment by mkraft** [comment]
Closing and moving to https://github.com/mattermost/mattermost-webapp/pull/348 because it was submitted from a forked branch that no longer exists.

**Pull request closed without merging**
