### PR TITLE
[MM-34304] Migrate 'components/admin_console/admin_button_outline' and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by arvinDarmawan**
Summary
This code migrate "components/admin_console/admin_button_outline" component to TypeScript.

Ticket Link
Jira card: https://mattermost.atlassian.net/browse/MM-34304
Github issue: https://github.com/mattermost/mattermost-server/issues/17246

```release-note
Release Note
- Refactor component to typescript, no changes in UI
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @arvinDarmawan! This looks good to me. We definitely appreciate the additional unit tests as well.

**Review by mkraft — APPROVED** [review]

**Comment by hmhealey** [comment]
@furqanmlk Are you able to take a look at this?

**Review by furqanmlk — APPROVED** [review]
image

image


image

**Pull request merged**
