### PR TITLE
[MM-38537] File-extension outside border fix

### PR DESCRIPTION
**Pull request by engineereng**
#### Summary
Fixes a bug where long file extensions would push the text and download icons out of the bounds of the file preview. This PR sets a set width for the file name and file type and truncates names and types based on how much space they take rather than the number of characters they use.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-38537

#### Screenshots
|  before  |  after  |
|----|----|
|before center  | after center |
|before rhs | after rhs

#### Release Note
```release-note
Fix long file extension names pushing out of the bounds of the module.
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @engineereng. I'll do a more thorough review, but right away I noticed there is a large gap between the file extension and the filesize in cases where truncation is not needed. This space should be collapsed in this case.
image

**Comment by engineereng** [comment]
@matthewbirtch Hopefully this commit fixes the issue.

after 2

**Comment by matthewbirtch** [comment]
Screenshots look better, but I can't verify since the test server failed

**Comment by engineereng** [comment]
@matthewbirtch The server should be fixed now. 

On another note, the test that the branch previously failed had to do with the file name truncation function. I replaced that truncation with spacing-based CSS truncation, so I've removed the test.

**Review by matthewbirtch — COMMENTED** [review]
Looks better now @engineereng. Thanks for resolving that. 

Just one question:
- On our community server, we have a 'more actions' button and a 'download' button on attachment cards. Is there a reason we don't have this in your PR server?

**PR:**
image

**Community:**
image

**Comment by engineereng** [comment]
@matthewbirtch The option was not [enabled in the System Console](https://docs.mattermost.com/messaging/sharing-files.html#sharing-public-links), which I have corrected.


I've pushed a PR that adjusts the spacing to accommodate the More Actions button.

center
rhs

**Review by matthewbirtch — APPROVED** [review]
Thanks @engineereng! I think we're good

**Comment by engineereng** [comment]
Awesome! Thanks for the review!

**Review by mkraft — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]
We could potentially add something an e2e test.

mattermost-webapp/e2e/cypress/integration/files_and_attachments/upload_files_spec.js

We could write a small test that uploads a file with a long name and then add this check

`cy.get('.post-image__name').should('have.css', 'text-overflow', 'ellipsis');`

Test would look something like this:
```
        const filename = 'svgwithaveryveryveryveryverylongname.svg';
        const aspectRatio = 1;

        cy.visit(channelUrl);
        cy.get('#post_textbox', {timeout: TIMEOUTS.ONE_MIN}).should('be.visible');

        // # Attach file
        cy.get('#centerChannelFooter').find('#fileUploadInput').attachFile(filename);
        waitUntilUploadComplete();

        cy.get('#create_post').find('.file-preview').within(() => {
            // * Filename is correct
            cy.get('.post-image__name').should('contain.text', filename);

            // * Type is correct
            cy.get('.post-image__type').should('contain.text', 'SVG');

            // * Size is correct
            cy.get('.post-image__size').should('contain.text', '6KB');

            // * Img thumbnail exist
            cy.get('.post-image__thumbnail > img').should('exist');
        });

        // # Post message
        cy.postMessage('hello');
        cy.uiWaitUntilMessagePostedIncludes('hello');

       cy.get('.post-image__name').should('have.css', 'text-overflow', 'ellipsis');
```

**Review by furqanmlk — COMMENTED** [review]
@engineereng Long file name looks good but download icon is outside border

image

**Comment by engineereng** [comment]
@furqanmlk Apologies for the delay. The error should be fixed now.
after

@BenCookie95 I like the idea of this e2e test, but I am having difficulty setting up my environment to run any Cypress tests. I'm going to hold off on implementing the test for now.

**Review by furqanmlk — APPROVED** [review]
Working as expected.

**Pull request merged**
