### PR TITLE
translations PR 20180109

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by kaakaa** [comment]
`ja` LGTM

**Comment by wget** [comment]
@jasonblais Thanks for this test VM. Could you give me right to launch such tests? This would definitelly help me each time I need to check translations in context and when there is a new pull request made to integrate translations.

Please pull a new version from the server, because there are multiple issues. I made a bunch of changes to the translation any way and I proofread it again in context.

Issues with French:

* `admin.gitlab.siteUrlDescription` while present in the translation file is not translated any more in context.
screenshot_20180110_002126
* `.admin.plugin.management.title` while properly translated as well is not translated in the UI (it is still written `Management` instead of `Gestion` in the sidebar.
screenshot_20180110_004743
* `Choose File` still in English
screenshot_20180110_005028
* Since you converted JIRA to a plugin implementation, the translation has been removed/cannot be applied
screenshot_20180110_005333
* The same applies for Zoom
* In `Edition and license` the text seems to be not translatable.
screenshot_20180110_020152

**Comment by jasonblais** [comment]
Thank you @wget 

1) I've created a ticket to fix some of these translations in the System Console: https://mattermost.atlassian.net/browse/PLT-8564

2) Plugins don't yet support translations, but we have a ticket for it here: https://mattermost.atlassian.net/browse/ABC-21

Really appreciate your thorough review. I can't unfortunately share permissions for you to create the test server, but you can ask me anytime and I'll set it up. We submit a PR for translations once every week.

**Comment by enahum** [comment]
Each plugin should handle their own translation

**Pull request merged**
