### PR TITLE
Cypress/E2E: Fix several tests from the recent cloud test run

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Screenshots
Screen Shot 2021-05-18 at 1 04 39 PM
Screen Shot 2021-05-18 at 1 09 41 PM
Screen Shot 2021-05-18 at 10 54 41 AM
Screen Shot 2021-05-18 at 11 34 57 AM
Screen Shot 2021-05-18 at 12 36 46 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM

**Comment by furqanmlk** [comment]
Thanks @saturninoabril 

One test case is failing as it can not find `Getting Started` item in Main Menu items list

image

**Review by furqanmlk — COMMENTED** [review]
Failing one test case

**Comment by saturninoabril** [comment]
Thanks for testing @furqanmlk! Should be good now. Please take a look again.

**Review by furqanmlk — COMMENTED** [review]
LGTM

image

image

image

image

image

**Pull request merged**
