### PR TITLE
GH-13171: Add Cypress automated test for "Can change iOS App Download Link setting"

### PR DESCRIPTION
**Pull request by themaverikk**
#### Summary

This pull requests adds a Cypress automated test for "Can change iOS App Download Link setting" on admin console Customizations page

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13171

#### Related Pull Requests

Awaiting on https://github.com/mattermost/mattermost-webapp/pull/4384 and https://github.com/mattermost/mattermost-webapp/pull/4376

### CODE REVIEW

**Comment by arjunlather** [comment]
This pull request will also fix #4376 and #4384

**Comment by hahmadia** [comment]
@themaverikk Could you please resolve the merge conflicts? Thanks!

@saturninoabril What PR is this waiting on?

**Comment by saturninoabril** [comment]
@hahmadia Those first 2 commits.  This PR is submitted on top of other PRs.

**Comment by hahmadia** [comment]
@saturninoabril Alright so we are waiting on https://github.com/mattermost/mattermost-webapp/pull/4384 and https://github.com/mattermost/mattermost-webapp/pull/4376 . Got it 👍

**Comment by hahmadia** [comment]
@themaverikk It seems that there is merge conflicts, could you please resolve them? We can merge it after 👍

**Comment by themaverikk** [comment]
@hahmadia I've resolved the conflicts. Please merge the PR.

**Pull request merged**
