### PR TITLE
[MM-49823] Adding new invite button for A/B testing

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Adding new invite button for A/B testing:

- Button will only appear for instances that are <= 28 days old
- Flag has to be enabled in split.io
- Added telemetry to the new button
- Hid the old invite team members button while the top one is visible

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49823

#### Related Pull Requests

- https://github.com/mattermost/mattermost-server/pull/22140

#### Release Note

```release-note
New invite team members button
```

### CODE REVIEW

**Review by kostaspt — COMMENTED** [review]
Can you elaborate on how split.io only affects certain users to get this button?

**Comment by BenCookie95** [comment]
> Can you elaborate on how split.io only affects certain users to get this button?

Yep! So with the server PR you can see we added a new value to the feature flag model, each MM cloud instance gets their own "workspace" in split.io. Their MM server will check split.io for feature flag values and if nothing is set, it will use the default value in `model/feature_flags.go`. 

So basically we can change `ShowInviteTeamMembersButton` value to `true` for whatever server we want

**Comment by kostaspt** [comment]
> > Can you elaborate on how split.io only affects certain users to get this button?
> 
> Yep! So with the server PR you can see we added a new value to the feature flag model, each MM cloud instance gets their own "workspace" in split.io. Their MM server will check split.io for feature flag values and if nothing is set, it will use the default value in `model/feature_flags.go`.
> 
> So basically we can change `ShowInviteTeamMembersButton` value to `true` in split.io for whatever server we want

Oh that's the flow, thanks for the explanation!

**Review by kostaspt — APPROVED** [review]
Nicely done 👍🏼

**Review by plant99 — APPROVED** [review]

**Comment by BenCookie95** [comment]
@plant99 & @kostaspt Requesting a re-review, removed the 28 day check https://github.com/mattermost/mattermost-webapp/pull/12066/commits/ae12498ddac414f4e64dcd41cf9aba13aff1056a

**Review by kostaspt — APPROVED** [review]

**Review by plant99 — APPROVED** [review]

**Review by furqanmlk — COMMENTED** [review]
@BenCookie95, Can you please fix the conflict branch?

**Pull request closed without merging**
