### PR TITLE
[MM-29395]Replaced line 522 changeCss to using CSS variable

### PR DESCRIPTION
**Pull request by talentedunicorn**
#### Summary

Replacing the use of the Javascript variable `theme.sidebarText` from line 522 of code with the CSS variable `--sidebar-text`

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15834 
#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Review by deanwhillier — APPROVED** [review]
LGTM, thanks @talentedunicorn!

**Review by jgilliam17 — APPROVED** [review]
Thank you @talentedunicorn 
Tested, looks good to merge.
- Verified old sidebar channel switcher text shortcut button in different themes.

**Pull request merged**
