### PR TITLE
Add markdown to apps field descriptions in forms and commands

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Add Markdown to field description, and errors.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35179

#### Related Pull Requests
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5426

#### Screenshots
Screenshot from 2021-06-07 14-44-19
Screenshot from 2021-06-07 14-44-25

#### Release Note
```release-note
Add support for markdown in apps forms and interactive dialogs field descriptions and errors, and slash commands.
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by larkox** [comment]
As per the conversation here,I reverted the changes to allow commands to show markdown: https://community.mattermost.com/core/pl/tiapzoetg7b33dx8yjji3xkbdo

**Comment by DHaussermann** [comment]
@larkox Is there a way you could add an example options to the Test App with markdown to validate this change? (I'm not sure where those screens are from)

**Comment by larkox** [comment]
@DHaussermann master test app should have this. Let me know if you don't find it / have any problem.

**Review by jfrerich — APPROVED** [review]
LGTM and I can't wait to add this to Zendesk!

**Review by DHaussermann — APPROVED** [review]
Tested and passed. 
Reviewed this PR along with the 2 related PRs
- All Markdown is displaying correctly
- Tested on Browser and desktop
- Tested on mobile web view
- No JS error in console when modal opens or on submit
No issues found

LGTM!

Please merge!

**Pull request merged**
