### PR TITLE
MM-37821 - remove global header option from user settings

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
removes the global header option from the user settings modal. Also changes the `getGlobalHeaderEnabled` selector to only use the feature flag and not the user-preferences object anymore.

replacement for #8583 since the old PR did run into severe Spinwick issues

#### Ticket Link
[MM-37821](https://mattermost.atlassian.net/browse/MM-37821

#### Related Pull Requests
Once this successfully runs a spinwick server for testing the old PR #8583 will be closed in favor of this one.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by michelengelen** [comment]
@andrewbrown00 I have added all changes from #8583 to this new PR and the test servers are running smoothly (strange, isn't it? 🧐 )

@nevyangelova @crspeller I am sorry for the onconvenience, but could you please re-review/approve? THX a lot! 🙇🏼‍♂️ 

cc// @jgilliam17 @spirosoik

**Comment by spirosoik** [comment]
@michelengelen I think the latest master across both repos helped.

**Review by nevyangelova — APPROVED** [review]
No inconvenience :)

**Review by crspeller — APPROVED** [review]

**Comment by andrewbrown00** [comment]
Hey, @michelengelen, looks like the `feature flag` is missing from here as well 😬

**Comment by michelengelen** [comment]
@andrewbrown00 the server now shows the global header correctly (aka feature flag set)

cc/ @spirosoik

**Comment by michelengelen** [comment]
@spirosoik do you know what happened here? all of those file changes do not come from my commits and the rebase somewhat messed up again.

Running `git diff origin/master...` shows the correct diffs ...

**Comment by michelengelen** [comment]
@andrewbrown00 this one works for me as well

**Comment by andrewbrown00** [comment]
@michelengelen this one is working for me too, reviewing now 👍

**Review by andrewbrown00 — APPROVED** [review]
Thanks, @michelengelen, changes look good 🙂 

* Verified the global header was enabled by default
* Verified the global header option is no longer available in the account settings
* Verified the feature flag is set to `true`

Default state | Account settings | Feature flag
----- | ----- | -----
image | image | image

**Comment by jgilliam17** [comment]
@michelengelen Test server is not loading for me. Seeing this error.
Screen Shot 2021-08-20 at 1 04 52 PM

**Comment by michelengelen** [comment]
@jgilliam17 I just tested and it works for me. @spirosoik could this be related to our problems last week?

**Comment by spirosoik** [comment]
@michelengelen because seem that it's happening on master.test.mattermost.com which is not deployed by our team, I think it's an issue in the code. So if we hit this again we need to a deeper investigation which is not related with cloud or spinwicks but I suppose with MM server codebase itself. (still an assumption though)

**Comment by michelengelen** [comment]
@jgilliam17 I will rebase this branch as well to have it incorporate the fix for the "white screen of death" bug! You should be able to review after the rebase just fine!

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified global header was enabled by default, feature flag is set to true and the option is no longer available in the account settings

**Pull request merged**
