### PR TITLE
translations PR 20190318

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by cpanato** [comment]
just ignore the test server is for a testing in mattermod :)

**Comment by jasonblais** [comment]
@enahum there are some conflicts that need to be resolved.

**Comment by enahum** [comment]
how is it that there is a conflict on two files that are not `en.json`?

**Comment by jasonblais** [comment]
@enahum Because of https://github.com/mattermost/mattermost-webapp/pull/2484, have pinged Brad

**Pull request merged**
