### PR TITLE
[MM-39287] - Fix alignment of clear button in message deleted indicator

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
This PR fixes the issue mentioned in https://mattermost.atlassian.net/browse/MM-39287 regarding the display of the clear button. The icon wasn't vertically aligned.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39287

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
The clear `x` button is shown on the same line on hover, but it's not aligned vertically, see Chrome and Firefox
Screen Shot 2021-11-18 at 4 13 32 PM
Screen Shot 2021-11-18 at 4 10 47 PM


Looks better on Compact message display
Screen Shot 2021-11-18 at 4 11 19 PM

**Comment by nevyangelova** [comment]
@jgilliam17 I did some digging and the HTML structure of this post button is completely wrong. I would have to move it to the post body if we wanted perfect alignment. However I feel like the priority is low so I would suggest we invest time in tasks with higher priority. I placed it in a more balanced point between standard and compact view.

**Comment by jgilliam17** [comment]
Thanks @nevyangelova agree on effort, and lower priority.
Tested, looks good to merge.
- Verified alignment of clear button on message deleted post.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
