### PR TITLE
downgrading Italian and Polish to Alpha

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
### Summary

```
Italian and Polish are degraded to Alpha
```
```release-note

```

### CODE REVIEW

**Comment by ctlaltdieliet** [comment]
Tagging @jasonblais and @cwarnermm for review

**Review by jasonblais — APPROVED** [review]

**Review by metanerd — APPROVED** [review]
Thank you @ctlaltdieliet !

**Comment by amyblais** [comment]
@metanerd @hmhealey @jgilliam17 I heard we want this small PR for today's v5.39 Code Freeze, please help with reviews today if you can.

**Review by jgilliam17 — APPROVED** [review]
Thanks @ctlaltdieliet 
Tested,, looks good to merge.
- Verified Italian and Polish have been downgraded, language options have `(Alpha)` label.

**Pull request merged**
