### PR TITLE
remove claim of 10 GB storage per user for grandfathered cloud plan

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Remove claim of 10 GB storage per user for grandfathered cloud plan

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45396
https://mattermost.atlassian.net/browse/MM-45233

#### Related Pull Requests
N/A

#### Screenshots
plan-details-and-no-bogus-claim

#### Release Note
```release-note
* Do not show claim of 10 GB storage per user for grandfathered cloud plan
* Standard subheader for system console cloud billing subscription page
```

### CODE REVIEW

**Review by AGMETEOR — APPROVED** [review]

**Review by pvev — APPROVED** [review]
LGTM! :shipit:

**Comment by marianunez** [comment]
@amyblais would like to include this change for next week dot release

**Review by stevemudie — APPROVED** [review]
Looks good @neallred1

**Pull request merged**
