### PR TITLE
#7775: allow team / system admin to convert a channel to private

### PR DESCRIPTION
**Pull request by liusy182**
#### Summary
This PR contains client side change for [#7775](https://github.com/mattermost/mattermost-server/issues/7775). It adds a dropdown item in channel header that allows team or system admin to convert a public channel to private

Corresponding server side PR:
https://github.com/mattermost/mattermost-server/pull/7950

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [X] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [X] Has server changes (please link)
- [ ] Has redux changes (please link)
- [X] Has UI changes
- [X] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by gfra54** [comment]
Hello all,
I have two questions : 
 - what is the current status of this PR ? Merging being blocked means that there is a problem with it ? SHould I/ Can I help in any way ?
 - without this feature, is it ok for now for a mm admin to just change the value of the "Type" field in database "Channels" to "P" to convert a channel to a private one? Are there dependencies anywhere else ?

Thanks a lot, and sorry for the dumb questions, I am very new to all this collaborative thing.

**Comment by saturninoabril** [comment]
- This is queued for PR review.
- Technically, changing `Type` field to `P` will convert channel into private one but it's not recommended since there are several key items that being bypassed like validation, log for audit, system message that the channel has been changed, etc.

**Comment by liusy182** [comment]
I see. please let me know in case change is needed. I was not aware of these complications.

**Comment by gfra54** [comment]
@liusy182 What are the complications ? Can I help ?

**Comment by esethna** [comment]
@saturninoabril can you please help with some technical guidance so we don't run into any of the issues you described?

**Comment by saturninoabril** [comment]
@esethna @liusy182 Sorry if I confused everyone. The comment I made above is a response to @gfra54 about directly modifying the field on the database and not about the changes/implementation on this PR.
Please proceed with PM review. Thanks!

**Comment by liusy182** [comment]
Thanks @esethna  for the feedback. I expect to be able to work on this in the next 2 weeks.

**Comment by esethna** [comment]
@liusy182 anything we can help with on this PR?

**Comment by liusy182** [comment]
@esethna i have pushed a change a few weeks ago. Looks like I missed to see merge conflicts. I will try to pick this up in the upcoming week est. before 21Feb. Sorry too busy on my schedule.

**Comment by jasonblais** [comment]
hey @liusy182! Let us know if we can help with the merge conflicts? I understand you're busy, but just wanted to offer help.

Huge appreciation for your work thus far.

**Comment by liusy182** [comment]
hi @jasonblais sorry it turns out i didn't get time to work on the merge. Could someone help on it? Thank you ! :)

**Comment by saturninoabril** [comment]
@jasonblais @liusy182 Let me fix merge conflicts.

**Comment by saturninoabril** [comment]
@jasonblais (Maybe worth a separate ticket) Do we need system message that the public channel has been converted to private channel?

**Comment by jasonblais** [comment]
@liusy182 Really great work here.

I found a few minor improvements/fixes that we could do here. Let us know if you need any help, or if you don't have time for the updates, and we'd be glad to help.

1) Focus not on "Yes, convert to private channel" button when dialog opens
 - Click "Convert to private channel" channel menu option.
 - Hit ENTER on the dialog that opens
 - observed: No action taken
 - expected: "Yes, convert to private channel" action taken

image

2) Part 3 of the issue (https://github.com/mattermost/mattermost-server/issues/7775) proposed adding a diagnostic event for telemetry each time this feature is used. This should be a two-line change similar to https://github.com/mattermost/platform/pull/5516/files#diff-4821c248760929f278cfda4b8c0e1fa3.

3) I agree with @saturninoabril that we should post a system message when the channel is converted to a private channel. We could simply re-use the existing string here: https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json#L215

4) I was able to join a channel after it was made private
 - User A: Create a new public channel, call it "Channel A"
 - User A: Converts "Channel A" to private
 - User B: Clicks the "More..." option below public channels, and finds "Channel A" as a channel he can join
 - observed: joining a channel works
 - expected: "Channel A" should not be in the list of available public channels to join

**Comment by liusy182** [comment]
hi @jasonblais could someone help to proceed from here? I don't expect to be able to pick this up in the upcoming 1~2 months. thank you :)

**Comment by esethna** [comment]
Thanks @liusy182, we have [queued this](https://mattermost.atlassian.net/browse/MM-9835) for one of our core developers to take over. Really appreciate your help here!

**Comment by saturninoabril** [comment]
@jasonblais 
1. Done
2. Done
3. Submitted PRs at server and redux
- https://github.com/mattermost/mattermost-server/pull/8501
- https://github.com/mattermost/mattermost-redux/pull/432
4. Can't repro (will take a look again after the server and redux PRs get in)

(Also, this PR needs to update redux commit after merging corresponding PR)

Added @enahum for dev review since I did the latest update to this PR.

**Comment by jasonblais** [comment]
Thanks @saturninoabril! I'll re-test once server and redux PRs are merged.

Requesting review from @grundleborg from the permissions team.

@enahum Ticket for RN app - it was only added for the webapp for now given there isn't a UI design for it https://mattermost.atlassian.net/browse/MM-9951
@enahum An admin can convert a private channel to be public, but we didn't want to allow this in the UI for now, given the risk of sharing private/confidential info from that private channel.

**Comment by saturninoabril** [comment]
@jasonblais @esethna Server and redux PRs were merged recently and this PR has been rebased to latest master (with corresponding commit on redux). This is now ready for PM review.

**Comment by saturninoabril** [comment]
Thanks @enahum!
Added ChannelPermissionGate to the 'Convert to Private' option with permission of `Permissions.MANAGE_PUBLIC_CHANNEL_PROPERTIES`.

This now ready for PM review.

**Comment by esethna** [comment]
@saturninoabril I think there is a permissions issue where this is appearing for all users. It should be limited to system admins only. Looks really good otherwise.

**Comment by saturninoabril** [comment]
Thanks @esethna! This should be ready for PM review.

**Comment by hmhealey** [comment]
Unassigning myself since there's already 3 other people reviewing this

**Comment by saturninoabril** [comment]
Thanks @grundleborg!  Submitted PRs for server and redux store
- https://github.com/mattermost/mattermost-server/pull/8655
- https://github.com/mattermost/mattermost-redux/pull/464

**Pull request merged**
