### PR TITLE
MM-38060 - Fix license check for Themes and others in System Console

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary
Theme Management and a few other settings in System Console was only checking for the existence of a license (assuming it would be available for both E10/E20). However, in Cloud Starter, there is a license present but Theme Management should not be enabled.

This PR changes it so that the following features are hidden if there is no license or if it's a Starter license:

- `ThemeManagement`: Features > Experimental:
          - EnableThemeSelection
          - AllowCustomThemes
          - DefaultThemes
          
- `RestrictCreationToDomains`: Authentication > Signups > `Restrict new system and team members to specified email domains`
- `EnableAuthenticationTransfer`: Features > Experimental > Allow Authentication Transfer
- `TownSquareIsReadOnly`:  Features > Experimental > Town Square is Read-Only
- `EnableOnlyAdminIntegrations`: Integrations > Integrations Management > Restrict managing integrations to Admins

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-38060

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]

**Comment by stevemudie** [comment]
@marianunez Most of it worked as expected but not all.

**Still present on both E0 and Cloud Starter edition**:
- RestrictCreationToDomains: Authentication > Signups > Restrict new system and team members to specified email domains

**Not present on any edition/SKU?**:
- EnableOnlyAdminIntegrations: Integrations > Integrations Management > Restrict managing integrations to Admins

**Comment by marianunez** [comment]
> @marianunez Most of it worked as expected but not all.

Thanks @stevemudie!

> **Still present on both E0 and Cloud Starter edition**:
> 
> * RestrictCreationToDomains: Authentication > Signups > Restrict new system and team members to specified email domains

Looking into this further, I noticed that this setting is duplicated in the code, one only showing for licensed and the other one showing when there is no license 🤷‍♀️ Going back to the [System Console Settings spreadsheet](https://docs.google.com/spreadsheets/d/1xC0L2XLXbpoAtiehvZ9gJW3Kr1HVPZwL0nTx72-qPMU/edit#gid=706073698), I noticed that is supposed to be available for all SKUs so I'll remove the duplicated one and it seems to be working as expected then.

> **Not present on any edition/SKU?**:
> 
> * EnableOnlyAdminIntegrations: Integrations > Integrations Management > Restrict managing integrations to Admins

This one I was able to see in Enterprise, Professional and not in Starter or E0:

Screen Shot 2021-09-07 at 10 06 00 PM

Could you check again on the latest test server?

**Comment by marianunez** [comment]
> Looking into this further, I noticed that this setting is duplicated in the code, one only showing for licensed and the other one showing when there is no license 🤷‍♀️ Going back to the [System Console Settings spreadsheet](https://docs.google.com/spreadsheets/d/1xC0L2XLXbpoAtiehvZ9gJW3Kr1HVPZwL0nTx72-qPMU/edit#gid=706073698), I noticed that is supposed to be available for all SKUs so I'll remove the duplicated one and it seems to be working as expected then.

@stevemudie Trying to determine why the setting is duplicated, found that the reason is just because it is shown with a different help text when it's licensed vs unlicensed - see [this ticket comment](https://mattermost.atlassian.net/browse/MM-17213?focusedCommentId=64491)

So, when licensed with Professional or Enterprise, the help text will show references to Guest Accounts as specified in the ticket and not when E0 or Starter.

**Review by stevemudie — APPROVED** [review]
Thank you for looking further into this @marianunez !

It's all good now and everything is working as expected and described.

**Pull request merged**
