### PR TITLE
Fix pipeline by increasing node memory for Makefile steps

### PR DESCRIPTION
**Pull request by metanerd**
#### Summary
This PR also includes that branches use their separate cache now. I retriggered pipeline a couple of times to see, if the pipeline still fails: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp?branch=fix-pipeline , but I need to bump the caching every time. 

#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by jwilander** [comment]
Will this also fix the failure on the mattermost-server pipelines?

**Comment by jwilander** [comment]
In particular, this failure https://app.circleci.com/pipelines/github/mattermost/mattermost-server/15008/workflows/4287172c-699a-49c2-9380-8177c0137000/jobs/82192

**Comment by metanerd** [comment]
> In particular, this failure https://app.circleci.com/pipelines/github/mattermost/mattermost-server/15008/workflows/4287172c-699a-49c2-9380-8177c0137000/jobs/82192

No, but this PR should fix this problem: https://github.com/mattermost/mattermost-server/pull/15380

**Pull request merged**
