### PR TITLE
[MM-24376] Show channel (and team) as unread if system message is adding current user to channel

### PR DESCRIPTION
**Pull request by bradjcoughlin**
#### Summary
When a user is added to a channel on another team, they are not immediately shown an unread badge that they have been added. Until the web app reconnects with the server (it periodically syncs every 15 mins), the channel and team remains as read.

The web client receives the post via the websocket but currently ignores it as it ignores all system messages. This change makes an exception to allow the "system_add_to_team" post type through and increment the unread count.

**Current Architecture**
Adding User to New Channel-3

**PR Changes to Architecture**
MM-24376

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24376

#### Related Pull Requests
https://github.com/mattermost/mattermost-redux/pull/1142

### CODE REVIEW

**Comment by bradjcoughlin** [comment]
@hmhealey @sudheerDev I'm going to talk to QA about test coverage for these cases as well as the issue of the periodic sync and reconnection potentially creating confusion when testing.

**Comment by bradjcoughlin** [comment]
@jgilliam17 this one is ready to be tested 😄

**Comment by amyblais** [comment]
@bradjcoughlin Looks like this wasn't cherry-picked yet.

**Comment by sudheerDev** [comment]
Manually cherrypicked to 5.25

**Pull request merged**
