### PR TITLE
Fixes global threads crash on md images

### PR DESCRIPTION
**Pull request by koox00**
#### Summary
MarkdownImageExpanded needs onImageHeightChanged prop to be defined,
this commit adds that, but not using it, since we have fixed height for
thread items.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37079

#### Screenshots

expanded
expanded

collapsed
collapsed

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by koox00** [comment]
@esethna, @matthewbirtch I'm requesting reviews from you both to see how the inline images are getting displayed

**Comment by esethna** [comment]
@koox00 test servers aren't working for PRs, but what's going on here? 
image

**Comment by koox00** [comment]
> @koox00 test servers aren't working for PRs, but what's going on here?

haha, the bug was for markdown images with custom dimensions so adding `=500x100` after the image url,
so that skewed that particular image!!

**Comment by esethna** [comment]
@koox00 ah got it, what happens with very tall markdown images?

**Comment by koox00** [comment]
> @koox00 ah got it, what happens with very tall markdown images?

in the example above the full image is the whole tux, with legs and all

**Review by esethna — APPROVED** [review]
Approving on behalf of UX since matt is out

**Review by lieut-data — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Tested, looks good to merge.
- Verified threads with single post markdown image with custom dimensions is not longer causing a crash when opening global threads.

Kyriakos - thanks for noting collapse/expand arrow being visible at this time on Threads, this should be fixed/addressed in the issue below, which will redesign how we display markdown, gifs, tables etc. on global threads https://mattermost.atlassian.net/browse/MM-37082

**Review by calebroseland — APPROVED** [review]

**Comment by calebroseland** [comment]
Also, just a brief mention to a design change possibility (that cc @matthewbirtch) mentioned a while back: dropping rich markdown support and use a simple parsing/preview that might behave similar to how notifications extract preview text (text content without formatting)

**Comment by matthewbirtch** [comment]
> Also, just a brief mention to a design change possibility (that cc @matthewbirtch) mentioned a while back: dropping rich markdown support and use a simple parsing/preview that might behave similar to how notifications extract preview text (text content without formatting)

Yes @calebroseland I believe there was a ticket for this effort: https://mattermost.atlassian.net/browse/MM-35492

**Pull request merged**
