### PR TITLE
[MM-31508] Rename URL to Path in Call 

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Rename URL to Path in Apps Call

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31508

### CODE REVIEW

**Comment by hanzei** [comment]
There is an unrelated (?) linter issue. I will check if I can repo it once `master` is merged into `feature/cloud-apps`.

**Comment by larkox** [comment]
You may be missing changes in one no typescript file: actions/command.test.js

**Comment by hanzei** [comment]
@larkox Thanks for the hint. I've fix that file.

**Review by mickmister — APPROVED** [review]

**Comment by larkox** [comment]
The following js files are missing the updates:
- /actions/command.test.js

**Comment by hanzei** [comment]
@larkox I think I fully covered that file. Could you please point me to the lines that I missed?

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
@hanzei Sorry, I missed that :sweat_smile:

**Pull request merged**
