### PR TITLE
Cypress/E2E: Fix flaky tests on cloud on boarding, upload files and user status

### PR DESCRIPTION
**Pull request by saturninoabril**
### Summary
Fix flaky tests on cloud on boarding, upload files and user status

#### Ticket Link
none, failing on daily

### CODE REVIEW

**Review by srkgupta — APPROVED** [review]
Tested and all tests passed. Wasn't able to execute the cloud onboarding test, but the changes LGTM. Approving the PR.

**Comment by prapti** [comment]
@saturninoabril The only test that's passing for me is the `upload_files`. Wondering if I'm missing anything.

`Cloud onboarding` is failing with the following:
Screen Shot 2020-09-15 at 4 40 05 PM

And `user status` is failing with the following for all 'away', 'online' and 'offline': 
Screen Shot 2020-09-15 at 4 38 23 PM

**Comment by saturninoabril** [comment]
For cloud onboarding, you need license with Cloud feature. I've posted the [link at QA Private few days ago](https://community-release.mattermost.com/core/pl/4wq6w63gafyzurbnh4bhsafsmw) on where to get it.

**Comment by prapti** [comment]
Thank you @saturninoabril! I can verify that the cloud onboarding test is passing with the appropriate license. The user_status test is still failing in Cypress though, although in theory it looks like a successful test. I can hopefully take a look later today.

**Comment by saturninoabril** [comment]
Hello @prapti. It's not failing on me but I made a change. PTAL again, thanks.

**Review by prapti — APPROVED** [review]
Tests are passing. Thank you for taking care of this @saturninoabril!

**Pull request merged**
