### PR TITLE
[MM-38138] Fix safari "bug" with SVG sizing

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
Turns out Safari doesn't respect the width/height values on an SVG `<symbol>` tag. This PR fixes that by moving the size attributes to the `<use>` tags that instance the symbol and does a bit of restructuring of the overall SVG to make it a bit cleaner.

Also, since the Cloud Upgrade Experience is now using a copy of the same background to better support theming, this PR applies the same Safari fix and updates the pill arrangement to match the corresponding designs.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38138

#### Screenshots
Tips and Next Steps:
image

Cloud Payment Details:
image

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]
Thanks @deanwhillier! LGTM!

**Comment by annelieseklein** [comment]
@deanwhillier thanks! The background look a bit funky - I think it is the wrong image.
Here is the right background https://www.figma.com/file/IYsHf8o2kwRfG6hqVNjgfC/MM-37605-Update-purchase-and-error-screens-with-branding?node-id=132%3A19995

**Comment by deanwhillier** [comment]
@annelieseklein, looks like this is one of those "I just missed you" moments. I took a local copy of that file at 5:12pm on Thursday to be able to get full control of the vectors to work out the exact transforms needed and it looks like you updated it at 7:15pm. :P

No worries, I'll apply the updates, push to this PR and ping you for another review. :)

**Comment by deanwhillier** [comment]
@annelieseklein, background has been updated, please take a look when you have a minute.

**Comment by matthewbirtch** [comment]
@deanwhillier this is what I'm seeing. It looks like the gradient fade is not rendering properly in Safari still: 

**Safari**
image

Seems okay in Chrome though:
image

**Comment by deanwhillier** [comment]
Thanks @matthewbirtch, should be fixed now! Safari can be such a pain sometimes. 🙄

**Review by matthewbirtch — APPROVED** [review]
Yep, that fixed it @deanwhillier

**Review by calebroseland — APPROVED** [review]

**Review by annelieseklein — APPROVED** [review]
looks good, thanks Dean!

**Comment by deanwhillier** [comment]
@annelieseklein, once the server updates, you should be able take a look at the tweaks we made to position and alignment of the background.

**Review by annelieseklein — APPROVED** [review]
looks great! thanks!!

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified background on Tips and Next Steps and Cloud Upgrade on Safari.

**Comment by deanwhillier** [comment]
Cherry pick done manually.

**Pull request merged**
