### PR TITLE
remove legacy mattermost cloud code

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Remove UI for removed, legacy "Mattermost Cloud" plan (removal effective November 1).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44700

#### Related Pull Requests
N/A

#### Release Note
```release-note
Remove UI for removed, legacy "Mattermost Cloud" plan (removal effective November 1).
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Comment by neallred** [comment]
@AGMETEOR @stevemudie gentle ping for review

**Comment by AGMETEOR** [comment]
> @AGMETEOR @stevemudie gentle ping for review

Reviewing now

**Review by stevemudie — APPROVED** [review]
Ran it through a short smoke test and everything worked as expected @neallred!

**Review by AGMETEOR — APPROVED** [review]
Great clean up 🚢

**Comment by neallred** [comment]
Adding do not merge because we want it to be timed with the first release on or after November 1.

**Pull request merged**
