### PR TITLE
MM-11822 Close channel autocomplete if multiple tildes are typed

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Close channel autocomplete if multiple tildes are typed.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-11822

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Needs to be implemented in mobile (https://github.com/mattermost/mattermost-mobile/pull/2138)
- [x] Has UI changes

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @jwilander can you set up a spinmint so I can test please?

**Comment by lindy65** [comment]
Thanks @jwilander 

1. When editing a post to reflect "strike-through", should the channel autocomplete close after typing the first two tildes or only after typing the two at the end? (At present, this is not happening but it does close after typing the two tildes at the end of the line).

image

2. Also in post edit, if I backspace and remove the double tilde at the beginning of the line, the channel autocomplete remains open

image

3. When using channel autocomplete in a message input box, I don't see the channel autocomplete close after typing two tildes.  _This is not easy to reproduce but seems easiest after switching channels to a fresh page load_.  The channel autocomplete does close once you start typing after the double tilde.

image

Note: behaviors for all the above are the same when reproducing in the RHS.

**Comment by jwilander** [comment]
Hmmm, none of that should happen and it didn't reproduce when I was testing. I wonder if it's related to slower connections, I'll see what I can do

**Comment by lindy65** [comment]
Thanks @jwilander - weird - I could consistently reproduce so didn't try it only once.  Could be my slower connection though, as you mentioned...

**Comment by jwilander** [comment]
@lindy65 yep that was it, if the request from typing the first `~` completed after the autocomplete was closed then it would re-open. Pushed a fix and once the build finishes I'll update the test server

**Comment by jwilander** [comment]
Also 2) looks like a different issue that reproduces on master, mind filing a bug for that one and I can look at in another PR?

**Comment by lindy65** [comment]
Thanks @jwilander - bug ticket for 2) here: https://mattermost.atlassian.net/browse/MM-12256

Retested and 1) and 3) are fixed.  I didn't find any other issues.  Looks good to me. 👍

**Pull request merged**
