### PR TITLE
Fix spurious redirect on playbooks upgrade

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
For the past few months, when Playbooks is upgraded on community, some users get redirected to the `/error?type=team_not_found` page.  We've been able to reproduce it locally when already on `/playbooks`, but mysteriously it also happens on community wherever you are.

The timing and code changes appear to date back to https://mattermost.atlassian.net/browse/MM-43306 and logic therein that fails to take into account reserved team names. Change this to ignore such transitions, with the hope it addresses the issue on community as well.

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-plugin-playbooks/issues/1747

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by lieut-data** [comment]
@M-ZubairAhmed, I tried to find a place to extend the existing unit tests to help cover this case, but had some difficulty. Any suggestions? I'd like to test this on community so we can go back to deploying playbooks regularly, at least until the monorepo solves all our problems :P

**Review by trilopin — APPROVED** [review]
Code seems fine to me.

However I tried to manually reproduce it but I couldn't (master vs this branch)

**Comment by lieut-data** [comment]
@trilopin, can you confirm that deploying while you are inside Playbooks behaves differently on this branch vs. `master`? On mine, it stops the team redirect for daily development at least.

**Review by m-ripper — APPROVED** [review]
I can confirm that it locally works, very nice. Let's hope it also fixes the issue we're facing on Community!

**Comment by M-ZubairAhmed** [comment]
It was in place to check while joining while MFA joining, let me check that. :)

**Comment by trilopin** [comment]
> @trilopin, can you confirm that deploying while you are inside Playbooks behaves differently on this branch vs. `master`? On mine, it stops the team redirect for daily development at least.

I could reproduce the error in master and verify that it's not happening in your branch. 👍🏽 

Thank you

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good doesnt add to the mfa error i was fearing it would.

**Comment by lieut-data** [comment]
@jgilliam17, @M-ZubairAhmed has kindly already run e2e tests and helped verify a few codepaths. Not sure what else is required here: mostly we'd like to deploy this to community and see if it addresses the spurious team redirects that have been happening when upgrading plugins.

**Comment by jgilliam17** [comment]
Thanks @lieut-data I checked the [E2Es ](https://automation-dashboard.vercel.app/cycle/291087)- no PR related failures.
Server is not creating, I'll /update-branch and try one more time. If it fails again I am ok with merging and verifying on community.

**Review by jgilliam17 — APPROVED** [review]
@lieut-data 
There's an issue with building a server, not just here but for few other PRs. Not to hold this further, I can test this after merge on community.

**Pull request merged**
