### PR TITLE
[MM-34551] Make button disabled for Read Only Admin

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

The `Renew License` button should be disabled for a read only admin

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34551

#### Screenshots

image

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]
LGTM! you need to add the isDisabled property to the tests. Thanks @hahmadia!

**Review by BenCookie95 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected and Test plan is updated

**Pull request merged**
