### PR TITLE
[MM-20584] Migrate 'components/admin_console/team_channel_settings/te…

### PR DESCRIPTION
**Pull request by cinlloc**
…am/details' module and associated tests to TypeScript

#### Summary
Migrate 'components/admin_console/team_channel_settings/team/details' module and associated tests to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13488

#### Notes
Only one file was left to migrate (`index.js`) but had impact on others.

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Comment by devinbinnie** [comment]
Thanks for the contributor @cinlloc, but it looks like the ticket you've picked up is not for the work you've done.
The ticket is to migrate the `components/admin_console/team_channel_settings/team/details` module, as opposed to the work you've done on the `components/admin_console/team_channel_settings/channel/details` module.

I'd be happy to merge this in to migrate the redux connector, but it will not finish the ticket you've chosen.

**Comment by cinlloc** [comment]
Oops. You're right! 

Anyway it seems there was one file missing to solve properly https://github.com/mattermost/mattermost-server/issues/13491. I will fix the current PR with correct code (that concerns `components/admin_console/team_channel_settings/team/details`) and move these changes to another PR (that will be linked to #13491, unless you provide me another ticket).

Thanks!

**Comment by devinbinnie** [comment]
> Oops. You're right!
> 
> Anyway it seems there was one file missing to solve properly [mattermost/mattermost-server#13491](https://github.com/mattermost/mattermost-server/issues/13491). I will fix the current PR with correct code (that concerns `components/admin_console/team_channel_settings/team/details`) and move these changes to another PR (that will be linked to #13491, unless you provide me another ticket).
> 
> Thanks!

That's perfect, thanks @cinlloc!

**Comment by cinlloc** [comment]
Changed moved to another PR: https://github.com/mattermost/mattermost-webapp/pull/6924

Fix is coming! (for current PR)

**Comment by jasonblais** [comment]
Sorry @cinlloc for the additional ping, I've removed the "stale" label given I see you'r actively working on these changes :)

If any questions, don't hesitate to let us know!

**Comment by cinlloc** [comment]
Unfortunately I will not have time to work more on this one. I will focus on getting merged the other one created https://github.com/mattermost/mattermost-webapp/pull/6924 . Current PR can be closed and ticket set to up-for-grabs. Thx for your understanding.

**Comment by jfrerich** [comment]
Thanks for letting us know, @cinlloc!

@devinbinnie, is this close enough that someone on the webapp team could complete the changes?  We could also close and open the issue back UFG and references this PR as a starting point?  I'm good with either choice

**Comment by devinbinnie** [comment]
> Thanks for letting us know, @cinlloc!
> 
> @devinbinnie, is this close enough that someone on the webapp team could complete the changes? We could also close and open the issue back UFG and references this PR as a starting point? I'm good with either choice

@jfrerich Nope, unfortunately this PR was done in error and the contributor has finished this work in another PR. We should close this and open the ticket as UFG. This PR can be discarded.

**Comment by jfrerich** [comment]
Thanks @devinbinnie. Closing this PR and opening https://github.com/mattermost/mattermost-server/issues/13488 back UFG.

**Comment by jfrerich** [comment]
Closing per https://github.com/mattermost/mattermost-webapp/pull/6823#issuecomment-729953335 and opening ticket in the description back UFG

**Pull request closed without merging**
