### PR TITLE
send activity messages to the server

### PR DESCRIPTION
**Pull request by granovsky**
#### Summary
Handle message from electron and keep online status if user is active 

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/7721

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has server changes (please link)

### CODE REVIEW

**Comment by esethna** [comment]
@deanwhillier can you take a look at this since you are working on this. Any thoughts on the approach in these PRs?

- https://github.com/mattermost/desktop/pull/949
- https://github.com/mattermost/mattermost-server/pull/10458

**Comment by granovsky** [comment]
@esethna @deanwhillier 
Hey! Any comments? It's on review for almost a week.

**Comment by deanwhillier** [comment]
Apologies for the delay @granovsky, we've been tied up with some internals. Will get back shortly!

**Comment by esethna** [comment]
Closing as per: https://github.com/mattermost/desktop/pull/949#issuecomment-475399949

**Pull request closed without merging**
