### PR TITLE
[MM-40739] Make-width-fit-content

### PR DESCRIPTION
**Pull request by bhimeshchauhan**
#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-40739 and cut-off `Manage members` button on safari
Issue https://github.com/mattermost/mattermost-server/issues/19238

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

### SAFARI
Screen Shot 2022-01-19 at 8 15 10 AM

### CHROME
Screen Shot 2022-01-18 at 10 58 19 PM

### FIREFOX
Screen Shot 2022-01-18 at 10 59 29 PM

#### Release Note

```release-note
Styling change
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR, @bhimeshchauhan!

This fixes the Add Button, but it looks like the Manage Members link at the bottom of the dropdown has gotten cut off. Would you be able to take a look at that as well?

**Comment by bhimeshchauhan** [comment]
@hmhealey It was a different issue but I have added the fix. Thanks for noticing that! 💪

**Review by pablovelezvidal — APPROVED** [review]
LGTM! thanks @bhimeshchauhan . I validated the fix and works as expected in Mac > Chrome/Firefox/Safari

**Review by hmhealey — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @bhimeshchauhan 
Tested, looks good to merge.
- Verified `Add` and `Add members` buttons on channel members dropdown
- E2E report looks good, no PR related failures.

**Pull request merged**
