### PR TITLE
Contribute : Voice Message

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
Added voice message capability in webapp
```

### CODE REVIEW

**Review by esethna — CHANGES_REQUESTED** [review]
This is great! A few things I noticed: 

1. Can we make sure the ENTER button on the keyboard works to stop a recording and send the message once the recording finishes processing?
2. The desktop tab seems to indicate the app is using the microphone even after the recording is stopped: https://gyazo.com/13f76a18cc25003cc8ccf2975f143afa
3. The tooltip on the voice message icon seems to get stuck open occasionally, but I cannot consistently repro
4. The ... menu on a voice message doesn't seem to do anything. Did we have thoughts about what we'd offer in there? I think at least having two options to start could make sense: 1. "Download", 2. "Copy link" that does the same as copying the permalink to the post) cc// @matthewbirtch 
5. CRT is disabled on the test server, let's just make sure it doesn't present any issues when enabled
6. I couldn't access the system console for testing the settings as I'm not a sys admin. What is the default value for the max duration of voice messages?

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
This is awesome @M-ZubairAhmed. A few things below that I noticed in my testing today (tested on https://calls.test.mattermost.com/). Let me know if you need any clarifications.

1. There seems to be something going on with the speed of recordings. I took an 8 second recording and when I went to preview it, the duration of the recording shows as 2 seconds. Then when I play back the message it plays at 4x speed and I sound like a chipmunk when reviewing my call :)
2. I also noticed that even after I finished a voice message recording and switch to another tab, even though I'm not actively recording anymore the recording dot displays in the browser tab and says my microphone is in use
image
3. When I click the Voice messages icon button, the tooltip seems to stay showing
image
4. For the playback controls, are we able to make it so that I can seek by clicking on the seek bar? Alternatively, we could add a drag handle for this kind of seeking. (something like this)

image

5. For messages that have been posted in the channel, the ••• icon button doesn't work. 

6. The ••• icon button will need a hover state. The hover state should look like this:

image

7.  The ••• icon also looks to be vertically misaligned within the button. I added a border to the button to demonstrate

image

8. We should also do the same for the remove icon button in this state. There is no hover state here either and it is also vertically misaligned

image

9. It looks like the Elapsed time text is using the wrong theme variable and it's causing it to be too hard to read - it should be `var(--center-channel-color)` instead of var(--center-channel-text)

image

10. Some styling updates to the `x` cancel button
    - The x icon button is smaller than the check icon. In the designs the icons (and the button they are contained in) were the same size (28x28)
    - In its default state, there should be no background on the x button
    - When hovered, the background should change to `center-channel-color` with 8% opacity
    -  The foregrounds should be `center-channel-color` with 56% opacity, and change to 72% opacity on hover
    - In dark theme this is how it is looking
image

11. For the recording visualization, is this customizable further? What you have here is close, but I'm wondering if it's possible to get even closer to what the design had
image

12. I also noticed that during the recording, the microphone icon is different. Can we use `icon-microphone-outline` instead?

**Comment by matthewbirtch** [comment]
> 4\. The ... menu on a voice message doesn't seem to do anything. Did we have thoughts about what we'd offer in there? I think at least having two options to start could make sense: 1. "Download", 2. "Copy link" that does the same as copying the permalink to the post) cc// @matthewbirtch

image

**Comment by esethna** [comment]
@matthewbirtch nice, we seem to think alike ;)

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Looks like a lot of the issues are resolved, nice work @M-ZubairAhmed. The audio visualizer looks great too. 

These are the issues that are outstanding:

> 1. There seems to be something going on with the speed of recordings. I took an 8 second recording and when I went to preview it, the duration of the recording shows as 2 seconds. Then when I play back the message it plays at 4x speed and I sound like a chipmunk when reviewing my call :)

It doesn't seem to be as bad, but I'm still hearing a pitch shift on the recording.

> 4. For the playback controls, are we able to make it so that I can seek by clicking on the seek bar? 

As you noted in your message, this one is still pending

> 9. It looks like the Elapsed time text is using the wrong theme variable and it's causing it to be too hard to read - it should be `var(--center-channel-color)` instead of var(--center-channel-text)
> 
> image

Still seeing this one ☝️ 

**In addition to the above:**

- Need to show the message when you've reached the max duration (this can probably auto hide after 5 seconds or so)
    image
- Clicking 'Download' from the menu doesn't seem to actually download the audio file.

**Comment by esethna** [comment]
@M-ZubairAhmed nothing to add other than the issues Matt's mentioned: (A) download not working, and (B) message needed for when max duration is reached. 

Side note: I cannot repro consistently, but occasionally I've noticed that the waveforms do not show when recording, and it results in the audio being lost: See below it shows as 0:00 long recording and can't be played. The waveforms did not show while recording this message
image

**Review by esethna — APPROVED** [review]
Nice work @M-ZubairAhmed!

**Comment by hmhealey** [comment]
Removing my review request on this to clear out some notifications. Let me know when this is ready for my review again

**Comment by M-ZubairAhmed** [comment]
Will sunset this for now, it will be here when we need to invest in this again soon.

**Pull request closed without merging**
