### PR TITLE
[MM-48800] Refresh bindings on plugin activation

### PR DESCRIPTION
**Pull request by javaguirre**
#### Summary

Refresh app bindings when an app_plugin_enabled_event gets triggered.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-48800

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
Refresh App bindings when a App plugin enabled event gets triggered.
```

### CODE REVIEW

**Comment by javaguirre** [comment]
Related: https://github.com/mattermost/mattermost-plugin-apps/pull/429

**Review by mickmister — APPROVED** [review]
This LGTM :+1: @javaguirre Are you able to take a look at the mobile app as well?

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by neallred — APPROVED** [review]

**Review by Afsoon — APPROVED** [review]

**Comment by javaguirre** [comment]
I tested this and it works fine, I'm gonna merge it since it's a bit overkill waiting for the oneliner to be tested.

**Pull request merged**
