### PR TITLE
Added hideRHSPlugin action to RHS plugin registy

### PR DESCRIPTION
**Pull request by Lisenish**
#### Summary

- Adds support for plugins to close the right-hand sidebar
- Adds missing test for showRHSPlugin

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/11893
  JIRA: https://mattermost.atlassian.net/browse/MM-17810
#### Related Pull Requests
- Has mattermost-plugin-demo changes https://github.com/mattermost/mattermost-plugin-demo/pull/60

### CODE REVIEW

**Comment by marianunez** [comment]
Removing the `QA Review` label until `Dev Review` is complete

**Comment by marianunez** [comment]
@prapti you can try to test again now with these latest changes

**Comment by prapti** [comment]
@marianunez Working now!!

**Comment by marianunez** [comment]
@Lisenish could you update and merge your branch with latest master? After that we should be able to merge your changes in 🤗

**Comment by Lisenish** [comment]
@marianunez Sure, done it

**Pull request merged**
