### PR TITLE
Admin onboarding tutorial tour

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@matthewbirtch @esethna We can test new onBoarding tutorial here (old one will no longer be available even for regular users). Right now it will show as soon as user login will add few conditions to that.

**Comment by matthewbirtch** [comment]
@AshishDhama I just tried to test using the `sysadmin` user and it opened right to the 'Customize your experience' tour point. I assume that's because this user previously completed the first 4 tour points? 

For now, I'll create a new user to go through the steps, but I'll need instructions for resetting the sysadmin user. Let me know!

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
**Tour point 1**
- Can you remove the bottom margin from the last paragraph? It's causing extra space under the last paragraph
- Can we please reposition the arrow so that it sits more at the top of the container (as designed below)
image

**Tour point 2**
- Ideally, I'd like to open the menu first and have the tour point open up slightly delayed right after
- As you noted, there is an awkward transition with the background overlay here
- Can you remove the margin on the bottom of the paragraph to reduce the white space under the paragraph
- Can we adjust the positioning of the arrow and the pulsing do to be aligned as in the design? (design below)
image
 
**Tour point 3**
- Can you remove the margin on the bottom of the paragraph to reduce the white space under the paragraph
- Can we adjust the positioning of the arrow and the pulsing do to be aligned as in the design? (design below)
image

**Tour point 4**
- Because the Getting Started screen is still there, it initially prevented me from seeing this tour point. I assume this will be resolved once Getting Started is removed (not sure who's owning that piece).
- Can we reduce the space under the preset message chips? It looks like we can remove at least 32px
- Can we adjust the positioning of the arrow and the pulsing do to be aligned as in the design? (design below)
image

**Tour point 5**
- Can you remove the margin on the bottom of the paragraph to reduce the white space under the paragraph (for any tour point, the last paragraph should have the margin removed)
- Can we adjust the positioning of the arrow and the pulsing do to be aligned as in the design? (design below)
image

**In general**
- love the animations - those are working great
- as you noted, we need to fix the behavior for clicking the dots

**Comment by AshishDhama** [comment]
@matthewbirtch Closing this in favour of https://github.com/mattermost/mattermost-webapp/pull/9774, Will add all the changes requested by you here in that.

**Pull request closed without merging**
