### PR TITLE
MM-T256 Mark as Unread New Messages line

### PR DESCRIPTION
**Pull request by openmohan**
#### Summary

MM-T256 Mark as Unread New Messages line

#### Ticket Link

[MM-T256](https://automation-test-cases.vercel.app/test/MM-T256)

### CODE REVIEW

**Comment by prapti** [comment]
@openmohan The PR needs needs to sync before I can merge, and the auto update command is not working here. Would it be possible to update the PR branch? That would be very helpful! Sorry for the trouble, but thank you in advance!

**Comment by openmohan** [comment]
Thanks for the reviews @prapti 

rebased with the updated master branch.

**Pull request merged**
