### PR TITLE
MM-35719: CRT, shows following when single message

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Changes:
    - It shows thread footer also in the case of: no replies but the
      message is followed.

Adds:
    - It shows a "following" button in the thread footer
    when a single message is followed.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-35719

#### Screenshots

image

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Makes sense -- is there an opportunity to extend unit tests?

**Review by calebroseland — APPROVED** [review]

**Comment by calebroseland** [comment]
cc @jgilliam17 / @ogi-m

**Comment by jgilliam17** [comment]
Thanks @koox00 
Verified "Following" button in the footer area. 
Seeing one issue with the "Following" button - it disappears after post is edited.

**Comment by koox00** [comment]
> Seeing one issue with the "Following" button - it disappears after post is edited.

Thanks!!

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Tested looks good to merge.
- Verified Follow button for single message.
Issue with button being removed for edited posts will be addressed in the server PR .

**Pull request merged**
