### PR TITLE
[MM-48542] Remove integrations limits and usage

### PR DESCRIPTION
**Pull request by javaguirre**
#### Summary

This PR removes all integrations limits and usage.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48542

#### Related Pull Requests

- [Has server changes](https://github.com/mattermost/mattermost-server/pull/21282)

#### Release Note

```release-note
Removes all integration limits and usage limit components in the billing UI.
```

### CODE REVIEW

**Comment by javaguirre** [comment]
I couldn't test how it's seen in the billing section because I don't have an enterprise license (the trial doesn't work on my machine either) to see it, but I'll try to get it to test this.

**Comment by javaguirre** [comment]
Solved the license problem!

**Review by Afsoon — CHANGES_REQUESTED** [review]
LGTM, I will add the missing texts that should be change or removed, this has been merged recently. The texts are located in `freemium_modal.tsx`:

 - Remove the key `LimitTypes.enabledIntegrations` from the `DescriptionMessages` variable. Also Remove the unit test that check that this text exist when the limit is surpassed.
 - Remove the mention of apps in the translation key `cloud_delinquency.modal.workspace_downgraded_freemium`

**Comment by neallred** [comment]
Ditto that there's some more removal needed. I know this feature kind of sprawls throughout the webapp, so I made a PR with everything additional I could find or think of: https://github.com/mattermost/mattermost-webapp/pull/11351

**Comment by javaguirre** [comment]
Great! Thank you! How do we proceed with all the changes? Should we merge both prs so it's easier to QA or continue in your pr?

**Comment by neallred** [comment]
my pr is a PR into your branch, so if you like it you can approve and merge it.

**Comment by javaguirre** [comment]
Thank you! I was reviewing it in the phone and didn't see that 🙂

**Review by neallred — APPROVED** [review]
LGTM, thanks @javaguirre !

**Review by Afsoon — APPROVED** [review]
thanks @javaguirre

**Comment by javaguirre** [comment]
Friendly reminder @DHaussermann :-)

**Pull request merged**
