### PR TITLE
Allow selecting JPEG pics with .jpeg extension

### PR DESCRIPTION
**Pull request by masonicboom**
Tested by editing DOM in browser web inspector to replicate this change.

Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
[A brief description of what this pull request does.]

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by masonicboom** [comment]
I signed the CLA

**Comment by jasonblais** [comment]
Thanks @masonicboom! Looks like the build doesn't pass, can you help take a look?

**Comment by masonicboom** [comment]
Ah. Snapshot tests. Should build now

**Comment by esethna** [comment]
@masonicboom looks like there's still a build failure, can you help investigate when you have a chance?

**Comment by jasonblais** [comment]
Hey @masonicboom - looks like a recent rebase might have pulled additional commits to your branch.

Let us know if you need any help resolving that, would be more than happy to help. Thanks for your contribution!

**Comment by esethna** [comment]
@masonicboom just checking in, let us know if we can help with anything

**Comment by masonicboom** [comment]
Got busy. Will get back to this when I get a chance

**Comment by esethna** [comment]
Hey @masonicboom, let me know if you have any questions :)

**Comment by esethna** [comment]
@masonicboom feel free to reopen if you're interested in taking this on again :)

**Pull request closed without merging**
