### PR TITLE
MM-26801 Update mattermost-redux to sort muted channels to bottom on new sidebar

### PR DESCRIPTION
**Pull request by hmhealey**
The actual functional changes are in the redux PR.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-26801

#### Related Pull Requests
https://github.com/mattermost/mattermost-redux/pull/1199

### CODE REVIEW

**Comment by hmhealey** [comment]
When this is cherry-picked onto the release branch, the mattermost-redux commit needs to be updated to `8440eccb5d940ee3ae9983790cefb618d305619b`

**Comment by prapti** [comment]
@hmhealey The channels are not reordered upon refresh so that the muted channels are at the bottom. I'm testing this on the PR test server as well as locally, but both have the muted channel in their original position even after refreshing (please see the screenshot). Am I missing anything?

Screen Shot 2020-07-22 at 4 34 19 PM

**Comment by hmhealey** [comment]
@prapti It looks like the Channels category on that user got switched to manual sorting by having the channels reordered. Unfortunately, there's no way to get back to that state on that team/user. If you try on a different user or team, it should work as expected. 

If you trust me to test it myself though, I can send you a video of me testing it on the test server :smile:

**Comment by prapti** [comment]
@hmhealey Ah I see! I tested with the new team you created on the same test server and on a new cloud test server too, and can verify that it's working. But as soon as a channel is reordered, the category gets set to the manual sorting mode and there is no way to get the original "auto-sorting" back?

**Comment by hmhealey** [comment]
Yeah, that's correct. This was only intended to work briefly when the user upgrades so that their sidebar is still sorted the same way

**Comment by hmhealey** [comment]
That's good since this is already on master with https://github.com/mattermost/mattermost-webapp/pull/5447 like https://github.com/mattermost/mattermost-webapp/pull/5956 :)

**Comment by hmhealey** [comment]
The update to mattermost-redux was merged into the release branch in https://github.com/mattermost/mattermost-redux/pull/1204

**Pull request closed without merging**
