### PR TITLE
MM-29908: Show warning text if mixed versions

### PR DESCRIPTION
**Pull request by agnivade**
We show a warning text if mixed versions are found
in a cluster.

https://mattermost.atlassian.net/browse/MM-29908

```release-note
NONE
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
@agnivade Will this be immediately pop up while doing a rolling upgrade? If so, it can be a little bit confusing.

**Comment by agnivade** [comment]
Yes, it will. This is a PM requirement. Let me cc stakeholders.

**Comment by isacikgoz** [comment]
> Yes, it will. This is a PM requirement. Let me cc stakeholders.

Thanks, I was wondering if there is a way to give some time to raise this warning as it will pop out on every rolling upgrade.

**Review by isacikgoz — APPROVED** [review]
I just wanted to raise my concern whether if it would annoy people during rolling upgrades, otherwise this looks good. Feel free to ask another review if anything changes in the implementation.

**Comment by marianunez** [comment]
I don't have much context on this request - Will defer the requirements review to @wiersgallak

**Comment by wiersgallak** [comment]
@nab-77 What is your opinion on the error message showing during a rolling upgrade? Is it worth adding another sentence to the effect of "Please disregard if you are performing a rolling upgrade."

**Comment by nab-77** [comment]
I think its correct to expand this message to cover the instances were mixed-versions in a cluster are supported. I suggest something along the lines of:

`WARNING: Multiple versions of Mattermost has been detected in your HA cluster. Unless you are currently performing an upgrade please ensure all nodes in your cluster are running the same Mattermost version to avoid platform disruption.`

**Comment by agnivade** [comment]
Thanks all! I will update accordingly.

**Comment by agnivade** [comment]
@wiersgallak - PTAL

**Comment by agnivade** [comment]
ping @hmhealey

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
