### PR TITLE
Show link previews on comments but not in searches, pinned or flagged

### PR DESCRIPTION
**Pull request by jespino**
Ticket Link
-----------
mattermost/mattermost-server#7258

Checklist
---------

- [x] Has UI changes

### CODE REVIEW

**Comment by jespino** [comment]
I followed a simple solution based on removed all the "Aditional info" on search results, pinned and flagged. I can change it to pass a paramter to the "Additional info" component enabling/disabling the preview, but additional info, currently only shows the preview (I think).

**Comment by ccbrown** [comment]
We need to make sure that attachments are still shown in the search results. See https://github.com/mattermost/mattermost-server/pull/7290.

**Comment by jespino** [comment]
I will test it tomorrow and take a closer look into the code, probably the solution is a prop to enable/disable link previous and move this logic down into the child component.

**Comment by jespino** [comment]
Manually testing it looks like the attachments are shown correctly, and the links preview aren't shown (in search results/pinned/flagged) which is the expected behavior.

**Comment by jespino** [comment]
I was testing the normal attachments (a photo for example) but I'm not sure we are talking about the same type of attachment.

**Comment by jespino** [comment]
Finally I can reproduce the error, and now I can confirm the attachment aren't showing in pinned/flagged/searches. I'll fix it tomorrow.

**Comment by ccbrown** [comment]
Yeah, sorry I should have been more clear. I was referring to Slack attachments.

Thanks!

**Comment by jespino** [comment]
I finally did it now. The solution is a new prop in PostBodyAdditionalContent and pass down when is needed the links preview.

**Comment by esethna** [comment]
Hi @jespino, looks like there is a build failure and conflicts, can you please help address this when you have a chance?

**Comment by jespino** [comment]
I rebased the branch, and compiles in my machine, I have to run the tests in my machine but could be nice to have the jenkins working to see what is happening in your side.

**Comment by ccbrown** [comment]
@jespino Indeed it would be nice if Jenkins was working. At the moment, @crspeller is the only person with access to it I believe. Maybe he can get you the log. But based on experience, I can almost guarantee you it's an eslint error. Run `make check-style` and see what it says.

**Comment by jespino** [comment]
Looks like you were right. I didn't check it, sorry.

**Comment by esethna** [comment]
Apologies @jespino, looks like we have two PR's for the same ticket. Are you okay if we close this one for https://github.com/mattermost/mattermost-webapp/pull/91? Sorry about this, we should've caught it earlier.

**Comment by jespino** [comment]
It's ok, no problem, :)

**Pull request closed without merging**
