### PR TITLE
[MM 11504] Refactor scroll logic 

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Refactor scroll logic. Remove few deprecated methods

#### Ticket Link
[MM-11504](https://mattermost.atlassian.net/browse/MM-11504)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

### CODE REVIEW

**Comment by sudheerDev** [comment]
this PR needs to be rebased when https://github.com/mattermost/mattermost-webapp/pull/1464 goes in

**Comment by sudheerDev** [comment]
I could clean up scroll emits logic because of postmeta data webapp PR, lets keep this PR on hold for review till we can review that PR

**Comment by sudheerDev** [comment]
Closing this. We can revisit this based on changes for infinite scrolling

**Comment by enahum** [comment]
@sudheerDev is this PR still valid?

**Comment by sudheerDev** [comment]
@enahum Yes we would need this as the post_list is refactored. let me close this as we have a ticket we can reopen when we get to here.

**Pull request closed without merging**
