### PR TITLE
[MM-28784] Migrate string refs to functional ones

### PR DESCRIPTION
**Pull request by archit-p**
#### Summary

PR migrates all string refs in `components/searchable_channel_list.jsx` to functional refs using the `React.createRef()` function.

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-server/issues/15520
#### Related Pull Requests
None

#### Screenshots
PR doesn't make any UI changes

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by sudheerDev — APPROVED** [review]
Thank you 🎉

**Review by jgilliam17 — APPROVED** [review]
Thank you @archit-p 
Tested, looks good to merge.
- Verified More Channels modal - as expected.

**Comment by archit-p** [comment]
Thank you @sudheerDev @jgilliam17 @nevyangelova for the reviews!

**Pull request merged**
