### PR TITLE
MM-18904 Remove unused fields from state.requests.admin

### PR DESCRIPTION
**Pull request by hmhealey**
We used to track the state of every type of request in Redux in `state.requests`, but it was difficult to use and didn't support parallel requests. It also meant that basically every API request would dispatch 3-4 pointless Redux actions which wasn't great for performance as well as also adding a bunch of extra boilerplate to Redux actions. Those have mostly been removed over time in favour of just awaiting on the Redux action and having it return whether or not it succeeded (which is used pretty much everywhere now). `state.requests` has mostly been removed over time except for a few files like this one.

I also ended up updating the docs to remove the instructions to add these since most of the Redux-related docs haven't been updated in 4-5 years. See below for that PR.

This does end up with a bunch of Thunk actions which don't usually dispatch anything to change the store outside of error cases, but I think that's fine since it wraps them in a way that makes everything consistent and makes it easier to re-add stuff like that in the future.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18904

#### Related Pull Requests
https://github.com/mattermost/mattermost-developer-documentation/pull/1100

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
Wow.. were they that many 🤯

**Comment by neallred** [comment]
Code LGTM other than I think these two actions are still used (and maybe their state is still used, too?)

```
    LINK_LDAP_GROUP_FAILURE
    UNLINK_LDAP_GROUP_FAILURE
```

**Comment by hmhealey** [comment]
Yeah, those are still they're. They just moved in the file for whatever reason. I'll move them back to reduce the size of the diff

**Comment by neallred** [comment]
ahh, ok, LGTM then. Thanks, @hmhealey !

**Review by neallred — APPROVED** [review]

**Pull request merged**
