### PR TITLE
Changed mobile protocol over to mattermost-mobile and removed unused protocol detection

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Update to Deep Linking page to use new `mattermost-mobile` protocol when trying to open the mobile app.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12215

### CODE REVIEW

**Comment by esethna** [comment]
Adding QA label, it can be removed if QA wants to test after merge. Expected is that hitting the link to open in app from the landing page launched the production mattermost app (from the app stores) if installed, and goes to the post. Needs to be tested against a build of the mobile app that has the deep linking changes - hence may be easier to test after the feature complete build is cut.

**Comment by jgilliam17** [comment]
@devinbinnie I am getting an error
- I removed all the MM apps from my phone and downloaded the one @chuttam shared [here](https://community-daily.mattermost.com/core/pl/aozzd3oob7r6iyinju9jbdc9mh) shown as Mattermost Beta on my phone
- created a post with the [permalink](https://mattermost-webapp-pr-4688.test.mattermost.cloud/landing#/pr4688/pl/gsawb4nn6pfoufdcys7yamr4ro) to the test server above 
- When opening the permalink in Safari, `View in App` I get this error
IMG_5652
- When opening in mobile Chrome nothing happens, I'm left on redirect screen after `View in App`
IMG_5651

**Comment by jgilliam17** [comment]
I forgot to mention that `open this link in your browser.` works on both safari and chrome

**Comment by chuttam** [comment]
`mattermost-mobile` is the protocol for Release Candidate Mattermost mobile apps.
`mattermost-beta` is the protocol for Beta Mattermost apps.
Could this be it?

Let me work on delivering @jgilliam17 Release apps for this test.

**Comment by devinbinnie** [comment]
@jgilliam17  @chuttam Yes, you'll need a non-beta version of the app to verify that this is working correctly. Is there a build we can provide that is non-beta?

**Pull request merged**
