### PR TITLE
MM-31882 - Add CodeQL check 

### PR DESCRIPTION
**Pull request by srkgupta**
#### Summary
Added step to run automated CodeQL checks. Once this file is merged, the codeql checks will automatically be performed on new pull requests to master branch.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31882

#### Related Pull Requests
N/A

#### Screenshots
N/A

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by srkgupta** [comment]
@Willyfrog can you please review this when you have a moment. Thanks.

**Review by Willyfrog — APPROVED** [review]

**Comment by Willyfrog** [comment]
should there be any other reviewer? or is it good to merge?

**Comment by srkgupta** [comment]
Thanks @Willyfrog. Its good to merge.

**Pull request merged**
