### PR TITLE
MI-372 - updated mattermost-redux commit ID to use the latest changes

### PR DESCRIPTION
**Pull request by harshilsharma**
#### Summary
Updated mattermost-redux commit ID to use the latest changes

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by enahum** [comment]
@harshilsharma same feedback as the mobile PR

**Comment by lieut-data** [comment]
@harshilsharma, can you help resolve the merge conflicts here? I can merge and cherry-pick once we've confirmed what bits to pull in.

**Comment by harshilsharma** [comment]
@lieut-data huh, strange there conflicts were not present earlier. Doing it,

**Comment by harshilsharma** [comment]
@lieut-data someone pushed something to redux after me, and have already updated commit it in webapp. So this PR is no longer needed.

**Comment by lieut-data** [comment]
🎉 -- procrastination pays off, @enahum ;P

**Pull request closed without merging**
