### PR TITLE
MM-21325 Rework how we scroll to channels

### PR DESCRIPTION
**Pull request by hmhealey**
This combines the logic to scroll to unread channels with the logic to scroll to whatever channel you switch to. Most importantly, this gives us more control over when we actually scroll to channels (which is whenever the channel is off the edge of the channel list), but it also has the nice benefit of giving us smooth scrolling when switching to a channel from the channel switcher. 

For devs, this required diving into the SpringSystem code in the sidebar to see how that works, so I have a better idea of how it works if we're going to use it in the new sidebar.

For QA and UX, please take a look at how scrolling feels when clicking on the unread indicators, using keyboard shortcuts to switch channels, and using the channel switcher.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21325

### CODE REVIEW

**Comment by jgilliam17** [comment]
Server creation is failing. Can someone please take a look and help create a test server? Thanks.

**Comment by hmhealey** [comment]
@andrewbrown00 One specific thing to look at that might not be obvious here is that scrolling when you switch teams is now animated instead of automatic.

**Comment by bradjcoughlin** [comment]
@hmhealey can you add a gif of what this does exactly? I'm not familiar with the animation you're describing.

**Comment by hmhealey** [comment]
I don't know how to record a gif on Mac, but here's a video clip. When you switch teams, it scrolls the current channel into view with an animation.
[Screen Recording 2020-01-28 at 3.30.46 PM.mov.zip](https://github.com/mattermost/mattermost-webapp/files/4124457/Screen.Recording.2020-01-28.at.3.30.46.PM.mov.zip)

**Pull request merged**
