### PR TITLE
MM Hackathon: Sys Console Nav

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
Navigating or finding a section in System Console has always been a bit tough for me. It struck me (as a low-hanging fruit) that with only a few lines of CSS, we could increase the visual accessibility on this screen without having to do an entire redesign. 

#### What problems do these changes solve?

- Hard-to-find sections because of low contrast ratios and small font sizes.
- Distracting emphasis on categories titles (stealing attention away from sections).

#### Changes
- Sections:
  - Larger font size and kerning
  - More opaque text color (contrast ratio from 5.33 to 12.17)
  - `:hover` semi-opaque white background (ex: Channels)
  - `--active` semi-opaque primary color background
- Category Headers:
  - Smaller font size, larger kerning
  - Less opaque text color
  - Move icons to the right
(This gives context for easy scanning if your eyes are drawn to the right while scrolling. So no matter if you scan-left or scan-right, you'll more easily be able to tell what category you're in while scrolling.)

#### Screenshots
Current, New
CleanShot 2020-12-10 at 16 39 06@2x

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@calebroseland I think @michaelgamble would be better suited to review this - he's on the enterprise team and focuses more on the system console stuff. Mike, would you be ok to do that?

**Review by Willyfrog — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]
LGTM!

**Comment by michaelgamble** [comment]
@calebroseland So in my review, I would propose some more changes to affect the goals you outlined... I've pulled together a quick design to specify what I would propose as a continued iteration to the nav adjustments:

https://www.figma.com/file/gisfPNv0IU7M91qeR64fyx/System-Console-Nav-Update?node-id=1%3A355

Have a look and feel free to DM me in Mattermost if you would like to setup a quick zoom or something to discuss further.

Cheers :)

**Review by michaelgamble — CHANGES_REQUESTED** [review]
@calebroseland  So in my review, I would propose some more changes to affect the goals you outlined... I've pulled together a quick design to specify what I would propose as a continued iteration to the nav adjustments:

https://www.figma.com/file/gisfPNv0IU7M91qeR64fyx/System-Console-Nav-Update?node-id=1%3A355

Have a look and feel free to DM me in Mattermost if you would like to setup a quick zoom or something to discuss further.

Cheers :)

**Pull request closed without merging**
