### PR TITLE
Revert "MM-37916: close product switcher on item click (#8594)"

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
This reverts #8594 since it added a bug to the existing webapp.

Adding UX and QA to check for correct restoration of previous behaviour.

#### Ticket Link
[MM-37916](https://mattermost.atlassian.net/browse/MM-37916)

Tickets reporting this bug:
[MM-38019](https://mattermost.atlassian.net/browse/MM-38019)
[MM-38056](https://mattermost.atlassian.net/browse/MM-38056)
[MM-38057](https://mattermost.atlassian.net/browse/MM-38057)

#### Related Pull Requests
#8594 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]

**Comment by amyblais** [comment]
@andrewbrown00 @jgilliam17 This would be good to include for this Wednesday's cloud release.
@michelengelen Nevy is off this week so another dev may need to be tagged for this.

**Comment by andrewbrown00** [comment]
Hey, @michelengelen, I'm not sure what I'm supposed to review on this PR. I can probably be removed as I've already approved the actual PR to fix the closing popover on item click https://github.com/mattermost/mattermost-webapp/pull/8678.

**Comment by michelengelen** [comment]
@andrewbrown00 it is regarding the other popovers mentioned in the issue list. Although there really might be no need for UX review, you are right. I added to make sure that all the other Popovers are working as expected.

**Review by deanwhillier — APPROVED** [review]

**Comment by jgilliam17** [comment]
@michelengelen TimedDND feature flag is true, but the test server does not appear to have the option to set custom time. Can you please take a look? One of the tickets is for the time selector on DND. Thanks

**Comment by michelengelen** [comment]
it works for me:

Screenshot 2021-08-24 at 15 55 08

**Comment by michelengelen** [comment]
oh, that's the custom status ... sry ... i am having a look now.

**Comment by michelengelen** [comment]
@jgilliam17 it works on my local instance ... just to be sure I rebased the branch onto the current master ... if that does not fix it we should try it with a CWS server.

**Comment by jgilliam17** [comment]
Not present on this server, I'll create a CWS one

**Comment by jgilliam17** [comment]
@michelengelen not working on CWS server either, not sure what the issue could be

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified various menus are closing on click: global header menu, post menu, channel menu and other menus throughout the app. DND custom time selector menu will be tested after merge.

**Pull request merged**
