### PR TITLE
Mm 27207 e2e archived channels i 2

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

MM-T1675 CTRL/CMD+K list private archived channels you are a member of

#### Ticket Link

[MM-27207](https://mattermost.atlassian.net/browse/MM-27207)
Tests:
[https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCaseMM-T1674](MM-T1674)

#### Related Pull Requests

Requires https://github.com/mattermost/mattermost-webapp/pull/6358

### CODE REVIEW

**Comment by hmhealey** [comment]
It looks like you might've pushed something wrong. This PR includes the changes from your other one.

**Comment by Willyfrog** [comment]
> It looks like you might've pushed something wrong. This PR includes the changes from your other one.

yes, this is the continuation of that one, it only add one more test, but relies on the previous one. I'll add a do not merge label

**Comment by srkgupta** [comment]
Hi @Willyfrog 
I am confused. I am seeing the changes similar to the PR https://github.com/mattermost/mattermost-webapp/pull/6373. Can you please clarify?

**Comment by hmhealey** [comment]
Assuming I've constructed the URL right, this PR is based on the previous one so it contains both sets of changes until that's merged. You can see the changes specific to this PR here: https://github.com/Willyfrog/mattermost-webapp/compare/Willyfrog:MM-27207_e2e-archived-channels-I...MM-27207_e2e-archived-channels-I_2

**Review by hmhealey — APPROVED** [review]

**Review by srkgupta — APPROVED** [review]
Tested and all tests passed on this PR. Test LGTM. Approving the PR

**Pull request merged**
