### PR TITLE
[MM-48290] Fix white screen when guest is removed from last channel while on Threads

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
When the user is a guest and removed, while being on that page there weren't any post information until the redirect so it would throw an error.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48290

#### Related Pull Requests
N/A

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

[MM-48290]: https://mattermost.atlassian.net/browse/MM-48290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
i think this also fixes this reported issue 
> someone kicked me from a channel and my client went blank... it should send me to some other channel like town square or do _something_ other than force me to refresh my client to do anything else

**Review by M-ZubairAhmed — APPROVED** [review]
ideally `getPost` should have returned `Post | undefined`, but thats for other day to solve

**Comment by kostaspt** [comment]
> i think this also fixes this reported issue
> 
> > someone kicked me from a channel and my client went blank... it should send me to some other channel like town square or do _something_ other than force me to refresh my client to do anything else

Hmm, I don't know what the exact cause was there. I tried to replicate that now in master, and it redirects to town square while throwing this info modal:
image

But in any case, it could help if websockets went wrong for some reason and didn't go the update.

**Comment by M-ZubairAhmed** [comment]
> > i think this also fixes this reported issue
> > > someone kicked me from a channel and my client went blank... it should send me to some other channel like town square or do _something_ other than force me to refresh my client to do anything else
> 
> Hmm, I don't know what the exact cause was there. I tried to replicate that now in master, and it redirects to town square while throwing this info modal: image
> 
> But in any case, it could help if websockets went wrong for some reason and didn't go the update.

Yeah the client did mention white screen, assuming the webapp crash but i do think it could have been also caused by other reasons as well.

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected with the following steps:
1. Login as Sysadmin
2. Create channelA and guestA
3. Create a thread with sysadmin and guestA in channelA
4. login as a guestA
5. Go to thread
6. As a sysadmin, remove guestA from channelA
Result: As a guestA, (URL/newteam/threads) is not getting crash.
image

**Pull request merged**
