### PR TITLE
[MM-38189] - removed `Open...` from the product switcher menu

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
remove the first "headline" entry from the product switcher: `Open ...` since it did create some misunderstanding among users.

#### Ticket Link
[MM-38189](https://mattermost.atlassian.net/browse/MM-38189)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — APPROVED** [review]
Looks good to me @michelengelen

**Review by nevyangelova — APPROVED** [review]
LGTM

**Review by crspeller — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @michelengelen 
Tested, looks good to merge.
- Verified "Open" header item has been removed from the product switcher menu.

**Comment by amyblais** [comment]
@michelengelen @esethna Is this for v6.0?

**Comment by esethna** [comment]
@amyblais yes it is

**Pull request merged**
