### PR TITLE
[MM-37814] - Handle quick switch shortcut in channel navigator

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR removes code duplication for the quick switch modal shortcut and moves the event handlers to the sidebar. Note for QA, the quick switch key press shortcut behaviour should stay the same. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37814

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by deanwhillier — COMMENTED** [review]
LGTM in general.

I am wondering though, if we should maybe locate the keyboard shortcut functionality directly with the [UI component](components/sidebar/channel_navigator/channel_navigator.tsx) associated with the functionality? In the absence of a centralized keyboard shortcut controller/functionality, it might be best to group keyboard shortcuts with their respective UI counterparts to keep them together until a more centralized alternative becomes available!

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by michelengelen** [comment]
I agree with @deanwhillier here. We should probably group the functionality directly to the associated component. IMO In this case it is sufficient to have it in the sidebar, but we should definitely have some kind of global controller for shortcuts etc.

**Comment by nevyangelova** [comment]
That is a good point, I can move it to the channel navigator for these purposes and it can be nice to discuss a shortcut controller as well :P

**Review by michelengelen — APPROVED** [review]
LGTM!

**Review by deanwhillier — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @nevyangelova 
Tested, works good to merge.
- Verified quick switch keyboard shortcuts work as before.

**Comment by amyblais** [comment]
@nevyangelova @deanwhillier Is this for v6.0 or v6.1 or doesn't matter?

**Comment by nevyangelova** [comment]
@amyblais v.6.0

**Pull request merged**
