### PR TITLE
MM-12443 Fix multiple uploads fail issue

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Fixes multiple uploads
#### Ticket Link
[https://mattermost.atlassian.net/browse/MM-12443](MM-12443)
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Touches critical sections of the codebase (auth, posting, etc.)

oct-02-2018 19-08-15

### CODE REVIEW

**Comment by sudheerDev** [comment]
I guess this has to go into release branch but will wait for fix version that will be assigned in sprint today.
Will merge to master and release if needed at once

**Comment by enahum** [comment]
You should assign the release manager so he can merge and cherry pick if this is for 5.4

**Comment by sudheerDev** [comment]
@enahum I thought we are not doing this https://pre-release.mattermost.com/core/pl/6d8scycpa7dk983ng4ri33djpa

**Comment by enahum** [comment]
Yes you are right

**Comment by jespino** [comment]
I think this must be cherry-picked to the release branch, because we are on time, and is a bug.

**Comment by sudheerDev** [comment]
Cherrypicked to 5.4

**Pull request merged**
