### PR TITLE
PLT-8120 Move "message below" bubble to be set after update

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
The message bubble was being set in `componentWillReceiveProps()` causing the `checkBottom()` function to use the old channel's data for determining if we were at the bottom of the channel. So in some cases (specifically where the new channel had no scroll bar but had new posts) the new message bubble would get set and never disappear because we were already at the bottom of the channel.

This moves the logic/setting to `componentDidUpdate()`. The downside is that it may cause another render on initial switch, but that shouldn't be too bad since everything is a pure component and only the one small piece of state is changing.

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-8120

### CODE REVIEW

**Comment by jwilander** [comment]
@lindalumitchell would you be able to give this a quick test first? This code is a little volatile so I think it's better to test it sooner rather than wait for it get into another RC

**Comment by lindalumitchell** [comment]
@jwilander I'm happy to test. Looks like I'm getting a 404 on the spinmint though?

**Comment by jwilander** [comment]
@lindalumitchell should be fixed now

**Comment by lindalumitchell** [comment]
@jwilander the original issue looks fixed; are there other specific things I should test, or general smoke testing? I'm posting a bunch of messages and checking new messages indicators; anything else?

**Comment by jwilander** [comment]
Nope, as long as the "messages below" bubble seems to be working correctly we're all good 👍  Thanks!

**Pull request merged**
