### PR TITLE
MM-19310 - Wrong validation message when Bot name ends in a .

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Not creating Bot whose Username ends with `.`.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-19310
#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/12905

#### Screenshot
image

### CODE REVIEW

**Comment by ali-farooq0** [comment]
@prapti this is ready for testing.

**Comment by ali-farooq0** [comment]
Adding @aaronrothschild as an FYI regarding the new behaviour, which is: Users cannot create bots whose usernames ends with a period `.` (See screenshot)

**Comment by prapti** [comment]
@ali-farooq0 Can the validation message be changed from "Must not end with '.' symbol." to "Username must not end with '.' symbol."? I think it can get confusing if all fields are filled out and end with multiple .s although I don't think that will be commonly done, but the validation message will be specific to the error.

**Comment by ali-farooq0** [comment]
> @ali-farooq0 Can the validation message be changed from "Must not end with '.' symbol." to "Username must not end with '.' symbol."? I think it can get confusing if all fields are filled out and end with multiple .s although I don't think that will be commonly done, but the validation message will be specific to the error.

Agreed. Updated @prapti 👍

**Pull request merged**
