### PR TITLE
[GH-18825] Added E2E test error on blank password in password edit

### PR DESCRIPTION
**Pull request by shzmr**
#### Summary
Added E2E test error on blank password in password edit

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/18825

```release-note
NONE
```

### CODE REVIEW

**Review by furqanmlk — APPROVED** [review]
Thanks @shzmr 

Test passed locally 

image

**Comment by furqanmlk** [comment]
@shzmr can you fix the conflict please ?

**Comment by shzmr** [comment]
> @shzmr can you fix the conflict please ?

Sure

**Comment by saturninoabril** [comment]
@shzmr Oh no. Not sure if there's something wrong with Github or during your recent merged to master. Right now, it showed no file change. Please take a look again.
Screen Shot 2021-11-07 at 10 40 14 PM

**Comment by shzmr** [comment]
I think it might be because my next pull request was merged https://github.com/mattermost/mattermost-webapp/pull/9297

**Comment by saturninoabril** [comment]
Hmm, I don't think it's related since they are on a different branch. Anyway, please push a commit with the approved code changes then I'll take a look.

**Comment by shzmr** [comment]
The other PR adds the same file and also contains this test, and it was merged, so I should probably close this PR.

**Comment by saturninoabril** [comment]
Oh, I see it's included from https://github.com/mattermost/mattermost-webapp/pull/9287/files#diff-b3c361e2a036319d07833855a6580e00964028d1a7f3810d20c9b8a274afca6cR33-R52

**Pull request closed without merging**
