### PR TITLE
[MM-44793] fixes: Mobile browser Advanced text editor formatting icon size issue

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
fixes: Mobile browser Advanced text editor formatting icon size issue

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-44795
  
#### Related Pull Requests
NONE

#### Screenshots
|  before  |  after  |
|----|----|
| image-20220603-153951 | Screenshot 2022-06-04 at 1 08 34 AM |

#### Release Note
```release-note
fixes: Mobile browser Advanced text editor formatting icon size issue
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
Hmm. Didn't know you could use attrs with className like that. 
The only critique here would be that this breaks the encapsulation of styled components making it dependent on css outside itself.

**Comment by AshishDhama** [comment]
> Hmm. Didn't know you could use attrs with className like that. The only critique here would be that this breaks the encapsulation of styled components making it dependent on css outside itself.

@crspeller Okay makes sense I think then the only option is to copy-paste the required CSS, passing this class like below
```
        <IconContainer
            type='button'
            id={`FormattingControl_${mode}`}
            onClick={onClick}
            classname={'style--none' + classname}
            {...otherProps}
        >
```
Doesn’t work. I am 0/5 if you suggest copy-paste will do that it’s just 3 properties.

**Review by Willyfrog — APPROVED** [review]

**Comment by Willyfrog** [comment]
Looks good on chrome and safari🚀

**Comment by AshishDhama** [comment]
@jgilliam17 This is ready for review.

**Comment by jgilliam17** [comment]
Thanks @AshishDhama 
Tested, looks good to merge.
- Verified formatting icons when using mobile browser - as expected.
- We're currently blocked on running e2es - approving without the report, not blocking this PR as the change is small. I will follow up and file failures, if any, after merge.
- Added an issue for follow up [MM-44855](https://mattermost.atlassian.net/browse/MM-44855)

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
