### PR TITLE
Add OIDC to the sign up page

### PR DESCRIPTION
**Pull request by phpfs**
#### Summary
Since at least 6.x, the sign up page (where invitation links take new users) does not include an OIDC button despite other openid providers like Google or Gitlab are present. In practice, this will lead to an error page stating "This server doesn’t have any sign-in methods enabled" in case only OIDC is active on a MM server. Since the invitation link generated within the UI leads new users to the sign up page, they will be very confused and contact the administrator (like stated on that page). On the other hand, the login page always displays OIDC correctly as an authentication method.

To restore expected behavior, code is added as part of this PR to make the necessary button available within the `signup.tsx` (based upon similar behavior in `login.tsx`). Test were adapted and all test suites (& linters) are happy.

#### Ticket Link
(pending)

#### Related Pull Requests
None

#### Screenshots

|  before  |  after  |
|----|----|
| before-oidc-on  | after-oidc |

#### Release Note

```release-note
Added the OpenID Connect authentication button to the sign up page
```

### CODE REVIEW

**Comment by hmhealey** [comment]
@phpfs Thanks for the PR! As mentioned by mattermod, you'll need to accept the CLA for us to be able to merge this.

@sbishel Feel free to re-assign this if another team (probably Suite Users) should be owning this feature, but I'm not sure what the intended use case of OpenID is vs OAuth or if that's something we meant to expose on the login screen.

**Comment by matthewbirtch** [comment]
@stevemudie I was able to get the Open ID Connect button to show on the test server above, but it's not a properly configured Open ID Connect - I just used dummy data. Are you able to set it up properly so we can see the full flow of creating an account with OIDC on this PR?

**Comment by julmondragon** [comment]
@dontoisme @matthewbirtch  Added ticket https://mattermost.atlassian.net/browse/MM-46240

**Comment by stevemudie** [comment]
> @stevemudie I was able to get the Open ID Connect button to show on the test server above, but it's not a properly configured Open ID Connect - I just used dummy data. Are you able to set it up properly so we can see the full flow of creating an account with OIDC on this PR?

@matthewbirtch Unfortunately, I'm not familiar with a way to set up an OIDC connection with which we can test the full flow.

As long as the button appears where we expect it then past that point we're relying on the underlying mechanism of that type of connection in the app which should just work right?

**Review by pvev — APPROVED** [review]
LGTM! thanks @phpfs :shipit:

**Review by matthewbirtch — APPROVED** [review]
I'm going to approve this assuming the Open ID flow is all handled correctly. From my perspective, the Open ID button is placed correctly and looks good, but can't full test the Open ID flow without it being set up

**Comment by phpfs** [comment]
> I'm going to approve this assuming the Open ID flow is all handled correctly. From my perspective, the Open ID button is placed correctly and looks good, but can't full test the Open ID flow without it being set up

@matthewbirtch We validated the OIDC flow in 7.1.2 and it worked :)

**Review by stevemudie — APPROVED** [review]
This looks good and is ready to go.

**Pull request merged**
