### PR TITLE
[MM-46567] - Self-Hosted admin: Add User Group in Product Switcher with CTA to start a trial

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR introduces the restriction indicator for self hosted admins trying to access user groups but are on starter

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46567

#### Screenshots
Screenshot 2022-10-04 at 15 01 47

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @AGMETEOR !

**Review by julmondragon — APPROVED** [review]
Looks good!

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
completed manual check Allan.

**Pull request merged**
