### PR TITLE
[PLT-8177] Fix multiple files upload error

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix multiple files upload error

#### Ticket Link
Jira ticket: [PLT-8177](https://mattermost.atlassian.net/browse/PLT-8177)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by saturninoabril** [comment]
Yes, not migrated yet. Original problem was that the object was said to be frozen and immutable. `Draft` is coming from BrowserStore.
I'm not totally sure why it's failing that way.
It's just a quick fix and might change once migrated.

**Comment by enahum** [comment]
@saturninoabril I don't quite get it, what does FilePreview with those objects, does it modify them somehow? this will make the FilePreview component to re-render every time as the props will always be different and that might affect performance, I think you need to look were the object is being modified and fix that

**Comment by saturninoabril** [comment]
The error is rooted from here - https://github.com/mattermost/mattermost-webapp/blob/master/stores/browser_store.jsx#L30 - but couldn't figure out why. 
I'll check once again.

**Comment by sudheerDev** [comment]
@saturninoabril I think it is from this line https://github.com/mattermost/mattermost-webapp/blob/05f2eb0cc4a2c91aa4a99de8d117c2e48eca3a9c/components/file_preview.jsx#L44

I changed it in this PR https://github.com/mattermost/mattermost-webapp/pull/210. I don't see any issues with that on my branch now though.

**Comment by saturninoabril** [comment]
@sudheerDev Thanks for the input!

@enahum I'm actually not sure. `FilePreview` does not modify the object but it's receiving a frozen object. I suspect that React prevents re-render whenever that frozen object changed from parent component (in this case either from `CreateComment` or `CreatePost`). So, the solution could be: 
- clone the object before passing into `FilePreview` (my initial commit),
- render `FilePreview` using cloned object (@sudheerDev  solution),
- clone the object into state of `FilePreview` (my second commit).

Any thoughts?

**Comment by enahum** [comment]
Well I don’t have a strong opinion on how to fix it but my onmy concern is that the object is getting modified somewhere and I would not be surprised if that causes any other issues, so go ahead make your fix and then if it causes other problems we can look deeper into it

**Comment by saturninoabril** [comment]
Thanks! I'll keep an eye on future issue.

@sudheerDev Sorry but I'll go and merge this. Please rebase your PR.

**Comment by sudheerDev** [comment]
@saturninoabril Just a note: if we can avoid state then we can replace that with stateless components later.

**Pull request merged**
