### PR TITLE
fix add bot error handling

### PR DESCRIPTION
**Pull request by LeonardJouve**
#### Summary
This pr fixes the add bot error handling.
Currently, if the user uploads a file larger than the config MaxFileSize for a bot profile picture, the error message is diplayed and instantly removed.
This is a bit difficult to reproduce on community.mattermost since MaxFileSize is 100mo.
But if it is a self hosted mattermost server with low MaxFileSize, the user might not understand why his bot profile picture did not change.

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
fix add bot error handling
```

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@DHaussermann gentle ping

**Comment by M-ZubairAhmed** [comment]
Hey there!, Thank you for your PR.
Webapp is now part of mattermost monorepo now at https://github.com/mattermost/mattermost-server/tree/master/webapp Would you be interested in opening the PR over there?

**Comment by hmhealey** [comment]
The web app now lives in the `webapp/channels` over in https://github.com/mattermost/mattermost-server. We decided to move it to be a monorepo to make both development and our CI pipelines easier, but it's unfortunately disruptive right now. We've updated [our setup docs](https://developers.mattermost.com/contribute/developer-setup/) and added [some steps for migrating to working with the monorepo](https://developers.mattermost.com/contribute/monorepo-migration-notes/).

Copying the changes over there hopefully shouldn't be too hard. There's a few changes to file paths (such as the code living in a dedicated `src` subdirectory), but most things should look the same as they do now. 

Let us know if you could use any help with this. Hopefully the process is smooth.

**Comment by LeonardJouve** [comment]
Hey, okay I'll do it soon

**Comment by hmhealey** [comment]
Thanks!

**Pull request closed without merging**
