### PR TITLE
[MM-49973] Bot and guest tags truncated on suggestion autocomplete

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
The `flex` rule in the row caused unexpected shrinkage of the tag, deviating from the desired functionality.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49973

#### Related Pull Requests
N/A

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot 2023-01-30 at 13 02 48  | Screenshot 2023-01-30 at 13 03 14 |

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by plant99 — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Thanks @kostaspt 
Working as expected
image

**Pull request merged**
