### PR TITLE
[MM-26973] Add disable gif setting

### LINKED ISSUE #17740: Account Setting for disabling GIF and emoji animation
Introduce a new setting in Account Settings > Display, below "website link previews":

**Allow animated images and emoji**
on < x ]
off [   >
When enabled, emoji and GIF Images will be allowed to animate.

Functionality: 
On: Autoplay GIFs and animated custom emoji 
Off: GIFs and animated emoji will appear as static images. GIFs will be playable by clicking (See https://mattermost.atlassian.net/browse/MM-26973)

WCAG guidelines: [https://www.w3.org/TR/WCAG20-TECHS/G152.html](https://www.w3.org/TR/WCAG20-TECHS/G152.html)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-22242

### LINKED ISSUE #20860: Provide setting to pause animated emoji and GIF
This ticket is to add a new account setting in Advanced called:

**Automatically play GIFs and animated emoji**

[ x ] On
[    ] Off

Help text: When disabled, GIFs and animated emoji will not play automatically.  

*_____*

Functionality: When the above setting is “Off”:

- custom emoji that are animated should be static based on the first frame
- GIFs should also be static based on the first frame with a button to start playing, see design below + [Figma](https://www.figma.com/file/7psXW8qYfp0LZTBT1ZWvkO/Gif-Controls?node-id=48%3A6768):

Note: See the related ticket for pausing GIFs after 6 plays (even when this animation setting is enabled) [https://mattermost.atlassian.net/browse/MM-26973](https://mattermost.atlassian.net/browse/MM-26973|smart-link) 

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-16478

### PR DESCRIPTION
**Pull request by AbhinavVihan**
#### Summary
Add disable setting for gif.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/17740
  Fixes https://github.com/mattermost/mattermost-server/issues/20860

#### Related Pull Requests
None

#### Release Note

```release-note
*Add disable gif setting

```

### CODE REVIEW

**Comment by esethna** [comment]
Thanks for the PR @AbhinavVihan! Please help resolve conflicts as needed and we will start the review process

**Review by esethna — CHANGES_REQUESTED** [review]
@AbhinavVihan I'm seeing an issue where gifs aren't playing (even with the setting on)

Please also see the original issue for the help text and setting name that should be used

**Comment by AbhinavVihan** [comment]
conflicts have been resolved

**Comment by AbhinavVihan** [comment]
And also, should this behaviour be true for the link adressess of gifs's previews

**Comment by AshishDhama** [comment]
@esethna Could you please take another look?

**Comment by matthewbirtch** [comment]
@AbhinavVihan the setting seems to be working for emojis within messages, and attached GIFs, but not in the following cases:
1. Inline Markdown GIF images
2. Emoji reactions - animated emojis still animate when the setting is off
3. Custom status emojis - wherever these display, they still animate when the setting is off

A few other things:
- In the setting, can we Captialize `On` and `Off` to be consistent with other settings?
- It looks like clicking an attached GIF plays the GIF rather than opening the preview modal. Can we just open the preview modal and play the gif within the modal context?

**Comment by matthewbirtch** [comment]
Is this ready for a re-review @AbhinavVihan?

**Comment by AbhinavVihan** [comment]
yeah, but few more changes i would like to make,
i'll let u know.
it that fine?

**Comment by matthewbirtch** [comment]
> yeah, but few more changes i would like to make, i'll let u know. is that fine?

Sounds good. Thanks! Just checking in. No rush.

**Comment by esethna** [comment]
@AbhinavVihan let us know when this ready for re-review. Thanks for your contributions!

**Comment by AbhinavVihan** [comment]
Hi @esethna  it's ready for re-review

**Comment by AbhinavVihan** [comment]
Hi @esethna, @AshishDhama, the setting is working fine for everything except the (Inline Markdown GIF images). 
But that too is working as expected on my local but not on the SpinWick test server ¯\_(ツ)_/¯

**Comment by esethna** [comment]
Hi @AbhinavVihan,

The setting doesn't seem to be taking effect for me in the test server, I'm still seeing even image link previews animating when the setting is off.

Also please note the expected text should be exactly as written in the issue:

image

Test server:
image

Thanks!

**Comment by AbhinavVihan** [comment]
The still image that i am generating seems to be blocked by the CORS policy that's why the image link previews and inline markdown images are not pausing even when the setting is off.
It is taking the actual src of previews and ... as a fallback.

**Comment by esethna** [comment]
@AbhinavVihan do you need any help or guidance here?

**Comment by AbhinavVihan** [comment]
@esethna, yes please, if someone worked on something like this.
Some help would be great
Thankyou

**Comment by esethna** [comment]
@Willyfrog any thoughts or help you can provide here?

**Comment by Willyfrog** [comment]
Have you tried on local? do you have the same results or different ones?

by enabling the dev tools, you can disable the cache and it still happens, there is a second request that succeeds and brings the gif, that's why I consider there might be something else at play, especially since there seems to be some cloudflare cookie going on.

But if we can detect the failure, we can always do a fallback, although this is not perfect as it might render images as unavailable. 

With that said, I'm still not sure why is it using the gif original url instead of the data one, even if we are fetching the info from the cache, it should later use the data url instead, but it is still relying on the original one. Maybe something is throwing and something else is catching the error? just a theory.

Sadly I can't provide much insight on this, maybe @hmhealey can help better.

**Comment by AbhinavVihan** [comment]
@Willyfrog, Thank you for all the information.
And yes, everything works fine for me on the local.

**Comment by esethna** [comment]
@AbhinavVihan let us know when this is ready for re-review

**Comment by AbhinavVihan** [comment]
@esethna, @AshishDhama , its ready for re-review. Thankyou

**Review by matthewbirtch — APPROVED** [review]
Looks good to me!

**Comment by hmhealey** [comment]
Sorry for the delay. So the issue is that, without an image proxy enabled, we can't read from the canvas after loading the image to get its first frame. Is that correct?

If so, that's odd to me that that's the case here but not when we're just showing an external image in an `img` tag. There must be security implications with canvases that I don't understand here since I haven't used them much myself. Setting the `cross-origin` attribute on the image that we're loading sounds promising to solve that though.

We should probably get a security review on this as well then since they're probably more familiar with the implications of doing this though. They'll also be better at finding a way to break it as well

**Comment by Willyfrog** [comment]
After discussing with security, seems that this approach is not entirely possible as it would require a proxy to work or to have the server hosting the gif to allow for CORS (which is impossible from a practical perspective)

One option suggested is since we draw the still image from the gif into a canvas already, we could use that canvas directly into the DOM. Would that help?

**Comment by hmhealey** [comment]
> After discussing with security, seems that this approach is not entirely possible as it would require a proxy to work or to have the server hosting the gif to allow for CORS (which is impossible from a practical perspective)

Not directly related to this PR, but one of these days, we should really think about enabling the local image proxy by default again since, if we'd been able to do that previously, I don't think we'd have an issue here. Unfortunately, that's an area that no one's really been working on, so it hasn't come up again.

**Comment by Willyfrog** [comment]
> Not directly related to this PR, but one of these days, we should really think about enabling the local image proxy by default again since, if we'd been able to do that previously, I don't think we'd have an issue here. Unfortunately, that's an area that no one's really been working on, so it hasn't come up again.

I'd like to discuss that further

@AbhinavVihan does the security suggestion helped figure it out? is there anything else we can do to help?

**Comment by birgitadyen** [comment]
@AbhinavVihan any change you can pick this up again? I can't contribute (sorry), but this feature would be amazing to have, since animated emoji are very difficult for my brain to deal with.

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Comment by esethna** [comment]
Hey @AbhinavVihan. Regarding the comment above, let us know if you have any interest in resubmitting this against the server repo? Apologies this PR got caught in the middle.

**Comment by ThiefMaster** [comment]
One of my Mattermost users would really appreciate this feature. So it'd be certainly nice if you reopened this PR and worked with the Mattermost guys to get it to a state where it can get merged :)

**Comment by ltning** [comment]
@esethna How about - given the amount of time passed - someone on your team do the forklifting? The original contributor may no longer be interested or able to start over, which is entirely fair, and the rest of us waiting for this to be merged are not really in a position (nor should we be expected) to submit this PR on behalf of someone else.

The feature is quite important for accessibility, and a bonus for energy-efficiency. So here's my Pretty Please, for whatever little it's worth..

**Pull request closed without merging**
