### PR TITLE
Add the autofocus into the login field in login page

### PR DESCRIPTION
**Pull request by leblanc-simon**
#### Summary
For better UX, in the login page, add the autofocus into the login field

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

### CODE REVIEW

**Comment by esethna** [comment]
Awesome, thanks @leblanc-simon!

**Comment by hmhealey** [comment]
@esethna Did you test this on the classic mobile apps? I'm a bit worried if this'll make the login screen behave weirdly for them

**Comment by saturninoabril** [comment]
@leblanc-simon Thanks for your contribution. Please rebase to latest and fix conflicts, then we can merge this.

**Comment by leblanc-simon** [comment]
rebase done.
Thanks for your work !

**Comment by jwilander** [comment]
Much thanks @leblanc-simon! Sorry for the late merge, we were waiting for the release branch to get cut

**Pull request merged**
