### PR TITLE
MM-25889 - Restored announcement type for email verification

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary
Restored `AnnouncementType` for announcement banner when email has been verified that was mistakenly removed during [typescript migration](https://github.com/mattermost/mattermost-webapp/pull/5426). 

#### Ticket Link
[MM-25889](https://mattermost.atlassian.net/browse/MM-25889)

### CODE REVIEW

**Comment by marianunez** [comment]
@amyblais This is a fix for a minor regression from v5.23. It might be a bit late but the change is very low impact, should we cherry pick this for 5.24?

**Comment by amyblais** [comment]
That should fine as long as this won't lead to new regressions.

**Comment by marianunez** [comment]
> We might need to cast the first argument to `logError` as an `any`, and we'll look into fixing `logError` at a later date.

Thanks @devinbinnie! I've updated the PR, hope the linter is happy now.

**Comment by amyblais** [comment]
On further discussion with Jesse we can push to v5.25 as we're past code freeze,

**Pull request merged**
