### PR TITLE
Promote Romanian from Beta

### PR DESCRIPTION
**Pull request by jasonblais**
/cc @uhlhosting

### CODE REVIEW

**Comment by jasonblais** [comment]
Hm, not sure why the build would fail.

**Comment by cpanato** [comment]
need to update the snapshot tests

**Comment by jasonblais** [comment]
Thanks, looks like I missed one of the entries for snapshot tests, updated

**Comment by jasonblais** [comment]
Tests pass, this is ready to merge @cpanato or @enahum

**Pull request merged**
