### PR TITLE
Fix tomorrow option in DND expiry and add options translations

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary
Display ending time for DND tomorrow expiry option.
I've also changed the computed ending time as it was set as 23:59:59 the next day but ticket asks to show (and so set) it as tomorrow same hour.

I've also took the opportunity to add options translations (for En and Fr) as it was not the case ATM

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/17732
JIRA: https://mattermost.atlassian.net/browse/MM-35885

#### Screenshots

tomorrow

#### Release Note
```release-note
Do Not Disturb option for Tomorrow now displays the expiry time.
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
Thanks @KuSh, this looks great!
One thing you'll have to do to fix the `i18n-check` error is add the translations you need in file using the `t()` marker function

**Comment by nevyangelova** [comment]
thanks @KuSh for the awesome change! You can also fix the i18n error by arranging the new keys alphabetically. Hope that helps!

**Comment by KuSh** [comment]
Thanks @nevyangelova , sorting keys wasn't enough but I did reference them with `t()` as suggested by @devinbinnie and it seems to be OK now (too bad there's no make i18n-check ^^)

**Comment by KuSh** [comment]
I think my change broke the css selector. I'll fix that ASAP

**Comment by KuSh** [comment]
This is now fixed. I've also fixed e2e tests but wasn't able to locally run `status_dnd_1_spec.js` as it requires TimedDND feature flag to be true and I didn't find how to enable that (I did add a FeatureFlagTimedDND entry in ServiceSettings in config/config.json but that didn't make it and I didn't found any documentation about that feature flag)

**Comment by nevyangelova** [comment]
> Thanks @nevyangelova , sorting keys wasn't enough but I did reference them with `t()` as suggested by @devinbinnie and it seems to be OK now (too bad there's no make i18n-check ^^)

That's a good suggestion to add the new check, thanks!

**Review by nevyangelova — APPROVED** [review]

**Comment by jgilliam17** [comment]
Additionally: Tomorrow option is not selectable

**Comment by KuSh** [comment]
Hi @jgilliam17 
> Thank you for your contribution @KuSh Seeing few small issues Can you please update the text? Per linked ticket we should only show abbreviated day of the week and expiry time e.g. `Thu, 9:00 AM`

I used Timestamp component which takes into account some options (notably the USE_MILITARY_TIME one that display hours in 12 or 24h format). I'll see what I can do to fix that 👍

> Screen Shot 2021-11-03 at 11 48 20 AM
> 
> We should also add some spacing or keep the expiry info right align to avoid crowding of the menu item.
> Screen Shot 2021-11-03 at 11 36 18 AM
> 
> Screen Shot 2021-11-03 at 11 38 09 AM
I'll fix that. I did base my change on another dnd related PR I did and used the wrong id for css selector. I'll  also add a non breaking space before the date to ensure at least words separation if space is limited.
But it seems this one will need to wait for my other PR to be merged or it will break  :/

**Comment by KuSh** [comment]
Ok. Everything is taken into account.
Last commit is for fixing option not selectable. The problem was submenu is accepting a ReactNode as text prop but was considering it was always a string in onClick handler.
I've simplified the check and I hope it won't break anything. I've run all unit tests plus every e2e tests whose name contains "menu" or "dnd" and didn't found anything wrong. But I can't help thinking that code I removed was certainly there for a good reason .. I just can't find why

**Comment by jgilliam17** [comment]
@nevyangelova @devinbinnie Since there were few additional changes after your review, can you please take another look at this PR? Thanks

**Comment by jgilliam17** [comment]
Note: [E2E test results ](https://mattermost-cypress-report.s3.amazonaws.com/53546-339fa02-ee-ent-webapp-pr-9295-mm-ee-test:339fa02/mochawesome.html) look good, current failures don't appear to be related to this PR when compared to results from [master run](https://mattermost-cypress-report.s3.amazonaws.com/53442-f7019fb-master-mm-ee-test:test/mochawesome.html)

**Comment by KuSh** [comment]
Rebased to fix conflict

**Review by nevyangelova — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]

**Pull request merged**
