### PR TITLE
[MM-41281] Change crt tour trigger condition and save onBoarding auto tour status in preferences

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Change CRT tour trigger condition and save onBoarding auto tour status in preferences

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-41281

#### Related Pull Requests
Webapp: https://github.com/mattermost/mattermost-webapp/pull/9289

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by esethna — APPROVED** [review]

**Comment by esethna** [comment]
Thanks Ashish. I removed the QA deferred label as I'd like to have @jgilliam17 test this to ensure there are no issues with this conflicting with the regular onboarding tutorial.

**Review by koox00 — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @AshishDhama 
Tested, looks good to merge - pending E2E report.
- CRT tour triggers only once for each user; Tour does not interfere with onboarding tutorial

**Review by jgilliam17 — APPROVED** [review]
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/109343-dd274a3-onprem-ent-webapp-pr-9700-mattermost/mm-ee-testdd274a3/mochawesome.html) looks good, no PR related failures.

**Pull request merged**
