### PR TITLE
[MM-41841] Changing group icon for mention suggestion

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Replacing the icons for @ group suggestions

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41841

#### Screenshots
Screen Shot 2022-02-17 at 2 09 13 PM

#### Release Note

```release-note
Updating the @ mention icon for groups
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by mylonsuren — APPROVED** [review]
Looks good, just looks like the linter is failing on `Icon` being an unused import.

**Comment by furqanmlk** [comment]
e2e-test

**Review by furqanmlk — APPROVED** [review]
Working as expected.

**Before**
image

**After**

image

**Pull request merged**
