### PR TITLE
MM-30139 Cypress/E2E: Force retry when test executions failed on internal server error

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Force retries (until CI timeout) when test executions failed on internal server error

#### Ticket Link
Jira ticket - https://mattermost.atlassian.net/browse/MM-30139

#### Screenshots
Screen Shot 2020-10-30 at 3 51 26 PM

### CODE REVIEW

**Comment by saturninoabril** [comment]
@amyblais I'm requesting to cherry-pick this into release-5.29 so that we'll be able to consistently save test results from Cypress to TM4J. No side-effect to product.

**Comment by amyblais** [comment]
Sounds good, thanks @saturninoabril!

**Review by srkgupta — CHANGES_REQUESTED** [review]
Hi @saturninoabril 
Can we add a max retry of upto 3 or 5 times. Currently this goes on forever and it might be stuck if there is something wrong somewhere. 

Oops. Looking at the screenshot, it takes around 16 retries for it to succeed. Please ignore my previous suggestion of 3-5 retries. But can we at least try for a definite amount of retries? Pl

**Comment by saturninoabril** [comment]
Unfortunately, I ended up a force retry like "retry until fail due to timeout in CI, usually up to 10 minutes" and try to save as much as possible.

**Comment by srkgupta** [comment]
> Unfortunately, I ended up a force retry like "retry until fail due to timeout in CI, usually up to 10 minutes" and try to save as much as possible.

Each test taking upto 10 mins (in worst case) sounds a lot. Can we retry max of say 25 or 40 times to begin with?

**Comment by saturninoabril** [comment]
Ah, I see where you're going to and I'd say it's not how it works. Saving test results has its own job/step with 10 mins default timeout. Worst case is 10 mins for all the tests (not per test) but as I observed it, its max saving time is 20 seconds. My suggestion is to go on max timeout and limit retry count in the future only if needed. Currently, I'm 3/5 to have it as is.

**Review by srkgupta — APPROVED** [review]
Thanks for the clarification @saturninoabril. That's fine then. LGTM

**Review by josephbaylon — APPROVED** [review]
LGTM. Ah this only retries saving of test executions and not retrying test execution itself. The title got me.

**Pull request merged**
