### PR TITLE
MM 18641 Keep the loading indicator at the center when loading images

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Adding a fit-content property to provide a way for svg to scale in the available space. This available space is used for centre aligning the loader 

This isn't working on master anymore and i don't think this would have catered to all the scenarios of image loaders previously because the svg inside the container used for positioning the image does not have the exact same dimensions(It takes up more space at times but the parent overflow prevents it from causing scroll pop).

Nov-08-2019 16-07-29

In the above gif without ` width: fit-content;` the svg overflows in parent container hence it wont be able to centre align the loading indicator. This wont cause a scroll pop because the overflow is taken care by the parent.

Scaling an svg in a container and maintaining aspect ratio is not possible without specifying an width on the parent and we cannot provide one because we need it to be responsive(width 100% wont work for inline images with markdown and text). 

Using ` width: fit-content;` we can make this work but there is no support on edge so we cannot support this feature on edge.
 
Note: This will not work on edge ATM and fallbacks to existing behaviour of loader at the center of channel

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18641

### CODE REVIEW

**Comment by sudheerDev** [comment]
@asaadmahmood Thoughts?

**Comment by asaadmahmood** [comment]
@sudheerDev if the loading indicator has a fixed width/heigh, like 20px or whatever, then we can just position it to the center of any container with whatever width/height based on flexbox.

**Comment by sudheerDev** [comment]
> @sudheerDev if the loading indicator has a fixed width/heigh, like 20px or whatever, then we can just position it to the center of any container with whatever width/height based on flexbox.

I am afraid this wont work because we don't contain the width of the svg above and that brings to the problem of centre aligning it. Flexbox here would not center align here as the parent has the entire horizontal space. Feel free to give this a try on top first commit above which fixes an issue with scroll pop. The ticket needs to be re-opened too.

**Comment by asaadmahmood** [comment]
Doesn't seem to be working for me.
Nov-29-2019 00-34-05

**Comment by cpanato** [comment]
will recreate this test server...

**Comment by cpanato** [comment]
will remove this test server since that last activity on this PR was December last year

**Pull request closed without merging**
