### PR TITLE
[MM-23213] - Mark 'me' messages as system messages in RHS as well

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
'/me' posts are not marked as system messages in RHS. This fixes it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23213

Fix v5.23.0

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Strange. I thought `/me` messages had different formatting as system messages. Code looks good, regardless.

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 
Tested, looks good to merge.
- Verified /me posts are faded out on, both, main channel view and RHS reply thread

**Pull request merged**
