### PR TITLE
MM-49058 : Remove unused getChannelRef from SidebarChannel component

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Removed `getChannelRef` prop from SidebarChannel and associated areas.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49058

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by kostaspt — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @M-ZubairAhmed 
Tested, looks good to merge
Verified channel sidebar drag drop and collapse - as before.
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/283030-4e8640e-onprem-ent-webapp-pr-11798-mm-ee-test:4e8640e/mochawesome.html)- no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
