### PR TITLE
[MM-42058] : fix onboarding tour e2e

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Fixed tutorial guided tour test case and finish tutorial tour e2e.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-42058

#### Related Pull Requests
``NONE``

#### Screenshots
``NONE``

#### Release Note

```release-note
E2E: Fixed tutorial guided tour test case and finish tutorial tour e2e
```

### CODE REVIEW

**Review by AGMETEOR — APPROVED** [review]

**Comment by AshishDhama** [comment]
@saturninoabril Could please prioritise this as we need it to be merged before 2 march cloud release

**Review by saturninoabril — APPROVED** [review]
Thanks @AshishDhama! Looks good to me.

**Pull request merged**
