### PR TITLE
[MM-28782] migrate string refs for filter

### PR DESCRIPTION
**Pull request by hardikmodi1**
#### Summary
Migrate string refs of filters to use createRef from react

#### Ticket Link
JIRA - https://mattermost.atlassian.net/browse/MM-28782
ISSUE - Fixes https://github.com/mattermost/mattermost-server/issues/15518

### CODE REVIEW

**Comment by hanzei** [comment]
@hardikmodi1 There are some small linter issues. Could you please fix them? After your done, I will queue it for review. https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/25859/workflows/e1eae05b-fe10-40b3-97ba-1dbe6c4c8ec5/jobs/168757/parallel-runs/0/steps/0-103

**Comment by hanzei** [comment]
@hardikmodi1 Heads up: CI is still failing with https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/25863/workflows/6900c21c-474e-4f8a-af45-8ff453cdca3b/jobs/168798

**Comment by hardikmodi1** [comment]
Here we are assigning the ref to class component, so we don't have access to the `focus` method on it. We have to first find it using ReactDOM, but that is also deprecated and shows the warning in console. any ideas?

**Comment by hanzei** [comment]
@sudheerDev Can you please help with the question above? :point_up:

**Comment by sudheerDev** [comment]
> Here we are assigning the ref to class component, so we don't have access to the `focus` method on it. We have to first find it using ReactDOM, but that is also deprecated and shows the warning in console. any ideas?

Hey @hardikmodi1, Sorry why don't we have access to focus method using create `createRef` and class component?. You should be able to access the focus method on the ref object.  

You seem to have done the changes required for focus method in the PR and it should work, am i missing something here?

**Comment by jasonblais** [comment]
Hi @hardikmodi1, let us know if you have any questions about the feedback from @sudheerDev above. We're happy to help :)

**Comment by Willyfrog** [comment]
hello @hardikmodi1 do you have any console errors or anything else so we can try and help you better? let us know how can we assist you :)

**Comment by hanzei** [comment]
As mentioned in https://github.com/mattermost/mattermost-server/issues/15518 this PR is not longer valid. Still, thanks for the contribution @hardikmodi1 :+1:

**Pull request closed without merging**
