### PR TITLE
[PLT-8064] Timestamp links in RHS on desktop app should open in permalink view in the current window

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Timestamp links in RHS on desktop app should open in permalink view in the current window	

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/PLT-8064

#### Checklist
n/a

### CODE REVIEW

**Comment by cpanato** [comment]
yeah thats true. @esethna do you want only for desktop or for both? the previous ticket I did for both

**Comment by hmhealey** [comment]
Yeah, I noticed that it was for both with your previous change. I don't have any strong feelings about how we end up doing it, but I posted this to the UX channel on pre-release, since it didn't seem to match the description in the ticket

**Comment by esethna** [comment]
I think it's fine to match that behavior on the browser as well. It seems common practice, for example GitHub timestamps.

**Comment by hmhealey** [comment]
Cool, thanks for clarifying, Eric. Merging this now

**Pull request merged**
