### PR TITLE
 [MM-29411] migrate string-refs in reset_emailmodal

### PR DESCRIPTION
**Pull request by filipghorbani**
#### Summary

Replace this.refs to using React.createRef in reset_emailmodal.jsx

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15850
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29411

#### Related Pull Requests

#5753

### CODE REVIEW

**Review by sudheerDev — APPROVED** [review]

**Comment by sudheerDev** [comment]
Thank you, @filipghorbani. Can you also remove `/* eslint-disable react/no-string-refs */` instances from the file

**Review by Willyfrog — APPROVED** [review]
LGTM

**Review by stevemudie — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
Thanks for the quick PR @filipghorbani :tada:

**Pull request merged**
