### PR TITLE
MM 16068 announcement bar tooltip show appropriately

### PR DESCRIPTION
**Pull request by fullstackguyhere**
#### Summary
This PR is mainly to fix the issue of Tooltips always displaying when a user hovers over an Announcement banner, even when the text isn't truncated.
It fixes the following issues:-

1. Only show the tooltip if the text in the banner truncates
2. Fix the z-index of the tooltip, it sits behind the banner

Along with these two issues, additionally fixed:-
3. Fix the additional issue of not being able to click links or other clickable content inside the tooltip. The reason being pointer-events proper for .tooltip class set to none. So I fixed this for announcement bar-related tooltips.

Apart from these issues, had to add constant OVERLAY_ANNOUCMENT_HIDE_DELAY to increase delay for hiding overlays since if the content inside the tooltip is clickable, the user needs more than 400 microseconds to click it. 

#### Ticket Link
Issue on Github: https://github.com/mattermost/mattermost-server/issues/14404

Issue on JIRA: https://mattermost.atlassian.net/browse/MM-16068

#### Related Pull Requests
Not applicable here

### CODE REVIEW

**Comment by jasonblais** [comment]
@fullstackguyhere I noticed some of the tests failed. Would you be open to help resolve them? We can then begin the review process.

Please let me know if you have any questions about them. :)

**Comment by esethna** [comment]
Awesome thanks for the PR! @jgilliam17 how can we trigger the banner for testing?

**Comment by jgilliam17** [comment]
> Awesome thanks for the PR! @jgilliam17 how can we trigger the banner for testing?

Done!
Banner text can be edited in System Console>Site Configuration>Announcement Banner

**Comment by esethna** [comment]
Thanks. @fullstackguyhere I'm not seeing the tooltip in this case: 
image

**Comment by fullstackguyhere** [comment]
Sure @esethna let me have a look. Could you give me the steps to reproduce that?

**Comment by fullstackguyhere** [comment]
Sure @jasonblais I will fix those failing tests after I fix the issue @esethna  is mentioning.

**Comment by esethna** [comment]
@fullstackguyhere you can log into the test server and you'll see it when you hover over the banner. The banner was added in the System Console. It's called "Announcement Banner"

**Comment by fullstackguyhere** [comment]
@esethna I am not able to access https://mattermost-webapp-pr-5907.test.mattermost.cloud/ with the account that I use to login community.mattermost.com

**Comment by esethna** [comment]
@fullstackguyhere creds are here for the test accounts for that server: https://github.com/mattermost/mattermost-webapp/pull/5907#issuecomment-658825978

**Comment by fullstackguyhere** [comment]
oh thanks, @esethna.

**Comment by fullstackguyhere** [comment]
I am getting tooltip @esethna. I have attached the screenshot below.

image

**Comment by fullstackguyhere** [comment]
ok @esethna , now I will fix the failing tests then!

**Comment by fullstackguyhere** [comment]
done @jasonblais.

**Comment by fullstackguyhere** [comment]
@hmhealey Sure no worries! I will just update my PR with latest changes from master, resolve conflicts and update the PR once I get time.

**Comment by cpanato** [comment]
terminated the test server due to underlying hardware issues for this test server. if you need the test server again please add back the label

**Comment by jgilliam17** [comment]
Thank you @fullstackguyhere - Tooltip looks great so far
Seeing few small issues
1. Tooltip is missing (until refresh) for a sysadmin user after banner has been enabled.
2. Safari > tooltip competes with browser tooltip
Screen Shot 2020-08-03 at 3 51 09 PM
3. Desktop app, Chrome, Edge > If the banner text starts with the link, link is not clickable within the banner, but it is clickable on the tooltip. Banner link is clickable if preceded by text on both, banner and/or tooltip.
 
- Also, if the link is preceded by longer text, timing wise, user may need a bit more time to reach/click the link on the bottom of the tooltip before it disappears. I'm 0/5 on this

Aug-03-2020 16-47-12

4. Tooltip occasionally surfaces even for shorter banner text (functionality does not scale with the browser window width, if the width is changed after banner has been enabled)
- To reproduce > enable banner with text 200+characters. 
Shrink the window to the point where banner text will be truncated. 
Refresh (to ensure you are not seeing issue from the 1st point above)
Verify tooltip on hover
Expand the browser window (e.g. enter full screen) and observe that tooltip is still present on hover even though text is no longer truncated

Screen Shot 2020-08-03 at 4 54 44 PM

**Comment by fullstackguyhere** [comment]
@jgilliam17 sure, I will look into these issues and add a commit to this PR.

**Comment by jgilliam17** [comment]
Thank you @fullstackguyhere 
I re-retested today and see an additional issue
- When banner text is truncated, is link-free or has the link within the text, but the user is not hovering over the link part of the banner -  tooltip fails to show on hover.
Aug-14-2020 15-40-21

- I would like to get some feedback from the UX team on the amount of time tooltip takes to disappear, taking into consideration cases where link in the banner may be preceded by longer text I mentioned in my previous comment. @andrewbrown00  Any thoughts?

**Comment by jfrerich** [comment]
@jgilliam17 did you get any feedback for your UX concern? @andrewbrown00, do you have any thoughts from UX?

**Comment by andrewbrown00** [comment]
@jgilliam17 or @jfrerich based on playing around with the banner, I recommend we have different conditions for the tooltip:

1. If a link(s) is present in the banner, keep the tooltip open for 800ms (may need to adjust this slightly) after the cursor leaves the banner, to give the user time to interact with the tooltip. Once the cursor leaves the tooltip or a link is clicked, hide the tooltip immediately (based on current in-product tooltip timing for other elements, i.e. icon buttons.

    [Here's a link to quick prototype to play around with](https://www.figma.com/proto/TMzbd1Ytm0u7McoJrnlczb/Scratch?node-id=937%3A23141&viewport=2467%2C3416%2C0.25&scaling=min-zoom)

2. If no link is present in the banner, the tooltip should follow the current in-product timing which hides the tooltip immediately.

Setting the tooltip to a fixed time could result in users not having enough time to interact with the links.

Also note, the tooltip should should show up anytime the cursor is hovering over the banner when the text is truncated, it still on shows when hovering over the link only.

**Comment by stylianosrigas** [comment]
Removing the test server for maintenance purposes. Please add the label again if you need it. Sorry for any inconvenience.

**Comment by fullstackguyhere** [comment]
Ok @andrewbrown00 , will include your suggestions as well fixes for bugs mentioned by @jgilliam17 and update here.

**Comment by esethna** [comment]
@fullstackguyhere hey there, just checking on this PR, let us know if you'd like to finish it up or if we should close it :)

**Comment by fullstackguyhere** [comment]
@esethna I will update the PR to fix the review comments. Will update here once done.

**Comment by hmhealey** [comment]
@fullstackguyhere No worries. Thanks for your work on this so far. We'll close the PR, but leave it around in case anyone else wants to pick up from here.

**Pull request closed without merging**
