### PR TITLE
MM-37957: fixes overlapping separators in thread

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Timestamps and or new messages line was overlapping the text message
making it impossible to read, this commit fixes that.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37957

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by asaadmahmood — APPROVED** [review]
Haven't worked on this in a while, so adding @michelengelen as well to have a look at this.

**Review by michelengelen — APPROVED** [review]
looks good

**Review by anurag6713 — APPROVED** [review]

**Pull request merged**
