### PR TITLE
MM-21933 Fix toast banner delays

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
  * Do not show unread toast when at bottom
  * Remove the delays for toasts
  * Change default state of virt list atBottom to be true so we don't see a flicker of unread toast and let the virt list decide if list is at bottom. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21933

### CODE REVIEW

**Comment by sudheerDev** [comment]
@andrewbrown00 @esethna There is a delay to determine if the channel is at bottom so, when visiting an unread channel not at bottom the toast appears after the posts are visible now. Let me know if that feels odd

**Comment by andrewbrown00** [comment]
> @andrewbrown00 @esethna There is a delay to determine if the channel is at bottom so, when visiting an unread channel not at bottom the toast appears after the posts are visible now. Let me know if that feels odd

@sudheerDev thanks for pointing this out. I would expect in this use case to see the toast banner immediately when switching to a channel that is not scrolled to the bottom. Here's a screen recording showing the lag which feels a bit unpolished.

.

**Comment by esethna** [comment]
Looks good to me, if the issue above is a hard fix I would propose merging and creating a follow-up ticket

**Comment by sudheerDev** [comment]
@andrewbrown00 @esethna It is animation transition delay of fade in making it feel slower.
i changed it to 0sec from 0.5sec and the result is the below gif. 
Jan-23-2020 19-06-34

We can tweak it on spinmint and see what feels right

**Comment by esethna** [comment]
@amyblais let's try to merge this soon, it should be verified by UX on daily after merge

**Comment by amyblais** [comment]
@hmhealey Can you help prioritize reviewing this?

**Pull request merged**
