### PR TITLE
Update compass-icons to v0.1.8 for new product icons

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
This PR updates the `@mattermost/compass-icons` package to get the updated product icons.

#### Screenshots
image

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@deanwhillier I'm sure this is fine, but I seem to be having trouble with the test server. Is it working for you?

**Comment by deanwhillier** [comment]
@matthewbirtch, it did when I initially set it up but wasn't for me this morning either. Started up the CWS server instead, which is working for me right now.

**Review by matthewbirtch — APPROVED** [review]
@deanwhillier that worked. I verified that the `Channels` product icon has been updated, but couldn't see the playbooks or boards icons

**Review by Willyfrog — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]
LGTM :)

**Review by esethna — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @deanwhillier 
Tested, looks good to merge.
- Verified updated product icon for channels (and by editing its icon also checked for boards & playbooks)
Screen Shot 2021-08-31 at 9 21 40 AM

edited Channels icon
Screen Shot 2021-08-31 at 9 19 28 AM
Screen Shot 2021-08-31 at 9 18 34 AM

**Pull request merged**
