### PR TITLE
[34475] Emoji 13.0

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

Update emojis to 13.0, there is a new category and some of the old ones have been renamed

[emoji 13.0 changes](https://emojipedia.org/emoji-13.0/)

#### Ticket Link

[34475](https://mattermost.atlassian.net/browse/MM-34475)

#### Screenshots
Screen Shot 2021-05-06 at 11 25 35
Screen Shot 2021-05-06 at 11 25 44
Screen Shot 2021-05-06 at 11 25 55
Screen Shot 2021-05-06 at 11 26 15

#### Release Note

```release-note
updated emojis and emoji categories to standard 13.0
```

#### Additional Notes
there are a few emojis failing, my guess is that most of those reuse the image from another one. The list of emojis failing are:

| png | link | name |
|--|--|--|
| 1f9d1-200d-1f91d-200d-1f9d1 | https://emojipedia.org/people-holding-hands/ | People holding hands
| 1f469-200d-2764-fe0f-200d-1f48b-200d-1f468 |https://emojipedia.org/emoji/%F0%9F%91%A9%E2%80%8D%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%92%8B%E2%80%8D%F0%9F%91%A8/ | Kiss: Woman, Man |
| 1f469-200d-2764-fe0f-200d-1f468 | https://emojipedia.org/emoji/%F0%9F%91%A9%E2%80%8D%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%91%A8/ | Couple with Heart: Woman, Man |
| 1f468-200d-1f469-200d-1f466 | https://emojipedia.org/emoji/%F0%9F%91%A8%E2%80%8D%F0%9F%91%A9%E2%80%8D%F0%9F%91%A6%E2%80%8D%F0%9F%91%A6/ | Family: Man, Woman, Boy, Boy |
| 2640-fe0f | https://emojipedia.org/emoji/%E2%99%80/ | Female Sign |
| 2642-fe0f | https://emojipedia.org/emoji/%E2%99%82/ | Male Sign |
| 2695-fe0f | https://emojipedia.org/emoji/%E2%9A%95%EF%B8%8F/ | medical sign |
| 0023-fe0f-20e3 | https://emojipedia.org/emoji/%23%EF%B8%8F%E2%83%A3/ | Keycap Number Sign | 
| 1f1e6-1f1e8 | https://emojipedia.org/emoji/%F0%9F%87%A6%F0%9F%87%A8/ | Flag: Ascension Island |
| 1f1e7-1f1fb | https://emojipedia.org/emoji/%F0%9F%87%A7%F0%9F%87%BB/ | Flag: Bouvet Island |
| 1f1e8-1f1f5 | https://emojipedia.org/emoji/%F0%9F%87%A8%F0%9F%87%B5/ | Flag: Clipperton Island |
| 1f1e9-1f1ec | https://emojipedia.org/emoji/%F0%9F%87%A9%F0%9F%87%AC/ | Flag: Diego Garcia |
| 1f1ea-1f1e6 | https://emojipedia.org/emoji/%F0%9F%87%AA%F0%9F%87%A6/ | Flag: Ceuta & Melilla |
| 1f1ed-1f1f2 | https://emojipedia.org/emoji/%F0%9F%87%AD%F0%9F%87%B2/ | Flag: Heard & McDonald Islands |
| 1f1f2-1f1eb | https://emojipedia.org/emoji/%F0%9F%87%B2%F0%9F%87%AB/ | Flag: St. Martin |
| 1f1f8-1f1ef | https://emojipedia.org/emoji/%F0%9F%87%B8%F0%9F%87%AF/ | Flag: Svalbard & Jan Mayen |
| 1f1f9-1f1e6 | https://emojipedia.org/emoji/%F0%9F%87%B9%F0%9F%87%A6/ | Flag: Tristan Da Cunha |
| 1f1fa-1f1f2 | https://emojipedia.org/emoji/%F0%9F%87%BA%F0%9F%87%B2/ | Flag: U.S. Outlying Islands |

### CODE REVIEW

**Comment by esethna** [comment]
@Willyfrog note that I think the plan was to finish the emoji picker UI that was partly implemented here (with a skin tone selector and some UI updates): https://github.com/mattermost/mattermost-webapp/pull/7234

Not sure if that helps with issue # 2 you identified here: https://community-daily.mattermost.com/core/pl/6xux1nsc4fnnxdcu645w1nf8xh

@matthewbirtch can you help with the missing icons as identified by Guillermo?

**Comment by matthewbirtch** [comment]
> @matthewbirtch can you help with the missing category icons as identified by Guillermo ^ in his post?

@Willyfrog will you be updating icons as part of this PR or a separate PR to update the entire emoji picker? There are a few conversations going around in a few different places right now and I'm having a hard time following

**Comment by Willyfrog** [comment]
> > @matthewbirtch can you help with the missing category icons as identified by Guillermo ^ in his post?
> 
> 
> 
> @Willyfrog will you be updating icons as part of this PR or a separate PR to update the entire emoji picker? There are a few conversations going around in a few different places right now and I'm having a hard time following. cc @esethna 

I wasn't planning on updating the UI more than needed. If there is a conversation going on about revamping the icons, then I can leave them as they are right now. 
The only things to keep in mind regarding those conversations are that the category names have changed and that there is a new category.

**Comment by esethna** [comment]
@matthewbirtch @Willyfrog let's do the emoji picker UI updates in a separate PR so this one can just be focused on updating the emoji set.

**Review by matthewbirtch — APPROVED** [review]
I see no issue with this as-is. We can look at the icons in a separate PR when the emoji picker gets updated.

**Comment by Willyfrog** [comment]
I moved the images to the first two commits so it can be easier to review this change. Use the range of commits https://github.com/mattermost/mattermost-webapp/pull/8070/files/be44116b136b11da6fb221449f57a74b57ffbc18..3ebcc70ee702f74885b42e2e6c8cc7822ddbfb51 to do the review without all the noise from png/css/jsx autogenerated changes

**Review by mkraft — COMMENTED** [review]
Should we change the Ruby class name from `AppleEmojiExtractor` since it's no longer extracting from the Apple system?

**Comment by Willyfrog** [comment]
Changed the name of the extractor
tests were partially failing because it wasnt generating skin tones

there are still many that are not generated if they end up with a woman sign:
```
missing sequence 🧑🏼‍♀️
```

**Comment by Willyfrog** [comment]
> @Willyfrog can you help guide @jgilliam17 on what specifically we should be testing in this PR

- emojis work as expected (posts, comments, reactions, custom status), as well as emojipicker doing its work correctly.
- new emojis (see [emoji 13.0 changes](https://emojipedia.org/emoji-13.0/)

some skin tones can be rendered if you know the name, but they wont appear in the emoji picker (like `:clap_light_skin_tone:`), but I'm not sure this should be tested as currently it is supported but not rendered in the emojipicker as well

**Comment by esethna** [comment]
Thanks! @jgilliam17 see above. Propose we wait to test the skin tones once we submit the PR for updating the emoji picker UI with the skin tone selector cc// @Willyfrog

**Review by jgilliam17 — APPROVED** [review]
Thanks @Willyfrog 
Tested, looks good to merge.
- Verified emoji picker and using emoji (including new) in posts, edit post modal, as reactions, in comments and custom statuses.

**Comment by hmhealey** [comment]
Code looks good, but I'm wanting to test a few different things. I've tested all the Unicode emojis on Mac/Firefox, and there's a few of the newer ones that don't support skin tones.

Screen Shot 2021-05-17 at 5 57 24 PM

Are those ones known issues? I also want to test these emojis on Windows as well, but I'll be doing that tomorrow.

**Comment by Willyfrog** [comment]
> Code looks good, but I'm wanting to test a few different things. I've tested all the Unicode emojis on Mac/Firefox, and there's a few of the newer ones that don't support skin tones.
> 
> Screen Shot 2021-05-17 at 5 57 24 PM
> 
> Are those ones known issues? I also want to test these emojis on Windows as well, but I'll be doing that tomorrow.

Weird, I can see the pinching ones with skin tones with mac and firefox. I'm on big sur and I'm guessing you are on catalina?

Screen Shot 2021-05-18 at 11 27 06

**Comment by Willyfrog** [comment]
@hmhealey updated, can you check if you can now see the images correctly?

**Comment by hmhealey** [comment]
> Weird, I can see the pinching ones with skin tones with mac and firefox. I'm on big sur and I'm guessing you are on catalina?

In case we didn't already discuss that elsewhere, that's because it's using the system font which includes the new emojis. You'll be able to tell when it's falling back to the system font because it's rendering the emojis as text instead of a span with a background image set like our emojis.

> updated, can you check if you can now see the images correctly?

Ninja and pinched fingers are correct now, but some of the later ones like woman feeding baby are missing still. I think those might be from the ZWJ sequences file we discussed earlier.
Screen Shot 2021-05-19 at 5 17 58 PM

**Comment by Willyfrog** [comment]
@hmhealey I think it still has problems with some of the emoji sequences, but now it is using the files directly instead of generating random sequences

**Comment by esethna** [comment]
@Willyfrog @hmhealey is this PR blocked or can we push forward on it and get it merged?

**Comment by Willyfrog** [comment]
We switched to a new library which should help us deliver new emojis better. As soon as I have the a PR with it I'll close this one. I'm currently using it for reference

**Comment by Willyfrog** [comment]
Closing in favour of https://github.com/mattermost/mattermost-webapp/pull/8220

**Pull request closed without merging**
