### PR TITLE
Romanian locale fix

### PR DESCRIPTION
**Pull request by licaon-kter**
...as per https://github.com/mattermost/mattermost-server/blob/f24f06c101811c472da00aad6aa5ae7d9bc1c18c/i18n/ro.json#L647

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you @licaon-kter, appreciate your contribution.

Translations are actually managed in our Translation server at https://translate.mattermost.com. Would you like to help make the changes there?

You can search for the strings at https://translate.mattermost.com/ro/mattermost/. Looks like the one you're proposing to change is here: https://translate.mattermost.com/ro/mattermost/translate/#search=Creati%20un%20nou%20cont&sfields=source,target

image

**Comment by licaon-kter** [comment]
Can I login with Github/Gitlab like on Crowdin, Transifex or Weblate? If not, I won't bother. Just link this to the Romanian team then. Thanks

**Comment by jasonblais** [comment]
@licaon-kter You can contribute the suggestion without logging in. It'll be anonymous in that case and our Romanian language maintainer would review the suggestion.

**Comment by jasonblais** [comment]
Hey @uhlhosting, FYI on the above note from @licaon-kter about a Romanian translation, if the change wasn't submitted to the translations server.

**Pull request closed without merging**
