### PR TITLE
[MM-35138] Avoid autofill on apps forms

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

When a secret field (type=`password`) field is used in a form, the browser treats the whole form as a login form, and tries to autofill the credentials for the current site into the form fields. This PR makes it so the apps form does not allow for autofill.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-35138

```release-note-none
```

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by hanzei — APPROVED** [review]
LGTM. Do we need to cherry-pick this?

**Review by abhijit-singh — APPROVED** [review]
Seems like the right thing to do UX wise. 👍

**Comment by hanzei** [comment]
@mickmister In which release should this go?

**Comment by mickmister** [comment]
> @mickmister In which release should this go?

@hanzei I'd say it can wait for the next cloud release. @DHaussermann What are your thoughts on this?

Should this fix also be applied to interactive dialogs?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
Auto-fill does not populate the form
including the case where I had preciously saved data into the brower

LGTM!

**Pull request merged**
