### PR TITLE
Improvements to copy/paste functionality within and outside mattermost

### PR DESCRIPTION
**Pull request by Wicked7000**
#### Summary
This add additional functionality for copying and pasting within and outside mattermost

When copying posts it will copy it in a rich-text(html) and plain-text format along with markdown
When pasting a post within mattermost we can then paste with markdown.
External applications can paste using the rich-text format (if they support it).
External applications that don't support the rich-text format will get the plain text format.
Format of rich text format:

```
Date Separator
<New Line]
Username – timestamp
message contents
consecutive post 1 message contents
consecutive post 2 message contents
[New Line>
Message
Username – timestamp
message contents
```

#### Ticket Link
[Link](https://github.com/mattermost/mattermost-server/issues/12619)

#### Questions
I did try to ask these questions on the initial issue but no one has replied.

- Ideally I'd make the pasting into mattermost accept the rich-text format (html) but that could open security problems as someone could paste it content with script tags and other malicious content. For now that means we'd only support rich text that was copied from within mattermost if external content was copied we wouldn't be able to use it. Do we want to try and deal with parsing html from copied data or is this okay?
- When pasting within mattermost currently we just paste each message on a new line (No format for the messages was originally given so I just went with this) Is this okay?

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you @Wicked7000 for the contribution - I've tagged the PM of this feature to start the review process.

In the meantime, I noticed there were some build failures. Would you be open to reviewing them? Happy to help if you have any questions! :)

**Comment by esethna** [comment]
@Wicked7000 let me know if you have questions or concerns on the above ^

**Comment by Wicked7000** [comment]
Apologies for the lack of updates, I'm good with the requested additions I should have them done over this weekend and will add another comment once I'm done.

Sorry again for the wait

**Comment by Wicked7000** [comment]
I've made the changes that were suggested above just some additional notes:

- If user X posts 10 times in a row but a post has a different timing than the last then the user date and time will be displayed. (otherwise I felt it wouldn't make much sense but I'm up for discussion if you think otherwise)
- If one post header is selected (user and time) then it applies showing the user and time for every post in the selection (This is due to there being quite a bit of complexity in figuring out which post header corresponds with each post) Although it is possible so if its something that you feel is required I can work on that.

**Comment by hanzei** [comment]
@esethna Gentle reminder to review this

**Comment by Wicked7000** [comment]
> Thanks @Wicked7000!
> 
> I found an issue where selecting and copying a part of a post copies the entire post:
> 
> image
> 
> Copying the above pastes:
> 
> ```
> komodo vulture  #one quit serenely fatuously manatee busted outside and handsomely exultingly  #handsomely  @sysadmin reined but much ouch one a after classically this amidst more   @user-1  #reined some yet.
> Less
>  @user-1 bat  @sysadmin behind mallard so  @user-1 thus however that more wayward flapped alas far the hence and  @sysadmin so wrote mindfully thanks that shook yellow
> kookaburra more as  @user-1 hey a far  @user-1 one much feverish where therefore versus the  @user-1 oh ouch the across  @sysadmin then and banded explicitly tamely for a circuitous cliquishly  @user-1 far normal and pithy al
> w therefore  @sysadmin  @user-1 far  @sysadmin some kindhearted irritably erately  #w dachshund demonstrably considering  @user-1 squirrel.
> Some reset yikes far wow
>  @user-1  @sysadmin emoted llo the  @sysadmin besides because mo that gross blushed however while and  #that far therefore  @user-1  #assenting dear.
> Far assenting  #therefore
> correctly  # #fishy leopard  @user-1 before  @sysadmin immaturely weasel and  @sysadmin buoyant   #before fishy jeez  #adventurous sniffled mandrill much.
> Jeepers  @user-1 where that annoying on th much  # #where  #where  @user-1  #fishy spitefully concentric remote adventurous wherever
> ca brightly jeez jeez loyal amidst more since much and naughtily bald then hence y  #y less logic by  @sysadmin across brought  @sysadmin the some left bluebird  #brightly  #much
> balked hey the  @user-1 and wrongly far black yet carib as  @sysadmin hello near ouch gosh alas a shrewdly far  @sysadmin tacky  @sysadmin  @user-1 yikes more much is sexy scallop sane among and
> more far versus acr  # #hey feverish and under far disbanded criminal  #where furrowed that a pithy hey a then unique ouch hey so the kookaburra  #that  #acr one for less normal circuitous  #hey more   @sysadmin  @user-1 where rose cliquishly the
> heron  #and  @sysadmin far essential duri robin mongoose and shined  inside  #the  @sysadmin the less dismounted confessedly beyond proudly
> sdfdsaf
> sadf
> sdaf
> link
> bold it
> 
> test
> ```
> 
> Looking good otherwise, but will have to retest after the above is addressed

Will look into trying to implement this on the weekend, is quite a bit complex to only select the text from posts that are highlighted but it should be possible

**Comment by esethna** [comment]
@Wicked7000 let me know if you need any help or guidance on this

**Comment by Wicked7000** [comment]
Sorry for this getting delayed so long, Christmas period has not left me with much time. Hopefully should have some time mid this week to be able to finish it off.

**Comment by jasonblais** [comment]
Thanks @Wicked7000 for the heads up! Totally understand, in the meantime, don't hesitate to let us know if you have any questions

**Comment by Wicked7000** [comment]
Hi,

I had a question regarding the issue of selecting partial text when copying. What would be the expected behaviour if someone was to partial copy across posts? (As shown below) The two ways I'd see of handling this are:

- When copying multiple posts it always gets all the post text. (Only when you are selecting content from a single post will it trim it)
- all selected posts would be trimmed to only the selected content. (This is complicated as browsers like firefox allow multiple selections at a time.)

image

There is also complications around even just single post partial text selection. Its easy for non-markdown posts but when markdown is used things become complicated and I'm not sure of how to handle it.

image

For example in the post above I've selected the eyes and some of the text. However the browser will only capture that I've selected 'test te' I could see if there is a way of capturing the range and where it starts and stops but that still leaves the issue of firefox. (And if they do selections that don't pass over but stop on a markdown item like the image below)

image
(Like this image actually has the eyes highlighted but it just doesn't show up)

If you've got any suggestions on how to possibly handle this I'm open to options as I can't think of a reliable one that will work for all cases. Also please let me know what I should do regarding the multiple posts issues. In the mean-time I'll look to see if I can find a way of getting around this and how other places do it.

Apologies for the delay, I assumed this would be simple but as with all things turned out to be a lot more complicated then I expected!

**Comment by jasonblais** [comment]
cc @esethna / @adamjclarkson on the above note form @Wicked7000 as well

**Comment by esethna** [comment]
@Wicked7000, appologies for the delay given holidays. 

Regarding the question of multiple posts, I would propose only theselected text is copied, so the copied text when pasted into a text editor would be as:

image

Regarding the question about emojis, can we include the emoji in the selected text? If you copied your post with the eyes, the paste into a text editor would be:

image

Ideally the eyes emoji would also be highlighted in Mattermost when the selection is made, see example: 

image

**Comment by ylluminate** [comment]
Thanks @amyblais for calling this out - what would it take to get it more along the lines of the requested formatting here: https://github.com/mattermost/mattermost-server/issues/11177
> ```
> username1 (TIMESTAMP): this is a line of text
> username1 (TIMESTAMP): another line of text
> username2 (TIMESTAMP): and yet another line of text
> username3 (TIMESTAMP): more text
> ```
> 
> I personally like to have the timestamp + short date format within parentheses each time to maintain context, but the big thing is that everything could be squeezed together and made very clear and compact.  This is what, I think, anyone would really want out of a copy and paste of text content.

**Comment by Wicked7000** [comment]
> @Wicked7000, apologies for the delay given holidays.
> 
> Regarding the question of multiple posts, I would propose only theselected text is copied, so the copied text when pasted into a text editor would be as:
> 
> image
> 
> Regarding the question about emojis, can we include the emoji in the selected text? If you copied your post with the eyes, the paste into a text editor would be:
> 
> image
> 
> Ideally the eyes emoji would also be highlighted in Mattermost when the selection is made, see example:
> 
> image

I'm not sure if its just my browser but emoji's don't seem to be highlighted? (Although that's a separate issue they are still actually being selected they just don't get highlighted for whatever reason).

That behaviour is fine by me I still need to work on the DOM parsing a little more to make sure that it can handle all cases for markdown, although I'm not sure if there is a better approach to copying content other than markdown. (As it does mean that any change to how markdown is rendered would also mean the parser for copying would have to be updated).

I should have a commit hopefully tomorrow with the parsing stuff if possible, apologies this has taken a lot longer than I originally thought it would.

> Thanks @amyblais for calling this out - what would it take to get it more along the lines of the requested formatting here: [mattermost/mattermost-server#11177](https://github.com/mattermost/mattermost-server/issues/11177)
> 
> > ```
> > username1 (TIMESTAMP): this is a line of text
> > username1 (TIMESTAMP): another line of text
> > username2 (TIMESTAMP): and yet another line of text
> > username3 (TIMESTAMP): more text
> > ```
> > 
> > 
> > I personally like to have the timestamp + short date format within parentheses each time to maintain context, but the big thing is that everything could be squeezed together and made very clear and compact.  This is what, I think, anyone would really want out of a copy and paste of text content.

Once I have the parsing working it should be fairly easy to switch around the format of the copied text quite easily.

**Comment by ylluminate** [comment]
@Wicked7000 I had assumed as much re: formatting. We like really dense / concise / compressed formatting that conveys all info needed in a single line vs having to hop around for context. It helps a lot in many circumstances (especially in documentation, project management, and dev work (logging, etc.)).

**Comment by Wicked7000** [comment]
> @Wicked7000 thank you so much and I'd assumed as much re: formatting. We like really dense / concise / compressed formatting that conveys all info needed in a single line vs having to hop around for context. It helps a lot in many circumstances (especially in documentation, project management, and dev work (logging, etc.)).

Yeah that makes sense, I'm not actually a member of mattermost (in terms of the core dev team) so I don't have that much of a say in terms of that format but it seems like a good idea to me.

**Comment by jasonblais** [comment]
cc @esethna on the above conversation

**Comment by Wicked7000** [comment]
To start I'd like to apologise for the long wait for this update, this problem turned out to be a lot harder to solve than I originally thought it would be. Especially as I haven't done anything around parsing before especially when it comes to the DOM.

I'd like to make a few points about the current solution to decide if this is even the correct way to go, currently like I've mentioned before I personally don't see any other possible solution aside from a parser but if there is one I'm more than happy to look into it.

**_Main points on 'parser' solution:_**
- The 'parser' solution is tied to how markdown is rendered to the DOM / represented in the DOM. (I.e if there is any change that will modify that representation the parser will have to be updated)
- The 'parser' solution does solve both issues of multiple selections (more on that below) and the problem of partial selections (where a user decides to only select part of a post / text content)

**Issues I've seen that I'm not sure how we want to solve:**
- Currently all markdown is removed from the 'rich' pasting format this can lead to issues for certain types of markdown namely images and emojis.
- Labelled code snippets can't be copied as labelled (What I mean by this is a code snippet where you specify the language), these are currently copied correctly but the parser has no way of knowing what language the snippet is in and thus pastes it as a normal snippet.
- There are some edge cases where the parser doesn't give the exact same result when the markdown is incorrect. (such as ``````yes``` ```hello`````` (which is a quote inside a quote), this ends up being copied as ```yes``` ```hello```, which isn't what was actually typed)

I think if the parser solution is seen as the way to go we could possibly deal with the Content -> Markdown -> Parser relationship by having tests that make sure that all is functioning well but they might be a bit hard to write. Let me know your thoughts.

**Comment by esethna** [comment]
> Once I have the parsing working it should be fairly easy to switch around the format of the copied text quite easily.

Makes sense, we can iterate on that once we have the main use cases working.

_______

Regarding questions Re Parser, I'm going to add @hmhealey to see if he has thoughts on implementation. In my mind the issues you've identified as failure cases are relatively minor:

image

If we can get a solution working for 90% of use cases with relatively small effort on top of what we have now that's definitely a win and we should go ahead with it.

**Comment by hmhealey** [comment]
I'll take a look at this when I get a chance, but it might take some time since this is rather complicated. My initial reaction is that trying to override what the browser copies by parsing the HTML might be overkill.

I haven't looked into this too much myself, but I think it might be possible to add invisible text to the post that gets selected when you copy/paste the text. Emojis are currently spans with a `background-image` style controlling the image, so we might be able to add the text for the emoji as its child and then make it invisible.

> There are some edge cases where the parser doesn't give the exact same result when the markdown is incorrect. (such as yes``` ```hello (which is a quote inside a quote), this ends up being copied as yes hello, which isn't what was actually typed)
@esethna Regarding this one, we should be clear about what we're trying to do here. Do we want to copy rich text, or do we want to copy the Markdown that generates the post? The way that the browser usually copies rich text is to set the font and colour, but not copy any boundaries. I think we should avoid fighting with the browser behaviour as much as possible since we're not matching the standard behaviour that the user might expect.

**Comment by esethna** [comment]
@Wicked7000 I've scheduled something on Monday for @hmhealey and I to work through this and determine a proposal.

My main concern is partial copying is very unexpected right now. See GIF where it works well when I paste in MM, but pasting into a non righ text editor shows the two pre-amble lines about username time and date that I didn't copy. That would be very unexpected to a user.
copy

**Comment by Wicked7000** [comment]
> @Wicked7000 I've scheduled something on Monday for @hmhealey and I to work through this and determine a proposal.
> 
> My main concern is partial copying is very unexpected right now. See GIF where it works well when I paste in Mattermost itself, but pasting into a non-rich text editor shows the two pre-amble lines about username time and date that I didn't copy. That would be very unexpected to a user.
> copy

No worries, I understand this is how I thought it was meant to work from the initial issue that was raised, but I can see how it would be unexpected behaviour to the user.

Let me know if you'd still like me to continue working on the problem after the proposal, I'm still more than happy to try and work it out.

**Comment by esethna** [comment]
@Wicked7000 apologies for the delay here, this turned out to be quite a complex ticket after we dug in a bit more. Here's how we're thinking about it and likely this is going to need to be split up into a few different PRs or tickets:

1. We should avoid fighting with the browsers native copying function, and instead we should change the structure of the actual Mattermost page so it supports selecting what we want selected. Then we let the browser handle the copying and we let the secondary program handle the pasting. This is likely going to be a significant task and should probably be tackled on it's own in multiple pieces. It will also require more direction from our UX team to propose what items on the screen are selectable, and then what the output of those selections should put into the clipboard. This will help us pasting outside of Mattermost into 

    - **Rich text editor** where we should attempt to render and match what's shown in Mattermost in the browser, within the limits of the rich text editing software's supported formatting. We would want to support certain markdown styling to work as a minimum (ie bold, italics, links, headings), and we'd want to trim out whitespace.

    - **Plain text editor** where we would strip Markdown formatting, but we don't want to lose any part of the users selection, except trim our whitespace.

2. Copying and pasting inside Mattermost can be considered a separate task that is perhaps easier to start with. What we are looking for is that the raw markdown gets pasted in the input box - but we don't want to lose any part of the users selection. We can start with a subset of the markdown features and build on support for more in additional PR's, perhaps we can start with: bold, italics, links, and headings.

image

3. Perhaps yet another PR is getting emojis to be selectable in the UI. While right now they are copied to the clipboard, they appear as though they are not highlighted in the UI:
image

We definitely need to better define (1), and likely there are cases in (2) that need input from our UX team. Let us know your thoughts, maybe we could schedule a call to discuss via video chat if you feel necessary to break down this problem more.

**Comment by Wicked7000** [comment]
@esethna No worries! I'd be more than happy to continue working on this although I do have quite a few questions regarding how to approach (1)  and (2). As I'm aware we don't want to work with a parser for understandable reasons (complicated and pretty hard to maintain).

- (1) If we are allowing the browser to just 'copy' does this mean that no transformation of data is done before putting data into the clipboard? As I'd assume you'd always need some level of transformation to get the raw html / text data into markdown for example. Although I don't know what would be the easiest way of doing that. (Even if you weren't transforming it to markdown you'd need to know about if the text is bold etc to be able to get the Rich text format)
- (2) Similar to what I mentioned above but again I'm not sure whats the best way to achieve this as some level of transforming needs to take place in order to obtain the markdown.

The only thoughts I've had on an approach that would be cleaner and it could be possible to  use something off the shelf that tries to achieve what would be wanted for (2) like [showdown](https://github.com/showdownjs/showdown). Although it would mean possibly having to re-do a lot of the code that handles post rendering to support the usage of showdown (or some other library).

The other interesting library is one called [turndown](https://github.com/domchristie/turndown) this would allow us to keep the rendering that is currently being down but use turndown to convert the HTML into markdown by using 'rules'

I can talk about this on a call if that would suit you better and get your thoughts on how this kind of thing should be handled before I move ahead with actually implementing anything.

**Comment by hmhealey** [comment]
Regarding (1), it seems like it might be standard to just copy as HTML from a web app and then transform it on paste. I haven't investigated too much what other apps do, but based on the code we have for pasting Excel data as a Markdown table, the data that is copied out of Excel is available as HTML. The same seems to occur when copying data from web pages as well.

If we could get more insight into what sort of data is copied by the browser without any special logic, we could tell if we need to do any sort of transformation on copy, but my guess would be that we don't need to do anything.

**Comment by Wicked7000** [comment]
> Regarding (1), it seems like it might be standard to just copy as HTML from a web app and then transform it on paste. I haven't investigated too much what other apps do, but based on the code we have for pasting Excel data as a Markdown table, the data that is copied out of Excel is available as HTML. The same seems to occur when copying data from web pages as well.
> 
> If we could get more insight into what sort of data is copied by the browser without any special logic, we could tell if we need to do any sort of transformation on copy, but my guess would be that we don't need to do anything.

I've looked around and I don't think it would be hard to allow for people to copy mattermost posts in rich format to outside mattermost. I've tried a snippet below that works well although we'd likely want to limit to only copying posts in rich format not just anything they happen to copy on the page.

You can try the bottom snippet by pasting it in the console while on mattermost, pasting in rich text editors seems to work fairly well.
```
var onCopy = function(e){
    const selection = document.getSelection().getRangeAt(0);
    const innerText = selection.commonAncestorContainer.cloneNode().innerText;
    e.clipboardData.setData("text/html", innerText);
    console.log(innerText);
}
window.addEventListener('copy', onCopy);
```

So in general I think that could be quite easy assuming we just copy everything the user has selected and we aren't doing anything else to it. Copying and Pasting within mattermost is the more complicated part.

**Comment by hmhealey** [comment]
Is that snippet needed though when copying from Mattermost to another application? I think the browser does the same thing automatically.

**Comment by cpanato** [comment]
removing the test server due stale, if need again add the label

**Comment by hanzei** [comment]
@hmhealey Could you help provide some next steps for this PR? Would a 1on1 call help resolve the outstanding questions?

**Comment by jasonblais** [comment]
@hmhealey @deanwhillier Any help we can share with @Wicked7000 for them to continue on this contribution?

**Comment by hmhealey** [comment]
I think we've ran into a case where the original ticket wasn't well defined and hadn't been reviewed by developers for to ensure what we were doing could be implemented properly. We might have to close this and have some more discussion about what is expected to work when copying and pasting text since this ticket doesn't align with what how a browser handles it natively.

**Comment by jasonblais** [comment]
@hmhealey Would you be open to raising with Apps team - to confirm next steps (close PR?) and to remind the team to PM and Dev review tickets before turning them to help wanted

**Comment by esethna** [comment]
@jasonblais @hmhealey @Wicked7000 closing this ticket for now. For context, the ticket had PM and dev review but it turned out to be more complex than anticipated. We will re-queue this ticket for dev to create an implementation spec

**Comment by hmhealey** [comment]
Thanks again for your work on this, @Wicked7000. Apologies that this ended up being more complicated than expected. We can let you know when the ticket is reopened more clearly.

**Comment by Wicked7000** [comment]
@hmhealey No worries, Please feel free to inform me when a new ticket is re-opened I'd be open to helping again

**Pull request closed without merging**
