### PR TITLE
[GH-15287] Implement hotkeys for bold/italic markdown.

### PR DESCRIPTION
**Pull request by jp0707**
#### Summary
Implements hotkeys for bold/italic markdown in post and comment creation. It adds appropriate markdown if selected text doesn't have it. In case selected text already has markdown around it, then it removes the markdown (undo). Also works on empty selection in which case it _starts_ the markdown.

After applying the markdown, also restores the selection state to originally selected text.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15287

#### Related Pull Requests
n/a

#### Screenshots
[Screenrecording](https://photos.app.goo.gl/eiARFToWTZPbdsLKA)

### CODE REVIEW

**Comment by jp0707** [comment]
Rebased changes to fix failing check

**Comment by jp0707** [comment]
@hmhealey, @calebroseland : Thank you. Just pushed those changes to this PR. Please take a look.

**Comment by jgilliam17** [comment]
Thank you @jp0707  - This looks great! 
I have few small requests:
1. Add the ability to undo formatting using ctr/cmd+z
Currently, on the test server, once I use hotkeys cmd+b or cmd+i to add `****`/`__` to the text box, or when formatting the existing text I am not able to undo using cmd+z (or even using edit>undo or right-click>undo) 
2. On double-click select the text, not markdown around it. 
I am only seeing this with `_`, works as expected with `**` appended to first word or last word of the formatted text. See gif.

Aug-28-2020 13-14-39
Aug-28-2020 13-20-36

**Comment by jp0707** [comment]
>     1. Add the ability to undo formatting using ctr/cmd+z
>        Currently, on the test server, once I use hotkeys cmd+b or cmd+i to add `****`/`__` to the text box, or when formatting the existing text I am not able to undo using cmd+z (or even using edit>undo or right-click>undo)

For other shortcuts like newline (`Shift+ENTER`) we don't do undo. We just default to `textarea`'s default undo behavior. For example on `Shift+ENTER` we add a newline character but on `ctr/cmd+z` we don't undo that.

While I agree that this is a nice feature to have, it's probably out of scope for this PR. Maybe we should create new ticket for undo feature of all existing shortcuts?

> 
>     2. On double-click select the text, not markdown around it.
>        I am only seeing this with `_`, works as expected with `**` appended to first word or last word of the formatted text. See gif.

Done.

**Comment by jp0707** [comment]
The failing test is passing on my machine with `npm run test components/timestamp/semantic_time.test.tsx`

**Comment by esethna** [comment]
@jp0707 really appreciate this PR, upon another review I found a something we should tweak:

We are moving toward standardizing on `*` for italics as it is more common/standard markdown. Can you help change the italics formatting to add `*` instead of `_`, then also update the subtext below the text input area to reflect the `*`? Note that `_` should still work to italicize when typed manually, but we should add the `*` via this keyboard shortcut

image

**Comment by esethna** [comment]
> Thanks @esethna. Yes, I'd love to tackle that.

Awesome! Let me work with the dev team to finish putting the spec together, then we can sync on it. Have you joined our community.mattermost.com instance so we can communicate there? Here is the channel for this feature: https://community.mattermost.com/core/pl/3xsoi17ah7drudbazb6acqr6da

**Comment by calebroseland** [comment]
Hi @jp0707, 
> The failing test is passing on my machine with `npm run test components/timestamp/semantic_time.test.tsx`

If you pull the latest (`semantic_time.test.tsx` + `semantic_time.test.tsx.snap`) from master, this should be fixed now.

**Comment by jp0707** [comment]
@esethna : Changed italic to use * now. PTAL.

@calebroseland : Thank you. Rebased this PR and it's fixed now.

**Comment by jp0707** [comment]
@jgilliam17 : Is there any pending items for this PR?

**Comment by jgilliam17** [comment]
@jp0707 Thank you for your patience. I will have this tested first thing tomorrow. 🙂

**Review by jgilliam17 — APPROVED** [review]
Thank you @jp0707 
Tested, looks good to merge.
- Verified hotkeys cmd+b  add **** to the textbox for bold formatting and cmd+i  adding ** for italics. 
- Verified same hotkeys can add selected formatting to the existing text when text is selected.
- Verified subtext below textbox has been updated with the new italics standard `*italics*` and that previous underscore characters work as expected when typed via keaybord e.g `_italics_`
Follow up for enabling undo/redo filed https://mattermost.atlassian.net/browse/MM-28317

**Comment by hmhealey** [comment]
Managing the undo/redo stack will be interesting. I'm not sure how much control we have over that from the JS side without entirely making our own.

Regardless, this is ready to merge then. Thanks again for your work here, @jp0707!

**Comment by esethna** [comment]
Thanks @jp0707, really appreciate the work on this! I'll be reaching out to you with the full text editor design soon :)

Have you joined our community instance? Feel free to shoot me a message there so we can communicate directly.  https://community.mattermost.com/core/channels/advanced-text-editor

**Comment by jp0707** [comment]
@esethna : Yes, I've joined that channel. My username there is jyoti0707. I don't check every messages on that channel though. Please tag me into any conversation that you think requires my attention so that it shows me a notification in app.

**Comment by esethna** [comment]
@jp0707 Thanks for your interest in taking on the advanced text editor project!

See message here: https://community.mattermost.com/core/pl/5dsppaweob8gjfne3nci1bbihh

Happy to message or chat there ^

**Pull request merged**
