### PR TITLE
[MM-28783] migrate string refs in edit post modal

### PR DESCRIPTION
**Pull request by hardikmodi1**
#### Summary
Migrate string refs in edit post modal to use createRef from react

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/MM-28783
ISSUE: Fixes https://github.com/mattermost/mattermost-server/issues/15519

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for submitting your first PR @hardikmodi1 :tada: I will queue it for review.

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @hardikmodi1! These changes look good to me.

For QA, note that https://mattermost.atlassian.net/browse/MM-27370 is still a known issue, so the emoji picker still isn't sized correctly in mobile view.

**Review by nevyangelova — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @hardikmodi1 
Tested, looks good to merge.
- Verified edit post modal - as expected. Note: verified emoji picker in mobile view waiting for fix MM-27370
@hmhealey Can you please help merge? Thanks 🙂

**Comment by hmhealey** [comment]
Thanks again for the pull request! Now that this is going in, it'll likely be available in the 5.29 release of Mattermost, shipping in November.

**Pull request merged**
