### PR TITLE
Cypress/E2E: Fix compliance export test

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Isolate admin test by using new custom admin user
- Added `@compliance_export` metadata so we can test this first and have the export processing time shorter given that the server has a small set of data during that initial period.
- S3 minio -- used `mattermost-test` bucket which is the same as in local dev
- Limit enabling/exporting as much as possible by moving some export commands at `before` hook
- Make `cy.visit` more explicit in the test block itself - (see our related [blog - item 4](https://mattermost.com/blog/automated-ui-testing-with-cypress/)). Also doing so, it lessen unnecessary visit to a default team/channel.

#### Ticket Link
none, failed on daily Cypress run

#### Screenshots
Screen Shot 2021-04-21 at 8 53 26 PM
Screen Shot 2021-04-21 at 9 00 08 PM
Screen Shot 2021-04-21 at 9 02 24 PM
Screen Shot 2021-04-21 at 9 10 57 PM
Screen Shot 2021-04-21 at 9 29 38 PM

```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — COMMENTED** [review]
@saturninoabril Not sure if I have to set any new environment variables locally but I'm getting failure on the `s3_bucket_storage_spec`

Screen Shot 2021-04-21 at 8 23 49 AM

**Comment by saturninoabril** [comment]
No, but please check if you have minio docker instance running, accessible at `localhost:9000` and see if it has the required bucket.

To add a bucket, either:
```
docker exec mattermost-minio sh -c 'mkdir -p /data/mattermost-test'
```
If still didn't work, then try to restart the minio docker instance.

Or add a bucket in the UI itself at `localhost:9000`.

I'll push another commit to add the instruction in the spec file itself.

Thanks for testing!

**Review by josephbaylon — APPROVED** [review]
LGTM. It passed now. It was the missing bucket. Thanks @saturninoabril !!

**Review by furqanmlk — COMMENTED** [review]
image

image

image

image

**After this [PR](https://github.com/mattermost/mattermost-server/pull/16977) S3 bucket has to be existed**
image

**Comment by saturninoabril** [comment]
Thanks @furqanmlk for the PR reference. Have you tried adding the bucket manually as [previously commented](https://github.com/mattermost/mattermost-webapp/pull/7964#issuecomment-824155877)? Did it pass or still fail?

**Review by prapti — APPROVED** [review]
Looks good, all tests passed as well.
Thanks Saturn!

**Comment by furqanmlk** [comment]
> Thanks @furqanmlk for the PR reference. Have you tried adding the bucket manually as [previously commented](https://github.com/mattermost/mattermost-webapp/pull/7964#issuecomment-824155877)? Did it pass or still fail?

Yes it's passing after adding Buckets. 
I thought it should be a part of test case to create bucket. 
Everything looks good

**Review by furqanmlk — APPROVED** [review]

**Pull request merged**
