### PR TITLE
Cypress/E2E: Promote tests to prod

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Tests were found stable based from the recent unstable runs:
- [build 5165](https://automation-dashboard.vercel.app/cycles/a759e45f-fdce-4d54-a3b4-e1ea314632ad)
- [build 5153](https://automation-dashboard.vercel.app/cycles/dab306dc-48b1-40ad-b21e-c75efe4ecf9a)
- [build 5132](https://automation-dashboard.vercel.app/cycles/1c923f46-f240-405d-9329-09b65c3bc942)
- [build 5118](https://automation-dashboard.vercel.app/cycles/41537afc-6906-43d8-928d-946ad7c31e9b)
- [build 5077](https://automation-dashboard.vercel.app/cycles/1f506cc4-4125-4767-a51b-fda48f1694bb)

#### Release Note
```
NONE
```

### CODE REVIEW

**Review by prapti — APPROVED** [review]
Thanks Saturn!

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril 👍

**Review by josephbaylon — APPROVED** [review]
LGTM

**Pull request merged**
