### PR TITLE
Updated the message shown for deactivated account

### PR DESCRIPTION
**Pull request by Vars-07**
#### Summary

Improve styling of deactivated user DM channel footer

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-25886
#### Related Pull Requests

- Has server changes (please link here)
- Has redux changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

Screenshot 2020-07-03 at 6 38 31 PM

### CODE REVIEW

**Comment by Vars-07** [comment]
Screenshot 2020-07-04 at 12 38 56 AM
Screenshot 2020-07-04 at 12 38 48 AM

@esethna Have a look at attached screenshots & let me know :)

**Comment by jgilliam17** [comment]
Thank you @Vars-07 
Styling looks good on the main channel view
Seeing some issues
- `Close Channel` button is not closing the DM and returning user to previously viewed channel.
-  Reply thread view styling, boldface text not rendering correctly  `**deactivated user**`
Screen Shot 2020-07-03 at 3 59 33 PM

**Comment by Vars-07** [comment]
@jgilliam17 Have fixed the RHS thread issue, for the first issue `Close Channel` is not working as expected, it is existing issue in master, have filed an issue for it https://github.com/mattermost/mattermost-server/issues/14968, will fix it as part of this!
Let me know :)

**Comment by Vars-07** [comment]
@sudheerDev @calebroseland, Please have a look!  :)

**Comment by Vars-07** [comment]
@calebroseland , have a look :)

**Pull request merged**
