### PR TITLE
MM-19252 - Making max length visible on mobile

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-19252 - Making max length visible on mobile

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19252

#### Screenshot
localhost_8065_bubbles_channels_town-square

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @cpanato - setting up a test server is failing on this PR. Can you please help?

**Comment by cpanato** [comment]
done @lindy65

**Pull request merged**
