### PR TITLE
[MM-46196] allow tabbing through dot menu items

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR allows a user to tab through the dot menu items when the menu is open. I tested that all shortuts work as expected and the user can tab to a menu item and <return> will execute that action.

I also refactored the code to reduce code duplication. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46196

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @jfrerich 
Tested, looks good to merge
- Verified tabbing through dot menu items
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/231473-9f9a8fa-onprem-ent-webapp-pr-10958-mm-ee-test:9f9a8fa/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Comment by jfrerich** [comment]
Thanks, @jgilliam17 :)

**Comment by jfrerich** [comment]
@jgilliam17, I added a change that prevents users from typing in the post input text area when the menu is open. Before this commit, non-shortcut keys (and Tab) would get typed in the post input area.

**Comment by jgilliam17** [comment]
Thanks @jfrerich - Can you please add an e2e too? I'll add one in Zephyr to generate a test case id.

**Review by esethna — CHANGES_REQUESTED** [review]
@jfrerich @jgilliam17 this is not working for me on chrome/win10. Can we ensure we try various browsers? 

Repro: Open ... menu on a post, hit tab key multiple times > nothing happens

**Comment by jfrerich** [comment]
> @jfrerich @jgilliam17 this is not working for me on chrome/win10. Can we ensure we try various browsers?
> 
> Repro: Open ... menu on a post, hit tab key multiple times > nothing happens

I was testing on Mac/chrome and it works for me.  I do see it failing on Mac/Safari and will investigate.

**Comment by jfrerich** [comment]
I also noticed tabbing does not work correctly on any of the following on Mac/Safari, so I don't think this is something necessarily caused by this PR. 

* team drop down menu
* channel drop down menu
* channel header drop down menu

I also logged into commmunity via safari and these are also not working.

**Comment by jfrerich** [comment]
To get tabbing through the menu items in safair I had to enable ` "Preferences > Advanced > Press tab to highlight each item on a page"` and found this answer here -> https://stackoverflow.com/questions/1848390/safari-ignoring-tabindex

**Comment by jfrerich** [comment]
@esethna, can you try to see if you have this setting in your chrome browser?   `Settings` → `Appearance` → `Pressing Tab on a web page highlights links, as well as form fields`

**Comment by jgilliam17** [comment]
@jfrerich tabbing worked fine for me on Chrome and Firefox before the latest change. But it no longer works on the test server.

**Review by jwilander — APPROVED** [review]

**Comment by esethna** [comment]
Friendly ping @jfrerich on this PR. Can you retry on the test server based on Jelena's comment ^

**Comment by jfrerich** [comment]
> Friendly ping @jfrerich on this PR. Can you retry on the test server based on Jelena's comment ^

I have been on mobile bug bashing for the past two weeks.  I'll get a look at this right after!

**Comment by jfrerich** [comment]
> Friendly ping @jfrerich on this PR. Can you retry on the test server based on Jelena's comment ^

This is weird and I cannot figure out why this is happening!  

I have confirmed that the test server does not work. (it is using commit c23590218f94934b3c90a42402e9c08a3dc61be6)

When I run with my local server (in the same browser) tabbing does work.

**Comment by jgilliam17** [comment]
@jfrerich 
Also noticed when freshly created, server theme is off, not sure why, once theme is updated in settings it looks fine.
Screen Shot 2022-09-28 at 11 53 35 AM

**Comment by M-ZubairAhmed** [comment]
Tabbing in menu is anti pattern as per ARAI guidelines https://www.w3.org/WAI/ARIA/apg/patterns/menubar/ So i am not sure if this should be taken forwarded.

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
