### PR TITLE
MM-47624 Rename "Client Performance Debugging" settings and move post formatting into it

### PR DESCRIPTION
**Pull request by hmhealey**
This is something we'd discussed a while back since it would be nice to have a more general place to put all sorts of settings that users probably shouldn't need but they're useful to have around for our sake.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47624

#### Related Pull Requests
https://github.com/mattermost/docs/pull/5948

#### Release Note
```release-note
Rename "Client Performance Debugging" settings to "Client Debugging" and move "Enable Post Formatting" setting into it
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@hmhealey we are already in the process of moving everything to the new design https://www.figma.com/file/dUGxJk4lfo38lXzoRZf3YP/MM-12122-Settings-Modal-Revamp?node-id=1389%3A88871
Let me know if it does make sense to delay till November. I will make the required changes in the new design.

**Review by cwarnermm — APPROVED** [review]

**Review by JulienTant — APPROVED** [review]
LGTM!

**Comment by hmhealey** [comment]
> @hmhealey we are already in the process of moving everything to the new design https://www.figma.com/file/dUGxJk4lfo38lXzoRZf3YP/MM-12122-Settings-Modal-Revamp?node-id=1389%3A88871 Let me know if it does make sense to delay till November. I will make the required changes in the new design.

@AshishDhama I'd like to get this in sooner if it's blocking @JulienTant since he had a setting he wanted to add that I had suggested by put under the Client Debugging section, but if it's not blocking him, then I think this can wait.

I'll probably still pull out some of the cleanup bits from this and merge those separately either way since a few things like the new selector will be helpful otherwise.

**Comment by JulienTant** [comment]
Nothing urgent, it's more of a quality of life/dev experience thing than a real need.

**Comment by hmhealey** [comment]
Closing this for the time being while the updates to the setting modal are done

**Pull request closed without merging**
