### PR TITLE
[MM-42472]: fixing misaligned avatars in threadfooter

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
fixes alignment of `Avatars` in `ThreadFooter` when message display is set to 'compact'. This was caused by a class being added on the surrounding buttons.

#### Ticket Link
Fixes [MM-42472](https://mattermost.atlassian.net/browse/MM-42472)

#### Screenshots
|  before  |  after  |
|----|----|
|Screenshot 2022-03-18 at 15 40 07|Screenshot 2022-03-18 at 15 39 31|

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — APPROVED** [review]

**Comment by jgilliam17** [comment]
Updating (just incase) so I can trigger e2es without any issues

**Comment by jgilliam17** [comment]
e2e cycle is failing on the dashboard, updating again to see if that fixes it

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge - pending e2e report, having some issues with the pipeline at the moment and will update here when that is resolved.
- Verified alignment of the items in the thread footer when using compact message display setting.

**Comment by jgilliam17** [comment]
@michelengelen When dev reviews are done we can merge without e2es. 
I didn't realize right away on Friday that this PR is not going to be merged to master, hence e2es were failing to start (thanks @furqanmlk for pointing that out) I can create a follow up to fix tests after merge, if needed.

**Review by jgilliam17 — APPROVED** [review]

**Comment by michelengelen** [comment]
@pvev gentle reminder to review

**Review by pvev — APPROVED** [review]
LGTM! nice work @michelengelen :shipit:

**Comment by jgilliam17** [comment]
I should have updated before commenting above. 
Thanks for changing base to master.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/173292-43aea65-onprem-ent-webapp-pr-10029-mm-ee-test:43aea65/mochawesome.html) looks good, no PR related failures.

**Pull request merged**
