### PR TITLE
MM-41211: Allows SessionLengthSSOInDays to validate and accept a decimals.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Allows `ServiceSettings.SessionLengthSSOInDays` config setting to validate and accept a decimals value.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41211

#### Related Pull Requests

* https://github.com/mattermost/mattermost-server/pull/19396

#### Screenshots

Screen Shot 2022-01-21 at 3 18 22 PM

#### Release Note

```release-note
Allows System Console > Environment > Sessions Lengths > Session Length SSO (days) to have a decimal value, for example 0.5.
```

### CODE REVIEW

**Comment by mkraft** [comment]
@BenCookie95 @harryfromwork Please don't interrupting your growth sprint for this, I'm just opening it for afterwards.

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
Should this PR also include the wording update?

**Review by jespino — APPROVED** [review]
LGTM

**Comment by lindy65** [comment]
Hi @mkraft :)

Does the server PR need merging before I test this PR?  At present, trying to change the setting in question to 0.5 does not work and the value is replaced by 0 (zero).

**Comment by mkraft** [comment]
> Hi @mkraft :)
> 
> Does the server PR need merging before I test this PR? At present, trying to change the setting in question to 0.5 does not work and the value is replaced by 0 (zero).

Looking at the commit ID (aka build hash) for the server side code being used in that spinwick, it's using a server build back from Jan 21st so not only did it not pickup the matching server branch it didn't even use the latest master. I'm assuming this is some bug in the CI setup.

When it's working you can expect to see a commit ID from here: https://github.com/mattermost/mattermost-server/pull/19396/commits (ex `8dadb9c347d97b4500b8d405ff43baaa5b0f8a48`).

I'll toggle the spinwick and see if that fixes it.

**Comment by lindy65** [comment]
Yep, that fixed it :) Thanks @mkraft!

**Review by lindy65 — APPROVED** [review]
Thanks @mkraft - looks good to me :+1 

`SessionLengthSSOInDays` can be changed to a decimal value (e.g. 0.5). Actual testing of session length in an SSO environment will be tested post merge.

**Comment by lindy65** [comment]
Perfect, thanks @mkraft :)

**Pull request merged**
