### PR TITLE
[MM-35703]: Maintain scroll position in channel when opening reply message permalinks(Fix reverted PR)

### PR DESCRIPTION
**Pull request by kyeongsoosoo**
#### Summary

In the [original PR](https://github.com/mattermost/mattermost-webapp/pull/10723), we reverted it because there was an unrelated code change.
I fixed the issue by reverting the commit. 

#### Related Pull Requests

- https://github.com/mattermost/mattermost-webapp/pull/10723
- https://github.com/mattermost/mattermost-webapp/pull/11407

#### Release Note

```release-note
Maintain scroll position in channel when opening reply message permalinks(Fix reverted PR)
```

### CODE REVIEW

**Comment by kyeongsoosoo** [comment]
@hmhealey @BenCookie95 I re-opened a PR!

**Review by BenCookie95 — APPROVED** [review]
LGTM, thanks!

**Review by jgilliam17 — APPROVED** [review]
Thanks @kyeongsoosoo 
Tested, looks good to merge.
Verified main channel scroll position is maintained when opening reply permalinks.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/257586-d7f810b-onprem-ent-webapp-pr-11444-mm-ee-test:d7f810b/mochawesome.html) - no PR related failures.

**Pull request merged**
