### PR TITLE
MM-17477: Fix for group display name column expanding too large when …

### PR DESCRIPTION
**Pull request by mkraft**
…the name wraps.

#### Summary

Identified by QA during the case where a group's display name is > 128 characters in the linking phase: this change fixes the styling when the name wraps.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-17477

### CODE REVIEW

**Comment by amyblais** [comment]
@mkraft @lindalumitchell Is this urgent for v5.16 or can this be for v5.17?

**Comment by michaelgamble** [comment]
@mkraft is there a reason we aren't clipping the characters with an ellipses?

**Comment by lindalumitchell** [comment]
@amyblais there was also an issue with the link not working when the name was too long, so I think this probably should be for v5.16.

@mkraft can you confirm whether the display issue is separate from the functionality issue, or whether they are fixed together?

**Comment by amyblais** [comment]
https://github.com/mattermost/mattermost-server/pull/12751

**Comment by lindalumitchell** [comment]
Ah cool, I thought that server PR was just display-related as well rather than function-related, thanks Amy.

**Comment by michaelgamble** [comment]
@lindalumitchell i couldnt figure out how to retest this to see if its been updated with my elipses suggestion or not..

**Comment by mkraft** [comment]
@michaelgamble Per your ellipsis question... are you proposing adding an an ellipsis and only displaying less than 128 characters (which is the max) of the group display name?

**Comment by michaelgamble** [comment]
yeah thats my suggestion, having it extend and overlap other columns of data or break the table visually seem like a worse aesthetic

I think there is a way to do it in CSS where the content is dynamically cut off based on the available width of the div that the content sits in with an elipses.. in my opinion that would be the best scenerio to solve this problem.

**Comment by mkraft** [comment]
@michaelgamble Is it currently extending and overlapping other columns with this fix? If so I wasn't aware of that. Also, how many characters would you have it display prior to en ellipsis?

**Comment by michaelgamble** [comment]
Last time i was able to look at a working test server with it, the overlapping is what i was seeing..

As far as the solution, it doesn't need to be a fixed character limit, you can just set the text-overflow:ellipsis; I think that will do what we want.

**Comment by lindalumitchell** [comment]
@mkraft @michaelgamble is this one still in process for v5.17? Ideally we should aim to complete and review by EOD Thursday if possible for code complete.

**Comment by mkraft** [comment]
@michaelgamble Here's the screenshot with your requested changes:

Screen Shot 2019-10-31 at 10 02 38 AM

**Comment by mkraft** [comment]
@lindalumitchell This is ready for QA now.

**Comment by lindalumitchell** [comment]
@mkraft I'm testing this, and the display issue looks good, but I still am unable to click the link to link the group with the long name (it says Link Failed), and for some reason the LDAP sync is stuck on Pending as well.

I tried the same LDAP instance on a v5.16 server and a master server, and both connected and synced without issue. So I'm not sure if there's an issue here that needs attention, or if somehow something expected is causing different behavior.

Can you take a look with a test instance of LDAP that you have and see if anything looks wrong?

**Comment by lindalumitchell** [comment]
Chatting with @mkraft and got the correct LDAP setup, and it is now connecting and syncing as expected, but linking the group with the long, truncated name is still failing.

**Comment by lindalumitchell** [comment]
@mkraft I think this is good to merge in and cherry-pick?

**Pull request merged**
