### PR TITLE
[MM-38992] : Remove beta label from CRT user settings text and move settings up

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Remove the beta label from CRT user settings text and move settings up

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-38992
  Fixes https://mattermost.atlassian.net/browse/MM-44453

#### Related Pull Requests
``None``

#### Screenshots
|  before  |  after  |
|----|----|
| image-2021-10-01-09-41-01-014 | Screenshot 2021-11-22 at 11 16 28 AM |

#### Release Note
```release-note
* Removing CRT beta labels
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
Hey @AshishDhama seems like the tests are failing, can you fix them

**Comment by koox00** [comment]
@esethna should we change the copy in the system's console as well?
Screenshot 2021-11-22 at 12 56 07 PM

**Comment by AshishDhama** [comment]
> Hey @AshishDhama seems like the tests are failing, can you fix them

@Willyfrog there is an issue on master, due to which type check is failing.
@koox00 there is another ticket for that.

**Review by Willyfrog — APPROVED** [review]

**Comment by esethna** [comment]
@koox00 yes but that's a separate ticket: https://mattermost.atlassian.net/browse/MM-32692

**Review by koox00 — APPROVED** [review]

**Review by esethna — APPROVED** [review]
@amyblais this should be merged for the January release, please provide guidance on when it is safe to merge to master

**Comment by amyblais** [comment]
> @amyblais this should be merged for the January release, please provide guidance on when it is safe to merge to master

@esethna It can be merged anytime.

**Comment by Willyfrog** [comment]
@AshishDhama can you fix the conflicts and ensure is up to date

**Comment by AshishDhama** [comment]
@jgilliam17 Could you please check if any test failed because I checked everything looked fine to me.
@esethna Should we merge this as well?

**Comment by esethna** [comment]
Added the do not merge as we should hold off until we go GA

**Comment by amyblais** [comment]
@esethna @AshishDhama Is this ready to be merged? Feature complete for v7.0 is on May 18th.

**Comment by AshishDhama** [comment]
@amyblais will resolve the conflict, then it will be ready.

**Comment by esethna** [comment]
@AshishDhama please merge when ready

**Review by Willyfrog — APPROVED** [review]

**Comment by amyblais** [comment]
@jgilliam17 This is now ready for testing.

**Comment by AshishDhama** [comment]
@jgilliam17 Gentle reminder, this is ready for review and needed for 7.0

**Comment by jgilliam17** [comment]
Thanks @AshishDhama looks good to merge
- Verified beta label has been removed, option moved up in user settings and help text changes
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/201173-9ecc624-onprem-ent-webapp-pr-9404-mattermost/mm-ee-test9ecc624/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Comment by amyblais** [comment]
@AshishDhama Needs a manual cherry-pick to ``release-7.0``.

**Pull request merged**
