### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-webapp_master/) for mattermost/mattermost-webapp_master.

### CODE REVIEW

**Comment by metanerd** [comment]
> nl.json looks good to me on the first sight. But it says only 76% is translated while we had 100% translated.

In weblate you mean? There were new translation strings added while we migrated.

**Comment by metanerd** [comment]
> > > nl.json looks good to me on the first sight. But it says only 76% is translated while we had 100% translated.
> > 
> > 
> > In weblate you mean? There were new translation strings added while we migrated.
> 
> No, weblate looks good! I was refering to the commits here.

Where is this 76%? I cannot find it.

**Comment by ctlaltdieliet** [comment]
> 
> 
> > > > nl.json looks good to me on the first sight. But it says only 76% is translated while we had 100% translated.
> > > 
> > > 
> > > In weblate you mean? There were new translation strings added while we migrated.
> > 
> > 
> > No, weblate looks good! I was refering to the commits here.
> 
> Where is this 76%? I cannot find it.



> 
> 
> > > > nl.json looks good to me on the first sight. But it says only 76% is translated while we had 100% translated.
> > > 
> > > 
> > > In weblate you mean? There were new translation strings added while we migrated.
> > 
> > 
> > No, weblate looks good! I was refering to the commits here.
> 
> Where is this 76%? I cannot find it.

Knipsel

**Comment by metanerd** [comment]
> > > > > nl.json looks good to me on the first sight. But it says only 76% is translated while we had 100% translated.
> > > > 
> > > > 
> > > > In weblate you mean? There were new translation strings added while we migrated.
> > > 
> > > 
> > > No, weblate looks good! I was refering to the commits here.
> > 
> > 
> > Where is this 76%? I cannot find it.
> 
> > > > > nl.json looks good to me on the first sight. But it says only 76% is translated while we had 100% translated.
> > > > 
> > > > 
> > > > In weblate you mean? There were new translation strings added while we migrated.
> > > 
> > > 
> > > No, weblate looks good! I was refering to the commits here.
> > 
> > 
> > Where is this 76%? I cannot find it.
> 
> Knipsel

Ah, thank you for showing me. That is indeed strange. 
`Currently translated at {{ stats.translated_percent }}% ({{ stats.translated }} of {{ stats.all }} strings)` this is what it uses in the commit message.

**Comment by jespino** [comment]
@metanerd Looks like this is including a lot of translations from languages that are not officially supported yet.

**Pull request merged**
