### PR TITLE
MM-47101 : Migrate "components/channel_notifications_modal/components/describe.jsx" to Typescript

### PR DESCRIPTION
**Pull request by VishakhaPoonia**
#### Summary
Migrate "components/channel_notifications_modal/components/describe.jsx" to Typescript

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/21068
  Jira: https://mattermost.atlassian.net/browse/MM-47101

#### Related Pull Requests
NA

#### Screenshots
NA

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]
🆗  It looks good to me. Thank you

**Review by jgilliam17 — APPROVED** [review]
Thanks @VishakhaPoonia 
Tested, looks good to merge.
Verified channel notifications modal is working as before.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/246598-9be3d97-onprem-ent-webapp-pr-11239-mm-ee-test:9be3d97/mochawesome.html) - no PR related failures.

**Comment by jgilliam17** [comment]
@M-ZubairAhmed can you please approve the workflow and merge. - thanks 🙂

**Pull request merged**
