### PR TITLE
[GH-18621] : Add capability in plugin/apps forms to resize textarea via draggable corner

### PR DESCRIPTION
**Pull request by jatinmark**
#### Summary
 in this pull request the i make the resizable prop from false to true of app-form-field.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/18621

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
updates : components/apps_form/apps_form_field/apps_form_field.tsx
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@jatinmark Could you please update the description with more details

**Comment by jatinmark** [comment]
Now , you can see the description i added the details regarding changes

**Comment by jatinmark** [comment]
Now , you can see the description i added the details regarding changes

**Comment by AshishDhama** [comment]
@jatinmark I don’t see the need of duplicating the whole file, I think setting the `resizable` prop to` true` should do the trick. 
Could you please go to this https://developers.mattermost.com/contribute/more-info/getting-started/ and make sure everything is there?
About CLA, it will update the next time you push a commit.

**Comment by jatinmark** [comment]
I want to ask that for the second link  i have to make another pr ?

**Comment by jatinmark** [comment]
i make an another PR with proper protocol and also make changes in the second link provided in the issue.

**Comment by AshishDhama** [comment]
@jatinmark could please make both changes in same pr.

**Comment by jatinmark** [comment]
I make both the changes in second PR you can check  it and consider it to be as Main PR.

**Comment by jatinmark** [comment]
So , if you agree with that i can close this PR .

**Comment by AshishDhama** [comment]
closing in favour of https://github.com/mattermost/mattermost-webapp/pull/11321

**Pull request closed without merging**
