### PR TITLE
[MM-20377] Convert persist_gate to TypeScript 

### PR DESCRIPTION
**Pull request by LauSam09**
#### Summary
This pull request converts the `persist_gate` component in the webapp to TypeScript. To do this I had to add a new `initialization` variable definition to the redux storage type.

#### Ticket Link
Fixes mattermost/mattermost-server#16730
https://mattermost.atlassian.net/browse/MM-20377

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR and for the help with this migration, @LauSam09. This looks good to me!

**Review by calebroseland — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @LauSam09 
Looks good to merge.

**Comment by hmhealey** [comment]
Thanks again for the PR! This'll be on Mattermost Cloud in a few weeks and then Mattermost 5.33 a couple weeks after that.

**Pull request merged**
