### PR TITLE
MM-21322 - Show page not found when navigating to missing plugin config page

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Display `Page not found` when navigating to a missing plugin setting page.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-21322

#### Screenshots
image

### CODE REVIEW

**Comment by jespino** [comment]
Pending of UX review @michaelgamble can you review this or assign it to the correct UX person to review it?

**Comment by michaelgamble** [comment]
This seems like a use case that is related to the plugins workflow, and i'm going to re-assign this ticket to @asaadmahmood as the design reviewer.

I went and checked the current system console behaviour, when you try to navigate to a page that doesn't exist it just dumps you to the root default "Edition and License" page in system console.

Whats implemented in this pr is not acceptable from my perspective.. so i don't know if we want to follow the existing behaviour, or actually figure out the use case in more detail and come up with a proper solution addressing this flow in context of the plugins.

As long as the net result is not a blank page with a title :)

**Comment by ali-farooq0** [comment]
Thanks for taking a look @michaelgamble! I tried implementing the default behaviour, to be consistent. However, at the time of loading the page we don't have enough information to figure out if someone navigated to the wrong pluginID or if the data is still loading. We can add hooks to figure that piece out, but that requires a bit more work. So in the mean time I went with the proposed solution, which is to show `Page not found` when navigating to plugin settings page that doesn't exist.

Will touch base with @asaadmahmood on how he wants to move forward on this.

**Comment by asaadmahmood** [comment]
@ali-farooq0 @prapti How does a person land on this page to begin with?
Is it because he navigates to a specific url? And if so, where did he get that url from? his browser history?

**Comment by ali-farooq0** [comment]
@asaadmahmood updated to show an error description and a link to the `plugin_management` page

image

**Pull request merged**
