### PR TITLE
MM-13945 - Updating spinner icon

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-13945 - Updating spinner icon

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-13945

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Needs to be implemented in mobile (link to PR or User Story)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@esethna This fixes the spinner issues in the center channel and the modal. Have a look. Once done, just mark this PR for Dev review.

**Comment by esethna** [comment]
@asaadmahmood I can't seem to upload files: 
image

**Comment by asaadmahmood** [comment]
@esethna No iea, @jwilander Any ideas?

**Comment by jwilander** [comment]
Not sure, looks like an issue with the spinmint. Let me know if the new one doesn't work

**Comment by esethna** [comment]
@jwilander same issue, if you don't mind looking into it?

**Comment by jwilander** [comment]
Fixed here as well @esethna

**Pull request merged**
