### PR TITLE
MM-47237: Migrate /account_settings/profile/ tests to TypeScript

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
Migrate /account_settings/profile/ tests to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21287
JIRA: https://mattermost.atlassian.net/browse/MM-47237

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by furqanmlk** [comment]
@sinansonmez 
Thank for picking up this ticket 
Actually there is already a PR open for this ticket, this PR is mentioned in the ticket as reference. 

https://github.com/mattermost/mattermost-webapp/pull/11254

Let me ask reviewers to merge this so can add your changes. 
Sorry about the confusion

**Comment by furqanmlk** [comment]
@sinansonmez 
Sorry this PR was already created https://github.com/mattermost/mattermost-webapp/pull/11254
It has been merged, see if you can further improve or close this PR.

**Comment by furqanmlk** [comment]
@sinansonmez 
do you still want to work on this PR ?

**Comment by sinansonmez** [comment]
I will check the merged PR and see if I can improve anything. If not I will close this PR @furqanmlk

**Comment by sinansonmez** [comment]
@furqanmlk as you already did a great job in the other PR, I am closing this one. You can close the issue as well

**Pull request closed without merging**
