### PR TITLE
MM-21876 Fix toast not showing up on marking channel as unread again

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
  * Use change in lastViewedAt on client to determine if channel is marked as unread again. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21876

Known issue: Toast wont show up if the same message is marked as unread. This case is hard to solve as it is. We could consider keeping a counter for keeping tracking for this i.e something of the sorts 2times marked as unread etc but otherwise this is hard to do with redux state.

### CODE REVIEW

**Comment by sudheerDev** [comment]
@esethna @andrewbrown00 

There is one case this PR still does not solve. i.e marking the same message as unread. IMO we should leave it as a known issue as solving it means tracking some unnecessary changes we most likely ever use.

**Comment by andrewbrown00** [comment]
@sudheerDev what do you think the mana would be to fix this issue?

**Comment by sudheerDev** [comment]
> @sudheerDev what do you think the mana would be to fix this issue?

Talked with ES on this. We are going to leave this as known issue for now. It is not hard < 8 Mana but the code is always be hacky and it will be specifically for this corner case.

**Pull request merged**
