### PR TITLE
MM-27444 removal of jquery from brand_image_settings

### PR DESCRIPTION
**Pull request by bharateshwq**
removed jquery from components/admin_console/brand_image_setting/brand_image_setting.jsx

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15163
https://mattermost.atlassian.net/browse/MM-27444

### CODE REVIEW

**Comment by devinbinnie** [comment]
Hey @bharateshwq, thanks for your contribution!

Would you be able to sign the CLA as per the comment above? Once you do so, let us know and we can have a look at your PR. Thanks!

**Comment by bharateshwq** [comment]
Hey,
I had changed my GitHub username recently.
But now I've filled the cla with the new username.

**Comment by hmhealey** [comment]
Thanks for signing that. Did you mean to close the PR, or was that done by accident?

**Comment by bharateshwq** [comment]
I'm sorry it think I clicked by accident.
I didn't mean to close the PR

**Comment by devinbinnie** [comment]
Thanks @bharateshwq.
Looks like you have a couple lint errors to resolve:
```
/root/mattermost/mattermost-webapp/components/admin_console/brand_image_setting/brand_image_setting.jsx
  83:1   error  Expected indentation of 16 spaces but found 15  indent
  83:42  error  Trailing spaces not allowed                     no-trailing-spaces
```

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the help with this, @bharateshwq. I've tried this out on the test server, and I'm seeing the following error when I try to upload a brand image
Screen Shot 2020-10-08 at 11 45 33 AM

**Comment by hanzei** [comment]
@bharateshwq Can you reproduce the error locally?

**Comment by jfrerich** [comment]
Hi @bharateshwq, have you been able to reproduce the error locally, as suggested by @hanzei?  Also, there is a merge conflict you will need to fix before we can merge the PR.

**Comment by lieut-data** [comment]
Thanks for the help with this one, @bharateshwq! Closing to re-open.

**Pull request closed without merging**
