### PR TITLE
MM-10500 - Implementing Relay chat UI updates

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-10500 - Implementing Relay chat UI updates

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10500

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Ran `make check-style` to check for style errors (required for all pull requests)
- [ ] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

Have a look @esethna. 
Did all the changes in the ticket except the font on the user generated image. That has to be done on the server, so probably better for a dev to look at that. (that also has to be done as a separate PR to the server repo).

### CODE REVIEW

**Comment by esethna** [comment]
Thanks Asaad, a few comments:

1. Not sure we want to take the decreased size of team icons. I actually think they look better on pre-release - or maybe we just decreased the size a bit too much. Seems like a lot of empty space. I'll leave it up to your judgement.

2. "+" icon in the create team box seems too heavily weighted.

^ If you can address these points (if you agree). Then we should probably post the link to this server in the spec reviews channel plus a list of the changes that we made, mentioning that we just took some pieces from the original RelayChat PR.

**Comment by asaadmahmood** [comment]
1. I like the breathing room now compared to pre-release. Relay had the team icon sized to 32px by 32px, I made them 36 by 36 in the instance.
2. I agree, relay chat had that heavy one, I'd like to go with a thinner one. Mike was leaning with a heavy one.
3. I think we should. And probably on other places as well. LHS header, team selection menu, etc.

I'll wait for @michaelgamble feedback on this before I move forward.

**Comment by michaelgamble** [comment]
Hey @asaadmahmood would it be possible for us to whip together a few designs in sketch.. its hard to make these calls without the ability to easily / quickly compare.

My feedback is somewhat inline with @eric:
1. would like to compare the size change, maybe something in-between current and what you have implemented in this PR
2. I agree the plus icon looks a bit big / imbalanced with the team names - they should feel balanced
3. Im not crazy about both letters being lowercase - Maybe first only, or both uppercase?
4. How much bigger are the emoji / attach icons? wondering if maybe something in-between is needed (hard to gauge without seeing it)

Things that look good to go:
- I like the removal of the team descriptions
- The post control hover menu look good

Lets do a quick zoom on Tuesday and sort out the tweaks (might be the quickest way)

**Comment by asaadmahmood** [comment]
Sounds cool.

**Comment by cpanato** [comment]
Removed the test server. doing some cleanup.

Thanks for this PR :)

**Comment by jasonblais** [comment]
@asaadmahmood One concern with removing the team name entirely is that you won't be able to distinguish between "Marketing" and "Mattermost" teams. But maybe we assume people use team icons instead. Do we have any stats on how many people use the team icon?

**Comment by lfbrock** [comment]
Changes look good to me. I'm okay with removing the name on team buttons since we have team icons now, but @esethna I think we should run it by IT as well since that was originally his design decision. 

0/5 on this and maybe we should do it separately, but @asaadmahmood do you think we should also update our other dropdown/pop up menus to have more rounded corners to be more consistent? For example in this screenshot the post menu and then the ... menu look like they're different styles. 

screenshot 2018-05-29 08 29 54

**Comment by asaadmahmood** [comment]
@lfbrock I think I can do that in this PR. I'll also update the designs.

**Comment by asaadmahmood** [comment]
@jasonblais Pretty sure that focus thing is not due to my PR. Regarding the team icons, yes. Now that we have team icons, we have a way to differentiate between teams. Plus since the team icons feature is new, not sure how accurately would it represent the usage of Team icons, but maybe @esethna has stats on that.

**Comment by asaadmahmood** [comment]
@lfbrock Spinmint is up with the rounded corners.

**Comment by hmhealey** [comment]
@asaadmahmood This needs a rebase before it can be merged

**Comment by asaadmahmood** [comment]
@hmhealey Done, also a package.json file got committed. See if I need to take that out.

**Comment by hmhealey** [comment]
I don't think this PR should be changing package-lock.json. It looks like you're reverting it to an older version of the file. If you have the latest version of master checked out, you can do `git checkout master -- package-lock.json` to get that file from the master branch

**Comment by asaadmahmood** [comment]
Done @hmhealey

**Comment by hmhealey** [comment]
Looks good now

**Pull request merged**
