### PR TITLE
[MM-14491] avoid hiding the popover when the cursor is moved away fro…

### PR DESCRIPTION
**Pull request by kosgrz**
…m the link to the popover

#### Summary
Gifs to illustrate the change:
#### Before
before
#### After
after

#### Ticket Link
(Jira ticket)[https://mattermost.atlassian.net/browse/MM-14491] | Fixes [GitHub issue #10424](https://github.com/mattermost/mattermost-server/issues/10424)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @kosgrz - do you have sample data I can populate the spinmint with that includes a link with a pop-over?

**Comment by kosgrz** [comment]
Hi @lindy65 - you can use my modified version of the Demo Plugin here: https://github.com/kosgrz/mattermost-plugin-demo/tree/test-button
You need to download it, build and install on the server.
This version of the plugin displays a popover with a button whenever the cursor is moved to any link in any post.

**Comment by lindy65** [comment]
Thank you @kosgrz !

Tested on the spinmint - hovering over the link in the text causes the pop-up to display and I am able to move my cursor to the pop-up to click on the button.

Looks good to me, thanks again!

**Comment by lindy65** [comment]
@crspeller - I think this PR is good to merge :)

**Comment by hanzei** [comment]
Thanks @kosgrz for the contribution!

**Pull request merged**
