### PR TITLE
MM-44900 Never roll back last_viewed_at when receiving channel members

### PR DESCRIPTION
**Pull request by hmhealey**
There's a race condition when switching teams to view an unread channel which has been made more common since we fixed an issue where we actually used to mark the channel as read 3 times when switching teams.

We mark the channel as read on viewing it, but at the same time, we're reloading all of your channels and channel members because you switched team. It's currently possible to mark the channel as read when you change teams and then receive the response to the request so that the channel is marked as read in the UI and then shows as unread. It's not actually unread though.

This is attempting to fix that by checking the last_viewed_at of each channel member before saving those received channel members. If the last_viewed_at is lower in a received channel member, then we've hit this race condition and the result from the server is out of date. In that case, we use the unread status from the existing channel member.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44900

#### Release Note
```release-note
Fixed a race condition where switching teams to an unread channel may not appear to mark that channel as read
```

### CODE REVIEW

**Comment by amyblais** [comment]
I changed the reviewer as Ben is out of office.

**Review by koox00 — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
- Verified unread behavior when changing channels on different team using channel switcher.
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/210895-9a1e62a-onprem-ent-webapp-pr-10589-mattermost/mm-ee-test9a1e62a/mochawesome.html)looks good, no PR related failures.

**Pull request merged**
