### PR TITLE
Making the scrollbar on pdfs previews always visible

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Making the scrollbar on pdfs previews always visible

#### Ticket Link
[MM-33370](https://mattermost.atlassian.net/browse/MM-33370)

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]
LGTM

**Review by nevyangelova — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @jespino 
Tested, looks good to merge.
- Verified PDF preview window displays scrollbars (when applicable). 
- Verified navigation arrows, when viewing multi-attachment PDFs, sit just outside of the PDF preview module and no longer interfere with the vertical scrolling.

**Pull request merged**
