### PR TITLE
[MM-46538]: Add Yearly/Monthly toggle UI Changes to Purchases Modal

### PR DESCRIPTION
**Pull request by emmyni**
### **Yearly/Monthly Toggle**
Added the new yearly/monthly toggle to the purchases page and updated the monthly and yearly view.

On the yearly view, there is an input field that takes in the number of users and displays the total cost of a yearly subscription for the given number of users. It also displays the discount compared to the monthly plan. The initial number in the input field matches the number of users in the workspace and there is a tooltip next to the input field that explains that. If the user inputs a value less than the number of users in the workspace (or something that is not whole number), it displays an error message in red (shown in the video below). 

### **Telemetry**
Added telemetry for when the yearly/monthly switch is clicked (as noted in https://mattermost.atlassian.net/browse/MM-46565). It is being tracked under the 'cloud_purchasing' category with the name 'click_yearly_toggle'. The yearly/monthly toggle on the pricing modal has the same name, but is under the 'cloud_pricing' category. I've also made 'cloud_pricing' into its own constant under `TELEMETRY_CATEGORIES `, so a few other files that were tracking for the 'cloud_pricing' category were updated. 

The telemetry for the “See how billing works” link is clicked already existed, so no changes where made there.

Note: The numbers used for the yearly and monthly plan are from the mocked CWS (currently using $7.50/month for the yearly plan and $10/month for the monthly plan)

#### Ticket Link

[MM-46538](https://mattermost.atlassian.net/browse/MM-46538)
[MM-46565](https://mattermost.atlassian.net/browse/MM-46565)

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Screenshots

Before:
image
After:
image 
image

Video:
https://user-images.githubusercontent.com/44761757/199163057-378b8636-d093-431a-9ae4-0562a949ccbe.mov

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
hey @emmyni it seems that you are using the same commits as of https://github.com/mattermost/mattermost-webapp/pull/11473 to work on this issue. Here is what i would have done since it has dependency on other pr and to avoid conflicts arising due to it.
- Wait for first pr to get merged in
- Or open the second pr with the first's pr branch as base.

**Comment by emmyni** [comment]
> hey @emmyni it seems that you are using the same commits as of #11473 to work on this issue. Here is what i would have done since it has dependency on other pr and to avoid conflicts arising due to it.
> 
> * Wait for first pr to get merged in
> * Or open the second pr with the first's pr branch as base.

@M-ZubairAhmed Yeah, sounds good. I originally just opened this PR as "work in progress" so I can fix the CI checks that aren't passing. But, I'll eventually switch the branch to my [11473](https://github.com/mattermost/mattermost-webapp/pull/11473) branch. Is that alright even if the other branch is also on my forked version of mattermost-webapp? Thanks

**Comment by M-ZubairAhmed** [comment]
> > hey @emmyni it seems that you are using the same commits as of #11473 to work on this issue. Here is what i would have done since it has dependency on other pr and to avoid conflicts arising due to it.
> > 
> > * Wait for first pr to get merged in
> > * Or open the second pr with the first's pr branch as base.
> 
> @M-ZubairAhmed Yeah, sounds good. I originally just opened this PR as "work in progress" so I can fix the CI checks that aren't passing. But, I'll eventually switch the branch to my [11473](https://github.com/mattermost/mattermost-webapp/pull/11473) branch. Is that alright even if the other branch is also on my forked version of mattermost-webapp? Thanks

yeah sounds good

**Comment by annelieseklein** [comment]
@emmyni not able to see the toggle for some reason?

**Comment by marianunez** [comment]
> @emmyni not able to see the toggle for some reason?

Same as the other one: https://github.com/mattermost/mattermost-webapp/pull/11473#issuecomment-1299204828 

The feature flag needs to be enabled in the test server

**Review by nickmisasi — COMMENTED** [review]
Just commenting so you can re-request review after https://github.com/mattermost/mattermost-webapp/pull/11473 has been merged

**Comment by emmyni** [comment]
Closed and moved to https://github.com/mattermost/mattermost-webapp/pull/11535

**Pull request closed without merging**
