### PR TITLE
Add S3 prefix configuration to the admin console

### PR DESCRIPTION
**Pull request by dpanic**
#### Summary
This PR is related to change in mattermost-server https://github.com/mattermost/mattermost-server/pull/14917

It adds S3 prefix configuration to the admin console.

### CODE REVIEW

**Comment by dpanic** [comment]
> Looks good! The only thing - package-lock.json I think should be excluded from the PR

removed

**Comment by jespino** [comment]
@dpanic the comment was more about not including the changes of the file. I going to fix everything here, and merge it with the other PR.

**Comment by jespino** [comment]
ok, I can't because is in your master branch. Please restore the `package-lock.json` using the `origin/master` branch and then merge the `origin/master` branch in your master branch.

```
git fetch origin
git checkout origin/master -- package-lock.json
git commit -a -m "restoring package-lock.json"
git merge origin/master
git push
```

That list should do the trick.

**Comment by dpanic** [comment]
> @dpanic the comment was more about not including the changes of the file. I going to fix everything here, and merge it with the other PR.

Oh I see, sorry about that

**Pull request merged**
