### PR TITLE
[MM-23645] - Align mention badge according to ticket requirements

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Aligns mention badge according to UX requirements

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23645

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Comment by andrewbrown00** [comment]
@nevyangelova or @devinbinnie will you confirm the changes are in, I opened the test server but it seems like some of the styles are being overwritten and the CSS doesn't match the changes.

image image

**Comment by nevyangelova** [comment]
@andrewbrown00 fixed

**Comment by esethna** [comment]
image

@nevyangelova, 0/5 thoughts, font weight is too thin and doesn't match design. "2" is not aligned properly in the center of the bubble (see there is more padding above the "2" than below it compared to design)

See design
image

**Comment by nevyangelova** [comment]
@esethna pushed the fix for the font-weight, but the padding seems good to me, in fact if i change it, it distorts it for other numbers.

**Review by andrewbrown00 — CHANGES_REQUESTED** [review]
@nevyangelova thanks for turning this around so quick! Minor update...

- [x] Increase the padding to `padding: 0 8px;`
- [x] Add letter spacing of `letter-spacing: 0.4px;`

**Intended outcome**

image

image

image

**Comment by deanwhillier** [comment]
Did some 'pixel-pushing' with @andrewbrown00  and submitted the results after chatting with @nevyangelova. 🙂

**Review by andrewbrown00 — APPROVED** [review]
Looks great 🎉 thanks all!

**Test on macOS in the following browsers:**

Chrome | Firefox | Safari
-------- | -------- | --------
image | image | image




**Note**
Firefox seems to shift the font down ~1px, nothing we can do outside of righting browser specific classes which is not worth the overhead.

**Review by deanwhillier — APPROVED** [review]

**Comment by esethna** [comment]
Looks so good! Thanks guys :)

**Review by esethna — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 

Tested, looks good to merge.
- Verified mention badge alignment on Chome, Firefox, Safari and Microsoft Edge.

**Pull request merged**
