### PR TITLE
MM-47361 : Remove global state & dispatch from logged_in.tsx

### PR DESCRIPTION
**Pull request by batebobo**
#### Summary
Included `viewChannel` in `mapDispatchToProps` so that we don't have to call it with `state` and `dispatch` inside the component

#### Ticket Link
fixes https://github.com/mattermost/mattermost-server/issues/21248

#### Related Pull Requests

~- Has server changes (please link here)~
~- Has mobile changes (please link here)~

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
this is awesome and very well thought out

**Review by nevyangelova — APPROVED** [review]
Thanks @batebobo 🎉 🎉 🎉 🎉 🎉

**Comment by nevyangelova** [comment]
cc/ @mkraft

**Pull request merged**
