### PR TITLE
MM-20627: Update wording in SECURITY.md

### PR DESCRIPTION
**Pull request by jupenur**
#### Summary
Copied over some additional wording changes from the server repo.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20627

### CODE REVIEW

**Comment by DSchalla** [comment]
Both the CLA and merge check are stuck currently, toggling a label helped for the update check but not for CLA - FYI @mattermost/core-build-engineers

**Comment by DSchalla** [comment]
TIL, didn't know that one! Thanks @metanerd :-)

**Comment by metanerd** [comment]
@cpanato reminded me during lunch! Great stuff!

**Pull request merged**
