### PR TITLE
[MM-29388] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 505 (#15827)

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

Remove the line as it is unconditionally overidden by linkColor theme at line 833

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15827
JIRA ticket: https://mattermost.atlassian.net/browse/MM-29388

### CODE REVIEW

**Comment by deanwhillier** [comment]
QA review will be done on the final PR that merges all changes to this campaign branch into master.

**Review by asaadmahmood — APPROVED** [review]
If QA has tested this, then fine, because I'm not sure if the duplicated rule exists already.

**Comment by hanzei** [comment]
@ogi-m Could you please give this a reivew?

**Comment by deanwhillier** [comment]
This PR will be QA'd in batch when the campaign branch is merged to master.

**Pull request merged**
