### PR TITLE
Cypress/E2E: Fix MM-T4688 copy text menu and shortcut

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fix MM-T4688 copy text menu and shortcut

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by saturninoabril** [comment]
See [test report](https://mattermost-cypress-report.s3.amazonaws.com/173681-9b2ed5a-onprem-ent-webapp-pr-10039-mattermost/mm-ee-test9b2ed5a/mochawesome.html)
Screen Shot 2022-03-22 at 9 40 20 AM

**Review by jgilliam17 — APPROVED** [review]
Thanks @saturninoabril for a quick fix.

**Review by furqanmlk — APPROVED** [review]
@saturninoabril LGTM
Just quick question 
`get('body').type` shouldn't be in common commands file ?

**Comment by saturninoabril** [comment]
It's only one liner and maybe not makes sense to create another custom command. We're doing that in several places and I feel like it's more readable that way, but it might only be me.

**Pull request merged**
