### PR TITLE
[MM-48570] - Upgrade plan options modal theme issues

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Update background color for plan addons 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48570

#### Screenshots
Screenshot 2023-01-09 at 18 47 39

Screenshot 2023-01-09 at 18 48 14

Screenshot 2023-01-09 at 18 48 39

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by ConorMacpherson — APPROVED** [review]

**Review by Afsoon — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
checked all themes, the text was visible,
Screenshot 2023-01-10 at 7 52 14 PM
Screenshot 2023-01-10 at 7 52 31 PM
Screenshot 2023-01-10 at 7 52 43 PM
Screenshot 2023-01-10 at 7 52 59 PM

**Comment by annelieseklein** [comment]
Screen Shot 2023-01-18 at 8 16 24 AM
the log in information for the most recent server didn't work - and i looked on the old server and couldn't see the view plans button @AGMETEOR

**Comment by annelieseklein** [comment]
Screen Shot 2023-01-18 at 11 41 25 AM
can we please add an 8% center channel text color border around the border of the container (excluding the color banner at the top)

**Pull request merged**
