### PR TITLE
MM-20541: Migrate 'components/user_settings/display/user_settings_theme/premade_theme_chooser' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR migrates 'components/user_settings/display/user_settings_theme/premade_theme_chooser' module (and converts to FC) and associated tests to TypeScript

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13700
JIRA: https://mattermost.atlassian.net/browse/MM-20541

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @sinansonmez!

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @sinansonmez 
Tested, looks good to merge.
- Verified setting for themes - as before.
- [E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/221314-bec9aca-onprem-ent-webapp-pr-10803-mattermost/mm-ee-testbec9aca/mochawesome.html)- no PR related failures.

**Comment by jgilliam17** [comment]
Thanks for noting @sinansonmez I'll create a ticket for follow up

**Comment by jgilliam17** [comment]
https://mattermost.atlassian.net/browse/MM-45938

**Comment by sinansonmez** [comment]
@jgilliam17 It seems like the issue was related to upgrading to React 17 (for [context](https://community.mattermost.com/core/pl/s17rz67icp8r3ndorsuxh3zjaw)), this [PR](https://github.com/mattermost/mattermost-webapp/commit/f8cd6f0e235c1db84dd980aaf86a0adcb5e751e1) fixed the issue. 

The JIRA issue can be closed. Sorry for effort

**Pull request merged**
