### PR TITLE
MM-46634: fixes opening a notification

### PR DESCRIPTION
**Pull request by koox00**
#### Summary
When you have the app minimized and receive messages clicking a
notification will focus the window and then redirect to the channel for
which the notification was clicked.
If the current channel has unread messages focusing the window and then
redirecting would mark current channel as read, which is unintended.

This PR fixes that issue, by first redirecting and then focusing the
window.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-46634

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by michelengelen — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @koox00 
This does not appear fixed for me on the test server. We can have pair-test on Monday. 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/235669-2fb5d12-onprem-ent-webapp-pr-11033-mm-ee-test:2fb5d12/mochawesome.html) looks good, no PR related failures

**Comment by jgilliam17** [comment]
Hi @koox00 - let me know if it's ready for retest. Thanks

**Comment by lieut-data** [comment]
Heads up that as part of our efforts to move to a monorepo, we're closing out a number of older pull requests like this one to help streamline the effort.

If you'd like to preserve these changes -- even if you're not the original author! -- feel free to resubmit the pull request against the monorepo once it's ready. You can subscribe to [mattermost-server-issue-22420](https://www.github.com/mattermost/mattermost-server/issues/22420) for status updates on this effort.

**Pull request closed without merging**
