### PR TITLE
[MM 11170] Remove Loader and someone from LHS

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Removes Loader and someone text from sidebar.

#### Ticket Link
[MM-11170](https://mattermost.atlassian.net/browse/MM-11170)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

This removes deleted users from LHS and reverts to old behavior. 

aug-10-2018 01-58-39

### CODE REVIEW

**Comment by enahum** [comment]
What if there are unread messages, how that gets solved?

**Comment by sudheerDev** [comment]
@enahum They will not be shown as it was previously. That is how it used to work. Adding `Someone` added these scenarios to LHS. So reverting them here.

**Comment by enahum** [comment]
ok and what about the mention count on the window tab, etc?

**Comment by jasonblais** [comment]
@sudheerDev Thanks! Can you help change the base branch from master to 5.2?

**Comment by sudheerDev** [comment]
@jasonblais Just checking all the scenarios for unreads with deleted channel, GM's and DM's. Will do it within the hour.

**Comment by jasonblais** [comment]
@sudheerDev If you'd also like to get QA's help to test this PR before we merge, happy to ask for their help.

**Comment by sudheerDev** [comment]
@enahum mention count for unread deleted users causes an issue while deleted GM's and DM's work fine. This is an existing issue.

I made a redux PR to fix it https://github.com/mattermost/mattermost-redux/pull/597 not sure if this would be a regression and considered for 5.2 and 1.11 so, just in case I am making redux PR.

**Comment by sudheerDev** [comment]
@jasonblais This works as it was before so, I just removed code that was added in https://github.com/mattermost/mattermost-webapp/pull/1502 and in https://github.com/mattermost/mattermost-webapp/pull/1412. 

I was testing the Redux PR. From what i know this PR is good.

**Pull request merged**
