### PR TITLE
[MM-20460] Migrate 'components/permissions_gates/channel_permission_gate' module and associated tests to TypeScript

### PR DESCRIPTION
**Pull request by didithilmy**
Migrates the following files to TypeScript:
- `components/permissions_gates/channel_permission_gate/index.ts`
- `components/permissions_gates/channel_permission_gate/channel_permission_gate.tsx`
- `components/permissions_gates/channel_permission_gate/channel_permission_gate.test.tsx` (the test does not need to be altered, just renamed)

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/15480

#### Related Pull Requests

None

#### Screenshots

None

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @didithilmy!

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @didithilmy. Looks good to me!

**Review by jgilliam17 — APPROVED** [review]
Thank you @didithilmy 
Tested, looks good to merge.
- Verified channel menu options visibility (view/manage members, edit channel details, archive etc)  based on user's permissions.

**Pull request merged**
