### PR TITLE
[MM-45206] fix error message not showing up if user add too long post or RHS comment

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Advanced Text Editor : fix error message not showing up if user add too long post or RHS comment

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-45206
  Fixes https://mattermost.atlassian.net/browse/MM-45394
  
#### Related Pull Requests
NONE

#### Screenshots
Screenshot 2022-06-22 at 1 35 35 AM

Screenshot 2022-06-22 at 1 43 33 AM

#### Release Note
```release-note
Advanced Text Editor : fix error message not showing up if user add too long post or RHS comment
```

### CODE REVIEW

**Review by anurag6713 — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @AshishDhama 
Tested, looks good to merge.
- Verified error message is present on too long posts on main channel and rhs.
- [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/212839-5be875e-onprem-ent-webapp-pr-10628-mattermost/mm-ee-test5be875e/mochawesome.html) looks good, no PR related failures.

**Pull request merged**
