### PR TITLE
fixing show more button for message previews

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
The show more indicator was showing when it wasn't needed.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38158

#### Screenshots
Screen Shot 2021-09-01 at 4 12 07 PM
Screen Shot 2021-09-01 at 4 12 24 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by engineereng — APPROVED** [review]
Looks great to me!

**Comment by furqanmlk** [comment]
@BenCookie95 

Same message preview is different in your ```PR``` and ```Community-daily ```

image


And looks like Issue is not fixed.
Please see the issue here in this instance 
https://mattermost-webapp-pr-8776.test.mattermost.cloud/pr8776/channels/off-topic

**Review by furqanmlk — COMMENTED** [review]
.

**Comment by BenCookie95** [comment]
> @BenCookie95
> looks like Issue is not fixed.
> Please see the issue here in this instance
> https://mattermost-webapp-pr-8776.test.mattermost.cloud/pr8776/channels/off-topic

Looks like it's something to do with the `edited` label. I'll take a look

**Comment by furqanmlk** [comment]
Hi @BenCookie95 
I still the issue, `show more` button does not show show anything.

https://mattermost-webapp-pr-8776.test.mattermost.cloud/pr8776/channels/off-topic


https://user-images.githubusercontent.com/6909890/133167939-96b74a7d-398f-4a18-982a-d5ed4229e8fc.mp4

**Review by furqanmlk — APPROVED** [review]
Working as expected 

Thanks 

https://mattermost-webapp-pr-8776.test.mattermost.cloud/pr8776/channels/off-topic

**Pull request merged**
