### PR TITLE
[MM-49265] Update translations when config is changed

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
Updated label to reflect functionality change.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49265
https://mattermost.atlassian.net/browse/MM-49812

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/21987

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by kostaspt** [comment]
As @furqanmlk noticed while QAing https://github.com/mattermost/mattermost-server/pull/21987 noticed, this inconsistency of the text and the change implemented there.

**Review by BenCookie95 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
LGTM
**Before**
image

**After**
image

**Pull request merged**
