### PR TITLE
[MM-33859] - Transition animation smoothly on long post permalinks

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR introduces the investigation of removing redundant CSS and transitioning long post permalinks smoothly. I believe more CSS can be removed but I would need help with testing it first. So far it works for me.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33895

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Seeing few issues
1. Background for `Show More` is missing
Screen Shot 2021-03-29 at 3 18 24 PM
2. Transition animation  (going from permalink to regular) is out of sync (see video)

https://user-images.githubusercontent.com/52937121/112889543-c1c64e80-90a3-11eb-80eb-1718f658f8c6.mov


3.  When long post is also pinned, the bottom of the post color gradient is present only on mouseover, otherwise it's missing 
Screen Shot 2021-03-29 at 3 27 22 PM

**Comment by nevyangelova** [comment]
@jgilliam17 working for me now.

**Comment by jgilliam17** [comment]
@nevyangelova Can you please check if the fix was applied? I am seeing the same issues on the test server.

https://user-images.githubusercontent.com/52937121/113199535-3b417680-9235-11eb-9f4a-9a3f95d4dc36.mov

**Comment by nevyangelova** [comment]
@jgilliam17 how are you testing? It's working for me when I click from a permalink or pinned post. We can discuss on chat later if you like.

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
Unfortunately `Show more` background is still missing and the animation (from permalink) seems to remove highlight suddenly without fadeout.

Screen Shot 2021-04-07 at 8 55 52 AM

**Comment by nevyangelova** [comment]
@jgilliam17 it works for me, even here on the test server. Could you please check again? I am using chrome on Mac OS Catalina

**Comment by jgilliam17** [comment]
@nevyangelova Something weird is happening, works for admin test user, but not for non-admin

On macOS Catalina:
   - Missing background reproduces for me consistently on Chrome, desktop app (beta1 & beta2), Firefox and Safari for **user-1**, but for sysadmin everything works fine 
   - Additionally on Safari for sysadmin - the bottom of the truncated long post with Show More button looks good on mouse hover, but a bit off when not hovering.
   
https://user-images.githubusercontent.com/52937121/114091707-fd70cd80-9886-11eb-89bd-57c7beeb00ac.mov

On macOS Big Sur
   - Works for sysadmin, but not for user-1
   - On Safari - seeing the same as on Catalina. (see video)

**Comment by nevyangelova** [comment]
@jgilliam17 nice catch! I fixed the problem with the second user. Of course safari interprets transparent differently than other browsers. I added a fix but it still might not be as smooth as on chrome. But I think we have spent enough time on this and we can tweak it later with the compass component implementation.

**Comment by jgilliam17** [comment]
Safari transparency looks bad in dark themes. I am ok with filing and addressing this separately as it's not related to animation. Let me know. Thanks
Screen Shot 2021-04-09 at 8 58 59 AM

**Review by jgilliam17 — APPROVED** [review]
Thank you @nevyangelova 
Tested, looks good to merge.
- Verified transition animation, background of Show More on pinned and permalink posts. 
- Safari related dark theme transition discrepancy is mostly fixed; there is an edge case where a slight difference in shade is visible when user is not hovering over the permalinked/pinned post - this will be fixed after compass components implementation.

**Pull request merged**
