### PR TITLE
Update path to focalboard API

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Focalboard APIs are changing for 7.2. This PR updates the Path to the focalboard APIs. 

This will need to be merged when the builtin Boards Plugin is rev'ed to v7.2.0
https://github.com/mattermost/mattermost-server/pull/20809

#### Release Note
```release-note
Updated path to Boards API
```

### CODE REVIEW

**Comment by wiggin77** [comment]
@sbishel one question.  The API path was changed to `v2` in a previous release via https://github.com/mattermost/focalboard/pull/2781    Not sure how the code in this PR worked in last release. 

On that note, I think there should be a constant defined with the API path so it can be changed in one place.  https://github.com/mattermost/focalboard/blob/393b961a6b6bce0d8e60f74f7beae14b407dfdbb/server/api/api.go#L76

**Comment by sbishel** [comment]
> The API path was changed to `v2` in a previous release via [mattermost/focalboard#2781](https://github.com/mattermost/focalboard/pull/2781) Not sure how the code in this PR worked in last release.

That PR has not been released, even though it was merged back in April. Here is setting in `release-7.1` branch.
https://github.com/mattermost/focalboard/blob/release-7.1/server/api/api.go#L71

**Review by wiggin77 — APPROVED** [review]

**Pull request merged**
