### PR TITLE
Onboarding wizard tweaks

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Fix various UI issues with use case onboarding. Also change max allowed team length to 64 characters (from 15).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29946
https://mattermost.atlassian.net/browse/MM-42050
https://mattermost.atlassian.net/browse/MM-42057

#### Screenshots

https://user-images.githubusercontent.com/13738432/155454626-e9cbeb95-c34e-40e4-8610-cfffd262952b.mp4

#### Release Note

```release-note
Change max allowed team length to 64 characters
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Nice work @neallred. Getting closer for sure!

1. The default state for cards now uses a 1px border, but it looks like the hover state for the card UI still uses 2px border. Can we change to 1px? Only use 2px for the selected state.
2. In the UI preview on the create channel screen, the channel name should also be metropolis (same as team name). Sorry, I missed this last round.
3. Error state on org name - error message needs to have the alert icon to the left of it and the input field itself needs to have a red border when in error.
image
4. For the transition in to the 'Launching your workspace', can we make the titles on the left move off the left edge of the screen and the UI preview on the right move off the right edge of the screen?

**Comment by neallred** [comment]
@matthewbirtch 1-3 have been addressed, and the server has been re-initialized if you could take another look. Will address 4 when I do the horizontal centering.

**Review by matthewbirtch — APPROVED** [review]

**Comment by neallred** [comment]
Re-requested review since I added horizontal alignment and progress line alignment issues.

**Review by AshishDhama — APPROVED** [review]
LGTM!

**Review by AGMETEOR — APPROVED** [review]

**Review by matthewbirtch — APPROVED** [review]
This is amazing. Thanks for resolving @neallred. Looks like you resolved the horizontal centering and the transition at the end as well

**Review by stevemudie — APPROVED** [review]
Looks and works great! Nice stuff @neallred!

Other than the Playbooks issue which you're aware of this is good to go.

**Comment by neallred** [comment]
Cherry pick completed manually.

**Pull request merged**
