### PR TITLE
Migrating storage admin console panel to declarative

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Migrating storage admin console panel to declarative.

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed

### CODE REVIEW

**Comment by jespino** [comment]
@hmhealey I don't know if the declarative implementation needs any thing with the new "environment settings" feature.

**Comment by hmhealey** [comment]
@jespino Nope, it doesn't need anything else. It just needs the `key` set to the full path for the setting in the config, and it should just work.

**Comment by hmhealey** [comment]
Is this for 4.10 or can it wait for 5.0?

**Comment by jespino** [comment]
Yes, exactly, it goes better in 4.11

**Pull request merged**
