### PR TITLE
[MM-5881] Add support for searching by position in user lists

### PR DESCRIPTION
**Pull request by mbecca**
#### Summary

Add support for searching by position in user lists

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-5881

#### Related Pull Requests

https://github.com/mattermost/mattermost-redux/pull/1118
https://github.com/mattermost/mattermost-redux/pull/1123

### CODE REVIEW

**Comment by hanzei** [comment]
@mbecca Thanks for taking the initiative and working on this issue. :rocket: 

@wiersgallak Could you take a look at the PR as it's search related?

**Comment by mbecca** [comment]
> 
> 
> Mattermost test server updated with git commit `346a3cbc436f15549f3763510dd2f64cd579099d`.
> 
> Access here: https://mattermost-webapp-pr-5271.test.mattermost.cloud

sysadmin -> Nickname: nicknameSysadmin and Position: PositionOne

user-1-> Nickname: nicknameUser-1 and Position: PositionTwo

**Comment by lindy65** [comment]
Thanks @mbecca - I'll test once the final dev review is done and the associated redux PR is merged 👍 

@mgdelacroix - please let me know once you've reviewed so I can test :) Thanks!

**Comment by lindy65** [comment]
Hi @mbecca @mgdelacroix - can you let me know once https://github.com/mattermost/mattermost-redux/pull/1118 is merged? Then I'll go ahead and test... Thanks! :)

**Comment by lindy65** [comment]
Hi @mbecca @mgdelacroix - can https://github.com/mattermost/mattermost-redux/pull/1118 be merged? Reviews are complete....

**Comment by mgdelacroix** [comment]
Yes! I've just merged it, thanks for pointing this out @lindy65.

@mbecca we need to update the references in `package.json` and `package-lock.json` to point to

```
"github:mattermost/mattermost-redux#a6e9bb2974a7c383584e9b88af66993a61e099b7"
```

so we can test and merge. I've tried to update your PR but I think GH won't allow me as it's on your `master` branch. Could you please update those refs?

**Comment by lindy65** [comment]
Thanks @mgdelacroix 👍 Once `mbecca` has done the necessary updates, I'll go ahead and test...

**Comment by mbecca** [comment]
> 
> 
> Yes! I've just merged it, thanks for pointing this out @lindy65.
> 
> @mbecca we need to update the references in `package.json` and `package-lock.json` to point to
> 
> ```
> "github:mattermost/mattermost-redux#a6e9bb2974a7c383584e9b88af66993a61e099b7"
> ```
> 
> so we can test and merge. I've tried to update your PR but I think GH won't allow me as it's on your `master` branch. Could you please update those refs?

done!, thx!

**Comment by mbecca** [comment]
> 
> 
> Yes! I've just merged it, thanks for pointing this out @lindy65.
> 
> @mbecca we need to update the references in `package.json` and `package-lock.json` to point to
> 
> ```
> "github:mattermost/mattermost-redux#a6e9bb2974a7c383584e9b88af66993a61e099b7"
> ```
> 
> so we can test and merge. I've tried to update your PR but I think GH won't allow me as it's on your `master` branch. Could you please update those refs?

When reference mattermost-redux with your comments, i have this error when run 'npm run check-types':

components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx:16:34 - error TS2741: Property 'allow_reference' is missing in type '{ id: string; name: string; display_name: string; description: string; type: string; remote_id: string; create_at: number; update_at: number; delete_at: number; has_syncables: false; member_count: number; scheme_admin: false; }' but required in type 'Group'.

 16         const groups: Group[] = [{
                                     ~
 17             id: '123',
    ~~~~~~~~~~~~~~~~~~~~~~
...
 28             scheme_admin: false,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 29         }];
    ~~~~~~~~~

  node_modules/mattermost-redux/types/groups.d.ts:22:5
    22     allow_reference: boolean;
           ~~~~~~~~~~~~~~~
    'allow_reference' is declared here.


Found 1 error.

What am i missing?

M.

**Comment by mbecca** [comment]
@lindy65 ready to test!

**Comment by mbecca** [comment]
> 
> 
> @mbecca it looks like you had a bad merge at some point, as the PR is now modifying more than 70K lines. Could you please take a look?

Hi,

when update de mattermost-redux reference to "github:mattermost/mattermost-redux#a6e9bb2974a7c383584e9b88af66993a61e099b7", I started having errors when run 'npm run check-types'  , which led me to merge with the master ... that's why there are 75 commits. That is wrong?.

Regards, M.

**Comment by mbecca** [comment]
Hello, any news for my previous post?

Regards,

M.

**Comment by mgdelacroix** [comment]
Apologies for the delay @mbecca. Merging with `master` is the right strategy, but now this PR includes several changes to unrelated files that we need to remove before merging.

My recommendation would be to create a branch from the current master, cherry pick the commits you authored, and then replace this branch with the new one.

**Comment by mbecca** [comment]
Hello @mgdelacroix , i revert my bads merge commits. Sorry!.. it all ok now?

Regards,

M.

**Comment by mbecca** [comment]
> 
> 
> Apologies for the delay @mbecca. Merging with `master` is the right strategy, but now this PR includes several changes to unrelated files that we need to remove before merging.
> 
> My recommendation would be to create a branch from the current master, cherry pick the commits you authored, and then replace this branch with the new one.

Hello, I revert my bads merge commits, sorry!, but after update your mattermost-redux suggestion (in package.json  y package-lock.json) with "github:mattermost/mattermost-redux#a6e9bb2974a7c383584e9b88af66993a61e099b7", the npm test and npm run check-types, they started to fail.

M.

**Comment by mbecca** [comment]
> Solved offline, looks good, thanks for your contribution @mbecca !!! :sparkles: 

Thank you for all!, You are very good and patience with the new contributors!

👏👏👏👏

**Pull request merged**
