### PR TITLE
Feature - Cloud Apps

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Merge feature branch onto master.

This feature includes:
- Binding fetching on channel switch
- Handle binding refresh on websocket event
- Bindings
  - Channel Header
  - Post option
  - Commands
  - Embedded bindings (in post)
- Calls
- Call response handling
  - OK
  - Error
  - Navigate To
  - Form
- Modal Forms
- Feature flag code guard (no code is executed if the feature flag is disabled)
- Invalid binding filtering

### CODE REVIEW

**Review by lieut-data — CHANGES_REQUESTED** [review]
@larkox / @catalintomai, can we work to break this long running feature branch into a series of smaller commits, clearly breaking apart distinct efforts around refactoring from the new functionality?

**Comment by catalintomai** [comment]
> @larkox / @catalintomai, can we work to break this long running feature branch into a series of smaller commits, clearly breaking apart distinct efforts around refactoring from the new functionality?

@lieut-data , we can definitely try to do that - do you see the QA effort splitting as well for the individual pieces? We'd like for QA to be able to test user scenarios, and doing QA on individual pieces (refactoring vs. additive code) might not work that well.

**Comment by lieut-data** [comment]
Thanks, @catalintomai! There will definitely be unavoidable QA effort on account of the multiple PRs. My hope, though, is that by breaking things up, it will allow for additional, focused testing on the refactored areas in addition to the key feature changes being made. Ultimately, I defer to the QA Guild's judgment though!

**Comment by catalintomai** [comment]
cc: @DHaussermann for the QA take on the issue.

**Comment by DHaussermann** [comment]
Yes, as mentioned above, It would take more time to test because we would want another round of testing once all PRs have been merged. The other more difficult concern here would be with how testable the individual PRs become depending on how they are devided.

**Comment by larkox** [comment]
Closing in preference of https://github.com/mattermost/mattermost-webapp/pull/7773#pullrequestreview-628985779

**Pull request closed without merging**
