### PR TITLE
Admin console search

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Adding Admin console full text search for the configuration options

#### Ticket Link
[MM-14465](https://mattermost.atlassian.net/browse/MM-14465)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jespino** [comment]
@wiersgallak Yes, this happens when the page itself needs loading, that is because we are using a javascript library, I going to take a look into it to make in a more "react" way.

**Comment by wiersgallak** [comment]
@jespino Mike has done a UI mock up for this search feature:  https://projects.invisionapp.com/share/P5QTQ16SRWM#/screens/352078422.  Only thing to note is that I asked him to capitalize "System Console" in the default search bar (with no text)

**Comment by jespino** [comment]
@wiersgallak Fixed the problem with the highlight and added the proposed changes from @michaelgamble 

I created another spinmint to test it.

Another thing, the text "Find in System Consoles" is long enough to generate problems in other languages, maybe we can change it to "Find settings", "Search" or something like that, the System console part is clear enough in the context, and will be even clearer after the first usage.

**Comment by wiersgallak** [comment]
@jespino Mike was good with "Find settings"

**Comment by jespino** [comment]
@wiersgallak 1. I'll fix it, 2. Not related bug, but will be fixed in the next rebase. 3. I'll change the text.

**Comment by jespino** [comment]
@wiersgallak fixes done, you should be able to see them in the spinmint

**Comment by jespino** [comment]
@michaelgamble some of them wasn't wrong in my firefox, I tested it with chrome, and now I think everything is fixed :)

**Comment by michaelgamble** [comment]
A few minor changes:
- input field is still at 5px when it should be 8px
- icon alignment needs to have its top alignment 1px less
- search icon should be left: 18px (which visually lands on 12px)
- padding for the input field should be 5px 36px
- close button icon should be right: 10px (which visually lands on 12px)
- input field should have a white bg @ 5% opacity

**Comment by jespino** [comment]
@michaelgamble Done all your proposed changes :)

**Pull request merged**
