### PR TITLE
MM-39061 - change purchase modal lhs text and link

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
This PR changes the LHS bottom links in the purchase modal as requested in the ticket.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39061

#### Screenshots
Captura de pantalla 2021-10-05 a las 15 47 54

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AGMETEOR — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
The new wording and link is there as expected so I'm approving the PR.

That said, the link is a dead end but I'm guessing thats a known issue at this point?
https://mattermost.com/deploy/

**Review by marianunez — APPROVED** [review]

**Review by marianunez — APPROVED** [review]
Thanks for putting this change up so quick 👍

**Review by neallred — APPROVED** [review]
lgtm! :shipit:

**Pull request merged**
