### PR TITLE
PLT-8332: Fix teambar styling on load

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
 Add channel-view class on root in the constuctor of logged_in component.

#### Ticket Link
[PLT-8332](https://mattermost.atlassian.net/browse/PLT-8332)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
@sudheerDev What is the effect the end user will see?

**Comment by sudheerDev** [comment]
@jasonblais if user is part of multiple teams he should not see this flicker of unstyled teambar.

**Comment by saturninoabril** [comment]
@jasonblais I had this line modified last time in this [PR PLT-8222](https://github.com/mattermost/mattermost-webapp/pull/409/files) and I didn't realize a side-effect on multi-teams setup.
He just reverted that line of code (without using JQuery).

**Comment by jasonblais** [comment]
Thanks! I missed the ticket link, sounds good

**Comment by saturninoabril** [comment]
@jasonblais Should this be submitted for release-4.5 branch?

**Comment by jasonblais** [comment]
@sudheerDev Can you help submit this PR against the 4.5 branch?

**Comment by sudheerDev** [comment]
@jasonblais Done

**Comment by sudheerDev** [comment]
@saturninoabril rebased

**Comment by jwilander** [comment]
Could you give this a rebase? We just updated the build job and it needs the latest Jenkinsfile

**Comment by sudheerDev** [comment]
@jwilander @crspeller Done

**Pull request merged**
