### PR TITLE
[MM-45261] Fixing channel name wrap for top threads

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Adding ellipsis for channel name when it is too long

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45261

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@furqanmlk can you enable the feature flag on the test server for this PR?

**Comment by furqanmlk** [comment]
> @furqanmlk can you enable the feature flag on the test server for this PR?

@matthewbirtch Done ✅

**Review by matthewbirtch — APPROVED** [review]
Nicely done! Looks fixed to me
image

**Review by plant99 — APPROVED** [review]
LGTM.

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — COMMENTED** [review]
@BenCookie95  I found two more issues, 

1. Longer channel name in the modal does not have Ellipsis 

image

2. In **My top thread** and **top thread modal**, Longer user name is pushing the Channel badge

image

**Comment by BenCookie95** [comment]
> @BenCookie95 I found two more issues,
> 
> 1. Longer channel name in the modal does not have Ellipsis
> 
> image
> 
> 2. In **My top thread** and **top thread modal**, Longer user name is pushing the Channel badge
> 
> image

Thanks @furqanmlk, those are fixed now

**Pull request merged**
