### PR TITLE
Added telemetry events for plugin marketplace

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Added diagnostic tracking events for the following actions:

- Opening the plugin marketplace
- Closing the plugin makerplace
- Installing a plugin from the marketplace
- Clicking on `Configure` in the marketplace

#### Ticket Link
[MM-18103](https://mattermost.atlassian.net/browse/MM-18103)

#### Related Pull Requests

- Redux PR: https://github.com/mattermost/mattermost-redux/pull/922
- [Webapp feature branch](https://github.com/mattermost/mattermost-webapp/tree/mm-17023-integrations-marketplace)
- [Server feature branch](https://github.com/mattermost/mattermost-server/tree/mm-17023-integrations-marketplace)

### CODE REVIEW

**Comment by marianunez** [comment]
Adding @grundleborg for platforms perspective 👀

**Comment by marianunez** [comment]
@grundleborg What is the recommended way for development to validate the events are tracking properly?

**Comment by lindalumitchell** [comment]
QA not needed on this PR; removing QA Review label.

**Comment by jasonblais** [comment]
@marianunez Here's the whitelist George is referring to https://github.com/grundleborg/mattermost-redux/blob/master/src/client/client4.js#L2907

**Comment by marianunez** [comment]
Thanks @grundleborg and @jasonblais! I've included the events in the whitelist in this PR: https://github.com/mattermost/mattermost-redux/pull/922

**Pull request merged**
