### PR TITLE
[MM-50430] Fix Forgot Password link when email login is enabled

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
The wrong variable was used for the login page.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50430

#### Related Pull Requests
N/A

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by coltoneshaw — APPROVED** [review]
LGTM - I'm upset it was only a single line or I would have added a PR! Thank you though!

**Review by BenCookie95 — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected with the following steps:
1. Open one browser with your SysAdmin and another browser just refreshing the login page
2.  As SysAdmin, Set up a sign-in method (Gitlab or etc)
3. Go to System Console > Auth > Email
4. `Enable account creation with email` set to `false`
5. `Enable sign-in with email` set to `false`
6. `Enable sign-in with username` set to `true`
7. Go to Login page and refresh
Result: `Forgot Password` is getting shown
8. `Enable sign-in with email` set to `true`
9. `Enable sign-in with username` set to `false`
Result: `Forgot Password` is getting shown
10. `Enable sign-in with email` set to `true`
11. `Enable sign-in with username` set to `true`
Result: `Forgot Password` is getting shown
12. `Enable sign-in with email` set to `false`
13. `Enable sign-in with username` set to `false`
Result: `Forgot Password` is not getting shown

**Pull request merged**
