### PR TITLE
[MM-22840/GH-14198] DMs (More dialog): show recent 20 with relative timestamp

### PR DESCRIPTION
**Pull request by calebroseland**
(This continues off of #5855, thanks for getting this to ~90% @pradeepmurugesan!)

- **[MM-22840](https://mattermost.atlassian.net/browse/MM-22840)**, fixes mattermost/mattermost-server/issues/14198:
  - If there are recent DMs/GMs, show up to 20.
  - If searching: show normal results (ordered by: recent DMs/GMs, Users, GMs). 
  - If not searching and no recent DMs/GMs: show normal list of Users.
  - Recent DMs/GMs: 
    - prioritize in results and 
    - display relative timestamp if available (as 'now', minutes, hours, months, or years ago).
- DMs More, debounce search: currently every keystroke will update the search term, this results in many API requests. Now, the search term gets updated 250ms after last keystroke, significantly reducing API requests and local filter/logic thrashing.
- **`<Multiselect/>`**: 
  - Use `onMouseEnter` instead of `onMouseMove` to reduce number of `select` invocations while dragging mouse around the dialog.
- Formally add `lodash` to dependencies—currently being used and finding its way to runtime through its @types devDependency. 
- Add `babel-plugin-lodash` to reduce bundle size.

Side notes:
- Notes-to-self will cause "(you)" to show in recents.
- If _all_ members of a GM are already added, the option will be removed, as re-adding would do nothing.
- GMs had a subtle bug that did not show the add/plus icon, and selection className was off.
- "(You)" will be excluded from recents/results if users have been selected/added.

#### Screenshots

Screen Shot 2020-10-25 at 18 23 18

Screen Shot 2020-10-27 at 04 09 50

### CODE REVIEW

**Comment by calebroseland** [comment]
(For tomorrow morning) @esethna / @michaelgamble: I have a couple of UX questions on this:
- If rDMs are present (even just one), the alphabetized list of users is no longer accessible.
  - this would force/require searching to find users I have not yet DM'ed
    (most probably do this already, but it effectively blocks the 'user directory' UX).
- I presume rGMs should also get a relative timestamp? (Coded as such, but not sure according to spec.)
- Should rGMs be included along with rDMs on first-open (group of 20)?

**Comment by esethna** [comment]
@calebroseland 

1) Yes that's intended. The DM list is not really intended to be a user directory. Users can always access the "view members" list from the main menu to see a user directory. 
2) Yes GMs and DMs should be treated the same here. ie get a relative timestamp and appear in the list of 20 (if applicable)

**Comment by calebroseland** [comment]
@esethna Sounds good, thanks. I'll circle back re: #2.

**Review by agarciamontoro — APPROVED** [review]
Looks good to me! :tada:

**Review by nevyangelova — APPROVED** [review]
Thanks Caleb!

**Comment by ogi-m** [comment]
@calebroseland Should there be some more space left between the GM participants text and the relative timestamp?

Screenshot (117)

**Comment by calebroseland** [comment]
> @calebroseland Should there be some more space left between the GM participants text and the relative timestamp?
> 
> Screenshot (117)

@ogi-m I agree there should, it also appears that the text overflow ellipsis isn't working on GMs (whereas it is on DMs)—I'll quick-patch that, too, while I'm back in there.

**Comment by stylianosrigas** [comment]
Removing cloud server for maintenance purposes. Please feel free to apply the label again if you need it.

**Comment by calebroseland** [comment]
@ogi-m should be good to go, let me know if you see anything else. 

CleanShot 2020-12-07 at 15 50 04@2x


Changes: 
  - Ellipsis/padding for GM suggestions
  - Fixed normal users showing as bots (🙈 can't believe I missed that one!)

**Review by ogi-m — APPROVED** [review]
LGTM, not seeing any more issues 👍

**Comment by esethna** [comment]
@calebroseland curious on the state of this PR and if it's ready to go in aside from fixing conflicts? I'm not sure what blocked it from being merged based on the conversation history, seems reviews were completed.

**Pull request merged**
