### PR TITLE
Use inline images for gif picker

### PR DESCRIPTION
**Pull request by bbodenmiller**
#### Summary
Move to use inline images for gif picker. Inserting the raw link is ugly and not user friendly.

Needs further testing from someone else.

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for the PR @bbodenmiller :+1: Could you please fix the two linter issue:
```
/root/mattermost-webapp/components/create_comment/create_comment.jsx
 
  444:39  error  Missing whitespace after semicolon  semi-spacing
 
  444:40  error  Unnecessary semicolon               no-extra-semi
 ```

**Comment by bbodenmiller** [comment]
Maybe fixed now? @hanzei can you respin the sever?

**Comment by bbodenmiller** [comment]
@hanzei server spin up didn't work?

**Comment by esethna** [comment]
@bbodenmiller thanks for the PR! Is there a ticket open for this?

My concern with this approach is that the GIFs cannot be collapsed if they are added as in-line markdown images. 

cc// @andrewbrown00

**Comment by bbodenmiller** [comment]
> Is there a ticket open for this?

No. I created a PR to try and address an issue I saw.

> My concern with this approach is that the GIFs cannot be collapsed if they are added as in-line markdown images.

That sounds like an entirely separate issue that should be addressed independently. It's an issue for plugins too e.g. https://github.com/moussetc/mattermost-plugin-giphy/issues/12. In my experience most people are already changing these in the inline image links and this just simplifies the process.

**Comment by esethna** [comment]
Thanks @bbodenmiller 

> That sounds like an entirely separate issue that should be addressed independently. 

I'd be concerned though that this is removing a feature of collapsing GIFs that currently exists. I commented on the thread you mentioned to try and understand the problem: https://github.com/moussetc/mattermost-plugin-giphy/issues/12#issuecomment-620179601

**Comment by esethna** [comment]
@bbodenmiller are you good with closing this as per: https://github.com/moussetc/mattermost-plugin-giphy/issues/12#issuecomment-621387037

**Comment by bbodenmiller** [comment]
@esethna is there any usage analytics data on how often the collapse feature is actually used?

**Comment by esethna** [comment]
@bbodenmiller unfortunately not but given the user feedback in the thread linked I’d be hesitant to make this change until we can offer a collapse for inline images.

**Comment by andrewbrown00** [comment]
Sorry I'm late to replying @bbodenmiller and I agree with @esethna

> I'd be concerned though that this is removing a feature of collapsing GIFs that currently exist

and I agree with you we should better understand the data around how often the collapse feature is used and not having the data supports my decision to not remove the feature at this time.

> is there any usage analytics data on how often the collapse feature is actually used?

**Comment by bbodenmiller** [comment]
@esethna @andrewbrown00 in light of the above how can we move along the ability to collapse inline images? As the gif picker doesn't work at all in my instance because link previews don't work on our instance.

**Comment by esethna** [comment]
Hi @bbodenmiller, I've already queued up the ticket for our design team to investigate. 

Can you explain more about why link previews don't work for your instance?

**Comment by teresa-novoa** [comment]
@esethna where are we with this PR? Thanks!

**Comment by esethna** [comment]
@teresa-novoa as discussed above, I'd propose closing this PR until we can sort out the expected UX for collapsing in-line images (queued with the UX team): https://mattermost.atlassian.net/browse/MM-12290

@bbodenmiller are you good with closing this until we complete the design ticket? ^

**Comment by bbodenmiller** [comment]
> Can you explain more about why link previews don't work for your instance?

@esethna because the Mattermost server does not have internet access and the link previews require internet access. In line images do not require internet access as they are loaded client side.

**Pull request closed without merging**
