### PR TITLE
Making search result type selector independent from the search result filter in the search box

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Making search result type selector independent from the search result filter in the search box

#### Ticket Link
[MM-34834](https://mattermost.atlassian.net/browse/MM-34834)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — COMMENTED** [review]
Should we also update the `onChange` on `MessageOrFileSelector` to call both the local function and the prop `setSearchType`?
It's not clear to me if there is a valid case for that though.

**Comment by jespino** [comment]
The point is to have a local state set on new searches (when terms changes) but keep it local later on, for that reason we only use the local one on change, and not the global one.

**Review by calebroseland — APPROVED** [review]
LGTM!

**Review by koox00 — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
LGTM

**Pull request merged**
