### PR TITLE
MM-20345: Adding changes for cleanup not longer visible users to the websockets event handlers

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Adding changes for cleanup not longer visible users to the websockets event
handlers. This change was made by @reflog at the mattermost-redux repo, but it
needs some changes in our webapp websockets handlers (which are a different
implementation).

#### Ticket Link
[MM-20345](https://mattermost.atlassian.net/browse/MM-20345)

#### Related Pull Requests
- Has server changes (mattermost/mattermost-server#13640)
- Has mattermost-redux changes (mattermost/mattermost-redux#1072)

### CODE REVIEW

**Comment by jespino** [comment]
@ogi-m Fixed!. The problem was, I was fixing the scenario where you remove the user from the channel, not from the team, and that was working, and I think you are removing the user from the team, and that wasn't working. Thanks!

**Comment by stylianosrigas** [comment]
@jespino Let me know if you face any other issues with the test server.

**Comment by ogi-m** [comment]
@jespino I still see the issue when removing the guest from a channel. I'll send you a video.

**Comment by jespino** [comment]
@ogi-m this is waiting for get tested.

**Comment by ogi-m** [comment]
I'm still seeing the issue. We can take a look at this together later today @jespino

**Comment by amyblais** [comment]
Pushing this from v5.21 since this missed code complete and is not a regression.

**Pull request merged**
