### PR TITLE
Mm 38941 tutorial tip punchouts

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Implements the punchout portion of tour point autotour a/b test. See https://github.com/mattermost/mattermost-webapp/pull/9150#issuecomment-946205286 for more discussion.

One call out. For a couple of the tips, the "glowing" portion of the dot lies slightly outide the punchout and we aren't easily able to make the glow lay on top of the shadow. It's not glaringly noticeable on any of the tips, but if we feel strongly, we can come back in a further effort and try to place the dots above the shadow but below the tip. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38941
https://mattermost.atlassian.net/browse/MM-39316

#### Screenshots
punch outs:

punch-out-tip-1

punch-out-tip-2

punch-out-tip-3

punch-out-tip-4

punch-out-tip-5

punch-out-tip-6

#### Release Note
No release note as this finishing out a feature that is not yet released.
```release-note
NONE
```

### CODE REVIEW

**Comment by esethna** [comment]
@annelieseklein should we have the "Try Playbooks and Boards" tip pointing upwards (similar to the next tip - "Customize your experience") so it doesn't overlap the "Channels" product name in the global header?  

image

For example:
image

**Comment by esethna** [comment]
@neallred looks good other than these two points above ^

**Comment by esethna** [comment]
@amyblais FYI this should be for the next cloud release (Oct 27)

**Comment by neallred** [comment]
@esethna @annelieseklein updated with the bigger punchout for the post and placing the product menu tip below the menu. What do you think?

**Pull request merged**
