### PR TITLE
[MM-20436] Migrate toggle_mute_channel to TypeScript

### PR DESCRIPTION
**Pull request by msal4**
#### Summary

This migrates the toggle_mute_channel component over to typescript.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16138
JIRA: https://mattermost.atlassian.net/browse/MM-20436

### CODE REVIEW

**Comment by hanzei** [comment]
@msal4 Could you please update the snapshot using `npm run test-ci -- -u`?

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @msal4!

**Review by nevyangelova — APPROVED** [review]

**Comment by jfrerich** [comment]
@DHaussermann, ping for review.  @msal4, QA has been pretty busy lately, but will review your PR soon! Thanks for the contribution!

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Ensured mute toggle is functional 
- No functional issues found or console errors
- Tested for all channel types
- Tested on browser and desktop

LGTM!
Thanks @msal4 for this enhancement. Sorry for the delay testing this. 

No new release tests needed to cover this.

**Comment by devinbinnie** [comment]
Hey @msal4, looks like a few lint errors are still present. We made a couple eslint changes recently that probably caused these:
```
/root/mattermost/mattermost-webapp/components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx
  17:112  error  Expected a semicolon  @typescript-eslint/member-delimiter-style
  25:23   error  Expected a semicolon  @typescript-eslint/member-delimiter-style
  30:22   error  Expected a semicolon  @typescript-eslint/member-delimiter-style
  35:22   error  Expected a semicolon  @typescript-eslint/member-delimiter-style
  40:17   error  Expected a semicolon  @typescript-eslint/member-delimiter-style
  45:22   error  Expected a semicolon  @typescript-eslint/member-delimiter-style
```

Can you fix these up and then we can merge? Thanks for your help :)

**Comment by msal4** [comment]
@devinbinnie sorry, I don't get these errors for some reason.

**Comment by devinbinnie** [comment]
> @devinbinnie sorry, I don't get these errors for some reason.

@msal4 You'll need to pull your branch down from the server. We updated it since it was out of sync, but unfortunately some lint errors came up so we weren't able to merge.

**Comment by msal4** [comment]
@devinbinnie thanks

**Pull request merged**
