### PR TITLE
MM-15806 Removing bot account email from manage team member's dialog

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by amyblais** [comment]
@jfrerich Was this cherry-picked?

**Comment by jfrerich** [comment]
@amyblais The PR has the `CherryPick/Approved` tag, but I did not do anything special aside from squash and merge.  Did I miss a step?

Another question. My understanding is that the 2nd approving reviewer does the merge.  Are they also tasked with finding the jira ticket and marking resolved, or is that up to the PR Author?

Thanks

**Comment by jfrerich** [comment]
Thanks @amyblais. 

@crspeller what is the flow for merging to master and also cherrypicking to v5.12?

**Comment by jfrerich** [comment]
Thanks @amyblais for the request to add documentation and thanks @mgdelacroix for reaching out through MM with cherry picking instructions.  I'll change the `CherryPick/Approve` tag once complete.

**Pull request merged**
