### PR TITLE
translations PR 20180604

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by kaakaa** [comment]
`ja` LGTM

**Comment by jwilander** [comment]
@enahum I think the base needs to be `release-5.0` if we need this for the release

**Comment by cpanato** [comment]
waiting a new pr to the release branch

**Comment by cpanato** [comment]
@enahum can you rebase using the release branch and move the PR to use the release branch? thanks!

**Comment by enahum** [comment]
@cpanato done

**Pull request merged**
