### PR TITLE
Making minor modifications to the css around input fields and chips

### PR DESCRIPTION
**Pull request by michaelgamble**
This pull-request is jesus showing me the process of submitting a pull request as a draft to understand the process

### CODE REVIEW

**Comment by michaelgamble** [comment]
@jespino need your help to finish fixing the last two items for this issue.
- For the space between the chip and the text, I left a note in the css for the line that the selector doesn’t seem to be working properly, I’m not sure what im doing wrong
- for the nickname font opacity, i think this requires modifying the jsx to create a selector

**Comment by michaelgamble** [comment]
TODO: A reminder to myself: once i have the enterprise repo / licensing up and running I need to apply all the same changes to the channel input field.

**Comment by michaelgamble** [comment]
> TODO: A reminder to myself: once i have the enterprise repo / licensing up and running I need to apply all the same changes to the channel input field.

This has been completed

**Comment by srkgupta** [comment]
Since this PR is just for testing purpose, tests are not required for it. Removing the QA Review Label and adding the Tests Not Required label.

**Comment by michaelgamble** [comment]
@srkgupta the beginning of this was just for testing purpose, but the code changes and execution were real world and require QA testing... ill remove my original (first comment) to eliminate any confusion.

**Comment by srkgupta** [comment]
Thanks for letting me know @michaelgamble. Can you please link the JIRA ticket to this PR so that we know what exactly needs to be tested. Looking at the css changes, it's not clear which screens are affected and what needs to be tested

**Comment by michaelgamble** [comment]
@srkgupta https://mattermost.atlassian.net/browse/MM-17329

**Comment by srkgupta** [comment]
Never mind, please ignore. I got the JIRA ticket from the name of your branch. We generally add this as part of the PR Overview itself, so that it's clear for all the stakeholders. 

Here is the link to the original ticket which this PR addresses:
https://mattermost.atlassian.net/browse/MM-17329

**Comment by michaelgamble** [comment]
@srkgupta I updated the first commit comment with the appropriate info aswell

**Comment by srkgupta** [comment]
The changes are part of the 5.16 release Guest Accounts feature and will be tested accordingly. Removing the QA Review label for now.

**Pull request merged**
