### PR TITLE
Add GitHub OAuth Support

### PR DESCRIPTION
**Pull request by svelle**
#### Summary
Adds support for GitHub OAuth account creation and login to mattermost

#### Ticket Link
related to this customer request: https://mattermost.atlassian.net/projects/CR/issues/CR-418?filter=allopenissues&orderby=priority%20DESC&keyword=github

#### Related Pull Requests
- Has server changes https://github.com/mattermost/mattermost-server/pull/12073

My first real webapp PR so please be gentle, because I'm fairly certain I missed a ton of stuff :D

### CODE REVIEW

**Comment by lindalumitchell** [comment]
Nice! Is there a corresponding JIRA feature story for this one (and is it scheduled for a particular release)? Can tests be added here as well?

**Comment by mkraft** [comment]
@svelle Sorry for the delay... I *just* realized my review was sitting in "pending" state so the comments hadn't been submitted.

**Comment by sudheerDev** [comment]
@svelle I thought this PR was not ready. Should devs go ahead with the review or you see any changes from `PM review`?

**Comment by svelle** [comment]
Sounds good to me.

**Pull request closed without merging**
