### PR TITLE
fixed coloring in EmojiPicker button for edit_post component

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
fixes miscolored emoji picker in edit_post component

#### Ticket Link
n/a

#### Related Pull Requests
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge 
- Verified emoji coloring in edit post textbox - as expected 
- [E2e report ](https://mattermost-cypress-report.s3.amazonaws.com/194946-4e69071-onprem-ent-webapp-pr-10312-mm-ee-test:4e69071/mochawesome.html)

**Review by jgilliam17 — APPROVED** [review]

**Comment by jgilliam17** [comment]
I am not sure what `blocker Expected — Waiting for status to be reported` means. Not able to merge.

**Comment by michelengelen** [comment]
@jgilliam17 the blocker is not resolving on the PRs lately. Might be something the devops team needs to have a look into

**Pull request merged**
