### PR TITLE
Fix mattermost/mattermost-server#10689

### PR DESCRIPTION
**Pull request by kkirsche**
Fix mattermost/mattermost-server#10689
Fix MH-15309

#### Summary
Adds additional validation to the `hasSettings` variable to ensure that invalid plugin settings do not cause the system console to fail to load

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/10689
https://mattermost.atlassian.net/browse/MM-15309

#### Related Pull Requests
N/A

### CODE REVIEW

**Comment by kkirsche** [comment]
CLA completed

**Comment by jasonblais** [comment]
Thank you @kkirsche!! Queuing for dev review.

@hanzei Let me know if any PM review or testing needed.
@bradjcoughlin I assigned you as a second reviewer, since you've been doing a lot of work around the System Console. Feel free to re-assign to EXT though if you're not familiar with this code base.

**Comment by hanzei** [comment]
@jasonblais I've tested with the provided and it works fine. I don't see the need for further testing.

But I don't feel knowable enough to review this. I'm requesting someone else's review.

**Comment by kkirsche** [comment]
Wanted to follow up on this to see what else is needed

**Comment by hanzei** [comment]
Thanks for the reminder @kkirsche. Would you please merge `master` into your branch?

**Comment by hanzei** [comment]
@bradjcoughlin @jfrerich Gently reminder about this PR.

**Comment by kkirsche** [comment]
@hanzei I can do that if you really want, but it seems both a rebase and a merge would add a merge commit, which seems a bit wasteful for something which if merged here would just fast-forward, as there are no conflicts.

If you can share how to do a rebase or merge which will not generate that commit (`--no-commit` just pauses after the merge but before committing) I can give it a shot

**Comment by hanzei** [comment]
@kkirsche What is the downside of having a merge commit in this branch? We will squash the commits anyway when merging.

**Comment by kkirsche** [comment]
Right, if just squashing at that point, it seems like that just muddies up the log commit messages, since it forces the merge commit message into the fix commit. Not the end of the world, just goes against what I've learned working on other open-source projects. 

Pushed a merged version for you. Merged via

```
git remote add upstream https://github.com/mattermost/mattermost-webapp.git
git fetch upstream master
git merge upstream/master
```

**Comment by hanzei** [comment]
Thank you very much @kkirsche for this contribution! :tada:

**Comment by kkirsche** [comment]
My pleasure :)

**Pull request merged**
