### PR TITLE
Add style linter

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Add style linter to webapp repo.

The linter added is https://stylelint.io/ (first found after a quick google search).

All rules are enabled but two:
- "no-descending-specificity" : Too many errors and time consuming to solve (require reordering the elements on the files, and probably someone with more css savvy could make sure the behaviour does not change)
- "font-family-no-missing-generic-family-keyword": This just needs to add the generic font family, but was not sure for each case which would be the correct one, so I will leave that also for someone with more css savvy.

#### Ticket Link
None

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
This sounds like a good inclusion. I'm not sure if UI Platform has their own plans around this, but I'm sure Nevy would know.

The only question I have is if this fits in with Prettier. We'd discussed potentially moving to using Prettier elsewhere, and as far as I know, it does have CSS support, so maybe it would make sense to turn that on for CSS in the mean time to see how it looks? That said, Web Platform isn't planning on doing that any time soon, so we could always use this for now and maybe switch in the future if that ends up being necessary.

**Review by nevyangelova — APPROVED** [review]
Thanks for handling this

**Comment by nevyangelova** [comment]
> This sounds like a good inclusion. I'm not sure if UI Platform has their own plans around this, but I'm sure Nevy would know.
> 
> The only question I have is if this fits in with Prettier. We'd discussed potentially moving to using Prettier elsewhere, and as far as I know, it does have CSS support, so maybe it would make sense to turn that on for CSS in the mean time to see how it looks? That said, Web Platform isn't planning on doing that any time soon, so we could always use this for now and maybe switch in the future if that ends up being necessary.

We actually haven't included those rules in our linter but the way we use styled components doesn't let us mess up the specificity. I can discuss the second rule with my team .

**Comment by larkox** [comment]
@nevyangelova heads up that I moved the commands from the makefile to the package.json file, in case you think it needs a re-review.

**Comment by larkox** [comment]
@nevyangelova for styled components, this linter has a special set of rules that may be interesting. I have not looked deep into it, but maybe you can figure out something interesting to add in the future :smile: 
https://github.com/kristerkari/stylelint-react-native

**Comment by nevyangelova** [comment]
Thanks @larkox we are in the process of figuring out rules and best practices I will let you know :)

**Comment by jgilliam17** [comment]
@larkox Can you please add test steps? Not sure I understand what needs to be tested. Thanks.

**Comment by larkox** [comment]
@jgilliam17 This is just a refactor, but touch the styles all around, so the idea would be a general test to make sure everything looks like it is supposed to. It is hard to pinpoint any area in specific. Sorry about that :(

**Comment by jgilliam17** [comment]
Thanks @larkox 
Noticed few issues while manually smoke testing and checking [Cypress errors](https://automation-dashboard.vercel.app/cycles/fb91c995-ccdc-49f6-ac79-f770affd2fc3)
The fix for some maybe the same, I'm listing all for my benefit so I know which screens to retest. 
1. emoji picker borders are not correctly styled 
Screen Shot 2021-06-25 at 3 22 50 PM
2. System Console>User Management>Channels 
Screen Shot 2021-06-25 at 4 37 40 PM
3. System Console>User Management>Teams
Screen Shot 2021-06-25 at 4 39 18 PM
4. System Console>User Management>System Roles
Screen Shot 2021-06-25 at 4 40 19 PM
5. System Console>Compliance>Data Retention Policy < This screen looks completely off when compared to master.test. I am not sure when it was updated with the new look 
Screen Shot 2021-06-25 at 4 41 53 PM
6. Additionally one step forward similar can be seen on  Add policy > Custom retention policy screen
Screen Shot 2021-06-25 at 5 08 30 PM
7. Not sure if this is related to changes here. There are also some server errors when trying to save settings, incident playbooks etc. this does not repro on master.
Error is sometimes missing when saving and displays `insert error`
Screen Shot 2021-06-25 at 4 56 15 PM
Screen Shot 2021-06-25 at 5 24 50 PM
Screen Shot 2021-06-25 at 5 37 06 PM

**Comment by larkox** [comment]
@jgilliam17 The borders and the tables should be fixed.
The changes in compliance are due to a feature flag. It seems there is a new feature that they are working on. The theme related things (like the text that is barely visible) is something outside of the scope of this PR.
The error, I have not being able to reproduce on my side, but should not be related.

**Review by jgilliam17 — APPROVED** [review]
Thanks @larkox 
Tested, looks good to merge.
- Verified styles in the app, issues found by Cypress and manual test have been resolved - borders and system console tables are displaying as expected.  
Follow up issue created for team theme in System Console https://mattermost.atlassian.net/browse/MM-36710

**Pull request merged**
