### PR TITLE
[GH-16035] Migrating refs plugin_management.tsx

### PR DESCRIPTION
**Pull request by Ampit**
#### Summary

This is part of the migration refs campaign

it migrates refs(fileInput) in plugin_management.tsx

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/16035
Jira ticket: https://mattermost.atlassian.net/browse/MM-29852

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for the contribution @Ampit :tada: 

Heads up that the type check failed with:
```

components/admin_console/plugin_management/plugin_management.tsx:463:14 - error TS2339: Property 'fileInput' does not exist on type 'PluginManagement'.

463         this.fileInput = React.createRef();
                 ~~~~~~~~~

components/admin_console/plugin_management/plugin_management.tsx:506:30 - error TS2339: Property 'fileInput' does not exist on type 'PluginManagement'.

506         const element = this.fileInput.current as HTMLInputElement;
                                 ~~~~~~~~~

components/admin_console/plugin_management/plugin_management.tsx:559:30 - error TS2339: Property 'fileInput' does not exist on type 'PluginManagement'.

559         const element = this.fileInput.current as HTMLInputElement;
                                 ~~~~~~~~~


Found 3 errors.
```

Let me know if you need help with resolving that.

**Comment by Ampit** [comment]
@hanzei 

Could you please guide me with that

**Comment by hanzei** [comment]
@Ampit You need to declare private Prop `fileInput` that `React.createRef()` is then assigned to. Something like https://github.com/mattermost/mattermost-webapp/blob/7809ea0848779008bf4b3f0f358e2de868bbb371/components/color_input.tsx#L21

**Comment by hanzei** [comment]
Heads up that there are some linter errors regarding white spaces and new lines. They should be straight forward to fix: https://app.circleci.com/pipelines/github/mattermost/mattermost-webapp/28061/workflows/8471a84a-24d3-453d-82ab-85f8def45f70/jobs/184685/parallel-runs/0/steps/0-103

**Comment by Ampit** [comment]
@hanzei 

Thank you for your help.

I think all checks are passing now..

 Please let me know if there is anything else i need to do.

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by Ampit** [comment]
@catalintomai Could i get a review please ?

**Review by catalintomai — APPROVED** [review]

**Review by prapti — APPROVED** [review]
Tested with cloud test server. The plugin management page works as expected, including the file upload function to manually upload plugin bundles.
Approving.

**Pull request merged**
