### PR TITLE
[MM-4712] Add progress  bar for uploads

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Add progress bar for uploads

#### Ticket Link
[MM-4712](https://mattermost.atlassian.net/browse/MM-4712)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
sep-18-2018 12-35-26

### CODE REVIEW

**Comment by sudheerDev** [comment]
@eric 
2. Added uploading text
screen shot 2018-09-20 at 11 49 09 pm

3. Fixed scroll issue

1 I am working on it but it is more complicated than it looks

**Comment by esethna** [comment]
Chatted with ST, #1 above is very tricky to accomplish and is a minor corner case so we are putting it on hold so we can get this PR in

**Comment by esethna** [comment]
@cpanato having trouble with this test server if you can take a look when you get a chance? ^

**Comment by esethna** [comment]
Also, adding @asaadmahmood to help with a UI review and make any styling tweaks necessary

**Comment by cpanato** [comment]
@esethna looks like the test server is up and running, no actions from my side.

**Comment by sudheerDev** [comment]
@esethna Yes, it stalls there because we added a check intentionally.  

https://github.com/mattermost/mattermost-server/pull/4271

>Once the uploading reaches 100%, it "hangs" there for 1-2 seconds making it look like the uploading freezes for a moment. This is because after the upload is completed, it grabs the file from the server (always being that way, not caused by your PR).
One improvement we've been thinking about is stopping the counter at 98%, then have it jump to 100% right before the upload is finished and the file type (or image thumbnail) appears.

Let me know if you want me to remove that

**Comment by esethna** [comment]
Thanks Sudheer, let's add the completed animation and revisit the above as it sounds like it might solve the issue ^

**Comment by esethna** [comment]
@asaadmahmood can you please take another CSS pass on this tomorrow morning? 

 Progress % text feels too small and thick. Also the progress circle feels a bit thick. 

image

Check mark feels too large and thick, and needs animation in/out effects.

image

**Comment by sudheerDev** [comment]
@esethna Last commit missed styles. I updated them so, this might solve couple of styling issues

sep-27-2018 00-08-51

**Comment by amyblais** [comment]
@sudheerDev Can you help merge this PR or will it go through more reviews?

/cc @cpanato

**Comment by cpanato** [comment]
merging....

**Comment by sudheerDev** [comment]
@amyblais They are just minor css changes after the review. It is safe to merge.

**Pull request merged**
