### PR TITLE
MM-38908: Handle /:team/_playbooks/:playbookId/run

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Navigating to `/:team/_playbooks/:playbookId/run` will switch to the last viewed channel in the team, defaulting to Town Square, and then will execute the `/playbook run-playbook` command, effectively rendering an interactive dialog to run the playbook.

This is needed to support the Run button in the Playbooks product, fixing a bug in the desktop where the app successfully changes the tab to Channels but still renders the interactive dialog in the Playbooks tab.

The video below shows the use-case: the user is in team `eligendi`, then goes to the Playbooks tab and opens a Playbook in team `minus`, when clicking on the Run button, the desktop app focuses the Channels tab, where the user is redirected to the last channel viewed in the playbook team (in this case `neque` in the team `minus`) and opens the interactive dialog. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38908

#### Related Pull Requests
- Playbooks PR: https://github.com/mattermost/mattermost-plugin-playbooks/pull/780

#### Screenshots
https://user-images.githubusercontent.com/3924815/135624556-f38d661e-e7a1-41a7-bea6-930e78227689.mp4

#### Release Note

```release-note

```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Brilliant!

**Comment by lieut-data** [comment]
Looping @devinbinnie for review from the Desktop's perspective.

**Comment by agarciamontoro** [comment]
Hm, I had also added @calebroseland as reviewer :thinking: Let's go with both, you never have too many reviews in a PR :)

**Review by devinbinnie — APPROVED** [review]
LGTM! Nice job guys!

**Review by calebroseland — APPROVED** [review]
I love the redirect solution! 

I'm not going to hold this up, but putting this in the `center_channel` flow doesn't quite feel right to me.

Perhaps `<PlaybookRunner/>` could be mounted in route handler/container that is provided by Playbooks via `PluginRegistry.registerCustomRoute` (listening for something like`/plug/playbooks/:playbookId/run`)

https://github.com/mattermost/mattermost-webapp/blob/master/components/root/root.jsx#L403-L414

**Comment by agarciamontoro** [comment]
> Perhaps `<PlaybookRunner/>` could mounted in route handler/container that is provided by Playbooks via `PluginRegistry.registerCustomRoute` (listening for something like`/plug/playbooks/:playbookId/run`)

Wouldn't this keep the bug as it is, with the interactive dialog spawning in the Playbooks tab? Maybe there is a better place to put it, but we need something *in* the Channels product, not in the URLs managed by the plugin.

**Comment by calebroseland** [comment]
> > Perhaps `<PlaybookRunner/>` could mounted in route handler/container that is provided by Playbooks via `PluginRegistry.registerCustomRoute` (listening for something like`/plug/playbooks/:playbookId/run`)
> 
> Wouldn't this keep the bug as it is, with the interactive dialog spawning in the Playbooks tab? Maybe there is a better place to put it, but we need something _in_ the Channels product, not in the URLs managed by the plugin.

5/5 You're right. Please disregard my comments above.

**Comment by agarciamontoro** [comment]
@amyblais, we need to get this into 6.0. Is there anything else I need to do apart from the cherry-pick?

**Comment by amyblais** [comment]
@agarciamontoro Just a cherry-pick to release-6.0.

**Comment by agarciamontoro** [comment]
Skipping QA, I reviewed the fix myself and this will be tested as part of Playbooks in our regular bug bash parties :)

**Pull request merged**
