### PR TITLE
MM-37951: follow thread on reply

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

ThreadUpdated event doesn't include `is_following` so when a thread is updated because current user posted a new post
we should set `is_following` to true. 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37951

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Tested, looks good to merge.
- Verified when replying on an explicitly unfollowed thread, the thread is Followed immediately and is not marked as unread for the current user.

**Pull request merged**
