### PR TITLE
[MM-14593] Add password type for Interactive Dialogs

### PR DESCRIPTION
**Pull request by goku321**
#### Summary

Add password type for Interactive Dialogs
#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/10460
#### Related Pull Requests

- Has mobile changes (https://github.com/mattermost/mattermost-mobile/pull/2998)

### CODE REVIEW

**Comment by hanzei** [comment]
@jasonblais / @aaronrothschild Should this PR get PM reviewed?

**Comment by aaronrothschild** [comment]
Since this is modifying only the contents of a field that is already positioned - this probably doesn't need a PM review, but a mention is appreciated.  

Lastly, https://docs.mattermost.com/developer/interactive-dialogs.html#elements should be updated (if it doesn't get auto-updated) with this new `type`.

**Comment by aaronrothschild** [comment]
Could I get a screenshot of the password field in use?

**Comment by lieut-data** [comment]
@goku321, are you able to share a screenshot as such? Or perhaps point @aaronrothschild at a test plugin we can use to verify?

**Comment by goku321** [comment]
@lieut-data Hi, Actually I wasn't aware that this question was for me :sweat_smile: My mistake, I should have confirmed. Let me take take a look and get back on this. Thanks for your patience

**Comment by lieut-data** [comment]
@goku321, not to worry! Thanks for being willing to help drive this functionality improvement :)

**Comment by lieut-data** [comment]
@prapti, wondering if this might be something for you to help test?

**Comment by lieut-data** [comment]
Actually, @goku321, sounds like @aaronrothschild is good with the changes as-is. No need to dredge up a screenshot, as this should be a fairly benign change :)

**Comment by goku321** [comment]
@lieut-data phewww, glad to hear that :sweat_smile: Thanks

**Comment by lieut-data** [comment]
@goku321, would you be open to helping us extend the https://github.com/mattermost/mattermost-plugin-demo to feature this functionality? There's already an interactive dialog there, so it's just a matter of adding a new field with your type.

**Comment by goku321** [comment]
@lieut-data Absolutely :+1:

**Comment by prapti** [comment]
@lieut-data @goku321 The changes worked on the browser and Mac desktop app as expected, but did not on Android and iOS mobile apps. The password field with password subtype revealed the input text on both. Please see the screenshots attached.

nopwsubtype-Android

nopwsubtype-iPhone

Tested on:
Web browser (Chrome 75.0.3770.142)
Android 9 - App Version 1.21.0 (Build 208)
iOS 12 - App Version 1.21.1 (Build 209)
Mac Desktop App

**Comment by goku321** [comment]
@prapti Thanks for the screenshot. I am working on the mobile app changes and will create a pull request soon

**Comment by goku321** [comment]
Hi @hanzei I have update this pull request and added the link to the pr which has mobile changes

**Comment by hanzei** [comment]
@prapti Given that there is a PR for the mobile changes: Is this ready to be mergedß

**Comment by prapti** [comment]
@hanzei I'd be more comfortable merging this one once the mobile changes get tested and approved with the other PR (2998).

**Comment by aaronrothschild** [comment]
Docs updated here:  https://github.com/mattermost/docs/pull/2897

**Comment by goku321** [comment]
> @goku321, would you be open to helping us extend the https://github.com/mattermost/mattermost-plugin-demo to feature this functionality? There's already an interactive dialog there, so it's just a matter of adding a new field with your type.

Hi @lieut-data Do I have to add an object inside `elements` array with a key `type` as `password` ?

**Comment by saturninoabril** [comment]
@goku321 No worries for demo plugin.  I added it while doing some test for Interactive dialog - https://github.com/mattermost/mattermost-plugin-demo/pull/65

**Pull request merged**
