### PR TITLE
MM-27530 Fix for Multiselect items not scrolling into view on arrow keys

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
   * The way it used to work is based on list item ref which is lost in recent refactors.
   * Passing in on an item ref if renderOption is overriding defaultOptionRenderer

Things to test:
Functionality is broken in multiple places and not just DM modal,  The other multiselect modals this PR fixes
Add groups to channel
Add groups to team
Add users to team 
Add user to channel
More DM channels modal
Select team to join

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27530

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thank you @sudheerDev 
I'm seeing few issues
1. Scrolling through Direct Messages - works through DMs, but stop at GMs on the list 
2. Unable to scroll using up/down keys on select team to join
3. More channels modal is not scrolling using arrow keys, instead it scrolls through text input suggestion list
Screen Shot 2020-09-07 at 4 05 27 PM

**Comment by sudheerDev** [comment]
> 1. Scrolling through Direct Messages - works through DMs, but stop at GMs on the list
WHich modal are we talking about here?

> 2. Unable to scroll using up/down keys on select team to join
Sorry about that, Change is in another modal for selection of team
Does a string  `This team is already selected in another team scheme, are you sure you want to move it to this team scheme` rings any bell? I am not sure where this is in the UI but i assume it is for something like groups or guests.

> 3. More channels modal is not scrolling using arrow keys, instead it scrolls through text input suggestion list
> Yes,  but it is not a regression with the PR. I can. confirm the behaviour on daily as well.

**Comment by jgilliam17** [comment]
@sudheerDev 
1. This is the modal that opens when you click on Direct Messages + icon on the LHS. 
 Steps:
Create 3+ group messages
Open Direct Messages modal by clicking on DM+ 
Use down arrow to scroll to the bottom of the list to see GMs
Observed: GMs are not being scrolled into view

2. I need to check this again. Thanks for additional info.

**Comment by jgilliam17** [comment]
@sudheerDev 
There are few white screens on sys console and row highlight missing when scrolling and mouse hover (see gif). 
1. System Console>User Management>Permissions>New Team Scheme
Click on Add Teams button 
2. System Console>User Management>Groups>Configure
Click on Add Team or Channel
Both multi-select lists cause the white screen
3. System Console>User Management>Teams 
Click on Edit by any team name
Click on Add Group - white screen
Click on Add Members - no white screen, but the slightly gray highlighting is missing while scrolling and on mouse hover
4.  System Console>User Management>Channels
Click on Edit  by any channel name
Click on Add Group - white screen
Click on Add Members - no white screen, but the slightly gray highlighting is missing while scrolling and on mouse hover
Sep-18-2020 11-51-26

**Review by Willyfrog — APPROVED** [review]

**Comment by amyblais** [comment]
@sudheerDev Kind reminder for this PR for v5.28.

**Review by jgilliam17 — APPROVED** [review]
Thank you @sudheerDev 
Tested, looks good to merge.
- Verified items are scrolling into view when using arrow keys.
Areas checked:
Direct messages modal
Add member to channel modal
System console: Add groups and/or members to channel, Add groups and/or members to team, Add team and/or channel to groups, Add users to team, Add user to channel

**Comment by sudheerDev** [comment]
@calebroseland @Willyfrog i had an issue with using this without arrow function hence the white screen. Made those changes  after approvals. I am gonna skip asking fro reviews again but feel free to let me know if you find any issue with the change

**Pull request merged**
