### PR TITLE
Cypress/E2E: Fix for importing Cypress support and plugin folders

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
The original idea and implementation of importing Cypress support and plugin folders as is came up from @mickmister - https://github.com/mattermost/mattermost-plugin-demo/pull/136.  Suggested usage is:
- At `/cypress/plugins/index.js`;
```
module.exports = require('mattermost-webapp/e2e/cypress/plugins');
```

- At `/cypress/support/index.js`;
```
import 'mattermost-webapp/e2e/cypress/support';
```

However, some change here in the webapp broke such ability to import. To fix the problem, first approach is to handle file processing to the consumer itself by using Cypress' [file preprocessor](https://docs.cypress.io/api/plugins/preprocessors-api.html#Usage) or [@cypress/webpack-preprocessor](https://www.npmjs.com/package/@cypress/webpack-preprocessor). However, for some reason, babel transformations on some preset seemed to be not working. Did several trials but to no avail.

The workaround made here is a quick fix so that the ongoing effort from @jfrerich and @mickmister on https://github.com/mattermost/mattermost-plugin-demo/pull/130 will be unblocked. Will revisit the approach in the future but for the meantime, this should work as expected per above usage.

#### Ticket Link
Jira ticket - https://mattermost.atlassian.net/browse/MM-31437

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. I spot tested a case that uses both client and uiInviteMemberToCurrentTeam and the test passed. As for integration to plugin-demo, I'll let Saturn test it once merged as he's the QA on that PR.

Screen Shot 2021-02-05 at 8 26 52 AM

**Review by catalintomai — APPROVED** [review]

**Comment by saturninoabril** [comment]
Hello @jfrerich, gentle reminder for your review.

**Review by jfrerich — APPROVED** [review]
LGTM

**Comment by jfrerich** [comment]
Sorry for the late review.  Approved :)

**Comment by saturninoabril** [comment]
No worries and thanks!

**Pull request merged**
