### PR TITLE
[MM-22498] Refactor channel header popover to match requirements

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
Refactored the popover for channel header info to match the desired behaviour linked in the Jira ticket

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22498

### CODE REVIEW

**Comment by esethna** [comment]
cc// @andrewbrown00  we may need to define the spacing and alignment here if you can help provide some direction:

image

**Comment by jgilliam17** [comment]
Thank you @nevyangelova 
Just adding few issues I noticed too.
- There is some word splitting at the end of the line, see image
Screen Shot 2020-02-20 at 12 22 49 PM

- Add a Mention in the popover e.g `@user-2` that is not part of the channel. Clicking on the mention opens profile popover and throws an error 
Screen Shot 2020-02-20 at 3 29 00 PM

The following may be out of scope of this PR and a feature request (question for @esethna)
- `hashtag` in the header popover does not start the search -  Wondering if we should add that functionality as hashtag in the popover appears to be clickable (cursor changes to hand), but it does nothing.

**Comment by nevyangelova** [comment]
> Thank you @nevyangelova
> Just adding few issues I noticed too.
> 
> * There is some word splitting at the end of the line, see image
> 
> Screen Shot 2020-02-20 at 12 22 49 PM
> 
> * Add a Mention in the popover e.g `@user-2` that is not part of the channel. Clicking on the mention opens profile popover and throws an error
> 
> Screen Shot 2020-02-20 at 3 29 00 PM
> 
> The following may be out of scope of this PR and a feature request (question for @esethna)
> 
> * `hashtag` in the header popover does not start the search -  Wondering if we should add that functionality as hashtag in the popover appears to be clickable (cursor changes to hand), but it does nothing.

I can fix the word break, the other things you mentioned I believe need to be discussed as the Jira ticket's scope was just about the visual behaviour of the popup. Waiting for advice

**Comment by esethna** [comment]
> cc// @andrewbrown00 we may need to define the spacing and alignment here if you can help provide some direction:

@nevyangelova regarding the comment above on spacing and alignment of elements, Andrew Brown and I discussed. Can we adjust the behaviour so that if the channel description is not multiple lines, can we not show the bounding box on hover? It seems the bounding box/popover is only needed if the description is over one line.

**Comment by esethna** [comment]
@jgilliam17 can you create a separate ticket for the hashtag and profile pop-over issues unless this is a regression in this PR?

**Comment by jgilliam17** [comment]
> @jgilliam17 can you create separate tickets for the hashtag and profile pop-over issues unless they are regressions in this PR?

They are not regressions. I'll create separate tickets.

**Comment by esethna** [comment]
New build doesn't seem to be working at all for multi-line descriptions ^

**Comment by nevyangelova** [comment]
@esethna  this is the behaviour I am observing in the test server. I felt like this is the expected behaviour. It seems that the Markdown component needs two new lines to start a new paragraph and format correctly. 

Screen Shot 2020-02-28 at 13 39 25
Screen Shot 2020-02-28 at 13 39 41

After adding extra new lines: 

Screen Shot 2020-02-28 at 13 40 05
Screen Shot 2020-02-28 at 13 39 57

**Comment by esethna** [comment]
@nevyangelova 

Using Chrome on the test server:

header

**Comment by esethna** [comment]
Looking good otherwise

**Comment by nevyangelova** [comment]
@esethna there are two options here, I can either get it to work randomly but hover over the text  itself, or create a hidden div, that takes the text and measure its length. Before the problem was that the new lines weren't included in the width and that's why the popover wasn't displayed in some cases. But when I add the fix to include new lines so that we see the popover, it extends the width of the text to include those new lines, and therefore we get the hovering on blank space issue. I think partly this is happening because of the react-bootstrap elements we are using because they have a specific documentation that we have to follow and not much flexibility outside of that. Maybe the devs can advice? @hmhealey @devinbinnie

**Comment by nevyangelova** [comment]
@esethna the size of the hover area is determined by the size of the longest line in the topic popover. If there is a longer line inside, even if its a few rows down, the hover area will still be larger than the first line of text. I pushed a fix to reduce the area when there are shorter lines in the popover. But I can't do it if there are longer ones inside, it will get complex. Maybe the devs can advice? Is this enough, because it seems there will be a lot of effort for less benefit past this point?

**Comment by esethna** [comment]
Let's aim for v5.22 release

**Comment by jgilliam17** [comment]
Thanks @nevyangelova 
There are two issues I am seeing
1. Here I was expecting a new line to be respected when displaying a popover.
See edit screen where I started a new line after "vix generales" 
Screen Shot 2020-03-09 at 11 45 12 AM

and this is how it displays in the popover. Is this as designed? I am not starting a new paragraph but still expect a new line to be started here.
Screen Shot 2020-03-09 at 11 44 54 AM

And this is how it is currently implemented
Screen Shot 2020-03-09 at 11 53 11 AM
 
2.  The word break issue 
Screen Shot 2020-03-09 at 12 17 17 PM

**Comment by nevyangelova** [comment]
@jgilliam17 interesting, I thought I fixed the word-break issue, will resubmit a fix. As for the other part, I think the user needs to enter a new line a second time for an empty line to appear. Generally in web-dev this is the behaviour (first new line takes you to the next row, second one adds an empty line). IMO this is correct, @esethna what do you think?

**Comment by jgilliam17** [comment]
@nevyangelova  - Personally, I would prefer to keep the words whole (no break) and see some empty space as a result. @esethna can you please indicate the correct approach?
With keeping the words whole, we can avoid having unpredictable breaks that may appear odd 
e.g.
this text a
nd some more text

**Comment by esethna** [comment]
word-breaking seem to be working as expected (ie knocking the long word down to the next line)

@jgilliam17 remember that this ticket is only changing the styling of how the header is triggered, so any changes to what the words or line breaks etc do in the header pop-over is out of scope for this ticket UNLESS they are regressions from how it works on master.

**Comment by jgilliam17** [comment]
> word-breaking seem to be working as expected (ie knocking the long word down to the next line)
> 
> @jgilliam17 remember that this ticket is only changing the styling and how the header is triggered, so any changes to what the words or line breaks etc do in the header pop-over is out of scope for this ticket UNLESS they are regressions from how it works on master.

Thanks Eric,
Yes, word break is now working as expected.
New line is not working though, and it is a regression from master.
We test for this [in the spreadsheet here](https://docs.google.com/spreadsheets/d/1-3usQeVbXS798rNt2IkcsKM-KxcckLnsehztSkeSiNw/edit#gid=2020308946&range=43:43)

Nevy explained the technical limitations of displaying the new line. 
If we are ok with changing the expected here and I can update our test cases accordingly. 
Let me know. Thanks.

**Comment by esethna** [comment]
Ah, sorry, understood on the issue you're referring to. Yes, I think we should update the expected in this case

Old behaviour:
image

New Behaviour: Same as above (in the channel header), but no pop-up appears if it fits on a single line
image

**Comment by jgilliam17** [comment]
😞 One more thing, I missed a related [test case](https://docs.google.com/spreadsheets/d/1-3usQeVbXS798rNt2IkcsKM-KxcckLnsehztSkeSiNw/edit#gid=2077175816&range=44:44) that is failing, when I commented earlier 
-  only first line of the list is showing in a popover,
paste the following list to edit channel header modal

- One
- https://google.com
- Three

**Comment by esethna** [comment]
> 😞 One more thing, I missed a related [test case](https://docs.google.com/spreadsheets/d/1-3usQeVbXS798rNt2IkcsKM-KxcckLnsehztSkeSiNw/edit#gid=2077175816&range=44:44) that is failing, when I commented earlier
> 
> * only first line of the list is showing ~in a popover~,
>   paste the following list to edit channel header modal
> * One
> * https://google.com
> * Three

@jgilliam17 this is not a regression in this PR I don't think? Can you file a separate ticket? See daily:

image

**Comment by jgilliam17** [comment]
@esethna Actually, I don't see it on daily or release (recorded on desktop app, but looks the same on the web)
header list

**Comment by esethna** [comment]
@jgilliam17 it depends if you put blank lines between the bullet points

```
- test
- testa
- testb
```
vs

```
- test

- testa

- testb
```

**Comment by jgilliam17** [comment]
Ok, to summarize
1. List will display in the popover **only** if user inserts blank lines between the bullet points (test case will need to be updated with the new expected)
2. First bullet point is out of line with the text (this is not a regression and will be filled separately)

**Pull request merged**
