### PR TITLE
Apps - Allow call response "navigate" on apps modal form submit

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR makes it so Apps modal form submit response can be type `navigate`. Before this PR, the client successfully navigates, but the modal also shows an error.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-48816

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Comment by mickmister** [comment]
Note that this is already working correctly on mobile

**Review by larkox — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann I've tested this manually and it's working properly. There's very low risk here, thoughts on merging at its current review state?

**Pull request merged**
