### PR TITLE
Updated error page to use site name instead of hardcoded 'Mattermost'

### PR DESCRIPTION
**Pull request by Alexgoodman7**
#### Summary
Updated the error page `/error&type=page_not_found` to use the defined Site Name rather than the hardcoded "Mattermost" string.

I fixed the style error in https://github.com/mattermost/mattermost-webapp/pull/667 with this PR.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @Alexgoodman7 how is this error page triggered?

And to clarify, is the Site Name in the config (System console custom branding section)?

image

**Comment by Alexgoodman7** [comment]
@esethna the error page occurs when you tried to reach a url slug that did not exist - like if i went to `/channelss/town-square` instead of `/channels/town-square.

And yes, it utilizes the site name from the config, I have tested that it works in a production environment.

**Comment by esethna** [comment]
@Alexgoodman7 in the case you offered above I just got redirected to Town Square if I was logged in, and redirected to the server login page if I was logged out. Can you please try on the test server above ^ and let me know how I can reproduce the error page?

**Comment by Alexgoodman7** [comment]
@esethna It happens in my environment because I am handling log-in's in a custom way.  If you go directly to http://i-02b6f4b6ebaa4c340.spinmint.com/error?type=page_not_found you can see the error. As in how to replicate it, I'm still attempting that.

If that page exists, clearly it holds some function, unless it has been deprecated.

**Comment by Alexgoodman7** [comment]
@esethna if you go to http://i-02b6f4b6ebaa4c340.spinmint.com/error?type=[anything] for that matter, you get that error page

**Comment by Alexgoodman7** [comment]
@hmhealey done!

**Comment by hmhealey** [comment]
Awesome, thanks!

**Pull request merged**
