### PR TITLE
[MM-29850] Migrate string-refs to functional ones: this.refs.errorMessage

### PR DESCRIPTION
**Pull request by lestgabo**
#### Summary
Update string ref to functional ref

#### Ticket Link
github issue -> fixes https://github.com/mattermost/mattermost-server/issues/16033
jira -> https://mattermost.atlassian.net/browse/MM-29850

#### Related Pull Requests
n/a

#### Screenshots
n/a

### CODE REVIEW

**Comment by lestgabo** [comment]
first push failed because snapshot expected `target={null}` but the previous version of the ref didnt have to trigger snapshot looking for `target`. This was because functional ref updates happen before mount. source: https://reactjs.org/docs/refs-and-the-dom.html

**Comment by jfrerich** [comment]
Thanks for your contribution, @lestgabo! 

@sudheerDev, @sbishel - gentle reminder for review

**Review by sudheerDev — APPROVED** [review]
LGTM, Thank you @lestgabo Sorry about the delay

**Review by sbishel — APPROVED** [review]

**Comment by srkgupta** [comment]
Hello @sudheerDev or @sbishel 
I am not sure what exactly needs to be tested here. Can you please update the QA test steps for this ticket?

**Comment by sudheerDev** [comment]
@srkgupta It requires a smoke test around the page `system console > user amangement > users > click on a user`

**Review by srkgupta — APPROVED** [review]
Thanks @sudheerDev for the clarification. 

Tested the User section on System Console > Users > User page and there were no issues observed in that section. Approving the PR. Thanks @lestgabo for your contribution.

**Pull request merged**
