### PR TITLE
[MM-40216] Fix Team Statistics Labels and Graph Not Rendering

### PR DESCRIPTION
**Pull request by mylonsuren**
#### Summary

Fixes Total Posts and Active Users With Posts graphs not rendering in Team Statistics.

#### Ticket Link

Fixes [MM-40217](https://mattermost.atlassian.net/browse/MM-40217)

#### Screenshots

| Before | After |
|---|---|
| image | image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Comment by mylonsuren** [comment]
> Thanks @mylonsuren LGTM
> 
> image
> 
> @mkraft I am able to see graph **only** for the older than today's posts. Is that expected ?

@furqanmlk This is existing behaviour for graphs in both Team Statistics and Site Statistics. We can look into updating the graphs to include the present day in another ticket/PR (created a ticket here: [MM-41903](https://mattermost.atlassian.net/browse/MM-41903)) as it's out of the scope for this specific issue.

**Review by furqanmlk — APPROVED** [review]
Working as expected

**Comment by furqanmlk** [comment]
@mkraft and @BenCookie95 sorry my mistake I re requested your review. Please ignore.
We are merging this PR

**Review by mkraft — APPROVED** [review]

**Pull request merged**
