### PR TITLE
MM-46041: only set team unread class in channels

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Avoid spuriously marking Playbooks (and the whole desktop app) as unread:
CleanShot 2022-07-27 at 16 19 40@2x

While we were correctly suppressing the mention and unread badge on the team button, we were still setting the class used by desktop to "detect" unreads.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-46041

```release-note
NONE
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]
Thanks @lieut-data for adding a test as well. LGTM!

**Comment by nevyangelova** [comment]
Nit: just need to fix the type import for TeamButton

**Review by Phrynobatrachus — APPROVED** [review]

**Comment by lieut-data** [comment]
Thank you, @Phrynobatrachus!

**Pull request merged**
