### PR TITLE
changing license renewal link to point to new renewal webpage

### PR DESCRIPTION
**Pull request by esadur**
#### Summary

Changing the license renewal link to point to the new renewal webpage. It currently points to an old wufoo form.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-26486

#### Related Pull Requests

- Has server changes (https://github.com/mattermost/mattermost-server/pull/14907)

#### Screenshots

N/A

### CODE REVIEW

**Comment by jwilander** [comment]
Similarly to the email in the other PR this link is appended with `?id=<license-id>&user_count=<user-count>`. Shouldn't cause issues but just to confirm you're aware

**Comment by esadur** [comment]
Ah it looks like a test failed because the link no longer matches the snapshot's link (https://github.com/mattermost/mattermost-webapp/blob/master/components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.jsx.snap). Is there a best practice here? I can go change the snapshot, just don't want to violate any testing norms.

**Comment by jwilander** [comment]
Snapshots shouldn't be manually edited. I'll update it for you

**Comment by jwilander** [comment]
@esadur sorry about the delay, had the update and forgot to push

**Pull request merged**
