### PR TITLE
Cypress/E2E: Fix E2E from recent Cloud test run

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Some notable changes included in this PR:
- added visibility check and message validation to `cy.postMessage` and `cy.postMessageReplyInRHS`. It primarily aimed to fix cases where a message is not being posted or a message is being cut-off especially the last character.
- used `cy.uiPostMessageQuickly` in cases where autocomplete is not to be verified
- moved `MM-T1762` and `MM-T1762` to non-cloud tests

#### Ticket Link
none, failing on Cloud test run

#### Some screenshots
Screen Shot 2021-04-20 at 6 30 21 PM
Screen Shot 2021-04-20 at 6 33 45 PM
Screen Shot 2021-04-20 at 7 03 46 PM
Screen Shot 2021-04-20 at 7 10 37 PM
Screen Shot 2021-04-20 at 7 17 27 PM
Screen Shot 2021-04-20 at 7 33 24 PM

### CODE REVIEW

**Review by josephbaylon — COMMENTED** [review]
@saturninoabril Most tests passed locally except for a `/msg` slash command test that consistently fails for me. I also checked the cypress runs and that test seems to pass there. Please check.

Screen Shot 2021-04-20 at 8 31 42 AM

**Comment by saturninoabril** [comment]
@josephbaylon Thanks for testing! I've added a couple of checks. Please take a look again if it works for you.
Screen Shot 2021-04-20 at 11 53 58 PM

**Review by josephbaylon — APPROVED** [review]
LGTM. Thanks @saturninoabril !! All tests are passing for me locally now.

**Comment by saturninoabril** [comment]
Thanks! fyi, I've pushed a small cleanup on latest commit but nothing change of test flow.

**Review by furqanmlk — APPROVED** [review]
Locally Passed

image

image

image

image

image

image


image

image

image

image

image

**Review by prapti — APPROVED** [review]
Looks good to me. Thanks for the fixes Saturn!

**Pull request merged**
