### PR TITLE
Revert "[MM-8497] Ability to set Do Not Disturb for a specified period of time  (#7037)"

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
This reverts commit 04ebf314dfcb0934ed76d988ce692cfc539e3394.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/15640

#### Related Pull Requests
- Has server changes: https://github.com/mattermost/mattermost-server/pull/17657

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by lieut-data** [comment]
Depending on when `cloud` was cut, this won't cherry-pick cleanly into that branch given the TypeScript typing added. Just a heads up that I may need to do this manually in `cloud`.

**Review by michelengelen — COMMENTED** [review]
Code-wise LGTM ... I will check out the PR tomorrow and run it to check functionality.

**Review by michelengelen — APPROVED** [review]
did a checkout and test-run. LGTM!

**Comment by michelengelen** [comment]
@amyblais should I merge directly, or do you want to have someone from QA looking over it as well?

**Pull request merged**
