### PR TITLE
GH-13175: Add automated Cypress test for "Can change Android App Download Link setting"

### PR DESCRIPTION
**Pull request by themaverikk**
#### Summary

This pull request adds a Cypress automated test for https://github.com/mattermost/mattermost-server/issues/13175 on admin console customizations page

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13175

#### Related Pull Requests
Awaiting on https://github.com/mattermost/mattermost-webapp/pull/4376

### CODE REVIEW

**Comment by devinbinnie** [comment]
Looks good to me, thanks @themaverikk!
@saturninoabril what is this PR waiting on?

**Comment by saturninoabril** [comment]
@devinbinnie This one - https://github.com/mattermost/mattermost-webapp/pull/4376

**Comment by saturninoabril** [comment]
@themaverikk Please update and fix merge conflicts, then ready to merge, thanks!

**Comment by themaverikk** [comment]
@saturninoabril I've fixed the merge conflicts. Please merge the PR.

**Pull request merged**
