### PR TITLE
MM-21726 Set theme defaults before applying

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Fixes the slack theme importer by making sure we set all the default theme properties before applying the theme.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21726

### CODE REVIEW

**Comment by jwilander** [comment]
What if we start applying themes from other places in the code? This function assumes that all the theme properties are set so it should confirm that by setting any defaults for undefined properties IMO

**Comment by hmhealey** [comment]
I don't really think we'll be applying themes from other places very often, especially since we want to get rid of this function for the most part, although I guess I could see it being more useful once the custom system theme stuff that Devin and I were working on gets done.

The big thing I'm concerned with is that it modifies the theme that's passed into `applyTheme`. I think there's a good chance that that will cause issues in the future since we usually pass constants or objects from redux into there, and modifying those would violate the fact that we treat them as immutable. Maybe could you make a copy of the theme before passing it into `setThemeDefaults`?

**Comment by jwilander** [comment]
I can make the change to copy the theme before it gets passed to default function 👍

**Comment by amyblais** [comment]
@jwilander What is the status on this PR?
Do we know if this was a regression in v5.18?

**Comment by jwilander** [comment]
I still need to make the change. I'll do that today. I didn't check if it was a regression but I don't think it is.

**Pull request merged**
