### PR TITLE
Upgrading german to official language

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
German translations are back at 100% and no need to keep German in Beta. We have multiple new maintainers for German now
#### Related Pull Requests
None
#### Release Note
```

```
```release-note
Reinstate German as official language. 
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Looks good! Perhaps we should actually include a release note for this since I assume it's something users will want to know about.

**Review by metanerd — CHANGES_REQUESTED** [review]
Thank you for your PR @ctlaltdieliet ! I think CI fails, because the snapshot would be required to be updated. WDYT?

**Review by metanerd — APPROVED** [review]
LGTM! Could you please add the release note @hmhealey mentioned?

**Review by jgilliam17 — APPROVED** [review]
Thanks @ctlaltdieliet 
Tested, looks good to merge.
- Verified "Deutsch" is available as an official language; beta label has been removed in account settings and system console.

**Comment by jasonblais** [comment]
@amyblais Can this be cherry-picked to the v5.38 release, along with the translations PR being submitted today?

**Comment by amyblais** [comment]
> @amyblais Can this be cherry-picked to the v5.38 release, along with the translations PR being submitted today?

I'll ask Elisabeth, she was off today.

**Pull request merged**
