### PR TITLE
MM-49371 : Improve typing of `utils/emoji_map.ts`

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
I noticed while revieweing a community PR, the typing of emoji_map could have been improved. Added correct iterator function for emoji map.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49371

#### Related Pull Requests
n/a

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by kostaspt — APPROVED** [review]

**Review by nevyangelova — APPROVED** [review]
LGTM

**Review by jgilliam17 — APPROVED** [review]
Thanks @M-ZubairAhmed 
Tested, looks good to merge.
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/283029-d0f354d-onprem-ent-webapp-pr-11862-mm-ee-test:d0f354d/mochawesome.html) - no PR related failures.

**Pull request merged**
