### PR TITLE
Fix JS error on cannot read property length of undefined (postListIds)

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Got an error after leaving all teams.  It breaks as all white screen only with console error of:
Screen Shot 2019-07-11 at 11 25 25 PM 

#### Ticket Link
n/a but Cypress test got it [[link to test report](https://build-push.internal.mattermost.com/job/mattermost-ui-testing/job/mattermost-cypress/104/testReport/(root)/TS14633%20Leave%20all%20teams/Teams_Suite_TS14633_Leave_all_teams/)]

### CODE REVIEW

**Comment by sudheerDev** [comment]
@saturninoabril That component should always mount with postListIds because on mount we use that data to define the scroll position. I am gonna look into the cause of this so we have to keep this PR on hold for now

**Comment by saturninoabril** [comment]
@sudheerDev Sure, maybe also look if we can make `postListIds: PropTypes.array,` as required.

**Comment by sudheerDev** [comment]
> @sudheerDev Sure, maybe also look if we can make `postListIds: PropTypes.array,` as required.

Make sense i will do that too.

**Comment by sudheerDev** [comment]
@saturninoabril PR here https://github.com/mattermost/mattermost-webapp/pull/3106

**Pull request closed without merging**
