### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [mattermost-languages-shipped/mattermost-webapp](https://translate.mattermost.com/projects/mattermost/mattermost-webapp_master/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
@amyblais this needs to be cherry picked?

**Comment by amyblais** [comment]
@cpanato This and the server PR can be cherry-picked to ``cloud``.

**Comment by amyblais** [comment]
@cpanato Now that the v6.4 release branch is cut, this and the server PR can also be cherry-picked to ``release-6.4``.

**Pull request merged**
