### PR TITLE
Remove incorrect string text

### PR DESCRIPTION
**Pull request by cwarnermm**
#### Release Note

```release-note
Removed incorrect in-product string text from the **Send full message contents** email notification option description displayed via **System Console > Site Configuration > Notifications**. 
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]

**Comment by cwarnermm** [comment]
@saturninoabril - This in-product text string update doesn't appear to have impact to test cases. In this case, should QA review this string update?

**Review by saturninoabril — APPROVED** [review]
Thanks Carrie!

**Comment by saturninoabril** [comment]
@cwarnermm I've hit the merge button fast. Would you mind submitting another PR to update the text in the component itself - https://github.com/mattermost/mattermost-webapp/blob/master/components/admin_console/admin_definition.jsx#L2228? Thanks!

**Comment by cwarnermm** [comment]
@saturninoabril - The outstanding updates are being applied via https://github.com/mattermost/mattermost-webapp/pull/9726. Thanks!

**Pull request merged**
