### PR TITLE
MM-45113 - fix product limits banner in subscription page

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR hides the product limits banner and shows the contact sales card when the trial started in the subscription page.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45113

#### Related Pull Requests
n/a

#### Screenshots
Before:
Captura de pantalla 2022-06-15 a las 14 47 06

After:
Captura de pantalla 2022-06-15 a las 15 11 45

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by pvev** [comment]
@neallred thinking about this one better, I am not sure if the limits condition and values (making the call to `hasSomeLimits(cloudLimits)` truthy again) will somehow change during the trial period, producing the necessity to show the limits banner again.

**Comment by neallred** [comment]
During the trial, there should be no limits ever because its a trial of enterprise. If we are seeing the condition as true, then it is most likely a bug that needs fixing. So the changes to hide the limits card look good to me. I think the change in index.tsx is redundant with the change in limits.tsx. I'd opt to keep the one in index.tsx because it prevents limits.tsx from rendering in the first place, and also makes the contact sales card render. The limits.tsx component isn't rendered anywhere else, so I don't think that check in limits.tsx is needed.

**Review by neallred — APPROVED** [review]

**Comment by pvev** [comment]
> During the trial, there should be no limits ever because its a trial of enterprise. If we are seeing the condition as true, then it is most likely a bug that needs fixing. So the changes to hide the limits card look good to me. I think the change in index.tsx is redundant with the change in limits.tsx. I'd opt to keep the one in index.tsx because it prevents limits.tsx from rendering in the first place, and also makes the contact sales card render. The limits.tsx component isn't rendered anywhere else, so I don't think that check in limits.tsx is needed.

ok, got it. Just out of curiosity, what would happen in a scenario where during the trial the limits for let's say storage or teams/channels creation are exceeded and the account doesn't upgrade and gets back to freemium?

**Review by julmondragon — APPROVED** [review]

**Comment by neallred** [comment]
> what would happen ... where during the trial the limits ... exceeded and the account doesn't upgrade and gets back to freemium?

During trial, nothing happens. After trial, they see the limits card in the admin console subscription page and the LHS.

For v1, they are still able to retrieve posts and files in excess of the limit, but for v2 we will be enforcing the limit of making those posts and files inaccessible. Some of that is already work in progress (posts backend work here https://github.com/mattermost/mattermost-server/tree/MM-44488_enforce-posts)

Teams will already be archived. I believe boards already enforces only seeing the latest 500 cards.

Integrations, additional integrations can't be enabled, and there's some UI to the effect that they have to disable integrations to be able to enable any additional integrations. As far as I know there's not yet anything to forcefully disable integrations in excess of the limit.

**Review by stevemudie — APPROVED** [review]
Looks good!

**Pull request merged**
