### PR TITLE
 PLT-5813 adding SAML sync settings to System Console

### PR DESCRIPTION
**Pull request by coreyhulen**
This needs https://github.com/mattermost/mattermost-server/pull/7668 from the server first.

### CODE REVIEW

**Comment by jasonblais** [comment]
@coreyhulen Any thoughts on why I'm getting errors on the Spinmint? I've tried a few different configuration for LDAP login and/or sync, each time giving me the same error. I tried increasing the timeout to 600 seconds but that didn't help.

```
[2017/10/31 19:00:32 UTC] [EROR] /api/v4/ldap/test:connect code=500 rid=7yeyqardmtrkdn78nd3cyesqgc uid=o3h3uuomibromd9g1dod864qzw ip=173.35.115.69 Unable to connect to AD/LDAP server [details: LDAP Result Code 200 "": dial tcp 10.10.0.64:389: i/o timeout]
[2017/10/31 19:00:32 UTC] [EROR] /api/v4/logs:client code=0 rid=f89uhc8fmfgp3rixo6j583q3cy uid=o3h3uuomibromd9g1dod864qzw ip=173.35.115.69 {"message":"Unable to connect to AD/LDAP server","server_error_id":"ent.ldap.do_login.unable_to_connect.app_error","status_code":500,"url":"http://i-0cf24f3295360b8e9.spinmint.com/api/v4/ldap/test"} [details: ]
```

I've used config settings from both bladekick and pre-release where the LDAP sync seems to work without issues.

----

Also wanted to confirm that if a server upgrades to v4.4 and had LDAP enabled, LDAP sync will be enabled by default, otherwise LDAP sync is disabled?

**Comment by coreyhulen** [comment]
@jasonblais you cannot reach our LDAP server from a spinmint.  They are on different AWS accounts.  I think it would be best to test this with jumpcloud LDAP.

**Comment by jasonblais** [comment]
@coreyhulen Okay, I'll try that instead

**Comment by jasonblais** [comment]
Functionally it works. Some minor text tweaks might be made, but I can do those either in this PR or separately.

1) Wondering if the SAML sync setting is necessary? I remember you mentioned there was a technical difficulty with having just a single setting, was that why we have both LDAP and SAML sync settings, instead of just the LDAP sync one?

2) Does the LDAP sync setting do anything for LDAP log in? Seems the synchronization works if LDAP login is enabled, regardless of whether LDAP sync is enabled or not.

**Comment by jasonblais** [comment]
@coreryhulen Functionally it works. Some minor text tweaks might be made, but I can do those either in this PR or separately.

1) Wondering if the SAML sync setting is necessary? I remember you mentioned there was a technical difficulty with having just a single setting, was that why we have both LDAP and SAML sync settings, instead of just the LDAP sync one?

2) Does the LDAP sync setting do anything for LDAP log in? Seems the synchronization works if LDAP login is enabled, regardless of whether LDAP sync is enabled or not.

**Comment by coreyhulen** [comment]
1. You can technically have SAML and LDAP setup to 2 different auth systems.  If you're SAML instance doesn't point to the same LDAP (or have the same users) they will all get disabled.  So you must explicitly tell use to sync SAML users.

2.  Login is independent.  This is because you want to enable sync with LDAP but only allow sign-in with SAML.  As a side benefit: some users want to disable LDAP sync so we would recommend them setting the sync time to some very large number, now you do not have too.

3. This might be a bug.

**Comment by jasonblais** [comment]
Thanks @coreyhulen, 1 & 2 sound good.

Combining my findings in 2 & 3, it then appears that 
 - if LDAP login is enabled, sync is always working regardless of the LDAP sync setting on AD/LDAP page
 - if SAML login is enabled, LDAP sync is enabled on AD/LDAP page, but "Enable synchronizing SAML accounts with AD/LDAP" is disabled, LDAP sync still applies to the SAML accounts.

^So appears that might be a bug. Happy to test further / give more info as needed.

**Comment by jasonblais** [comment]
@coreyhulen Did you have a chance to investigate the potential bug yet?

**Comment by coreyhulen** [comment]
The bug is on the backend, nothing todo with this PR.  @jasonblais can you file a jira tix and we cn merge this PR.

**Comment by coreyhulen** [comment]
PR for the bug fix is at https://github.com/mattermost/mattermost-server/pull/7763

**Comment by jasonblais** [comment]
@coreyhulen Okay great. I just tweaked help text a little. I'll test it to make sure it's rendered properly and we can merge this PR after

**Comment by jasonblais** [comment]
Sorry for the delay, good to merge @coreyhulen

**Pull request merged**
