### PR TITLE
[MM-41671] Support Email Position+Validation

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
This PR moves the Support  Email field and adds more validation around emails.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41671

#### Related Pull Requests
- Has server changes https://github.com/mattermost/mattermost-server/pull/19590

#### Screenshots
N/A

#### Release Note
```release-note
Moved the support email field from "Customization" to "Notifications" in the admin console
```

### CODE REVIEW

**Comment by pablovelezvidal** [comment]
From the code review perspective, it looks good to me. However, by checking the JIRA ticket and the conversations around it, I am not sure I completely understand the requirement so I can not tell if the solution fulfills the acceptance criteria. That's why I requested @dontoisme review. Also, should UX review this solution aswell?

**Review by pablovelezvidal — APPROVED** [review]
LGTM! thanks @JulienTant !

**Review by stevemudie — APPROVED** [review]
Looks good @JulienTant!

The support email field is now nested in System Console ➜ Site Configuration ➜ Notifications  as expected.

**Comment by JulienTant** [comment]
> @JulienTant can you please confirm your changes, also, it is always helpful to set in the PR description either a video or images of the before and after

👌🏻 Yes this is it (Support email field moved in this page + errors when some fields are empty).
I'll make sure to add before/after in my next PRs thank you!

**Pull request merged**
