### PR TITLE
MM-12027 Adding paging for elasticsearch results.

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by jwilander** [comment]
@wiersgallak I don't think this can be tested until the redux PR goes in but added you as a reviewer

**Comment by crspeller** [comment]
@jasonblais As noted above, this needed to wait for the redux PR. I will update this PR with that.

@amyblais Yes.

**Comment by jasonblais** [comment]
Sorry about that. Didn't realize we'd have to update this PR in addition to merging the redux PR.

**Comment by jasonblais** [comment]
@crspeller I'm not seeing a search bar for the spinmint quite yet. Though I was having trouble getting the spinmint up so maybe the Redux changes didn't get pulled properly?

image

**Comment by crspeller** [comment]
@jasonblais Make sure you refresh? It seems to be working for me. If it still doesn't work post console error and browser.

**Comment by jasonblais** [comment]
Yeah works after a refresh, and works after clearing cache so must have been a caching issue somehow.

**Comment by jasonblais** [comment]
@crspeller I've noticed a few issues with database search. Mac/Chrome. No console errors reported throughout.

1 - After you log out, then log back in, search bar is missing. It re-appears on refresh, or after switching a channel.

image

2 - When I scroll to the bottom of the search results, the results are duplicated. Here are repro steps
-  On the spinmint, search for "hello*"
- On the search results, scroll to the bottom. You will see "hello1" there, which is the first "hello*" message I posted at 17:45. The latest message I posted was "hello60" at 17:46.
image

- Wait for a second.
- Notice that more search results are returned. These are in fact the search results already displayed ("hello 60", "hello 59", etc, which are the most recent posts I made).
image


3. There is no paging of search results (I get all 60 results for "hello*")

--

Let me know if you can't reproduce any of the above and I will ask someone else to take a look.

**Comment by crspeller** [comment]
1. Can't reproduce this. On FF or Chrome.
2. Fix for this is here: https://github.com/mattermost/mattermost-server/pull/9471
3. That's expected, paging only works for elasticsearch.

**Comment by jasonblais** [comment]
Thanks Chris

1. Katie will be helping with further testing. Perhaps this is somehow an issue on my end.
2. 👍 
3. Cool, makes sense based on the PR title. Is paging for database search coming with a separate ticket?

**Comment by wiersgallak** [comment]
I was unable to reproduce #1 either (Chrome or Safari).  Keeping an eye out for the merging of mattermost/mattermost-server#9471 and eager to test on a Elasticsearch spinmint when you get have it ready @crspeller

**Comment by wiersgallak** [comment]
@crspeller This works well and looks like this is fairly close to an infinite scroll type of UI!  The one thing I noticed is that when you initially search a term (red* in my test) the entire result is highlighted ("red123"), when the page loads the next set of results when I scroll through only partial results are highlighted ("red" is highlighted ,"123" is not highlighted).  I am reproducing on Mac >Safari, Chrome, and on my Safari on my mobile as well. ( [video](https://drive.google.com/file/d/1nUIuW9K_3FZnOpQKFIVKk8AR71gHCBtz/view?usp=sharing) )

**Comment by jasonblais** [comment]
Did some further testing on elasticsearch (Mac/Chrome)

1 - Issue Katie noticed above
2 - Flagged posts search doesn't return results (infinite loading) with attached JS error

image

Once you search for flagged posts, search breaks because you can't search for another term, unless you refresh the page.

Note that I flagged 40+ messages.

3 - Same error for pinned posts search

image

4 - When searching `in:minus-6` on the spinmint, no results returned, though there are messages in the channel. Reproduces with other `in:` modifiers.

image

image

5 - In terms of UX, propose we load the next set of results as the user scrolls near the bottom, similar to the custom emoji in emoji picker. I'm aware this needs a more specific requirement on what "near the bottom" means, which PM or UX can take a look at part of this PR or separately.

6 - Second note on UX: We typically show a loading indicator while more results are loaded. On a 3G network connection, it takes about 3 seconds to load more results, so it appears there are no more results. May not be necessary if 5 is implemented.

**Comment by crspeller** [comment]
@jasonblais @wiersgallak None of the problems above (except the UX notes 5, 6) are not issues with this PR, patch for all of the above is here: https://github.com/mattermost/mattermost-redux/pull/657

**Pull request merged**
