### PR TITLE
[MM-20599] Removed state variable from action creator functions

### PR DESCRIPTION
**Pull request by diode**
#### Summary
Avoid passing global state into actions

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22995

### CODE REVIEW

**Comment by jasonblais** [comment]
@marianunez and @devinbinnie kind remind to help with reviews :)

**Comment by marianunez** [comment]
Removing my review request why still WIP. Feel free to request review when ready 👍

**Comment by jfrerich** [comment]
Hi @diode, can you clarify if this PR is still a work in progress, or ready for review?

**Comment by lindy65** [comment]
Hi @diode - I'm helping review stale PRs and am closing this one as we haven't heard from you in over 7 months. I've re-added the "Up for grabs" label on https://github.com/mattermost/mattermost-server/issues/14222

//cc @devinbinnie @marianunez

**Pull request closed without merging**
