### PR TITLE
GH-1878: Display Bot Badge in Auto Complete For Focalboard

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Bot Badge being used in Focalboard. Bot Badge is required to be exported here.

#### Ticket Link

Required for https://github.com/mattermost/focalboard/pull/1906

#### Related Pull Requests

- Has server changes (please link here)
- Has mobile changes (please link here)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by jespino** [comment]
@hmhealey can you confirm if that is ok? We need that, but maybe we just want to replicate the styles for this or copy over the component.

**Review by jespino — APPROVED** [review]
LGTM, but I would wait for confirmation from @hmhealey about if we want to export it, or just copy it into focalboard.

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
This one should be fine. Most of the widgets are pretty simple, so I'm not as worried about breaking them randomly

**Pull request merged**
