### PR TITLE
Aesthetic design upgrade

### PR DESCRIPTION
**Pull request by irrational-pai**
#### Summary

These design changes were made as a part of visual improvements to [Relay](http://relay-chat.com). Many of these changes address the projects as listed in the [Design Challenge](https://github.com/mattermost/mattermost-server/issues/8350).

I've written a blog post detailing the _why_s and _how_s of these changes:
https://medium.com/@irrational_pai/mattermost-relay-e19dfb68c708

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/8350

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has server changes (please link)
- [ ] Has redux changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, posting, etc.)

### CODE REVIEW

**Comment by irrational-pai** [comment]
Note that `make check-style` fails on the jsx icon files. I've left them as is for now, since it involves a larger discussion around overhauling icons.

**Comment by jasonblais** [comment]
@asaadmahmood Wondering if you'd have any initial thoughts or feedback?

**Comment by irrational-pai** [comment]
I wanted to elaborate a bit on the design decisions that were taken for this change. I would split the design changes into the following chunks:

- Font change
- Icon change
- Overall cleanup

## Font change

The font change focuses on getting the typography and reading experience right. We've worked on tightening up the line-heights, spacing between posts, bumped up the default font-size, and picked a font that has various weights to help distinguish it better when used in markdown.

---

## Icon change

The icon change follow suit. The current set of Mattermost icons aren't of consistent weights and our aim was to get the icons that are well-designed, open source, and have a more consistent style. We've also  fixed the CSS to be modular so future icon changes can be as simple as a swap.

---

## Overall cleanup

This, along with the font and icon change, is what elevates the design changes we've made. We've addressed (some of) the problems mentioned in the design challenge. We've made better use of the white space to improve readability (tested this internally at nilenso), we've cleaned up the sidebar, the team sidebar, and a bunch of other changes to make sure the entire experience of using Mattermost/Relay is as enjoyable as possible.

**Comment by koxen** [comment]
@irrational-pai just a quick one comment, haven't done a full review yet.
there's some css issue that cuts the bottom part of page at the textbox level and creates a second 'scroolbar' when it shouldn't have
xshell_2018-03-23_20-07-02

**Comment by hwcltjn** [comment]
@irrational-pai nice contribution and design!
I really like the square avatars and layout adjustments. Is there anyway for the font to be sharper/crisper?

I tried it out by re-building the web-app using [relay-ops](https://gitlab.com/nilenso/relay-ops) - I had to make a few modifications to the `rebrand-webapp` script to get it working correctly and applied some patches manually.

I realise it was intended for 4.7.3 but I found two bugs when used on 4.8:
- In the Mattermost Mac client the icons are over-sized. This does not happen in Chrome or FF for example.
- Everything except "Reporting" in the System Console disappears?

mm_relay

**Comment by irrational-pai** [comment]
@hwcltjn Glad you liked the changes. The oversized icons in the Mattermost client is something other members of our team have also pointed out. We have some pending bugs before we get to this one but I'll keep you posted on the progress :)

---

Re: System console issue

I've made a note of this. The issue you're facing is on MM 4.8 or 4.7.3 or both?

---

Re: Font being crisper

Is there an instance where you've noticed the font rendering not being crisp or sharp?

**Comment by hwcltjn** [comment]
@irrational-pai thanks!

The system console issue is happening in 4.8 - but it's also happening in your demo link over at https://pr-aesthetic-design-upgrade.relay-chat.com/admin_console/system_analytics which is running 4.7.1 .

Regarding the fonts - I think its a client issue not your theme. 
The fonts are generally better in Chrome as opposed to client.

**Comment by esethna** [comment]
Appreciate these changes! We've pulled out some pieces in another PR here: https://github.com/mattermost/mattermost-webapp/pull/1220

Closing this one.

**Pull request closed without merging**
