### PR TITLE
MM-18818: Don't display default Support Email

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Support gets emails from users that should be going to the users own support. Currently if the Support Email is empty, we don't display it. This PR expands that to if the Support Email is the default (feedback@mattermost.com), it won't display it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18818

#### Screenshots
Screen Shot 2020-02-03 at 10 20 09 AM
Screen Shot 2020-02-03 at 10 19 10 AM

### CODE REVIEW

**Comment by srkgupta** [comment]
@sbishel can you please fix the failing unit tests. 
Screenshot 2020-02-24 at 4 48 00 PM

**Comment by sbishel** [comment]
Closed. After further review, this fix is not correct. This will remove the help email from community. Need a different fix.

**Pull request closed without merging**
