### PR TITLE
WIP: [PLT-7685] Improving how UI elements in the message view indicate focus for 508 Compliance

### PR DESCRIPTION
**Pull request by santos22**
#### Summary
This pull request includes some minor changes to make buttons and other elements in view gain focus for users tabbing through the webapp via keyboard

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/8034

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Has UI changes

Adding the items for this PR, just to make more easy to follow:

Proposed changes for the expected tab order (follows Slack):

   1 - Assume message box is in focus
   - [x] File upload paperclip icon (current: not tabbed + no visual cue when in focus)
   - [ ] Emoji picker icon (current: not tabbed + no visual cue when in focus)
   - [ ] "Preview" below message box (current: not tabbed + not underlined when in focus)
   - [x] "Help" below message box (current: gets tabbed + visual cue)
   - [x] Team icons and + sign in the team sidebar (current: gets tabbed + visual cue)
   - [ ] Profile status indicator in channel sidebar (current: not tabbed)
   - [x] Main menu in channel sidebar (current: gets tabbed + visual cue)
   - [x] Channel sidebar from top to bottom, including "+" signs, channel names, "x" button on DMs, "More.." and channel switcher button. (current: get tabbed but no visual cue)
   - [ ] Channel header from left to right, including star, "v" next to channel name, channel description, channel member list, pin icon, search bar, at-mention icon, flag icon (current: most don't get tabbed nor have a visual cue)
   - [x] "Set a header" in channel intro, if shown on the UI (current: gets tabbed + visual cue)
   - [ ] For each message, tabs through profile picture, username, timestamp, flag icon, [...] menu, emoji icon, reply arrow, links in post, emoji reactions (current: only timestamp and links gets tabbed)
   - [ ] Right-hand sidebar, from top to bottom, including expand arrow, close sidebar icon, username, timestamp, [...], emoji, links, and reactions of messages, comment box, file upload icon, emoji picker icon, "Preview" link, "Help" link, "Add Comment" box (current: not tabbed)
   - [x] URL bar if on browser
   - [ ] Back to center pane message box.

### CODE REVIEW

**Comment by jasonblais** [comment]
Applying work in progress label while @cpanato finishes the changes :)

**Comment by jasonblais** [comment]
@cpanato You can touch base with `@asaad` first on pre-release if it's CSS-related, or `@harrison` from the dev side.

**Comment by jasonblais** [comment]
Hey @santos22 - how are things going on this one? :)

**Comment by jasonblais** [comment]
@santos22 No worries! Totally understand. Looks like half of the work is now done based on the PR description, is that correct?

**Comment by santos22** [comment]
@jasonblais yep!

**Comment by jasonblais** [comment]
Thanks again @santos22 - have added a note in the help wanted ticket: https://github.com/mattermost/mattermost-server/issues/8034

Closing this for now

**Pull request closed without merging**
