### PR TITLE
chore/MM-37187 : Update minor or patch version of the packages - Nov 21

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Dependency updates for :

| Dependency | From | To | Upgrade type | Changelog | Notes |
|---|---|---|---|---|---|
|css-vars-ponyfill|2.4.5|2.4.7|Patch|[Changelog](https://github.com/jhildenbiddle/css-vars-ponyfill/blob/master/CHANGELOG.md#247)|Ability to have `.` in variable names, perf improvements|
|html-to-react|1.4.5|1.4.7|Patch|[Diff](https://github.com/aknuds1/html-to-react/compare/v1.4.5...v1.4.7)|Updated underlying htmlparser2 library, handling of boolean attributes such as realOnly, noValidate added, handling of event handlers added|
|localforage|1.9.0|1.10.0|Minor|[Changelog](https://github.com/localForage/localForage/blob/master/CHANGELOG.md#1100)|Fixed bug when db is accessed at the same time from two different tabs|
|xregexp|5.0.2|5.1.0|Minor|[Release](https://github.com/slevithan/xregexp/releases)|Upgrade Unicode, new matchRecursive supports more three options|
|nock|13.1.0|13.2.1|Minor|[Release](https://github.com/nock/nock/releases)|New `update` mode added, other bug fixes|
|yup|0.32.9|0.32.11|Patch|[Changelog](https://github.com/jquense/yup/blob/master/CHANGELOG.md)|Can add custom generic types to object schema|
|luxon|2.0.2|2.1.1|Minor|[Changelog](https://github.com/moment/luxon/blob/master/CHANGELOG.md)|Miliseconds parsing added, other fixes|
|moment-timezone|0.5.33|0.5.34|Patch|[Release](https://github.com/moment/moment-timezone/releases)|Updated DB|
|react-virtualized-auto-sizer|1.0.5|1.0.6|Patch|Commit|Fix related to rAF (request animation frame)|
|styled-components|5.3.0|5.3.3|Patch|[Changelog](https://github.com/styled-components/styled-components/blob/main/CHANGELOG.md)|sourcemaps improved|
|timezones.json|1.5.2|1.5.3|Patch|[Commits](https://github.com/dmfilipenko/timezones.json/commits/master)|Alias Calcutta added, Yukon added to MST|
|@testing-library/jest-dom|12.0.0|12.1.2|Minor|[Release](https://github.com/testing-library/react-testing-library/releases)|jsdocs improved, Types improved|
|@testing-library/jest-dom|5.14.1|5.15.0|Minor|[Commit](https://github.com/testing-library/jest-dom/pull/415)|Minor improvement|
||||||

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37187

#### Related Pull Requests
~Has server changes (please link here)~
~Has mobile changes (please link here)~

#### Screenshots
n/a

#### Release Note

```release-note

```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by jespino — APPROVED** [review]
LGTM

**Review by calebroseland — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
@M-ZubairAhmed Did you make that fancy table of all the dependencies that changed or was that generated automatically somehow? That's really nice to have

**Comment by M-ZubairAhmed** [comment]
Haha @hmhealey i read up the release and commit and condensed the changes for others to easily understand:)

**Comment by jgilliam17** [comment]
Thanks @M-ZubairAhmed E2Es running [here](https://automation-dashboard.vercel.app/cycles/4024915a-4e85-4a83-b6fe-f5c839a33ed9)

**Comment by jgilliam17** [comment]
Thanks @M-ZubairAhmed 
Tested, looks good to merge.
- Verified [E2E report](https://automation-dashboard.vercel.app/cycles/4024915a-4e85-4a83-b6fe-f5c839a33ed9), existing failures also present on the [master run](https://automation-dashboard.vercel.app/cycles/c93b399d-1d24-448b-9e8c-074a053f4fe1).

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
