### PR TITLE
Prevent focus change when RHS is open

### PR DESCRIPTION
**Pull request by shamboozles**
#### Summary

The changes prevent the focus from changing when the thread tab is open, which happens sometimes and makes the cursor jump to the main textarea.

#### Screenshots

|  before  |  after  |
|----|----|
|[mc_not_fixed.webm](https://user-images.githubusercontent.com/108882245/180980264-abf6be83-27a6-46e7-9dc3-5e401239338a.webm)|[mc_fixed.webm](https://user-images.githubusercontent.com/108882245/180980336-bf883ce0-1d04-4d77-9dcc-ba2683ff36c7.webm)|

#### Release Note

```release-note
* Added a condition for the 'focusTextboxIfNecessary' that when the RHS is open and if the focus changes to the body, the main textarea will not be focused 
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Thanks for the PR, @shamboozles! Was there a ticket open for this already? If not, I'm going to file one so that we can properly track this since it seems like a pretty impactful regression.

**Review by hmhealey — APPROVED** [review]
This looks good to me after some testing.

I did find a bug where I can get the centre channel's post textbox to occasionally lose focus if I have the RHS open and spam sending a bunch of messages (with sending them as fast as I could hit the enter key), but since I wasn't able to get it to happen when sending messages at a more reasonable rate (around one message per second), I think that's totally fine

**Comment by AshishDhama** [comment]
@saturninoabril Jelena is PTO so adding you.

**Review by saturninoabril — APPROVED** [review]
Thanks @shamboozles! Tested and passed.

**Pull request merged**
