### PR TITLE
MM-20433 - convert view_pinned_posts to typescript

### PR DESCRIPTION
**Pull request by pablovelezvidal**
### Summary
This converts the view_pinned_posts component in the webapp to TypeScript. 

### Ticket Link
https://mattermost.atlassian.net/browse/MM-20433
Fixes https://github.com/mattermost/mattermost-server/issues/16141

### CODE REVIEW

**Review by sudheerDev — APPROVED** [review]
@pablovelezvidal Thank you!

**Review by nevyangelova — APPROVED** [review]
LGTM!

**Review by josephbaylon — APPROVED** [review]
LGTM. Thanks @pablovelezvidal for your contribution !! Verified unit tests are updated and I also ran pinned post related e2e tests locally and they passed.

**Comment by jfrerich** [comment]
@josephbaylon, it looks like all reviews are done.  Can you merge the PR if nothing remains? Thanks for the PR, @pablovelezvidal!

**Comment by josephbaylon** [comment]
@jfrerich I just realized after merge that this doesn't have a milestone. Can you please add the milestone if necessary?

**Pull request merged**
