### PR TITLE
[MM-38042] Change file preview modal animation to fade in and out

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Change file preview modal animation to fade in and out

#### Ticket Link
Fixes [https://mattermost.atlassian.net/browse/MM-38042](https://mattermost.atlassian.net/browse/MM-38042)

#### Related Pull Requests
NONE

#### Screenshots
Screenshot 2021-08-23 at 12 17 09 PM

#### Release Note
```release-note
* Change file preview modal animation to fade in and out
```

### CODE REVIEW

**Review by esethna — APPROVED** [review]

**Review by ashishbhate — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @AshishDhama 
Tested, looks good to merge.
- Verified file preview modal animation fades in when opening, no longer slides down from the top.

**Comment by esethna** [comment]
@asaadmahmood please help review and merge if it looks good :)

**Review by asaadmahmood — APPROVED** [review]
LGTM.

**Comment by AshishDhama** [comment]
@amyblais ``release-6.0`` doesn’t have [https://github.com/mattermost/mattermost-webapp/pull/8526#issuecomment-900565344](https://github.com/mattermost/mattermost-webapp/pull/8526#issuecomment-900565344) these changes yet, Should I cherry pick to ``cloud``

**Comment by amyblais** [comment]
> @amyblais `release-6.0` doesn’t have [#8526 (comment)](https://github.com/mattermost/mattermost-webapp/pull/8526#issuecomment-900565344) these changes yet, Should I cherry pick to `cloud`

You can cherry-pick to cloud.

**Pull request merged**
