### PR TITLE
chore/MM-37187 : Update all babel related dependencies to v7.16.0 - Nov 21

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Dependency updates for :

| Dependency | From | To | Upgrade type | Notes |
|---|---|---|---|---|
| @babel/cli | 7.14.5 | 7.16.0 | minor | No breaking changes, majorly are fixes and improvements, https://github.com/babel/babel/compare/v7.14.5...v7.16.4 all @babel follows same release cycle |
| @babel/core | 7.14.6 | " | " | " |
| @babel/plugin-proposal-class-properties | 7.14.5 | " | " | " |
| @babel/plugin-proposal-object-rest-spread | 7.14.7 | " | " | " |
| @babel/preset-env | 7.14.7 | " | " | " |
| @babel/preset-react | 7.14.7 | " | " | " |
| @babel/preset-typescript | 7.14.5 | " | " | " |
| babel-loader | 8.2.2 | 8.2.3 | patch | minor patch for using md5 for caching |

#### Ticket Link
Part of https://mattermost.atlassian.net/browse/MM-37187

#### Related Pull Requests

~Has server changes (please link here)~
~Has mobile changes (please link here)~

#### Screenshots
none

#### Release Note

```release-note

```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Review by calebroseland — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thank you @M-ZubairAhmed 
Here's the [E2E report](https://mattermost-cypress-report.s3.amazonaws.com/89892-b56b2a7-ee-ent-webapp-pr-9405-mm-ee-test:b56b2a7/mochawesome.html). Most of the failures are related to invite modal and can be disregarded.
Can you please take a look at these 2 failing tests and make sure they are not related to your changes? Thanks
MM-T2408_2 and MM-T613

**Comment by jgilliam17** [comment]
Thanks @M-ZubairAhmed 
Tested, looks good to merge. 
- [Re-ran the E2Es](https://automation-dashboard.vercel.app/cycles/523d150b-3136-4718-b527-9fe87ec5f3dd) and verified failures manually - no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
