### PR TITLE
MM-9656: Validating uploads of 0 bytes files

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Not allow to upload 0 bytes files (no even try, only show errors about it).

#### Ticket Link
[MM-9656](https://mattermost.atlassian.net/browse/MM-9656)

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit and component tests passed
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-webapp/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@jespino I thought the expected behaviour in the ticket is `Upload the 0KB file to message drafts`

**Comment by jespino** [comment]
Me too, but @lindy65 understood the current implemented behavior (based on what Gmail and others does).

I can implement it in the other way. maybe it needs UX discussion?

**Comment by lindy65** [comment]
I think there are two things the ticket mentions,
1. the expected `Upload the 0KB file to message drafts` and,
2. possible fixes `Attaching 0KB files should be validated to prevent user error`
Not sure whether this is where my confusion arose?

To clarify, should the expected then be:
`Attaching 0KB files should be validated` followed by `Upload the 0KB file to message drafts`?

**Comment by jespino** [comment]
Ok sorry, clearly my fault. I going to rewrite the PR. :)

**Pull request closed without merging**
